### ISSUE TITLE
S3 service endpoint handling where LocationConstraint is "EU"

### ISSUE THREAD

**Issue by jimcroft** [aws/aws-sdk-js#1001]
For reasons unknown there's a difference between S3 buckets created through the console or API and via CloudFormation. When creating an S3 bucket in eu-west-1/Ireland with the console or APIs LocationConstraint is set or defaults to eu-west-1. This is grand and S3 API operations using aws-sdk-js work fine.

When the S3 buckets are created in the same region using CloudFormation LocationConstraint is set to EU. EU and eu-west-1 are both valid values according to http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html and there's no way in CloudFormation to set this property on a bucket.

When the LocationConstraint is set to EU whatever endpoint aws-sdk-js is using sends a 301 back for all operations and bombs out. We have to manually set the endpoint In the S3() constructor to work with these buckets.

**Comment by chrisradek** [comment]
@jimcroft 
Can you share the error message and headers (minus sensitive info) that are returned by the response when you see the 301 error? Do you see this issue using the node.js or browser sdk, and which version?

Also, can you share how you're configuring your S3 client through the JavaScript SDK? Are you configuring it to use the `eu-west-1` region?

**Comment by jimcroft** [comment]
Hi Chris,

This is using node.js aws-sdk@2.3.1 and configured using a AWS.SharedIniFileCredentials profile that includes the correct region. I'm not very familiar with with node.js, I was just helping a colleague debug a code deployment issue, I don't know how to get the full headers, request, response, etc. but have some additional information below.

I created a trivial test script to put a single object in a bucket. When configured like:

```
var credentials = new AWS.SharedIniFileCredentials({profile: 'deployer'});
AWS.config.credentials = credentials;
AWS.config.logger = process.stdout;
var s3 = new AWS.S3();
```
the logs show: 
```
[~/Desktop/s3test]$ node test.js
[AWS s3 301 0.596s 0 retries] putObject({ Bucket: 'REDACTED',
  Key: 'node.test.file',
  Body: 'some content for the test object' })
{ PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
    at Request.extractError (/Users/jim/Desktop/s3test/node_modules/aws-sdk/lib/services/s3.js:350:35)
    at Request.callListeners (/Users/jim/Desktop/s3test/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jim/Desktop/s3test/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jim/Desktop/s3test/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/Users/jim/Desktop/s3test/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jim/Desktop/s3test/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jim/Desktop/s3test/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jim/Desktop/s3test/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jim/Desktop/s3test/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/Users/jim/Desktop/s3test/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.',
  code: 'PermanentRedirect',
  region: null,
  time: 2016-05-24T17:44:43.240Z,
  requestId: 'BF8F5C85B73F4C2B',
  extendedRequestId: 'n2FBw04JX0Xs0U0dqO3iTMelYfYxea1w0TrOTh0+q3Kg6vynE0GBNxhfuaEhug+9AJK6Uejf6WM=',
  cfId: undefined,
  statusCode: 301,
  retryable: false,
  retryDelay: 70.64452964808434 }
```

When configured like:
```
var credentials = new AWS.SharedIniFileCredentials({profile: 'deployer'});
AWS.config.credentials = credentials;
AWS.config.logger = process.stdout;
var ep = new AWS.Endpoint('s3-eu-west-1.amazonaws.com');
var s3 = new AWS.S3({endpoint: ep});
```

all's well:
```
[AWS s3 200 0.328s 0 retries] putObject({ Bucket: 'REDACTED',
  Key: 'node.test.file',
  Body: 'some content for the test object' })
{ ETag: '"eba398d822af73a2b8c91b0d5a62558f"' }
```

The only two differences in the buckets (aside from their names) is that one was created through the AWS console, the other via CloudFormation. Doing a little digging this is all I could come up with as a difference between them:

```
$ aws s3api get-bucket-location --bucket REDACTED_BUCKET_1
{
    "LocationConstraint": "EU"
}
]$ aws s3api get-bucket-location --bucket REDACTED_BUCKET_2
{
    "LocationConstraint": "eu-west-1"
}
$
```

REDACTED_BUCKET_1 being the CloudFormation created bucket which exhibits this 301 redirect behaviour.

**Comment by jimcroft** [comment]
PS. The CloudFormation behaviour of setting LocationConstraint to EU is valid but I raised a support case with AWS and it's being logged as a bug.

**Comment by chrisradek** [comment]
@jimcroft 
If you replace
```javascript
var s3 = new AWS.S3();
```
with
```javascript
var s3 = new AWS.S3({region: 'eu-west-1'});
```
does your code run properly?

**Comment by jimcroft** [comment]
Yes, that works.

**Comment by LiuJoyceC** [comment]
Hi @jimcroft 
The latest release, `v2.3.15`, that came out today should also resolve this issue without you needing to configure the region in the S3 constructor. Let me know if updating to the latest version also resolves the issue for you.

However, note that it is recommended to configure the correct region if the bucket region is known and is different from your default configuration.

**Comment by jimcroft** [comment]
New release fixed this issue. Thanks!

**Comment by LiuJoyceC** [comment]
I'm glad to hear it!
