### ISSUE TITLE
lib util readFileSync does not work in Electron

### ISSUE THREAD

**Issue by michaelwittig** [aws/aws-sdk-js#1006]
The `readFileSync` function in [lib/util.js](https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L100)  does not work in environments like [Electron](http://electron.atom.io/).
In Electron, typeof window := "object" but I have access to node's fs module.
Maybe it would be easier to check if we are in a node.js context?

Btw: This behavior prevents me from using version 2.3.16 lib/credentials/shared_ini_file_credentials.js with Electron :)

**Comment by chrisradek** [comment]
@michaelwittig 
Thanks for reporting the issue! I created a PR to check if we're in the browser instead. As long as you aren't using the browser version of the SDK, `readFileSync` should work with this change.

**Comment by chrisradek** [comment]
I merged in a change that should resolve this. It'll be available via npm in the next release, or you can install it from github.

Thanks for reporting this!

**Comment by michaelwittig** [comment]
@chrisradek thanks!
