### ISSUE TITLE
region param required in ElasticBeanstalk constructor

### ISSUE THREAD

**Issue by lauterry** [aws/aws-sdk-js#1007]
Hello

I set my region in a json file using ```AWS.config.loadFromPath```

However, when using trying to : 

```
var elasticbeanstalk = new AWS.ElasticBeanstalk();
elasticbeanstalk.createApplicationVersion(params, cb);
```

I got the following error message :  

```
Unable to download from S3 location (Bucket: perfectstay.builds  Key: pfs-1.5.24.zip). Reason: Moved Permanently
```

I have to set the region param in the constructor and the problem disappear.

```
var elasticbeanstalk = new AWS.ElasticBeanstalk({
    region: "eu-west-1"
});
```

The question is Why do I have to set it in the constructor while I already set it in my json file using ```AWS.config.loadFromPath``` ?

**Comment by chrisradek** [comment]
@lauterry 
Can you share how your json file is set up (minus credentials if those are set)? Just to verify, are you calling `AWS.config.loadFromPath` prior to instatiating `elasticbeanstalk`?

I just tried a very simple example and was able to set the SDK region.

`config.json`
```json
{
  "region": "us-west-1"
}
```
`example.js`
```javascript
var AWS = require('aws-sdk');

AWS.config.loadFromPath('./config.json');

var ebs = new AWS.ElasticBeanstalk();
console.log(ebs.config.region); // Output: us-west-1
console.log(ebs.config.endpoint); // Output: elasticbeanstalk.us-west-1.amazonaws.com
```

**Comment by lauterry** [comment]
Hi @chrisradek 

My bad,

I have just figured out that my region was incorrect. I have put us-west-1 instead of eu-west-1   -_-

So everything is fine

So sorry for the noise
