### ISSUE TITLE
Uncatchable error in request.js (ECONNREFUSED)

### ISSUE THREAD

**Issue by olalonde** [aws/aws-sdk-js#1010]
Getting the following error when testing locally:

```javascript
/myproject/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: connect ECONNREFUSED 192.168.99.100:4567
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1073:14)
```

I can't figure a way to catch this error as it seems to be thrown within a callback:

https://github.com/aws/aws-sdk-js/blob/master/lib/request.js#L31

It crashes my whole process when I try to create a read stream and the S3 server is unreachable, not ideal... `192.168.99.100:4567` is https://github.com/olalonde/docker-fake-s3 which I use for testing locally. S3 is not likely to become unreachable in production but it's not impossible.

Would it not be possible to emit it or pass it to the callback?

**Comment by chrisradek** [comment]
@olalonde 
Are you attaching an `error` event listener to the returned read stream? I created a quick test script that causes the error you're seeing, and was able to catch the error by listening for it on the read stream. Here's a quick example:

```javascript
var s3Stream = s3.getObject({/*params*/}).createReadStream();
s3Stream.on('error', function(err) {
  console.log(err); // Prints the ECONNREFUSED error
});
s3Stream.pipe(writeStream);
```

**Comment by satypro** [comment]
Hi,
I also have the same issue.
Following is my code and invoking this from Express endpoint.

AWSS3.prototype.getStream = function(param,cb){
 
   if (!_.has(param, 'Key'))
   {
       cb({error:'Key is missing, please provide...'},null);
   }

   var params = {
                Bucket: _.has(param, 'Bucket')?param.Bucket:this._bucket,
                Key: _.has(param, 'Key')?param.Key:''
   };
  
    s3.getObject(params, function(err, data) {
     if (err) 
     cb(err,null); 
     cb(null,{data:data});
   });   
};


it sets the callback successfully  and I receive the err  also in the callback function.

router.get('/downloadStream', function(req, res, next){
	
	  var params = {
                Bucket: req.query.bucket , /* required */
                Key: req.query.key  /* required */
     };
	  
    store.getStream(params, function(err, result){
        if(!err)
        {
            res.set('Content-Type', result.data.ContenType);
            res.send(result.data.Body);
        }
        else
        {
          res.status(500).send({error:err});
        }
    });
});

But after this error is thrown from the place mentioned above.
And application gets shutdown.

When I change the throw err  to done(err). It works fine.

@olalonde  is it always require to attach error event ?
                   And what if I just pass the error in done callback in request.js

**Comment by olalonde** [comment]
AFAIK, error events must be listened to or they will crash the process. But I think in my code, I do listen to every possible event so I'm really not sure what that error is coming from.

**Comment by chrisradek** [comment]
@olalonde 
Can you share a minimal code sample that reproduces the error you're seeing? Does it happen using the sample code I provided above?

**Comment by olalonde** [comment]
@chrisradek I'm fairly sure I have an error event handler attached and still getting occasional crashes but it's pretty hard to reproduce reliably. Next time it happens I will try to see if I can pinpoint the problem.

**Comment by olalonde** [comment]
I realised I wasn't properly attaching an error handler to the writable stream.
