### ISSUE TITLE
"; charset=UTF-8" appended for multipart upload

### ISSUE THREAD

**Issue by apires** [aws/aws-sdk-js#1011]
Hi all,

Issue #244 introduced a normalization for content-type but it seems like it's being applied too eagerly. Please excuse my lack of full understanding in this process.

We're using the ManagedUpload functionality in the browser SDK with the following code.

``` javascript
    let params = {
      Bucket: bucket,
      Key: name,
      ContentType: "video/mp4",
      Body: file,
      Metadata: { blob: JSON.stringify(uploadMeta) }
    };

    let upload = new AWS.S3.ManagedUpload({
      params: params,
      service: new AWS.S3({credentials: new UploadCredentials(), endpoint: 's3-accelerate.amazonaws.com'})
    });

    upload.destination = bucket+'/'+name;
    return upload;
```

When the managed uploader issues the first POST however, which I'm assuming puts a "placeholder" for the upload parts, it will change the content type by appending adding charset=UTF8. The issue I think is that the SDK is too eager in checking for a string, if the string is empty it seems reasonable to not tamper with the content type. This is done here:

<img width="1053" alt="screen shot 2016-06-03 at 9 16 09 am" src="https://cloud.githubusercontent.com/assets/3407711/15781654/b9936408-296c-11e6-9a9b-097e593c8ddb.png">

This in turn causes this post, which creates the S3 object with a content type that's different from what's intended.

<img width="1210" alt="screen shot 2016-06-03 at 9 16 49 am" src="https://cloud.githubusercontent.com/assets/3407711/15781682/dc7f7358-296c-11e6-8237-30f1eee5f7fa.png">

I can understand that suffix for some type of data, but for video/mp4 it's incorrect, it is not in fact UTF-8 encoded.

Perhaps the fix could check the op type or even if the string is empty and bypass this header change.

**Comment by chrisradek** [comment]
@apires 
Thanks for reporting this issue. It looks like the code to always add `; charset=UTF-8` was due to a bug with firefox: #190 

We'll take a look and see if firefox is still affected, and what else we might be able to do if it is.

**Comment by chrisradek** [comment]
@apires 
I read through #244 as well and understand the issue better now. The SDK has a check to see if the body being uploaded is a string, but when doing a multipart upload the initiate multipart upload operation is always setting the `Body` to an empty string.

We might be able to check that the `Content-Type` is a text type before setting a charset. I still need to see if firefox or other browsers will always set a charset as well. I'll do some testing and report back.

**Comment by apires** [comment]
Not working on this anymore, but adding an option to preserve the mime as is sounds good. 

Thanks!
