### ISSUE TITLE
Cloudwatch SDK cache's key signing across objects

### ISSUE THREAD

**Issue by tyrsius** [aws/aws-sdk-js#1020]
The docs for the [cloudwatch sdk](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatch.html#constructor-property) constructor show a parameter for `signatureCache`. I understand why this would perform caching on the object that this constructor call creates; that makes sense.

However, it controls caching for other constructed SDK objects. *This is surprising behavior*. Object constructors should only affect the object they are creating; they should not set global flags that affect future objects using the same constructor. *Parameters to one constructor should not affect global application state*.

I have a lambda that needs to constuct multiple Cloudwatch instances, to access Cloudwatch alarms in multiple accounts. Calling this constructor twice, with different access keys, should not produces two Cloudwatch instances that use the same keys.

**Comment by chrisradek** [comment]
@tyrsius 
Thanks for reporting this issue. It looks like the signature cache uses the service name as the key to store the signature info. We'll need to instead use a unique identifier so we can distinguish individual clients as well.

**Comment by tyrsius** [comment]
Do you have an ETA on this? I know you guys have a big schedule, so I would understand if you don't. This is a pretty big blocker for us though.

**Comment by LiuJoyceC** [comment]
Hi @tyrsius 
This is a high priority issue for us and we are currently looking at it. Thanks for your patience!

**Comment by chrisradek** [comment]
@tyrsius 
Are you actually seeing this issue when using different access key ids?

I wrote a really simple test script that creates 2 `AWS.CloudWatch` clients with different credentials, and calls an operation one after the other. The correct credentials are being used because I'm using different `accessKeyIds`.

```javascript
var AWS = require('aws-sdk');
// User A
var cloudwatch = new AWS.CloudWatch({
    credentials: {
        accessKeyId: 'AccessKeyId1',
        secretAccessKey: 'Secret1'
    }
});

// User B
var cloudwatch2 = new AWS.CloudWatch({
    credentials: {
        accessKeyId: 'AccessKeyId2',
        secretAccessKey: 'Secret2'
    }
});
cloudwatch.listMetrics().promise()
    .then(function(data) {
        // Logs data from account 1
        console.log(data);
    })
    .then(function(){
        return cloudwatch2.listMetrics().promise();
    })
    .then(function(data) {
        // Logs data from account 2
        console.log(data);
    })
    .catch(function(err) {
        console.error(err);
    });
```
Now if I alternate between the two, that's essentially disabling caching since they have the same service name but different `accessKeyId`s. We want to fix that, but I want to make sure we cover the case you're seeing as well.

**Comment by chrisradek** [comment]
@tyrsius 
Any chance you can report back on the above? I've come up with a fix but it slightly increases the memory footprint of the SDK for each service client that's instantiated with `signatureCache: true`. I did some performance testing and didn't see a significant change in code execution speed with the change.

With all that in mind, unless you actually are setting different credentials for your clients but are seeing the same set being used for all clients, I'm more inclined not to make this change.

**Comment by tyrsius** [comment]
@chrisradek I will have some time tomorrow to verify this

**Comment by tyrsius** [comment]
Unfortunately I cannot test this today, because [AWS broke the lambda test tool](https://forums.aws.amazon.com/thread.jspa?threadID=234837), and I don't have to add add all the layers it would take to test this externally

**Comment by tyrsius** [comment]
@chrisradek  Unfortunately I cannot test this today, because [AWS broke the lambda test tool](https://forums.aws.amazon.com/thread.jspa?threadID=234837), and I don't have time to add add all the layers it would take to test this externally
