### ISSUE TITLE
Upload mp3, mov to s3. Error

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [aws/aws-sdk-js#1033]
Hey Guys. 
I'm stuck on uploading mp3 files.
The formats like: .pages, .docx, .pptx, .key, .xlsx, .csv, .numbers, .pdf, .jpg, .png, .mp4, .tiff works well!
But mp3 has some issue. 

Here is my log:
![screen shot 2016-06-23 at 1 57 28 pm](https://cloud.githubusercontent.com/assets/3968373/16300899/095be63e-394b-11e6-94df-632d3ff6d2e4.png)
![screen shot 2016-06-23 at 1 57 45 pm](https://cloud.githubusercontent.com/assets/3968373/16300900/09796718-394b-11e6-9371-66db38739d26.png)
![screen shot 2016-06-23 at 1 57 52 pm](https://cloud.githubusercontent.com/assets/3968373/16300902/0987f882-394b-11e6-9dc9-45acc4b48609.png)
![screen shot 2016-06-23 at 1 57 59 pm](https://cloud.githubusercontent.com/assets/3968373/16300904/09886ace-394b-11e6-9ff4-a78e112c484b.png)
![screen shot 2016-06-23 at 1 58 17 pm](https://cloud.githubusercontent.com/assets/3968373/16300901/0987ce7a-394b-11e6-85e3-dc98a5fb006f.png)
![screen shot 2016-06-23 at 1 58 23 pm](https://cloud.githubusercontent.com/assets/3968373/16300905/098ccb14-394b-11e6-9431-433370f362e3.png)
![screen shot 2016-06-23 at 1 58 31 pm](https://cloud.githubusercontent.com/assets/3968373/16300903/098838ce-394b-11e6-8598-838b1cb6043c.png)
![screen shot 2016-06-23 at 1 58 36 pm](https://cloud.githubusercontent.com/assets/3968373/16300906/09964464-394b-11e6-8938-37cde10d92c1.png)

**Comment by Iuriy-Budnikov** [comment]
The same issue with .mov files

**Comment by chrisradek** [comment]
@Iuriy-Budnikov 
It looks like you're using the `s3.upload` method. Can you share what your S3 client configuration looks like, as well as the params you're passing into the upload operation?

**Comment by chrisradek** [comment]
@Iuriy-Budnikov 
Can you also share any specific error messages you're receiving?

**Comment by Iuriy-Budnikov** [comment]
I am using custom build 
```
$ AWS_SERVICES=s3 browserify index.js > browser-app.js
```
from [http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-building.html](url)

Config
```
new AWS.S3({
      region: config.awsS3Region,
      signatureVersion: 'v4',
      params: {
        ACL: 'public-read',
        Bucket: config.awsS3Bucket
      },
      accessKeyId: config.awsS3AccessKeyId,
      secretAccessKey: config.awsS3SecretAccessKey,
    });
```

Upload params
![screen shot 2016-06-24 at 11 43 23 am](https://cloud.githubusercontent.com/assets/3968373/16332850/e9585c1c-3a00-11e6-98f1-a73b84b5ba10.png)


Response with errors are empty
![screen shot 2016-06-24 at 11 45 07 am](https://cloud.githubusercontent.com/assets/3968373/16332915/41a7e8ec-3a01-11e6-9ac0-eccfde8f4790.png)
![screen shot 2016-06-24 at 11 45 16 am](https://cloud.githubusercontent.com/assets/3968373/16332914/41a6dfb0-3a01-11e6-8054-90ea7fb5ca15.png)
![screen shot 2016-06-24 at 11 45 21 am](https://cloud.githubusercontent.com/assets/3968373/16332918/41a9ff10-3a01-11e6-8b5f-3e67b91f37af.png)
![screen shot 2016-06-24 at 11 45 27 am](https://cloud.githubusercontent.com/assets/3968373/16332917/41a8dfc2-3a01-11e6-9a66-5cb91c20c42c.png)
![screen shot 2016-06-24 at 11 45 33 am](https://cloud.githubusercontent.com/assets/3968373/16332916/41a88f18-3a01-11e6-8613-0270167c128a.png)
![screen shot 2016-06-24 at 11 45 41 am](https://cloud.githubusercontent.com/assets/3968373/16332919/41abf284-3a01-11e6-929d-1394fceecf2d.png)
![screen shot 2016-06-24 at 11 45 46 am](https://cloud.githubusercontent.com/assets/3968373/16332921/41cd85ac-3a01-11e6-8da7-c011e87d247d.png)
![screen shot 2016-06-24 at 11 45 51 am](https://cloud.githubusercontent.com/assets/3968373/16332920/41cadc12-3a01-11e6-8ed7-51b3c413b7c3.png)

**Comment by chrisradek** [comment]
@Iuriy-Budnikov 
What browser/os combination are you testing with? Have you tried any other browsers? Using Chrome on mac os x, I'm unable to reproduce your issue using the same configuration you are.

Are you exposing any headers in your bucket CORS configuration? Based on your original screenshots I don't see a `Access-Control-Expose-Headers` response header in any of your responses, and you should at least be exposing `ETag`.

Bucket CORS configuration - expose headers:
```xml
<ExposeHeader>ETag</ExposeHeader>
```

Also, the callback you supply to your `upload` operation receives an `error` and `data` object, depending on of it succeeded or failed. Can you log the error if there is one?

Also, are your mp3's >= 5MB in size? Do you have a smaller mp3 or mov file you can test to see if you get the same result?

**Comment by Iuriy-Budnikov** [comment]
@chrisradek I'm tested on Mac OS, latest version of Chrome.
Also, are your mp3's >= 5MB in size?

I tried to upload file less 5 mb. It works.

**Comment by Iuriy-Budnikov** [comment]
I'll check with ```<ExposeHeader>ETag</ExposeHeader>``` today.

**Comment by Iuriy-Budnikov** [comment]
@chrisradek Is it possible to upload files >= 5mb ?

**Comment by Iuriy-Budnikov** [comment]
>Also, the callback you supply to your upload operation receives an error and data object, depending on of it succeeded or failed. Can you log the error if there is one?

The issue that I didn't see any errors in log and response.

**Comment by chrisradek** [comment]
@Iuriy-Budnikov 
It is possible to upload files >= 5mb. When using the `s3.upload` method, internally the SDK will do a multipart upload if the file size is larger than 5 MB. If the file is less than 5 MB, it will do a single `s3.putObject`. 
Multi-part uploads need to send the `ETag` of all the parts to work properly. Since `putObject` is working, but multi-part uploads aren't, my hunch is that `ETag` headers aren't exposed in your bucket's CORS configuration.

**Comment by Iuriy-Budnikov** [comment]
@chrisradek thanks. ```ETag``` resolved my issue.
