### ISSUE TITLE
unsafe use of 'hasOwnProperty'

### ISSUE THREAD

**Issue by mediaupstream** [aws/aws-sdk-js#1038]
I notice you are using 'hasOwnProperty' in an unsafe way. example: https://github.com/aws/aws-sdk-js/blob/master/lib/param_validator.js#L68

The above code fails if the params object was created with `Object.create(null)`. Bad idea to assume that objects have a prototype and that it points to `Object.prototype`.

The safe way is to use `Object.prototype.hasOwnProperty.call()` for example, to fix the code from param_validator.js you could do:

```javascript
if (!Object.prototype.hasOwnProperty.call(params, paramName)) continue;
````
Thoughts?

**Comment by mediaupstream** [comment]
easy solution: don't use `Object.create(null)` to create objects which will be used with the aws-sdk. But, NodeJS core modules often times use Object.create(null), for example the `querystring.parse` method: https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options

**Comment by LiuJoyceC** [comment]
Hi @mediaupstream 
Thanks for sharing your concern. Do you have a particular use case where you would need to point your `params` object to null as its prototype in production code? It is common practice to call `hasOwnProperty` on objects and assume that `Object.prototype` is in its prototype chain, and we have never seen any customers run into this theoretical edge case in practice. However, please do let us know if you have a special use case that would require this edge case to be addressed. Thanks!

**Comment by mediaupstream** [comment]
Hi @LiuJoyceC 
Some nodejs core modules return objects by way of `Object.create(null` see: https://github.com/nodejs/node/blob/master/lib/url.js#L75
So if you pass the output of `url.parse('http://example.com?foo=bar', true).query` straight to `aws.CloudSearchDomain.search` for example it will fail.

**Comment by LiuJoyceC** [comment]
Hi @mediaupstream 
Thanks for the suggestion. We will add this as a feature request.

**Comment by LiuJoyceC** [comment]
Thanks for the PR!

**Comment by mediaupstream** [comment]
Thanks for merging!
