### ISSUE TITLE
mismatch file size and partSize when streaming to S3 halts upload

### ISSUE THREAD

**Issue by donnut** [aws/aws-sdk-js#1042]
My question is: what is the relationship between file size streaming to S3 and the option `partSize`.

I'm streaming files to S3 using `dd` as the source.

When streaming a 1 Gb file I don't need to set the options `partSize` and `queueSize`. 
When streaming 100Gb the process halts and I need to set `partSize` to 200MB and `queueSize` to 1. 

The minimum `partSize` is about 5 Mb and the max number of parts/chunks must be below 1000 (is that correct?) . What is the best practice to determine the value for `partSize`?

```javascript

conn.exec('dd if='bigfile', function(err, stream) {
    ...
    managedUpload = s3.upload({
        Key:    "#{backupName}",
        ACL:    aws.ACL,
        Bucket: aws.Bucket,
        Body:   stream.stdout
    }, {
        partSize:  200 * 1024 * 1024,
        queueSize: 1
    })
    ....

```

I'm using node 4.2.6 and aws-sdk version 2.3.18

**Comment by chrisradek** [comment]
@donnut 
When uploading files larger than 5 MB, the `upload` method will do a multipart upload. This allows it to upload multiple parts of your file in parallel, and each part can be retried individually. `partSize` refers to the size of each individual part. It essentially determines how to slice up your file when uploading.

Here's a link to S3 documentation that hopefully helps answer part of your question:
http://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html

By default, the SDK's `upload` method will use a `partSize` of 5 MB, with the maximum number of parts set to 10,000.
A 100 GB file, split up into 5 MB parts, would need to be sent in 20,480 parts, which is above the 10,000 limit imposed by S3 and the SDK.

You can simply take the file size in bytes, divide by the maximum number of parts (10,000), and that will give you the smallest `partSize` you can use. Your `partSize` can't be lower than 5 MB, and you might round up your `partSize` to the nearest MB.

Let me know if that helps!

**Comment by donnut** [comment]
@chrisradek Thanks for your explanation. There seems to be an upper limit to the partSize as well. I noticed that increasing the partSize and/or queueSize increases the memory requirements. If the partSize to chosen too big w.r.t. the available memory, things get very slow.
