### ISSUE TITLE
SWF in current dist build?

### ISSUE THREAD

**Issue by jhludwig** [aws/aws-sdk-js#1044]
I don't seem to see SWF in the current 2.4.5 built version, is there a reason it is being excluded?

**Comment by LiuJoyceC** [comment]
Hi @jhludwig 
By default, the dist build only includes services that have enabled CORS support. If you are working in an environment that doesn't enforce CORS, you can create a custom build here: https://sdk.amazonaws.com/builder/js/

Let me know if you have any questions!

**Comment by jhludwig** [comment]
ah.  ugh.  any idea if swf is going to add CORS support?  thanks.

**Comment by LiuJoyceC** [comment]
We are working towards adding CORS support for all services in the future. I will mark this as a service change and let you know when CORS support has been added to SWF.

**Comment by LiuJoyceC** [comment]
Hi @jhludwig 
I will reach out to the SWF team again for an update. It would be helpful post this request for CORS support on the AWS Forum for SWF to add visibility to this issue. Thanks! I will close this issue as it is not an SDK issue.
