### ISSUE TITLE
S3.listObjects throws error if Bucket is prefixed with /

### ISSUE THREAD

**Issue by bisrael** [aws/aws-sdk-js#1046]
If you remove the leading `/`, the request will succeed.

Other S3 methods like `upload` accept the leading `/` gracefully.

```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at Request.extractError (/proj/node_modules/aws-sdk/lib/services/s3.js:524:35)
    at Request.callListeners (/proj/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/proj/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/proj/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/proj/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/proj/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /proj/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/proj/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/proj/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/proj/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

**Comment by chrisradek** [comment]
@bisrael 
Does your bucket contain a leading `/`?

Can you also share what version of the SDK you're using?

**Comment by bisrael** [comment]
looking at our S3 console, no the bucket is just like `bucket-desktop`.

Maybe the problem is more that the other methods accept the leading slash?

Version 2.4.3 from npm:
```
npm list | grep aws
├─┬ aws-sdk@2.4.3
```

**Comment by chrisradek** [comment]
I'll have to investigate why some operations safely remove the leading slash. One thing I noticed, is that if you configure your S3 client to use `signatureVersion: 'v2'`, `s3.listObjects` will accept the leading slash, but it won't when `signatureVersion: 'v4'` (default) is used. It seems that with `v2`, S3 was more lax with removing the invalid slash. We might be able to add logic to remove those slashes automatically in the SDK, though really leading slashes shouldn't be used as S3 will strip them out when creating a bucket anyway, and that might cause confusion for some users if their provided bucket name doesn't match the actual bucket name.

**Comment by bisrael** [comment]
Thanks for investigating.

If it helps, we are not altering the default config in any way other than to set up our credentials (code below).

```js

function setupAws() {
  aws.config.update(findAWSCredentials());
}


function findAWSCredentials() {
  var aws_config_files = ['/.aws/credentials', '/.s3cfg', '/.aws/config'];
  var awsSecrets = {};

  for (var i = 0, l = aws_config_files.length; i < l; ++i) {
    var fn = process.env['HOME'] + aws_config_files[i];
    try {
      var inistring = fs.readFileSync(fn, 'utf-8');
      var awscreds = ini.parse(inistring);
    } catch (e) {
      // console.log(fn, 'errored:', e);
    }
    if (awscreds && awscreds.default) {
      awsSecrets = awscreds.default;
      break;
    } else if (awscreds && awscreds['profile eb-cli']) {
      awsSecrets = awscreds['profile eb-cli'];
      break;
    } else if (awscreds && ((awscreds.access_key && awscreds.secret_key) || (awscreds.aws_access_key_id || awscreds.aws_secret_access_key))) {
      awsSecrets = awscreds;
      break;
    }
  }

  return {
    accessKeyId: awsSecrets.aws_access_key_id || awsSecrets.access_key,
    secretAccessKey: awsSecrets.aws_secret_access_key || awsSecrets.secret_key,
  }
}
```

**Comment by BehrensT** [comment]
To add to this issue: 

It seems like if the bucket contains a '/' it is getting URL encoding and causing the SignatureDoesNotMatch code to get thrown. 

Example:

s3.getObject({
    Bucket: 'logs.abc.com/vin',
    Key:  "WP0CB2A95BS754907.xml"
}, function(err, data) {

    if (err) {
        console.log("Code:", err.code);
        console.log("Request:");
        console.log(this.request.httpRequest);

    } else if (data) {
        console.log("data", data);

    }
});

OUTPUTS
Code: SignatureDoesNotMatch
Request:
HttpRequest {
  method: 'GET',
  path: '/logs.abc.com%2Fvin/WP0CB2A95BS754907.xml',
}

If I remove the "/vin" for the bucket property and move the file I am looking for in the root of the bucket.  The SignatureDoesNotMatch error goes away and I get my data. 

Thanks.

**Comment by chrisradek** [comment]
After investigating further, the SDK shouldn't allow `/` in a bucket name. They appear to work in some but not all cases when using `signatureVersion: 'v2'`, and not at all when using `signatureVersion: 'v4'`. Other SDKs, like Ruby and the AWS CLI throw a more helpful error when a `/` is in a bucket name. We can also throw a more informative error when `/` is in the bucket name and the user is using `signatureVersion: 'v4'`, but may need to hold off on doing the same with `v2` since this change could break users relying on existing (arguably broken) behavior.

**Comment by ajredniwja** [comment]
Closing this issue since the feature was implemented.
