### ISSUE TITLE
Creation of many S3 buckets programmatically 

### ISSUE THREAD

**Issue by LamourBt** [aws/aws-sdk-js#1049]
Instead of creating buckets into S3 manually, I am trying to create a script where all the buckets get created programmatically.  So let's say I had an array containing the name of the buckets. 

`var arrayOfBuckets = ["bucket1","bucket2","bucket3"];`
`arrayOfBuckets.forEach(function(each) {`
`var params = {Bucket:each};`
   `s3.createBucket(params,function(err) {`
      `if (err)  console.log(err);`
      `else console.log("bucket was saved");});`
`});`

**Just to say: I have access S3 Full Administration Access to s3** 

But when I do it this way i get this error **{ [BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.]
  message: 'The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.',
  code: 'BucketAlreadyExists',
  region: null,
  time: Sat Jul 09 2016 22:47:10 GMT-0400 (EDT),
  requestId: '87C3299EFD832EAE',
  extendedRequestId: 'wFTn7vt88hEROnTteIpqBD1VLrzqlO7Hn3fmaQ/sP/hFe4eA+9LqTFrxyroYn9pq+mI5aQsf92k=',
  cfId: undefined,
  statusCode: 409,
  retryable: false,
  retryDelay: 90.22490077186376 }**

**Comment by chrisradek** [comment]
@LamourBt 
Bucket names are shared across all S3 users, so it may be that the names you've chosen are already taken. That's what the error from S3 is indicating. Were you able to create them in the console manually after seeing this error?

**Comment by LamourBt** [comment]
Problems solved
