### ISSUE TITLE
Adding custom metadata to log messages

### ISSUE THREAD

**Issue by tepez** [aws/aws-sdk-js#1051]
I'm doing AWS API calls from a [hapi](http://hapijs.com/) server.

I want to associate each AWS log message with the hapi request it was done for.

This will make debugging issues much easier.

What is the correct pattern to do that?

Is creating a new `AWS.XXX` objects, with custom loggers, for every request that needs it reasonable?
Are there any downsides to this, e.g. loosing a cache?

**Comment by LiuJoyceC** [comment]
Hi @tepez 

As you mentioned, creating new service clients (`AWS.XXX` objects) for each request does have the downside of not allowing those requests to share certain caches or potential caches the SDK could implement in the future. However, it is not unreasonable to create new service clients for each request if this does not negatively impact your use case.

If you don't wish to create new service clients for each request, here is a workaround to still create separate logs for each request. Your server's handler could do something like this:
```
function(request, reply) {
    // assume you have some function that returns a custom logger for your hapi request
    var customLogger = getCustomLoggerForRequest(request);
    var params = getAWSParamsForHapiRequest(request);
    // for most service operation calls, `this` in the callback is equal to the AWS.Response obj
    s3.getObject(params, function(err, data) {
        var awsResponse = this;
        var awsRequest = awsResponse.request;
        // create your own log message with the desired data from the response or request
        var logMessage = generateLogMessage(awsResponse, awsRequest);
        // this example assumes the customLogger is a writable stream
        customLogger.write(logMessage);
        // you can call customLogger.end() if you won't be writing any other log messages to it

        // do other stuff you need for the server
    });
}
```

Let me know if this works for your use case.

**Comment by tepez** [comment]
Hey @LiuJoyceC
It that creating custom log messages as you suggested is the best option for my use case.
Thanks for the quick response.
