### ISSUE TITLE
response-content-disposition ignored

### ISSUE THREAD

**Issue by kengoldfarb** [aws/aws-sdk-js#1055]
It seems that ```response-content-disposition``` is being ignored.  I'm using the latest version of the SDK (and have tested several older versions as well).

Has something changed?  This was working for me a week ago and my code hasn't changed since then.

Steps to reproduce:

* Make a request to get a signed url w/ 'ResponseContentDisposition'

```
const params = {
	Bucket: bucket,
	Key: fileKey,
	Expires: expires,
	ResponseContentDisposition: 'attachment; filename=test.mov'
};

s3.getSignedUrl('getObject', params, (err, data) => {
	if (err) {
		// Handle error
		return;
	}

	// Redirect user to signed download url
});
```

* Follow the returned url

```
https://MYBUCKET.s3.amazonaws.com/media/123458b3-e472-4f2f-af03-4dbe792cee58.mov?AWSAccessKeyId=[MYKEY]&Expires=[EXPIRES]&Signature=[SIG]&response-content-disposition=attachment%3B%20filename%3Dtest.mov
```

I'd expect that the filename downloaded would be 'test.mov', but instead the response Content-Disposition header uses the actual filename:

```
Content-Disposition  attachment; filename=/media/123458b3-e472-4f2f-af03-4dbe792cee58.mov
```

**Comment by kengoldfarb** [comment]
Apparently this is a known issue:
https://forums.aws.amazon.com/thread.jspa?messageID=730470&#730470

**Comment by LiuJoyceC** [comment]
Hi @kengoldfarb 
Thanks for reporting the issue. This is a service issue, and S3 is working on it.

**Comment by LiuJoyceC** [comment]
Hi @kengoldfarb 
The S3 team posted back on the forum thread on Aug 3 that the fix has been deployed. I am closing this issue. If you have any questions about this fix, please feel free to post back on the forum thread. Thanks!
