### ISSUE TITLE
DMS waiters

### ISSUE THREAD

**Issue by wjordan** [aws/aws-sdk-js#1060]
AWS [Database Migration Service](https://aws.amazon.com/dms/) (DMS) has several APIs for managing underlying resources that take a non-trivial time after creation/modification to transition into an available state, and could benefit from SDK waiters. Here are some resources managed by DMS, the `describe*` client operations used to query the resources, and the corresponding `status` variables that describe their availability:
- ReplicationInstance ([DescribeReplicationInstances](http://docs.aws.amazon.com/dms/latest/APIReference/API_DescribeReplicationInstances.html) [`ReplicationInstances[].ReplicationInstanceStatus`](http://docs.aws.amazon.com/dms/latest/APIReference/API_ReplicationInstance.html#DMS-Type-ReplicationInstance-ReplicationInstanceStatus))
- Endpoint ([DescribeEndpoints](http://docs.aws.amazon.com/dms/latest/APIReference/API_DescribeEndpoints.html) [`Endpoints[].Status`](http://docs.aws.amazon.com/dms/latest/APIReference/API_Endpoint.html#DMS-Type-Endpoint-Status)
- ReplicationTask ([DescribeReplicationTasks](http://docs.aws.amazon.com/dms/latest/APIReference/API_DescribeReplicationTasks.html) [`ReplicationTasks[].Status`](http://docs.aws.amazon.com/dms/latest/APIReference/API_ReplicationTask.html#DMS-Type-ReplicationTask-Status)
- ReplicationSubnetGroup ([DescribeReplicationSubnetGroups](http://docs.aws.amazon.com/dms/latest/APIReference/API_DescribeReplicationSubnetGroups.html) [`ReplicationSubnetGroups[].SubnetGroupStatus`](http://docs.aws.amazon.com/dms/latest/APIReference/API_ReplicationSubnetGroup.html#DMS-Type-ReplicationSubnetGroup-SubnetGroupStatus))

While `Endpoint` and `ReplicationSubnetGroup` seem to complete creation relatively quickly, `ReplicationInstance` and `ReplicationTask` take a non-trivial time (several minutes or longer) to complete.

**Comment by LiuJoyceC** [comment]
Hi @wjordan 
Thanks for the suggestion! We will add this as a feature request to our backlog.

**Comment by wjordan** [comment]
@LiuJoyceC any updates on the process to get #1062 merged somewhere upstream? Are the shared files across AWS SDKs you [mentioned](https://github.com/aws/aws-sdk-js/pull/1062#issuecomment-233056420) in a public repo I can submit a separate PR for, or is there anything else I can do to help this process along?

**Comment by LiuJoyceC** [comment]
Hi @wjordan 
This feature request is currently in our backlog and has been prioritized. The shared files are private, but your previous PR is already helping the process along, so thanks for submitting it!

**Comment by wjordan** [comment]
Any updates in the last year on this? I've been patiently waiting for these waiters to be added upstream..

**Comment by srchase** [comment]
DMS waiters were added in [2.345.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#23450).

Closing out this request.
