### ISSUE TITLE
Better documentation for Credentials.expiryWindow

### ISSUE THREAD

**Issue by kentor** [aws/aws-sdk-js#1068]
Link to docs: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html

The entry on `expiryWindow` just shows the default value of `15`. From reading the source code, I think this means 15 _seconds_. The description should probably say something like "the amount of time (in seconds) before the `expireTime` that the credentials is considered expired."

**Comment by chrisradek** [comment]
@kentor 
Nice catch! We'll get this updated.

**Comment by scottw-finao** [comment]
I'm seeing it's still not updated with anything other than Integer, Number. What is it and how is it used?

**Comment by bosmanx** [comment]
@jeskew Changed the comment in code, but that does not propagate to documentation at http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html, which is still not helpful at all.
