### ISSUE TITLE
S3 Upload PutObject 403 using STS keys

### ISSUE THREAD

**Issue by eetee** [aws/aws-sdk-js#1069]
I've been trying to set up Amazon's STS (Security Token Service) to create temporary credentials for client side uploads to S3.

I can get the code working fine with an access key generated from the IAM user, but when I swap out the access key/secret key and then add the session token I am getting a 403 Forbidden. S3 access logs do not log the attempt.

On the STS side I am generating the credentials via the aws-sdk for node.js, using the same IAM user as above, the SDK generates the STS credentials happily:

    let sts = new AWS.STS({apiVersion: '2011-06-15'});
    sts.assumeRole({
      RoleArn: 'arn:aws:iam::[REMOVED]:role/[REMOVED]',
      RoleSessionName: [REMOVED (generated by concatenating a few ids)]
      DurationSeconds: 60 * 20,
    }, (err, data)=>{
      //callback handling
    });

Upload test code:

    var AWS = require('aws-sdk');
    
    // Load the stream
    var fs = require('fs');
    var body = fs.createReadStream('./helloworld.txt');
    
    AWS.config.update({
      region: 'ap-southeast-2',
      accessKeyId: '[REMOVED]',
      secretAccessKey: '[REMOVED]',
      sessionToken: '[REMOVED]'
    });
    
    // Upload the stream
    var s3 = new AWS.S3();
    
    s3.putObject({
      Body: body,
      Bucket: '[REMOVED]',
      Key: 'helloworld.txt'
    }, function(err, data) {
      if (err) console.log(err, err.stack); // an error occurred
      else     console.log(data);           // successful response
    });

aws-sdk version: 2.4.8
node.js: 4.2.3

I've tested the role policy that it assumes using the IAM simulator which says it's fine. Tried on both browser side and server side uploading using the sdk.

I opened up the S3 CORS (for debugging) to make sure nothing weird was going on there:

    <?xml version="1.0" encoding="UTF-8"?>
    <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
        <CORSRule>
            <AllowedOrigin>*</AllowedOrigin>
            <AllowedMethod>PUT</AllowedMethod>
            <AllowedMethod>GET</AllowedMethod>
            <AllowedMethod>POST</AllowedMethod>
            <MaxAgeSeconds>0</MaxAgeSeconds>
            <ExposeHeader>ETag</ExposeHeader>
            <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
            <ExposeHeader>x-amz-request-id</ExposeHeader>
            <ExposeHeader>x-amz-id-2</ExposeHeader>
            <AllowedHeader>*</AllowedHeader>
            <AllowedHeader>x-amz-acl</AllowedHeader>
        </CORSRule>
    </CORSConfiguration>

S3 policy I've opened up (again for debugging):

    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "s3:*"
                ],
                "Resource": [
                    "[REMOVED]"
                ]
            }
        ]
    }

I've tried asking on StackOverflow with no luck, I'm hoping you guys might have a better idea?
[http://stackoverflow.com/questions/38473103/aws-sdk-upload-with-sts-credentials-403-error](http://stackoverflow.com/questions/38473103/aws-sdk-upload-with-sts-credentials-403-error)

**Comment by chrisradek** [comment]
@eetee 
How are you updating your credentials once you've called `assumeRole`?

```javascript
AWS.config.update({
  accessKeyId: /* */,
  secretAccessKey: /* */,
  sessionToken: /* */
});
```
The credentials should actually be one level lower:
```javascript
AWS.config.update({
  credentials: {
    accessKeyId: /* */,
    secretAccessKey: /* */,
    sessionToken: /* */
  }
});
```

**Comment by eetee** [comment]
Hi @chrisradek,

First of all thanks for replying, much appreciated.

It seems both methods are accepted: [http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property)

Nonetheless, I tried it again after your comment and still get the same 403 (Forbidden) Error: Access Denied

Do you have any other suggestions for me to try?

Thanks

**Comment by eetee** [comment]
The issue was the ACL on the bucket itself an extra ACL rule was required for the STS to go through but not the regular IAM user for some reason. 

It's not a aws-sdk-js issue so I won't go into detail here. I've posted my answer to the stackoverflow post: [http://stackoverflow.com/questions/38473103/aws-sdk-upload-with-sts-credentials-403-error](http://stackoverflow.com/questions/38473103/aws-sdk-upload-with-sts-credentials-403-error)

**Comment by josedarwoft** [comment]
Hi @eetee I know this is a old post, but, have you fixed this? I'm working trying to get working something similar ( I can upload files, but I'm having some issues with the STS) thanks!

**Comment by trivikr** [comment]
Locking this thread as the issue is old, and resolved.
@josedarwoft Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
