### ISSUE TITLE
connect ECONNREFUSED behind company proxy

### ISSUE THREAD

**Issue by sandyleo26** [aws/aws-sdk-js#1070]
Hi Guys,

My company uses a proxy for internet access. And I always get the following error using a simple example below. **However**, it's OK if I use `aws s3 cp ...` in command line OR commenting out the proxy code and use my iphone's hotspot through USB. I'm using git-bash terminal under Win 7. 

I tried proxy-agent and disable sslEnabled but still fail. aws cli (and npm) and proxy seems working fine together. And a similar example to [this](https://www.npmjs.com/package/proxy-agent#example) also works, which makes me think maybe I miss some configuration regarding s3 in aws-sdk-js? Any ideas? Thanks

```
           throw err;
            ^
Error: connect ECONNREFUSED 54.211.18.10:443
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
```

```javascript
var aws = require('aws-sdk');
var s3 = new aws.S3();
var fs = require('fs');
var proxy = require('proxy-agent');

aws.config.update({
    httpOptions: {
        agent: new proxy('http://192.168.20.200:80')
    }
});

aws.config.update({sslEnabled: false});

var file = fs.createWriteStream('download.js');
s3.getObject({Bucket: 'mybucket', Key: 'config.js'}).createReadStream().pipe(file);
```

**Comment by chrisradek** [comment]
@sandyleo26 
You're setting the config options a little too late. When you instantiate a service client (`new aws.S3()`), it is instantiated with whatever the config options were at that point in time. Instead, you'll either want to instantiate your `s3` client after updating the global config, or move the config into your S3 client declaration:
```javascript
var s3 = new aws.S3({
  sslEnabled: false,
  httpOptions: {
    agent: new proxy('...')
  }
});
```

Let me know if that helps!

**Comment by sandyleo26** [comment]
man that works like a charm! Thanks so much!

**Comment by seventrust** [comment]
MAN!!! ty so much :D

**Comment by gangavh** [comment]
thanks a lot.
