### ISSUE TITLE
Problem Invoking Lambda Functions Using Javascript and Internet Explorer

### ISSUE THREAD

**Issue by mark3072** [aws/aws-sdk-js#1080]
Just last week, it was relatively easy to invoke lambda functions directly from javascript using the javascript sdk. By bypassing the API Gateway one could allow invoke times up to 5 minutes which is very handy.

However, as of late last week a change was introduced to lambda's OPTION response it switched from:
```
Response	HTTP/1.1 200 OK
Access-Control-Allow-Headers	content-type, accept, authorization, x-amz-invocation-type, x-amz-date
Access-Control-Allow-Methods	POST
Access-Control-Allow-Origin	*
Access-Control-Expose-Headers	x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
Access-Control-Expose-Headers	x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,x-amz-log-result,x-amz-function-error
Access-Control-Max-Age	172800
Date	Fri, 22 Jul 2016 19:52:45 GMT
x-amzn-RequestId	dc2b763a-5045-11e6-bf3d-e59bcec371fd
Content-Length	0
Connection	keep-alive
```

To:
```
Response	HTTP/1.1 200 OK
Access-Control-Allow-Headers	accept
Access-Control-Allow-Headers	x-amz-invocation-type
Access-Control-Allow-Headers	content-type
Access-Control-Allow-Headers	authorization
Access-Control-Allow-Headers	x-amz-date
Access-Control-Allow-Methods	POST
Access-Control-Allow-Origin	*
Access-Control-Expose-Headers	x-amz-log-result
Access-Control-Expose-Headers	x-amzn-ErrorMessage
Access-Control-Expose-Headers	x-amzn-RequestId
Access-Control-Expose-Headers	x-amzn-ErrorType
Access-Control-Expose-Headers	x-amz-function-error
Access-Control-Expose-Headers	Date
Access-Control-Max-Age	172800
Date	Fri, 22 Jul 2016 19:54:10 GMT
x-amzn-RequestId	0e995057-5046-11e6-b263-c568e27957b5
Content-Length	0
Connection	keep-alive

```
Unfortunately, this breaks on IE which seems to be incapable of handling header in a row format instead of a comma delimited list. It now throws errors like the following:

SEC7123: Request header authorization was not present in the Access-Control-Allow-Headers list.

Is this a permanent change that Amazon has chosen to make and to drop support for IE? Or is it a bug?

**Comment by LiuJoyceC** [comment]
Hi @mark3072 

Thanks for bringing up this issue. Amazon has not dropped support for IE. I will investigate this issue further and let you know.

**Comment by LiuJoyceC** [comment]
Hi @mark3072 

Lambda has rolled back this change and it should work now on IE and Edge. Thanks!
