### ISSUE TITLE
NetworkingError: first argument must be a string or Buffer

### ISSUE THREAD

**Issue by merlinpatt** [aws/aws-sdk-js#1082]
I'm updating an old project that uses `2.3.7` of this SDK. When I attempt to update to the latest code, I get the below error. I've managed to trace it back to [changes made in 2.3.8 in the lib/http/node file](https://github.com/aws/aws-sdk-js/compare/0bfea05...3ecb3b4#diff-e8a1def4cf1938c1bdf0c30b2dac533d).

Any thoughts on what the issue is and how I can fix it?

This is the error I'm getting

    Exception in callback of async function: NetworkingError: first argument must be a string or Buffer
        at ClientRequest.OutgoingMessage.end (_http_outgoing.js:549:11)
        at [object Object].writeBody (node_modules/aws-sdk/lib/http/node.js:103:14)
        at [object Object].handleRequest (node_modules/aws-sdk/lib/http/node.js:71:12)
        at executeSend (node_modules/aws-sdk/lib/event_listeners.js:241:29)
        at Request.SEND (node_modules/aws-sdk/lib/event_listeners.js:256:9)
        at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:101:18)
        at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:77:10)
        at Request.emit (node_modules/aws-sdk/lib/request.js:615:14)
        at Request.transition (node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)

This is the code I'm using

      const response = HTTP.get(url, {npmRequestOptions: {encoding: 'binary'}});
      const buffer = Buffer.from(response.content, 'binary');

      const contentType = response.headers['content-type'];
      const extension = contentType.replace('image/', '').replace(/;.*/, '');
      const metaContext = {cardId, directory: Meteor.userId(), name, type: 'image', extension};

      const fileObject = {
        Key: Files.getPath(metaContext),
        Body: buffer,
        ContentType: contentType,
        ContentLength: buffer.length,
      };

      const s3 = new AWS.S3({params: {Bucket: Meteor.settings.AWS.bucket}});
      s3.putObject(fileObject, Meteor.bindEnvironment(error => {
        if (error) {
          throw error;
        }

        Meteor.call('insertFile', metaContext);
      }));

**Comment by chrisradek** [comment]
@merlinpatt 
Can you share the exact version of node.js you're using?

I'm not using `Meteor`, but it looks like it just uses `request` internally. I wrote a quick test that mimics your code but using `request` directly instead:

```javascript
var request = require('request');
var AWS = require('aws-sdk');
var url = '<URL>';
request({
    url: url,
    encoding: 'binary',
    method: 'get'
}, function(err, resp, body) {
    var buffer = Buffer.from(body, 'binary');
    var contentType = resp.headers['content-type'];

    var s3 = new AWS.S3();
    s3.putObject({
        Key: 'test.jpg',
        Bucket: 'bucket',
        Body: buffer,
        ContentType: contentType,
        ContentLength: buffer.length
    }, function(err, data) {
        if (err) {
            console.log(err);
        } else {
            console.log(data);
        }
    });
});

console.log(AWS.VERSION); //2.3.8
```
I was able to verify (using node 6.3.0 and SDK 2.3.8) that the image was uploaded to S3 and was not corrupted.

Can you verify what the type of `buffer` is in your example, and that the `response.content` passed into `Buffer.from` is a string? 

You mentioned that you traced the issue to version 2.3.8 of the SDK. Is that the same version that your stack trace was generated with?

**Comment by merlinpatt** [comment]
Yeah my stack trace was generated with 2.3.8. I'm running node 4.4.7.

I can verify that `response.content` is in fact a string (using `typeof`). And that `buffer` is Buffer (using `.constructor` since `typeof` just returns object)

**Comment by chrisradek** [comment]
Can you try using version 6.x of node.js? 

`Buffer.from` wasn't a public API in node.js 4.4.7, and it didn't accept a string until version 5.10.0, so I'm not sure how it's being used in your example.

**Comment by merlinpatt** [comment]
Turns out the issue was that I was using [Buffer for the browser](https://www.npmjs.com/package/buffer) and not the builtin one. I don't see why that should cause a problem since it's supposed to be the same but that's what it was.

Thanks for your help.

**Comment by roo2** [comment]
Thanks I also had the issue of bufer for the browser overwriting the nodejs default buffer. In my case I was using electron and webpack and was able to solve the issue by adding buffer to webpack externals https://webpack.js.org/configuration/externals/
