### ISSUE TITLE
Use strict mode

### ISSUE THREAD

**Issue by ash2k** [aws/aws-sdk-js#1083]
I wonder why AWS SDK is not using [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)?

**Comment by chrisradek** [comment]
I can't speak to why it wasn't originally used, but flipping it on now for the entire SDK would likely cause some issues. We can transition to using strict mode as we add new code, but we probably won't devote time to add it to existing functions unless there was a strong case to do so.

This would be something we could use from the start with a major version bump of the SDK.

Closing this issue, but feel free to comment if you have a use-case for enabling it.
