### ISSUE TITLE
Using client side encryption with upload multipart ?

### ISSUE THREAD

**Issue by clakech** [aws/aws-sdk-js#1089]
Hi,

I would like to send quite big files to S3, so I am using s3.upload with multipart but as you know aws s3 js sdk does not manage client side encryption (yet?) :cry: 

The use case is a browser uploading a file to my server unencrypted, and while I received streams of this upload, I send these streams to s3 with s3.upload (sample here: https://www.terlici.com/2015/05/16/uploading-files-locally.html) That way, I don't have to wait for the whole download to finish before uploading to S3. That way, I can use client side encryption to my own server.

Do you think aws sdk js is usable in this use case (multipart upload with CSE) ?

I am worrying that s3 will not be able to recompose the file with all the differents parts if they have been encrypted on their own side.

I know it is not completely clear. But If someone understand my need, your helpful advices are welcome :wink:

**Comment by chrisradek** [comment]
@clakech 
You're correct, we don't currently support client-side encryption in the JS SDK.

I'm not sure I understand your example. The sample you linked creates a signed url on the server, then the front-end uploads the file using that url. `s3.upload` is never called.

If your use case is to send the file from the client to your server without encryption, and then to S3, do you really need client-side encryption? Would server-side encryption work?

**Comment by clakech** [comment]
You are right, the sample URL was not the good one. I edited the link. 

I would like to know if we could use libraries like multer and multer-s3 to upload client side encrypted files with multipart  (https://github.com/badunk/multer-s3)

**Comment by bikeath1337** [comment]
@clakech https://github.com/TTLabs/EvaporateJS supports creating MD5 digests and a bunch of other features; is efficient; and works with node.js, plain old browsers and can also be used with Electron apps.

**Comment by jeskew** [comment]
@clakech If you're doing a multipart upload of a client-side encrypted ciphertext, S3 will treat the parts it receives as opaque byte streams and concatenate them. As far as S3 is concerned, the bytes are not altered or inspected. When you download the object, you would get back the ciphertext as it was uploaded. 

In the scenario described above, you would need to proxy the download through a server that could decrypt the ciphertext and return the plaintext to a browser. Please feel free to reopen if you have any questions or concerns.
