### ISSUE TITLE
Range param not enforced when using signed url for getObject

### ISSUE THREAD

**Issue by charlieduong94** [aws/aws-sdk-js#1095]
Not sure whether or not this is the correct place to post this, but it doesn't seem like the Range param for a getObject operation works correctly.

An operation like this:
```
let params = {
    Bucket: bucket,
    Key: "this/is/a/path",
    Range: `bytes=0-3999`
};
let signedUrl = s3.getSignedUrl('getObject', params);
```
produces a url that returns the entire file, instead of the 4000 byte chunk that is specified.

The url seems to include the Range in the querystring, but it is not enforced.

**Comment by austinkelleher** [comment]
+1 seeing this issue too. cc @chrisradek

**Comment by chrisradek** [comment]
Thanks for the reports! I'll have to get in contact with someone from `S3`, as they may not honor the `Range` in the querystring.

**Comment by chrisradek** [comment]
It looks like we're generating the URL correctly, but S3 seems to be ignoring it. Please post to the S3 AWS forums if you'd like to see this functionality supported!
