### ISSUE TITLE
s3.upload never calls back

### ISSUE THREAD

**Issue by n2liquid** [aws/aws-sdk-js#1096]
- OS: Debian 8.
- Node versions: 6.3.0 and 6.2.0 (at least).
- Affected library versions: 2.5.0 and 2.2.47 (at least).
- Unaffected library versions: 2.4.13 (at least).
- Reproducible: Always.

```
$ AWS_ACCESS_KEY_ID=myKey AWS_SECRET_ACCESS_KEY=mySecret node
> const AWS=require('aws-sdk')
undefined
> AWS.config.region = 'us-west-2';
'us-west-2'
> const s3 = new AWS.S3({ params: { Bucket: 'myBucket' } });
undefined
> void s3.upload({ Key: 'test', ContentType: 'text/plain', Body: 'hello' }, console.log)
undefined
> // No matter how long I wait, console.log is never called
```

**Comment by chrisradek** [comment]
@n2liquid 
When you see this issue, it happens every time you make the call, but doesn't happen at all with version `2.4.13` of the SDK?

I tried your code with the same versions of Node and the SDK, but using Mac OSX and haven't been able to reproduce the issue. Have you seen this issue on any other machines as well? There weren't any changes made to `S3` between `2.4.13` and `2.5.0` besides a new optional flag for dualstack, can you try version `2.4.14` as well?

Does an S3 object get created for you despite the callback never getting called?

**Comment by n2liquid** [comment]
Hi, Chris. On my home computer (Debian 9) the behavior was as I explained (you got it right). On my office computer (Debian 8), I just found out that 2.5.0 is working fine, and the problem was a proxy configuration. I was able to get it working using [proxychains](http://proxychains.sourceforge.net/).

I will retest this on my home computer later tonight because it's making no sense. My home network is not behind a proxy.

I see [here](https://blogs.aws.amazon.com/javascript/post/Tx3CV0OSVN2TBPS/Using-the-AWS-SDK-for-JavaScript-from-Behind-a-Proxy) what looks like an official way of getting aws-sdk-js to work behind a proxy.

That said, it's weird that `s3.upload` never times out, so maybe that's the real bug here:

```
> const AWS=require('aws-sdk')
> AWS.config.region = 'us-west-2';
> const s3 = new AWS.S3({params: {Bucket: 'myBucket'}});
> void s3.upload({ Key: 'test', ContentType: 'text/plain', Body: 'hello' }, console.log)
> console.time()
> console.timeEnd()
undefined: 247350.091ms
```

Should I create a separate issue for that?

**Comment by chrisradek** [comment]
@n2liquid 
Sorry, I meant, if you look in your S3 bucket, was the object created?

Are you still having issues on your home network? If so, can you successfully connect to any other services, or call any other operations on S3?

**Comment by Cactucs** [comment]
I'm having same/similar issue. I'm uploading a bunch of files (~350 files) to S3 bucket. I call putObject for all of them at once and than wait until the callback calls back. Sometimes it happens stright away. But sometimes I have to wait some time until something happends. Then after some time some files (cca. 20 to 50) are uploaded to bucket and their callback is called. This happends several times until all whole upload is compeleted.

**Comment by chrisradek** [comment]
Closing old issues. If you're still encountering this issue, please open a new issue and reference this one.
