### ISSUE TITLE
XMLParser Error, message: "Invalid character in entity name"

### ISSUE THREAD

**Issue by crawfobw** [aws/aws-sdk-js#1098]
I was getting a really weird error when trying to use SNS Topic. This started happening all of a sudden while I was working on a project today where code that had worked with SNS Topic suddenly started throwing these errors. I tried checking out previous commits I had made that I knew work and each one threw this error. I ended up resolving the problem by reinstalling the amazon-sdk node module. I know that I did not somehow screw up the node module as other contributors on the same project were receiving the same error and we install node modules from the project's package.json file. I'm not sure what the underlying issue is but I'm hoping that it can be fixed so deployed services don't need to be stopped in order to reinstall the node module in the case that this happens again.

Full Error message below:

{ [XMLParserError: Invalid character in entity name
Line: 216
Column: 326
Char:  ]
  message: 'Invalid character in entity name\nLine: 216\nColumn: 326\nChar:  ',
  code: 'XMLParserError',
  retryable: true,
  time: Wed Aug 17 2016 16:18:10 GMT-0400 (EDT),
  statusCode: 407 } 'XMLParserError: Invalid character in entity name\nLine: 216\nColumn: 326\nChar:  \n    at error ({projectpath}/node_modules/aws-sdk/node_modules/sax/lib/sax.js:666:10)\n    at strictFail ({projectpath}/node_modules/aws-sdk/node_modules/sax/lib/sax.js:692:7)\n    at Object.write ({projectpath}/node_modules/aws-sdk/node_modules/sax/lib/sax.js:1499:13)\n    at Parser.exports.Parser.Parser.parseString ({projectpath}/node_modules/aws-sdk/node_modules/xml2js/lib/xml2js.js:502:31)\n    at Parser.parseString ({projectpath}/node_modules/aws-sdk/node_modules/xml2js/lib/xml2js.js:7:59)\n    at NodeXmlParser.parse ({projectpath}/node_modules/aws-sdk/lib/xml/node_parser.js:30:10)\n    at Request.extractError ({projectpath}/node_modules/aws-sdk/lib/protocol/query.js:33:33)\n    at Request.callListeners ({projectpath}/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit ({projectpath}/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit ({projectpath}/node_modules/aws-sdk/lib/request.js:661:14)'

**Comment by crawfobw** [comment]
The aws-sdk version that I got the error with was version 2.4.10. Calling the SNS publish() function generated this error.

Reinstalling this version also corrected the error however. 

Unfortunately I do not believe I can reproduce the error and log the http response body as I did not keep the aws-sdk node module in version control. I wish I could help here! I'll be sure to log the response should the error occur again.

**Comment by crawfobw** [comment]
We recently reproduced the error and discovered that it is most like a proxy issue. I will follow up if something changes.

**Comment by jarjis** [comment]
@crawfobw i'm seeing the same issue with ec2 calls  but not with s3 calls. I'm using 
```
AWS.config.update({
    httpOptions: { agent: proxy('http://proxyserver') }
}); 

```
Can you please share how did you resolve it.

**Comment by crawfobw** [comment]
When we encountered this error, we determined that it was caused by the proxy returning an html page describing a proxy error.

We ended up solving the issue by including proxy credentials in the proxy url e.g proxy('http://{username}:{password}@proxyserver')

This may or may not solve your issue, it really is more dependent on how the proxy you are using is configured if your error has the same root cause.

**Comment by shirbr510** [comment]
I know that this is an ancient issue but I'm currently experiencing this when trying to work with a 3rd party mock server of s3.
my aws-sdk version is 2.288.0.
it seems like  `this.response.httpResponse.body.toString()` doesn't produce the xml and I'm trying to understand what is wrong with my request.

**Comment by GabiAcea** [comment]
I got the same issue with an xml containing an '&': Example <exampleTag>Exam&ple value</exampleTag> I removed the '&' and all works well.
