### ISSUE TITLE
ExpiredToken using the link generated by getSignedUrl 

### ISSUE THREAD

**Issue by sandyleo26** [aws/aws-sdk-js#1099]
Hi,
I get the following error when trying to download a file on S3 with the link generated by `getSignedUrl`. It works when the link is just generated but fails after 1 day. The `Expires` I pass to this function is `(60 * 60 * 24 * 90)`.

    <Error>
    <Code>ExpiredToken</Code>
    <Message>The provided token has expired.</Message>

I tried the workaround in #685 to use the `s3` signature but not working. According to [this](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html) the default signature is V4 now. So does it mean longer-than-7-day expiration time for signed url is not possible? The aws-sdk-js document is not very clear about this. Thanks.

**Comment by chrisradek** [comment]
@sandyleo26 
The default signing for S3 was changed back to using `v2` by default in `2.4.12`, but the change to `v4` by default did not pertain to signed urls. However, some regions only support `v4`, so if you're creating URLs in one of those regions, then you won't be able to exceed the 7 day expiration.

Can you share what region your bucket is in?

**Comment by sandyleo26** [comment]
@chrisradek thanks for the quick reply. my bucket is in Sydney which is ap-southeast-2, which I think use `v4`.

**Comment by chrisradek** [comment]
Actually, `ap-southeast-2` does support `v2` as well:
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

Are you sure it lasts for a full day? Can you check if it only works for 15 minutes?

Just to verify, what version of the SDK are you using?

**Comment by sandyleo26** [comment]
I used the default sdk on lambda which I think is `2.4.9`. I'm not sure it lasts a full day but it's surely more than 15min and less than 1.5 days. So are you saying using `v2` could workaround this? I only tried `s3` and none (which is `v4` I think).

**Comment by chrisradek** [comment]
`v2` and `s3` can be considered the same for our purposes, I just meant that your region didn't have to use `v4`. Are you using node.js 4.3.x in Lambda?

Can you share what the value for `Expires` is in your URL? If its set for a date in the future, this might be something to bring up with `S3`. Is this a new issue?

I also created a url with a 90 day expiration, and I can test again tomorrow to see if it still works.

**Comment by sandyleo26** [comment]
It is `&Expires=1479166229`. Yes, I'm using nodejs 4.3 in lambda. I used it a month ago but didn't find it until recently. Let me know if you need more info. Thanks.

**Comment by seriousben** [comment]
We've seen the same issue on `us-east`.

**Comment by chrisradek** [comment]
Thanks for the reports. This is looking like it's an issue on S3's side. Do you mind posting on the AWS forums to S3?

If my url stops working, I can also send that info to S3, but it looks like the SDK is creating the url properly, and S3 isn't honoring the expiration past a certain amount of time.

**Comment by RichardSilveira** [comment]
Why only one week? This value should depends on busines rules of each application...

**Comment by wuseal** [comment]
The same, Creat url with expiration with 7 days, and expired about one hour later when using v2 sign.

**Comment by wuseal** [comment]
@chrisradek Hi, I have just test, The valid period is about 15 minutes, And what the 15-minute meaning?
