### ISSUE TITLE
SharedIniFileCredentials in CredentialProviderChain not works with specified profile name

### ISSUE THREAD

**Issue by pahud** [aws/aws-sdk-js#1103]
Hello,

The following code does not work when I specify my profile other than **'default'**.  Actually it will always use the default profile.

```
'use strict';
var AWS = require('aws-sdk');

var chain = new AWS.CredentialProviderChain();
var credentials, aws_region;

AWS.CredentialProviderChain.defaultProviders = [
  function () { return new AWS.SharedIniFileCredentials({profile: 'pahud'}); }
];


chain.resolve((err, cred)=>{
	AWS.config.credentials = credentials = cred;
	var sts = new AWS.STS()
	sts.getCallerIdentity(function(err, data) {
		console.log(data)
	})
});
```

However, if I specify the following env variable in the beginning then it works.

**process.env['AWS_PROFILE'] = 'pahud'**

Did I miss anything?

Pahud

**Comment by LiuJoyceC** [comment]
Hi @pahud 
Thanks for your question. At the time when you construct `chain`, the `AWS.CredentialProviderChain.defaultProviders` array is copied and stored at `chain.providers`. When you modify `AWS.CredentialProviderChain.defaultProviders`, previously constructed instances of the `CredentialProviderChain` will keep the same `providers` array that they had at the time they were constructed. Modifying `AWS.CredentialProviderChain.defaultProviders` will only affect new instances going forward. To make your code above work, you would simply need to move the line where you construct `chain` below the line where you change `defaultProviders`. Let me know if that resolves the problem!

**Comment by pahud** [comment]
Hi @LiuJoyceC 

It works!  Thank you so much !
