### ISSUE TITLE
Missing API Gateway Usage Plans for Lambda 

### ISSUE THREAD

**Issue by alexandrepage** [aws/aws-sdk-js#1104]
Hi, I've noticed that the aws-sdk use for the Lambda function doesn't include the latest changes about the API Gateway Usage Plans. 
Example: 
```javascript
var AWS = require('aws-sdk'); 
var apigateway = new AWS.APIGateway();

exports.handler = function(event, context) {
    apigateway.getUsage({
    	endDate: "2016-08-13",
    	startDate: "2016-08-13",
    	usagePlanId: "PLAN_ID", 
    	keyId: "SOME_API_KEY",
    }, function (err, data) {
    	context.done(err, data);
    })
};
```

This example works outside the Lambda runtime but gives this error when run inside Lambda: 
```
TypeError: apigateway.getUsage is not a function
    at exports.handler (/var/task/index.js:5:16)
```

Event thought your SDK documentation says otherwise: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#getUsage-property

By the way, I'm a huge fan of API Gateway and Lambda. Great work :)

**Comment by chrisradek** [comment]
@alexandrepage 
The version of the SDK that is included with Lambda lags behind our releases a bit. You can see the version in Lambda here:
http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

They are currently on `2.4.9`, and API Gateway usage plans were added in [`2.5.1`](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md)

Please feel free to post to the AWS forums for Lambda to update to at least `2.5.1`. If you don't want to wait, you can also bundle your own version of the SDK up to Lambda:
https://github.com/aws/aws-sdk-js/issues/765#issuecomment-152033324
