### ISSUE TITLE
ssm describeDocumentPermission TypeError

### ISSUE THREAD

**Issue by riteshatsencha** [aws/aws-sdk-js#1106]
Hello,

Making an api call to ssm. describeDocumentPermission throws an error. 

Params : {Name : 'TestDocument', PermissionType: 'Share'}

TypeError: ssm.describeDocumentPermission is not a function.  

Am I missing something? or a bug?

**Comment by LiuJoyceC** [comment]
Hi @riteshatsencha 
What version of the AWS SDK are you using? The latest version should have this function. Are you still seeing this problem after you update the version?

**Comment by LiuJoyceC** [comment]
The earliest version which has this function is `2.3.11`, released on May 12.

**Comment by riteshatsencha** [comment]
Updating the SDK has resolved the issue. Thank you!
