### ISSUE TITLE
ssm describeDocument missing Owner, Hash, HashType

### ISSUE THREAD

**Issue by riteshatsencha** [aws/aws-sdk-js#1107]
Hello,

Seems like, describeDocument response is missing Owner for (public, self) documents. Additionally, "self" documents are missing Hash and HashType in a de-serialized data. Below is the response. 

```json
{
	"status": "success",
	"data": {
		"Document": {
			"Name": "TestDocument",
			"CreatedDate": "2016-08-22T21:51:04.874Z",
			"Status": "Active",
			"Description": "Check ip configuration of a Linux instance.",
			"Parameters": [],
			"PlatformTypes": [
				"Linux"
			]
		}
	}
}
```
Making same call for AWS documents it returns Hash, HashType but still missing Owner property. Please see below.

```json

{
	"status": "success",
	"data": {
		"Document": {
			"Sha1": "fd3de0c08a718005d1a4990df860e138a6fa2eac",
			"Name": "AWS-ConfigureCloudWatch",
			"CreatedDate": "2015-10-13T16:04:06.475Z",
			"Status": "Active",
			"Description": "Export metrics and log files from your instances to Amazon CloudWatch.",
			"Parameters": [{
				"Name": "status",
				"Type": "String",
				"Description": "(Optional) Enable or disable CloudWatch. Valid values: Enabled | Disabled",
				"DefaultValue": "\"Enabled\""
			}, {
				"Name": "properties",
				"Type": "String",
				"Description": "(Optional) The configuration for CloudWatch in JSON format. Learn more at http://docs.aws.amazon.com/ssm/latest/APIReference/aws-cloudWatch.html",
				"DefaultValue": "\"\""
			}],
			"PlatformTypes": [
				"Windows"
			]
		}
	}
}
```

Any thoughts?

Thank you,

Ritesh

**Comment by LiuJoyceC** [comment]
Hi @riteshatsencha 

This is a service-side issue, as the SDK has no control over the response sent back from the service. Please post this question on the AWS Forums to engage the service team: https://forums.aws.amazon.com/category.jspa?categoryID=3
Thanks!

**Comment by LiuJoyceC** [comment]
Hi @riteshatsencha 
Actually, can you tell us what version of the AWS SDK you are using? This may actually be an issue with your version of the SDK being outdated. For example, the `Owner` property in the response was not added to the API model until version `2.3.11`, so if your SDK version is older than that, you will not see the `Owner` property in the response. Try updating to the latest version, and if you are still missing properties in the response, then feel free to post on the AWS Forum. Thanks!

**Comment by riteshatsencha** [comment]
Updating the SDK has resolved this issue.
