### ISSUE TITLE
Run Command: listCommands is missing NotificationConfig

### ISSUE THREAD

**Issue by riteshatsencha** [aws/aws-sdk-js#1108]
Hello,

Making an api call to "ssm.listCommands" is not displaying NotificationConfig. Yes, SNS is configured and I can see the "Notification role, event, topic and type" through EC2 console for a given run command. Api de-serialized data should display the same as per the api docs, but not the case. Please see below.

```json
{
			"CommandId": "13815cba-249f-45c3-a677-f3de73c8f5ee",
			"DocumentName": "AWS-RunShellScript",
			"Comment": "One more attempt to run the command with SNS.",
			"ExpiresAfter": "2016-08-19T15:35:33.828Z",
			"Parameters": {
				"commands": [
					"ls -all"
				],
				"executionTimeout": [
					"3600"
				],
				"workingDirectory": [
					"/"
				]
			},
			"InstanceIds": [
				"i-5e752083"
			],
			"RequestedDateTime": "2016-08-19T15:25:33.828Z",
			"Status": "Success",
			"OutputS3BucketName": "rp-run-command-output",
			"OutputS3KeyPrefix": "output"
		}
```

<img width="1207" alt="notification-config" src="https://cloud.githubusercontent.com/assets/14277904/17873695/0be65640-6895-11e6-81aa-caa8887a7606.png">

**Comment by LiuJoyceC** [comment]
Hi @riteshatsencha 

Could you post this question on the AWS Forum, as it is a service-side issue rather than an issue with the AWS SDK. The SDK does not have control over the response sent by the service.
https://forums.aws.amazon.com/category.jspa?categoryID=3
Thanks!

**Comment by LiuJoyceC** [comment]
Hi @riteshatsencha 

This may actually be due to an outdated SDK version. Try updating to the latest version of the SDK, and if you are still missing properties from the response after that, then feel free to post in the AWS Forum. Thanks!

**Comment by riteshatsencha** [comment]
Updating the SDK version has resolved the issue. Thx.
