### ISSUE TITLE
Mechanical Turk

### ISSUE THREAD

**Issue by mcfedr** [aws/aws-sdk-js#111]
Are there any plans to support the mechanical turk api? Or would you be open to pull requests with such support?

**Comment by jeskew** [comment]
The Mechanical Turk Requester Service (available as [`AWS.MTurk`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/MTurk.html)) is supported in the AWS SDK for JavaScript as of version 2.22.0.
