### ISSUE TITLE
What is the correct way to over-write retry delay?

### ISSUE THREAD

**Issue by xiao** [aws/aws-sdk-js#1110]
In `lib/request.js`, it says:

``` javascript
/*
 *   If the response is retryable, the listener should set the
 *   `response.error.retryable` property to `true`, and optionally set
 *   `response.error.retryCount` to the millisecond delay for the next attempt.
 * ...
 */
```

and provides the following example:

``` javascript
/**
 *   @example Adding a custom retry for a 404 response
 *     request.on('retry', function(response) {
 *       // this resource is not yet available, wait 10 seconds to get it again
 *       if (response.httpResponse.statusCode === 404 && response.error) {
 *         response.error.retryable = true;   // retry this error
 *         response.error.retryCount = 10000; // wait 10 seconds
 *       }
 *     });
 */
```

It doesn't seem right to use `error.retryCount` to over-write the delay for retries. Should we use `error.retryDelay` instead?

**Comment by chrisradek** [comment]
@xiao 
You are correct, the docs should say to over-write `error.retryDelay` instead.
You can over-write `error.retryCount` as well, but that will affect how many more times to retry this request. Once `retryCount` equals the [`maxRetries`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#maxRetries-property) (default of 3 for anything besides DynamoDB), the request won't automatically retry anymore.

We'll have to update our docs.

**Comment by xiao** [comment]
Thanks, @chrisradek. Very helpful!

I will leave this issue open in case you want to track the doc change.
