### ISSUE TITLE
EC2MetadataCredentials.refresh does not return a promise

### ISSUE THREAD

**Issue by oliversalzburg** [aws/aws-sdk-js#1121]
[`EC2MetadataCredentials.refresh`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2MetadataCredentials.html#refresh-property) can not be converted to a promise, it returns `undefined` instead of something I could call `.promise()` on.

**Comment by LiuJoyceC** [comment]
@oliversalzburg 
Currently, `.promise()` can only be called on instances of the `AWS.Request` class, which is what is returned from most service operation calls. We can mark this as a feature request.

Are you calling `.refresh()` directly? It's recommended to call `.get()` instead on credential providers so that new credentials are only retrieved if the current ones are expired. The `.get()` doesn't return a `Request` instance that can be promisified either, I just wanted to see your use case for calling `.refresh()` directly.

**Comment by oliversalzburg** [comment]
Hi @LiuJoyceC, yeah, after posting this, I read about the `get` vs. `refresh` in the documentation.

My use case is (or, let's say *was*) a bit complicated. Let me elaborate. We abstract all AWS interaction in our stack into a common npm module. In that modules, I used a check for `AWS.config.credentials` to see if proper credentials were provided, otherwise requests would not be forwarded to the SDK.

I realized that this is an issue, because it doesn't take into account that the module could be used on EC2, with an IAM role supplying the credentials (asynchronously). This would cause the module to misbehave.

So I decided to manually attach `EC2MetaDataCredentials` to `AWS.config.credentials` and call `refresh()` on them to make sure I had that path covered as well. So I think using `refresh()` in that case was legit (because it happened before any other requests were attempted).

However, all of this was counter-productive as we had to introduce asynchronicity into the construction of our AWS SDK wrapper, which was not desirable, so we dropped the whole aspect and now only issue a warning/analysis after failed requests.

Back to the initial request though. I have now encountered a few methods in the SDK, which *feel* like they should return promises, but don't. This is unfortunate, because you end up messing with callbacks again or writing your own promise wrappers all over the place. A generic approach would be very welcome :)

**Comment by LiuJoyceC** [comment]
Hi @oliversalzburg 

I agree it would provide a more consistent and easier experience if all asynchronous functions that take a callback also had a promise interface without users having to write promise wrappers. I've marked this as a feature request.
