### ISSUE TITLE
ec2 describeInstances silently fails when globalAgent is disabled

### ISSUE THREAD

**Issue by emptyemail** [aws/aws-sdk-js#1122]
The following code silently fails with no explanation. This happens on every version I've tried including 2.5.5

```
require('https').globalAgent = false;

aws = require('aws-sdk');
ec2 = new aws.EC2({region: 'us-east-1'});
ec2.describeInstances({}, console.log);
```

**Comment by chrisradek** [comment]
@emptyemail 
Thanks for reporting this issue! I've submitted PR #1130 to fix this.
