### ISSUE TITLE
Requiring the SDK now loads all services into memory

### ISSUE THREAD

**Issue by lsegal** [aws/aws-sdk-js#1124]
It looks like changes to the API loader in 2.6.0 now cause `require('aws-sdk')` to load all service definitions into memory, including definitions for previous (typically unused) service versions, which increases the memory footprint of an app by roughly 20+MB (on my machine):

```js
console.log('mem before', process.memoryUsage());
var AWS = require('aws-sdk');
console.log('mem after', process.memoryUsage());

// all services are loaded into API loader:
var l = require('aws-sdk/lib/api_loader');
var e = l.services.ec2;
if (e) {
  var numOps = Object.keys(e[Object.keys(e)[0]].operations).length;
  console.log('EC2 Operations', numOps);
} else {
  console.log('EC2 not yet loaded');
}
```

In `aws-sdk@2.5.x`:

```
mem before { rss: 19165184, heapTotal: 10481664, heapUsed: 4117368 }
mem after { rss: 29241344, heapTotal: 18870272, heapUsed: 9707864 }
EC2 not yet loaded
```

In `aws-sdk@2.6.0`:

```
mem before { rss: 19111936, heapTotal: 10481664, heapUsed: 4116632 }
mem after { rss: 42848256, heapTotal: 34598912, heapUsed: 16902912 }
EC2 Operations 210
```

Note the almost doubling of memory usage from previous releases.

Load time is also significantly increased:

```
$ time node -e 'a=require("aws-sdk");console.log(a.VERSION)'
2.5.6

real	0m0.208s
user	0m0.174s
sys	0m0.034s

$ time node -e 'a=require("aws-sdk");console.log(a.VERSION)'
2.6.0

real	0m0.300s
user	0m0.260s
sys	0m0.047s
```

This represents a startup time increase of over 50%.

**Comment by chrisradek** [comment]
Thanks for reporting this issue @lsegal 
I'm currently working on a solution for this, I'll keep this thread updated.

**Comment by chrisradek** [comment]
@lsegal I've submitted #1125 to fix this issue. 
Repeating the test with your script with these changes lowers memory consumption below what it was prior to `2.6.0`:
```
mem before { rss: 21164032, heapTotal: 10481664, heapUsed: 3961344 }
mem after { rss: 29724672, heapTotal: 13627392, heapUsed: 8686336 }
EC2 not yet loaded
```

Thank you very much for reporting this issue.

**Comment by AdityaManohar** [comment]
@chrisradek 

Given the performance implications of `v2.6.0`, it would be nice if you could mark `v2.6.0` as deprecated on npm, so that `v2.6.0` is not actively used.

**Comment by chrisradek** [comment]
@AdityaManohar 
Done, `v2.6.0` is now marked as deprecated.
