### ISSUE TITLE
Can I delete a temporary credentials got from Cognito?

### ISSUE THREAD

**Issue by tktk8924** [aws/aws-sdk-js#1131]
I'm developing a single page application using Cognito UserPool and Identity.
I'm having trouble with temporary credentials.

My problem occurs when I follow the procedures below.
1. Log in to the application on device1
2. Device1 gets a temporary credentials
3. Reset password on device2
4. Device1 can continue to call APIs using the credentials for 1hour

I have to delete the credentials issued at 2 to avoid 4.
Can I delete the credentials?
Or any other good ideas?

**Comment by chrisradek** [comment]
Hey @tktk8924 
This would be a better question to ask the Cognito service team since it is a question about how to use their service. Feel free to reach out to them on the forums: https://forums.aws.amazon.com/forum.jspa?forumID=173
