### ISSUE TITLE
Loopback integration

### ISSUE THREAD

**Issue by pbrain19** [aws/aws-sdk-js#1132]
I can't seem to find a reliable loopback or integration. Can you point to the right way?

**Comment by chrisradek** [comment]
@pbrain19 
I'm not sure what you mean by a reliable loopback or integration. Can you explain what you're trying to accomplish?

**Comment by pbrain19** [comment]
Many of my clients want to use loopback orm to connect to the db...
Loopback doesn't officially support dynamodb. And the connectors found
online are not working as they should. Do you guys have any  plans to
create your own juggler/ connector so that people can use dynamodb with
loopback...
