### ISSUE TITLE
target._set is not a function(…)

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [aws/aws-sdk-js#1133]
Hi, I am trying to upload base64 image to amazon using "aws-sdk" module, I am getting error as "target._set is not a function(…)". I am not able find out where I am doing wrong.

Please help me to resolve it.

Here is my code:

```
import 'aws-sdk/dist/aws-sdk';
const AWS = window.AWS;

var configData = {
    "accessKeyId": "******",
    "secretAccessKey": "********",
    "region":"*****"
}

AWS.config.update(configData);

var buf = new Buffer(this.state.pic.replace(/^data:image\/\w+;base64,/, ""),'base64');
var s3Bucket = new AWS.S3( { params: {Bucket: '****'} } );

var data = {
    Key: 'myImage.jpg',
    Body: buf,
    ContentEncoding: 'base64',
    ContentType: 'image/jpeg'
};

s3Bucket.putObject(data, function(err, data){
    if (err) {
      console.log(err);
      console.log('Error uploading data: ', data);
    } else {
      console.log('successfully uploaded the image!');
    //  console.log(profilePic);
      this.updateUser(profilePic, e);
    }
});

```

**Comment by chrisradek** [comment]
@HarshaVardhanPVK 
Can you provide the follow info?
- What version of the SDK you're using.
- If you're running inside a browser or node.js
- The stack trace/full error
- When do you see the error? (For example, in the `putObject` callback, when creating a buffer, etc)

When looking at the current version of the browser SDK, we're not attempting to call `target._set` anywhere in the code, nor are our dependencies, so we would need more information.

**Comment by HarshaVardhanPVK** [comment]
@chrisradek
Thank you for your response.

I got that error while using "2.3.7" aws-sdk version, I am running it in browser (react) only.

Now I updated my aws-sdk module to "2.6.2" and I am getting another error as 
`"Missing credentials in config(…)"`

But am sending config data as shown above.

Got both these errors in putObject callback only.

**Comment by chrisradek** [comment]
@HarshaVardhanPVK 
Sorry for the delay. The missing credentials error you're getting is due to the way you're adding `credentials` to `config`.

You had:
```javascript
var configData = {
    "accessKeyId": "******",
    "secretAccessKey": "********",
    "region":"*****"
}
```
it should be:
```javascript
var configData = {
    credentials: {
        "accessKeyId": "******",
        "secretAccessKey": "********"
    },
    "region":"*****"
}
```
See the `General Configuration Options` in the [docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html) for more info.

**Comment by HarshaVardhanPVK** [comment]
@chrisradek
Hi, actually I did a small mistake, cause of that I got that error as "Missing credentials in config(…)". There first I created s3Bucket object then I updated configData. Now I placed them in correct order and am getting same error as "target._set is not a function(…)".


Please check this part of code:

```
if (this === target && start < targetStart && targetStart < end) {
	// descending copy from end
	for (i = len - 1; i >= 0; i--) {
		target[i + targetStart] = this[i + start]
	}
} else if (len < 1000 || !Buffer.TYPED_ARRAY_SUPPORT) {
	// ascending copy from start
	for (i = 0; i < len; i++) {
		target[i + targetStart] = this[i + start]
	}
} else {
	target._set(this.subarray(start, start + len), targetStart)
}
```

Getting that issue in this part of code...

**Comment by chrisradek** [comment]
@HarshaVardhanPVK 
Sorry for the delay, are you still having issues?

Are you using the sdk located at [`dist/aws-sdk.js`](https://raw.githubusercontent.com/aws/aws-sdk-js/v2.6.2/dist/aws-sdk.js)? When I look at the source code, there isn't a `target._set` call, instead `set` is called via the `Uint8Array.prototype`.

**Comment by chrisradek** [comment]
Closing old issue due to inactivity.
