### ISSUE TITLE
Uncaught TypeError when using keep-alive HTTP agent

### ISSUE THREAD

**Issue by cdhowie** [aws/aws-sdk-js#1137]
By simply adding this code to our application:

```
AWS.config.update({
    httpOptions: {
        agent: new http.Agent({ keepAlive: true })
    }
});
```

The following exception is thrown some time later, after numerous successful operations:

```
     Uncaught TypeError: cb is not a function
      at afterWrite (_stream_writable.js:354:3)
      at onwrite (_stream_writable.js:345:7)
      at WritableState.onwrite (_stream_writable.js:89:5)
      at Socket._writeGeneric (net.js:706:5)
      at Socket._writev (net.js:711:8)
      at doWrite (_stream_writable.js:298:12)
      at clearBuffer (_stream_writable.js:387:5)
      at Socket.Writable.uncork (_stream_writable.js:237:7)
      at ClientRequest._flushOutput (_http_outgoing.js:673:10)
      at ClientRequest.OutgoingMessage._flush (_http_outgoing.js:647:16)
      at _http_client.js:156:10
      at callSocketMethod (_http_client.js:552:7)
      at ClientRequest.onSocket (_http_client.js:557:7)
      at tickOnSocket (_http_client.js:523:7)
      at onSocketNT (_http_client.js:535:5)
```

Changing `keepAlive` to `false` eliminates the errors.

Node 4.5.0 and aws-sdk 2.6.2.

**Comment by chrisradek** [comment]
@cdhowie 
Are you making calls across multiple services? Do you know if it's a specific operation that always throws the exception? How long is 'some time later'?

**Comment by cdhowie** [comment]
These service tests exclusively run against DynamoDB.  At the point where it fails, there are multiple concurrent requests and they are all DeleteItem requests.  It will consistently fail on that test, and I haven't been able to locate any bug in my code (yet).

**Comment by cdhowie** [comment]
My spidey sense says this is actually a bug in Node's `http.Agent` class, but I'm not super-familiar with Node's internals so I'm not well-equipped to go about debugging them to make sure.  So I'm not sure if I should leave this issue open or go report it to Node. :/

The first stack frame shown is this Node-internal code:

```
function afterWrite(stream, state, finished, cb) {
  if (!finished)
    onwriteDrain(stream, state);
  state.pendingcb--;
  cb();
  finishMaybe(stream, state);
}
```

The `cb()` invocation is what's failing.  This parameter gets set earlier from `state.writecb`, which, according to the comments in that file, are supplied when invoking `write()` on the stream.  Apparently the callback is required, at least in Node v4?  That doesn't match the docs, but it wouldn't be the first time the docs are wrong.

**Comment by cdhowie** [comment]
I am seeing the same behavior on Node 6.6.0 using the stock `http.Agent` with `keepAlive: true`.

**Comment by chrisradek** [comment]
Closing old issues. Please open a new issue if you are still encountering this behavior.
