### ISSUE TITLE
Possible breaking change about service configuration

### ISSUE THREAD

**Issue by awerlang** [aws/aws-sdk-js#1139]
This used to work until 2.5.6:

```js
AWS.config.update({dynamodb: {endpoint: '...'}});
```

With 2.6.2, this change was required:

```js
AWS.config.update({dynamodb: {endpoint: '...'}}, /* allowUnknownKeys */ true);
```

Was this intended? It doesn't figure on CHANGELOG.

**Comment by chrisradek** [comment]
@awerlang 
Do you mean it first broke in `2.5.6`? And it's fixed by setting `allowUnknownKeys` to `true` in the latest version?

**Comment by chrisradek** [comment]
@awerlang 
Nevermind, I'm able to reproduce the issue you're seeing. Marking as a bug.
