### ISSUE TITLE
ECSCredentialsProviderFailure With ECS IAM Roles

### ISSUE THREAD

**Issue by jamesongithub** [aws/aws-sdk-js#1142]
Followed the instructions here: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

Version "aws-sdk": "2.5.3"

```
2016-09-16T02:03:15.561Z - error: {
  "message": "Missing credentials in config",
  "code": "CredentialsError",
  "time": "2016-09-16T02:03:15.555Z",
  "originalError": {
    "message": "Could not load credentials from any providers",
    "code": "CredentialsError",
    "time": "2016-09-16T02:03:15.555Z",
    "originalError": {
      "message": "Response data is not in valid format",
      "code": "ECSCredentialsProviderFailure",
      "time": "2016-09-16T02:03:15.555Z"
    }
  }
}
```

```
curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
{"RoleArn":"arn:aws:iam::REDACTED:role/REDACTED","AccessKeyId":"REDACTED","SecretAccessKey":"REDACTED","Expiration":"2016-09-16T08:05:02Z"}
```

Are we missing additional configuration?

**Comment by LiuJoyceC** [comment]
Hi @jamesongithub 
It looks like the data returned from the request is missing a "Token" property, which is required by the ECS credentials provider. The documentation you linked to shows "Token" as a field that should be returned in the payload. If you have questions on why the "Token" field is missing from the payload, please post on the AWS Forum for the ECS service: https://forums.aws.amazon.com/forum.jspa?forumID=187

**Comment by jamesongithub** [comment]
thanks @LiuJoyceC
