### ISSUE TITLE
Passing an invalid key name to s3.getObject() with error handler causes node app to crash

### ISSUE THREAD

**Issue by jamorales-bsft** [aws/aws-sdk-js#1145]
If an invalid key is passed to s3.getObject() with an error handler attached an uncatchable error is thrown after the error handler is fired. 

    params = {Bucket: "bucket",  Key: badkey}

	s3Request = s3.getObject(params)

	s3Request.on("success", successCB)
	s3Request.on("error", errorCB)

	var s = s3Request.createReadStream().pipe(res)

	function successCB (response) {
		$.log("downloading file")
	}

	function errorCB (error, response) {
		$.log(Got error: ${error.message})	
	}

```
Got error: The specified key does not exist.
aws-sdk/lib/request.js:31
            throw err;
            ^

NoSuchKey: The specified key does not exist.
    at Request.extractError (aws-sdk/lib/services/s3.js:538:35)
```

**Comment by chrisradek** [comment]
@jamorales-bsft 
You'll need to attach the error handler to the stream returned by `createReadStream()`. The stream itself will emit an error event.

**Comment by jamorales-bsft** [comment]
works thanks. It would be nice if that was in the docs somewhere as a gotcha.
