### ISSUE TITLE
SES: The address does not align with the given ARN error when using labelled email address

### ISSUE THREAD

**Issue by mjmasn** [aws/aws-sdk-js#1146]
When sending an email using a verified email ARN (as opposed to a domain ARN) I get the error:
```
The address 'Example support <support.dev@example.com>' does not align with the given ARN 'arn:aws:ses:eu-west-1:XXX:identity/support.dev@example.com'
```

If I change the source from `Example support <support.dev@example.com>` to `support.dev@example.com`, or don't change the source but send via a domain ARN e.g. `arn:aws:ses:eu-west-1:XXX:identity/example.com` it works fine. However, I need to use the verified email address ARN because I want delivery notifications to go to a different place in dev mode.

Essentially the issue is that it's not possible to label an email address when sending from a verified email ARN.

**Comment by LiuJoyceC** [comment]
Hi @mjmasn 
This is a service-side issue and not an issue with the SDK. Please post your question on the AWS Forums for SES: https://forums.aws.amazon.com/forum.jspa?forumID=90
Thanks!
