### ISSUE TITLE
AWS S3 upload failed: TypeError: punycode.toASCII is not a function

### ISSUE THREAD

**Issue by MaxVita** [aws/aws-sdk-js#1148]
Hi, 

i got an "old" error in the 2.6.3 sdk version if i try to upload something in our requirejs environment. 

Please see [https://github.com/aws/aws-sdk-js/issues/999](https://github.com/aws/aws-sdk-js/issues/999)

Thank you.

**Comment by LiuJoyceC** [comment]
Hi @MaxVita 
So according to the other issue, version 2.5.6 works, but you start getting this error in 2.6.0 and above? Or does it only start failing with 2.6.3? The version of browserify that the SDK uses was updated in 2.6.0. I'll investigate to see why it's causing this error. Thanks.

**Comment by MaxVita** [comment]
Hey @LiuJoyceC 

2.5.6 works well and all versions >2.5.6  (2.6.0 and above) will fail with "TypeError: punycode.toASCII is not a function".
