### ISSUE TITLE
Getting both response data and a read stream?

### ISSUE THREAD

**Issue by olalonde** [aws/aws-sdk-js#1153]
I would like to do something like (e.g. get both Metadata and a read stream for the body):

```javascript
      const data = await client
        .getObject(buildParams(key))
        .promise()
      console.log(data.Metadata)
      data.Body.pipe(process.stdout)
```

Is something like that possible? I know I could do `client.getObject(buildParams(key)).createReadStream()` but then I need another request to get the Metadata field.

**Comment by chrisradek** [comment]
@olalonde 
You would need to attach an event listener onto the [request](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#httpHeaders-event) that gets returned when calling a service operation by the SDK. The SDK handles converting the headers received into fields on the data object, but when using streams that step is skipped. In your scenario, you would either need to make a separate 'headObject' call, or you can parse the headers manually using the below as a starting point:

```javascript
var request = client.getObject(buildParams(key));
request.on('httpHeaders', function(statusCode, headers, response) {
  // metadata gets returned as headers that start with 'x-amz-meta-'
  // write code to grab the metadata from those headers and do something with them.
  });
});
// create the read stream for the body
request.createReadStream().pipe(process.stdout);
```

**Comment by olalonde** [comment]
Thanks. I'd still like to request a feature that could make it possible for the `Body` returned by getObject be an readable stream. That would be more similar to how whatwg-fetch and most http client libraries handle this for example.

**Comment by adueck** [comment]
@olalonde and @chrisradek  Thanks for asking about this as I have a use case exactly like this. Do you know if there has been any feature development like you suggested? It would by nice to simply get the metadata in JSON rather than having to scrape it out from the http headers as explained [above](https://github.com/aws/aws-sdk-js/issues/1153#issuecomment-248934838).

**Comment by chrisradek** [comment]
@adueck 
The next major version of the [AWS SDK](https://github.com/aws/aws-sdk-js-v3) will set the `Body` field to a stream if the operation supports a streaming response, as is the case with s3.getObject. The next major version of the SDK is currently in developer preview and the S3 package needs to be generated, but feel free to try it out and leave feedback!
