### ISSUE TITLE
putBucketCors() errors with `ExposeHeaders` but accepts `ExposedHeaders`

### ISSUE THREAD

**Issue by donpark** [aws/aws-sdk-js#1154]
Documentation states `ExposeHeaders` should be used but results in error unless `ExposedHeaders` is used.

**Comment by LiuJoyceC** [comment]
Hi @donpark 
I was not able to reproduce this behavior. When I use `ExposeHeaders` as shown in the documentation, there is no error, but using `ExposedHeaders` causes errors. This matches with the `Access-Control-Expose-Headers` header in the CORS spec: https://www.w3.org/TR/cors/

Can you provide more information for reproducing this behavior? What version of the SDK are you using? Can you show the relevant snippet of code? What does your `CORSConfiguration` json param look like? Does the its structure match what is shown in the documentation? http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketCors-property

Thanks.

**Comment by donpark** [comment]
Funny you should ask. I just deleted the bucket I successfully set Cors using this code:

```typescript
    ensureBucketPublicCorsRule(bucket: string) {
      if (TRACE) console.log('ensureBucketPublicCors', bucket);
      // Promise complicates retry so uses callback here. 
      return new Promise((resolve, reject) => {
        this.client.getBucketCors({
          Bucket: bucket,
        }, (err, data) => {
          let rules = !err && data ? data.CORSRules : null
          if (rules && rules.filter(rule => this.isPublicCorsRule(rule)).length > 0) return resolve(rules);

          // rules either doesn't exist or is not set to public access, create or override
          let publicCorsRule = {
            AllowedHeaders: ['Authorization'],
            AllowedMethods: ['GET'],
            AllowedOrigins: ['*'],
            MaxAgeSeconds: 3000,
            ExposedHeaders: ['Content-Length', 'Content-Type'],
          }

          if (rules) {
            rules.push(publicCorsRule)
          } else {
            rules = [publicCorsRule]
          }
          this.client.putBucketCors({
            Bucket: bucket,
            CORSConfiguration: {
              CORSRules: rules,
            },
          }, (err, data) => {
            if (err) return reject(err);

            // make sure rule is set
            this.client.getBucketCors({
              Bucket: bucket,
            }, (err, data) => {
              if (err) return reject(err);
              rules = !err && data ? data.CORSRules : null
              if (rules && rules.filter(rule => this.isPublicCorsRule(rule)).length > 0) return resolve(rules);
              reject(new Error('could not add public CORS rule'))
            })
          })
        })
      })
    }
```

and reran it and it failed. But if I change `ExposedHeaders` to `ExposeHeaders`, it now runs successfully.

So either I'm hallucinating or someone fixed it at the backend sometime after I created the bucket.
Either way, this issue can be closed now.

**Comment by LiuJoyceC** [comment]
I'm glad to hear it resolved!
