### ISSUE TITLE
Non-file stream objects are not supported with SigV4

### ISSUE THREAD

**Issue by olalonde** [aws/aws-sdk-js#1157]
I'm getting this error with v2.6.3 when using the `uploadPart` API with a readable stream: `Non-file stream objects are not supported with SigV4`

I setup my client like this:

``` javascript
const client = new aws.S3({
  accessKeyId: 'AKIAIOSFODNN7EXAMPLE',
  secretAccessKey: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
  endpoint: new aws.Endpoint('http://127.0.0.1:9000'),
  s3ForcePathStyle: true,
  signatureVersion: 'v4',
  s3DisableBodySigning: true,
})
```

`putObject` works as expected, but `uploadPart` doesn't. As a workaround, this monkey patch fixes the problem:

``` javascript
client.shouldDisableBodySigning = () => true
```

I'm using [minio](https://github.com/minio/minio) for [testing my code](https://github.com/blockai/s3-tus-store/blob/master/test/index.test.js) in [Travis](https://github.com/blockai/s3-tus-store/blob/master/.travis.yml) but it isn't using https which I believe may be the [source of the problem](https://github.com/aws/aws-sdk-js/issues/965#issuecomment-228796954).

**Comment by chrisradek** [comment]
@olalonde 
`s3DisableBodySigning: true` is only meant to work when using an `https` endpoint, which is why your non-file stream isn't working with minio.

However, I would also expect `putObject` to give you the same warning. What type of streams are you passing into `putObject` and `uploadPart`?

What the SDK does in the `ManagedUploader` to handle non-file streams is read a stream into a buffer until the specified size for a part has been reached, then it can calculate the SHA256 of the buffer and send that. Does it make sense to do something similar in your case (or use the `upload` method?)

**Comment by olalonde** [comment]
Yes, I was only getting this bug using the `uploadPart` API directly which is strange. All my streams are non file streams, typically they come from an HTTP request but I use other types of streams when testing. Well, the workaround is working... But couldn't `uploadPart` also automatically buffer up before issuing the request, like `upload` does?

**Comment by kothari775** [comment]
I m also getting same issue. My snippet is 

var s3 = require('s3');
var client = s3.createClient({
  maxAsyncS3: 20,     // this is the default
  s3RetryCount: 3,    // this is the default
  s3RetryDelay: 1000, // this is the default
  multipartUploadThreshold: 20971520, // this is the default (20 MB)
  multipartUploadSize: 15728640, // this is the default (15 MB)
  s3Options: {
    accessKeyId: "myAccessKey",
    secretAccessKey: "secretKey",
    region: "regionId",
    s3ForcePathStyle: true,
    signatureVersion: 'v4'
    //s3DisableBodySigning: true
    // endpoint: 's3.yourdomain.com',
    // sslEnabled: true
  }
});
var params = {
  localDir: "some/dir",
  deleteRemoved: true, // default false, whether to remove s3 objects
                         // that have no corresponding local file.
  Body: fs.readdir('some/local/dir'),
  s3Params: {
    Bucket: 'bucketname',
    Prefix: "sample"
  }
};
var uploader = client.uploadDir(params);
uploader.on('error', function(err) {
  console.error("unable to sync:", err.stack);
});
uploader.on('progress', function() {
  console.log("progress temp : ", uploader.progressAmount, uploader.progressTotal);
});
uploader.on('end', function() {
  console.log("done uploading");
});

I tried with uploadFile that works fine

Guide me I have 2 options  1) upload whole local directory to S3 or 2) Streaming from MongoDB Gridfs and upload to AWS S3.

**Comment by chrisradek** [comment]
Amazon S3 requires knowledge of the object length in order to upload. As a work-around you can use the s3.upload method which performs a multipart upload in chunks.
