### ISSUE TITLE
Question - Equivalent of sync

### ISSUE THREAD

**Issue by ranode** [aws/aws-sdk-js#1159]
How can I use this sdk for syncing a foder to S3? I find sync with aws-cli http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html, but is there an equivalent with the sdk?

**Comment by LiuJoyceC** [comment]
Hi @ranode 
There is currently not an equivalent operation in the AWS SDK for JavaScript, but I will mark this as a feature request. Thanks!

**Comment by Anonyfox** [comment]
We would also LOVE to have this feature!

**Comment by ZY-Ang** [comment]
+1 for this feature. Need this to integrate a DevOps workflow for my web applications

**Comment by tenoriojuann** [comment]
+1 Would like to be able to use the `sync` feature without the cli.

**Comment by kellertk** [comment]
Thank you for this feature request, but we have no plans to implement a sync client in the JS SDK at this time.
