### ISSUE TITLE
Performance issue with SQS with sslEnabled: true

### ISSUE THREAD

**Issue by runvnc** [aws/aws-sdk-js#116]
Hello.  I'm running into an issue with SQS taking quite a long time on my system when using sslEnabled: true.  It seems like at least the createQueue calls are slow and also possibly the sendMessage. Here are some lines from my log.

with sslEnabled: false

```
Queue constructor returned for manager-runvnc-Rev-1-0 in 405 ms.
Queue constructor returned for testappmgr in 367 ms.
Request returned in 839 ms. Sending response to server..
Request returned in 1038 ms. Sending response to server..
```

with sslEnabled: true

```
Queue constructor returned for testappmgr in 12148 ms.
Request returned in 9527 ms. Sending response to server..
Request returned in 9524 ms. Sending response to server.
```

So those logs are measuring the time it takes for createQueue and also sendMessage.  

First question I have, and I apologize if this is a bit ignorant, but I would like to just leave sslEnabled: false, but I'm not sure if that would be a security problem.  If I have most of my code running on EC2, by any chance is there some aspect of Amazon's VM configuration that would mean that my HTTP messages for AWS API requests would be private, even if they weren't encrypted with SSL (doubt it, just thought I would ask).

Second question, is there something about my configuration (or code) that I can change/fix to get better performance from SQS with sslEnabled: true?  (Maybe something to do with OpenSSL or something?)

Third question, is this perhaps a bug, or is there maybe a way that the AWS SDK for Node implementation could be improved to provide better performance with sslEnabled: true?

Thanks so much for your help.

**Comment by dsjoerg** [comment]
Just got bit by this myself
