### ISSUE TITLE
Unable to Create Bucket from browser using aws sdk

### ISSUE THREAD

**Issue by zymr-keshav** [aws/aws-sdk-js#1160]
I am trying to create bucket from the browser using aws sdk 2.4.8  but gives 403 error. 

Kindly guide me whether we can create Bucket from browser (using javascript) using[ createBucket ](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createBucket-property) method

below is my code

```
createBucket: function() {
                  var params = {
                      Bucket: 'alpha',
                      ACL: 'public-read-write',
                      CreateBucketConfiguration: {
                        LocationConstraint: 'us-west-1'
                      },
                      GrantRead: 'id="b3xxxxxxxxxxxxxxxxxa"',
                      GrantReadACP: 'id="b3xxxxxxxxxxxxxxxxxa"',
                      GrantWrite: 'id="b3xxxxxxxxxxxxxxxxxa"',
                      GrantWriteACP: 'id="b3xxxxxxxxxxxxxxxxxa"'
                    };
                    S3Bucket.createBucket(params, function(err, data) {
                        console.log('while creating bucket');
                      if (err) console.log(err, err.stack); // an error occurred
                      else     console.log(data);           // successful response
                    });
},

```
this is from general section of heades in chrome developer tool bar

> Request URL:https://alpha.s3.amazonaws.com/
> Request Method:OPTIONS
> Status Code:403 Forbidden

**Comment by chrisradek** [comment]
@zymr-keshav 
S3 CORS support only extends to already existing buckets that you configure. The service doesn't support CORS on operations such as `createBucket`. You can find more information here:
https://github.com/aws/aws-sdk-js/issues/1112
If your environment (most browsers) supports CORS, then `createBucket` won't work at this time.

Please feel free to post on the [AWS S3 forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) to request this feature.

**Comment by zymr-keshav** [comment]
even we can not call _listBucket()_ method?

```
S3Bucket.listBuckets({},function(err, data) {
                        console.log('ListBucket');
                        // console.log(err);
                        if(err) {
                            console.log(err, err.stack);
                            // deferred.reject(err);
                        }
                        else {
                             console.log(data);
                            // deferred.resolve(data);
                        }
                    });
```

it gives network failure all the time as it goes to err block?

Why SO?

**Comment by paulfryer** [comment]
@chrisradek I just ran into this issue. Any workaround identified? Looks like this post is a couple years old so thought I'd check.

**Comment by AllanFly120** [comment]
hey @paulfryer The S3 Service team still doesn't add CORS support for `CreateBucket`. One workaround is that you can set up a proxy server to relay the requests. You could post on [AWS S3 forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) to request this feature.

**Comment by paulfryer** [comment]
@AllanFly120 I actually did end up using a proxy pattern, in this case I just build a CloudFormation template with one bucket and send it to the CloudFormation API. That works since CF is not using CORS. It's kind of strange, but works and the advantage over proxy via Lambda is that I don't have to install a Lambda.
