### ISSUE TITLE
ManagedUpload and slow connections prevent uploads from succeeding

### ISSUE THREAD

**Issue by apires** [aws/aws-sdk-js#1162]
Hi all,

I've been having some issues reported from users with terrible internet connections, that their uploads just seem to hang forever. I've been using a line conditioner (on mac os x) and I think I've been able to reproduce their case. Here's my data and findings.

- I'm using the ManagedUpload class from the browser version of the SDK (2.6.6)
- My overall upload speed is 67KB/s
- The minimum (hardcoded) part size is 5MB
- The timeout for each chunk is 2 minutes
- My file is around 20MB

Essentially my problem is that quite frequently it seems, the parts just time out. The upload is happening as as quick as it can, but it unfortunately fails to transmit 5MB in that 2 minute window. So it starts over. And it fails again. Then it starts over.

Unfortunately I cannot dial down the upload speed without changing the SDK source code. That being said, I did download the minified version locally and modified the code. It seems to works if I lower the minPartSize manually, as we would expect. However that severely affected my uploads when i turned off the line conditioner.

Do you have a recommended approach here? I don't mind "slow" for some users, as long as it doesn't affect correctness.

I guess as a feature request, I think it would be nice if the uploader kept track of average speeds and adjusted the knobs automatically ~ I'm too ignorant, or there's no way, to do that in client code in between upload chunks.

It sounds like I will have to ditch the ManagedUpload class to get my stuff working though.

Any thoughts would be very helpful!

**Comment by chrisradek** [comment]
@apires 
There are a couple things you can try to improve the experience for users with poor internet connections.

Setting the `queueSize` of the `ManagedUpload` to 1 would reduce the number of simultaneous uploads occurring at once. The 2 minute timeout applies to each chunk, and only allowing one chunk at a time may allow them the bandwidth they need to complete.

The other thing you can do is remove the timeout by setting it to 0, or increase it, as mentioned in this post:
https://github.com/aws/aws-sdk-js/issues/949#issuecomment-204178782

**Comment by apires** [comment]
Hello @chrisradek,

Thank you for the reply. We've been testing over the last few days with doubling the timeout. We'll try lowering the queue size also.

We might have to remove the timeout altogether as you mentioned.

I guess we can close this as a feature request for having the the uploader instrumented to keep track of of runtime stats and adjust partSize / timeout based on runtime heuristics.

Thanks again!

**Comment by morbo84** [comment]
@chrisradek

> The 2 minute timeout applies to each chunk, and only allowing one chunk at a time may allow them the bandwidth they need to complete.

Where can I find this info in the doc? This is exactly what I eventually figured out, but only after a hard time spent debugging the issue. If this is the case, I think it **should** be documented.
