### ISSUE TITLE
incorrect reading of credentials

### ISSUE THREAD

**Issue by andreineculau** [aws/aws-sdk-js#1163]
as per http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles

source_profile define which credentials to load, yet with a configuration like that, I get into "Missing credentials in config" errors.

In order to fix this situation, I basically need this as my `~/.aws/credentials` i.e. duplicate the credentials:

```
[development]
aws_access_key_id=foo
aws_secret_access_key=bar
[crossacount]
aws_access_key_id=foo
aws_secret_access_key=bar
`
``

**Comment by LiuJoyceC** [comment]
Hi @andreineculau 
The AWS JavaScript SDK does not currently support the AWS CLI config file, which is intended for the AWS CLI. However, we are looking into this as a feature request.

We already have this open as a feature request (https://github.com/aws/aws-sdk-js/issues/1039), so I will mark this as a duplicate and close it. Thanks.
