### ISSUE TITLE
Should retry Route53 requests that get PriorRequestNotComplete errors

### ISSUE THREAD

**Issue by Answashe** [aws/aws-sdk-js#1166]
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests has a description of the PriorRequestNotComplete error. In most cases this can be retried with the normal exponential backoff strategy. In fact, that's what boto does.

boto works a little differently in that its retry behavior is defined as data instead of code, but see https://github.com/boto/botocore/pull/682 for the corresponding change in boto.

**Comment by Answashe** [comment]
I think the easy way to do this would be to modify the [Route53 service](https://github.com/aws/aws-sdk-js/blob/e8bd91efa373d943edbf6a0498dc1e386459c64f/lib/services/route53.js) to override `retryableError` similar to the way the [S3 service](https://github.com/aws/aws-sdk-js/blob/3be3e8098be82ae514e9ef0255efdd92d6ef272b/lib/services/s3.js#L385) does

**Comment by LiuJoyceC** [comment]
Hi @Answashe 
Thanks for the suggestion! I will mark this as a feature request.

**Comment by LiuJoyceC** [comment]
Hi @Answashe 
The feature has been merged in and is available immediately on Github, and will be available from NPM in the next release. Thanks again for bringing this to our attention!
