### ISSUE TITLE
describeLoadBalancers with Marker doesn't return next set of results

### ISSUE THREAD

**Issue by nytins** [aws/aws-sdk-js#1170]
I'm using the `NextMarker` that I received from previous request as `Marker` but doesn't get next set of results back.

```
function fetchELBs(param, region) {
    console.log("Inside fetchELBs ")
    console.log(param)
    var elb = new AWS.ELB();
    elb.describeLoadBalancers(param, function(err, data) {
      if (err) console.log(err, err.stack);
      else {
          console.log(data);
          if (data.NextMarker != null) {
              fetchELBs({Marker: data.NextMarker}, region)
          }
      }
    });
}
```

And I'm calling this function like `fetchELBs(null, 'us-east-1');`

I see the first request returns `400` results. But the next request with `Marker` returns 0 results.

In chrome inspect I see the request going out with below form data and I can see the Marker being sent correctly.
```
Action:DescribeLoadBalancers
Marker:A1FG5NAKX0MRJL
Version:2012-06-01
```

**Comment by chrisradek** [comment]
@nytins 
Can you try lowering the `PageSize` and see if subsequent calls return results?

**Comment by AdityaManohar** [comment]
@nytins 

Do you get another marker back with the response that is not returning results?

**Comment by nytins** [comment]
The issue turned out to be the way I set region. I was reading info from 2 regions like this:
```
AWS.config.region = 'us-east-1';
loadInfo(AWS.config.region);
AWS.config.region = 'us-west-2';
loadInfo(AWS.config.region);
```
So during the describe call, the region would have changed and it caused the issue.

To fix it, I moved setting the region just before the describe function call.
