### ISSUE TITLE
Set bucket properties in aws-sdk-js OR get latest sibling using aws-sdk-js

### ISSUE THREAD

**Issue by essapalaxo** [aws/aws-sdk-js#1172]
I am storing file buffer in riak but when I read it back I get the following error message:

`{"name":"restelasticsearch","hostname":"xxxx","pid":31046,"level":50,"statusCode":400,"stack":"XMLParserError: Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: S\n    at error (/home/xxx/zzz/xxx-backend/node_modules/aws-sdk/node_modules/sax/lib/sax.js:666:10)\n    at strictFail (/home/xxx/zzz/xxx-backend/node_modules/aws-sdk/node_modules/sax/lib/sax.js:692:7)\n    at beginWhiteSpace (/home/xxx/zzz/xxx-backend/node_modules/aws-sdk/node_modules/sax/lib/sax.js:965:7)\n    at Object.write (/home/xxx/zzz/xxx-backend/node_modules/aws-sdk/node_modules/sax/lib/sax.js:1014:11)\n    at Parser.exports.Parser.Parser.parseString (/home/xxx/zzz/xxx-backend/node_modules/aws-sdk/node_modules/xml2js/lib/xml2js.js:502:31)\n    at Parser.parseString (/home/xxx/zzz/xxx-backend/node_modules/aws-sdk/node_modules/xml2js/lib/xml2js.js:7:59)\n    at NodeXmlParser.parse (/home/xxx/zzz/xxx-backend/node_modules/aws-sdk/lib/xml/node_parser.js:30:10)\n    at Request.extractError (/home/xxx/zzz/xxx-backend/node_modules/aws-sdk/lib/services/s3.js:524:39)\n    at Request.callListeners (/home/xxx/zzz/xxx-backend/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/home/xxx/zzz/xxx-backend/node_modules/aws-sdk/lib/sequential_executor.js:77:10)","msg":"Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: S","time":"2016-10-08T06:03:14.415Z","v":0}`

Any idea why this might be happening?

Thanks in anticipation.

**Comment by essapalaxo** [comment]
Ok, Looks like while updating, Riak created new siblings object instead of replacing the existing object. I found in Riak documentation that setting `allow_mult` to `false` in bucket properties will prevent this from happening i.e. create new siblings.

Now my question is how can I set bucket propeties in `aws-sdk` i.e. set `allow_mult` to `false`?

Any idea?

Thanks!

**Comment by essapalaxo** [comment]
Another solution to my problem would be to get the latest sibling i.e. updated object. Is there any way I can get the latest sibling using aws-sdk-js?

I can get the latest sibling from url but I want to get it through aws-sdk API.

Thanks!

**Comment by chrisradek** [comment]
@essapalaxo 
Can you explain what you're trying to accomplish with the SDK? You've mentioned `Riak`, but I'm not familiar with that library or what it is trying to do.

**Comment by essapalaxo** [comment]
@chrisradek 
Thanks for the reply. `Riak` is a distributed NoSQL database. We are using it as `endpoint` in AWS API. While using `Riak` when we call `putObject` to update an existing `Body` with `Key`, the `Body` is not replaced with the new buffer instead it creates a new sibling of buffer and when we try to retrieve that same object using `getObject` method in AWS API we get the error message as shown in the very first part of the question.

`Riak` documentation mentions that we can disable the creation of siblings if we set the bucket property attribute `allow_mult` to `false` & this way AWS API will work as it suppose to. Does AWS API provides any method or way to set bucket properties?

Another & much better way is that AWS API may provide me a method which can fetch me the latest or any sibling I want from `Riak`.

Right now when AWS API tries to fetch the object using `getObject` method, it gets the following in response:

```
Siblings:
7S5lizOWHAnaeA13EdyDP5
5XgitL5OstvVBurVUp1d1V
```

See, it returns the ids of siblings & not the file content which is causing error that I pasted in the very first comment. 

I can access any sibling by the following url:
http://example.com/riak/MyBucket/Key?vtag=sibling_id

I hope you understand my problem.

Thanks!

**Comment by jeskew** [comment]
@essapalaxo Since Riak supplies [a self-hosted storage product described as S3-compatible](http://docs.basho.com/riak/cs/2.1.1/), any incompatibilities between Riak siblings and S3 object versions should be addressed in that compatibility layer rather than in the AWS SDK for JavaScript. Please feel free to reopen if you have any questions or concerns.
