### ISSUE TITLE
Cannot be used with Rollup

### ISSUE THREAD

**Issue by danbucholtz** [aws/aws-sdk-js#1175]
When using this library in the browser via Browserify, Webpack or Rollup, the `process` global from Node.js is Shimmed.

When trying to process this with Rollup, since Rollup converts this library to ES2015 modules, it imports `process` from the the Shim, and then this [line](https://github.com/aws/aws-sdk-js/blob/master/lib/browser_loader.js#L20) overwrites it, triggering an error.

Is there a way that we can NOT modify/overwrite the global variable of `process` so this library can be used with Rollup?

Thanks,
Dan

**Comment by chrisradek** [comment]
@danbucholtz 
Sorry, I'm not too familiar with rollup, can you share how you've got it set up with the SDK?
That line should only modify `process` if it hasn't been defined yet, so I'm not sure how it's overwriting the global variable.

All that said, it wouldn't be difficult to move away from using `process` to determine if we're in the browser or not.

**Comment by danbucholtz** [comment]
@chrisradek,

This was user error. If we removed the `process` shim, this whole issues goes away. We don't actually need it in this case.

Sorry about that!

Thanks,
Dan

**Comment by raphaguasta** [comment]
@danbucholtz I'm having the same problem! How did you fix it? Thanks!!

**Comment by cptflammin** [comment]
Still experimenting the same issue with StencilJS (based on rollup) and aws-amplify, which relies on this lib.
Could you please fix this asap ?
