### ISSUE TITLE
There is no CodeDeliveryDetails property in SignUp callback

### ISSUE THREAD

**Issue by xeniaRen** [aws/aws-sdk-js#1176]
I use AWS SDk for JS in a Web page. I cann't get CodeDeliveryDetails object in SignUp Callback. I notice the http response of SignUp has CodeDeliveryDetails in devtool, but SignUp callback dosen't include it. Do I miss something?

**Comment by chrisradek** [comment]
@xeniaRen 
Can you share how you're calling `SignUp`? It would be helpful to see what the returned `data` object looks like, compared to the results in your devtools as well.

**Comment by xeniaRen** [comment]
I call signUp like this.

userPool.signUp(username, password, attributeList, null, function(err, result){
      if(err) {
        alert(err);
        return;
      }
      cognitoUser = result.user;

      sessionStorage.setItem('username', username)

      if(!result.userConfirmed){
        changePage('confirm_signup')
        //turn to confirmed ui
        // alert("to confirmed ui")
      }
    });

**Comment by xeniaRen** [comment]
I call signUp like this.

`userPool.signUp(username, password, attributeList, null, function(err, result){
if(err) {
alert(err);
return;
}
cognitoUser = result.user;

  sessionStorage.setItem('username', username)

  if(!result.userConfirmed){
    changePage('confirm_signup')
    //turn to confirmed ui
    // alert("to confirmed ui")
  }
});`

**Comment by xeniaRen** [comment]
I call signUp as follow.
userPool.signUp(username, password, attributeList, null, function(err, result){
if(err) {
alert(err);
return;
}
cognitoUser = result.user;

  sessionStorage.setItem('username', username)

  if(!result.userConfirmed){
    changePage('confirm_signup')
    //turn to confirmed ui
    // alert("to confirmed ui")
  }
});

**Comment by chrisradek** [comment]
@xeniaRen 
It looks like you're using the [`amazon-cognito-identity-js` sdk](https://github.com/aws/amazon-cognito-identity-js), not the AWS JS SDK. That SDK is built on top of this one, but adds the functionality you're using.

Please open up an issue on that SDK's repo.
