### ISSUE TITLE
XMLBuilder Dependency too old

### ISSUE THREAD

**Issue by KromDaniel** [aws/aws-sdk-js#1182]
Hey, 
As you can see here:
https://github.com/aws/aws-sdk-js/blob/master/package.json

You are using `"xmlbuilder": "2.6.2"` and it is too old, it has the dependency : `"lodash": "~3.5.0"` which is too old also conflicts with many other packages

Can you please update the dependency?
If I'm using modern lodash then I'm getting the next error:

> node_modules/aws-sdk/lib/xml/builder.js:2:15)
>  Error: Cannot find module 'lodash/object/assign'

If I'm using the 3.5.0 lodash I'm getting error from many other packages:

> Cannot find module 'lodash/assign'

**Comment by gurpreetatwal** [comment]
When merged, #1143 will fix this

**Comment by magnattic** [comment]
Why is this not simply fixed by the merge? Killed my application recently

**Comment by shyamchandranmec** [comment]
@gurpreetatwal Any update on when this issue will be fixed?

**Comment by gurpreetatwal** [comment]
@shyamchandranmec just depends on the maintainers, not much I can do from my side

**Comment by menkari** [comment]
Has there been any update against this? More and more modules are making a requirement against lodash@4

**Comment by shyamchandranmec** [comment]
@menkari I have created a npm package with the changes. You can use [this](https://www.npmjs.com/package/aws-sdk-webpack) until aws developers resolve this.
[Here is the url](https://www.npmjs.com/package/aws-sdk-webpack)

**Comment by gurpreetatwal** [comment]
resolved by #1440

**Comment by jeskew** [comment]
Thanks for your help in tracking down the right dependencies to include, @gurpreetatwal!

**Comment by gurpreetatwal** [comment]
No problem @jeskew ! You should consider enabling [`greenkeeper`](https://greenkeeper.io/) if you can, it'll help by automatically notifying you when your dependencies get updated. However since the package is strict versioned, it might notify you a bit too much.
