### ISSUE TITLE
2.6.9 Causes npm ERR! cb() never called! npm v 3.7.3

### ISSUE THREAD

**Issue by justinffs** [aws/aws-sdk-js#1184]
The release that just happened a couple hours ago broke our build which runs on bamboo npm version 3.7.3 which is node version 5.9.1.  I tested with this same version on OS X and it give the same error.    Node version 5.12.0 and NPM 3.8.6 seem to work OK.

2.6.7 and 2.6.8 do not cause this issue with NPM on version 3.7.3.  I have not looked at the diffs to see what may have caused this issue.

**Comment by chrisradek** [comment]
@justinffs 
It looks like this may be an issue with npm itself. Other users have reported seeing this issue for other packages as well when using node 5.9.x with npm 3.x:
https://github.com/npm/npm/issues/11976

I also tried installing the sdk using multiple versions of node 5.x and npm (by using nvm). Installing with node v5.8.0 with npm v3.7.3 works, as does node v5.10.0 with npm v3.7.3. Node versions 5.9.0 and 5.9.1 are the only ones that I'm encountering issues with, but it seems to be with every 3.x version of npm. Downgrading to npm 2.x with node 5.9.x was able to install the sdk.

We didn't make any major changes between 2.6.8 and 2.6.9 of the SDK, and the package.json was unchanged aside from the version number. It's not clear why node 5.9.x with npm 3.x is failing. The comments in the above thread indicate that sometimes publishing a new version of a package will 'fix' the issue, but not always.

**Comment by justinffs** [comment]
Thanks for looking into it.

**Comment by chrisradek** [comment]
I just tested using v2.6.10 of the SDK, and that one is working with node v5.9.1 and npm 3.7.3.

**Comment by justinffs** [comment]
Thanks @chrisradek
