### ISSUE TITLE
Configuring the maxSockets in both http and https for S3.

### ISSUE THREAD

**Issue by thihara** [aws/aws-sdk-js#1185]
Hi Guys,

I was wondering if there's a way I can define the maxSockets option for both http and https agents in the SDK.

I know either http or https agent can be configured this way using the httpOptions and setting the agent, but it doesn't look like there's a way to do both.

Thanks,
Thihara

**Comment by chrisradek** [comment]
@thihara 
If you are using `http` for some services, and `https` for others, you can configure the same `httpOptions` as part of the configuration passed into a service constructor as you would on the global `AWS.config` object. 

To make things simpler, you could create a single http Agent, and a single https Agent, then pass one or the other into your service constructors as needed.

**Comment by chrisradek** [comment]
Closing, let me know if the information above didn't help.

**Comment by thihara** [comment]
@chrisradek It did. Basically update the config if your connection type changes. Also http://stackoverflow.com/questions/39970302/aws-sdk-for-node-js-connection-management/40035293#40035293
