### ISSUE TITLE
PUT with Presigned Url fails if CacheControl is specified

### ISSUE THREAD

**Issue by davidecantini** [aws/aws-sdk-js#1192]
Uploading a file to S3 from the browser with pre-signed URL as follows:

```
const s3 = new aws.S3();
const s3Params = {
        Bucket: bucketName,
        Key: obKey,
        Expires: 600,
        ContentType: fileType,      
      };
const sReq = s3.getSignedUrl('putObject', s3Params);
```
works properly (the PUT to sReq completes successfully).

However, if adding CacheControl as follows:

```
const s3Params = {
        Bucket: bucketName,
        Key: obKey,
        Expires: 600,
        ContentType: fileType,
        CacheControl: 'max-age=300000'
      };
```
The PUT to sReq fails with a 503 error: "The request signature we calculated does not match the signature you provided. Check your key and signing method."

Here is the full error message:

> 
> <Error>
> <Code>SignatureDoesNotMatch</Code>
> <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
> <AWSAccessKeyId>AKIA**************A</AWSAccessKeyId>
> <StringToSign>AWS4-HMAC-SHA256
> 20161018T175404Z
> 20161018/eu-central-1/s3/aws4_request
> c4a20b52767d66d145aceb48cfca023063f2f4b59976cc48e2ef301c1483e09e</StringToSign>
> <SignatureProvided>74e5d9d6e8b2a8705c6286f9c01ada038d23dee0f0820503de56b4d9ec8d0cb3</SignatureProvided>
> <StringToSignBytes>41 57 53 34 2d 48 ... (_truncated_)</StringToSignBytes>
> <CanonicalRequest>PUT
> /orig
> Cache-Control=max-age%3D300000&Content-Type=image%2Fjpeg&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA**************A%2F20161018%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20161018T175404Z&X-Amz-Expires=600&X-Amz-SignedHeaders=cache-control%3Bhost
> cache-control:no-cache
> host:test-app-orig.s3.eu-central-1.amazonaws.com
> 
> cache-control;host
> UNSIGNED-PAYLOAD</CanonicalRequest>
> <CanonicalRequestBytes>50 55 54 0a 2f 32 ... (_truncated_)</CanonicalRequestBytes>
> <RequestId>C12B55C35AABF9E4</RequestId>
> <HostId>47+/9U6wzceSV4aZUsuARRhvwcocgUAwkSUEp1 (truncated) =</HostId>
> </Error>

Am I missing something? Thank you in advance.

**Comment by davidecantini** [comment]
The issue described above seems to be related to the region:

region: "eu-central-1",  it fails (with the error described above).
region: "us-east-1", it works.

Please advise, thank you

**Comment by chrisradek** [comment]
@davidecantini 
Are you also passing the cache-control header when you're using the presigned url? Since it is a signed header, it would need to be included when making your put request with the URL.

**Comment by davidecantini** [comment]
@chrisradek 
I'm sending an ajax PUT $.ajax(sReq, settings) where:

- sReq, is what the s3.getSignedUrl() returned (please see the first post for its parameters)
- settings, is just the ajax settings object { method: 'PUT',  contentType: false,  processData: false,  data: blob}

Hopefully that addresses your question. Please take also into account the second post about the region, if it can be useful.

As a temporary workaround, assuming that it's acceptable to have all objects in the bucket with the same max-age, can you please confirm that setting <MaxAgeSeconds>31536000</MaxAgeSeconds> in the CORS settings would be equivalent to specifying the CacheControl in the signed upload? 

Thanks again for your help.

**Comment by chrisradek** [comment]
Based on your settings, it looks like you are not setting the cache-control header when making your put request. You would need to add it to the `headers` field within `settings`.

You're seeing different results in us-east-1 vs eu-central-1 because those regions support different signature versions:
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

us-east-1 will use `sigv2` by default, and eu-central-1 will use `sigv4` by default, since that's the only signature version it supports. Sigv4 will allow you to specify CacheControl, but then forces you to also pass the cache-control header when making a request. Really, this means that the presigned url is enforcing what cache-control should be set as, not necessarily providing it to S3.

**Comment by davidecantini** [comment]
@chrisradek 
That fixed it. Thanks!
