### ISSUE TITLE
CloudWatchLogs filterLogEvents always empty

### ISSUE THREAD

**Issue by tj** [aws/aws-sdk-js#1193]
- version: 2.6.10
- node: v6.9.0

Trying to confirm still, but I'm not sure that this API is mapped properly.

```js
const aws = require('aws-sdk')

const logs = new aws.CloudWatchLogs({
  region: 'us-west-2'
})

const params = {
  logGroupName: '/aws/lambda/vitals_check_processor'
}

logs.filterLogEvents(params, function(err, res) {
  if (err) throw err
  console.log(res)
})
```

I can execute the same via the AWS CLI using the same profile, and I get events, however with aws-sdk-js I get `events: []` no matter what I use for params. Anyone have similar issues?

thanks!

**Comment by chrisradek** [comment]
@tj 
Are you certain that the CLI is using the same credentials and region as the JS SDK? The CLI can reference the shared config file, which the JS SDK can't, but they should both look at the shared credentials file first.

**Comment by tj** [comment]
The only relevant config there would be the region right? I have that hard-coded above, tried via `aws.config.update()` as well

**Comment by tj** [comment]
oh wow interesting, appears to work fine in other regions, even though I have this function in all regions... weird
