### ISSUE TITLE
Expose DynamoDB client 'converter'

### ISSUE THREAD

**Issue by ddura** [aws/aws-sdk-js#1195]
Small feature request, we would like to use the 'converter' function in the DynamoDB library when converting data in DynamoDB streams (using Lambda). Instead we are writing our own function that does the same thing (ie. converting AttributeValues to a JavaScript object.)

**Comment by chrisradek** [comment]
@ddura 
You would expect to pass in an AttributeValue to get back a JavaScript object, right? Would you need to be able to go the other way as well?

**Comment by johncmckim** [comment]
+1 on this. If you have to process a DynamoDB stream on Lambda right now you have to convert the Image to an object yourself.

@ddura I'm wrapping the `aws-sdk` with this to convert to and from an image. I'm accepting the risk of using a private api and I've got a unit test for it to try catch any issues.

It would be much better if it was supported out of the box.

```
const converter = require('aws-sdk/lib/dynamodb/converter');

module.exports = {
    toImage: (item) => {
        return Object.keys(item).reduce((accum, key) => {
            const val = item[key];
            accum[key] = converter.input(val);
            return accum;
        }, {})
    },
    fromImage: (image) => {
        return converter.output({
            M: image
        });
    },
}
```

**Comment by hashitha** [comment]
Hope this gets implemented soon

**Comment by jonpaul** [comment]
I literally sourced the shapes module and tried to compose a ListShape so I could do this transform with DynamoDB event streams. I just said forget the whole thing and did the same thing as [above](#issuecomment-266912638)
