### ISSUE TITLE
Successful s3.deleteObject call returns empty results

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js#1197]
Using aws-sdk 2.6.9. When I execute a successful deletion request:

``` js
s3.deleteObject({
  Bucket: 'my-bucket',
  Key: 'some/key/file.txt',
}, (error, result) => {
  console.log(error, result);
});
```

`error` is `null` and `result` is `{}`. I'm pretty sure this is unexpected behavior.

**Comment by monken** [comment]
No it isn't.

From http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectDELETE.html

> This implementation of the operation does not return response elements.

**Comment by ffxsam** [comment]
I'm not so sure about that:

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#deleteObject-property

Quote:

### Parameters:

- err (Error) — the error object returned from the request. Set to null if the request is successful.
- data (Object) — the de-serialized data returned from the request. Set to null if a request error occurs. The data object has the following properties:
  - DeleteMarker — (Boolean) Specifies whether the versioned object that was permanently deleted was (true) or was not (false) a delete marker.
  - VersionId — (String) Returns the version ID of the delete marker created as a result of the DELETE operation.
  - RequestCharged — (String) If present, indicates that the requester was successfully charged for the request. Possible values include:
"requester"
```

**Comment by monken** [comment]
That seems to only apply to DELETEs in versioned buckets.

**Comment by chrisradek** [comment]
@ffxsam 
@monken is correct, those fields on the `data` object are not guaranteed to be there. `DeleteMarker` and `VersionID` should be there when working with versioned objects, and `RequestCharged` should be there is the object is configured such that requesters get charged for downloads.

**Comment by ffxsam** [comment]
Good to know - thanks for clarifying!
