### ISSUE TITLE
AWS.S3.getObject() can't access object in US Standard bucket

### ISSUE THREAD

**Issue by johndanek** [aws/aws-sdk-js#1198]
My bucket is located in US Standard, according to the AWS S3 browser dashboard. I am attempting to use the Node.js 'aws-sdk' package to perform a getObject from this bucket.

My code looks like:

```
AWS.config.update({
  region: 'us-standard',
  accessKeyId: accessKey,
  secretAccessKey: process.env.AWS_SECRET_KEY,
  httpOptions: {
    timeout: 300000 //5 minute timeout
  }
})

var s3 = new AWS.S3()

var params = {
    Bucket: "myBucket",
    Key:    "my/key/to/object.mov"
}

var file = fs.createWriteStream("filepath.mov", {autoClose:true})

requests[i] = s3.getObject(params, overallResponse())
requests[i].createReadStream()
    .on('error', errorResponse())
    .pipe(file)
    .on('error', errorResponse())
```

No matter what I do, I get the following error:
`PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`

My guess is that 'us-standard' is not the correct string for the US Standard region, but there is nowhere in the documentation that I can find such a list of regions to config strings. http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region has a list but lacks US Standard. http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Setting_the_Region offers no help in choosing the correct string.

I don't know if this is a bug, or documentation needs to be fleshed out, or the error is not representative of what is actually happening.

**Comment by chrisradek** [comment]
@johndanek 
`us-standard` is actually `us-east-1`. In the [AWS Regions and Endpoints](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) docs, there's the following note:

> Amazon S3 renamed the US Standard Region to the US East (N. Virginia) Region to be consistent with AWS regional naming conventions. There is no change to the endpoint and you do not need to make any changes to your application.

If you update your region to `us-east-1` in the code sample you provided, you should be able to access your objects.

**Comment by johndanek** [comment]
@chrisradek Gotcha. That worked! Should have read above and below the table for that note. Thanks!
