### ISSUE TITLE
API usage for budget service

### ISSUE THREAD

**Issue by xiaowei-tian** [aws/aws-sdk-js#1199]
var budget = new AWS.Budgets({apiVersion:'2016-10-20'});

var params = {
    AccountId: accountid,
    BudgetName: 'test1'
};

budget.describeBudget(params, function(err, data) {
    if (err) console.log(err,err.stack);
    else console.log(data);
});

Getting error like this: 
https://budgets.amazonaws.com/ Failed to load resource: the server responded with a status of 403 (Forbidden)
XMLHttpRequest cannot load https://budgets.amazonaws.com/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 403.

**Comment by chrisradek** [comment]
@tinnytian 
It looks like you're trying to use this service in a browser, please correct me if I'm wrong. This service doesn't currently support CORS, so it won't work in an environment that enforces it (many browsers.) We are pushing services to support CORS, so we'll bring this up with them.

**Comment by chrisradek** [comment]
Cleaning up old issues. Unfortunately there isn't anything the SDK can do to enable CORS for the Budgets service as they have to make a change on the service side. Please open a request on the AWS forums requesting CORS support for the Budgets service:
https://forums.aws.amazon.com/forum.jspa?forumID=8
