### ISSUE TITLE
SDK Builder is broken

### ISSUE THREAD

**Issue by samwilcoxon** [aws/aws-sdk-js#1200]
The link to the SDK Builder in the Documentation (http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-building.html) is broken and is causing a TEXT file to be downloaded instead of the usual interface: https://sdk.amazonaws.com/builder/js

**Comment by chrisradek** [comment]
@samwilcoxon 
Thanks for reporting this issue. The link should be working again, apologies for the inconvenience.
