### ISSUE TITLE
Is there any method which will describe all the resources of a VPC?

### ISSUE THREAD

**Issue by zymr-keshav** [aws/aws-sdk-js#1202]
There is one method [describeVpcs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeVpcs-property)  which will display only vpcID and DHCP options.

I am looking for any single function which will display all attached resources of an individual VCP such as
- VPC ID
- Subnet ID
- SecurityGroups ID
- RouteTable ID
- InternetGateway ID
- CustomerGateway ID
- Elastic IP
- VPC Endpoint
- Network ACL

likewise when we select a VPC from amazon console then it show the filtered VPC details . and when we trying to delete a VPC than it display all the related resources deletion information.

**label :** suggestion / feature request

**Comment by chrisradek** [comment]
@zymr-keshav 
Since this is a feature request for service-level functionality, please make a post to the [EC2 service forums](https://forums.aws.amazon.com/forum.jspa?forumID=30). The SDK would need EC2 to provide or enhance an operation to return this data.

**Comment by zymr-keshav** [comment]
I tried . but it says **"Your account is not ready for posting messages yet. Please try again later. "**
