### ISSUE TITLE
Moving to SemVer (semantic versioning)

### ISSUE THREAD

**Issue by dorongutman** [aws/aws-sdk-js#1204]
Can the versioning of releases in this library utilize the [semantic versioning standard](http://semver.org/) ? 
So releasing a new feature will increase the middle number of the version, and reset the right-most number ? 
This will allow us to pin to ^2.6.0 and not fear to update patch versions or even minor ones, as there are no breaking changes.

**Comment by chrisradek** [comment]
@dorongutman 
We do try to follow SemVer today, except service updates result in patch updates instead of minor ones as they typically don't require any code changes.
Our goal is to not make any breaking changes unless we do a major version bump.

**Comment by dorongutman** [comment]
@chrisradek 
If you're releasing both bugfixes and service updates in patch, and breaking changes in major - when do you increment the minor version part ?

**Comment by chrisradek** [comment]
When features are added to the SDK that require code changes. For example, `2.2.0` was created when the DocumentClient was added to the SDK. `2.3.0` added support for promises, `2.6.0` added webpack support. Sometimes we do have to make code changes with a service update, and in general we've also treated these as patch updates. However you're right, according to SemVer, these should be treated as minor updates as well.

**Comment by dorongutman** [comment]
Ok that's sound reasonable.
Just to be sure - when you're updating the patch version, does that mean it's safe to update without a careful eye  ?

**Comment by chrisradek** [comment]
I don't think I'd ever recommend updating a dependency without at least running some tests, since sometimes mistakes can happen even with the best intentions. Patch updates should not affect existing code paths though, unless it's to fix a bug.

**Comment by carnesen** [comment]
Sorry to comment on a closed issue, but I came to this repo to say what dorongutman did, 
"Can the versioning of releases in this library utilize the semantic versioning standard?" It's clear from the release notes that new patch versions include both new features as well as bug fixes. In the semantic standard, such a release should be a new minor. The distinction of "service updates" vs "code changes" is an internal implementation detail that is immaterial to the consumer of the library.
