### ISSUE TITLE
STS endpoint URL

### ISSUE THREAD

**Issue by hellopeera** [aws/aws-sdk-js#1205]
According to the [AWS Javascript SDK document](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#constructor-property), it says the endpoint should be a string like '**https://{service}.{region}.amazonaws.com'**.

However, according to the file lib/region_config.json on line 12, every instance of AWS.STS will use the global endpoint i.e. sts.amazonaws.com regardless of the region specified in the constructor option. 

Therefore, I would suggest change the line 12 
from 
`"*/sts": "globalSSL",` 

to 
`"*/sts": {"endpoint": "https://{service}.{region}.amazonaws.com"},`

**Comment by chrisradek** [comment]
@hellopeera 
`https://{service}.{region}.amazonaws.com` is a general rule. However, some services use a global endpoint. The `region_config.json` controls the default endpoints to use based on a service and region, but it is possible for users to specify a different endpoint.
