### ISSUE TITLE
getSignedUrl Expires parameter vs IAM expireTime?

### ISSUE THREAD

**Issue by zeevl** [aws/aws-sdk-js#1207]
Given the following scenario: 
 - node server running on ec2
 - Temporary credentials provided by IAM
 - Credentials expire in an hour

If I call `getSignedUrl` with an Expires parameter of, say, 24 hours, the returned URL will be invalid when the IAM credentials expires in 1 hour, correct?  Even though the Expires= parameter on the URL indicates 24 hours?

If so, it seems like `s3.getSignedUrl` should either check against `AWS.config.expireTime` and error out, and/or attempt a refresh of credentials before returning.

Not sure if my understanding of this is correct, so there might be different options?

**Comment by chrisradek** [comment]
@zeevl 
Found a similar issue on the AWS SDK for Ruby:
https://github.com/aws/aws-sdk-ruby/issues/808

Unfortunately, I don't think we can make the SDK start throwing errors in this case, as it could break existing applications that are generating URLs with a longer `Expires` than the `expireTime` allows, but also using the url before credentials expires.

It is possible to call `refresh` on the credentials (and check if `expireTime` is near to further reduce the number of calls made), then generate the url once credentials have been refreshed.

The ruby issue mentions it may be possible to update the policy to allow for longer expiration times, but I haven't looked into it myself to see if that's the case.

**Comment by zeevl** [comment]
Thanks @chrisradek.   I thought about taking the `refresh` approach, but unfortunately I haven't had any luck with that on my EC2 instances.   It seems to have something to do with https://github.com/aws/aws-sdk-js/issues/246, where `AWS.config.credentials` never appear populated and `AWS.config.credentialProvider` is `[null, null, null, null]`, so `getCredentials` (and consequently, `refresh`) fails with "No credentials to load".

Is there a better way to check/`refresh` credentials on EC2 instances?
