### ISSUE TITLE
Import CognitoIdentityCredentials without loading all of AWS

### ISSUE THREAD

**Issue by thinkloop** [aws/aws-sdk-js#1210]
Hello,

I granularly import the pieces of the sdk I need, to keep files sizes down. For example:

```
import Config from 'aws-sdk/clients/configservice';
```

I would like to do the same for AWS.CognitoIdentityCredentials, but I have only been able to do it by loading the entire sdk:

```
import AWS from 'aws-sdk';
```

This ballons the build from 3mb to 8.5mb.

Is there a way to surgically load AWS.CognitoIdentityCredentials?

**Comment by chrisradek** [comment]
@thinkloop 
There isn't a good way of requiring just the `AWS.CognitoIdentityCredentials`. You can import `aws-sdk/global` to give you the `AWS` namespace with all the core classes (including credentials) loaded. Services aren't added to `AWS` when importing from `aws-sdk/global` unless you explicitly import them elsewhere.

This should result in a smaller build, since you won't be importing every single service.

**Comment by thinkloop** [comment]
Thanks! That worked. Do I still need the separate `Config` or does it also come with `global`:

```
import Config from 'aws-sdk/clients/configservice';
import AWS from 'aws-sdk/global';

Config.credentials = new AWS.CognitoIdentityCredentials({
	IdentityPoolId: 'us-east-1_xxxx',
	Logins : {
	    'cognito-idp.us-east-1.amazonaws.com/us-east-xxxx': result.getIdToken().getJwtToken()
	},
	Paranoia : 7
});
```

**Comment by chrisradek** [comment]
@thinkloop 
`AWS.ConfigService` is different from `AWS.Config`. The former is a service you'd need to import explicitly, the latter controls the SDK configuration settings. In your example, it looks like you're trying to update the SDK's credentials, so you can do something like this:
```javascript
import AWS from 'aws-sdk/global';

AWS.config.credentials = new AWS.CognitoIdentityCredentials({
  /** params **/
});
```

**Comment by thinkloop** [comment]
+1, thanks again!

**Comment by sandangel** [comment]
Sorry I'm using Angular typescript,  I have an error that aws-sdk/global doesn't has a default export. How can I config global credential after retrieved it from CognitoIdentityCredentials ?

**Comment by weblucaseduardo** [comment]
@sandangel 
in typescript use * as
`import * as AWS from "aws-sdk/global";`

**Comment by sandangel** [comment]
I found a more efficient way. 
```ts
import {config as AWSConfig} from 'aws-sdk/global';
```

**Comment by ispyinternet** [comment]
its still 23k lines and 1.8MB. Is there no way to expose this as a module so it can be used effectively in the front end? At the moment is still only realistic for backend.

**Comment by devourment77** [comment]
I am running into this issue today as well, is there a work around for a small build? I do not see CognitoIdentityCredentials in clients, only cognitoidentity and cognitoidentityserviceprovider.
