### ISSUE TITLE
DynamoDB scan returning all documents in the table

### ISSUE THREAD

**Issue by gsuresh92** [aws/aws-sdk-js#1211]
My Policy Details :-
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "dynamodb:GetItem",
                "dynamodb:BatchGetItem",
                "dynamodb:Query",
                "dynamodb:PutItem",
                "dynamodb:UpdateItem",
                "dynamodb:DeleteItem",
                "dynamodb:Scan",
                "dynamodb:BatchWriteItem"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-east-1:{account-id}:table/Sim"
            ],
            "Condition": {
                "ForAllValues:StringEquals": {
                    "dynamodb:LeadingKeys": [
                        "${cognito-identity.amazonaws.com:sub}"
                    ]
                }
            }
        }
    ]
}`

JS Code:-
`var dynamodb = new AWS.DynamoDB();
var params = {
    TableName: 'Sim'
}

dynamodb.scan(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});`

I am getting all the records rather than just the matching records based on Identity ID

Please let me know if i have to do any modifications for the policy 
FYI :- GetItem, PutItem are working as expected

**Comment by chrisradek** [comment]
@gsuresh92 
Since this looks like an issue with how the policy is configured, can you post your question to the [DynaomDB forums](https://forums.aws.amazon.com/forum.jspa?forumID=131)? They will be better equipped to answer this sort of question.
