### ISSUE TITLE
When using adminInitiateAuth is there a way to use new AWS.CognitoIdentityCredentials instead of calling getId and then getCredentialsForIdentity?

### ISSUE THREAD

**Issue by VictorioBerra** [aws/aws-sdk-js#1212]
I am performing authentication using Identity Pools as my provider. I then use Federated Identities to fetch AWS credentials for my authenticated user. Im doing all of this on my back-end without the need for https://github.com/aws/amazon-cognito-identity-js I plan to blog about this soon as documentation for actually doing this is really sparse. And hopefully in the future release some ExpressJS middleware for plugging Cognito in as easily as tools like Stormpath.

I want to be able to go from `adminInitiateAuth()` to new `AWS.CognitoIdentityCredentials()` but instead im having to call `getId()` and then pass the IndentityId to `getCredentialsForIdentity()`. From what I understand the call to `new AWS.CognitoIdentityCredentials()` takes nearly identical params, and it also calls some of these methods like `getId()` under the hood. When I try I get: `NotAuthorizedException: Access to Identity 'us-east-1:REDACTED-DDD-CCC-BBB-AAA' is forbidden.`

**Comment by chrisradek** [comment]
@VictorioBerra 
Do you mind sharing a code sample that illustrates what you're trying to do? I'm not sure I follow how you're linking an id generated from the back-end to a client.

**Comment by VictorioBerra** [comment]
This is a working example on how to authenticate a user via Identity Pools as an Identity Provider with `adminInitiateAuth()`, and then turn around and grab an IdentityID by validating a User Pool IdToken against Amazon Cognito Federated Identities via `getId()`, and finally requesting AWS credentials from Amazon Cognito Federated Identities via `getCredentialsForIdentity()`.

```javascript
var authParams = {
    AuthFlow: 'ADMIN_NO_SRP_AUTH',
    ClientId: 'MY_CLIENT_ID',
    UserPoolId: 'us-east-1_MY_POOL_ID',
    AuthParameters: {
        USERNAME: 'USERNAME',
        PASSWORD: 'PASSWORD'
    }

};

var cognitoidentityserviceprovider = new req.AWS.CognitoIdentityServiceProvider({
    region: 'us-east-1' // Why do I need this? Its in .aws/config
});

cognitoidentityserviceprovider.adminInitiateAuth(authParams, function(err, sessionData) {
    
    if (err) {
        console.log(err, err.stack);
    } else {

        var cognitoidentity = new req.AWS.CognitoIdentity({
            region: 'us-east-1' // Why do I need this? Its in .aws/config
        });
        
        var getIdParams = {
            IdentityPoolId: 'us-east-1:IDENTITY_POOL_GUID',
            Logins: {
                'cognito-idp.us-east-1.amazonaws.com/us-east-1_MY_POOL_ID': sessionData.AuthenticationResult.IdToken
            }
        }

        cognitoidentity.getId(getIdParams, function(err, identity) {
            if (err)
            {
                console.log(err, err.stack);
            }
            else
            {       

                var getCredentialsParams = {
                    IdentityId: identity.IdentityId,
                    Logins: {
                        'cognito-idp.us-east-1.amazonaws.com/us-east-1_MY_POOL_ID': sessionData.AuthenticationResult.IdToken
                    }                        
                };

                cognitoidentity.getCredentialsForIdentity(getCredentialsParams, function(err, credentials) {                        
                  if (err)
                  {
                      console.log(err, err.stack);
                  }
                  else 
                  {
                      console.log(credentials); // SUCCESS!
                  }
                });
                
                
            }
        });


    }
});
```

**Comment by pprabhu3430** [comment]
'I want to be able to go from adminInitiateAuth() to new AWS.CognitoIdentityCredentials()' . This is exactly what I want to do and the documentation is unbelievably frustrating. 

But looks like your code will also work as long as I get hold of a credentials object. My purpose is to first generate the session idTken server side and then use it client side to build a credentials object so as to make AWS Lex calls via Javascript. 

I used adminInitiateAuth and logged the user in. Now I need to use the session.idToken to build the credentials object on the client side. However what is the IDENTITY_POOL_GUID? How do I get hold of that value. Do I have to link a federated identity provider to my user pool? 

Thanks for any help or clarification you can provide.

**Comment by pnandak** [comment]
I am struggling to get this done from Server side. (admin_no_srp_auth) with Cognito identity. I used your above code but i get following error: Process exited before completing request and 	TypeError: Cannot read property 'IdToken' of undefined

**Comment by pnandak** [comment]
@VictorioBerra 	I am struggling to get this done from Server side. (admin_no_srp_auth) with Cognito identity. I used your above code but i get following error: Process exited before completing request and TypeError: Cannot read property 'IdToken' of undefined. Can you help me to provide the lambda code for reference

**Comment by VictorioBerra** [comment]
@pnandak It has been so long i barely remember most of this. It would take me a couple hours to ramp back up and get my own examples working.

You can see an older example here that may or may not work https://github.com/VictorioBerra/js-cognito-auth-example

Best of luck.

**Comment by JamieShelley** [comment]
> 'I want to be able to go from adminInitiateAuth() to new AWS.CognitoIdentityCredentials()' . This is exactly what I want to do and the documentation is unbelievably frustrating.

Amen to that, Days of reading to get a clear godamn answer.

**Comment by JamieShelley** [comment]
You need to use async await on promises. - I assume you're using node, not standard javascript.
Once you have 'resolved' your promise, you need to return your data via a 'then'.
This effectively forces callback to be synchronous...And yes it was a nightmare to work this out . If you are confused. Please feel free to email: jshelley@linxglobal.com

**Comment by VictorioBerra** [comment]
I don't think our issues stem from misunderstanding how promises work.

**Comment by JamieShelley** [comment]
> I don't think our issues stem from misunderstanding how promises work.

pnandak's issue is
