### ISSUE TITLE
CloudWatchEvents putRule/putTargets not triggering Lambda function

### ISSUE THREAD

**Issue by juancabrera** [aws/aws-sdk-js#1214]
I'm building a node app that is creating a new rule with a `ScheduleExpression` of `rate(5 minutes)` then it's adding a Lambda function as a target to it (adding the respective permissions). But is not triggering the Lambda function even though all looks to be ok on the console. 

Only way to get it working is going to the Lambda Management Console, get into the function, then on the `Triggers` tab click `disable` and then `enable`.

Response I got when creating Rule:
```javascript
{ RuleArn: 'arn:aws:events:us-east-1:111111111111:rule/SyncData' }
```

Response I got when adding permissions:
```javascript
{ Statement: '{"Sid":"statementID","Resource":"arn:aws:lambda:us-east-1:111111111111:function:FUNCTIONNAME","Effect":"Allow","Principal":{"Service":"events.amazonaws.com"},"Action":["lambda:InvokeFunction"],"Condition":{"ArnLike":{"AWS:SourceArn":"arn:aws:events:us-east-1:111111111111:rule/SyncData"}}}' }
```

Response I got when adding target (Lambda function) to Rule:
```javascript
{ FailedEntryCount: 0, FailedEntries: [] }
```

This is the code:
```javascript
// Creating Rule
cloudWatchEvents.putRule({
  Name: ruleName, 
  ScheduleExpression: 'rate(5 minutes)',
  Description: ruleName
}, (err, data) => {
  if (err) {
    console.log('ERROR: putRule', err, err.stack)
  } else {
    console.log('putRule', data)
    ruleARN = data.RuleArn
    // Add permissions to Lambda Function
    lambda.addPermission({
      Action: 'lambda:InvokeFunction',
      FunctionName: lambdaFunctionName,
      StatementId: 'statementID',
      Principal: 'events.amazonaws.com',
      SourceArn: ruleARN
    }, (err, data) => {
      if (err) {
        console.log('ERROR: addPermission', err, err.stack)
      } else {
        // Adding target to Rule
        cloudWatchEvents.putTargets({
          Rule: ruleName, 
          Targets: [{
            'Id': '1', 
            'Arn': ruleARN.replace('events', 'lambda').replace('rule', 'function').replace(ruleName, lambdaFunctionName)
          }]
        }, (err, data) => {
            if (err) {
              console.log('ERROR: putTarget', err, err.stack)
            } else {
              console.log('putTarget', data)
            }
        })
      }
    })
  }
})
```
Hope this is enough to explain the issue, let me know you guys need more specific info.

**Comment by juancabrera** [comment]
Just a quick update with more information.

I'm using `aws-sdk` `v2.6.12` on node `v6.4.0`

**Comment by juancabrera** [comment]
Anything else you guys need to provide some feedback ?

**Comment by chrisradek** [comment]
@juancabrera 
According to the [`CloudWatchEvents.putTargets` docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatchEvents.html#putTargets-property):

> Note: When you add targets to a rule, when the associated rule triggers, new or updated targets might not be immediately invoked. Please allow a short period of time for changes to take effect. 

It seems it might take some time for the change to take effect.

Since this question is more about how the `CloudWatchEvents` service functions rather than the SDK, you can also post to the [`AWS CloudWatch` forums](https://forums.aws.amazon.com/forum.jspa?forumID=138) if you need more information, like how long it can take for changes to take effect.

**Comment by pex** [comment]
@juancabrera, I am currently experiencing the same issue (using version `2.7.21`). Did you get an answer on how long it takes for changes to take effect?
Though this might be a question about `CloudWatchEvents` in general I am only experiencing this behaviour when creating / updating `CloudWatchEvents` programmatically via API. Using AWS console interfaces reflects changes immediately.

**Comment by a-astakhov** [comment]
Hi, did you find a solution?

**Comment by wswoodruff** [comment]
Having the same problem when adding an sqs target to a cloudwatch rule and it not firing until I use aws console UI. Opened a new issue for it here: https://github.com/aws/aws-sdk-js/issues/2724

**Comment by trivikr** [comment]
Locking this issue as it has been resolved and inactive for a long time.
The follow up will happen on #2724
