### ISSUE TITLE
ListObjects failure on empty response

### ISSUE THREAD

**Issue by rclark** [aws/aws-sdk-js#1216]
This ticket may sound similar to #886 ....

We started noticing situations where a `listObjects()` SDK call would provide an invalid response. Specifically, there would be no error, and the response data would be an empty `{}` -- **not** what you would expect from an empty response or the end of pagination, `{ Contents: [] }`.

It turns out we can reproduce this behavior by providing the SDK with an HTTP response that is a `200` with no body. 

So if you create a mock S3 server:

```js
var server = http.createServer(function (req, res) {
  res.writeHead(200);
  res.end();
});
```

... then you'll find that a `listObjects` request will provide an invalid response:

```js
s3.listObjects(params, function(err, data) {
  assert.notOk(err); // there is no error object
  assert.deepEqual(data, {}); // response.data is malformed
});
```

I believe that the correct behavior in this event would be for the SDK to provide an error object. Clearly the API did not respond correctly.

p.s. We found this case by adding [this catcher to an application that performs a lot of `listObjects` requests](https://github.com/mapbox/s3scan/pull/18/files). What we found was that when this condition was met `!Array.isArray(data.Contents)`, `this.httpResponse.body` and `this.httpReponse.headers` were both `undefined`, though we did see `this.httpResponse.statusCode === 200` and we also had a `.requestId`.

**Comment by chrisradek** [comment]
@rclark 
Would you be able to reproduce this test, logging the response details? Specifically, I want to know what the body of the response, and content-length were sent back as. This would help in determining how we should tackle this issue with S3.

**Comment by rclark** [comment]
We [ran this code](https://github.com/mapbox/s3scan/blob/d0d3f6782b5f8a83b0f3fc5a4056b4cbf2ba12d2/lib/keys.js#L53-L60) for a while and encountered this situation a couple of times while running it. 

The clues here were that the error objects we produced indicated that `response.httpResponse.body` and `response.httpResponse.headers` were undefined, while `response.httpResponse.statusCode` was `200`. Beyond that, I'm not sure I know how I can get an answer to your questions.

**Comment by srchase** [comment]
@rclark 

Is this still an open issue for you?  We haven't seen anything like this lately, so I'd like to close this unless you have some additional information to add in tracking down the issue.

**Comment by srchase** [comment]
Since there have been significant changes to the SDK, I'm going to go ahead and close the issue.  If you do find that this happens with a more recent version of the SDK, do let us know and we'll be happy to take a look.
