### ISSUE TITLE
Please export AWSError in core.d.ts

### ISSUE THREAD

**Issue by lukiano** [aws/aws-sdk-js#1219]
in core.d.ts

**Comment by chrisradek** [comment]
@lukiano 
Thanks for logging an issue. Just so I understand better, can I ask why you need it exposed? Are you getting any errors, trying to specify the type, etc? Very interested in any feedback around this feature.

Depending on your use case, you may be able to use this as a temporary work-around:
```javascript
import {AWSError} from 'aws-sdk/lib/error';
```

**Comment by jacobdr** [comment]
Not sure what the use case is specifically here, but in general publicly exposing the errors allows you to use certain conveniences around catching errors. 

For example, the `bluebird` promise library exposes an `.catch` method that could be used like this:
```typescript
import {AWSError} from 'aws-sdk';
import * as Promise from 'bluebird';

Promise.resolve(uploadToS3)
    .catch(AWSError, (error) => handler)
    .catch((error)=> {
        // Handle all other errors down here
    })
```

**Comment by lukiano** [comment]
In my case it's for "instance of"s and accessing the error fields like code

**Comment by lukiano** [comment]
Also, in error.d.ts, it should say _extendedRequestId_ instead of _extendedRequstId_

**Comment by ehartford** [comment]
Of course there is a use case for exporting AWSError.
It's a commonly used error class, and we need it.
Otherwise we are using 'any'
There's no reason we should have to do that when there's a perfectly good class that just needs to be exported.
I made a PR please review

**Comment by jeskew** [comment]
An export of `AWSError` was added to lib/core.d.ts in #1355, which has been merged to master and will be included in the next release.

**Comment by ehartford** [comment]
it's not useful to create them,

it's only useful in interpreting them when aws sdk produces them.

in short there's no need to make that class visible in raw js.  if you want
to know what it contains just console.log one.
