### ISSUE TITLE
Allow noImplicitAny = true from TypeScript

### ISSUE THREAD

**Issue by marcote** [aws/aws-sdk-js#1220]
Hi Guys, thanks for the latest update.

When trying to compile a TS app using the library, with the `noImplcitAny` = `true` flag, it fails because the `resolve` method in the CredentialProviderChain class doesn't declares it return type.

I'll send a pull request to fix this in a few minutes

**Comment by austinried** [comment]
👍 and thank you, this started failing my builds last night.

**Comment by mrapptambour** [comment]
Thank you as well, uncovered just this morning. You're on top of it!

**Comment by marcote** [comment]
Kudos goes to my boss who discovered the bug and suggested the fix .

**Comment by PabloZaiden** [comment]
Thanks!. Hope it gets pushed to npm soon :)

**Comment by chrisradek** [comment]
Thank you @marcote, and apologies to anyone who was affected. The change has been pushed to master, if anyone encounters more problems please open another issue.

Was anyone that was affected already using 3rd party typings for the SDK?

**Comment by maghis** [comment]
@chrisradek yes, I was using https://www.npmjs.com/package/@djabry/aws-sdk-typescript (it's a fork of a project that auto-generates them).

When will this be pushed to npm?
