### ISSUE TITLE
Typescript def: S3.Body doesn't contain RadableStream as a valid option

### ISSUE THREAD

**Issue by mrgleba** [aws/aws-sdk-js#1225]
S3.Body should be (as per doc in http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html):
Buffer, Typed Array, Blob, String, ReadableStream

Currenty it is:
export type Body = Buffer|Uint8Array|Blob|string;

**Comment by forbesmyester** [comment]
To further this... This code is valid and should work (it did with DT/@types typings):

    let s3obj = new AWS.S3();
    let body = createReadStream(srcPath).pipe(createGzip());
    let params = {
        Body: body,
        Bucket: getEnv('UPLOAD_S3_BUCKET'),
        ContentEncoding: 'gzip',
        Key: 'some-key-here',
    };
    s3obj.upload(params, next);

**Comment by jeskew** [comment]
Resolved by #1662.
