### ISSUE TITLE
Aborted/Cancelled requests causes s3.getObject() to not callback (i.e. hang)

### ISSUE THREAD

**Issue by jacktuck** [aws/aws-sdk-js#1230]
With the below snippet, at first you will get `got object` consistently, but after a few seconds it looks like the `complete` handler stops getting hit and only `closed` is logged. 

Is there any explanation for this, it's happening IRL when I get a lot of cancelled browser requests it looks like the event loop is blocked and no more requests are served properly as it looks like `.getObject` hangs as completed listener is not called anymore.

```
var AWS = require('aws-sdk')
var s3 = new AWS.S3({
    accessKeyId: process.env.accessKeyId,
    secretAccessKey: process.env.secretAccessKey,
    params: {Bucket: process.env.bucket}
})
var http = require('http')

http.createServer(function(req, res) {
    req.on('close', () => console.log('closed'))

    s3.getObject({
        Key: process.env.key
    })
    .on('complete', function () {
        console.log('got object')
    })
    .on('error', function (err, response) {
        console.error(err, response)
    })
    .on('httpHeaders', function(statusCode, headers) {
        res.writeHead(statusCode, headers)

        var stream = this.response.httpResponse.createUnbufferedStream()

        stream.pipe(res)
            .on('error', function(err) {
                console.error(err)
                res.end()
            })
    }).send()
}).listen(1337, function () {
    setInterval(function () {
        var request = http.get({
          port: 1337,
        })
        request.end()

        request.on('error', err => {
            // console.error(err)
        })

        setTimeout(() => request.abort(), 200)
    }, 5)
})

```

**Comment by chrisradek** [comment]
@jacktuck 
Sorry for the delay, can you also share what version of node.js and the SDK you are using so I can more accurately reproduce your issue?

**Comment by sudheerg9** [comment]
We had the same issue and we are using aws-sdk 2.128.0

**Comment by shystruk** [comment]
Hi all,

I have the same issue with `s3.listObjects`.
In browser the request is canceled (Provisional headers are shown).

Has anyone found a solution?

**Comment by srchase** [comment]
@jacktuck 

Were you able to get this working?

If it's no longer an issue, I'd like to close this out.

**Comment by shystruk** [comment]
Close please

**Comment by jacktuck** [comment]
This was some time ago not sure what i did in the end. Happy to close.
