### ISSUE TITLE
Severe SQS memory leak when sslEnabled is true

### ISSUE THREAD

**Issue by AndrewBarba** [aws/aws-sdk-js#1231]
When using a basic `AWS.config` with `sslEnabled: true` we saw severe memory leaks from our polling node and web nodes (which write to SQS). Config:

```
AWS.config = new AWS.Config({
  accessKeyId: config.amazon.key,
  secretAccessKey: config.amazon.secret,
  region: 'us-east-1',
  sslEnabled: true
});
```

Screen shot of polling node (SSL disabled around 10:15pm):

<img width="1223" alt="screen shot 2016-11-17 at 7 53 57 am" src="https://cloud.githubusercontent.com/assets/1316152/20390192/aa1bead8-ac9b-11e6-93bb-d8a4a0c275a3.png">

Screenshot of web node (SSL disabled around 10:15pm):

<img width="1227" alt="screen shot 2016-11-17 at 7 54 39 am" src="https://cloud.githubusercontent.com/assets/1316152/20390196/b2d2c8f4-ac9b-11e6-90fe-0867ace36aaa.png">

Final config that I deployed which finally stopped the leaks:

```
AWS.config = new AWS.Config({
  accessKeyId: config.amazon.key,
  secretAccessKey: config.amazon.secret,
  region: 'us-east-1',
  sslEnabled: false,
  httpOptions: {
    agent: new http.Agent({
      keepAlive: true
    })
  }
});
```

Relevant Versions:

Node.js v6.9.1 LTS
Aws-sdk v2.7.2
Heroku Cedar Stack - Ubuntu 14.04, 512mb RAM
Start command - `node --max_old_space_size=$WEB_MEMORY server-cluster.js`
Node cluster - yes

**Comment by chrisradek** [comment]
@AndrewBarba 
Is the script you ran in the test something you can share, or can you provide a simplified form of it so I can reproduce on my end?

Did you try setting `keepAlive` while also keeping `sslEnabled: true`?

Often times when we see reports of memory leaks, it's due to a huge number of requests being sent in a loop, faster than the connection pool can assign a socket to a request. The queue of requests can then fill up, taking up space in memory. The SDK by default will set `maxSockets` to `50` for https hosts if the global configuration is `Infinity` or undefined, which is the case by default in node v0.12 and higher. If you supply your own `https.Agent`, similar to what you're doing above, you can override `maxSockets`. Can you change the `maxSockets` value to something larger and see if the observed leak diminishes?

**Comment by AndrewBarba** [comment]
Thanks for the response @chrisradek ! So to give more context, the screenshots above are AFTER I set the WaitTime to just 1 second. I needed to do that so I could test things faster. Originally it was set to the max of 20 seconds and would still climb but obviously much more slowly, and hit the limit every 6 hours or so. We have 4 queues on that node so that was 4 https requests every 20 seconds, not exactly anything crazy... 

But to actually answer your question, no I never tried keeping SSL enabled with a custom https agent. When I read the docs regarding ssl I remember seeing that you guys use a custom agent when ssl is enabled so I wasn't sure if I should be supplying my own. With ssl off you use the global agent so I figured it didn't to give my own in that case.

Happy to test again with ssl enabled and a custom agent. I can also share the script that we use. I'll post the relevant piece below, and if you need full script let me know and I can email it to you:

```
  /**
   * @method process
   * @return SQSQueue
   */
  process(concurrency, handler) {
    if (arguments.length === 1 && _.isFunction(concurrency)) {
      handler = concurrency;
      concurrency = DEFAULT_CONCURRENCY;
    }

    let queueOptions = {
      MaxNumberOfMessages: concurrency,
      WaitTimeSeconds: DEFAULT_WAIT_TIME
    };

    this._loadQueueOptions(queueOptions)
      .then(options => {
        return sqs.receiveMessage(options).promise();
      })
      .then(data => {
        return data.Messages || [];
      })
      .mapSeries(message => {
        let body = JSON.parse(message.Body);
        return handler(body, message).reflect()
          .then(() => this.complete(message));
      })
      .finally(() => {
        process.nextTick(() => this.process(concurrency, handler));
      });
  }
```

**Comment by mdw19873** [comment]
For anyone else that comes across this, there still seems to be some kind of an issue with SQS receiving and memory leaks. Using a custom http/https agent seems to alleviate the issue. The example provided by AndrewBarba above seems to work well. In my implementation I used the following for the agent.

`new https.Agent({
  keepAlive: true,
  maxSockets: 100
})`
