### ISSUE TITLE
Cloudwatch getMetricStatistics for AWS/CloudFront doesn't return intended results

### ISSUE THREAD

**Issue by izogain** [aws/aws-sdk-js#1232]
Hi, I am using the AWS SDK in the browser (Release v2.7.3) to access cloudwatch metrics but i am getting some weird behavior.

Here is the code : 
```
    AWS.config.accessKeyId ='access key id';
    AWS.config.secretAccessKey ='secret key';
    AWS.config.region = 'us-east-1';

    var cloudwatch = new AWS.CloudWatch({apiVersion: '2010-08-01'});
    var endDate = new Date();
    var startdate = new Date();
    var durationInMinutes = 30*60;
    startdate.setMinutes(endDate.getMinutes() - durationInMinutes);

    var params = {
      EndTime: endDate,
      MetricName: 'BytesDownloaded',
      Namespace: 'AWS/CloudFront',
      Period: 300,
      StartTime: startdate,
      Statistics: [
         'Sum'
      ],
      Dimensions: [
        {
          Name: 'DistributionId',
          Value: '<Your distribution ID>'
        },
        {
          Name: 'Region',
          Value: 'Global'
        }
      ],
      Unit: 'Bytes'  //the problem
    };
    cloudwatch.getMetricStatistics(params, function(err, data) {
      if (err) console.log(err, err.stack); // an error occurred
      else     console.log(data);           // successful response
    });
```
In the code above, i am asking for the metric "BytesDownloaded" with the namespace "AWS/CloudFront"  and dimensions DistributionID / Region. The Unit to specify according to documentation is Bytes ([cloudfront cloudwatch metrics](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cf-metricscollected.html#cloudfront-metrics)), However when the Unit parameter is set, Cloudwatch returns 0 results. The only way to get results is to completely remove it or set it to None. Is this a normal behavior  of the API ?

The [documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatch.html#getMetricStatistics-property) states "If the metric only ever reports one unit, specifying a unit will have no effect.". This isn't really the case.

Note: i tried with [an S3 metric (](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/s3-metricscollected.html)AWS/S3 , BucketSizeBytes, BucketName/StorageType, Bytes) and it worked. My guess is that its only specific to cloudfront metrics. 

Thanks for your help.

**Comment by chrisradek** [comment]
Hi @izogain 
Since this is a question about the behavior of a service, please ask your question on the [AWS CloudWatch forums](https://forums.aws.amazon.com/forum.jspa?forumID=138). They will be able to better answer your question, and take feedback on improvements.
