### ISSUE TITLE
DocumentClient.createSet returns void when it should return an object.

### ISSUE THREAD

**Issue by midknight41** [aws/aws-sdk-js#1234]
I've found another bug in the TypeScript definition for DocumentClient. The AWS definition is:

```js
createSet(list: number[]|string[]|binaryType[], options: CreateSetOptions): void;
```

The DefinitelyTyped definition is:
```ts
createSet(list: any[], options?: { validate?: boolean }): { values: any[], type: string };
```
```void``` is incorrect as a return type. I'm happy to submit a PR if you want.

**Comment by chrisradek** [comment]
@midknight41 
Sure, would appreciate the PR!

**Comment by midknight41** [comment]
Will do.
