### ISSUE TITLE
AWS.config.credentials.get() resets IdentityId to null when offline.

### ISSUE THREAD

**Issue by johnborges** [aws/aws-sdk-js#1238]
This particular use case is with a Cordova/PhoneGap enabled JavaScript app.

Steps to reproduce:

1. Call `AWS.config.credentials.get()`
2. Verify CognitoIdentityCredentials exists.
3. Close app.
4. Enable Airplane Mode / Disconnect Network
5. Launch app and call `AWS.config.credentials.get()`. Produces: `Error: Network Failure(…)`. Upon inspecting `AWS.config.credentials.identityId` ends up being `null`, even though I can still see a localStorage index for the identityId.

Shouldn't the last step use the cached IdentityID which was already retrieved?

**Comment by jeskew** [comment]
When running in a single process, the call to `AWS.config.credentials.get` will not overwrite the identityId, as that is only done as part of the refresh process. In the scenario you describe, the network failure encountered is expected, and credentials.get should not be able to source any credentials. 

Are you running into the issue described in the linked amazon-cognito-js issue? I think the solution might be to add an accessor for the identityId property that reads from cache and to mark the property itself as `private`.

**Comment by johnborges** [comment]
Thank you for the clarification. And yes, the issue linked from amazon-cognito-js is where I'm encountering this.
