### ISSUE TITLE
File upload to S3 fails from Firefox and Edge

### ISSUE THREAD

**Issue by dibakardas67** [aws/aws-sdk-js#1239]
Hi,

When I am trying to upload a file from Firefox and Edge, the file upload fails. Getting a 403 forbidden error. With the same code I am able to upload files via Chrome.

Please find details of the issue below:

- Firefox Version = 50.0
- Edge Version = 25.10586.0.0
- aws-sdk Version = 2.4.8

<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>

**Request Header :** 
Content-Length 164585
Content-Type	image/jpeg
Referer http://localhost:3000/
User-Agent Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Code Snippet:**
Upload = function (file) {
        var deferred = $q.defer();
        var params = { Bucket: 'abc', Key: file.name, ContentType: file.type, Body: file };
        var options = {
            // Part Size of 10mb
            partSize: 10 * 1024 * 1024,
            queueSize: 1,
            // Give the owner of the bucket full control
            ACL: 'bucket-owner-full-control'
        };
        var uploader = bucket.upload(params, options, function (err, data) {
            if (err) {
                deferred.reject(err);
            }
            deferred.resolve();
        });
        uploader.on('httpUploadProgress', function (event) {
            deferred.notify(event);
        });
        return deferred.promise;
    };

Please let me know if this is a know issue or any fix that I can implement to get the upload going in Firefox and Edge.

Thanks You

**Comment by chrisradek** [comment]
@dibakardas67 
What does your bucket CORS configuration look like? Do you have the following in it:
```xml
        <ExposeHeader>ETag</ExposeHeader>
```

**Comment by dibakardas67** [comment]
@chrisradek - Please find my bucket CORS configurations below

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>ETag</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>

**Comment by dibakardas67** [comment]
@chrisradek  - Yes is have <ExposeHeader>ETag</ExposeHeader> in my bucket CORS configuration.
Please refer attached image for my complete CORS configuration.
![cors](https://cloud.githubusercontent.com/assets/13719174/20632955/751488e0-b367-11e6-8399-32746c460849.JPG)

**Comment by chrisradek** [comment]
@dibakardas67 
If you omit the `ContentType` from your operation parameters, does the upload work?

**Comment by dibakardas67** [comment]
@chrisradek 
I removed the ContentType from my parameters. The upload is still working in Chrome, like before.
But I am unable to upload via Firefox/Edge.

I believe this issue has got something to do with how Firefox calculates the signature. Getting below error:
The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by chrisradek** [comment]
In the callback you provide to `s3.upload`, can you log `this.httpRespose.body.toString()`? There should be more clues as to why it's failing.

Can you also try using the latest (2.7.7) version of the SDK just to verify this isn't something that's been fixed?

**Comment by dibakardas67** [comment]
@chrisradek  - using the latest (2.7.7) version of SDK fixed the issue in Edge and Firefox(Chrome and IE was working fine before as well as now also).

**But we are still facing the same issue when we upload from Android devices.**

**Comment by chrisradek** [comment]
@dibakardas67 
Can you log `this.httpResponse.body.toString()` when you upload from an Android device?

**Comment by srchase** [comment]
@dibakardas67,

Were you able to get this sorted out on Android devices?  Could you provided the logged httpResponse.body?

If this is no longer an issue, I'd like to close this out.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
