### ISSUE TITLE
When using v2.7.9 in browser, seems not to work the class of AWS.Rekognition.

### ISSUE THREAD

**Issue by north-river** [aws/aws-sdk-js#1246]
I tried it following  [this document ](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Rekognition.html).
But it seems not to work the class of AWS.Rekognition.
(I've not tried other new functions yet.)
Is this working correct?

**Comment by chrisradek** [comment]
@north-river 
The browser version of the SDK by default only includes services that are configured to support CORS.

If you're working in an environment where you know CORS won't be enforced, you can build a custom version of the browser SDK. Instructions on how to do this can be found here:
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html

We are pushing service teams to enable CORS support but I don't have an ETA on when that work will be completed.

**Comment by north-river** [comment]
@chrisradek 
I understood that. Thank you.
