### ISSUE TITLE
Feature Request: Export HttpOptions config interface

### ISSUE THREAD

**Issue by dlee-nvisia** [aws/aws-sdk-js#1250]
I'm currently working on a pull request to add typings to the [nodemailer-ses-transport](https://github.com/andris9/nodemailer-ses-transport) project. Their public interface allows either a fully-created SES instance to be passed in, or for a group of options to be passed in, which are then fed into the SES constructor. Most of those options are simple strings, and could be added easily. However, the httpOptions parameter should be typed with the HttpOptions interface found on line 80 of lib/config.d.ts

As this is not currently exported in any way from the top level index.d.ts, I'm writing this issue to gather suggestions for a fix. I'm not sure if it would be ideal to export it all by itself at the top level - perhaps some form of namespacing would be appropriate?

**Comment by chrisradek** [comment]
Since `AWS.Config` is already exposed, I think we just need to export the interfaces it uses so you can do something like `AWS.Config.HttpOptions`.

I'm all for that. If you want to submit a PR for it I'd be happy to take a look, otherwise I'll try to take a look next week.

**Comment by ajredniwja** [comment]
I see the PR was merged, closing this issue now, please reach out if you have any other questions.
