### ISSUE TITLE
Error in Class: AWS.CloudSearchDomain sdk document

### ISSUE THREAD

**Issue by Beyondlost** [aws/aws-sdk-js#1251]
Just FYI for (AWS.Request) search(params = {}, callback) in the return param its _no_fields not  no_fields

return — (String)
Specifies the field and expression values to include in the response. Multiple fields or expressions are specified as a comma-separated list. By default, a search response includes all return enabled fields (all_fields). To return only the document IDs for the matching documents, specify no_fields. To retrieve the relevance score calculated for each document, specify _score.

**Comment by chrisradek** [comment]
@Beyondlost 
Thanks for reporting this issue, it should be fixed now!
