### ISSUE TITLE
Update API Gateway putRestAPI

### ISSUE THREAD

**Issue by Titozzz** [aws/aws-sdk-js#1253]
In the documentation : (http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-documenting-api-quick-start-import-export.html)

_In addition, you can also call restapi:import or restapi:put, supplying the documentation parts in the x-amazon-apigateway-documentation object as part of the input Swagger file of the API definition. To exclude the documentation parts from the API import, set ignore=documentation in the request query parameters._

But the ignore parameter is not supported by the sdk

EDIT: fixed url 👍

**Comment by chrisradek** [comment]
@Titozzz 
Your link takes me to the API Gateway welcome page, can you update it?

**Comment by Titozzz** [comment]
To add a bit of context, I use the SDK to upload my swagger definition to AWS, but since amazon last documentation update, can't do that anymore, since It tells me I have too much documentation parts, so I just wan't to disable it for now :) !

**Comment by Titozzz** [comment]
okay, so I had to put the ignore:documentation inside the parameters object.
I think I can close the issue
