### ISSUE TITLE
typescript: error TS2304: Cannot find name 'Promise'.

### ISSUE THREAD

**Issue by yinso** [aws/aws-sdk-js#1257]
* OS: Mac El Capitan
* Node: v5.5.0
* Typescript: v2.1.4
* AWS-SDK: 2.7.12

My code includes `bluebird` and `aws-sdk` as follows:

```
import * as Promise from 'bluebird';
import * as AWS from 'aws-sdk';

...
```

Compile with typescript and it returns the following errors:

```
node_modules/aws-sdk/lib/config.d.ts(38,37): error TS2304: Cannot find name 'Promise'.
node_modules/aws-sdk/lib/request.d.ts(164,16): error TS2304: Cannot find name 'Promise'.
node_modules/aws-sdk/lib/s3/managed_upload.d.ts(15,16): error TS2304: Cannot find name 'Promise'.
```

Looks like it needs a global reference of `Promise` - how can I introduce that into aws-sdk's type definitions?

**Comment by chrisradek** [comment]
@yinso 

Are you using types with bluebird? It looks like this may be a common problem with a few workarounds when using `bluebird` as your global `Promise` library. 
See this issue for more info on some work-arounds:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10801

If you don't care about having type checks for bluebird specific promise apis, you might be able to get around the issue by including [`es2015.promise`](https://github.com/aws/aws-sdk-js/blob/master/ts/tsconfig.json#L10) in your `tsconfig.json`

**Comment by yinso** [comment]
@chrisradek - thanks for the help. I was able to make use of your second approach, which is to add `es2015.promise` to `tsconfig.json`. I also need to add `es5` in order to supress some other errors, so now it looks like this:

```
{
  "compilerOptions": {
    "lib": [
      "es5",
      "es2015.promise"
    ]
  },
  ...
}
```

This at least suppresses the compiler errors. Typescript is good but its errors can be very esoteric to fix, but that's not your issue, so hopefully I wouldn't have to ask again when I have to make future changes, but definitely thanks for the help!
