### ISSUE TITLE
Always get unable to verify the first certificate when create bucket

### ISSUE THREAD

**Issue by testtshoretel** [aws/aws-sdk-js#1258]
Is there any way I can turn off verify cert from client options? Thanks.

**Comment by testtshoretel** [comment]
@chrisradek Can you take a took? Is there any way in client options to disable certificate verification so I do not need to install cert in my development, Thanks.

**Comment by jeskew** [comment]
You can direct the SDK to use a custom HTTP(S) agent by providing it as [the `httpsOptions.agent` configuration option](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#httpOptions-property).

An example of how to customize the agent can be found [in our developer guide](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-registering-certs.html). To disable certificate verification, you would want to set `rejectUnauthorized` to `false`. Alternatively, you could use the `ca` option to provide the self-signed certificate used in your development environment.

**Comment by testtshoretel** [comment]
@jeskew Thanks. 

I added this in my code: 
   AWS.config.update({
      httpOptions: {
        agent: new https.Agent({
          rejectUnauthorized: false
        })
      }
    });

Then I createbucket with params:
{
 Bucket: "testbucket",
        ACL: 'private'
 };

I got this error:
InvalidArgument: null. 

Can you let me know if it is still my cert related error?

Thanks
