### ISSUE TITLE
Request to open-source cloudformation type definitions

### ISSUE THREAD

**Issue by dzharii** [aws/aws-sdk-js#1259]
Dear AWS-SDK Team, 

Many people, including me, find it difficult to manage their cloudformation stacks. 
Cfn in a form of a single json file does not scale, while your cfn template grows. 
Cfn stacks could be much better defined in a high level language and than composed and generated as json. 

It is necessary to have a reliable source for cfn resources and type information in order to build a high-level language bindings. 
And some projects, like botox, are scrapping the cfn reference html and generate type information files: 

https://github.com/tmont/botox/tree/890161cb98ee06e49ba17ce6573e089eab9ab2a8/scripts/scrapers/resources

While I find this implementation impressive, I doubt that  the way the type information has been obtained is reliable. 

This is why I would like to ask open source the official cfn type definitions and, possibly, include the type and resource definitions  as a part of the aws sdk. 

Kind regards, 
@dzharii

**Comment by chrisradek** [comment]
@dzharii 
Thanks for the request!
It looks like CloudFormation has a repo with some sample templates: https://github.com/awslabs/aws-cloudformation-templates

This might be a good place to ask to open source the official type definitions. You can also post to the [AWS CloudFormation forums](https://forums.aws.amazon.com/forum.jspa?forumID=92).

For our part, I can forward this request on to their team.
