### ISSUE TITLE
Does upload() verify checksum?

### ISSUE THREAD

**Issue by ox42** [aws/aws-sdk-js#1260]
Hello,
   first of all, I apologize if this is answered somewhere - i tried googling it, looking at previous issues, and the documentation for the AWS JavaScript SDK. 
   I have a question. By default, when doing s3.upload() of a large file, are there any checks in place that verify that the file has been uploaded correctly - an MD5 check or something? (i.e. s3.upload() does "Upload an arbitrarily sized buffer, blob, or stream, using intelligent concurrent handling of parts if the payload is large enough.").

   The documentation does not make this obvious. As a matter of fact, there is a parameter for s3.upload() that says "ContentMD5 — (String) The base64-encoded 128-bit MD5 digest of the part data.", but even if I want to fill that with an md5 value that I calculate, I'm not sure what "part data" means, should I put the entire file checksum there, etc.

   When I login to the S3 console (the UI on console.aws.amazon.com) and look at files, I cannot find any metadata (headers or something) sent by the s3.upload() call, but that may be because on the project we use a bit older version of the SDK. There is an etag, but I believe that is calculated on the AWS size.

   Thanks.

**Comment by jeskew** [comment]
Hi @ox42,

ContentMD5 isn't stored as metadata on the object in S3. It's used by Amazon S3 on individual HTTP requests to ensure that the request body was not corrupted in transit: [when S3 receives a request with a `Content-Md5` header, it will hash the request body and compare the two values](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html). The SDK will compute this value for you by default, so it's not something you would need to specify when upload an object to S3. Unless you explicitly set the [computeChecksums config property](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#computeChecksums-property) to `false`, an integrity check will be performed on each part of the large file that is uploaded.
