### ISSUE TITLE
Question: Exponential backoff for DynamoDB would be triggered only if the entire items from a batchWrite() call failed or even if just some items failed? 

### ISSUE THREAD

**Issue by develoser** [aws/aws-sdk-js#1262]
Got a question about **DynamoDB.batchWrite()**, the SDK exponential backoff is only triggered when the whole batch of items failed or it would be also triggered even when just a few items failed to be written?

I saw [this previous questions](https://github.com/aws/aws-sdk-js/issues/402) and realized the SDK can handle retries, but is not clear to me if it handles all scenarios:

a) all items failed
b) just some items failed

I wanna know if I need to write my own exponential backoff handler when the batchWrite() returns some *"UnprocessedItems"*, in order to do not end up coding what the SDK already does or to lose *UnprocessedItems* assuming the SDK is doing something it is not.

Thanks in advance.

**Comment by jeskew** [comment]
The SDK will only retry requests that fail with a status code of 429 or 500 or greater. If only some writes in a batch failed, the request is considered by the service to have succeeded and is therefore not retried.

Retrying items in the `UnprocessedItems` list in the response would need to be handled in the code that is calling `batchWrite`.

**Comment by develoser** [comment]
Thank you so much, it's clear now.
