### ISSUE TITLE
Cloudfront updateDistribution() impossible

### ISSUE THREAD

**Issue by georgesben** [aws/aws-sdk-js#1263]
Hi everybody !

I'm sorry to trouble you but I have a little with the updateDistribution() method (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront.html#updateDistribution-property).
I have tried to update my distribution to disable it. But I have received erros like I was missing some fields. At the end, I have put all the fields (I don't know if is it normal even for the non-required fields).
Now, I have a big problem because the sdk says I'm must have `Origins` and `CallerReference`, but if I do so, I have this error:
```
{ IllegalUpdate: You cannot update Origin or CallerReference.
    at Request.extractError (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\protocol\rest_xml.js:44:29)
    at Request.callListeners (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\request.js:668:14)
    at Request.transition (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\request.js:670:12)
    at Request.callListeners (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
  message: 'You cannot update Origin or CallerReference.',
  code: 'IllegalUpdate',
  time: 2016-12-12T21:27:12.256Z,
  requestId: 'beece864-c0b1-11e6-a851-09521e8d47bf',
  statusCode: 400,
  retryable: false,
  retryDelay: 18.587123688744445 }
```

Can someone help me ?
Regards :)

**Comment by chrisradek** [comment]
@georgesben 
Since this is a question about how to use a service's api, you'll be able to get better advice on the [`Amazon CloudFront forums`](https://forums.aws.amazon.com/forum.jspa?forumID=46).

Looking at the docs for `updateDistribution`, I'm not sure you can disable a distribution using this method. The `Enabled` field says:

> Specifies whether you want CloudFront to save access logs to an Amazon S3 bucket.

The service forums should be able to give you better advice on how to disable a distribution.

**Comment by georgesben** [comment]
But there is a problem with the sdk which asks field non-required. For example, this is my JSON:
```
let params = {
                DistributionConfig: { /* required */
                    CallerReference: new Date().toString(), /* required */
                    Comment: 'disable cloudfront', /* required */
                    DefaultCacheBehavior: { /* required */
                        ForwardedValues: { /* required */
                            Cookies: { /* required */
                                Forward: 'none', /* required */
                            },
                            QueryString: false, /* required */
                        },
                        MinTTL: 0, /* required */
                        TargetOriginId: "S3-" + zipBucketName, /* required */
                        TrustedSigners: { /* required */
                            Enabled: false, /* required */
                            Quantity: 0, /* required */
                        },
                        ViewerProtocolPolicy: 'allow-all', /* required */
                        Compress: false,
                    },
                    Enabled: false, /* required */
                    Origins: { /* required */
                        Quantity: 1, /* required */
                        Items: [
                            {
                                DomainName: zipBucketName + ".s3.amazonaws.com", /* required */
                                Id: "S3-" + zipBucketName, /* required */
                                S3OriginConfig: {
                                    OriginAccessIdentity: '' /* required */
                                }
                            },
                            /* more items */
                        ]
                    },
                    DefaultRootObject: '',
                    PriceClass: 'PriceClass_100',
                },
                Id: id, /* required */
                IfMatch: data.ETag
            };
```

I have the following error:
```
{ IllegalUpdate: Aliases are missing for the resource.                                                       
    at Request.extractError (E:\GitHub\partyhard\cli\node_modules\aws-sdk\lib\protocol\rest_xml.js:44:29)    
    at Request.callListeners (E:\GitHub\partyhard\cli\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (E:\GitHub\partyhard\cli\node_modules\aws-sdk\lib\sequential_executor.js:77:10)          
    at Request.emit (E:\GitHub\partyhard\cli\node_modules\aws-sdk\lib\request.js:668:14)                     
    at Request.transition (E:\GitHub\partyhard\cli\node_modules\aws-sdk\lib\request.js:22:10)                
    at AcceptorStateMachine.runTo (E:\GitHub\partyhard\cli\node_modules\aws-sdk\lib\state_machine.js:14:12)  
    at E:\GitHub\partyhard\cli\node_modules\aws-sdk\lib\state_machine.js:26:10                               
    at Request.<anonymous> (E:\GitHub\partyhard\cli\node_modules\aws-sdk\lib\request.js:38:9)                
    at Request.<anonymous> (E:\GitHub\partyhard\cli\node_modules\aws-sdk\lib\request.js:670:12)              
    at Request.callListeners (E:\GitHub\partyhard\cli\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
  message: 'Aliases are missing for the resource.',                                                          
  code: 'IllegalUpdate',                                                                                     
  time: 2016-12-15T17:45:26.882Z,                                                                            
  requestId: '46f6c0a0-c2ee-11e6-bff2-a73c203c5e7b',                                                         
  statusCode: 400,                                                                                           
  retryable: false,                                                                                          
  retryDelay: 76.41972873266478 }                                                                            
```

But, if you look at the doc, you can see that the field is not mandatory.


NB: You have look at the `Loggin.Enable`, I'm using just the field Enable which is:

**Comment by dinvlad** [comment]
Could we please re-open this issue? IfMatch is still indicated as non-required field. Since the API lists it as required, it should also be indicated as such in the JS SDK. Thanks!

**Comment by jeskew** [comment]
Hi @dinvlad,

In CloudFront's API documentation for both updateCloudFrontOriginAccessIdentity and deleteCloudFrontOriginAccessIdentity, the IfMatch parameter is listed as optional. The error message you received does seem to indicate that IfMatch must always be specified, but that may not be true in all cases. You might want to try reporting this in the [CloudFront AWS forum](https://forums.aws.amazon.com/forum.jspa?forumID=46) if you believe that the IfMatch parameter has been mislabeled.

**Comment by dinvlad** [comment]
Sorry for stealing the thread - I can either create a new issue, or just post it on the forums. Although I do believe there are problems with this SDK's documentation and/or typings:

1) the official API doc for `DeleteCloudFrontOriginAccessIdentity` (not `Update`, sorry) does list `If-Match` as a required parameter: http://docs.aws.amazon.com/cloudfront/latest/APIReference/API_DeleteCloudFrontOriginAccessIdentity.html#API_DeleteCloudFrontOriginAccessIdentity_RequestSyntax
> The request **requires** the following URI parameters.
Id
If-Match

2) For the `updateCloudFrontOriginAccessIdentity()` call, it incorrectly implies that `CallerReference` must be _unique_ per update _request_, and if the contents of `CloudFrontOriginAccessIdentityConfig` changes then this request will fail with `CloudFrontOriginAccessIdentityAlreadyExists`. In fact, the SDK errors out when I specify a _new_ value for `CallerReference`, saying that `You cannot update the value of CallerReference`. However, when I specify the _old_ `CallerReference`, and a new `Comment`, it updates successfully, despite that the doc implies that such request would fail. So the behavior described in the doc for that method is the opposite to what happens in practice.

Please let me know if I should delegate it to the forums or create a new issue here.
Thanks

**Comment by dinvlad** [comment]
Sorry for stealing the thread - I thought that it was about If-Match field, while it's just the same error message.
