### ISSUE TITLE
Outbound Rules for a Security Group

### ISSUE THREAD

**Issue by riteshatsencha** [aws/aws-sdk-js#1265]
Seems like there is a bug in outbound rules for a security group. This is on AWS EC2 console.

1) I added 3 rules. All good.
2) Removed IPV6 rule and see an error while trying to save the rules.
3) Removed all rules and still see an error on the save.

Keeps showing no changes were made. Actually, I removed rule(s). So yes, there are changes. Am I missing something? 

Thx

![orig-outbound-rules](https://cloud.githubusercontent.com/assets/14277904/21123593/a611b5ec-c0a7-11e6-95d5-0eea0092498e.jpg)
![removed-ipv6-rule](https://cloud.githubusercontent.com/assets/14277904/21123602/b45346e8-c0a7-11e6-8120-cdd118a8eacc.jpg)
![error-after-removed-all](https://cloud.githubusercontent.com/assets/14277904/21123610/c03031d8-c0a7-11e6-9100-0a22446008bd.jpg)

**Comment by jeskew** [comment]
Did you see a similar issue using the AWS SDK for JavaScript, or was the error only encountered when performing these operations in the AWS console?

**Comment by riteshatsencha** [comment]
I can try with the SDK and let you know. Where exactly do I report issues with the console?

**Comment by jeskew** [comment]
When you sign into the console, there's a link to submit feedback on the landing page. Since this isn't an issue with the SDK, going through AWS support or console feedback will be a better way to get the issue you encountered addressed.

![console_landing](https://cloud.githubusercontent.com/assets/705500/21123814/db5a6cde-c08f-11e6-8ef9-15c514177445.jpg)

**Comment by riteshatsencha** [comment]
Thank you. What is the response time?

**Comment by riteshatsencha** [comment]
Yeah, so I am a basic support client. Therefore, can't really contact technical support and if I simply submit a feedback then I have to pretty much "write the whole story" without images. 

As a client I saw an issue and thought should be fixed: whether it's with an API or UI. Isn't it AWS's responsibility to communicate the issue among their teams?

Stumped!

**Comment by jeskew** [comment]
In that case, the best way to contact the service team directly is through their [AWS customer forum](https://forums.aws.amazon.com/forum.jspa?forumID=30), which is monitored and tracked by EC2 engineers. Unfortunately, individual AWS services do not monitor GitHub issues on any of the AWS SDKs, so they would not be able to respond here.

If you ask a question in the forum, please post a link here and I'll make sure to notify EC2 internally as well.

**Comment by riteshatsencha** [comment]
Thank you. Reported via feedback and put the link to this issue. Hopefully someone will take care of it.

**Comment by riteshatsencha** [comment]
Oh here is the [link](https://forums.aws.amazon.com/thread.jspa?threadID=244894) to the issue on support forum.

**Comment by jeskew** [comment]
Thanks for opening communication with the EC2 team on the forum. I sent them an email as well providing a link to this issue as context.
