### ISSUE TITLE
how to create multiple folder within s3 bucket

### ISSUE THREAD

**Issue by zymr-keshav** [aws/aws-sdk-js#1266]
I am using aws sdk and create a file within a folder and done successfully.  what i am lokking is there any way/ method by which we can create multiple folder  excpet looping the same function for various folder.
 here is my code to create a directory and a file
 ```
              createDirectory: function(base) {
                    var dir = encodeURIComponent(base) + '/';
                    var promise = s3.putObject({ Key: dir}).promise();
                    return $q.when(promise);
                },

                writeFile: function(folderName, fileName, fileContent) {
                    var folder = encodeURIComponent(folderName) + '/';
                    var key = folder + fileName;
                    var params = {
                        Key: key,
                        Body: fileContent,
                        ACL: "private",
                        ContentType: "text/plain"
                    };
                    var promise = s3.putObject(params).promise();
                    return $q.when(promise);
                },
```

even there is `copyObject` method but it copy to one folder only; i want o copy to multiple folder.

**Comment by chrisradek** [comment]
@zymr-keshav 
If you're trying to create nested directories, you can create them at once.

For example:
```javascript
s3.putObject({
  Key: 'folderA/subfolder/'
});
```
should create directories `folderA->subfolder` even if `folderA` doesn't exist.

If you're trying to create multiple folders that are siblings, then you'll have to use the method you're already using.

The SDK doesn't currently expose an interface for copying/uploading/deleting multiple files at once.

**Comment by zymr-keshav** [comment]
Thanks @chrisradek for the response. Yes i want to create sibling folders and that is not yet supported as you said. I will go with the `.putObject()`  in loop.
