### ISSUE TITLE
Plans for Athena support

### ISSUE THREAD

**Issue by devhyunjae** [aws/aws-sdk-js#1270]
Interested in the new aws service [Atena](https://aws.amazon.com/athena/).

But it seems like, it only supports JDBC

https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html

Any plans for javascript client?

**Comment by jeskew** [comment]
Hi @devhyunjae,

Could you tell me a bit more about what kind of support would you be looking for in JavaScript? Athena is meant to be accessed via a database client, so, like with RDS, the AWS SDK does not provide a means to query the data plane of the service.

**Comment by devhyunjae** [comment]
Ok i got it. I was hoping programatical query...😢

**Comment by jeskew** [comment]
You could try one of the JDBC wrappers available on [npm](https://www.npmjs.com/search?q=jdbc). Those would allow you to send SQL queries to Athena.

**Comment by jeskew** [comment]
Support for querying over an API was added in [version 2.54.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#2540)

**Comment by rebeccacaroline** [comment]
@jeskew is there any documentation or code examples for querying athena over an API?

**Comment by jeskew** [comment]
@rebeccacaroline There's API documentation for the JavaScript client accessible [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Athena.html), but you might also want to take a look at [this blog post on how to write Athena SQL queries](https://aws.amazon.com/blogs/aws/amazon-athena-interactive-sql-queries-for-data-in-amazon-s3/).

**Comment by rebeccacaroline** [comment]
@jeskew thank you, this is very helpful!
