### ISSUE TITLE
Breaking change of setPromisesDependency() in patch version update

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [aws/aws-sdk-js#1274]
A breaking change was added to the `setPromisesDependency()` and pushed as a patch version update of the `aws-sdk` NPM module in version `v2.6.12` and every version since.

Previously, it was possible to use the native Node.js implementation of the `Promise` object by specifying `null` as the `PromiseDependency` argument of the `addPromises()` function which `setPromisesDependency()` proxies to like this:

```
const AWS = require('aws-sdk');
const sqs = new AWS.SQS();

sqs.config.setPromisesDependency(null);
```

This behaviour was allowed by this line of code up until `v2.6.11`:

https://github.com/aws/aws-sdk-js/blob/v2.6.11/lib/util.js#L753

It was even publicised in the Node.js examples in the Promise support announcement on the official AWS blogpost:

https://aws.amazon.com/blogs/developer/support-for-promises-in-the-sdk/

After `v2.6.12`, only `undefined` (and of course passing the `Promise` object directly) is allowed as a value to default to the native Node.js implementation:

https://github.com/aws/aws-sdk-js/blob/v2.6.12/lib/util.js#L755

The previous snippet would then have to be changed to this to keep the same behaviour:

```
const AWS = require('aws-sdk');
const sqs = new AWS.SQS();

sqs.config.setPromisesDependency();
```
This week some of our long running apps crashed due to this breaking change.

I wonder if it would be possible to add a mention of this in the Changelogs maybe or even allow `null` back as a possible value for the `dep` argument?

The individual commit that broke `v2.6.12` is the following: https://github.com/aws/aws-sdk-js/commit/b0ad8bc1b381ffd5cb1361efe527a9197d5cf205#diff-3deb3f32958bb937ae05c6f3e4abbdf5R754

**Comment by chrisradek** [comment]
@Mickael-van-der-Beek 
Thanks for reporting this issue and sorry for the problems it caused you. I don't believe disallowing `null` was intentional. I'll mark this as a bug and we'll allow `null` again.
