### ISSUE TITLE
Missing Typescript Definition for HttpClient, as well as documentation

### ISSUE THREAD

**Issue by mboudreau** [aws/aws-sdk-js#1278]
There seems to be a succinct lack of documentation around this very helpful utility class: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/HttpClient.html

I've been trying to use it with my new typescript lambda project to be able to mock the responses for unit testing, but it seems to be missing the definition file as well, giving me a compilation error.

Guess in the meantime I'll just fork my own :/

**Comment by jeskew** [comment]
Hi @mboudreau,

I'll look into how much of the HttpClient interface can be effectively documented. The two provided implementations (one for [node](https://github.com/aws/aws-sdk-js/blob/master/lib/http/node.js) and one for [browsers](https://github.com/aws/aws-sdk-js/blob/master/lib/http/xhr.js)) differ significantly, and and TS definition would only be able to cover the overlap between the two.

**Comment by TomBeckett** [comment]
Still very much an issue in 2021.

**Comment by ealiaga** [comment]
I solved it this way:

``` typescript
 // @ts-ignore
 const client = new AWS.HttpClient();
 ```
 
 also depending on your eslint configuration you may need to override the rule: 
 ```
 / * eslint-disable @typescript-eslint/ban-ts-ignore * /
 ```

**Comment by mboudreau** [comment]
> I solved it this way:
> 
> ```ts
>  // @ts-ignore
>  const client = new AWS.HttpClient();
> ```
> 
> also depending on your eslint configuration you may need to override the rule:
> 
> ```
> /* eslint-disable @typescript-eslint/ban-ts-ignore */
> ```

That's not solving it, you're just completely ignoring typescript which is the point of the original issue.
