### ISSUE TITLE
API call for instance type

### ISSUE THREAD

**Issue by riteshatsencha** [aws/aws-sdk-js#1280]
Hi,

From the forum I understand there is no API call for retrieving instance-types. (t2.nano, t2.micro ... etc). Is there a plan to add that to the api? 

Or is it already in the api and I can't find it?

Thank you

**Comment by chrisradek** [comment]
@riteshatsencha 
Have you posted a feature request on the EC2 forums? This is something that EC2 would need to support on their end.

If you post to their forums, feel free to respond with the link here and I can forward it to the EC2 team.
