### ISSUE TITLE
AWS.config.update() type definition is missing CredentialsOptions

### ISSUE THREAD

**Issue by yangchristian** [aws/aws-sdk-js#1284]
Per [docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property) and [implementation](https://github.com/aws/aws-sdk-js/blob/master/lib/config.js#L372), `AWS.config.update()` should support the credentials keys like `accessKeyId` and `secretAccessKey` directly.

Minimal repro:
```ts
import * as aws from 'aws-sdk';
aws.config.update({
  accessKeyId: 'abc123',
  secretAccessKey: 'abc123',
});
```

Results in:

> [ts]
Argument of type '{ accessKeyId: any; secretAccessKey: any; region: any; }' is not assignable to parameter of type 'ConfigurationOptions & ConfigurationServicePlaceholders & APIVersions'.
  Object literal may only specify known properties, and 'accessKeyId' does not exist in type 'ConfigurationOptions & ConfigurationServicePlaceholders & APIVersions'.

I should have a quick PR ready soon.

**Comment by chrisradek** [comment]
Closing since this was added with #1285. Thanks for the PR!
