### ISSUE TITLE
Error: One or more parameter values were invalid: An AttributeValue may not contain an empty string

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-js#1287]
This is related to #833 no doubt, but here I am using AWS SDK version: 2.7.20 with **convertEmptyValues: true**

https://static.spuul.com/devops/2017-01-04/convertEmptyValues.log

Is there something I've forgotten? I was hoping to avoid manually removing key with empty values.

**Comment by jeskew** [comment]
Hi @kaihendry,

There was a bug in how convertEmptyValues operated on members of maps and lists that was fixed in 2.7.21, which was just released. Could you upgrade and see if that fixes the issue for you?

**Comment by kaihendry** [comment]
Thank you, 2.7.21 seems to work.
