### ISSUE TITLE
endpoints.json

### ISSUE THREAD

**Issue by wadeharrell** [aws/aws-sdk-js#129]
It would be valuable to have a mirror of https://github.com/aws/aws-sdk-ruby/blob/master/endpoints.json available in this SDK.

**Comment by lsegal** [comment]
Sorry about the delay in responding to this issue!

Given the simple workaround above we've decided that we're going to leave this out of the SDK for now. Creating a third-party plugin via an external npm package might be the best way to support this in the community if users are still looking for this behavior. We'd be happy to see it turned into a third-party npm package. If it was popular enough, we could look at merging it in at that point.
