### ISSUE TITLE
downloading RDS logs; DownloadCompleteDBLogFile missing?

### ISSUE THREAD

**Issue by hulbert** [aws/aws-sdk-js#1292]
I'm having trouble downloading the whole file (I'm using the marker but still never end up w/ more than 10k lines). I see this (http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/RESTReference.DownloadCompleteDBLogFile.html) but it's not documented in the SDK?

**Comment by chrisradek** [comment]
@hulbert 
None of the SDKs support the `DownloadCompleteDBLogFile` operation at this time, but calling [`downloadDBLogFilePortion`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS.html#downloadDBLogFilePortion-property) with pagination should work.

Can you share your code snippet of how you're downloading the log file? The docs do mention that up to 1 MB of data will be downloaded, so if your logs hit 1 MB before reaching 10,000 lines, you'll get less than that.

**Comment by hulbert** [comment]
Here's what I'm trying:

```js
function downloadLogFile(databaseId, logFileName, outputStream) {
    return new Promise(function(resolve, reject) {
        let callIter = 0 
        
        function download(marker) {
            console.log('call #' + callIter)
            callIter++
            
            rds.downloadDBLogFilePortion({
                DBInstanceIdentifier: databaseId,
                LogFileName: logFileName,
                Marker: marker
            }, function(err, data) {
                if (err) {
                    return reject(err)
                }
            
                const logData = data.LogFileData
                const marker = data.Marker
                const isAdditionalData = data.AdditionalDataPending
                
                outputStream.write(logData, function(err) {
                    if (err) {
                        return reject(err)
                    }
                    
                    if (isAdditionalData === false) {
                        outputStream.end('\n')
                        
                        return resolve()
                    }
                    
                    download(marker)
                })
            })
        }
        
        download()
    })
}
```

AFAICT pagination doesn't work the same as I've used in past where the callback has pagination info on the bound context, but maybe I'm overlooking something

**Comment by hulbert** [comment]
This change seems to end up with files of the correct size—I assume it triggers it to start from the beginning rather than tail end of the log?

```diff
-                Marker: marker,
+                Marker: marker || '0'
```

**Comment by hulbert** [comment]
And a slightly more elegant solution using the SDK's paging:

```js
function downloadLogFile(databaseId, logFileName, outputStream) {
    return new Promise(function(resolve, reject) {
        outputStream.on('error', function(err) {
            reject(err)
        })

        // bound w/ AWS#Response
        // recurses itself if more pages
        // ends the outputStream when done
        function pageCb(err, data) {
            if (err) {
                return reject(err)
            }

            outputStream.write(data.LogFileData, err => {
                if (err) {
                    return reject(err)
                }

                if (this.hasNextPage()) {
                    return this.nextPage(pageCb)
                }

                // otherwise we've completed this file
                outputStream.end('\n')
                resolve()
            })
        }

        rds.downloadDBLogFilePortion({
            DBInstanceIdentifier: databaseId,
            LogFileName: logFileName,
            Marker: '0'
        }, pageCb)
    })
}
```

**Comment by jeskew** [comment]
The link you posted to the API reference for `DownloadCompleteDBLogFile` now redirects to the RDS user guide, so I guess they really want customers to use `DownloadDBLogFilePortion` :)

You're correct about needing to set `Marker` to `'0'`: omitting both `NumberOfLines` and `Marker` will cause the most recent lines (up to 10K) to be downloaded, whereas setting `Marker` to `'0'` instructs RDS to read from the head of the file rather than the tail. (This is discussed in the `NumberOfLines` section of [the REST API reference for the operation](http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DownloadDBLogFilePortion.html)).

Please feel free to reopen if you have any questions or concerns.
