### ISSUE TITLE
Lambda.updateFunction(Configuration/Code) started throwing "InvalidParameterValueException: SubnetIds and SecurityIds must coexist or be both empty list."

### ISSUE THREAD

**Issue by jcready** [aws/aws-sdk-js#1293]
This just started happening today 2017-01-10 (someone else also [posted in the AWS Developer Forums](https://forums.aws.amazon.com/thread.jspa?threadID=246719)). No code has been changed and it was working yesterday.

Here is the response body from AWS:

```js
{
	"message": "SubnetIds and SecurityIds must coexist or be both empty list.",
	"code": "InvalidParameterValueException",
	"time": "2017-01-10T11:07:59.046Z",
	"requestId": "0ac2f734-d725-11e6-a3f1-316b78af70c0",
	"statusCode": 400,
	"retryable": false,
	"retryDelay": 25.95228413119912
}
```

**Comment by chrisradek** [comment]
@jcready 
Thanks for reporting this issue. This appears to be a service-side issue, so I'm forwarding this issue and the forums link to the Lambda team.

I'm closing this issue since we can't do anything to fix this from the SDK side, but leaving feedback on that forums thread would be helpful.
