### ISSUE TITLE
Receiving falsy error and empty object from Firehose putRecordBatch

### ISSUE THREAD

**Issue by loopsysdev** [aws/aws-sdk-js#1299]
Once in a while (twice in us-east-1 overnight, at 2017-01-13T03:07:43.538Z and 2017-01-13T03:39:46.855Z, during a two-hour period in which the system sent about 20,000 batches, evenly distributed) it seems the callback passed to `putRecordBatch` receives

1. a falsy `err` parameter and
1. an empty object (`{}`) `data` parameter.

This violates the [contract](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Firehose.html#putRecordBatch-property).

Using aws-sdk version 2.7.21.

**Comment by jeskew** [comment]
Hi @loopsysdev,

Just to make sure I understand correctly, the `PutRecordBatch` did not encounter an error but also did not return the appropriate output data? The SDK does not validate the responses returned from services, so we would not convert an empty response to an error, but this is likely something the service team will need to look into. Do you have any additional information logged about the failed batches that could assist the service team in investigating the issue?

**Comment by loopsysdev** [comment]
Yes, that's correct. I've reported the issue to AWS, and will be following up on that side. I'll reopen this if that doesn't lead anywhere.
