### ISSUE TITLE
CopySource fails with special characters

### ISSUE THREAD

**Issue by Janpot** [aws/aws-sdk-js#1302]
I'm using following function:

```js
function putObject (options) {
  var keys = Array.isArray(options.Key) ? options.Key : [ options.Key ];
  var [ mainKey, ...copyKeys ] = keys;
  return s3.putObject(Object.assign({}, options, { Key: mainKey })).promise()
    .then(() => {
      return Promise.all(copyKeys.map(copyKey => {
        return s3.copyObject({
          Bucket: options.Bucket,
          CopySource: `${options.Bucket}/${mainKey}`,
          Key: copyKey
        }).promise();
      }));
    });
}
```

Which basically extends the `putObject` to allow for multiple `Key`s.

My keys have special characters in them like `%2F` and this function fails on those, to fix it I need to urlencode `CopySource`. This doesn't seem like expected behavior;

```js
function putObject (options) {
  var keys = Array.isArray(options.Key) ? options.Key : [ options.Key ];
  var [ mainKey, ...copyKeys ] = keys;
  return s3.putObject(Object.assign({}, options, { Key: mainKey })).promise()
    .then(() => {
      return Promise.all(copyKeys.map(copyKey => {
        return s3.copyObject({
          Bucket: options.Bucket,
          CopySource: encodeURIComponent(`${options.Bucket}/${mainKey}`),
          Key: copyKey
        }).promise();
      }));
    });
}
```

**Comment by jeskew** [comment]
You will need to URL encode the CopySource parameter before passing it as an argument to the s3.copyObject. Having the SDK handle this for you would be ideal but would unfortunately be a breaking change for anyone currently URL encoding parameters. Please see https://github.com/aws/aws-sdk-js/issues/712 for further discussion and a workaround.

**Comment by Janpot** [comment]
@jeskew Why don't you do it on a major release then?

**Comment by jeskew** [comment]
That's fair. I'll leave this open as a feature request and tag it as needing a version bump.

**Comment by misantronic** [comment]
@jeskew I am facing the same issue. Nevertheless, the workaround does not work for me. Please see my code:

```js
s3.copyObject(
    {
        Bucket: 'MyBucket',
        CopySource: encodeURIComponent(`MyBucket/verschwörung/verschwörung-aaae4e29.pdf}`),
        Key: 'verschwörung/verschwörung-aaae4e29.pdf',
        MetadataDirective: 'REPLACE',
        ACL: 'public-read',
        ContentType: 'application/pdf',
        ContentDisposition: `attachment; filename="verschwörung-aaae4e29.pdf"
    },
    err => {
        ...
    }
);
```

I am not sure what's wrong with my code.

**Comment by trivikr** [comment]
We tried to fix this in V3 in https://github.com/aws/aws-sdk-js-v3/pull/282, but decided not to go ahead because of the complexity described in https://github.com/aws/aws-sdk-js-v3/pull/282#discussion_r298750313

**Comment by n1ru4l** [comment]
Since nobody actually posted a solution 🤷‍♂️

```js
import { uriEscapePath } from "aws-sdk/lib/util";

s3
    .copyObject({
      Bucket: SOURCE_BUCKET,
      Key: key,
      CopySource: uriEscapePath(`${SOURCE_BUCKET}/${key}`)
    });
```

**Comment by JCLimpide** [comment]
Still the same issue in Aug 2022, thx @n1ru4l  for the fix
