### ISSUE TITLE
Can we set a Timeout value to sqs.receiveMessage ?

### ISSUE THREAD

**Issue by wahengchang** [aws/aws-sdk-js#1304]
I am running a worker, which uses sqs.receiveMessage and works well. 
However, if there is a Timeout error, for example download file online, Timeout might happen in http request. and the worker is going to wait for every.

```
var AWS = require('aws-sdk');
AWS.config.loadFromPath('./config.json');

var sqs = new AWS.SQS({apiVersion: '2012-11-05'});
var queueURL = "myurl";

var params = {
 AttributeNames: [
    "SentTimestamp"
 ],
 MaxNumberOfMessages: 1,    // how many messages do we wanna retrieve?
 MessageAttributeNames: [
    "All"
 ],
 QueueUrl: queueURL,
 VisibilityTimeout: 0,      // seconds - how long we want a lock on this job
 WaitTimeSeconds: 0          // seconds - how long should we wait for a message?
};

sqs.receiveMessage(params, function(err, data) {
  if (err) {
    console.log("Receive Error", err);
  } else {

    console.log(data)

    var deleteParams = {
      QueueUrl: queueURL,
      ReceiptHandle: data.Messages[0].ReceiptHandle
    };
    sqs.deleteMessage(deleteParams, function(err, data) {
      if (err) {
        console.log("Delete Error", err);
      } else {
        console.log("Message Deleted", data);
      }
    });
  }
});

```

**Comment by jeskew** [comment]
Hi @wahengchang,

I see that you're setting the `VisibilityTimeout` to 0 in the code snippet above. Is that the timeout you want to change?

**Comment by jeskew** [comment]
Closing due to age. 

I believe the timeout you're asking about is the `VisibilityTimeout` passed to `sqs.receiveMessage`. It represents the number of seconds for which the message should be considered "in flight" and is set to 0 in the snippet above. You can change that to a different integer as necessary.
