### ISSUE TITLE
syntaxerror-unexpected-token-in-json-at-position-0/

### ISSUE THREAD

**Issue by dsouzamanish** [aws/aws-sdk-js#1305]
Hello,
         I am sometimes getting the above error when trying to search in dynamo table by mobile number using following query. The error doesnot occur every time the query is executed. 
`{
    TableName: 'tablename',
    IndexName: 'mobile_email',
    KeyConditionExpression: '#mobile = :mobile',
    ExpressionAttributeNames: {
        '#mobile': 'mobile'
    },
    ExpressionAttributeValues: {
        ':mobile': '8xxxxxxxx9'
    }
}  `     

mobile_email index is a globalSecondary index with schema as below:
`{
    IndexName: "mobile_email",
    KeySchema: [{
        AttributeName: "mobile",
        KeyType: "HASH"
    }, {
        AttributeName: "email",
        KeyType: "RANGE"
    }, ],
    Projection: {
        "ProjectionType": "ALL"
    },
    ProvisionedThroughput: {
        "ReadCapacityUnits": 1,
        "WriteCapacityUnits": 1
    }
}`

Error stack trace is as below : 
{ SyntaxError: Unexpected token < in JSON at position 0
   at Object.parse (native)
   at Request.extractError (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/protocol/json.js:29:18)
   at Request.callListeners (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
   at Request.emit (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
   at Request.emit (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/request.js:668:14)
   at Request.transition (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/request.js:22:10)
   at AcceptorStateMachine.runTo (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/state_machine.js:14:12)
   at /home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/state_machine.js:26:10
   at Request.<anonymous> (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/request.js:38:9)
   at Request.<anonymous> (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/request.js:670:12)
   at Request.callListeners (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
   at Request.emit (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
   at Request.emit (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/request.js:668:14)
   at Request.transition (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/request.js:22:10)
   at AcceptorStateMachine.runTo (/home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/state_machine.js:14:12)
   at /home/ubuntu/deploy/serving/users/node_modules/aws-sdk/lib/state_machine.js:26:10
 message: 'Unexpected token < in JSON at position 0',
 code: 'SyntaxError',
 time: 2017-01-17T11:19:00.380Z,
 statusCode: 412,
 retryable: false,
 retryDelay: 0 }

**Comment by dsouzamanish** [comment]
After some debugging we found error in file  aws-sdk/lib/protocol/json.js at line no 29.
`var e = JSON.parse(httpResponse.body.toString());`
 Here it is trying to parse response from dynamo. However dynamo returns following error which is in xml.
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PreconditionFailed</Code><Message>At least one of the pre-conditions you specified did not hold</Message><Condition>Bucket POST must be of the enclosure-type multipart/form-data</Condition><RequestId>26B96E8FF1A4AF11</RequestId><HostId>K2Ln02V9/B3vhRUk++ydbC//xR7G23otWRqnsa0fyd+O2qqNuoCnyN1y6rKgKznhoFQLYU6naU4=</HostId></Error>`

**Comment by jeskew** [comment]
Dynamo errors are supposed to be JSON encoded, so I've reached out to that team to ask what might be causing the underlying issue. I will update this ticket when I hear back from them.

**Comment by jeskew** [comment]
@dsouzamanish 
Are you using any other SDK services in the same process as the one querying Dynamo?

**Comment by dsouzamanish** [comment]
Yes we are also using s3 service to download images from s3. On furrher
debugging of issue it was found dat whenever we request for resource not
available at s3 such error is returned and then for all subsequent requests
after the error; to the dynamo fail returning with same error.
Althought different clients of aws-sdk have been instantiated it somehow
mixes the error messeges with dynamo requests

**Comment by chrisradek** [comment]
@dsouzamanish 
Can you share a code snippet of how you're calling S3 and DynamoDB? Are you calling S3 or DynamoDB in the callback of the other service?

**Comment by jeskew** [comment]
@dsouzamanish 
One more question: are you setting a custom endpoint for S3 using `AWS.config.update`?

**Comment by wrosb** [comment]
Hello guys, i reported similar issue with CloudWatch Service. here you can find my issue https://forums.aws.amazon.com/thread.jspa?threadID=247520&tstart=0

Here my log for this.httpResponse.body.toString():

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"` `"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`
`<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">`
`<head>`
  `<title>Page Not Found</title>`
`</head>`
`<body>Page Not Found</body>`
`</html>`

**And my code:**
  ```
var AWS = require('aws-sdk');
    var profile = {
        "accessKeyId": "...",
        "secretAccessKey": "...",
        "region": "us-east-1"
    }
   AWS.config.update(profile);

    // Create CloudWatchEvents service object
    var cwevents = new AWS.CloudWatchEvents({ "apiVersion": "2015-10-07" });
    var params2 =
        {
            "Name": "demo-test"
        }; 
    cwevents.deleteRule(params2, function(err, data) {
        
        if (err) {
            console.log(err, err.stack);
            console.log(`cwResponse: ${this.httpResponse.body.toString()}`);
        }
        else {
            console.log(data);

        };
    })

```

**Comment by dsouzamanish** [comment]
@jeskew  Yes we are setting custom end point
Our config is as follows :  s3: {
        primarybucket: "XXXX-staging",
        accessKeyId: "XXXXXXXXXX",
        secretAccessKey: "XXxxxXXXXXXXXXxxxxxxxXXXXXX",
        region: "ap-south-1",
        s3BucketEndpoint: true,
        signatureVersion: "v4",
        endpoint: "http://xxxxxxxx-staging.s3.amazonaws.com",
    }

**Comment by jeskew** [comment]
@dsouzamanish Are you also calling DynamoDB in the callback passed to an S3 client operation?

**Comment by dsouzamanish** [comment]
No not in the callback.We simply stream images received to client. But subsequent requests may have dynamo calls through different client.

**Comment by jeskew** [comment]
@dsouzamanish I was only able to reproduce by calling `AWS.config.update({endpoint: s3Endpoint})`, which sets the endpoint for all services to be the one you intended to use for S3. If you're certain that's not happening in your code, could you provide a minimal reproduction case or some more details about how you're setting your configuration?

**Comment by alexanimal** [comment]
Also getting this error on a Basic CloudWatch Example, can't seem to tell if its a bad CloudWatch Log record or some issue with the SDK parsing the response from AWS.

**Comment by jeskew** [comment]
@alexanimal I believe the error you're seeing is related to #1379, not to this ticket.

**Comment by RegEM** [comment]
I get the same error when trying to set the custom endpoint with lambundaler, which calls config on  aws.lambda.

`{ SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.extractError (H:\project\node_modules\lambundaler\node_modules\aws-sdk\lib\protocol\json.js:29:18)`

**Comment by srchase** [comment]
@dsouzamanish 

Is this still an open issue for you?  If not, we'd like to close it out.
