### ISSUE TITLE
Error when getting Cognito identity credentials with older node versions

### ISSUE THREAD

**Issue by thadd** [aws/aws-sdk-js#1307]
Using the following testing code:

```javascript
var AWS = require("aws-sdk");

var params = {
  "IdentityPoolId": "MY_IDENTITY_POOL", 
  "Logins": {
    "MY_DEVELOPER_ID": "john.doe"
  }
}

var CognitoIdentity = new AWS.CognitoIdentity();
CognitoIdentity.getOpenIdTokenForDeveloperIdentity(params, (err, data) => {
  console.log(err, data);
});
```

When running with Node 4.3.2 (the latest version running on AWS Lambda), and AWS SDK version 2.7.23, I get the following error:

```
{ [NetworkingError: this is not a typed array.]
  message: 'this is not a typed array.',
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: 'cognito-identity.us-east-1.amazonaws.com',
  retryable: true,
  time: Tue Jan 17 2017 14:51:06 GMT-0800 (PST) }
```

When running with Node 4.3.2 and AWS SDK version 2.7.22, it works as expected. This looks to be related to using `Buffer.from` here: https://github.com/aws/aws-sdk-js/compare/v2.7.22...master#diff-e8a1def4cf1938c1bdf0c30b2dac533dR104.

**Comment by Kenny-House** [comment]
Running into this as well in an ECS cluster. Same `NetworkingError: this is not a typed array.` 

Stack trace points to the `writeBody` function.
