### ISSUE TITLE
v2.7.23 broke SNS - running Lambda nodeJs v.4.3.x

### ISSUE THREAD

**Issue by kevbook** [aws/aws-sdk-js#1308]
```js
   "message": "this is not a typed array.",
    "code": "NetworkingError",
    "region": "us-east-1",
    "hostname": "lambda.us-east-1.amazonaws.com",
    "retryable": true,
```

**Comment by magtutu** [comment]
Having this problem with KMS as well...
failed to decrypt: Could not decrypt KMS data key: this is not a typed array.

**Comment by chrisradek** [comment]
Are you having these issues in Lambda, and did this just start happening recently?
Lambda is currently on version [`2.7.10`](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) of the SDK, and has been since December.

Can you also provide any code snippets that reproduce this issue?

**Comment by kevbook** [comment]
I am not using amazon lambda SDK. I use it via `package.json` 
Its happening locally as well. Only on v2.7.23 not v2.7.22

**Comment by chrisradek** [comment]
@kevbook 
Gotcha. We've identified the issue and are working now to correct it. Thanks for reporting!

**Comment by magtutu** [comment]
This happens for KMS in 2.7.23 and not 2.7.22.

**Comment by jphaas** [comment]
Not sure if it's related but upgrading to 2.7.23 broke RDS describeInstances; I'm calling

rds.describeDBInstances({}, my_callback);

And getting the following stack trace passed to my_callback(err):

NetworkingError: socket hang up
    at createHangUpError (_http_client.js:211:15)
    at TLSSocket.socketOnEnd (_http_client.js:303:23)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

**Comment by lukehutton** [comment]
When you think this will make it into v2.7.24 and get released? Have to downgrade in meantime

**Comment by jakepruitt** [comment]
We have production systems that have to run on node 4.0-4.4, with deep dependencies on aws-sdk that are difficult to peg at the downgraded aws-sdk. Is it possible to release a patch in the near future?

**Comment by neftaly** [comment]
It was just patched & updated on NPM, should all be fixed now

**Comment by lukehutton** [comment]
Awesome! thanks for quick fix! Will now patch my apps to update again
