### ISSUE TITLE
Node v2.1.0 SQS problem With Release 2.7.23

### ISSUE THREAD

**Issue by GingerAebi** [aws/aws-sdk-js#1310]
I use this package for send request by using sqs, and I got error in node v2.1.0

I got two error and SQS error message is like this 
"there is not typed array", "socket hang up" 

I solve this problem by update my aws node version as v3.3.0

     64bit Amazon Linux 2016.03 v2.1.0 running Node.js 
-> 64bit Amazon Linux 2016.09 v3.3.0 running Node.js
 
Thank you

**Comment by jeskew** [comment]
Hi @GingerAebi,

This was a regression in 2.7.23 that was addressed in 2.7.24. Could you try updating and see if that resolves the problem?

**Comment by GingerAebi** [comment]
I think It appear agin in 2.7.24

**Comment by GingerAebi** [comment]
It's fine in 2.7.24 Thanks

**Comment by jeskew** [comment]
Glad to hear the upgrade fixed the problem. Please feel free to reopen this issue if any you see the error again.
