### ISSUE TITLE
assumeRole returns an empty data object

### ISSUE THREAD

**Issue by petterbergman** [aws/aws-sdk-js#1311]
About 60 days ago, assumeRole broke and started returning blank data.  I reverted to an older build, but this too is broken, so the only thing that must have changed are the AWS API endpoints being called.

Code:
    var sts = new AWS.STS();
    var params = {
        RoleArn: 'arn:aws:iam::xxxxxxxxxx:role/s3role', /* required */
        RoleSessionName: 'temp_server_session' /* required */
    };
    sts.assumeRole(params, function (err, data) {
        if(err){
            console.error(err);
        } else {
            // successful response, should contain data.Credentials
            console.log(data);
        }
    });

Returns a blank object, i.e. console prints "{}".

Should return a data object with Credentials and AssumedRoleUser.  I know this works, cause I can do it in the CLI and I haven't changed any of my code (i.e. this was working fine before).

**Comment by jeskew** [comment]
If reverting to an older version of the SDK did not correct the unexpected behavior, then I believe you are right that the behavior originates from the service. I was unable to reproduce what you've described (`sts.assumeRole` is still returning an object with the `AssumedRoleUser`, `Credentials`, and `ResponseMetadata` properties), but you could try directing your question to the service team via [the AWS forums](https://forums.aws.amazon.com/forum.jspa?forumID=76).

**Comment by bo-ora** [comment]
I have exactly the same situation with `assumeRole` and empty data returned.
@petterbergman have you found out the reason ?

**Comment by petterbergman** [comment]
No, I never found a reason why.  Instead I worked around it, by calling the API directly using https.request.  I used aws4 to sign my request and xml2js to parse the result.

It's been a while since I wrote this work-around, but here's what it should look like:

var getS3Credentials = function(){
	var deferred = q.defer();
	var duuid = uuid.v4();

	var
		https = require('https'),
		aws4  = require('aws4'),
		xml2js = require('xml2js');

	opts = {service: 'sts', path: '/?Version=2011-06-15&Action=AssumeRole&RoleSessionName=nodeserver' +
		'&RoleArn=' + process.env.AWS_ASSUME_ROLE_ARN +
		'&DurationSeconds=3600&ExternalId=node' +
		'&AUTHPARAMS'};

	aws4.sign(opts); // assumes AWS credentials are available in process.env

	// we can now use this to query AWS using the standard node.js http API
	https.request(opts, function(res) {
		var str = '';
		res.on('data', function (chunk) {
			str += chunk;
		});
		res.on('error', function (e) {
			throw new Error(e);
		});
		res.on('end', function () {
			var parser = new xml2js.Parser();
			parser.parseString(str, function (err, result) {
				if (err) {
					throw new Error(err);
				}
				var tacccesskeyid = result.AssumeRoleResponse.AssumeRoleResult[0].Credentials[0].AccessKeyId[0];
				var tsecretaccesskey = result.AssumeRoleResponse.AssumeRoleResult[0].Credentials[0].SecretAccessKey[0];
				var tsessiontoken = result.AssumeRoleResponse.AssumeRoleResult[0].Credentials[0].SessionToken[0];
				var data = {Credentials:{}};
				data.Credentials.uuid = duuid;
				data.Credentials.AccessKeyId = tacccesskeyid;
				data.Credentials.SecretAccessKey = tsecretaccesskey;
				data.Credentials.SessionToken = tsessiontoken;
				deferred.resolve(data.Credentials);
			});
		});
	}).end();
	return deferred.promise;
};


Hope that helps.

**Comment by cuipengfei** [comment]
Getting exactly same problem here.

My code is running in ECS, call to assumeRole returns empty object.
However, the same code works ok locally.

The only difference I can see is ECS.

**Comment by cuipengfei** [comment]
Problem solved.

It was somehow related to node version.

My code was running in ECS, with a base docker image: node:8.9.4.

I switched to node:9.4, which is the latest version, that solved the problem.

Don't know why, but it's working.

@bo-ora & @petterbergman , was your situation perhaps similar? What is your node version?

**Comment by srchase** [comment]
This looks like an old issue and may have been resolved.  I'm unable to reproduce the issue with the current version of the SDK, so I'm opting to close this issue.  

Let us know if you encounter the issue with a current version of the SDK and we can re-open.
