### ISSUE TITLE
Forbidden error: iotdata.getThingShadow with cognito credentials

### ISSUE THREAD

**Issue by azhicodan** [aws/aws-sdk-js#1312]
I'm using AWS Cognito to manage the authentication and authorization in the app. I have created a user pool and one identity pool which is federated with the cognito user pool.

User logs-in with the credentials. I authenticate the user against the user pool and then exchange the returned id token with Cognito Identity to get temporary aws credentials, which can be used to connect to other aws resource, in my case aws resource is aws iot.

There are two aws iot modules in sdk:

1. AWS .IoT (List Things etc.)
2. AWS IotData (Get Thing Shadow, Update Thing Shadow etc.)

I'm able to successfully call the methods in first AWS IOT SDK with the temporary credentials. But I'm not able to use the same credentials to get the data from AWS IOT Data SDK. I get a forbidden error.

Every identity pool creates 2 roles, Authenticated Role and UnAuthenticatedRole. And in IAM console, I have attached the Full IOT access policy to the authenticated role. So i'm not sure why I'm getting the forbidden error. 

IAM IOT Full access Policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:*"
            ],
            "Resource": "*"
       }
    ]
}
```

Code:

```
// Snippet from login method. 
cognitoUser.authenticateUser(authDetails, {
            onSuccess: function (result) {
                // Get credentials from identity pool to access other AWS resource
                AWSCognito.config.region = REGION;
                AWS.config.credentials = new AWSCognito.CognitoIdentityCredentials({
                    IdentityPoolId: IDENTITY_POOL_ID, // your identity pool id here
                    Logins: {
                        'cognito-idp.us-west-2.amazonaws.com/USERPOOLID': result.idToken.getJwtToken()
                    }
                });
                
                getRegisteredThings(username); // Calls aws iot sdk
                getThingShadow('ShadowName'); // Calls aws iot data sdk
            },
            onFailure: function (err) {
                console.log('Error while authenticating user ' + +err);
            }
        });

// Works Fine
 var getRegisteredThings = function (username) {
        // Get the credentials and then call the iot api
        AWS.config.credentials.get(function (err) {
            if (err) {
                console.log(err);
                return;
            }
            AWS.config.region = REGION;
            var iot = new AWS.Iot();

            var params = {
                attributeName: 'owner',
                attributeValue: username
            };

            iot.listThings(params, function (err, data) {
                debugger; // This works absolutely fine. I am able to get the things registered
                if (err) {
                    console.log(err);
                    return;
                }
                console.log('List things data: ' + data);

            });
        });
    };

// Forbidden error
    var getThingShadow = function(thingName){
        AWS.config.credentials.get(function (err) {
            if (err) {
                console.log(err);
                return;
            }

            AWS.config.region = REGION;
            var iotdata = new AWS.IotData({
                endpoint: 'XXXXXX.iot.us-west-2.amazonaws.com'
            });

            var params = {
                thingName : thingName
            };
            iotdata.getThingShadow(params, function(err, data) {
                debugger; // This is where I get forbidden error
                if (err)
                    console.log(err, err.stack); // an error occurred
                else {
                    console.log(data);           // successful response
                }
            });

        });
    };
```

Question:
1. Is this the right way to call the thing shadow api?'The intention is to get the current state of the shadow.
2. Does the thingshadow api work with temporary credentials?

Workaround:
As a work around I'm thinking of going the MQTT way, using the paho client library to publish to thing shadow's 'get' topic and then subscribe to 'get accepted' topic to get the state. I'm hoping that might work.

Exception:

```
Error: Forbidden
    at Object.extractError (aws-iot-iotdata-sdk-2.7.24.js:7810)
    at Request.extractError (aws-iot-iotdata-sdk-2.7.24.js:7133)
    at Request.callListeners (aws-iot-iotdata-sdk-2.7.24.js:6976)
    at Request.emit (aws-iot-iotdata-sdk-2.7.24.js:6954)
    at Request.emit (aws-iot-iotdata-sdk-2.7.24.js:4057)
    at Request.transition (aws-iot-iotdata-sdk-2.7.24.js:3834)
    at AcceptorStateMachine.runTo (aws-iot-iotdata-sdk-2.7.24.js:5945)
    at aws-iot-iotdata-sdk-2.7.24.js:5954
    at Request.<anonymous> (aws-iot-iotdata-sdk-2.7.24.js:3850)
    at Request.<anonymous> (aws-iot-iotdata-sdk-2.7.24.js:4059) "ForbiddenException: Forbidden
    at Object.extractError (http://localhost:63342/aws-iot-sample/app/js/lib/aws-iot/aws-iot-iotdata-sdk-2.7.24.js:7810:37)
    at Request.extractError (http://localhost:63342/aws-iot-sample/app/js/lib/aws-iot/aws-iot-iotdata-sdk-2.7.24.js:7133:18)
    at Request.callListeners (http://localhost:63342/aws-iot-sample/app/js/lib/aws-iot/aws-iot-iotdata-sdk-2.7.24.js:6976:38)
    at Request.emit (http://localhost:63342/aws-iot-sample/app/js/lib/aws-iot/aws-iot-iotdata-sdk-2.7.24.js:6954:22)
    at Request.emit (http://localhost:63342/aws-iot-sample/app/js/lib/aws-iot/aws-iot-iotdata-sdk-2.7.24.js:4057:30)
    at Request.transition (http://localhost:63342/aws-iot-sample/app/js/lib/aws-iot/aws-iot-iotdata-sdk-2.7.24.js:3834:26)
    at AcceptorStateMachine.runTo (http://localhost:63342/aws-iot-sample/app/js/lib/aws-iot/aws-iot-iotdata-sdk-2.7.24.js:5945:22)
    at http://localhost:63342/aws-iot-sample/app/js/lib/aws-iot/aws-iot-iotdata-sdk-2.7.24.js:5954:22
    at Request.<anonymous> (http://localhost:63342/aws-iot-sample/app/js/lib/aws-iot/aws-iot-iotdata-sdk-2.7.24.js:3850:29)
    at Request.<anonymous> (http://localhost:63342/aws-iot-sample/app/js/lib/aws-iot/aws-iot-iotdata-sdk-2.7.24.js:4059:30)"
```

**Comment by chrisradek** [comment]
@azhicodan 
Do you get the same error if you only run `getThingShadow, and not `getRegisteredThings`?

It looks like you're calling the `iotdata.getThingShadow` api correctly. I created a new user/role that matches your policy, put the credentials in `~/.aws/credentials` and was able to call `getThingShadow` successfully, so your policy looks correct. It'll take me more time to set up CognitoCredentials with a similar setup as yours.

**Comment by azhicodan** [comment]
@chrisradek 
Yes, I get the same error if I run only getThingShadow. I tried my own aws credentials (not the cognito one) and it works absolutely fine. I think that's what you tried as well. Here's the code for that:

```
var getThingShadowDirect = function (thingName) {
        AWS.config.region = REGION;
        var credentials = {
            accessKeyId : 'ACCESS_KEY_ID',
            secretAccessKey : 'SECRET_ACCESS_KEY'
        };
        var iotdata = new AWS.IotData({
            endpoint: 'XXXXX.iot.us-west-2.amazonaws.com',
            credentials : credentials
        });

        var params = {
            thingName: thingName
        };
        iotdata.getThingShadow(params, function (err, data) {
            debugger;
            if (err)
                console.log(err, err.stack); // an error occurred
            else {
                console.log(data);           // successful response
            }
        });
    };
```

But the problem with cognito credentials still there. Actually, I'm not able to use cognito credentials to open up a websocket connection either (using paho client library).

   ```
 var connectToIot = function () {
        AWS.config.credentials.get(function (err) {
            if (err) {
                console.log(err);
                return;
            }

            // Request URL with SigV4 credentials
            var requestUrl = SigV4Utils.getSignedUrl('XXXXXX.iot.us-west-2.amazonaws.com', 
			'us-west-2', AWS.config.credentials);

            // Create mqtt client object to open up a websocket connection
            var clientId = String(Math.random()).replace('.', '');
            var client = new Paho.MQTT.Client(requestUrl, clientId);

            var connectOptions = {
                onSuccess: function () {                                        
                    console.log('Websocket Success');
                },
                useSSL: true,
                timeout: 3,
                mqttVersion: 4,
                onFailure: function (error) {                    
                    console.log('Websocket Failure');
					console.log(error);
                }
            };
				
            client.connect(connectOptions);            

        });
    };
```

The client connect fails with following error "_AMQJS0008I Socket closed_."

So I have a bigger problem with cognito credentials now. Because I really need to open up this web socket, to subscribe and get real time state from the thing shadows.

**Comment by yesiyan01** [comment]
Any updates on this issue? I'm having the exact same issue

**Comment by just4give** [comment]
@azhicodan @yesiyan01  I faced same issue "AMQJS0008I Socket closed". After spending hours on google, I learnt each cognito user must have a policy attached to the user. Checkout this [link](https://forums.aws.amazon.com/thread.jspa?messageID=728067)
So I created a policy named "light-policy" as below 
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect",
        "iot:DeleteThingShadow",
        "iot:GetThingShadow",
        "iot:Publish",
        "iot:Receive",
        "iot:Subscribe",
        "iot:UpdateThingShadow"
      ],
      "Resource": "*"
    }
  ]
}
```
You can make it more restrictive but for testing purpose I kept it open. Then when you register or login users , attach the policy as below

```
AWS.config.credentials.get(function(err){
 if (err) {
              alert(err);
             }else {
             var iot = new AWS.Iot();
             var params = {
                 policyName: 'light-policy', /* required */
                 principal: AWS.config.credentials.identityId /* required */
               };
             iot.attachPrincipalPolicy(params, function(err, data) {
              })
}
});
```

**Comment by eczajk1** [comment]
Experiencing the same issue here. Any guidance? Thanks.

**Comment by bentranmyriota** [comment]
I have the same issue for a while now. This seems to be a serious issue as I need to have an unauthenticated identity pool to be able to read thing shadow.

**Comment by louisdvs** [comment]
I am experiencing the same issue. 
AWS.IoT calls are working but AWS.IoTDATA calls are forbidden when authenticating with credentials from Cognito. Tested in the same manner as @azhicodan with a hard-coded secret and access key.

**Comment by azhicodan** [comment]
It's been a long time since I worked on this. But I remember resolving the issue by adding an IAM policy to allow access to IOT resources.

**Comment by eczajk1** [comment]
I was ultimately able to get around this with `AWS.Iot.attachPolicy`:

```
var params = {
  policyName: policyName,
  target: identityId,
};

// NOTE: `iot` is an instance of AWS.Iot
iot.attachPolicy(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

The `policyName` refers to an IoT policy - not an IAM policy. The target is an "arn" for the IoT certificate.

After the script runs successfully, you can see a certificate for "Cognito Identity" in "IoT > Secure > Policies > Certificates" in the AWS console.

Note that this script was run server-side. And, I do not currently understand how best to access `identityID` other than to observe the value in the browser after I log in - i.e. after we are authenticated via Cognito, you can observe the identityID at AWS.config.credentials.identityId. So I was only able to get this to work for a Cognito account for which I have the credentials.

**Comment by bentranmyriota** [comment]
I have solved this issue with some helps from AWS support and stackoverflow. Basically, like @eczajk1 mentioned above, you need to get identityID of the credentials and attach it to the iot policy on the client side. 
Steps:
    1) Log in with AWS cognito
    2) Get credentials (make sure the policy of the role allows attachPrincipalPolicy)
    3) Call attachPrincipalPolicy(policyName, identityID). Note: The Iot policy should allow getThingShadow
    4) Then you can call getThingShadow()

**Comment by louisdvs** [comment]
Thanks for your feedback @eczajk1 and @bentranmyriota 
For anyone else > I access to the shadows operations from the frontend by manually adding the policy to the identityID (I obtained the identityID from the Cognito console> manage federated identities > identity pool > identity browser) in the AWS CLI using:
`aws iot attach-principal-policy --principal us-east-2:XXXX-XXXX-XXXX-XXXX --policy-name my-custom-policy`
But from my understanding, it's not possible (and not secure) to attach a policy to an identity directly in the front-end using the iot.attachPrincipalPolicy().
I'm going to try attachning the policy to the identityID in a Lambda function.

**Comment by bentranmyriota** [comment]
I think there is a misunderstanding about the principal value. You can't use the identityPoolID of the federated identity shown in the console. 
Each authenticated user will get an unique identityID, only be returned with the credentials in the step 2. You then should attach that identityID to the iot policy.
``aws iot attach-principal-policy --principal <identityID> --policy-name <my-custom-iot-policy>``
FYI, it is possible to attachPrincipalPolicy() in the front end ( I did it), and I agree with you it is not secure.

**Comment by louisdvs** [comment]
@bentranmyriota you can get the unique identityID of a user (rather than a pool) from the federated identity pool in the console (see screenshot with identityID obscured). For my use case (prototyping) I'm happy to manually add the few users that need access to shadows.
![cognito](https://user-images.githubusercontent.com/24875769/34805414-f0bf908a-f6b8-11e7-90dd-f4a92e312ab7.jpg)

**Comment by Bassem-Samy** [comment]
Guys @eczajk1  @bentranmyriota @louisdvs  , You saved my day (actually days trying to get this to work)
The thing though I can add is how to get your user id (Identity Id) used as the target in attaching the policy request , you mentioned getting it from the console and url but according to this link:
https://docs.aws.amazon.com/cognito/latest/developerguide/getting-credentials.html
there is a methind in the CredentialsProvider that's getIdentityId it's a web request that gets the Identity Id but after providing the userIdToken in the login maps
` map.put("cognito-idp.eu-west-1.amazonaws.com/<USER POOL ID>",yourCurrSession().getIdToken().getJWTToken());
credentialsProvider.setLogins(map);
`
`String identityId = credentialsProvider.getIdentityId();
Log.d("LogTag", "my ID is " + identityId);
`
That's Java code and I used in android app and thank God it works instead of hard coding the user id.
And dear Amazon please please please put a working step by step samples for authenticated users not just unauthenticated as all the sample in the android and ios sdk samples <3 thank you

**Comment by eczajk1** [comment]
After revisiting this thread, just wanted to add this note for clarification:

Earlier posts make reference to an AWS Forum post that references [another Forum post](https://forums.aws.amazon.com/thread.jspa?messageID=726121) where it is indicated that the Cognito Identity must be given desired IoT permissions.

> "For authorized Cognito identities, just attaching the policy to the pool is not sufficient, you will also need to attach policy to each identity. You could use the AWS IoT AttachPrincipalPolicy API to grant the specified Amazon Cognito user permissions..."

In my earlier post, I had mentioned `attachPolicy` which is favored over the now deprecated `attachPrincipalPolicy`. My post was confusing though, because I had mentioned that the `target` param "is an arn for the IoT certificate".

While `attachPolicy` does allow you to attach an IoT policy to a certificate, the more relevant action here is adding a policy for the Cognito Identity (also using `attachPolicy`) so that a logged in user has any permissions it needs. So, `attachPolicy` is used to attach a policy to an IoT certificate as well as a Cognito Identity.

**Comment by RavirajKakadeGit** [comment]
I'm facing same issue, Any luck?
