### ISSUE TITLE
pre-signed S3 putObject URLs don't allow tags

### ISSUE THREAD

**Issue by Suiname** [aws/aws-sdk-js#1313]
I'm currently using the latest version of the aws-sdk-js.  I have found what I think is a bug relating to uploading objects to an S3 bucket using the pre-signed URLs.  If I create an object using the SDK like so:
```
const params = { Bucket, Key: 'testfile', Metadata, Body: "This is a test object", Tagging: 'sem=somethingSemantic' };
s3.putObject(params, (err, data) => {
  if (err) {
    console.log('s3 error: ', err);
  }
  console.log('it worked: ', data);
}
```
This works, I see an object called `testfile` appear in my bucket and it has a tag `sem: somethingSemantic`.

However, when I try to generate a url using the following code:
```
s3.getSignedUrl('putObject', { Bucket, Key: 'testfile', Metadata, Tagging: 'sem=somethingSemantic' Expires: 1800 }, (error, url) => {
  if (error) {
    console.log('s3 error: ', error);
  }
  console.log('The URL is', url);
}
```
This code generates a URL similar to the following: `https://bucketname.s3.amazonaws.com/testfile?AWSAccessKeyId=mykey&Expires=1484777697&Signature=signatureString&x-amz-tagging=sem%3DsomethingSemantic`
When I do a put on this URL using postman and upload the binary file, it creates the file correctly, however it does NOT create the tag.  Even more curious is the fact that if I take out the x-amz-tagging part of the pre-signed URL and manually input the header into postman, like so:
![image](https://cloud.githubusercontent.com/assets/14084959/22084905/8aa6e9a0-dd97-11e6-924e-02e9eb1425ae.png)
Everything works fine.  Can someone verify if this is actually a bug or if something else is going on here?
UPDATE:  I ran the pre-signed URL in curl as well to verify this is not a postman issue, same behavior with curl, no tagging via pre-signed URLs.

**Comment by chrisradek** [comment]
@Suiname 
This appears to be an issue on S3's side, but I've reached out to them to be sure. I'll respond back once I get a response.

**Comment by Suiname** [comment]
@chrisradek Thanks, I appreciate it

**Comment by Suiname** [comment]
@chrisradek Any update on this?  We are blocked from integrating S3 until this gets fixed.

**Comment by chrisradek** [comment]
@Suiname 
Sorry, I haven't gotten a response yet from the S3 team. It might help if you post the same question to the [S3 forums](https://forums.aws.amazon.com/forum.jspa?forumID=24). If you do, post a link back here and I'll forward the link as well.

**Comment by Suiname** [comment]
Here's my S3 forum thread: https://forums.aws.amazon.com/thread.jspa?threadID=247687

**Comment by Suiname** [comment]
@chrisradek I assume there hasn't been an update on this?  They asked me to create a support request, but unfortunately my AWS account doesn't allow for that.

**Comment by chrisradek** [comment]
@Suiname 
I know they're looking into it, but I don't know what their final resolution will be. Anyone else that also needs this functionality should respond to the forum thread to let S3 know they want this feature. I'll update when I hear something new as well.

**Comment by iamatharkhan** [comment]
@Suiname I've had the same issue. I managed to resolve it by generating presigned URL with **Tagging** param as well as adding _x-amz-tagging_ header in the POST request i.e. _x-amz-tagging_ should be present in both presigned url and the POST request header.

**Comment by s2maki** [comment]
+1 . Being able to add tags via presigned URL is a must-have.

**Comment by jeskew** [comment]
@s2maki As a work-around, tagging is supported for direct-from-browser uploads via [the S3 PostObject API](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html). You can create a policy document for a POST upload with [`AWS.S3.createPresignedPost`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createPresignedPost-property).

**Comment by s2maki** [comment]
I'll give that a try, thanks!

**Comment by dustMason** [comment]
The PostObject API does not meet my requirements. Only browsers that support XHRv2 can do ajax multipart posts. Using a presigned PUT request allows us to support XHRv1 clients because the params are part of the URL.

Dear AWS, please fix this bug!

**Comment by jeskew** [comment]
@dustMason I've passed your feedback on to the S3 team internally. The best way to reach out to them directly is via the [S3 AWS developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=24), as they do not monitor any SDK's issue queue.

**Comment by jonface** [comment]
Anyone got an update on this? Or a URL to the forum post where S3 have replied?

**Comment by allensarkisyan** [comment]
Seems like you also need to send the 'x-amz-tagging' header as a part of the actual PUT/POST request as well. Solved the problem on my side doing just that. Hope this helps!

**Comment by bradbenvenuti** [comment]
Has anyone found a solution for this?

**Comment by epeli** [comment]
There is something weird going on. It seems that when signing the url you must set just some random tag within but you actually set real tags within the PUT operation.

Here's my signing code:

```js
    var signedURL = s3.getSignedUrl("putObject", {
        Bucket: process.env.KV_BUCKET,
        Key: "foobar.pdf",
        ContentType: "application/pdf",
        ACL: "public-read",
        Tagging: "foo=anything",
    });
```

And here's browser upload code 

```js
    const headers = new Headers();
    headers.append("x-amz-tagging", "myrealtag=tagvalue");

    const uploadRes = await fetch(signedURL, {
        method: "PUT",
        body: file,
        headers,
    });

```

**Comment by Suiname** [comment]
@epeli That's interesting.  Maybe the signature just checks whether or not a tag is set as a boolean or something and not the actual tag content.   Either way, that will work for me.

**Comment by noambonnie** [comment]
I observed the same behavior. Tagging does not happen (put operation succeeds but no tag). I have putObjectTagging permission.

**Comment by srchase** [comment]
@Suiname 

This is currently working.  Are you able to get this working with the latest version of the SDK?

**Comment by jsdtaylor** [comment]
Hey @epeli, re:

> There is something weird going on. It seems that when signing the url you must set just some random tag with it but you actually set real tags within the PUT operation.
> 
> Here's my signing code:
> 
> ```js
>     var signedURL = s3.getSignedUrl("putObject", {
>         Bucket: "mybucket",
>         Key: "foobar.pdf",
>         ContentType: "application/pdf",
>         ACL: "public-read",
>         Tagging: "foo=anything",
>     });
> ```
> 
> And here's browser upload code
> 
> ```js
>     const headers = new Headers();
>     headers.append("x-amz-tagging", "myrealtag=tagvalue");
> 
>     const res = await fetch(signedURL, {
>         method: "PUT",
>         body: file,
>         headers,
>     });
> ```

I had the exact same issue and was banging my head against a brick wall, but then I realized the current documentation notes that some params are not processed, including `Tagging`: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property. They need to be passed as headers, e.g. `x-amz-tagging=mytagkey%3Dmytagvalue`.

Regardless, I don't see why this issue dies in December last year without someone from AWS mentioning this fact?

> Note: Not all operation parameters are supported when using pre-signed URLs. Certain parameters, such as SSECustomerKey, ACL, Expires, ContentLength, or Tagging must be provided as headers when sending a request. If you are using pre-signed URLs to upload from a browser and need to use these fields, see createPresignedPost().
