### ISSUE TITLE
Increased Latency in 2.7.25

### ISSUE THREAD

**Issue by thenovelnomad** [aws/aws-sdk-js#1314]
I just upgraded a production application from version 2.7.21 to 2.7.25 of this sdk. In this application, I am using the sdk to make the following API requests to SNS, createPlatformEndpoint and setEndpointAttributes.

Prior to the upgrade, these calls were averaging around 40ms each. Post-upgrade, each call is averaging around 75ms each.

I have verified it is due to the version change by switching between them.

**Comment by chrisradek** [comment]
@thenovelnomad 
Can you share what version of node.js you are using, and any configuration that you use when setting up your SNS client?

**Comment by thenovelnomad** [comment]
Sure.

Still running nodejs 0.12.18 for this app, since we are running on OpsWorks Chef 11 stack. 

The only configuration used when setting up the SNS client, is passing in the region, `us-west-2`.

**Comment by thenovelnomad** [comment]
I didnt really see anything that stood out diffing the two versions, but looks like body-parser version changed:
`body-parser@1.15.2	-> body-parser@1.16.0`

**Comment by jeskew** [comment]
I believe this was related to #1303, which seems to prevent node's HTTP client from optimizing how a request is translated into packets. That change will be reverted in the next release.

**Comment by jeskew** [comment]
@thenovelnomad Could you try with version 2.7.27?

**Comment by thenovelnomad** [comment]
@jeskew yeah, i can test tonight. Sorry for the delay.

**Comment by thenovelnomad** [comment]
2.7.27 appears to fix the issue. Thanks, @jeskew

**Comment by jeskew** [comment]
Glad to hear it! Thanks for running those tests.
