### ISSUE TITLE
AWS Step Functions in JS SDK

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#1318]
Hi guys,

Can you make the step functions available in the JS SDK?

Best Regards,

**Comment by jeskew** [comment]
Hi @ramonck,

[The SDK includes support for AWS Step Functions](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/StepFunctions.html), but that service is not included in the default browser distribution. By default, the browser distribution will only include services that support CORS.
