### ISSUE TITLE
RDS is not injecting correct pre-signed url

### ISSUE THREAD

**Issue by BSick7** [aws/aws-sdk-js#1324]
## Environment
Using the aws sdk available through Lambda.

## Overview
According to the AWS docs, the RDS `copyDBSnapshot` operation expects `PreSignedUrl`.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS.html#copyDBSnapshot-property

## Problem
The code sets `PresignedUrl` instead.
https://github.com/aws/aws-sdk-js/blob/master/lib/services/rds.js#L45-L51

## Symptom
When trying to execute `copyDBSnapshot` for cross-region backups, you get this:
```
InvalidParameterValue: PreSignedUrl could not be authenticated
```

CloudTrail shows neither `PresignedUrl` or `PreSignedUrl` in the `requestParameters`.

**Comment by BSick7** [comment]
Update on above bug:
It appears that I needed to set `SourceRegion` in `params`.

When I do that, I get 
```Unexpected key 'SourceRegion' found in params```

This appears to me like a client-side validation as I do not get any information in CloudTrail.

**Comment by chrisradek** [comment]
@BSick7 
The `copyDBSnapshot` PreSignedUrl update was made in version `2.7.18` of the SDK. Lambda is currently on version [`2.7.10`](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html), so this functionality is not yet supported in Lambda unless you also bundle a newer version of the SDK.

**Comment by BSick7** [comment]
Thanks @chrisradek 
Is there a link that tells the version of the SDK in Lambda?
Should I expect Lambda to be updated soon?

**Comment by chrisradek** [comment]
@BSick7 
Actually, there was a bug in the SDK, as you originally pointed out. I created #1325 to address it.

The Lambda team controls when the SDK is updated in their runtimes, so I don't know what their timeline is. You might try asking on their forums for an update.

**Comment by BSick7** [comment]
Thanks @chrisradek
