### ISSUE TITLE
CloudDirectory: TypeError on listIndex operation

### ISSUE THREAD

**Issue by k3karthic** [aws/aws-sdk-js#1332]
When i try to perform a listIndex operation (with or without RangesOnIndexedValues param) on my cloud directory the following error is thrown. The issue occurs on Lambda and on Node version 6.9.4.

The same operation when performed from the aws cli returns the expected result.

OS: CentOS 7
Node: v6.9.4
AWS SDK: v2.9.0

`
{ [TypeError: must start with number, buffer, array or string]
message: 'must start with number, buffer, array or string',
code: 'TypeError',
time: Sat Jan 28 2017 01:07:18 GMT+0000 (UTC),
statusCode: 200,
retryable: false,
retryDelay: 29.344943910837173 }

TypeError: must start with number, buffer, array or string
at fromObject (buffer.js:141:11)
at new Buffer (buffer.js:62:10)
at BinaryShape.decode64 [as toType] (/var/task/node_modules/aws-sdk/lib/util.js:112:134)
at translateScalar (/var/task/node_modules/aws-sdk/lib/json/parser.js:61:16)
at translate (/var/task/node_modules/aws-sdk/lib/json/parser.js:16:21)
at Object.<anonymous> (/var/task/node_modules/aws-sdk/lib/json/parser.js:29:20)
at Object.each (/var/task/node_modules/aws-sdk/lib/util.js:478:32)
at translateStructure (/var/task/node_modules/aws-sdk/lib/json/parser.js:25:8)
at translate (/var/task/node_modules/aws-sdk/lib/json/parser.js:13:30)
at Object.<anonymous> (/var/task/node_modules/aws-sdk/lib/json/parser.js:29:20)
`

**Comment by chrisradek** [comment]
@k3karthic 
Can you share what your parameters look like for this operation?

**Comment by k3karthic** [comment]
The following snippet is what i am using,

```
let aws = require('aws-sdk');
aws.config.update({region: 'us-east-1'});

let client = new aws.CloudDirectory();
client.listIndex(
    {
        DirectoryArn: 'arn:aws:clouddirectory:us-east-1:<acc_no>:directory/AZE76Gb8lUQNvHWL3bqpO4k', 
        IndexReference: { 
            Selector: '$AQGRO-hm_JVEDbx1i926qTuJ05koCRypQ7yKUugJ1H-abg' 
        }
    }, 
    function(err, data) { 
        if (err) { 
            console.log(err); 
        } else { 
            console.log(data) 
        }
    }
);
```

**Comment by chrisradek** [comment]
@k3karthic 
I was able to reproduce the issue and have identified it as a bug. The error is occurring because CloudDirectory is sending back `BinaryValue: null` when an object is a non-binary type, and the SDK attempts to base64 decode the `null` value. I'm researching the best way to fix this in the SDK without impacting other services.

**Comment by chrisradek** [comment]
@k3karthic 
I have just merged in a fix for this issue. Thanks for reporting it! The next version of the SDK will include the fix, or you can install the SDK from the GitHub repo directly.
