### ISSUE TITLE
setting ACL in presigned url

### ISSUE THREAD

**Issue by andrewgoodchild** [aws/aws-sdk-js#1335]
Hi,

I am having challenges with setting the ACL in presigned URLs.  

I have a node server with a route that allows a client to get a presigned URL using the javascript sdk.  We have segregated AWS accounts.  So, the node server is generating presigned URL for a bucket in a different AWS account and we have cross account access set up via a policy on the receiving bucket (and a policy on the AWS account with the node server is).

Here is a code fragment from that server that creates the presigned put url:

`
var s3 = new AWS.S3();
var params = {
        Bucket: new_file.bucket,
        Key: new_file.key,
        Expires: 1440,
        ContentType: new_file.content_type,
        ACL: 'bucket-owner-full-control',
        Metadata: {
                user: new_file.user,
                uuid: create_uuid()
        }
};

s3.getSignedUrl('putObject', params, function(err, url) {
        if (err) {
                response.outcome = con.OUTCOME.BAD_IMPLEMENTATION;
                response.message = err;
                resolve(response);
        } else {
                response.outcome = con.OUTCOME.SUCCESS;
                response.value.url = url;
                response.value.uuid = params.Metadata.uuid;
                resolve(response);
        }
});
`
This successfully creates a presigned URL:

`
Request URL:https://THE_BUCKET.s3.amazonaws.com/Test/test%281%29.jpeg?AWSAccessKeyId=XYZ&ContentType=image%2Fjpeg&Expires=1485737883&Signature=ZZZZZZ&x-amz-acl=bucket-owner-full-control&x-amz-meta-user=john.smith%40test.com&x-amz-meta-uuid=b8d45ca5-8788-4b5e-a5bc-ecacac13d472&x-amz-security-token=XXXXXX
`

The receiving bucket in another AWS account has the following policy, which ensures any uploaded files grant the bucket owner full control:

`
{
    "Version": "2012-10-17",
    "Id": "PolicyXXXX",
    "Statement": [
        {
            "Sid": "StmtYYY",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::NODE_SERVER_AWS_ACCT_ID:role/NODE_SERVER_ROLE",
                       "arn:aws:iam::NODE_SERVER_AWS_ACCT_ID:root"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::THE_BUCKET/*",
                "arn:aws:s3:::THE_BUCKET"
            ]
        },
        {
            "Sid": "StmtZZZZZ",
            "Effect": "Deny",
            "Principal": {
                "AWS": "arn:aws:iam::NODE_SERVER_AWS_ACCT_ID:role/NODE_SERVER_ROLE",
                       "arn:aws:iam::NODE_SERVER_AWS_ACCT_ID:root"
            },
            "Action": "s3:PutObject",
            "Resource": [
                "arn:aws:s3:::THE_BUCKET/*",
                "arn:aws:s3:::THE_BUCKET"
            ],
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        }
    ]
}
`

So, if we try this the AWS account with the receiving bucket throws a 403 error back when we try an upload using a pre-signed URL.

Now here is the confusing bit ...  we can do an upload using the AWS CLI running on an EC2 host in the same AWS account as the node server running using the same role as the node server.  CLI request here:

`
aws s3 cp test.jpg s3://THE_BUCKET/test/ --acl=bucket-owner-full-control
`

Now I know the CLI isnt doing presigned urls, so it is not an apples to apples comparison, but the policy is valid.

So I asked AWS support (we have enterprise support - so we white gloved it through with our TAM) and as we got nothing helpful back.  So I am hoping the community has some suggestions?  

Has anyone here used pre-signed URLs with an ACL granting the bucket owner full control in a cross account situation and gotten it to work?

**Comment by jeskew** [comment]
I will reach out to the S3 team to clarify whether the PutObject API should be honoring ACLs specified in pre-signed URLs. There are several parameters in this API that are only supported when represented as headers and are ignored when they are included in the query string of a presigned URL (e.g., server-side encryption directives and `ContentLength`).

**Comment by elginlam-amazon** [comment]
@jeskew I am the TAM for the account, please keep me updated on the case.

**Comment by andrewgoodchild** [comment]
For those who are interested I did solve my problem.  

I ended up writing a lambda function that creates a presigned URL and runs in the target bucket account.  I then set up cross account privileges to allow the server account to call the lambda in the target bucket account.  

Works a treat, ut I would have preferred to have the ability for the ACL to be honoured in the first place.

**Comment by jeskew** [comment]
@andrewgoodchild You can also use a [presigned POST policy](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createPresignedPost-property) to upload objects with ACLs directly from the browser. This feature lets you construct HTML forms that are submitted directly to S3, and those forms cover a few of the feature gaps in signed PutObject URLs.

**Comment by srchase** [comment]
@andrewgoodchild 

As it looks like you went a different direction, and there is also the option of presigned POSTs as @jeskew suggested, I'm going to close this issue.
