### ISSUE TITLE
[TypeScript] S3.Types.ClientConfiguration and SES.Types.ClientConfiguration missing credentialProvider

### ISSUE THREAD

**Issue by RLovelett** [aws/aws-sdk-js#1338]
The documentation for [`AWS.S3`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property) and [`AWS.SES`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#constructor-property) both state that they accept `credentialProvider`, which is an instance of [`AWS.CredentialProviderChain`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html), as part of the configuration options.

However, the declaration for [`ConfigurationOptions`](https://github.com/aws/aws-sdk-js/blob/67f8e309fb2ab748880a826911573beaa0e7986c/lib/config.d.ts#L155) does not expose such a parameter.

This prevents something like this from compiling:

```typescript
const s3 = new S3({
  region: `${process.env.GC_AWS_REGION}`,
  credentialProvider: new CredentialProviderChain([
    () => { return new EnvironmentCredentials('GC_AWS'); },
    () => { return new EnvironmentCredentials('GC_AMAZON'); },
    () => { return new SharedIniFileCredentials({ profile: 'govcloud' }); },
    () => { return new SharedIniFileCredentials({ profile: 'default' }); },
    () => { return new EC2MetadataCredentials(); }
  ]);
});
```

> foo.ts(45,3): error TS2345: Argument of type '{ region: string; credentialProvider: CredentialProviderChain; }' is not assignable to parameter of type 'ClientConfiguration | undefined'.
  Object literal may only specify known properties, and 'credentialProvider' does not exist in type 'ClientConfiguration | undefined'.

**Comment by RLovelett** [comment]
Also, for now I've been working around the issue by applying this patch before compiling.

```diff
diff -ub config.d.ts node_modules/aws-sdk/lib/config.d.ts                     11:19AM   typescript-conversion ±
--- config.d.ts	2017-02-02 11:18:22.000000000 -0500
+++ node_modules/aws-sdk/lib/config.d.ts	2017-02-02 11:17:38.000000000 -0500
@@ -2,6 +2,7 @@
 import {Agent as httpsAgent} from 'https';
 import {AWSError} from './error';
 import {Credentials, CredentialsOptions} from './credentials';
+import { CredentialProviderChain } from './credentials/credential_provider_chain';
 import {ConfigurationServicePlaceholders, ConfigurationServiceApiVersions} from './config_service_placeholders';

 export class ConfigBase extends ConfigurationOptions{
@@ -172,6 +173,10 @@
      */
     credentials?: Credentials|CredentialsOptions
     /**
+     * The provider chain used to resolve credentials if no static credentials property is set.
+     */
+    credentialProvider?: CredentialProviderChain
+    /**
      * AWS access key ID.
      *
      * @deprecated
```

I'd submit this as a PR but:

1. I know it works but I'm not sure this is the "right" way.
2. Perhaps these files are auto-generated and if that's the case then it's likely I need to fix that instead of just fixing the symptom.

**Comment by chrisradek** [comment]
@RLovelett 
Your patch looks correct. This file is not auto-generated, so it's safe to edit directly.

If you want to provide a PR we'd be happy to accept it! I'd just ask that you also add a new test case in https://github.com/aws/aws-sdk-js/blob/master/ts/config.ts and run `npm run tstest` to make sure it compiles after your change.

**Comment by RLovelett** [comment]
I will do that! 🙏 for the review @chrisradek
