### ISSUE TITLE
support a succinct way to control what credential loading methods are active

### ISSUE THREAD

**Issue by jdc0589** [aws/aws-sdk-js#1340]
There are lots of ways to load and inherit credentials with the SDK, this is a good thing. However the way in which credential loading silently supports fallbacks to different credential sources can introduce weird behavior in development environments. 

It would be great if there was a simple way to explicitly disable automatically loading credentials via any subset of the supported methods via the global `aws.config` interface (or somewhere else that made sense).

**Example:**
When credentials have not explicitly been set in the global configuration and aren't explicitly passed to client constructors (e.g. `new aws.s3()`), the SDK silently falls back to looking for credentials in the known credential file location (`~/.aws/credentials` on linux/osx). So, if I have the official aws-cli installed (which relies on the exact same credentials file), I'm working on an application that supports N aws accounts via configuration, and I forget to explicitly pass credentials to `new aws.s3()` (or any of the other clients), then I magically get an s3 client authenticated with the `[default]` credential in my local user's file. This isn't unexpected relative to the aws-sdk documentation, but it _is_ functionally unexpected within the context of plenty of applications someone could be developing, and could easily allow for unforeseen bugs to make it though that otherwise could have immediately been caught.

If there isn't already some way to control automatic credential loading fallbacks, it would be pretty handy to be able to do something along the lines of:

```javascript
var aws = require("aws-sdk");

aws.config.autoFileCredentials = false;
aws.config.autoEnvironmentCredentials = false; // not sure if env vars are even supported for anything other than profile name actually
```

Thoughts?

**Comment by jeskew** [comment]
Wouldn't this mean that pulling in a dependency could potentially alter the credential loading behavior of your application? I think using any global variable for this purpose would be dangerous.

If you would prefer to be explicit about where clients are loading credentials, wouldn't it be easiest to just pass your own credential provider chain to the client constructor?

**Comment by jdc0589** [comment]
I hadn't thought of that. That would potentially be way more ore confusing.

Hadn't stumbled across provider chains yet, but it looks like that will get
the job done.

Thanks.
