### ISSUE TITLE
Could not load aws-sdk using node.js

### ISSUE THREAD

**Issue by N1N** [aws/aws-sdk-js#1343]
Hi,

I installed node.js in my PC, and installed aws-sdk successfuly with the below command.
**npm install aws-sdk -g package.json**

I have a html file, in which i am trying to link aws-sdk. But it is failing.
Code looks like this,

var s3;
function inits3()
{
alert("alert1");
//var AWS = require('C:/Program Files/nodejs/node_modules/aws-sdk');
var AWS = require('aws-sdk');

alert("alert2");
s3 = new AWS.S3({ params: { Bucket: 'test' }});
}

**Note : I am getting the alert box message alert1 but not alert2**.

Please suggest!!

Regards.

**Comment by chrisradek** [comment]
@N1N 
Can you explain what sort of environment you're working in? Are you using a bundler like browserify or webpack to package your code for the browser?

If you're just trying to set up a simple HTML page with the SDK on it, you can include the SDK using a script tag:`<script src="https://sdk.amazonaws.com/js/aws-sdk-2.9.0.min.js"></script>`
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-the-jssdk.html

**Comment by N1N** [comment]
Hi @chrisradek ,

I am using just HTML page.I even added the tag <script src="https://sdk.amazonaws.com/js/aws-sdk-2.9.0.min.js"></script> to my HTML page.

I want to load the credentials from the file (Right now it is Hard coded,which is not preferred).

In that case, i need to use, 
**var AWS = require('aws-sdk');**
**AWS.config.loadFromPath('C:\Users\N1N\Desktop\config.json');**

But its not working for me.

I tried, bundling with browserify refering the following link,
http://browserify.org/#install

But still facing the same issue.
My project files looks like this.

1) Browserify main.js into header.js
---- main.js ----
var AWS = require('aws-sdk');
----- main.js ----

2)Add browserified header.js into HTML page.
----- index.html ----
<html>
<head> 
<script src="header.js"></script>
</head>

<script>
function inits3()
{

//Able to get this alert box
alert("1");
                // Load credentials and set region from JSON file
		AWS.config.loadFromPath('C:\Users\nandang\Desktop\config.json');
//Not able to get this alert box
alert("2");
		//var credentials = new AWS.SharedIniFileCredentials({profile: 'default'});
		//AWS.config.credentials = credentials;
	
  // create the AWS.Request object
        s3 = new AWS.S3({ params: { Bucket: 'nshost.com' }});
alert("Welcome to AWS!");
}
</script>
<body onload="inits3()">
</body>
</html>
----- index.html ----

**Comment by chrisradek** [comment]
@N1N 
The SDK doesn't have access to the file system from a browser environment, so you won't be able to use credentials stored in a file here.
Please take a look [here](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-browser.html) for instructions on how to load credentials in the browser. The suggested way is to use Cognito Identity for managing credentials.

With regards to your use of `require('aws-sdk')`, you would only import the SDK this way if you were building your front-end project with a tool like browserify or webpack that can bundle up your dependencies into consumable bundles. Browsers don't understand what `require` means on their own.
