### ISSUE TITLE
Type named 'Partial' conflicts with TS 2.1

### ISSUE THREAD

**Issue by JustASquid** [aws/aws-sdk-js#1344]
On line 151 of clients/cloudsearchdomain.d.ts we have:

`  export type Partial = boolean;`

Since the release of Typescript 2.1, ['Partial' is a special mapped type.](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html)

The code will still compile, however my IDE will continue to prompt an import for the AWS type when I just want to use the mapped type.

**Comment by jeskew** [comment]
I think changing the name of that exported type would be a breaking change (anyone who was importing it would encounter a compilation error).

Which IDE are you using? Perhaps there's a way to tell it not to prompt an import for types that are already defined in the global namespace.

**Comment by JustASquid** [comment]
I'm using the Webstorm IDE. I suppose it makes sense to file this as a bug in their court, unless there are some settings I'm missing.

**Comment by jeskew** [comment]
Closing, since there's not really anything the SDK can do short of changing the name of the exported type. If you do hear back from Jetbrains with tips on how to disable the prompts for importing `Partial`, please let us know!
