### ISSUE TITLE
S3.deleteObject - returns an empty data object

### ISSUE THREAD

**Issue by nathanmalishev** [aws/aws-sdk-js#1349]
Expected - Calling S3.deleteObject will return a data object with the properties listed https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#deleteObject-property

Actual - S3.deleteObject - returns an empty data object on successfully deleting an item from a bucket. It also returns an empty object when nothing is deleted from the bucket.

Tested using 
nodejs - 6.9.4, 7.4.0
aws-sdk: "^2.10.0"

**Comment by chrisradek** [comment]
@nathanmalishev 
Unless you are working with versioned objects, this is expected behavior.
Please see an earlier discussion at #1197

**Comment by nathanmalishev** [comment]
Thanks @chrisradek
