### ISSUE TITLE
polly:  Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by klinquist** [aws/aws-sdk-js#1353]
I'm trying to use AWS Polly - the exact example provided in the docs:

```
    var params = {
        OutputFormat: "mp3",
        SampleRate: "8000",
        Text: "All Gaul is divided into three parts",
        TextType: "text",
        VoiceId: "Joanna"
    };
    polly.synthesizeSpeech(params, function (err, data) {
        cb(err, data)
    });
```

I'm getting an error into the callback:   
`{"message":"Unexpected token < in JSON at position 0","code":"SyntaxError","time":"2017-02-09T18:38:06.459Z","statusCode":400,"retryable":false,"retryDelay":26.743564588273294}`

Using the latest aws-sdk.

**Comment by chrisradek** [comment]
@klinquist 
In the callback you provide to `synthesizeSpeech`, can you log `this.httpResponse.body.toString()`?

**Comment by chrisradek** [comment]
@klinquist 
It might also be helpful to log `this.httpResponse.headers`. The body should be a Buffer if the operation succeeds.

Is this happening intermittently? I just ran the operation with the exact same parameters in `us-east-1` and node `6.9.1`. Can you share your environment details and region?

**Comment by klinquist** [comment]
us-west-2,  node 6.9.4.    Not intermittent - happens every time.

![image](https://cloud.githubusercontent.com/assets/1343376/22798172/d386aa0a-eeb5-11e6-9be1-fcb5dc68bc0b.png)

**Comment by klinquist** [comment]
body toString is ```this.httpResponse.body.toString()
"<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-west-2' is wrong; expecting 'us-east-1'</Message><Region>us-east-1</Region><RequestId>63F538FBA8496F6C</RequestId><HostId>UXa+AHXPijKFkuitMtbi8Cc9Zy3edUSp6Y0E+gx/hVHZi44aZKuJUtH6Z2emPc8z/dBW7xFQntM=</HostId></Error>"```

Looks like I need to use us-east-1?

**Comment by klinquist** [comment]
Aah - nevermind.   Looks like my AWS.config was setting the endpoint (used the same config as I was using for an s3 api call).
