### ISSUE TITLE
AWS.CognitoIdentityServiceProvider's adminCreateUser returns "UserNotFoundException: User does not exist."

### ISSUE THREAD

**Issue by rsshilli** [aws/aws-sdk-js#1357]
Hello,

I'm trying to create a new user.  There are currently no users at all in my user pool.  I've checked in the console and programatically by calling deleteUser.  I'm also super confused why a "create user" command would return "user not found".  Of course the user isn't found... that's why I'm creating it.  :-)

I'm using AWS SDK 2.12.0 and Node 4.6.0 on Windows 10.  Here's the code I'm calling:

      var params = {
        UserPoolId: "@cognito_pool_id@",
        Username: email.replace("@", "__"),
        DesiredDeliveryMediums: ["EMAIL"],
        ForceAliasCreation: false,
        MessageAction: "RESEND",
        TemporaryPassword: tempPassword,
        UserAttributes: [
          { Name: "given_name", Value: firstName },
          { Name: "family_name", Value: lastName},
          { Name: "name", Value: firstName + " " + lastName},
          { Name: "email", Value: email},
          { Name: "custom:title", Value: "Made up title"},
          { Name: "custom:company", Value: companyName},
          { Name: "phone_number", Value: "+15124262345"}
        ],
      };
      console.log("Sending params to cognito: " + JSON.stringify(params));
      var cognitoIdentityServiceProvider = new AWS.CognitoIdentityServiceProvider({region: "us-east-1"});
      cognitoIdentityServiceProvider.adminCreateUser(params, function(error, data) {
        if (error) {
          console.log("Error adding user to cognito: " + error, error.stack);
        } else {
          console.log(data);
          module.exports.addUserToDB(firstName, lastName, email, "Rockets R US", "XXXXXXXX", callback);
        }
      });

My log statement prints the following, which looks good to me.  I X'd out the UserPoold.  The rest is fake test data including the phone num:

    Sending params to cognito: {"UserPoolId":"us-east-1_XXXXXXXXX","Username":"qdbvision-test__mailinator.com","DesiredDeliveryMediums":["EMAIL"],"ForceAliasCreation":false,"MessageAction":"RESEND","TemporaryPassword":"23x3l.023LQ","UserAttributes":[{"Name":"given_name","Value":"Ryan"},{"Name":"family_name","Value":"Rocket"},{"Name":"name","Value":"Ryan Rocket"},{"Name":"email","Value":"qdbvision-test@mailinator.com"},{"Name":"custom:title","Value":"Made up title"},{"Name":"custom:company","Value":"Rockets R US"},{"Name":"phone_number","Value":"+15124262345"}]}

When the error arrives, here's the output/stack trace:

    Error adding user to cognito: UserNotFoundException: User does not exist. UserNotFoundException: User does not exist.
        at emitNone (events.js:72:20)
        at IncomingMessage.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:921:12)
        at nextTickCallbackWith2Args (node.js:442:9)
        at process._tickDomainCallback (node.js:397:17)

I can add a very similar user with the exact same username & email through the browser using "amazon-cognito-identity-js" on our sign-up pages.  I wanted a quick way to do this on the back-end as a setup for test cases.

Any idea why I'm receiving this "UserNotFoundException"?

**Comment by jeskew** [comment]
I haven't set up a repro case for this yet, but wouldn't you expect to encounter a `UserNotFoundException` when the `MessageAction` parameter is set to `RESEND`? The [API reference](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html#CognitoUserPools-AdminCreateUser-request-MessageAction) implies that the "RESEND" action should only work on existing users.

**Comment by rsshilli** [comment]
Yup.  Right you are.  Changing RESEND to SUPPRESS fixed it.  Sorry to bother you!

**Comment by neerajaset71** [comment]
but are you getting welcome email with temp password after this change? I am not getting..what am I missing?

**Comment by jeskew** [comment]
Hi @neerajaset71,

That's the intended behavior if you set the `MessageAction` parameter to 'SUPRESS'. To create a new user and send a notification email, omit the `MessageAction` parameter.
