### ISSUE TITLE
[Request] Improve stack traces

### ISSUE THREAD

**Issue by awerlang** [aws/aws-sdk-js#1358]
Please, how can we have more helpful information in stack traces for DynamoDB (haven't confirmed for other services, like S3 or SES, but perhaps that's the same thing), to make it easier to make sense of it?

This is a sample stack trace for `ProvisionedThroughputExceededException`, but it's the same thing for invalid requests like invalid values sent over to DynamoDB.

I installed `longjohn` package but it didn't captured any trace of my application code.

```
Stack trace: ProvisionedThroughputExceededException: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API.
    at Request.extractError (/var/app/current/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/app/current/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/var/app/current/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/app/current/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/app/current/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/app/current/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/var/app/current/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/app/current/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/app/current/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by jeskew** [comment]
The stack traces from the DynamoDB client would be significantly longer than stack traces from SES or S3 due to the [higher number of retries enabled by default for that service](https://github.com/aws/aws-sdk-js/blob/4c768539749f4c3056d30a58fa0ddba28df5504c/lib/services/dynamodb.js#L44). 

I haven't used longjohn, but [their documentation states that stack trace length is configurable](https://github.com/mattinsler/longjohn#limit-traced-async-calls). You should be able to set that configuration parameter to `-1` to get a full trace.

**Comment by awerlang** [comment]
By default it limits on 10 frames, but it doesn't makes any difference, as a single frame is captured.

**Comment by jeskew** [comment]
So is the issue that the message provided by the service could be clearer?

**Comment by awerlang** [comment]
I'd like to see on the stack trace a trace to the originating call site, something that points to user code. It is okay to achieve this by requiring use of `longjohn`, as a regular stack trace usually points to library code anyways.

**Comment by wmonk** [comment]
Any updates on this issue? In certain situations it's hard to work out where the error actually originates from in my own code.

**Comment by yuta-imai** [comment]
I'm also struggling here.

**Comment by philiiiiiipp** [comment]
We have been experimenting with a couple of solutions to give us stack traces with the focus of getting the original place in our code when using dynamodb. We came up with:

```ts
const __client = new DynamoDB.DocumentClient()

const methods = [
  'batchGet',
  'batchWrite',
  'createSet',
  'delete',
  'get',
  'put',
  'query',
  'scan',
  'transactGet',
  'transactWrite',
  'update',
];

// @ts-ignore
export const Client = methods.reduce((prev, method) => {
  // @ts-ignore
  prev[method] = (...args) => {
    return {
      promise: async () => {
        const error = new Error();

        return __client[method](...args)
          .promise()
          .catch(async (e) => {
            e.message +=
              '\nExtended stack\n' +
              error.stack +
              '\n' +
              util.inspect(args, {
                showHidden: false,
                depth: null,
              });
          });
      },
    };
  };

  return prev;
}, {});
```

We currently only use this when running our tests locally, so we have not tested this in production or under load, but it has been very helpful there.

**Comment by ajredniwja** [comment]
Hey everyone, this needed a major version change which has been out now. V3 of the SDK should fix this. 

The [version 3.x](https://github.com/aws/aws-sdk-js-v3) of the AWS SDK for JavaScript is generally available. For more information see the [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/) or [API Reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html).

**Comment by philiiiiiipp** [comment]
Hey @ajredniwja I tried it and it seems to work there 🎉. The API's changed quite a bit, but the moment it has support for the `DocumentClient` I would happily switch. 

This is probably not the right place to ask this, but while on the topic, 

1. Do you know what the idea is to make this available inside the [Lambda runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)?
2. Will v2 become deprecated ?

**Comment by ajredniwja** [comment]
DocumentClient V3: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/dynamodb-example-dynamodb-utilities.html

1. V3 should be available in Node.js 18 runtime. 
2. V2 is currently in maintenance mode but no dates mentioned right now: https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html
