### ISSUE TITLE
getUrl forgets x-amz-security-token when using IAM STS

### ISSUE THREAD

**Issue by djechlin** [aws/aws-sdk-js#136]
I'm generating a URL using IAM STS, which requires a session token in the query string.  This token is missing and the URL returns a 403 with status InvalidAccessToken.  However manually adding &x-amz-security-token=... makes the URL work, so that is the patch I am currently using.

Causing my issue here - https://forums.aws.amazon.com/message.jspa?messageID=470481#470481

It seems you just need to add the parameter at this line here - https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L302 but I don't know if this will interfere with/break other forms of authentication.

FWIW we were able to figure this out in part from this issue here: https://github.com/boto/boto/issues/837

**Comment by koiker** [comment]
I'm testing the signing with query parameter for ES service and I got the same issue.
I need to include X-Amz-Security-Token and x-amz-security-token to work.
