### ISSUE TITLE
Add Dart support

### ISSUE THREAD

**Issue by DanTup** [aws/aws-sdk-js#1360]
I don't know if this belongs in this repo (if not, please point me where best to it) but since the TypeScript support is here I thought it'd be a good place to start.

More and more people are trying out Dart and it runs in both the browser and on the server (in a VM, similar to Node JS). It would be great to have an official Dart SDK similar to other platforms (I'm currently trying to use DynamoDB from Dart but it's turning out to be more involved than I'd hoped).

It's possible a lot of it could be generated from another SDK (I believe Google ported a lot of Java to Dart) as a starting point.

I'm sure there are many people in the Dart community who would happily contribute and send PRs; there are already a bunch of Dart AWS packages on pub.dartlang.org (though none anywhere near complete and some use JS-interop so only work in the browser).

**Comment by jeskew** [comment]
Hi @DanTup,

Is there anything a javascript package can do to make js-interop with Dart work better or more transparently? In an ideal world, we wouldn't need a separate SDK for compile-to-js languages like Dart or CoffeeScript but could instead support them better with the JavaScript SDK.

**Comment by DanTup** [comment]
@jeskew You could use the JS interop package to create bindings for Dart (like you do TypeScript), however that would limit its use to compiled-to-js Dart (eg. in the browser; maybe Node). Dart has a full VM that runs server side which I think is much more interesting and what I'm trying to do. This would require the code all be native Dart (the Dart VM runs Dart and not JavaScript).

At the moment I'm interested in DynamoDB, so I might have a go at porting the JS code for it; though I haven't started looking yet, I don't know how separated it is from the rest of the SDK (which is a much bigger job).

**Comment by jeskew** [comment]
The SDK is not split vertically across services but instead horizontally across concerns, so porting DynamoDB would mean porting most of the SDK. You would need to port (at least) the request signer, the credentials sourcing code, the JSON marshaller and unmarshaller, and the HTTP abstraction.

I'm going to go ahead and close this issue, as it isn't something the JS SDK can address, but I have passed this request along to see if this is something that could be taken on. There are also a few community-supported SDKs (such as [Rusoto](https://github.com/rusoto/rusoto), [PAWS](https://github.com/pplu/aws-sdk-perl), the [Haskell SDK](https://hackage.haskell.org/package/aws-sdk), etc), so there might already be a Dart SDK or one that's partially completed. 

Please feel free to reopen if you have any questions or concerns.
