### ISSUE TITLE
Add AES 256 encryption as a default for all the files.??

### ISSUE THREAD

**Issue by vyas07** [aws/aws-sdk-js#1362]
How to add AES 256 encryption as a default for all the files.??

any idea?

thankyou

**Comment by jeskew** [comment]
Hi @vyas07,

You could set the appropriate parameters as [bound parameters](https://github.com/aws/aws-sdk-js/blob/master/doc-src/guide/browser-services.md#bound-parameters) on the S3 client you're using.

FYI: Usage questions are a better fit for StackOverflow, which lets you pick the best answer and also ensures people googling similar questions will see your question and the answer provided. Make sure to tag usage questions with [`aws-sdk-js`](https://stackoverflow.com/questions/tagged/aws-sdk-js).
