### ISSUE TITLE
Unable to create a PresignedURL for RDS CopyDBSnapshot

### ISSUE THREAD

**Issue by grahamjenson** [aws/aws-sdk-js#1363]
To copy snapshots between regions it requires you to pass a 'PreSignedUrl' with the parameters 'DestinationRegion', 'KmsKeyId', 'SourceDBSnapshotIdentifier' so the best way to generate this url would be:

```
RDS.makeRequest("copyDBSnapshot", { 
 DestinationRegion: "", 
 KmsKeyId: "", 
 SourceDBSnapshotIdentifier: ""
}).presign(900)
```

However, because the RDS API requires the 'TargetDBSnapshotIdentifier' parameter, and does not allow for the 'DestinationRegion' parameter this makes it very difficult.

My workaround is to monkey patch the API definition on the RDS instance, e.g.

```
RDS.api.operations.copyDBSnapshot.input.required = ['SourceDBSnapshotIdentifier'] // Remove 'TargetDBSnapshotIdentifier'
sr_shape = RDS.api.operations.copyDBSnapshot.input.members['SourceRegion']
dr_shape = JSON.parse(JSON.stringify(sr_shape)) // Simple clone
dr_shape.name = 'DestinationRegion'
dr_shape.api = RDS.api
dr_shape.toWireFormat = sr_shape.toWireFormat
RDS.api.operations.copyDBSnapshot.input.members['DestinationRegion'] = dr_shape

// Now this will work
RDS.makeRequest("copyDBSnapshot", { 
 DestinationRegion: "", 
 KmsKeyId: "", 
 SourceDBSnapshotIdentifier: ""
}).presign(900)
```

The better solution would be to change the RDS api JSON definition file to remove the 'TargetDBSnapshotIdentifier' from required, and add DestinationRegion as a possible parameter.

**Comment by chrisradek** [comment]
@grahamjenson 
The SDK can generate the `PreSignedUrl` for you.

If you want to see some examples, we have some tests written around this functionality:
https://github.com/aws/aws-sdk-js/blob/master/test/services/rds.spec.coffee#L39

As long as the `SourceRegion` differs from the `DestinationRegion` and you don't pass in a `PreSignedUrl`, one should be generated for you.

**Comment by grahamjenson** [comment]
@chrisradek Cheers this has solved my issue. In case someone else comes along, this is what worked for me:

```
RDS = AWS.RDS({region: 'us-west-2'})

var params = {
  SourceDBSnapshotIdentifier: "arn:aws:...:snap_id",
  TargetDBSnapshotIdentifier: "new_snap",
  KmsKeyId: "...",
  SourceRegion: 'us-east-1'
};

RDS.copyDBSnapshot(params)
```
