### ISSUE TITLE
Unable to open downloded file .file corrupted 

### ISSUE THREAD

**Issue by vyas07** [aws/aws-sdk-js#1372]
Iam using putOblect  API for uploading files .After uploading file to amazon the file is corrupted and unable to open .
          ```
  ```
  var params = {
            Bucket: "testing",
            Key : 'test/live.jpg'
            Body:"hello",
        };
    s3.putObject(params, function(err, data) {
           console.log(params)
             if(err){
                   console.log(err)
              } else{
                    console.log(data,"the data is")
                     }
              } )
```
```
```
please respond asap.

thanks in advance.
```

**Comment by chrisradek** [comment]
@vyas07 
How are you downloading the object? Can you make a getObject call directly, and check that the body matches your text?

If you're downloading the object from the browser and opening it on your computer, the jpg extension with a text body is probably causing the issue.

**Comment by vyas07** [comment]
hey @chrisradek 

this is what iam getting in console when i **get** the uploaded file .what should be given in body to get proper image or file.  please help me in getting this.

**browser console when i GET the object**
```
Object
Body
:
Uint8Array[5]
0
:
104
1
:
101
2
:
108
3
:
108
4
:
111
buffer
:
(...)
byteLength
:
(...)
byteOffset
:
(...)
length
:
(...)
Symbol(Symbol.toStringTag)
:
(...)
__proto__
:
Uint8Array
ContentType
:
"application/octet-stream; charset=UTF-8"
ETag
:
""5d41402abc4b2a76b9719d911017c592""
LastModified
:
"Sat, 25 Feb 2017 10:54:33 GMT"
Metadata
:
Object
VersionId
:
"kzNZ2io86hjm3GzrxDx6SVnIynRzDnPW"
__proto__
:
Object
```

**Comment by jeskew** [comment]
@vyas07 The Uint8Array in the response data dump contains the bytes for the string "hello" encoded in UTF-8. Try running the following in the Chrome console:

```js
const arr = new Uint8Array([104, 101, 108, 108, 111])
const decoder = new TextDecoder('utf8')
console.log(decoder.decode(arr)) // prints "hello"
```

To upload a JPEG image from a browser to S3, you will need to load the image from the file system into the browser's JavaScript runtime. MDN has a [good tutorial](https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications) on how to use files in web applications.

**Comment by vedavyas772** [comment]
Hey @jeskew 
Even if I did not give the body.... it is showing the size of the image/file  is zero .I think it's not the issue with 'body"

**Comment by vyas07** [comment]
hey @jeskew  iam getting the same body text when i get the object .i came to know that if we pass body  then it is taking the size of the object.But unable to open the downloaded image/file.when i download or open  the file it is saying cannot open the file  &  the size of the file downloaded  is **1kb** in local .
