### ISSUE TITLE
 putObject never returns any response. 

### ISSUE THREAD

**Issue by testtshoretel** [aws/aws-sdk-js#1373]
@lsegal Hi, yesterday we encountered the problem in our production system: all putObject API  calls are without any response. Other test and staging systems are fine. 
I know there is AWS.config.httpOptions.timeout for http inactivity timeout. But I guess in our case, the network BW may have some issue so upload is very very slow. I want to know how to limit **retry** times for putObject and how to set the **response timeout** (not http inactivity timeout) here.  I try to use nodejs 
setTimeout but there is complicated logic to take care if Timeout happens before putObject Response comes back. 

Also, I want to use AWS.upload to improve upload. Is there any way to limit retry times and set response timeout for this?

Thanks,

**Comment by chrisradek** [comment]
@testtshoretel 
To clarify, in node.js, `AWS.config.httpOptions.timeout` specifies the amount of time an assigned socket can be idle before timing out.

It is possible to abort a request. This should effectively allow you to set a response timeout.
```javascript
var req = s3.putObject({/*params*/});
req.on('send', function() {
  // abort request after 5 seconds
  setTimeout(function() {
    req.abort();
  }, 1000 * 5);
});
req.send(function(err, data) {
  console.log(err, data);
});
```

You can also limit the number of retries for operations by specifying [`AWS.config.maxRetries`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#maxRetries-property)
```javascript
var s3 = new AWS.S3({
  maxRetries: 1
});
```

If you want to limit the amount of delay between retries, there's an option for that as well!
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#retryDelayOptions-property

**Comment by srchase** [comment]
@testtshoretel 

I apologize we haven't responded sooner.

I'm not sure I fully understand your last question.  Can you restate your question?  Or did you get this resolved already?
