### ISSUE TITLE
CognitoIdentityServiceProvider listUsers

### ISSUE THREAD

**Issue by vanerleo** [aws/aws-sdk-js#1374]
```
  var params = {
            UserPoolId: 'XXXXX',
            Filter: 'email="Ashlee-Heathcote@xxxxxxx.com"',
            Limit: 1
        };
return cognitoIdentityServiceProvider.listUsers(params).promise()
```

throws
```
message: 'Unexpected key \'Filter\' found in params',
  code: 'UnexpectedParameter',
```

While Using command line (cli) with the same filter works

`cognito-idp list-users --user-pool-id xxxxxx --filter 'email="Ashlee-Heathcote@xxxxxx.com"' --limit 1`

running aws-sdk@2.21.0

**Comment by chrisradek** [comment]
@vanerleo 
Is this is node.js or the browser?

I ran the following in node.js v6.9 and am not receiving the same error:
```javascript
var AWS = require('aws-sdk');
AWS.config.update({
    region: 'us-west-2'
});

var cogdp = new AWS.CognitoIdentityServiceProvider();
cogdp.listUsers({
    UserPoolId: 'POOL_ID',
    Limit: 1,
    Filter: 'email="my@realaddress.com"'
}).promise().then(function(data) {
    console.log(JSON.stringify(data, null, 2));
}).catch(function(err) {
    console.error(err);
});
```

**Comment by vanerleo** [comment]
nodejs v7.2.1

**Comment by chrisradek** [comment]
The `Filter` field was added in version `2.4.11` of the SDK. That error you're getting indicates that `Filter` field isn't modeled, but it definitely exists:
https://github.com/aws/aws-sdk-js/blob/master/apis/cognito-idp-2016-04-18.normal.json#L3596

Just to be sure, can you also log AWS.VERSION right after you instantiate your service client? `2.21.0` should definitely have the field, and with my test it is there.

**Comment by vanerleo** [comment]
Great hint, yep, looks like its loading OLD version from somewhere
