### ISSUE TITLE
DynamoDB DocumentClient doesn't translate class instances

### ISSUE THREAD

**Issue by spencerhakim** [aws/aws-sdk-js#1378]
While reading through the new code, I noticed that due to the way `typeOf` works [here](https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/types.js#L8-L9), `convertInput` will just implicitly return `undefined` due to the if-else chain [only specifically handling `'Object'`, as well as not having a terminating `else` statement](https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/converter.js#L15-L49). I'd expect the instance to be translated like any other object (of course, I'd be responsible for converting it back from an arbitrary object to a class instance).

Example:
```js
const AWS = require("aws-sdk/global");
require("aws-sdk/clients/dynamodb");
const typeOf = require("aws-sdk/lib/dynamodb/types").typeOf;

class MyClass {
    constructor() {
        this.someProp = 123;
    }
}
let myInstance = new MyClass();

console.log(typeOf(myInstance)); // 'MyClass'
console.log(AWS.DynamoDB.Converter.input(myInstance)); // undefined

let myObject = {
    someProp: 123
};

console.log(typeOf(myObject)); // 'Object'
console.log(AWS.DynamoDB.Converter.input(myObject)); // { M: { someProp: { N: '123' } } }
```

**Comment by jeskew** [comment]
This seems like a usage pattern that the DocumentClient should support. I'll mark this as a feature request and add an item to our backlog.

**Comment by spencerhakim** [comment]
I think this should also be considered a bug. At a minimum, if this isn't a supported pattern, an error should be thrown instead of just silently converting my data to `undefined`.

**Comment by jeskew** [comment]
That's fair. I'll update the tag.
