### ISSUE TITLE
Memory leak on s3 getObject for node 7.7.0

### ISSUE THREAD

**Issue by optimisme** [aws/aws-sdk-js#1385]
Hi,

I run s3 getObject thousands of times from a bucle and it causes a memory leak on node 7.7.1, the same source does not have any problems on node 7.5.0.

This is the source I am having problems with:

    loadText (path, callback) {

        let params = {},
            pathFull = this.getBase(path) + path

        params = {Key: pathFull}
        this.s3bucket.getObject(params, (err, data) => {
            callback(err, data)
        })
    }

Executing the same source without the getObject call works fine.

**Comment by optimisme** [comment]
Maybe it is important, I use this function with promises:

    promiseLoadText (path) {
        return new Promise((resolve, reject) => {
            return this.loadText(path, (err, rst) => { if (err) { return reject(err) } else { return resolve(rst) } })
        })
    }

And the call: 

try { await promiseLoadText('/file.txt') } catch (e) { console.log(e) }

**Comment by optimisme** [comment]
Hi,

At my main source, there is no difference using 'getObject' with 
callbacks or with '.promise()' (allways from async functions, I can't change that)

I readied an example reading a file from the filesystem and also from S3, 
the memory keeps growing when reading from S3 (using the same file)

This is running on node 7.7

When I run 'top' while executing the script these are the results:

- Memory stays at 1.1% for node 7.7 reading from filesystem
- Memory KEEPS GROWING for node 7.7 reading from S3 (over 5% waiting some hours)

This is the example:
(call 'promiseLoadS3' or 'promiseLoadFile' from 'call' function)

// main.js ---------------------------------------------------------------------

var 
    aKey        = '...',
    sKey        = '...',
    buck        = '...',
    path        = '...'

var
    aws         = require('aws-sdk'),
    https       = require('https'),
    agent       = new https.Agent({ maxSockets: Infinity }),
    s3bucket    = null,
    fs          = require('fs')

async function promiseLoadFile () {

    return new Promise(async (resolve, reject) => {
        let path = './file.json.gz',
            data = null

        fs.readFile(path, function (err,data) {
            if (err) { return reject(err) }
            return resolve(data)
        })
    })
}

async function promiseLoadS3 () {

    return new Promise(async (resolve, reject) => {
        let params = {Key: path},
            data = null

        try {
            data = await s3bucket.getObject(params).promise()
        } catch (err) {
            return reject(err)
        }

        return resolve(data)
    })
}

async function call () {

    let cnt = 0,
        rst = null

    aws.config.update({sslEnabled: true, accessKeyId: aKey, secretAccessKey: sKey, region: 'us-east-1', httpOptions: { agent: agent, timeout: 1000000 }})
    s3bucket = new aws.S3({ params: { Bucket: buck }})
    
    try {
        for (cnt = 10000000000; cnt >= 0; cnt = cnt - 1) {
            rst = await promiseLoadS3()
            console.log(cnt)
        }
    } catch (err) {
        console.log(err)
    }
}

call()

**Comment by optimisme** [comment]
Hi @chrisradek, why the 'Question' label?

**Comment by optimisme** [comment]
Any news about this issue?

**Comment by srchase** [comment]
@optimisme 

Is this still an open issue for you?  Quite a bit of time (and node versions) have passed since it was originally opened.
