### ISSUE TITLE
erratic putBucketLifecycleConfiguration behavior 

### ISSUE THREAD

**Issue by marcoeg** [aws/aws-sdk-js#1386]
The code below gives erratic results. When the `expireS3object()` function is called once the object expiration is not set, and no error. If called more than once, only the expiration date for the object in the last invocation is set.

The function is called in node/express.

Please advise.

```var AWS = require('aws-sdk'); 
var awsS3Client = new AWS.S3(config.s3credentials);

function expireS3object(s3object) {
  var s3params = {
      Bucket: 'vederly-service',
      LifecycleConfiguration: {
          Rules: [
              { 
                  Prefix: s3object, 
                  Status: 'Enabled',
                  Expiration: {
                      Days: 1,
                  }
              }
          ]
      }
  }
  awsS3Client.putBucketLifecycleConfiguration(s3params, function(err, data) {
    if (err)
      logger.log(err);
    else 
      logger.log("Changed expiration days for " + s3object);
  });
```

**Comment by jeskew** [comment]
In the example code provided, only the input passed to `expireS3object` is logged if no error is encountered. The `PutBucketLifecycleConfiguration` operation [does not return any response data](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTlifecycle.html), so you would need to call `aws.S3Client.getBucketLifecycleConfiguration` to see the updated value.

FYI: StackOverflow is a better forum for questions about how to use an AWS service, as answers provided there are more discoverable than answers provided on GitHub.

**Comment by marcoeg** [comment]
But checking the expiry date for the objects on the S3 console doesn't show any updated value for most of the times. Most likely it is a bug.

**Comment by marcoeg** [comment]
I misinterpreted the way `putBucketLifecycleConfiguration` works. I had mistakenly thought it would add a rule when it is instead replacing all the previous ones. Hence only the last was actually stored. You were right in closing this issue.
