### ISSUE TITLE
AppStream.createStreamingURL doesn't automatically authenticate me even though the credentials are specified in the config

### ISSUE THREAD

**Issue by osdavison** [aws/aws-sdk-js#1387]
I'm using the below code to create a new URL for an appStream session, but the server return 403 Forbidden.

`var cred = new AWS.Credentials('MyAccessKey', 'MySecretKey')

            AWS.config.update({ credentials: cred });
            AWS.config.update({ region: 'us-east-1' });
            AWS.config.update({ endpoint: 'https://appstream2.us-east-1.amazonaws.com' });
            AWS.config.apiVersions = { appstream: '2016-12-01' }
            AWS.endpoint = new AWS.Endpoint('https://appstream2.us-east-1.amazonaws.com')

            // Get AWS url
            var params = {
                FleetName: 'AppStream_Testing_Fleet',
                StackName: 'AppStream_Testing_Stack',
                UserId: username,
            };
            
            var appstream = new AWS.AppStream();

            appstream.createStreamingURL(params, function (err, data) {
                if (err) console.log(err, err.stack); // an error occurred
                else { // successful response
                    console.log(data);
                    $location.path(data.StreamingURL)
                }
            });`

Request sent by the SDK:
`OPTIONS https://appstream2.us-east-1.amazonaws.com/ HTTP/1.1
Host: appstream2.us-east-1.amazonaws.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Access-Control-Request-Method: POST
Origin: http://localhost:41658
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Access-Control-Request-Headers: authorization, content-type, x-amz-content-sha256, x-amz-date, x-amz-target, x-amz-user-agent
Accept: */*
DNT: 1
Referer: http://localhost:41658/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,es;q=0.6`

Server response from Fiddler:
`HTTP/1.1 403 Forbidden
x-amzn-RequestId: 6fa36106-ff85-11e6-b099-4dd4a37e4a0f
Content-Length: 127
Date: Thu, 02 Mar 2017 20:18:44 GMT

<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>`

**Comment by chrisradek** [comment]
@osdavison 
Are you running the SDK in a browser or in node.js? The request looks like it's from the browser, in which case `AWS.config.loadFromPath()` shouldn't work, since it requires access to the filesystem.

One thing, it doesn't look like your credentials are being used once you've created them. You can pass them into your `AppStream` service client like this:
```javascript
var appstream = new AWS.AppStream({
  credentials: new AWS.Credentials('ID', 'SECRET'),
  region: 'us-east-1'
});
```

Note that I passed in a region instead of an endpoint. The SDK knows how to generate the endpoint based on the region and service name, so if you're using a standard endpoint, you shouldn't have to specify it.

**Comment by osdavison** [comment]
I'm running it in a browser. I was testing the loadFromPath function and forgot to change it back. I have updated my original question.

The code you suggested doesn't work for me. I did some digging and found that the httpRequest **does** have the necessary headers, but that the XMLHTTPRequest doesn't actually send them. 

Function from the SDK that sends the request:

> 35: [ function(require, module, exports) {
        var AWS = require("../core");
        var EventEmitter = require("events").EventEmitter;
        require("../http");
        AWS.XHRClient = AWS.util.inherit({
            handleRequest: function handleRequest(httpRequest, httpOptions, callback, errCallback) {
                var self = this;
                var endpoint = httpRequest.endpoint;
                var emitter = new EventEmitter();
                var href = endpoint.protocol + "//" + endpoint.hostname;
                if (endpoint.port !== 80 && endpoint.port !== 443) {
                    href += ":" + endpoint.port;
                }
                href += httpRequest.path;
                var xhr = new XMLHttpRequest(), headersEmitted = false;
                httpRequest.stream = xhr;
                xhr.addEventListener("readystatechange", function() {
                    try {
                        if (xhr.status === 0) return;
                    } catch (e) {
                        return;
                    }
                    if (this.readyState >= this.HEADERS_RECEIVED && !headersEmitted) {
                        try {
                            xhr.responseType = "arraybuffer";
                        } catch (e) {}
                        emitter.statusCode = xhr.status;
                        emitter.headers = self.parseHeaders(xhr.getAllResponseHeaders());
                        emitter.emit("headers", emitter.statusCode, emitter.headers);
                        headersEmitted = true;
                    }
                    if (this.readyState === this.DONE) {
                        self.finishRequest(xhr, emitter);
                    }
                }, false);
                xhr.upload.addEventListener("progress", function(evt) {
                    emitter.emit("sendProgress", evt);
                });
                xhr.addEventListener("progress", function(evt) {
                    emitter.emit("receiveProgress", evt);
                }, false);
                xhr.addEventListener("timeout", function() {
                    errCallback(AWS.util.error(new Error("Timeout"), {
                        code: "TimeoutError"
                    }));
                }, false);
                xhr.addEventListener("error", function() {
                    errCallback(AWS.util.error(new Error("Network Failure"), {
                        code: "NetworkingError"
                    }));
                }, false);
                xhr.addEventListener("abort", function() {
                    errCallback(AWS.util.error(new Error("Request aborted"), {
                        code: "RequestAbortedError"
                    }));
                }, false);
                callback(emitter);
                xhr.open(httpRequest.method, href, httpOptions.xhrAsync !== false);
                AWS.util.each(httpRequest.headers, function(key, value) {
                    if (key !== "Content-Length" && key !== "User-Agent" && key !== "Host") {
                        xhr.setRequestHeader(key, value);
                    }
                });
                if (httpOptions.timeout && httpOptions.xhrAsync !== false) {
                    xhr.timeout = httpOptions.timeout;
                }
                if (httpOptions.xhrWithCredentials) {
                    xhr.withCredentials = true;
                }
                try {
                    console.log(httpRequest);
                    console.log(xhr);
                    xhr.send(httpRequest);
                } catch (err) {
                    if (httpRequest.body && typeof httpRequest.body.buffer === "object") {
                        xhr.send(httpRequest.body.buffer);
                    } else {
                        throw err;
                    }
                }
                return emitter;
            },
            parseHeaders: function parseHeaders(rawHeaders) {
                var headers = {};
                AWS.util.arrayEach(rawHeaders.split(/\r?\n/), function(line) {
                    var key = line.split(":", 1)[0];
                    var value = line.substring(key.length + 2);
                    if (key.length > 0) headers[key.toLowerCase()] = value;
                });
                return headers;
            },
            finishRequest: function finishRequest(xhr, emitter) {
                var buffer;
                if (xhr.responseType === "arraybuffer" && xhr.response) {
                    var ab = xhr.response;
                    buffer = new AWS.util.Buffer(ab.byteLength);
                    var view = new Uint8Array(ab);
                    for (var i = 0; i < buffer.length; ++i) {
                        buffer[i] = view[i];
                    }
                }
                try {
                    if (!buffer && typeof xhr.responseText === "string") {
                        buffer = new AWS.util.Buffer(xhr.responseText);
                    }
                } catch (e) {}
                if (buffer) emitter.emit("data", buffer);
                emitter.emit("end");
            }
        });
        AWS.HttpClient.prototype = AWS.XHRClient.prototype;
        AWS.HttpClient.streamsApiVersion = 1;
    }, {
        "../core": 21,
        "../http": 34,
        events: 6
    } ],

**Comment by jeskew** [comment]
@osdavison Per the CORS spec, [browsers must exclude user credentials from preflight requests](https://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0). XHR is acting as it should.

The issue is that AppStream does not support CORS and is therefore not handling OPTIONS requests any differently from GET or POST requests, which is to say that it attempts to authenticate them. I believe that you would see similar behavior from most services on [our supported services list](https://github.com/aws/aws-sdk-js/blob/master/SERVICES.md) that do not have a :tada: icon in the 'Allows CORS' column.

**Comment by osdavison** [comment]
Are you saying that it is an issue with the AppStream API? How can I do this differently so I won't encounter this error?

**Comment by jeskew** [comment]
You cannot use AppStream from a web browser. Their API does not support cross-origin resource sharing, so browsers will block the request from being sent if it contains an `Authorization` header.

You can submit open a thread on the [AppStream forum](https://forums.aws.amazon.com/forum.jspa?forumID=233) to request that they add support for CORS. 

In the meantime, you could use Lambda as a middleman to invoke AppStream operations. Lambda does accept CORS requests, and CORS limitations do not apply when invoking an API from a node environment like AWS Lambda.

**Comment by osdavison** [comment]
I used Fiddler to ignore the response from the API and send the GET request anyways and it worked fine then. Why is that if the API doesn't support cross origin sharing?

**Comment by jeskew** [comment]
If you're referring to [this Fiddler](https://chrome.google.com/webstore/detail/fiddler/hkknfnifmbannmgkdliadghepbneplka?hl=en), I believe browser extensions are not subject to the same restrictions as code running on a web page. 

In any case, requiring authentication on an OPTIONS request means that AppStream does not support CORS per the specification. The best way to get the service to change this is to request on [their AWS developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=233) that they add support for CORS.

**Comment by osdavison** [comment]
I was actually talking about [this Fiddler](http://www.telerik.com/fiddler). I will look into using Lambda. Thanks for your help.
