### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by Almad** [aws/aws-sdk-js#139]
When using aws-sdk 1.4.0 on node v0.8.25

I am trying to fetch an object from S3:

```
  aws               = require 'aws-sdk'

  aws.config.update
    accessKeyId:     process.env.AWS_API_KEY
    secretAccessKey: process.env.AWS_SECRET

  bucket = new aws.S3 params: Bucket: process.env.BUCKET
  client   = bucket.client
  request = client.getObject Key: fileKey

  request.on 'httpError', (err) ->
    console.error 'http error', err

  request.send()
```

I am getting

```
http error { [NetworkingError: Hostname/IP doesn't match certificate's altnames]
  code: 'NetworkingError',
  retryable: true,
  name: 'NetworkingError' }
```

Is there any workaround?

**Comment by DelvarWorld** [comment]
Not sure if this will help anyone, but:

The domain for my files in S3 is as follows:

    s3-us-west-1.amazonaws.com

But when I instantiate the sdk and pass in `"region": "s3-us-west-1"`, I get the same Hostname/IP error. It turns out the string you're supposed to pass is just "us-west-1" without the s3- prefix.
