### ISSUE TITLE
MTurk Sandbox

### ISSUE THREAD

**Issue by isTravis** [aws/aws-sdk-js#1390]
Hello! Thanks for the exciting new updates with the 2017-01-17 API. 

I'm trying to create HITs with the mturk service. Everything is working fine if I simply call `const mturk = new AWS.MTurk`, but this creates the HIT on the production environment. I'm trying to find how to use the MTurk sandbox, but can't find it anywhere in the documentation. 

I know I can set a custom endpoint, and was able to piece together from the API code that the production endpoint is `https://mturk-requester.amazonaws.com`. Is there a requester sandbox endpoint? I tried a few guesses, but none of them resolved. 

Searching the whole repo for the word `sandbox` didn't lead to any useful results, and the docs seem to never mention the MTurk sandbox at all. Apologies if I'm missing something - and thanks for your support!

**Comment by taneemtee** [comment]
Hi Travis - thanks for opening this. The sandbox endpoint is: https://mturk-requester-sandbox.us-east-1.amazonaws.com.

I apologize for the Sandbox endpoint not being easy to find in our docs - we'll be adding it in a few places to make it easier to find.

***
Here is an example of Javascript code calling the sandbox -
```
var AWS = require('aws-sdk');
var region = 'us-east-1';

AWS.config = {
    "region": region,
    "sslEnabled": 'true'
};

var endpoint = 'https://mturk-requester-sandbox.us-east-1.amazonaws.com';

// Uncomment this line to use in production
// endpoint = 'https://mturk-requester.us-east-1.amazonaws.com';

var mturk = new AWS.MTurk({ endpoint: endpoint });

// This will return $10,000.00 in the MTurk Developer Sandbox
mturk.getAccountBalance(function(err, data){
    console.log(data.AvailableBalance);
});
```
When calling in production, you can also just call  var mturk = new AWS.MTurk(), without specifying the endpoint, but I find it helps keep it clearer when I do.
