### ISSUE TITLE
Getting InvalidParameterException without host port in container definition

### ISSUE THREAD

**Issue by harishreddy-m** [aws/aws-sdk-js#1397]
SDK version : aws-sdk@2.25.0

As per documentation
If you want an automatically assigned host port, use the following syntax:

"portMappings": [
    {
        "containerPort": integer
    }
    ...
]

When I omit hostPort or set hostPort as 0 
I am getting the error
A host port mapping for the container port 80 is required.

**Comment by jeskew** [comment]
Hi @harishreddy-m,

Have you tried asking on the [ECS developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=187)? That forum is monitored by engineers who work on ECS.

**Comment by harishreddy-m** [comment]
I tried posting on forum.I got error like this.
_Your account is not ready for posting messages yet. Please try again later._ 

Can someone post it on behalf of me.

I am able to run my task without hostPort in portMappings.App is running at dynamically assigned 32774 port.

When I try to create a service behind Application load balancer - I am getting following error.
InvalidParameterException : A host port mapping for the container port 80 is required.

Here is my service creation definition
 var params = {
      desiredCount: 1,
      cluster:"my-first-cluster",
      loadBalancers: [
        {
          containerName: name,
          containerPort: 80,
          loadBalancerName: "harish-alb-ecs"
        }
      ],
      role: "ecsInstanceRole",
      serviceName: name+"-alb",
      taskDefinition: taskDef
    };


Then I tried to manually create the service from aws console GUI - Same task is running and ec2 instance is registered as listener to ALB automatically.But the health check fails- I tried increasing timeout,interval of health check without any success.

Is Application Load balancer stable?

**Comment by jeskew** [comment]
I opened a question on your behalf at https://forums.aws.amazon.com/thread.jspa?threadID=251584

**Comment by jeskew** [comment]
Hi @harishreddy-m,

I heard back from the service team, and it looks like you need to specify a `targetGroupArn` property in the load balancer definition in the call to ECS.createService when the load balancer is an ALB. (This is documented on the [`createService` property](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECS.html#createService-property).)
 
If the `targetGroupArn` is missing, ECS assumes that the load balancer specified is a classic ELB load balancer, and classic LBs require a static host port. The ECS team is looking into ways to improve the error messaging for this particular issue, but adding targetGroupArn should unblock you.

Please feel free to reopen if you have any questions or concerns.
