### ISSUE TITLE
Response of S3.listObjectsV2 won't contains Owner parameter in data.Contents

### ISSUE THREAD

**Issue by huoqi** [aws/aws-sdk-js#1400]
version: 2.6.0, 2.27.0 (I just tested these two version)

S3.listObjects is working fine, but listObjectsV2 can not return data.Contents.Owner parameter.

Could anyone confirm that?
<img width="479" alt="s3 listobjectsv2 data contents" src="https://cloud.githubusercontent.com/assets/7303359/23843768/123f12c6-07f9-11e7-9c3d-2ed09a40c451.png">

**Comment by jeskew** [comment]
Hi @huoqi,

By default, listObjectsV2 does not include the data's owner in response returned. You can modify this behavior by setting the `fetchOwner` input parameter to `true`:
```javascript
s3.listObjectsV2({Bucket: bucketName, fetchOwner: true}, function(err, data) {
    // if err is null, data.Contents.Owner should be set
});
```
