### ISSUE TITLE
Failure to scan DynamoDB table in `setInterval` callback

### ISSUE THREAD

**Issue by maxcountryman** [aws/aws-sdk-js#1401]
Hello,

I'm experiencing a bizarre issue where I am unable to scan a DynamoDB table from the callback of `setInterval`. Please see the snippet below:

```js
import AWS from 'aws-sdk';

const activeHosts = {};


// Setup DynamoDB.
const docClient = new AWS.DynamoDB.DocumentClient({
  region: 'us-west-1',
  dynamoDbCrc32: false,
});


function getActiveHosts(cb) {
  const TableName = 'Hosts';
  docClient.scan({ TableName }, (err, data) => {
    if (data.Items) {
      cb(data.Items);
    } else {
      cb([]);
    }
  });
}


function setActiveHosts() {
  getActiveHosts((hosts) => {
    hosts.forEach(({ Host, Config }) => {
      const hostConfigMap = {};
      hostConfigMap[Host] = Config;
      Object.assign(activeHosts, hostConfigMap);
    });
  });
}


// Poll the active hosts configuration periodically, i.e. every 30 seconds.
setInterval(setActiveHosts, 1000 * 30);
```

If I call `setActiveHosts` directly after its definition it returns the expected data, but when it's called from the `setInterval` callback, I get an empty object.

What could possibly be going on here?

**Comment by jeskew** [comment]
Hi @maxcountryman,

I wasn't able to reproduce with a simplified example. It looks like the `getActiveHosts` function will convert any error into an empty array; it's possible that an unrelated error is occurring. Can you add a logging statement to the callback statement passed to `docClient.scan` to capture any error returned?

**Comment by maxcountryman** [comment]
@jeskew if I allow the CRC check I get a CRC error and data is `null`.

Note that it works when called outside of `setInterval`.

Node v7.4.0.

**Comment by maxcountryman** [comment]
```
console.log(err, data) -->

{ CRC32CheckFailed: CRC32 integrity check failed
    at Request.checkCrc32 (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/services/dynamodb.js:23:35)
    at Request.callListeners (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/max/Documents/projects/prism/node_modules/aws-sdk/lib/event_listeners.js:233:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  message: 'CRC32 integrity check failed',
  code: 'CRC32CheckFailed',
  retryable: true,
  time: 2017-03-13T21:26:37.497Z,
  statusCode: 200 } null
```

**Comment by jeskew** [comment]
Just to clarify, you don't see any issues when the CRC32 check is disabled? I believe that a related issue may have been reported to the Java SDK where CRC32 checks fail when receiving throttling exceptions. Scans tend to use a lot of read capacity, so executing one every 30 seconds could cause throttling issues.

**Comment by maxcountryman** [comment]
No I see issues in both cases. If The CRC check is disabled I see null data and no error when called from the setInterval callback. If enabled and when called from the setInterval I see the above error. Note that in both cases when setActiceHosts is called in line it works consistently. The only place it seems to fail is inside of setInterval.

**Comment by jeskew** [comment]
I think you're running into throttling issues, as that would explain why the behavior is different in `setInterval` vs just directly calling the scan operation a single time. I'll need to look into why no error is being surfaced to the callback.

**Comment by maxcountryman** [comment]
I raised the allowed reads to 100 per minute and still see the same issue.

**Comment by jeskew** [comment]
The amount of read capacity used by a scan is proportional to the amount of data in the table. (See http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithTables.html#CapacityUnitCalculations for details.) Without knowing how large the table being read is, I can't say whether a 100 read capacity units is enough to allow a full scan every 30 seconds.

Could you inspect the HTTP response being returned from the scan operation? It would be the calling context for the callback passed to `docClient.scan`; if you use an unbound function rather than an arrow function, you should be able to view the raw HTTP response by calling `console.log(this.httpResponse.body.toString())`

**Comment by maxcountryman** [comment]
Sure. I'll do that in a moment. I can tell you the table has 26 entries, each containing a small JSON blob of three or four keys.

**Comment by maxcountryman** [comment]
@jeskew I modified the code in this way:

```js
function getActiveHosts(cb) {
  const TableName = 'Hosts';
  const params = { TableName };
  docClient.scan(params, function (err, data) {
    console.log(this.httpResponse.body.toString());
    if (data && data.Items) {
      cb(data.Items);
    } else {
      cb([]);
    }
  });
}
```

However I don't see anything in the console, it's logging what appears to be a line break.

**Comment by maxcountryman** [comment]
(Note that the CRC32 check is still failing. If I log the `err` I see the same error message.)

**Comment by jeskew** [comment]
Could you log the headers and status code? (`this.httpResponse.headers` and `this.httpResponse.statusCode`, respectively.) 

Sorry to keep sending you back to gather more data, but I'm still trying to reproduce this locally.

**Comment by maxcountryman** [comment]
@jeskew Not a problem. Here's the output from `this.httpReponse.headers` and `this.httpResponse.statusCode` respectively:

```
{ server: 'Server',
  date: 'Tue, 14 Mar 2017 19:12:29 GMT',
  'content-type': 'application/x-amz-json-1.0',
  'content-length': '11581',
  connection: 'keep-alive',
  'x-amzn-requestid': 'LVDC9787R33D0IE9RGF0S0014BVV4KQNSO5AEMVJF66Q9ASUAAJG',
  'x-amz-crc32': '1885504171' }

200
```

**Comment by jeskew** [comment]
I heard from the AWS Support rep you were working with that the root cause had been identified as a third-party module. Please feel free to reopen if that turns out to be incorrect or if you have any further questions.

**Comment by maxcountryman** [comment]
The issue surfaced through a third-party library but I believe is due to the fact the SDK makes assumptions about the configuration of the underlying Node HTTP machinery.

I have isolated the issue to [a specific release over at the Raven repo](https://github.com/getsentry/raven-node/releases/tag/v1.1.3).

You and your team may be in a better position to understand how this affects the SDK and the assumptions it makes. If this is indeed a configuration issue I would suggest at the very least documenting this constraint and if possible enforcing those configuration parameters within the SDK itself.

I would consider this an SDK bug.

**Comment by jeskew** [comment]
The SDK will only listen to `data` events if the underlying node engine does not support v2 of the streams API. It's the only way we can be sure that we don't lose any data from responses.

It looks like Raven made [a change to keep the library from automatically transitioning response streams from 'paused' mode to 'flowing' mode](https://github.com/getsentry/raven-node/issues/273). Do you see any issues when using the latest version of Raven with the SDK?

**Comment by maxcountryman** [comment]
That's also the change I highlighted as the likely cause.

From the AWS SDK's end, *please* enforce this configuration! Again: this is an assumption on this library's part and needs to be documented and if possible enforced within the library itself: Fail to run if not set properly or at the very least display a prominent warning.

The latest Raven release seems to work.

**Comment by jeskew** [comment]
It's not configuration that's exposed to the SDK; [any readable stream can be transitioned to flowing mode by attaching a listener to its `data` event](https://nodejs.org/api/stream.html#stream_two_modes). I'll look into how we can better document incompatibilities with libraries that coerce streams from paused to flowing mode.

**Comment by maxcountryman** [comment]
At a minimum this is a documentation bug. Thanks for looking into this.
