### ISSUE TITLE
DynamoDB maxRetries=0 never resolves?

### ISSUE THREAD

**Issue by tomowens3** [aws/aws-sdk-js#1402]
It will take me sometime to figure out a way to force a retryable error with DynamoDB but I am sharing my findings thus far.

We have an API with a sub 150ms P99 which are trying to improve. I understand that the default maxRetries is 10 with +56sec of potential latency with the default exponential delay calculation and that the timeout is disable by default. I attempted first to reduced the maxRetries to zero because we do not even want to wait the 50ms for the first retry attempt. Failing fast.

However it appears that there is a bug in the SDK where if maxRetries are set to 0 and the error is retryable where:

1. A retry call happens even when maxRetries is set to zero.
2. Because of the IF condition check below the retryCount is never incremented and never fails.

https://github.com/aws/aws-sdk-js/blob/fb2fef795899bf6fe3bb81411777bc11474bf385/lib/event_listeners.js#L141

```
add('RESTART', 'restart', function RESTART() {
      var err = this.response.error;
      if (!err || !err.retryable) return;

      // This appears to say if the request is retryable then retry it. 
      this.httpRequest = new AWS.HttpRequest(
        this.service.endpoint,
        this.service.region
      );

      if (this.response.retryCount < this.service.config.maxRetries) {
        this.response.retryCount++;
      } else {
        this.response.error = null;
      }
    });

```

**Comment by jeskew** [comment]
Hi @tomowens3,

Whether a request gets retried get determined in `AWS.util.handleRequestWithRetries`, [which always checks if `retryCount < maxRetries`](https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L844). Did you observe requests never resolving?

**Comment by tomowens3** [comment]
I should have held on submitting the ticket until I had repro steps with a test table and shareable code.

Also, it appears I was looking into the wrong code path. Will continue to dig deeper.
