### ISSUE TITLE
stream data with managed upload, how to tell managed upload the stream is end?

### ISSUE THREAD

**Issue by testtshoretel** [aws/aws-sdk-js#1403]
Hi,

I am trying to use managed upload to upload big files (5Gb), here is my flow: 

client send http req with big files -> server(my work) read data req.on('data', function(data)), once data buffer reaches 10 Mb, server will call managed upload with this buffer. 

This way, server does not need to save the file to the local disk and also does not need to use a lot of memories. 

My question is once server get req.on('end'),  how should server tell managed upload it is the last buffer to send? 

Thanks,

**Comment by chrisradek** [comment]
@testtshoretel 
If the data you want to upload to S3 is a stream, then you can just set the stream as the `Body`.

```javascript
s3.upload({
  Bucket: 'BUCKET',
  Key: 'KEY',
  Body: your_readable_stream
}, function(err, data) {
  /* do stuff */
});
```

By default this will attempt to upload up to 4 parts, each 5MB, at a time until the upload completes.

You can also configure the `ManagedUpload` to change the part size and concurrency:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#constructor-property

Once the source stream is `end`ed, the managed uploader should be notified automatically.

**Comment by testtshoretel** [comment]
Hi Chrisadek,

Thanks for the quick response. In my case, all data is many buffers from http payload req.on('data'),  If I do not want to streamifier those buffers, is there any way to tell managed upload it is end?

**Comment by chrisradek** [comment]
Are you using the managed uploader in the SDK, or doing a multi-part upload directly?
The managed upload in the SDK only allows one body to be set, so you'd have to either pass in all of your buffers at once, or a stream. Is there a reason you can't pass the stream directly to s3.upload?

**Comment by testtshoretel** [comment]
In my case, client send file(5gb)  with http request, server(my job) parse the payload and do the upload to S3. I do not want to save the file to disk or use very large buffer(memories), so what I want to do is get the data buffer and then upload. I guess I could not use managed upload in this case and I should use multipart upload directly. Am I right?

**Comment by chrisradek** [comment]
@testtshoretel 
In your case, it sounds like you have 2 options.
1) Parse the payload using a transform stream, then pass the transform stream to s3.upload.
2) Do a multipart upload directly.

Since s3.upload can only handle a single Body, it would have to be a stream for your use case.

**Comment by testtshoretel** [comment]
@chrisradek  Thanks. I tried to use option 1 and  googled transform buffers to stream but could not find an   example, can you give me some links for transform multiple buffers to stream?

**Comment by chrisradek** [comment]
The request your server receives should already be a stream. When you call `on('data')` on the `req` object, you're listening to the stream's `data` events. You can `pipe` this into a transform stream. 

I would suggest looking into some of the node.js API documentation to get more details on working with streams.
[incoming requests are readable streams](https://nodejs.org/dist/latest-v7.x/docs/api/http.html#http_class_http_incomingmessage)
[implementing transform streams](https://nodejs.org/dist/latest-v7.x/docs/api/stream.html#stream_implementing_a_transform_stream)

**Comment by jeskew** [comment]
Closing as answered by the earlier comments. Please feel free to reopen if you have further questions.
