### ISSUE TITLE
Feature Request: --Query to EC2.describeInstances

### ISSUE THREAD

**Issue by gitisz** [aws/aws-sdk-js#1404]
DescribeInstances brings back a lot of data, is it possible to add the "--query" argument?

**Comment by jeskew** [comment]
The CLI's query argument evaluates a JMESPath expression, which the SDK uses internally but does not expose at the moment. You could include [the JavaScript version of JMESPath](https://github.com/jmespath/jmespath.js) as a top-level dependency of your application and run the `jmespath.search` method it exposes on any JS object or array.

**Comment by jeskew** [comment]
@gitisz Does using the JMESPath library directly solve your issue, or were you looking for something built into the SDK? Not sure if I should close this out or mark it as a feature request.

**Comment by gitisz** [comment]
I haven't had a chance... but I believe it will solve my issue.  Thanks for pointing me to this :)

**Comment by jeskew** [comment]
Happy to help! Let me know if you have any questions about how to use JMESPath.js.
