### ISSUE TITLE
AWS.Rekognition is not a constructor

### ISSUE THREAD

**Issue by palakons** [aws/aws-sdk-js#1410]
I am trying to implement Rekognition on Node.js following codes on [this reference](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Rekognition.html)

requir ing aws module using

> var AWS = require('aws-sdk');

I got this error

> TypeError: AWS.Rekognition is not a constructor

Can you recommend any fix?

**Comment by jeskew** [comment]
Which version of the SDK are you using? Support for Rekognition was added in [2.11.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#2110)

**Comment by palakons** [comment]
looks like this is the issue... 
as my npm install aws-sdk@2.1.39 for me

I tried uploaded to AWS Beanstalk, still get same error though

pls bear with me, I'm really new to node.js

**Comment by palakons** [comment]
I managed to have aws-sdk 2.28.0
rekognition worked now, thanks :)
