### ISSUE TITLE
DMS.createEndpoint times out when called from Lambda

### ISSUE THREAD

**Issue by Ballhorn** [aws/aws-sdk-js#1413]
I have a Lambda function that creates a role in a RDS instance that is then passed as a parameter to DMS target endpoint. The problem is that whenever I try to call DMS.createEndpoint the function times out. I can create the endpoint manually from the console with exactly the same parameters.

I tried increasing timeout to 25 seconds with no help. The Lambda function uses a role that has AmazonDMSVPCManagementRole attached to it.

Example parameters below:

 

```
{
EndpointIdentifier: '********',
EndpointType: 'target',
EngineName: 'postgres',
DatabaseName: '********',
Password: '*********',
Port: 5432,
ServerName: '***********.rds.amazonaws.com',
SslMode: 'none',
Tags: [ { Key: '*******', Value: '********' } ],
Username: '************'
 }
```

Thanks in advance!

**Comment by jeskew** [comment]
Hi @Ballhorn,

Are all resources used by the Lambda function available in the VPC in which the function is running? 

You might also want to try posting this question in the [AWS Lambda forum](https://forums.aws.amazon.com/forum.jspa?forumID=186), the [AWS DMS forum](https://forums.aws.amazon.com/forum.jspa?forumID=216), and on StackOverflow. The former two are monitored by Lambda and DMS engineers, respectively.

**Comment by Ballhorn** [comment]
I found a solution. My function was in a VPC to be able to connect the RDS instance. This prevented me from calling DMS.createEndpoint function and timed out instead.

I put the RDS part that required VPC to a separate Lambda function and called it from another Lambda function that handled the DMS part and wasn't in a VPC.

**Comment by jeskew** [comment]
Glad you were able to track that down. Please feel free to reopen if you have any questions or concerns.
