### ISSUE TITLE
APIGateway:getBasePathMappings returning empty object

### ISSUE THREAD

**Issue by JordanSinko** [aws/aws-sdk-js#1416]
Hello,

Recently something has changed with the APIGateway:getBasePathMappings response. Before, if my domain didn't have any mappings, I would get a response object like so:

```
{
    items: []
}
```

Now when I run it we get an empty object:

```
{}
```

Was this intended? If so, are there other response objects that also changed?

Thank you!

**Comment by chrisradek** [comment]
@JordanSinko 
Did your version of the SDK change? If so, what were the versions involved?

**Comment by JordanSinko** [comment]
@chrisradek 
More info.. When I view the network traffic on the AWS console, it also returns an empty object for

`https://console.aws.amazon.com/apigateway/backend/domainnames/{{domainName}}/basepathmappings?limit=1000`

It appears to be a broader issue than the SDK/CLI.

**Comment by chrisradek** [comment]
@JordanSinko 
Did this just start happening? Right now this is sounding like an issue on API Gateway's side, but knowing when the last time you saw the old behavior would help. Also, what region are you running in?

**Comment by JordanSinko** [comment]
Region: us-east-1

Seems to be recent, within the last couple of weeks. Coincidentally, around the time the AWS console UI changed for the Custom Domain Names view.

**Comment by JordanSinko** [comment]
@chrisradek 
More info.. I added a base path to the domain having issues, and then immediately removed it. Once removed, and when I call GetBasePathMappings on it, I get the expected response of
```
{
    items: []
}
```

It appears the issue of it not returning the right response happens when the domain name is first created and no mappings have been added.

**Comment by JordanSinko** [comment]
Closing. https://forums.aws.amazon.com/thread.jspa?threadID=251826&tstart=0
