### ISSUE TITLE
Support using the SDK in a ServiceWorker context

### ISSUE THREAD

**Issue by treyrich** [aws/aws-sdk-js#1423]
So, unfortunately I'm not sure when this started happening, but our code (which has worked flawlessly for a long time now) seems to be broken by a fairly recent SDK update.

As a point of reference, this is the flow our application is taking:
1. At the very start of our app we update our config:
```js
var cognitoCredProvider = new AWS.CognitoIdentityCredentials({
  IdentityPoolId: this.authConfig.cognitoIdentityPoolId
});
AWS.config.update({
  region: cognitoRegionType,
  credentials: cognitoCredProvider
});
```
2. Once the user successfully authenticates with our service, we supply them with a developer authenticated identity token:
```js
cognitoCredProvider.params.IdentityId = IDENTITY_ID;
var logins = {};
logins['cognito-identity.amazonaws.com'] = TOKEN;
cognitoCredProvider.params.Logins = logins;
cognitoCredProvider.expired = true;
```
3. At some later time, a request is made to an AWS service, let's say to delete an S3 object for example. When the call to delete this S3 object is made, the browser fires off a POST request which results in the following error:
`POST https://cognito-identity.us-east-1.amazonaws.com/ 400 (Bad Request)`
```json
{"code":"BadRequest","message":"The server did not understand the operation that was requested.","type":"client"}
```

Again, it's not terribly clear, when this started happening, but the error that we're receiving is very vague and doesn't seem related to our code at all. It seems as if the issue is that the aws-sdk-js library is making a call incorrectly. If this isn't the case, I'd welcome the chance to be proved incorrect so that we can get our app functioning properly again.

**Comment by chrisradek** [comment]
@treyrich 
Did you recently update the version of the SDK you're using? If so, do you know from what to what?

For the error message you're getting, could you share what the `X-Amz-Target` header on that request looks like? I'd expect something like `AWSCognitoIdentityService.GetCredentialsForIdentity`

Also, we have seen some issues where the region the CognitoIdentityCredentials uses was incorrect. By default, it will use whatever `AWS.config.region` is set to at the time it is instantiated. You can now specify the region when instantiating your credentials directly:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html#constructor-property

**Comment by treyrich** [comment]
@chrisradek thanks for the quick reply!

Unfortunately, this was something missed by our tests, and our package.json was configured incorrectly and this library has been updating freely, so this has possibly been broken over the course of a couple of different versions (hate it when that happens!). So I can't track down the exact version that this started occurring.

Here's the request headers:
```
Content-Type:application/x-amz-json-1.1
Origin:http://localhost:5555
Referer:http://localhost:5555/profile
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
X-Amz-Content-Sha256:801f1cb7f717cb7778c7ec6d80721e3db93fd9b343007100a1fdaef4b6ec2238
X-Amz-Target:AWSCognitoIdentityService.GetCredentialsForIdentity
X-Amz-User-Agent:aws-sdk-js/2.30.0 callback
```

I just tested by setting the region directly, and have the same result, but I would have expected that since the request is being made to `https://cognito-identity.us-east-1.amazonaws.com/` and we're using the us-east-1 region.

**Comment by chrisradek** [comment]
Do you happen to get a `requestId` back in the response, or is that missing as well?

I meant to ask before, does this error always occur, or is it sporadic?

**Comment by treyrich** [comment]
Yes, there is a request ID. Here's the response headers:
```
access-control-allow-origin:*
access-control-expose-headers:x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
connection:keep-alive
content-length:113
date:Wed, 22 Mar 2017 17:29:42 GMT
x-amzn-requestid:233609a1-0f25-11e7-b000-e71ef302849e
```
Based on tests today, this seems to happen 100% of the time. But I only caught the error today, so I can't say much beyond that.

**Comment by chrisradek** [comment]
@treyrich 
As a sanity check, is it possible to try version `2.7.20` of the SDK? `2.7.21` was the last time we made a change to the CognitoIdentityCredentials that wasn't purely additive.

**Comment by treyrich** [comment]
No problem. I just tried it, and it's not working on that version either. Same error.

I know FOR SURE we have been functional since 2.7.x though. So maybe this isn't an issue with the SDK? Is it possible a server-side change on AWS caused an issue with the compatibility of this SDK? My mind keeps going back to the fact that I seem to be the only one having this issue (based on the lack of bug reports), which means it probably is project specific. But the relevant code in the project hasn't changed for close to a year.

**Comment by chrisradek** [comment]
@treyrich 
I tried reproducing your issue with the same type of credentials, but I haven't been able to get an error message yet.

At this point, it might be worth reaching out to the Cognito team directly on their forums:
https://forums.aws.amazon.com/forum.jspa?forumID=173
They may be able to help determine if the issue is related to your configuration in some way.

If you open an issue, feel free to link back here. It looks like you're calling the parameters correctly, but the error coming back is from the service, so they may be able to provide more info on what's going on.

**Comment by treyrich** [comment]
Fair enough. I posted this thread https://forums.aws.amazon.com/thread.jspa?threadID=252029

**Comment by jeskew** [comment]
Hi @treyrich,

I heard back from the Cognito team, and it looks like the request in question was being sent to `https://cognito-identity.us-east-1.amazonaws.com/index.html` (instead of to the . Since the issue isn't fixed by using a different version of the SDK, is it possible that a browser plugin or a proxy server is altering the request in flight?

**Comment by treyrich** [comment]
Hey @jeskew thanks for the response. I was actually wondering about the lack of activity on the forum post I made.

So, interestingly enough we have recently introduced a Service Worker into our project, it hadn't occurred to me that it could be connected though since all other services/APIs we're using work perfectly and the service worker is only caching specific resources.

Have you guys tried running the API along with a service worker? It would be interesting to know whether this is something specific to our implementation of a service worker, or if this is a global problem with service workers.

(To confirm it's definitely related to service workers I've verified by testing in Safari which doesn't support service workers and everything seems to function properly.)

**Comment by jeskew** [comment]
While some services may work in some browsers, I wouldn't recommend using the SDK in service workers. The browser version of the SDK has a hard dependency on XMLHttpRequest, which [doesn't appear to be available in all ServiceWorker implementations](https://bugzilla.mozilla.org/show_bug.cgi?id=931243). XML-based services (like S3 and Ec2) also use the Document API to parse responses, which would not be available in service or web workers.

**Comment by treyrich** [comment]
@jeskew sorry, I may not have made this clear. We aren't using the SDK in a service worker, but we're using it alongside a service worker. When you have a service worker installed all network traffic flows through the worker (basically as an in-browser proxy). See https://github.com/w3c/ServiceWorker/blob/master/explainer.md#network-intercepting

So although we aren't trying to make use of the SDK within the service worker, we are using the service worker within our application which causes all network traffic to pass through. I expect that as ServiceWorkers get more and more prevalent (which Google is pushing hard for with Chrome) this will become more pronounced of an issue if the SDK has some incompatibility with this paradigm though.

I think there is some potential that our specific implementation of a service worker could be causing this incompatibility, but we're using other 3rd party APIs (LinkedIn, FB, Twilio, etc) without any issue so I guess the question is whether any testing has been done in a web app with a service worker? If not I think someone (probably me) needs to build a barebones app with the SDK and a skeleton service worker to determine whether this is a broad issue, or specific to this particular case.

**Comment by jeskew** [comment]
I think you're probably right: there may be something in the particular service worker implementation being used that's resolving requests from the bare domain to `/index.html`. I can set up a test case with S3 and Dynamo to determine if we support using the SDK on a page that also happens to be using service workers.

**Comment by jeskew** [comment]
I put together [a small test](https://gist.github.com/jeskew/1a8bc1a6d21158b17c74f6041444d863) that uses service workers in the background and also uses Cognito and was not able to reproduce.

I didn't get a chance to dig too deeply into the mobile toolkit, but are you using a manifest like the one on [this page](https://github.com/angular/mobile-toolkit/blob/d585cc9edbd9391cae08d88ebda8bf2dd6a2e618/guides/service-worker.md) for any endpoints? There's a `routing` section at the bottom of the manifest that maps the root to `/index.html`, which may be what's causing the issue you're encountering.

**Comment by treyrich** [comment]
Interesting. Ok, I'll look into that. Obviously if that routing section of the manifest results in other domains being routed that's a fairly large issue on their end.

Let me look into that before you go any further with this in case it's a bug on Google's end, I truly appreciate all the help so far! I'll update once I find out if that is indeed what's causing this issue.

**Comment by treyrich** [comment]
Ok. I've confirmed, this is indeed a bug with the Angular Mobile Toolkit.

I have opened this issue here: https://github.com/angular/mobile-toolkit/issues/135

Thanks for all the help here, sorry for the false alarm, this is obviously a very frightening bug to have in the Angular code.

**Comment by henrysachs** [comment]
has anybody a solution for this? or do we still live with this bug and go on?
