### ISSUE TITLE
Issue with documentation on (update|delete)CloudFrontOriginAccessIdentity()

### ISSUE THREAD

**Issue by dinvlad** [aws/aws-sdk-js#1429]
Hi team,

I believe there are a couple problems with this SDK's documentation and/or typings on the following methods:

1) the official API doc for `DeleteCloudFrontOriginAccessIdentity` lists `If-Match` as a required parameter: http://docs.aws.amazon.com/cloudfront/latest/APIReference/API_DeleteCloudFrontOriginAccessIdentity.html#API_DeleteCloudFrontOriginAccessIdentity_RequestSyntax
> The request **requires** the following URI parameters.
Id
If-Match

However, this parameter is listed as optional in the `deleteCloudFrontOriginAccessIdentity()`, which leads to confusion when using this SDK method. It's also reflected in the associated definitions for Typescript, which should remove the `?:` syntax for that parameter in this call.

2) For the `updateCloudFrontOriginAccessIdentity()` call, it incorrectly implies that `CallerReference` must be _unique_ per update _request_, and if the contents of `CloudFrontOriginAccessIdentityConfig` changes then this request will fail with `CloudFrontOriginAccessIdentityAlreadyExists`. But that would prohibit us to update `Comment`, while it's possible to do so using the Console and/or CLI!

In fact, the SDK errors out when I specify a _new_ value for `CallerReference` in this call, saying that `You cannot update the value of CallerReference`. However, when I specify the _old_ `CallerReference` (as used in `createCloudFrontOriginAccessIdentity()`), and set a new `Comment`, it updates successfully, despite that the doc implies that such request would fail. So the behavior described in the doc for that method is the opposite to what happens in practice.

Please let me know if I should delegate it to the forums instead, but it does seem like an issue with this SDK rather than a general problem with the API (which does behave according to its docs).

Thanks

**Comment by jeskew** [comment]
Hi @dinvlad,

Which parameters are marked as required comes from the model files shared by all the AWS SDKs, and the ultimate source for that information is the service team themselves. The same is true for the documentation provided for services and API operations. 

I've let the CloudFront team know that they should investigate whether the IfMatch parameter is always required. I would recommend asking this question on the forums as well.

**Comment by dinvlad** [comment]
Ok, thank you. Will ask it on the forums.

**Comment by jeskew** [comment]
Closing, as there's nothing the SDK can do on its own. I will update this issue when I hear back from the CloudFront team.
