### ISSUE TITLE
Disable ELB stickiness

### ISSUE THREAD

**Issue by riteshatsencha** [aws/aws-sdk-js#1430]
I see one can create stickiness policies for a given LB, but is there a way to disable it? I can't seem to locate any information on it in the docs. Please advise.

Thank you,

Ritesh

**Comment by jeskew** [comment]
Hi @riteshatsencha,

Calling [`createAppCookieStickinessPolicy`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ELB.html#createAppCookieStickinessPolicy-property) or [`createLBCookieStickinessPolicy`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ELB.html#createLBCookieStickinessPolicy-property) creates a policy but does not enable it on any particular load balancer. To enable one or more policies, you would need to call [`setLoadBalancerPoliciesOfListener`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ELB.html#setLoadBalancerPoliciesOfListener-property) and provide an array of the names of the policies you would like to enable on the load balancer identified with the `LoadBalancerName` property. To disable one or more policies, you would need to call the `setLoadBalancerPoliciesOfListener` operation again and omit the names of the policies you would like to disable. ELB has [a section in their developer guide](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.htm) on sticky sessions if you want to dive a little deeper on the topic.
