### ISSUE TITLE
awsm doesn't work when package is included via npm link

### ISSUE THREAD

**Issue by iwllyu** [aws/aws-sdk-js#1433]
I have a package DynamodbUtils that makes calls to dynamodb using aws sdk.

MyPackage installs DynamodbUtils from an private npm registry. In a test in MyPackage I mock dynamodb via
```
        awsm.mock('DynamoDB.DocumentClient', 'query', (params, callback) => {
            // console.log("querying with params: %j", params);
            callback(null, mockDynamodbResponse);
        });
```

and later call the DynamodbUtils function that will eventually call (the mocked) dynamodb. Everything works as expected. 

However if I go into DynamodbUtils and `npm link`, and then in MyPackage do `npm link DynamodbUtils` and then try to run the test, I get `ResourceNotFoundException: Requested resource not found` and the error originates comes from DynamodbUtils/node_modules/aws-sdk/lib dir, which seems like AWS is no longer being mocked appropriately.

**Comment by jeskew** [comment]
That does sound like the SDK is not being stubbed in the way you intended, but it doesn't sound like an issue in the SDK. Which mocking library are you using?

**Comment by iwllyu** [comment]
oh sorry this is totally on the wrong forum - this should be opened at aws-sdk-mock

apologies
