### ISSUE TITLE
aws cognito user pool authentication sdk

### ISSUE THREAD

**Issue by jmparsons** [aws/aws-sdk-js#1434]
I'm currently using the `react-native` branch and including the source code manually from https://github.com/aws/amazon-cognito-identity-js/ to ad hoc the sdk onto the cognito identity service provider. It works with some caveats https://github.com/aws/amazon-cognito-identity-js/issues/340.

Are there any plans to merge the cognito sdk together in the future like how it is with the ios and android mobile sdk's?

**Comment by jeskew** [comment]
Hi @jmparsons,

Other than the latency encountered doing BigInteger math in the Cognito SDK, have you encountered any difficulties integrating the two SDKs in a project?

**Comment by jmparsons** [comment]
Hi @jeskew, 

The only part that stands out is the persistence layer. Inside of the cognito sdk is the StorageHelper class: 

https://github.com/aws/amazon-cognito-identity-js/blob/master/src/StorageHelper.js

It does mimic every method already available in react-native using AsyncStorage here:

https://github.com/facebook/react-native/blob/master/Libraries/Storage/AsyncStorage.js

With the differences being the AsyncStorage calls are asynchronous using promises. The cognito library uses the values mostly in one class CognitoUser for storing sessions and tokens. 

The integration was very straightforward. I copied the src folder, then changed all of the imports to point to the react-native version of aws-sdk-js:

```javascript
// AuthenticationHelper.js, CognitoAccessToken.js, CognitoToken.js, CognitUser.js
import { util } from 'aws-sdk/global';
// to this:
import { util } from 'aws-sdk/dist/aws-sdk-react-native';

// CognitoUserPool.js
import CognitoIdentityServiceProvider from 'aws-sdk/clients/cognitoidentityserviceprovider';
// to this:
import { CognitoIdentityServiceProvider } from 'aws-sdk/dist/aws-sdk-react-native';
```

Then created a file to load AWS and map the classes onto it using lodash:

```javascript
// AWS.js
import AWS, { CognitoIdentityServiceProvider } from 'aws-sdk/dist/aws-sdk-react-native';
import _ from 'lodash';
import * as enhancements from '../AWSCognito/src';

_.assign(CognitoIdentityServiceProvider, enhancements);

export default AWS;
```

**Comment by rbbruce** [comment]
Howdy,

We have recently stumbled across this issue when exploring Cognito for an app we are building for react native. Can you give any background as to why this is an issue? Additionally, can you give any status of a fix for this issue?

Thanks,
RB Bruce

**Comment by jmparsons** [comment]
@rbbruce I ended up writing a bridge module to compute modpow. It was taking 6 seconds on the simulator and 20+ seconds on the device before. I used https://github.com/kirsteins/JKBigInteger/ the same library that is used in the aws IOS sdk. Java does modpow natively. Now modpow is instant. 

I was planning on releasing it, but I ended up changing the source code quite a bit from the cognito identity library - converted it to use promises. If I have time I will recreate it as a standalone, but that may not be for awhile.

**Comment by rbbruce** [comment]
@jmparsons Thanks for the quick response. We have not gotten that far with the testing. Will keep the delay in mind. That could make things a bit more interesting.

What about having to bring source code in from amazon-cognito-identity-js into the react-native branch? Is that something that is in queue to be fixed? This method seems to be the cleanest implementation for using Cognito with react native. Just concerned about using this method in production. 

Thanks,
RB Bruce

**Comment by jmparsons** [comment]
@rbbruce Even if it's merged in, the modpow method won't change and really is just too slow in javascript. The cognito library is mostly getters and setters for data modeling, the majority of the code is in CognitoUser and AuthenticationHelper, both of which rely on modpow to generate their auth values. I'm going to make my setup a library probably within the next month to separate it out of my project.

**Comment by jmparsons** [comment]
@jeskew @rbbruce I've open sourced my project. 

https://github.com/AirLabsTeam/react-native-aws-cognito-js

https://github.com/aws/amazon-cognito-identity-js/issues/327#issuecomment-297166971

**Comment by rbbruce** [comment]
@jmparsons Thank you! Will check it out!

**Comment by rahuljaguste** [comment]
thank you @jmparsons . You just helped me save 10 secs of boot time for my app. 👍
