### ISSUE TITLE
compress json file using zlib before uploading to s3

### ISSUE THREAD

**Issue by karna41317** [aws/aws-sdk-js#1435]
It would be valuable to have the ability to configure AWS.S3 upload method to compress files before uploading them to s3. At the moment we manually download, compress, upload, delete uncompressed files. Perhaps something like:

```
params =  {
     Bucket: 'branch2s3.ebuilder.io',
     Key: file.json`,
     Body: data,
     ContentType: 'application/json',
    ACL: 'public-read', 
    compress: 'gzip'  --> using gzip
}
```

What do you think ? or is there any other good approach for this ?

**Comment by jeskew** [comment]
Hi @karna41317,

I'm not sure it would be a good idea for the SDK to take on this responsibility, as we would need to find a way to offer that functionality in the browsers we support. Both the `putObject` and the `upload` methods on an S3 client will accept a stream object, so you could pipe the uncompressed file through a [`zlib.Gzip` stream](https://nodejs.org/api/zlib.html#zlib_class_zlib_gzip) before handing it to the S3 client.
