### ISSUE TITLE
Auto Create Presigned URL for Cross Region RDS Copy like python library does

### ISSUE THREAD

**Issue by Deamoner** [aws/aws-sdk-js#1437]
I've been trying to get a node lambda working to cross region copy our rds snapshots for DR purposes. 

I'm getting stuck on calculating the Pre-signed URL mostly because it is a complicated process and I cannot figure out how to validate it beyond it just saying it's wrong. 

Python library creates the pre-signed url for you as per the link below, but node does not do that. Could we please add this: 
https://github.com/boto/botocore/commit/33898eae74c86275b8c0dce970b8f36a5de1ff5b

**Comment by jeskew** [comment]
This SDK supports automatically generating a pre-signed URL for the appropriate RDS operations. Cf https://github.com/aws/aws-sdk-js/blob/master/lib/services/rds.js#L13.

You need to specify a `SourceRegion` parameter per the documentation at http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS.html#copyDBSnapshot-property, but we should look at how to make that documentation clearer.

**Comment by Deamoner** [comment]
Yep that works, wow spent so much time making my own presigned url function lol thanks

**Comment by jeskew** [comment]
I added a note to the docs for the `PreSignedUrl` property for [`CopyDBClusterSnapshot`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS.html#copyDBClusterSnapshot-property), [`CopyDBSnapshot`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS.html#copyDBSnapshot-property), [`CreateDBCluster`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS.html#createDBCluster-property), and [`CreateDBInstanceReadReplica`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS.html#createDBInstanceReadReplica-property). For each of those operations, a pre-signed URL will be calculated on your behalf if the `SourceRegion` parameter is present and the `PreSignedUrl` parameter is empty.
