### ISSUE TITLE
How to use aws.s3 in nativescript??

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-js#1442]
I want to store data at aws.s3. But i didn't get any plugin for that.

have any one done that except using nativescript-aws?? 

please help me. I need it urgently

**Comment by chrisradek** [comment]
@SumanSingh4 
We don't currently officially support running the SDK in NativeScript. Taking a quick look at the [NativeScript docs](http://docs.nativescript.org/cookbook/fetch), it looks like NativeScript supports using either `fetch` or node.js' `http` for making network calls. The browser SDK uses XMLHttpRequest, while the node SDK uses http. The node sdk depends on a number of native node modules (`fs`, `crypto`, `url`, etc) that don't appear to be available in NativeScript.

I can mark this as a feature request to support NativeScript, but for this sort of question I'd recommend using StackOverflow to see if anyone else has had luck using S3 from NativeScript.

**Comment by SumanSingh4** [comment]
@chrisradek  Ok Thanks.
