### ISSUE TITLE
createRole params should NOT be URL encoded

### ISSUE THREAD

**Issue by tierfire** [aws/aws-sdk-js#1444]
The documentation example for `createRole` specifies using `URL-encoded-JSON` for the AssumeRolePolicyDocument: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IAM.html#createRole-property

I was using `JSON.stringify(<my-object>)` and `encodeURIComponent` to create a uri encoded param but this fails with 
`'MalformedPolicyDocument: This policy contains invalid Json\n    at Request.extractError <snip>`

If you just pass the param as a `JSON.stringify` it works, but the response does come back as uri encoded.

**Comment by kpotehin** [comment]
Still the same, @tierfire thank you for posting a correct way to pass AssumeRolePolicyDocument.
