### ISSUE TITLE
SES international email encoding

### ISSUE THREAD

**Issue by lajpatshah** [aws/aws-sdk-js#1447]
I am trying to send an email using SES to a international email id: Dörte@gmail.com

As per SES we have to mime encode local part of the address ie Dörte

The conversion value looks this: =?US-ASCII?Q?D=FFrte?=@gmail.com

But AWS is literally considering this as a non-converted email id.

I tried converting normal email such as myname@gmail.com into =?US-ASCII?Q?myname?=@gmail.com & yet it failed to sent an email.

Please help in solving this critical issue

**Comment by chrisradek** [comment]
@lajpatshah 
Please see https://forums.aws.amazon.com/thread.jspa?messageID=522709
and
https://forums.aws.amazon.com/thread.jspa?threadID=236854 for more information from SES.
It appears that only ASCII characters are allowed in the name part (the part before the `@` sign) of an email address.

From the rfc2047 spec:

> + An 'encoded-word' MUST NOT appear in any portion of an 'addr-spec'.

I would recommend either commenting on an existing post, or creating a new one, on the SES forums to support non-ascii characters in an email address.
