### ISSUE TITLE
TypeError: AWS.StepFunctions is not a constructor

### ISSUE THREAD

**Issue by charly3pins** [aws/aws-sdk-js#1448]
I'm trying to invoke the StepFunctions() constructor in an angularjs controller as is described in the documentation of the aws-sdk-js http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/StepFunctions.html but it says that 
```
StepFunctions() is not a constructor.
```

I've tried the same with node and it works. Is it because it's only working from a server side?

I've tested a AWS.Lambda() call from angularjs and it works...

My code:
```
AWS.config.apiVersions = {
	lambda: '2015-03-31',
	stepfunctions: '2016-11-23'
};
var stepfunctions = new AWS.StepFunctions();
var params = {};
stepfunctions.listStateMachines(params, function(err, data) {
	if (err) console.log(err, err.stack); // an error occurred
	else     console.log(data);           // successful response
});
```

**Comment by chrisradek** [comment]
@charly3pins 
`StepFunctions` doesn't currently support CORS, a requirement for running in most browsers, so is not included in the browser version of the SDK by default. Please see the following page for a list of services that do or do not support CORS:
https://github.com/aws/aws-sdk-js/blob/master/SERVICES.md

If you post a feature request on the [`AWS Step Functions forum`](https://forums.aws.amazon.com/forum.jspa?forumID=237) for CORS support and post a link here, I'd be happy to relay the message internally.

**Comment by charly3pins** [comment]
Thank you @chrisradek for your answer!
