### ISSUE TITLE
Intermittent error, only when logged in to cognito, CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by jdilkes** [aws/aws-sdk-js#1450]
Get CredentialsError: Missing credentials in config when calling a Lambda function to load HTML into a web page.

Usually the function works fine; intermittently it fails with this error, but so far only when a user is already logged in.

**Comment by chrisradek** [comment]
@fuchsiagroan 
Can you share what version of the SDK and if this is the browser SDK you're using?

Can you share what the full error looks like? There should be additional fields on the error object, including possibly `originalError` that can give more clues as to what is happening.

**Comment by fuchsiagroan** [comment]
aws-sdk-2.36.0.min.js
I can not see any other error in the console; the error message received is a pop-up on the screen.

**Comment by chrisradek** [comment]
There's no way to view the error in the debugger?

It's possible that the region you're using with your credentials isn't the same as the one your identity pool id is located in. If that's the case, you can pass the correct region in when constructing your [`CognitoIdentityCredentials`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html#constructor-property).

If you can get the full error, we might be able to help more with troubleshooting your issue.

**Comment by fuchsiagroan** [comment]
The regions are the same.

The error is intermittent, and if I subsequently refresh the page it then loads correctly.

I don't know how to get the full error, can you advise me how to do that?

**Comment by srchase** [comment]
@jdilkes,

Did you have any further questions?  It looks like you got it sorted in #1599.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
