### ISSUE TITLE
Not able to send email from Lambda to SES from within a VPC?

### ISSUE THREAD

**Issue by lajpatshah** [aws/aws-sdk-js#1451]
I am trying to send email from Lambda to SES.

When I run Lambda in NO VPC mode then email is successfully sent.

But when I assign my VPC it doesn't work.

AWS has VPC endpoint to connect to S3. It same available for SES? Or it is not possible to do so?

Sorry this might be wrong place to ask this question but I wasn't getting any reply so had to ask. Thanks

**Comment by jeskew** [comment]
At the moment, only Amazon S3 offers VPC endpoints. You would need to add a rule to the VPC to allow outbound connections to https://email.us-east-1.amazonaws.com/  (as discussed in [the AWS forums](https://forums.aws.amazon.com/thread.jspa?threadID=120848)).
