### ISSUE TITLE
DynamoDB: Syntax for ExpressionAttributeValues

### ISSUE THREAD

**Issue by pjmolina** [aws/aws-sdk-js#1455]
Hi: Using a DynamoDB **Scan** I found the following issue when using the _aws-sdk-js_:

The [docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#scan-property) explains to use type envelopes for the values. Example:

```
...
FilterExpression: "app = :v",
ExpressionAttributeValues: { ":v": {"S": "myApp"}}
...
```
However, this way of encoding **ExpressionAttributeValues** did not work, returning 0 matching records.

Digging on the issues, I found samples using this without the envelop in a direct way, so I tried it also:
```
...
FilterExpression: "app = :v",
ExpressionAttributeValues: { ":v": "myApp" }
...
```
And, in this way, already filters as expected.

My questions are: 

1. It is me looking at the wrong docs?
2. Is the doc out of sync with the current implementation? 
3. Or is the JS implementation not using the enveloping and should use it?

Environment: windows 10, nodejs v. 7.7.3, aws-sdk v.  2.39.0
Thanks.

**Comment by jeskew** [comment]
The [DynamoDB documentation for `Scan` operations](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html) matches what's in the JS docs. 

Are you using the an instance of `AWS.DynamoDb.DocumentClient`? The document client [will automatically convert ExpressionAttributeValues](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#scan-property) in the same way it converts items supplied to `PutItem` operations.

**Comment by jeskew** [comment]
Right, the document client automatically converts `ExpressionAttributeValues` from JavaScript types to DynamoDB envelope objects. This is the documented behavior of instances of `AWS.DynamoDB.DocumentClient` and differs from the behavior of instances of `AWS.DynamoDB`.

**Comment by pjmolina** [comment]
Excuse me @jeskew I don't understand. If I am using DocumentClient why the enveloping is not working?

**Comment by jeskew** [comment]
The document client automatically converts JavaScript types to DynamoDB's `AttributeValue` types. 

For example `documentClient.put({TableName: "table1", Item: "myApp"})` converts `"myApp"` to `{S: "myApp"}` and calls DynamoDB's `PutItem` operation with `{TableName: "table1", Item: {S: "myApp"}`.

Similarly, `documentClient.scan` converts the value passed to `ExpressionAttributeValues` to a DynamoDB type, so `ExpressionAttributeValues: {":v": "myApp"}` is being sent as `ExpressionAttributeValues: {":v": {S: "myApp"}}` to DynamoDB. 

If you provide an already converted item to the document client, it will convert the object to a DynamoDB map, so `ExpressionAttributeValues: {":v": {S: "myApp"}}` would be converted to `ExpressionAttributeValues: {":v": {M: {S: {S: "myApp"}}}}` before being sent to the service.

**Comment by pjmolina** [comment]
I see: double envelope. Thanks for the explanation. Much clear for me now.
