### ISSUE TITLE
Unable to sign AWS IoT MQTT/WSS url

### ISSUE THREAD

**Issue by prestomation** [aws/aws-sdk-js#1456]
Hi,

I set out with the intention of submitting a simple PR to allow simple presigning of a IoT websocket url. Using the sample code in the IoT docs is..not something I want to continue to do :) http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html#mqtt-ws

Problem is, the JS sdk _always_ signs the x-Amz-Security-Token header, but AWS IoT does NOT accept this header if it's signed.
CPP SDK also has this issue: https://github.com/aws/aws-sdk-cpp/pull/338

1. Is it acceptable to modify the SDK to never sign this header?(I don't really see security implications as it's an encrypted blob, but I dunno if other services expect it to be signed)
2. If not 1, what is the best way to ask AWS IoT to allow this header to be signed?
3. What other options do we have here?

Thanks!

**Comment by jeskew** [comment]
Hi @prestomation,

From the sample code in the developer guide you linked to, signed websocket URLs shouldn't include any headers but should instead hoist everything that would normally be a header to the query string. That's pretty close in spirit to the way the SDK's S3 and Polly presigners work, but different enough that I think we would need a custom signer.

**Comment by carlnordenfelt** [comment]
I'm running on Lambda and doing just what you want to do I think:

    var v4 = require('aws-signature-v4');
    function signEndpointUrlAwsV4(endpointAddress) {
        var signedUrl = v4.createPresignedURL(
            'GET',
            endpointAddress,
            '/mqtt',
            'iotdevicegateway',
            signatureV4Hash,
            {
                key: process.env.AWS_ACCESS_KEY_ID,
                secret: process.env.AWS_SECRET_ACCESS_KEY,
                region: process.env.AWS_REGION,
                protocol: 'wss',
                expires: WSS_URL_EXPIRY_SECONDS
            }
        );
        return signedUrl + '&X-Amz-Security-Token=' + encodeURIComponent(process.env.AWS_SESSION_TOKEN);
    };

**Comment by prestomation** [comment]
Err, yes, in the query parameters of course.

Thanks @carlnordenfelt, makes sense. I just wish this sort of interface was more cleanly available in the SDK so I don't need to have multiple copies of the signing code.
I hacked something together using the SDK, it's pretty ugly though! https://gist.github.com/prestomation/b0f15b4492146a64b9deffaf7ef011eb#file-iot_presign-js

**Comment by unirey** [comment]
@carljparker 

Im also trying to figure this out & docs really aren't helping. I don't need to `assumeRole`?

This and S3 uploading w/ presigned url (presigned urls in general actually) are the most confusing things I've faced in AWS for sure. 
There has to be a better way to document this stuff and/or have a group of utility functions to presign for different AWS services.

**Comment by rianwouters** [comment]
Also see this AWS SDK extension: https://gist.github.com/rianwouters/17605cdb84a28ab59c89f2a46a7a36be

**Comment by ajredniwja** [comment]
Closing this issue, please open it at https://github.com/aws/aws-iot-device-sdk-js-v2/issues.
