### ISSUE TITLE
Issue on using mobile analytics service for react native app

### ISSUE THREAD

**Issue by peterdev6** [aws/aws-sdk-js#1458]
I am currently using react-native branch to integrate mobile analytics feature into my react native application. 

Question: do I need to manually call putEvents function to send custom events or is it working just like javascript sdk and will send events automatically once set up? 

And when I am trying to call _putEvents(params, callback)_ function, what is the format of the first argument _params_? According to AWS documentation, 

> clientContext is a string value including the client ID, app title, app version and package name.

But no matter what value I put it always shows this error: 

> Error: Client context is malformed or missing.

Does anyone have this issue before?

**Comment by jeskew** [comment]
When using an instance of `AWS.MobileAnalytics`, you would need to manually call [`putEvents`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/MobileAnalytics.html#putEvents-property) with the collected events. The [Mobile Analytics SDK](https://github.com/aws/aws-sdk-mobile-analytics-js) handles batching and dispatching for you, but I'm not sure if the library is directly usable in react native. I see that you've opened [an issue](https://github.com/aws/aws-sdk-mobile-analytics-js/issues/24) on their GitHub page; I would recommend asking on the [Mobile Analytics AWS developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=174) as well.

Taking a look at the mobile analytics sdk, it looks like `clientContext` should be [a JSON document](https://github.com/aws/aws-sdk-mobile-analytics-js/blob/master/lib/MobileAnalyticsClient.js#L535) containing [information about the client, environment, and any custom data you want to include](https://github.com/aws/aws-sdk-mobile-analytics-js/blob/master/lib/MobileAnalyticsClient.js#L203).
