### ISSUE TITLE
using .promise() makes it difficult to get the requestId property

### ISSUE THREAD

**Issue by jhford** [aws/aws-sdk-js#1461]
Because only the response body is provided  as the resolution value, unlike the original library that the `.promise()` function came from (aws-sdk-promise), it's not possible to get the requestId.

Instead, I have to do this:
```javascript
ec2 = new aws.EC2({region: us-east-1});
let request = ec2.describeRegions();
let data = await request.promise();
let requestId = request.response.requestId; // <---- wow ugly.
```

This is not so nice.  Is there a better way to do this?  Can you add some way to allow the requestId to be passed back?

**Comment by jeskew** [comment]
Adding some way to access the response from the resolved value of a promise would be one way to solve this. The `response` property isn't part of the request object's publicly documented interface, so a better way to access the request ID etc should be added.
