### ISSUE TITLE
How to send custom email message using cognito user pool

### ISSUE THREAD

**Issue by ayasyadigital** [aws/aws-sdk-js#1464]
We are developing mobile application for which we are using the cognito user pool for user verification, but we need to send the email with different content for user sign up with USER attributes and different email will be sent with verification code for forgot password.

I am unable to achieve it.

2) We are not able send the RESEND CODE link in the email as well.

Can somebody Help on this ?

**Comment by jeskew** [comment]
Looking at the Cognito User Pools [documentation](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-message-customizations.html) and console, I only see a way to customize the email messages for user invitations and user email verifications.

I would recommend reaching out to the Cognito team on the [AWS developer forums](https://forums.aws.amazon.com/forum.jspa?forumID=173) to request that they add this feature.
