### ISSUE TITLE
UserImportJob CSV File

### ISSUE THREAD

**Issue by iyz1891** [aws/aws-sdk-js#1470]
Howdy,

This is regarding the CognitoIdentityServiceProvider service and the userImportJob related methods.
I'm setting up a feature to allow an authorized user to bulk import users into a pool. The createUserImportJob operation works fine (shows up in console import job list), the problem is I can't seem to find anywhere in the documentation to actually upload/attach the CSV file with the request (or attach after it's created). None of the userImportJob methods seem to have a spot for it. Not sure If I overlooked something but any help is appreciated.

Thanks.

**Comment by chrisradek** [comment]
@iyz1891 
The response that comes back after calling `createUserImportJob` includes a `PreSignedUrl` you can use to upload your csv file.

Docs:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#createUserImportJob-property

> PreSignedUrl — (String)
The pre-signed URL to be used to upload the .csv file.

You could upload the CSV using something like node.js' `http` module, `request`, etc.

**Comment by iyz1891** [comment]
Thank you for response, overlooked that. Much appreciated!
