### ISSUE TITLE
Admin unable to ec2.describeInstances - HTTP 403

### ISSUE THREAD

**Issue by pawansharma15** [aws/aws-sdk-js#1471]
I am calling the following in sequence
- AWS.config.update({accessKeyId: <ID>, secretAccessKey: <KEY>, region: <REGION>})
- elb.describeLoadBalancers: From here get all the Instance IDs as an array
- Then for each of the IDs array object call ec2.describeInstances({InstanceIds: <IDs>})
- The response to ec2.describeInstances is 403, although when the same id and key is used via aws cli to describe the instances, it works

Actual error: POST https://ec2.eu-west-1.amazonaws.com/ 403 (Forbidden)

Detail of versions
- Using the SDK via browser in Electron (https://electron.atom.io/)
- node --version v0.12.7
- userAgent - "aws-sdk-js/2.43.0 callback"
- body: "Action=DescribeInstances&InstanceId.1=i-07641fa5f42f13912&InstanceId.2=i-09aac10987dfdb154&Version=2016-11-15"
- endpoint host: "ec2.eu-west-1.amazonaws.com"
- X-Amz-User-Agent: "aws-sdk-js/2.43.0 callback"
- method: "POST"
- region: "eu-west-1"
- response: Error at constructor.extractError (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:41:8982) at constructor.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:30356) at constructor.emit (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:30067) at constructor.emitEvent (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:16548) at constructor.e (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:12321) at i.runTo (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:42:7102) at https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:42:7307 at constructor.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:12531) at constructor.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:16603) at constructor.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:30462)

---------------
POST https://ec2.eu-west-1.amazonaws.com/ 403 (Forbidden)
handleRequest @ aws-sdk-2.43.0.min.js:39
o @ aws-sdk-2.43.0.min.js:39
(anonymous) @ aws-sdk-2.43.0.min.js:39
callListeners @ aws-sdk-2.43.0.min.js:40
emit @ aws-sdk-2.43.0.min.js:40
emitEvent @ aws-sdk-2.43.0.min.js:40
e @ aws-sdk-2.43.0.min.js:40
i.runTo @ aws-sdk-2.43.0.min.js:42
(anonymous) @ aws-sdk-2.43.0.min.js:42
(anonymous) @ aws-sdk-2.43.0.min.js:40
(anonymous) @ aws-sdk-2.43.0.min.js:40
callListeners @ aws-sdk-2.43.0.min.js:40
s @ aws-sdk-2.43.0.min.js:40
(anonymous) @ aws-sdk-2.43.0.min.js:39
t @ aws-sdk-2.43.0.min.js:38
(anonymous) @ aws-sdk-2.43.0.min.js:38
get @ aws-sdk-2.43.0.min.js:38
(anonymous) @ aws-sdk-2.43.0.min.js:38
getCredentials @ aws-sdk-2.43.0.min.js:38
(anonymous) @ aws-sdk-2.43.0.min.js:39
callListeners @ aws-sdk-2.43.0.min.js:40
emit @ aws-sdk-2.43.0.min.js:40
emitEvent @ aws-sdk-2.43.0.min.js:40
e @ aws-sdk-2.43.0.min.js:40
i.runTo @ aws-sdk-2.43.0.min.js:42
(anonymous) @ aws-sdk-2.43.0.min.js:42
(anonymous) @ aws-sdk-2.43.0.min.js:40
(anonymous) @ aws-sdk-2.43.0.min.js:40
callListeners @ aws-sdk-2.43.0.min.js:40
s @ aws-sdk-2.43.0.min.js:40
(anonymous) @ aws-sdk-2.43.0.min.js:39
(anonymous) @ aws-sdk-2.43.0.min.js:42
hash @ aws-sdk-2.43.0.min.js:42
sha256 @ aws-sdk-2.43.0.min.js:42
computeSha256 @ aws-sdk-2.43.0.min.js:42
(anonymous) @ aws-sdk-2.43.0.min.js:39
callListeners @ aws-sdk-2.43.0.min.js:40
emit @ aws-sdk-2.43.0.min.js:40
emitEvent @ aws-sdk-2.43.0.min.js:40
e @ aws-sdk-2.43.0.min.js:40
i.runTo @ aws-sdk-2.43.0.min.js:42
(anonymous) @ aws-sdk-2.43.0.min.js:42
(anonymous) @ aws-sdk-2.43.0.min.js:40
(anonymous) @ aws-sdk-2.43.0.min.js:40
callListeners @ aws-sdk-2.43.0.min.js:40
emit @ aws-sdk-2.43.0.min.js:40
emitEvent @ aws-sdk-2.43.0.min.js:40
e @ aws-sdk-2.43.0.min.js:40
i.runTo @ aws-sdk-2.43.0.min.js:42
(anonymous) @ aws-sdk-2.43.0.min.js:42
(anonymous) @ aws-sdk-2.43.0.min.js:40
(anonymous) @ aws-sdk-2.43.0.min.js:40
callListeners @ aws-sdk-2.43.0.min.js:40
s @ aws-sdk-2.43.0.min.js:40
(anonymous) @ aws-sdk-2.43.0.min.js:39
t @ aws-sdk-2.43.0.min.js:38
(anonymous) @ aws-sdk-2.43.0.min.js:38
get @ aws-sdk-2.43.0.min.js:38
(anonymous) @ aws-sdk-2.43.0.min.js:38
getCredentials @ aws-sdk-2.43.0.min.js:38
(anonymous) @ aws-sdk-2.43.0.min.js:39
callListeners @ aws-sdk-2.43.0.min.js:40
emit @ aws-sdk-2.43.0.min.js:40
emitEvent @ aws-sdk-2.43.0.min.js:40
e @ aws-sdk-2.43.0.min.js:40
i.runTo @ aws-sdk-2.43.0.min.js:42
runTo @ aws-sdk-2.43.0.min.js:40
send @ aws-sdk-2.43.0.min.js:40
makeRequest @ aws-sdk-2.43.0.min.js:41
none.e.api.operations.(anonymous function).authtype.e.(anonymous function) @ aws-sdk-2.43.0.min.js:41
describeInstances @ main.js:49
(anonymous) @ main.js:24
main.js:50 Error
    at constructor.extractError (aws-sdk-2.43.0.min.js:41)
    at constructor.callListeners (aws-sdk-2.43.0.min.js:40)
    at constructor.emit (aws-sdk-2.43.0.min.js:40)
    at constructor.emitEvent (aws-sdk-2.43.0.min.js:40)
    at constructor.e (aws-sdk-2.43.0.min.js:40)
    at i.runTo (aws-sdk-2.43.0.min.js:42)
    at aws-sdk-2.43.0.min.js:42
    at constructor.<anonymous> (aws-sdk-2.43.0.min.js:40)
    at constructor.<anonymous> (aws-sdk-2.43.0.min.js:40)
    at constructor.callListeners (aws-sdk-2.43.0.min.js:40) "403: null
    at constructor.extractError (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:41:8982)
    at constructor.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:30356)
    at constructor.emit (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:30067)
    at constructor.emitEvent (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:16548)
    at constructor.e (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:12321)
    at i.runTo (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:42:7102)
    at https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:42:7307
    at constructor.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:12531)
    at constructor.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:16603)
    at constructor.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.43.0.min.js:40:30462)"

--------------------
Please help!

**Comment by chrisradek** [comment]
@pawansharma15 
Are you creating your ec2 client after calling `AWS.config.update` with the region/credentials? Can you verify that your region/credentials match what you are using with the CLI when making the same call?
What do you see if you don't pass in an array of ids to `describeInstances`? Do you see your instances in the results?

**Comment by pawansharma15** [comment]
Hi @chrisradek,
I am calling in the following sequence AWS.config.update -> elb.describeLoadBalancers -> ec2. describeInstances. 
So the config update is done once, right at the start and with the same config, calls to describe elb is successful but describeInstances fails, the policy attached to the user is the default AWS admin access policy via a group, also have tried directly attaching the policy to the user with same result.

I have verified in the browsers' javascript console that the right set of credentials are passed, when I printed the whole request/response object to js console. Plus the same credentials could successfully describe the elbs.

When I do not pass anythin to describe instance i.e. {} I get same the response HTTP 403.

**Comment by pawansharma15** [comment]
Logs after setting AWS.config.logger = process.stdout
`[AWS elb 200 0.758s 0 retries] describeLoadBalancers({})
[AWS ec2 403 0.515s 0 retries] describeInstances({ InstanceIds: [ 'i-049ce2e4ae3e364c3', 'i-07405b2211892801a', [length]: 2 ] })`

**Comment by pawansharma15** [comment]
Have anyone faced similar problem? Could anyone have a look, please?

**Comment by pawansharma15** [comment]
More information: The response object does not contain the requestid.

**Comment by srchase** [comment]
@pawansharma15 

Were you able to get this working?

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
