### ISSUE TITLE
.getObject().createReadStream invalid error handling

### ISSUE THREAD

**Issue by andrewcharnley** [aws/aws-sdk-js#1479]
```.getObject((err, data) => {})``` takes a callback which traps errors with the object such as invalid bucketname, key etc. 

If this callback is specified then ```.createReadStream``` will have write after end errors causing the process to end.

If the callback is omitted the stream will function correctly **however** all callback, rather than read errors aren't firing the ```stream.emit('error, ...)```, causing the stream to hang.

**Comment by andrewcharnley** [comment]
aws sdk 2.35.0

Node 6, 7.

**Comment by chrisradek** [comment]
@andrewcharnley 
Which callbacks are you defining on the `stream` object? I'm not quite understanding your use case.

**Comment by andrewcharnley** [comment]
Not on the stream object, on getObject().

Any initial errors with getObject() such as invalid credentials, invalid bucket, are passed the callback (which can't exist when using .createReadStream() ), whereas they should be emitted onto the stream.

I believe this is the cause of several open bugs such that doing .getObject({ Bucket:... Key:...}).createReadStream() can result in;

1. errors are swallowed
2. a stalled stream

I haven't looked into the implementation but I assume the initial errors are racing against the stream creation so don't get pushed on. A fix would be to include a flag within the getObject() configuration which queues the error(s) and pushes them onto the stream when available.

As a temporary fix I also tried creating a transform stream and piping the callback errors onto it, but using a callback causes a write after end to the stream, crashing Node. This is another "feature" that's been open bug reported a while back.

So;
```
x = s3.getObject({ Bucket:xxx, Key:xxx, usingStream:true })

=> if usingStream, queue errors

x.createReadStream()

if queue errors, emit onto stream ```

This is absolutely critical, we're trying to use s3 streams and have no means of debugging. Silent stalls are not good!

Regards,

Andrew

**Comment by mlund01** [comment]
@andrewcharnley I recently ran into this issue, and I agree that `s3.getObject({}).createReadStream()` should be able to pipe errors to from `getObject` to `createReadStream`. However, I did come up with a workaround that satisfies my need to check for relevant errors (including invalid auth, invalid bucket, or resource doesn't exist) that will undoubtably come from `getObject`.

Here is a my full route (using express),


```javascript
router.get('/:file', function(req, res, next) {
	s3.listObjects({
		Bucket: process.env.AWS_BUCKET,
		Prefix: 'images/' + req.params.file
	}, function(err, data) {
		if (err) {
			next(err);
		} else if (data.Contents.length == 0 || data.Contents[0].Key != ('images/' + req.params.file)) {
			next({status: 404, message: "This image does not exist"});
		} 
		else {
			var imgStream = s3.getObject({
		  	Bucket: process.env.AWS_BUCKET,
		  	Key: 'images/' + req.params.file
		  }).createReadStream();

		  imgStream.pipe(res);
		}
	})
  
})

```

What is unfortunate is that I have call to AWS twice, once to verify the object exists and no errors arise (albeit with little overhead as possible given the available endpoints in the aws-sdk), and the second to actually get the object given no errors.

Hope this helps!

**Comment by kevinbror** [comment]
@mlund01 In the code you give it is possible that between the listObjects call and getObject call the image is deleted. So while this may reduce the chance of a hanging stream, it does not solve the issue.

**Comment by andrewcharnley** [comment]
In my case it must return a stream as I made the module a drop in interface for fs.*. I tried wrapping with a transform stream but it's the same problem really, the callback isn't possible without a write after end crash and thus various errors get swallowed and the stream hangs. 

@mlund01, there are others your code doesn't consider such as access and credentials.

Amazon should be ashamed by this bug.

**Comment by kevinbror** [comment]
The docs [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property) seem to indicate that when the callback is provided as follows, 
`
const AWS = require('aws-sdk');
const s3 = new AWS.S3({ apiVersion: 'latest' });
const params = {Bucket: 'bucketName', Key: 'keyName'};
s3.getObject(params, (err, data) => { ... });
`
that data.Body may be a readable stream. In my experiments however it always seems to be a buffer. Is there a way to configure data.Body to be a stream? Were that the case it seems that we could bypass the issue with swallowed errs.

**Comment by jeskew** [comment]
@kevinbror When a callback is provided, the body will always be returned as a buffer. The only way to get the body as a stream is to call `createReadStream` on the S3 request.

**Comment by kevinbror** [comment]
@jeskew Thanks for clarifying

**Comment by andrewcharnley** [comment]
Good work jeskew and thank you!
