### ISSUE TITLE
getSignedUrl used in sync form fails to return a valid signed URL occasionally 

### ISSUE THREAD

**Issue by sgnn7** [aws/aws-sdk-js#1482]
Deployment environment:

- OS: Ubuntu 16.04
- NodeJS: 4.4.7-1nodesource1
- EC2 instance
- Credentials through AWS IAM roles
- Only occurs on first app load in this env (doesn't show up when running locally).

Code:
```
...
const filename = uuid.v4() + '.' + fileExtension;
const putUrl = s3.getSignedUrl('putObject', {
  Bucket: config.bucket,
  Key: filename,
  ContentType: contentType,
  ACL: 'public-read'
});

return {
  putUrl: putUrl,
};
...
```

Expected: 
```
{"putUrl":"https://bucket-name.s3.amazonaws.com/10456004-d296-46fc-bc08-4cb6c40b6216.pdf?AWSAccessKeyId=foobar&Content-Type=application%2Fpdf&Expires=1493058200&Signature=foobar%3D&x-amz-acl=public-read"}
```

Result (first load only) that also doesn't throw:
```
{"putUrl":"https://s3.amazonaws.com/"}
```

I resolved this problem by wrapping it in a Promise and using the async form of the function but the bug is there for sure. I don't have currently time to dig deeper into why this happens but I included as much info on it as I could.

**Comment by chrisradek** [comment]
@sgnn7 
When calling `getSignedUrl`, you can only use the sync method if your credentials are resolved synchronously.

EC2 credentials are resolved asynchronously, so you should always use the callback method (or wrap it in a promise) when getting urls.
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property

> Note: You must ensure that you have static or previously resolved credentials if you call this method synchronously (with no callback), otherwise it may not properly sign the request. If you cannot guarantee this (you are using an asynchronous credential provider, i.e., EC2 IAM roles), you should always call this method with an asynchronous callback.

**Comment by sgnn7** [comment]
@chrisradek Agh! I should have read the docs better though I did expect auth problems to result in a throw of some sort which is why I thought it was an unintended bug! Thanks!

**Comment by gsanj** [comment]
Hi all 
I am also getting same issue very first time/load only
https://s3.amazonaws.com/

Second time onward it is working fine like: 
https://bucketname.s3.amazonaws.com/flowers.png?AWSAccessKeyId=ASIAINQI3VXHA22H...

My code is:
var params = {Bucket: 'bucket name, Key: 'file path', Expires:'3600' };
var url = s3.getSignedUrl('getObject', params);

Last one day I am trying to find out root cause but not get success, please provide some expert opinion  why this is happening first time only and what is the solution?

I am using Node.JS

**Comment by DrLongGhost** [comment]
Thanks for this!

**Comment by asafch** [comment]
@gsanj you should call the SDK function with a callback, but wrap the whole thing with a promise:

```javascript
getPublicUrl(bucket, key, expiresIn = 300) {
        return new Promise((resolve, reject) => {
            this._s3.getSignedUrl('getObject', {
                Bucket: bucket,
                Key: key,
                Expires: expiresIn
            }, (error, url) => {
                if (error) {
                    reject(error);
                } else {
                    resolve(url);
                }
            });
        });
    }
```

Then you can work with the promise:

```javascript
async () => {
	const url = await getPublicUrl('bucket', 'key');

	return url;
}
```

or:
```javascript
getPublicUrl('bucket', 'key')
.then(...)
.catch(...);
```

**Comment by trivikr** [comment]
Locking this thread as the issue is old.
Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
