### ISSUE TITLE
Upload file "Expires" did not work

### ISSUE THREAD

**Issue by testtshoretel** [aws/aws-sdk-js#1491]
[s3Console.docx](https://github.com/aws/aws-sdk-js/files/965296/s3Console.docx)
Hi, 

I use upload function to upload a small text file. Here is the param:
 params {"Bucket":"media-tw-channel","Key":"1493406017626-eb5da2b0-2c44-11e7-8ce1-890484b        0beb7","ContentType":"plain/text","Body":{"type":"Buffer","data":[123,13,10,32,32,34,116,101,110,97,110,116,34,58,32,34,49,34,44,13,10,32,32,34,102,105,108,101,95,110,97,109,101,34,58,32,34,109        ,121,116,101,115,116,46,116,101,120,116,34,44,13,10,32,32,34,99,111,110,116,101,110,116,95,116,121,112,101,34,58,32,34,112,108,97,105,110,47,116,101,120,116,34,44,13,10,32,32,34,97,118,97,116,9        7,114,34,58,32,102,97,108,115,101,44,13,10,32,32,34,101,120,112,105,114,101,34,58,32,54,48,48,44,13,10,32,32,34,115,101,114,118,101,114,95,101,110,99,114,121,112,116,34,58,32,34,65,69,83,50,53,        54,34,44,13,10,32,32,34,112,111,115,116,34,58,32,123,13,10,32,32,32,32,32,34,99,111,110,116,101,110,116,34,58,32,34,112,111,115,116,32,116,101,115,116,34,13,10,32,32,32,125,13,10,125]},"Metadat        a":{"tenant":"1","bucket":"0181486e_810b_48f1_8e28_218884c006fe","uploader":"yuser1@shoretel.com","filename":"mytest.text"},"ServerSideEncryption":"AES256","Expires":"2017-04-28T19:10:34.278Z"}

Here is the S3 response: 
resp {"ETag":"\"951fb012d5439e242b9        1099063dcc4d8\"","ServerSideEncryption":"AES256","Location":"https://media-tw-channel.s3.amazonaws.com/1493406017626-eb5da2b0-2c44-11e7-8ce1-890484b0beb7","key":"1493406017626-eb5da2b0-2c44-11e        7-8ce1-890484b0beb7","Key":"1493406017626-eb5da2b0-2c44-11e7-8ce1-890484b0beb7","Bucket":"media-tw-channel"}

Time during upload: 
Fri Apr 28 19:01:04 UTC 2017

But when I checked the s3 console: there is no expire value as seen in attached file. And after 30 minutes, the file is still there in the bucket. Can you take a look? From my test, it worked before. 

Thanks,

**Comment by jeskew** [comment]
Hi @testtshoretel,

Did you upgrade the SDK in between when the expiration was working and when it stopped working? Or did you experience both behaviors using the same version of the SDK?

**Comment by testtshoretel** [comment]
@jeskew  Same SDK 2.4.8

**Comment by jeskew** [comment]
Since you've experienced both behaviors with the same version of the SDK, the change would necessarily be due to a server-side change by S3. The best way to reach out to S3 engineers is via [their AWS developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=24).

**Comment by testtshoretel** [comment]
@jeskew I posted a new issue here: 
Discussion Forums	
Welcome, eee Logout Your Stuff Private Messages (0) Forums Help
Discussion Forums > Category: Storage & Content Delivery > Forum: Amazon Simple Storage Service >Thread: Upload file "Expires" did not work

Is this the right place? Nobody updated this issue. How can I ask somebody to take a look?

Thanks.
