### ISSUE TITLE
s3 getObject returns empty Body in react-native

### ISSUE THREAD

**Issue by brianomchugh** [aws/aws-sdk-js#1503]
I am trying to download a file from s3 withinin a react-native app, and the response shows that there is content, but the Body is empty.
```
AcceptedRanges: "bytes"
Body: Uint8Array(0)
ContentLength: 26784
ContentType: "binary/octet-stream"
```

Meanwhile if I run the same code in a lambda function (node environment), the response is the same except the Body is populated with data:
```
AcceptedRanges: "bytes"
Body: <Buffer ff e3 48 c4 00 00 00 00 00 00 00 00 00 49 6e 66 6f 00 00 00 0f 00 00 00 5c 00 00 68 a0 00 02 05 08 0b 0d 10 13 16 19 1b 1e 21 21 24 26 29 2c 2f 32 34 ... > }
ContentLength: 26784
ContentType: "binary/octet-stream"
```

Here is the code I am using: 
```    
S3.getObject(params, function (err, data) {
  if (err) {
    console.log(err, err.stack)
  } else {
    console.log(data)
   }
})
```

**Comment by jeskew** [comment]
Can you share a bit more about the execution environment, such as:
* Which version of the SDK are you using?
* Are you using the react-native distributable described in the readme?
* Are you seeing this issue on iOS, Android, or both?

**Comment by brianomchugh** [comment]
@jeskew 
I am using version 2.49.0, and am using the react-native distributable ('aws-sdk/dist/aws-sdk-react-native').
I am experiencing this on iOS (have not tested Android yet)

**Comment by chrisradek** [comment]
@brianomchugh 
I just merged in a change to master that should fix the issue you saw. I tested it by downloading an image using `s3.getObject` in iOS and Android. Interestingly, while Android did have a Body that was populated, it's size did not match the object's content-length. After this change, it should match.
