### ISSUE TITLE
about pinpoint error in ionic2 project

### ISSUE THREAD

**Issue by jsochen** [aws/aws-sdk-js#1506]
in browser i sea the console(now I Open the service) ，I konw because Cross domain but i want konw how to deal with some interface
![image](https://cloud.githubusercontent.com/assets/16857454/25882808/8c96caa8-3578-11e7-8134-168436b76b96.png)

when the ionic2  app   running in  touch  the result is  (now that webview Access method if 'file:///...')
![image](https://cloud.githubusercontent.com/assets/16857454/25882646/8ee557f8-3577-11e7-842f-0acbfced8aa9.png) 
from this photos I know maybe i froget to add the session but i don't know how to do  ,next photo is my code 
aws.component.ts: ![image](https://cloud.githubusercontent.com/assets/16857454/25882721/26b6bc0c-3578-11e7-8042-2beab478c9a3.png)
index.html
![image](https://cloud.githubusercontent.com/assets/16857454/25882747/49a48190-3578-11e7-8522-6c09ca134577.png)

**Comment by jsochen** [comment]
if someone have a dome ， please tell me， Grateful！

**Comment by jeskew** [comment]
By default, [Cognito credentials will only be able to access Cognito Sync and Mobile Analytics](http://docs.aws.amazon.com/cognito/latest/developerguide/iam-roles.html). You will need to grant a more permissive role to the Cognito Identity Pool used by your application in order to access Pinpoint APIs.

**Comment by jsochen** [comment]
thanks , I'll try again with you suggest。

**Comment by humusdigital** [comment]
Hi, I'm following this posts and I have the same problem and I will like to know if you can set correctly Cognito credentials to run the app into pinpoint or what was the correct configuration or code to connect your ionic app with pinpoint to received pushnotifications. thanks.
