### ISSUE TITLE
Not able to add custom endpoint to upload file.

### ISSUE THREAD

**Issue by mano-bharathi** [aws/aws-sdk-js#1508]
##Hi, My bucket is located in our storage layer which is above aws. So when ever i try to upload by passing endpoint it is uploading the url "bucketname.endpoint" example (mybucket.10.86.2.44) which is throwing error as my bucket is not the subdomain for me. How to change this to custom endpoint. I want to upload the file to url like this http://10.86.2.44/mybucket/directory. Is that possible ??

**Comment by jeskew** [comment]
You can accomplish this by setting the `s3BucketEndpoint` configuration parameter to true when creating the S3 client:

```javascript
const s3 = new AWS.S3({
    region: 'us-west-2',
    s3BucketEndpoint: true,
});
```

You can read more about the configuration options availabe [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property).
