### ISSUE TITLE
How to enable logs of aws-sdk

### ISSUE THREAD

**Issue by mano-bharathi** [aws/aws-sdk-js#1511]
Hi,
How will i enable logs of this to check where exactly it tried to upload and the post call, request object etc.

**Comment by jeskew** [comment]
Hi @mano-bharathi,

You can accomplish this by setting the `logger` constructor parameter when creating a client. You will need to pass in an object that has a defined `log` or `write` method. For example, if you want to log directly to the console, you can pass in the global `console` object:

```javascript
const s3 = new AWS.S3({
    region: 'us-west-2',
    logger: console,
});
```
