### ISSUE TITLE
Cannot read property 'crypto' of undefined

### ISSUE THREAD

**Issue by CodeHobbit** [aws/aws-sdk-js#1512]
Getting the following error when importing aws-sdk.  Not sure if it is a bug or just my set-up.

Seems to be happening on the following lines:
if (_global.crypto && crypto.getRandomValues) {
    whatwgRNG = function(size) {
      var bytes = new Uint8Array(size);
      crypto.getRandomValues(bytes);
      return bytes;
    }
  }

**Comment by CodeHobbit** [comment]
Never-mind, this seems to have been an issue with my webpack config.

I needed to add the following:
exclude: /node_modules/,

Thanks.

**Comment by SanderElias** [comment]
@jasoneversole Can you reopen this? I stumbled on the same issue.  There is an ancient version of `crypto-browserify` (1.0.9) included in aws. This broke my build too.  Updating it to the latest version solved it for me, but I'm not entirely sure this is without consequences.

**Comment by timotgl** [comment]
@SanderElias thanks this helped us fix the issue. We monkey-patched `rng.js` with a patched version (the one line you suggested) in the `postinstall` script.

**Comment by matrunchyk** [comment]
I think it should be reopened. Patching files (even ad-hoc) is a good solution but would be great if you guys can fix the real problem here.

**Comment by Ch3ck** [comment]
I some how cannot find the full source for this package so as to apply this patch. Another fix will be to change the `crypto-browserify` to `amplify-crypto-browserify`. Looking at the package json I couldn't find this package
