### ISSUE TITLE
synthesizeSpeech very slow on RPi 3

### ISSUE THREAD

**Issue by ddwp99** [aws/aws-sdk-js#1513]
Polly.synthesizeSpeech takes a long time on my Raspberry Pi 3 for the callback to trigger.
With the benchmark below, I am getting dt ~ 300 ms on Win10 and Win7 desktops, and dt ~15000 ms on the RPi 3. This is pretty unacceptable!

```
// Load the SDK
const AWS = require('aws-sdk')

// Create an Polly client
const Polly = new AWS.Polly({
    signatureVersion: 'v4',
    region: 'us-east-1'
})

let params = {
    'Text': 'Hello.',
    'OutputFormat': 'mp3',
    'VoiceId': 'Kimberly'
}

speechHandler = function(err,data){
    if (err) {
        console.log(err.code)
    } else if (data) {
        if (data.AudioStream instanceof Buffer) {
            console.timeEnd('a')
            console.time('a')
            Polly.synthesizeSpeech(params,speechHandler)
        }
    }
}

console.time('a')
Polly.synthesizeSpeech(params,speechHandler)

```

All the machines are on the same network and have similar ping times and ul/dl rates; and this happens to the RPi regardless wired or wireless connectivity (tried both). I tried doing a fresh install of Raspbian Jessie w/ Pixel on the entire 32 GB SD card, and set up with my minimum dev config:
 - Node.js 7.10, Samba, RealVNC, SSH, 16 MB GPU Memory.

Same slow response. So I suspect the reason may have to do with either system or network performance - since the response looks really snappy in @anaptfox's [video](https://www.losant.com/blog/speech-synthesis-on-the-raspberry-pi-using-node.js?utm_source=nodeweekly&utm_medium=email).

Tried:
 - Booting to CLI, disabling Samba, disabling swap. Still terribly slow. `top` shows swap was not even touched during the execution (when I had swap enabled), and `node` did not even exceeds 2% in CPU load while handling callbacks. 
- Changed the script so it only requires the necessary aws libs: 
``import AWS = require('aws-sdk/global'); awsPolly = require('aws-sdk/clients/polly')``. Same results.
- Finally went with fresh install of Jessie Lite. Set up Wif, enabled SSH, installed node 7.10 via nvm, installed git to clone aws-nodejs-sample, npm install in the source directory. Rebooted headless and no USB devices. Literally no excess other than the Wifi WPA2 connection. Still the slow benchmark... :(

Does anyone have any idea? I am close to throwing my network router at my RPi3 to knock out a loose screw or something. Thank you!

**Comment by chrisradek** [comment]
@ddwp99 
Can you instantiate your polly client to include logging?
Ex:
```javascript
new AWS.Polly({
  logger: console
});
```
It will give us the total time the request took, which might not be super helpful, but also let us know if the request is being retried.

I'm not very familiar with debugging node.js on a Raspberry Pi. Is it possible to profile the code to tell if it's the response that's taking a long time to come back, or if some code is taking a long time to execute?

**Comment by ddwp99** [comment]
Hey @chrisradek thanks for the question. I was able to resolve this issue and posted an answer to my original question [here](https://github.com/Losant/inspiration-station/issues/1).

As it turns out, the script was spending most of its time re-establishing the SSL handshake on each Polly request (As confirmed by CPU profiles sampled with Chrome DevTools). To resolve this issue, the node module _agentkeepalive_ was used. 

I hope this will be able to help some other confused folks as well.

**Comment by chrisradek** [comment]
@ddwp99 
Glad you found a solution!
You should be able to use the same solution you have with a native https agent as well. Very interesting that the SSL handshake takes so much time on a Raspberry Pi!

**Comment by ddwp99** [comment]
Thanks Chris! I've edited the comment above to use the build-in _https_ module instead.
