### ISSUE TITLE
Is there a way to safely upload photos to S3 from browser without authenticating users

### ISSUE THREAD

**Issue by Andriy-Kulak** [aws/aws-sdk-js#1515]
Hi Team,

I am using aws-sdk to give the user the ability to upload photos from browser and manipulate them. The photos themselves aren't sensitive data and I have no interest in really authenticating the user because my product does not require me keeping track of user personal information.

The problem that I am running into with this however is that I have to expose the API key and secret on the browser like in the example below. I made sure to give this key the minimum permissions (only allowing PUT request to the specific S3 bucket), but I still don't like the fact that the secret is exposed on client side.

Is there any way for me to give users ability to upload photos in a safer manner without exposing API secret or authenticating?

**Sample Client Side Code with Key and Secret being exposed... :-/**
```
import AWS from 'aws-sdk';
import { AwsAccessKeyId, AwsSecretAccessKey } from '../constants';

  AWS.config.update({
    accessKeyId: AwsAccessKeyId,
    secretAccessKey: AwsSecretAccessKey,
    region: 'us-west-2'
  });
  const S3 = new AWS.S3({ params: { Bucket: 'My_Random_Image_Bucket' } });

  const params = {
    Key: `${randomKey}`,
    ContentType: 'image/png',
    Body: my_random_image_file,
    ACL: 'public-read'
  };

    S3.upload(params, (err, data) => {
      if (err) {
        console.log('error S3', err);
        return alert(err);
      }

      return console.log('s3 pass', data);

    });
```

**Comment by lirantal** [comment]
Yes, you can implement an endpoint on your API server that would implement S3's getSignedUrl() and will send the browser back a special temporary URL for the browser to upload files with (check the docs at http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property)

**Comment by Andriy-Kulak** [comment]
thanks @lirantal I will look into it. Also to follow up, since I will not be using authentication, is it possible to limit the amount (lets say 0.5 gb) that a user based on IP address can upload per day. 
 This will prevent someone maliciously trying to fill my bucket with tons of crap. Maybe using Lambda or some other tool. I haven't been able to find any examples online of anything like this.

**Comment by jeskew** [comment]
@Andriy-Kulak You can use a presigned POST policy if you want to limit the size of an individual upload by setting a `content-length-range` condition in the policy itself. Documentation on how presigned policies work can be found [here](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html), and documentation on how to create them in the SDK can be found [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createPresignedPost-property).

Since the policy only applies limits to a single upload, you would need to find a different way to throttle uploads based on IP. You could set up a lambda function that creates a POST policy that could only be called a certain number of times per day per IP, but users would be able to execute multiple POST uploads with each policy, as they can be used until they expire.

**Comment by Andriy-Kulak** [comment]
Hi @jeskew and @lirantal - I also discovered that there is a cognito option to have unauthenticated users [(link)](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-console.html)

Would there be any benefit in using cognito (unathenticated version) and UserPoolId to let users upload photos over presignedUrl that is mentioned above?

the AWS params config on the front end would look something like below:

```
var albumBucketName = 'BUCKET_NAME';
var bucketRegion = 'REGION';
var IdentityPoolId = 'IDENTITY_POOL_ID';

AWS.config.update({
  region: bucketRegion,
  credentials: new AWS.CognitoIdentityCredentials({
    IdentityPoolId: IdentityPoolId
  })
});

```

**Comment by jeskew** [comment]
@Andriy-Kulak,

If you allow unauthenticated users to get credentials that can upload objects to your S3 bucket, you lose the ability to impose any conditions beyond those that can be embedded in an IAM role policy. I would recommend investigating presigned POST uploads before going down that route.

**Comment by usamamashkoor** [comment]
@jeskew  the presigned POST return us the url   [docs url](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property) which @Andriy-Kulak has given in his response how we can use that url to upload objects to amazon s3 and also show the progress bar during the s3 file upload.
Thanks

**Comment by usamamashkoor** [comment]
@lirantal  can you please guide us a little how we can process after getting the presigned POST url from according to docs [docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property)
