### ISSUE TITLE
Support for Observable ?

### ISSUE THREAD

**Issue by terryx** [aws/aws-sdk-js#1516]
sdk version v2.54.0

Is the sdk support observable and library like RxJS ? 
I can't get bindCallback, bindNodeCallback and fromPromise to work for example like below
```javascript
      const dynamodb = new AWS.DynamoDB.DocumentClient()

      const params = {
        TableName: 'Table',
        Item: {name: 'abc'}
      }

      return Observable.fromPromise(dynamodb.put(params).promise)
```

the result is `promise.then` is not a function

**Comment by jeskew** [comment]
`dynamodb.put(params).promise` is a function that, when called, will return a promise. Add a pair of parentheses to the end of that expression and the above snippet should work.
