### ISSUE TITLE
Issue with s3-> createPresignedPost -> params with SOLUTION

### ISSUE THREAD

**Issue by omkardusane** [aws/aws-sdk-js#1518]
Dear aws,

the createPresignedPost api as :
`
 var params = {
        Bucket: 'kennect-test',
        Fields: {
            key: 'file3.txt',
            Expires: 86400 ,
        },
    };
    s3.createPresignedPost(params, function ( ......
`
doesn't work , the generated Policy gets rejected by aws saying , 'invalid policy - field value must be string' 

but changing the field in above request as : 
   ` Expires: '86400' , ` // a string
makes it work. 
though it is not specified in the docs, the file [https://github.com/aws/aws-sdk-js/blob/master/lib/s3/presigned_post.d.ts](url) says , Expires must be a number and all fields inside Fields can be any. it should specify that Expires should be in the Fields and it should be string. 

Thanks,

**Comment by jeskew** [comment]
Hi @omkardusane,

The `Expires` parameter is handled separately from the `Fields` hash and should be passed in at the same level as `Bucket` and `Fields`. If not present, the SDK will use a default value of `3600` and set the policy expiration as the current time plus one hour (and this gets included in the policy as an ISO-8601 date string).

If expires is included as a string field, it will be included in the policy and must appear in the form submitted, but I don't think S3 would use that value.

**Comment by omkardusane** [comment]
Let me check and let you know

**Comment by omkardusane** [comment]
HI @jeskew , You are right, the `Expires` parameter is expected at the level of Bucket and Fields, and s3 Doesn't use the value of `Fields.Expires` is passed. So the solution is I won't pass the Expires at all and will include the Expires in the params when creating the request. Thanks for the clarification. I am glad its working after so many hours.

**Comment by jeskew** [comment]
Happy to help! Glad you were able to verify the fix.
