### ISSUE TITLE
Abusing AWS Unauthenticated Cognito Identities and other services from the Browser (not Nodejs)?

### ISSUE THREAD

**Issue by mattlockyer** [aws/aws-sdk-js#1519]
Feel free to close this if I am incorrect.

I was curious what prevents a malicious bot from visiting a static site and creating an AWS unauthenticated cognito identity and then abusing services that may be available through the unauthed cognito identity IAM Role?

The code to do perform these actions is stored in the client-side js so it would be easy to write a bot that requests new identities.

Is the issuing of unauth cognito identities able to be throttled? Is there some AWS Pixie dust happening in Cognito that would prevent this?

I was able to create several identities simply be accessing my script from incognito windows, so there doesn't seem to be any IP mapping, which makes sense for multiple users per device.

Some information on how this works would be appreciated, thanks!

**Comment by jeskew** [comment]
Hi @mattlockyer,

You're correct that you can call Cognito's [GetId operation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html#getId-property) to generate a new identity multiple times. It's an unauthenticated API, so whether it's called from a browser or with `curl`, the identities are effectively anonymous. 

You can choose to require authentication for a given identity pool, and I would encourage you to do so if the role assumed by Cognito includes access to services that you don't want anonymous users to have.

**Comment by mattlockyer** [comment]
Do the unauthenticated identities created by a call to Cognito's getId count towards MAUs that one can get charged for? This seems like an issue if someone had malicious intent, almost like a DDOS of Cognito.

**Comment by jeskew** [comment]
You're only billed for MAUs of Cognito User Pools, which is a separate but related offering. Using Cognito Identity with either federated authentication or no authentication is free per https://aws.amazon.com/cognito/pricing/

I'm not a Cognito expert, so I don't really have the background to answer many questions beyond what's covered in Cognito's and the SDK's documentation. If you reach out to the Cognito team via their [AWS developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=173), they might be able to put your in touch with a product manager or solutions architect who can answer more specific questions.
