### ISSUE TITLE
Retried S3 request uses a bogus hostname (the bucket name is repeated)

### ISSUE THREAD

**Issue by mmcminn** [aws/aws-sdk-js#1520]
This is a duplicate of issue #585 and possibly regresses #636 
Using sdk version 2.55.0

Ive attached a log where I have placed a console.log(listener) in callListeners right before listener.apply and a console.log in populateUri that prints as console.log(b + "." + endpoint.hostname)

As is shown from the sequence, the host name is getting doubled up on retry regressing the solution from #636

This is on an ElasticBeanstalk Node Js instance running "64bit Amazon Linux 2016.09 v4.0.0 running Node.js" using the Amazon provided aws-sdk version 2.55.0 (taken from package.json in the node_modules/aws-sdk) folder.

[issue_sequence.txt](https://github.com/aws/aws-sdk-js/files/1020674/issue_sequence.txt)

**Comment by jeskew** [comment]
Hi @mmcminn,

Are you seeing this error frequently? From the log shared, it looks like every other request is made to `<bucket>.<bucket>.s3.amazonaws.com`, whereas retries shouldn't happen as part of every request.

Could you also share how the S3 client is being instantiated and the affected operation called? (I.e., are you using any configuration parameters like `useDualstack` etc.)

**Comment by mmcminn** [comment]
Ya I thought that was pretty odd as well. I have been having a hell of a time recreating the issue outside of my module that is wrapping the call to S3.

That said is there a good way to dump the s3 client state that will get you what you want or will console.log(s3) work assuming var s3 = new AWS.S3({stuff});

**Comment by jeskew** [comment]
You can pass a logger to a client when instantiating it by setting the `logger` parameter, e.g. `const s3 = new AWS.S3({...stuff, logger: console})`. Any object that responds to either a `log` method or a `write` method will work.

**Comment by mmcminn** [comment]
Okay so I have had a hard time getting a dump that does not have a whole bunch of creds on it however I have been able to see that for the specific requests in issue the populate. I was able to assicate this specific action sequence with the one of the requests.

'BUILD_IDEMPOTENCY_TOKENS',
     'VALIDATE_PARAMETERS',
     'validateScheme',
     'validateBucketEndpoint',
     'correctBucketRegionFromCache',
     'buildRequest',
     'addContentType',
     'populateURI',
     'POPURI : s3.amazonaws.com',
     'computeContentMd5',
     'computeSseCustomerKeyMd5',
     'SET_CONTENT_LENGTH',
     'SET_HTTP_HOST',
     'addExpect100Continue',
     'disableBodySigning',
     'BUILD_IDEMPOTENCY_TOKENS',
     'VALIDATE_PARAMETERS',
     'validateScheme',
     'validateBucketEndpoint',
     'correctBucketRegionFromCache',
     'buildRequest',
     'addContentType',
     'populateURI',
     'POPURI : testplatform-us-east-1-platform.s3.amazonaws.com',
     'computeContentMd5',
     'computeSseCustomerKeyMd5',
     'SET_CONTENT_LENGTH',
     'SET_HTTP_HOST',
     'addExpect100Continue',
     'disableBodySigning'

**Comment by jeskew** [comment]
@mmcminn When you provide a callback to an operation, [`send` is called on your behalf] before the request object is returned to you. Each requests was being sent twice and would succeed on the first invocation and fail on the second.

I believe sending a request a second time is firmly in undefined territory, but I'll confer with @chrisradek about whether this is a bug or just working as expected.

**Comment by jeskew** [comment]
I discussed this with the team, and the fact that registered callbacks on a particular request are not necessarily idempotent means that requests cannot reliable be sent more than once. I'll update the documentation to make this more clear.
