### ISSUE TITLE
Glacier's `uploadArchive` doesn't support file name?

### ISSUE THREAD

**Issue by zhanzhenzhen** [aws/aws-sdk-js#1521]
I've read #418. To contain a large file in a buffer is very expensive. I understand that the SDK can't use Readable Stream, but can it use a file name (rather than a buffer)? I've also found that many other AWS SDKs (.NET, JAVA) support file names.

Of course we can use multipart upload, but it seems too complicated, and I guess it counts as multiple requests so costs more money.

**Comment by jeskew** [comment]
Hi @zhanzhenzhen,

Unfortunately, using a file name would present the same issue as a stream: the SDK would need to iterate over the stream to calculate the hash and then also pass an unconsumed stream to the HTTP layer. It's not impossible to do this with a file -- the SDK could just call `fs.createReadStream` on the path twice -- but the file could change in between when the first and second calls are made, there wouldn't be a great way to port this functionality for browser-based applications, and the SDK would need an efficient and robust way to distinguish between strings that represent file paths and strings that represent archive contents.

I think a better path forward would be to implement a managed uploader (like the one the SDK has for S3) that could perform a multipart upload from streaming input. It would require a fixed amount of memory (~5MB, though this would be customizable) and support uploading streams or files of an arbitrary size. Would adding a feature like that solve your issue?

**Comment by zhanzhenzhen** [comment]
Adding this feature would be nice. But I still don't know why in CLI we can use a filename to upload a big file with very little memory consumption?

**Comment by jeskew** [comment]
I would need to check with the CLI team to be sure, but it looks like this is due to a language difference between Node and Python. Python's file abstraction allows you to seek to any arbitrary position in the file, which the CLI [does after computing the relevant hash](https://github.com/boto/botocore/blob/8483d71daf66234644e760050ab2371eae95eac9/botocore/handlers.py#L629), whereas Node streams are not seekable.

I know that the PHP SDK has a managed uploader that is internally multipart. The advantage of this approach is that part uploads can be completed in parallel and if any fail, only the upload of that part needs to be retried.

**Comment by zhanzhenzhen** [comment]
How about using `fs.read` which can also seek to any arbitrary position in the file?

> the SDK would need an efficient and robust way to distinguish between strings that represent file paths and strings that represent archive contents.

That's easy. Adding a new property such as `filename` can tell it it's a file.

**Comment by jeskew** [comment]
That's certainly an option. I think it would be preferable to add an abstraction that will also work with non-file streams, but a custom incremental hasher based on `fs.read` and a customization that populates the `body` parameter with a stream from a path specified at `filename` could also work for this use case.

**Comment by zhanzhenzhen** [comment]
Oh, just found in .NET SDK there's an upload manager which can automatically decide whether or not to do multipart uploading depending on the file size. So "manager" just means doing it intelligently? Sorry I just know there're many differences between the SDKs.

**Comment by jeskew** [comment]
Yeah, the higher level abstractions are not completely standardized across SDKs. A manager would just use a multipart or single part upload based on the size of the input under the hood.
