### ISSUE TITLE
Why Am Getting This Erorr while pushing the values to Route53 server

### ISSUE THREAD

**Issue by shiva151** [aws/aws-sdk-js#1522]
![screenshot from 2017-05-24 12-31-30](https://cloud.githubusercontent.com/assets/17164977/26393607/f0e26df4-4087-11e7-80c0-875e6af00955.png)

**Comment by chrisradek** [comment]
@shiva151 
Can you share what version of the SDK you're using, and what operations you're calling? Does this error occur frequently or is it sporadic?

**Comment by shiva151** [comment]
Hello,@chrisradek 
I am using aws-sdk@2.32.0, and I am not getting that error frequently, sometimes it's working perfectly. actually am not able to figure it out, when the problem occurring, am just pushing one domain to aws server to get the nameservers of that domain, sometimes it's working perfectly and sometimes not.
Hope U will help me in this.

**Comment by chrisradek** [comment]
@shiva151 
Sorry for the delayed response. Can you share the operation with parameters that you're calling? The parameters can be fake.

Can you also log the error with something like `JSON.stringify` so we can also see the extra fields on the error object?
