### ISSUE TITLE
LexModelBuildingRuntime missing from all.js

### ISSUE THREAD

**Issue by adenhertog** [aws/aws-sdk-js#1526]
The `LexModelBuildingRuntime` can't be loaded from the aws-sdk at runtime although the type definitions are present.

The cause appears to be that `clients/all.js` is missing the `LexModelBuildingRuntime` service definition.

**Comment by chrisradek** [comment]
@adenhertog 
I think you're looking for the LexModelBuildingService, not LexModelBuildingRuntime.
There's also LexRuntime, but that's different than the builder.

`LexModelBuildingService` is in `clients/all.js`:
https://github.com/aws/aws-sdk-js/blob/master/clients/all.js#L102

**Comment by adenhertog** [comment]
@chrisradek 
Yep thanks, I did mean to refer to `LexModelBuildingService` :)

When I look at https://raw.githubusercontent.com/aws/aws-sdk-js/master/dist/aws-sdk.js I still can't find that service being exported anywhere? I figured it should be somewhere like:
```
module.exports = {
   ...
   LexModelBuildingService: require('./lexmodelbuildingservice'),
   LexRuntime: require('./lexruntime'),
   ...
}
```

When I do this in TS, I'm getting `LexModelBuildingService is undefined`:
```
import { LexModelBuildingService } from 'aws-sdk'
console.log(LexModelBuildingService)
```

This is all with v2.57.0

**Comment by chrisradek** [comment]
@adenhertog 
Ah, the browser version of the SDK only contains the services that we have verified support CORS. You can build a version of the SDK that includes the LexModelBuildingService.

There's a few ways you can do this.
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html
If you're using script tags to import the SDK, then the easiest way to build a new version of the SDK is to use our browser builder:
https://sdk.amazonaws.com/builder/js/

If you're using a tool like webpack, you can follow instructions here:
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/webpack.html

Let me know if this helps or if you need more info!

**Comment by adenhertog** [comment]
@chrisradek 
That makes sense, thanks for the info :+1:
