### ISSUE TITLE
Set TTL attribute for a table on localhost

### ISSUE THREAD

**Issue by westpole** [aws/aws-sdk-js#1527]
I am trying to enable Time To Live feature on one of my tables. According to the documentation describeTimeToLive method should set TTL (and it is available from aws-sdk package), but it triggers an error message:

> UnknownOperationException: An unknown operation was requested.

Did I missed any configuration option, that I need to enable in order to use TTL? Or this TTL simply does not available for a localhost instance? 

I am using aws-sdk v2.57.0 and localhost DynamoDB v1.11.86.

**Comment by jeskew** [comment]
Hi @westpole,

I reached out to the relevant team and asked if TTL is supported in DynamoDB local. I will update this issue when I hear back from them.

**Comment by jeskew** [comment]
@westpole DynamoDB Local does not yet support TTL, but I've passed the feedback on to the service team. 

The best place to look for announcements of features like that would the [DynamoDB blog](https://aws.amazon.com/blogs/aws/category/amazon-dynamo-db/) or the [AWS twitter feed](https://twitter.com/awscloud).

**Comment by westpole** [comment]
Thank you @jeskew for an information.

**Comment by gurpreetatwal** [comment]
Any updates on when this might be available?

**Comment by rfmauri** [comment]
Any updates on when this might be available?

**Comment by platform-climate** [comment]
Hi is there any update when this feature will be available in local dynamodb

**Comment by msolimans** [comment]
any updates?

**Comment by trivikr** [comment]
Locking this thread as the issue is old, and resolved. As per https://github.com/aws/aws-sdk-js/issues/1527#issuecomment-305026722, the support has to be provided by DynamoDB and not SDK.
Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
