### ISSUE TITLE
Credentials in React-Native

### ISSUE THREAD

**Issue by ChristophRob** [aws/aws-sdk-js#1531]
In React Native it is not possible to set the credentials. I tried every possibility. 
1.  the .aws/credentials file (which works in node.js) does not seem to get loaded automatically.
--> missing credentials

2. If i try to use Cognito, it gives me the error "undefined is not an object (evaluating 'cognitoClient.initWithOptions')":
`AWSCognitoCredentials.initWithOptions({"region":CognitoRegion,"identity_pool_id":identity_pool_id})`

3. and log from file also not works:
`import { Config, S3 } from 'aws-sdk/dist/aws-sdk-react-native';`
`Config.credentials = new Config.loadFromPath('./config.json');`

<img width="359" alt="loadfrompath" src="https://cloud.githubusercontent.com/assets/16916263/26523784/0d65946c-431f-11e7-9a52-2c466abcd33a.png">

There seems to be something wrong

**Comment by chrisradek** [comment]
@ChristophRob 
In React Native, the SDK doesn't have access to the file system. You'll need to set up credentials similarly to how you would in a web browser. The recommended way is to use Cognito Identity. You should be able to follow the instructions on setting up credentials in a web browser for your project as well:
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-browser.html

**Comment by ChristophRob** [comment]
Thats it! Thank you very much!!

**Comment by MrHubble** [comment]
@ChristophRob are you able to share what solution you used? Cognito seems too feature rich to me if you simply want to allow all users to upload photos to the same bucket on S3.

**Comment by ChristophRob** [comment]
@MrHubble Yes of course, i also added how i downloaded my pics (with Buffer), if that helps you, too. Well in my solution i am not using the feature that an individual user has some priviliges. I just use the IdentityPool for everyone.
But maybe this new Starter Kit helps you more:
https://github.com/awslabs/aws-mobile-react-native-starter

Here my code:


    const AWS = require('aws-sdk/dist/aws-sdk-react-native');

    var Buffer = require('buffer/').Buffer
    import { Image } from 'react-native';

    export const REGION = 'eu-central-1'
    export const BUCKET_NAME = "bucketname"

    AWS.config.update({region: REGION});
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: 'eu-central-1:xxxxx',
    });

    const s3 = new AWS.S3({
      apiVersion: '2006-03-01',
      params: {Bucket: settings.BUCKET_NAME}
    });

    let picParams = {
      Bucket: settings.BUCKET_NAME,
      Key: "pics/1.png"
    }
    
    export const lambda = new AWS.Lambda({region: REGION, apiVersion: '2015-03-31'});

    const getPic = (key, callback) => {
      picParams.Key = "pics/" + key
      s3.getObject(picParams, function(err, data) {
        if (err) {
          console.log('There was an error getting a pic: ' + err.message);
        } else {
          const buffer = Buffer.from(data.Body);
          const base64ImageData = buffer.toString('base64');
          const imgSrc = "data:image/png;base64," + base64ImageData;
          Image.getSize(imgSrc, (width, height) => {
            callback({
              picId: key,
              picData: imgSrc,
              picHeight: height,
              picWidth: width,
            });
          });
        }
      }.bind(this))
    }

    export { getPic };
