### ISSUE TITLE
Credentials per bucket

### ISSUE THREAD

**Issue by caub** [aws/aws-sdk-js#1534]
If the way to pass credentials is global like:

```js
AWS.config.update({
	credentials: new AWS.Credentials({
		accessKeyId: '.......',
		secretAccessKey: '.........'
	})
});
```

How would it be possible to do a [copyObject](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property) from one bucket to another?

**Comment by chrisradek** [comment]
@caub 
You can also pass in any configuration options to a service client constructor.

For example:
```javascript
var s3 = new AWS.S3({
  region: 'us-west-2',
  signatureVersion: 'v4',
  credentials: new AWS.Credentials({/**/})
});
```

Then you can call `s3.copyObject`. Your credentials and region should match your destination bucket.

```javascript
s3.copyObject({
  Bucket: 'DestinationBucket',
  Key: 'filename',
  CopySource: 'bucket/key' // this is the source bucket/key
});
```

**Comment by caub** [comment]
Thanks, so I should instantiate one AWS.S3  object, or two?

I tried multiple ways, the objects test/hello1 to hello7 exists on both bucket `foo` and `bar`, but copyObject returns either 'AccessDenied: Access Denied' or 'All access to this object has been disabled' if I just try `CopySource: 'test/hello5', Key: 'test/hello33'` in the same bucket. I tried also 

```js
var s3Foo = new AWS.S3({
	apiVersion: '2006-03-01',
	params: {Bucket: 'foo'},
	accessKeyId: '.....', 
	secretAccessKey: '.....'
});

var s3Bar = new AWS.S3({
	apiVersion: '2006-03-01',
	params: {Bucket: 'bar'},
	accessKeyId: '.....', 
	secretAccessKey: '........'
});

s3Foo.copyObject({
	CopySource: encodeURIComponent('bar/test/hello5'), // CopySource — (String) The name of the source bucket and key name of the source object, separated by a slash (/). Must be URL-encoded.
	Key: 'test/hello33',
	
}, function(err, data) {
	console.log(err, data);
})
```

**Comment by chrisradek** [comment]
@caub 
Does the same account have access to both buckets, or do you require 2 accounts?

If you have to use 2 accounts, I believe you need to configure the source bucket to allow your primary account access to the objects you want to copy. I'm not 100% sure how that works, so I'd suggest asking on the S3 forums if that's the case.

Alternatively, you could stream the object from one bucket to another, though this makes multiple S3 calls then, while also buffering some data locally.
```javascript
var s3Foo = new AWS.S3({
	apiVersion: '2006-03-01',
	params: {Bucket: 'foo'},
	accessKeyId: '.....', 
	secretAccessKey: '.....'
});

var s3Bar = new AWS.S3({
	apiVersion: '2006-03-01',
	params: {Bucket: 'bar'},
	accessKeyId: '.....', 
	secretAccessKey: '........'
});

var source = s3Bar.getObject({Key: 'test/hello5'}).createReadStream();
s3Foo.upload({Key: 'test/hello33', Body: source}, function(err, data) {
       console.log(err, data);
});
```

**Comment by caub** [comment]
Perfect, that's what I was wondering, I'll try to see if I can manage both with one account or do the streaming way
Thanks very much
