### ISSUE TITLE
module initialization error: ReferenceError when using kms.decrypt

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [aws/aws-sdk-js#1535]
Hello everyone,

I have a function which decrypt the encrypted variable which is sent to it. I just copied and paste the code from the button called code which is beside encypt button in aws lambda console. Here is my code after some modification:
` var decryptEnvVariable = function (encryptedEnvVar) {
        var promise = new Promise(function (resolve, reject) {
        const kms = new AWS.KMS();
        kms.decrypt({CiphertextBlob: new Buffer(encryptedEnvVar, 'base64')}, (err, data) = > {
            if (err) {
                console.log('Error in decryption of environment variable', err);
                reject(err);
            }
            resolve(data.Plaintext.toString('ascii'));
    });
    });
    return promise;

}`

     

So when I call the above I get the following error:
``START RequestId: eb7dd1ac-4549-11e7-b41b-071b15adaf2f Version: $LATEST
module initialization error: ReferenceError
        kms.decrypt({CiphertextBlob: new Buffer(encryptedEnvVar, 'base64')}, (err, data) = > {
                                                                             ^^^^^^^^^^^
ReferenceError: Invalid left-hand side in assignment
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: eb7dd1ac-4549-11e7-b41b-071b15adaf2f
REPORT RequestId: eb7dd1ac-4549-11e7-b41b-071b15adaf2f	Duration: 56.15 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 18 MB	

Any idea?

**Comment by chrisradek** [comment]
@hminaeeBrunswicknews 
You have a syntax error.
```javascript
kms.decrypt({CiphertextBlob: new Buffer(encryptedEnvVar, 'base64')}, (err, data) = > {
```
Notice that there is a space between `=` and `>` when there shouldn't be, so the runtime thinks you're trying to to do an invalid assignment.

**Comment by hminaeeBrunswicknews** [comment]
ooops right thanks
