### ISSUE TITLE
Mocking SDK functions

### ISSUE THREAD

**Issue by kbariotis** [aws/aws-sdk-js#1539]
I am running a GraphQL-js app in an AWS Lambda function. Mutations/Queries are calling lots of SDK's functions DynamoDB's, Lambda Invokes, etc. 

What's the preferred way of mocking/stubbing those functions so I can do an end to end test? I want to hit the Lambda handler that serves the GraphQL API and go all the way back but without actually calling the DynamoDB but instead to call my mocked functions.

Thank you and let me know if you need an example.

**Comment by chrisradek** [comment]
@kbariotis 
We don't officially have a way of mocking/stubbing functions. You might be able to get some community responses from StackOverflow.

Have you taken a look at [some of the libraries on NPM](https://www.npmjs.com/search?q=aws+mock) that support mocking SDK functions? Some of them allow mocking individual operations, and allow you to specify what the response should look like.

**Comment by darrenhgc** [comment]
@kbariotis
The solution I've settled on for this is to require the `aws-sdk` and then, using sinon, stub out the lower level `makeRequest` call of the `aws.Service.prototype`. Essentially a switch statement on the operation parameter passed to `makeRequest`. Then use the modified aws mock in your proxyquire to mock the aws service

```javascript
let aws = require('aws-sdk')
let sendEmailStub = sinon.stub(aws.Sevice.prototype, 'makeRequest', (op, params, cb) => {
  // in the case of sending emails
  if (op == 'sendEmail') return callback(null, true)
})

// maybe in your beforeEach()

let email = proxyQuire('file', {
  `aws-sdk`: aws
})
```

I want to believe that there is a better solution so I'd love to hear your feedback if you try this out.
