### ISSUE TITLE
upload() failures and why does it then make a request to `/?max-keys=0`?

### ISSUE THREAD

**Issue by davidmaxwaterman** [aws/aws-sdk-js#1545]
I am seeing upload() fail after about 14%-20% of uploading, and I'm not sure why.

I'm uploading with queueSize=1 and partSize=6MiB, and the file is 10MiB; so two parts, one at a time.

I have the HAR file, but with it containing keys and such, I'm not sure what parts are sensitive so prefer not to post it here.

In the network panel, the part upload says '(canceled)', seemingly always after 2 minutes (in the Time) column. In the console, it says 'upload failed: Error: Timeout' (I think 'upload failed' is my text in a console.error(), but the rest is from the promise rejection).

Observations:
1. I specify a region ('eu-west-1') in my AWS.Config(), and if I take that out, it doesn't do the '/?max-keys=0' request. Should I not be specifying a region? Why is it making this request if I do?
1. The requests always take `2.0 min`, which is suspicious. The 'Timing' panel says `Stalled`.
1. It seems to try partNumber=1 four times, then attempts three 'Access-Control-Request-Method: DELETE' requests that are 403/Forbidden (also each followed by a '?max-keys=0' request).
1. All the '?max-keys=0' requests are 403/Forbidden.

This was working OK previously. I even managed a 1GiB upload (still 1 part at a time, size 5MB+1B). I'm not entirely sure what has changed since then that is relevant, but I did play with the `leavePartsOnError` for a while (I set it to false when those efforts failed) - perhaps it left junk on the server that is causing a problem (though I thought subsequent uploads would overwrite them). Having said that, a totally new file behaves similarly.

Comments/thoughts to help me move forward are very appreciated.

**Comment by chrisradek** [comment]
@davidmaxwaterman 
Is your bucket in `eu-west-1`?
The request you're seeing with `/?max-keys=0` occurs when the region S3 is configured with differs from the region the bucket is in. The SDK has [logic](https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L554-L565) in place to determine the correct region the bucket is in. Assuming you're running the SDK in a browser, it will call `listObjects` with `MaxKeys = 0` if it encountered one of these errors: https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L19-L24

I think you've already discovered the SDK has a default timeout of 2 minutes. Are you testing with a slow internet connection? How many concurrent requests do you typically have going at once?
 Can you also share which browser(s) you've tested with? It is also possible to completely remove the timeout by setting it to 0 (`AWS.config.httpOptions.timeout = 0`.

**Comment by davidmaxwaterman** [comment]
I'm using chrome on Windows; yes all this is client-side.

Thanks for the explanation of what is going on with the logic. I *thought* my bucket is in eu-west-1 (Ireland), but perhaps I am wrong (I'm a front-end guy so I don't know too much about the back end).

**Comment by davidmaxwaterman** [comment]
The internet connection might possibly be slow. I can only typically get it to work with a single queue (ie 1), and with the smallest chunk/part size.

I'll try removing the timeout and see how that works...it sounds like it might be the best option for me, since I suspect the SHA might actually serve a purpose :)

**Comment by davidmaxwaterman** [comment]
I'll close this and continue in #1548 - they're probably at least closely related.
