### ISSUE TITLE
S3 getobject stream consumes more RAM in ec2

### ISSUE THREAD

**Issue by navaneetharaopy** [aws/aws-sdk-js#1546]
**Setup:**
```
Node version : 4.8.3
EC2 RAM: 4GB
SDK version : apiVersion: '2006-03-01'
```
**Problem**
Currently i am trying to access and write  1.5GB file from s3 bucket to ec2 disk. When this task is performed the RAM usage will  increase drastically. I use pipe for this operation. Below code gets file from s3 and writes to disk at `tempFilePath`.

      
 
           writeStream  = fs.createWriteStream(tempFilePath);
            readStream = s3.getObject(s3params).createReadStream();

            writeStream.on('close',function(arg1,arg2){
                console.log('write stream close');                
                async_cb();
            })

            writeStream.on('end',function(){
                console.log('write stream end');
            })
            writeStream.on('error',function(err){
                async_cb(err);
            })
            readStream.pipe(writeStream);

While searching for answer i came across [this](https://github.com/aws/aws-sdk-js/issues/605), But it only mention nodejs version related issue. 

So is there any optional parameter where i can limit the read and write speed of streams? as explained [here](https://nodejs.org/api/stream.html#stream_buffering)

**Comment by chrisradek** [comment]
@navaneetharaopy 
Do you see the same issue happening locally? What OS are you running on EC2?

Can you also share how much RAM usage increases by? Are you downloading multiple files at once?

**Comment by navaneetharaopy** [comment]
System Info : `4.9.27-14.31.amzn1.x86_64 #1 SMP Wed May 10 01:58:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` (Amazon AMI OS)

**RAM** usage before process start:
![screen shot 2017-06-06 at 5 02 17 pm](https://cloud.githubusercontent.com/assets/6571626/26827299/37632a82-4ada-11e7-8214-d04ec2addfd0.png)

**RAM** usage during process 



![screen shot 2017-06-06 at 5 03 22 pm](https://cloud.githubusercontent.com/assets/6571626/26827325/536ca686-4ada-11e7-80ac-f51489b2a5be.png)

There are no multiple file download. Only single file of size **1.5GB** is piped into ec2 disk from s3.

**Comment by srchase** [comment]
@navaneetharaopy 

Can you share how the ec2 ram usage compares to doing the same thing locally?
