### ISSUE TITLE
SerializationException No assembly name on stack! when creating attribute`__type`

### ISSUE THREAD

**Issue by benishak** [aws/aws-sdk-js#1547]
I'm trying to save an Item with the following attributes

```
_id : 123
name : "cool book"
date : { "__type" : 'Date', "iso" : "2017-06-04T19:54:41.117Z" }
```

when I replace `__type` with `_type` or `type` it works ...

**Comment by chrisradek** [comment]
@benishak 
Can you share what operation you're calling?

**Comment by benishak** [comment]
this doesn't work `put` and `update` 
I also get same error message doing it from the AWS Console

**Comment by jeskew** [comment]
Hi @benishak,

`__type` has a special meaning in DynamoDB's serialization format and is used to identify the type into which a document should be unmarshalled. (If you take a look at [the documentation on error handling](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html), you can see how `__type` is used to tell clients what species of error they've encountered.) This is a feature of the wire protocol and not something that the DocumentClient would be able to work around.

As a workaround for your application, you could use a different key for the discriminator field in the `date` map. As you mentioned, `_type` and `type` do not trigger any errors, nor would `___type` or `__dateType`. The document client could also proactively reject maps with a `__type` field and include a more detailed and specific error message.

**Comment by benishak** [comment]
@jeskew 
I'm ok with the workaround, actually the date object with `__type` comes from another library/api, so I cannot change it before it lands on my callback. I had to catch it, rename it and save it and when my application read it from dynamodb I must convert it back. 

I don't see any reason why this keyword can interfere with the response message of the error handling.
supposing that message also included key such `ok` or `errorCode`, this shouldn't mean at all that I cannot save object with these kewords, or am I wrong?

The error message is also misleading and doesn't tell anything about the cause
```
SerializationException No assembly name on stack
```

I was just lucky I was trying to save this particular single object, but if my object contained more attributes, then I will be clueless about the cause.

**Comment by jeskew** [comment]
The `__type` field has a special meaning to the serializer, which is why its usage triggers a `SerializationException` from DynamoDB. The best example of this particular usage in DynamoDB's documentation that I could find was in the section on error handling, but `__type` is not specific to error handling, and other error-related keys like `ok` and `errorCode` do not have a special meaning to the serializer.

**Comment by benishak** [comment]
@jeskew 

for some reasons while testing with DynamoDB Local, I didn't get that error and I was able to save my custom Date object with the attribute `__type`

```
@test.only 'handles updating a single object with array, object date'(done) {
        const adapter = $;
        const objectId = randomString(10);
        const className = randomString(7);

        const schema = {
            fields: {
                array: { type: 'Array' },
                object: { type: 'Object' },
                date: { type: 'Date' },
            }
        };


        adapter.createObject(className, schema, { objectId: objectId })
        .then(() => adapter._rawFind(className))
        .then(results => {
            expect(results.length).to.be.equal(1);
            const update = {
                array: [1, 2, 3],
                object: {foo: 'bar'},
                date: {
                    __type: 'Date',
                    iso: '2016-05-26T20:55:01.154Z',
                },
            };
            const query = { objectId: objectId };
            return adapter.findOneAndUpdate(className, schema, query, update)
        })
        .then(results => {
            const mob = results;
            expect(mob.array instanceof Array).to.be.equal(true);
            expect(typeof mob.object).to.be.equal('object');
            expect(mob.date.__type).to.be.equal('Date');
            expect(mob.date.iso).to.be.equal('2016-05-26T20:55:01.154Z');
            return adapter._rawFind(className);
        })
        .then(results => {
            expect(results.length).to.be.equal(1);
            const mob = results[0];
            expect(mob.array instanceof Array).to.be.equal(true);
            expect(typeof mob.object).to.be.equal('object');
            expect(typeof mob.date).to.be.equal('object');
            expect(mob.date.__type).to.be.equal('Date');
            expect(mob.date.iso).to.be.equal('2016-05-26T20:55:01.154Z');
            done();
        })
        .catch(error => {
            console.log(error);
            expect(error).to.be.undefined;
            done();
        });
    }
```
