### ISSUE TITLE
problems with 2 minute timeout on multi-part upload

### ISSUE THREAD

**Issue by davidmaxwaterman** [aws/aws-sdk-js#1548]
I see from the below issue that there is a 2 minute timeout.

I seem to be hitting this timeout with multi-part uploads on all but the most basic settings - ie I can get successful uploads with queue-size of 1 and part size of 5*1024*1025+1, but anything more than that is very unreliable, and the chunk upload(s) fail(s) at 2 mins.

My (temporary?) solution is to remove the calculation of the SHA sum using the `s3DisableBodySigning` option (thanks for that). I also have the option of increasing the timeout, but that just seems to be moving the issue to when the user selects a higher queue size and/or a larger chunk size - which they can do in my UI (since they might have faster hardware than I do).

1. It confuses me why the calculation of the SHA is included in the 'timeout'. Is that intended?
2. It seems to me that the calculation of SHAs should be done in web workers so that they can be done on their own thread/cores, perhaps even making the concurrency/queue-size default to the number of cores on the CPU. Is this something that is already done (or planned)?

Any comments?

Ref:

https://forums.aws.amazon.com/thread.jspa?messageID=787608&#787608
https://github.com/aws/aws-sdk-js/issues/942

**Comment by chrisradek** [comment]
@davidmaxwaterman 
The SHA256 calculation should not be part of the timeout. The 2 minute timeout specified by the SDK gets applied to the underlying XMLHttpRequest after that calculation.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout
[SDK Timeout Logic](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout)

Can you share which browser you are testing with? I'd like to run a profile and check if there are any quirks with the XMLHttpRequest implementation there.

**Comment by davidmaxwaterman** [comment]
Thanks for looking into this. I'm using Chrome on Windows 10:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by chrisradek** [comment]
Thats David. Do you have an idea how long the requests take when you aren't performing a SHA256 calculation?

With regards to your comment about doing the calculation in a webworker, that is something we've talked about supporting and would like to in the future, but isn't supported today.

**Comment by davidmaxwaterman** [comment]
I'm not too sure what you mean. If I don't do SHA calculations, then they usually succeed...and I just tested a 10MiB file 6MiB chunks, one at a time, and chunk#1 took 56.42s and #2 took 38.56s (using the numbers from chrome's network panel).
If I restrict the bandwidth using chrome's network panel, it slows down - 'Good 3G' is 1.1m + 43.95s; GPRS causes failures at 2 mins, and after 4 attempts, overall failure (including a final 4 DELETE requests that result in '403/Forbidden' for some reason - I guess I don't have permission to delete).

**Comment by davidmaxwaterman** [comment]
At per #1545, removing the timeout seems to improve things immensely - I've removed the SHA disable option so it is enabled again. However, if I throttle to GPRS, it doesn't fail in the same way: part 1 uploaded ok taking 41 mins, but part 2 had four net::ERR_CONNECTION_ABORTED failures after 22.5 mins, 22.5 mins, 25 mins, and 22.5 mins (followed by the usual four 403/Forbidden attempts). If that third one was also 22.5 instead of 25, I'd be tempted to think I had hit another timeout somewhere.

Anyway, I think I'll leave it this way since it seems to covers more connection attempts.

I wonder what your thoughts are. What is the purpose of the 2 min timeout?

**Comment by srchase** [comment]
@davidmaxwaterman 

From the comments exchanged between you and chrisradek, it appears this was resolved.

I'd like to close out this issue, but can re-open if you have followup questions.
