### ISSUE TITLE
[s3] upload is occasionally super slow

### ISSUE THREAD

**Issue by stevedomin** [aws/aws-sdk-js#1552]
Hello,

We are uploading images to S3 from a Node.js (express) server running in a container on a EC2 server. The images weigh no more than a few hundred KBs (between 50KB and 300KB most of the time).

We are using this SDK to upload the images using `AWS.S3.upload()` and most of the time the upload goes through in 100-200ms but occasionally it will take between 15 and 30s. It seems like the library is failing to establish a connection to S3

I also tried [stracing the process (gist with logs)](https://gist.github.com/stevedomin/61d6964971753276d5adb4dfd0396024) and all I can see is that long delay between the `connect` and `getsockopt` syscalls, and then a new socket being created. It looks like my server doesn't manage to connect to its S3 counterpart.

I've tried many things like setting keepAlives, connectTimeout, etc. but haven't had any success.

AWS SDK version: 2.63.0
Node version: 8.0 (same problem on 7.10)
OS: Ubuntu 16.04.2

**Comment by jeskew** [comment]
Hi @stevedomin,

`connectTimeout` settings only take effect [once a socket is assigned to a request](https://github.com/aws/aws-sdk-js/blob/master/lib/http/node.js#L58) and won't cause requests to time out if node is taking 15-30 seconds to provision a socket. Are you providing an HTTP agent to the SDK? If so, are you specifying a value on the agent for [`maxSockets`](https://nodejs.org/api/http.html#http_agent_maxsockets)?

**Comment by stevedomin** [comment]
Hi @jeskew,

I'm providing an agent but haven't configured `maxSockets`. How would that help in this case?

I've updated the strace logs, I didn't realise they were being truncated: https://gist.github.com/stevedomin/61d6964971753276d5adb4dfd0396024

My understanding of these logs is that a socket is being assigned by the kernel but then the actual connection takes a long time. I might be entirely wrong as my strace-fu is not fantastic :)

**Comment by jeskew** [comment]
If the agent is only allowed to provision a small number of sockets, then a request could potentially have to sit idle waiting for a socket to free. The SDK's `connectTimeout` only kicks in once a socket is assigned to a request.

I'll admit that I'm not very familiar with strace, but it looks like the error that took 30 seconds to trigger is a read timeout rather than a connect timeout. `getsockopt` is only called three times in the strace log in the linked gist, and twice it's getting the error for a socket that was opened within the same second on the system clock:

```
08:52:48 socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 66
08:52:48 connect(66, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("52.216.226.152")}, 16) = -1 EINPROGRESS (Operation now in progress)
08:52:48 recvmsg(18, 0x7fff2d233200, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:52:48 recvmsg(24, 0x7fff2d233210, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:52:48 recvmsg(24, 0x7fff2d233240, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:52:48 recvmsg(18, 0x7fff2d233200, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:52:48 recvmsg(24, 0x7fff2d233210, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:52:48 recvmsg(24, 0x7fff2d233240, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:52:48 getsockopt(66, SOL_SOCKET, SO_ERROR, [0], [4]) = 0

...

08:53:32 socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 59
08:53:32 connect(59, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("54.231.80.240")}, 16) = -1 EINPROGRESS (Operation now in progress)
08:53:32 recvmsg(18, 0x7fff2d233200, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:53:32 recvmsg(24, 0x7fff2d233210, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:53:32 recvmsg(24, 0x7fff2d233240, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:53:32 recvmsg(18, 0x7fff2d233200, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:53:32 recvmsg(24, 0x7fff2d233210, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:53:32 recvmsg(24, 0x7fff2d233240, 0) = -1 EAGAIN (Resource temporarily unavailable)
08:53:32 getsockopt(59, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
```

The second time `getsockopt` is called, however, occurs ~30 seconds after the socket reported that the operation was in progress:

```
08:53:03 socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 66
08:53:03 connect(66, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("54.231.98.88")}, 16) = -1 EINPROGRESS (Operation now in progress)
...
08:53:32 getsockopt(66, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
```

Since this is a reuse of the socket with the identifier 66, it's possible that the connection was kept alive and that node emitted a `socket` event with an already connected socket. (This would cause the SDK to skip attaching a connection timeout, as the connection would already be established.) 

The only timeout that would then apply is the "socket idle timeout," which severs the connection if the socket neither receives nor dispatches messages within a given timeframe. This value is configurable as the `timeout` HTTP option in the SDK but defaults to 30 seconds. Have you tried altering that value to more aggressively sever connections?

**Comment by ashishpai2** [comment]
I am facing the same issue.  JS S3 SDK's upload function is very slow. It took me 30 minutes to upload a 3gb file. Whereas if I use S3 command line tools, it takes 3-4 minutes.

**Comment by stevedomin** [comment]
@jeskew I did, but the problem stayed. We've decided to use a different approach and are no longer affected by this issue so I'll close to keep your tracker clean. Thanks for your help.

**Comment by usamamashkoor** [comment]
@stevedomin can you please share which approach you have used.

Thanks.

**Comment by caleb0199** [comment]
I would also appreciate seeing your new approach.

Thanks.

**Comment by stevedomin** [comment]
@usamamashkoor @caleb0199 we actually got rid of the upload to S3 altogether...

**Comment by usamamashkoor** [comment]
@stevedomin  and can you please explain it a little bit how did you manage to do that. 

Thanks.

**Comment by stevedomin** [comment]
We are no longer uploading files to S3 and serving them directly instead. This works well in that case but this bug could still have been problematic in other situations.

**Comment by eddjlam** [comment]
@stevedomin do you remember if you were using the IAM Role on the ec2 instance to authenticate?  I ran into a similar issue and found that by setting the credentials as environment variables greatly sped up the upload process.

**Comment by stevedomin** [comment]
@eddjlam unfortunately this was a while ago and I can't remember. Did you figure out why that's the case?
