### ISSUE TITLE
MODULE_NOT_FOUND: Could not find API configuration cognitoidentityserviceprovider-2016-04-18

### ISSUE THREAD

**Issue by exortech** [aws/aws-sdk-js#1554]
It seems like the latest changes to cognitoidentityserviceprovider have not propagated the new API  version (cognito-identity-2014-06-30) to the invoking code:  clients/cognitoidentityserviceprovider.js:10:17

It is still looking for version cognitoidentityserviceprovider-2016-04-18

**Comment by chrisradek** [comment]
@exortech 
There are 2 Cognito services.
1) CognitoIdentity, at 2014-06-30
  https://github.com/aws/aws-sdk-js/blob/master/clients/cognitoidentity.js
  https://github.com/aws/aws-sdk-js/blob/master/apis/cognito-identity-2014-06-30.normal.json
2) CognitoIdentityServiceProvider, at 2016-04-18
  https://github.com/aws/aws-sdk-js/blob/master/clients/cognitoidentityserviceprovider.js
  https://github.com/aws/aws-sdk-js/blob/master/apis/cognito-idp-2016-04-18.normal.json

Are you sure you've got the right service/apiVersion combo? If you're getting an error, can you share a code snippet that produces it?

**Comment by exortech** [comment]
Thanks for the response. This is working now that the new release of amazon-cognito-identity-js is available.
