### ISSUE TITLE
Deleting a Table

### ISSUE THREAD

**Issue by lengk** [aws/aws-sdk-js#1557]
According to the [documentation](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DeleteTable.html) there is a way of deleting tables.

However I didn't notice the operation in the [library](https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/document_client.js). 

Am I missing something?

**Comment by chrisradek** [comment]
@lengk 
Please see the API docs for the DynamoDB client:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#deleteTable-property
