### ISSUE TITLE
what is the best way to test DynamoDB ?

### ISSUE THREAD

**Issue by benishak** [aws/aws-sdk-js#1561]
Now when using MongoDB or other databases, you can use docker container and run a service to test your code against it.

Is there anyway to test DynamoDB without the need for any credentials just something like dry-run to test if ValidationException may happens and know that DynamoDB accepts my data.

there is a module aws-sdk-mock but I think it is only stub and spy

**Comment by benishak** [comment]
if something like this doesn't exist, I would like to see this market as feature request. (dry-run-or something in this context)

**Comment by jeskew** [comment]
Hi @benishak,

You can use [DynamoDB Local](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) for this purpose. The local installation still requires credentials, but you can use any values for your access key and secret key.
