### ISSUE TITLE
Unable to sign file without extension

### ISSUE THREAD

**Issue by Christilut** [aws/aws-sdk-js#1564]
So I have a file without extension that contains some text. I can't sign a url without a contenttype because the SDK will say `contenttype is required`. 
If I try to use `text/plain` as contenttype, then the signing works and the upload to S3 works when I add the `Content-Type` header to the PUT request, however... when I then download the file from S3, it will result in `filename.txt` where as the original file did not have an extension.

How should I handle this?

**Comment by chrisradek** [comment]
@Christilut 
Can you share the code that generates the presigned url, and the request you make to it? Also, are you using the node.js or browser SDK?

You should not have to specify a Content-Type to use a presigned url. The filename should exactly match the key in the presigned url as well.

**Comment by Christilut** [comment]
You're right, it was an error in my code. SIgning without ContentType works fine and the download is as expected now.
