### ISSUE TITLE
C# API Gateway API examples

### ISSUE THREAD

**Issue by genifycom** [aws/aws-sdk-js#1578]
I do not seem to be able to find any C# examples of how to use the API Gateway API.

I want to be able to create API Gateway proxy items from an existing list. I do not want to have to create a swagger file.

Can the AWSSDK create API Gateway proxy items? If so how?

Thanks
Dave

**Comment by chrisradek** [comment]
@genifycom 
The API docs for API Gateway in the .NET SDK can be found here:
http://docs.aws.amazon.com/sdkfornet/v3/apidocs/Index.html

This repo is for the JavaScript SDK. Can you post your question to the .NET SDK instead?
https://github.com/aws/aws-sdk-net
