### ISSUE TITLE
Is there a plan to completely move to promise style?

### ISSUE THREAD

**Issue by caub** [aws/aws-sdk-js#1580]
To be able to do for example
```js 
await s3.copyObject(...)
// instead of 
await s3.copyObject(...).promise()
``` 

It won't change much from callback style 
```js 
s3.copyObject(...).then(..).catch(..)
// instead of 
s3.copyObject(..., function(err, data){ ... })
```

Maybe with v3?

**Comment by jeskew** [comment]
We wouldn't be able to make the change described in a backwards compatible way, since calling an operation without a callback returns a request object. I'll leave this open as a feature request with the "needs major version" label.

**Comment by AlexThomasWebElevate** [comment]
+1

**Comment by graingert** [comment]
@jeskew You totally can, if you return a thenable instead of a promise

**Comment by graingert** [comment]
Eg here's a mixin:

```const thenable = Promiseable => class Thenable extends Promiseable {
   then(resolve, reject) {
      return this.promise(resolve, reject);
   }

   catch(reject) {
       return this.promise(v => v, reject);
   }
}
```

Might need to cache the promise too

**Comment by graingert** [comment]
This is what knex does http://knexjs.org/#Interfaces-then

**Comment by ajredniwja** [comment]
@caub 

This feature is introduced in [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3) which is not GA yet but it might be a good start for you to try.
