### ISSUE TITLE
unable to resolve modules 'event'

### ISSUE THREAD

**Issue by awitherow** [aws/aws-sdk-js#1582]
I have installed the dependency `amazon-cognito-identity-js` which seems to have a peer/whatever dependency on aws-sdk-js.

I am unable to resolve the module shown in the screenshot.

I have taken the recommended steps and it does not solve the issue.

<img width="322" alt="screen shot 2017-06-18 at 11 00 56" src="https://user-images.githubusercontent.com/1827147/27259768-dc61aad8-541a-11e7-9293-72aa0070c622.png">

I have attempted to install my node_modules with yarn 0.24.5 and npm 5.0.3 and both are failing in approach.

**Comment by jeskew** [comment]
Are you using webpack to create the application bundle? If so, which version?

**Comment by awitherow** [comment]
I have been in touch with some dudes from Exponent, and apparently that is the cause of the issue.

There is apparently a PR being worked on for this?

They have forked it and I have things working on this fork: https://github.com/expo/amazon-cognito-identity-js
