### ISSUE TITLE
s3.getObject returns a body with empty buffer data 

### ISSUE THREAD

**Issue by replicat0r** [aws/aws-sdk-js#1586]
I have a simple service that allows user to upload a json, and later fetch it if they like. The code works last week, Now a week later, the service is breaking, I have made no change to the code since then. 

After some investigation, I found out that even the file is uploaded file, when I use s3 to fetch the object, this is the response I would get back

{"AcceptRanges":"bytes","LastModified":"2017-04-27T14:45:03.000Z","ContentLength":1979,"ETag":"\"0c9fe5331bd43a0829667996ae1d30a5\"","ContentType":"binary/octet-stream","Metadata":{},"Body":{"type":"Buffer","data":[]}}

When I manually download the file, the object itself is fine. However fetching it via s3 seems to return an empty binary object. 

I am using the latest version of the the sdk, 2.7.x

What can i do to fix this?

**Comment by chrisradek** [comment]
@replicat0r 
What environment are you running the SDK in?

**Comment by replicat0r** [comment]
Nodejs v7.9.0

**Comment by chrisradek** [comment]
Can you share how you're making the download call? Are you by chance mixing streams and callbacks?

**Comment by replicat0r** [comment]
Well I was using Rxjs as my async, control mechanism, upload and download. I wanted to make sure that it wasnt that messing things up, So went to s3 docs and copy pasted the example code. as follows. 

Initially, I tried toString, JSON.stringify, and String() on the data.Body object, but it always returned emtpy, So I stringified the entire data object, thats when i found out it returned an empty buffer. 


    S3.getObject({
        Key: 'sample.json',
        Bucket: 'TESTBUCKET'
    }, function (err, data) {
        if (err) {
            console.log('FILE NOT FOUND')

            console.log(err, err.stack);
        } else {
            console.log(data)
            console.log(data.ETag)
            console.log ('thisis tostring',JSON.stringify(data))
            
        } // an error occurred

    });

**Comment by replicat0r** [comment]
and this is my s3 upload code

function _constructS3Object({
    filename,
    extension,
    folder,
    fileContent,
}) {
    const _folder = String(folder).replace(/\/$/, "");
    const _fileContent = JSON.stringify(fileContent);
    console.log('file to be uploaded',_fileContent)
    return {
        Bucket: BUCKET_NAME,
        Key: `${_folder}/${filename}.${extension}`,
        Body: _fileContent,
        Metadata: {}
    };
}

this basically produces a params object that gets piped into S3.upload(), _fileContent is a Json

**Comment by jeskew** [comment]
If there are any callbacks listening for an HTTP stream's `'data'` events, the stream will be consumed before the SDK can collect it into a buffer. Is anything in your application listening to HTTP `'data'` events? This could also be happening in a dependency -- for instance, older versions of Sentry's Raven library [were known to listen for `'data'` events on all HTTP streams](https://github.com/getsentry/raven-node/issues/273). Are you using any dependency that might be attaching listeners to all HTTP streams?

**Comment by replicat0r** [comment]
@jeskew you are right! I have been using glimpse [https://www.npmjs.com/package/@glimpse/glimpse] to analyse my requests. I just took it off, everything is working as expected. Ill submit a issue to the glimpse team. This such an edge case to happen. If you didnt bring this up, I would still be banging my head against the wall. Thanks!

**Comment by jeskew** [comment]
Happy to help. Please feel free to reopen if updating to version 0.21.5 or later of Glimpse does not resolve the issue.
