### ISSUE TITLE
Not able to import only S3 directly

### ISSUE THREAD

**Issue by mechanicals** [aws/aws-sdk-js#1588]
I am trying to use AWS Javascript SDK, but I am getting some errors. 
I am using the latest version of AWS SDK & using Webpack to build.

I am not able to use

import S3 from 'aws-sdk/clients/s3';
gives me S3 undefined.

Interestingly this works perfectly

import AWS from 'aws-sdk';
const S3 = new AWS.S3();
But I only want to import S3 not the whole AWS SDK. Any ideas what Am i doing wrong.

**Comment by chrisradek** [comment]
To import a service client using es2015 syntax, you would need to do:
```javascript
import * as S3 from 'aws-sdk/clients/s3';
```
This is because we aren't using default exports in the SDK.

**Comment by jeskew** [comment]
Closing, as it appears that the last comment answered the question. Please feel free to reopen if you have any questions or concerns.
