### ISSUE TITLE
Examples for TypeScript + Promises

### ISSUE THREAD

**Issue by luketn** [aws/aws-sdk-js#1591]
Hi!

I'm really enjoying the new TypeScript definitions in the SDK. They make working with the data fantastic.

I'm struggling to find good examples and best practices for working with it though. 

Would you be able to create a little sample project (or point me to one that exists) which demonstrates using the TypeScript bindings to drive the SDK?

Also I'm really struggling to figure out how to get a Promise out of the Route53 SDK methods. 
Here's my code - I feel like I shouldn't have to create my own Promise object here - is there a way to avoid it?

```
import { Route53, AWSError } from 'aws-sdk';

export class DnsApi {
    private route53:Route53;
    constructor() {
        this.route53 = new Route53();
    }

    getHostedZone(domain: string): Promise<Route53.HostedZone> {
        return new Promise<Route53.HostedZone>((fulfill, reject) => {
            this.route53.listHostedZonesByName({DNSName: domain, MaxItems: "1"}, (err:AWSError, data:Route53.ListHostedZonesByNameResponse) => {
                    if (err) {
                        reject('An error occurred attempting to call listHostedZonesByName()\n' + JSON.stringify(err));
                    }else if (data && data.HostedZones && data.HostedZones.length > 0) {
                        fulfill(data.HostedZones[0]);
                    } else {
                        reject('No hosted zone found.');
                    }
                });
        });
    }
}
```

Cheers,
Luke

**Comment by teledemic** [comment]
In general, you can just replace `awsfunction(blah, blah, callback)` with `awsfunction(blah, blah).promise()` to return the promisified version.

**Comment by jeskew** [comment]
Hi @luketn,

We don't have any full TypeScript sample apps in our documentation, but there is [a folder of "typescript tests."](https://github.com/aws/aws-sdk-js/tree/master/ts) These are files that include snippets of code invoking SDK functions and making type assertions on the input and return. I wouldn't copy and paste from them directly, as the code is not meant to be executed but just to be compiled.

**Comment by jeskew** [comment]
@teledemic is correct that operations on service clients can be called as `operationName(params).promise()` instead of as `operationName(params, callback)` to send a request and obtain a promise.
