### ISSUE TITLE
S3: Upload.abort() yields "reqRegionForNetworkingError" which results in "HTTP 400 Bad Request"

### ISSUE THREAD

**Issue by steffenweber** [aws/aws-sdk-js#1592]
This is a regression from version 2.18.0 to version 2.19.0. The bug still exists in version 2.75.0.

Calling the `abort` method on an S3 upload to *intentionally* abort the upload raises a `NetworkingError` which eventually causes the method `reqRegionForNetworkingError` to be called.

But the resulting HTTP request (`https://BUCKET_NAME.s3.amazonaws.com/?max-keys=0`) fails with the error `HTTP 400 Bad Request` and the message `AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1'`. The region `us-east-1` seems to be hardcoded in [s3.js#L647](https://github.com/aws/aws-sdk-js/blob/v2.75.0/lib/services/s3.js#L647).

My bucket is located in the region `eu-central-1` which I'm correctly specifying in my `new AWS.S3(…)` constructor call. Uploading, listing and deleting files is working fine and without errors. But aborting an upload raises the mentioned issue (the upload is aborted nevertheless but then causes the mentioned error).

Maybe calling the `abort` method should not raise a NetworkingError in the first place.

```javascript
var s3 = new AWS.S3({
    accessKeyId: config.accessKeyId,
    secretAccessKey: config.secretAccessKey,
    region: config.region,
    params: {Bucket: config.bucket},
});

var request = s3.upload({
    Key: file.name,
    ContentType: file.type,
    Body: file,
});

request.send();

window.setTimeout(function() {
    request.abort();
}), 1000);

```

**Comment by steffenweber** [comment]
According to https://stackoverflow.com/a/27092765/444959, `us-east-1` is probably hardcoded intentionally because it can be used to query the region of any bucket. Maybe this request should be sent to `https://s3.amazonaws.com/BUCKET_NAME?location` instead?

**Comment by jeskew** [comment]
Hi @steffenweber,

I think you may be aborting requests that have already completed. Per the [XmlHttpRequest spec](https://xhr.spec.whatwg.org/#the-abort()-method), aborting an already received message (one whose `readystate` property is 4) should transition the readystate back to 0 and replace the response with a [network error](https://fetch.spec.whatwg.org/#concept-network-error). If you abort a request before it reaches its final `readystate`, the SDK will halt processing with a [`RequestAbortedError`](https://github.com/aws/aws-sdk-js/blob/master/lib/http/xhr.js#L58).

I agree that the SDK's bucket region lookup shouldn't be invoked if a request is aborted, but I'll need to do some testing to figure out if a networking error triggered by aborting a completed request can be reliably identified. The spec is pretty adamant that network errors should be opaque (status of 0, null body, no headers, etc), so this would probably need to be pieced together from context clues. The bucket region query would still need to rely on a request sent to `https://BUCKET_NAME.s3.amazonaws.com/?max-keys=0`, as requests sent to `https://s3.amazonaws.com/BUCKET_NAME?location` require a special IAM permission. It should, however, be sent to the correct region.

As a workaround, you could try replacing the call to `window.setTimeout` with an `httpOptions.timeout` configuration parameter:

```javascript
var s3 = new AWS.S3({
    accessKeyId: config.accessKeyId,
    secretAccessKey: config.secretAccessKey,
    region: config.region,
    params: {Bucket: config.bucket},
    httpOptions: {timeout: 1000},
});
```

The value is used as the [XMLHttpRequest timeout](https://xhr.spec.whatwg.org/#the-timeout-attribute), which will halt the underlying request with a `TimeoutError`.

**Comment by steffenweber** [comment]
Thank you for the reply! :smiley:

In the demo code I've used `window.setTimeout` only to indicate that the upload is not aborted immediately. In reality, my users can cancel the upload anytime by clicking a button next to the progress bar. I should have said that, sorry!

I think we can definetely rule out the possibility that I'm aborting a request that has already completed. My internet connection is simply not fast enough.

There seems to have been another misunderstanding: When I said `NetworkingError`, I was referring to the code in `s3.js`. However, what the SDK passes to the `send` callback is indeed a `RequestAbortedError` with the message `Request aborted by user`.

However, for some reason calling the `abort` method eventually leads to a call of the `reqRegionForNetworkingError` method (that's why I talked about a `NetworkingError`).

I hope this resolves some misunderstandings. :smiley:

**Comment by steffenweber** [comment]
I think the problem originates here: https://github.com/aws/aws-sdk-js/blob/v2.75.0/lib/http/xhr.js#L56

Whenever an XmlHttpRequest is aborted, an error is raised. I think this should not happen in response to explicitly calling the `abort` method.

**Comment by jeskew** [comment]
It looks like the error code is being overwritten in [an event listener](https://github.com/aws/aws-sdk-js/blob/v2.75.0/lib/event_listeners.js#L273), which is causing `reqRegionForNetworkingError` to run for both `RequestAbortedError`s and `TimeoutError`s.

**Comment by steffenweber** [comment]
I can confirm that version 2.84.0 fixes this issue. Thank you!

**Comment by zaraustra** [comment]
Hello, I'm using aws-sdk v2.86.0
I managed to create that browser image upload and it's working, the only thing is that error message is still there... Should I leave it there or there is a way to "fix it"?
The error comes up immediatly but then the "second request" upload the image correctly and gives me back the uploaded file location.

```
let bucketName = '*****';
let bucketRegion = 'eu-west-2';
let IdentityPoolId = 'eu-west-2:*****-*****-*****-*****';
import AWS from 'aws-sdk';

AWS.config.update({
    region: bucketRegion,
    credentials: new AWS.CognitoIdentityCredentials({
        IdentityPoolId: IdentityPoolId
    })
});

let s3 = new AWS.S3({
    apiVersion: '2006-03-01',
    params: {Bucket: bucketName}
});

exports.addPhoto = addPhoto;
function addPhoto(photo, cb) {
    let file = photo;
    let fileName = file.name;
    let photoKey = Date.now() + '-' + fileName;
    s3.upload({
        Key: photoKey,
        Body: file,
        ACL: 'public-read'
    }, function(err, data) {
        if (err) {
            return cb('There was an error uploading your photo: ' + err.message);
        }
        console.log('Successfully uploaded photo.');
        cb(null, data.Location);
    });
}
```

**Comment by usamamashkoor** [comment]
@zaraustra can you please let me know how did you create these credentials 
 ```
credentials: new AWS.CognitoIdentityCredentials({
        IdentityPoolId: IdentityPoolId
    })
```
please let me know because i dont want to use S3 key and secret on client side. 
Thanks in advance.

**Comment by jeskew** [comment]
@usamamashkoor There's a page in our developer guide on using `CognitoIdentityCredentials` [here](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-browser-credentials-cognito.html). You might also want to take a look at the [Amazon Cognito developer guide](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html)
