### ISSUE TITLE
elbv2.describeTargetHealth: Target.NotRegistered

### ISSUE THREAD

**Issue by ludoblues** [aws/aws-sdk-js#1593]
I am using the aws-sdk (experimented with v2.75.0 and v2.76.0) to perform multiple operations on an ALB.

Every operations work fine except one:` elbv2.describeTargetHealth`, i get this error:
``` json
{
    "ResponseMetadata": {
        "RequestId": "***"
    },
    "TargetHealthDescriptions": [
        {
            "Target": {
                "Id": "i-***",
                "Port": 8081
            },
            "TargetHealth": {
                "State": "unused",
                "Reason": "Target.NotRegistered",
                "Description": "Target is not registered to the target group"
            }
        }
    ]
}
```

I am sure my `targetGroupArn` and my `instanceId` are correct, i use it just before to perform a `elbv2.registerTargets` and it works just fine.

i also tried to wait 10sc between executing `elbv2.registerTargets` and `elbv2.describeTargetHealth`, but i still get the same issue...

So i guess there is a bug with the `elbv2.describeTargetHealth` operation.

**Comment by jeskew** [comment]
Does the target never become available? ELBv2's operations usually operate on an eventual consistency model that requires consumers to poll until the operation takes effect. The SDK has abstractions for a few of these in the form of waiters, but it looks like [we do not have one that polls for `TargetHealth` transitions](https://github.com/aws/aws-sdk-js/blob/master/apis/elasticloadbalancingv2-2015-12-01.waiters2.json). 

We could add a waiter that calls `describeTargetHealth` until all members of the `TargetHealthDescriptions` array have a `TargetHealth.State` of `healthy`.

**Comment by ludoblues** [comment]
@jeskew thanks for the explaination about waiters.
I built a similar mecanism i use when i launch an EC2 to wait untill it is in running state.

First, i have created the ALB rules before i try to configure the target group helth checks (after having seen that the "unused" state means that the target is not configured to receive traffic from the ALB). 

Then, i used the mecanism i use to track EC2s state to wait for the target group health checks state to change, but it never change (i mean, according to the API response...).

What i observe from the AWS console is, when the API is still saying it is in "unused" state, i have seen it switching to the "unhealthy" state.

Also (and the reason it is in "unhealthy" state and not "heathy"), the health checks port is the default one (the one the targets are listening on), in my case 3000, while i am trying to set a different port (8081) with the API (as you can see in my first post).

So it looks like the API is not in sync with the real state (while everything works great using the console).

**Comment by ludoblues** [comment]
@jeskew regarding my last post, don't you think it should be labelized as a ``bug``?
It would be nice if someone could confirm observing (or not) the same issue with this method.

**Comment by jeskew** [comment]
I'll check back in with the ELB team to see if they have an update. In any case, this does not sound like a bug in the SDK. You can also raise this issue with them directly via [the EC2 Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=30).

**Comment by ajredniwja** [comment]
Hey @ludoblues 

Is this still an ongoing issue for you, closing this issue for now, please reach out if you continue to see the problem.
