### ISSUE TITLE
DynamoDB can Conditional Put ensure uniqueness on non-key attributes?

### ISSUE THREAD

**Issue by benishak** [aws/aws-sdk-js#1611]
Can I use ConditionalExpression to ensure that a duplicate item is not inserted with a non-key ?

Consider the example I have User table with the following params

```
- Primary Key : userId,
- Range Key : activityId
- non-keys attributes : username, email, activityCount
```

Can I use Condition Expression when creating to ensure uniqueness on **username** or/and **email** ?

```
let params : DynamoDB.DocumentClient.PutItemInput = {
            TableName : 'User'
            Item: {
                userId : uid
                username : "benishak",
                email : "git@github.com",
            },
            ExpressionAttributeNames : {
                '#un' : 'username',
                '#email' : 'email',
            },
            ConditionExpression : 'attribute_not_exists(#un) OR attribute_not_exists(#email)',
        }

        db.put(params).promise().then(....);
```

or
```
ConditionExpression : '#un <> :un OR #email <> :email',
```

I tested it and it seems to work but article around the internet seems to contradict me, people say ConditionExpression works only with HASH/Range Keys, so I though maybe I'm doing something wrong ....

**Comment by jeskew** [comment]
Hi @benishak,

I don't think you can enforce uniqueness on non-key attributes in this way. According to the [developer guide](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html), the `attribute_not_exists` function does something different when the field is a key vs not a key. For key fields, the operation will not be executed if an item with the provided key already exists in the table; for non-key fields, the operation will not be executed if the item already in the table with the same key as the `PutItemInput.Item` value has an attribute with the provided name.

You could enforce uniqueness on the client side by creating a global secondary index for each attribute you want to be unique with that attribute as its hash key, then querying that index before inserting a new user record.

**Comment by superandrew213** [comment]
@jeskew what if 2 users are querying that index for uniqueness at the same time? Both users will get the green flag to putItem and you will end up with duplicates for a unique field.

**Comment by linehrr** [comment]
I wonder if you just create another table with that attribute as hashKey, now you can use condition. and create a dynamo stream to update the main table whenever the helper table succeeded.

**Comment by artista7** [comment]
just stumbled upon the similar issue, and makes me think, is dynamo db nuts? There should be conditional checks on non-key attributes also...

**Comment by Triforcey** [comment]
Running into this problem myself, I'm thinking the solution would be to use updateItem rather than put, by supplying the field wanted to be kept unique in the key query and using a condition expression to cancel the operation if that field exists. In effect, updateItem should fail if the query gets a result, and succeed if it didn't, creating a new item.

**Comment by trivikr** [comment]
Locking this thread as the issue is old, and resolved.
@Triforcey Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
