### ISSUE TITLE
Asynchronous getSignedUrl callback is not really asynchronous

### ISSUE THREAD

**Issue by colinhemphill** [aws/aws-sdk-js#1612]
The AWS docs offer both a synchronous and asynchronous version of the `getSignedUrl` request. I default to using the async option since it has better authentication support. However, it appears that if you don't use one of the asynchronous authentication methods, the async version of the request isn't _actually_ asynchronous.

Here's an example.

```
async.eachLimit(items, 5, function (item, callback) {
  s3.getSignedUrl('getObject', {
    Bucket: 'my-bucket',
    Key: item.s3Key
  }, function (err, url) {
    if (err) return callback(err);
    // do something with the url
    return callback();
  });
}, function (err) {
  // done with async loop
});
```

If `s3.getSignedUrl(operation, params, callback)` was really asynchronous when you use a callback, the above code would work great. With a large enough array of `items`, this fails and gives me a `RangeError: Maximum call stack size exceeded` error from the aws-sdk module.

If I wrap the callback in `async.setImmediate()`, the above works as I expect it to. This indicates to me that the callbacks are happening on the same tick in the event loop as the `getSignedUrl` function that's calling them. Can we force this to wait for the next tick if you're using the asynchronous version?

**Comment by jeskew** [comment]
Resolved in #1674 and #1676.
