### ISSUE TITLE
GetObjectOutput.LastModified is defined in Typescript as a Date, but is actually a string.

### ISSUE THREAD

**Issue by worldgnat** [aws/aws-sdk-js#1613]
The following code snippet doesn't work correctly: 
`let result = await s3.getObject({
      Bucket: "some_bucket",
      Key: "some_key"
  }).promise();
  console.log(result.LastModified.valueOf())`

The result is a formatted date string, which it should actually be a number in Epoch time. 

Furthermore, using the "getMilliseconds()" method fails, since it's a String, not a Date.

**Comment by jeskew** [comment]
Hi @worldgnat,

I'm having trouble reproducing the error. When I run the following script (in Node 7.10 and 8.1), an epoch milliseconds timestamp is always printed out to the console:

```javascript
const AWS = require('aws-sdk');
const s3 = new AWS.S3({region: 'us-west-2'});
const Bucket = '<bucket name>';
const Key = '<object key>';

(async function() {
  let result = await s3.getObject({Bucket, Key}).promise();

  console.log(result.LastModified.valueOf());
})();
```

Can you provide a bit more information about the runtime environment in which you're seeing the issue? E.g., Is this happening in Node or a browser? If Node, which version? If a browser, which one? Are you using a polyfill for async/await?

**Comment by worldgnat** [comment]
Interesting. We're using Node 6.11 and async/await.

**Comment by worldgnat** [comment]
Async/await shouldn't have anything to do with this though. If I modify the code to not use async/await, I still get the same result: 
```javascript
const AWS = require('aws-sdk');
const s3 = new AWS.S3({region: 'us-west-2'});
const Bucket = '<bucket name>';
        const Key = '<object key>';
        s3.getObject({Bucket, Key}).promise().then((result: any) => {
             console.log(result.LastModified.valueOf()); 
        });
```
returns "Thu, 06 Jul 2017 20:00:35 GMT"

**Comment by jeskew** [comment]
I thought a polyfill might be altering the values it received in some way. Which version of the SDK are you using?

**Comment by worldgnat** [comment]
We're using version 2.9

**Comment by jeskew** [comment]
I was able to reproduce on version 2.9. Any value that appears in a response header was not being properly deserialized to non-string types; this was fixed in version [2.29.0](https://github.com/aws/aws-sdk-js/pull/1407/files#diff-c4d0de556f9123dfa113c4b35ecdb7b1R128).

**Comment by worldgnat** [comment]
Oh! I didn't realize that. We'll upgrade. Thanks for looking into this, and sorry for bugging you about an old version.

**Comment by jeskew** [comment]
No worries! I've seen this issue reported before but had not previously tracked down which versions were affected.
