### ISSUE TITLE
CognitoIdentityCredentials Weird Behavior

### ISSUE THREAD

**Issue by alihalabyah** [aws/aws-sdk-js#1615]
Hi Guys,

I'm not sure if there is a similar issue was submitted recently but we are experiencing a weird behavior when calling the below:

```
config.credentials = new CognitoIdentityCredentials({
    IdentityPoolId: environment.cognitoIdentityPoolId,
    Logins: {
        [this.cognitoLogins]: this.getIdToken()
    }
});
``` 
It's firing a post request as below:

```
X-Amz-Target:AWSCognitoIdentityService.GetId
X-Amz-User-Agent:aws-sdk-js/2.80.0 callback
```
And then returning the below response:

```
{"IdentityId":"eu-west-1:cb137797-f62e-4c94-b797-e8fc3ad789cd"}
```
In which it will replace our identity pool id with an auto generated one that is breaking our application since any requests after the above will result in the below error:

```
{"__type":"InvalidIdentityPoolConfigurationException","message":"Invalid identity pool configuration. Check assigned IAM roles for this pool."}
``` 

This was working just fine few days ago and now our production app is not functional, the requests IDs for the above two requests are:

```
x-amzn-RequestId:7d230565-6267-11e7-8d50-b7aa6b6eeebd
x-amzn-RequestId:7d6c4318-6267-11e7-8aa2-0d819903032e
```

Can you please support urgently?

**Comment by jeskew** [comment]
Hi @alihalabyah,

Did the issue appear when upgrading to a new version of the SDK, or did the calls stop working without any changes to your application or its dependencies?

**Comment by alihalabyah** [comment]
@jeskew We have updated all of our packages recently and the version number we are using for the SDK is included above `aws-sdk-js/2.80.0`

Could that be the issue?

**Comment by jeskew** [comment]
Did the issue only occur after upgrading, and, if so, does downgrading to an earlier version fix the issue?

I don't think anything released recently would have the effect you're seeing, but I'm just trying to determine if the issue is coming from the SDK or the Cognito service.

**Comment by alihalabyah** [comment]
Apparently we were using `2.58.0` before, so it might be the reason for this issue, We'll try to downgrade, test and get back to you

**Comment by jeskew** [comment]
I don't see any changes in either [the commits included between 2.58.0 and 2.80.0](https://github.com/aws/aws-sdk-js/compare/v2.58.0...v2.80.0) or [the changelog](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md), so I suspect this is something the service team will need to help debug. If you can jump onto [Gitter](https://gitter.im/aws/aws-sdk-js?source=orgpage), I can get your contact information to pass on to them.

**Comment by alihalabyah** [comment]
Yes @jeskew i confirm this just tried and got the same

```
X-Amz-Target:AWSCognitoIdentityService.GetId
X-Amz-User-Agent:aws-sdk-js/2.58.0 callback
```

**Comment by jeskew** [comment]
I heard back from Cognito, who were able to provide the following guidance about the exception encountered:

> We throw InvalidIdentityPoolConfigurationException in 2 cases:
> 1. If the roles are not configured for the userPools. For example, user has enabled unauthenticated access and not configured roles for it.
> 2. If the roles are configured but they do not have correct policy associated with them. For example, roles do not allow access to Cognito.

Was there any change to the roles that corresponded with the start of the behavior described above?

**Comment by srchase** [comment]
@alihalabyah 

Is this an open issue for you?  I understand some time has passed and wanted to see if this is still relevant.
