### ISSUE TITLE
Can we abort/cancel donwloads

### ISSUE THREAD

**Issue by vimal** [aws/aws-sdk-js#1616]
```javascript
var file_download = s3.getObject(download_params);
```

Can we do in any means abort the getObject request
```javascript
file_download.abort()
```

**Comment by jeskew** [comment]
Yes. If you call `s3.getObject` without a callback, the method will return a [request object](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html). You can send a request object by calling [`send`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#send-property) on it and cancel it by calling [`abort`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#abort-property).

**Comment by vimal** [comment]
Even after calling abort it is still going for completion. Same while I am trying to upload a file and trying to abort.

**Comment by jeskew** [comment]
Can you share a bit more detail about how you're queuing requests and the runtime environment?
