### ISSUE TITLE
Implement GatewayResponse

### ISSUE THREAD

**Issue by nknotts** [aws/aws-sdk-js#1620]
http://docs.aws.amazon.com/apigateway/api-reference/resource/gateway-response/

It would be nice to have the get/put/update/delete methods as part of the APIGateway API.

In the meantime, I would like to manually issue the rest requests. It is possible to use the SDK to handle the authentication and make a generic rest call?

**Comment by jeskew** [comment]
The SDK is able to sign the request objects it generates, but this is not a public API. We have an open feature request to refactor the signers for public use (#1247).

**Comment by nknotts** [comment]
I was able to get it working with the latest [request](https://www.npmjs.com/package/request) which natively handles aws auth.
