### ISSUE TITLE
How will i delete all the files inside a bucket

### ISSUE THREAD

**Issue by mano-bharathi** [aws/aws-sdk-js#1621]
Hi,

I have bucket named "myBucket"  and it has lot of folders each folders will contain multiple files, if i want to delete all the folders how can i do ? Basically i need to clear the bucket. Please help me in this

**Comment by jeskew** [comment]
Hi @mano-bharathi,

"Folders" in S3 are just key prefixes, so calling [the `listObjects` method on an S3 client](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property) will retrieve a list of all objects in all folders. This API is paginated, so you will want to use [the `eachPage` method](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#eachPage-property) to get all pages of data and then call [the `deleteObjects` method on an S3 client](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#deleteObjects-property) to delete the objects listed on the page of data.

Please feel free to reopen if you have any further questions.
