### ISSUE TITLE
`httpUploadProgress` fires before the upload

### ISSUE THREAD

**Issue by aichholzer** [aws/aws-sdk-js#1623]
Running:
`aws-sdk: 2.82.0`
`node: 8.0.0` 

As it would seem `httpUploadProgress` does not fire after the upload has been successful, but before it happens. Look at this code:
```
const upload = new aws.S3.ManagedUpload({
  partSize: 5 * 1024 * 1024,
  queueSize: 8,
  params: {
    Bucket: 'BUCKET_NAME',
    Key: 'file.dmg',
    Body: fs.createReadStream('./file.dmg')
  }
});

upload.on('httpUploadProgress', (event) => {
  console.log(event.loaded * 100 / event.total);
});

upload.send((error, result) => {
  console.log('Done');
});
```

`file.dmg` has a size of 28.8 Mb.

After about 1 second, this gets logged to the console:
```
19.569250155460217
39.138500310920435
58.70775046638065
78.27700062184087
97.8462507773011
```
then, after about 10 seconds, this:
```
100
```
then, after a few minutes, this;
```
Done
```

I would imagine that the whole idea behind the `httpUploadProgress` event is to track the upload progress in "real time", as it happens. As it's currently implemented, it does not have any use.

**Comment by mebibou** [comment]
I am using version `2.113.0` and after a few seconds I get:
```
{ loaded: 7328032, total: 7328032 }
```
Then it will just hang for a long time before finishing, I will never get any other progress updates. There is definitely a bug on this

**Comment by aichholzer** [comment]
@srchase -Thank you. It's been over a year... I would not have imagined issues have such a low priority. In the meantime, I have moved away from AWS. So this is not relevant anymore.

**Comment by srchase** [comment]
This was investigated further.  httpUploadProgress is triggered as an event when that part is sent.  It is not based on when the upload of a given part succeeds.

httpUploadProgress gives some approximation for working through large uploads, but may not give the full picture because of the timing of how those events are fired.
