### ISSUE TITLE
[Question] Is there an API call to add triggers for Lambdas

### ISSUE THREAD

**Issue by halt-hammerzeit** [aws/aws-sdk-js#1625]
The API docs doesn't seem to contain any mentions of "trigger" word
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html
From the UI one can set a Lambda to run, say, every day.
Is it point-and-click only or could it be set programmatically?

**Comment by jeskew** [comment]
Hi @halt-hammerzeit,

You can set up Lambda functions to be automatically invoked in response to a number of triggers, including messages on SNS topics, inbound email messages received by SES, objects being uploaded to S3, items being inserted into a DynamoDB table, etc. A full list can be found [here](http://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html).

I'm not familiar with the UI feature you describe, but it sounds like it's using Cloudwatch Events behind the scenes. Cloudwatch has a tutorial on setting up a scheduled event programmatically with Lambda and the AWS CLI [here](http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/RunLambdaSchedule.html).

**Comment by halt-hammerzeit** [comment]
Ok, thx for the tip, the CloudWatch Events feature seems to do the same and it seems to have the API requried.

The trigger interface looks like this:

![image](https://user-images.githubusercontent.com/477167/28142402-6090cdaa-6769-11e7-884d-8ed6cae97c97.png)
