### ISSUE TITLE
getObject + callback + createReadStream = corrupted file downloads

### ISSUE THREAD

**Issue by broofa** [aws/aws-sdk-js#1628]
While using getObject() + createReadStream() to save an S3 file, we found we needed to pick up the case where the s3 key was not recognized.  The only way to do this is to provide a callback function to `getObject()`, thus we ended up with the following code: 

```
    const file = fs.createWriteStream(filepath);
    const s3Obj = s3.getObject(params, (err, data) => {
      if (err) callback(err);
    });
    s3Obj.createReadStream(). stream.pipe(file);
```

***However***... this resulted in corrupted files being saved to disk.   In our case, the S3 file was expected to be a ~640KB image file but what we ended up with was a ~900KB file where the first and last parts were correct, but that ~260-300KB of additional garbage in the middle.

After some experimentation, we found this bug only happened if we provided the getObject() callback.  Without the callback the file saves correctly.  Or, alternatively, getting the content via `data.Body`  in the callback also works.

So, the issue here is that 1) it's possile to use getObject+createReadStream in a way that produces corrupt files, and 2) the documentation does not describe how to capture invalid key errors in the context of getObject()+createReadStream() 

cc @pipemachine @chrisgilmerproj

**Comment by chrisradek** [comment]
@broofa 
When a request is called with a callback and createReadStream, it triggers a race condition where 2 requests are opened at once, but the data from both are piped to the same destination. There are some details about this [here](https://github.com/aws/aws-sdk-js/issues/959#issuecomment-209066648).

Instead of passing a callback function to `s3.getObject` to catch the error from the service, you should attach an error event listener to the s3 stream.

Example:
```javascript
var fs = require('fs');
var path = require('path');
var S3 = require('aws-sdk/clients/s3');

var s3 = new S3({
    region: 'us-west-2'
});

var name = 'fake.file';

var fileStream = fs.createWriteStream(path.join(__dirname, name));
var s3Stream = s3.getObject({Bucket: 'BUCKET', Key: name}).createReadStream();

// Listen for errors returned by the service
s3Stream.on('error', function(err) {
    // NoSuchKey: The specified key does not exist
    console.error(err);
});

s3Stream.pipe(fileStream).on('error', function(err) {
    // capture any errors that occur when writing data to the file
    console.error('File Stream:', err);
}).on('close', function() {
    console.log('Done.');
});
```

Our plan is to throw an error when mixing callbacks with streams are attempted, since doing so will usually cause unexpected behavior.

**Comment by broofa** [comment]
I believe we tried attaching an error listener to the stream, but did not see an error event for the case in question (invalid s3 key).   I'm traveling today, however, so am unable to work up a test case for this.  I'll try to put something together in the next few days.

**Comment by SneakyMax** [comment]
Also happens if you call `.promise()`

**Comment by elsonwu** [comment]
@broofa  Is this design too complicated and easy to cause a bug? move the `createReadStream` out as an individual method like this `s3.getObjectReadStream()` might work much clear, how do you think?

**Comment by broofa** [comment]
Sorry for the long delay here.  @elsonwu I missed (or didn't get notified?) of your comment.

Breaking this out into a separate and distinct method doesn't seem like a particularly good solution.  #1631 is probably good enough (haven't done a complete review), in that it at least throws an error with an explanation of the problem rather than corrupting data.

Another solution might be to rename `createReadStream()` to `getReadStream()`, and then return the existing read stream if one already created, or create a new one if needed.

That said, I haven't used this library in a couple years so I'm not confident that's actually a good idea.

**Comment by Doug-AWS** [comment]
I've updated the topic to include this information. Thanks everyone.
