### ISSUE TITLE
get signed url for s3 object?

### ISSUE THREAD

**Issue by Grummfy** [aws/aws-sdk-js#1629]
Hello,
in v2 we get a $s3Client->getObject()->getObjectUrl(); with an expiration time to get the url of an object inside s3 and make it available with a temporary url.

in v3 this was removed, and then we need to use preSignedUrl with

```php
	$cmd = $client->getCommand(
		'GetObject',
		[
			'Bucket' =>'my-bucket',
			'Key' => 'path/name.extension',
		]
	);
	$request = $client->createPresignedRequest($cmd, '+10 minutes');
	return (string)$request->getUri();
```

But this give an url with the famous "X-Amz-Content-Sha256=UNSIGNED-PAYLOAD".

So I can do $client->execute($cmd) to get the object but I can't get the signed url.
So to get the content of a private object I need to handle the download by the local server instead of redirecting.

The test I have made were with valid credentials (in the v2 they still working properly).

So how can we get this: getting a temporary url to a specific file inside s3.
Thanks

**Comment by chrisradek** [comment]
@Grummfy 
I think you meant to post this to the php sdk team overe [here](https://github.com/aws/aws-sdk-php). This is the JavaScript SDK. 😄
