### ISSUE TITLE
CodeBuild is not included in the browser build

### ISSUE THREAD

**Issue by bradzacher** [aws/aws-sdk-js#1637]
In file `clients/browser_default.js`, codebuild is not included.

From [the doco](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CodeBuild.html) it looks like it should be supported (the doco makes mention of browser specific config options).

Is this intentional?

**Comment by jeskew** [comment]
The browser build only includes services that support cross origin resource sharing, which CodeBuild does not. We maintain a list of supported services with a notation on which allow CORS [here](https://github.com/aws/aws-sdk-js/blob/master/SERVICES.md)

**Comment by tj** [comment]
damn, this got me too haha, seems odd that this one doesn't support CORS
