### ISSUE TITLE
Can we send an email with an attachment using sendEmail function or is this feature not supported?

### ISSUE THREAD

**Issue by arunrreddy** [aws/aws-sdk-js#1638]
`var params = {
        Destination: {
            ToAddresses: to
        },
        Message: {
            Body: {
                Html: {
                    Data: htmlTemplate
                }
            },
            Subject: {
                Data: subject
            }
        }
    }`
I am using this currently. Would be good if I could send an attachment using the following params:
`var params = {
        Destination: {
            ToAddresses: to
        },
        Message: {
            Body: {
                Html: {
                    Data: htmlTemplate
                }
            },
            Subject: {
                Data: subject
            },
            Attachments:  [
            {fileName: <fileName>, contentType: <contentType>, data: <base-64 encoded data>}
            ]
        }
    }`

**Comment by chrisradek** [comment]
@arunrreddy 
I believe you need to use [`sendRawEmail`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendRawEmail-property) to add attachments. 

There's an example of adding an attachment from SES here:
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html#send-email-raw-mime

If you want to request attachment support in sendEmail, you can also reach out to SES on the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=90&start=0).
