### ISSUE TITLE
How to use putObject and getObject with Transfer Acceleration?

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js#1639]
If I've enabled Transfer Acceleration on a bucket, do `putObject` and `getObject` automatically use it? (I'm assuming these just use XHR `POST` behind the scenes.. so really, my question is about the REST API)

**Comment by ffxsam** [comment]
Never mind, figured it out.
https://github.com/aws/aws-sdk-js/blob/d3f0701e8aff9697231f023d2e5a5c289a8ec8ec/lib/services/s3.js#L203-L233

**Comment by chrisradek** [comment]
@ffxsam 
Once you've enabled transfer acceleration on your bucket, you will need to configure the S3 client from the SDK to use the accelerate endpoint. By default, it is turned off.
We use the same bucket name you specify, but do change the endpoint.

```javascript
var s3 = new AWS.S3({useAccelerateEndpoint: true});
```

**Comment by ffxsam** [comment]
Ahh, it is indeed `false` by default. Thanks for pointing that out!

**Comment by chrisradek** [comment]
No problem!

**Comment by rwholey-eb** [comment]
@chrisradek Thank you for posting! Is there documentation for the 'useAccelerateEndpoint' flag? I can't find it on the sdk doc here https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html
