### ISSUE TITLE
Cannot run my app with genymotion

### ISSUE THREAD

**Issue by caneta** [aws/aws-sdk-js#1640]
Hi, I've followed your guide to use a react native app and it works with Expo on my phone, but it does not on my desktop with Genymotion emulator:
```
user@host:/home/user/projects/awsmobile$ npm run android

> awsmobile@0.1.0 android /home/candini/projects/ariadnesperimentazioni/awsmobile/awsmobile
> react-native-scripts android

17:49:49: Starting packager...
17:50:03: Starting Android...
(node:15443) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: write EPROTO 140413336405888:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
```
I'm behind a proxy and I've followed [this official guide](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html), but it seems not to be related to my problem...any suggestions?

**Comment by chrisradek** [comment]
@caneta 
Have you tried running it within the official android emulator? I haven't tried Genymotion, but I have tested the SDK on an Android emulator. The above guide is for node.js, so I'm not sure if it will work in a react native environment. Did you only have to reconfigure the SDK once you switched to the emulator, or did you have to do that for expo too?

**Comment by caneta** [comment]
Hi @chrisradek. I've used Genymotion because on create-react-native-app project, [they recommend using it](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#npm-run-android).
I haven't reconfigured anything: following the guide the Expo App works, the emulator doesn't, giving to my that SSL error.

**Comment by srchase** [comment]
@caneta 

Were you able to get this resolved?  Did you have any luck with the official android emulator?

**Comment by caneta** [comment]
No @srchase, sorry but I didn't tried...

**Comment by srchase** [comment]
I'm going to close this issue for now.   We're happy to re-open if you have time to re-engage.
