### ISSUE TITLE
Can not create new S3 instance

### ISSUE THREAD

**Issue by cuongnm265** [aws/aws-sdk-js#1641]
Hi I'm using aws sdk with Angular via angular-cli. Every worked well in development mode but in the production, this line: 
`let s3Bucket = new AWS.S3()` raise `Cannot convert undefined or null to object at hasOwnProperty`.
I used `/// <reference types="aws-sdk" />` and `import * as AWS from 'aws-sdk';`

**Comment by chrisradek** [comment]
@cuongnm265 
Can you make sure that the SDK is getting installed in production? Can you also provide the stack trace of the error you're seeing?

**Comment by cuongnm265** [comment]
@chrisradek Thanks for your help. I solve this problem by build my app on local and serve it on another host instead of heroku
