### ISSUE TITLE
Typings: Incorrect type definition for DocumentClient.QueryOutput.Items

### ISSUE THREAD

**Issue by tomc974** [aws/aws-sdk-js#1642]
According to [DynamoDb documentation][doc-link], and confirmed by testing, when you use the `DocumentClient.query()` method, the `QueryOutput.Items` should **always be a result set**. Current type definition `Items?: ItemList;` should be changed to `Items: ItemList;`

[doc-link]: http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html

**Comment by jeskew** [comment]
Hi @tomc974,

The typescript definition files (and the API documentation) are generated from a shared service model. I'll pass your feedback on to the service team to see if the service model could be made more explicit in what is returned by DynamoDB's `Query` operation.

**Comment by srchase** [comment]
This feedback has been passed along to that team.  I'm going to close this issue as it's up to the Service Team to make the change.
