### ISSUE TITLE
Incorrect promise rejection being thrown instead of being handled by try/catch (FOR ENTIRE SDK)

### ISSUE THREAD

**Issue by niftylettuce** [aws/aws-sdk-js#1650]
```js
try {
  const cloudfront = new AWS.cloudfront({}); // intentional typo (should actually be CloudFront)
} catch (err) {
  throw err;
}
```

Instead of getting thrown as an error in the try/catch `catch` block, it gets thrown as an unhandled promise rejection for who knows what reason.

```log
(node:31923) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: AWS.cloudfront is not a constructor
(node:31923) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is a CRITICAL and CORE bug that is directly related to #1076.

We should be throwing this error.  It is currently nested inside an unhandled promise.

**Comment by jeskew** [comment]
Hi @niftylettuce,

Are you running the snippet above in an `async` function? `async` functions implicitly return a promise, so throwing an error (as is done on the third line of the snippet posted above) inside of one will result in a promise rejection. 

Running the following script will result in a `TypeError` being thrown, as the SDK does not use promises internally unless a `.promise()` or similar method is called:

```javascript
const AWS = require('aws-sdk');

const cf = new AWS.Cloudfront({region: 'us-east-1'});
```

console output in Node 8.1.3:
```
const cf = new AWS.Cloudfront({region: 'us-east-1'});
           ^

TypeError: AWS.Cloudfront is not a constructor
    at Object.<anonymous> (/~/Workspace/aws-sdk-js/.sandbox/promiseRejection.js:3:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by jeskew** [comment]
While we're investigating if this is a bug in the SDK or an unrelated promise rejection in code calling the SDK, I'm going to remove the `**CRITICAL BUG**` text from the issue title.

**Comment by niftylettuce** [comment]
Np I think this is a bug as described with my usage of promises and async.
You can close it.

**Comment by niftylettuce** [comment]
Sorry about that, one of those days 🤦‍♂️
