### ISSUE TITLE
InvalidSignatureException: Signature not yet current

### ISSUE THREAD

**Issue by tgensol** [aws/aws-sdk-js#1652]
Hi there,

I am using the sdk with a ionic 3 app, and for some of my users I am getting these errors : 
`
Signature not yet current: 20170731T092200Z is still later than 20170731T092115Z (20170731T091615Z + 5 min.)`

I try to look for a fix, I understand when the sdk is running on a server, but how to do it when it is running on a mobile phone ? Maybe I am using wrong the sdk ? I am using the SNS and Kinesis parts,

Thanking you in advance,
Regards

**Comment by jeskew** [comment]
The SDK has built-in clock skew correction for use in browsers and in mobile applications. (On a server, you would want to rely on a system clock synchronized over NTP, but that's not an option on a client device.)

Could you try setting [the `correctClockSkew` configuration option](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#correctClockSkew-property) to `true` and see if that takes care of the errors?

**Comment by AllanFly120** [comment]
Due to no update in this thread, it will be closed.

**Comment by Usamaliaquat123** [comment]
set `AWS.config.correctClockSkew = true` its working ❤️
