### ISSUE TITLE
Add AssumeRoleCredentials

### ISSUE THREAD

**Issue by eladidan** [aws/aws-sdk-js#1657]
Similarly to: 
http://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/AssumeRoleCredentials.html
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSAssumeRoleSessionCredentialsProvider.html

To enable clients that are using assumed roles to manage access to resources (e.g. cross accounts) to handle session refresh and hide the need to directly talk to STS

**Comment by jeskew** [comment]
Hi @eladidan,

The SDK makes this feature available as the [`AWS.TemporaryCredentials` class](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/temporary_credentials.js).
