### ISSUE TITLE
How can I specify where the multi-upload is success and can be downloaded when I use aws-js-sdk

### ISSUE THREAD

**Issue by Halimao** [aws/aws-sdk-js#1661]
Hi All:
 I'm using aws-sdk-js, I using it process multi-upload, I can justify it whether it has uploaded all pieces success by listening hasUploadSize/totalSize==1. But once it equal to 1, I send a request soon to download which I just uploaded, it returns key is valid. While if I send the download request after hasUploadSize/totalSize==1 about 3s, it can be download success.It seems that S3 server hasn't integrate the multi-upload pieces complete, here comes the question-- How can I specify where the multi-upload is success and can be downloaded?

**Comment by AllanFly120** [comment]
Hi, it seems like you are looking for [waitfor()](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#objectExists-waiter).  This method can check several states every 5 seconds. In this case, the state is `'objectNotExists'`. Here is an example for waiting for this state.

```javascript
var params = {
  Bucket: BUCKET_NAME, /* required */
  Key: KEY_VALUE, /* required */
};
s3.waitFor('objectExists', params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

**Comment by Halimao** [comment]
@AllanFly120, Thank you very much, it works(^_^)
