### ISSUE TITLE
Some HTTP errors not invoking callback

### ISSUE THREAD

**Issue by mbp** [aws/aws-sdk-js#1663]
Sometimes when an HTTP error occurs from any of the AWS APIs, the callback function is not invoked. 

Code to reproduce:
```
    var cloudformation = new AWS.CloudFormation();
    for (var i = 0; i < 20; i++) 
    {
        cloudformation.getTemplateSummary({ StackName: "MyStackName" }, function (err, data) {
            if (err) {
                console.log("err", err);
            }
        });
    }
```

Run the above in the browser a few times, eventually you will get 20 HTTP errors but only a few of them will actually log "Error: Rate exceed" (in my case it was 3 out of 20).

**Comment by jeskew** [comment]
Hi @mbp,

The SDK will retry throttling errors up to three times by default, so your callback would only be invoked if the third retry failed. If a retry succeeds, no error would be passed to your callback.

**Comment by mbp** [comment]
Oh! Thanks
