### ISSUE TITLE
TemporaryCredentials Does Not Work With MFA When Invoked in Parallel

### ISSUE THREAD

**Issue by jthomerson** [aws/aws-sdk-js#1664]
If your SDK is configured to use the `TemporaryCredentials` provider and is using MFA to assume a role and your app has parallel processes calling the SDK, it will result in a credentials error.

This happens because `TemporaryCredentials` lazily-loads credentials in its `refresh` method. Unfortunately, that method does not have a lock around it, so if more than one asynchronous operation ends up making a call, `TemporaryCredentials` will call `refresh` for each call, and use the MFA token you passed it more than once. Thus, only the first call to refresh will work because the MFA token is a one-time-use token.

Here is some example code that demonstrates the problem. You can download it, `npm install underscore q aws-sdk minimist` and run it, passing it the `--role-arn`, `--mfa-serial`, `--mfa-token`, and optionally `--profile` arguments (if you need to use a profile from your shared INI credentials to assume the role). Pass `--refresh-first` to "fix" (workaround) the bug by calling refresh and waiting for it to succeed before your parallel operations start.

```js
#!/usr/bin/env node
'use strict';

var _ = require('underscore'),
    Q = require('q'),
    AWS = require('aws-sdk'),
    minimist = require('minimist'),
    argvOpts, argv;

argvOpts = {
   string: [ 'profile', 'role-arn', 'mfa-serial', 'mfa-token' ],
   'boolean': [ 'refresh-first' ],
};

argv = minimist(process.argv.slice(2), argvOpts);

if (!_.isEmpty(argv.profile)) {
   console.log('Setting AWS credentials provider to use profile %s', argv.profile);
   AWS.config.credentials = new AWS.SharedIniFileCredentials({ profile: argv.profile });
}

if (!_.isEmpty(argv['role-arn'])) {
   (function() {
      var params = { RoleArn: argv['role-arn'] };

      if (_.isEmpty(argv['mfa-serial'])) {
         console.log('Assuming role %s', params.RoleArn);
      } else {
         params.SerialNumber = argv['mfa-serial'];
         params.TokenCode = argv['mfa-token'];
         console.log('Assuming role %s with MFA %s (%s)', params.RoleArn, params.SerialNumber, params.TokenCode);
      }

      AWS.config.credentials = new AWS.TemporaryCredentials(params);
   }());
}


function startParallelProcesses() {
   return Q.all(_.map([ 'us-east-1', 'us-west-2', 'eu-west-1' ], function(region) {
      var s3 = new AWS.S3({ region: region });

      return Q.ninvoke(s3, 'listBuckets')
         .then(function(resp) {
            _.each(resp.Buckets, function(bucket) {
               console.log('Region "%s", bucket "%s" was created "%s"', region, bucket.Name, bucket.CreationDate);
            });
         });
   }))
   .then(function() {
      console.log('All done');
   });
}


if (argv['refresh-first']) {
   // If we manually call refresh on the temporary credentials first, we can avoid the
   // problem described below.
   Q.ninvoke(AWS.config.credentials, 'refresh')
      .then(function() {
         return startParallelProcesses();
      })
      .done();
} else {
   // Here is where the real issue is:
   // If we start a bunch of parallel processes simultaneously, they will all end up
   // resulting in the `refresh` function getting called on the temporary credentials,
   // which will result in our MFA code getting used more than once, which doesn't work
   // since it's a one-time-use code.
   startParallelProcesses().done();
}
```

**Comment by jthomerson** [comment]
Here's the same code as a zip. Unzip it and run `npm install`, then run `node index.js` with the args described above.

[provetempcreds.zip](https://github.com/aws/aws-sdk-js/files/1201139/provetempcreds.zip)

**Comment by jeskew** [comment]
I believe we can update `TemporaryCredentials` to limit itself to a single in-flight request (as we do with [EC2 instance metadata service credentials](https://github.com/aws/aws-sdk-js/blob/master/lib/metadata_service.js#L92)).

**Comment by jthomerson** [comment]
Any update on this issue? @jeskew?

**Comment by jthomerson** [comment]
One year later. Just checking on this issue. 

Also @srchase I disagree that this is a feature request - to me this is a bug.
