### ISSUE TITLE
Credentials per service

### ISSUE THREAD

**Issue by akaNightmare** [aws/aws-sdk-js#1666]
Hello,

I want to use different credentials for each service, i.e.: SES, EC2, ELB, S3. Can I set once only:
```js
AWS.config.setPromisesDependency(global.Promise);
AWS.config.update({
    region: config.get('aws.region') as string,
    apiVersions: config.get('aws.apiVersions'),
// something like this:
    services: {
       SES: {
         credentials: {
            accessKeyId: config.get('aws.ses.accessKeyId') as string,
            secretAccessKey: config.get('aws.ses.secretAccessKey') as string,
         },
       }
    },
// common
    credentials: {
        accessKeyId: config.get('aws.accessKeyId') as string,
        secretAccessKey: config.get('aws.secretAccessKey') as string,
    },
});
```

**Comment by jeskew** [comment]
Hi @akaNightmare,

You can do this by setting service-specific configuration in the AWS.config object, e.g., by setting [the `ses` property](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#ses-property). There's a property on AWS.config for every service, and the names can be found in the Service-Specific Configuration section of [the AWS.config documentation page](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html).
