### ISSUE TITLE
Ability to use sdk without setting config variables

### ISSUE THREAD

**Issue by pruhstal** [aws/aws-sdk-js#1667]
Scenario: Generating presigned_url to POST a file (.csv) to our S3 bucket from Python using boto3:

```
        s3 = boto3.client('s3')  # Get the service client
        return s3.generate_presigned_post(
            Bucket=settings.S3_BUCKET,
            Key=self._get_s3_path(page_id),
            Conditions=[
                {'acl': 'bucket-owner-full-control'},
                ['starts-with', '$x-amz-meta-tag', ''],
                ['content-length-range', 0, 1000000000] # Only added this recently to see if it'd help fix the timeouts.
            ]
        )
```

Client (javascript) receives the presigned post object from our Python server with the presigned_url in it. It uses that URL to POST a file upload using `FormData`:

```
    const fd = new FormData();
    fd.append('AWSAccessKeyId', presignedRes.data.fields.AWSAccessKeyId);
    fd.append('key', presignedRes.data.fields.key);
    fd.append('policy', presignedRes.data.fields.policy);
    fd.append('signature', presignedRes.data.fields.signature);
    fd.append('acl', 'bucket-owner-full-control');
    fd.append('x-amz-meta-tag', JSON.stringify(metadata));
    fd.append('file', parsedFile);
```

We currently aren't using the aws-sdk, however, think we may need to because we're seeing timeouts for large files.

Is there a way to use the sdk without having to initialize it with any of the config variables? Specifically the aws_secret_key and everything else that is required (since it's quite moot considering we get everything generated from the presigned_url object)?

**Comment by jeskew** [comment]
Hi @pruhstal,

You would need to provide AWS credentials, though you should not share your production credentials. We have a guide on using Cognito or Web Identity in the [developer guide](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-browser.html).

**Comment by pruhstal** [comment]
@jeskew Do you know if it's possible to do it with only using boto3?

**Comment by jeskew** [comment]
The only way I know of to do so is to use presigned POST forms (as you describe in the issue description) or presigned PutObject URLs (which are more limited than- and unlikely to avoid the timeout issues encountered with- POST forms).

I would recommend opening a support ticket with S3 or posting a question on [the S3 developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=24), as it really sounds like using boto3's `generate_presigned_post`  is the right technical solution for you.
