### ISSUE TITLE
Issues with S3.createBucket CreateBucketConfiguration.LocationConstraint validation

### ISSUE THREAD

**Issue by breathe** [aws/aws-sdk-js#1670]
LocationConstraint is not allowed to be "us-east-1" -- the 'default' value when not specified.  Its also not allowed to be empty string.  There is no way to specify a valid value for CreateBucketConfiguration that refers to us-east-1 -- in particular, this fails:

```
      const locationConstraint =
        awsprovider.region === "us-east-1"
          ? {}
          : {
              LocationConstraint: awsprovider.region
            };

      console.log("locationConstrain", locationConstraint);
      const createResponse = await s3
        .createBucket({
          Bucket: awsprovider.deploymentBucket,
          CreateBucketConfiguration: { ...locationConstraint }
        })
        .promise();
``` 

Here's the code that gets passed the sdk validation and works for "us-east-1" ...  Can the sdk's validation of this parameter be made more sane?

```
      // HOLY TECHNICAL DEBT BATMAN: aws s3 'default region' for buckets is us-east-1 -- but us-east-1 cannot be specified explicitly ...
      // to refer to us-east-1 make sure no CreateBucketConfiguration is supplied ...
      const locationConstraint =
        awsprovider.region === "us-east-1"
          ? {}
          : {
              CreateBucketConfiguration: {
                LocationConstraint: awsprovider.region
              }
            };

      console.log("locationConstrain", locationConstraint);
      const createResponse = await s3
        .createBucket({
          Bucket: awsprovider.deploymentBucket,
          ...locationConstraint
        })
        .promise();
```

**Comment by jeskew** [comment]
The `CreateBucketConfiguration` parameter [will be populated for your automatically if it is not supplied](https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L1012). 

Do you see any issues if you shorten the above code snippet to something resembling the following code?

```javascript
const createResponse = await s3
    .createBucket({
        Bucket: awsprovider.deploymentBucket,
    })
    .promise();
```

As you point out, if you supply the `CreateBucketConfiguration` parameter to the SDK, you will need to omit the `LocationConstraint` for buckets in `us-east-1`.

**Comment by breathe** [comment]
I don't actually need to generate buckets anywhere other than us-east-1 at the moment -- however I am adapting these requests from a different data-source which always specifies the region.  Maybe I will at some point specify a region other than us-east-1.  I can solve for now as above it just seems messy

**Comment by jeskew** [comment]
I'm still not sure why you need to specify the `CreateBucketConfiguration` at all. The SDK will automatically populate that parameter if it is not supplied.

**Comment by breathe** [comment]
Do you not need to specify it if you want to create the bucket in a particular region?

**Comment by jeskew** [comment]
The default behavior will create a bucket in the region of the S3 client. You would only need to specify the parameter if you want to create a bucket in a location other than the one to which the `CreateBucket` request was sent.

**Comment by breathe** [comment]
Hmm, yes I see now ... -- maybe relying on that behavior is the right thing for my use as well.  I'll close this.
