### ISSUE TITLE
Getting unable to get property 'Location' of undefined or null reference error in IE11

### ISSUE THREAD

**Issue by Lanceshi2** [aws/aws-sdk-js#1671]

**Comment by Lanceshi2** [comment]
I am getting the error unable to get property 'Location' of undefined or null reference error in IE11. In Chrome it work well. 

The error is on (107175, 13) in aws-sdk-2.77.0.js. I find it hard to debug this issue as I can't locate where is the exact line which has caused this. 

I have checked the file object I have passed for uploading which seems correct to me.

**Comment by jeskew** [comment]
Hi @Lanceshi2,

Can you provide a bit more information? Which service are you using, which operation are you calling?

**Comment by Lanceshi2** [comment]
@jeskew I'd love to. But I am not sure what to include. I am calling S3 service to ap-southeast-2 region. 

The code I am using is: 

```
    if(file) {
        var params = {
            Key: 'content-upload-development/' + file.name,
            ContentType: file.type,
            Body: file
        };
        bucket.upload(params).on('httpUploadProgress', function(evt){
            var percent = parseInt((evt.loaded * 100) / evt.total);
            var signedFormData = null;
            $(document).trigger("AmazonStatusUpdateEvent", ["Uploading", file.name, percent, signedFormData]);
        }).send(function(err, data) {
            var signedFormData = {};
            signedFormData.fileURL = data.Location;
            signedFormData.fileSize = "400m";
            $( document ).trigger( "AmazonStatusUpdateEvent", [ "Completed", file.name, 100, signedFormData ] ); 
        });
    }
```

file is got from event.target.files. From an <input type="file"> tag. Is there any other information I need to provide here? @jeskew

**Comment by jeskew** [comment]
It looks like `signedFormData.fileURL = data.Location;` could be triggering the error in the issue's title; if the callback is called with an error, `data` will be undefined. Can you check and log `err` in the callback to `send`?

**Comment by Lanceshi2** [comment]
@jeskew Thank you. You are right! I am getting the error:  Object doesn't support property or method 'addEventListener'. I will investigate this one...

**Comment by jeskew** [comment]
The only usage of `addEventListener` was the [HTTP handler calling `addEventListener` on an XMLHttpRequest object](https://github.com/aws/aws-sdk-js/blob/2c1b94e52edac41b08e999cb8f37cda54d2a1afd/lib/http/xhr.js#L22), which [should be supported in IE 11](https://msdn.microsoft.com/en-us/library/ms535874(v=vs.85).aspx). It's possible that an error is being thrown in a callback supplied to the SDK, as the SDK would catch and rethrow those.

**Comment by Lanceshi2** [comment]
@jeskew Thank you for the response. I know this has been a while but we still haven't figured out which line has caused the issue. Is there a way we can find which line has caused this issue?

**Comment by Lanceshi2** [comment]
@jeskew And I am not quite sure what does callback supplied to the sdk mean. It doesn't seem to me that I have used an addEventListener in the callback function...

**Comment by jeskew** [comment]
I was referring to the callback function. My hunch is that the `$(document).trigger("AmazonStatusUpdateEvent", ["Uploading", file.name, percent, signedFormData]);` line is causing an error to be thrown.

**Comment by Lanceshi2** [comment]
@jeskew I have put a break point into that line but it seems that it has never been reached.

**Comment by srchase** [comment]
@Lanceshi2,

Were you able to sort this out?  It looks like you have a usage question, and not an issue with the SDK itself.  I'd like to close this out if you have no further questions.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
