### ISSUE TITLE
Callback function called twice if a connection error occurs AFTER a response has been received

### ISSUE THREAD

**Issue by sjakthol** [aws/aws-sdk-js#1678]
We have been using the aws-sdk with NodeJS and have recently started to notice weird cases in which the callback function of the AWS API calls we make through the SDK are called multiple times. This is not that common but still occurs a few times a day. We have noticed this behavior with the Firehose PutRecordsBatch call but that is likely because we are calling that API quite often.

We started to look into this issue and managed to catch it while we had debug logging for the NodeJS http module on (NODE_DEBUG=http). Here's how that log looks like (irrelevant parts have been omitted):
* The initial connection to Firehose API is made
	> 2017-08-10T11:29:32.137Z HTTP 1: createConnection firehose.eu-west-1.amazonaws.com:443:::::::true: { agent: Agent { domain: null, _events: { free: [Function] }, _eventsCount: 1, _maxListeners: 0, defaultPort: 443, protocol: 'https:', options: { rejectUnauthorized: true, path: null }, requests: {}, sockets:
* A response to the request is received:
	> 2017-08-10T11:29:31.981Z HTTP 1: AGENT incoming response!
	> 2017-08-10T11:29:31.981Z HTTP 1: AGENT isHeadResponse false
	> 2017-08-10T11:29:31.981Z HTTP 1: AGENT socket.destroySoon()

* The connection receives a socket error immediately after seeing the response:
	> 2017-08-10T11:29:31.995Z HTTP 1: SOCKET ERROR: write ECONNRESET Error: write ECONNRESET at Object.exports._errnoException (util.js:870:11) at exports._exceptionWithHostPort (util.js:893:20) at WriteWrap.afterWrite (net.js:763:14)

The log then shows that a two new connections to Firehose are established (I'm assuming these are for the retry) and our callback is called for the first time. After some time passes our callback function is called for the second time which is kind of bad.

Based on the http module debug log I would be inclined to say that the response is handled properly when it is received but the error that occurs after that causes the retry mechanism to kick in. However, I have not been able to determine if this is really the case as I haven't been able to debug the AWS SDK when this error occurs.

Looking at the code at [1] I can see that it would be possible for the error callback (at [2]) to be called after the success callback (at [3]) as the success callback does not set the didCallback flag to true after being called. If the error handler at [2] fired after that, it would call the errCallback given to that function too.

This is the best theory I have so far on what could cause our callback function to be called multiple times.

Unfortunately, I have not been able to make a reliable test case for this issue as I have no visibility on what firehose.eu-west-1.amazonaws.com endpoint is responding to Node that causes that ECONNRESET to be emitted after the response has been received. The issue is also extremely hard to debug as it happens very rarely (for example, I had to make about 6000 calls to the PutRecordsBatch API just to get that to occur with debug logging on).

Here are the versions of Node and the SDK we have seen this with
* NodeJS 4.3 runtime in AWS Lambda
* AWS-SDK v2.86.0

Here's the full debug log:
> 2017-08-10T11:29:28.455Z Calling PutRecordsBatch with 500 records
> 2017-08-10T11:29:28.735Z HTTP 1: call onSocket 0 0
> 2017-08-10T11:29:28.772Z HTTP 1: createConnection firehose.eu-west-1.amazonaws.com:443:::::::true: { agent: Agent { domain: null, _events: { free: [Function] }, _eventsCount: 1, _maxListeners: 0, defaultPort: 443, protocol: 'https:', options: { rejectUnauthorized: true, path: null }, requests: {}, sockets:
> 2017-08-10T11:29:28.773Z HTTP 1: sockets firehose.eu-west-1.amazonaws.com:443:::::::true: 1
> 2017-08-10T11:29:28.773Z HTTP 1: write ret = false
> 2017-08-10T11:29:28.773Z HTTP 1: outgoing message end.
> 2017-08-10T11:29:31.981Z HTTP 1: AGENT incoming response!
> 2017-08-10T11:29:31.981Z HTTP 1: AGENT isHeadResponse false
> 2017-08-10T11:29:31.981Z HTTP 1: AGENT socket.destroySoon()
> 2017-08-10T11:29:31.995Z HTTP 1: SOCKET ERROR: write ECONNRESET Error: write ECONNRESET at Object.exports._errnoException (util.js:870:11) at exports._exceptionWithHostPort (util.js:893:20) at WriteWrap.afterWrite (net.js:763:14)
> 2017-08-10T11:29:32.012Z HTTP 1: CLIENT socket onClose
> 2017-08-10T11:29:32.012Z HTTP 1: removeSocket firehose.eu-west-1.amazonaws.com:443:::::::true: destroyed: true
> 2017-08-10T11:29:32.012Z HTTP 1: HTTP socket close
> 2017-08-10T11:29:32.013Z HTTP 1: call onSocket 0 0
> 2017-08-10T11:29:32.013Z HTTP 1: createConnection firehose.eu-west-1.amazonaws.com:443:::::::true: { agent: Agent { domain: null, _events: { free: [Function] }, _eventsCount: 1, _maxListeners: 0, defaultPort: 443, protocol: 'https:', options: { rejectUnauthorized: true, path: null }, requests: {}, sockets:
> 2017-08-10T11:29:32.014Z HTTP 1: sockets firehose.eu-west-1.amazonaws.com:443:::::::true: 1
> 2017-08-10T11:29:32.014Z HTTP 1: write ret = false
> 2017-08-10T11:29:32.014Z HTTP 1: outgoing message end.
> 2017-08-10T11:29:32.136Z HTTP 1: call onSocket 0 0
> 2017-08-10T11:29:32.137Z HTTP 1: createConnection firehose.eu-west-1.amazonaws.com:443:::::::true: { agent: Agent { domain: null, _events: { free: [Function] }, _eventsCount: 1, _maxListeners: 0, defaultPort: 443, protocol: 'https:', options: { rejectUnauthorized: true, path: null }, requests: {}, sockets:
> 2017-08-10T11:29:32.138Z HTTP 1: sockets firehose.eu-west-1.amazonaws.com:443:::::::true: 2
> 2017-08-10T11:29:32.152Z HTTP 1: write ret = false
> 2017-08-10T11:29:32.152Z HTTP 1: outgoing message end.
> 2017-08-10T11:29:32.572Z HTTP 1: AGENT incoming response!
> 2017-08-10T11:29:32.572Z HTTP 1: AGENT isHeadResponse false
> 2017-08-10T11:29:32.576Z HTTP 1: AGENT socket keep-alive
> 2017-08-10T11:29:32.577Z Callback called for request with 500 records (first request)
> 2017-08-10T11:29:32.933Z Calling PutRecordsBatch with 250 records (second call)
> 2017-08-10T11:29:33.092Z HTTP 1: call onSocket 0 0
> 2017-08-10T11:29:33.093Z HTTP 1: createConnection firehose.eu-west-1.amazonaws.com:443:::::::true: { agent: Agent { domain: null, _events: { free: [Function] }, _eventsCount: 1, _maxListeners: 0, defaultPort: 443, protocol: 'https:', options: { rejectUnauthorized: true, path: null }, requests: {}, sockets:
> 2017-08-10T11:29:33.094Z HTTP 1: sockets firehose.eu-west-1.amazonaws.com:443:::::::true: 3
> 2017-08-10T11:29:33.094Z HTTP 1: write ret = false
> 2017-08-10T11:29:33.094Z HTTP 1: outgoing message end.
> 2017-08-10T11:29:33.094Z HTTP 1: agent.on(free) firehose.eu-west-1.amazonaws.com:443:::::::true:
> 2017-08-10T11:29:33.094Z HTTP 1: CLIENT socket onClose
> 2017-08-10T11:29:33.094Z HTTP 1: removeSocket firehose.eu-west-1.amazonaws.com:443:::::::true: destroyed: true
> 2017-08-10T11:29:33.094Z HTTP 1: AGENT incoming response!
> 2017-08-10T11:29:33.094Z HTTP 1: AGENT isHeadResponse false
> 2017-08-10T11:29:33.095Z HTTP 1: AGENT socket keep-alive
> 2017-08-10T11:29:33.132Z Callback called for request with 500 records (first request)
> [application crashes due to the callback being triggered for the second time]

As I cannot give out the code we are using in internally as a test case for this bug, I will try to see if I could reproduce this issue with a bit more simpler code and update this issue with the findings there.

[1] https://github.com/aws/aws-sdk-js/blob/master/lib/http/node.js
[2] https://github.com/aws/aws-sdk-js/blob/master/lib/http/node.js#L87-L90
[3] https://github.com/aws/aws-sdk-js/blob/master/lib/http/node.js#L42-L52

**Comment by srchase** [comment]
@sjakthol 

Were you able to sort this our?  Or are you now able to provide some simplified code for reproducing the issue?

**Comment by sjakthol** [comment]
We were not able to produce this reliably and just accepted the fact that we will see bunch of errors like that every once in a while. So I cannot provide any code to reproduce this issue.

**Comment by roman-io** [comment]
I can confirm that something similar is happening in SDK version `2.279.1` with the Kinesis stream `putRecords` function. We are using this function in conjunction with Async module. 5 seconds after receiving a valid callback, it's being called again, and the Async module throws an exception `Error: Callback was already called.`.

**Comment by roman-io** [comment]
Unfortunately no. It's rarely happening, but when it does, it's a global issue in all our applications at the same time. I can only provide when this happened in the past in Oregon region.
```
Wednesday 03 October, 2018 19:30:00 UTC
Sunday 30 September, 2018 10:10:35 UTC
Thursday 20 September, 2018 16:37:53 UTC
Monday 17 September, 2018 18:32:53 UTC
Friday 14 September, 2018 20:43:08 UTC
```

**Comment by srchase** [comment]
@roman-io 

Are you also using Lambda?

Would you be able to capture the request-ids for these failures?  Those request-ids could be used by the Service Team to investigate further.
