### ISSUE TITLE
Signature Does not match after s3.getSignedUrl('putObject', ....

### ISSUE THREAD

**Issue by ChrisGrigg** [aws/aws-sdk-js#1679]
![screen shot 2017-08-10 at 11 33 14 pm](https://user-images.githubusercontent.com/3083238/29221758-cefeed02-7eb7-11e7-865d-25a723203bbf.png)

Hi,

I have a strange issue that happens on Safari 10.1.1 only on one machine.

The error: "Could not upload file: "blah" . Signature Does not Match. The request signature we calculated does not match the signature you provided ..."

First I get a signed URL:

    const AWS = require('aws-sdk');
    AWS.config.region = 'ap-southeast-2';

    const S3_BUCKET = process.env.S3_BUCKET;
    const s3 = new AWS.S3();`
   
    const s3Params = {
        Bucket: S3_BUCKET,
        Key: fileName,
        ContentType: fileType,
        ACL: 'public-read'
    };
    s3.getSignedUrl('putObject', s3Params, (error, data) => {
        if (error) {
            console.error(error);
            return res.status(500).send(error);
        }
        const returnData = {
            signedRequest: data,
            url: `https://${S3_BUCKET}.s3.amazonaws.com/${fileName}`
        };
        console.log('image get: ' + JSON.stringify(returnData));
        res.write(JSON.stringify(returnData));
        res.end();
    });

Then I go an JQuery Ajax put request:

     function putLocalFiles(file, signedRequest, reference, fileName, url, counter, callback) {
        // https://gist.github.com/guumaster/9f18204aca2bd6c71a24
        $.ajax({
            type: 'PUT',
            url: signedRequest,
            // Content type must much with the parameter you signed your URL with
            contentType: file.type,
            // this flag is important, if not set, it will try to send data as a form
            processData: false,
            // the actual file is sent raw
            data: file,
            success: function () {
                addToSupportingDocsURLDO(reference, fileName, url, counter, callback);
            },
            error: function (err) {
                _errorCallback('Could not upload file: ' + url + ' Error: ' + err.responseText);
                // TODO: send support@judgeit.com.au email with error
            }
        });
    }

I'm going to try adding 'signatureVersion: 'v4'' when I test tomorrow but really not 100% on this, any other ideas?

Thanks

**Comment by jeskew** [comment]
Is the system clock synchronized? The current date is included in an AWS signature, so clock skew can sometimes result in invalid signatures. The SDK uses v4 signing by default.

**Comment by ChrisGrigg** [comment]
Thanks for your quick response @jeskew I'm told the system clock is synchronised.

**Comment by nxmohamad** [comment]
In case someone else is looking at this and is in a similar situation as me, I got a similar SignatureDoesNotMatchError when my s3 bucket's CORS Configuration did not contain `    <AllowedHeader>*</AllowedHeader>`

I ran into this when moving from one bucket to another, copying all the settings except for the CORS Configuration.

**Comment by srchase** [comment]
@ChrisGrigg 

This is possible on OSX, so that shouldn't be your issue.  Is this still an open issue?
