### ISSUE TITLE
how to pass commands from node.js to running EC2 instance 

### ISSUE THREAD

**Issue by sajjanhubale** [aws/aws-sdk-js#1680]
We have created virtual sever(ec2 instance) where SAP Application is installed. we want to start/stop sap by passing command/instruction form node.js
Please let me know code to pass the command to ec2 instance form node.js

**Comment by jeskew** [comment]
You would need to SSH into the EC2 instance and then interact with it as you would a physical machine with a shell.

Just FYI: StackOverflow is a better fit for this kind of question, as they have a built in mechanism for sharing the answer you receive with others asking the same or similar questions.
