### ISSUE TITLE
Upload to SQS fails with incorrect error when trying to upload to a bucket that does not exist

### ISSUE THREAD

**Issue by jcollum-cambia** [aws/aws-sdk-js#1681]
I have two buckets: 

`https://internal-msgs-svc-dev-xxxxx.us-west-2.elb.amazonaws.com/yyyy/zzzz` -- dev env (does not exist) (note that this url is totally wrong)

`https://sqs.us-west-2.amazonaws.com/xxxxxx/yyyyyy` - playground env (exists)

I think I copied the wrong url at some point and pasted it in to my config. When my code was trying to upload to it I was seeing a strange error about `self signed certificate` even though `NODE_TLS_REJECT_UNAUTHORIZED` was set to `0` when the app booted up. 

Here's the code: 

```
const AWS = require("aws-sdk");
const config = require("../config");
AWS.config.update(config.aws.enrichment.access);
const sqs = new AWS.SQS({apiVersion: "2012-11-05"});

const message = {hay: "for horses!"};
console.dir({NODE_TLS_REJECT_UNAUTHORIZED: process.env.NODE_TLS_REJECT_UNAUTHORIZED});

const msg = {
  MessageBody: JSON.stringify(message),
  QueueUrl: config.aws.enrichment.queueUrl
};

console.dir(msg);
console.log("Sending message...");
sqs.sendMessage(msg, (err, data) => {
  if (err) {
    console.log("Sending message downstream failed.");
    console.log("Failing message: ", msg.MessageBody);
    console.dir(err);
  } else {
    console.log("Message sent", data);
  }
});
```

Output: 

```
$ NODE_ENV=lab NODE_TLS_REJECT_UNAUTHORIZED=0 node ./etc/sqs-put.js
{ NODE_TLS_REJECT_UNAUTHORIZED: '0' }
{ MessageBody: '{"hay":"for horses!"}',
  QueueUrl: 'https://internal-msgs-svc-dev-xxxxx.us-west-2.elb.amazonaws.com/yyyy/zzzz' }
Sending message...
Sending message downstream failed.
Failing message:  {"hay":"for horses!"}
{ Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
  message: 'self signed certificate',
  code: 'NetworkingError',
  region: 'us-west-2',
  hostname: 'https://internal-msgs-svc-dev-xxxxx.us-west-2.elb.amazonaws.com/yyyy/zzzz',
  retryable: true,
  time: 2017-08-11T23:10:29.861Z }
```

The problem here is that it should have been telling me that I had an invalid url or something but instead it threw a cryptic error about "self signed certificate" while `NODE_TLS_REJECT_UNAUTHORIZED` was set to `0`.

**Comment by AllanFly120** [comment]
Hi @jcollum-cambia 
Unfortunately, this error message is not raised by Javascript SDK. I haven't reproduced your case on my machine but does the error message still exist after you set the `NODE_TLS_REJECT_UNAUTHORIZED `?

**Comment by jcollum-cambia** [comment]
I'm on Windows 10 behind a proxy, if that's relevant. The code above shows me setting `NODE_TLS_REJECT_UNAUTHORIZED` so I don't understand your question. The default for that value is 1, so setting it to 1 wouldn't really do anything.

**Comment by jeskew** [comment]
Hi @jcollum-cambia,

The SDK doesn't set or alter the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable (see https://github.com/aws/aws-sdk-js/search?utf8=%E2%9C%93&q=NODE_TLS_REJECT_UNAUTHORIZED&type= for verification the string doesn't appear in the codebase). Could you check if the variable is being reset or overridden by another library or if it is compatible with the proxy being used?

**Comment by jcollum-cambia** [comment]
>being reset or overridden by another library 

Complete code sample up there. There is no other library. I don't know how you can reproduce this though without having a self-signed cert somewhere in the path from your machine to AWS.

**Comment by jeskew** [comment]
Could you try making a call to the endpoint with a self-signed cert without loading the SDK at all? I can't find anything in the SDK that would affect that environment variable.

**Comment by majgis** [comment]
I was experiencing this issue with the S3 client as well, while using a test server.

I found the issue here:
https://github.com/aws/aws-sdk-js/blob/master/lib/http/node.js#L141

Changing this line
```
AWS.NodeHttpClient.sslAgent = new https.Agent({rejectUnauthorized: true});
```
to 
```
AWS.NodeHttpClient.sslAgent = new https.Agent({rejectUnauthorized: process.env.NODE_TLS_REJECT_UNAUTHORIZED === '0' ? false : true});
```
resulted in the expected behaviour.

**Comment by srchase** [comment]
@jcollum-cambia 

Were you able to get this resolved after @jeskew's last comment?

**Comment by bbeausej** [comment]
Ran into this recently when using the SDK with a small dev minio (compatible S3 storage layer) under a self-signed certificate. 

Submitted #2670 with the fix mentioned in this issue.
