### ISSUE TITLE
Where are the S3 Request ID and Extended Request ID

### ISSUE THREAD

**Issue by kevinbror** [aws/aws-sdk-js#1682]
I was told by amazon support that every s3 response contains a s3 request id and an extended request id. I am logging the full error object returned from s3.upload().send() but do not see it there. Where can I find these ids?

**Comment by AllanFly120** [comment]
I guess you are asking for `x-amz-request-id` and `x-amz-id-2`.  The former one is an HTTP response header entry that created by Amazon S3 to identify requests, and the latter one is also called extended request id which used for the internal debugging purpose. They are shown in the HTTP response headers. You can inspect it using the browser or log the `res.headers` using Node. They are mainly used in the internal trouble shootings. Could you be more specific on the problem you are encountered with?

**Comment by yalamanchili29** [comment]
How do I get the Request Id while reading the property from S3

**Comment by srchase** [comment]
@yalamanchili29 

You can use ```Request``` documented here: [Request](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html)

```
const AWS = require('aws-sdk')
const s3 = new AWS.S3();
const req = s3.listBuckets();

req.on('complete', (response) => {  console.log(response.httpResponse.headers ); })

req.send();
```
