### ISSUE TITLE
Polly is truncating UTF-8 characters when getting speech marks.

### ISSUE THREAD

**Issue by joe1chen** [aws/aws-sdk-js#1683]
I'm using an input with the `”` character (3-byte UTF-8 E2 80 9D) followed by a period.  When calling polly for speech marks json, the response that is returned has truncated the `”` character and is only returning the first byte of the unicode character (E2) and dropping the last 2 bytes (80 9D).

To reproduce:
```
var Polly = new AWS.Polly({
    signatureVersion: 'v4'
});

var params = {
    'Text': "pools”.",
    'OutputFormat': 'json',
    'VoiceId': 'Joanna',
    'SpeechMarkTypes': ['word','sentence']
}

Polly.synthesizeSpeech(params, function (err, data) {
  console.log(data.AudioStream.toString('utf-8'));
}
```

Output:
```
{"time":0,"type":"sentence","start":0,"end":6,"value":"pools�"}
{"time":6,"type":"word","start":0,"end":5,"value":"pools"}
```

The `end` value, which refers to the end position in the UTF-8 byte stream, also show an `end` value of `6` in the `sentence` line, which is incorrect and also indicative that truncation is occurring.

The expected correct output should be:
```
{"time":0,"type":"sentence","start":0,"end":8,"value":"pools”"}
{"time":6,"type":"word","start":0,"end":5,"value":"pools"}
```

**Comment by AllanFly120** [comment]
Hi @joe1chen 
This issue seems like a Service/API issue, which means it does not arise from the SDK. I will forward it to Polly service team to see how we will solve this issue. For now, you can try passing in the readable words only.

**Comment by srchase** [comment]
@joe1chen 

The Polly Service Team made a fix for this quite a while ago.  Closing this issue.
