### ISSUE TITLE
exposing requestId and extendedRequestId in s3 managed uploads

### ISSUE THREAD

**Issue by kevinbror** [aws/aws-sdk-js#1688]
I see this issue talking about the accessibility of s3 request ids https://github.com/aws/aws-sdk-js/issues/781. Have any changes been made to make the request ids available in the case of s3.upload()?

**Comment by AllanFly120** [comment]
Hi @kevinbror,
According to #797, the `requestId` and `extendedRequestId` are now bound to error object of the `s3.upload()` method's callback as well. You can access the value using following code. 
```
bucket.upload(params).send((err, data) => {
    if (err) {
        console.log(err.extendedRequestId);
    }
}
```  
One more thing needs to be noticed is that the extraction of `requestId` and `extendedRequestId` is based on the response headers. So the bucket's CORS config needs to be set to expose these headers. See [this](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html) for more information.

**Comment by kevinbror** [comment]
Thanks for the reply. I had an invalid signature error a few days ago and I add the full error object to my logs. I see requestId there but not the extendedRequestId. Will that not be present in some cases (like auth failure)?

**Comment by AllanFly120** [comment]
Hi @kevinbror,
Many reasons can result in an invalid signature. Do you mind sharing the CORS config of your bucket?

**Comment by kevinbror** [comment]
It's just the sample config: 

<CORSConfiguration>
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>GET</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>Authorization</AllowedHeader>
	</CORSRule>
</CORSConfiguration>
 
But should a signature error still have the extendedRequestId? (regardless of the cause of the signature verification failure)

**Comment by jeskew** [comment]
Hi @kevinbror,

The request ID and extended request ID are both sent to clients as a header. If the bucket's CORS configuration does not expose these headers, then client applications will not be able to access them. The [S3 guide to CORS configuration](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) includes an example that lists the correct headers as exposed:

```xml
<CORSConfiguration>
 <CORSRule>
   <AllowedOrigin>http://www.example.com</AllowedOrigin>
   <AllowedMethod>PUT</AllowedMethod>
   <AllowedMethod>POST</AllowedMethod>
   <AllowedMethod>DELETE</AllowedMethod>
   <AllowedHeader>*</AllowedHeader>
   <MaxAgeSeconds>3000</MaxAgeSeconds>
   <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
   <ExposeHeader>x-amz-request-id</ExposeHeader>
   <ExposeHeader>x-amz-id-2</ExposeHeader>
 </CORSRule>
</CORSConfiguration>
```

**Comment by kevinbror** [comment]
Great thanks!
