### ISSUE TITLE
attachPrincipalPolicy no longer works in browsers

### ISSUE THREAD

**Issue by msl-kabo** [aws/aws-sdk-js#1690]
Using [attachPrincipalPolicy](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Iot.html#attachPrincipalPolicy-property) with aws-sdk version 2.97.0 or higher doesn't work for me. The error in chromium is:

```
XMLHttpRequest cannot load https://iot.us-east-1.amazonaws.com/principal-policies/[policyname]. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.
```

Reading the [Changelog for 2.97.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#2970) I see

> bugfix: REST-JSON serialization: Automatically add a content-type header of application/json to requests with a JSON body

It seems that endpoint needs to update its CORS response or aws-sdk shouldn't add the content-header when calling that endpoint.

**Comment by shinoda-akm** [comment]
Got the same problem :(

**Comment by srchase** [comment]
We've reached out to the IoT Service team to understand why this CORS error is being returned.

**Comment by srchase** [comment]
@msl-kabo 

attachPrincipalPolicy is deprecated.

Do you encounter the same issue if you use [attachPolicy](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Iot.html#attachPolicy-property) instead?
