### ISSUE TITLE
DocumentClient UpdateExpression does not support underscore_ in the name

### ISSUE THREAD

**Issue by Bramzor** [aws/aws-sdk-js#1691]
Apparently UpdateExpression fails when there is an underscore **at the start of** the name.
Example:

    const DynamoDB = require('aws-sdk/clients/dynamodb')

    let docClient = new DynamoDB.DocumentClient()
    let params = {
	    TableName:'Items',
	    Key: { 
		    "_id": "6c773d17-270c-4b29-a185-629e0b90990e"
		    },
	    UpdateExpression: "set _something = :something",
        ExpressionAttributeValues:{
	        ":something": "STRING TEXT"
        },
        ReturnValues:"UPDATED_NEW"
	    }
    
	docClient.update(params, function(err, result) {
      if (err) {
        console.log('function returned error: ' + err + '')
      } else {
	    console.log(result)
      }
    })

Returns error: function returned error: ValidationException: Invalid UpdateExpression: Syntax error; token: "_", near: "set _something"

While for a normal put, there isn't any issue pushing an underscore in front of a name. For example to allow using reserved names like _status.

An underscore at the end however does work. For example: something_

**Comment by AllanFly120** [comment]
Hi @Bramzor 
I think Dynamodb may do server-side validation on the key names and prohibit the those beginning with '_'. But on the other hand, they offer an another way around: you can use `ExpressionAttributeNames` param to replace the name with strings you want. So your params may be like:
```
let params = {
    TableName:'Items',
    Key: { 
	"_id": "6c773d17-270c-4b29-a185-629e0b90990e"
    },
    UpdateExpression: "set #a = :something",
    ExpressionAttributeValues:{
        ":something": "STRING TEXT"
    },
    ExpressionAttributeNames: {
        "#a": "_something"
    },
    ReturnValues:"UPDATED_NEW"
}
```
Dynamodb should better document what they allow in `UpdateExpression` though.

**Comment by jeskew** [comment]
DynamoDB's page on allowable attribute names in expressions indicates that this is expected behavior:

   > You can use any attribute name in a document path, provided that the first character is a-z or A-Z and the second character (if present) is a-z, A-Z, or 0-9. If an attribute name does not meet this requirement, you will need to define an expression attribute name as a placeholder. For more information, see [Expression Attribute Names](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeNames.html).

Using the `ExpressionAttributeNames` field to avoid including reserved words or invalid characters in expressions is the correct resolution.
