### ISSUE TITLE
Does aws sdk js for browser support multipart upload

### ISSUE THREAD

**Issue by Lanceshi2** [aws/aws-sdk-js#1692]
We are serving a customer which has some weird network settings. So we need to have multipart uploading. I am trying to find out whether the aws sdk support this. But I didn't find the related information in the documents. 

May I confirm whether the sdk supports that?

**Comment by chrisradek** [comment]
@Lanceshi2 
Yes, the SDK does support using the multi-part upload in a browser. You can do so by either calling [`s3.upload`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) or using the [`S3.ManagedUpload`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html) class directly.

The managed uploader supports passing in a [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) object as the `Body`. There is an example of that in the developer guide here:
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html#s3-example-photo-album-adding-photos

Note: You may need to update your bucket CORS configuration to support multipart uploads. @AllanFly120 posted an [example configuration](https://github.com/aws/aws-sdk-js/issues/1644#issuecomment-317808677) that will work. Note that `ETag` needs to be exposed to complete a multi-part upload. The `DELETE` method also needs to be allowed to clean up a multi-part upload in case a failure occurs.

**Comment by igormalyk** [comment]
Hi @chrisradek, Thanks for the examples and links to the docs. 

The PhotoAlbum example uses Cognito to configure the SDK. In our application we use presigned URLs from the server to upload files from the Web App to the S3. Does the AWS JS SDK support such case? i.e. I want to give it a file, region and a number of presigned URLs for the chunks for a multipart upload.
