### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by aaroncai08** [aws/aws-sdk-js#1694]
Hi Guys,

When i am trying to use `  event.Records.forEach((record) => {` function 

the following error appeared 
`
TypeError: Cannot read property 'forEach' of undefined

**Comment by chrisradek** [comment]
@aaroncai-myob 
This error indicates that `Records` is not available on the `event` object. Can you verify that it does exist and is an array by logging the event object?

**Comment by aaroncai-myob** [comment]
hi guys. plz close it 👍 found the problem
