### ISSUE TITLE
Adding metadata to object on upload

### ISSUE THREAD

**Issue by seaBass3** [aws/aws-sdk-js#1695]
Hello - I am trying to add metadata to an image on upload using the Javascript SDK but I can't find any documentation on how to do this.  Here is my code that works just fine if I don't include the Metadata in the parameters of the s3.upload:

s3.upload({
               Key: 'tester/asdf.jpg',
               ContentType: 'image/jpeg',
               Body: dataURItoBlob(can.toDataURL('image/jpeg')),
               Metadata: 'x-amz-meta-test,just a test'
           }, function(err, data) {
               if (err) {
                   return alert('Error: ' + err.message);
               }
               alert('Successful upload.');
           });

I get an error that says "Expected params.Metadata to be a map"  but I can't figure what a map structure should look like.  Can anyone help?

**Comment by chrisradek** [comment]
@seaBass3 
When the documentation says `Metadata` needs to be a map, it just means you need to pass in an object where keys and values are strings. It requires a map so you can specify multiple Metadata fields/values.

For example, your `Metadata` could look like:
```javascript
Metadata: {
  'test': 'just a test'
}
```

**Comment by seaBass3** [comment]
I figured it out with the help of AWS support.  The solution is:

Metadata: {'test':'just a test'}
