### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames on getObject/putObject/listObjectsV2

### ISSUE THREAD

**Issue by dkesler** [aws/aws-sdk-js#1696]
Over half the time that I attempt to call getObject, putObject, or listObjectsV2 (i haven't tried other operations yet), I am getting the following error:

error: { Error: Hostname/IP doesn't match certificate's altnames: "Host: <bucketName>.<bucketName>.s3.amazonaws.com. is not in the cert's altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com"

The duplicate <bucketName> in that error is not a typo and seems highly suspicious to me, although I'm not sure whether or not that's the cause, or why that would only happen some of the time.  The bucket is in us-east-1, and I get the error whether or not I specify the region to be us-east-1 explicitly or not when creating the S3 client.

Curiously, the putObject call seems to actually update the object in s3 deterministically, regardless of whether or not I get the error back in the code.

**Comment by chrisradek** [comment]
@dkesler 
Are you able to get any request ids back in the error message? Can you also share what version of node.js you're using?

As a work-around, you can force the SDK to use path style URLs which should mitigate the issue you're seeing:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property

```javascript
var s3 = new AWS.S3({
  s3ForcePathStyle: true
});
```

**Comment by dkesler** [comment]
node version is 7.10.0.
header from the request: 'x-amz-request-id': 'F8F2960C57F5B3D7',

I tried s3ForcePathStyle:true and that does avoid the issue.

**Comment by chrisradek** [comment]
@dkesler 
Thank you for the info.
Can you also share if your bucket name contains any periods or non-alphanumeric characters?

**Comment by dkesler** [comment]
it's all alphanumeric and dashes.

**Comment by srchase** [comment]
@dkesler,

Did you sort out this issue?  Are you seeing consistent behavior between buckets?

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
