### ISSUE TITLE
Having trouble view metadata on folders

### ISSUE THREAD

**Issue by seaBass3** [aws/aws-sdk-js#1697]
Hello - I'm having a problem viewing metadata that the console says was successfully applied.

Here is the metadata I am applying using the console:  x-amz-meta-office: Jacksonville

Here is my CORS config:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>https://emedtrax*</AllowedOrigin>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <ExposeHeader>x-amz-meta-office</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

Can anyone tell me what I'm doing wrong?
Can you use wildcards like this?  <ExposeHeader>x-amz-meta-*</ExposeHeader>

**Comment by chrisradek** [comment]
@seaBass3 
You can't use wildcard characters within the `ExposeHeader` tags.

From what I can tell your configuration looks correct. Below is the CORS configuration I tested with and I was able to see the metadata in the console.

Can you check in the networking tab that you see `x-amz-meta-office` in the `Access-Control-Expose-Headers` header, and that you also see the `x-amz-meta-office` header itself returned in the S3 response?
 
Example Config:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>ETag</ExposeHeader>
    <ExposeHeader>x-amz-meta-one</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

**Comment by seaBass3** [comment]
"Can you check in the networking tab that you see x-amz-meta-office in the Access-Control-Expose-Headers header, and that you also see the x-amz-meta-office header itself returned in the S3 response?"

I not sure what you mean here.  Where's the network tab in the s3 management console?

**Comment by chrisradek** [comment]
I'm sorry, where are you trying to confirm that your metadata is set on an object? I assumed you were testing the SDK in a browser since you posted your CORS configuration. What error are you encountering?

**Comment by seaBass3** [comment]
I am testing in the Javascript SDK but I was also looking for it in the s3 console.  Shouldn't I be able to see the new tag after I've applied it by checking the folder I just applied it to and clicking "more" and "change metadata"?  It doesn't look like it is coming down s3.headObject either.

**Comment by seaBass3** [comment]
I'll be darn, it is coming down with s3.headObject!  Just can't see it in the s3 Management Console.  Weird!

**Comment by chrisradek** [comment]
@seaBass3 
In the new S3 console, you should be able to click on the object, then under `Properties` click on `Metadata` and see the metadata you applied. Note that these are different from `tags`.

Glad to hear you are seeing your metadata using the SDK! I'm closing this issue since the SDK is functioning correctly.
