### ISSUE TITLE
S3 Upload Callback Missed Sometimes

### ISSUE THREAD

**Issue by dumbird** [aws/aws-sdk-js#1699]
We upload a large number of files to S3, and noticed that sometimes the callback passed to the upload request is not called. It seems that a similar bug was filed 2 years ago but was related to a bug of stream handling and now resolved. We're uploading with buffer, so it seems to be a new bug?  When this happens, the progress report callback is still being called multiple times, with loaded bytes same as total bytes in the report, and we can verify that the file has been indeed uploaded. Not sure if it matters, we have server side encryption with KMS enabled. With thousands of files uploaded, there are a few having this issue, all with size around 4M.
This is a sample of related code:
    var params = {
        Key: filename,
        Body: plugin.build_body_text(tranx, email_info),
        ServerSideEncryption: 'aws:kms',
        SSEKMSKeyId: master_key_alias_name
    };
    req = s3.upload(params);
    req.on('httpUploadProgress', function (evt) {
        logger.debug("Uploading file... Status:", evt);
    }
    req.send(function (err, data) {
        logger.debug("S3 sent response:", data);
        if (err) {
            logger.error("Error uploading to S3", err);
        }
    });

**Comment by chrisradek** [comment]
@dumbird 
Can you share which version of the SDK you're using, and which version of node.js?

Do you know if this is happening when you have multiple requests running concurrently, or if it happens even with just one request at a time?

**Comment by dumbird** [comment]
The SDK version is 2.72. Node version is 6.3.0. We only ran the program in cluster mode, and it's handling multiple requests from client at the same time, so there are multiple requests running concurrently. We've been running the same tests for some time, but this problem just showed up yesterday. One possibility is that now there are more files under the same prefix, but the prefix includes some hash, well distributed. There are only fewer than 20 files under the prefixes where upload had issue.

**Comment by dumbird** [comment]
Some update: we encountered another S3 upload failure, but this time we got the callback with an internal error, even though we got the progress report multiple times. In the previous failures, we didn't get the progress report so often, and we had a timer for the uploading process to kill the job once it's beyond 30 seconds. Not sure if we will eventually get a callback if the timer didn't kick in.
This is the related log:

```
2017-08-25 12:18:59.044 DEBUG [16292] [aws_s3] Starting s3 upload; uuid=74D09101-BC33-4AD4-BA9A-20EEC2D1FF99
2017-08-25 12:18:59.058 DEBUG [16292] [aws_s3] Uploading file... Status: { loaded: 222682,
  total: 222682,
  part: 1,
  key: '74D0_2579_2799/74D09101-BC33-4AD4-BA9A-20EEC2D1FF99.1.eml' }
--
2017-08-25 12:18:59.542 DEBUG [16292] [aws_s3] Uploading file... Status: { loaded: 222682,
  total: 222682,
  part: 1,
  key: '74D0_2579_2799/74D09101-BC33-4AD4-BA9A-20EEC2D1FF99.1.eml' }
--
2017-08-25 12:19:00.088 DEBUG [16292] [aws_s3] Uploading file... Status: { loaded: 222682,
  total: 222682,
  part: 1,
  key: '74D0_2579_2799/74D09101-BC33-4AD4-BA9A-20EEC2D1FF99.1.eml' }
--
2017-08-25 12:19:01.279 DEBUG [16292] [aws_s3] Uploading file... Status: { loaded: 222682,
  total: 222682,
  part: 1,
  key: '74D0_2579_2799/74D09101-BC33-4AD4-BA9A-20EEC2D1FF99.1.eml' }
--
2017-08-25 12:19:02.188 DEBUG [16292] [aws_s3] Uploading file... Status: { loaded: 222682,
  total: 222682,
  part: 1,
  key: '74D0_2579_2799/74D09101-BC33-4AD4-BA9A-20EEC2D1FF99.1.eml' }
--
2017-08-25 12:19:02.882 DEBUG [16292] [aws_s3] Uploading file... Status: { loaded: 222682,
  total: 222682,
  part: 1,
  key: '74D0_2579_2799/74D09101-BC33-4AD4-BA9A-20EEC2D1FF99.1.eml' }
--
2017-08-25 12:19:03.747 DEBUG [16292] [aws_s3] Uploading file... Status: { loaded: 222682,
  total: 222682,
  part: 1,
  key: '74D0_2579_2799/74D09101-BC33-4AD4-BA9A-20EEC2D1FF99.1.eml' }
--
2017-08-25 12:19:04.886 DEBUG [16292] [aws_s3] Uploading file... Status: { loaded: 222682,
  total: 222682,
  part: 1,
  key: '74D0_2579_2799/74D09101-BC33-4AD4-BA9A-20EEC2D1FF99.1.eml' }
--
2017-08-25 12:19:02.182 ERROR [16292] [aws_s3] Error uploading to S3 { message: 'We encountered an internal error. Please try again.',
  code: 'InternalError',
  region: null,
  time: '2017-08-25T12:19:02.182Z',
  requestId: 'C1DF69DEABA3751E',
  extendedRequestId: 'EDsKq/IdVsw3J8K9qXK5N0/MyAtq5l8WH4XQ98fCpvePcoc8qVlCdC0Ia2nuppfyV3SPws0llDI=',
  statusCode: 500,
  retryable: true }
```

**Comment by dumbird** [comment]
Any update on this? We're seeing more issues like this. Is there any workaround? We're close to our release date and this would be a major bug for us. Thanks.

**Comment by jeskew** [comment]
@dumbird Have you reached out to S3 support regarding the internal error? That error is not originating in the SDK but is coming directly from S3.

**Comment by dumbird** [comment]
No, we haven't. Because our major concern is the missing callback. If we got the callback with failure  our code will try a secondary region. But thanks for asking, we will check with S3 support.

**Comment by jeskew** [comment]
Were you able to identify any pattern to which requests did not have their callbacks invoked? I'm having trouble reproducing, and a simple repro case would really help identify any underlying issues.

**Comment by dumbird** [comment]
Unfortunately no. With 200k files uploaded, only a few failed. It's not the file itself for sure, because we use a few templates in different size to generate testing files. And the files are evenly distributed in the process, so we don't see any pattern.

**Comment by srchase** [comment]
@dumbird,

Did this issue persist?  Or were you able to track down anything that hints at the cause?

**Comment by dumbird** [comment]
The issue of not getting callback seemed to be caused by we didn't wait long enough (we had a 30 seconds timer), but we're still seeing occasional slow upload (about 0.5% of files uploading took more than 10 seconds, with no large files)

**Comment by srchase** [comment]
As there have been significant updates to the SDK, I'm going to close out this issue.  If you encounter this issue in a reliable way with a recent version of the SDK, let us know and we'll be happy to re-open and take another look.  Thanks!
