### ISSUE TITLE
S3 Multipart upload breaks when using v2.29.0 and above

### ISSUE THREAD

**Issue by lonormaly** [aws/aws-sdk-js#1701]
Hello,

After upgrading from v2.28.0 to v2.29.0 and every version afterwards, the upload process from client just breaks, the upload fails to finish with error code "FileNotValid".
in the "err" console there is "null" for some reason...

`var s3Obj = new AWS.S3({
                httpOptions: {timeout: 300000}, // 5 minutes for each request, default was 2 minutes (120000)
                params: {
                    Bucket: params.bucket
                }
            });`

            // Taken from: https://github.com/aws/aws-sdk-js/issues/399#issuecomment-279812538
            AWS.config.update({
                correctClockSkew: true,
            });

            var s3Params = {
                Key: params.key,
                ACL: params.acl,
                ContentType: file.type,
                Body: file
            };

            // Reference http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property
            var request = s3Obj.upload(s3Params, {leavePartsOnError: true, queueSize: 4}, function(err, data) {
                console.log(err, data);
            });`

**Comment by AllanFly120** [comment]
Hi @lonormaly,
The code snippet you show here looks correct. I'm using sdk 2.77 running on a browser. Does your upload always fail or sometimes success? What is the size of the file you are testing? Does the file name contain any non-English characters?

**Comment by lonormaly** [comment]
Hey, Thanks for answering :)
It fails constantly; Any filesize but tested mostly on files under 5MB; The filename doesn't contain any non-english character.

**Comment by AllanFly120** [comment]
Do you have any other changes with your project? I have some difficulties reproducing your issue only with the code. There may be reasons other than upgrading lead to the issue.
