### ISSUE TITLE
Multipart managed upload Location differs from single part for keys with spaces

### ISSUE THREAD

**Issue by zerojuan** [aws/aws-sdk-js#1707]
Similar to this issue: https://github.com/aws/aws-sdk-js/issues/811, but for spaces in keys.

Multipart:
```Location: 'https://s3.amazonaws.com/bucket/with+space/largeimage.jpg'```

Singlepart:
```Location: 'https://s3.amazonaws.com/bucket/with%20space/largeimage.jpg'```

**Comment by AllanFly120** [comment]
Hi @zerojuan 
This issue arises from 2 different mechanisms that how SDK extract `data.Location`. For multipart upload, the SDK calls `completeMultipartUpload()` [(see here)](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#completeMultipartUpload-property) after all parts get uploaded and the `'/with+space/'` is what s3 server responds. However, for single-part upload, server's response doesn't contain a `Location` field. What the SDK does is concatenating URIEncoded paths into a `Location`.
So in this case, you may URIDecode the `Location` especially when file size is smaller than `partSize` [(see here)](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#constructor-property), which is when using single-part upload.

**Comment by jeskew** [comment]
It looks like either changing single part uploads to match multipart uploads or vice versa would be a change for some users. @zerojuan am I correct in assuming that this is an aesthetic issue rather than a technical one?
