### ISSUE TITLE
TypeScript: generate typescript definitions for aws-sdk-react-native

### ISSUE THREAD

**Issue by itchingpixels** [aws/aws-sdk-js#1709]
Is it / will it be possible to access the TS type definitions for the react-native part of the SDK?

Thank you!

**Comment by jeskew** [comment]
@itchingpixels Which typings in particular are missing? The React Native SDK should have the same level of typescript definition coverage as the standard browser and Node distributables.

**Comment by itchingpixels** [comment]
@jeskew : I can not seem to use the existing ones because of the path we need to use to use the react-native module.

code:
`import * as AWS from 'aws-sdk/dist/aws-sdk-react-native'`

results:
```
app/src/login/helpers.ts(1,22): error TS7016: Could not find a declaration file for module 'aws-sdk/dist/aws-sdk-react-native'. '/Users/mark/Dev/drops-react-native/node_modules/aws-sdk/dist/aws-sdk-react-native.js' implicitly has an 'any' type.
  Try `npm install @types/aws-sdk/dist/aws-sdk-react-native` if it exists or add a new declaration (.d.ts) file containing `declare module 'aws-sdk/dist/aws-sdk-react-native';`
```

**Comment by chrisradek** [comment]
@itchingpixels 
With version `2.83.0` of the SDK, you should be able to import the SDK using `import * as AWS from 'aws-sdk'` instead of going into the `dist` directory.

Can you try importing the SDK as above and test if the typings work then? You will also need `@types/node`, since the SDK types rely on some of the nodejs typings to be present.

**Comment by itchingpixels** [comment]
Great, thank you!

Originally we were using the react-native branch, with https://github.com/AirLabsTeam/react-native-aws-cognito-js.

We're still using react-native-aws-cognito-js, but I switched to using the master branch and to: 
import * as AWS from 'aws-sdk'

I needed to fix some type error, but now getting this runtime error when starting the react-native app

Currently using 2.111.0, and getting this error:
![image](https://user-images.githubusercontent.com/5416288/30228805-99bbc046-94df-11e7-8c86-4f5430ee8e69.png)

**Comment by itchingpixels** [comment]
this can be closed, I can not reproduce this error with the latest version of the lib.
