### ISSUE TITLE
The security token included in the request is invalid. - Lambda - IOT.

### ISSUE THREAD

**Issue by mveera21** [aws/aws-sdk-js#1710]
I have opened ticket at https://github.com/aws/aws-iot-device-sdk-js/issues/146#issuecomment-327696907, but groteworld suggested to open ticket here.

Hi,

We are on AWS IOT, and I've setup everything 3 weeks ago.
It's been working great until yesterday, but it failed today with the following error.

I haven't changed any policies, and no one else has access to my account.

Benefit of doubt, I recreated new policy with Full IOT access and created new Lambda function, but I still get same error.

Error:
2017-09-07T05:43:22.249Z	734caa95-938f-11e7-87af-5350e6ad1d43	{ ForbiddenException: The security token included in the request is invalid.
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request. (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request. (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)

Policies attached to my role:

AWSLambdaBasicExecutionRole-8a08e2cf-887c-4b7b-873e-49a101bb53ec
AmazonDynamoDBFullAccess
AWSLambdaInvocation-DynamoDB
AWSIoTFullAccess
AmazonSNSFullAccess

Could you please help me to understand this issue? I was hoping that AWS IOT is more reliable.

Thank you,

**Comment by mveera21** [comment]
Hi,
Could you please provide solution to our problem? It seems others are hitting the same problem, and it's posted on the below forum. I have lost whole day today to debug this issue.
https://forums.aws.amazon.com/thread.jspa?threadID=263089&tstart=0

Thank you

**Comment by jeskew** [comment]
Hi @mveera21,

Based on the discussion in https://forums.aws.amazon.com/thread.jspa?threadID=263089&tstart=0, it sounds like Lambda is rolling out an update to address the issue.

**Comment by mveera21** [comment]
RyanB@AWS said in the forum "We identified and addressed an issue with treating request headers as case-sensitive that affected some customers' authentication using the Node.js and .NET AWS SDKs in the US West (Oregon) region. The issue was fixed and measures have been put in place to prevent this issue from reoccurring. The duration of this impact was from 9/6 15:45 PST to 9/7 9:45 PST. Thank you for bringing this issue to our attention", so I'm closing this defect. We are evaluating AWS IOT reliability  and scalability to bring it to our product, and I hope we don't hit this kind of outage in the production. 
Thank you for taking care this issue.

**Comment by helderdb** [comment]
I'm getting the issue again with NodeJS (8.10) SDK. I tried invoking the lambda from CLI with the same keys and this works. However the SDK generates: 
```
{"errorMessage":"The security token included in the request is invalid.","errorType":"UnrecognizedClientException","stackTrace":["Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)","Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)","Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)","Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","/var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)"]}
```
