### ISSUE TITLE
Cannot update DynamoDB field if it is named 'state'

### ISSUE THREAD

**Issue by leantide** [aws/aws-sdk-js#1720]
Using AWS.DynamoDB.DocumentClient.update() with a params object, I am able to update my DynamoDB table fields as expected, unless that field is named 'state'. Replacing 'state' with anything else works fine, whether it updates an existing field or creates a new field if it didn't previously exist.

ex. this fails:

params = {
...
UpdateExpression: 'SET state = :state',
ExpressionAttributeValues: {
   ':state': 'update my state value please'
},
...
};

**Comment by chrisradek** [comment]
@leantide 
There is a list of DynamoDB [reserved words](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html) that can't be used as AttributeNames. `state` is one of those.

If you want to continue using `state`, you can define an `ExpressionAttributeName` and use the `#` symbol to prefix `state`.

Example:
```javascript
var params = {
  /** more fields */
  UpdateExpression: 'SET #state = :state',
  ExpressionAttributeValues: {
    ':state': 'update my state value please'
  },
  ExpressionAttributeNames: {
    '#state': 'state'
  }
}
```

**Comment by leantide** [comment]
Thank you. 

Even as a reserved word, I'm surprised I could still create using the 'state' field. The reservedness seems to be only with the update command.

**Comment by jeskew** [comment]
@leantide The list of reserved words only restricts which strings may be used as unescaped attribute names inside of an expression. The only restriction applied to AttributeNames (outside of the context of their direct use in expressions) is that they must be 255 or fewer characters in length. DynamoDB has [a good overview of naming rules and restrictions](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.NamingRules).
