### ISSUE TITLE
correctClockSkew = true does not adjust the time

### ISSUE THREAD

**Issue by CFCSystem** [aws/aws-sdk-js#1723]
Using Release v2.117.0

I'm passing with RequestTimeTooSkewed error.

I already know that the S3 service requires that client clocks and aws do not make a big difference to this is suggested in api:

correctClockSkew = true

This is being done, and I still keep getting the error.

At one time this error only occurred after the requests took more than 15 minutes.

But I found the resolution of the problem in this commit: https://github.com/aws/aws-sdk-js/commit/02f0b8cda3c2113b77ceb6318e284fbe993132e0

Could you check?

My code snippet:

`               let body = fs.createReadStream(this.filePath);
                let conf = new AWS.Config();

                conf.update({
                    accessKeyId: this.credentials.AccessKeyId,
                    secretAccessKey: this.credentials.SecretAccessKey,
                    sessionToken: this.credentials.SessionToken,
                    correctClockSkew: true
                });

                let s3 = new AWS.S3(conf);
                let params = {
                    Body: body,
                    Bucket: this.bucket,
                    Key: this.key,
                };

                this.HandleEvent();

                this.status = "Preparando";

                s3.putObject(params).on('httpUploadProgress', this.Progress.bind(this)).send(function (err, data) {
`

The only way I could solve it was by adding this outline:
```

AWS.events.on('retry', function (response) {
    console.log("AMAZON DATE::", response.httpResponse.headers['date']);
    if (response.error.name === 'RequestTimeTooSkewed') {
        console.error('User time is not correct. Handling error!');
        console.log('AWS systemClockOffset:', AWS.config.systemClockOffset);
        var serverTime = Date.parse(response.httpResponse.headers['date']);
        var timeNow = new Date().getTime();
        console.log('AWS timestamp:', new Date(serverTime));
        console.log('Browser timestamp:', new Date(timeNow));
        AWS.config.systemClockOffset = Math.abs(timeNow - serverTime);
        response.error.retryable = true;
        console.log('Setting systemClockOffset to:', AWS.config.systemClockOffset);
        console.log('Retrying uploading to S3 once more...');
    }
});
`
                 `

**Comment by AllanFly120** [comment]
have you tried [managed upload](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property)? Does this error still exist when using the `upload()`?

**Comment by CFCSystem** [comment]
I am using putObject. Because ?

**Comment by AllanFly120** [comment]
Hi @CFCSystem 

This is a bug introduced from V2.116.0. You can use any older versions. Thank you for revealing this to us! We will be working on fixing this.

**Comment by CFCSystem** [comment]
Thanks for the attention, I'm waiting for a new version!

**Comment by jeskew** [comment]
A fix for this issue was included in https://github.com/aws/aws-sdk-js/commit/3ffe62255d99c09680f519bc40ac5b04b0cb220b, which went out in 2.120.0
