### ISSUE TITLE
How to use the "start-time" parameter in the ec2.describeSnapshots

### ISSUE THREAD

**Issue by viniciuseduardo** [aws/aws-sdk-js#1724]
Hi,

I'm developing an automation script for removing old Snapshots. On some accounts, there are over 10000 snapshots and I'd like to perform a filtering directly on the API call.

I checked in the documentation that there is a parameter called start-time, but in all the attempts none returned me the expected result.

I wonder if there is any specific format for this kind of parameter?

Here is the snippet of code used:
`  var ec2 = new AWS.EC2();

    var params = {
        OwnerIds:[
            "self"
        ],
        Filters:[
            {
                Name: 'start-time',
                Values: [
                    "<2017-08-18T00:00-03:00"//  Retry 01
                    "<2017-08-18T00:00:00.000Z"//  Retry 02
                    "<2017-08-18"//  Retry 03
                    "2017-08-18"//  Retry 04
                ] 
            }
        ]
    };
    
    self.ec2.describeSnapshots(params, function (err, data){
        if(err) console.log(err);
        else console.log(data);
    });`

Thansk for the help.

**Comment by jeskew** [comment]
I believe you will need to specify a filter using the equals operator (`=`) (as discussed in [the EC2 forum](https://forums.aws.amazon.com/message.jspa?messageID=465584)).

Just FYI, StackOverflow is a better forum for this kind of usage question. They have an excellent tagging system and a more targeted search feature, the upshot of which is that questions and answers are more discoverable there than they are in the SDK's issue queue.
