### ISSUE TITLE
Too many network requests  because window.localStorage got full

### ISSUE THREAD

**Issue by pnkjgupta111** [aws/aws-sdk-js#1730]
Used aws sdk in a webview (used inside the javascript of webview) inside android application. 

###Steps to reproduce:
In low bandwidth conditions (so that aws event data cannot be sent):
1) open the app
2) wait for 3 minutes
3) Kill the app
3) Repeat  2 and 3 indefinately ( for about a whole day)

###Issue:

The app got hung. The app will not work unless data of the app is cleared rendering the app useless.

On doing console.log(window.localStorage.AWSMobileAnalyticsStorage.length)  it returned around 52 lakh entries!!! Notably, localStorage size for browsers is  ~5 MB. Hence it got full due to accumulation of aws events.

In console high volume of this error is shown: "Missing credentials in config"

In the nework tab inside chrome it shows thousands of post requests to some awsma url which kept on increasing exponentially. Ultimately forcing the browser to throw net::ERR_INSUFFICIENT_RESOURCES in console together with "Missing credentials in config" errors.

###Reason as per my understanding

Due to localStorage getting full aws sdk is unable to write IdentityId in localStorage hence it repeatedly calls getCredentials which in turn calls getId (self.params.IdentityId is missing) to fetch the IdentityId for each request resulting in such large number of network calls and leading to high contention of browser resources.

**Comment by jeskew** [comment]
Is application where this behavior was observed using the [Amazon Mobile Analytics JavaScript SDK](https://github.com/aws/aws-sdk-mobile-analytics-js)? The SDK for JavaScript does not use the AWSMobileAnalyticsStorage storage key, but [it appears that the library linked to above does](https://github.com/aws/aws-sdk-mobile-analytics-js/search?utf8=%E2%9C%93&q=AWSMobileAnalyticsStorage&type=)

**Comment by pnkjgupta111** [comment]
Yes, the application is using Amazon Mobile Analytics JavaScript SDK.

**Comment by jeskew** [comment]
In that case, I don’t think there’s anything this library could do. Have you opened an issue with the mobile analytics SDK?

**Comment by pnkjgupta111** [comment]
Can you provide me the exact library's link? Thanks in advance

**Comment by pnkjgupta111** [comment]
Thank you :)

**Comment by srchase** [comment]
Closing this issue as it was referred to the mobile analytics repository.
