### ISSUE TITLE
[WARN]: Electron v1.8.0 + aws-sdk = CRASH

### ISSUE THREAD

**Issue by bradennapier** [aws/aws-sdk-js#1731]
Not sure what the cause is as its almost impossible to debug this one... but it would appear that aws-sdk crashes electron v.1.8.0 which is using Chromium v 59.

Not sure specifically waht the aws-sdk may be doing to crash it but all i need to do is "import 'aws-sdk'" and it will crash chrome completely.  Since I can't use chrome when this happens i cant really check the timeline or anything, that all stops working.

![image](https://user-images.githubusercontent.com/15365418/30713342-d4084a60-9ec3-11e7-845e-944888adfc84.png)

```
Time Awake Since Boot: 320000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrRendererMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

Thread 0 Crashed:: CrRendererMain  Dispatch queue: com.apple.main-thread
0   libnode.dylib                 	0x000000010585c050 node::Environment::EnvPromiseHook(v8::PromiseHookType, v8::Local<v8::Promise>, v8::Local<v8::Value>) + 64
1   libnode.dylib                 	0x00000001060495e4 0x105785000 + 9192932
2   ???                           	0x0000102b56c843fd 0 + 17778325603325
3   ???                           	0x0000102b56d068ef 0 + 17778326137071
4   ???                           	0x0000102b56d776fc 0 + 17778326599420
```

**Comment by jeskew** [comment]
Can you share the code that triggers the issue?

**Comment by bradennapier** [comment]
Sure!

```
import AWS from 'aws-sdk'
```

**Comment by jeskew** [comment]
From what I can tell from [the Electron releases page](https://electron.atom.io/releases/) and the [Electron releases published to GitHub](https://github.com/electron/electron/releases), there has not yet been a stable release of 1.8.0 yet, and some instabilities and crashes are to be expected. Have you observed any crashes with a 1.6.x or 1.7.x release? Does the crash occur with [the latest release in the 1.8.x series (1.8.2-beta.1)](https://github.com/electron/electron/releases/tag/v1.8.2-beta.1), and, if so, have you logged an issue with the electron team?

**Comment by srchase** [comment]
@bradennapier 

Is this still an issue for you?  Did you see these crashes on a stable release of Electron?

If it's not, I'd like to close out this issue.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if there is any followup needed.
