### ISSUE TITLE
DynamoDB Accelerator (DAX) with AWS Javascript SDK

### ISSUE THREAD

**Issue by mooyoul** [aws/aws-sdk-js#1734]
Currently, it seems only Java SDK supports DynamoDB query that uses DAX, and There're no way to query dynamodb with DAX on Javascript SDK.

We're making huge amount of DynamoDB queries from bunch of Node.js Lambda runtime based Lambda functions. but sadly, we cannot make query with DAX even purchased DAX Clusters, due to missing DAX support on aws-js-sdk.

It would be nice if aws-js-sdk supports DynamoDB query with DAX 😉

**Comment by adjourn** [comment]
[From What's New:](https://aws.amazon.com/about-aws/whats-new/2017/10/amazon-dynamodb-accelerator-dax-releases-sdk-for-node-js-support-for-r4-instances-and-general-availability-in-asia-pacific-mumbai-and-south-america-sao-paulo-regions/)


> Posted On: Oct 5, 2017
> 
> Amazon DynamoDB Accelerator (DAX), today announced the release of the following:
> * SDK for Node.js.
>
> ...

I didn't find anything in [SDK documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html) nor [SDK changelog](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md). Documentation has [DAX section/constructor](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DAX.html) but it's only for administrative tasks.

Then I found [this guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.run-application-nodejs.html) and [this page](http://dax-sdk.s3-website-us-west-2.amazonaws.com/).

It's a separate package. Just out of curiosity, why it's separate package?

**Comment by jeskew** [comment]
Hi @adjourn,

The DAX SDK for Node.JS does not run in browsers or in some end-of-life versions of Node supported by the AWS SDK for JavaScript.

Closing, as the DAX SDK for Node.JS is [now available via NPM](https://www.npmjs.com/package/amazon-dax-client).
