### ISSUE TITLE
Is Typescript CloudWatch Dimension's definition invalid?

### ISSUE THREAD

**Issue by uzimith** [aws/aws-sdk-js#1735]
https://github.com/aws/aws-sdk-js/blob/master/clients/cloudwatch.d.ts#L376

Dimension's fields is capitalized.

```
  export interface Dimension {
    /**
     * The name of the dimension.
     */
    Name: DimensionName;
    /**
     * The value representing the dimension measurement.
     */
    Value: DimensionValue;
  }
```

However I got  lowercase letters (in the case of CloudWatch -> SNS -> Lambda).

```
"Dimensions":[{"name":"InstanceId","value":"i-hoge"},{"name":"FilePath","value":"/hoge/hoge"}]
```

I guess this definition is invalid, is it right?

**Comment by AllanFly120** [comment]
Hi @uzimith 
The type definitions are generated from [the API model](https://github.com/aws/aws-sdk-js/blob/8673931835a178a131e4f8ffe841e61369ad9e64/apis/monitoring-2010-08-01.normal.json#L601), usually it should be Uppercased. Can you tell me more about this issue? Are you using it on Node? which SDK version are you using? Which function are you calling?

**Comment by uzimith** [comment]
I used `aws-sdk@2.121.0`.

In AWS Lambda with Node, I want to define Message interface by aws-sdk types.

```
import { MetricName, Namespace, Statistic, Dimensions, Period, StandardUnit, EvaluationPeriods, Threshold, ComparisonOperator, TreatMissingData, EvaluateLowSampleCountPercentile } from 'aws-sdk/clients/cloudwatch';

interface Message {
    AlarmName: string;
    AlarmDescription: string | null;
    AWSAccountId: string;
    NewStateValue: string;
    OldStateValue: string;
    NewStateReason: string;
    StateChangeTime: string;
    Region: string;
    Trigger: Trigger;
}

interface Trigger {
    MetricName?: MetricName;
    Namespace?: Namespace;
    Statistic?: Statistic;
    StatisticType?: string;
    Dimensions?: Dimensions;
    Period?: Period;
    Unit?: StandardUnit;
    EvaluationPeriods?: EvaluationPeriods;
    Threshold?: Threshold;
    ComparisonOperator?: ComparisonOperator;
    TreatMissingData?: TreatMissingData;
    EvaluateLowSampleCountPercentile?: EvaluateLowSampleCountPercentile;
}

export function handler(event: any, context: any) {
    const message: Message = JSON.parse(event.Records[0].Sns.Message);
    // some codes.
}
```

However, when I trigger this lambda by SNS from CloudWatch status change action, this SNS Record is like below code.

```
{
  "Type": "Notification",
  "MessageId": "uuid",
  "TopicArn": "arn:aws:sns:ap-northeast-1:...",
  "Subject": "OK: \"...\" in Asia Pacific (Tokyo)",
  "Message": "{\"AlarmName\":\"...\",\"AlarmDescription\":null,\"AWSAccountId\":\"...\",\"NewStateValue\":\"OK\",\"NewStateReason\":\"...\",\"StateChangeTime\":\"2017-10-02T18:50:03.901+0000\",\"Region\":\"Asia Pacific (Tokyo)\",\"OldStateValue\":\"INSUFFICIENT_DATA\",\"Trigger\":{\"MetricName\":\"HTTPCode_ELB_5XX\",\"Namespace\":\"AWS/ELB\",\"StatisticType\":\"Statistic\",\"Statistic\":\"SUM\",\"Unit\":null,\"Dimensions\":[{\"name\":\"LoadBalancerName\",\"value\":\"...\"}],\"Period\":000,\"EvaluationPeriods\":0,\"ComparisonOperator\":\"GreaterThanOrEqualToThreshold\",\"Threshold\":000.0,\"TreatMissingData\":\"\",\"EvaluateLowSampleCountPercentile\":\"\"}}",
  "Timestamp": "2017-10-02T18:50:04.011Z",
  "SignatureVersion": "1",
  "Signature": "...",
  "SigningCertUrl": "....pem",
  "UnsubscribeUrl": "...",
  "MessageAttributes": {}
}
```

So I thought dimension's actual type is interface `{name: string; value: string}`.

**Comment by jeskew** [comment]
Based on your findings, @uzimith, I would say that the typings shipped with the SDK are not directly compatible with the structure of events as passed to lambda functions. They are, however, correct with regards to the CloudWatch APIs, which is what our SDK must keep accurate typings for. I would recommend raising an issue on the [AWS Developer Forum for CloudWatch](https://forums.aws.amazon.com/forum.jspa?forumID=138), the [AWS Developer Forum for Lambda](https://forums.aws.amazon.com/forum.jspa?forumID=186), and/or the [AWS Developer Form for SNS](https://forums.aws.amazon.com/forum.jspa?forumID=72), but this doesn't look like something we could accommodate in the SDK's type definitions.

Please feel free to reopen or continue the discussion if you have any questions or concerns.
