### ISSUE TITLE
Upgrade uuid to version 3.1.0

### ISSUE THREAD

**Issue by B3ll89** [aws/aws-sdk-js#1737]
Will it be possible to upgrade `uuid` to 3.1.0?
It has been out for quite a while now and I'm now aware of any *actual* changes.

**Comment by chrisradek** [comment]
The uuid dependency has been updated and is merged into master. The next version of the SDK will include this change.

3.1.0 did not include any code changes, just documentation. Did you need it upgraded to avoid duplicate copies, or some other reason?

**Comment by B3ll89** [comment]
It is indeed a duplication issue.

Thank you very much!
