### ISSUE TITLE
How can i get object from s3 presigned url

### ISSUE THREAD

**Issue by sastrygunnu** [aws/aws-sdk-js#1741]
Hi, is there any way to get object from presigned url?  

and can i make multiple requests for same presigned url to get entire objects from given bucket?

  var s3 = new AWS.S3();
                    var params = {
                        Bucket: "build001",
                        Expires: 20,
                        Key: ''
                    };
                    
            var url = s3.getSignedUrl('getObject', params);

**Comment by chrisradek** [comment]
@sastrygunnu 
I'm not sure what you're asking for. Are you trying to make presigned urls for multiple objects in a bucket?

**Comment by sastrygunnu** [comment]
I`m able to generate the pre-signed URL for my bucket, i made HTTP request to get my object from the call but its returns (1000 object per call) and its returns XML data.
My question is that  how to make another call and find next set of objects from the same url and update my array? i m unable use s3 methods to get entire object from my bucket  something like 
below
 s3.listObjects(params).
                on('success', function handlePage(r) {
                    
                    if (r.hasNextPage()) {
                        r.nextPage().on('success', handlePage).send();
                        getdata(r.data.Contents)

                    }else{
getdata(r.data.Contents)
}

is there any other way around to get full object from pre-signed url using multiple http requests. 
i have to use pre-signed url to get access to entire object for given bucket.
can you help?

**Comment by jeskew** [comment]
You would need a different pre-signed URL for each page of results. Each request for a page following the first will include a "NextMarker" parameter that is part of the URL that gets signed.

**Comment by srchase** [comment]
@sastrygunnu,

Did this get things working for you? I'm going to close out this issue as it looks like you've got more of a usage question.

**Comment by sastrygunnu** [comment]
Yep it's working thanks you can close this now
