### ISSUE TITLE
S3.getSignedUrl params argument lack TypeScript type

### ISSUE THREAD

**Issue by zommarin** [aws/aws-sdk-js#1742]
In `lib/services/s3.d.ts` the `getSignedUrl()` is defined as:

    getSignedUrl(operation: string, params: any, callback: (err: Error, url: string) => void): void;

And as the `params` parameter is of type any there will be no type checks or autocompletion when accessing the library from TypeScript. It should have a type like other function (probably named `S3.GetSignedUrlRequest`)

**Comment by waelsy123** [comment]
any updates in here?

**Comment by garysb** [comment]
Thanks @ajredniwja , been waiting for this...

**Comment by ajredniwja** [comment]
> Thanks @ajredniwja , been waiting for this...

Sorry for the long wait, this was updated because the team wanted to work on this feature request but not sure about the priority. Additionally we'd welcome any PRs if anyone from the community wants to work on it.

**Comment by jmoliugp** [comment]
Are there any updates on this?
