### ISSUE TITLE
Accessing S3 Bucket on SnowballEdge

### ISSUE THREAD

**Issue by kent-williams** [aws/aws-sdk-js#1744]
Unable to call s3 methods that require bucket name because Snowball does not expose an endpoint in the virtual host format like this 'bucketname.192.168.128.114', but instead like this '192.168.128.114' without the bucket name prefixed as the host name. 

Using node v6.11.0

Error output on listObjects call:
"Error: getaddrinfo ENOTFOUND bucketname.192.168.128.114 bucketname.192.168.128.114:8080
       at errnoException (dns.js:28:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     message: 'getaddrinfo ENOTFOUND bucketname.192.168.128.114 bucketname.192.168.128.114:8080',
     code: 'NetworkingError',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'bucketname.192.168.128.114',
     host: 'bucketname.192.168.128.114',
     port: 8080,
     region: 'us-east-1',
     retryable: true,
     time: 2017-10-05T18:34:36.988Z"

I have tried using the AWS.Endpoint object to specify the endpoint, but in every case the bucket name is still prefixed before the host.

Am I missing an option to construct the endpoint without this, or is this not currently supported by the SDK?

Thanks!

**Comment by jeskew** [comment]
When creating the S3 client, you can direct the client not to use the bucket name in the URL by setting `s3ForcePathStyle` to `true`. However, the SDK should probably automatically detect when an IP address is used and set `s3ForcePathStyle` automatically.

**Comment by kent-williams** [comment]
Thank you @jeskew! I knew I was probably missing something.

Appreciate the help!
