### ISSUE TITLE
aws-sdk crashes nodejs program

### ISSUE THREAD

**Issue by shreya-work** [aws/aws-sdk-js#1745]
I am using aws-sdk for javascript.
node v 6.10

The code below works fine when using in a stand-alone program

//program.js
```
const AWS = require('aws-sdk');
const firehose = new AWS.Firehose({
   accessKeyId: "XXX",
  secretAccessKey: "YY"
});

const params = {
  DeliveryStreamName: 'demo1',
  Record: {
    Data: new Buffer("Hello World")
  }
};

firehose.putRecord(params, function (err, data){
  if (err) {
    console.log(err);
    return;
  }
  console.log(data);           // successful response
});
```
Again, the above code works fine as a stand alone file. Data gets pushed into firehose and then further down to Redshift. 
so if i execute 
`node program.js`

I am able to see my data in Redshift. Yay!!

----------------

However, what i really want to achieve is to push data to firehose when a certain route gets hit in my express application. So I take the exact same code as above and stick it in my route 

```
const AWS = require('aws-sdk');
const firehose = new AWS.Firehose({
   accessKeyId: "XXX",
  secretAccessKey: "YY"
});

router
  .get('/v1/locations/:id?', (req, res) => {

   const params = {
     DeliveryStreamName: 'demo1',
     Record: {
        Data: new Buffer("Hello World")
     }
   };

    firehose.putRecord(params, function (err, data){
     if (err) {
       console.log(err);
       return;
     }
      console.log(data);           
      
    });
 // do the necessary work for this route and then send response to client
// this work has nothing to do with firehose
 res.send("some response");  
  });
```

The minute  firehose.putRecord is executed .. it crashes my program with the following error:

```
TypeError: doneCallback.cal is not a function
    at Request.callListeners (/api-project/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/api-project/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /api-project/node_modules/aws-sdk/lib/event_listeners.js:74:9
    at finish (/api-project/node_modules/aws-sdk/lib/config.js:315:7)
    at /api-project/node_modules/aws-sdk/lib/config.js:333:9
    at Credentials.get (/api-project/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/api-project/node_modules/aws-sdk/lib/config.js:327:24)
    at Config.getCredentials (/api-project/node_modules/aws-sdk/lib/config.js:347:9)
    at Request.VALIDATE_CREDENTIALS (/api-project/node_modules/aws-sdk/lib/event_listeners.js:69:26)
    at Request.callListeners (/api-project/node_modules/aws-sdk/lib/sequential_executor.js:101:18)

```
I can't understand why this code crashes my express program. is this is bug in the aws-sdk library or am i doing something wrong ?

**Comment by jeskew** [comment]
Can you take a peek at the line mentioned in the top line of the stack trace inside of the project's `node_modules` folder (`/api-project/node_modules/aws-sdk/lib/sequential_executor.js:115`)? That line [should read `doneCallback.call(self, error);`](https://github.com/aws/aws-sdk-js/blob/master/lib/sequential_executor.js#L115), but the error reported indicates that the file as downloaded to disk is missing a character (`doneCallback.cal` is invoked instead of `doneCallback.call`).

**Comment by shreya-work** [comment]
That fixed the problem.

**Comment by jeskew** [comment]
Closing, as I can't find a version of the SDK we've shipped in which `doneCallback.cal` was invoked. Please reopen or comment if you encounter this issue again.
