### ISSUE TITLE
Putobject() and upload() both uploading partial 'binary' encoded data in Object Store with data over 4MB

### ISSUE THREAD

**Issue by ssshah5** [aws/aws-sdk-js#1747]
I have been using the aws-sdk node module the following way and have been seeing issues for data uploads larger than 4MB

The data is binary and is stored in a variable.

```
var AWS = require('aws-sdk');
var crypto = require('crypto');

var configOptionsAws =
  new AWS.Config({
    accessKeyId: config.s3AccessKeyId,
    secretAccessKey: config.s3SecretAccessKey,
    region: config.s3Region,
    endpoint: config.s3Endpoint,
    sslEnabled: true,
    s3ForcePathStyle: true
});

AWS.config.update(configOptionsAws);
var clientS3 = new AWS.S3();

var hash = crypto.createHash('sha256');
var iv = hash.digest('hex').substr(0, 16);
var cipher = crypto.createCipheriv('aes-256-ctr', cipherKey, iv);
var log = options.content;
var encryptedLog = cipher.update(log, 'utf8', 'binary');
encryptedLog += cipher.final('binary');
options.content = encryptedLog;


var params = {Bucket: s3LogsBucketName, Key: options.container + '/' + options.name, Body: options.content};
 clientS3.putObject(params, function (err, data) {
      if (err) {
           logger.error("failed to upload file", err);
           return reject(err);
       } else {
           console.log(data);
           return resolve();
       }
});
```

Its working fine if I don't encrypt the data and send it as plain text. However, for encrypted data, I can consistently reproduce the issue where the last part/text of the data is not getting uploaded and is truncated. The file size for encrypted data (truncated) on S3 object-storage is roughly around 3.4MB

For smaller encrypted data, it works fine and uploads the complete data to the Object Store.  No errors are reported but when I open the file on Object Storage, it has missing data at the end. This behavior is consistent.

I also tried using clientS3.upload() and have been having the same issue there. Any suggestions?

**Comment by ssshah5** [comment]
## UPDATE

It worked for large files when I use "hex" instead of `binary` as follows in the above code.

```
var encryptedLog = cipher.update(log, 'utf8', 'hex');
encryptedLog += cipher.final('hex');

```
However, I want it to work with Binary as I need to be backward compatible with the files that are already encrypted using binary.

**Comment by jeskew** [comment]
Since the encryption is happening before the value is passed to the SDK, my hunch is that the ciphertext cannot be accurately represented by the `latin1` character set (Node's `binary` encoding target [is just an alias for `latin1`](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings)). If you want to send the raw bytes of the ciphertext, could you try using a buffer?

**Comment by ssshah5** [comment]
Hello @jeskew , I tried the following but having the same issue. The same code works fine against Swift Object Storage. Any Suggestions to try out the buffer differently? 

```
const buf = Buffer.from(options.content);
var params = {Bucket: s3LogsBucketName, Key: options.container + '/' + options.name, Body: buf};
```

**Comment by jeskew** [comment]
Can you tell me a bit more about `options.content`? (Is it a stream? A string? A buffer?) Since the encryption is happening before the data is passed to the SDK, I don't believe there's an issue in `putObject`.

**Comment by ssshah5** [comment]
@jeskew - Yes `options.content` is a string. We get the data from the DB and encode it in binary using following code before calling the putObject.
```
var log = options.content;
var encryptedLog = cipher.update(log, 'utf8', 'binary');
encryptedLog += cipher.final('binary');
```
The putObject() doesn't have issues if I use `base64` or `hex` for encoding. However I see the issue with `binary` encoding an that too only with file size larger than 3.5 MB.

**Comment by jeskew** [comment]
I'm unable to reproduce any error when operating directly on binary data (i.e., `Buffer` objects). This is the script I'm using to try to reproduce the error:

```javascript
const assert = require('assert');
const Buffer = require('buffer').Buffer;
const crypto = require('crypto');
const AWS = require('aws-sdk');

const plaintext = crypto.randomBytes(4 * 1024 * 1024 + 1);
const iv = crypto.randomBytes(16);
const key = crypto.randomBytes(32);
const cipher = crypto.createCipheriv('aes-256-ctr', key, iv);

let ciphertext = cipher.update(plaintext);
ciphertext = Buffer.concat([ciphertext, cipher.final()]);

assert.strictEqual(ciphertext.byteLength, plaintext.byteLength);

const Bucket = '3f929dc0-997b-4fde-a4e5-7e83b453aa60';
const Key = 'encrypted.ext';
const s3 = new AWS.S3({region: 'us-west-2'});
s3.putObject({Bucket, Key, Body: ciphertext}).promise().then(() => {
  console.log('upload complete!');
  s3.getObject({Bucket, Key}).promise().then(result => {
    console.log('download complete!');
    assert.ok(result.Body.equals(ciphertext));
    console.log('ciphertext not corrupted');

    const decipher = crypto.createDecipheriv('aes-256-ctr', key, iv);
    let decrypted = decipher.update(result.Body);
    decrypted = Buffer.concat([decrypted, decipher.final()]);
    assert.ok(decrypted.equals(plaintext));
    console.log('plaintext successfully recovered');
  });
});
```

If, however, I attempt to use `latin1` text encoding via its alias, `'binary'`, then I am unable to decrypt the ciphertext even before it is sent to S3. I believe I'm running into the same issue you describe by running the following script:

```javascript
const assert = require('assert');
const Buffer = require('buffer').Buffer;
const crypto = require('crypto');

const plaintext = crypto.randomBytes(4 * 1024 * 1024 + 1);
const iv = crypto.randomBytes(16);
const key = crypto.randomBytes(32);
const cipher = crypto.createCipheriv('aes-256-ctr', key, iv);

let ciphertext = cipher.update(plaintext, 'binary');
ciphertext += cipher.final('binary');

const decipher = crypto.createDecipheriv('aes-256-ctr', key, iv);
let decrypted = decipher.update(ciphertext, 'binary');
decrypted = Buffer.concat([decrypted, decipher.final()]);
assert.ok(decrypted.equals(plaintext));
```

Based on these test cases, I do not believe there is any issue in the `PutObject` operation. Instead, I believe you are seeing the result of encoding errors that can be reproduced without using S3 or the AWS SDK.

**Comment by ashrafmangalore** [comment]
@jeskew can you show me one example to upload the image.. image is coming in `base64` format from fron-end so how to mention `body` and `key`. can you show me one example in node.js.

**Comment by ssshah5** [comment]
@jeskew - Thanks for sharing the code. I finally solved the issue by changing the encoding. Appreciate your time and response. Thank you.
