### ISSUE TITLE
Don't include compiled dist and create seperate package for react native

### ISSUE THREAD

**Issue by kevinsimper** [aws/aws-sdk-js#1748]
I am using the `aws-sdk` in my `aws lambda` functions and right now the biggest file in my bundle is the 
```
3.2 MB node_modules/aws-sdk/dist/aws-sdk-react-native.js
3.1 MB node_modules/aws-sdk/dist/aws-sdk.js
```

those two files i 50% of my bundled zip

I think it would help a lot on many people bundle sizes if the `aws-sdk` did not include the precompile bundles and did not also include the one for the react-native project.

I can bundle my project to avoid the whole `node_modules` folder but that is something only for advance users and even complicated with native modules like `fs` and `net` which requires special config.

I hope it makes sense and thanks for the awesome sdk!

**Comment by jeskew** [comment]
That sounds reasonable, but I'm not sure how removing the `dist/*` files could be done in a backwards-compatible way.

**Comment by kevinsimper** [comment]
@jeskew We could publish a new version of `aws-sdk` called something like minimal or bare or es6 or slim? or `aws-sdk-node`?

**Comment by jeskew** [comment]
That is a possibility, but we would need to formulate a good long-term plan for keeping the two packages in sync. `aws-sdk-node` would essentially be the maintenance overhead of a new major version.

**Comment by CoreyAR** [comment]
I'm getting a timeout error when building react-native locally because of the file size. 

```
TimeoutError: transforming  .../node_modules/aws-sdk/dist/aws-sdk-react-native.js took longer than 601 seconds.
```

**Comment by chrisradek** [comment]
@CoreyAR 
If you try to use the SDK without importing the aws-sdk-react-native file directly, do you still see this issue?

Can you also share what version of React Native you're if the above doesn't work? We made some changes so that you shouldn't need to import the dist file anymore, but I haven't run into this issue when testing locally so not 100% sure the above will fix the issue for you.

**Comment by CoreyAR** [comment]
I tried importing with `import AWS from 'aws-sdk'` and still got the error. We are on react-native 
 version 0.51.0

**Comment by Janardhanrao** [comment]
@CoreyAR 
Any Update on this issue?

Thanks in advance

**Comment by rekha110254** [comment]
@CoreyAR 

Thanks for the reply it is working now

**Comment by ajredniwja** [comment]
Closing this issue for now, please reach out if you still continue to see this problem with the latest version of the SDK.

**Comment by kevinsimper** [comment]
@ajredniwja Why did you close this issue? It doesn't look like it has been solved?

**Comment by kevinsimper** [comment]
```
$ ls -lh node_modules/aws-sdk/dist
total 13M
-rw-rw-r-- 1 app app 398K Oct 26  1985 aws-sdk-core-react-native.js
-rw-rw-r-- 1 app app 4.7M Oct 26  1985 aws-sdk.js
-rw-rw-r-- 1 app app 2.2M Oct 26  1985 aws-sdk.min.js
-rw-rw-r-- 1 app app 5.3M Oct 26  1985 aws-sdk-react-native.js
-rw-rw-r-- 1 app app 4.6K Oct 26  1985 BUNDLE_LICENSE.txt
-rw-rw-r-- 1 app app 517K Oct 26  1985 xml2js.js
```
