### ISSUE TITLE
The receipt handle has expired

### ISSUE THREAD

**Issue by keviin55** [aws/aws-sdk-js#1750]
I switched to a FIFO queue and I got this error message when I tried to delete a message from the queue.

`Value {VALUE} for parameter ReceiptHandle is invalid. Reason: The receipt handle has expired.`

It appears that the error happens because I tried to delete the message after visibility timeout has expired. I changed the default visibility timeout 0 to the maximum, 12 hours, this solved partially the issue. Sometimes it could happens that a message still in my queue for longer than 12 hours before I could perform it and than delete it, so I will get the error again. Is there any solution to increase the visibility timeout for more than 12 hours or to bypass this error by another way?

**Comment by jeskew** [comment]
FIFO queues will reject `DeleteMessage` requests when the receipt handle is expired, which means that handles with a `VisibilityTimeout` of 0 cannot be deleted. Please see [here](https://github.com/aws/aws-sdk-js/issues/1279#issuecomment-268830676) for more discussion of this.

My understanding from [the SQS developer guide](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibility.html) is that 12 hours is the longest possible message timeout allowed by SQS. If the visibility timeout has elapsed, then the message may have been delivered to and acted on by another recipient.

**Comment by keviin55** [comment]
and the other recipient will never be able to delete the message too? I still don't get it. I can keep a message in the queue for more than 12 hours, but when I process it after the 12 hours, I can never delete it again?

**Comment by jeskew** [comment]
The other recipient would be able to delete the message up to 12 hours after they received it. `VisibilityTimeout` only refers to the lifetime of the receipt handle (i.e., the duration for which the message should be considered ["in flight"](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html#sqs-inflight-messages) and not sent in response to other `ReceiveMessage` operations). In addition, each queue has a maximum retention period -- the amount of time messages should be allowed to remain in the queue. By default, all queues have a maximum retention period of four days, though this can be configured to any duration between one minute and fourteen days. The queue's retention period is not related to any given receipt handle's visibility timeout.

The SQS Developer Guide contains a [brief guide to message lifecycles](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-lifecycle.html) that probably explains this better.

**Comment by keviin55** [comment]
Thank you for the explanation
