### ISSUE TITLE
Environment variable naming inconsistency for credentials  between SDK and ElasticBeanstalk.

### ISSUE THREAD

**Issue by mattbryson** [aws/aws-sdk-js#1751]
This is not a bug as such, but an inconsistency with Elastic Beanstalk Environments, that causes the SDK to authenticate with the wrong credentials.

The JS SDK, by default looks for  `AWS_SECRET_ACCESS_KEY`.  The prefix can be changed, but the suffix is `SECRET_ACCESS_KEY`. 
https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/environment_credentials.js#L70

However, The Elastic Beanstalk console pushes you to use `AWS_ACCESS_KEY` instead.
<img width="805" alt="screen shot 2017-10-06 at 18 05 45" src="https://user-images.githubusercontent.com/548948/31346791-2dd740b2-ad12-11e7-9d62-b83d6a35652a.png">

Im not sure which one AWS is pushing as correct, but maybe the SDK should support both? Or at least log out / warn about failed providers in the credentials provider chain? 

When running the SDK on a EB instance, it fails to find valid ENV credentials  (due to naming inconsistency), so it fails over to use the EB instance role creds - which the chances are, don't have rights to access to any of your AWS resources.

Its very confusing as according to the EB console it has valid ENV vars, but the SDK ends up using a completely different set of credentials - with no warnings in the log file - and then things like access S3 or sending emails fails.

**Comment by jeskew** [comment]
I’ll reach out to the ElasticBeanstalk team to get the inconsistency addressed.

**Comment by jeskew** [comment]
I heard back from someone on the Elastic Beanstalk team, and the properties listed should not appear on the console listed for platforms released in the last 2-3 years. Which platform is the application you saw this console for running on?

**Comment by mattbryson** [comment]
This does happen to be on an older platform from a few years back (we were making an update to a legacy app).

But the same property name is used on all the other EB environments that we have. The newest one we have running is..

64bit Amazon Linux 2016.09 v2.3.0 

Which I assume is September 2016, so only just over a year old.  Maybe this change has been made more recently than reported?  Ill spin up a 2017 and see.

**Comment by mattbryson** [comment]
I just span up a 

64bit Amazon Linux 2017.03 v2.5.0

And it has the same issue..

![screen shot 2017-10-10 at 12 38 30](https://user-images.githubusercontent.com/548948/31384747-2d73c298-adb8-11e7-906b-742086978b56.png)

Maybe they changed *from* `AWS_SECRET_ACCESS_KEY` to `AWS_SECRET_KEY ` 2-3 years ago :)

**Comment by jeskew** [comment]
The response I received from Elastic Beanstalk is this:

> AWS_SECRET_KEY and AWS_ACCESS_KEY_ID are deprecated on AWS Elastic Beanstalk platforms. You won't find those environment variables by default on any platform published in the last 2-3 years. 
>
> It's not recommended that customers continue to use those variables to establish their AWS credentials on an EC2 host in an Elastic Beanstalk environment.

Since the `AWS_SECRET_KEY` environment variable is considered a legacy feature by Elastic Beanstalk, I don't think there's a compelling reason to add support for it to the AWS SDK.

The Elastic Beanstalk team now recommends using [IAM roles](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts-roles.html) to provide credentials to your application.
