### ISSUE TITLE
Facebook Login Integration

### ISSUE THREAD

**Issue by MatheusParanhos** [aws/aws-sdk-js#1752]
Hello everyone, I'd like to make a question and feature request regarding Facebook Login.
How would one proceed to using the token that facebook gives you  #to use that to create a cognito user. I couldn't find any documentation for that in react-native. Any thoughts on how to proceed from here?

**Comment by jeskew** [comment]
Hi @MatheusParanhos,

The documentation you're looking for can be found [here](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity.html). The SDK supports React Native, so you would be able to use `AWS.CognitoIdentity` to interact with the AWS Cognito Identity service in the same way in React Native as you would in a browser or in a Node.JS application. API documentation for the AWS SDK for JS's Cognito Identity service client can be found [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html).

**Comment by MatheusParanhos** [comment]
@jeskew Thanks for the reply and for clarifying that! cheers

**Comment by frangeris** [comment]
Hey @MatheusParanhos did you find a way? 

I'm struggle with this and the only how to it's using UI custom in app integrations.

**Comment by zhongqin0820** [comment]
how do you solve this problem finally? @MatheusParanhos @frangeris

**Comment by frangeris** [comment]
@zhongqin0820 end up using firebase auth, easier and cleaner....  `¯\_(ツ)_/¯`

**Comment by zhongqin0820** [comment]
thanks @frangeris
