### ISSUE TITLE
createPresignedPost doesn't pick up EC2 IAM role

### ISSUE THREAD

**Issue by mrfez** [aws/aws-sdk-js#1756]
This error is generated when createPresignedPost is used in node on EC2: "Upload POST Error: Unable to create a POST object policy without a bucket, region, and credentials"

However getSignedUrl works perfectly well, using the IAM role credentials.

Forcing an accessKeyId and secretAccessKey in to the s3 config seems to work, but obviously isn't ideal.

**Comment by AllanFly120** [comment]
Hi @mrfez 
Are you using the callback in `createPresignedPost `? You know it's preferable to use the asynchronous method when you use the IAM credentials. It seems like your credentials cannot be resolved. Which credentials are you using?

**Comment by mrfez** [comment]
Hi @AllanFly120 
Thanks for that - I wasn't. It's disconcerting when getSignedUrl works fine using synchronous, but createPresignedPost doesn't.
