### ISSUE TITLE
How to get an object with wildscard key like 'image_2017*'

### ISSUE THREAD

**Issue by aflext** [aws/aws-sdk-js#1758]
I use [ceph](http://docs.ceph.com/docs/giant/radosgw/s3/#api) to store my object.
I just download the file from other rescources and store it in `ceph` with unique filename and the original postfix.
I wander if i can retrive an object without the postfix  like:

```javascript
// just assume the file path is `bucket/unique_id.jpg`
let file = require('fs').createWriteStream('image.png');
s3.getObject({
    Bucket: 'bucket',
    Key: 'unique_id*',
}).createReadStream().pipe(file);
```

**Comment by AllanFly120** [comment]
Hey @aflext,
I think you are looking for [`listObjectsV2`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property). This is a revised list object operation, in which you can specify the prefix.

```javascript
const params = {
    Bucket: 'bucket',
    Prefix: 'unique_id',
    MaxKeys: 10 //to limit the results number returned from operation
};
s3.listObjectV2(params, function(err, data) {
        if (err) {
            console.log(err)
        } else {
            console.log(data);
       }
})
```
You can then get these objects according to the Keys returned by `listObjectsV2`. 
```javascript
s3.listObjectsV2(params).promise().then(data => {
    let q = [];
    for (content of data.Contents) {
        const getObjectParams = {
            Bucket: bucketName,
            Key: content.Key
        }
        q.push(s3.getObject(getObjectParams).promise())
    }
    return Promise.all(q);
}).then(data => {
    console.log(data)
}).catch(err => {
    console.log(err);
})
```

**Comment by aflext** [comment]
@AllanFly120 Can i user the Prefix with regexp like `file_name_with{.txt,jpg}`
