### ISSUE TITLE
the link of tsconfig.json do not work

### ISSUE THREAD

**Issue by jingpengw** [aws/aws-sdk-js#1759]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/#Usage_with_TypeScript

Your tsconfig.json or jsconfig.json includes 'dom' and 'es2015.promise' under compilerOptions.lib. See tsconfig.json for an example.

**Comment by AllanFly120** [comment]
Hi @jingpengw 
Thank you for pointing this out! Also, the link you are looking for is here: https://github.com/aws/aws-sdk-js/blob/master/ts/tsconfig.json
