### ISSUE TITLE
Amazon S3 file upload node js socket hang up and write ECONNRESET error 

### ISSUE THREAD

**Issue by usamamashkoor** [aws/aws-sdk-js#1768]
Hi i am uploading a video file to amazon s3 bucket the file is inside my project folder. but i am getting the following error  when i tries to upload the file.
```
error in callback
{ NetworkingError: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  message: 'socket hang up',
  code: 'NetworkingError',
  retryable: true,
  statusCode: 400 }
and sometimes i also get this error to 
Error: write ECONNRESET
  errno: 'ECONNRESET',
```
Here is my code for uploading the file 
```
const path = require('path');
const fs   = require('fs');
const AWS = require('aws-sdk');

AWS.config.update({
  region: "us-east-1",
  accessKeyId: "my key",
  secretAccessKey: "my secret",
});
let S3 = new AWS.S3({httpOptions: {timeout: 0},params: {Bucket: bucket_name'}});
function uploadToS3(file) {
  fs.readFile(file, function (err, data) {
      var params = {
        Key: 'videoobitio360.mp4',
        Body: data
      };
      var options = {partSize: 5 * 1024 * 1024, queueSize: 4};
      S3.upload(params,options, function (err, data) {
        if (err) {
          console.log('error in callback');
          console.log(err);
        }
        console.log('success');
        console.log(data);
      });
 });    
} 
```
i have tried setting httpOptions: {timeout: 0} to 0 also but it also did not work.
kindly help me on this issue.
Thanks.

**Comment by chrisradek** [comment]
@usamamashkoor 
How fast is your connection? Are you able to make other S3 requests successfully?

Note:
You don't have to do this, but when using `s3.upload`, you can set the `Body` parameter to a stream. The benefit here is you don't have to load the entire file into memory first (which is what `fs.readFile` will do).

Example:
```javascript
var videoStream = fs.createReadStream('filepath');
var params = {
  Key: 'video',
  Body: videoStream
};
```

**Comment by usamamashkoor** [comment]
@chrisradek thanks for replying me my connection is `4 MB` and downloading speed is `500kb `my s3 file upload functions works for files under `10 MB` mean the function works for smaller files but it does not work for files larger than `10 MB` which also means the s3 request are working correctly but they are not working correctly for larger files.  .  

Thanks for tip about `Fs.readfile` i will try it and will let you know. 
Thanks again for the reply.

**Comment by usamamashkoor** [comment]
I think you will have to use queue mean upload file in chunks of 5 mb . You can open 4 queues.

**Comment by srchase** [comment]
@usamamashkoor,

Did this get things working for you?  Do you have any followup questions?  It looks like this is a usage questions, and not an issue with the SDK, so I'd like to close this if there's nothing further.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
