### ISSUE TITLE
createBucket error==>InvalidArgument: Request has content-type header but signed headers not include it.

### ISSUE THREAD

**Issue by shuaishenk** [aws/aws-sdk-js#1770]
createBucket error==>InvalidArgument: Request has content-type header but signed headers not include it.

In aws and huawei cloud env,the operation is successful.While in the internal huawei cloud,the error above accured

**Comment by chrisradek** [comment]
@shuaishenk 
I'm not clear about what the issue you're reporting is. Are you saying that within your internal cloud, when you try to call s3.createBucket, S3 is returning an error?  Can you share the full error here?

We intentionally do not sign the `Content-Type` header: https://github.com/aws/aws-sdk-js/blob/v2.138.0/lib/signers/v4.js#L192

**Comment by srchase** [comment]
Closing without further information to reproduce.
