### ISSUE TITLE
react-native s3 putObject uri support

### ISSUE THREAD

**Issue by sibelius** [aws/aws-sdk-js#1772]
How can I upload an uri using s3 upload function?

```jsx
const file = {
    uri,
    name: key,
    type: 'image/jpeg',
  };

  const params = {
    Bucket: bucket,
    Key: key,
    ContentType: 'image/jpeg',
    // ContentLength: file.size,
    Body: file,
    // Body: file.buffer,
    // Body: new Buffer(base64, 'base64'),
    ACL: 'public-read',
  };

s3.putObject(params, (err, data) => ())
```

**Comment by chrisradek** [comment]
@sibelius 
The SDK doesn't currently know how to read a file using the uri method. Instead it would require either a Blob, string, or a Buffer/Uint8Array be passed in as the body.

I'll mark this as a feature request. In the meantime, you could try generating a presigned url and make either a fetch or XMLHttpRequest call directly, setting the Body as an object that contains the uri. I haven't tested this myself, but I think that should work.

**Comment by haikyuu** [comment]
I generated a presigned url and successfully uploaded a file using curl. But it does not work on react-native. I have tried using xhr and fetch and attaching an object `{uri: "file://..."}` to the body but i get the following error:
`Expected dynamic type string but had type object (constructing arguments for Networking.SendRequest at argument index 1)`

![screen shot 2017-10-30 at 10 19 15 pm](https://user-images.githubusercontent.com/8558836/32198553-7497792c-bdc0-11e7-8892-090c0da97375.png)
I even tried using `react-native-fetch-blob` but i get the same error (with index 3).

Using form-data sends the request but S3 responds with error ```<Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>```

Any clues how to upload a file using a presigned url in react-native?

**Comment by Sangrene** [comment]
Any news on this ?

**Comment by sibelius** [comment]
I think we can do that on rn54 using fetch with blob

**Comment by ngocketit** [comment]
@sibelius Could you please elaborate the idea a bit more? Have you found solution to this yet? I'm uploading a large file and run into the same problem. Thank you!
