### ISSUE TITLE
broken aws sdk release notes in README.md

### ISSUE THREAD

**Issue by nsaboo** [aws/aws-sdk-js#1774]
broken aws sdk releasenotes link in README.md

- broken link
For release notes, see the CHANGELOG. Prior to v2.4.8, release notes can be found at http://aws.amazon.com/releasenotes/SDK/JavaScript

- correct link
For release notes, see the [CHANGELOG](CHANGELOG.md). Prior to v2.4.8, release notes can be found at https://aws.amazon.com/releasenotes/?tag=releasenotes%23keywords%23javascript

- broken link snapshot
![aws-sdk-broken-link](https://user-images.githubusercontent.com/7092026/31917625-4772a11e-b80d-11e7-8e29-595a4dbd7de5.png)

**Comment by chrisradek** [comment]
Thanks for reporting and fixing this, @nsaboo 

Fixed by #1775

**Comment by nsaboo** [comment]
Thanks @chrisradek appreciate your help on merging it, looks like travis had some transient failure with this commit checkin.

Thanks,
Nanda.
