### ISSUE TITLE
Error while tagging sqs resources

### ISSUE THREAD

**Issue by ddimitrioglo** [aws/aws-sdk-js#1779]
I'm trying to tag multiple SQS resources and receiving an error:
> InvalidParameterException: Unsupported service=sqs in ARN=arn:aws:sqs:[region]:[account]:[queue]

P.S. working with [API_TagResources](http://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_TagResources.html)

P.S.S. aws-sdk@2.140.0

**Comment by chrisradek** [comment]
@ddimitrioglo 
According to [this list](http://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/supported-resources.html), SQS is not one of the resources that supports tagging.

Please create a feature request on the [SQS forums](https://forums.aws.amazon.com/forum.jspa?forumID=12) letting them know you'd like for them to support tagging.

**Comment by ddimitrioglo** [comment]
@chrisradek 
According to this [changelog](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#21370) QSQ **_is_** supported, and I can easily tag it via AWS CLI like this `aws sqs tag-queue --queue-url="https://sqs.[region].amazonaws.com/[account]/[queue]" --tags="Key=Value"`

Please reopen the issue.

**Comment by ddimitrioglo** [comment]
@chrisradek 
Apologies from my side too...
I am using ResourceGroupsTaggingAPI and I thought that it should support SQS too.
Will try to make a workaround with SQS.tagQueue and let you know.

**Comment by ddimitrioglo** [comment]
As a summary:

1. AWS-CLI tagging (one queue) - supported
2. AWS-SDK tagging (one queue) - supported
3. GroupsTaggingAPI - is **NOT** supported **BUT** you can use a workaround which worked for me:
```
let promises = queueUrls.map(url => {
  return this._sqs.tagQueue({
    QueueUrl: [queue url],
    Tags: [tags payload]
  }).promise();
});

Promise.all(promises).then(res => {}).catch(err => {});
```

@chrisradek Thank you for explanations.
