### ISSUE TITLE
S3 putObject progress

### ISSUE THREAD

**Issue by refaelos** [aws/aws-sdk-js#178]
Is it possible to get the upload (or putObject) progress? 

If there was a putStream it might be easier to get it.

**Comment by john-aws** [comment]
Hi, is there any way to get httpUploadProgress events in the browser if you call putObject via makeUnauthenticatedRequest? If I add .on('httpUploadProgress', f) then I see "TypeError: undefined is not a function", for example:

```javascript
var params = { Key: key, Body: body };

s3.makeUnauthenticatedRequest('putObject', params, function(err, data) {
  console.log("err: " + err);
})
.on('httpUploadProgress', function(progress) { // TypeError here
  console.log("progress: " + progress);
});
```

**Comment by sebastientromp** [comment]
Just in case someone else arrives here looking for this:

The `makeUnauthenticatedRequest` function returns the `request` object if you don't pass a callback:

```java
return callback ? request.send(callback) : request;
```
So if you want to add a progress listener, you will do:

```java
var params = { Key: key, Body: body };

var req = s3.makeUnauthenticatedRequest('putObject', params);
req.on('httpUploadProgress', function(progress) {
  console.log("progress: " + progress);
});
req,send(function(err, data) {
  console.log("err: " + err);
})
```

**Comment by kaarthikeyansp** [comment]
But  I could see only {"isTrusted":true} now in 2.94 version of aws-sdk
