### ISSUE TITLE
How can I remove the AWSAccessKeyId, Signature etc... from s3 Bucket image URL?

### ISSUE THREAD

**Issue by vishalmindinventory** [aws/aws-sdk-js#1780]
@lsegal @ericb @corymsmith 
**I am uploading image to bucket from below code ::**

fs.readFile(temp_path, function (err, binaryData) {
	let data = {
	    Key: imgarray.folder + '/' + file_name,
	    Body: binaryData,
	    ACL: 'public-read',
	    ContentType: files[imgarray.name].type
	};

	s3Bucket.putObject(data, function (err, data) {
	    if (err) {
	        reject(err)
	    } else {
	        resolve(file_name)
	    }
	});
})

**For retrieve image from  bucket using below code** 

let urlParams = {Key: 'folder'+'/'+offerDetail.offer_image};

s3Bucket.getSignedUrl('getObject', urlParams, function(err, url){
    offerData.push(url)
    inerresolve(true)
},err=>{
    offerData.push(BaseController.imageUrl('folder'))
    inerresolve(true)
})

Can anybody help for this?

**Comment by chrisradek** [comment]
@vishalmindinventory 
If you're setting `ACL: 'public-read'`, then you don't have to use presigned URLs if you just want to allow others to read the file. You can construct the URL (If you look at the S3 console, you can see the pattern used for URLs by clicking on an object).

What's your reason for not wanting the URL to contain the AccessKeyId/Signature? The URL does not contain the secretAccessKey, an attacker won't be able to make requests using your account, and using temporary credentials would also change the AccessKeyId further.

**Comment by vishalmindinventory** [comment]
@chrisradek 
Thanks.
