### ISSUE TITLE
Metadata not working on upload

### ISSUE THREAD

**Issue by ir-fuel** [aws/aws-sdk-js#1787]
sdk version 2.142.0

```
    let s3Params = {}

    s3Params.ContentType = mimetype
    s3Params.Bucket = bucket
    s3Params.Key = path.join(subfolder, name)

    s3Params.ContentLength = data.length
    s3Params.Body = data
    s3Params.MetaData = {
      "mode":"33188"
    }

    s3.upload(s3Params, (err) => {})
```

When I run this and I check the file in S3, it tells me there is only 1 metadata attribute, called `Content-Type`

**Comment by jeskew** [comment]
S3 object metadata should be specified with the `Metadata` property name, not `MetaData`. By changing line 9 of the sample above from `s3Params.MetaData = {` to `s3Params.Metadata = {`, I was able to successfully save an object with custom metadata.
