### ISSUE TITLE
InvalidSignatureException: Patch

### ISSUE THREAD

**Issue by GDavisSS** [aws/aws-sdk-js#1788]
![image](https://user-images.githubusercontent.com/32397295/32341368-b0568376-bfd3-11e7-95af-990c3a579aed.png)

![image](https://user-images.githubusercontent.com/32397295/32341469-f25a810a-bfd3-11e7-9649-6c8111434bdc.png)
![image](https://user-images.githubusercontent.com/32397295/32341516-12e11434-bfd4-11e7-9b28-ddda6190d730.png)

The response for PATCH message says "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."
There is nothing else in the message about the expected signing key or expected anything else I've seen on other pages that should be in the message.  Everything in the PATCH request appears correct.
I have seen this issue in many forums for GET and POST and none of those responses helped (ex: remove content-type from headers, replace secret key variable with hard coded secret key, etc).  I also noticed many forums that say adding a body to a POST can cause this because of an AWS bug that has supposedly been fixed.  Not sure how different PATCH is from POST so I don't know if this is just another AWS bug.

I can successfully do a GET request to the same endpoint with the same type of signature.  The only differences are:
1) GET instead of POST
2) 'accesstoken' is not in GET headers, but it shows up in allowed headers for PATCH (as it should) so i don't see how that can be the issue
3) GET has no body, but PATCH does

An empty body for the PATCH request responds with 415 Unsupported Media Type.  Obviously, I want to be able to pass a body.

**Comment by jeskew** [comment]
Was this call made using [an SDK generated by API Gateway](http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk.html)?

**Comment by GDavisSS** [comment]
I installed the aws sdk as well as the api gateway generated sdk.

**Comment by jeskew** [comment]
The API Gateway-generated SDKs do not use the AWS SDK for JavaScript or its internals. I recommend reaching out to the API Gateway service either by opening a support ticket or by posting to their [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=199).

**Comment by GDavisSS** [comment]
I will try asking on the AWS forums, but your response makes no sense.  It makes no difference if the generated sdk uses the AWS SDK or not.  My web page for testing my api would not work if I had not installed the AWS SDK.  I would not be able to use AWSCognito for authentication or do basic front-end/aws back-end interactions because they require the AWS SDK.
What's important is that others have posted issues to github.com/aws/aws-sdk-js about the exact same problem and they were helped.  Why treat me differently?

**Comment by jeskew** [comment]
Hi @GDavisSS,

We try to limit this forum to issues with the AWS SDK for JavaScript or questions about its use. It's used to prioritize work on the code in this repository and is not monitored by API Gateway or by AWS Support.

Since the signature error is originating from code that is not worked on in this repository, I thought you would get much faster resolution by reaching out to the service who controls the API Gateway SDK generator or by opening a support ticket with API Gateway. I believe that the issues others posted to which you refer were issues with the AWS SDK's request signer, which is not being used in the request whose signature is being rejected.
