### ISSUE TITLE
S3: "aws:kms" Signing an upload to S3 is failing with 'InvalidEncryptionAlgorithmError'

### ISSUE THREAD

**Issue by andrew-e** [aws/aws-sdk-js#1789]
When attempting to `putObject` with the following parameters
```
        const params = {
            Bucket: bucketName,
            Key: s3Key,
            Body: body,
            ACL: 'authenticated-read',
            ContentType: contentType,
            ServerSideEncryption: "aws:kms",
            SSEKMSKeyId: encryptionKey
        }
```

I get the following error
```
{
  "errorMessage": "The Encryption request you specified is not valid. Supported value: AES256.",
  "errorType": "InvalidEncryptionAlgorithmError",
  "stackTrace": [
    "Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:577:35)",
    "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)",
    "Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)",
    "Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)",
    "Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
    "AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "/var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
    "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)",
    "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"
  ]
}
```

This is strange because when I try to do the same via the AWS CLI via this command
```aws s3 cp config.json s3://{bucketName}/{s3Key} --sse aws:kms --sse-kms-key-id {encryptionKey}```

with the same variables as above, it works great.

I am using the latest aws-sdk version in package.json `"aws-sdk": "2.143.0"`

The even stranger part is that aws:kms seems like it should work from the s3.d.ts file, but I still get this error.

**Comment by jeskew** [comment]
The parameters you're using should be working, so the error message might be being provided in error. Trying to reproduce with parameters similar to those described, I consistently get back a successful response that includes the object ETag and the id of the KMS key used to encrypt the object.

Could you open a support ticket with S3? They would be able to provide more detailed information about a particular request or account.

**Comment by andrew-e** [comment]
Thanks jeskew, I'm so sorry I made a mistake in my reporting... it wasn't the putObject call that was failing, it was the getObject call.  And that also seems to be failing on the AWS CLI, so maybe I'm using it incorrectly!  I think I'm using it according to the docs though.

I'm calling it with these params
```
        const getParams = {
            Bucket: bucket,
            Key: key
            SSECustomerAlgorithm: "aws:kms";
            SSECustomerKey: encryptionKey;
        }
```

The error above was in fact the getObject failure, so that bit remains the same

**Comment by jeskew** [comment]
Understood. When using server-side encryption with KMS keys or S3-managed keys, you only need to supply the `Bucket` and `Key` to `getObject`. The data is encrypted at rest in S3, but they have the information they need to decrypt it when you call `getObject`.

The `SSECustomerAlgorithm` and `SSECustomerKey` are used for objects [encrypted with customer-managed keys](http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html), which S3 does not store.

**Comment by andrew-e** [comment]
Ah, great to know.  Thanks for your help!
