### ISSUE TITLE
Bad checksum for 2.145.0

### ISSUE THREAD

**Issue by aaayushsingh** [aws/aws-sdk-js#1790]
for `npm install aws-sdk --save` and `npm install aws-sdk@2.145.0`

> 237 error code EINTEGRITY
> 238 error sha1-CFu0VTIx3v2TuWsNlQI3F8nDwJM= integrity checksum failed when using sha1: wanted sha1-CFu0VTIx3v********* but got sha1-noU7IQ******** (1242173 bytes)

debug log last lines.

**Comment by AllanFly120** [comment]
Hi @aaayushsingh 
It seems that your npm finds a wrong checksum. You can try running cleaning cache cmd: `npm cache --force clean`. If this still exists you can remove the `.npm` file and re-install the sdk. 

This is not an issue with sdk, so I will just close this issue. But feel free to comment here if you have further questions.
