### ISSUE TITLE
5 second delay to s3.putObject and sqs.deleteMessage

### ISSUE THREAD

**Issue by doapp-jeremy** [aws/aws-sdk-js#1792]
I'm noticing a 5 second delay after to certain aws sdk calls after some other calls. I'm receiving 10 messages from my sqs queue.  I then make 20 calls to s3.getObject, 10 to s3.putObject and then another 10 to sqs.deleteMessage

Thinking that this could be maxSocket issue, I ran the attached [log.txt](https://github.com/aws/aws-sdk-js/files/1459136/-.txt) with maxSockets set at 500, but that did not affect the results.

I'm stumped at where this delay is coming from.  I tried profiling the running code, however, I'm fairly new to node and could not find anything glaring in the profile results.

I'm using node v8.9.0 and aws-sdk-js version 2.149.0

**Comment by AllanFly120** [comment]
Hi @doapp-jeremy,
I see the deleteMessage operation with 5s delay in your attachment. But I can't reproduce this issue.
Is this a consistent issue?(the delay always exists in some specific sequence of operations or always the same operation)

**Comment by doapp-jeremy** [comment]
@AllanFly120 thanks for the response, yes, it's a consistent issue, however, the exact # of putObject or deleteMessage calls that are delayed varies by 1 or two.

**Comment by AllanFly120** [comment]
Do you mind showing me your code to reproduce this issue? How do you specify the `ReceiptHandle` when you delete the message? And your Queue config.(regular or fifo queue; default visibility timeout)

**Comment by doapp-jeremy** [comment]
@AllanFly120 sorry for the slow response, been out of the office for quite some time.
Below is the code I use to delete the message.  It's a regular queue and the default visibility timeout is 1 minute.

`let deleted = 0;
const deleteMessage = async(receiptHandle) => {
  let deleteNum = ++deleted;

  logger.log('info', 'deleting message %d', deleteNum);
  const start = new Date().getTime();
  return sqs.deleteMessage({
      QueueUrl: QUEUE_URL,
      ReceiptHandle: receiptHandle
    }).promise()
    .then(result => {
      const end = new Date().getTime();
      logger.log('info', 'deleted %d message in %dms: %s', deleteNum, (end - start), result.ResponseMetadata.RequestId);
      return result;
    })
    .catch(err => {
      logger.log('error', err.stack);
    });
}
`

**Comment by srchase** [comment]
Hello @doapp-jeremy 

I apologize we have not responded sooner.  Is this still an open issue for you, or were you able to get it resolved?
