### ISSUE TITLE
S3 Uploading using a pre-signed URL

### ISSUE THREAD

**Issue by ktalebian** [aws/aws-sdk-js#1801]
I cannot find any documentation or support for uploading to S3 using a pre-signed URL. Is this supported at all? Ideally, the upload function should take nothing more than the pre-signed URL (i.e. no bucket information, no aws key, region, etc).

On the documentation [page](http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) JS is not included.

**Comment by chrisradek** [comment]
@ktalebian 
Once you have a presigned-url, you should be able to use it directly with your http client. The SDK doesn't use them itself, it just generates them.

For example, you could do something like the below using [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch):

```javascript
fetch(presignedUrl, {
  method: 'PUT',
  headers: new Headers() // any extra headers you want to send,
  body: file
});
```
