### ISSUE TITLE
S3 Uploading pre-signed URL with signature v4, Content Disposition causes signature mismatch

### ISSUE THREAD

**Issue by CanGokdere** [aws/aws-sdk-js#1804]
I am currently using pre-signed uploading to directly upload from browser to s3. I can upload with no problems when I do not set the content disposition in options, for instance:

> var s3upload = new AWS.S3({
      signatureVersion: 'v4',
      accessKeyId: process.env.S3_UPLOAD_CLIENT_KEY,
      secretAccessKey: process.env.S3_UPLOAD_CLIENT_SECRET,
    });
  var baseOptions = {
      Bucket: process.env.S3_BUCKET,
      ACL: 'public-read',
      Key: uuidv4(),
    }

This works fine, http request:
![works1](https://user-images.githubusercontent.com/1070781/32938848-971e8dce-cb8e-11e7-8b1c-9b7fc398b6d5.jpg)

This also works fine when I set encryption

> var baseOptions = {
      Bucket: process.env.S3_BUCKET,
      ACL: 'public-read',
      Key: uuidv4(),
     ServerSideEncryption: 'AES256'
    }
![works2](https://user-images.githubusercontent.com/1070781/32938925-e2d83684-cb8e-11e7-90bb-704462f912e9.jpg)

But if I add content disposition to options, I always get Signature mismatch
> var baseOptions = {
      Bucket: process.env.S3_BUCKET,
      ACL: 'public-read',
      Key: uuidv4(),
     ContentDisposition: 'attachment',
     ServerSideEncryption: 'AES256'
    }

![notworking](https://user-images.githubusercontent.com/1070781/32938984-12902774-cb8f-11e7-90cc-f13acf81cf1b.jpg)

I get the following response:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>`

What is the problem and how can I fix it ?

**Comment by jeskew** [comment]
Hi @CanGokdere,

It looks like we're hoisting headers to the query string after the request has already been signed, which invalidates a V4 signature. This appears to be permitted in V2 presigned URLs, but we'll need to modify the presigner to properly account for SigV4's requirements.

**Comment by CanGokdere** [comment]
Hello @jeskew,
I have updated the sdk but my issue with Content Disposition still persists. I have removed all the headers and only using pre-signed url and query parameters. If I want to include content disposition in presigned url it still causes signature mismatch.

**Comment by jeskew** [comment]
Hi @CanGokdere,

I was able to successfully use pre-signed URLs to execute a `PutObject` operation using the following code that relies on the master branch of the SDK (the update has not yet been included in a release):

```javascript
const AWS = require('aws-sdk');
const uuidv4 = require('uuid/v4');
const https = require('https');
const url = require('url');
const s3 = new AWS.S3({
    region: 'us-west-2',
    signatureVersion: 'v4'
});
const presigned = s3.getSignedUrl('putObject', {
    Bucket: bucketName,
    Key: uuidv4(),
    ContentDisposition: 'Attachment'
});
console.log(presigned);
const options = url.parse(presigned);
options.method = 'PUT';
options.headers = {'content-disposition': 'Attachment'};

const stream = https.request(options);
stream.on('response', (res) => {
    console.log(res.statusCode);
    res.pipe(process.stdout);
});

stream.end('body');
```

Please note that you can add a `Content-Disposition` header after signing.

**Comment by vladgolubev** [comment]
@jeskew thanks for the fix! I had the same problem after I added X-Ray to my Lambda which generated a signed link. It added an extra header `xray-trace-id` or smth like that. After updating to `2.156.0` the signature is valid again.

But it's a pity Lambda environment has still old `2.129.0` version, so people need to deploy extra dependencies.
