### ISSUE TITLE
httpUploadProgress callback not being called

### ISSUE THREAD

**Issue by iamtekeste** [aws/aws-sdk-js#1805]
I don't believe this is an issue with this package but I could use some help. I am trying to get back progress report of my file upload to AWS S3 from a react native app. As you can see I am listening for the httpUploadProgress event and trying to print the progress. But this callback function is not being called. What am I missing here?

```js
const imageArrayBuffer = decode(image.data);
    const s3 = new AWS.S3();
    const params = {
        Bucket: BUCKET_NAME,
        Key: photoKey,
        Body: imageArrayBuffer,
        ContentType: image.type
    };

    s3
        .upload(params)
        .on('httpUploadProgress', function(evt) {
            console.log(
                'Uploaded :: ' + parseInt(evt.loaded * 100 / evt.total) + '%'
            );
        })
        .send(function(err, data) {
            console.log(data);
        });
```

**Comment by chrisradek** [comment]
@iamtekeste 
Are you using the most recent version of React Native?

The SDK uses XMLHttpRequest to make requests, and attaches a progress listener to the xhr.upload object:
https://github.com/aws/aws-sdk-js/blob/46a5ab29c1dc0a40e824cbabf623343c5e9e622a/lib/http/xhr.js#L42-L44

Reading through [this issue](https://github.com/facebook/react-native/issues/3181) on React Native's repo, it sounds like progress events may not be implemented. It's possible they've added support on a newer version of React Native, but the fact that your callback isn't being triggered suggests they don't support this event yet. I'd suggest posting another issue on their repo asking if they can support this progress events.
