### ISSUE TITLE
createReadStream events - where are the event docs???

### ISSUE THREAD

**Issue by tomgallagher** [aws/aws-sdk-js#1809]
I guess loads of people must be using getObject.createReadStream()

But finding a list of events emitted is very hard.

For example, how do I get data about the object info. 

`.on(info, info =>`

or 

`.on(entry, entry =>  `

And making the getObject.createReadStream() complete event called 'httpdone' is downright obtuse.

What's going on?

Any help or pointers gratefully received, much though I love amateur detective work...

**Comment by jeskew** [comment]
Hi @tomgallagher,

The list of events emitted by `AWS.Request` (the class that has the `createReadStream` method) can be found [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html). The object metadata returned with `GetObject` are sent as headers, so you would want to attach a handler to the [`'httpHeaders'`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#httpHeaders-event) event.

**Comment by tomgallagher** [comment]
Many thanks.


Sent from Samsung Mobile on O2
-------- Original message --------From: Jonathan Eskew <notifications@github.com> Date: 24/11/2017  16:59  (GMT+00:00) To: aws/aws-sdk-js <aws-sdk-js@noreply.github.com> Cc: Pathfinder <thomasgallagher101@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [aws/aws-sdk-js] createReadStream events - where are the event docs??? (#1809) 
Hi @tomgallagher,
The list of events emitted by AWS.Request (the class that has the createReadStream method) can be found here. The object metadata returned with GetObject are sent as headers, so you would want to attach a handler to the 'httpHeaders' event.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aws/aws-sdk-js","title":"aws/aws-sdk-js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aws/aws-sdk-js"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jeskew in #1809: Hi @tomgallagher,\r\n\r\nThe list of events emitted by `AWS.Request` (the class that has the `createReadStream` method) can be found [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html). The object metadata returned with `GetObject` are sent as headers, so you would want to attach a handler to the [`'httpHeaders'`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#httpHeaders-event) event."}],"action":{"name":"View Issue","url":"https://github.com/aws/aws-sdk-js/issues/1809#issuecomment-346869122"}}}
