### ISSUE TITLE
Multipart upload with SSE KMS

### ISSUE THREAD

**Issue by sksin28** [aws/aws-sdk-js#1814]
I am using the upload function with SSE properties set in the params. However, if the user has the permission to use the key for encryption only, the upload fails with error Access Denied. If the decrypt permission is given, the upload works smoothly.

```
let response = yield this.s3.upload({
                Key: outputFile,
                Body: gzip,
                ServerSideEncryption: "aws:kms",
                SSEKMSKeyId: kmsKeyId
            }).promise();
```
It's not mentioned on the AWS docs that user should have both the encrypt and decrypt permissions of the key.

This happens only when the object size is greater than 100 MB. Otherwise, there is no error. So I guess the error is related to multipart upload.

The error is generated by the req.send in uploadPart function.

**Comment by AllanFly120** [comment]
Hi @sksin28 
The s3.upload method doesn't modify the parameters fed into the operation. This behavior may result from the service. You can raise this issue on the S3 service forum, they should be able to answer this question.😅
