### ISSUE TITLE
aws-sdk bucket.getObject: No 'Access-Control-Allow-Origin' header is present 

### ISSUE THREAD

**Issue by squarewave24** [aws/aws-sdk-js#1817]
the s3 bucket i am accessing is already configured to allow * gets 

```
<!-- Sample policy -->
<CORSConfiguration>
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>GET</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>Authorization</AllowedHeader>
	</CORSRule>
</CORSConfiguration>
```

but getting: 

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 403

perhaps i need to set CORS headers on my request?  if so not sure where to do this. At least couldn't find any obvious header properties so far on bucket or s3config 

```
        var options = <awsservice.ServiceConfigurationOptions> {};
        options.secretAccessKey = environment.secretKey;
        options.accessKeyId = environment.accessKeyId;
        
        AWS.config.update(options);
        AWS.config.region = environment.region;
        
        var s3Config = <s3.ClientConfiguration>{};
        
        var fileName = 'x';
        var params = { Bucket: environment.bucket, Key: fileName, ContentType: 'application/json', ServerSideEncryption: 'AES256' };
        
        s3Config.params = params;        
        var bucket = new s3(s3Config);
        console.log('getting bucket')
        
        bucket.getObject( (err,data) => console.log(err, data)); // 403 ! 
```

here are my imports 

```
import * as AWS from "aws-sdk/global";
import * as awsservice from "aws-sdk/lib/service";
import * as CognitoIdentity from "aws-sdk/clients/cognitoidentity";
import * as s3 from "aws-sdk/clients/s3";
```

**Comment by squarewave24** [comment]
figured it out, I added this on server cors configuration and that got rid of the error 

```<AllowedHeader>*</AllowedHeader>```

**Comment by msnikhil** [comment]
In addition to @squarewave24's answer above, also add `<AllowedMethod>PUT</AllowedMethod>` to the CORS configuration file.
