### ISSUE TITLE
TypeError: lambda.invoke is not a function

### ISSUE THREAD

**Issue by kaushalparik27** [aws/aws-sdk-js#1823]
I am trying to call an aws lambda function within another lambda function. I tried a very simple code snippet. However, every time I am receiving "TypeError: lambda.invoke is not a function".

```
exports.handler = function(event, context) {
    var AWS = require('aws-sdk');
    AWS.config.apiVersions = {
      lambda: '2015-03-31'
    };

    var lambda = new AWS.Lambda();

    var params = {
        FunctionName: "node-sendsms", 
        Payload: null
    };

    lambda.invoke(params, function(err, data) {
        if (err) console.log(err, err.stack); // an error occurred
        else     console.log(data);           // successful response
    });
};
```
I referred to the documentation here for invoke function: [http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property) and followed same code. I tried changing api version but that did not help. I also tried looking out for any solution online as well as on SO; at least information I got is that it can be an issue of variable scoping for AWS variable. But, as it can be seen in code - it does not seems like that.

Any experts on this error? I am working on node.js 6.10. Here is error detail:
```
2017-12-01T08:38:39.023Z	063f3cea-d673-11e7-9b62-0fa01eaf399f	TypeError: lambda.invoke is not a function
    at exports.handler (/var/task/index.js:15:12)
END RequestId: 063f3cea-d673-11e7-9b62-0fa01eaf399f
REPORT RequestId: 063f3cea-d673-11e7-9b62-0fa01eaf399f	Duration: 1581.95 ms	Billed Duration: 1600 ms 	Memory Size: 128 MB	Max Memory Used: 25 MB	
RequestId: 063f3cea-d673-11e7-9b62-0fa01eaf399f Process exited before completing request
```

**Comment by chrisradek** [comment]
@kaushalparik27 
Are you using the AWS SDK that's bundled with Lambda, or are you bundling your own? Can you inspect your `lambda` object to see what methods are available to it?

I just created a new node.js 6.10 lambda function and am not getting that error. Is your code above exactly what your Lambda function look like?

**Comment by kaushalparik27** [comment]
@chrisradek I am writing Lambda right inside inline code editor in AWS console and I have not bundled my own. It will be a great help if you can provide me hint or documentation on how can I inspect lambda object in AWS console line editor.
The code that I posted above, is what exactly my lambda function is.

**Comment by chrisradek** [comment]
You would need to inspect the lambda object and log the properties. Specifically, we want to make sure you see `invoke` as a method. If you log properties, you'll want to view the log in CloudWatch logs instead of the viewer embedded in Lambda, otherwise some logs will be cut off.

Here is my example that does not receive the `TypeError`:

```javascript
exports.handler = (event, context, callback) => {
    var AWS = require('aws-sdk');
    AWS.config.apiVersions = {
        lambda: '2015-03-31'
    };
    
    var lambda = new AWS.Lambda();
    
    var params = {
        FunctionName: 'FAKE',
        Payload: null
    };
    
    var logs = [];
    var invokeExists = false;
    for (var method in lambda) {
        if (typeof lambda[method] === 'function') {
            logs.push(`lambda.${method} exists.`);
            if (method === 'invoke') {
                invokeExists = true;
            }
        }
    }

    console.log(logs.join('\n'));
    console.log(`invoke exists: ${invokeExists}`);
    
    lambda.invoke(params, function(err, data) {
        if (err) console.log(err, err.stack);
        else console.log(data);
        callback(err, data);
    });
};
```

**Comment by kaushalparik27** [comment]
@chrisradek thx for this help!
I see invoke is not showing in the log (invokeAsync is the one, though). Is that expected?

```
2017-12-05T18:27:43.045Z	faca2b09-d9e9-11e7-9286-b53eee0eeb97	lambda.constructor exists.
lambda.addEventSource exists.
lambda.deleteFunction exists.
lambda.getEventSource exists.
lambda.getFunction exists.
lambda.getFunctionConfiguration exists.
lambda.invokeAsync exists.
lambda.listEventSources exists.
lambda.listFunctions exists.
lambda.removeEventSource exists.
lambda.updateFunctionConfiguration exists.
lambda.uploadFunction exists.
lambda.initialize exists.
lambda.validateService exists.
lambda.loadServiceClass exists.
lambda.getLatestServiceClass exists.
lambda.getLatestServiceVersion exists.
lambda.makeRequest exists.
lambda.makeUnauthenticatedRequest exists.
lambda.waitFor exists.
lambda.addAllRequestListeners exists.
lambda.setupRequestListeners exists.
lambda.getSignerClass exists.
lambda.serviceInterface exists.
lambda.successfulResponse exists.
lambda.numRetries exists.
lambda.retryDelays exists.
lambda.retryableError exists.
lambda.networkingError exists.
lambda.expiredCredentialsError exists.
lambda.throttledError exists.
lambda.endpointFromTemplate exists.
lambda.setEndpoint exists.
lambda.paginationConfig exists.

18:27:43
2017-12-05T18:27:43.084Z	faca2b09-d9e9-11e7-9286-b53eee0eeb97	invoke exists: false

```

**Comment by chrisradek** [comment]
@karthiksaligrama 
So this is puzzling! It looks like the lambda API version you're getting is for [`2014-11-11`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda_20141111.html), not [`2015-03-31`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html). By default, the SDK should be using the latest version of lambda if you don't provide an apiVersion.

Can you remove your apiVersion and check again? If that doesn't work, can you make sure the model for lambda exists by logging:
```javascript
console.log(`Model exists: ${!!require('aws-sdk/apis/lambda-2015-03-31.min.json')}`);
```
It would be very bizarre if that model wasn't available, but we'll see!

**Comment by kaushalparik27** [comment]
@chrisradek thanks for right direction! I believe it has something to do with API version. I deleted Lambda and recreated it again and now I see invoke method working fine!
Could this be because of one fact that initially before starting on inline editor, I uploaded the lambda function using Visual Studio Toolkit (by creating a AWS Lambda node.js project in Visual Studio)?

**Comment by chrisradek** [comment]
@kaushalparik27 
Were you you using one of the tools from https://github.com/aws/aws-vsts-tools?

I don't think that should have the affect you're seeing, but if you do try it again and see the same issue, please provide the steps you took so the team can take a look at what's happening.

**Comment by kaushalparik27** [comment]
Yes, I was using VSTS Tools for publishing initially for same lambda function. I confirm this was due to old API npm installed in my AWS node.js project. I did two tests:
1. Created a new lambda function in inline editor and I found invoke function as log result:
```

2017-12-06T06:31:36.431Z 19aab9b1-da4f-11e7-8a77-69dbeb7399b9 lambda.constructor exists.
lambda.addPermission exists.
lambda.createAlias exists.
lambda.createEventSourceMapping exists.
lambda.createFunction exists.
lambda.deleteAlias exists.
lambda.deleteEventSourceMapping exists.
lambda.deleteFunction exists.
lambda.getAccountSettings exists.
lambda.getAlias exists.
lambda.getEventSourceMapping exists.
lambda.getFunction exists.
lambda.getFunctionConfiguration exists.
lambda.getPolicy exists.
lambda.invoke exists.
lambda.invokeAsync exists.
lambda.listAliases exists.
lambda.listEventSourceMappings exists.
lambda.listFunctions exists.
lambda.listTags exists.
lambda.listVersionsByFunction exists.
lambda.publishVersion exists.
lambda.removePermission exists.
lambda.tagResource exists.
lambda.untagResource exists.
lambda.updateAlias exists.
lambda.updateEventSourceMapping exists.
lambda.updateFunctionCode exists.
lambda.updateFunctionConfiguration exists.
lambda.setupRequestListeners exists.
lambda.initialize exists.
lambda.validateService exists.
lambda.loadServiceClass exists.
lambda.getLatestServiceClass exists.
lambda.getLatestServiceVersion exists.
lambda.customizeRequests exists.
lambda.makeRequest exists.
lambda.makeUnauthenticatedRequest exists.
lambda.waitFor exists.
lambda.addAllRequestListeners exists.
lambda.getSignerClass exists.
lambda.serviceInterface exists.
lambda.successfulResponse exists.
lambda.numRetries exists.
lambda.retryDelays exists.
lambda.retryableError exists.
lambda.networkingError exists.
lambda.timeoutError exists.
lambda.expiredCredentialsError exists.
lambda.clockSkewError exists.
lambda.getSkewCorrectedDate exists.
lambda.applyClockOffset exists.
lambda.isClockSkewed exists.
lambda.throttledError exists.
lambda.endpointFromTemplate exists.
lambda.setEndpoint exists.
lambda.paginationConfig exists.

2017-12-06T06:31:36.487Z 19aab9b1-da4f-11e7-8a77-69dbeb7399b9 invoke exists: true
```
2. Created a new lambda function in Visual Studio thru AWS VSTS Tools/Templates and published function thru it, and I found the same issue I was facing. Ultimately when referring npm dialog window in solution explorer; it has complained me of old api being used for aws-sdk. When I updated and again published, the error went away.

Thanks for all help!

**Comment by chrisradek** [comment]
Thanks for the follow-up! Glad you're no longer facing this issue!

**Comment by eMahtab** [comment]
It was due to aws js sdk version I was using, changed it to https://sdk.amazonaws.com/js/aws-sdk-2.2.32.min.js , that solved the problem
