### ISSUE TITLE
Latest SDK version availability on Lambda

### ISSUE THREAD

**Issue by steverob** [aws/aws-sdk-js#1825]
Current SDK version available in Lambda seems to be `2.143.0`. Any idea when this will be updated?

Thanks.

**Comment by chrisradek** [comment]
@steverob 
Please reach out to the Lambda team on their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=186&start=0). They handle updating the version of the SDK in Lambda.

Feel free to take a look [here](https://github.com/aws/aws-sdk-js/issues/765#issuecomment-152033324) if you want info on packaging up your own version of the SDK to include in a lambda function.
