### ISSUE TITLE
Uncaught Error: Cannot find module

### ISSUE THREAD

**Issue by rainnaren** [aws/aws-sdk-js#1828]
Uncaught Error: Cannot find module 'function (e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(require("aws-sdk/global"),require("aws-sdk/clients/cognitoidentityserviceprovider")):"function"==typeof define&&define.amd?define(["aws-sdk/global","aws-sdk/clients/cognitoidentityserviceprovider"],t):"object"==typeof exports?exports.AmazonCognitoIdentity=t(require("aws-sdk/global"),require("aws-sdk/clients/cognitoidentityserviceprovider")):e.AmazonCognitoIdentity=t(e.AWSCognito,e.AWSCognito.CognitoIdentityServiceProvider)}'

**Comment by jeskew** [comment]
Hi @rainnaren,

Can you provide a bit more context on where you're running into this error and under what circumstances? Please include the runtime used, the version of that runtime, and which tools (if any) you're using to bundle.

**Comment by rainnaren** [comment]
hi @jeskew,

Iam using angularjs and the version of angularjs is 1.5.3 and the version of aws-sdk is 2.166.0 ,cognito version is 1.28.0 for bundling iam using the gulp that will minify the bower files only not npm

**Comment by jeskew** [comment]
I'm not able to reproduce using the SDK we host at `https://sdk.amazonaws.com/js/aws-sdk-2.166.0.min.js`. The following code logs an `Invalid Access Token` error (as would be expected if the code loads properly and is able to send a request to Cognito):

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.166.0.min.js"></script>
</head>
<body>
    <script>
        const cognitoIdp = new AWS.CognitoIdentityServiceProvider({
            region: 'us-west-2'
        });
        cognitoIdp.getUser({AccessToken: "fake-access-token"}, console.log);
    </script>
</body>
</html>
```

It sounds like you might be having issues bundling the SDK with the rest of the application hosting it. You can build a single file containing the AWS SDK and only the services you need to use at https://sdk.amazonaws.com/builder/js/

**Comment by nexeh** [comment]
@jeskew I have this same issue. Let me see if i can get you some information

**Comment by nexeh** [comment]
@jeskew Like the original poster i am adding cognito to an existing angular application. The key piece here is that it is NOT angular 2+ or using webpack. these were not popular when this application was created. So i have coped some piece of information from my bower.json and package json for you

```
"angular": "~1.5.3",
"aws-sdk": "^2.251.1",
"amazon-cognito-identity-js": "^1.31.0",
```

```
gulp": "~3.9.0",
    "gulp-autoprefixer": "~3.0.2",
    "gulp-angular-templatecache": "~1.8.0",
    "del": "~2.0.2",
    "lodash": "~3.10.1",
    "gulp-cssnano": "~2.1.1",
    "gulp-filter": "~3.0.1",
    "gulp-flatten": "~0.2.0",
    "gulp-eslint": "~1.0.0",
    "eslint-plugin-angular": "~0.12.0",
    "gulp-load-plugins": "~0.10.0",
    "gulp-size": "~2.0.0",
    "gulp-uglify": "~1.4.1",
    "gulp-useref": "~3.0.3",
    "gulp-util": "~3.0.6",
    "gulp-ng-annotate": "~1.1.0",
    "gulp-replace": "~0.5.4",
    "gulp-rename": "~1.2.2",
    "gulp-rev": "~6.0.1",
    "gulp-rev-replace": "~0.4.2",
    "gulp-htmlmin": "~1.3.0",
    "gulp-inject": "~3.0.0",
    "gulp-protractor": "~2.1.0",
    "gulp-sourcemaps": "~1.6.0",
    "gulp-ruby-sass": "~0.7.1",
    "gulp-angular-filesort": "~1.1.1",
```

I have been stuck on this issue for a few hours. It works fine when im running locally with just source files. Once i concatenate and minify it doesn't work any more. im by trying to get around it

**Comment by srchase** [comment]
@rainnaren 

Is this still an open issue for you?
