### ISSUE TITLE
Node script doesn't terminate on successful execution of SQS sendMessage

### ISSUE THREAD

**Issue by aniketdivekar** [aws/aws-sdk-js#1831]
I've written a script which iterates over array of objects and sends them to the specified SQS queue. But problem here is that my script doesn't terminate after successful execution. If I pass empty array, then the script ends. Only when it actually makes a call to enqueue message, the script doesn't terminate. Any help is appreciated. I'm using version `2.82.0`.

Here is a code snippet:
```
const AWS = require('aws-sdk')

let sqs = new AWS.SQS({
  apiVersion: '2012-11-05',
  region: '<some-region>'
})
```
Below code runs in loop:
```
const params = {
    QueueUrl: queueUrl,
    MessageBody: messageBody,
    DelaySeconds: options.delaySeconds,
    MessageAttributes: options.messageAttributes
  }

return sqs.sendMessage(params).promise()
```

I'm running my script using `npm run start-script`
`start-script: 'node runmyscript.js'` in package.json

The script sends all the messages successfully to the queue but doesn't terminate. **I don't want to use _process.exit(0)_ to manually terminate the script.** 
Am I missing anything here?

**Comment by jeskew** [comment]
Hi @aniketdivekar,

Does the process eventually terminate or does it hang forever? If the former is the case, my first guess would be that the pending promises created by calling `sqs.sendMessage(params).promise()` in a synchronous loop are competing for networking resources to send HTTP requests and then to wait for and process HTTP responses. How many requests are you sending concurrently, and is the script using the SDK with its default `maxConnections` setting of 50?

**Comment by srchase** [comment]
@aniketdivekar,

Do you have any further questions? If not, I'd like to close this issue.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
