### ISSUE TITLE
Docker login bad request when using authorizationToken returned from ECR.getAuthorizationToken()

### ISSUE THREAD

**Issue by bliu13** [aws/aws-sdk-js#1835]
I am able to use all the other functions, but when I run:
```
let AWS = require('aws-sdk');
let ecr = new AWS.ECR({
    apiVersion: '2015-09-21',
    accessKeyId: accessKeyId,
    secretAccessKey: secretAccessKey,
    region: (region === undefined || region === null) ? 'us-west-2' : region,
});

const childProcess = require('child_process');
let authParams = {};
ecr.getAuthorizationToken(authParams, function(err, data) {
  let login = null;
  if (/^win/.test(process.platform)) {
    // If Windows
    login = childProcess.spawnSync('cmd',
      ['/s', '/c', 'docker', 'login', '-u', 'AWS', '-p',
        AwsDockerAuth.authorizationData[0].authorizationToken,
        AwsDockerAuth.authorizationData[0].proxyEndpoint,],
      {env: process.env,
        stdio: 'pipe',
        encoding: 'utf-8',
      });
  } else {
    // If not Windows, and is a Unix-like environment
    login = childProcess.spawnSync('docker',
      ['login', '-u', 'AWS', '-p',
        AwsDockerAuth.authorizationData[0].authorizationToken,
        AwsDockerAuth.authorizationData[0].proxyEndpoint,],
      {env: process.env,
        stdio: 'pipe',
        encoding: 'utf-8',
      });
  }
});

console.log(login.output.toString());
```

The message I get is:

> ,,WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: login attempt to https://xxxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/v2/ failed with status: 400 Bad Request

I have no issues using aws cli where the authorization token actually works. Is the length of the authorization token the same for both aws cli and from getAuthorizationToken()? They have different lengths when I was debugging and counted the number of characters.

**Comment by jeskew** [comment]
Are you using the same encoding, proxy endpoint, and account/IAM role in both the AWS CLI and in the code snippet included above?

**Comment by bliu13** [comment]
Yes, they are the same. I am using the Access Key Id and the same Secret Access Key.
The one from AWS CLI gives me a password hash that is 1888 characters and the one from the SDK gives a hash that is much larger, around 2500 characters.

**Comment by jeskew** [comment]
Given the size difference, I would guess that the CLI is automatically decoding the authorization token. (The token is modeled as a base64-encoded string, so the decoded version would be ~75% of the size of encoded version.) Could you try first decoding the string?

**Comment by bliu13** [comment]
I think you are entirely correct, I reread the documentation more carefully and it says you have to base64 decode it.

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECR.html#getAuthorizationToken-property

Thank you for the help.
