### ISSUE TITLE
Sarissa is undefined. 

### ISSUE THREAD

**Issue by ashah1311** [aws/aws-sdk-js#1837]
I am trying to use svg4everybody in order to make svg icons work in salesforce. however , script throws error : "Object doesn't support property or method." I tried solving it using solution mentioned  [here](https://github.com/aws/aws-sdk-js/issues/491). However, when I added Sarissa code, it throws error that "Sarissa is undefined."

**Comment by chrisradek** [comment]
@ashah1311 
I think you've logged an issue to the wrong repository. This repo is for the `aws-sdk` npm package, not `svg4everybody` or `Sarissa`.

**Comment by ashah1311** [comment]
Sorry.
