### ISSUE TITLE
How to decrypted EC2 windows adm pass?

### ISSUE THREAD

**Issue by blablabla156** [aws/aws-sdk-js#1839]
Hello, I'm using the script on this issue (https://github.com/aws/aws-sdk-js/issues/166), I'm using the instance Id from the desktop information but it sill not working. I'm new to all of this and I would love some help. Every dependencies are installed.

**Comment by AllanFly120** [comment]
Hi @blablabla156, so you already have the encrypted password right? then do you see any error message when you run the decrypting script?

**Comment by blablabla156** [comment]
I'm getting the else response.

**Comment by AllanFly120** [comment]
Hey @blablabla156,
It seems like you didn't retrieve the ec2 windows password data successfully. Can you show me your error response? Just change the code `console.log("Could not get the encrypted password");` to `console.log(err);`

**Comment by jeskew** [comment]
@blablabla156 Are you able to get your login password using the .pem file decryption built into the AWS console? If not, then the file is likely corrupted somehow.

**Comment by blablabla156** [comment]
Sorry for the long time no answer. I had to take an emergency travel of 20 days and I'm back at home today. Really sorry for this, I'm going to answer tomorrow or in a couple of hours.

**Comment by blablabla156** [comment]
Okay, got this after changing 

> console.log("Could not get the encrypted password"); to console.log(err);

https://imgur.com/nJLqJpe

**Comment by jeskew** [comment]
@blablabla156 Sorry for the delay in replying; the error screenshot posted indicates that no region was provided, and the call to EC2's [GetPasswordData operation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_GetPasswordData.html) could not be initiated. Make sure to set the region on the EC2 client instance by providing that argument to the constructor:

```javascript
const ec2 = new AWS.EC2({
    region: 'us-west-2', // replace with the region in which the EC2 instance is located
});
```
