### ISSUE TITLE
describeAutoScalingGroups return wrong LaunchConfigurationName

### ISSUE THREAD

**Issue by Bang-Kwangmin** [aws/aws-sdk-js#1840]
LaunchConfigurationName : A , B

my "test-ASG" has some instances created by A launchconfiguration.
In this state, Even if  I change LaunchConfiguration from A to B via updateAutoScalingGroup() or AWS web console, below describeAutoScalingGroups function still return LaunchConfigurationName A.
However, I can see launchConfiguration B on AWS web console.
And updateAutoScalingGroup returned success message.

// Describe AutoScalingGroup Info
var params = { AutoScalingGroupNames: [ "test-ASG" ] };
autoscaling.describeAutoScalingGroups(params, function(err, data)

// Update LaunchConfiguration
var params = {  AutoScalingGroupName: "test-ASG",
                        LaunchConfigurationName: "B"};
 autoscaling.updateAutoScalingGroup(params, function(err, data)

Please help me. Thank you in advance.

**Comment by Bang-Kwangmin** [comment]
@AllanFly120 Thank you for your response.
But, I think this issue is not related with async call.

It's NOT about the case that updateAutoScalingGroup() and describeAutoScalingGroups() are called continuously.
Even if wait few minutes after updating launch config(A->B) on AWS web console, describeAutoScalingGroups() api returns always launch_config A.

You can test like below senario :
1. test-ASG has a instance created by launch_config A.
2. describeAutoScalingGroups() return launch_config A.
3. change launch_config from A to B via updateAutoScalingGroup() or AWS web console.
4. AWS web console shows launch_config B. !!!
5. describeAutoScalingGroups() still returns launch_config A .
   Even if trying many times, it's not changes.

6. create 2 or more instance created by launch config B in test-ASG. now test-ASG has 2 B, 1 A.
7. AWS web console show launch config B. 
8. Fianally, describeAutoScalingGroups() also return launch config B.

**Comment by Bang-Kwangmin** [comment]
In same situation, boto3 describe_auto_scaling_groups api return B.
only JS api returns the launch config name of the most-used launch config for instances in ASG.

**Comment by AllanFly120** [comment]
@Bang-Kwangmin Sorry, I cannot reproduce this issue. Actually, both Python and JS SDK don't tune the request, so they shouldn't behave differently. Could you check whether you are using the correct account and region?
