### ISSUE TITLE
CloudwatchLogs GetLogEvents doesn't respect startFromHead parameter

### ISSUE THREAD

**Issue by kensaggy** [aws/aws-sdk-js#1841]
Using the latest SDK (version 2.172.0) and NodeJS version 6.10.1 it seems like the CloudWatch Logs API doesn't respect the `startFromHead` flag.

Here's a short example to demonstrate the issue.
I'm making 2 identical calls, except for the `startFromHead` parameter - and both return same results (=the assertion passes) even though you'd expect it to fail

```js
const aws = require('aws-sdk')
const Promise = require('bluebird')
const assert = require('assert')

aws.config.setPromisesDependency(Promise)

const cloudwatchlogs = new aws.CloudWatchLogs({apiVersion: '2014-03-28'})

const params1 = {
  logGroupName: 'my-log-group',
  logStreamName: '***************',
  startFromHead: false
};

const params2 = {
  logGroupName: 'my-log-group',
  logStreamName: '***************',
  startFromHead: true
};

const headStart = cloudwatchlogs.getLogEvents(params1).promise()
const tailStart = cloudwatchlogs.getLogEvents(params2).promise()
Promise.join(headStart, tailStart, (head, tail) => {
  /* uncomment for a more eye pleasing display of line comparison :) 
  for (let i = 0; i < head.events.length; i++){
    console.log(head.events[i].message)
    console.log(tail.events[i].message)
  }
  */
  assert.deepEqual(head, tail)
})
```

**Comment by AllanFly120** [comment]
Hi @kensaggy I don't have much experience on CloudwatchLogs. Since the SDK doesn't alternate any parameter in the request, this might be issue from service team. You can directly ask the service team on [their forum](https://forums.aws.amazon.com/forum.jspa?forumID=138).
