### ISSUE TITLE
CognitoIdentityServiceProvider.listUsers() AccessDeniedException

### ISSUE THREAD

**Issue by kevindavee** [aws/aws-sdk-js#1843]
hi,

I need to get list of users in a user pool. I call this API when my user is authenticated.

```
const serviceProvider = new CognitoIdentityServiceProvider()

serviceProvider.listUsers(parameters, (err, data) => {
      console.tron.log(err)
      console.tron.log(data)
 })

```

It didn't return any data but the error message says

`CognitoIdentityCredentials is not authorized to perform: cognito-idp:ListUsers on resource: XXXX`

Is there anything wrong with my code ? Please help me and let me know if I need to provide more code thanks

**Comment by chrisradek** [comment]
@kevindavee 
What does your role policy look like? Based on your error message, it sounds like your policy doesn't have the required permissions. Assuming you've configured your credentials prior to instantiating your serviceProvider, I don't see anything weird about your code.

**Comment by kevindavee** [comment]
@chrisradek the problem is I can't find `listUsers` action under any amazon cognito userpools permissions

<img width="1190" alt="screen shot 2017-12-27 at 09 16 39" src="https://user-images.githubusercontent.com/28204154/34368466-ce01fdcc-eae6-11e7-98cd-e6c1ee3fa765.png">

**Comment by chrisradek** [comment]
@kevindavee 
Can you reach out to the Cognito team on the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=173)? If you post a link here to your forum post I can forward the message to the team internally as well. Unfortunately there isn't anything we can do on the SDK side for this issue.

**Comment by PedrooBritoo** [comment]
I have the same problem.

**Comment by aventurella** [comment]
Just do I could test, I granted all permissions. When I manually add 

```
"cognito-idp:ListUser"
```
OR

```
"cognito-idp:ListUsers"
```

As the Action to allow in the policy, it tells me I'm crazy. I can only seem to use `"cognito-idp:*"

**Comment by chrispaynter** [comment]
I'm also having this problem. I'm using the wildcard for now, but this really needs to be fixed.

**Comment by jessedoyle** [comment]
> I'm also having this problem. I'm using the wildcard for now, but this really needs to be fixed.

I just wanted to add that we were experiencing the same problem.

We had to add the following permissions to successfully list users:

* `cognito-idp:ListUsers`
* `cognito-idp:ListUsersInGroups`

Just trying to help out anyone who may be encountering the same issue!
