### ISSUE TITLE
getObject() not append http authorization header in safari 9

### ISSUE THREAD

**Issue by RoyLiou** [aws/aws-sdk-js#1845]
Hi, everyone
I want to visit s3 to fetch files via S3.getObject.
If use safari 11 ,which no problem but use version 9.0.2 is failed
Does anyone have this issue?

operating system: OS X 10.9
browser: safari 9.0.2

**Comment by chrisradek** [comment]
@RoyLiou 
What error are you getting when calling getObject?

**Comment by srchase** [comment]
@RoyLiou,

Do you have any   further questions? If not, I'd like to close this issue.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
