### ISSUE TITLE
X-Ray captureAWSClient DynamoDB DocumentClient didn't work

### ISSUE THREAD

**Issue by polovi** [aws/aws-sdk-js#1846]
Is there some workaround for capture DocumentClient with xray except capture whole SDK?
Due to creating custom [service provider](https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/document_client.js#L99-L102) this code didnt work.

```JavaScript
const AWSXray = require('aws-xray-sdk')
const AWS = require('aws-sdk')
 
const client = new AWS.DynamoDB.DocumentClient({
  service: AWSXray.captureAWSClient(new AWS.DynamoDB({...}))
})
```
If service from configuration will be used as it is and not created again then captureAWSClient will be work. I also set everything up in my service and no configuration params ar pushed to DocumentClient constructor

**Comment by chrisradek** [comment]
@polovi 
A possible workaround would be to wrap the service client after you've created the `DocumentClient`.

```javascript
const AWSXray = require('aws-xray-sdk');
const AWS = require('aws-sdk');

const client = new AWS.DynamoDB.DocumentClient({
  service: new AWS.DynamoDB({...})
});

AWSXray.captureAWSClient(client.service);
```

**Comment by polovi** [comment]
@chrisradek 
Seems that `AWSXray.captureAWSClient(client.service)` works as workaround

But there is problem if i use  typescript that AWS.DynamoDB.DocumentClient.service is internal and not defined in d.ts file so I am not able to compile it
