### ISSUE TITLE
Cognito Pool web identity does not have permission to put events to Kinesis

### ISSUE THREAD

**Issue by washcapsfan37** [aws/aws-sdk-js#1849]
I have created an unauthorized Federated Identity Cognito pool with the permission to write to Kinesis.  The attached policy to the Cognito Pool unauthenticated Role is:

    {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "kinesis:PutRecords"
            ],
            "Resource": [
                "arn:aws:kinesis:*:MY_ACCOUNT_ID:stream/diagnostic",
                "arn:aws:kinesis:*:MY_ACCOUNT_ID:stream/events"
            ]
        }
    ]
    }

From my Android app, I can put events to the two streams using the KinesisRecorder and the CognitoCachingCredentialsProvider linked to my Cognito Pool.  Now I am trying to duplicate this in NodeJS Lambda using [this blog](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/kinesis-examples-capturing-page-scrolling.html) as an example.

    let AWS = require("aws-sdk");
    AWS.config.region = 'us-east-1';
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: 'us-east-1:MY_COGNITO_POOL_ID'
        //RoleSessionName: 'web'
        // RoleArn: 'arn:aws:iam::MY_ACCOUNT_ID:role/MY_COGNITO_POOL_ROLE_ARN'
    });
    AWS.config.credentials.get(function (err) {
        if (err) {
            callback(err);
            return;
        }
        console.log(`Cognito ID => ${AWS.config.credentials.identityId}`);

        let kinesis = new AWS.Kinesis({apiVersion: '2013-12-02'});
        let eventData = getEvent();
        let params = {
            Data: new Buffer(eventData),
            PartitionKey: uuidv1(),
            StreamName: 'events'
        };
        kinesis.putRecord(params, function (err, data) {
            if (err) {
                callback(err);
                return;
            }
            callback(null, "Succeeded");
        });
    });

When I invoke this, I receive the following error:

    User: arn:aws:sts::MY_ACCOUNT_ID:assumed-role/MY_COGNITO_POOL_ROLE_ARN/web-identity is not authorized to perform: kinesis:PutRecord on resource: arn:aws:kinesis:us-east-1:MY_ACCOUNT_ID:stream/events (RoleArn set)

    User: arn:aws:sts::MY_ACCOUNT_ID:assumed-role/MY_COGNITO_POOL_ROLE_ARN/CognitoIdentityCredentials is not authorized to perform: kinesis:PutRecord on resource: arn:aws:kinesis:us-east-1:MY_ACCOUNT_ID:stream/events (RoleArn not set)

Note: I have tried this with and without the 'RoleSessionName' and 'RoleArn' set.

I validated the unauthenticated role the Cognito pool uses has permission to write to the stream, and my Android app which uses the same pool has no issues writing to the stream.  What am I doing wrong?

**Comment by chrisradek** [comment]
@washcapsfan37 
Does your android app call `kinesis.putRecords` or `kinsesis.putRecord`? Your IAM policy looks like it specifically allows the `kinesis:PutRecords` action, but in your example, you're calling the singular version of the operation. Can you also add `kinsesis:PutRecord` to your policy, or update your code to use `PutRecords` and see if that fixes the issue?

**Comment by washcapsfan37** [comment]
The android app uses KinesisRecorder.saveRecord() which (apparently) uses PutRecords under the hood.  When I added "kinesis:PutRecord" to the IAM Role it worked.  D'oh.
