### ISSUE TITLE
putObject can be called 2 times and 1 of them fail by Forbidden error

### ISSUE THREAD

**Issue by kyasbal-1994** [aws/aws-sdk-js#1852]
I've tried to putObject with aws-sdk-js.  I have confirmed that I could correctly upload that file.
However,  non neccessary 403 Forbidden error is shown. It seems PUT request is fired 2 times for each `putObject`.

![](https://i.gyazo.com/f774bcc234d03b23230f26c3a95e991e.png)

This is detail of PUT request which is successed part of the request.

![Screenshot from Gyazo](https://gyazo.com/1a862bf6210dbd74e6014328ab8a48a1/raw)

And this is another part of the request.( Failed part)

![](https://i.gyazo.com/d0536b59fbcb789f2458aac79833a88b.png)

Even redundant request is fired everytime when I need to request putObject, It works for me. It is OK for now. But it is something weired. Is this desired behaviour?

**Comment by jeskew** [comment]
Can you post the code snippet that is calling the SDK? Only one PUT request should be sent, but the application using the SDK may be inadvertently sending the request returned by PutObject twice.

**Comment by kyasbal-1994** [comment]
@jeskew This is snippet calling putObject.

```ts
    public async setMetadata(key: string, meta: { [key: string]: any }): Promise<void> {
        if (this.currentIndex === -1) {
            return;
        }
        try {
          // A
            await ai.putObject({
                ...bucketConfiguration,
                Key: `${key}/${this.nameList[this.currentIndex]}.json`,
                Body: JSON.stringify(meta),
                ContentType: "application/json",
                ContentEncoding: "utf-8",
                Tagging: "annotationType=" + key
            }, () => { }).promise();
       // B
        } catch (e) {

        }
    }
```

The variable `bucketConfiguration` is an object containing `Bucket` property. In my code, there is no other code using putObject API. And I confirmed that this API is surely called one time when I send request.

Therefore, when I put `debugger` on A(commented on the snippet), there is no any request in Network devtool on Chrome. But, I get 4 requests(including 2 pre-flight OPTIONS request) is fired when I put `debugger` on B.

**Comment by jeskew** [comment]
You'll want to remove the callback being passed to `bucket.putObject`. Both providing a callback and calling `.promise()` will cause the request to be sent, so the request is being sent twice.
