### ISSUE TITLE
Insecure Randomness: Affecting crypto-browserify package, versions <2.1.11

### ISSUE THREAD

**Issue by danieljoppi** [aws/aws-sdk-js#1853]
`crypto-browserify` is implementation of crypto for the browser.

Affected versions of the package are vulnerable to Insecure Randomness due to using the cryptographically insecure `Math.random()`. This function can produce predictable values and should not be used in security-sensitive context.

You can read more about node's insecure `Math.random()` in [Mike Malone's post](https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d)

**Comment by hakanson** [comment]
I also saw this when running `snyk test` on a project.

```
$ snyk test
✗ High severity vulnerability found on crypto-browserify@1.0.9
- desc: Insecure Randomness
- info: https://snyk.io/vuln/npm:crypto-browserify:20140722
- from: redacted@0.0.1 > alexa-sdk@1.0.24 > aws-sdk@2.85.0 > crypto-browserify@1.0.9
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.
```

**Comment by jeskew** [comment]
Hi @danieljoppi and @hakanson,

The result you encountered is a false positive. The AWS SDK for JavaScript uses Node's `crypto` module (polyfilled with `crypto-browserify` in the browser SDK) to perform MD5 and SHA-256 hashing when signing requests and does not use it to directly perform any encryption, decryption, or random generation. The only time `Math.random` could be called is when UUIDs are generated for use as idempotency tokens in browsers that do no support WebCrypto's [`RandomSource.getRandomValues`](https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues) method.

Closing as a duplicate of #1602
