### ISSUE TITLE
AWS.WorkMail is not a constructor

### ISSUE THREAD

**Issue by paulfryer** [aws/aws-sdk-js#1855]
Trying to use WorkMail client in NodeJS Lambda function in the AWS console, using the most simple example pulled right from the online docs:

```
var AWS = require('aws-sdk');
var workmail = new AWS.WorkMail({apiVersion: '2017-10-01'});

exports.handler = (event, context, callback) => {
};
```
Getting error:

```
{
  "errorMessage": "AWS.WorkMail is not a constructor",
  "errorType": "TypeError",
  "stackTrace": [
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}
```
Online Docs: 
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/WorkMail.html

**Comment by jeskew** [comment]
Hi @paulfryer,

The copy of the SDK provided by Lambda is currently [version 2.143.0](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html), whereas support for AWS.WorkMail was only [added in version 2.169.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#21690).

You can bundle a newer version of the SDK in your Lambda function by following the instructions [here](https://github.com/aws/aws-sdk-js/issues/765#issuecomment-152033324).

**Comment by paulfryer** [comment]
Yep, that did it. Thanks @jeskew !
