### ISSUE TITLE
Dynamodb: "Supplied AttributeValue is empty" error ,though all fields are filled in  iOS swift

### ISSUE THREAD

**Issue by Manan0510** [aws/aws-sdk-js#1861]
func createNews() {
        let dynamoDbObjectMapper = AWSDynamoDBObjectMapper.default()
        
        // Create data object using data models you downloaded from Mobile Hub
        let newsItem: News = News()
        
        newsItem._userId = AWSIdentityManager.default().identityId
        newsItem._articleId = "MyArticleId"
        newsItem._title = "MyTitle"
        
        //Save a new item
        dynamoDbObjectMapper.save(newsItem, completionHandler: {
            (error: Error?) -> Void in
            
            if let error = error {
                print("Amazon DynamoDB Save Error: \(error)")
                return
            }
            print("An item was saved.")
        })
    }

**Comment by jeskew** [comment]
Hi @Manan0510,

You'll need to raise this issue with on [the AWS SDK for iOS repository](https://github.com/aws/aws-sdk-ios); this repo only houses the AWS SDK for JavaScript.
