### ISSUE TITLE
Unable to use Range header for small files

### ISSUE THREAD

**Issue by eyalcohen7** [aws/aws-sdk-js#1862]
I am using the aws s3 sdk in my project to download partial files from s3.  For this I am using a Range request:
params = {
    Bucket: 'my-bucket',
    Key: '/path/to/my/file',
    Range: 'bytes=0-100000'
}
s3.getObject(params, (err, data) => {
...
});

This works fine for files which are bigger than 100,000 bytes. However, when I try to download a file which is less than 100,000 bytes, I get an error: "The request signature we calculated does not match the signature you provided. Check your key and signing method."

Unfortunately, I don't know the file size in advance and would like to avoid making another round-trip to get that information.    

Some notes:
1. If I enable the 'Disable-Cache' checkbox in the developer console, this seems to work with no issues.
2. When I looked at the actual request being sent to AWS, it seems like somehow, the Range header is changing to the "correct" value (i.e. "bytes=0-75433", the actual file size)... so I suspect that the signer is signing the request with a Range header of "bytes=0-100000" while the actual header sent is different, hence the error...

Thanks!

**Comment by eyalcohen7** [comment]
Does anyone has an idea what's the issue?  We are stuck with this and unable to use the sdk as a result...

Thanks.

**Comment by jeskew** [comment]
@eyalcohen7 As far as I know, there's nothing in the SDK that would modify the range header, so my hunch is that the modification is being performed by Chrome's HTTP agent. Do you see Chrome sending a GET request with the truncated range and an `If-None-Match` header when the object is already in Chrome's HTTP cache?

**Comment by eyalcohen7** [comment]
I indeed see Chrome's sending a GET request with the truncated Range, I assumed the SDK somehow changed that value, but I guess this is not the case. I also see the If-None-Match header:

Here's a the relevant portion of the HTTP request from chrome: (The range I am requesting is 0-10000 in this example):
If-Modified-Since:Wed, 17 Jan 2018 15:53:33 GMT
If-None-Match:"956efcee3a5bd0420019d1c77ccb569a"
Range:bytes=0-57043

Is there anyway to prevent chrome from doing that?

**Comment by jeskew** [comment]
That seems like a bug in Chrome... if you requested the first 100,000 bytes of a file, the fact that the first 57,043 bytes have not changed does not necessarily mean the object is still 57,043 bytes long. Let me see if there's a related bug report in Chrome (which might list some workarounds).

For S3 specifically, if a file was uploaded using a multipart upload, you could download those parts individually instead of downloading a range. You would need to provide a `PartNumber` parameter as described on https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property The numbered object parts are the same parts that were uploaded with each `UploadPart` operation.

**Comment by jeskew** [comment]
I wasn't able to find a relevant bug in Chrome, but do you see similar behavior in other browsers?

**Comment by eyalcohen7** [comment]
I was unable to reproduce this on Safari or Firefox - it seems taht both send the request with the correct Range...however both browsers don't have the If-None-Match header (or other cache related headers).

**Comment by srchase** [comment]
@eyalcohen7,

This appears to be a chrome-specific issue.  Were you able to get it resolved since then?

**Comment by eyalcohen7** [comment]
No, I wasn't able to solve this issue. I ended up requesting the first chunk (100K for example) and if I get a SignatureError message I request it again, but without the range header, so the second request works).

Please note that I am not monitoring the code, so I don't know if this error still happens.
