### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_0_aws_sdk_global__.util.crypto.lib. randomBytes is not a function

### ISSUE THREAD

**Issue by dfrkp** [aws/aws-sdk-js#1867]
Hi, 
me and multiple other people are right now stuck on version 2.177.0.
See:
https://stackoverflow.com/questions/48160979/global-util-crypto-lib-randombytes-is-not-a-function-error/48164887

In my case I'm using aws-amplify and with 2.178.0 cognito sign in starts to fail with
```
__WEBPACK_IMPORTED_MODULE_0_aws_sdk_global__.util.crypto.lib.
randomBytes is not a function
```

**Comment by mszu** [comment]
As per [this comment](https://stackoverflow.com/questions/48174252/util-crypto-lib-randombytes-is-not-a-function-aws-cognito-js-throws-error-on#comment83329253_48174450) on one of the related questions linked to the SO post above, the commit where this behavior was introduced is 0638060402931f572f9f75d77a12bd6c529b0424

**Comment by AllanFly120** [comment]
Sorry for the late reply. This is due to cognito identity SDK depends on one of private functions of our SDK. You can go to here to follow the issue: https://github.com/aws/amazon-cognito-identity-js/issues/646

**Comment by srchase** [comment]
Closing at this was handled in the thread on Cognito Identity.
