### ISSUE TITLE
add a version of S3.listObjectsV2 that returns more than 1000 objects

### ISSUE THREAD

**Issue by MeBNoah** [aws/aws-sdk-js#1870]
Right now if you want to list more than 1000 objects out of a S3 bucket you have to build your own mechanism that returns all objects because listObjectsV2 is limited to 1000 objects. IMHO the sdk should provide either a separate function that returns all of the objects, or the existing functionality should be extended (by using a flag for example) in order to provide that. 

What do you guys think of that?

**Comment by jeskew** [comment]
Hi @MeBNoah,

`ListObjectsV2` is a pageable operation, so you can traverse all the objects in a bucket using the [`eachPage` method](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#eachPage-property) on the request returned by `s3.listObjectsV2(params)`.

**Comment by MeBNoah** [comment]
Hi @jeskew 

thank you so much for the info. I couldn't find that solution anywhere on the interwebs.

Cheers 
Noah
