### ISSUE TITLE
Not able to catch error from AWS sdk [S3]

### ISSUE THREAD

**Issue by amitdhawan** [aws/aws-sdk-js#1871]
Im trying to download a file from S3 which doesn't exist on S3. I expect a error in this scenario and im also getting that error from aws-sdk i.e.

**/vagrant/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

NoSuchKey: The specified key does not exist.**

But the issue is, im not able to catch this error. If you check the code below, my listener request.on gets called and when i call reject in that the promise doesn't return from method downloadFontInfoFileFromS3 with reject.

Is there any way i can catch the error and gracefully reject the promise from downloadFontInfoFileFromS3 function?

```
downloadFontInfoFileFromS3(fileKey) {
        return new Promise((resolve, reject) => {
            const sThree = new awsSDK.S3();
            const options = {
                Bucket: awsConf.bucket,
                Key: fileKey,
            };
            const downloadFilePath = SOME_PATH
            const file = fs.createWriteStream(downloadFilePath);

                const request = sThree.getObject(options);

                const download = request
                    .createReadStream().pipe(file);

                // called when error in aws-sdk
                request.on('error', (error) => {
                    logger.error('Failed to download file from S3:', error.message);
                    reject(error);
                });

                download.on('error', (error) => {
                    reject(error);
                });

                download.on('finish', () => {
                    resolve(downloadFilePath);
                });
                // the synchronous code that we want to catch thrown errors on
        });
    }
```

**Comment by AllanFly120** [comment]
It seems like you can do what like below to use callback on `error` event but not when you are using `request.createReadStream()`. I will investigate it later.
```javascript
var request = s3.getObject(params);
request.on('error', (error) => {
    console.log('Failed to download file from S3:', error.message);
});
request.send();
```
If you just want to promisify this function, the SDK already provided much easier way to accomplish it:
```javascript
function downloadFontInfoFileFromS3(fileKey) {
    var s3 = new AWS.S3();
    const options = {
        Bucket: awsConf.bucket,
        Key: fileKey,
    };
    const downloadFilePath = SOME_PATH
    return s3.getObject(options).promise()
        .then(data => {
            var body = data.Body;
            fs.writeFileSync(SOME_PATH, body, {encoding: 'utf8'})
        })
}
downloadFontInfoFileFromS3().catch(err => console.log(err));
```

**Comment by amitdhawan** [comment]
Hey Allan,

I did use promise for the getObject function but still get the crash. Also using writeFileSync will not work for large files to be written.
And i tried using callback for getObject in which case I cannot use createReadStream which is the preferred way to read and write large files.

Please suggest.

**Comment by amitdhawan** [comment]
@AllanFly120  Any updates on this?
