### ISSUE TITLE
DynamoDB presigned URL returns error

### ISSUE THREAD

**Issue by gerhardberger** [aws/aws-sdk-js#1875]
I'm attempting to create a presigned URL for a DynamoDB query. I can successfully obtain one with the `sign` method of the `AWS.Signers.Presign` class, but the url returns locally a 404 HTTP error.

Is there some extra configuration needed to successfully run the request?

While I know presigning DynamoDB queries are not publicly documented, this is the only solution I found for my usecase, which is accessing a DynamoDB resource, without the AWS credentials.

**Comment by gerhardberger** [comment]
The presigned url looks like this (the request body has a json DynamoDB query):
```
POST https://dynamodb.eu-central-1.amazonaws.com

Content-Type:application/x-amz-json-1.0
X-Amz-Target:DynamoDB_20120810.Query
X-Amz-Date:20180113T154227Z
X-Amz-Expires:3600
X-Amz-Security-Token: XXXXXXXX
Authorization:AWS4-HMAC-SHA256 Credential=XXXXXX/20180113/eu-central-1/dynamodb/aws4_request, SignedHeaders=host;x-amz-target, Signature=XXXXX
```

However making this request results in `InvalidSignatureException`.

A took a look at Cognito and it looks quite fitting for my use case! But it is not yet clear to me, that whether is it a good practice to commit an `IdentityPoolId` in your code. Am I correct that this would be the only thing needed to access DynamoDB from a client application?

**Comment by jeskew** [comment]
The `IdentityPoolId` would be sufficient to access DynamoDB only if you grant access to unauthenticated identities and if the IAM role assumed for unauthenticated users has read permissions on the DynamoDB table. There's a good guide to setting up an identity pool and configuring how you want that pool to authenticate users available [here](https://docs.aws.amazon.com/cognito/latest/developerguide/getting-started-with-identity-pools.html)

**Comment by srchase** [comment]
I'm going to close out this issue, as it looks like it was resolved.  Let us know if you have any further questions.
