### ISSUE TITLE
React-Native release builds fail to find main.bundle.js

### ISSUE THREAD

**Issue by aaronallan** [aws/aws-sdk-js#1882]
**node:** 8.9.1
**npm:** 5.5.1
**react-native:** 0.51.0
**react:** 16.0.0
**aws-sdk-js:** 2.182.0

What is the correct way to use this library with RN? Currently, I am able to compile iOS and Android apps in debug.  However, in release they fail when they attempt to bundle the js and assets.  I am importing like so:

`import { CognitoIdentityCredentials, SNS, config } from 'aws-sdk/dist/aws-sdk-react-native';`

Using `v2.182.0` my app hangs for a long time and ultimately fails to find main.bundle.js.

When building with https://github.com/aws/aws-sdk-js/pull/1868/commits/ff2e841ef3ecbb9ae67043adfe602fafb587b020, my app compiles. However, the associated PR was closed a few days ago.

https://github.com/aws/aws-sdk-js/pull/1618 led me to believe I could import like so:

`import { CognitoIdentityCredentials, SNS, config } from 'aws-sdk'`

However, using `v2.182.0` my release build quickly fails as it is unable to find main.bundle.js

**Comment by chrisradek** [comment]
@aaronallan 
You should no longer have to import from `aws-sdk/dist/aws-sdk-react-native`.
To get smaller bundles, you can instead import individual services/global namespace similar to the documentation [here](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/webpack.html#webpack-importing-services).

Example:
```javascript
import {config, CognitoIdentityCredentials} from 'aws-sdk/global';
import * as SNS from 'aws-sdk/clients/sns';
```

Your last example should also work, but there was a bug introduced in v2.178.0 of the SDK that was causing problems when bundling the SDK in react native. #1880 fixes that issue and was just merged yesterday. It will be in the next version of the SDK that should ship today.

For now, can you pin your version of the SDK to 2.177.0 to verify what you're trying works? If it doesn't, there may be a different issue than what #1880 addresses.

**Comment by aaronallan** [comment]
@chrisradek thank you for the clarification and quick response. v2.177.0 works as expected. I'll keep an eye out for the next release. Thanks again.

**Comment by chrisradek** [comment]
Closing, since the code change from the PR is available in the latest version of the SDK. Please let us know if you still encounter this issue after upgrading.
