### ISSUE TITLE
DynamoDB scan is not using the page-size for pagination

### ISSUE THREAD

**Issue by erwineverts** [aws/aws-sdk-js#1884]
I am using the scan property for a potential large dynamoDb table and I would like to add pagination to my view. Old data is not really relevant so I would like to add a filter to the scan.

Normally I would add a limit and it would work, but the limit is executed before the filter and therefore sometimes return an empty result. Then I come to the pagination part of the scan (also linked below) that adds a PageSize or --page-size to the scan parameters. When I then execute the scan, it seems that the page size is ignored and will get the full result as if the parameter was not there.

Could anybody help me with this issue? 

DynamoDb scan function:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#scan-property

Link to the working of scan pagination. (is referenced by the above link)
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.Pagination

**Comment by jeskew** [comment]
Hi @erwineverts,

DynamoDB's `Scan` operation does not have a `PageSize` input parameter; `Limit` is used to control the size of pages returned. The CLI aliases this parameter to `--page-size`, but the API defines it as `Limit`.

**Comment by erwineverts** [comment]
Thanks for your reaction @jeskew!
The problem I was having was that with the Limit, the limit is first taken into account and then the filters/expressions. In that case if I would search for example status equals open with a limit of 5 and the fist 4 items have a status closed, I get only 1 result. 

Is there a workaround on this issue?

**Comment by jeskew** [comment]
The only workaround would be to continue paging through scan results until you have gotten all the results you need. 

My understanding is that what `Limit` technically does is restrict the number of reads performed so that you consume a bounded number of read capacity units during a single scan or query operation; this has a side effect of limiting the number of results returned, but as you point out, filters are applied after the items have been read.

**Comment by napikle** [comment]
Any ways to over come this issue of first limiting then adding filter ?

**Comment by AllanFly120** [comment]
Hi @napikle 
This issue is on the service end, I'm afraid SDK cannot do much mitigation. You can raise this issue on the [DynamoDB forum](https://forums.aws.amazon.com/forum.jspa?forumID=131), the DynamoDB service will notice it.
