### ISSUE TITLE
function startCelebrityRecognition not found...

### ISSUE THREAD

**Issue by gohackfelipe** [aws/aws-sdk-js#1885]
Hi there,

I tried to use the function startCelebrityRecognition and I got this error:

TypeError: rekognition.startCelebrityRecognition is not a function

It looks like that the function really does not exist in the class Rekognition (rekognition.d.ts).

**Comment by chrisradek** [comment]
@gohackfelipe 
What version of the SDK are you using? `startCelebrityRecognition` became available in 2.159.0.

**Comment by gohackfelipe** [comment]
Yeahh I am using the 2.141.0. So we found the problem...

**Comment by chrisradek** [comment]
Excellent! I'm closing this issue then, let us know if you still encounter problems after upgrading the SDK.

**Comment by gohackfelipe** [comment]
But there's a issue with npm repository beacuse when i use the command npm install aws-sdk it consider as the 2.159.0 as last version ..

**Comment by chrisradek** [comment]
Does your package.json have a version specified for the SDK?

Can you try installing it in a fresh project and verifying what version of the SDK you get? I'm currently seeing v2.185.0 when I install from npm.
