### ISSUE TITLE
Fetch userData on EC2 machine boot up issue

### ISSUE THREAD

**Issue by amitdhawan** [aws/aws-sdk-js#1886]
I have a Lambda which triggers the EC2 machine to spin up, using the ami-Id. When the lambda executes it also sends some userData to the EC2 machine instance which will be started.

Now, when i try to fetch the userData in the nodeJs code that will be executed on the EC2, it returs status 200 but the response body is empty.

Im using the api "http://169.254.169.254/latest/user-data" with superagent npm module to make the request. Below is the code for request:

```
request.get(config.awsUserDataUrl)
        .then((response) => {
            const schema = joi.object().keys({
                bucketname: joi.string().min(3).max(30).required(),
                // alphanumeric string of 24 characters in length
                jobid: joi.string().regex(/^[0-9a-fA-F]{24}$/),
                appid: joi.string().min(3).max(30).required(),
                snstopic: joi.string().min(3).max(60).required(),
                filepath: joi.string().min(3).max(60).required(),
            });
            logger.info('response', JSON.stringify(response.body));
            logger.info('response.body', response.body);
            logger.info('response.status', response.status);
            const result = joi.validate(response.body, schema);
            if (result.error === null) {
                logger.info('result', result);
                resolve(response.body);
            } else {
                logger.info('result.error', result.error);
                reject(result.error);
            }
        })
        .catch((err) => {
            logger.info('err.message', err.message);
            logger.info('err.response', err.response);

            // err.message, err.response
            reject(err);
        });
```

Note: I have not assigned any IAM role for EC2 in Lambda environment variable. 

Can the issue of not getting the response userData in EC2 be due to Role not assigned to EC2?

Im abe to get the user data in Curl on terminal when login in Ec2 machine also i can see the userData being successfully set on the AWS Ec2 console only issue is im not able to fetch it in my code.

**Comment by chrisradek** [comment]
@amitdhawan 
Please reach out to the EC2 team on their forums [here](https://forums.aws.amazon.com/forum.jspa?forumID=30). Since your question is about how to access EC2 UserData from a script, you should be able to get better info there.
