### ISSUE TITLE
Error TS1128

### ISSUE THREAD

**Issue by danielrambo** [aws/aws-sdk-js#1888]
Hi!

When I compile my project the following error occurs: node_modules / aws-sdk / index.d.ts (7,1): error TS1128: Declaration or statement expected.

Note: Use typescript.

How can I solve?

**Comment by chrisradek** [comment]
@danielrambo 
Can you share a code sample that triggers this error, and which version of TypeScript you are using?

**Comment by danielrambo** [comment]
example code:
import amazon = require("aws-sdk")

I'm using a version 2.6.2

**Comment by danielrambo** [comment]
My tsconfig.json:
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": false,
    
    "rootDir":"src",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true
  },
  "exclude": [
    "node_modules"
  ]
}


Yes, I had tried to change the import syntax.

**Comment by srchase** [comment]
@danielrambo 

Were you able to get this sorted?  If there are not further questions, I'm going to close out this issue.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
