### ISSUE TITLE
Unable to create an SQS FIFO queue, using the JS SDK

### ISSUE THREAD

**Issue by thecodejunkie** [aws/aws-sdk-js#1889]
Hi,

## Description

I'm trying to create an SQS FIFO queue, from a Node application using the JS SDK. I've attempted to do it in `eu-west-1`, which according to this [release announcement](https://aws.amazon.com/about-aws/whats-new/2017/06/amazon-sqs-fifo-queues-are-now-available-in-the-us-east-n-virginia-region/) should be supported.

According to the [createQueue](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#createQueue-property) documentation and, more specifically, the `QueueName` parameter

> A FIFO queue name must end with the `.fifo` suffix.

I have verified that `aws.config` has the region set to `eu-west-1`

## Steps to reproduce

```
const aws = require('aws-sdk');

aws.config.loadFromPath('./credentials.json');
aws.config.apiVersions = {
    sqs: '2012-11-05'
};

console.dir(aws.config);

const sqs = new aws.SQS();

const params = {
    QueueName: 'mytest.fifo'
};
  
sqs.createQueue(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
```

## Results

> Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length

## Environment

Using `aws-sdk` version `2.185.0` from a Node 8.6.0 application

**Comment by thecodejunkie** [comment]
I figured it out, I was missing the `FifoQueue` attribute. I'll post the solution here in-case someone else ends up here thanks to a search

```
const params = {
    QueueName: 'mytest.fifo',
    Attributes: {
        "FifoQueue": "true"
    }
};
```

**Comment by ratkorle** [comment]
Can anyone help me of how I push messages or queues to FIFO using SDK. I have this but it is not working:
`async function sendJob(job) {
    console.log('new AWS.SQS');
    let params = {
        DelaySeconds: 10,
        MessageAttributes: {
            "Title": {
                DataType: "String",
                StringValue: "job.name"
            },
            "Author": {
                DataType: "String",
                StringValue: "Subscription Job"
            },
            "WeeksOn": {
                DataType: "Number",
                StringValue: "6"
            }
        },
        MessageBody: job,
        QueueUrl: "https://sqs.eu-west-1.amazonaws.com/978485304731/scraper-jobs-queue.fifo"
    };
    console.log('params defined');
    console.log(params);
    await sqs.sendMessage(params, function(err, data) {
        console.log('sending message');
        if (err) {
            console.log("Error", err);
        } else {
            console.log("Success", data.MessageId);
        }
    });
}`
