### ISSUE TITLE
Programatic way to list required permissions from methods called

### ISSUE THREAD

**Issue by geovanisouza92** [aws/aws-sdk-js#1890]
It would be a lot easier easier to maintain policies if the we could check, at development time, what permissions are required from the methods consumed from the SDK.

**Comment by jeskew** [comment]
You could also open this feature request on the [IAM developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=76). The standalone [IAM policy generator](http://awspolicygen.s3.amazonaws.com/policygen.html) appears to already be a JavaScript application, so it may just need to be repackaged for use in Node.

**Comment by ajredniwja** [comment]
Closing this issue as it should be opened in [IAM developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=76).

Please reach out if you have any other questions.
