### ISSUE TITLE
Recursive config profiles don't work.

### ISSUE THREAD

**Issue by akdor1154** [aws/aws-sdk-js#1891]
I can set up my `~/.aws/config` like
```ini
; matching aws credentials in ~/.aws/credentials
[profile base]
region = ap-southeast-2
output = text

[profile first]
role_arn = arn:aws:iam::00000:role/first-role
source_profile = base

[profile second]
role_arn = arn:aws:iam::00000:role/second-role
source_profile = first
```

then set `AWS_PROFILE=second`. Botocore, and hence the AWS CLI, will then use base to assumeRole into first, which is then used in turn to assumeRole into second. This chain can be as long as you like, but I've kept it short in this issue.

This should be supported in the JS SDK as it is in botocre, but currently this doesn't work. Any chance of allowing this?

**Comment by jeskew** [comment]
Hi @akdor1154,

Is the `AWS_SDK_LOAD_CONFIG` environment variable set to a truthy value?

**Comment by akdor1154** [comment]
yep, no luck with this sorry.
