### ISSUE TITLE
Misleading error message when waiting for the status imageAvailable

### ISSUE THREAD

**Issue by MeLlamoPablo** [aws/aws-sdk-js#1892]
**Edit: see my message below:**

Hi!

I don't know if I'm missing something, but it doesn't make sense to me. When I'm polling the AWS API using `ec2.waitFor` to wait for the status `imageAvailable` of an AMI, I get the error `Resource is not in the state imageAvailable`. Here's the full error object:

```js
{ [Error: Resource is not in the state imageAvailable]
  occurredWhen: 'Waiting for imageAvailable on snapshot ami-12b1d56b',
  message: 'Resource is not in the state imageAvailable',
  code: 'ResourceNotReady',
  time: 2018-01-23T20:27:36.787Z,
  requestId: 'e81a70b4-8058-4c52-91b3-2eb72d07dde7',
  retryable: false,
  originalError: 
   { message: 'You are not authorized to perform this operation.',
     code: 'UnauthorizedOperation',
     time: 2018-01-23T20:27:36.784Z,
     requestId: 'e81a70b4-8058-4c52-91b3-2eb72d07dde7' },
  statusCode: 403,
  retryDelay: 15000 }
```

Note that the `occurredWhen` property is added by myself to make debugging easier (The stack traces don't get preserved for some reason).

Here are the steps to reproduce:

* Launch an EC2 instance in the AWS console
* Use the `ec2.createImage` method on the image.
* Use the `ec2.waitFor("imageAvaliable")` method on the AMI ID returned by the previous method.

Here's the [exact line of code where the error is caused in my repo](https://github.com/iepaas/machine-provider-ec2/blob/f2ef135d5fc395d8692f8d398fc4ca9c07261c18/src/functions/takeSnapshotOfMachine.ts#L21). This is part of a bigger experimental project which I haven't documented, so if you don't understand anything feel free to ask. But all you really need to know is that `machine.id` is the instance ID.

Thanks for your help.

**Comment by MeLlamoPablo** [comment]
Alright so I'm very dumb. Turns out that my IAM user was missing the `DescribeImages` policy. However the error message is deceitful, I would suggest to change it.

**Comment by jeskew** [comment]
Hi @MeLlamoPablo,

It might make sense to use the original error message instead of (or in addition to) the "Resource is not in the state X" message used for terminal waiter errors.
