### ISSUE TITLE
S3 cannot handle connection interruption; weird ?max-keys=0 requests

### ISSUE THREAD

**Issue by zverev** [aws/aws-sdk-js#1895]
Hi!

In my client-side application users upload about 1-2 thousands of files for a very long time. Sometimes they experience connection problems or have to connect to another network and it is quite important to keep session alive.

I use S3.upload function and while debugging I've found, that once I go offline, my network tab is flooded with `?max-keys=0 requests`. What is it?
Maybe it would be ok, but sometimes if I disconnect for about 30 seconds these requests always return `403` status code. File upload hangs.

![image](https://user-images.githubusercontent.com/5755474/35351925-78508e06-0153-11e8-8f8c-211ab1048a0e.png)

I've tried to google this issue and found, that it could be related to region. My region is `eu-west-1`. I tried to remove it from `AWS.S3` options, but it doesn't help.

By the way, does S3 SDK have any tools to handle multiple files upload?

**Comment by jeskew** [comment]
The `max-keys=0` request you're seeing is the S3 client attempting to determine the region in which the bucket being interacted with is located. The S3 client will often only see a generic "NetworkingError" in the browser, which prevents it from differentiating between legitimate networking errors (such as a laptop disconnecting from the internet) and the errors we would see if the request were sent to or signed for the wrong region. 

Is the internet disconnecting in the middle of a number of simultaneous operations? It's not clear from the screenshot if the SDK is sending one `?max-keys=0` request per failed operation or if the requests are being sent in a loop.

**Comment by zverev** [comment]
These requests appear if I disconnect after at least one file is uploaded. Seems that they are sent in series immediately one after another and there is no any timeout between them.
If I break the connection at the beginning of download, I see only failing file upload requests.
Why is it trying to determine the region? I've specified it in options. And why it returns 403 after connection is established again? There is no such problem if I am always online.

**Comment by baharev** [comment]
Interesting. I have the same behavior in https://github.com/aws/aws-amplify/issues/177 

> If the HTTP PUT fails in such a way that it hasn't even been sent (note the `(failed)` in red in the status column, and the provisional header), then I do not understand the GET request (`?max-keys=0`) that follows it. It seems pointless to me: The PUT hasn't been sent to the server.

**Comment by zverev** [comment]
[EvaporateJS](https://github.com/TTLabs/EvaporateJS) solved my problem.
But I still have no idea, what is the nature of these requests.

**Comment by andregagne** [comment]
I am also seeing this problem with the newest version of the SDK (built about a month ago from here: https://sdk.amazonaws.com/builder/js/)

Any suggestions on how to prevent this?

**Comment by ryno1234** [comment]
I'm also seeing this if I attempt to `abort()` the multipart upload. I'm receiving a 403 forbidden as well.

**Comment by Voltmod** [comment]
It's still not resolved. Any s3 requests in offline causes an uncontrolled new requests spam `{Bucket}?max-keys=0`

**Comment by simonbuchan** [comment]
Caused by this: https://github.com/aws/aws-sdk-js/blob/4e1b1afabe5754b8f7c956e15772c3c0fb0a3a45/lib/services/s3.js#L629

Really should be checking further into the error to see if it's due to missing bucket, and handling errors here, but from the code it looks like you can disable the check by using `forcePathStyle: true` in the config?

**Comment by huyongyong1992** [comment]
we can rewrite this function:
AWS.util.update(AWS.S3.prototype, {
    reqRegionForNetworkingError(resp, done) {
      if (AWS.util.isBrowser()) {
        // console.log('网络错误！！！')
        errorCb('network error')
      }
    }
  })

**Comment by simonbuchan** [comment]
@jeskew can you re-open this issue? It's definitely still a problem.
