### ISSUE TITLE
AWS S3 File upload Access-Control-Allow-Origin Error

### ISSUE THREAD

**Issue by nimeshabuddhika** [aws/aws-sdk-js#1898]
I'm trying to upload an image to aws s3 using javascript. But when i attempt to upload it, I'm getting the following error.

`
Failed to load https://demoapp.s3-us-west-2.amazonaws.com/IMG_2484.JPG: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:63342' is therefore not allowed access.
`

Code :

`<input id="file-chooser" type="file"/>`
`<button id="upload-button">Upload</button>`
`<p id="results"></p>`

Javascript :
![capture](https://user-images.githubusercontent.com/7195953/35479710-bdc6ce3c-0423-11e8-8f27-6d8427cb2ce4.PNG)

CORS  Configuration : 
![capture](https://user-images.githubusercontent.com/7195953/35479716-e5383d02-0423-11e8-810d-10beb20ae33e.PNG)

**Comment by AllanFly120** [comment]
Sorry for the late reply, I think your CORS setting should work. My suspicion is that you preflight request was blocked somewhere. Are you accessing the bucket that in the same region as your client?

**Comment by nimeshabuddhika** [comment]
It was my bad. I used wrong region. Thanks for your help.

https://docs.aws.amazon.com/general/latest/gr/rande.html

**Comment by phanikumar252** [comment]
hi @AllanFly120  i am also getting th same issue like "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource." Can you please help on this.Thank you

**Comment by AllanFly120** [comment]
Hey @phanikumar252, you might need to setup the S3 bucket's CORS config. Please refer to [this](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) document for more information.

**Comment by trivikr** [comment]
Locking this thread as the issue is old, and resolved.
Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
