### ISSUE TITLE
Instance types through API

### ISSUE THREAD

**Issue by riteshapatel** [aws/aws-sdk-js#1899]
Hi,

Is there a way to get instance type listing through the API? I see a question was posed in AWS Forum in 2015. Any updates?

https://github.com/aws/aws-cli/issues/1279

Thx

Ritesh

**Comment by AllanFly120** [comment]
Hi @riteshapatel 
There's still no API for querying all the instance type information as I know. You can retrieve up-to-date full instance type list from [here](https://github.com/aws/aws-models/blob/master/ec2/2016-11-15/service-2.json), the list is like [this](https://gist.github.com/AllanFly120/9fb95e49fbd0c403b29a369ed3a49be2). 
But this list only contains names, I guess you also want to query the detail information for each instance. I will follow this up with service team inform here if I get any updates.

**Comment by riteshapatel** [comment]
@AllanFly120 Thank you for your response. First link in the commends above returns Git 404. Any idea? I just need the listing of instance types. No other details, if there is a way to accomplish that via api or curl would be great. 

Thx

Ritesh

**Comment by AllanFly120** [comment]
Hey, @riteshapatel 
I find [Price List API](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-pelong.html) offers some useful APIs to query the instance details, such as [get attributes](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pricing.html#getAttributeValues-property). But the query API is only available in 2 regions. For other regions, you can use Bulk API to download instance details files. This is the API closest to what you need for now.

**Comment by tomgoren** [comment]
@riteshapatel I added an example to the original thread: https://github.com/aws/aws-cli/issues/1279#issuecomment-415458307

Copying here in case someone lands on this page.
```
$ aws pricing get-attribute-values --service-code AmazonEC2 --attribute-name instanceType
{
    "AttributeValues": [
        {
            "Value": "c1.medium"
        },
        {
            "Value": "c1.xlarge"
        },
        {
            "Value": "c3.2xlarge"
        },
...
        {
            "Value": "z1d.xlarge"
        },
        {
            "Value": "z1d"
        }
    ]
}
```

**Comment by srchase** [comment]
@riteshapatel,

Looks like you were able to find a sufficient answer over on the CLI repository.  I'm going to close out your issue here.
