### ISSUE TITLE
S3 file link isn't deleted after object is deleted

### ISSUE THREAD

**Issue by michaelyfan** [aws/aws-sdk-js#1901]
Hello,

I noticed today that even if I delete a file from an album in an AWS bucket (via the S3 management console), the file's link is still valid and navigating to the link prompts me to download the deleted file.

Attempting to update a file (by overwriting with a file of the same key) also fails in a very curious way. In the S3 management console, the new file's changes are reflected (ex. updated size), but the link continues to redirect me to download the old file.

Here is my code that deals with the S3 upload (on the server):
```
var multer = require('multer');
const storage = multer.memoryStorage();
const upload = multer({ storage: storage });
app.post("/api/profilepicupload", upload.single('file'), (req, res) => {
  var S3 = new AWS.S3({
    apiVersion: '2006-03-01',
    params: {Bucket: 'name_here'}
  });

  S3.upload({
    Key: req.headers.filecaption,
    Body: req.file.buffer,
  }, function(err, data) {
    if (err) {
      res.status(500).send(err);
      console.log(err);
      return;
    }
    res.sendStatus(200);
  });
})
```

This is very frustrating, as getting my photos simply utilizes the public link; if I can't update the link, then any updates for the photo won't be reflected.

**Comment by srchase** [comment]
@michaelyfan,

Do you have any further questions?  If not, I'd like to close this issue.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
