### ISSUE TITLE
Elastic IP Addresses

### ISSUE THREAD

**Issue by jferrer21** [aws/aws-sdk-js#1906]
When using the below code to obtain the public IP address of a running instance, I get the  information of of a non-running instance.  How can I obtain, using Node, the PublicIp of the running instance.

Thank you.

var AWS = require('aws-sdk');
// Set the region 
AWS.config.update({region: 'REGION'});

// Create EC2 service object
var ec2 = new AWS.EC2({apiVersion: '2016-11-15'});

var params = {
  Filters: [
     {Name: 'domain', Values: ['vpc']}
  ]
};

// Retrieve Elastic IP address descriptions
ec2.describeAddresses(params, function(err, data) {
   if (err) {
      console.log("Error", err);
   } else {
      console.log("Success", JSON.stringify(data.Addresses));
   }
});

**Comment by AllanFly120** [comment]
Hi @jferrer21 ,
There's a 'instance-state-code' filter available for `DescribeInstances` method. You can using this operation to get the public IP address as well.
```javascript
ec2.describeInstances({
    Filters:[{
        Name:'instance-state-code',
        Values:['16']//'16' for status running
    }]
}, function(err, data) {
    if(err) {
        console.log('Error', err)
    } else {
        //may differ according your EC2 setting
        data.Reservations.map((reservation) => {
            reservation.Instances.map((instance) => {
                console.log(instance.PublicIpAddress);
            })
        })
    }
})
```

**Comment by AllanFly120** [comment]
Hi @jferrer21 ,
I'm not an expert on ec2. I find this in EC2 API reference, hope it can help you. There's an 'instance-state-code' filter available for `DescribeInstances` method. You can using this operation to get the public IP address as well.
```javascript
ec2.describeInstances({
    Filters:[{
        Name:'instance-state-code',
        Values:['16']//'16' for status running
    }]
}, function(err, data) {
    if(err) {
        console.log('Error', err)
    } else {
        //may differ according your EC2 setting
        data.Reservations.map((reservation) => {
            reservation.Instances.map((instance) => {
                console.log(instance.PublicIpAddress);
            })
        })
    }
})
```

**Comment by jferrer21** [comment]
@AllanFly120

Thank you.  It worked.
