### ISSUE TITLE
Implement the Lerna pattern.

### ISSUE THREAD

**Issue by rizowski** [aws/aws-sdk-js#1907]
### Problem

The aws-sdk is one of the largest packages I end up using. Most of the time I really only need a few clients out of the package as a whole. Where deploying to lambda the size of the dependencies must be considered, this can be a potential problem.

### Solution

It would be nice for the project to follow and implement the [lerna pattern](https://github.com/lerna/lerna). Packages such as [lodash](https://github.com/lodash/lodash) follow this pattern. It allows you to be able to require in the full SDK if you require it or require small components of the SDK. For example, instead of `npm i -S aws-sdk` you could:

```shell
npm i -S aws-sdk.s3 aws-sdk.lambda
```

```js
const S3 = require('aws-sdk.s3');
const Lambda = require('aws-sdk.lambda');
```

### The difference

You are still able to install the `aws-sdk` package from npm and use it the way it is used today. The SDK would still return all the clients. The difference would be each client from the aws-sdk would become its own package. (`aws-sdk.s3`, `aws-sdk.lambda`, ...) This allows others to be able to **install** only the clients they will use, instead of needing to install the general all inclusive aws-sdk.

**Comment by jeskew** [comment]
Hi @rizowski,

You can do this today by requiring specific service clients as submodules. There's a quick mention of this [in the README](https://github.com/aws/aws-sdk-js#in-nodejs-1), but essentially it ends up looking very much like the ideal example given above:

```javascript
const S3 = require('aws-sdk/clients/s3');
const Lambda = require('aws-sdk/clients/lambda');
```

**Comment by rizowski** [comment]
@jeskew Thanks for the quick response. The biggest thing I would like to get out of what I am proposing is being able to reduce code deployed to services other than front end. Although, by its very nature, implementing the lerna pattern could also produce smaller bundle sizes for webpack. 😄

**Comment by dncrews** [comment]
+1. I've actually been bumping up against the Lambda total file size limit for months now. This would be significant.

**Comment by tusbar** [comment]
I would definitely be happy to see smaller and independently versioned packages, so I don’t have to update aws-sdk when a client I’m not using gets updated. 

Lerna (or equivalent) seems like a good solution to this, so I could just `yarn add @aws/s3`, which would depend on something like `@aws/core`, just like https://github.com/Turfjs/turf.

**Comment by spilliton** [comment]
+1 also running into this.  

As an alternative solution, what if `aws-sdk` was available on all lambdas by default?  Seems like such a common dependency it would be nice if it were just available for you (and didn't count toward total size) similar to the base node stuff you can import.

**Comment by srchase** [comment]
@spilliton 

```aws-sdk``` is available in all Lambdas.

Lambda is currently using 2.290.0, but this page will be updated when that's moved to a newer version: [Lambda Current Supported Versions](https://docs.aws.amazon.com/lambda/latest)/dg/current-supported-versions.html

**Comment by spilliton** [comment]
@srchase awesome I had no idea!  Thanks!

**Comment by aldegoeij** [comment]
sdk versions in lambdas in AWS are not updated anymore, due to backward compatibility problems.

existing tested and deployed lambdas could/would break if AWS updates the lambda in the environment from their side.

If you want to do anything on the aws-sdk currently without there being any partial imports, you could use AWS Lambda Layers.

+1 for lerna like modularity

**Comment by cuongphamcxa** [comment]
+1 fr lerna. I'm only need to work with s3 but still need to install aws-sdk which the unpacked size is 47Mb.

**Comment by ajredniwja** [comment]
Hey everyone, this has been a known issue and hence the version 3 of the SDK takes care of it. 

Please check [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3) which consists of modular packages and provides much more efficiency. The beta is out now.
