### ISSUE TITLE
Cannot load profile from ~/.aws/credentials

### ISSUE THREAD

**Issue by GuidoS** [aws/aws-sdk-js#1910]
Based on the example [given here](https://github.com/aws/aws-sdk-js/blob/1f52beba04f74104df4b599a1499504b26f290cc/lib/credentials/shared_ini_file_credentials.js#L31) and using a config/credential file that work with the aws cli, I was unable to get my profile to load. I also read the [documentation here](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html) and I believe I am following it correctly.

I have been able to setup the profiles and get them to work with the aws tool, so I think my config/credential files are setup correctly.

# First Attempt
```js
var AWS = require('aws-sdk');
var s3 = new AWS.S3();
var creds = new AWS.SharedIniFileCredentials({profile: 'myBucket'});
AWS.config.credentials = creds;
```

This is the error message I got:
```
ConfigError: Missing region in config
```

# Second Attempt

Adding in the region manually:
```js
var AWS = require('aws-sdk');
var s3 = new AWS.S3();
var creds = new AWS.SharedIniFileCredentials({profile: 'myBucket'});
AWS.config.credentials = creds;
AWS.config.update({region:'us-east-1'});
```

This is the error message I got:
```
InvalidToken: Invalid Token: 'Invalid token'
```

**Comment by AllanFly120** [comment]
Hi @GuidoS,
I know the client config credential and global config object is somewhat confusing. The S3 client loads the config from global config object at its construction. Once the s3 client is constructed, the update on global config object won't affect the S3 client then. Which is said, you need to always set global credentials before constructing any clients.

```javascript
var AWS = require('aws-sdk');
AWS.config.credentials = new AWS.SharedIniFileCredentials({profile: 'myBucket'});
AWS.config.update({region:'us-east-1'});
var s3 = new AWS.S3();
```
