### ISSUE TITLE
Request to add slotDetails to AWS.LexRuntime.postText() and postContent() response

### ISSUE THREAD

**Issue by windhamg** [aws/aws-sdk-js#1911]
According to https://docs.aws.amazon.com/lex/latest/dg/built-in-slot-time.html:

>Amazon Lex uses the slotDetails attribute of a Lambda event to pass resolutions for the ambiguous times to your Lambda function. For example, if your bot prompts the user for a delivery time, the user can respond by saying "10 o'clock." This time is ambiguous. It means either 10:00 AM or 10:00 PM. In this case, the value in the slots map is null, and the slotDetails entity contains the two possible resolutions of the time. Amazon Lex inputs the following into the Lambda function:

```
"slots": {
   "deliveryTime": null
},
"slotDetails": {
   "deliveryTime": {
      "resolutions": [
         {
            "value": "10:00"
         },
         {
            "value": "22:00"
         }
      ]
   }
}
```
I have exactly this situation in one of my projects, yet the AWS SDK for Javascript is not returning the `slotDetails` object in the response. I am using v2.188.0. 

Is it possible to get the `slotDetails` object back when using "return parameters to client" as the fulfillment option for an Intent, rather than using a Lambda function?

If not, I would like to request that the `slotDetails` object be added to the `AWS.LexRuntime.postText()` and `postContent()` data objects passed to the callback.

Thanks!
--Gary

**Comment by AllanFly120** [comment]
Hey @windhamg,
The [Lex Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=251) would be a better place for API usage or any feature request. The service team would be happy to answer your questions.
