### ISSUE TITLE
How do I use ses?

### ISSUE THREAD

**Issue by intergleam** [aws/aws-sdk-js#1912]
sorry but i don't get it how do I send an email with aws-sdk-js?

**Comment by AllanFly120** [comment]
Hi @intergleam ,

You can refer to the [Developer Guide](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/Welcome.html) and [JS SDK Reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html) to get started with it. Feel free to ask questions here when you have issue using JS SDK.
