### ISSUE TITLE
runInstances spawns on-demand instance if the spot maxPrice is too low

### ISSUE THREAD

**Issue by RomainGeffraye** [aws/aws-sdk-js#1915]
Hi, 

I'm trying to spawn a new spot instance with runInstances.

However, if I set a MaxPrice lower than the actual price of the market, I don't have any error in the response and an on-demand instance is created instead.

**Comment by srchase** [comment]
@RomainGeffraye 

Did you raise this issue with the Service Team?

That kind of validation would need to be handled on the Service side.
