### ISSUE TITLE
InvalidClientTokenId using aws sns text message service

### ISSUE THREAD

**Issue by mashwin** [aws/aws-sdk-js#1919]
Hi All,

I am trying to send sms using aws sns text messaging service. I have used credentials of the root user. But still keep getting the following error:

```
{ InvalidClientTokenId: The security token included in the request is invalid.
 message: 'The security token included in the request is invalid.',
  code: 'InvalidClientTokenId',
  time: 2018-02-07T14:29:47.917Z,
  requestId: '7fbcf4f5-d4f3-5a6e-babb-a600db68c2d1',
  statusCode: 403,
  retryable: false,
  retryDelay: 23.474719889043616 }
```
The code is as below:

```
const sns = new AWS.SNS();

var params = {
	Message: 'test message',
	MessageStructure: 'string',
	PhoneNumber: cellNumber
};

sns.publish(
	params,
	function (error, data) {
		if (error) {
			console.log(error);
		} else {			
			callback(null, data);
		}
	}
);
```

Please let me know if I am missing anything. The same code used to work earlier.
Thanks

**Comment by chrisradek** [comment]
@mashwin 
When you say the same code used to work earlier, was this using different credentials or a different version of the SDK? Do you also have a region configured? The error indicates that there is something wrong with the credentials the SDK is using.

**Comment by mashwin** [comment]
No. The same credentials were used. But not able to figure out what has changed. Do we need to pass security token to the sdk ?

**Comment by srchase** [comment]
@mashwin 

Were you able to get this resolved?  Were there any changes to the permissions for the credentials or the code you were executing?

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
