### ISSUE TITLE
Electron app: 403 Forbidden on EC2 on app mode / 200 OK on web mode

### ISSUE THREAD

**Issue by halmeida82** [aws/aws-sdk-js#1920]
Greetings,

I'm developing an electron-based app to gather information regarding EC2 instances and Billing.
When I run my electron app I get a 403 forbidden response on the EC2 request, and 200 OK on the cost explorer requests.
When I run the same app via browser, I get 200 OK on all the requests.

Via App:
![app](https://user-images.githubusercontent.com/27915436/35966096-c113088c-0cb4-11e8-8ab6-8f326ce73467.png)

Via Browser:
![browser](https://user-images.githubusercontent.com/27915436/35966097-c2d0d3ac-0cb4-11e8-9402-794ce181d7e5.png)

I'm using the version 2.188 of the aws-sdk.

Here is the code:

`
const AWS = window['AWS'];

    AWS.config.update({
      accessKeyId: 'xxx',
      secretAccessKey: 'yyy',
      region: 'eu-west-1'
    });

      AWS.config.apiVersions = {
        ec2: '2016-11-15',
        costexplorer: '2017-10-25'
      };

      const ec2 = new AWS.EC2();
      const ec2_params = {
        DryRun: false,
      };
      ec2.describeInstances(ec2_params, (err, data) => {
        if (err) {
          console.log(err, err.stack);
        } else {
          console.log(data);
            }
          });          
        }
      });

      AWS.config.update({
        region: 'us-east-1'
      });

      const costexplorer = new AWS.CostExplorer();
      var ce_params = {
        Dimension: 'SERVICE',
        TimePeriod: {
          End: '2018-01-31',
          Start: '2018-01-01'
        }
      };
      costexplorer.getDimensionValues(ce_params, function(err, data) {
        if (err) console.log(err, err.stack); // an error occurred
        else     console.log(data);           // successful response
      });

Can anyone shed some light on this problem?

Thanks in advance

**Comment by jeskew** [comment]
The main difference I can see between the two requests is the presence of an `X-DevTools-Request-Id` header on the one that received a 403. Is that header being signed? (The `Authorization` header will have a `SignedHeaders` section indicating which headers are signed.) If so, it may be a hop-by-hop header that is stripped before the request reaches EC2.

**Comment by chrisradek** [comment]
@halmeida82 
Are you bundling your electron code using something like webpack?

If you aren't, you can use the node version of the SDK directly in Electron (just require the SDK like normal).

I suspect (but haven't tested) that the issue is due to the origin of your requests starting with `file://`. Using the node.js version of the SDK prevents the origin header from being sent by default, or you can try serving your front-end from localhost and loading that in your electron main thread.

Would you be able to try either of the above workarounds?

**Comment by halmeida82** [comment]
by @chrisradek :
> Are you bundling your electron code using something like webpack?
> If you aren't, you can use the node version of the SDK directly in Electron (just require the SDK like normal).

This is what I thought/think is the problem too.. but I haven't found a way to make this work.

I've tried using aws-sdk trough "normal" packaging by:
terminal :> npm install aws-sdk -- save
code :> var aws = require('aws-sdk');

But in this way, aws doesn't have the necessary client configurations and I get errors like:
![2018-02-09_09h33_14](https://user-images.githubusercontent.com/27915436/36021131-c44cd0dc-0d7c-11e8-85bd-5790aea4583d.png)

Probably due to the fact that EC2's service is null:
![2018-02-09_09h34_12](https://user-images.githubusercontent.com/27915436/36021140-c95bf0bc-0d7c-11e8-8fdf-ab669fec7d7f.png)

So, what I did was use https://sdk.amazonaws.com/builder/js/ and build a version with all the services.
Then include in index.html like a normal .js file, and the use:
`const AWS = window['AWS'];`

This way I don't get the above error and the service is not null:
![2018-02-09_09h40_59](https://user-images.githubusercontent.com/27915436/36021333-5d55e660-0d7d-11e8-8a83-9f7f1a847a91.png)

I've also tried including the EC2 service directly:
![2018-02-09_09h48_28](https://user-images.githubusercontent.com/27915436/36021691-79f7e330-0d7e-11e8-9eb3-1941281d675b.png)

But as you can see, the service is null.. and on this line the error is the same as above:
" Could not find API configuration ec2-2016-11-15"

**Comment by chrisradek** [comment]
@halmeida82 
Since there's a few moving parts here (webpack, custom SDK, and of course electron!) would you be able to provide a minimal example of your setup in a separate repo? 

I've actually only used the nodejs version of the SDK in electron without any bundlers, so if you can provide some more info about your setup it'll help bootstrap my efforts to reproduce! 😃

**Comment by halmeida82** [comment]
Sorry for the delay in the reply.

While trying to replicate the issue on a minimal Electron build + require('aws-sdk'), everything started working.

So the problem must be on my bundled package. I'm using this: https://github.com/maximegris/angular-electron
The problem must be related to it. 

Thanks for the replies

**Comment by fedeverdi** [comment]
I solved using Electron API:

`const {session} = require(‘electron’);

  // Modify the user agent for all requests to the following urls.
  const filter = {
   urls: [‘https://*.amazonaws.com/*’]
 };

 session.defaultSession.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
     details.requestHeaders[‘Origin’] = ’http://localhost:4200';
     callback({ cancel: false, requestHeaders: details.requestHeaders });
 });`
