### ISSUE TITLE
Bucket#upload _sometimes_ uses unexpected Access-Control-Request-Method header

### ISSUE THREAD

**Issue by ethagnawl** [aws/aws-sdk-js#1928]
I'm seeing unexpected behavior while trying to upload an mp4 to S3 via Bucket#upload. I'm using v2.193.0 and this issue is browser independent. (I've also seen this in older versions of the library, too.)

_Sometimes_ the initial OPTIONS request will be sent with the header `Access-Control-Request-Method: POST` instead of `Access-Control-Request-Method: PUT`. In my case, I do not have a `POST` entry in my bucket's CORS config, so these requests are failing with a 403 and the upload is aborted.

[The documentation for this method](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) explicitly mentions the HTTP PUT method and every upload that is successful issues an OPTIONS request with a `Access-Control-Request-Method: PUT` header.

So, is this a bug or am I working under mistaken assumptions about what the header value should be?

![options-put](https://user-images.githubusercontent.com/289949/36187769-66fbd724-1115-11e8-8efe-664d290a65dd.png)
![option-post](https://user-images.githubusercontent.com/289949/36187770-67173a8c-1115-11e8-9788-c860c6a10e52.png)

**Comment by jeskew** [comment]
`AWS.S3#upload` will decide based on the input size whether to use a single `PutObject` operation or to orchestrate a multipart upload. A multipart upload must begin with a `CreateMultipartUpload` operation and end with a `CompleteMultipartUpload` operation, both of which use the `POST` HTTP method. The documentation for the `Bucket` parameter can be updated to remove the reference to `PUT`, but you will need to allow `POST` operations in your CORS configuration if you wish to allow concurrent part uploads of large files.

**Comment by ethagnawl** [comment]
Thanks for the prompt, insightful response, @jeskew!
