### ISSUE TITLE
DynamoDB SSESpecification - fails validation

### ISSUE THREAD

**Issue by raducoti** [aws/aws-sdk-js#1929]
Please have a look at my comment on this commit: https://github.com/aws/aws-sdk-js/commit/1f07afaed7c8a069e0e25b1d0aa4c9ee1037b42d

According to the docs, this property should be **SSEEnabled** https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-ssespecification.html#cfn-dynamodb-table-ssespecification-sseenabled

CreateTable validation fails right now:
```
MultipleValidationErrors: There were 2 validation errors:
MissingRequiredParameter: Missing required key 'Enabled' in params.SSESpecification
UnexpectedParameter: Unexpected key 'SSEEnabled' found in params.SSESpecification
at ParamValidator.validate (/Users/myuser/project/path/node_modules/aws-sdk/lib/param_validator.js:40:28)
```

**Comment by jeskew** [comment]
Hi @raducoti,

The documentation linked to above refers to CloudFormation templates. Both the API and the SDKs use an [`SSESpecification` object](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html#DDB-CreateTable-request-SSESpecification) with an boolean `Enabled` property.
