### ISSUE TITLE
UnexpectedParameter: Unexpected key 'VerificationMessageTemplate' found in params

### ISSUE THREAD

**Issue by Ashirogi-Muto** [aws/aws-sdk-js#1930]
While creating a new user pool with createUserPool method, I want to add custom email verification messages for my user pool. As per the [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#createUserPool-property) I can provide these params for that requirement.
`
VerificationMessageTemplate: {
            DefaultEmailOption: CONFIRM_WITH_LINK | CONFIRM_WITH_CODE,
            EmailMessage: 'STRING_VALUE',
            EmailMessageByLink: 'STRING_VALUE',
            EmailSubject: 'STRING_VALUE',
            EmailSubjectByLink: 'STRING_VALUE',
            SmsMessage: 'STRING_VALUE'
  }
`

I want the users of the user pool to verify themselves with this attribute:- CONFIRM_WITH_LINK

But while creating the user pool with these params I get:-

> UnexpectedParameter: Unexpected key 'VerificationMessageTemplate' found in params

**Comment by jeskew** [comment]
This parameter looks like it was added in [version 2.97.0 of the SDK](https://github.com/aws/aws-sdk-js/commit/4616765edab3e5ac821db9830fa00baf4ee4e569); could you make sure that you're using this version or later?

**Comment by Ashirogi-Muto** [comment]
My AWS SDK version is 2.24.0. I'll update the SDK. Thanks for pointing it out.

**Comment by jeskew** [comment]
Happy to help!
