### ISSUE TITLE
lambda list-functions MasterRegion="us-east-2" gives Error and is Empty

### ISSUE THREAD

**Issue by AmareshB** [aws/aws-sdk-js#1931]
```
var params = {
      MasterRegion: "us-east-1",
      FunctionVersion: "ALL",
      //Marker: '',
      MaxItems: 10
    };

lambda.listFunctions(params, function(err, data) {
      if (err) console.log(err, err.stack);
      else console.log("Lambdas list ", data);
    });
```

This return empty even though I have lambdas in the region, whereas

```
var params = {
      //MasterRegion: "us-east-1",
     // FunctionVersion: "ALL",
      //Marker: '',
      MaxItems: 10
    };
```

This lists the functions in the default region.

**Comment by jeskew** [comment]
The [Lambda documentation](https://docs.aws.amazon.com/lambda/latest/dg/API_ListFunctions.html) indicates that the `MasterRegion` parameter filters the list returned to only include functions *replicated from* the region indicated. If not specified, only non-replicated functions will be returned. The first example should only list functions originally published to `us-east-1` and subsequently replicated to the region to which the `ListFunctions` operation was sent, whereas the second example should only list functions originally published to the region to which the `ListFunctions` operation was sent.

**Comment by AmareshB** [comment]
So, the only way to pull all the lambdas in a region is by passing in the top level region and leave masterRegion empty. Is that right?
