### ISSUE TITLE
ApiGateway getRestApiId

### ISSUE THREAD

**Issue by manjbhachu** [aws/aws-sdk-js#1934]
We are monitoring our API Gateway services using Cloud Watch, and sending alarms via SNS for processing.
The tags associated with the API Gateway Stage are crucial to our processing/routing.
Unfortunately, Cloud Watch sends alarm notifications for API Gateways with only an API name and Stage name.
This means to get the REST API ID we have to make a call to ApiGateway.getRestApis and loop through them to until we find one with the same name to determine its ID - so that we can build the ARN to use the ApiGateway.getTags method.

Ideally the Cloudwatch alarm notification should send the REST API ID... But failing that it would seem useful to be able to either be able to getTags using API name and Stage name, or there should be a getRestApiId that takes the API name.

Hopefully this is the right place to raise this feature request... please let me know if I should be doing it elsewhere.

**Comment by jeskew** [comment]
Hi @manjbhachu,

The API Gateway team does not monitor this forum, so the best place to reach out to them is via their [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=199).
