### ISSUE TITLE
How to return ReadStream from s3.getObject

### ISSUE THREAD

**Issue by manju16832003** [aws/aws-sdk-js#1935]
I'm querying Athena output (that is s3 location) and its in CSV format.
when I try to get the object
`s3.getObject(params).createReadStream()` 

This returns a `PassThroguh`, 
how can I return `ReadStream` instead of `PassThrough`

**Comment by jeskew** [comment]
Hi @manju16832003,

`PassThrough` is an instance of `ReadStream`. We use a `PassThrough` stream internally to make sure the body returned has the same length as dictated by the `Content-Length` header on the response from S3.

**Comment by manju16832003** [comment]
@jeskew Thanks you for the response.
The athena output location (i.e. S3) returns the following  csv string format
```
"id","country","title","count","date"
"111","ga","Test","1","2018-02-12"
"111","ga","Test","2","2018-02-12"
"11","ga","Test","3","2018-02-14"
"11","ga","Test","1","2018-02-13"
```
When I try to receive it as a `createReadStream`, I would not get any stream
Here is my sample code
```
const stream = s3.getObject(params).createReadStream()
stream.pipe(process.stdout)
```
Since its PassThrough as instance of ReadStream, wouldn't display the results when I try it `process.stdout`

**Comment by jeskew** [comment]
I'm not able to reproduce the issue as described, and I do not believe it is related to our using a `PassThrough` stream (which is a readable stream). The following reliably pipes an S3 object to a local file:

```javascript
const { createWriteStream } = require('fs');
const S3 = require('../../clients/s3');

const s3 = new S3({region: 'us-west-2'});

s3.getObject({Bucket: bucketName, Key: objectKey})
    .createReadStream()
    .pipe(createWriteStream('./out.ext'));

```
The HTTP response's stream can sometimes be consumed by third-party libraries before it gets to the SDK. Are you using any library that attaches a listener to all HTTP responses' `data` events?

**Comment by manju16832003** [comment]
@jeskew OK, sorry probably I would missed out some pointers here.

To your question whether i'm using any third-party libraries ? No.

Here is my scenario:
1. When I query athena, Athena execution query gives me a path to CSV something looks like this
`s3://bucketname/results.csv`
2. When I use AWS SDK to read the csv, I do the following

```
      const results = execution.ResultConfiguration.OutputLocation.split('/')
      const s3 = new AWS.S3({ region: config.region })
      const params = {
        Bucket: results[2],
        Key: results[3]
      }

const readableStream = await s3.getObject(params).createReadStream()
```
I want to pipe this `readableStream` to another `Transform` stream, where I do some conditional checking.

The problem I have is, 
`const readableStream = await s3.getObject(params).createReadStream()`
This one actually doesn't return the stream
However, when I tried to 
```
      const bufferdata = await s3.getObject(params).promise()
      const result = s3Buffer.Body.toString()
```
The CSV results are returned at once as a Buffer.
However, I'm trying to create a Readable stream on that csv returns, parse line by line and pipe it to another Transformer

Note.
This is what Athena csv results looks like

```
"id","country","title","count","date"
"111","ga","Test","1","2018-02-12"
"111","ga","Test","2","2018-02-12"
"11","ga","Test","3","2018-02-14"
"11","ga","Test","1","2018-02-13"
```

I want this to be a stream where I can read line by line, But not a Buffer.
Is there a way around to read CSV results line by line from the SDK, instead of returning it as  Buffer
