### ISSUE TITLE
getBucketLocation returns empty string

### ISSUE THREAD

**Issue by rguiliani** [aws/aws-sdk-js#1937]
s3.getBucketLocation returns an empty string.

Docs say it will return "null" on error, or give me the region. It does neither.

{ LocationConstraint: '' }

aws-sdk@^2.197.0:
version "2.197.0"
resolved "https://registry.yarnpkg.com/aws-sdk/-/aws-sdk-2.197.0.tgz#986e3749f4d1944c6253d7824aa8035efb1db0e4"
dependencies:
buffer "4.9.1"
events "^1.1.1"
jmespath "0.15.0"
querystring "0.2.0"
sax "1.2.1"
url "0.10.3"
uuid "3.1.0"
xml2js "0.4.17"
xmlbuilder "4.2.1"

$ node --version
v9.4.0

**Comment by rguiliani** [comment]
aws-sdk@^2.197.0:
  version "2.197.0"
  resolved "https://registry.yarnpkg.com/aws-sdk/-/aws-sdk-2.197.0.tgz#986e3749f4d1944c6253d7824aa8035efb1db0e4"
  dependencies:
    buffer "4.9.1"
    events "^1.1.1"
    jmespath "0.15.0"
    querystring "0.2.0"
    sax "1.2.1"
    url "0.10.3"
    uuid "3.1.0"
    xml2js "0.4.17"
    xmlbuilder "4.2.1"

**Comment by rguiliani** [comment]
$ node --version
v9.4.0

**Comment by jeskew** [comment]
Hi @rguiliani,

Are there any other dependencies included in the affected application that might be adding a listener to the `'data'` event of all HTTP(S) responses? Some HTTP logging/monitoring utilities do this and have been known to consume response streams before the SDK can read them.

**Comment by rguiliani** [comment]
Thank you for the link. I was going off of this: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getBucketLocation-property, which doesn't mention that nuance. It doesn't include 'us-east-1' in the list of possible values though, so I guess that should have been a clue.

**Comment by 3DEsprit** [comment]
Thanks for this.

Even though us-east-1 is not listed, neither is us-east-2 yet it returns the correct region when using this method.
