### ISSUE TITLE
I have exact same issue (InvalidSignatureException: Signature expired)

### ISSUE THREAD

**Issue by saikiran91** [aws/aws-sdk-js#1938]
https://github.com/aws/aws-sdk-js/issues/527
I run Ubuntu terminal on Windows 10. Any solution for this?

**Comment by jeskew** [comment]
Is the `correctClockSkew` configuration parameter set to `true`?

**Comment by fcheong3b** [comment]
I'm having the same issue and I had set the correctClockSkew = true using the AWS
