### ISSUE TITLE
Remove circular references

### ISSUE THREAD

**Issue by haraldrudell** [aws/aws-sdk-js#1940]
THIS IS A BUG NOT A FEATURE REQUEST

because circular references work differently in Node.js require and bundlers, aws-sdk cannot presently be bundled.

**action: remove circular references**

**symptom**
> code: 'CIRCULAR_DEPENDENCY',
>   importer: '../../node_modules/aws-sdk/lib/util.js',
>   'Circular dependency: ../../node_modules/aws-sdk/lib/util.js -> ../../node_modules/aws-sdk/lib/core.js ->
>  ../../node_modules/aws-sdk/lib/util.js'

The root cause is that util.js uses modules that are using util

There are many instances of this pattern in aws-sdk

**Comment by jeskew** [comment]
Which bundler in particular are you seeing the reported error with? If you're using RollUp, there's [an open bug on the project to support circular CommonJS dependencies](https://github.com/rollup/rollup/issues/1507).  The browser build of the SDK is produced using browserify, and there are instructions in the README for use with webpack.

I disagree that this is a bug, as circular dependencies are permitted in CommonJS.

**Comment by haraldrudell** [comment]
I want **aws-sdk** to be better and more useful to me and other **CloudFormation** users

**Circular import references** is not good software engineering principles and to me, it is an embarrassment to see it from **Amazon Web Services** in its repository knowingly since at least October 2017.

**CommonJS** is a disorganized standard that prominent people has tried to replace since 2013. As late as 2015, **Node.js** did not support circular references surfaced by breaking https for everyone building Node.js from source.

The right thing to do is **ECMAScript modules** with **.mjs** Michael Jackson extension and the **--native-modules** flag for Node.js. This has been Elvis since **v8.5**

**Rollup** is the bundler that matters for the last 12 months and into the future unless you need a development server, and is crucial to the server-side infrastructure management that AWS does for a living. I wrote the **es2049package** package exactly for this reason and tried to make @Facebook browser people use it for React. They were at the time thinking there was something good about Node.js 6.

AWS seems to be using some sort of generator or systematic structure. To fix those circular references should not be more than a day for a skilled engineer prior to testing.

**Step 1 is to remove circular references**, it’s about a week and bundling with Rollup will list exactly where they are

**Step 2 is to rewrite to ES.Next ECMAScript 2017+** which is a major undertaking but worth it since both maintainability and performance is 10x better. For example, I refactored a stream-thing to **async iterators** and it immediately got 100x faster. This rewrite is not urgent but a fun exercise and making of history and greatness. Here’s what it looks like when I do it: https://github.com/haraldrudell/ECMAScript2049/blob/master/workspace/packages/allspawn/src/SpawnAsync.mjs

Please make aws-lib great again…

**Comment by haraldrudell** [comment]
I only use aws-sdk in two executables:

**yarn the cloud creator** that integrates configuring the AWS account and deploying to it with the build scripts command making it easy as create-react-app

**stack enforcer** that handles all those esoteric AWS troubles surfacing in managing an AWS account with nothing else than **CloudFormation** yaml files under version control

At the present time, **aws-sdk** is an unbundled external dependency so that **Node.js** deals with the circularities

**Comment by leoafarias** [comment]
Hi guys, I am currently using Rollup, and I am getting circular dependencies warnings up the wazoo. It seems that this is causing issues in certain deployment situations

`(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/json.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/json.js -> node_modules/aws-sdk/lib/json/builder.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/json.js -> node_modules/aws-sdk/lib/json/builder.js -> commonjs-proxy:/Users/leofarias/Documents/Projects/neardb/node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/json.js -> node_modules/aws-sdk/lib/json/parser.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/json.js -> node_modules/aws-sdk/lib/protocol/helpers.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/json.js -> node_modules/aws-sdk/lib/protocol/helpers.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/json.js -> node_modules/aws-sdk/lib/protocol/helpers.js -> commonjs-proxy:/Users/leofarias/Documents/Projects/neardb/node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/query.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/query.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/query.js -> node_modules/aws-sdk/lib/query/query_param_serializer.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/query.js -> node_modules/aws-sdk/lib/model/shape.js -> node_modules/aws-sdk/lib/model/collection.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/query.js -> node_modules/aws-sdk/lib/model/shape.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/rest.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/rest_json.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/rest_xml.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/rest_xml.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/xml/builder.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/model/api.js -> node_modules/aws-sdk/lib/model/operation.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/model/api.js -> node_modules/aws-sdk/lib/model/paginator.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/model/api.js -> node_modules/aws-sdk/lib/model/resource_waiter.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/model/api.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/sequential_executor.js-> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/service.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/service.js -> node_modules/aws-sdk/lib/region_config.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/config.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/config.js -> node_modules/aws-sdk/lib/credentials.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/config.js -> node_modules/aws-sdk/lib/credentials/credential_provider_chain.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/http.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/event_listeners.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/event_listeners.js -> node_modules/aws-sdk/lib/discover_endpoint.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/util.js -> node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/event_listeners.js -> node_modules/aws-sdk/lib/discover_endpoint.js -> node_modules/aws-sdk/lib/util.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/request.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/response.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/resource_waiter.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/v2.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/v3.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/v3https.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/v4.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/v4.js -> node_modules/aws-sdk/lib/signers/v4_credentials.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/s3.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/presign.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/param_validator.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/readable.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js
(!) Circular dependency: node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/writable.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js
(!) Circular dependency: node_modules/aws-sdk/lib/node_loader.js -> node_modules/aws-sdk/lib/credentials/temporary_credentials.js -> node_modules/aws-sdk/clients/sts.js -> node_modules/aws-sdk/lib/node_loader.js
(!) Circular dependency: node_modules/aws-sdk/lib/node_loader.js -> node_modules/aws-sdk/lib/credentials/temporary_credentials.js -> node_modules/aws-sdk/clients/sts.js -> commonjs-proxy:/Users/leofarias/Documents/Projects/neardb/node_modules/aws-sdk/lib/node_loader.js -> node_modules/aws-sdk/lib/node_loader.js
(!) Circular dependency: node_modules/aws-sdk/lib/node_loader.js -> node_modules/aws-sdk/lib/credentials/cognito_identity_credentials.js -> node_modules/aws-sdk/clients/cognitoidentity.js -> node_modules/aws-sdk/lib/node_loader.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLElement.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLElement.js -> commonjs-proxy:/Users/leofarias/Documents/Projects/neardb/node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLCData.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLComment.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLDeclaration.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLDocType.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLDocType.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLDTDAttList.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLDocType.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLDTDEntity.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLDocType.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLDTDElement.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLDocType.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLDTDNotation.js-> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLRaw.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLText.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js
(!) Circular dependency: node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLProcessingInstruction.js -> node_modules/xml2js/node_modules/xmlbuilder/lib/XMLNode.js`

**Comment by leoafarias** [comment]
Sorry for the verbose log. I am currently importing the following way

`import S3 from 'aws-sdk/clients/s3'`

I tried importing as described on the documentation for typescript.

`import S3 = require('aws-sdk/clients/s3');`

But I get an error about import assignment not being able to be used for ECMAscript modules
