### ISSUE TITLE
S3 is not fully promisified 

### ISSUE THREAD

**Issue by TrejGun** [aws/aws-sdk-js#1943]
```js
AWS.config.setPromisesDependency(bluebird);
const client = new AWS.S3({...})
client.getObject(params, (err, res) => {})
// works
client.getObject(params).promise().then(() => {}) 
// works
client.getSignedUrl("getObject", params, (err, res) => {})
// works
client.getSignedUrl("getObject", params).promise().then(() => {}) 
// TypeError: client.getSignedUrl(...).promise is not a function
```

PS yes I know I don't need neither callback nor promise in there because `getSignedUrl` is sync, but still

**Comment by AllanFly120** [comment]
Hi @TrejGun ,
Like you said, the promise dependency is used to 'promisify' the operation that makes http request. Since `getSignedUrl` doesn't make any request, this operation is not 'promisified'. I don't think this is an issue with SDK, it more of a style inconsistency. Is there any documentation mentioning using promise on `s3.geSignedUrl`?

**Comment by TrejGun** [comment]
Hi Allan

> I don't think this is an issue with SDK, it more of a style inconsistency
Yes you are right

> Is there any documentation mentioning using promise on s3.geSignedUrl
it says nothing about it, so I spent some time thinking what i'm doing wrong

>  is used to 'promisify' the operation that makes http request
actually i can't say from the method name if it does request or not

so please add some notes in docs or add `promise` method to `getSignedUrl`

**Comment by TrejGun** [comment]
guys its already one year passed since this issue was raised. is it so difficult to add one line to docs?

**Comment by srchase** [comment]
@TrejGun 

Opened a PR to add a note.

If there are any other docs issues you feel need addressing, we'd be happy to take PRs.

**Comment by TrejGun** [comment]
thanks a lot, will do

**Comment by srchase** [comment]
This change has been merged and the docs will be updated with the next release.
