### ISSUE TITLE
Feature request: S3 upload progress for non-multi-part uploads

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js#1945]
It would be great if the XHR upload progress could be exposed somehow, for a single-part upload. E.g. if I'm uploading a single 3MB file, I still want to get progress updates as the upload progresses. Currently this doesn't appear to be possible.

**Comment by AllanFly120** [comment]
Yes you can do this. You can always listen to the `httpUploadProgress` event for `putObject` as well as `upload`. [This](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#httpUploadProgress-event) is the API reference. For example:
```javascript
bucket.putObject(params).on('httpUploadProgress', function(evt) {
    console.log("Uploaded :: " + parseInt((evt.loaded * 100) / evt.total)+'%');
}).send(function(err, data) {
    if(!err) {
        alert('upload complete');
        console.log(data.requestId);
    } else {
        console.log(err);
    }
});
```
Showing the upload persentage for multipart upload is similar, [here](https://aws.amazon.com/blogs/developer/announcing-the-amazon-s3-managed-uploader-in-the-aws-sdk-for-javascript/) contains an example of multipart upload.

**Comment by ffxsam** [comment]
Believe me, I've been through tons of different attempts, none of them work. 😫 

What winds up happening is, I upload (for example) a 1MB file. With your code, I would see something like this right away:

```
Uploaded :: 100%
```

And _then_ it uploads the whole file, sitting there, then completes.

Here's my test file I'm running:

```js
const S3 = require('aws-sdk/clients/s3');
const fs = require('fs');

const data = fs.readFileSync('/Volumes/Internal/Users/samh/Desktop/1MB.pdf');
const s3 = new S3();
const upload = s3
  .upload({
    Bucket: 'rc2-test',
    Key: 'wow.pdf',
    Body: data,
  })
  .on('httpUploadProgress', event => {
    console.log(`Uploaded ${event.loaded} out of ${event.total}`);
  })
  .send((err, data) => {
    console.log(err, data);
  });
```

**Comment by ffxsam** [comment]
Ahh, I'm glad I tried that! Yes, in front-end code, it works as you'd expect. Perfect!

Any idea why, in a Node.js environment, the `httpUploadProgress` event only gets called once?

**Comment by jeskew** [comment]
In browsers, the SDK [adds an event listener to the underlying XmlHttpRequest’s `progress` event](https://github.com/aws/aws-sdk-js/blob/master/lib/http/xhr.js#L42). In Node, progress is detected by the [body stream being read](https://github.com/aws/aws-sdk-js/blob/master/lib/http/node.js#L111), which can only be done for streaming inputs. For non-streaming inputs, the `http` module is given the entire body and tasked with sending it in the most efficient way. Thus there is only a single `progress` event emitted when the body is written in a single chunk to the `http` request stream.
