### ISSUE TITLE
AWS SDK for JS is not throwing an error when encountered a 403 (authentication error).

### ISSUE THREAD

**Issue by xlukaszgrabowskix** [aws/aws-sdk-js#1946]
It looks that AWS SDK for JS is not throwing an error when encountered a 403 (authentication error). That being said, these errors were not reported and measured in Lambda function's invocation errors metric.

**Comment by AllanFly120** [comment]
What service are you calling in lambda? If possible, can you show us the exception response data? As far as I know, it's not an intended behavior for SDK to ignore the errors.

**Comment by xlukaszgrabowskix** [comment]
I'm using AWS.NodeHttpClient().
(new AWS.NodeHttpClient()).handleRequest {} doesn't return Authorization error when AWS Elasticsearch cluster access is denied. Other errors are handled without issue.
Thanks

**Comment by jeskew** [comment]
Hi @xlukaszgrabowskix,

The `AWS.NodeHttpClient` doesn't convert HTTP messages into errors; that is handled further down the stack. When using the client outside of the SDK, you will need to inspect the response's status code. Errors will be emitted for connection and timeout errors.
