### ISSUE TITLE
[CodeCommit] API call to get repository content at specific branch/commit/tag

### ISSUE THREAD

**Issue by IlCallo** [aws/aws-sdk-js#1947]
Currently to download the last version of the content of a repo (for what I could find around searching) it's needed to upload and initialize a GIT client via a `git clone <repo-name> --depth=1 <path>`, which on a Lambda instance could be a bit cumbersome (we currently use `lambda-git` package).

I saw you implemented an endpoint into CodeCommit API to add a file into a repository, are you considering also a repo "shallow copy" feature? If it could be a "copy of contents at a target branch/commit/tag" it would be a great.

The use case, for me, is a process of automatic building of our application, which takes configuration files from different repo and merge them together, then saves the package in an S3 bucket and launch an EC2 instance to do the test+build process, saving it again in another S3 bucket.

As a side note: is this the right place to propose API additions? Is there some `internals` repo or something like that? Because there's a few things that could be useful but I don't actually know where to suggest them.

**Comment by AllanFly120** [comment]
I'm not sure if there are any existing workaround for your use case. You can raise your request for Codecommit API at [their forum](https://forums.aws.amazon.com/forum.jspa?forumID=189). I will close this issue since this is not actually an issue with SDK.
