### ISSUE TITLE
Windows 10 WSL: credential path is wrong

### ISSUE THREAD

**Issue by efortes** [aws/aws-sdk-js#1948]
When working on Windows 10 with WSL (Windows Subsystem for Linux)  the credential path is wrong in the config.

Can anyone fix this?

 **The error:**
```
{ message: 'Could not load credentials from SharedIniFileCredentials',
     errno: -2,
     code: 'CredentialsError',
     syscall: 'open',
     path: '%HOME%/.aws/credentials',
     time: 2018-02-23T14:14:57.525Z,
     originalError:
      { message: 'Missing credentials in config',
        errno: -2,
        code: 'CredentialsError',
        syscall: 'open',
        path: '%HOME%/.aws/credentials',
        time: 2018-02-23T14:14:57.525Z,
        originalError: [Object] } } }
````
This problem occurs because the `aws-sdk` sees WSL as windows. But it should see WSL as an ubuntu distro.

If you are facing the same error you can temporary fix this by doing the following:

**File**: `C:\Users\elvin\workspace\new10\new10-app/node_modules/aws-sdk/lib/util.js`

Edit method readFileSync by adding `path = path.replace('%HOME%', process.env.HOME)`.

```
    readFileSync: function readFileSync(path) {
        if (util.isBrowser()) return null
        // HACK
        path = path.replace('%HOME%', process.env.HOME)
        return require('fs').readFileSync(path, 'utf-8')
    },
```

**Comment by jeskew** [comment]
I'm having trouble trying to reproduce this issue. When [locating the home directory](https://github.com/aws/aws-sdk-js/blob/master/lib/shared_ini.js#L32), the SDK doesn't try to deduce the operation system on which it is running; instead, it first checks if `process.env.HOME` is defined, then falls back to `process.env.USERPROFILE`, then falls back to `process.env.HOMEPATH`, then finally tries `require('os').homedir()`.

To try to reproduce, I ran the following script:

```javascript
const AWS = require('aws-sdk')

const creds = new AWS.SharedIniFileCredentials()
creds.get(err => {
    if (err) console.error(err)
    else console.log(creds.accessKeyId)
})

```

This correctly identified my home directory on both Windows 10 and inside the WSL.

Can you check on what `process.env.HOME`, `process.env.USERPROFILE`, and `process.env.HOMEPATH` are set to inside of the WSL shell? Please note that `%HOME%` would be recognized as a string literal in Ubuntu (and not expanded as an environment variable). `%HOME%` is a legal directory name in Linux.

**Comment by efortes** [comment]
@jeskew seemed like an internal problem. The `AWS_CONFIG_FILE` env was there and pointing to the wrong path. I will close this ticket. Thank you for your reply.
