### ISSUE TITLE
s3.copyObject cannot copy files with special characters in them

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js#1949]
If a file has a special character in it (in this case, the endash "–"), it cannot be copied using `s3.copyObject`. Yet the odd thing is, S3 allows this character when the object is created. I can even create the file via the JS SDK with no problems, but copying fails.

**Comment by jeskew** [comment]
S3 requires the copy source to be URL-encoded, and unfortunately introducing this behavior to the SDK would be a breaking change. Please see #1302 & #712 for further discussion.
