### ISSUE TITLE
Can you help me with an example of CognitoIdentityServiceProvider

### ISSUE THREAD

**Issue by RameshRM** [aws/aws-sdk-js#1953]
Hi, 

I am using `cognito-sdk` from Lambda have full User Registraiton, Reset Pwd Flow. But I need contextual information to be passed from the `API Gateway` to Cognito, I found the `cognito-sdk` limiting, want to use `CognitoIdentityServiceProvider` for pwd reset flow and email messaging part. Can you point me how can i make use of "UserContextData" in a Lambda & Cognito flow and access the values ?

Thx

**Comment by jeskew** [comment]
Hi @RameshRM,

The best introduction to how to make use of `UserContextData` that I could find was [this blog post written by the Cognito team](https://aws.amazon.com/blogs/mobile/customizing-your-user-pool-authentication-flow/).
