### ISSUE TITLE
IAM endpoint CORS support

### ISSUE THREAD

**Issue by mwasiluk** [aws/aws-sdk-js#1957]
Hi,

Is there any way to enable CORS support for the IAM endpoint (Any update since #938)? 

Thanks

**Comment by jeskew** [comment]
Hi @mwasiluk,

There's nothing that can be done client-side to enable CORS support in IAM, so this is something the service team would need to handle. I'll update the internal request opened in response to #938, but please reach out to them directly via [their AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=76).
