### ISSUE TITLE
Expires field in copyObject/createMultipartUpload

### ISSUE THREAD

**Issue by ronayadid** [aws/aws-sdk-js#1959]
Hi,

I'm trying to understand the meaning of this parameter. 
When passing a date in this field, When looking at the object properties in S3 I see there is no expiration date in the object overview. I only see in the object's metadata an 'Expires' key and the value is the date I passed in the request.

How can I set the expiration date for an object from the API?

Thanks

**Comment by jeskew** [comment]
Hi @ronayadid,

The `Expires` parameter is included by S3 as then `'Expires'` header on responses to `GetObject` operations. Setting this value does not cause objects to be automatically deleted at that time by S3, but the header will be used by browsers and similar HTTP clients to control client-side caching as described in [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21).

**Comment by ronayadid** [comment]
Thanks @jeskew 

So the way S3 can automatically delete object is by using a bucket lifecycle rule?
