### ISSUE TITLE
s3.getSignedUrl('getObject') NOT WORK with static website hosting endpoint.

### ISSUE THREAD

**Issue by staradayev** [aws/aws-sdk-js#1961]
The first of all, while target bucket has open (public) bucket policy - all works okey.

When I'm trying to close public access to the bucket, and start using pre-signed urls a few unpredictable behavior appears.

For example:
**S3** bucket with **Static website hosting** enabled and **Redirection rules** like:

`<RoutingRules>
  <RoutingRule>
    <Condition>
      <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
    </Condition>
    <Redirect>
      <Protocol>http</Protocol>
      <HostName>MY_API_GATEWAY_ID.execute-api.us-west-2.amazonaws.com</HostName>
      <ReplaceKeyPrefixWith>prod/resize?key=</ReplaceKeyPrefixWith>
      <HttpRedirectCode>307</HttpRedirectCode>
    </Redirect>
  </RoutingRule>
</RoutingRules>
`

1. Way *Public policy*
If those configuration used with *Public policy* on the bucket.

in case where file is not found - MY_API_GATEWAY_ID was called.

2. *Not public bucket* pre-signed Url for S3
S3 config params:
`{
          accessKeyId: config.aws.accessKeyId,
          secretAccessKey: config.aws.secretAccessKey,
          region: config.aws.region
}`

Files which already exists at the bucket were returned by pre-signed url request

Files which are not exists, **not called MY_API_GATEWAY_ID** trough Redirection rules as expected.
It return an Error

`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>`

3. *Not public bucket* pre-signed Url for S3 bucket with static website endpoint and s3BucketEndpoint: true
S3 config params:
`{
          accessKeyId: config.aws.accessKeyId,
          secretAccessKey: config.aws.secretAccessKey,
          region: config.aws.region,
          endpoint: config.photoBucketEndpoint, // (or new AWS.Endpoint(config.photoBucketEndpoint) *it doesn't metter*)
          s3BucketEndpoint: true,
}`

3.1 Regular way not works
Files which already exists at the bucket were returned *403 Forbidden* - Access denied responce
Files which are not exists at the bucket were returned *403 Forbidden* - Access denied responce

3.2 It starts partially work, if we will remove region from url:
After a hours of investigation and different tries, i've found that if we've change the
**endpoint-bucket.*s3-website-us-west-2*.amazonaws.com/path/to/file**
to the 
**endpoint-bucket.*s3*.amazonaws.com/path/to/file**

Files which already exists at the bucket were returned by pre-signed, with region changed url request

Files which are not exists, **not called MY_API_GATEWAY_ID** trough *Redirection rules* as expected.
It return an Error

`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>`

# **Question:**
1. How I can manage to work a *Redirection rules* on the *Static website hosting* S3 with *pre-signed* URLs for have a chance to handle 404 responce with my API gateway?

2. Why s3.getSignedUrl() return the url doesn't wanna work for Static website hsoting enabled S3 endpoint?

Thank you!

**Comment by jeskew** [comment]
Hi @staradayev,

It sounds like everything's working fine with presigned URLs when you try to use the S3 REST API, but not when accessing the bucket via its static website URL. My understanding is that this is by design; S3 static website hosting requires that objects be publicly readable; otherwise a 403 is returned. [This developer guide from S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteAccessPermissionsReqd.html) explains permissions and static website hosting in more depth.
