### ISSUE TITLE
Issue with DynamoDB binary range query

### ISSUE THREAD

**Issue by jdgarrett** [aws/aws-sdk-js#1962]
I am not really sure where to post this issue, but I have encountered an odd behavior while performing a range query on a table with a composite key consisting of binary data.  I know the range in question should have well over 3k results, so I would expect the `LastEvaluatedKey` to be returned when either the size limit or the limit defined by the query is reached.  I found that in some cases, the `LastEvaluatedKey` was not returned when it should have been.  For example, with the following query parameters:

```
{
    "TableName": “test_table”,
    "KeyConditions": {
        "P": {
            "ComparisonOperator": "EQ",
            "AttributeValueList": [{
                "B": {
                    "0": 128
                }
            }]
        },
        "R": {
            "ComparisonOperator": "BETWEEN",
            "AttributeValueList": [{
                "B": {
                    "0": 104,
                    "1": 97,
                    "2": 105,
                    "3": 108,
                    "4": 17,
                    "5": 155,
                    "6": 255,
                    "7": 248,
                    "8": 0,
                    "9": 0,
                    "10": 0,
                    "11": 0
                }
            }, {
                "B": {
                    "0": 104,
                    "1": 97,
                    "2": 105,
                    "3": 108,
                    "4": 17,
                    "5": 156,
                    "6": 127,
                    "7": 255,
                    "8": 255,
                    "9": 255,
                    "10": 255,
                    "11": 255
                }
            }]
        }
    },
    "Limit": 1,
    "Select": "COUNT"
}
```
I get the following results as expected:
```
{
    "Count": 1,
    "ScannedCount": 1,
    "LastEvaluatedKey": {
        "P": {
            "B": {
                "type": "Buffer",
                "data": [128]
            }
        },
        "R": {
            "B": {
                "type": "Buffer",
                "data": [104, 97, 105, 108, 17, 156, 0, 47, 81, 179, 200, 224, 104, 97, 105, 108, 46, 50, 51]
            }
        }
    }
}
```
However, by simply increasing the value of the end range by 1, the `LastEvaluatedKey` is not returned (note the change in the second attribute value of the 'R' condition):
```
{
    "TableName": "test_table",
    "KeyConditions": {
        "P": {
            "ComparisonOperator": "EQ",
            "AttributeValueList": [{
                "B": {
                    "0": 128
                }
            }]
        },
        "R": {
            "ComparisonOperator": "BETWEEN",
            "AttributeValueList": [{
                "B": {
                    "0": 104,
                    "1": 97,
                    "2": 105,
                    "3": 108,
                    "4": 17,
                    "5": 155,
                    "6": 255,
                    "7": 248,
                    "8": 0,
                    "9": 0,
                    "10": 0,
                    "11": 0
                }
            }, {
                "B": {
                    "0": 104,
                    "1": 97,
                    "2": 105,
                    "3": 108,
                    "4": 17,
                    "5": 156,
                    "6": 128,
                    "7": 0,
                    "8": 255,
                    "9": 255,
                    "10": 255,
                    "11": 255
                }
            }]
        }
    },
    "Limit": 1,
    "Select": "COUNT"
}
```
This returns the following result:
```
{"Count":1,"ScannedCount":1}
```
I am wondering if there is some kind of signed comparison within DynamoDB that is causing the `LastEvaluatedKey` to not be returned as the issue only seemed to present itself when 7th byte of the end range reached 128.  With an unsigned comparison of that value against the last evaluated key, it would be greater, but if it was an unsigned comparison, it would be less.  The documentation states that DynamoDB treats all binary comparisons as unsigned, so I am not sure.

I have also seen the same behavior when performing the same query through the java sdk.

**Comment by jeskew** [comment]
Since you're seeing the same behavior with the Java SDK, the issue likely does not reside in the client. Would you be able to open an AWS support ticket with the same question? I can send forward this issue to the DynamoDB team, but contacting them directly will be the fastest way to get a response. You can also reach out to the service team directly via [their AWS developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=131).

**Comment by jdgarrett** [comment]
Thanks for the quick response!  I will post the issue on the developer forum.
