### ISSUE TITLE
How can I use a customized build of the AWS sdk in ReactJS?

### ISSUE THREAD

**Issue by bootrino** [aws/aws-sdk-js#1965]
I make a customized build here of the AWS SDK:

https://sdk.amazonaws.com/builder/js/

I can't find any examples of how to use this in ReactJS.  Can anyone please point me in the right direction?

I have tried putting this in my index.html

`<script src="./aws-sdk-2.207.0.min.js"/>`

And in my ReactJS code replaced imoprt with var:

```
//import AWS from 'aws-sdk'
var AWS = require('aws-sdk')
```

Also tried this which did not work:

`import * as AWS from 'aws-sdk';`

But now my application does not even load - shows only the background image and does not load - absolutely zero shows in the Chrome console - no messages at all.

![screen shot 2018-03-11 at 3 31 10 pm](https://user-images.githubusercontent.com/22624099/37249828-2d5c2b94-2543-11e8-839c-3f404d7d8858.png)

I can see in the Chrome network console that the custom sdk build is being loaded OK with a status 200 so that seems to be OK.

I've also tried:

```
import EC2 from 'aws-sdk/clients/ec2'
import Credentials from 'aws-sdk/clients/credentials'
import Pricing from 'aws-sdk/clients/pricing'

```

Now I;m just doing voodoo programming - trying anything and hoping it might work.

Can anyone suggest what I need to do please?

thanks

**Comment by chrisradek** [comment]
@bootrino 
Are you building a react app using create-react-app, or some bundler like webpack?

If you're doing either, then you should be able to import the clients you need directly:
```javascript
// es2015 imports
import * as EC2 from 'aws-sdk/clients/ec2';
// or commonjs style
const EC2 = require('aws-sdk/clients/ec2');
```

**Comment by bootrino** [comment]
Hi Chris - I wanted to use the Pricing API which does not seem to be built in to the npm version of the aws-sdk.

I also wanted to trim down the aws sdk to only include the services that my application actually uses.

Are there instructions for how to do this and use it in ReactJS?

thanks

**Comment by srchase** [comment]
@bootrino 

The Pricing API is built into the NPM version of the SDK.

You can require and instantiate the pricing client like this:

```
const pricing = require('aws-sdk/clients/pricing');
const pricingClient = new pricing({region: 'us-east-1'})
```
