### ISSUE TITLE
Documentation is really hard to use on iPad

### ISSUE THREAD

**Issue by ctranstrum** [aws/aws-sdk-js#1968]
The HTML layout of the documentation makes it really hard to access on an iPad. The menu on the left is allowed to flow beyond the bottom of the visible page, but the documentation is stuck in a box that is the size of the visible page. When scrolling, most of the time the iPad scrolls the menu, which moves the actual content box up and off the page. If you're really careful when you click, you can usually find a spot in the content box that will allow you to scroll that box, but it's a pretty hit or miss scenario. The end result being that it's almost useless trying to use an iPad as a quick reference for AWS Javascript SDK documentation.

To reproduce: grab an iPad and navigate to https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/_index.html, then click on any individual service's API. Then try to scroll through the entire content of the API documentation.

**Comment by AllanFly120** [comment]
Hi @ctranstrum 
We already noticed this issue and will take step to improve the experience on mobile devices. Thank you very much for informing us this.

**Comment by ajredniwja** [comment]
Hi @ctranstrum,

Is this still an ongoing issue? Closing this issue for now please reach out if you continue to see the problem.
