### ISSUE TITLE
ScanFilter

### ISSUE THREAD

**Issue by sheibeck** [aws/aws-sdk-js#1969]
I'm trying to scan() with DocumentClient() in javascript and when I use multiple values in the AttributeValueList it I'm getting an error: 

> One or more parameter values were invalid: Invalid number of argument(s) for the CONTAINS ComparisonOperator

```javascript
params.ScanFilter = {
  'adversary_name': {
    ComparisonOperator: 'CONTAINS',
    AttributeValueList: ["dog", "Dog"]
  }
}
```

**Comment by jeskew** [comment]
According to https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Condition.html#DDB-Type-Condition-ComparisonOperator, a `CONTAINS` filter predicate may only have one item in its `AttributeValueList` property. You could try using a condition expression instead:

```
params.FilterExpression = 'contains(adversary_name, 'dog') OR contains(adversary_name, 'Dog')'
```

**Comment by sheibeck** [comment]
Ahh, thanks.
