### ISSUE TITLE
getSignedUrl for V4 Authorization

### ISSUE THREAD

**Issue by Vishesh07** [aws/aws-sdk-js#1970]
getSignedUrl creates v2 url which is not supported for some regions. So, is there any way by which we can create v4 url or can download private object from bucket.

**Comment by chrisradek** [comment]
@Vishesh07 
You can force the S3 client to use sigv4:
```javascript
var s3 = new AWS.S3({signatureVersion: 'v4', region: 'YOUR_REGION'})
```

The SDK should already be defaulting to sigv4 though if you've configured your client to be using a region that only supports sigv4 and not sigv2. Which region are you still seeing the v2 url in?
