### ISSUE TITLE
Method to check if a bucket has enabled the Accelerated Transfer

### ISSUE THREAD

**Issue by fcarrilLB** [aws/aws-sdk-js#1971]
I need a method to check if a bucket has enabled the Accelerated Transfer, then, if it's enabled, I could initialize the `AWS.S3` with the accelerated transfer enabled

Currently, if I initialize the `AWS.S3` with `useAccelerateEndpoint: true` and the bucket has not the Accelerated Transfer enabled I got the next error: `S3 Transfer Acceleration is not configured on this bucket`

Is there any way to check this before do the request?

**Comment by chrisradek** [comment]
@fcarrilLB 
I think you're looking for the [getBucketAccelerateConfiguration](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getBucketAccelerateConfiguration-property) method.

However, this does mean after you make the request, you may need to create a new S3 client with `useAccelerateEndpoint` set to the value you want.

**Comment by fcarrilLB** [comment]
@chrisradek
That's exactly what I was looking for, thank you very much!

**Comment by chrisradek** [comment]
Awesome!
