### ISSUE TITLE
StepFunctions not included in the build

### ISSUE THREAD

**Issue by l-hendriks** [aws/aws-sdk-js#1972]
I am trying to use StepFunctions in the JS SDK. However, StepFunctions is not included in the AWS object.

This does not work:
```
import * as AWS from 'aws-sdk';
AWS.StepFunctions // undefined
```

This works:
```
import StepFunctions from 'aws-sdk/clients/stepfunctions';
// StepFunctions is now defined
```

**Comment by AllanFly120** [comment]
Hi,

I cannot reproduce this issue. Have you tried npm reinstall the aws-sdk? or update to newest version.

**Comment by rbirkby** [comment]
Is this browser-based? If so, StepFunctions does not support CORS and therefore isn't included in the default build:
https://github.com/aws/aws-sdk-js/blob/master/SERVICES.md

**Comment by srchase** [comment]
Closed for inactivity.
