### ISSUE TITLE
adminInitiateAuth - Session

### ISSUE THREAD

**Issue by jlfabi** [aws/aws-sdk-js#1976]
After calling the adminInitiateAuth method, using ADMIN_NO_SRP_AUTH as the AuthFlow value,  how long does session value last?

**Comment by jeskew** [comment]
The ID and access tokens you receive are valid for one hour per [the Cognito developer guide](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html). The refresh token is valid for 30 days by default, but this is configurable.

As far as I could tell from the developer guide, token validity is not affected by the AuthFlow selected.

**Comment by srchase** [comment]
This looks like a usage question and not an issue with the SDK.  Closing this out, but let us know if you have any issues getting things configured properly.
