### ISSUE TITLE
ACM requestCertificate: Unexpected key 'ValidationMethod'

### ISSUE THREAD

**Issue by bencmbrook** [aws/aws-sdk-js#1978]
I've matched my request exactly to the spec in the docs, and I'm getting an unexpected key error.

`{ UnexpectedParameter: Unexpected key 'ValidationMethod' found in params ...`\

```js
const acmCertificate = await acm.requestCertificate({
  DomainName: `*.${organization.domain}`,
  SubjectAlternativeNames: [
    `${organization.uri}.${HOSTED_PAGES_BASE_DOMAIN}`,
  ],
  ValidationMethod: 'DNS',
}).promise();
```

As you can see [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ACM.html#requestCertificate-property), this is according to spec.

To me, it seems that either I messed something up in this call and it's triggering the wrong error, or the SDK isn't matching the docs.

**Comment by AllanFly120** [comment]
which sdk version are you using? It seems that the parameter is only added in [2.156.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#21560).

**Comment by bencmbrook** [comment]
@AllanFly120 the latest, assuming this works:
```js
const acm = new AWS.ACM({ apiVersion: 'latest' });
```

**Comment by bencmbrook** [comment]
Were you able to replicate this? Still no luck for me. Not so sure this should stay labeled as a question

**Comment by bencmbrook** [comment]
Got it. NPM package was in fact out of date. Thanks
