### ISSUE TITLE
SignatureDoesNotMatch error from putObject

### ISSUE THREAD

**Issue by gischer** [aws/aws-sdk-js#1984]
I'm getting a SignatureDoesNotMatch return from the server when I use this code.  It is intended to be used to upload a user avatar.  I'm hardcoding the accessKeyId and secretAccessKey for now, and taking the file and key for uploading from a web form:

```
 document.getElementById("upload-button").onclick = function() {
     const key = document.getElementById("key-text").value;
     var file = document.getElementById("file-chooser").files[0];

     const S3 = new AWS.S3({`
      signatureVersion: "v4",
      apiVersion: '2006-03-01',
      accessKeyId: 'ACCESS_KEY_ID',
      secretAccessKey: 'SECRET_ACCESS_KEY',
      region: 'us-west-2'
    })

      S3.putObject({
        Key: key,
        Bucket: 'my-bucket-name',
        Body: file,
      }, (err, data) => {
        if (err) {
          alert("Error: " + err);
        } else {
          alert("Upload successful: " + data);
        }
      })
  }
 document.getElementById("upload-button").onclick = function() {
     const key = document.getElementById("key-text").value;
     var file = document.getElementById("file-chooser").files[0];

     const S3 = new AWS.S3({`
      signatureVersion: "v4",
      apiVersion: '2006-03-01',
      accessKeyId: 'ACCESS_KEY_ID',
      secretAccessKey: 'SECRET_ACCESS_KEY',
      region: 'us-west-2'
    })

      S3.putObject({
        Key: key,
        Bucket: 'ilarp-data-prod-1',
        Body: file,
      }, (err, data) => {
        if (err) {
          alert("Error: " + err);
        } else {
          alert("Upload successful: " + data);
        }
      })
  }

```
The code above gives me an error return of SignatureDoesNotMatch  I'm a bit mystified by that, since I thought I was letting the API do the signing, and earlier versions of this (which I unfortunately cannot reproduce) did not give me this error.

**Comment by AllanFly120** [comment]
@gischer Sorry for the late reply. The code you post here looks good. Can you share a reproducable code snippet here?

**Comment by gischer** [comment]
@AllanFly120 Thank you for your interest.  I have resolved this issue. Ultimately what happened is I was working with two different access keys and got them mixed up:  access_key_id and secret_access_key from the other.  Which quite clearly should lead to the error shown.

This happened despite my checking that it wasn't happening.  So I was apparently experiencing an hallucination.  At least it was temporary.

I suspect that the issue that started me down this path was that I was trying to set an ACL with the call to putObject, but the policy didn't grant permission to set ACLs.

It's all working now.
