### ISSUE TITLE
SQS receiveMessage does not return Attributes

### ISSUE THREAD

**Issue by lajpatshah** [aws/aws-sdk-js#1988]
My code is as below
sqs.receiveMessage({
    QueueUrl: sqsQueueUrl,
    AttributeNames: [ 'All '],
    MaxNumberOfMessages: 1, .......

In response I am not receiving any list of attributes. Please help.

**Comment by AllanFly120** [comment]
Hi, @lajpatshah 
Can you share what response did you get? Http response body is also helpful.
```javascript
sqs.receiveMessage(params, function(data, error) {
    if (data) {
        console.log('success!');
        console.log(data);
    } else {
        console.log('fail: ', error);
        console.log('body: ', this.httpResponse.body.toString'utf8')//print response body
    }
})
```

**Comment by lajpatshah** [comment]
Hi @AllanFly120 
Thanks for guidance.
I tried again my original code & now I am receiving the attributes. I did not changed my code yet why I couldn't receive the attributes earlier is not clear to me.
One thing is I had created Queue on the day of testing the code itself. Could be that attributes are not given immediately? Just wondering.
Thanks
