### ISSUE TITLE
Cloudfront Signer not using AWS4 Signatures, prevents KMS encrypted uploads.

### ISSUE THREAD

**Issue by Aedalus** [aws/aws-sdk-js#1994]
I can successfully upload files to s3 through cloudfront when using the `"x-amz-server-side-encryption": "AES256",` header. However when I try to switch to use the kms headers

`"x-amz-server-side-encryption-aws-kms-key-id": "my_key_arn"`
`"x-amz-server-side-encryption": "aws:kms"`

then when I do a PUT request to the signed URL I get the error `Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.` Attached is a snippit of my code, to see if I am possibly uploading incorrectly.

```
    const Signer = new AWS.CloudFront.Signer(process.env.CF_KEYPAIR_ID,process.env.CF_PRIVATE_KEY);
    let expires = Math.round(new Date().getTime() / 1000) + 30; //Expire in 30 seconds
    let signedURL = Signer.getSignedUrl({url: "https://d3ubkrhcrypa2w.cloudfront.net/tmp/testtext3.txt",expires});

    try {
      let options = {
        headers: {
          "x-amz-server-side-encryption-aws-kms-key-id": "process.env.kms_arn",
          "x-amz-server-side-encryption": "aws:kms",
          // "x-amz-server-side-encryption": "AES256", // Switching to this works fine.
          "x-amz-acl": "bucket-owner-full-control"
        }
      };
      let result = await axios.put(signedURL, "Hello World",options);
      console.log(result.data);
    } catch (err) {
      console.error(err);
    }
```

**Comment by srchase** [comment]
Hello @Aedalus,

Thanks for reaching out with this question.  I apologize that we did not respond sooner.

Currently, the SDK's CloudFront signer produces V2 signatures.  There could be work done to add support for V4 signatures, but we first need to confirm that CloudFront supports KMS encrypted uploads to S3.  I've contacted the CloudFront team with that question and will update this issue once I've gotten a response.

If they confirm it's possible, we can then track this as a feature request.

**Comment by srchase** [comment]
@Aedalus 

The Service Team confirmed that KMS encrypted PUTs via CloudFront are possible.

There are however a few requirements:
1.  This cannot be done with an Origin Access Identity in place.  That OAI cannot be accessed by KMS.
2. The signature needs to be calculated for the underlying S3 API endpoint: a PUT for 'foo.txt' to 'mybucket.s3.amazonaws.com' would have to be calculated against: 'mybucket.s3.amazonaws.com/foo.txt'.
3. That signature must be added as a query string or headers on the PUT to CloudFront.

**Comment by kwarnkepcty** [comment]
@Aedalus - Sorry to dig this thread up from the past but I'm running into a very similar issue although I'm trying to upload through CloudFront and have CloudFront inject the headers mentioned above.  This will allow us to maintain a list of Key Ids on the AWS side and not leak those out into the browser that are performing the uploads.

Here is my Lambda@Edge for Origin Request:

```
'use strict';
 exports.handler = (event, context, callback) => {
     const request = event.Records[0].cf.request;
     request.headers['x-amz-acl'] = [{ key: 'x-amz-acl', value: 'bucket-owner-full-control'}];
     request.headers['x-amz-server-side-encryption'] = [{ key: 'x-amz-server-side-encryption', value: 'aws:kms'}];
     request.headers['x-amz-server-side-encryption-aws-kms-key-id'] = [{ key: 'x-amz-server-side-encryption-aws-kms-key-id', value: 'MY KEYID'}];

    callback(null, request);
};
```

I'm getting the same error `Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.`

I'm not sure how your answer from December would apply to me.  I am currently using an OAI but I'm not sure how to get uploads to work without one.  I'm also not creating any signatures myself (I'm assuming that CloudFront is doing that under the hood).  Is there a way for me to tell CloudFront to use SigV4?

Thanks!
Kevin
