### ISSUE TITLE
lib/s3/managedUpload.js #fillStream

### ISSUE THREAD

**Issue by mdaum** [aws/aws-sdk-js#1995]
I recently implemented a lambda that streams documents from MongoDB into an S3 bucket using managed-upload. I ran into quite a bit of issues using a custom object stream wrapping MongoDBClient's cursor with managedUpload's read loop. The event driven nature of the loop, as well as using read(0) to kick the stream into emitting another readable event seemed to cause the most strife. I have noticed that if the stream's underlying source is exhausted but there is still contents in the internal buffer, read(0) will not result in a readable being emitted, but instead will return null, resulting in the 'end' event never being emitted, making the upload hang until lambda timeout. If the end event is triggered manually on the stream side, the remaining internal buffer is obviously left out of the upload. I had to do some work to force the stream to essentially detect this situation and emit readable's until the internal buffer is exhausted.

I would love to know why you guys opted for read(0) as the primary read loop mechanism instead of a simple iterative approach. I'm sure there is a good reason, but it is not jumping out at me. I have found that this issue is most easily reproduced locally (via lambda-local or SAM-Local) by setting the queueSize to 1 and pumping a large amount of data through the lambda (about 500MB or so on a 5 MB partSize). Let me know if you have any questions. Thanks.

**Comment by srchase** [comment]
@mdaum 

Thanks for your patience.

I apologize we missed this issue.

Were you able to resolve this issue?  If so, what change did you make?  

Which simple iterative approach did think might be a better approach for the SDK to use?
