### ISSUE TITLE
Union member `Blob` is used in public types but is not exported itself.

### ISSUE THREAD

**Issue by fahrradflucht** [aws/aws-sdk-js#1997]
A lot of service typings have a private type alias for `{}` named `Blob`. Some don't use it but for example the [S3 client typings use it in the union type for `S3.Body`](https://github.com/aws/aws-sdk-js/blob/d6518e0f73f62aae688acc4cd9ee74f1af2f3326/clients/s3.d.ts#L777).

This is not a good practice because it causes TypeScript errors in modules that have the public union part of their own public API since it can not be named.

**Comment by ljharb** [comment]
Additionally, since it's just the empty interface, it incorrectly matches any object, which caused me to get an error in production.

Can that type please be changed to something that either contains the actual interface, or is like `{ readonly brand: unique symbol }`?

**Comment by ljharb** [comment]
This is still a problem.

Also, bots closing issues is very user-hostile.

**Comment by ryami333** [comment]
What even is the attention of that `Blob` type? Shouldn't it just be removed outright, in favour of the native Blob object?

**Comment by ljharb** [comment]
It’s not a native Blob instance though. If the library accepted and produced that, then that would be the correct type.

Note as well, Blob doesn’t exist in node, only in browsers, so that would make this package useless :-)

**Comment by ljharb** [comment]
Eternally an issue until it’s fixed.

**Comment by ljharb** [comment]
nope, bump forever

**Comment by OneHoopyFrood** [comment]
Still an issue. What is this type supposed to represent?

**Comment by OneHoopyFrood** [comment]
Seems like it should be the native Blob type, which _does_ exist in Node now. This seems like it's just a mistake.

**Comment by kellertk** [comment]
Hi, I am closing this issue because we are no longer considering feature requests for AWS SDK for JS v2. Please migrate to AWS SDK for JS v3.
