### ISSUE TITLE
Is it possible to allow Unauthorized Certification?

### ISSUE THREAD

**Issue by HappyRainy** [aws/aws-sdk-js#1998]
I am using a bastion box with SSH Tunnel to connect Elastic Search Cluster from my local development environment. Since the ES cluster host is https://localhost:9200 from my local, the SSL certificate returned with the request is invalid. Then, AWS SDK refuses to connect. If we can provide a way to set the option `rejectUnauthorized` based on environment. It will really easy for development.

https://github.com/aws/aws-sdk-js/blob/8904e9c730fb2fccf9d201f66266a6e2cbb75348/lib/http/node.js#L141

**Comment by chrisradek** [comment]
@HappyRainy 
You can construct your own `https.Agent` and pass it into a client constructor.
 
You can also configure your agent to accept additional certs:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-registering-certs.html

You can modify the example in the docs for your use case as well to set `rejectUnauthorized` to false, though understand that this will prevent checking the certs for any network calls you make using that agent.
