### ISSUE TITLE
Errors with SDK on require since 2.221.1 update

### ISSUE THREAD

**Issue by murphman300** [aws/aws-sdk-js#1999]
Hello, Having two errors (the first which was fixed within 5 minutes of this error showing up).

First error, on npm start -ing my app:

`module.js:540
    throw err;
    ^

Error: Cannot find module './connect'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/spotituserprod/node_modules/aws-sdk/clients/all.js:135:12)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spotituserprod@0.0.0 start: `npm install --save && node ./app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spotituserprod@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-04-05T16_28_38_507Z-debug.log`

Which now does not happen,

However, i reinstalled the sdk, and i now get this error:

`(node:14554) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module './request_types/http1_2'
(node:14554) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I don't have any files or modules named request_type or http1_2, so i am assuming this is on the side of the SDK.

Running on t2.micro on amazon linux.

Any updates on an upcoming fix would be great

**Comment by murphman300** [comment]
Nevermind, second error was another package. Thanks for the quick fix on the first issue!

**Comment by chrisradek** [comment]
Thanks for posting back, closing!

**Comment by murphman300** [comment]
Apologies for jumping back in, the fix only seems to work if i npm uninstall/install manually post fetch from my app's repo. If you notice in the first copy-paste in the code in my post, i call npm install on npm start (this is an auto-deploy app on ec2 from a custom ami).

This is first for the first launch start, however, my git hook which re-bases the app's directory on repo updates seems to reset the uninstall/install fix, meaning i still have to manually uninstall/install the aws-sdk package each time. The error i get is still the same, any clue as to why this might be happening? It wasn't doing this yesterday

**Comment by chrisradek** [comment]
@murphman300 
So it looks like based on your error, when you start your app it can't find [this file](https://github.com/aws/aws-sdk-js/blob/v2.221.1/clients/connect.js). Can you verify the contents of the AWS SDK when you run `npm start` and which version it is? If that file is missing, I'd like to check if it's missing when you initially download it from npm, or it is somehow getting deleted afterthe fact.

**Comment by murphman300** [comment]
It seems that the file ./connect in the clients directory isn't present when running npm install inside a clean directory (before uninstall/install or running npm install through npm start), and after the previous approaches
