### ISSUE TITLE
Use EC2 client of aws-sdk (JS) in a browser

### ISSUE THREAD

**Issue by nkratzke** [aws/aws-sdk-js#200]
I am wondering whether it is (should be) possible to get the EC2 Client of aws-sdk-js library working in a browser and not in a node.js environment?

I just get answers from AWS like: Failed to load resource: the server responded with a status of 400 (Bad Request).

Is this a CORS problem? My code works fine in a node.js environment but not in the browser (chrome, firefox, safari all the same error above).

Here is the working code (node.js):

```
var AWS = require('aws-sdk');

var ec2 = new AWS.EC2({
    accessKeyId: "snipped",
    secretAccessKey: "snipped",
    region: "eu-west-1"
});

ec2.describeInstances({}, function(err, data) {
    if (err) {
        console.log(err);
        return;
    }

    for (var r in data.Reservations) {
        for (var i in data.Reservations[r].Instances) {
            var instance = data.Reservations[r].Instances[i];
            var state = instance.State.Name;
            console.log(instance.InstanceId + " (" + state + ") " + instance.PublicDnsName);            
        }
    }
});
```

For browser I generated a aws-sdk including the EC2 client according to this link:
http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-building.html

and included it this way in the head element of the html document.

```
<script src="js/3rd-party-libs/aws-sdk-ec2.js"></script>
```

The code stays the same:

```
var ec2 = new AWS.EC2({
    accessKeyId: "snipped",
    secretAccessKey: "snipped",
    region: "eu-west-1"
});

ec2.describeInstances({}, function(err, data) {
    if (err) {
        console.log(err);
        return;
    }

    for (var r in data.Reservations) {
        for (var i in data.Reservations[r].Instances) {
            var instance = data.Reservations[r].Instances[i];
            var state = instance.State.Name;
            console.log(instance.InstanceId + " (" + state + ") " + instance.PublicDnsName);            
        }
    }
});
```

**Comment by lsegal** [comment]
@nkratzke Quick update in case you're still interested! Amazon EC2 has recently introduced CORS support and the AWS.EC2 service is now available in the hosted build of the AWS SDK for JavaScript in the browser:

http://blogs.aws.amazon.com/javascript/post/Tx30V18CDJFNSB/Announcing-CORS-Support-for-Amazon-EC2

**Comment by nkratzke** [comment]
Thanks a lot for this information.

Nane


Loren Segal <notifications@github.com> schrieb am Fr., 12. Juni 2015 um
01:47 Uhr:
