### ISSUE TITLE
API docs mention non-documented property "region"

### ISSUE THREAD

**Issue by mt-ronkorving** [aws/aws-sdk-js#2000]
On https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html in the constructor configuration it mentions under the `region` property to `See AWS.S3.region for more information.` That property doesn't seem to be documented however.

The reason why I ended up looking for that was that I was curious if the constructor would throw an error if a region was provided that didn't exist (ie: a spelling error was made).

**Comment by mt-ronkorving** [comment]
@AllanFly120 Thanks for the feedback. Do you know by any chance if there's a machine-parseable file with the information from that table?

**Comment by AllanFly120** [comment]
@mt-ronkorving  our SDK doesn't provide such command. The best I can find is in Python SDK boto3 [get_available_regions function](http://boto3.readthedocs.io/en/latest/reference/core/session.html?highlight=get_available_partition#boto3.session.Session.get_available_regions)

**Comment by mt-ronkorving** [comment]
@AllanFly120 Sure 👍 

Given that you closed this issue, does that mean the documentation issue has been resolved?
