### ISSUE TITLE
s3 select support

### ISSUE THREAD

**Issue by YousefED** [aws/aws-sdk-js#2001]
Am I correct that the SDK doesn't yet support S3 Select? Any idea when this will be available now S3 Select has been rolled out?

Thanks,

**Comment by AllanFly120** [comment]
Hey @YousefED, thank you very much for following our new features closely. You are right, Javascript SDK doesn't support S3 select yet. But this feature is among the top of our priority list. So please stay tuned.

**Comment by JorisAndrade** [comment]
Definitely interested by this feature too ! :)

**Comment by imjustd** [comment]
Is this done? I see in the changelog https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#22341 this feature: S3: Added BytesReturned details for Progress and Stats Events for Amazon S3 Select

**Comment by Rinoir** [comment]
Is there any information, when this feature will be implemented?

**Comment by joshrussell** [comment]
+1. I have a use case for S3 Select now. Is this released yet?

**Comment by chrisradek** [comment]
S3 select is not implemented yet but is being worked on. #2054 is the first PR to add support, and we'll be merging into the `wip-s3-select` branch until it's ready to be released.

There will be a few tasks to complete before we merge into master (like documentation/typescript definitions) but I can respond back here once the branch is useable so you can try it out before its final release.

**Comment by chrisradek** [comment]
Unfortunately I can't give a better idea except that we are actively working on it now.

**Comment by chrisradek** [comment]
@kymc and others
S3 Select support has officially landed in version 2.256.1 of the SDK (yesterday's release).

Take a look at the docs for info on how to use it:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#selectObjectContent-property

Please let us know if something isn't clear in the docs. This is a new pattern where the JSON output contains a stream that emits the events from S3.

Closing now that this is in the SDK!

**Comment by alexvpickering** [comment]
This doesn't seem to be available on lambda environment version yet ([listed as](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) AWS SDK – AWS SDK for JavaScript version 2.233.1).

**Comment by jewelsjacobs** [comment]
bummer.

**Comment by jewelsjacobs** [comment]
Being able to get this supported in lambda would be great.

**Comment by willvincent** [comment]
@chrisradek 

> Please let us know if something isn't clear in the docs. This is a new pattern where the JSON output contains a stream that emits the events from S3.

Basically nothing is clear. your examples are fairly worthless, most of the available (even required) properties are so poorly documented that one must guess about what they mean. This is a problem that plagues aws documentation across the board.

You have good tools, but the instructions on their use tend toward being so obtuse, incomplete and uninformative that it's hard to get excited about _using_ your tools.

Please run this up the flagpole to whomever needs to see it and make generation of GOOD documentation a priority.

**Comment by robermar2** [comment]
I'd like to second the lack of documentation on this.  

The examples in the documentation don't work.

Nor is their a clear explanation on how to actually get this new pattern working with async/promises, if it even can.

**Comment by srchase** [comment]
@jewelsjacobs Lambda is now using 2.290.0, so you'll be able to use this operation.

@willvincent 

We appreciate your candid feedback. Is there a specific spot where you got stuck?  If you were interested in posting an example, we'd be happy to help clear up any issues (and improve the documentation where possible).

@robermar2

I do see there is a typo in the [Async Iterator EventStream Example (Experimental)](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#selectObjectContent-property).  The line ```const events = data.Payload;``` should be ```const events = result.Payload;```

Would that solve your issue?  Or is there something else that isn't working?

**Comment by srchase** [comment]
Fix for the Async Iterator EventStream example in https://github.com/aws/aws-sdk-js/pull/2549

**Comment by chrisradek** [comment]
Just wanted to chime in in case this helps someone; there is a more complete example of using S3 Select written in [this blog post](https://aws.amazon.com/blogs/developer/introducing-support-for-amazon-s3-select-in-the-aws-sdk-for-javascript/). It's still a relatively simple example but gives a more in-depth look at the feature.

I think in general the examples that are detailed in blog posts should find their way back into the developer guide.

**Comment by robermar2** [comment]
@srchase I was using lambda with nodejs 8.10 runtime.

So I was using the EventStream example and was confused on the async logic.  I needed to wrap the selectObjectContent call (and thus also handling of the event stream) in a promise as my call was in an async function.
