### ISSUE TITLE
DynamoDB - Auto Scaling Configuration

### ISSUE THREAD

**Issue by mogwai** [aws/aws-sdk-js#2002]
Are you planning to add auto scale configuration to the createTable and updateTable methods

**Comment by AllanFly120** [comment]
Hi @mogwai,
Thank you for bringing this up. I agree it's very useful to add this configuration. But our SDK is not able to implement this feature unless DynamoDB service updates the [API](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html). I've already cut a ticket to service team concerning this feature. You can also call this out on the [DynamoDB forum](https://forums.aws.amazon.com/forum.jspa?forumID=131) where it is visible from service team.

**Comment by AllanFly120** [comment]
@mogwai  I find you can do this using [ApplicationAutoScaling service](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.HowTo.SDK.html). The basic idea is to call `ApplicationAutoScaling.registerScalableTarget` to register autoscaling to the DynamoDB table. And then call `ApplicationAutoScaling.putScalingPolicy` to edit your policy. Comment if you have more question.
