### ISSUE TITLE
S3 Pre-Signed url with PUT update the file lastModified but not the content

### ISSUE THREAD

**Issue by maxeber** [aws/aws-sdk-js#2004]
### S3 Pre-Signed url with **PUT** update the file `lastModified` but not the content
*aws-sdk: 2.221.1*

On the server, I have a route that dynamically put a new file on an S3 bucket and then send back a `signed url` to the client.

```javascript
function getS3PreSignedUrl(req, res) {
    S3.putObject({
        Bucket: myBucket,
        Key: myKey,
        Body: Buffer.from('Blank').toString(),
        ContentType: 'text/csv'
    },
        () => res.status(200).send({ url: _generateS3PreSignedUrl() })
    )
}

function _generateS3PreSignedUrl() {
    const signedUrlExpireSeconds = 60 * 5
    const url = S3.getSignedUrl('getObject', {
        Bucket: myBucket,
        Key: myKey,
        Expires: signedUrlExpireSeconds
    })
    return url
}
```

So I tried a `signed url` with a simple curl `PUT` and something strange occur. It seems the `key` that the url point to let me update it but only the `lastModified` column gets updated. If I download the file, it's still the same old `Blank` file.

**Comment by srchase** [comment]
Hello @maxeber,

I apologize that we did not respond to your question sooner.

This line ```const url = S3.getSignedUrl('getObject', {```, includes 'getObject'.  Did you intend for that to be 'putObject'?

If you already resolved this issue, let us know and we can close this out.  If it's still an issue for you, we're happy to help.
