### ISSUE TITLE
234 kB download. Just to upload a photo to s3

### ISSUE THREAD

**Issue by cekvenich** [aws/aws-sdk-js#2009]
In order to upload a photo to S3, I need:
https://sdk.amazonaws.com/js/aws-sdk-2.224.1.min.js

That is 234 kB download. 
For comparison, jquery is ~34 kB - and we avoid it due to size, and this is 10x.

How can I slim down .js when used for photo upload only?

**Comment by AllanFly120** [comment]
Hi @cekvenich 
There are different approaches to keep the SDK size smallest. Firstly you can use bundlers like webpack, browserify (or parcel) and import the SDK S3 client like `import * as S3 from 'aws-sdk/clients/s3';` to your project. The bundler will automatically prune the unused files. 
Another approach is to use SDK browser builder. You can build the SDK with only S3 client. I tried this approach and it's 85kB after gzipping.

**Comment by cekvenich** [comment]
I tried a browser builder https://sdk.amazonaws.com/builder/js/
and selected only S3.
384 kB.

**Comment by AllanFly120** [comment]
This is still significantly smaller than the Cloudfront distribution https://sdk.amazonaws.com/js/aws-sdk-2.224.1.min.js. That is 1.7MB before gzipping. We have noticed this defect and working on a big version bump.

**Comment by cekvenich** [comment]
Things that run in browser | mobile browser need to be managed.
