### ISSUE TITLE
Unable to set Lambda triggers via Cognito "updateUserPool" call

### ISSUE THREAD

**Issue by yuyuma** [aws/aws-sdk-js#2011]
cognitoidentityserviceprovider.updateUserPool call does not persist changes when attempting to set Lambda triggers.  A sample params is provided below.  While the example is for PreSignUp only, the issue should apply to any LambdaConfig options.  Note that the call is successful and returns no errors.

```
        var params = {
          UserPoolId: userPoolIdVariable,
          LambdaConfig: {
            PreSignUp: fullLambdaFunctionArnVariable
          }
        };
        return cognitoidentityserviceprovider.updateUserPool(params).promise();
```

The same userPoolIdVariable has worked for other updateUserPool calls (e.g. when setting EmailConfiguration) and the fullLambdaFunctionArnVariable has been confirmed by updating the lambda trigger manually via console and then issuing a cognitoidentityserviceprovider.describeUserPool call to verify that it is the same value.  In other words, the input params shouldn't be the cause of the issue here.

**Comment by AllanFly120** [comment]
I cannot reproduce this issue. your code snippet looks right. Which version are you using?

**Comment by yuyuma** [comment]
Thanks for your response.  I kept digging and turns out the issue I encountered was not due to the trigger association but due to the fact that lambda needed additional privileges to be invoked by Cognito.  https://forums.aws.amazon.com/thread.jspa?messageID=748566 has more details in case anyone else needs it.
