### ISSUE TITLE
sts.assumeRole().promise() returns undefined when succeds

### ISSUE THREAD

**Issue by mim-Armand** [aws/aws-sdk-js#2015]
Using callback works in both happy-path and failure:
```javascript
// This works
assumeRole() {
    let params = {
        RoleArn: 'arn:aws:iam::xxxxxx:role/test_assume_role',
        RoleSessionName: 'Bob',
    };
    return sts.assumeRole(params, function(err, data) {
        if (err) console.log(err, err.stack); // an error occurred
        else     console.log(data);           // successful response
    });
  }
```
using `.promise()` however returns `undefined` when the request succeeds, it behaves as expected when the request fails:
```javascript
// This returns undefined for happy-path
assumeRole() {
    let params = {
        RoleArn: 'arn:aws:iam::xxxxxx:role/test_assume_role',
        RoleSessionName: 'Bob',
    };
    
    return sts.assumeRole(params)
      .promise()
      .then((data) => {
        console.log('ASSUME ROLE RESULTS >>> ', data);
      })
        .catch( (err) => {
          console.log('ERROR ASSUMING ROLE: ', err);
        });
  }
```

Thanks

**Comment by mim-Armand** [comment]
Not using any library for that, I simply add ( the undocumented ) `.promise()` at the end of the method call, as it does promisify most of the other methods I've worked with, it does with this one too, the only difference is that it returns `undefined` when the promise is resolved.

So `sts.assumeRole(params).promise()` returns the correct response for you? If so, please let me know and I'll do more investigation to find out what was the cause of the issue. thanks

**Comment by AllanFly120** [comment]
Yes. I used the code snippet you shared as above and it works as expected. I was using a test user with all STS permissions. Can you show me what's the printout you get from the code snippet above?

**Comment by mim-Armand** [comment]
the printout was `undefined` when stringified, but I think found the problem, adding `.promise()` doesn't return a normal promise, in contrary to the promises standard api which can have more than one `.then()` and executes them one after the other, AWS Node SDK, executes the second `then()` as well but it doesn't pass the resolved value to `then`s after the first one.
I had one `then()` in my class and one in my test, I was logging the results in my test which was printing `undefined`. however, logging the results in the class itself works, and if I remove the `then()` from the class, the test will start working.
So I will close this issue as it's kind of solved, I appreciate your help @AllanFly120

**Comment by maxharris9** [comment]
I have run into this same issue, and the discussion above is about as clear as mud. Is there an actual code example of how to work around this issue?

I can't just use the v3 SDK because it won't be out for at least another six months...

**Comment by mim-Armand** [comment]
@maxharris9 The snippet in [the original post](https://github.com/aws/aws-sdk-js/issues/2015#issue-315582375) actually works, just make sure to consume the promise **only** in one place otherwise it may cause a racing condition.

There is a difference ( or maybe a bug ) in the implementation of the Promise in this SDK ( at least the version I was using back then ) and the standard implementation/specifications of the Promise APIs:
In the standard spec, when a promise is resolved/rejected, all the subscribers will be notified ( This is called Promise Branching ), but here only one of them will receive the results ( that's not the case however when the promise is rejected, pointing to a possible bug, again )

I will re-open this issue hoping someone will explain it better and/or clearer than me to help you out, or put it on the roadmap if it's a bug or something that can help more people, but otherwise please feel free to close it

**Comment by maxharris9** [comment]
@srchase `await sts.assumeRole(params).promise()` doesn't work, and it should. closing this without actually fixing the broken code is going to cause more frustration for more people...

**Comment by maxharris9** [comment]
Dear Amazon: `await sts.assumeRole(params).promise()` doesn't work, and it should

**Comment by AllanFly120** [comment]
@maxharris9 Can you make sure the 'complete' event is triggered in your request? like here:
```javascript
request.
  on('complete', function(resp) {
    console.log('request completes: ', resp.data);
  });
await request.promise();
```
