### ISSUE TITLE
Unhandled rejection, catching internal promise rejections when no promises are exposed

### ISSUE THREAD

**Issue by aaronpeterson** [aws/aws-sdk-js#2016]
^2.84.0

Specifically I am able to "catch" your "AWS.SimpleQueueService.QueueDeletedRecently" and do something productive with it but not without seeing the "unhandled rejection" in the console.

Is there a plan to make this a promise library?  Why aren't you handling your promise rejections internally?  What is the solution to not seeing the "unhandled rejection" in my console?  It's very noisy.

**Comment by AllanFly120** [comment]
Hi, @aaronpeterson 
Can you share your code how do you catch rejections? When you see the message, did your operation succeed? Can you log out the exact error you get?  Usually, you will see this error when `catch` statement is not appended to a promise. Is your code look like bellow?
```javascript
var sqs = new AWS.SQS();
sqs.deleteMessage(params).promise().then((data) => {
    //success
}).catch((err) => {
    console.log('error: ', err);
})
```

**Comment by aaronpeterson** [comment]
I didn't know promise() was required.  Thank you.
