### ISSUE TITLE
CORS Support for Amazon Transcribe

### ISSUE THREAD

**Issue by bytenaija** [aws/aws-sdk-js#2024]
I successfully uploaded a file to S3 using a custom build of aws javascript SDK that included Amazon transcrib API on April 24, 2018.

I am trying to programmatically start a transcripption job and keep geting this error:

OPTIONS https://transcribe.us-east-2.amazonaws.com/ 403 (Forbidden)
handleRequest @ aws-sdk-2.227.1.min.js:7
s @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
o @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
t @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:3
get @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:3
getCredentials @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
o @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:3
hash @ aws-sdk-2.227.1.min.js:3
sha256 @ aws-sdk-2.227.1.min.js:3
computeSha256 @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
o @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
t @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:3
get @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:3
getCredentials @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
runTo @ aws-sdk-2.227.1.min.js:1
send @ aws-sdk-2.227.1.min.js:1
makeRequest @ aws-sdk-2.227.1.min.js:1
none.e.api.operations.(anonymous function).authtype.e.(anonymous function) @ aws-sdk-2.227.1.min.js:1
awsTranscribe @ home.js:108
(anonymous) @ home.js:81
finishSinglePart @ aws-sdk-2.227.1.min.js:18
(anonymous) @ aws-sdk-2.227.1.min.js:1
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
o @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
n.emit @ aws-sdk-2.227.1.min.js:8
finishRequest @ aws-sdk-2.227.1.min.js:7
(anonymous) @ aws-sdk-2.227.1.min.js:7
XMLHttpRequest.send (async)
handleRequest @ aws-sdk-2.227.1.min.js:7
s @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
o @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
t @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:3
get @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:3
getCredentials @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:1
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
o @ aws-sdk-2.227.1.min.js:2
(anonymous) @ aws-sdk-2.227.1.min.js:2
t @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:3
get @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:3
getCredentials @ aws-sdk-2.227.1.min.js:3
(anonymous) @ aws-sdk-2.227.1.min.js:2
callListeners @ aws-sdk-2.227.1.min.js:2
emit @ aws-sdk-2.227.1.min.js:2
emitEvent @ aws-sdk-2.227.1.min.js:2
e @ aws-sdk-2.227.1.min.js:1
n.runTo @ aws-sdk-2.227.1.min.js:2
runTo @ aws-sdk-2.227.1.min.js:1
send @ aws-sdk-2.227.1.min.js:1
nextChunk @ aws-sdk-2.227.1.min.js:18
fillBuffer @ aws-sdk-2.227.1.min.js:18
send @ aws-sdk-2.227.1.min.js:18
upload @ aws-sdk-2.227.1.min.js:18
HomeViewModel.self.upload @ home.js:76
domListener @ ojknockout.js:2471
localhost/:1 Failed to load https://transcribe.us-east-2.amazonaws.com/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 403.

<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>

There is no mention of setting CORS on Amazon transcribe

**Comment by chrisradek** [comment]
@bytenaija 
The Amazon Transcribe service doesn't currently support CORS, so it isn't possible to use it in an environment that enforces it. A temporary workaround would be to write a Lambda function that calls transcribe, and either invoke it directly from the front-end or access it through API Gateway.

I have notified the service team about your request to support CORS, but feel free to also post to their forums [here](https://forums.aws.amazon.com/forum.jspa?forumID=278&start=0).
