### ISSUE TITLE
AWS S3 Signed URL expires after a default time quantum

### ISSUE THREAD

**Issue by azkarmoulana** [aws/aws-sdk-js#2029]
Is there any way to disable expiration of a signed URL with signedVersion 4, so that I can  use the URL more than 7 days?

**Comment by AllanFly120** [comment]
Hi @azkarmoulana 
After signatureV4 introduced in as default signing algorithm, 7 days is the longest expiration time we can get according to [here](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html). This is a limitation of the pre-signed URI. Close this issue as it's duplicated with #685
