### ISSUE TITLE
How to capture internet disconnection error during manage upload?

### ISSUE THREAD

**Issue by bkarv** [aws/aws-sdk-js#2030]
How do you capture internet disconnection error during a manage upload? 

Currently my code is (in angular) where I listen to the error object in .send. However upon disconnection the error is not fired.

```
        this.authService.setBucketUpload(params.Key, params.Body, params.ContentType);
          // Upload to S3
          this.bucket = this.authService.getBucket();           
          this.bucket.on('httpUploadProgress',  (progress) => {
            // Update progress uploaed bytes
            console.log('progress', progress.loaded);
          }).send((err, data) => {
            if (err) {
                console.log('AWS Error', err);     
                alert(err);
            } else {
              // Success 
              console.log('Success', data);   
            }
           }); 
```

S3 Config

```
setBucketUpload(key: any, body: any, contentType: string): void {
  AWS.config.update({
      region: AWSREGION,
      credentials: new AWS.CognitoIdentityCredentials(
          {
              IdentityPoolId: AWSIDENTITYPOOLID,
              IdentityId: this.getAwsIdentityId(),
              Logins: {
                  'cognito-identity.amazonaws.com': this.getAwsToken()
              }
          }
      )
  });

    this.bucket = new AWS.S3.ManagedUpload({partSize: 5 * 1024 * 1024, params: {Bucket: 'xxxx-s3-test/', Key: key, Body: body, ContentType: contentType}});
  }
```

**Comment by AllanFly120** [comment]
Hi @bkarv 
ManagedUpload is actually a serial of API calls: `createMultipartUpload()`, `uploadPart()`, `completeMultipartUpload()`. And they each will call the callback if the request is failed: [createMultipartUpload](https://github.com/aws/aws-sdk-js/blob/4ea818e7e2edbc6f60ac274e0f06b29b450b0d66/lib/s3/managed_upload.js#L499), [uploadPart](https://github.com/aws/aws-sdk-js/blob/4ea818e7e2edbc6f60ac274e0f06b29b450b0d66/lib/s3/managed_upload.js#L557), [completeMultipartUpload](https://github.com/aws/aws-sdk-js/blob/4ea818e7e2edbc6f60ac274e0f06b29b450b0d66/lib/s3/managed_upload.js#L630). So technically,  if any of these api call fails they callback should be triggered. Can you share what's the error you are seeing?
