### ISSUE TITLE
AWS S3 putObject Body "InvalidParameterType"

### ISSUE THREAD

**Issue by firohuber** [aws/aws-sdk-js#2031]
Hey, after applying npm install my code would not work, I keep getting an error that Body is "InvalidParameterType",
 I'm using nwjs v0.29.1 and aws-sdk 2.229.1 and before the I was using aws-sdk 2.224.1. 
I tried to remove node_modules folder and reinstall it with aws-sdk 2.224.1 but it doesn't work now too
```
let _S3 = new _AWS.S3({
  apiVersion: '2006-03-01'
});
let fileData = _fs.createReadStream(file.path);
let params = {
  Bucket: bucket,
  Body: fileData,
  Key: key,
  ServerSideEncryption: 'AES256'
};
let request = _S3.putObject(params);
this.setServerProcess(id, request, null, null);
request.on('httpUploadProgress', (progress) => {
  console.log(progress.loaded);
});
request.on('complete', (response) => {
  if (response.error) {
    return reject(response.error);
  }
  return resolve();
});
request.send();
});
```

When I use 
```
_fs.readFile(file.path, (err, fileData) => {
  if (err) {
    return reject(err);
  }
  let params = {
    Bucket: bucket,
    Body: fileData,
    Key: key,
    ServerSideEncryption: 'AES256'
  };
  let request = _S3.putObject(params);
  this.setServerProcess(id, request, null, null);
  request.on('httpUploadProgress', (progress) => {
    console.log(progress.loaded);
  });
  request.on('complete', (response) => {
    if (response.error) {
      return reject(response.error);
    }
    return resolve();
  });
  request.send();
});
```
Instead it does work but I do not wish to use readFile instead of createReadStream.

**Comment by AllanFly120** [comment]
I believe it's because the stream type from the `_fs.createReadStream(file.path)` is not valid [here](https://github.com/aws/aws-sdk-js/blob/4ea818e7e2edbc6f60ac274e0f06b29b450b0d66/lib/param_validator.js#L244). Only node buffer and stream can be put in Body. Can you try print the type of the `fileData`? The idea is: `require('buffer').Buffer.isBuffer(fileData) || fileData instanceof require('stream').Stream`

**Comment by firohuber** [comment]
`ReadStream {_readableState: ReadableState, readable: true, _events: {…}, _eventsCount: 1, _maxListeners: undefined, …}`
That's what I get when I print it

**Comment by firohuber** [comment]
I went to this section of the aws
```
if (AWS.util.isNode()) { // special check for buffer/stream in Node.js
      var Stream = AWS.util.stream.Stream;
      if (AWS.util.Buffer.isBuffer(value) || value instanceof Stream) return;
}

var types = ['Buffer', 'Stream', 'File', 'Blob', 'ArrayBuffer', 'DataView'];
  if (value) {
    for (var i = 0; i < types.length; i++) {
      if (AWS.util.isType(value, types[i])) return;
      if (AWS.util.typeName(value.constructor) === types[i]) return;
    }
  }
```
Because I'm working in nwjs it return false on `if (AWS.util.isNode())` and the typeof fileData is returning readstream

**Comment by AllanFly120** [comment]
You are right. We need to be smarter on detecting the running environment. You can forcibly set the SDK to believe that it's running on the Node by this: `AWS.util.isBrowser = () => false`. 
I'm also wondering if you are using bundler. The concern is that, if you are using a bundler, it is possible you are using the browser build of SDK(although it should default to be Node SDK). If it's this case we need to think of other ways.

**Comment by firohuber** [comment]
I am using a bundler and when we excluded it out of the bundle it does work well but we will prefer to bundle it all together is there a way to solve it?

**Comment by daryllstrauss** [comment]
I'm having the same problem with an electron app, where I have node enabled in the worker. The check is deciding that we're isBrowser instead of isNode. We're actually both!

I tried to force it as @AllanFly120 suggested, but that changes the error:

```
core.js:1449 ERROR TypeError: Cannot read property 'Stream' of undefined
    at ManagedUpload.send (managed_upload.js:179)
    at features.constructor.upload (s3.js:1067)
    at Village.performUpload (village.ts:82)
    at SafeSubscriber.eval [as _next] (worker.component.ts:117)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:243)
    at SafeSubscriber.next (Subscriber.js:190)
    at Subscriber._next (Subscriber.js:131)
    at Subscriber.next (Subscriber.js:95)
    at TakeSubscriber._next (take.js:83)
    at TakeSubscriber.Subscriber.next (Subscriber.js:95)
```

**Comment by AllanFly120** [comment]
Hey @daryllstrauss, this is an interesting use case. Can you let the workers post message back and then integrate with node version of SDK or make all AWS service calls in worker? I mean you need to choose depend on one environment instead of two.

**Comment by daryllstrauss** [comment]
I was doing that originally. I was including the code in the main thread, and then using remote to send it messages.

That sort of worked. It definitely identified the ReadStream correctly, but I wasn't getting all the callbacks I should from the SDK. I'd call it periodically and I get them in batches rather than having each one run to completion before the next call. It was weird enough I had no idea how to diagnose it.

They seem to discourage doing much in the main thread. Having that thread be fast is critical to a responsive UI. The recommended way to do multithreading is to launch a new window without showing it and run the code there. 

Forcing the AWS SDK to node mode seemed like a good solution. I get the rest of my web environment for other backend HTTP commands, Observables, etc that I'd have to replicate. I do a parallel multipart get using a node module and it works great. It's just the upload that's giving me trouble.

**Comment by AllanFly120** [comment]
Keeping main thread clean makes a lot sense. I agree this is hard. I'm also thinking of if you can bundle the worker code in individual package with individual node_modules and use webpack(if you use that) to target at 'web' only for the worker's code. I haven't tested it yet but that's the idea.

**Comment by daryllstrauss** [comment]
I went down that path as well, using webpack in fact. The problem is that these are really large files (multi GB). I don't know how to get a stream without using fs. As far as I can tell XMLHTTPRequest only hands me the complete file in memory. That's also why I'm doing all the multipart stuff.

**Comment by daryllstrauss** [comment]
My work around was to create a class that duck-type's the file object the uploader wanted for it's web interface. It really only needed slice() and size in the end.

I'd still like to see the native node interface work. The Slice problem is that once we fooled it to know it was in node, the node_loader.js was doing require(...) not window.require(...) which is what electron wants. 

The detector should be smarter (understand node/electron/etc) and/or allow you to specify the environment.
