### ISSUE TITLE
Browser upload: File validation or preview

### ISSUE THREAD

**Issue by elgalu** [aws/aws-sdk-js#2032]
We need to create a single page app that will allow uploading huge CSV files (e.g. 4 GB) to S3.

Some basic CSV validation should be in place, at least for first N lines of the file.

If there are errors in the file we would abort the upload and show the validation error to the user.

Is that possible with this library?

**Comment by AllanFly120** [comment]
We don't have an out-of-box solution for previewing the upload Body. I don't think there is a strong necessary integrating this feature to SDK itself. You can always validate the CSV file before supplying to SDK. Also validating file for each request would be a considerable performance loss.

**Comment by AllanFly120** [comment]
That is to say, instead of calling ManagedUpload `upload()`, you can call `createMultipartUpload`, `uploadPart` and `completeMultipartUpload` by yourself, which is also what `upload()` does under the hood. And for each `uploadPart` call, you can read a chunk from the file and do the validation.

**Comment by elgalu** [comment]
Awesome! thanks
