### ISSUE TITLE
Unable to upload a directory using s3.upload?

### ISSUE THREAD

**Issue by ArjunMani** [aws/aws-sdk-js#2033]

**Comment by AllanFly120** [comment]
Your machine will return an error if you are doing something to file but actually a directory. This is not an issue or sharp edge of SDK. When you upload the file, the Node will, in the end, make syscall to read the file, and the syscall will return error here.

**Comment by ArjunMani** [comment]
Thanks for the response.

Then what is the best way to upload multiple files inside a directory?

Thanks in advance.

**Comment by AllanFly120** [comment]
You can put your directory in a tar file first and upload. 'tar-fs' packae might be helpful.Here's an example. 
```javascript
const tar = require('tar-fs');
const s3 = new AWS.S3();
s3.upload({
    Bucket: bucket,
    Key: key,
    Body: tar.pack('path/to/your/directory'),
}, function (error, data) {
    console.log(error, data);
})
```

**Comment by ArjunMani** [comment]
Ohh Greatt!!!

Same way is there any to download a directory from browser??

Thanks in advance.
