### ISSUE TITLE
upload response object has a duplicate property

### ISSUE THREAD

**Issue by dougwit** [aws/aws-sdk-js#2034]
**Environment:**
 - Node.js v9.6.1
 - npm v5.8.0
 - aws-sdk package v2.230.1

Using this code (sensitive data changed):
```javascript
let options = {
  Bucket: 'my-bucket',
  Key: 'test-file',
  Body: fs.createReadStream('/path/to/file.ext')
}

S3.upload(options, console.log)
```

I get this response:
```javascript
null { ETag: '"0a4ca52d1b05cf4f78b10c3992cf1b97"',
  ServerSideEncryption: 'AES256',
  VersionId: '0f3d9e3f7bd7117d9f308aec18a4f2df',
  Location: 'https://my-bucket.s3.amazonaws.com/test-file',
  key: 'test-file',
  Key: 'test-file',
  Bucket: 'my-bucket' }
```

As you can see, the response object contains a `Key` property and a `key` property, both of which have the same value.

**Comment by dougwit** [comment]
@AllanFly120 yes. All I'm doing with the response object is printing it.

**Comment by srchase** [comment]
Hello @dougwit,

Were you able to uncover any additional details to help reproduce this issue?

**Comment by dougwit** [comment]
Hey guys. My apologies for the late response. 

I just traced the call and found the offending line of code: https://github.com/aws/aws-sdk-js/blob/ef10482481ea827f88c4f3cd8311024fb75f32e6/lib/s3/managed_upload.js#L664

I'm not sure why that's there, or why others aren't able to reproduce the issue.

**Comment by srchase** [comment]
@dougwit,

Thanks for following up.

This is the expected behavior.  The code you referenced was introduced to drive consistency between the responses returned by simple and multi-part upload operations.

Additional details are on the original [issue](https://github.com/aws/aws-sdk-js/issues/918).
