### ISSUE TITLE
s3.upload method disregards ContentType and ContentEncoding parameters

### ISSUE THREAD

**Issue by pgrzesik** [aws/aws-sdk-js#2037]
Hello,

today I stumbled on a weird issue. I'm using axios and aws-sdk to fetch *csv.gz files, unzip them and upload to S3 bucket as csv files, using following snippet:

```
const response = await axios.get(link, { responseType: 'stream' });
const uploadParams = {
      Bucket: S3_BUCKET_NAME,
      Key: bucketKey,
      Body: response.data,
      ContentType: 'text/csv',
      ContentEncoding: 'utf-8'
}
s3.upload(uploadParams, ....)
```

However, whenever I download the file and check it's type (`file -i filename.csv`), I get back `application/x-gzip; charset=binary`.

Is that a problem with s3.upload method or do I not understand something here ?

Regards,
Piotr

**Comment by AllanFly120** [comment]
Hi @pgrzesik 
Are you trying to upload in browser or Node? I wonder whether it's possible that the browser overwrite the content-type and content-encoding headers.

**Comment by pgrzesik** [comment]
Hello @AllanFly120,

I'm uploading from Node, what's more interesting, S3 Object in bucket has the correct Content-Type and Content-Encoding Metadata, however after downloading, it's the same as I showed in my first message. I tried downloading it via cURL, Node, from Browser - the same for all cases.

**Comment by AllanFly120** [comment]
Hey @pgrzesik, can you get the object directly from the bucket using Node and check the response header? I believe it's there. You can try this to print the response header:
```javascript
s3.getObject(params, function(){
    console.log(this.httpResponse.headers);
})
```
I think MIME content-type is for browsers to determine what to do with the file. For example, you can host a static website in an S3 bucket. When you retrieve an object with content-type gzip, the browser will help you inflate it automatically.

**Comment by pgrzesik** [comment]
Hey @AllanFly120, sorry for delayed response. I tried getting it this way and while provided snipped doesn't yield any results, I managed to get them and headers look like in S3 buckets.

**Comment by AllanFly120** [comment]
So, that's the expected behavior. The `getObject` or `download` doesn't change the file type on your behalf automatically. You need to handle it by yourself accordingly. All the SDK does is encapsulating the download stream and provide it to users. I think the file type `application/x-gzip` is set by your OS instead of inferring from HTTP response.

**Comment by pgrzesik** [comment]
Thanks for your engagement @AllanFly120, it looks like it's not a matter of AWS SDK so I'm closing this issue.

Cheers
