### ISSUE TITLE
When trying to upload a file to S3 in the browser, get a CORS error. 

### ISSUE THREAD

**Issue by Tombert** [aws/aws-sdk-js#204]
http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-examples.html

Following the file upload example, modified it like this. 

```
$.get('/admin/credentials').success(function(data) {
  var bucket, params, req;
  AWS.config.region = 'us-west-2';
  if (data.success) {
    AWS.config.update(data.credentials);
    AWS.config.region = 'us-west-1';
    bucket = new AWS.S3({
      params: {
        Bucket: "example-incoming"
      }
    });
    params = {
      Key: file.name,
      ContentType: file.type,
      Body: file
    };
    req = bucket.putObject(params);
    return req.send(function(err, data) {
      return $scope.loading = (err ? "ERROR!" : "UPLOADED.");
    });
  }
});
```

When doing the request, I get the following error

```
OPTIONS https://example.s3-us-west-1.amazonaws.com/sintel_trailer-480p.mp4 No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://example.com' is therefore not allowed access.
```

(with example.com obviously being a made-up site, and sintel being a free movie I use for testing)
I'm not sure what I'm doing wrong...Could someone elucidate on what I'm doing wrong?

**Comment by mrcoles** [comment]
This is probably completely irrelevant now, but did you try adding `<AllowedMethod>OPTIONS</AllowedMethod>`?

**Comment by Tombert** [comment]
Sadly the company I was working for on this site went bankrupt about a year ago, so I don't have an opportunity to try this.

**Comment by marcosnils** [comment]
> This is probably completely irrelevant now, but did you try adding <AllowedMethod>OPTIONS</AllowedMethod>?

S3 doesn't allow you to confgure OPTIONS as a value for the `AllowedMethod` tag. Any hints on this?
