### ISSUE TITLE
TypeError: AWS.IAM is not a constructor

### ISSUE THREAD

**Issue by fedeverdi** [aws/aws-sdk-js#2041]
I'm using aws-sdk-js in Angular 5. No issues with EC2, RDS or SES class, but when I tried to create an instance of IAM class I received this error:

**TypeError: AWS.IAM is not a constructor**

I have already updated to the version 2.233.1. 
Any Ideas ?

Thx

**Comment by AllanFly120** [comment]
Hey @fedeverdi, currently IAM service doesn't support CORS, which means it isn't available in browsers by default. However, if your environment doesn't enforce CORS, you can get around it by [generating a customize SDK](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html).
