### ISSUE TITLE
set cors header, (Access-Control-Allow-Origin) for SendEmail request

### ISSUE THREAD

**Issue by ArunPrasathSubramani** [aws/aws-sdk-js#2042]
Hi I am trying to send email from my angular 5 application.

I am getting the error as 
> **Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

```
ses.sendEmail(params, function (err, data) {
if (err) console.log(err, err.stack); // an error occurred
            else console.log(data);           // successful response
        });
```
I could not find a way to set the header for the request.
Can someone help me out here.

**Comment by ArunPrasathSubramani** [comment]
Resolved the issue with a Lambda function in AWS, calling the same through AWS- API Gateway.

**Comment by AllanFly120** [comment]
I'm glad that you resolved this issue. The SES service does not support the environment enforces CORS like browser. Using Lambda instead is a great workaround. Closing this issue due to this has been resolved. Feel free to comment here if you have further problems.
