### ISSUE TITLE
Vulnerable lodash dependency via xmlbuilder

### ISSUE THREAD

**Issue by thom-nic** [aws/aws-sdk-js#2044]
NSP notified me that lodash <4.17.5 has several prototype pollution vulnerabilities. https://nodesecurity.io/advisories/577

xmlbuilder started using `lodash: "^4.0.0" which will allow upgrading the lodash dependency to a non-vulnerable version.  xmlbuilder v8.2.0 removed the dependency on lodash altogether.

**Comment by chrisradek** [comment]
Closing since we have replaced XMLBuilder for serializing XML.
