### ISSUE TITLE
TypeError: translator.translateInput is not a function

### ISSUE THREAD

**Issue by warmjaijai** [aws/aws-sdk-js#2046]
Im using DynamoDB query on Adonis (Node.js)

Controller.php

```
const AWS = require('aws-sdk')
...
...
...
async testing({params,response}){
   var table_name='testing8'
   var year = "2015"
   var title = "The Big New Movie"
   var dynamoDB_params = {
      TableName: table_name,
      Item:{
         "year": {
            S: year,
         },
         "title": {
            S: title,
         },
         "info": {
            M: {
               "plot": {
                  S: "Nothing happens at all."
               },
               "rating": {
                  N: "0"
               }
            }
         }
      }
   }
   var data = AWS.DynamoDB.DocumentClient().put(dynamoDB_params)
   response.json(data)
}
```
error message:

> TypeError: translator.translateInput is not a function

Hardly find any example on google of having this error message. But seemingly `translator.translateInput` is out of aws-sdk? ( Issue #1236 ) I am new to DynamoDB please enlighten me.

**Comment by chrisradek** [comment]
@warmjaijai 
Which version of the SDK are you using? Can you also share the stack trace from the error?

One thing, it looks like you're using the `DocumentClient` the way you'd expect to use the low-level `DynamoDB` client. The DocumentClient will convert your standard JSON into the DynamoDB AttributeValues that the low-level client expects for you, so instead of
```javascript
var dynamoDB_params = {
      TableName: table_name,
      Item:{
         "year": {
            S: year,
         },
         "title": {
            S: title,
         },
         "info": {
            M: {
               "plot": {
                  S: "Nothing happens at all."
               },
               "rating": {
                  N: "0"
               }
            }
         }
      }
   }
```

you could just pass:
```javascript
var dynamoDB_params = {
      TableName: table_name,
      Item: {
        "year": year,
        "title": title,
        "info": {
          "plot": "Nothing happens at all.",
          "rating": 0
      }
}
```

The `put` operation is also async. The return value of `put` will actually be an [AWS.Request](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html) object. It's possible that `response.json` can't handle the `Request` object. There are a few ways to get the result from the `put` operation, using callbacks or promises:

```javascript
// callback example
documentClient.put(/*parameters*/, function(err, data) {
  if (err) {
    // handle error
  } else {
    response.json(data);
  }
});

// promise example
documentClient.put(/*parameters*/).promise().then(function(data) {
  response.json(data);
}).catch(function(err) {
  // handle errros
});
```

**Comment by warmjaijai** [comment]
Thank you very much @chrisradek , for the first part I actually used the code you mentioned at the first place. But it came up with a lot of errors (Sorry can't copied what exactly popped up coz its on my other computer) such as 

> There were 25 validation errors....

and

> InvalidParameterType: and Expected params.Item['year'] to be a structure

And that's why I changed it to what I have done there.

**Comment by AllanFly120** [comment]
Hey @warmjaijai  Can you show your input and the full validation errors you got here? It's helpful to deal with this issue.

**Comment by warmjaijai** [comment]
@AllanFly120 

> { MultipleValidationErrors: There were 25 validation errors:
> 
> * InvalidParameterType: Expected params.Item['year'] to be a structure
> 
> * UnexpectedParameter: Unexpected key '0' found in params.Item['year']
> 
> * UnexpectedParameter: Unexpected key '1' found in params.Item['year']
> 
> * UnexpectedParameter: Unexpected key '2' found in params.Item['year']
> 
> * UnexpectedParameter: Unexpected key '3' found in params.Item['year']
> 
> * InvalidParameterType: Expected params.Item['title'] to be a structure
> 
> * UnexpectedParameter: Unexpected key '0' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '1' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '2' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '3' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '4' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '5' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '6' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '7' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '8' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '9' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '10' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '11' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '12' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '13' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '14' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '15' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key '16' found in params.Item['title']
> 
> * UnexpectedParameter: Unexpected key 'plot' found in params.Item['info']
> 
> * UnexpectedParameter: Unexpected key 'rating' found in params.Item['info']

**Comment by AllanFly120** [comment]
Hey @warmjaijai 
Did you use the `dynamoDB` client? (not the document client). For example:

```javascript
var dynamoDB_params = {
      TableName: table_name,
      Item:{
         "year": {
            S: year,
         },
         "title": {
            S: title,
         },
         "info": {
            M: {
               "plot": {
                  S: "Nothing happens at all."
               },
               "rating": {
                  N: "0"
               }
            }
         }
      }
   }
var client = new AWS.DynamoDB({region: region});
client.putItem(dynamoDB_params, funtion(err, data) {
    if (err) console.log(err);
    if (data) console.log(data);
})
```

**Comment by warmjaijai** [comment]
it says
`Unexpected key 'M' found in params.Item['info']`

**Comment by srchase** [comment]
@warmjaijai,

Do you have any additional questions?
