### ISSUE TITLE
[AWS COGNITO] TypeError: cognitoidentityserviceprovider.adminCreateUser is not a function

### ISSUE THREAD

**Issue by meetzaveri** [aws/aws-sdk-js#2049]
Hi Devs,

I have been getting this issue since long. The AWS Cognito JS SDK has this API called `AdminCreateUser` link - https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html

Error - TypeError: cognitoidentityserviceprovider.adminCreateUser is not a function

Code - 
```js

const AWS = require('aws-sdk');
AWS.config.update({
  accessKeyId: 'something',
  secretAccessKey:credentials.secret_key,
  region:credentials.region
})

export function createUser(email,password,role){
  var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider({apiVersion: '2016-04-18'});
  return new Promise((resolve,reject) => {
    var params = {
      UserPoolId: poolData.UserPoolId, /* required */
      Username: email, /* required */
      // DesiredDeliveryMediums: [ SMS| EMAIL,
      //   /* more items */
      // ],
      TemporaryPassword: password,
      UserAttributes: [
        {
          Name: 'Email', /* required */
          Value: 'STRING_VALUE'
        },
        {
          Name: 'Role', /* required */
          Value: role
        },
        /* more items */
      ],
      ValidationData: [
        {
          Name: 'Email', /* required */
          Value: email
        },
        /* more items */
      ]
    };
    cognitoidentityserviceprovider.adminCreateUser(params, function(err, data) {
      if (err){
        console.log(err, err.stack); // an error occurred
        reject(err);
      } else{
        console.log(data); // successful response
        resolve(data);
      }    
    });
  })
  
}
```

What's the solution to this? Also is there any alternative from AWS SDK ??

Thank You

**Comment by chrisradek** [comment]
@meetzaveri 
What version of the SDK are you using? Also, what environment are you running this in?
I just ran `adminCreateUser` using the latest version of the SDK in node.js and am not encountering an error.

**Comment by meetzaveri** [comment]
@chrisradek  AWS SDK version - 2.6.4 . I have imported it as npm module rather than having manual js file to import.

Thanks

**Comment by chrisradek** [comment]
@meetzaveri 
It looks like the `adminCreateUser` operation was added in version 2.6.7 of the SDK.
https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#267

**Comment by meetzaveri** [comment]
Okay I'll try whether it works or not. Will inform you!

thanks!
