### ISSUE TITLE
Unable to resolve module `util`

### ISSUE THREAD

**Issue by anandwahed** [aws/aws-sdk-js#2052]
We are using the `aws-amplify` and `aws-sdk-js` in our React Native project. The local build's seems to work without any issues but when the same is pushed in the Microsoft AppCenter the following error is thrown and the build fails for both Android and iOS. Any idea what could be the issue here ?

```bash
Unable to resolve module `util` from `/Users/vsts/agent/2.133.3/work/1/s/node_modules/sha.js/sha1.js`: Module `util` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 36s
337 actionable tasks: 337 executed
Error: /Users/vsts/agent/2.133.3/work/1/s/android/gradlew failed with return code: 1
    at ChildProcess.<anonymous> (/Users/vsts/agent/2.133.3/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/1.128.0/node_modules/vsts-task-lib/toolrunner.js:569:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
##[error]Error: /Users/vsts/agent/2.133.3/work/1/s/android/gradlew failed with return code: 1
```

**Comment by anandwahed** [comment]
@zohaibahmed-22, FYI

**Comment by nakulp007** [comment]
Having same error. I have working project. However, if I delete the _node_modules_ folder and run `npm install` again. After that launching the application, I receive the mentioned error. 

Launching using backup version of _node_module_ folder still works. But transporting to different environment this way is not ideal.

**Comment by chrisradek** [comment]
@anandwahed and @nakulp007 
Sorry for the delayed response. Can you share which versions of aws-amplify and aws-sdk-js you're using? 

@nakulp007 Does your backup copy of node_modules have `amazon-cognito-identity-js`? And if so, which version?

**Comment by anandwahed** [comment]
@chrisradek we were able to fix it by manually upgrading certain dependencies. The version of the aws-amplify and aws-sdk-js are mentioned below,

```json
"amazon-cognito-identity-js": "2.0.3",
"aws-amplify": "0.3.3",
"aws-amplify-react-native": "0.2.9",
```

**Comment by zohaibahmed-22** [comment]
we use `npm install aws-amplify` , `npm install aws-amplify-react-native` which automatically installs `amazon-cognito-identity-js` latest version as dependencies. which throws this error, we can removed this error by explicitly installing the  `npm install amazon-cognito-identity-js@2.0.4` and it worked

**Comment by nakulp007** [comment]
@chrisradek my node_modules had `amazon-cognito-identity-js` version 2.0.1, however it wasn't explicitly mentioned in our package.json in our app backup copy. 

We resolved the problem by adding `amazon-cognito-identity-js": "2.0.3"` to package.json.
