### ISSUE TITLE
The specified bucket is not valid setting region

### ISSUE THREAD

**Issue by eldyvoon** [aws/aws-sdk-js#2055]
I got the error of 

running below code

```
module.exports = (id, content) => {
  AWS.config.update({
    accessKeyId: process.env.S3_ACCESSKEY_ID,
    secretAccessKey: process.env.S3_SECRET_KEY,
    region: 's3-ap-southeast-1'
  })

  const S3 = new AWS.S3()

  const fileBuffer = new Buffer(content)

  const params = {
    Bucket: 'my-bucket-name',
    Key: id,
    Body: fileBuffer,
    ACL: 'public-read',
    ContentType: 'text/html'
  }

  S3.upload(params, (err, s3res) => {
    if (err) {
      console.log(err)
    } else {
      console.log(s3res)
    }
  })
}
```

But I got it working adding empty region object to the constructor.

```
const S3 = new AWS.S3({
    region: ''
  })
```

Please fix this, it's so strange. 

* This won't work too

```
AWS.config.update({
    accessKeyId: process.env.S3_ACCESSKEY_ID,
    secretAccessKey: process.env.S3_SECRET_KEY
  })

  const S3 = new AWS.S3({
    region: 's3-ap-southeast-1'
  })
```

**Comment by chrisradek** [comment]
@eldyvoon 
The region you are specifying isn't valid. I think you mean to use `ap-southeast-1`, not `s3-ap-southeast-1`.  I suspect when you don't have a region specified that the SDK is determining the correct region by defaulting to the global endpoint, but when you specify the `s3-ap-southeast-1` region the endpoint that is constructed is invalid so it can't redirect.

There's a list of all the S3 regions and endpoints [here](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region).

**Comment by eldyvoon** [comment]
I have this case where I use `ap-southeast-1` In generating signature it will fail, I used `s3-ap-southeast-1` then it worked.

https://gist.github.com/eldyvoon/ca80812e2f0074c605ea0e7ef7b83b13
