### ISSUE TITLE
Error sending Email using Pinpoint

### ISSUE THREAD

**Issue by Rads999** [aws/aws-sdk-js#2058]
I get an error saying "Unexpected key 'Email Message' found in params.MessageRequest.MessageConfiguration" when trying to send direct message using email channel via Pinpoint. Below is the code snippet used

var pinpoint = new AWS.Pinpoint({ "region": "us-east-1" });

```
var params = {
        ApplicationId:<app id>,
        MessageRequest: {
            Addresses : {
            "xxx@gmail.com" : {
                ChannelType:"EMAIL",
                BodyOverride : "hello"
            },
        },
            Endpoints: {
                "xxx@gmail.com": {
                    BodyOverride : "hello"
                }       
            },
            MessageConfiguration : {
                DefaultMessage: {
                    Body: '<p>Hello,</p><p>Welcome to PHA.</p><p>Regards</p><p>PHA</p>'
                },
                EmailMessage : {
                    Body:"<p>Hello,</p><p>Welcome to PHA.</p><p>Regards</p><p>PHA</p>"
                }
            }   
        }
};
pinpoint.sendMessages(params, function (err, data) {
        if (err) {alert("error "+JSON.stringify(err));} // an error occurred
        else alert("success "+JSON.stringify(data));           // successful response
 });
```
If EmailMessage is not the correct key then what is the key to be used to send email message?

**Comment by chrisradek** [comment]
@Rads999 
`EmailMessage` isn't one of the listed `MessageConfiguration` options:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#sendMessages-property

It looks like `DefaultMessage` is the right one to use based on it's description for `Body`:

> The message body of the notification, the email body or the text message.

If removing `EmailMessage` doesn't work, you may need to reach out to the service team on their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=225). They should be able to provide guidance on how to use the API for your use case.
