### ISSUE TITLE
Error: ETag does not match MD5 checksum

### ISSUE THREAD

**Issue by Prashant-Yadav** [aws/aws-sdk-js#2065]
Getting above error while downloading file from Leofs S3 bucket using client [node-s3-client](https://github.com/andrewrk/node-s3-client).

- aws-sdk version: 2.246.0

It download some chunks of data correctly and then truncates the file.

I am seeing this problem frequently.

**Comment by chrisradek** [comment]
@Prashant-Yadav 
The Etag returned my S3 is not guaranteed to be the MD5 checksum of the entire object. Notably, for multipart uploads[1], the Etag might be different when downloading.

[1]: https://forums.aws.amazon.com/thread.jspa?messageID=293789

You could calculate an MD5 or sha256 checksum for the file and save it as part of the object metadata, then calculate/compare that value when you download it.

The SDK also doesn't compare checksums on download (currently), so this seems like a feature that may be built into the library you're using. Please open an issue there. If you still believe there is a bug in this package, please provide the error you're seeing and if possible a minimal code sample to reproduce.
