### ISSUE TITLE
Search Cognito User Pools by custom attributes

### ISSUE THREAD

**Issue by lampidudelj** [aws/aws-sdk-js#2068]
Currently CognitoIdentityServiceProvider.ListUsers API call allows filtering by standard attributes only. Is there a possibility filtering by custom attributes will be added in the near future?

**Comment by AllanFly120** [comment]
Hey @lampidudelj, you can go to the [Cognito forum](https://forums.aws.amazon.com/forum.jspa?forumID=173) for news of new features or any feature request. The forum is run by the service team so that's where you can get a better answer.
