### ISSUE TITLE
Exception in S3: AWS authentication requires a valid Date or x-amz-date header on upgrade of IOS to 11.3 / 11.4 via a Cordova application 

### ISSUE THREAD

**Issue by xtianus79** [aws/aws-sdk-js#2070]
Exception in S3: AWS authentication requires a valid Date or x-amz-date header

I don't know why but that is the error that is generated when running my application for cordova for 11.3 and or 11.4

**Comment by AllanFly120** [comment]
Hey @xtianus79 
Do you see the similar exception in earlier version of Cordova? have you tried to log the headers?

**Comment by xtianus79** [comment]
@AllanFly120 yes it wa a problem with the headers.  The issue is and is probably causing some poor soul's frustration regarding a code base out there that is creating a signature in the manner we are for an S3 bucket... Along with the fact that IOS has now updated their internal browser to not accept Date as an awsheader or aparently a signature authorization we had been using.
