### ISSUE TITLE
Cannot use credentials that rely on Ec2InstanceMetadata

### ISSUE THREAD

**Issue by g-cassie** [aws/aws-sdk-js#2071]
Given this `~/.aws/credentials` file on an ec2 instance with an instance role:
```
[iam]
aws_access_key_id = <secret>
aws_secret_access_key = <secret>

[assume-via-user]
role_arn = arn:aws:iam:<id>:role/my-role
source_profile = iam

[assume-via-ec2role]
role_arn = arn:aws:iam:<id>:role/my-role
credentials_source = Ec2InstanceMetadata
```

Using the cli both profiles work:
```
aws s3 ls my-bucket --profile=assume-via-user
aws s3 ls my-bucket --profile=assume-via-ec2role
```

Using the sdk only the first one works:
```
AWS.config.credentials = new AWS.SharedIniFileCredentials({profile: 'assume-via-user'});
var client = new AWS.S3();
client.listObjects({Bucket: 'my-bucket'}, function(err, data){
   throw new Error(err);
});
// throws null

AWS.config.credentials = new AWS.SharedIniFileCredentials({profile: 'assume-via-ec2role'});
var client = new AWS.S3();
client.listObjects({Bucket: 'my-bucket'}, function(err, data){
   throw new Error(err);
});
// CredentialsError: Missing credentials in config
```

**Comment by AllanFly120** [comment]
Hi @g-cassie 
You don't need to specify using the EC2 metadata credentials in the shared credentials file. In fact, the SDK won't resolve the `credentials_source` key. You can explicitly use the EC2 credentials like this: 
```javascript
AWS.config.credentials = new AWS.EC2MetadataCredentials()
```
Sorry for the confusion here, this is a discrepancy between SDKs behaviors.

**Comment by g-cassie** [comment]
Hi @AllanFly120 

Is it possible to use an assumed role using this method? I don't see any documentation on that here:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2MetadataCredentials.html

**Comment by g-cassie** [comment]
Hi @AllanFly120,

Thanks, this kind of addresses the issue. Basically I now need to do this:

```
 AWS.config.credentials = new AWS.TemporaryCredentials({
   RoleArn: 'arn:aws:iam::<my-account>:role/my-role'
  }, new AWS.EC2MetadataCredentials());
```
This means I have to patch the third party library I'm working with because it assumes you can do all the config in `~/.aws/credentials`.  Not real ideal but will work for now.

I think the SDK should have parity with the cli so that if you can perform an action in the cli with a given a profile, it will also work in the SDK.  At a minimum the SDK should throw an error notifying the user that the `credentials_source` property is not supported as that took a considerable amount of time to get to the bottom of.

**Comment by Firefishy** [comment]
@trivikr It would be great if this issue could be fixed. There is an existing PR above which could be used. https://github.com/aws/aws-sdk-js/pull/3006

**Comment by Firefishy** [comment]
Duplicate of https://github.com/aws/aws-sdk-js/issues/1916
