### ISSUE TITLE
ResponseMetadata missing on SNS.PublishResponse

### ISSUE THREAD

**Issue by ktwbc** [aws/aws-sdk-js#2072]
sns.d.ts is not showing ResponseMetadata as existing on type PublishResponse, but per the docs it is an included value.

**Comment by AllanFly120** [comment]
Hey @ktwbc 
The `*.d.ts` for services are generated from service models([here](https://github.com/aws/aws-sdk-js/blob/eff411003edf9037e57fd298d68351e86dd1febe/apis/sns-2010-03-31.normal.json#L1261)) and they are written by service teams. If the field is not included in response shape, it sometimes means that the field may be omitted in some situation. I can reach out to SNS team to confirm whether the field is always exist.
