### ISSUE TITLE
I am signing a JS ajax request with a proper HmacSHA256 signature but it still says the signature doesn't match

### ISSUE THREAD

**Issue by xtianus79** [aws/aws-sdk-js#2075]
I know this is a question but perhaps this is a feature request too.  

I have done everything to properly output a proper signature.  

I start it with AWS aws_key:awssignature  <<<< and no bueno.  

A question I have is where can I see the proper key it is looking for (this would be the most helpful)?  

Other questions I have are in the signature... things like dateStamp is in this format YYYYMMDD >>> is that all that is needed?  

Lastly, I have cors setup to take <allowedheaders> Authorization and x-amz-date >>>> technically it is also publically open read operation and only allows GET my question is 2 fold.  

A. if it is public should I be trying to authorize it with a signature anyways... i.e. i can get everything working by simply removing the authorization and only passing over a date in the headers... but is that why the signature is failing.  

B. I am doing a Get operation... does that need to be in the signature somewhere.  Should it be something to the effect of GET\n\n\n ?  

Where in the signature generation would that fit?  

Here is the code reference I am using... 

https://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html#signature-v4-examples-javascript

`var crypto = require("crypto-js");

function getSignatureKey(Crypto, key, dateStamp, regionName, serviceName) {
    var kDate = Crypto.HmacSHA256(dateStamp, "AWS4" + key);
    var kRegion = Crypto.HmacSHA256(regionName, kDate);
    var kService = Crypto.HmacSHA256(serviceName, kRegion);
    var kSigning = Crypto.HmacSHA256("aws4_request", kService);
    return kSigning;
}
`

**Comment by xtianus79** [comment]
any help with this?

**Comment by AllanFly120** [comment]
Hey @xtianus79 

> where can I see the proper key it is looking for (this would be the most helpful)?

When trying to generate correct signature, it's always helpful to compare it with what [our SDK](https://github.com/aws/aws-sdk-js/blob/master/lib/signers/v4.js) is doing. It implements the same thing as in the doc, feel free to reach out if you have any questions reading it. The documentation is good but implementing a signer solely from it may lead to some issues hard to debug.

> format YYYYMMDD >>> is that all that is needed?

For datetime used in signing, this is the only format you need.

>  i can get everything working by simply removing the authorization and only passing over a date in the headers... but is that why the signature is failing.

I don't think so. Although your request gets through without signing when the resource is public. But when you provide a signature, the service(s3 e.g.) will validate your signature even if the resource is public. If you are working with s3, it's generally not advisable to set your resource as public.

**Comment by srchase** [comment]
@xtianus79 

Did you have any followup questions?  Did @AllanFly120's answers provide any help in getting this resolved?
