### ISSUE TITLE
S3 constructor doesn't like `AWS.Credentials` objects

### ISSUE THREAD

**Issue by decompil3d** [aws/aws-sdk-js#2078]
I'm working with temporary credentials coming from `STS.assumeRole`. They come back as an object with capital field names like `AccessKeyId` and `SecretAccessKey`. When I try to directly pass in this credentials object to the `S3` constructor, however, it fails with an error about missing Credentials.

It appears that the `S3` constructor is expecting credentials with camelCase key names, rather than the TitleCase keys that come back from `assumeRole`. I'm working around the issue for now by manually re-casing the keys before ferrying the credentials between the APIs. But this seems like a bug.

**Contrived example:**

```js
const sts = new AWS.STS({
  apiVersion: '2011-06-15',
  credentials: myBaseUserCredentials
});
const assumeRoleResult = await sts.assumeRole({
  RoleArn: myRoleArn,
  RoleSessionName: myRoleSessionName
}).promise();
const tempCreds = assumeRoleResult.Credentials;

const s3 = new AWS.S3({
  apiVersion: '2006-03-01',
  credentials: tempCreds,
  region: 'us-west-2'
});

// This operation will now fail because of a missing credentials error
await s3.getObject({
  Bucket: myBucket,
  Key: someKey
}).promise();

// But if I munge the credentials casing, it works
const mungedCreds = Object.entries(tempCreds).reduce((acc, [key, value]) => {
  const lowerCaseKey = key[0].toLowerCase() + key.substr(1);
  acc[lowerCaseKey] = value;
  return acc;
}, {});
const s3Fixed = new AWS.S3({
  apiVersion: '2006-03-01',
  credentials: mungedCreds,
  region: 'us-west-2'
});
await s3.getObject({
  Bucket: myBucket,
  Key: someKey
}).promise();
```

I'm using version 2.247.1 of the SDK, running on Node 8.11.1.

By all means, please let me know if I'm just missing something obvious. Thank you!

**Comment by chrisradek** [comment]
@decompil3d 
I think you want to use the [AWS.TemporaryCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/TemporaryCredentials.html) class to get your assume role credentials.

This will automatically call STS.assumeRole for you.

**Comment by decompil3d** [comment]
@chrisradek Thank you, that did the trick. I do wish that this had been made more clear in the `assumeRole` SDK docs though.
