### ISSUE TITLE
secretsManager.deleteSecret misleading Error Message

### ISSUE THREAD

**Issue by JuHwon** [aws/aws-sdk-js#2082]
when im executing the following function

```
function deleteSecret(event) {
  const { SecretName } = event.ResourceProperties
  var params = {
    RecoveryWindowInDays: 1,
    SecretId: SecretName,
  }
  return promisify(cb => secretsManager.deleteSecret(params, cb))
    .catch(error => {
      console.log(error, error.stack)
      throw error
    })
}
```

i do get the following error message: `Failed to delete resource. The RecoveryWindowInDays value must be less than or equal to 30.`

while the documentation says:
![image](https://user-images.githubusercontent.com/9406772/41175382-2f82b6b2-6b5d-11e8-96f6-4a8fe3083657.png)

i guess the documentation points out my failure, though the error message does not.
this could be a bit confusing if you only read the error message.

**Comment by AllanFly120** [comment]
Thank you. I will update with the service team to make the error message more helpful!

**Comment by AllanFly120** [comment]
The service team has acknowledged this issue and working on a fix. I will close this issue for now. Feel free to comment here if you have further question.
