### ISSUE TITLE
Documentation of httpOptions.timeout incorrect for browser implementation

### ISSUE THREAD

**Issue by kheyse-oqton** [aws/aws-sdk-js#2091]
The [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property) of the config httpOptions.timeout says:

> timeout [Integer] — Sets the socket to timeout after timeout milliseconds of inactivity on the socket. Defaults to two minutes (120000).

However, the browser implementation implements it as 
https://github.com/aws/aws-sdk-js/blob/8f8d1cc6429cdb1684858ba834aca87559bd37cf/lib/http/xhr.js#L70-L72

And the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout) of xhr.timeout says

> The XMLHttpRequest.timeout property is an unsigned long representing the number of milliseconds a request can take before automatically being terminated

As a result many requests get terminated before they are due. (e.g. any download that is executed using getObject and that takes longer than 2 minutes (default timeout), is timed out)

**Comment by AllanFly120** [comment]
Thank you for calling this out. Actually, the `timeout` setting in both Node and browsers actually sets the timeout before the connection will be closed instead of the stream is in inactivity. We will update the documentation. 
you can set the timeout to 0 `AWS.config.httpOptions.timeout = 0`, to make the client always wait until the connection is done.

**Comment by kadishmal** [comment]
From the XHR docs, it is saying that a request will be terminated in the specified `timeout` milliseconds.

The way I understand it is that even though the connection was successful and the request went through, and even the response is coming through but is taking longer than the `timeout`, the browser will kill the request. This is not what the SDK doc says:

> timeout [Integer] — Sets the socket to timeout after timeout milliseconds of inactivity on the socket. Defaults to two minutes (120000).

The SDK doc mentioned that the timeout is for inactivity of the socket, and not about the request timeout. So, the SDK docs need to be fixed.

I am also looking for a way to set the connection timeout for an XHR. Please let me know if anybody knows.
