### ISSUE TITLE
scanning DynamoDB returns shape.toType is not a function

### ISSUE THREAD

**Issue by ada1013** [aws/aws-sdk-js#2092]
I'm trying to use Lambda to scan DynamoDB, but always returns "shape.toType is not a function" and don't have any idea to fix it. Any help? thanks~
Code:
 ```
exports.Find = function(slot) {
	var params = {
		TableName : "test",
		ProjectionExpression:"ID, name"; 
		FilterExpression: "UserID = :id",
		ExpressionAttributeValues: {":id": {S:"abc"}}
	};
	var AWS = require('aws-sdk');
	AWS.config.region = "us-east-1";    
	var documentClient = new AWS.DynamoDB.DocumentClient();
	documentClient.scan(params, function(err, data){
		if (err) {
			console.error("Unable to scan the table. Error JSON:", JSON.stringify(err, null, 2));
		} else {
			console.log("Scan succeeded.");
		}
	}
};
```

error message:
```
Unable to scan the table. Error JSON:
{
    "message": "shape.toType is not a function",
    "code": "TypeError",
    "time": "2018-06-15T09:55:59.242Z"
}
```

**Comment by chrisradek** [comment]
@ada1013 
I haven't been able to reproduce your issue. Can you share the stack trace in the error being thrown?

One thing you'll want to change when using the `DocumentClient` is that your `ExpressionAttributeValues` don't need to be specified using the `AttributeValue` structure.

So instead of `ExpressionAttributeValues: {":id": {S:"abc"}}`, you can shorten it to `ExpressionAttributeValues: {":id": "abc"}`.

If you don't do that, then instead of comparing `:id` to a string, it will compare it to a JSON object with the field `S: 'abc'`.

**Comment by ada1013** [comment]
Thanks chrisradek,
But if I removed the attribute value S, the error message shows:

> Unable to scan the table. Error JSON:
> {
>     "message": "There were 4 validation errors:\n* InvalidParameterType: Expected params.ExpressionAttributeValues[':id'] to be a structure\n* UnexpectedParameter: Unexpected key '0' found in params.ExpressionAttributeValues[':id']\n* UnexpectedParameter: Unexpected key '1' found in params.ExpressionAttributeValues[':id']\n* UnexpectedParameter: Unexpected key '2' found in params.ExpressionAttributeValues[':id']",
>     "code": "MultipleValidationErrors",
>     "time": "2018-06-20T07:33:47.185Z",
>     "errors": [
>         {
>             "message": "Expected params.ExpressionAttributeValues[':id'] to be a structure",
>             "code": "InvalidParameterType",
>             "time": "2018-06-20T07:33:47.184Z"
>         },
>         {
>             "message": "Unexpected key '0' found in params.ExpressionAttributeValues[':id']",
>             "code": "UnexpectedParameter",
>             "time": "2018-06-20T07:33:47.184Z"
>         },
>         {
>             "message": "Unexpected key '1' found in params.ExpressionAttributeValues[':id']",
>             "code": "UnexpectedParameter",
>             "time": "2018-06-20T07:33:47.184Z"
>         },
>         {
>             "message": "Unexpected key '2' found in params.ExpressionAttributeValues[':id']",
>             "code": "UnexpectedParameter",
>             "time": "2018-06-20T07:33:47.184Z"
>         }
>     ],
>     "originalError": {
>         "message": "shape.toType is not a function",
>         "code": "TypeError",
>         "time": "2018-06-20T07:33:47.124Z"
>     }
> }

Here is the stack trace content:

> Error
> at Object.<anonymous> (/var/task/iot-intents.js:8:13)
> at Module._compile (module.js:570:32)
> at Object.Module._extensions..js (module.js:579:10)
> at Module.load (module.js:487:32)
> at tryModuleLoad (module.js:446:12)
> at Function.Module._load (module.js:438:3)
> at Module.require (module.js:497:17)
> at require (internal/module.js:20:19)
> at Object.<anonymous> (/var/task/alexa-skills-index.js:4:18)
> at Module._compile (module.js:570:32)

This issue really make me confuse, thanks~
