### ISSUE TITLE
KinesisVideo putMedia method

### ISSUE THREAD

**Issue by roccomuso** [aws/aws-sdk-js#2093]
Hi,

I wasn't able to find a `putMedia` method in the KinesisVideo service in this js SDK.
Is it possible to push a video stream to KinesisVideo in node.js?

**Comment by roccomuso** [comment]
I asked there. I'm trying to do it in JS.
From the documentation I can't really understand what's the issue with my mkv payload.
I keep getting this:

`{"Output":{"__type":"com.amazon.coral.service#SerializationException","Message":null},"Version":"1.0"}`

I'm using [aws4](/mhart/aws4) to generate my signatures.

**Comment by srchase** [comment]
Hi @roccomuso,

Are you able to call DescribeStream to get back the relevant StreamInfo object?

Or were you able to sort this out another way?

**Comment by roccomuso** [comment]
I've used aws4 to generate the signature, and axios to put the video stream to kinesis.

**Comment by srchase** [comment]
@roccomuso 

Do you have any additional questions?  If there's nothing further, I'm going to close out this issue.
