### ISSUE TITLE
Rules execute multiple times 

### ISSUE THREAD

**Issue by Balakumar-mobo** [aws/aws-sdk-js#2099]
i am using aws iot rules engine and am created one rule  temp > 45   if success republish to one topic . in my case temp reached 45 and it will continuously republish to that topic. how to set time interval for rules

**Comment by darrenhgc** [comment]
You should be able to add a `WHERE` clause to your rule's SQL statement that checks the `metadata.desired.temp.timestamp` against the `metadata.reported.temp.timestamp`. Keep in mind that your shadow may be structured differently than the example I provided.

**Comment by chrisradek** [comment]
Closing this issue since it isn't specific to the SDK.

For questions specific to how a service works, please reach out on the aws forums for that service:
https://forums.aws.amazon.com/forum.jspa?forumID=210
