### ISSUE TITLE
Is there a way to interogate what event source triggered a lambda?

### ISSUE THREAD

**Issue by lucas-rudd** [aws/aws-sdk-js#2103]
Feature Request:

I have a use case in which a lambda is being invoked from multiple different event sources (e.g. SNS and API Gateway, DynamoDB and S3, etc.); because these event sources have differing data mappings, in order to get the data needed from the source, it is first needed to determine which event source invoked the lambda, thus revealing where the data is in the object (and if it needs to be parsed, in the case of SNS et. al.).

This is kind of an obnoxious task... and in order to make it generic and stable (so that it isn't required to alter the source interrogation method when a new event source is required to trigger the lambda) all possible event sources need to be known by the lambda.

I'd imagine this would be provided in the context object sent to the lambda (e.g. an 'event source' key), but I couldn't find anything in the documentation which seemed to indicate this was the case. I also logged the context object sent to my lambda, and I didn't see anything there which looked like what I needed.

Is there currently a method in the sdk that will do this parsing? Or, at least provide the event source which triggered the lambda so that it can be determined where the data is?
If not, is there a 3rd party module which does this?

I'd prefer not to have to write my own, and I'm sure other developers will also find themselves in this situation at some point.

**Comment by AllanFly120** [comment]
I don't think there's a method provided to determine the Lambda trigger. Right now you can have a flag entry in your event to differentiate the resource, but I agree it's better to be provided by the service. I will provide your feedback to the service team and turn back if I have response from them.

**Comment by lucas-rudd** [comment]
Thank you. I'll check out the Lambda forum. Please update this if the service team responds. It would give us the ability to make our lambdas more generic to accept data from multiple places such as SNS or SQS, etc.

**Comment by lucas-rudd** [comment]
@AllanFly120 Any update on this?
