### ISSUE TITLE
Object was not deleted in s3

### ISSUE THREAD

**Issue by lenin-jaganathan** [aws/aws-sdk-js#2104]
I used s3.deleteObject() and passsed bucket name and key as params,there was no error thrown but the object was not deleted in  s3 bucket

**Comment by chrisradek** [comment]
@lenin-jaganathan 
Are you checking if the object is deleted immediately after calling `deleteObject`?

Amazon S3 uses [eventual consistency](https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel) for DELETES, so it's possible that trying to retrieve or list an object that's been deleted will return the deleted data until the change is fully propagated across their servers.

Does the object eventually become deleted?

**Comment by lenin-jaganathan** [comment]
That issue has been sorted out..but i got a new one the images i am storing were displaying some garbage characters instead of file itself.
![screenshot from 2018-06-24 16-17-38](https://user-images.githubusercontent.com/32874349/41818330-23e15aec-77ca-11e8-9e46-42154fa2e2b0.png)

**Comment by chrisradek** [comment]
@lenin-jaganathan 
This should probably be a separate issue. Can you open another one and share an example of how you're uploading your object to S3?
