### ISSUE TITLE
error amazon ses

### ISSUE THREAD

**Issue by GlauberF** [aws/aws-sdk-js#2105]
I have tried everything to solve the image problem below and nothing works, I follow the end-to-end settings.

I'm already thinking of swapping and going to the sparkpost, which worked on the first try

![captura de tela de 2018-06-22 17-18-50](https://user-images.githubusercontent.com/11314585/41797279-cc826894-763f-11e8-8ea1-204b0378edcd.png)

**Comment by chrisradek** [comment]
@GlauberF 
That error typically occurs when your system's clock is skewed from what the service clock is (assuming UTC time on both ends).

To see if that's the case, can you try setting the [correctClockSkew](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#correctClockSkew-property) property to `true` when instantiating your SES client?

**Comment by GlauberF** [comment]
now gave the following error

![captura de tela de 2018-06-22 17-39-19](https://user-images.githubusercontent.com/11314585/41797895-1dbb35a4-7642-11e8-8138-adc1cb20c183.png)

my user created, direct by SMTP settings
https://console.aws.amazon.com/ses/home?region=us-east-1#smtp-settings:

**Comment by GlauberF** [comment]
It worked

**Comment by chrisradek** [comment]
@GlauberF 
Glad to hear! I'll close the issue then, but feel free to open a new issue if you encounter errors.
