### ISSUE TITLE
Using spot instances with autoscaling group and launch templates.

### ISSUE THREAD

**Issue by ajhool** [aws/aws-sdk-js#2106]
It appears that spot instances are incompatible with launch templates and autoscaling groups -- the node.js sdk suggests that spot instances can be used with autoscaling groups, but the functionality does not actually appear to be supported. Should spot fleet requests and ApplicationAutoScaling be used in place of AutoScaling groups?

**Comment by AllanFly120** [comment]
Could you share the Nodejs SDK document about spot instances? And could you also elaborate what you are trying to do and how did you find the inconsistency between doc and the service functionality? I'm not familiar with this feature, not sure whether this is an SDK issue.
