### ISSUE TITLE
SimpleDB is not respecting custom endpoint

### ISSUE THREAD

**Issue by justinmchase** [aws/aws-sdk-js#2108]
I have this code:
```
const simpledb = new SimpleDB({
  apiVersion: '2009-04-15',
  endpoint: 'https://localhost:12345',
  region: 'us-east-1'
})

simpledb.createDomain({ DomainName: 'account' }, function (err, data) {
  if (err) console.log(err, err.stack)
  else console.log(data)
})
```

But instead of connecting to my localhost endpoint it is throwing this error:
```
{ Error: connect ECONNREFUSED 169.254.169.254:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2018-06-26T01:19:07.315Z,
  originalError:
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '169.254.169.254',
     port: 80,
     time: 2018-06-26T01:19:07.315Z,
     originalError:
      { code: 'ECONNREFUSED',
        errno: 'ECONNREFUSED',
        syscall: 'connect',
        address: '169.254.169.254',
        port: 80,
        message: 'connect ECONNREFUSED 169.254.169.254:80' } } } 'Error: connect ECONNREFUSED 169.254.169.254:80\n    at Object._errnoException (util.js:1022:11)\n    at _exceptionWithHostPort (util.js:1044:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)'
```

Can I not override the endpoint to be localhost for this service?

**Comment by chrisradek** [comment]
@justinmchase 
Based on the error message, it looks like the SDK is unable to resolve your credentials using the default credential provider chain. The last credential provider the default provider chain attempts to use is the EC2/ECS metadata credential provider. What you're seeing is the error the metadata credential provider encountered (it's unable to connect to the metadata service).

Can you try providing credentials to your client as well? I'm not familiar with SimpleDB, so I don't know if AWS credentials are required if you're accessing the local client. If they aren't, you could try passing fake credentials, which is what I think the local DynamoDB client requires.

**Comment by justinmchase** [comment]
Well that's true that's what the error is, but I think the reason why that error is happening because it is going up to the public endpoint, which does require credentials. You see the IP address `169.254.169.254:80` is the AWS service endpoint address.

If it were to actually go to localhost it would not need credentials and everything would work fine. So it appears to be ignoring the `endpoint: 'https://localhost:12345'` option, the server is not recording any calls to it.

**Comment by justinmchase** [comment]
I see what you're saying! If I add `AWS_PROFILE=example` when calling my app then it doesn't resolve the credentials and goes right to the api. It makes sense now, thanks!
