### ISSUE TITLE
Ligther version of SDK for multi-part upload from browser

### ISSUE THREAD

**Issue by korya** [aws/aws-sdk-js#2110]
Is there any official or other library providing functionality for multi-part upload of files from browser directly to S3?

I think that using the SDK for such a simple task is an overkill. It is 1.5MB of minimized JS that most of it will never get used.

What I really need is the implementation of S3 Multi-part upload protocol and retry logic for failing parts.

**Comment by chrisradek** [comment]
@korya 
Is that 1.5 MB with just the S3 client in your SDK? If you haven't already, you can build a version of the SDK with just S3, using either the browser builder UI/CLI:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html
Or by using a bundler like Webpack or Browserify and importing just the S3 client:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/webpack.html

That said, we do realize that the core of the SDK is large, and are working on addressing that. I can't provide an ETA on when that work will be done, but it is something we plan to improve on.

**Comment by korya** [comment]
Thanks!

The builder is great, but the generated minimized file containing only S3 functionality is still 250KB. So I will probably wait for the official solution and stick to EvaporateJS for now.
