### ISSUE TITLE
Image not viewing correctly

### ISSUE THREAD

**Issue by lenin-jaganathan** [aws/aws-sdk-js#2112]
![screenshot from 2018-06-24 16-17-38](https://user-images.githubusercontent.com/32874349/41970642-20c7b0fc-7a29-11e8-9cee-d34baf691d35.png)
I had uploaded an image to S3 using node js. I used getSignedUrl(method,params) to get the signed url.
Here
method = 'putObject'
const params = {
    Bucket: 'myBucketName/'+'some dynamic path',
    Key: key,
    Expires: 86400,
    ACL: 'public-read-write',
    "ContentType": 'image/png'
  };

After getting the image url, I used axios.put({
url : signedUrl,
method : 'PUT'
data : file,
contentType: 'image/png'})

The image was uploaded successfully.But when i view it using a link i was seeing something similar to the image below.But if i use it in html <img /> i was able to see the image in my web page.

**Comment by AllanFly120** [comment]
I cannot reproduce this issue. Can you check the whether the length of your PNG equals that you uploaded?

**Comment by lenin-jaganathan** [comment]
No the file size compresses by some 2-3%.I don't why it is compressing

**Comment by AllanFly120** [comment]
Hi @lenin-jaganathan 
What is the 'data: file' in your code snippet? Is it buffer or stream? Also can you check what is the value of the content-length header in your put request? It's possible the axios is setting the wrong content-length in putObject

**Comment by lenin-jaganathan** [comment]
data: file.
Here file is an file standard file object.

**Comment by srchase** [comment]
Hello @lenin-jaganathan,

Were you able to determine if axios is setting the wrong content-length?
