### ISSUE TITLE
Where is the pinpoint createEndpoint function?

### ISSUE THREAD

**Issue by ddemoll** [aws/aws-sdk-js#2113]
### AWS Pinpoint

There is a function to deleteEndpoint:
[https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#deleteEndpoint-property]

Why not createEndpoint?

**Comment by AllanFly120** [comment]
Hey @ddemoll 
According to the [doc](https://docs.aws.amazon.com/pinpoint/latest/developerguide/endpoints.html), you can call [`updateEndpoint`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#updateEndpoint-property) instead to use a new endpoint.
