### ISSUE TITLE
Cognito: calling initiateAuth requires credentials

### ISSUE THREAD

**Issue by FabricioFFC** [aws/aws-sdk-js#2119]
The `initiateAuth` function from `CognitoIdentityServiceProvider` is given the following error when I call without pass the credentials: `Missing credentials in config`

```
Missing credentials in config
    at credError (config.js:324)
    at getStaticCredentials (config.js:345)
    at Config.getCredentials (config.js:354)
    at Request.VALIDATE_CREDENTIALS (event_listeners.js:80)
    at Request.callListeners (sequential_executor.js:101)
    at Request.emit (sequential_executor.js:77)
    at Request.emit (request.js:683)
    at Request.transition (request.js:22)
    at AcceptorStateMachine.runTo (state_machine.js:14)
    at Request.runTo (request.js:403)
    at Request.send (request.js:367)
    at features.constructor.makeRequest (service.js:193)
```
I found this validation inconsistent, because other functions like `signUp` and `getUser` don't require the credentials. Also the docs doesn''t mention the credentials need: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#initiateAuth-property

Is there any way that I can use the `initiateAuth` without pass the credentials?

**Comment by chrisradek** [comment]
@FabricioFFC 
The SDK determines if credentials can be ignored for an operation if it is modeled with the `authtype: 'none'` trait:
https://github.com/aws/aws-sdk-js/blob/a56b2c08ba4bb045725c6e5b40e2aa667507e84b/apis/cognito-idp-2016-04-18.normal.json#L571

It's up to the service team to decide which operations can be excluded from requiring credentials, so you might want to ask on the [Amazon Cognito forums](https://forums.aws.amazon.com/forum.jspa?forumID=173) on if this should be possible.

We can update your documentation to explicitly call out when credentials are being used or not.

If you're absolutely sure AWS credentials are not needed, it is possible to remove the credentials check:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EventListeners/Core.html#VALIDATE_CREDENTIALS-property

However, note that this will remove the check from every request the SDK makes. If you wanted to remove them from just CognitoIdentityServiceProvider requests, you would need to remove the listener on the request returned by each operation call.

**Comment by thiagohirata** [comment]
You can call initiateAuth without AWS Credentials by removing the listeners of the request:

``` javascript
  const params = {
    ClientId: clientId,
    AuthFlow: 'USER_PASSWORD_AUTH',
    AuthParameters: {
      USERNAME: username,
      PASSWORD: password,
    },
  }
  cognitoidentityserviceprovider
    .initiateAuth(params)
    .removeListener('sign', AWS.EventListeners.Core.SIGN)
    .removeListener('validate', AWS.EventListeners.Core.VALIDATE_CREDENTIALS)
    .send(function(err, data) {
      console.log({ err, data })
    })
```

No hints about it in the documentation, though.
