### ISSUE TITLE
Pinpoint SNS topics?

### ISSUE THREAD

**Issue by ddemoll** [aws/aws-sdk-js#2127]
Why are there no topics in pinpoints like in SNS? It is very difficult to send a push notification to a dynamically changing limited audience. sendUsersMessages has a limit of 15 recipients. I can't use segments because they are statically loaded from an s3 bucket. I guess I'll have to send my messages in 15 user chunks or maybe I'll switch to firebase

**Comment by chrisradek** [comment]
@ddemoll 
Please post your feedback about Amazon Pinpoint on their AWS forums page:
https://forums.aws.amazon.com/forum.jspa?forumID=225

Their service team monitors the forums and I'm sure would be happy to hear your feedback.
