### ISSUE TITLE
URL returned by createPresignedPost is incorrect

### ISSUE THREAD

**Issue by andy-viv** [aws/aws-sdk-js#2128]
Hello!

When using `createPresignedPost`, I get an object in the following format:

```json
{ "url": "https://s3.amazonaws.com/[BUCKET_NAME]", "fields": {...} }
```
However, the actual URL to upload that works is `https://[BUCKET_NAME].s3.amazonaws.com`. Using the URL returned by `createPresignedPost` results in an error telling me to use the subdomain format.

I checked through existing issues and didn't see one with this exact problem, so my apologies if this is a duplicate.

**Comment by AllanFly120** [comment]
Hi @andy-viv  
I cannot reproduce this issue. Can you show me the response you get and which region is the bucket in? It will also be helpful if you can paste a code snippet here showing how you post the form.

**Comment by alsmola** [comment]
I've encountered this too. The URL I was getting returned by `createPresignedPost` was `https://s3.amazonaws.com/{bucket_name}`, which breaks the CORS preflight OPTIONS request when POSTed to directly (301 status code). I feel like the URL returned should have the bucket name in the host `https://[BUCKET_NAME].s3.amazonaws.com` to prevent this issue. Note that the region may be included and mitigate this issue if it is set in the AWS config, environment var, etc. but adding the bucket name to the host feels like a more straightforward change.
