### ISSUE TITLE
aws-sdk have control on concurrency to invoke lambda?

### ISSUE THREAD

**Issue by donglaizhang** [aws/aws-sdk-js#2129]
Hey,

This is  a question, not an issue. 
I am trying to do some test in invoking lambda via aws-sdk. Now, I have a very simple lambda function with nodejs 6, and a client with nodejs6 and aws-sdk.

In lambda side, there is nothing but only give response after 5s: 
```javascript
exports.handler = (event, context, callback) => {
   callback(null, 'Hello from Lambda');
};
let var1 = undefined;
function wait(ms){
   var start = new Date().getTime();
   var end = start;
   while(end < start + ms) {
     end = new Date().getTime();
  }
}
```
Other setting is normal: 5min timeout,  `Use unreserved account concurrency`, `no VPC`, then in the client side to invoke this lambda:

```javascript
aws.config.update({ region: 'xxxx' });
aws.config.logger = console;
aws.config.httpOptions = {
    timeout: 8000
}
aws.config.maxRetries = 0;
...
//invoke fn:
function promiseInvoke(ctx) {
 let params = {
        FunctionName: 'xxxx',
        InvocationType: 'RequestResponse'
    }
    params.ClientContext = new Buffer(JSON.stringify(ctx)).toString('base64');
    params.Payload = ""; //empty payload
        let s1 = new Date().getTime();
        return new Promise((resolve, reject) => {
            lambda.invoke(p, function(err, data) { 
                      if (err) {
                    return reject(err);
                }
                return resolve(data);
            });
        });
    }
    return promiseInvoke(params).then(data => {
                console.log(context, "error");
    }).catch(e => {
                console.log(context, "ERROR, performance:", (new Date().getTime() - s1) + "ms, error:", e);
    });
}

function batchexec(count) {
    for (let i = 0 ; i < count;i++) {
        let trackid = "trackid:" + i + "-end";
        promiseInvoke({"trackid": trackid}));
    }
}
batchexec(200);
```
Lastly, some logs came out like the following:
```
[AWS lambda 200 **52.586s** 0 retries] invoke({ FunctionName: 'xxx',
  InvocationType: 'RequestResponse',
  ClientContext: 'xxx',
  Payload: '' })
{ 'trackid': 'trackid:188' } 'InvokePerformance:' '52586ms, data:' '{"StatusCode":200,"ExecutedVersion":"$LATEST","Payload":"\\"Hello from Lambda\\""}'

```
As I understood, some lambda invoking request took a longer response time than http timeout. However, from cloud watch, this invocation only cost 5s more or less:
```
REPORT RequestId: xxxx	Duration: 5130.91 ms	Billed Duration: 5200 ms Memory Size: 128 MB	Max Memory Used: 23 MB	
```
From the above information, it looks aws sdk has some kind of concurrency control in the client side. From the client logs, the concurrency threshold looks like 50 -- 50 http request are able to process at the same time. If there are 50 http requests was in processing, and more requests was coming, and waiting until there are some spaces(one or more requests in the first 50 request get response). 

Is that correct?  If it is correct, how to config the capacity of the concurrency. By the way, is that possible to invoke lambda via http client without aws-sdk and api-gateway?

Regards,
Donglai

**Comment by chrisradek** [comment]
@donglaizhang 
In nodejs, the SDK has a default setting where it will only allow 50 connections to a host a time. However, that is configurable by changing the `maxSockets` setting of your Lambda client:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-maxsockets.html

For your other question, it is possible to invoke lambda functions directly using their REST API, but you would need to be able to sign your request using sigv4 signing (the SDK handles that for you):

https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html
https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

**Comment by donglaizhang** [comment]
Thank you for the quick response.
