### ISSUE TITLE
Empty data object returned when using dynamoDB.getItem and sts.assumeRole. 

### ISSUE THREAD

**Issue by kscherr** [aws/aws-sdk-js#2130]
Simplified code:

```js
const AWS = require('aws-sdk');

// get credentials
const { Credentials: credentials } = await this.sts.assumeRole({
  RoleArn: roleArn,
  RoleSessionName: roleSessionName
}).promise();

// convert to proper case
const creds = {
  accessKeyId: credentials.AccessKeyId,
  secretAccessKey: credentials.SecretAccessKey,
  sessionToken: credentials.SessionToken
};

// make dynamo client with new creds
const dynamo = new AWS.DynamoDB({credentials: creds, region: 'us-east-1'});

// get item
const result = await dynamo.getItem({
  Key: {
    my_id: {
       S: myId,
    }
  },
  TableName: myTableName
}).promise();
```
At the end of this, result is always an empty object (no Item and error is null). This is true regardless of if a matching result exists. I verified the role returns proper errors for things it can't do (like describe table).

Let me know if you need more info.

**Comment by Sparticuz** [comment]
What was the problem/solution @kscherr?

**Comment by leonfs** [comment]
Yes, what was the solution @kscherr ? I'm seeing the same behaviour and it does not match the documentation. I would expect to see a `null` response instead of an `{}` (empty) object.
