### ISSUE TITLE
When trying to query Organizations we get a TooManyRequestsException

### ISSUE THREAD

**Issue by robertsj-vmware** [aws/aws-sdk-js#2135]
We were seeing this in the AWS CLI, and boto3 code as well. Botocore has a fix (https://github.com/boto/botocore/commit/0a157efcd373648ac59023f58df972410ee31458) in 1.10.53+. They say that organizations wasn't triggering their retry logic because it was using HTTP Status 400 instead of 429.

The message from our logs is below:
`{
"message": "Error getting linked accounts from AWS for account 127776885678",
"stack": "TooManyRequestsException: AWS Organizations can't complete your request because another request is already in progress. Try again later.\n at Request.extractError (/opt/app/node_modules/aws-sdk/lib/protocol/json.js:48:27)\n at Request.callListeners (/opt/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n at Request.emit (/opt/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n at Request.emit (/opt/app/node_modules/aws-sdk/lib/request.js:683:14)\n at Request.transition (/opt/app/node_modules/aws-sdk/lib/request.js:22:10)\n at AcceptorStateMachine.runTo (/opt/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n at /opt/app/node_modules/aws-sdk/lib/state_machine.js:26:10\n at Request.<anonymous> (/opt/app/node_modules/aws-sdk/lib/request.js:38:9)\n at Request.<anonymous> (/opt/app/node_modules/aws-sdk/lib/request.js:685:12)\n at Request.callListeners (/opt/app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)",
"code": "TooManyRequestsException",
"name": "TooManyRequestsException",
"time": "2018-06-29T15:42:40.663Z",
"requestId": "0e70b5a3-7bb3-11e8-bd1f-31c934394d24",
"statusCode": 400,
"retryable": false,
"retryDelay": 14.748112670521895,
"level": "error",
"label": {
"type": "server"
},
"timestamp": "2018-06-29 03:42:40.6630"
}`

**Comment by AllanFly120** [comment]
Hey @robertsj-vmware Thank you for bringing this up. Sometimes we don't get informed of the changes from service. We will get a fix for this soon.

**Comment by robertsj-vmware** [comment]
Thanks @AllanFly120!!

**Comment by srchase** [comment]
Fixed in https://github.com/aws/aws-sdk-js/pull/2246.

Closing out this issue.
