### ISSUE TITLE
AWS Cognito not able to delete user as admin

### ISSUE THREAD

**Issue by ihd2911** [aws/aws-sdk-js#2136]
I am using aws cognito create customers for my application and store their id in my database to keep local records. I have used local database for admin users. I have used aws amplify to sign up users But i am facing issue in deleting a user when logged in as admin.

I am using aws sdk for it

```
aws.config.update({
    accessKeyId: "string",
    secretAccessKey: "string",
    region: process.env.REACT_APP_REGION
});


aws.config.credentials = new aws.CognitoIdentityCredentials({
    IdentityPoolId: process.env.REACT_APP_IDENTITYPOOLID,
    AllowUnauthenticatedIdentities: true,
    AccountId: 'string',
    RoleArn: 'arn:aws:iam::string:role/Cognito_WebReactAuth_Role',
});


var params  = {
    UserPoolId: process.env.REACT_APP_USERPOOLID,
    Username: id,
};

var cognitoidentityserviceprovider = new aws.CognitoIdentityServiceProvider();

cognitoidentityserviceprovider.adminDeleteUser(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
```

But it give me error **Not authorized to perform sts:AssumeRoleWithWebIdentity** and **CredentialsError: Missing credentials in config**

What i am trying to achieve is logging as admin using my local database and listing of all the customers from local database. When i will click on delete user from cognito as well as local database will be deleted.

Any help appreciated.

**Comment by chrisradek** [comment]
@ihd2911 
Sorry for the late response.

One thing I want to point out is that the credentials you supply in your first `aws.config.update` statement get immediately overridden when you set `aws.config.credentials` to a CognitoIdentityCredentials provider.

Does the role that your identity pool has access to also have the ability to assume the role you've defined in your `RoleArn` parameter? Based on the error message it seems it may not.

**Comment by ihd2911** [comment]
import aws from 'aws-sdk';

    aws.config.accessKeyId = process.env.REACT_APP_AWS_ACCESS_KEY;
    aws.config.secretAccessKey = process.env.REACT_APP_AWS_SECRET_ACCESS_KEY;
    aws.config.region = process.env.REACT_APP_REGION;

    let params = {
        UserPoolId: process.env.REACT_APP_USERPOOLID,
        Username: user.cognitoClientId,
    };

    let cognitoidentityserviceprovider = new aws.CognitoIdentityServiceProvider();

    cognitoidentityserviceprovider.adminDeleteUser(params, function (err, data) 

All the admin services can be used like this. AWS documentation is hard to understand.
This example for admin should be put somewhere as it can come handy.


No need to add following, as it is done for frontend only.

     aws.config.credentials = new aws.CognitoIdentityCredentials({
       IdentityPoolId: process.env.REACT_APP_IDENTITYPOOLID,
       AllowUnauthenticatedIdentities: true,
       AccountId: 'string',
       RoleArn: 'arn:aws:iam::string:role/Cognito_WebReactAuth_Role',
    });
