### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by jayeshsheta** [aws/aws-sdk-js#2141]
ncaught ReferenceError: global is not defined
    at Object../node_modules/buffer/index.js (index.js:43)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/aws-sdk/lib/browserHashUtils.js (browserHashUtils.js:1)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/aws-sdk/lib/browserHmac.js (browserHmac.js:1)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/aws-sdk/lib/browserCryptoLib.js (browserCryptoLib.js:1)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/aws-sdk/lib/browser_loader.js (browser_loader.js:4)
    at __webpack_require__ (bootstrap:76)
./node_modules/buffer/index.js @ index.js:43
__webpack_require__ @ bootstrap:76
./node_modules/aws-sdk/lib/browserHashUtils.js @ browserHashUtils.js:1
__webpack_require__ @ bootstrap:76
./node_modules/aws-sdk/lib/browserHmac.js @ browserHmac.js:1
__webpack_require__ @ bootstrap:76
./node_modules/aws-sdk/lib/browserCryptoLib.js @ browserCryptoLib.js:1
__webpack_require__ @ bootstrap:76
./node_modules/aws-sdk/lib/browser_loader.js @ browser_loader.js:4
__webpack_require__ @ bootstrap:76
./node_modules/aws-sdk/clients/s3.js @ s3.js:1
__webpack_require__ @ bootstrap:76
./src/app/system-service/upload-file.service.ts @ system-service.service.ts:9
__webpack_require__ @ bootstrap:76
./src/app/components/form-upload/form-upload.component.ts @ main.js:852
__webpack_require__ @ bootstrap:76
./src/app/components/system.module.ts @ system-routing.module.ts:19
__webpack_require__ @ bootstrap:76
./src/app/app.module.ts @ app.component.ts:8
__webpack_require__ @ bootstrap:76
./src/main.ts @ environment.ts:15
__webpack_require__ @ bootstrap:76
0 @ main.ts:12
__webpack_require__ @ bootstrap:76
checkDeferredModules @ bootstrap:43
webpackJsonpCallback @ bootstrap:30
(anonymous) @ main.js:1

**Comment by craigbrett17** [comment]
Got this too after resolving #1271.

**Comment by craigbrett17** [comment]
It seems slightly related to the aforementioned bug.

Temporary hack around seems to be (from StackOverflow) to add something like this to your polyfils.ts

```
// aws-sdk requires global to exist
(window as any).global = window;
```

**Comment by srchase** [comment]
@jayeshsheta 

I apologize we didn't get back to you on this issue.

Are you still encountering this issue?  Can you provide additional details if it is still happening for you?

**Comment by afaneh262** [comment]
@jayeshsheta in my case i had to add: 
```
// aws-sdk requires global to exist
(window as any).global = window;
```

to `/src/polyfills.ts`
and 
`"types": ["node"]`
to compilerOptions block in `/src/tsconfig.app.json`

**Comment by nlndby** [comment]
worked
