### ISSUE TITLE
AWS.Firehose.putRecordBatch does not work

### ISSUE THREAD

**Issue by nodren** [aws/aws-sdk-js#2145]
It has correct typings in typescript, and is documented in the docs, but attempting to call it presents me with this error:

`firehoseStream.putRecordBatch is not a function`

code in question:

```
const firehoseStream = new AWS.Firehose()
firehoseStream.putRecordBatch(params, (err, data) => {
	if (err) {
		reject(err)
		return
	}
	resolve()
})
```

**Comment by AllanFly120** [comment]
Hi @nodren which SDK version are you using? Can you try using the newest version of SDK?

**Comment by nodren** [comment]
Problem was found back in v2.187.0, updated to latest v2.275.1 with no affect.  Tried this before posting the issue here

**Comment by AllanFly120** [comment]
I cannot reproduce this issue. How do you import the SDK?

**Comment by srchase** [comment]
Closing without further information to reproduce.
