### ISSUE TITLE
ResourceNotFoundException on IoTJobsDataPlane updateJobExecution

### ISSUE THREAD

**Issue by jchirschy** [aws/aws-sdk-js#2146]
Hello,

Trying unsuccessfully to run any methods of `IoTJobsDataPlane` in a **AWS lambda** function. I got `ResourceNotFoundException` or `InvalidSignatureException`.

With :
``` javascript
const iotjobsdataplane = new AWS.IoTJobsDataPlane({
  endpoint: 'xxx.iot.eu-west-1.amazonaws.com',
  region: 'eu-west-1',
  accessKeyId: 'xxx',
  secretAccessKey: 'xxx',
})
```
I get : `ResourceNotFoundException`

With : 
``` javascript
const iotjobsdataplane = new AWS.IoTJobsDataPlane({
  endpoint: 'iot.eu-west-1.amazonaws.com',
  region: 'eu-west-1',
  accessKeyId: 'xxx',
  secretAccessKey: 'xxx',
})
```
I get `InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'`

And, of course, with no endpoint, I got `AccessDeniedException`. 

The user behind accessKeyId got `AWSIoTFullAccess` policy. I first try with a role that assumes the same policy but in vain.

Did I miss something with this API ?
I'm trying to update update job execution.

Thanks for your help.

**Comment by AllanFly120** [comment]
Hi @jchirschy When do you see these exceptions? We don't make any API calls when constructing the client. Have you tested locally with the same credentials?

**Comment by maitien2004** [comment]
@AllanFly120 

I try to call updateJobExecution API  but job status not change.

`
  const iotJobsDataPlane = new AWS.IoTJobsDataPlane(
    { 
      endpoint: 'xxxx.jobs.iot.us-west-2.amazonaws.com' 
    }
  );

  var updateJobExecutionParams = {
    thingName: 'thingId',
    jobId: 'jodId',
    status: 'SUCCEEDED'
  };

  iotJobsDataPlane.updateJobExecution(updateJobExecutionParams, function (err, data) {
    if (err) {
      console.log(err);
    } else {
      console.log(data);
    }
  });`

Here is output when execute above functions
`{}`

**Comment by AllanFly120** [comment]
Hi @maitien2004 
Where are you getting the endpoint from? Endpoint from the [iot jobs data model](https://github.com/aws/aws-sdk-js/blob/bb421b7553b0e8a79299475a26e8c65350e642a1/apis/iot-jobs-data-2017-09-29.normal.json#L5) should be automatically set to something like `data.jobs.iot.{region}.amazonaws.com` Then you don't need to set the endpoint.
What makes the issue a little weird is that the service returns a successful response instead of a `resourceNotFound` exception. Can you first try to remove the endpoint setting in constructing the client to see if that solve the problem?

**Comment by maitien2004** [comment]
Hi AllanFly120,

I got the endpoint from describeEndpoint API with iot:Jobs endpoint type.

I try remove endpoint in constructor but i have a difference problem.(Access Denied: Invalid enpoint. Use describe enpoint api to get vaild endpoint)

Please let me know if anything incorrect.

Thanks,
Tiến Mai

**Comment by srchase** [comment]
@jchirschy 

Were you able to get this resolved?

The jobs endpoint should be something like: ```XXX.jobs.iot.us-west-2.amazonaws.com```

**Comment by nsraptor** [comment]
I am facing the same issue while trying to update the  job status .

**Comment by srchase** [comment]
@nsraptor 

Can you provide an example of your code?

**Comment by nsraptor** [comment]
Appreciate your help :)
