### ISSUE TITLE
Update JS documentation to include need to generate custom SDK

### ISSUE THREAD

**Issue by JerryKurata** [aws/aws-sdk-js#2151]
I fought with error "AWS.Translate is not a constructor" for a day.  This occurred because document just told me to install the SDK from NPM.  But the aws-sdk.js installed does not contain support for Translate.  After a lot of searching I found reference to https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html and learned how to generate the custom SDK containing support for Translate.  And this fixed the issue.

It would be great if someone could go through any javascript examples and point out there may be a need to generate a custom SDK.

I was following along the steps listed on this page: https://docs.aws.amazon.com/translate/latest/dg/examples-polly.html

Thanks!

**Comment by AllanFly120** [comment]
I agree with you. The AWS.Translate example in browser is not exact. The SDK get imported in the example is actually Browser SDK, which only has services that support [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) according to the service model we have. But our service model may not always up-to-date with the services. Seems like AWS.Translate does support CORS now, we will fix our code shortly. Thank you for bringing this to us.

This is a rough edge of SDK and we do mention this in the repo's [README](https://github.com/aws/aws-sdk-js#in-the-browser)

**Comment by JerryKurata** [comment]
AllanFly120.  Thanks for looking into this so quick!
