### ISSUE TITLE
Node.js(8.10) AWS Lambda inconsistent functionality in s3.putObject upload of data object

### ISSUE THREAD

**Issue by ANTGOMEZ** [aws/aws-sdk-js#2152]
Here is the Lambda code I am using to read a table and then upload the results to S3:

`'use strict';

const pg = require('pg');
const aws = require('aws-sdk');
const awsParamStore = require( 'aws-param-store' );

exports.handler = async function (context)
{    

function putObjectToS3(bucket, key, data){
    var s3 = new aws.S3();
        var params = {
            Bucket : bucket,
            Key : key,
            Body : data
        }
        s3.putObject(params, function(err, data) {
          if (err) console.log(err, err.stack); // an error occurred
          else     console.log(data);           // successful response
        });
}

context.callbackWaitsForEmptyEventLoop = false;

var dbname = 'pg_db';
var milliseconds = (new Date).getTime();
var fileName = 'process_log_' + milliseconds.toString() + '.json';

let parameter = awsParamStore.getParameterSync(process.env.ParameterPath);

var client = new pg.Client(parameter.Value + '/' + dbname);
await client.connect();

const { rows } = await client.query('SELECT * FROM public.mytable LIMIT ' + process.env.LimitRes.toString() + ';');    
client.end();

var json = JSON.stringify(rows);

putObjectToS3('mybucket', 'thefile.json', json);

//return JSON.stringify(rows); << verified that there are actually 10,000 rows of data 
//return json; << verified that the json is valid.
//return rows.length; << 10,000 count    
};
`

I have verified that the data is valid and that the number of rows do actually exist in the result.

However, the behavior is inconsistent. Sometimes the upload will happen but most times it won't. I have to run the lambda several times to get it to upload, and the larger the set of rows, the less likely it is to happen.

By the way, the Lambda memory setting is set to 1664 MB so there is plenty to handle the data. Also, the code never throws an error when it runs, always green despite file not always getting created in s3. Also is well within the Lambda timeout period of 5 mins.

Advice appreciated, thanks!

**Comment by chrisradek** [comment]
@ANTGOMEZ 
I suspect the issue is because you are not `await`ing the S3 putObject command, and you have `context.callbackWaitsForEmptyEventLoop = false;`

The `putObjectToS3` method will run asynchronously when you call it within your async handler and then your handler will immediately resolve. Since you've turned off waiting for an empty event loop before freezing your lambda function, your Lambda function is likely freezing before the full call to S3 is made.

You can call S3 putObject such that it returns a promise, then await that within your handler:

```javascript
function upload() {
 return s3.putObject(/*params*/).promise();
}

async test() {
  await upload();
}
```

**Comment by ANTGOMEZ** [comment]
Yes, that worked. Thank you!

**Comment by Priya62** [comment]
Hello,
I have a similar issue where i'm trying to upload object to s3 inside  a for loop, essentially my code is as below, any idea how to resolve this?
function putObject(bucketinpt, keyinput, datainput) {

    var uploadparams = {
        Bucket: bucketinpt,
        Key: keyinput,
        Body: datainput
    };



    s3.putObject(uploadparams, function(err, data) {

        if (err) {
            console.log("error: " + err, err.stack); // an error occurred
            throw new Error("error in writing file to S3");
        }
    }).promise();
}


exports.handler = async (event, context, callback) => {


    var s3ReadStream = s3.getObject(rawFileParams).createReadStream().pipe(zlib.createGunzip());


    var rl = readline.createInterface({

        input: s3ReadStream,
        terminal: false
    });

    //variable declaration

    //Calculate number of lines per file
    promises.push(new Promise((resolve, reject) => {

        rl.on('line', (line) => {
            //console.log('line'+line)

            wholeFileCount = wholeFileCount + 1

            //console.log("splitLineCount+++"+splitLineCount)
            if (splitLineCount < lineCountPerFile) {



                let result = await putObject(bucketName, filePath + fileNamewithoutExtension + "_" + splitFileCount + ".txt", linesToBeWritten);
                console.log(result)

                splitLineCount = 0;
                splitFileCount += 1;
                linesToBeWritten = "";



            } else {
                linesToBeWritten += line;
                linesToBeWritten += "\n";
                splitLineCount = splitLineCount + 1
            }

        });
        rl.on('error', () => {

            throw new Error("error in file streaming operation");
        });
        rl.on('close', function() {
            resolve();
        });
    }));

    // wait for all promised operations to complete

    await Promise.all(promises);



};


but this gives me an error saying,  "errorMessage": "await is only valid in async function",
