### ISSUE TITLE
Bucket needs to be an optional field in the s3.d.ts file

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js#2153]
https://github.com/aws/aws-sdk-js/blob/master/clients/s3.d.ts

Bucket should be `Bucket?: BucketName`, as it could be defined globally upon S3 instantiation, e.g.:

```js
new S3({
  apiVersion: '2006-03-01',
  credentials: await getCredentials(),
  params: {
    Bucket: process.env.BUCKET,
  },
});
```

**Comment by chrisradek** [comment]
Hi @ffxsam 
This is currently a known limitation with our typings. Please see #2123 for more information.
