### ISSUE TITLE
Could not load credentials from constructor

### ISSUE THREAD

**Issue by stripathix** [aws/aws-sdk-js#2156]
**Exception:**
{
code: CredentialsError, 
column: 1465900, 
line: 1, 
message: Could not load credentials from constructor, 
name: CredentialsError, 
originalError: {
code: NotAuthorizedException, 
column: 1465900, 
line: 1, 
message: Invalid login token. Token expired: 1532210722 >= 1532175445, 
requestId: dc5661d5-8d32-11e8-bf2e-43b6cf1946d5, 
retryable: False, 
retryDelay: 55.72289339705143, 
sourceURL: http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js, 
statusCode: 400, 
time: 2018-07-21T22:10:22.128Z
}, 
requestId: dc5661d5-8d32-11e8-bf2e-43b6cf1946d5, 
retryable: False, 
retryDelay: 173.29459975732328, 
sourceURL: http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js, 
stack: 
extractError@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1465900
callListeners@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1496130
emit@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1495849
emitEvent@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1481947
e@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1477519
runTo@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1538012
http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1538218
http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1477804
http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1482002
callListeners@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1496235
emit@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1495849
emitEvent@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1481947
e@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1477519
runTo@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1538012
http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1538218
http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1477804
http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1482002
callListeners@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1496235
i@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1496004
http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1439033
emit@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1578699
finishRequest@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1448819
http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:1447421
d@http://localhost:8080/js/vendor.bundle.4.4.1.0.18.07.09.20.36.js:1:23143
, 
statusCode: 400, 
time: 2018-07-21T22:10:22.130Z
}

**Stacktrace:**
t()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:48:3399
o()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:49:1911
a()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:49:1630
this()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:48:19726
a()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:48:15368
r()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:50:11911
e()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:50:12117
a()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:48:15575
this()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:48:19781
o()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:49:2016
a()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:49:1630
this()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:48:19726
a()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:48:15368
r()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:50:11911
e()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:50:12117
a()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:48:15575
this()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:48:19781
o()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:49:2016
e()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:49:1785
t()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:47:8381
this()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:51:20935
finishRequest()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:47:18192
m()@http://localhost:8080/app/node_modules/aws-sdk/dist/aws-sdk.min.js:47:16794
this()@http://localhost:8080/app/node_modules/raven-js/dist/raven.min.js:2:4707

**Comment by chrisradek** [comment]
@stripathix 
Can you share how you've configured your credential provider, and which one you're using? Most providers should automatically refresh when the credentials have expired.

**Comment by stripathix** [comment]
I an using AWS cognito no external provider.

`
AWS.config.region = AccountConst.awsCognito.region;

        AWS.config.correctClockSkew = true;

        AWS.config.credentials = new AWS.CognitoIdentityCredentials({IdentityPoolId: identityPoolId});

        var userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);`



`if (cognitoUser !== null) {

            cognitoUser.getSession(function (err, oldSession) {
                if (!err) {
                    var refreshToken = oldSession.getRefreshToken();
                    console.log("Refreshing session");
                    cognitoUser.refreshSession(refreshToken, function (err, refreshedSession) {
                        if (!err) {
                            console.log("Session refreshed successfully!");
                            var logins = {};
                            logins[cognitoEndpoint + "/" + poolData.UserPoolId] = refreshedSession.getIdToken().getJwtToken();
                            AWS.config.credentials = new AWS.CognitoIdentityCredentials({
                                IdentityPoolId: identityPoolId,
                                Logins: logins
                            });
                            // Make the call to obtain credentials
                            AWS.config.credentials.get(function () {
                                console.log("Success credentials");
                                refreshingToken = false;
                                client = new AWS.CognitoSyncManager();
                                if (client) {
                                    client.openOrCreateDataset(bnDataSetName, function (err, dataset) {
                                        if (!err) {
                                            bnUserPreferencesDataset = dataset;
                                        } else {
                                            errorLogService(err);
                                        }
                                    });
                                }
                            });
                            deferred.resolve(true);
                        } else {
                            err.message = "ResumeAppplicationCognito: Not able to refresh session: User " + cognitoUser.username + ":" + err.message;
                            err.emailTried = cognitoUser.username;
                            if (!err.code.match(new RegExp(AppConst.exceptionsCodes.UserNotFoundException)) && !err.message.match(new RegExp(AppConst.exceptionsCodes.incorrectPassword))) {
                                errorLogService(err);
                            }
                            deferred.resolve(false);
                        }
                    });
                }
            });
        }``

**Comment by chrisradek** [comment]
@stripathix 
When do you see this error? Does it happen the first time you call `AWS.config.credentials.get`, or after some time?

Since the error says that your token has expired, I suspect that your user pool token eventually expires. The [CognitoIdentityCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html) provider doesn't manage refreshing tokens:
> In addition to AWS credentials expiring after a given amount of time, the login token from the identity provider will also expire. Once this token expires, it will not be usable to refresh AWS credentials, and another token will be needed.

**Comment by stripathix** [comment]
It's intermittent so I would say it happens after some time using app. 

I have a aws configuration that refresh token expiry after 3650 days. As CognitoIdentityCredentials does not manage refreshing token, so what should I use to make sure that AWS sdk handle refreshing of auth token by itself.

**Comment by srchase** [comment]
@stripathix 

Getting a 'refresh token' will depend on the identity provider's implementation.  You'll need to refer to the documentation from whichever identity provider you are using.
