### ISSUE TITLE
Cannot update credentials

### ISSUE THREAD

**Issue by lpender** [aws/aws-sdk-js#2157]
Hi!

I'm using `2.279.1`. This code is adopted from [awsmoblile-cli](https://github.com/aws/awsmobile-cli/blob/master/lib/aws-operations/aws-client.js), which has been failing for me. After digging, I've found what I think is the source of the problem.

This is as simple and direct a demonstration of the issue as is possible.

Here's my code:

```
  AWS.config.update({
      credentials: new AWS.Credentials('accessKeyId', 'secretAccessKey')
  });

  console.log(AWS.config);
```

Here is the output:

```
Config {
  credentials:
   Credentials {
     expired: false,
     expireTime: null,
     accessKeyId: 'accessKeyId',
     sessionToken: undefined },
  credentialProvider:
   CredentialProviderChain {
     providers: [ [Function], [Function], [Function], [Function] ] },
  region: 'eu-central-1',
  logger: null,
  apiVersions: {},
  apiVersion: null,
  endpoint: undefined,
  httpOptions: { timeout: 120000 },
  maxRetries: undefined,
  maxRedirects: 10,
  paramValidation: true,
  sslEnabled: true,
  s3ForcePathStyle: false,
  s3BucketEndpoint: false,
  s3DisableBodySigning: true,
  computeChecksums: true,
  convertResponseTypes: true,
  correctClockSkew: false,
  customUserAgent: null,
  dynamoDbCrc32: true,
  systemClockOffset: 0,
  signatureVersion: null,
  signatureCache: true,
  retryDelayOptions: {},
  useAccelerateEndpoint: false }
```

Expected Result:

Config->Credentials should include the `secretAccessKey` 

Actual Result:

The Credentials do not show a `secretAccessKey`

This config is resulting in my getting an error: `UnrecognizedClientException: The security token included in the request is invalid.`.

Thanks in advance!

**Comment by chrisradek** [comment]
@lpender 
The `secretAccessKey` is set so that it doesn't show up when logging the credentials object (to prevent it from accidentally showing up in logs). However, you can still access the field and log it if you log that field directly. Can you confirm it exists when you log `AWS.config.credentials.secretAccessKey`?

The message makes it seem like a session token is needed as well. Are you using temporary credentials by chance?

**Comment by srchase** [comment]
Closing without further information to reproduce.
