### ISSUE TITLE
Doc for AWS.S3.ManagedUpload should mention Metadata parameter

### ISSUE THREAD

**Issue by mclaborn** [aws/aws-sdk-js#2160]
The documentation for AWS.S3.ManagedUpload should mention the Metadata parameter of the "params" hash in the constructor and also show an example.  Include a discussion of the key names.  Ref: https://stackoverflow.com/questions/51508320/aws-javascript-sdk-upload-object-with-metadata

**Comment by mclaborn** [comment]
Setting Metadata. I did find and follow the Tags example and it works as written. I did see Metadata mentioned on the s3.upload function but not on the AWS.S3.ManagedUpload object. Both places need to discuss the header names and the fact that the SDK adds the necessary prefix for you.

**Comment by fribourgpierre** [comment]
As far as I have been so far, by default AWS set:
'Content-Type' to 'application/octet-stream' when using AWS.S3.ManagedUpload
even using:

` const upload = new AWS.S3.ManagedUpload({
    params: {
      Bucket: event.bucketName,
      Key: event.key,
      Body: passtrough,
      Metadata: {
        'Content-Type': 'video/mp4'
      }
    },
    partSize: 1024 * 1024 * 64 // in bytes
  });`

it ends with the following Metadata:
'Content-Type' 'application/octet-stream'
'x-amz-meta-content-type' 'video/mp4'
