### ISSUE TITLE
s3.getObject in a for loop behaves inconsistently, sometimes returns duplicates of the data.

### ISSUE THREAD

**Issue by ANTGOMEZ** [aws/aws-sdk-js#2161]
In the code below the getObjects behaves inconsistently inside the `FOR` loop. Sometimes `content` array is populated with the expected 2 items, other times it is populated with multiple copies of the same item.

I need to have the exact available items for which I'm iterating over: 2.

New to this API, am I missing something or is this an issue?

`

     var params = { Bucket: "thebucket", Prefix: "theprefix/" }
     var content = [];

    async function getS3Data()
    {    
     
     var s3 = new aws.S3();
     var d;
     await s3.listObjects(params, async function (err, data) 
     {        
         if (err) throw err; // an error occurred
         else d = data;                                      
     }).promise();//listObjects

    var i;
    d.Contents.shift();    
    for (i = 0; i < d.Contents.length; i++)               
    {   
        var currentValue =  d.Contents[i];
        
        if(currentValue.Size>0) 
        {            
            var goParams = { Bucket: params.Bucket, Key: currentValue.Key };                   
            await s3.getObject(goParams, function(err, data) 
            {             
                if (err) throw err; //error     
                else                
                content.push({Size: data.ContentLength, Body: data.Body.toString()});  
            }).promise();        
        };        
    };
     }//getS3L

     async function doit()
     {
         await getS3Data();
    
         console.log(content);
     } 

     doit();
`

**Comment by AllanFly120** [comment]
Hi @ANTGOMEZ to make the SDK request, you can either supply a callback function or `await` a promise. Looks like you mixed the 2 ways in your code. Also, the `d`, that will be set asynchronously, is accessed in a synchronous way. You can do it like this:

```javascript
async function getS3Data() {
  var s3 = new aws.S3();
  var d;
  try {
      d = await s3.listObjectsV2(params).promise();
  } catch(e) {
      throw e // an error occurred
  }
  d.Contents.shift();
  var content = [];
  for (var currentValue of d.Contents) {
    if (currentValue.Size > 0) {
      var goParams = { Bucket: params.Bucket, Key: currentValue.Key };
      var data;
      try {
        data = s3.getObject(goParams).promise();
      } catch(e) {
        throw e; //error
      }
      content.push({Size: data.ContentLength, Body: data.Body.toString()});
    }
  }
  return content;
}
```
