### ISSUE TITLE
getSignedUrl fails the first time when using IAM role

### ISSUE THREAD

**Issue by zhiwei-nu** [aws/aws-sdk-js#2166]
I'm doing a very simple function to return signed urls of resources.

```
const officialS3 = new AWS.S3();

function getSignedUrl(s3Key) {
  return officialS3.getSignedUrl('getObject', {
    Bucket: S3_BUCKET,
    Key: s3Key,
  });
}
```
The very first call to this function will always return `s3.amazonaws.com`, which is the response when the instance has no access to the resource. Subsequent requests will succeed and return expected URLs until the IAM role rotates the keys, then it fails for one request again.

I suspect that somewhere the SDK aynchronously requests for the credentials required for the signing from the IAM role on the EC2 instance, but it doesn't wait for the credentials to return and thus fails to sign it.

**Comment by chrisradek** [comment]
@zhiwei-nu 
When you're using asynchronous credentials (which is the case when assuming a role), you must provide a callback to `getSignedUrl` to get the proper URL.

See [this comment](https://github.com/aws/aws-sdk-js/issues/2109#issuecomment-400386738) for more information.

**Comment by zhiwei-nu** [comment]
@chrisradek I see, thanks for the info! Could be worth having a warning for this scenario :)
