### ISSUE TITLE
When expires attribute is used in cloudFront api methods getSignedUrl/getSignedCookie - generated values are causing 403

### ISSUE THREAD

**Issue by Autushka** [aws/aws-sdk-js#2169]
Hello,

Using version 2.282.1. 

Just by chance found a difference in behavior of getSignedUrl/getSignedCookie methods of AWS.CloudFront.Signer depending on whether 'expires' options attribute or 'policy' options attribute is used.

According to sdk documentation you can use one or another [(SDK):](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront/Signer.html#getSignedUrl-property)
> expires (Number) — A Unix UTC timestamp indicating when the signature should expire. Required unless you pass in a full policy.
> policy (String) — A CloudFront JSON policy. Required unless you pass in a url and an expiry time.

Values generated by getSignedUrl/getSignedCookie methods when 'policy' attribute is used do allow access to the private content (Example 1) but in case of 'expires' attribute - attempt to access private content gives 403 (Example 2).

Example 1:
```
    var policyJson = {
        "Statement": [
            {
                "Resource":"http://***.cloudfront.net/*",
                "Condition":{
                    "DateLessThan":{"AWS:EpochTime": parseInt((new Date().getTime() + 60000 * 60 * 24 * 7)/1000)}
                }
            }
        ]
    };

    var policyString = JSON.stringify(policyJson);

    var signer = new AWS.CloudFront.Signer(keyPairId, privateKey);
    var options = {url: 'http://***.cloudfront.net/*', policy: policyString};

    var signedUrl = signer.getSignedUrl(options);
    var signedCookies = signer.getSignedCookie(options);
```

Example 2:
```
 var signer = new AWS.CloudFront.Signer(keyPairId, privateKey);
    var options = {url: 'http://****.cloudfront.net/*', expires: parseInt((new Date().getTime() + 60000 * 60 * 24 * 7)/1000)};

    var signedUrl = signer.getSignedUrl(options);
    var signedCookies = signer.getSignedCookie(options);
```

**Comment by srchase** [comment]
@Autushka 

I apologize we did not followup with you on this issue sooner.

Are you still seeing this behavior?  Using the latest version of the SDK, I am able to successfully use the expires option to create a signed URL or Cookie.

**Comment by zolaemil** [comment]
Using `2.532.0` I get the same problem as described by @Autushka in the initial post.

@srchase 
>Using the latest version of the SDK, I am able to successfully use the expires option to create a signed URL or Cookie.

Creating the signed cookie is not a problem, but using it to access a restricted resource is.

It may be that the problem is that CloudFront does not actually authorise the access based on the following cookies.
```
CloudFront-Expires
CloudFront-Signature
CloudFront-Key-Pair-Id
```
In which case, a possible fix would be to return the generated policy (`Policy: policy`) instead of `Expires` in https://github.com/aws/aws-sdk-js/blob/master/lib/cloudfront/signer.js#L35.

I've verified this fix, happy to send PR if it's welcome.

**Comment by trivikr** [comment]
@zolaemil Please create a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.

I'm locking this issue, as it's old and resolved.
