### ISSUE TITLE
Update an item in dynamodb ?

### ISSUE THREAD

**Issue by Yaswanth-C** [aws/aws-sdk-js#2170]
**My usecase :**

I am updating an item in Dynamodb based on primary key(ID) . Basically my record has 4 columns ( ID, description, name , price ) . So, i am triggering a lambda function to do that 

  

    console.log('starting function');
    
    
    var AWS = require("aws-sdk");
    
    var docClient = new AWS.DynamoDB.DocumentClient({region : 'xxxxxx'});
    
    var tablename = "Example";
    
    
    exports.handler = (event, context, callback) => {
        // TODO implement
      
        var params = {
     TableName: tablename,
     Key:{
     "ID": event.ID
     },
     UpdateExpression: "set description = :d, #na = :n , price = :p",
     ExpressionAttributeNames: {'#na' : 'name'},
     ExpressionAttributeValues:{
     ":d":event.description ,
     ":n":event.name ,
     ":p":event.price 
     },
     ReturnValues:"UPDATED_NEW"
    };
    console.log("Updating the item...");
    docClient.update(params, function(err, data) {
      if (err) 
       {
           callback(err)
           }
       else 
       {
           callback(null,data)
           };
    });
    };

The problem here is suppose when i have an item with key 123

    ID description name price
    
    123 Model      nokia  10

when i use above lamda function to update all the columns it is working fine.
But when i try to update only the `description` column it is throwing error that 'ExpressionAttributeValues can't be empty` . So for that i had did some thing like this 

    ExpressionAttributeValues:{
         ":d":event.description ? event.description : null ,
         ":n":event.name ? event.name : null,
         ":p":event.price ? event.price : null
         }

But the problem with this is it will update the only value that i had given .
Like if i had given only `description` to `modal1` then it will change that and give the result like this 

    ID description name price
        
    123 Model1  null  null

Which is right because that above snippet says to do that. 

**What i want to achieve ?**

How can i change that behaviour to acheive like this 

    ID description name price
        
    123 Model1     nokia  10
 
 1. Is there a way that it will
        update only the passed parameters and keep the others to its previous
        values ?

Please Bear with my above explanation.

Any help is appreciated

**Comment by srchase** [comment]
Hello @Yaswanth-C,
 
To update a single field, instead of updating the entire item, your ExpressionAttributeValues should only include the field to be updated.  The fields that are not being updated cannot be included as empty fields or set to null.
 
For example, if you just want to update the description, params will need to look like this:
 
```
params = {
  TableName: tablename,
   Key:{
     "ID": event.ID
   },
  UpdateExpression: "set description = :d”,
 ExpressionAttributeValues:{
    ":d":event.description
  },
  ReturnValues:"UPDATED_NEW"
}
```
 
If the fields to be updated can vary in your call to the Lambda function, you’ll need to dynamically generate params to include only the appropriate fields for the update call.
