### ISSUE TITLE
Release 2.286.1 was released even though CI build failed

### ISSUE THREAD

**Issue by sul4bh** [aws/aws-sdk-js#2173]
I see that this build failed: https://travis-ci.org/aws/aws-sdk-js/jobs/411465869

But 2.286.1 was released anyways. I am sure there was a good reason for doing so. I am concerned because I am getting the same error on my dev machine. Do you guys know what's up with that error?

```
clients/kinesis.d.ts(995,130): error TS2304: Cannot find name 'ResourceNotFoundException'.
clients/kinesis.d.ts(995,180): error TS2304: Cannot find name 'ResourceInUseException'.
clients/kinesis.d.ts(995,225): error TS2304: Cannot find name 'KMSDisabledException'.
clients/kinesis.d.ts(995,272): error TS2304: Cannot find name 'KMSInvalidStateException'.
clients/kinesis.d.ts(995,323): error TS2304: Cannot find name 'KMSAccessDeniedException'.
clients/kinesis.d.ts(995,370): error TS2304: Cannot find name 'KMSNotFoundException'.
clients/kinesis.d.ts(995,409): error TS2304: Cannot find name 'KMSOptInRequired'.
clients/kinesis.d.ts(995,450): error TS2304: Cannot find name 'KMSThrottlingException'.
clients/kinesis.d.ts(995,499): error TS2304: Cannot find name 'InternalFailureException'.
```

**Comment by chrisradek** [comment]
@sul4bh 
Sorry for that, some unused shapes made it into our generated typings, we're currently working on a short-term fix and will follow-up with something more long-term: #2174

**Comment by sul4bh** [comment]
Awesome. Thanks for the quick fix.

**Comment by chrisradek** [comment]
Version 2.286.2 has been released. Please upgrade, you should no longer see this error.
