### ISSUE TITLE
listAttachedUserPolicies ResourceNotFoundException

### ISSUE THREAD

**Issue by coolrz** [aws/aws-sdk-js#2178]
We have one lambda in role which has permission AMFullAccess,AdministratorAccess,AmazonSESFullAccess these AWS managed policy, but when run the lambda code, i got below issue. I am confused that the log tell me the resource not found, but when i search the same user in AWS console, it existed. Code is very sample, just give the param the username and call the IAM listAttachedUserPolicies API. Is there any query limitation in Lambda for this role/account, or role has no enough permission?
BTW, the same code/role in another account is ok. 

![log](https://user-images.githubusercontent.com/9249080/43766549-4fda3d36-9a65-11e8-88fc-ec84b1c57443.jpg)

![log2](https://user-images.githubusercontent.com/9249080/43766597-7547c106-9a65-11e8-8dec-073f2cd5f6d8.png)

![capture](https://user-images.githubusercontent.com/9249080/43766834-1732adb4-9a66-11e8-9302-7e09fc78df5a.PNG)

**Comment by srchase** [comment]
Hello @coolrz,

Thanks for reaching out.

When you say that "the same code/role another account is ok." are you referring to running this same code in another Lambda function?  Or are you executing it another way?

**Comment by coolrz** [comment]
it is not regarding AWS API issue, sorry for misunderstanding
