### ISSUE TITLE
How to create group in user pool with api?

### ISSUE THREAD

**Issue by andrew-aladev** [aws/aws-sdk-js#2180]
Hello. We can see a beautiful groups list in cognito.

![screenshot_2018-08-07_15-03-40](https://user-images.githubusercontent.com/941925/43774929-86f70b76-9a53-11e8-9ac9-96ac9a787c83.png)

Ok, we wants to create a new group with api. We've found only 1 suspicious method in docs:

![screenshot_2018-08-07_15-27-18](https://user-images.githubusercontent.com/941925/43775877-d0611a1a-9a56-11e8-8665-62b197b55b1f.png)

The problem is that method belongs to `CognitoIdentityServiceProvider`. `CognitoIdentityServiceProvider` itself depends on `CognitoIdentityCredentials` and `CognitoIdentityCredentials` depends on 2 fields.

> // either IdentityPoolId or IdentityId is required
> // See the IdentityPoolId param for AWS.CognitoIdentity.getID (linked below)
> // See the IdentityId param for AWS.CognitoIdentity.getCredentialsForIdentity
> // or AWS.CognitoIdentity.getOpenIdToken (linked below)

We don't have any identity pools, we didn't want even to listen about it, but it looks like we should.

I have 3 questions:

1. Why there is no user friendly way (like `CognitoServiceProvider`) to work with user pools without identity pools?
2. We can create identity pool associated with single (target) user pool and try to create group in target user pool with IdentityPoolId and userPoolId. Will it give any result?
3. What is `IdentityId` and how to use it in terms of user pool. Why it is not documented? We can burn dozens of hours in this abstraction hell.

**Comment by srchase** [comment]
Hello @andrew-aladev,

The CognitoIdentityServiceProvider supports creating a group and you do not need an IdentityPool or the associated IDs.

Per the documentation linked below, only the GroupName and UserPoolId are required to call createGroup.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#createGroup-property

Closing this issue. If you have further questions, please refer to the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=148).
