### ISSUE TITLE
TypeError: AWS.SageMakerRuntime is not a constructor

### ISSUE THREAD

**Issue by surajpotnuru** [aws/aws-sdk-js#2182]
Hi,

I am using AWS Javascript SDK Version 2.287.  I am trying to invoke a SageMaker Endpoint using the AWS.SageMakerRuntime().invokeEndpoint() in the below way.

1. I configured AWS Cognito using an identity pool.
AWS.config.region = 'us-east-1'; // Region
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'MY-POOL-ID',
});
2. var sagemakerRuntime = new AWS.SageMakerRuntime({
    apiVersion: "2017-05-13"
});

When 2nd statement is running, I am getting an error:
**Uncaught TypeError: AWS.SageMakerRuntime is not a constructor**

Can some one help me with what I am doing wrong?

**Comment by surajpotnuru** [comment]
![image](https://user-images.githubusercontent.com/12714084/43791180-751a165c-9a92-11e8-8d62-8d3f9854152c.png)

**Comment by morenoh149** [comment]
I have the same error

**Comment by klaytaybai** [comment]
@morenoh149, what version of the SDK are you using?

**Comment by morenoh149** [comment]
actually I think it 's because the default bundle doesn't have Sagemaker. https://github.com/aws/aws-sdk-js#in-the-browser

you need to make a bundle that has Sagemaker in one of these ways https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html
