### ISSUE TITLE
Doesn't respect environment variable `AWS_SHARED_CREDENTIALS_FILE`

### ISSUE THREAD

**Issue by mclark-newvistas** [aws/aws-sdk-js#2188]
## What happened:

Ran JS code with AWS SDK - it failed to authenticate:

```
2018-08-06T18:57:24:michael@mclark-dev:/m/n/project$ node .
ensureTable error: { Error: connect ENETUNREACH 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  message: 'Missing credentials in config',
  errno: 'ENETUNREACH',
  code: 'CredentialsError',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2018-08-07T01:09:17.854Z,
  originalError:
   { message: 'Could not load credentials from any providers',
     errno: 'ENETUNREACH',
     code: 'CredentialsError',
     syscall: 'connect',
     address: '169.254.169.254',
     port: 80,
     time: 2018-08-07T01:09:17.854Z,
     originalError:
      { errno: 'ENETUNREACH',
        code: 'ENETUNREACH',
        syscall: 'connect',
        address: '169.254.169.254',
        port: 80,
        message: 'connect ENETUNREACH 169.254.169.254:80' } } }
```

After `ln -s ~/.config/aws ~/.aws` it worked fine.

## What I expected:

The SDK would find the credentials file using the `AWS_SHARED_CREDENTIALS_FILE` environment variable, just like the `aws` command line application.

## Other Information

* `aws-sdk` version: `aws-sdk@2.286.2`
* `aws` cli version: `aws-cli/1.15.68 Python/3.7.0 Linux/4.14.55-1-lts botocore/1.10.67`
* `aws-sdk` _does_ respect `AWS_PROFILE`, so there is some basis to expect it to support `AWS_SHARED_CREDENTIALS_FILE`

**Comment by chrisradek** [comment]
@mclark-newvistas 
Can you try setting `AWS_SDK_LOAD_CONFIG` to 1 as well? I believe when we added support for `AWS_SHARED_CREDENTIALS_FILE`, we only made it accessible behind the `AWS_SDK_LOAD_CONFIG` flag so that existing applications didn't start unexpectedly reading this value. This is something we plan to change when we do a major version bump so our credential/config loading matches the CLI.

**Comment by mclark-newvistas** [comment]
Yep, that does it. Thank you. Where did I miss this documented?

**Comment by mclark-newvistas** [comment]
Hmm - though I'm not specifically trying to load the config - just the credentials file. Doesn't hurt me in this case since I only have a region in the config and I specify the desired region in my code, but the environment variable appears to accomplish my objective via a side-effect :S.

**Comment by srchase** [comment]
Currently, it's only documented explicitly in regards to setting the region:  https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html, so you didn't miss anything.  I've flagged this as something that could be improved on the documentation.

**Comment by mclark-newvistas** [comment]
Fair enough, I look forward to the next major version bump, and the doc update :).

**Comment by ArnfinnA** [comment]
Hello.

Sorry for all the waiting for you right now. But I’m trying not to get stuffed with all the blame for all of the things for the shit that has been. bought at Amazon, Goggle, Apple, Adobe and Microsoft. So I’m using my time to try to cancel all of my accounts that I have. Not so easy for I’m in  Norway 🇳🇴 and all of the support is in a different country. ☹️ 
But I have a question for all of you. That I’m trying to get my Aws account  back, but I don’t think 🤔, know that Amazon has approved this? I have to be sure about that before I start up my account again. 
 But it would have been nice 👍 to talk with you about everything actually 😉👌 if you got time for it? Think 🤔 about it then you can contact me.

 Best regards Arnfinn Aursoey 🇳🇴
