### ISSUE TITLE
Accessing the next sequence token from cloudwatch logs in a structured way.

### ISSUE THREAD

**Issue by seanirby** [aws/aws-sdk-js#2190]
We are using cloudwatch logs in a distributed application and it will be relying on the PutLogEvents API to publish error messages.  If my call to 'putLogEvents' fails because my sequence token was wrong then it would be nice if the library provided it in a structured way in the callback so I could retry the call again.  I see that it's provided in the error message:

```
Error: The given batch of log events has already been accepted. The next batch can be sent with sequenceToken: 49585678206974203352194957394759596517722131379957907170
```

I don't want to parse the error message for the token.  Also, I understand that 'DescribeLogStreams' can give me the correct sequence token but that would be another network call I'd like to avoid.

Is there any way the sequence token could be provided in the callback?  Would you be willing to add this support, or accept a pull request for this support?

**Comment by seanirby** [comment]
Thanks for taking a look!

**Comment by srchase** [comment]
Hello @seanirby,
 
We appreciate your interest in submitting a pull request.   At this time, we’re not able to accept a customization to provide the structured errors for this specific case.
 
Instead, this is something we’re considering as part of a larger effort to support structured errors across the SDK and is something that would potentially be included in a future major version release.

**Comment by srchase** [comment]
As this is a known limitation and is actively being considered for a a future major release, I'm going to close out this issue.  Thanks for submitting this originally.
