### ISSUE TITLE
Using Angular6 - aws-sdk/clients/cognitoidentity has no exported member 'String' 

### ISSUE THREAD

**Issue by crjacinro** [aws/aws-sdk-js#2192]
A solution is available but it seems wrong to modify generated node_modules files by the developers. 

https://stackoverflow.com/questions/51770885/aws-sdk-clients-cognitoidentity-has-no-exported-member-string

**Comment by srchase** [comment]
Since this is being tracked as a bug on the Amplify repository, I'm going to close out this issue.
