### ISSUE TITLE
API Gateway Authorizer policy object losing attributes on return parse

### ISSUE THREAD

**Issue by d1sco** [aws/aws-sdk-js#2195]
AWS expects the output of a policy object to look like this 

```

{
  "principalId": "user",
  "policyDocument": {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Action": "execute-api:Invoke",
        "Effect": "Deny",
        "Resource": "arn:aws:execute-api:us-west-2:123456789012:ymy8tbxw7b/*/GET/"
      }
    ]
  }
}
```
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-output.html

instead my policy object is returned like this 

```
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Action": "execute-api:Invoke",
        "Effect": "Deny",
        "Resource": "arn:aws:execute-api:us-west-2:123456789012:ymy8tbxw7b/*/GET/"
      }
    ]
  }

```

my generatePolicy return is formatted exactly like the desired object, when I test my custom authorizer over API Gateway -> Authorizers -> test , i even get the correct policy object BEFORE body parse, after body parse is when i lose my outer object with PrincipalId and PolicyDocument attributes

My Authorizers generatePolicy function

```
const generatePolicy = (principalId, effect, resource) => {
  return {
    principalId: principalId,
    policyDocument: {
      Version: '2012-10-17',
      Statement: [
        {
          Action: 'execute-api:Invoke',
          Effect: effect,
          Resource: resource
        }
      ]
    },
//optional context
    Context: {
      stringKey: "value",
      numberKey: "1",
      booleanKey: "true"
    }
  }
```

In my protected endpoint the authroizer object never comes through with proxy under `event.contextRequest.authorizer` and in mapping template its not anywhere under context/request :/

I did read somewhere that the policy object will not get passed if it is not formatted correct

**Comment by srchase** [comment]
Hello @d1sco,

The API Gateway service handles the parsing the authorizer policy object.  That isn't done by the SDK itself.

I'm going to refer you over to the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).  They'll be best suited to help you understand why these attributes are being lost.

**Comment by d1sco** [comment]
Just to help anyone else stuck in this situation.

Invoking the lambda over testing showed the proper result, invoking the Authorizer over API Gateway > Testing shows the response after body parse.

If you getting successful body parse over Authorizer testing you are good. I was acting paranoid, my API Gateway Authorizer is working great and allowing me to Authenticate and Authorizer my users no issues!

Hope this helps someone else
