### ISSUE TITLE
Getting the URL with extension in s3.getSignedUrl('getObject'

### ISSUE THREAD

**Issue by olahivepriyanka** [aws/aws-sdk-js#2200]
Is there any method to get the extension of the file in getSignedUrl. 

var params = {Bucket:'your-bucket-name on s3', Key: 'key-name-on s3 you want to store under', Expires: 20}
s3.getSignedUrl('getObject', params, function (err, url) {
console.log('Signed URL: ' + url);
});

Here params will be only Bucket and Key

If my key is 1531994728558.mp3 
my signed url will be like https://scgallery.s3.ap-south-1.amazonaws.com/artistgallery/1531994728558.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F20180815%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20180815T083839Z&X-Amz-Expires=900&X-Amz-Signature=67b4c6ac7ceb5f414e912b2010e8419707d5371b83fdc62d6&X-Amz-SignedHeaders=host

My media player is expecting file of **.mp3** extension , is there any way to do this?

Thanks in advance

**Comment by srchase** [comment]
Hello @olahivepriyanka,

Has the ContentType been properly set on the object?

You can use [headObject](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html) to get the metadata, including ContentType, of an object without retrieving the object itself.

**Comment by olahivepriyanka** [comment]
Im sorry for the late response , my question is how to generate a SignedURL with extension?

now my signed url is coming like this  [](https://scgallery.s3.ap-south-1.amazonaws.com/artistgallery/1531994728558.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F20180815%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20180815T083839Z&X-Amz-Expires=900&X-Amz-Signature=67b4c6ac7ceb5f414e912b2010e8419707d5371b83fdc62d6&X-Amz-SignedHeaders=host)

i want something like this
[]( https://scgallery.s3.ap-south-1.amazonaws.com/artistgallery/1531994728558.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F20180815%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20180815T083839Z&X-Amz-Expires=900&X-Amz-Signature=67b4c6ac7ceb5f414e912b2010e8419707d5371b83fdc62d6&X-Amz-SignedHeaders=host.mp3)

At the end i need extension of the file

**Comment by srchase** [comment]
The signed URL does include the file-extension.

The extension is just prior to the "?", where the key is used as the final part of the path, in this case as "1531994728558.mp3".  The extension is not one of the query params and would not be added onto the "X-Amz-SignedHeaders" value of "host" at the end of the full SignedURL.

I'm not sure what media player you're using, but you may want to check their documentation to understand how URLs with query params need to be handled.

**Comment by AllanFly120** [comment]
Hi @olahivepriyanka, when you upload the file, if you set the content-type properly(like 'audio/mpeg'), the (browser)download file will have the `.mp3` extension, no need to change the presigned url.
