### ISSUE TITLE
ListUsers Not returning attributes if AttributesToGet is Empty array 

### ISSUE THREAD

**Issue by sgil-carecloud** [aws/aws-sdk-js#2203]
As per the documentation in https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-manage-user-accounts.html

The following example returns all users and includes all attributes.

{
    "AttributesToGet": [],
    "Filter": "",
    "Limit": 10,
    "UserPoolId": "us-east-1_samplepool"
}

but it is not returning the attributes

**Comment by srchase** [comment]
Hello @sgil-carecloud,

Which version of the SDK are you using?

Can you provide the code you are using?

**Comment by srchase** [comment]
@sgil-carecloud 

Closing as inactive.  Feel free to respond if you have additional details.

**Comment by jomicega** [comment]
this problem pass but the attribute "AttributesToGet" is empty, remember that should have between 1 and 30, if likes get all Attributes dont write this attribute.

**Comment by trivikr** [comment]
Locking this thread as the issue is old. Please open a new issue for related bugs and link to relevant comments in this thread.
