### ISSUE TITLE
elbv2 listener RedirectConfig bug

### ISSUE THREAD

**Issue by Grimml** [aws/aws-sdk-js#2204]
I am trying to configure a listener for a LoadBalancer which redirects HTTP to HTTPS. 
When i use: 
```
var elbv2 = new AWS.ELBv2();
var params = {
                DefaultActions: [{
                    Type: "redirect",
                    Order: 1,
                    RedirectConfig: {
                        StatusCode: "HTTP_301",
                        Host: '#{host}',
                        Path: '/#{path}',
                        Port: 443,
                        Protocol: 'HTTPS',
                        Query: '#{query}'
                    }
                }],
                LoadBalancerArn: 'someARN',
                Port: 80,
                Protocol: "HTTP"
            };
 elbv2.createListener(params, function(err, data) {
                if (err) console.log(err, err.stack); // an error occurred
                else console.log(data); // successful response
            });
```
I get an exception 

> '{ UnexpectedParameter: Unexpected key 'RedirectConfig' found in params.DefaultActions[0]'

if i don't set the RedirectConfig i get the following exception 

> '{ InvalidLoadBalancerAction: For actions of type 'redirect', you must specify the following fields: 'RedirectConfig''

**Comment by srchase** [comment]
Hello @Grimml,

Which version of the SDK are you using?  Are you using Node.js (which version?) or running this somewhere else?

**Comment by Grimml** [comment]
Hi,

I am using it in a LambdaFunction with Node.js 8.10. i tried specifying the api version but it did not fix anything.

**Comment by srchase** [comment]
Executing the code you've provided, I get an error that the Port needs to be a string:
>InvalidParameterType: Expected params.DefaultActions[0].RedirectConfig.Port to be a string

Fixing that, I'm able to create a listener successfully.

Is there some other part of your code that could be involved?  Anything with the execution role?

Are you able to run this outside of Lambda successfully?

**Comment by Grimml** [comment]
I just ran it now on Lambda again (the exact same code as yesterday) and it worked fine, I also got 

> InvalidParameterType: Expected params.DefaultActions[0].RedirectConfig.Port to be a string

which I quickly changed. 
I guess this is resolved, though I still wonder why it didn't work yesterday.

**Comment by srchase** [comment]
Glad to hear it's working for you.

I'll hold this issue open for a few days before closing it in case you're able to find a consistent way to reproduce the errors.
