### ISSUE TITLE
S3 - headBucket does not return the same amount of error information as other commands

### ISSUE THREAD

**Issue by dougmoscrop** [aws/aws-sdk-js#2219]
I was using `headBucket` to determine if a bucket exists as part of a larger workflow. Sometimes a user may have expired credentials, and the easiest way for them to know this (among other things) is I forward the err.message up to the command line.

Consider this:

```js
const aws = require('aws-sdk');
const s3 = new aws.S3();
s3.listObjects({ Bucket: 'some-bucket-name' })
    .promise()
    .then(res => console.log(res))
    .catch(e => console.error(e));
```
If my token is expired I get something like this:

```js
{
  message: 'The provided token has expired.',
  code: 'ExpiredToken',
  region: null,
  time: 2018-08-22T23:34:20.523Z,
  requestId: 'F041E533A52C538C',
  extendedRequestId: 'SFnWwWp3N+08j8lMK/yVsPR2uSc8ih0gasuPrdizXe7tFBl9wIHMNRMxV4Jmhok30NO3LTiN9Gc=',
  cfId: undefined,
  statusCode: 400,
  retryable: true }
```

Also as an aside, I am not sure expired credentials are `retryable: true`. I mean, yes, they are, if you take some other action, but what happens is any kind of retry logic usually spins for a few seconds as it sees `true`, backs off, retries.. fails again, backs off even more.. and so on. So, actually most of the time you can detect expired credentials because the program looks like it's hung ;)

Anyway, if I change the above code to use `headBucket` instead of `listBucket`, you get:

```js
{
  message: null,
  code: 'BadRequest',
  region: 'us-east-1',
  time: 2018-08-22T23:36:07.277Z,
  requestId: '2A6F9C7E8789E4FD',
  extendedRequestId: '6AsnqFezFvNRemA2Nfn5o3d4YVV84yERGD6GpE7Ug/IchmtPmhfrxKSCHK580KkEDlcsB+JAoBY=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 35.838740500478664
}
```

Is there a reason that headBucket omits the error message?

**Comment by srchase** [comment]
hello @dougmoscrop,

Thanks for pointing out this inconsistency.  Unfortunately, this message is being left out by the underlying call to the s3 service.  You'll get the same inconsistency if you were to use a different SDK or the CLI.

We've reached out to the service team to see if we can get this resolved.

**Comment by srchase** [comment]
Hello again,

I have not received a response from the service team.  Since this cannot be resolved via the SDK, I'd encourage you to open a question on the [AWS S3 Forum](https://forums.aws.amazon.com/forum.jspa?forumID=24).

I'm going to close this issue.  If you do open a request on the forums, let us know and we can pass along the link to the service team with our original request.
