### ISSUE TITLE
Missing eventSourceARN Attribute in DynamoDBStreams declaration file

### ISSUE THREAD

**Issue by sdrioux** [aws/aws-sdk-js#2226]
https://github.com/aws/aws-sdk-js/blob/master/clients/dynamodbstreams.d.ts#L215

In an event from a DynamoDB Stream, I would expect to have an `eventSourceArn` attribute on a Record, in addition to the `eventSource`.  However, in the `DynamoDBStreams.Record` interface, eventSourceArn seems to be missing?

**Comment by srchase** [comment]
@sdrioux 

The eventSourceArn is not provided by the underlying service (as documented [here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_GetRecords.html)).

We will pass along the request to have it added, and you could make the same request on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=131).

**Comment by sdrioux** [comment]
Aha, thank you!  That makes more sense.  I was using the definitions in a lambda that was reading off the stream.  It seems a little odd that when a lambda reads off the stream, the eventSourceArn is present, however, when reading the stream from the CLI it is missing.

**Comment by srchase** [comment]
@sdrioux 

Unfortunately, these are not perfectly consistent inside and outside of Lambda.

We've passed along the feedback to have it added.  You're welcome to submit that feedback to the DynamoDB service directly.

As there isn't an issue with the SDK itself, I'm going to close out this issue.  Thanks for your understanding.
