### ISSUE TITLE
bluebird with aws-sdk: Cannot promisify an API that has normal methods with 'Async'-suffix

### ISSUE THREAD

**Issue by IronSourceFusionUI** [aws/aws-sdk-js#2229]
Seems there is a bug when working with bluebird@3.5.1 and aws-sdk@2.305.0
`const bluebird = require('bluebird');`
`const AWS = require('aws-sdk');`
`const AWSSQS = new AWS.SQS();`
`bluebird.promisifyAll(AWSSQS);`

trigger an error: `TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix`
See http://goo.gl/MqrFmX

the problem probably because you added function with 'Async'  suffix.

**Comment by jasonfutch** [comment]
We had same issue.. the root cause of the issue has to do with dynasty package not locking into one version ^ of aws-sdk.

Also AWS-SDK team should of never changed a callback to a promise in a minor release as this is a breaking change.

**Comment by felipefcm** [comment]
From `http://bluebirdjs.com/docs/api/promise.promisifyall.html`:

> If a method name already has an "Async"-suffix, it will be duplicated. E.g. getAsync's promisified name is getAsyncAsync.

Apparently Bluebird changed this behaviour, and throws an exception now.

**Comment by kbariotis** [comment]
The same happened to us. Could that be the reason for it https://github.com/aws/aws-sdk-js/commit/fe88308a8699b39aef06492c898b265a3a24251f#diff-cca1065697cbb567e3320496b1f7448fR43? That's hilarious.

**Comment by chrisradek** [comment]
@DanielSuperSonic 
It shouldn't be necessary to promisify the SDK. If promises are available in your environment, any operation can return a promise by calling the `promise()` method on the operation's return value:

```javascript
// with callbacks
sqs.listQueues(function(err, data) {});

// using .promise
sqs.listQueues().promise();
```

If you specifically want to use the bluebird implementation of promises, you can [configure](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/using-promises.html#w2aac19c17c14c17) the SDK to use that instead:
```javascript
AWS.config.setPromiseDependency(require('bluebird'));
```

@jasonfutch 
You can still use callbacks with the SDK. To avoid making a breaking change, we only return promises on operations if you explicitly call the `promise()` method on the operation's return value.

**Comment by kbariotis** [comment]
@chrisradek we happen to have some legacy code that we don't want to update just yet. I haven't been working with the SDK for some time but I thought that a promise() property was the pattern to return a promise, not an Asynchronous suffixed function.

Anyway, this incident was so random Boone could have saw it coming. :)

**Comment by ronjouch** [comment]
@chrisradek regarding https://github.com/aws/aws-sdk-js/issues/2229#issuecomment-417386675 :

> It shouldn't be necessary to promisify the SDK. If promises are available in your environment, any operation can return a promise by calling the `promise()` method on the operation's return value:
> 
> ```js
> // with callbacks
> sqs.listQueues(function(err, data) {});
>
> // using .promise
> sqs.listQueues().promise();
> ```

I initially liked that path, but after move a chunk of existing code to using `.promise()`, I'm going to stay with Bluebird, only replacing `promisifyAll` with specific `promisify` calls (thus avoiding collisions when/if AWS introduces new `foo`/`fooAsync` APIs like done in https://github.com/aws/aws-sdk-js/commit/fe88308a8699b39aef06492c898b265a3a24251f with `on`/`onAsync`). Promisifying callback-based APIs is a pattern I'm okay with, and AWS `promise()` sounds neat, but makes mocking a bit more painful and a lot more ugly:

```js
// stubbing a promisified DynamoDB.DocumentClient
sinon.stub(dynamo.documentClient, 'putAsync')
     .resolves({ Attributes: response });

// stubbing a DynamoDB.DocumentClient using promise()
sinon.stub(dynamo.documentClient, 'put')
     .returns({ promise: () => (new Promise(resolve => (resolve({ Attributes: response })))) });
```

**Comment by mflores-verys** [comment]
@jasonfutch when did that change occur, do you know?

**Comment by jasonfutch** [comment]
It happened Wednesday about 4pm EST, it was with release 3.305.0

**Comment by ebrearley** [comment]
Thanks @jasonfutch. Moving back and pegging `aws-sdk-js` to version `2.304.0` is the perfect workaround for now.

**Comment by Palisand** [comment]
What's wrong with using the latest version of the sdk and using a different suffix?
```
bluebird.promisifyAll(AWSSQS, {suffix: 'Promise'})
```

**Comment by ankon** [comment]
> What's wrong with using the latest version of the sdk and a different suffix?

This would require existing code (using ...Async until now) to be modified, which clearly should not be the intent of a patch semver release.

**Comment by nghiadhd** [comment]
We can change suffix while doing promisifyAll
`Promise.promisifyAll(
    Object target,
    [Object {
        suffix: String="Async",
        multiArgs: boolean=false,
        filter: boolean function(String name, function func, Object target, boolean passesDefaultFilter),
        promisifier: function(function originalFunction, function defaultPromisifier)
    } options]
) -> Object`
http://bluebirdjs.com/docs/api/promise.promisifyall.html

I changed to 'Async2' and it works well

**Comment by chrisgarber** [comment]
I know this is the dumbest solution, but we're just going to

```javascript
delete Object.getPrototypeOf(Object.getPrototypeOf(Object.getPrototypeOf(AWSSQS)))['onAsync'];
```

for now, and either wait for the sdk to work with promises natively, or migrate to using the `.promise()` syntax as we can.

**Comment by benw25** [comment]
> Does anyone know if there's an option to disable the newer "exception on existing async method" "feature" in bluebird or else configure it to ignore routines for which there is an existing async version?

Bluebird promisifyAll has an option filter (http://bluebirdjs.com/docs/api/promise.promisifyall.html#option-filter) that you can pass in.

`const  s3 = Promise.promisifyAll(new AWS.S3(), options);`

Using this, you can set options to filter out any name that already ends with Async

```
const s3 = Promise.promisifyAll(new AWS.S3(),
   { filter: (name) => { return !_.endsWith(name, 'Async') }
);
```

Two things to be careful of:

1. The filter will replace the default filter.  Straight from the source code:

```
if (typeof filter !== "function") filter = defaultFilter;

...

var defaultFilter = function(name, func) {
    return util.isIdentifier(name) &&
        name.charAt(0) !== "_" &&
        !util.isClass(func);
};
```

2. You must ensure that the behavior of the new functions added by AWS-SDK (or whatever you're promisifying) have the exact same behavior, e.g. `getObject` -> promisified -> `getObjectAsync` has the same behavior as aws-sdk's `getObjectAsync`

**Comment by RanVaknin** [comment]
Hi Everyone,

Im not sure what is the use case for Bluebird in here. Native promises have been available on Node.js for years now. 
Since there are multiple workarounds on this thread, and the functionality is natively supported there is no plan to fix this.

Apologies for the inconvenience,
Ran~
