### ISSUE TITLE
Batch TooManyRequestsException is not retried as a throttling exception

### ISSUE THREAD

**Issue by cdraper-CS** [aws/aws-sdk-js#2233]
This problem reported and fixed for the Ruby SDK:

https://github.com/aws/aws-sdk-ruby/issues/1522

is still a problem with the Javascript SDK. When Batch throttles, it returns a 429 with error TooManyRequestsException. The SDK treats this as a fatal error and not one that should be retried with backoff.

https://github.com/aws/aws-sdk-js/blob/master/lib/service.js#L573-L583

**Comment by AllanFly120** [comment]
Hi @cdraper-CS 

Thank you for bringing this up, we will add the feature to align with other AWS SDKs.

**Comment by srchase** [comment]
Closing as this has been implemented.
