### ISSUE TITLE
Type definitions from `lib/config.d.ts` not available to consumers

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-sdk-js#2234]
I'm trying to implement proxy support for our program that uses the JS SDK, according to this:

https://aws.amazon.com/blogs/developer/using-the-aws-sdk-for-javascript-from-behind-a-proxy/

I'm trying to save the `httpOptions` configuration in my program, to come up with a program like so:

```ts
import AWS = require('aws-sdk');

class SDK {
    private readonly httpOptions?: ????;  // What's the declared type here?

    constructor() {
        if (process.env.https_proxy) {
            this.httpOptions = {
                agent: // ... proxy agent here
            }
        }
    }

    public makeClient() {
        return AWS.EC2(..., {
            ...,
            httpOptions: this.httpOptions,
        });
    }
}
```

However, I can't type the `this.httpOptions` properly. Althought `HTTPOptions` is declared in `lib/config.d.ts`, there's no way for me to access that type declaration, because `index.d.ts` prohibits me from getting to it:

```ts
// index.d.ts
import {GlobalConfigInstance} from './lib/config';

export * from './lib/core';
export * from './clients/all';
export var config: GlobalConfigInstance

export as namespace AWS;
```

As you can see, `lib/config` is never exposed so I cannot properly type my field. 

Yes, I know I can bypass the type checker and that's what I'm going to do to make this work, but it doesn't make for a nice experience. Please expose these types.

**Comment by AllanFly120** [comment]
Hey @rix0rrr  
I'm not sure I understand your request. Can you import the `httpOptions` inferface like this?
```typescript
import AWS = require('aws-sdk');
import {HTTPOptions, ConfigurationOptions} from 'aws-sdk/lib/config';
const httpOptions: HTTPOptions = {
  timeout: 6000
}
const config: ConfigurationOptions = {
  region: 'us-west-2',
  httpOptions
}
const s3 = new AWS.S3(config);
```

**Comment by chrisradek** [comment]
@rix0rrr 
Agreed we should expose httpOptions directly.

As a workaround, instead of importing from `aws-sdk/lib/config`, you can set the type like this:

```typescript
import * as AWS from 'aws-sdk';

const httpOptions: AWS.Config['httpOptions'] = {
    timeout: 6000
}
```
