### ISSUE TITLE
Signed CloudFront URLs Returning Malformed (MalformedPolicy)

### ISSUE THREAD

**Issue by davidadas** [aws/aws-sdk-js#2236]
I've been attempting to get signed image URLs from CloudFront as of late but I'm getting an error whenever I run the close equivalent of:
```ts
import { CloudFront } from "aws-sdk";
import { readFileSync } from "fs";
import { promisify } from "util";

const cfPrivateKey = readFileSync(`/path/to/cloudfront.pem`).toString("ascii");
const cfKeyPairId = process.env.CLOUDFRONT_KEYPAIR_ID;

if (!cfKeyPairId) throw new Error("No CloudFront Keypair ID Provided.");

export const getSignedCloudFrontUrl = async (s3Path: string): Promise<string> => {
    const signer = new CloudFront.Signer(cfKeyPairId, cfPrivateKey);
    const getSignedUrl = promisify(signer.getSignedUrl).bind(signer);

    const cfQuery = {
        url: s3Path,
        expires: Date.now() + 30000,
    };

    return getSignedUrl(cfQuery);
};

getSignedCloudFrontUrl("https://host.example.com/user-photos/1234/companyLogo/companyLogo.jpeg")
    .then(console.log)
    .catch(console.error);
```

The URL is generated correctly but requesting the resource I get:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>MalformedPolicy</Code>
    <Message>Malformed Policy</Message>
</Error>
```

Not sure if this is an error in AWS, a user error in my code, or a bug in the `aws-sdk`.  No `policy` is provided to get `getSignedUrl` though, which leads me to think it's a bug in the way the signed URL is being generated.

Any insights?

**Comment by srchase** [comment]
@davidadas 

Also, have you tried to use the AWS CLI to get the same signed URL?

**Comment by davidadas** [comment]
@srchase I'm using version `2.282.1`.  And yes, we did try with the AWS CLI and it created the URL correctly.

**Comment by davidadas** [comment]
@srchase sure will try!  Thanks!

**Comment by srchase** [comment]
@davidadas 

I'm going to close out this issue.  If that doesn't do the trick, let us know and we can re-open.

**Comment by davidadas** [comment]
@srchase apologies for the delay.  I tried again and got the same error :( .

**Comment by srchase** [comment]
Hi @davidadas,

Are you still getting a malformed policy error?  Or a 403? Or a different error?

In your code, are you using the CloudFront distribution url?  Or the url of the actual s3 bucket?

```
const AWS = require("aws-sdk");
const fs = require("fs");
const key = fs.readFileSync('./cloudFrontPrivateKey.pem').toString("ascii");
const id = 'cloudFrontAccessKeyId';
const signer = new AWS.CloudFront.Signer(id, key);

const params = {
  url: 'https://myDistribution.cloudfront.net/foobar.jpeg',
  expires: 1538999532,
};

signer.getSignedUrl(params, function (err, data) {
  if(err) { console.log(err) }
  console.log(data);
});
```

The url I get from something like this is working for me.

**Comment by davidadas** [comment]
@srchase no, I'm now getting a 403.  Methinks this is a configuration error now.  

Any recommendations?

**Comment by srchase** [comment]
Yes, Restrict Viewer Access is set to "Yes" and I've set Trusted Signers to "self" with a CloudFront key pair setup on the "My Security Credentials" page.

**Comment by davidadas** [comment]
Okay, that fixed it @srchase!  Thanks a bunch!  Closing out this issue.
