### ISSUE TITLE
Why are all the services not available? Rekognition etc

### ISSUE THREAD

**Issue by elliotthill** [aws/aws-sdk-js#2238]
Why bundle up an SDK but only provide a fraction of the services in it?

To gain access to all the services we need to build from source - how is this a good idea? Now we can't use our dependency managers and have to manually require it.

**Comment by elliotthill** [comment]
Also when I do require the aws-sdk I build from source, I get this error:

```
ReferenceError: AWS is not defined
    at Object.<anonymous> (/my/path/aws-sdk.js:12302:1)
```

Very frustrating

**Comment by srchase** [comment]
@elliotthill 

When building the SDK, you can use the 'all' parameter to include every service:

```node dist-tools/browser-builder.js all > aws-sdk-full.js```

By default, only select services are included to keep the package size down.

Similarly, you could use Webpack and only import the individual services you need, which will also help to minimize the package size.  Documentation can be found here: [Bundling with Webpack](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/webpack.html)

**Comment by chrisradek** [comment]
@elliotthill 
To build on what @srchase said, the browser bundle only includes services that we know support CORS. This helps keep the total bundle size small as it excludes services that likely don't work in the majority of browsers.

Sometimes a service adds CORS support and we don't know about it, or a browser bundle is needed for an environment that doesn't enforce CORS, and that's when you would need to import the service client directly, or build a custom version of the browser SDK, as srchase pointed out.

**Comment by elliotthill** [comment]
I'm only concerned with back end environment. It is a node package after all, node doesn't run within a browser.

I've built the new source with the above instructions but still getting:

`TypeError: AWS.Rekognition is not a constructor`

Can you spell out exactly what I need to do to get this to work please. I've tried overwriting the aws-sdk with aws-sdk-all within /dist and still the above error.

**Comment by chrisradek** [comment]
@elliotthill 
Can you share how you're importing the SDK and instantiating Rekognition?

Here's an example that will print collections in your account:
```javascript
const AWS = require('aws-sdk');

const rekognition = new AWS.Rekognition({
    region: 'us-west-2'
});

rekognition.listCollections(console.log);
```

**Comment by elliotthill** [comment]
That code returns:

`TypeError: AWS.Rekognition is not a constructor`

My aws-sdk was installed with npm install and I've run the above instructions to build all services into aws-sdk-full.

Interestingly my aws-sdk-full has no references at all within it to 'rekognition'. Its obviously not packing that into it.

**Comment by srchase** [comment]
If you're installing with NPM, you won't need to do any of the build steps.

Could you try an ```npm install aws-sdk``` in a fresh directory?

**Comment by elliotthill** [comment]
I uninstalled and reinstalled. Its working now.

Interesting the version now is 2.309.0 but before it was 2.6.7 WTF?

**Comment by elliotthill** [comment]
How did I end up with version 2.6.7 when that doesn't even exist?
https://www.npmjs.com/package/aws-sdk

**Comment by srchase** [comment]
2.6.7 does exist: [https://www.npmjs.com/package/aws-sdk/v/2.6.7](https://www.npmjs.com/package/aws-sdk/v/2.6.7)

You can see the full list of versions on the NPM package page [here](https://www.npmjs.com/package/aws-sdk/v/2.6.7?activeTab=versions).

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have any further questions.
