### ISSUE TITLE
S3 constructor ignores accessKeyId and secretAccessKey in options hash

### ISSUE THREAD

**Issue by zxlin** [aws/aws-sdk-js#2241]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property states that the S3 constructor can take in the following in the constructor options hash

- `accessKeyId (String) — your AWS access key ID.`
- `secretAccessKey (String) — your AWS secret access key.`
- `credentials (AWS.Credentials) — the AWS credentials to sign requests with. You can either specify this object, or specify the accessKeyId and secretAccessKey options directly.`

but a basic example like:

```javascript
const S3 = require('aws-sdk/clients/s3');
const s3 = new S3({
  region : 'us-east-1',
  accessKeyId : '{insertYourKeyHere}',
  secretAccessKey : '{insertYourKeyHere}'
  /* yes I understand that this is not the preferred method for security purposes, disregard that for this example */
});

console.log(s3.config.credentials);

s3.upload({
  Key : 'test',
  Bucket : 'test',
  Body : 'test',
}, (err) => {
  console.log(err);
}
```
will yield this error:
```
{ CredentialsError: Missing credentials in config
    at ClientRequest.<anonymous> (~/project/node_modules/aws-sdk/lib/http/node.js:83:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:706:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:410:8)
    at ontimeout (timers.js:498:11)
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: 2018-09-06T21:49:35.653Z,
  retryable: true,
  originalError:
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: 2018-09-06T21:49:35.653Z,
     retryable: true,
     originalError:
      { message: 'Connection timed out after 1000ms',
        code: 'TimeoutError',
        time: 2018-09-06T21:49:35.653Z,
        retryable: true } } }
```

Digging further, it seems like the TimeoutError is caused by the sdk trying to lookup IAM roles from http://169.254.169.254 but this is not an ec2 instance, so it obviously doesn't have the IAM service running

I guess this is likely because `s3.config.credentials` is still set to null after the constructor is called, so the SDK is looking for other credentials to use. 

I don't know why `s3.config.credentials` is still set to null when the constructor is called with the `accessKeyId` and the `secretAccessKey`

**Comment by srchase** [comment]
How are you populating the accessKeyId and secretAccessKey?

If those are hardcoded strings (as you acknowledge is not recommended), this should be working.

Are you doing anything else that would be trying to resolve credentials elsewhere in your code?

**Comment by zxlin** [comment]
No, I don't have any other creds configured, e.g. aws configure, the code is verbatim, except the keys obviously

________________________________

**Comment by srchase** [comment]
Which version of the SDK are you using?  How are you executing the code?

Using node and the latest version of the SDK, logging s3.config.credentials should give you something like this (based on your credentials):

```
Credentials {
  expired: false,
  expireTime: null,
  accessKeyId: '{your_access_key_id}',
  sessionToken: undefined }
```
