### ISSUE TITLE
Support --enable-debugging in the EMR definitions

### ISSUE THREAD

**Issue by whitfin** [aws/aws-sdk-js#2243]
It looks like the optional to enable debugging for EMR tasks is unavailable in the SDK, but available in the CLI/Console. Any chance this can be supported?

**Comment by srchase** [comment]
Thanks for submitting this feature request.

To make sure we understand your use case, is this something you'd want to specify when calling runJobFlow?

**Comment by whitfin** [comment]
@srchase yep, exactly! :)

**Comment by srchase** [comment]
@whitfin 

One additional thought:

The SDK does support addJobFlowSteps.  It's not documented (and certainly not as clean as supplying a flag like the CLI), but you could follow the pattern for the Java SDK to enable debugging that way: [Example Enabling debugging using the Java SDK](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-debugging.html#emr-plan-debugging-info)

**Comment by whitfin** [comment]
@srchase that's what I'm doing right now - found that after an hour of so looking around. I have a feeling it would be more familiar for people to just be an option. Appreciate the tip though!

**Comment by ajredniwja** [comment]
Closing this now, please reach out if you have additional questions.
