### ISSUE TITLE
TypeScript v 3.0.3: Cannot find global type 'Promise'

### ISSUE THREAD

**Issue by hanginwithdaddo** [aws/aws-sdk-js#2244]
I am seeing the following error while trying to compile using TypesScript v3.0.3. There is no context other than what you see below. I don't know if this is coming from tslint or the compiler. Has anyone seen this error and can give me a clue as to what might be wrong? I am using Promise<void> through out my code.

Failed to compile.
(undefined,undefined): Cannot find global type 'Promise'.

Here is the content of my tsconfig.json file (ignore the "..." that appears for the "paths" value):
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "out/",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "allowJs": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "noEmitHelpers": true,
    "jsx": "react",
    "lib": ["dom", "es2016", "es2017", "esnext.asynciterable"],
    "types": ["jest"],
    "target": "es2017",
    "module": "esnext",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "strict": true,
    "strictFunctionTypes": false,
    "pretty": true,
    "removeComments": true,
    "sourceMap": true,
    "skipLibCheck": true,
	"paths": {
	  . . .
    }
  },
  "include": ["src/**/*", "typings/*"],
  "exclude": [
    "node_modules",
    "src/**/*.spec.*",
    "build",
    "scripts",
    "webpack",
    "src/setupTests.ts",
	"vendor"
  ]
}

```
Thanks in advance for any hints anyone might be able to provide.

**Comment by hanginwithdaddo** [comment]
update: problem does not appear using typescript@3.1.0-dev.20180906

**Comment by AllanFly120** [comment]
Hey, @hanginwithdaddo I'm using typescript@3.0.3 and the similar compilerOptions as above but cannot reproduce it. 

Can you try to reinstall all the dependencies? And make sure you installed '@types/node' and add "node" to `"types"` config? Or maybe you can add `"es2015.promise"` to the "lib". You don't need to add this lib since you target at newer ES standard that doesn't require promise lib explicitly, but I'm just curious. Do you see any another compile issues that type cannot be found?

**Comment by hanginwithdaddo** [comment]
I did not have time yesterday to look into this further yesterday, but will do so today. I believe all of the necessary dependencies are installed correctly (if they weren't upgrading to typescript@3.0.3-insiders.20180829 wouldn't have worked either).

**Comment by hanginwithdaddo** [comment]
@types/node is installed:
$ ls -d node_modules/@types/node
node_modules/@types/node
$ grep version node_modules/@types/node/package.json
    "version": "10.1.0",
However, I've run into what could be another compiler bug that is precluding me from continuing to test this issue. Let me see if I can produce a smaller example of this new issue. If it turns out to be a compiler bug and not my code, I'll submit a new issue and link this ticket to the new one.

**Comment by hanginwithdaddo** [comment]
Based on one of the other problems I was running into, this appears to be a problem in compatibility between typescript and tslint versions. Using typescript 3.0.3 requires running tslint 5.11.0. I had tslint 5.10.0 installed. Closing this ticket. Unfortunately, with the error that was reported,  there was no context indicating that this could have been a problem with tslint.
