### ISSUE TITLE
Calling `ssm.getParameter` will not return the value, instead returns undefined.

### ISSUE THREAD

**Issue by ANTGOMEZ** [aws/aws-sdk-js#2245]
Th code below should return a value because the Parameter does exist. However it returns null instead. I have verified that the Parameter exists and that the name is exactly as I am requesting. I also have verified that the client is pointing to the correct ssm endpoint because I can call putParameter and that works. But _resp.Parameter.Value_ is returning _undefined_

<pre>
'use strict';
const aws = require('aws-sdk');
var ssm = new aws.SSM();
exports.handler = function (event, context)
{  
   event = { "func":"getStoredParameterValue", "params":{"p1": '/some/param/name/item, "p2":true}};        
    try 
    {    
        switch(event.func) 
        {
            case "getStoredParameterValue":
                getStoredParameterValue.apply(null, [event.params]);                
                break;
      }
   }
  catch(ex)
  {
     throw ex;
  }
}//export

function getStoredParameterValue({p1, p2=true})
{
    var params = {
        Name: p1, 
        WithDecryption: p2
      };
    var resp = ssm.getParameter(params, function(err, data) {
        if (err) throw err;      // an error occurred        
    });    

    if(resp.response.data == null)
      return resp.response.data;
    else
      return resp.Parameter.Value;
}</pre>

**Comment by srchase** [comment]
@ANTGOMEZ 

When you're calling getParameter, you're supplying a callback, so that call that is being made asynchronously.

If you want to use the response object, you can do something like this:

```
var request = ssm.getParameter(params);

request.on('success', function(response) {
  console.log(response.data); // or return in your function
});

request.on('error', function(err) {
  throw err;
});

request.send();
```

**Comment by ANTGOMEZ** [comment]
Thanks. This gets me undefined still:
 Here it is simplified.

<pre>
 function getP(){
    var params = {
        Name: '/redshift/cluster/cluster-name-test/endpoint2', 
        WithDecryption: true
    };
    
    var request = ssm.getParameter(params);

    request.on('success', function(response) {
      return response.data; // or return in your function
    });

    request.on('error', function(err) {
        throw err;
      });

    request.send();    
}

var resp = getP();

console.log(resp);</pre>

**Comment by srchase** [comment]
@ANTGOMEZ 

I apologize.  The function, getP, will return before request.on is able to return the response.

If you console log inside the function, do you get the correct response.data you're expecting?

**Comment by ANTGOMEZ** [comment]
Yes the data is there inside the function, but I need to be able to return it so I can use it outside.

**Comment by ANTGOMEZ** [comment]
It's so much simpler, here it is:
<pre>
 async function getP()
 {
    var params = {
        Name: '/redshift/cluster/cluster-name-test/endpoint2', 
        WithDecryption: true
    };
    
    var request = await ssm.getParameter(params).promise();
    
    return request.Parameter.Value;          
}

async function getParam()
{
    var resp = await getP();

    console.log(resp);
}

getParam();

<pre>

**Comment by OriginUnknown** [comment]
Dude! You are a legend! I spent a day on this and it drove me to near insanity! Massive thanks again :)
