### ISSUE TITLE
sdk makes requests to lambda.undefined.amazonaws.com 

### ISSUE THREAD

**Issue by skazska** [aws/aws-sdk-js#2249]
lambda = new Lambda({apiVersion: '2015-03-31'})
lambda.config.loadFromPath(pathToFile)  
//file contains {"accessKeyId": "MY KEY", "secretAccessKey": "MY SEC",  "region": "eu-west-1"
}  
lambda.createFunction(params)
//cause error Inaccessible host: `lambda.undefined.amazonaws.com'. This service may not be available in the `eu-west-1' region.

Reasons:
when construct Lambda, lib/service.js(40) constructor calls initialize, which in turn calls lib/service.js(53) regionConfig to set endpoint (only if endpoint is not set yet)  lib/region_config uses region to compose hostname,  but region is not set yet.
When region is get set on loadFromPath then, it wont go to initialize and not reconfigure endpoint

**Comment by srchase** [comment]
Hello @skazska 

You need to set the region before constructing the lambda client.

Here are two ways you can do that:

1. Load the entire SDK
```
const AWS = require('aws-sdk')

AWS.config.loadFromPath('config.json')
const lambda = new AWS.Lambda({apiVersion: '2015-03-31'})
```

2. Pull in global AWS namespace, but only load the lambda client:
```
const AWS = require('aws-sdk/global')
const Lambda = require('aws-sdk/clients/lambda')

AWS.config.loadFromPath('config.json')
const lambda = new Lambda({apiVersion: '2015-03-31'})
```

Additional details can be found here: [Creating and Calling Service Objects](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/creating-and-calling-service-objects.html)
