### ISSUE TITLE
Expires doesn't work properly on IoT mqtt over wss and v4

### ISSUE THREAD

**Issue by PinnacleOne** [aws/aws-sdk-js#2254]
Here is my code:

```
const v4 = require('aws-signature-v4');
const crypto = require('crypto');
const mqtt = require('mqtt');

const url = v4.createPresignedURL(
        'GET',
        'XXXXXXXXXXXXXXXXXX', // Your IoT end point here
        '/mqtt',
        'iotdevicegateway',
        crypto.createHash('sha256').update('', 'utf8').digest('hex'),
        {
            'key': 'XXXXXXXXXXXXXXXXXXXX', // your AWS access key
            'secret': 'XXXXXXXXXXXXXXXXXXX', //your AWS access secret
            'protocol': 'wss',
            'region': 'ap-southeast-1',
            'expires': 172800
        }
      );

setTimeout(() => {
   const client = mqtt.connect(url);

   client.on('connect', () => {
        console.info("CONNECTED!");
      });

   client.on('close', () => {
          console.warn("CLIENT CLOSED!!");
            client.end();
      });
}, 600000);

```
It works only for few mins, but If I try to connect in 10-15 min later with the same signed url connection drops returning 426 code response.

Why? I it should sustain at lest 48 hours.

**Comment by fyn-dev** [comment]
@srchase 
Please provide example code how to achieve same result using aws-sdk? I can't find any example in entire internet.

**Comment by srchase** [comment]
@fyn-dev 

There's an open feature request to add that capability to the SDK: https://github.com/aws/aws-sdk-js/issues/1456

**Comment by PinnacleOne** [comment]
@srchase but anyone tested this signature generation with wss uri?

> wss://endpoint_name.iot.region.amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX&X-Amz-Date=20180920T092557Z&X-Amz-Expires=172800&X-Amz-SignedHeaders=host&X-Amz-Signature=e4f6d25ecca833052b7858c26539e524080f99389cc88dbcb6d5c35c36ca895a

Why X-Amz-Expires doesn't work? Is problem with this third party library or just AWS service related to wss and iot has issue? Anyone can help investigate this please?

**Comment by srchase** [comment]
Hello @PinnacleOne,

Unfortunately, the SDK doesn't currently support creating presigned urls for use with IoT endpoints.  If you have usage questions for IoT and getting it to work with Third-Party clients for creating presigned urls, you'll need to refer to the [AWS IoT Forum](https://forums.aws.amazon.com/forum.jspa?forumID=210) for additional help with your use case.

**Comment by rianwouters** [comment]
You may want to consider this extension: https://gist.github.com/rianwouters/17605cdb84a28ab59c89f2a46a7a36be
