### ISSUE TITLE
Calling STS.assumeRole() twice reports an 404 error, calling STS.getCallerIdentity() after first STS.assumeRole() reports 404 error...

### ISSUE THREAD

**Issue by Dom-HMH-MTL** [aws/aws-sdk-js#2256]
Hi,

My server is stateless.

I first tried to call `STS.assumeRole()` before calling aws-sdk `config.apply()`. The first call after a server restart is successful, subsequent ones always fails with a error `code` equals to 404.

Then I tried to rely on `STS.getCallerIdentity()` to avoid unnecessary calls to `STS.assumeRole()`. The first call after a server restart is successful, and because the returned `Arn` attribute value does not match the `RoleArn` I want to assume, I can successfully call `STS.assumeRole()`. On a following call however, the call to `STS.getCallerIdentity()` does report an error with `code` being 404.

Questions:
- Why am I receiving a 404 error [*MalformedQueryString*](https://docs.aws.amazon.com/STS/latest/APIReference/CommonErrors.html) instead of a meaningful one?
- What should I do to verify that the role has been already applied and that I can skip calls to `STS.assumeRole()`?

I've been using the aws-sdk to remotely control DynamoDB and it works fine. It's just here that while trying to apply a role for cross account interactions (from an app on EC2 in one account to DynamoDB in another account) that I face some hurdles...

Thanks, Dom

**Comment by Dom-HMH-MTL** [comment]
Sure, here is the set of Typescript functions I rely on. The one directly called is `configureAWS()` with the corresponding parameters (`region`, `endpoint`, and `credentials`). The role has the format `arn:aws:iam::<accountId>:role/<customName>`.

``` typescript
private async configureAWS(config: ServiceConfigurationOptions, applicationRole: string): Promise<void> {
    if (applicationRole) {
        if (!(await this.isRoleAssumed(config, applicationRole))) {
            await this.assumeRole(config, applicationRole);
        }
    }
    AWSConfig.update(config);
}

private async isRoleAssumed(config: ServiceConfigurationOptions, applicationRole: string): Promise<boolean> {
    return this.getSTS()
        .getCallerIdentity({})
        .promise()
        .then(
            (data: any): boolean => {
                // tslint:disable-next-line: no-console
                console.log('STS.getCallerIdentity():\n', data);
                return data.Arn === applicationRole;
            }
        )
        .catch(
            (error: any): boolean => {
                // tslint:disable-next-line: no-console
                console.log('STS.getCallerIdentity() Error!\n', error);
                if (error.code === 404) {
                    return true; // FIXME: understand why the `sts` role is returned with an error 404 when the doc (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#getSessionToken-property) says it should be successfully returned.
                }
                throw error;
            }
        );
}

private async assumeRole(config: ServiceConfigurationOptions, applicationRole: string): Promise<any> {
    return this.getSTS()
        .assumeRole({ RoleArn: applicationRole, RoleSessionName: 'CrossAccountCredentials' })
        .promise();
}

private getSTS(): STS {
    return new STS();
}
```

**Comment by Dom-HMH-MTL** [comment]
Re: how are you applying the credentials...

As you can see in the code above, I don't do anything other than calling `assumeRole()`. I did not find a documentation explaining their usage per-se... If I don't call `assumeRole()`, the access to the DynamoDB instance on the other account fails. When I call it the first time, the call is successful and I can access the DynamoDB on another account. It returns the subsequent error 404 after that initial call. I does not seems to have an effect (the call to the remote DynamoDB are fine, AFAIK) but I don't like to have let the misunderstood error incorrectly handled... That's why I try to rely on `getCallerIdentity()` first, but it has the same behaviour.

Maybe the effect of the role endorsement is managed by the environment my application is deployed on... Going to follow-up with our tech team here.

**Comment by AllanFly120** [comment]
I'm not sure I understand the issue. The first `assumeRole()` succeeds and you can access remote DynamoDB. Are you saying you see the errors if you call `assumeRole` later? If you see the `MalformedQueryString` exception from the `assumeRole()` call can you share what the query looks like?

**Comment by srchase** [comment]
@Dom-HMH-MTL 

This page from the Developer Guide has details on [Using the Response Object](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/the-response-object.html).

You can access the originating AWS.Request object by using this syntax:

```
s3.getObject({Bucket: 'bucket', Key: 'key'}).on('success', function(response) {
   console.log("Key was", response.request.params.Key);
}).send();
```

**Comment by Dom-HMH-MTL** [comment]
I've tried to get more information at the request level. So far the main difference I can see is located in the endpoint which is switched from `sts.amazon.com` to `dynamodb.us-east-1.amazonaws.com` when it's always the same sequence of `new STS().getCallerIdentity()`...

Any idea on this URL switch? A cache incorrectly updated? An unexpected interaction in a cache induced by sequences of `new STS()`, `new DynamoDB(config)`, `new DocumentClient()`, etc.?

Thanks, Dom
--

``` javascript
{
        protocol: 'https:',
        host: 'dynamodb.us-east-1.amazonaws.com',
        port: 443,
        hostname: 'dynamodb.us-east-1.amazonaws.com',
        pathname: '/',
        path: '/',
        href: 'https://dynamodb.us-east-1.amazonaws.com/',
        constructor: [Function] 
}
```

``` javascript
{
        protocol: 'https:',
        host: 'sts.amazonaws.com',
        port: 443,
        hostname: 'sts.amazonaws.com',
        pathname: '/',
        path: '/',
        href: 'https://sts.amazonaws.com/',
        constructor: [Function] 
}
```

**Comment by Dom-HMH-MTL** [comment]
it appears that relying on a `instanceSTS` initialized only once (instead of calling `new STS()` every time, as illustrated in my comment above) fixed the issue...

Now, there is no more endpoint mixed-up, and the role can be applied many times. For all subsequent call, the `STS.getCallerIdentity()` always returns the same payload (that is with a non matching `Arn` value) so the code is always triggering `STS.assumeRole()`. It seems that the applied role information is lost after the interaction with the DynamoDB instance belonging to another AWS account, but I don't know enough the intrinsics of the library to get a clear reason...

I'm going to close this issue but if someone can confirm the impact of the `new STS()` every time ;)
