### ISSUE TITLE
SWF.pollForActivityTask loses tasks "on the wire"

### ISSUE THREAD

**Issue by tristanls** [aws/aws-sdk-js#2259]
I've noticed that when `SWF.pollForActivityTask` is aborted prior to 60 seconds, tasks are lost "on the wire", that is, it appears that the service marked the task as started, but the client never received the task. This is a significant problem with activity tasks that have Start to Close timeouts in hours or days.

This seems like a flaw in the PollForActivityTask protocol in general. 

What would resolve this flaw would be an additional timeout `StartToStartAckTimeout` along with an `SWF.respondActivityTaskStarted` call.

"on the wire" loss scenario:
1. service marks task as `Started` and starts `StartToStartAck` timer
2. client aborts connection and never receives the task
3. `StartToStartAckTimeout` fires
4. service attempts activity re-delivery

usual case scenario 1:
1. service marks task as `Started` and starts `StartToStartAck` timer
2. client responds with `SWF.respondActivityTaskStarted`
3. service turns off `StartToStartAck` timer

usual case scenario 2:
1. service marks task as `Started` and starts `StartToStartAck` timer
2. client responds with `SWF.respondActivityTaskCompleted`
3. service does the usual

usual case scenario 3:
1. service marks task as `Started` and starts `StartToStartAck` timer
2. client responds with `SWF.recordActivityTaskHeartbeat`
3. service does the usual

This way, an addition of `SWF.respondActivityTaskStarted` and `StartToStartAckTimeout` are optional, and there solely to not lose tasks "on the wire".

I observe an identical failure scenario in `SWF.pollForDecisionTask`, but for my use case, decisions happen quickly enough where the decision `StartToCloseTimeout` along with deterministic decider is sufficient to trigger decision redeliveries.

**Comment by srchase** [comment]
@tristanls 

Thanks for reaching out.  I want to make sure we fully understand what you're encountering with this issue.

Do you have any evidence that this is an issue with the SDK handling long polling for Activity Tasks (and Decision Tasks)?  Have you gotten the same 'on the wire' losses with any of the other SDKs or with the AWS CLI?

**Comment by srchase** [comment]
@tristanls 

Thanks for the thorough response.

We will pass along the feedback to the service team for that feature request.  You're welcome to make the same request that to the team directly via their forum page.

I've noted this as a place where we could improve the documentation in the area you've suggested.

**Comment by tristanls** [comment]
Thank you.
