### ISSUE TITLE
Modular Imports for Aws-sdk ? Minimal bundle size for aws-sdk + aws-xray is 6.3 Mb

### ISSUE THREAD

**Issue by XCarle** [aws/aws-sdk-js#2263]
Hi guys,

do you provide modular import for the aws-sdk ? 6.3Mb minimal size for a lambda embedding the sdk 
 + xray seems like a lot.

We use serverless to package our lambda and it would be interesting to optimise the size of the bundle : 
- packaging time reduction
- cold to warm timing might improve as well.

**Comment by srchase** [comment]
Hello @XCarle,

The aws-sdk is included in the lambda runtime, currently version 2.290.0.

You can see details for all of the [Lambda Execution Environment and Available Libraries](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).

If you only need to use an individual service, you can import that client directly:

```
var XRAY = require('aws-sdk/clients/xray');
var xray = new XRAY();
```

Refer to the [Creating and Calling Service Objects](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/creating-and-calling-service-objects.html) for additional examples.
