### ISSUE TITLE
Update Crypto browerify package

### ISSUE THREAD

**Issue by Ch3ck** [aws/aws-sdk-js#2265]
I encountered an issue as many others with the `undefined` _global variable appearing as a side effect as others have pointed out below:
1. https://github.com/aws/aws-sdk-js/issues/1512
2. https://github.com/aws/aws-sdk-js/issues/1566

I literally had to patch this package as a temporary solution, however after filing an issue with the 
* [crypto-browerify developers](https://github.com/crypto-browserify/crypto-browserify/issues/180)

One recommendation is to update this package reference. Let me know your thoughts I'll be happy to make the PR for this if necessary.

**Comment by chrisradek** [comment]
@Ch3ck 
The AWS JS SDK no longer depends on `crypto-browserify`. Are you by chance using this with Amplify or another package that depends on `crypto-browserify`? If you check `crypto-browserify`'s `package.json` file in `node_modules`, it will tell you which package required it, as well as the package version.

**Comment by srchase** [comment]
@Ch3ck 

I see you've opened an issue on the Amplify repository.  I'm going close out this issue as it should be addressed there.  Thanks for raising this issue.
