### ISSUE TITLE
DynamoDB batchGet response empty

### ISSUE THREAD

**Issue by SnooHD** [aws/aws-sdk-js#2269]
Hello, i have a problem using batchGet on a table.

What happens is the following:
- Run a `getItem` request on an item which contains 2 unique id's
- Run a `batchGet` on another table with these 2 id's

The response is simply empty (no errors or whatever).
The items do exist! If i do a normal `getItem` request on either of them, i get a result.
The items are almost completely empty..
The table is very basic with a primary key only.
When i try to run the `batchGet` directly through the CLI, it only returns the last Item it can find.

I do have another table which i also run `batchGet` on, and here everything works as expected.

What i have tried:
- make a new table
- change the primary key
- remove all data
- enable autoscaling

Honestly i have no clue why this happens.
The query i am right now using:
![image](https://user-images.githubusercontent.com/14291499/45902427-c87df780-bdbc-11e8-8fdb-0408ca5dcc70.png)

The table:
![image](https://user-images.githubusercontent.com/14291499/45902475-ee0b0100-bdbc-11e8-90a7-61fe84b4ff24.png)

The response:
![image](https://user-images.githubusercontent.com/14291499/45902437-d3d12300-bdbc-11e8-925f-8a88d635819a.png)

Any help is appreciated.

**Comment by srchase** [comment]
@SnooHD 

Can you provide an example of the code you're using for the batchGet?

Which version of the SDK are you using?

**Comment by SnooHD** [comment]
Hello, thanks for your reply.
The SDK im using is: `2012-08-10`.

The code im using is split in multiple function that return the query based on a simple input..
If you make an API request like this: `{test: 'hi'}` it will make a getItem request.
If you make an API request like this: `[{test: 'hi'}, {test: 'h2'}]` it will make a batchGetItem request.

The query that it returns is correct, as it also works with another table im using.
The final query it returns would be something like this:
```
{
   query:{
      RequestItems: {
         paths: {
            Keys: [{
               test: 'hi'
            },{
               test: 'hi1'
            }]
         }
      }
   },
   type: 'batchGet'
}
```

The final code that runs to fetch the actual response:
```
export const runQuery = async (queryData) => {
  try{
    let data;
    try{
      data = await db[queryData.type](queryData.query).promise();
    }catch(error){
      throw Error(error);
    }

    let response;
    try{
      response = await getters.getResponse(queryData.type, data, queryData.query);
    }catch(error){
      throw Error(error);
    }

    return response;
  }catch(error){
    console.log(error);
    return {error: error};
  }
}
```

`getResponse` is where i check the response that is returned, if it contains the `key` that contains id's for another request, i simply trigger the function again to build the query and then run it.

**Comment by srchase** [comment]
@SnooHD 

Thanks for providing this code. 

I'm not sure I follow exactly where your issue is with the response.

Are you getting the empty response for the getItem call with a single key?

Or do you get that empty response for the batchGetItem call with multiple keys?

Could you craft some tailored, specific calls to each to determine if the actual SDK is not working, or if it's the abstraction and way you're forming the queries that could be the issue?

**Comment by srchase** [comment]
@SnooHD 

Can you use describeTable to inspect and compare the two different tables (one where batchGetItem works, and and one where it doesn't)?

**Comment by SnooHD** [comment]
@srchase this is the table that works: (tags)
![image](https://user-images.githubusercontent.com/14291499/46014737-acbd6e80-c0a6-11e8-8ec8-baa2ffab7ac6.png)

This is the table that does NOT work: (paths)
![image](https://user-images.githubusercontent.com/14291499/46014772-cd85c400-c0a6-11e8-9407-3dd6636f4828.png)

**Comment by SnooHD** [comment]
I just noticed that me query in the previous post was wrong! (I only had 1 object inside the array).
It was supposed to be like this: 
```
{
  "paths": {
    "Keys":[
      {"_id": {"S":"4ec43e9c9a95abcfd928f166f61a623d016c5251"}},
      {"_id": {"S":"c40f9cccb8625c42f0732cea777237b091db2864"}}
      ]
  }
}
```

Now the CLI DOES return the correct result!

**Comment by srchase** [comment]
@SnooHD 

Thanks for trying the CLI again.  That makes more sense!

Can you use this syntax to inspect the getBatchItem request?

```
s3.getObject({Bucket: 'bucket', Key: 'key'}).on('success', function(response) {
   console.log("Key was", response.request.params.Key);
}).send();
```

**Comment by SnooHD** [comment]
This is for `S3` right?
I'm not sure if i'm following the magic relation with `DynamoDB` here.

**Comment by SnooHD** [comment]
I tried running this direct:
```
  let test;
  try{
    test = await db.batchGet({"RequestItems":{
      "paths": {
        "Keys":[
          {"_id": "4ec43e9c9a95abcfd928f166f61a623d016c5251"},
          {"_id": "c40f9cccb8625c42f0732cea777237b091db2864"}
        ]
      }
    }}).promise();
  }catch(error){
    console.log(error);
  }

  console.log(test);
```
And the response is correct!?

So i changed my code back to the way it was originally.. and all works as expected now..
This seems very weird to me.. Any clue whats going on here?

At least i'm happy to say that its working correctly now!

**Comment by srchase** [comment]
@SnooHD 

Glad to hear it's working!

Unfortunately, I was never able to get the same empty response, and thus wasn't able to dig any deeper into what was happening for your specific example.

If you get this behavior again and have any additional details, let us know and we can re-open this issue.
