### ISSUE TITLE
Ionic aws starter error

### ISSUE THREAD

**Issue by Shery11** [aws/aws-sdk-js#2272]
`[app-scripts] [05:28:45]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/acm.d.ts, line: 108
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L107:  export type CertificateBody = string;
[app-scripts]      L108:  export type CertificateBodyBlob = Buffer|Uint8Array|Blob|string;
[app-scripts]      L109:  export type CertificateChain = string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/acm.d.ts, line: 110
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/acm.d.ts, line: 401
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/apigateway.d.ts, line: 1146
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/appsync.d.ts, line: 248
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/clouddirectory.d.ts, line: 1469
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/cloudsearchdomain.d.ts, line: 7
[app-scripts]      L109:  export type CertificateChain = string;
[app-scripts]      L110:  export type CertificateChainBlob = Buffer|Uint8Array|Blob|string;
[app-scripts]      L111:  export interface CertificateDetail {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L400:  export type NextToken = string;
[app-scripts]      L401:  export type PrivateKeyBlob = Buffer|Uint8Array|Blob|string;
[app-scripts]      L402:  export type RecordType = "CNAME"|string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L1146:  export type _Blob = Buffer|Uint8Array|Blob|string;
[app-scripts]     L1147:  export type Boolean = boolean;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L247:  export type AuthenticationType = "API_KEY"|"AWS_IAM"|"AMAZON_COGNITO_USER_POOLS"|string;
[app-scripts]      L248:  export type _Blob = Buffer|Uint8Array|Blob|string;
[app-scripts]      L249:  export type Boolean = boolean;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L1469:  export type BinaryAttributeValue = Buffer|Uint8Array|Blob|string;
[app-scripts]     L1470:  export type Bool = boolean;
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L6:  import {ConfigBase as Config} from '../lib/config';
[app-scripts]        L7:  import {Readable} from 'stream';
[app-scripts]        L8:  interface Blob {}
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L41:  export type Adds = number;
[app-scripts]       L42:  export type _Blob = Buffer|Uint8Array|Blob|string|Readable;
[app-scripts]       L43:  export interface Bucket {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L140:  export type Boolean = boolean;
[app-scripts]      L141:  export type ByteBuffer = Buffer|Uint8Array|Blob|string;
[app-scripts]      L142:  export interface CreateTrailRequest {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L1539:  export type blob = Buffer|Uint8Array|Blob|string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L2580:  export type IdpIdentifiersListType = IdpIdentifierType[];
[app-scripts]     L2581:  export type ImageFileType = Buffer|Uint8Array|Blob|string;
[app-scripts]     L2582:  export type ImageUrlType = string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L992:  export type LoaContent = Buffer|Uint8Array|Blob|string;
[app-scripts]      L993:  export type LoaContentType = "application/pdf"|string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L447:  export type CertificateList = Certificate[];
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/cloudsearchdomain.d.ts, line: 42
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/cloudtrail.d.ts, line: 141
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/codecommit.d.ts, line: 1539
[app-scripts] [05:28:46]  typescript: ...c3V1/mzflIonic3/node_modules/aws-sdk/clients/cognitoidentityserviceprovider.d.ts, line: 2581
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/directconnect.d.ts, line: 992
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/dms.d.ts, line: 448
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/dynamodb.d.ts, line: 466
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/dynamodbstreams.d.ts, line: 92
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/ec2.d.ts, line: 3026
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/ecr.d.ts, line: 767
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/firehose.d.ts, line: 156
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/glacier.d.ts, line: 7
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/glacier.d.ts, line: 1313
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/iam.d.ts, line: 1112
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/iam.d.ts, line: 3106
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/iot.d.ts, line: 4325
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/iotdata.d.ts, line: 73
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/iotdata.d.ts, line: 74
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/kinesis.d.ts, line: 237
[app-scripts] [05:28:46]  typescript: ...lIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/kinesisvideoarchivedmedia.d.ts, line: 7
[app-scripts] [05:28:46]  typescript: ...lIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/kinesisvideoarchivedmedia.d.ts, line: 121
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/kinesisvideomedia.d.ts, line: 7
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/kinesisvideomedia.d.ts, line: 53
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/kms.d.ts, line: 328
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/kms.d.ts, line: 962
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/lambda.d.ts, line: 7
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/lambda.d.ts, line: 372
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/lambda.d.ts, line: 373
[app-scripts] [05:28:46]  typescript: ...zflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/lexmodelbuildingservice.d.ts, line: 306
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/lexruntime.d.ts, line: 7
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/lexruntime.d.ts, line: 35
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/mediastoredata.d.ts, line: 7
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/mediastoredata.d.ts, line: 199
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/mobile.d.ts, line: 106
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/polly.d.ts, line: 8
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/polly.d.ts, line: 70
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/rekognition.d.ts, line: 1135
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/s3.d.ts, line: 10
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/s3.d.ts, line: 777
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/s3.d.ts, line: 1131
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/s3.d.ts, line: 3473
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/sagemakerruntime.d.ts, line: 24
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/ses.d.ts, line: 1513
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/sns.d.ts, line: 275
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/sqs.d.ts, line: 216
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/ssm.d.ts, line: 4580
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/support.d.ts, line: 336
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/waf.d.ts, line: 604
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/clients/wafregional.d.ts, line: 648
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/lib/config.d.ts, line: 1
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/lib/config.d.ts, line: 2
[app-scripts] [05:28:46]  typescript: ...:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/lib/dynamodb/document_client.d.ts, line: 2
[app-scripts] [05:28:46]  typescript: ...:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/lib/dynamodb/document_client.d.ts, line: 93
[app-scripts] [05:28:46]  typescript: ...:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/lib/dynamodb/document_client.d.ts, line: 274
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/lib/http_response.d.ts, line: 1
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/lib/http_response.d.ts, line: 14
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/lib/request.d.ts, line: 1
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/lib/request.d.ts, line: 132
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/node_modules/aws-sdk/lib/services/glacier.d.ts, line: 10
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/src/app/app.module.ts, line: 31
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/src/pages/tasks/tasks.ts, line: 7
[app-scripts] [05:28:46]  typescript: E:/mzflIonic3V1/mzflIonic3/src/providers/aws.dynamodb.ts, line: 4
[app-scripts]      L448:  export type CertificateWallet = Buffer|Uint8Array|Blob|string;
[app-scripts]      L449:  export type CompressionTypeValue = "none"|"gzip"|string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L465:  export type BatchWriteItemRequestMap = {[key: string]: WriteRequests};
[app-scripts]      L466:  export type BinaryAttributeValue = Buffer|Uint8Array|Blob|string;
[app-scripts]      L467:  export type BinarySetAttributeValue = BinaryAttributeValue[];
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L92:  export type BinaryAttributeValue = Buffer|Uint8Array|Blob|string;
[app-scripts]       L93:  export type BinarySetAttributeValue = BinaryAttributeValue[];
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L3025:  export type BillingProductList = String[];
[app-scripts]     L3026:  export type _Blob = Buffer|Uint8Array|Blob|string;
[app-scripts]     L3027:  export interface BlobAttributeValue {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L766:  export type LayerList = Layer[];
[app-scripts]      L767:  export type LayerPartBlob = Buffer|Uint8Array|Blob|string;
[app-scripts]      L768:  export type LayerSizeInBytes = number;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L156:  export type Data = Buffer|Uint8Array|Blob|string;
[app-scripts]      L157:  export type DataTableColumns = string;
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L6:  import {ConfigBase as Config} from '../lib/config';
[app-scripts]        L7:  import {Readable} from 'stream';
[app-scripts]        L8:  interface Blob {}
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L1312:  export type StorageClass = "STANDARD"|"REDUCED_REDUNDANCY"|"STANDARD_IA"|string;
[app-scripts]     L1313:  export type Stream = Buffer|Uint8Array|Blob|string|Readable;
[app-scripts]     L1314:  export type TagKey = string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L1112:  export type BootstrapDatum = Buffer|Uint8Array|Blob|string;
[app-scripts]     L1113:  export interface ChangePasswordRequest {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L3106:  export type ReportContentType = Buffer|Uint8Array|Blob|string;
[app-scripts]     L3107:  export type ReportFormatType = "text/csv"|string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L4324:    disableAllLogs?: DisableAllLogs;
[app-scripts]     L4326:  export type Signature = Buffer|Uint8Array|Blob|string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L73:  export type JsonDocument = Buffer|Uint8Array|Blob|string;
[app-scripts]       L74:  export type Payload = Buffer|Uint8Array|Blob|string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L73:  export type JsonDocument = Buffer|Uint8Array|Blob|string;
[app-scripts]       L74:  export type Payload = Buffer|Uint8Array|Blob|string;
[app-scripts]       L75:  export interface PublishRequest {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L237:  export type Data = Buffer|Uint8Array|Blob|string;
[app-scripts]      L238:  export interface DecreaseStreamRetentionPeriodInput {
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L6:  import {ConfigBase as Config} from '../lib/config';
[app-scripts]        L7:  import {Readable} from 'stream';
[app-scripts]        L8:  interface Blob {}
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L120:  export type PageLimit = number;
[app-scripts]      L121:  export type Payload = Buffer|Uint8Array|Blob|string|Readable;
[app-scripts]      L122:  export type StreamName = string;
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L6:  import {ConfigBase as Config} from '../lib/config';
[app-scripts]        L7:  import {Readable} from 'stream';
[app-scripts]        L8:  interface Blob {}
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L53:  export type Payload = Buffer|Uint8Array|Blob|string|Readable;
[app-scripts]       L54:  export type ResourceARN = string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L328:  export type CiphertextType = Buffer|Uint8Array|Blob|string;
[app-scripts]      L329:  export interface CreateAliasRequest {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L961:  export type PendingWindowInDaysType = number;
[app-scripts]      L962:  export type PlaintextType = Buffer|Uint8Array|Blob|string;
[app-scripts]      L963:  export type PolicyNameList = PolicyNameType[];
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L6:  import {ConfigBase as Config} from '../lib/config';
[app-scripts]        L7:  import {Readable} from 'stream';
[app-scripts]        L8:  interface Blob {}
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L371:  export type BatchSize = number;
[app-scripts]      L372:  export type _Blob = Buffer|Uint8Array|Blob|string;
[app-scripts]      L373:  export type BlobStream = Buffer|Uint8Array|Blob|string|Readable;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L372:  export type _Blob = Buffer|Uint8Array|Blob|string;
[app-scripts]      L373:  export type BlobStream = Buffer|Uint8Array|Blob|string|Readable;
[app-scripts]      L374:  export type Boolean = boolean;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L305:  export type AliasNameOrListAll = string;
[app-scripts]      L306:  export type _Blob = Buffer|Uint8Array|Blob|string;
[app-scripts]      L307:  export type Boolean = boolean;
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L6:  import {ConfigBase as Config} from '../lib/config';
[app-scripts]        L7:  import {Readable} from 'stream';
[app-scripts]        L8:  interface Blob {}
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L34:  export type AttributesString = string;
[app-scripts]       L35:  export type BlobStream = Buffer|Uint8Array|Blob|string|Readable;
[app-scripts]       L36:  export type BotAlias = string;
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L6:  import {ConfigBase as Config} from '../lib/config';
[app-scripts]        L7:  import {Readable} from 'stream';
[app-scripts]        L8:  interface Blob {}
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L198:  export type PathNaming = string;
[app-scripts]      L199:  export type PayloadBlob = Buffer|Uint8Array|Blob|string|Readable;
[app-scripts]      L200:  export interface PutObjectRequest {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L105:  export type ConsoleUrl = string;
[app-scripts]      L106:  export type Contents = Buffer|Uint8Array|Blob|string;
[app-scripts]      L107:  export interface CreateProjectRequest {
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L7:  import {Presigner as presigner} from '../lib/polly/presigner';
[app-scripts]        L8:  import {Readable} from 'stream';
[app-scripts]        L9:  interface Blob {}
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L69:  export type Alphabet = string;
[app-scripts]       L70:  export type AudioStream = Buffer|Uint8Array|Blob|string|Readable;
[app-scripts]       L71:  export type ContentType = string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L1135:  export type ImageBlob = Buffer|Uint8Array|Blob|string;
[app-scripts]     L1136:  export type ImageId = string;
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L9:  import {PresignedPost as presigned_post} from '../lib/s3/presigned_post';
[app-scripts]       L10:  import {Readable} from 'stream';
[app-scripts]       L11:  interface Blob {}
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L776:  export type AnalyticsS3ExportFileFormat = "CSV"|string;
[app-scripts]      L777:  export type Body = Buffer|Uint8Array|Blob|string|Readable;
[app-scripts]      L778:  export interface Bucket {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L1130:  export type CopySourceSSECustomerAlgorithm = string;
[app-scripts]     L1131:  export type CopySourceSSECustomerKey = Buffer|Uint8Array|Blob|string;
[app-scripts]     L1132:  export type CopySourceSSECustomerKeyMD5 = string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L3472:  export type SSECustomerAlgorithm = string;
[app-scripts]     L3473:  export type SSECustomerKey = Buffer|Uint8Array|Blob|string;
[app-scripts]     L3474:  export type SSECustomerKeyMD5 = string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L23:  declare namespace SageMakerRuntime {
[app-scripts]       L24:    export type BodyBlob = Buffer|Uint8Array|Blob|string;
[app-scripts]       L25:    export type EndpointName = string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L1513:    Data: RawMessageData;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L275:  export type Binary = Buffer|Uint8Array|Blob|string;
[app-scripts]      L276:  export interface CheckIfPhoneNumberIsOptedOutInput {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L215:  export type BatchResultErrorEntryList = BatchResultErrorEntry[];
[app-scripts]      L216:  export type Binary = Buffer|Uint8Array|Blob|string;
[app-scripts]      L217:  export type BinaryList = Binary[];
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]     L4580:  export type MaintenanceWindowLambdaPayload = Buffer|Uint8Array|Blob|string;
[app-scripts]     L4581:  export type MaintenanceWindowLambdaQualifier = string;
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L336:  export type Data = Buffer|Uint8Array|Blob|string;
[app-scripts]      L337:  export interface DescribeAttachmentRequest {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L603:  export type ByteMatchSetUpdates = ByteMatchSetUpdate[];
[app-scripts]      L604:  export type ByteMatchTargetString = Buffer|Uint8Array|Blob|string;
[app-scripts]      L605:  export interface ByteMatchTuple {
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L647:  export type ByteMatchSetUpdates = ByteMatchSetUpdate[];
[app-scripts]      L648:  export type ByteMatchTargetString = Buffer|Uint8Array|Blob|string;
[app-scripts]      L649:  export interface ByteMatchTuple {
[app-scripts]             Cannot find module 'http'.
[app-scripts]        L1:  import {Agent as httpAgent} from 'http';
[app-scripts]        L2:  import {Agent as httpsAgent} from 'https';
[app-scripts]             Cannot find module 'https'.
[app-scripts]        L1:  import {Agent as httpAgent} from 'http';
[app-scripts]        L2:  import {Agent as httpsAgent} from 'https';
[app-scripts]        L3:  import {AWSError} from './error';
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L1:  import DynamoDB = require('../../clients/dynamodb');
[app-scripts]        L2:  import * as stream from 'stream';
[app-scripts]        L3:  import {Request} from '../request';
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L93:      export type binaryType = Buffer|File|Blob|ArrayBuffer|DataView|Int8Array|Uint8Array|Uint8ClampedArray|In
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L273:  export type BatchWriteItemRequestMap = {[key: string]: WriteRequests};
[app-scripts]      L274:  export type BinaryAttributeValue = Buffer|Uint8Array|Blob|string;
[app-scripts]      L275:  export type BinarySetAttributeValue = BinaryAttributeValue[];
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L1:  import * as stream from 'stream';
[app-scripts]        L2:  interface XMLHttpRequest {}
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L14:  body: string|Buffer|Uint8Array;
[app-scripts]             Cannot find module 'stream'.
[app-scripts]        L1:  import * as stream from 'stream';
[app-scripts]        L2:  import {Service} from './service';
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]      L132:  on(event: "httpData", listener: (chunk: Buffer|Uint8Array, response: Response<D, E>) => void): Request<D, E>
[app-scripts]             Cannot find name 'Buffer'.
[app-scripts]       L10:      computeChecksums(data: Buffer|string): GlacierComputeChecksumsOutput;
[app-scripts]             Cannot find name 'require'.
[app-scripts]       L31:  const aws_exports = require('../aws-exports').default;
[app-scripts]             Cannot find name 'require'.
[app-scripts]        L6:  import { TasksCreatePage } from '../tasks-create/tasks-create';
[app-scripts]        L7:  const aws_exports = require('../../aws-exports').default;
[app-scripts]             Cannot find name 'require'.
[app-scripts]        L3:  import AWS from 'aws-sdk';
[app-scripts]        L4:  const aws_exports = require('../aws-exports').default;
`

Got this while serving ionic project tried every solution available on the internet still no luck

**Comment by srchase** [comment]
@Shery11 

Which versions of the SDK and Ionic are you using?

**Comment by Shery11** [comment]
I got the issue resolved.

**Comment by srchase** [comment]
Thanks for following up.  We'll close this issue.
