### ISSUE TITLE
DAX, signifient performance drawback comparing to other platforms

### ISSUE THREAD

**Issue by victorbartel** [aws/aws-sdk-js#2276]
### DAX, signifient performance drawback comparing to other platforms
Hi,

I'm using your dedicated [DAX client library](https://www.npmjs.com/package/amazon-dax-client), and since I've shifted from just DynamoDB to DAX library I've noticed a considerable drop of performance. My simple `get_by_id` request became ~6 times slower than before(I was thrown from 25 ms per request to 145ms). Here is my code:
##### Init
```typescript
export function createDocumentClient() {
    const config = getConfig();
    const service = isEmpty(config.dynamo.daxEndpoint) ? null : new AmazonDaxClient({
        endpoints: [config.dynamo.daxEndpoint],
        region: "eu-west-1",
    });
    const documentClient = new DynamoDB.DocumentClient({convertEmptyValues: true, service});
    return documentClient;
}
```
##### Usage
```typescript
    public async findItem(tableName: string,
                          id: string,
                          subId?: string): Promise<IOperationResult<GetItemOutput>> {
        const documentClient = createDocumentClient();
        const params = {
            TableName: tableName,
            Key: {
                id,
                subId: subId || id,
            },
        } as GetItemInput;
        const result = await documentClient
            .get(params).promise()
            .then(x => this.failureOnEmpty(x))
            .catch(failure);
        return result;
    }
```
Version of DAX Client: `1.1.4`
Version of AWS-SDK: `2.7.0`
AWS Lambda runtime: `nodejs8.10`

### Awkward part

When I try to request the same DAX Endpoint with the same parameter but using a Scala/jvm based lambda, I get my result in 0,7ms. Here is a part of this lambda:
```scala
object Handler {
  val tableName = "ZZZZZZZ"
  val endpoint = "ZZZZZZZ:8111"
  implicit final class MLPipe[T](val x: T) extends AnyVal {
    def |>[B](f: T => B) = f(x)
  }

  val `default client`: DynamoDB = getDaxClient()

  def getDynamoDB(x: AmazonDynamoDB) = new DynamoDB(x)
  def getDaxClient(endpoint: String = endpoint): DynamoDB =
    AmazonDaxClientBuilder.standard()
      .withRegion("zz-zzzz-1")
      .withEndpointConfiguration(endpoint)
      .build() |> getDynamoDB

  def findById(client: DynamoDB = Handler.`default client`) (id: String): Map[String, AnyRef] = {
    val table = client.getTable(tableName)
    val startTime = System.nanoTime()
    val item = table.getItem("id", id, "subId", id)
    val endTime = System.nanoTime()
    printTime(startTime, endTime)
    item.asMap.asScala.toMap
  }
  def printTime(startTime: Long, endTime: Long, iterations: Int = 1): Unit = {
    printf("\tTotal time: %.3f ms - ", (endTime - startTime) / 1000000.0)
    printf("Avg time: %.3f ms\n", (endTime - startTime) / (iterations * 1000000.0))
  }
}
```
Did you notice same issues? Many thanks.

**Comment by srchase** [comment]
Hello @victorbartel,

Thanks for reaching out.  The SDK Team does not maintain the DAX Client, but I've gone ahead and passed along your issue to the DynamoDB team.

I'm going to close out this issue, as we try to reserve this repository for SDK issues, but we'll pass along any followup from that team.  You can also engage them directly via the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=131).

**Comment by srchase** [comment]
@victorbartel 

The DAX Team responded with the suggestion that each findItem function call is opening a new connection:

```
    public async findItem(tableName: string,
                          id: string,
                          subId?: string): Promise<IOperationResult<GetItemOutput>> {
        const documentClient = createDocumentClient();  // This line
        const params = {...
```

Instead, a better pattern would be to re-use an existing connection (where possible).

This [example](https://github.com/aws-samples/amazon-dax-lambda-nodejs-sample/blob/master/lambda/index.js) re-uses the client between calls and will hopefully help speed things up.
