### ISSUE TITLE
Using deleteObject with empty Key will delete bucket

### ISSUE THREAD

**Issue by blakewilson** [aws/aws-sdk-js#2278]
Hi AWS team!

Deleting an object when specifying a Bucket and empty Key will delete the bucket if the bucket is empty. Is this a desired effect? This seems dangerous to me considering deleteObject is used to delete items in a bucket.

For example:
```
const s3 = new aws.S3()

const params = {
    Bucket: 'Bucket-Name',
    Key: '' // Empty string will delete the bucket when bucket is empty.
  }

s3.deleteObject(params, (err, data) => {
    if (err) {
      console.log(err)
    }

    // Success
  })
```

Will end up deleting the `Bucket-Name` bucket.

**Comment by srchase** [comment]
@blakewilson 

Thanks for reporting this issue!  That is not the desired effect.  The team is taking a look and will update this issue when a fix is in place.

**Comment by blakewilson** [comment]
Awesome work! Thanks for the quick response.
