### ISSUE TITLE
createUserPoolDomain; Unexpected key 'CustomDomainConfig' error

### ISSUE THREAD

**Issue by dppower** [aws/aws-sdk-js#2281]
I was trying to call the createUserPoolDomain method on the CognitoIdentityServiceProvider client, in a lambda function, nodejs8.10. The documentation says it is possible to call createUserPoolDomain and pass the certificate arn as a property of CustomDomainConfig, however when I do this I get an error "Unexpected key 'CustomDomainConfig' found in params" (the typescript interface also omit the property).

```
const params = {
    Domain,
    UserPoolId,
    CustomDomainConfig: {
        CertificateArn
    }
};
const result = await cognitoIdp.createUserPoolDomain(params).promise();
const aliasTarget = result.CloudFrontDomain;
```

I replaced the aws-sdk with making a HTTP request directly to API and that works as expected.

```
const params = aws4.sign({
    service: 'cognito-idp',
    region: process.env.AWS_REGION,
    method: 'POST',
    body: JSON.stringify({ Domain, UserPoolId, CustomDomainConfig: { CertificateArn } }),
    path: '/',
    headers: {
        'Content-Type': 'application/x-amz-json-1.1',
        'X-Amz-Target': 'AWSCognitoIdentityProviderService.CreateUserPoolDomain'
    }
});
const url = `https://${params.hostname}${params.path}`;
const res = await fetch(url, params);
const data = await res.json();
const aliasTarget = data.CloudFrontDomain;
```

**Comment by srchase** [comment]
@dppower 

CustomDomainConfig is supported in the SDK as of version 2.301.0 with this change: https://github.com/aws/aws-sdk-js/pull/2209.

Lambda's current supported version of the SDK is 2.290.0.  Details on all the supported versions are documented [here](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).

Your options are to wait until Lambda updates the SDK, or you could include a later version of the SDK to use in place of the Lambda provided package.

**Comment by dppower** [comment]
@srchase 
Thanks, I was thinking it might be to do with the version lambda uses. Calling the API directly like the code I show above works, so I'll keep using that for now.
