### ISSUE TITLE
Change User to AWSUser

### ISSUE THREAD

**Issue by jpike88** [aws/aws-sdk-js#2285]
The namespace 'User' is very common in projects, and my auto-import keeps suggesting the User object from aws-sdk references. Every time I have to choose the 6th option just to import our User class.

I suggest you guys give it a more unique namespace to not force devs to do it on their own projects

**Comment by srchase** [comment]
@jpike88 

Thanks for submitting this feedback.

Which editor/IDE are you using?

**Comment by jpike88** [comment]
VSCode

**Comment by srchase** [comment]
@jpike88 

Thanks for following up.

Prefixing every User definition with AWS is not a change that we will likely make.  At a minimum, it would be a breaking change and would require a major version bump.  Further, I'm not sure it would completely fix your concern.  Depending on how a specific editor/IDE's auto-import works, it could still suggest AWSUser when adding the User typing.

In your instance, it looks like you're importing your own package as a 1st party package.  If it were imported as a local package, you might see VSCode give it precedence in auto-import suggestions.  I did not find any documentation to confirm this however.

You may want to research if there is an extension for VSCode that would allow you to configure and modify the standard auto-import behavior to list your package first.
