### ISSUE TITLE
AWS Lambda function for upload/putObject image works only on local machine

### ISSUE THREAD

**Issue by ChenFeldman** [aws/aws-sdk-js#2287]
I have a lambda function which uses 'request' to get a stream of a file by URL and suppose to upload it to a bucket on s3. It is working perfectly on my local machine using node but not inside the lambda. After running the lambda, I have an empty file with the name I wanted.

Stuff you should know

- The lambda function is async
- The node version is 8.10
- In the example you see putObject, but I have also tried with upload
- Even when adding a manual sleep of 90-120 seconds to let the lambda run, the file is not uploaded
- I tried using context.succeed or callback('some result'), but it still did not work properly 

This is the relevant part of the code
```
module.exports.handler = async(event, context, callback) => {
  const path = 'bucketToUpload';
  const name = 'imageFileName.jpg';
  let options = {
    uri: responseUrl, // This is the url of the image
    encoding: null
  };
  let reqRes = await request(options); // Here I have the stream
  let awsPutRes = await s3.client.putObject({
    Body: reqRes.body,
    Key: name,
    Bucket: path
  }).promise();
};
```

Would really appreciate any help or directions for this issue.

**Comment by srchase** [comment]
Hello @ChenFeldman,

This doesn't look like an issue with the SDK, but with Lambda and reqeust.

I was able to get it working with request-promises-native instead though:

```
const req = require('request-promise-native');

async function upload(body) {
  let params = {
    Body: body,
    Key: 'imageFileName.jpg,
    Bucket: 'bucketToUpload'
  };
  await s3.putObject(params, function(err, data) {
    if(err) { console.log('error');
    } else { console.log('succes')}
  });
}

exports.handler = async (event) => {
  await req.get(myUrl)
  .then((response) => {
    upload(response)
  })
  .catch((err) => {
    console.log('error: ', err);
  })
};
```

**Comment by ChenFeldman** [comment]
Hey @srchase 

Thank you for trying to help.
I tried running you code with lambda but now it is also not putting an empty object after using putObject.

I am trying to figure out what am I missing here?

**Comment by srchase** [comment]
@ChenFeldman 

Can you try uploading something to s3 directly?  Even populating the body with some text will be a good test to see if you can successfully use putObject on the s3 bucket you're specifying.

Once you confirm that you're able to use putObject, you can introduce fetching the file using request-promise-native, and then put the two pieces together.

**Comment by ChenFeldman** [comment]
@srchase Will try it now and get back to you here

**Comment by ChenFeldman** [comment]
So after some more tries I was able to solve the issue.

Here is part of the code:

```

async function upload(fileStream, fileName, bucketName) {
      let params = {
        Body: fileStream,
        Key: fileName,
        Bucket: bucketName
      };
      await s3.client.putObject(params).promise();
    }

module.exports.handler = async(event, context) => {
      try {
        let s3UploadParams = {
          uri: imageDownloadUrl,
          encoding: null
        };
        let imageFileStream = await request(s3UploadParams);
        await upload(imageFileStream, s3FileName, bucketName);
      } catch (err) {
        context.fail(null, 'Error trying to upload to aws' + err);
      }
    }

```


Instead of using 'request' lib I am using 'request-promise-native' to get the stream from the url. (thanks for that @srchase )
And also using the .promise() of aws-sdk library to make it fully work.
