### ISSUE TITLE
Is is possible to use aws-sdk-js with react-native for authentication via secrets and certificates?

### ISSUE THREAD

**Issue by AntonSmatanik** [aws/aws-sdk-js#2288]
Is is possible to use aws-sdk-js with react-native for authentication via secrets and certificates?

With aws-iot-device-sdk I just set it like:

`awsIot.device({
    keyPath: awsConfig.broker.keyPath,
    certPath: awsConfig.broker.certPath,
    caPath: awsConfig.broker.caPath,
    host: awsConfig.broker.endpoint,
    clientId: uuid.v4(),
    baseReconnectTimeMs: awsConfig.broker.reconnect,
    maximumReconnectTimeMs: awsConfig.broker.maximumReconnect,
})`

Question is if something like this is possible with React Native...

**Comment by srchase** [comment]
Hello @AntonSmatanik,

Yes, this SDK works with React Native.  Check out the blog post by @chrisradek on [React Native Support](https://aws.amazon.com/blogs/developer/react-native-support-in-the-aws-sdk-for-javascript/).

[AWS Amplify](https://aws-amplify.github.io/amplify-js/media/quick_start) also works with React Native.

**Comment by AntonSmatanik** [comment]
That is nice, but is there some example how to set device with secrets and certificates?

**Comment by srchase** [comment]
@AntonSmatanik 

This SDK allows you to administer IoT Devices, but does not include any functionality to act as a device via MQTT.

AWS Amplify does include a PubSub module, but I suspect that might not fit your use case as you're wanting to use certificates for authentication.
