### ISSUE TITLE
Typescript Lambda Callback optional

### ISSUE THREAD

**Issue by shawnmclean** [aws/aws-sdk-js#2291]
I'm using `@types/aws-lambda`.

The `Handler` object specifies the `callback` param is optional but that is not the case with the typings file.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/index.d.ts#L761

I think it should be:

```
export type Handler<TEvent = any, TResult = any> = (
    event: TEvent,
    context: Context,
    callback?: Callback<TResult>,
) => void | Promise<TResult>;
```

**Comment by srchase** [comment]
@shawnmclean 

Was this issue meant to be opened on the DefinitelyType repository?

**Comment by shawnmclean** [comment]
I'm not sure. It's a repository that stems from the code in this repo. What I understood from their repo is to reach out to the original maintainers.

**Comment by srchase** [comment]
@shawnmclean 

@types/aws-lambda is maintained by the community in the DefinitelyTyped repository.  Their maintained definitions are not something that can be fixed on the aws-sdk side.

You are correct that callback param is optional though.
