### ISSUE TITLE
Typescript definitions incompatible in v2.330.00

### ISSUE THREAD

**Issue by ztzven** [aws/aws-sdk-js#2292]
Definition object looks like this:

```javascript
import * as AWS from "aws-sdk";
export declare class Notification {
    private sns;
    constructor(sns: AWS.SNS);
}
```

However when instantiating like so
```javascript
new Notification(new AWS.SNS())
```

I get the following type definition error
```
[ts]
Argument of type 'AWS.SNS' is not assignable to parameter of type 'import("/.../node_modules/sqs-client/node_modules/aws-sdk/clients/sns").Types'.
  Types of property 'defineService' are incompatible.
    Type '(serviceIdentifier: string, versions: string[], features?: any) => typeof AWS.Service' is not assignable to type '(serviceIdentifier: string, versions: string[], features?: any) => typeof import("/.../node_modules/aws-sdk/lib/service").Service'.
      Type 'typeof AWS.Service' is not assignable to type 'typeof import("/.../node_modules/sqs-client/node_modules/aws-sdk/lib/service").Service'.
```

**Comment by chrisradek** [comment]
@ztzven 
Did your types work with a previous version of the SDK? Can you share which version of TypeScript you are using?

**Comment by ztzven** [comment]
Currently using typescript v3.1.0.. types seemed to worked with v2.282.1 however a similar definition using SQS seems to be broken using v2.282.1.

Could the issue be local?

**Comment by chrisradek** [comment]
I'm wondering if it has to do with the version of TypeScript. Can you try using version 3.0?

**Comment by ztzven** [comment]
Ahh found it, typescript version wasn't the issue.

The module that `Notification` resided in specified sdk v2.298.0, yet the project used v2.330.0.

This seemed to have type incompatibilities.

Should be okay to mark as closed.

**Comment by chrisradek** [comment]
@ztzven 
Glad to hear it!
