### ISSUE TITLE
HTTPOptions cannot be configured for AssumeRole credentials (apart from globally)

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-sdk-js#2298]
We got this report (https://github.com/awslabs/aws-cdk/pull/898) about assume role credentials not working when a proxy was configured.

We were configuring the proxy by passing additional `httpOptions` to every service client constructor, because configuring it globally makes me uneasy. It could be a convenience but should not be a necessity, especially if I want to combine differently-configured AWS clients in my application.

Unfortunately, there is no way of passing `httpOptions` to the STS client that's being used for the assume-role operation:

https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/shared_ini_file_credentials.js#L209

So this is effectively not configurable right now.

**Comment by rix0rrr** [comment]
Ping?

**Comment by srchase** [comment]
This has been implemented. Closing this issue.
