### ISSUE TITLE
Feature request: HTTP2 support 

### ISSUE THREAD

**Issue by mattheworiordan** [aws/aws-sdk-js#2300]
[Node.js supports HTTP2](https://nodejs.org/api/http2.html), and it appears the Lambda endpoints now too support HTTP2 (see below).

It would be considerably more efficient if it were possible to invoke Lambda functions using HTTP2 to avoid needless TLS handshakes and high concurrent of TCP/IP connections for HTTP/1.1 support.

Is there any plan to add HTTP2 support to this library any time soon?

---

```
$ curl --verbose https://lambda.us-east-1.amazonaws.com
* Rebuilt URL to: https://lambda.us-east-1.amazonaws.com/
*   Trying 52.5.91.208...
....
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fa311006600)
> GET / HTTP/2
> Host: lambda.us-east-1.amazonaws.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 403
< date: Mon, 15 Oct 2018 11:57:58 GMT
< content-length: 127
< x-amzn-requestid: 8f59aa36-d071-11e8-8fd1-0558df7ee5f8
<
```

**Comment by srchase** [comment]
Thanks for submitting this request.

This is a feature that we're considering for the next major version of the SDK.

**Comment by mattheworiordan** [comment]
Any ETA on the next major version release?

**Comment by mattheworiordan** [comment]
I see the Java SDK now supports HTTP/2, see https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-http2.html.  Any update on when HTTP/2 support may surface in Node?

**Comment by baobo5625** [comment]
+1

**Comment by felops** [comment]
The newly [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3) supports HTTP2. From aws blog:
> We also added many other features, which we are planning to cover in detail in future blog posts:
> - ...
> - Support for HTTP/2

Source: https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available

**Comment by mattheworiordan** [comment]
> The newly aws-sdk-js-v3 supports HTTP2. From aws blog:

Woop

**Comment by hakan-bilgin** [comment]
@mattheworiordan did you succeed to use HTTP2 on the browser with new sdk v3? I use [this](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_fetch_http_handler.fetchhttphandler-1.html) handler to on the browser but it sends HTTP 1.1 requests. If the aws client is in node.js environment there is two options [http](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_node_http_handler.nodehttphandler-1.html) and [http2](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_node_http_handler.nodehttp2handler-1.html)

**Comment by clhuang** [comment]
if you look at the code for @aws-sdk/client-lambda, it still doesn't use HTTP/2, and attempting to just directly use the NodeHttp2Handler doesn't work: https://github.com/aws/aws-sdk-js-v3/issues/3292; I also detail a workaround in that ticket.

It appears there are some implementation details with the Lambda service HTTP/2 server that don't play well with the NodeHttp2Handler in @aws-sdk.
