### ISSUE TITLE
CloudFormation waitfor stackUpdateComplete failing when update completes

### ISSUE THREAD

**Issue by bamapookie** [aws/aws-sdk-js#2301]
I am using AWS SDK for JavaScript version 2.200, and as of 7 days ago, the call worked fine.  Now it fails in about 30 seconds following invocation.  I updated to 2.334, and the stack update runs and completes after about 2 minutes.  Then the waitfor fails as the stack completes.  I am not using any non default timeouts or delays.

Command that is failing:
```
CF.waitFor('stackUpdateComplete', {StackName: existingStackId})
```

Error message:
```
{
    "errorMessage": "Resource is not in the state stackUpdateComplete",
    "errorType": "Error"
}
```

The stack does indeed complete successfully, and is in the state `UPDATE_COMPLETE`.

**Comment by srchase** [comment]
Hello @bamapookie 

Thanks for submitting this issue.

Does the call work with v2.293.0?  How about v2.292.0?

**Comment by bamapookie** [comment]
Noooooooo!  Intermittent problem!  I tried it again in another environment with the latest version, 2.334.0.  It succeeded once and failed once.  (I am updating a number of sibling stacks, and it stops when one fails.)  I then rolled back to 2.293.0 and tried again.  Failed.  Then I rolled back to 2.292.0.  Succeeded twice, then failed.  All of these sibling stacks are essentially the same.  All the CF stacks complete just fine, ending up in `UPDATE_COMPLETE` status with no errors, but the javascript seems to think that they are failing.

**Comment by bamapookie** [comment]
I can reproduce it pretty reliably with that code.  It always creates the stack.  If I uncomment the waitfor's, they always fail.

**Comment by srchase** [comment]
That's the same error you get if you submit an invalid or unknown stack name:

CF.waitFor('stackCreateComplete', {StackName: 'some unknown stack name'}).promise())

In your code, the waitFor is sometimes getting called before createStack call has been completed.

Can you try something like this?

```
const AWS = require('aws-sdk'),
  CF = new AWS.CloudFormation({region: 'us-west-2'}),
  UUID = require('uuid/v4');

let stackName = `TempStack-${UUID()}`;
console.log(`Stack name: ${stackName}`);

const params = {
  StackName: stackName,
  DisableRollback: false,
  EnableTerminationProtection: false,
    TemplateBody: `AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SampleResource:
    Type: AWS::CloudFormation::WaitConditionHandle
    Metadata:
      Comment: Dummy resource
      StackTime: ${new Date().getMilliseconds()}`}

const createStackPromise = CF.createStack(params).promise()

createStackPromise.then(function(data) {
  console.log('stack creation started')
  const waitForPromise = CF.waitFor('stackCreateComplete', {StackName: stackName}).promise();
  waitForPromise.then(function(data) {
    console.log('stack creation completed')
  }).catch(function(err) {
    console.log(err)
  })
}).catch(function(err) {
  console.log(err)
})
```

**Comment by bamapookie** [comment]
I left out some `() => `'s in front of the waitFor calls.  Now I can't get it to fail, even though I haven't changed my actual code that was failing.

**Comment by srchase** [comment]
Does the change I suggested also work for you?

**Comment by bamapookie** [comment]
That was just another way of making the call a properly chained promise.
It was different from the way I have it implemented in the private code
that was failing.  Either way, I can't get the old code to fail now.

**Comment by srchase** [comment]
As it's no longer failing, I'm going to close out this issue.  If you see this crop back up in a reliable way, let us know and we'll be happy to re-open.
