### ISSUE TITLE
S3: Cannot get or put objects starting with `soap/`

### ISSUE THREAD

**Issue by gpittarelli** [aws/aws-sdk-js#2302]
Using the AWS console, I created a public test bucket named `soap-path-test` with an object with key `soap/a.txt` with 21 bytes of content. This object cannot be retrieved with the js SDK:
```
aws = require('aws-sdk')
aws.VERSION // => '2.335.0'
s3 = new aws.S3()
req = s3.getObject({Bucket: 'soap-path-test', Key: 'soap/a.txt'}, (e, d) => {console.log('err:', e, 'body:', d);})
// => err: null body: { ContentLength: 0, Metadata: {}, Body: <Buffer > }
req.response.httpResponse.statusCode // => 200

// Works with s3ForcePathStyle: true
s3 = new aws.S3({s3ForcePathStyle: true})
req = s3.getObject({Bucket: 'soap-path-test', Key: 'soap/a.txt'}, (e, d) => {console.log('err:', e, 'body:', d);})
// => err: null body: { ContentLength: 21, /* ... good data */ }
req.response.httpResponse.statusCode // => 200
```
Note it returns a 200, but an empty body unless `s3ForcePathStyle` is manually specified.

The HTTP API responds to this in the following ways:

 - `GET https://soap-path-test.s3-us-west-1.amazonaws.com/soap/a.txt` => Returns 200 and empty body
 - `GET https://s3-us-west-1.amazonaws.com/soap-path-test/soap/a.txt` => Returns 200 and the real body

And for a non-existent file:

 - `GET https://soap-path-test.s3-us-west-1.amazonaws.com/soap/d.txt` => Returns 200 and empty body
 - `GET https://s3-us-west-1.amazonaws.com/soap-path-test/soap/d.txt` => Returns 404 and xml error message

The issue seems to be here: https://github.com/aws/aws-sdk-js/blob/9ef04224bb4b3da437be039c19d4b25a08dc7a6e/lib/services/s3.js#L207
the library should use the path-style requests if the key being requested starts with `soap/`

Related, but unresolved: https://forums.aws.amazon.com/thread.jspa?threadID=73717

**Comment by srchase** [comment]
Thanks for opening this issue.

This is a known issue that the S3 Service Team is reviewing.

**Comment by srchase** [comment]
I'm going to close this issue for now.  The Service Team needs to make the change on their end in order to resolve this issue.  You're welcome to engage that team on the AWS Developer Forums if you have additional questions.
