### ISSUE TITLE
Occasionally getting this AccessDenied (403) and file not found error(404) using getSignedUrl

### ISSUE THREAD

**Issue by m-athar** [aws/aws-sdk-js#2306]
First I'm getting signedUrl and then sending a put request to upload an image to AWS. Most of the time it works fine but occasionally it starts returning 403 on get request using getSignedUrl and then 404 error on put request. I'm using synchronous call i.e no call back function as i'm using static information in the config file. Following is my code

`  yield async dispatch => {
    try {
      // get signed upload image url
      const urlData = await APICall({
        method: 'get',
        url: `/images/uploadURL`,
        params: {
          hash: imageData.hash,
          mime: imageData.mime
        }
      });
      if (urlData.uploadUrl) {
        // upload image to signed url
        await APICall({
          method: 'put',
          url: urlData.uploadUrl,
          payload: data,
          headers: { 'Content-Type': imageData.mime }
        });
      }` 

And following is the method from which i'm getting SignedUrl

` getUploadUrl(key, mime) {
    const params = {
      Bucket: this._bucketName,
      Key: key,
      ACL: 'public-read',
      Expires: _.get(this._config, 'signedURLExpiration', AWS_SIGN_URL_EXPIRATION_TIMEOUT),
      ContentType: mime
    };
    return this._s3.getSignedUrl('putObject', params);
  }`

**Comment by srchase** [comment]
Hello @m-athar,

Thanks for opening this issue.

Which version of the SDK are you using?  Can you provide any additional details about the environment you're using when you get these errors?

**Comment by m-athar** [comment]
Hi @srchase  ,
Appreciate your response. 
I'm using node js.  Also the version of aws-sdk is: ^2.88.0.

**Comment by srchase** [comment]
Here are a couple of suggestions to check:

Do the content-types match?  Does it work if you remove the content-type?

Has the URL expired in any of these cases?  I'm not sure what you're using for AWS_SIGN_URL_EXPIRATION_TIMEOUT.

**Comment by m-athar** [comment]
I'm using 10 seconds of time out. Let me remove the content-types , run it and test it again. Will update on this thread.

**Comment by m-athar** [comment]
@srchase  He, 
I removed the content type and it gave like the previous mention error 1 time out of like 60 times. Which is some progress I guess,  but I need to specify the content type so Images on the AWS is properly saved along with specific content type. Is there any other way around this error??

**Comment by srchase** [comment]
Do you get an errors with a longer timeout?

**Comment by m-athar** [comment]
I increased the expiration time to 1000 seconds but still getting the same 403 and 404 error as described above.

**Comment by srchase** [comment]
What environment are you using for these requests?  What version of the SDK are you using?

**Comment by szulfiqar** [comment]
@srchase  I'm using node js environment and the version of **SDK** is :^**2.88.0**.

**Comment by m-athar** [comment]
@srchase  I'm using node js environment and the version of **SDK** is **^2.88.0**

**Comment by srchase** [comment]
Is there any pattern to when you see the failures vs when the upload succeeds?  Do you get failures for specific files only?  Or file types?  Or uploads at specific times?

**Comment by srchase** [comment]
@m-athar,

Which error did that return?  Could you provide the error and stacktraces you have received?

**Comment by m-athar** [comment]
@srchase  only this is the information I'm getting in my console. 

![capture](https://user-images.githubusercontent.com/38557458/47780961-60f18b00-dd1e-11e8-90c6-d065a937a79c.PNG)

**Comment by m-athar** [comment]
"Error: Forbidden
    at Request.<anonymous> (http://szulfiqar.getvela.com:3000/client.js:49842:20)
    at Request.Emitter.emit (http://szulfiqar.getvela.com:3000/client.js:50462:21)
    at XMLHttpRequest.xhr.onreadystatechange (http://szulfiqar.getvela.com:3000/client.js:50130:11)
From previous event:
    at APICall (http://szulfiqar.getvela.com:3000/client.js:49332:19)
    at callee$1$0$ (http://szulfiqar.getvela.com:3000/client.js:406096:79)
    at tryCatch (http://szulfiqar.getvela.com:3000/client.js:23900:41)
    at Generator.invoke [as _invoke] (http://szulfiqar.getvela.com:3000/client.js:24162:23)
    at Generator.prototype.(anonymous function) [as next] (http://szulfiqar.getvela.com:3000/client.js:23933:22)
    at tryCatch (http://szulfiqar.getvela.com:3000/client.js:23900:41)
    at invoke (http://szulfiqar.getvela.com:3000/client.js:23974:21)
    at http://szulfiqar.getvela.com:3000/client.js:23982:14"

**Comment by srchase** [comment]
Which console is this?  Is this from a browser?

**Comment by m-athar** [comment]
yes it's from browser...

**Comment by srchase** [comment]
Can you try to use the presigned URL to make PUTs using Node instead of the browser?

As the presigned URLs do mostly work, this seems to be an issue between the browser and the S3 service.  If your internet connection is inconsistent, or you have high latency, the browser's connection may close, resulting in intermittent errors.

**Comment by m-athar** [comment]
@srchase 
Following is my presigned Url code which i'm using to get url, 
`  getUploadUrl(key, mime) {
    const params = {
      Bucket: this._bucketName,
      Key: key,
      ACL: 'public-read',
      Expires: _.get(this._config, 'signedURLExpiration', AWS_SIGN_URL_EXPIRATION_TIMEOUT),
      ContentType: mime
    };
    return this._s3.getSignedUrl('putObject', params);
  }`
Following is the request url which is generated 
Request URL: https://s3-us-west-1.amazonaws.com/[bucket-name]/cd461bc0417f454d3b6d26236a94a62b8d13a53d?AWSAccessKeyId=[accesskey]&Expires=1541396225&Signature=[signature]&x-amz-acl=public-read

and after that I use put method with above url to upload the image, but it gives 
<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Expires>2018-11-05T05:37:05Z</Expires><ServerTime>
this error... And sometimes it works totally fine

**Comment by srchase** [comment]
Do you get the same error if you use a node script (and not the browser) to upload the files?

Using a node script to upload with a presigned url will help to determine if there is an issue with the browser or now.

**Comment by szulfiqar** [comment]
Ahan let me give it a try..
