### ISSUE TITLE
ECONNRESET NetworkingError When Assume Role STS

### ISSUE THREAD

**Issue by maryalfredkamel** [aws/aws-sdk-js#2307]
I'm Trying to **AssumeRole** using **aws-sdk** **NodeJS** on Lambda to get temporary credentials to access cross account, _lambda have permission to assume role and i tried it using aws-sdk for .net core and its working_, but for  Lambda RunTime **_Node.js 8.10_**  i got the following error:

>{ Error: read ECONNRESET
at _errnoException (util.js:1022:11)
at TLSWrap.onread (net.js:628:25)
message: 'read ECONNRESET',
code: 'NetworkingError',
errno: 'ECONNRESET',
syscall: 'read',
region: 'us-east-1',
hostname: 'sts.amazonaws.com',
retryable: true,
time: 2018-10-14T16:42:47.474Z } 'Error: read ECONNRESET\n at _errnoException (util.js:1022:11)\n at TLSWrap.onread (net.js:628:25)'

the following code snippet for assuming role:
```
var AWS = require('aws-sdk');
var sts = new AWS.STS();
 
var self = module.exports = {
AssumeRole: function (RoleArn, callback) {
    return new Promise((resolve, reject) => {
      var params = {
        RoleArn: RoleArn,
        RoleSessionName: "SubAccount",
        DurationSeconds: 300
      };
      sts.assumeRole(params, function (err, data) {
        if (err) {
          console.log(err, err.stack);
          reject(new Error('Could not assume role'));
        }// an error occurred
        else {
          console.log(data); // successful response
          resolve(data)
        }
      })
    });
  }
}
```

**Comment by srchase** [comment]
@maryalfredkamel 

Do you get a ECONNRESET error every time you make the call with Node.js?  Or is this intermittent?

**Comment by maryalfredkamel** [comment]
Yes every time I'm calling assume role
But any other calls to aws features is working fine.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by srchase** [comment]
I tried replicating your code.  I have not received an ECONNRESET error, but did get this:

ValidationError: 1 validation error detected: Value '300' at 'durationSeconds' failed to satisfy constraint: Member must have value greater than or equal to 900

The ECONNRESET error seems more like a transient error on the STS service.  When did you get that error?

**Comment by maryalfredkamel** [comment]
I got it last Sunday and until today?
Also from. Net SDK it's working fine.


Regarding duration it was just a try but I didn't even get the same error

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by srchase** [comment]
Can you inspect the differences between your .NET and JavaScript requests to STS?  I'm curious if that would give us any clues as to why one is working and the other is not.

**Comment by maryalfredkamel** [comment]
Nothing is different, same role for the lambda, same role I'm assuming, same parameters
The difference is SDK only

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by maryalfredkamel** [comment]
Just Solve it by execluding aws-sdk from the installed packages and depend on aws-sdk inside lambda it self

**Comment by mkulgeorge** [comment]
Can any one explain what this statement means "depend on aws-sdk inside lambda it self"?

I am trying to invoke a lambda function from a lambda function.
**Scenario 1**
 If I am calling from a lambda function which is not assigned to any VPC/Subnet/SG it works fine.
**Scenario 2**
If I am calling from a lambda function which is assinged to VPC/Subnet, then I am getting the below error.
```
{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:628:25)
  message: 'read ECONNRESET',
  code: 'NetworkingError',
  errno: 'ECONNRESET',
  syscall: 'read',
  region: 'eu-central-1',
  hostname: 'lambda.eu-central-1.amazonaws.com',
  retryable: true,
 time: 2019-05-07T11:28:03.010Z }
```
