### ISSUE TITLE
CloudFront signer issue dealing with single quote in content-disposition

### ISSUE THREAD

**Issue by lsholubka** [aws/aws-sdk-js#2308]
There seems to be an issue in CloudFront signer when passing content-disposition header with single quotes in it.

If I sign url with `'` not encoded (encodeURIComponent doesn't encode `'`):

``` `?response-content-disposition=${encodeURIComponent(`attachment; filename="${fileName}"`)}` ```

Then latest Chrome, Safari and Firefox get access denied, because those automatically encode `'` as `%27` in all requests. Edge/IE works ok.

If I sign url with `'` encoded:

``` `?response-content-disposition=${encodeURIComponent(`attachment; filename="${fileName}"`).replace(/'/g, '%27')}` ```

Then it works in Chrome, Safari and Firefox, but the downloaded file name will contain `%27` instead of `'`, because seems like CloudFront signer is not decoding it when signing.

S3 signer works as expected.

**Comment by srchase** [comment]
@lsholubka,

Can you share the code snippet of how you are passing in that content-disposition header?

**Comment by lsholubka** [comment]
@srchase 

```
    const url = `${configs.downloads.url}/${s3Path}/${file}` +
      `?response-content-disposition=${encodeURIComponent(`attachment; filename="${fileName}"`)}`;
    const signer = new AWS.CloudFront.Signer(
      config.key_pair_id,
      config.private_key,
    );
    const expires = 3000;
    return signer.getSignedUrl({
      url,
      expires,
    });
```

**Comment by srchase** [comment]
Thanks for responding with this.  How are you using content-disposition with the S3 Signer?

**Comment by lsholubka** [comment]
```
    const downloadIframe = $('<iframe>', { src: signResponse.signedRequest });
    downloadIframe.hide().appendTo('body');
```

**Comment by lsholubka** [comment]
sorry, that was how I use it in the browser. Here is s3 signer:

```
    const s3Params = {
      Bucket: bucket,
      Key: `${s3Path}/${file}`,
      Expires: 30000,
      ResponseContentDisposition: `attachment; filename="${fileName}"`,
    };
    const s3 = AwsHelpers.getS3(configs);
    return s3.getSignedUrl('getObject', s3Params);
```

**Comment by srchase** [comment]
@lsholubka 

It seems there are two issues we need to resolve:

1.  The signer should handle encoding a plain url, which it does, but results in an invalid signature when the url includes response-content-disposition:

Passing in this url (double quotes):
```https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment;filename="foobar.txt"```

Returns this (non-working) signed url:
```https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment%3Bfilename%3D%22foobar.txt%22&Expires=1540047153&Key-Pair-Id=...&Signature=...```

Passing in this url (single quotes):
```https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment;filename='foobar.txt'```

Returns this (improperly encoded) signed url:
```https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment%3Bfilename%3D'foobar.txt'&Expires=1540047153&Key-Pair-Id=...&Signature=...```

2. If the signer is passed an encoded url, the signed result will work, as long as it does not contain encoded single quotes:

Passing in this url with single quotes:
```https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment%3Bfilename%3D%27foobar.txt%27```

Returns this improperly encoded url:
```https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment%3Bfilename%3D'foo.txt'&Expires=1540047153&Key-Pair-Id=...&Signature=...```

However, passing in an encoded URL with double quotes:
```https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment%3Bfilename%3D%22foobar.txt%22```

Returns a properly encoded url with a valid signature:
```https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment%3Bfilename%3D%22foo.txt%22&Expires=1540047153&Key-Pair-Id=...&Signature=...```

Does that match what you've seen?  We'll take a look at getting this fixed.

**Comment by lsholubka** [comment]
@srchase 
The issue I'm seeing is when file name contains single quote in it, but I guess it is the same one you are describing in scenario 2.

Passing in this url with everything encoded except `'`:
https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment%3Bfilename%3D%22foo'bar.txt%22

Returns this encoded url (which works only in IE/Edge because these browsers do not automatically encode `'` in the requests):
https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment%3Bfilename%3D%22foo'bar.txt%22&...

Passing in an encoded URL, including encoded `'`:
https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment%3Bfilename%3D%22foo%27bar.txt%22

Returns a properly encoded url with a valid signature, but downloaded file name will contain `%27` instead of `'`:
https://foo.cloudfront.net/foo.txt?response-content-disposition=attachment%3Bfilename%3D%22foo%27bar.txt%22&...

**Comment by srchase** [comment]
Regarding the single quotes, the RFC indicates that double-quotes should be used for content-disposition filenames: [rfc2616](https://tools.ietf.org/html/rfc2616#section-2.2), so no action on that part of this.  Stick with double-quotes when setting the content-disposition.

**Comment by lsholubka** [comment]
@srchase sorry, I think I was not very clear, I was always using double quotes to surround file name, the issue is caused by single quote in the name itself, which I cannot replace because that will change the original file name. I am not sure that [encoding params before signing](https://github.com/srchase/aws-sdk-js/commit/95b70d3f5728cb8058059c120e50091165041646) will fix it because `encodeURIComponent` doesn't encode single quotes, but we can give it a try. Thank you.

**Comment by srchase** [comment]
@lsholubka 

I agree, this will not solve your issue for single quotes in the original filenames.

You may want to refer to [rfc6266](https://tools.ietf.org/html/rfc6266) as well, but I'm not sure that Content-Disposition and the various browsers implementations of it that feature will work the way you're needing.

**Comment by srchase** [comment]
A change to the documentation was merged to help make this more clear.  Going to close out this issue.
