### ISSUE TITLE
Add getSignedUrl method for CloudFront

### ISSUE THREAD

**Issue by jasonsims** [aws/aws-sdk-js#231]
Currently there is only functionality for signing direct S3 links. The process is a lot more complicated if you have a CloudFront distribution and also want to serve up signed links. A method that accepts your key-pair and link expiration epoch and returns a signed URL would be awesome.

http://stackoverflow.com/questions/21521302/creating-signed-s3-and-cloudfront-urls-via-the-aws-sdk

**Comment by aseemk** [comment]
(Hat-tip to my colleague @chanadian for finding this.)

It'd be great if you guys could mention this lack of feature in the docs, and link to this module and/or issue. Thanks folks!
