### ISSUE TITLE
Minimum Number of Tasks, ECS

### ISSUE THREAD

**Issue by CrlsPerez** [aws/aws-sdk-js#2319]
I want to know if it is possible in any way to update this field **Minimum Number of Tasks**.

Why ? Because I have problems with the balancer that I have linked to the service.

From the SDK, I can change the **desired tasks** field which is fine, but the tasks created are stopped by the alarms that I have in Cloudwatch.

What I see is that I have to update the two so that they do not stop, I tested it on the console.

How can edit this field in my service of my cluster on ecs?

Or another ways to add task to my service.

-- I know that my service is going to receive many requests, that's why I've been creating the tasks before.

Events of my service.
[https://imgur.com/a/e7orPHq](https://imgur.com/a/e7orPHq)

**Comment by srchase** [comment]
Hello @CrlsPerez,

Have you looked at minimumHealthyPercent?

That, along with the desiredCount will determine how many tasks remain in the running state and how the balancer distributes traffic.

If you have specific ECS usage questions, you may want to refer to the [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=187).

**Comment by CrlsPerez** [comment]
> Hello @CrlsPerez,
> 
> Have you looked at minimumHealthyPercent?
> 
> That, along with the desiredCount will determine how many tasks remain in the running state and how the balancer distributes traffic.
> 
> If you have specific ECS usage questions, you may want to refer to the [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=187).

Yes.
But I think this is not my problem, i have the default values 50, 200.

**Comment by srchase** [comment]
I apologize, but I'm not sure I completely follow based on the image.

The ECS API does not allow the minimum number of tasks to be set, so the SDK itself cannot help set that number either.

**Comment by CrlsPerez** [comment]
> I apologize, but I'm not sure I completely follow based on the image.
> 
> The ECS API does not allow the minimum number of tasks to be set, so the SDK itself cannot help set that number either.

Oh ok, maybe I need to elavorate "custom alarms" in lambda or something like that.

One basic example:

In one service of ECS i have...

Minimum tasks: 1
Desired Taks: 1
Autoscaling Policy: Average < 30% CPU, remove one task

When I use the sdk and change the desired count to 2, some minutes/seconds the alarm in cloudwatch is set to "alarm" and the new tasks are removed (Those tasks dont have a ready status yet).

Exist a way to change the desired count in one service of ECS and not trigger the alarm, I prevent many request for that I increment the tasks but the use is low when I make the change.

**Comment by srchase** [comment]
If you have followup questions, I suggest you check out the [AWS Developer Forums for ECS](https://forums.aws.amazon.com/forum.jspa?forumID=187).  As far as I can tell, the SDK is working as expected.  If you are seeing any behavior that would suggest an issue with the SDK, let us know and we can re-open this issue to investigate.
