### ISSUE TITLE
S3.getObject doesn't return metadata or WebsiteRedirectLocation

### ISSUE THREAD

**Issue by Peksa** [aws/aws-sdk-js#232]
I'm using aws-sdk-2.0.0-rc9 in the browser and I'm trying to put and get objects together with metadata and/or WebsiteRedirectLocation without much success.

``` javascript
bucket.getObject({ Key: key }, function(err, response) {
  // response.WebsiteRedirectLocation is undefined
  // response.Metadata is an empty object
  // this.httpResponse.headers only contains 3 headers: 
  // Cache-Control, Content-Type & Last-Modified
}
```

If I look at the request the appropriate headers seem to have been sent:

```
Request URL:https://s3-eu-west-1.amazonaws.com/pek.so/about
Request Method:GET
Status Code:200 OK

x-amz-meta-url:http://peksa.se
x-amz-request-id:CC30069BAA417533
x-amz-website-redirect-location:http://peksa.se
```

It looks a bit similar to #52..

Am I doing something wrong or is this a bug?

**Comment by alexpearce92** [comment]
@msafi 

What is the "file" that you are referring to in:

.putObject({
  Bucket: bucketName,
  Key: file.key,
  Body: file.body,
  ContentType: file.type,
  ACL: file.acl,
  Metadata: { 'foobar': JSON.stringify(file.metadata) }
})

**Comment by msafi** [comment]
@alexpearce92 it is just a simple JS object

**Comment by alexpearce92** [comment]
@msafi 
Thanks for the quick reply. 
I am trying to replicate what you explained above by exposing one of my meta headers, x-amz-meta-type. I successfully exposed it in my CORS and am currently trying to implement the above code. However, I'm at a loss as to what I try to JSON.stringify(). Here is my current setup:

```javascript
bucket = new AWS.S3({
  params: {
    Bucket: 'myBucket',
    Key: 'myKey',
    Metadata: {
      'type': JSON.stringify(?)
    }
  }
});
var url = bucket.getSignedUrl('putObject');
console.log('The URL is', url);

```
If you could give me any input I would greatly appreciate it.

**Comment by msafi** [comment]
@alexpearce92 It looks to me that you're specifying the file meta-data in the AWS.S3 constructor configurations. As far as I understand, meta-data is per file, so you wanna specify it in your putObject request.

**Comment by alexpearce92** [comment]
@msafi 
I guess I may be going about this the wrong way then. My goal is to read the x-amz-meta-type of each file in an s3 folder in order to organize them by the returned meta-type, which will be accomplished by looping through all of the files and performing a putObject. 
I was attempting to retrieve the value of meta-type in a url so that I could substring the value out of the url and organize my files that way.
Do you know of or is there already a thread about a better way of extracting meta tags from several files?

**Comment by alexpearce92** [comment]
Answered my own question. I was able to get it to work by switching to putObject:

```javascript
                s3 = new AWS.S3();
                var params = {
                    Bucket: 'myBucket',
                    Key: 'myFileName',
                };
                s3.getObject(params, function(err, data){
                    if (err) {
                        console.log("error: " + err.code);
                    } else {
                        console.log(this.httpResponse.headers['x-amz-meta-type']);
                    }
                });
```
Thanks for the help @msafi

**Comment by lsegal** [comment]
@alexpearce92 you should not be using `getObject()` if you just want to access metadata. Use `headObject()` instead. Your data will be in the `Metadata` property of the response.
