### ISSUE TITLE
TypeError: AWS.S3 is not a constructor

### ISSUE THREAD

**Issue by Nop0x** [aws/aws-sdk-js#2321]
Hey there!

I'm currently running into a problem with our backend.

While uploading CSV files to S3 I out of the sudden get the following error without changing any code:

> AWS.S3 is not a constructor

My Sourcecode:
```javascript
var AWS = require('aws-sdk');
var s3 = new AWS.S3();
// return a promise
return s3.upload({
   Bucket: 'xxx-xxx-xxx',
   ACL: 'private',
   Key: `${project.value}/f${fFile.id}_${fileName}${extension}`,
   Body: buffer,
}).promise();
```

And this part of the function is called like this:

```javascript
const {Location, ETag, Bucket, Key} = await uploadFileToS3(
        app,
        project,
        file,
        fFile);
```
Node Version: v8.12.0
AWS SDK Version: aws-sdk@2.341.0

Any idea what this could mean and how to fix it?

Thanks in advance,

Marvin (Nop0x)

**Comment by srchase** [comment]
@Nop0x 

Can you provide the rest of the uploadFileToS3 function?

**Comment by Nop0x** [comment]
@srchase 

```javascript
  const uploadFileToS3 = (app, project, file, fFile, options = {}) => {
    // turn the file into a buffer for uploading
    const buffer = readFileSync(file.path);

    // generate a new random file name
    const fileName = options.name || String(Date.now());

    // the extension of the file
    const extension = extname(file.path);
    letAWS = require('aws-sdk');
    let s3 = new AWS.S3();
    // return a promise
    return s3.upload({
      Bucket: 'xxx-xxx-xxx',
      ACL: 'private',
      Key: `${project.value}/f${fFile.id}_${fileName}${extension}`,
      Body: buffer,
    }).promise();
  };
```

this is the full code, as requested

**Comment by srchase** [comment]
@Nop0x 

Does this work by itself?

```
const AWS = require('aws-sdk');
const s3 = new AWS.S3();
console.log(s3);
```

Can you also re-install the SDK?

**Comment by Nop0x** [comment]
@srchase 
Did as you requested and put the code in a new file:

> Service {
>   config: 
>    Config {
>      credentials: null,
>      credentialProvider: CredentialProviderChain { providers: [Array] },
>      region: 'us-east-1',
>      logger: null,
>      apiVersions: {},
>      apiVersion: null,
>      endpoint: 's3.amazonaws.com',
>      httpOptions: { timeout: 120000 },
>      maxRetries: undefined,
>      maxRedirects: 10,
>      paramValidation: true,
>      sslEnabled: true,
>      s3ForcePathStyle: false,
>      s3BucketEndpoint: false,
>      s3DisableBodySigning: true,
>      computeChecksums: true,
>      convertResponseTypes: true,
>      correctClockSkew: false,
>      customUserAgent: null,
>      dynamoDbCrc32: true,
>      systemClockOffset: 0,
>      signatureVersion: 's3',
>      signatureCache: true,
>      retryDelayOptions: {},
>      useAccelerateEndpoint: false,
>      clientSideMonitoring: false },
>   isGlobalEndpoint: false,
>   endpoint: 
>    Endpoint {
>      protocol: 'https:',
>      host: 's3.amazonaws.com',
>      port: 443,
>      hostname: 's3.amazonaws.com',
>      pathname: '/',
>      path: '/',
>      href: 'https://s3.amazonaws.com/' },
>   _events: 
>    { apiCallAttempt: [ [Function: EVENTS_BUBBLE] ],
>      apiCall: [ [Function: CALL_EVENTS_BUBBLE] ] },
>   MONITOR_EVENTS_BUBBLE: [Function: EVENTS_BUBBLE],
>   CALL_EVENTS_BUBBLE: [Function: CALL_EVENTS_BUBBLE],
>   _clientId: 1 }

Reinstalled the SDK in my main application, didnt fix it.

**Comment by Nop0x** [comment]
Can be closed, I fixed it.

**Comment by srchase** [comment]
Thanks for following up.

**Comment by Guss42** [comment]
@Nop0x, can you explain how you solved this issue, I run actually through the same issue, and after a day of research nothing new, I will be glad to see how you have done.

**Comment by Nop0x** [comment]
@Guss42 
I actually instanced S3 multiple times inside my application. Moving the S3 constructor to a central global variable fixed it.
