### ISSUE TITLE
IAM policy for S3 bucket doesn't see Cognito's federated identity

### ISSUE THREAD

**Issue by OskarKaminski** [aws/aws-sdk-js#2324]
I set my Cognito Federated Identities to support FB app.

My code:
```javascript
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'us-east-1:{myID}',
    Logins: {
        'graph.facebook.com': this.state.tokenFb
    }
});
const S3 = new AWS.S3({apiVersion: '2006-03-01'});
S3.putObject(params);
```

My IAM role associated with the Cognito Federated Identity:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "cognito-identity:*",
                "s3:ListAllMyBuckets",
                "mobileanalytics:PutEvents",
                "s3:HeadBucket",
                "cognito-sync:*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::squad-health-check",
                "arn:aws:s3:::squad-health-check/${graph.facebook.com:id}/*"
            ]
        }
    ]
}
```
If my user try to PUT a file with the key `{userId}/{key}` he gets 403 Access Denied.
Although he can PUT a file if I change the Resource in associated IAM role to `arn:aws:s3:::squad-health-check/*`.

It looks like IAM role doesn't see a proper value under `${graph.facebook.com:id}`.

I'm doing everything according to the docs. I face the same issue when utilizing Cognito User Pool instead of FB.
Do you have any clue what I'm doing wrong or how can I verify that variable?

**Comment by srchase** [comment]
@OskarKaminski 

Thanks for opening this issue.

The [documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_oidc_user-id.html) provides an example that could be adapted like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "cognito-identity:*",
                "s3:ListAllMyBuckets",
                "mobileanalytics:PutEvents",
                "s3:HeadBucket",
                "cognito-sync:*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::squad-health-check/${graph.facebook.com:id}",
                "arn:aws:s3:::squad-health-check/${graph.facebook.com:id}/*"
            ]
        }
    ]
}
```

Does that make a difference for you?

If not, I'd suggest you check with the [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=173).  As this works when you adjust the policy, it does not seem to be an issue with the SDK itself, but with the service.  An expert with Amazon Cognito could better answer why this is not working for you.

**Comment by OskarKaminski** [comment]
I've tried this form as well, and it doesn't work.
But you are right, it may be not an issue with the SDK.
I'll check there, and add the comment here what was the issue.

**Comment by OskarKaminski** [comment]
Yes. I've created the role for authenticated users through Cognito Federated Identities configuration, and everything with the Trust Policy was setup correct.

**Comment by srchase** [comment]
@OskarKaminski 

Were you able to get this issue resolved?
