### ISSUE TITLE
global.TYPED_ARRAY_SUPPORT is undefined for react-native

### ISSUE THREAD

**Issue by woodpav** [aws/aws-sdk-js#2326]
I get the above error on `import AWS from 'aws-sdk/dist/aws-sdk-react-native`. Others have gotten when using `babel-preset-env` instead of `module:metro-react-native-babel-preset`

    "@babel/runtime": "^7.1.2",
    "aws-sdk": "^2.198.0",
    "buffer": "^5.2.1",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "metro-react-native-babel-preset": "^0.48.2",
    "react": "^16.6.0-alpha.8af6728",
    "react-native": "^0.57.4",
		

I fixed it by editing `node_modules/aws-sdk/dist/aws-sdk-react-native.js` and changing the below code to `Buffer.TYPED_ARRAY_SUPPORT = typedArraySupport()`.

    // https://i.imgur.com/xyjLBOl.jpg
    Buffer.TYPED_ARRAY_SUPPORT = global.TYPED_ARRAY_SUPPORT !== undefined
		  ? global.TYPED_ARRAY_SUPPORT
		  : typedArraySupport()

I believe this is a problem with `babel` polyfilling `global` and is maybe related to `webpack`. 

More in depth troubleshooting at https://github.com/aws-amplify/amplify-js/issues/803 and https://github.com/aws-amplify/amplify-js/issues/2005

**Comment by AllanFly120** [comment]
Hey @woodpav, 
I went through the old amplify issue, it looks like issues with babel working together with webpack. Are you using webpack in your project?

**Comment by woodpav** [comment]
I’m not but amplify is.

**Comment by AllanFly120** [comment]
Hi can you share your full dependencies? I'm having trouble reproducing this issue.

**Comment by woodpav** [comment]
"@aws-amplify/api": "^1.0.18",
    "@aws-amplify/auth": "^1.2.4",
    "@aws-amplify/core": "^1.0.13",
    "@babel/runtime": "^7.1.2",
    "amazon-cognito-identity-js": "^3.0.3",
    "aws-sdk": "^2.198.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "buffer": "^5.2.1",
    "extensible-runtime": "^4.1.0",
    "react": "^16.7.0-alpha.0",
    "react-native": "^0.57.4",
		
    // dev
    "@babel/plugin-external-helpers": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "babel-preset-flow": "^6.23.0",
    "metro-react-native-babel-preset": "^0.48.2",
    "schedule": "0.4.0",
    "xmlhttprequest": "^1.8.0"

**Comment by woodpav** [comment]
For the record, I am no longer getting this error. I'm not sure what changed 😅

**Comment by srchase** [comment]
Thanks for following up.  I'll close out this issue for now. If it reoccurs, let us know and we can re-open the issue.

**Comment by EliSadaka** [comment]
I'm also experiencing this error after updating my React Native project from 0.55 to 0.57. If I comment out all the references to the aws-sdk package from my project then it runs fine.
Here are my dependencies:

```
"dependencies": {
    "@babel/runtime": "^7.3.1",
    "@feathersjs/authentication-client": "^1.0.8",
    "@feathersjs/feathers": "^3.2.3",
    "@feathersjs/socketio-client": "^1.1.5",
    "autolinker": "^1.7.1",
    "aws-sdk": "^2.392.0",
    "lodash": "^4.17.11",
    "mobx": "^5.9.0",
    "mobx-react": "^5.4.3",
    "moment": "^2.22.2",
    "prop-types": "^15.6.2",
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-animatable": "^1.3.1",
    "react-native-background-upload": "^4.4.0",
    "react-native-firebase": "^5.2.1",
    "react-native-gesture-handler": "^1.0.10",
    "react-native-keyboard-input": "^5.3.1",
    "react-native-linear-gradient": "^2.5.3",
    "react-native-navigation": "^2.8.0",
    "react-native-tab-view": "^1.3.1",
    "react-native-text-size": "^3.0.0",
    "react-native-video": "^4.3.1",
    "recyclerlistview": "^2.0.0-beta.1",
    "rn-fetch-blob": "^0.10.15",
    "shortid": "^2.2.14",
    "socket.io-client": "2.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-decorators": "^7.3.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "23.6.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^5.12.1",
    "eslint-plugin-react": "^7.12.4",
    "jest": "23.2.0",
    "metro-react-native-babel-preset": "^0.51.1",
    "react-test-renderer": "16.6.3"
  },
```

And here is my .babelrc:
```
{
	"presets": ["module:metro-react-native-babel-preset"],
	"ignore": ["node_modules/aws-sdk/dist/aws-sdk-react-native.js"],
	"env": {
		"production": {
			"plugins": [
				[
					"@babel/plugin-proposal-decorators",
					{
						"legacy": true
					}
				],
				"@babel/plugin-transform-runtime",
				"transform-remove-console"
			]
		},
		"development": {
			"plugins": [
				[
					"@babel/plugin-proposal-decorators",
					{
						"legacy": true
					}
				],
				"@babel/plugin-transform-runtime"
			]
		}
	}
}
```
