### ISSUE TITLE
Inconsistent createChangeSet status for change sets without any changes

### ISSUE THREAD

**Issue by RLThomaz** [aws/aws-sdk-js#2331]
When trying to use AWS-SDK-JS to automate my CFN stack creation/update it returns me a FAILED status for Change Sets without any changes. However, by reproducing the same thing on CFN console, the Change Set status is CREATE_COMPLETE even for templates without any change.

It is simple to reproduce this on both AWS-SDK-JS and CFN Console.

1. Create a simple template with just one resource and one template parameter.
2. Create a stack using the template.
3. Create a changeset for the stack using the same template and parameter.

It returns FAILED for AWS-SDK-JS - which breaks lambda updates using S3 buckets - and returns CREATE_COMPLETE - thus updating the stack after execution - for CFN Console.

Similar issues on other tools:
https://github.com/aws/aws-vsts-tools/issues/97
https://github.com/aws/aws-cli/issues/3123

**Comment by mostafafallah** [comment]
Hi @srchase 
I have same problem.
I am going to publish a ASPNet Core application with standard template. (attached here) with stack. (I did it with AWS Toolkit but i am doing with SDK). 
The steps are : (after uploading package and template on the s3)
1 - Creating Change set (change type is CREATE)
2 - executing Change setC (change type is UPDATE),but I faced with this error in change set status :

FAILED - No updates are to be performed.

is there anyway to handle it ?

[awsserverlesssample1-7-serverless-636760004622837156.zip](https://github.com/aws/aws-sdk-js/files/2539993/awsserverlesssample1-7-serverless-636760004622837156.zip)

**Comment by RLThomaz** [comment]
Hello @srchase,

Thanks for your help.

Sure, the actual template that is failing to create changeset is pretty simple. Of course, I removed all sensitive data - company name, userId, etc - so this won't work if you try to deploy it, but this is just a sample.

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "LambdaDeployment": {
      "DependsOn": [],
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "FunctionName": "My-Macro-Lambdas",
        "Code": {
          "S3Bucket": {
            "Fn::Sub": "mybucket.${AWS::Region}.cloud"
          },
          "S3Key": "macro/api.zip"
        },
        "Description": "Macro to deploy lambdas, stages, versions and alias.",
        "Environment": {
          "Variables": {
            "SomeVariables": "{\"AWSTemplateFormatVersion\":\"2010-09-09\",\"Parameters\":{\"Stage\":{\"Type\":\"String\",\"Default\":\"dev\"}},\"Conditions\":{\"NotDev\":{\"Fn::Not\":[{\"Fn::Equals\":[\"dev\",{\"Ref\":\"Stage\"}]}]}},\"Resources\":{},\"Outputs\":{}}"
          }
        },
        "Handler": "api.handler",
        "Role": "arn:aws:iam::SomeUserId:role/Role-Lambda",
        "Timeout": 300,
        "Runtime": "nodejs8.10"
      }
    },
    "DeployLambdas": {
      "Type": "AWS::CloudFormation::Macro",
      "Properties": {
        "FunctionName": {
          "Fn::GetAtt": [
            "LambdaDeployment",
            "Arn"
          ]
        },
        "Name": "DeployLambdas"
      }
    }
  },
  "Parameters": {
    "Product": {
      "Type": "String",
      "Description": "Product name."
    }
  }
}
```

So I can create a stack using the template by either using the CFN Console or using my AWS-SDK-JS script. The script is also pretty simple, here is a snipt to create the stack and changeset (for update) if the stack already exists. At first the script tries to deploy (create) a stack. If the stack already exists it tries creating a changeset. So the second method creates the changeset and describes it, there it checks the changeset status, and for this specific template (without any changes) it will be FAILED right away.

```nodejs
const cf = new AWS.CloudFormation();

async function deployStack(stackname, params) {
	try {
		const stack = await cf.describeStacks().promise()
		if (JSON.stringify(stack).match(stackname) === null) {
			console.log("Creating " + stackname + " ...")
			await cf.createStack(params).promise()
			const createComplete = await cf.waitFor("stackCreateComplete", { StackName: stackname }).promise()
			console.log("CREATE_COMPLETE - " + stackname)
			return createComplete
		} else {
			params.ChangeSetName = params.StackName + "-CS"
			await deployChangeSet(stackname, params)
		}
	} catch (e) {
		console.log(e, e.stack)
	}
}

async function deployChangeSet(stackname, params) {
	try {
		console.log("Computing changes for " + stackname)
		const stack = await cf.describeStacks().promise()
		if (JSON.stringify(stack).match(stackname) === null)
			params.ChangeSetType = "CREATE"
	
		await cf.createChangeSet(params).promise()
		const changeSetStatus = await cf.describeChangeSet({ ChangeSetName: params.ChangeSetName, StackName: params.StackName }).promise()
		if (changeSetStatus.Status === "FAILED") {
			await cf.deleteChangeSet({ChangeSetName: params.ChangeSetName, StackName: params.StackName }).promise()
			console.log("FAILED - " + stackname + "-CS")
			return changeSetStatus
		}
		await cf.waitFor("changeSetCreateComplete", { ChangeSetName: params.ChangeSetName, StackName: params.StackName }).promise()
		console.log("Executing " + stackname + "-CS")
		await cf.executeChangeSet({ ChangeSetName: params.ChangeSetName, StackName: params.StackName }).promise()

		if (JSON.stringify(stack).match(stackname) === null) {
			console.log("Creating " + stackname + " ...")
			const createComplete = await cf.waitFor("stackCreateComplete", { StackName: stackname }).promise()
			console.log("CREATE_COMPLETE - " + stackname)
			return createComplete
		} else {
			console.log("Updating " + stackname + " ...")
			const updateComplete = await cf.waitFor("stackUpdateComplete", { StackName: stackname }).promise()
			console.log("UPDATE_COMPLETE - " + stackname)
			return updateComplete
		}
	} catch (e) {
		console.log(e, e.stack)
	}
}

async function cfdeploy() {
	console.log("Starting CloudFormation deployment...")

	try {
		const macros = await deployStack("Mercury-Macros", {
			StackName: "My-Macros",
			Parameters: [{ ParameterKey: "Product", ParameterValue: "ProductName" }],
			TemplateURL: "https://s3.amazonaws.com/mybucket.cloudformation/my.template.macro"
		})
		console.log(macros)
	} catch (e) {
		console.log(e, e.stack)
	}
}

cfdeploy()
```

**Comment by srchase** [comment]
@RLThomaz 

Thanks for submitting this thorough response.

The CLI has a greater level of abstraction built into it than the SDK.  For example, the ```aws deploy``` command wraps several underlying CloudFormation API calls and there are additional flags to suppress the changset failures you are encountering.

The SDK offers the access to the CloudFormation calls directly.  If you have the possibility of submitting creating empty changesets and want to catch those specific errors, you'll need to add logic look for the StatusReason of 'The submitted information didn\'t contain changes. Submit different information to create a change set.'

You're correct to point out the inconsistency between the console and the CloudFormation API.  You're welcome to raise this question with that team directly on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=92).

**Comment by RLThomaz** [comment]
@srchase 

Thank you for your response. I understand that the console (web version) has greater abstraction - which makes sense since it is a graphical interface, and also for the CLI to reduce verbosity. 

I am already catching failed changesets and cleaning them afterward. I'll introduce versioning to my lambda CFN resource by activating S3 bucket versioning, that way whenever there is an updated lambda version the changeset shall not fail.

I'll raise the question with the team to understand their decision on failing the changeset creation, instead of only warning that no update is required, when there are no changes on the template. After all, when no changes are present it still creates the changeset on the console version and updates the stacks.

Thank you again
