### ISSUE TITLE
Sign in failes in IE10

### ISSUE THREAD

**Issue by oshklyaruk** [aws/aws-sdk-js#2333]
When I try to sign in in IE10 I am getting "Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException)", though in Chrome, Safari, IE11 it works fine. Forgot PW works without an issue in IE10. New users are created in AWS Cognito Console.

**Comment by srchase** [comment]
@oshklyaruk 

Thanks for opening this issue.

Can you give additional details so we can recreate this issue?
