### ISSUE TITLE
AWS.S3 reading from ~/.aws/credentials instead of config object

### ISSUE THREAD

**Issue by riwu** [aws/aws-sdk-js#2337]
```
const AWS = require('aws-sdk');

const config = {
  accessKeyId: 'xxxx',
  secretAcessKey: 'xxxx',
};
const s3 = new AWS.S3(config);
```

I noticed that the sdk is completely ignoring `config` and is instead reading from `~/.aws/credentials`. 

If I remove `~/.aws/credentials`, then `s3.upload()` etc will fail with
> CredentialsError: Missing credentials in config
> Could not load credentials from any providers

even though the credentials are provided via the `config` object in JS.

## Environment

OS: macOS High Sierra 10.13.5 / Ubuntu 18.04.1 LTS
Node: 8.12.0
Yarn: 1.9.4
aws-sdk: "^2.270.1"

**Comment by srchase** [comment]
Hello,

Thanks for opening this issue.

I'm trying to reproduce this issue, but am not getting the same error.

Are you able to load credentials from a JSON file?  

Can you try [loadFromPath](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-json-file.html)?

**Comment by gatsbyz** [comment]
Try it like 
```
       if (environment.AWS_ACCESS_KEY_ID && environment.AWS_SECRET_ACCESS_KEY) {	    
               awsConfigurationParmeters.httpOptions = customHttpOptions;
               aws.config.update({	
                         credentials: new aws.Credentials(environment.AWS_ACCESS_KEY_ID, 
 environment.AWS_SECRET_ACCESS_KEY)	
    });
```

**Comment by gatsbyz** [comment]
I had to remove env credential configuration - sdk handles this by default and its use breaks lambda usage

**Comment by riwu** [comment]
@srchase sorry didn't have time to respond, can you please reopen this?

Adding either 
```
aws.config.update({
  credentials: new aws.Credentials(process.env.S3_ACCESS_KEY_ID, process.env.S3_ACCESS_KEY_SECRET),
});
```
or
```
aws.config.loadFromPath('./config.json');
```
or setting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables fix the problem.

Not sure why `new AWS.S3(config)` does not work?

**Comment by riwu** [comment]
Figured out the problem...had a typo `secretAcessKey` instead of `secretAccessKey`.
