### ISSUE TITLE
Etag check where content-encoding gzip

### ISSUE THREAD

**Issue by leonetosoft** [aws/aws-sdk-js#2338]
Hello .. Good night,

I am developing a code that downloads an object in S3 through a signed URL, the url is working correctly.

When I start the download I'm using request, first I get the answer containing important data that I collect the content-encoding and also etag to buy after the download is finalized.

The integrity check works correctly when it is not a ZIP object, but when it is zip it returns a strange Etag, for example: "d89ee748a92eca6bae72d98ff3143df-1", when the object is not a zip stream the returned etag checks with the generated etag of the file saved to disk.

In the end this etag is verified but it is never the same as recorded on disk, am I doing something wrong or would it be a bug?

I have already tried to buy the compressed and uncompressed file, both have different Etag and the file is not corrupted.

My code: (You can assume that other parts are working correctly, and the check "Util.Etag" returns the correct etag of the file, the same one used by aws):

`
async Download() {
        if (!this.upaki) {
            this.upaki = new Upaki(Environment.config.credentials);
        }

        this.received_bytes = 0;

        Logger.debug(`Try Download ${this.fileDownload.name}`);

        let contentZip = false;

        let url = await this.upaki.GetSignedUrl(this.fileDownload.id, true);

        Logger.debug(`Signed URL ok start request ${this.fileDownload.name}`);
        let req = request({
            method: 'GET',
            uri: url
        });

        let folderDest = path.join(this.destFolder, this.fileDownload.path);

        if (!fs.existsSync(folderDest)) {
            mkdirp.sync(folderDest);
        }

        let dest = path.join(this.destFolder, this.fileDownload.path, `${this.fileDownload.name}.upakidownload`);

        Logger.debug(`Download file path dest: ${dest}`);

        let out = fs.createWriteStream(dest);

        this.fileDownload.state = DownloadFileState.DOWNLOADING;

        req.pipe(out);

        req.on('response', (data) => {
            // Change the total bytes value to get progress later.
            this.total_bytes = parseInt(data.headers['content-length']);
            this.fileDownload.etag = data.headers['etag'];
            contentZip = data.headers['content-encoding'] && data.headers['content-encoding'] === 'gzip';
        });

        req.on('data', (chunk) => {
            this.received_bytes += chunk.length;
            this.fileDownload.progress = (this.received_bytes * 100) / Number(this.total_bytes);
            Logger.debug(`${this.fileDownload.name}: Progress ${this.fileDownload.progress}`);
        });

        req.on('end', async () => {
            try {
                Logger.debug(`End download ${this.fileDownload.name}`);
                out.end();
                console.log('ETAG GERADO=', Util.Etag(fs.readFileSync(dest)), 'comparar=', this.fileDownload.etag);

                if (contentZip) {
                    console.log('descompacta');
                    await this.unzipFlush(dest);
                }

                console.log('ETAG GERADO=', Util.Etag(fs.readFileSync(dest)), 'comparar=', this.fileDownload.etag);

                let etagObj = Util.Etag(fs.readFileSync(dest));

                if (this.fileDownload.etag.indexOf(etagObj) === -1) {
                    Logger.error(`File ${this.fileDownload.name} corrupted !!! retry download`);
                    this.fileDownload.state = DownloadFileState.ERROR;
                    this.job.Fail(10000);
                    return;
                }

                fs.renameSync(dest, dest.replace('.upakidownload', ''));

                this.fileDownload.state = DownloadFileState.COMPLETED;

                setTimeout(() => { this }, 5000);
                this.job.Finish();
            } catch (error) {
                Logger.error(error);
                this.fileDownload.state = DownloadFileState.ERROR;
                this.job.Fail(10000);
            }
        });
    }
`

Node version: v8.11.4
Aws SDK: 2.213.1
System: windows 10

**Comment by leonetosoft** [comment]
I just read: https://docs.aws.amazon.com/en/AmazonS3/latest/API/RESTCommonResponseHeaders.html

> If an object is created by either the Multipart Upload or Part Copy operation, the ETag is not an MD5 digest, regardless of the method of encryption.

How do I check to see if my client has had problems with data transport?

**Comment by srchase** [comment]
@leonetosoft 

Thanks for submitting this issue.

How are you creating the objects in S3?

**Comment by leonetosoft** [comment]
I am sending through MultiPart Upload, sending through the gzip stream, create the request, partition in 2MB parts, send the parts and then complete the upload.

Code of class send multipart:
[https://github.com/leonetosoft/upaki-cli/blob/master/src/upaki/S3Stream.ts](url)

Code multipart start:
`    MultipartUploadManaged(credentials: MakeUpload, localPath: string, session: S3StreamSessionDetails, config: { maxPartSize: number; concurrentParts: number }): S3StreamEvents {
        var read = fs.createReadStream(localPath);
        //var compress = zlib.createGzip();

        let upStream = new S3Stream(new AWS.S3({
            correctClockSkew: true,
            accessKeyId: credentials.credentials.AccessKeyId,
            secretAccessKey: credentials.credentials.SecretAccessKey,
            sessionToken: credentials.credentials.SessionToken,
        }), session);

        let upload = upStream.Upload({
            Bucket: credentials.bucket,
            Key: credentials.key,
            ServerSideEncryption: 'AES256'
        });

        // Optional configuration
        upStream.setMaxPartSize(config.maxPartSize); // 20 MB
        upStream.setConcurrentParts(config.concurrentParts);

        upload.on('credentials', (config: any) => {
            try {
                upStream.client.config.credentials = new AWS.Credentials({
                    accessKeyId: config.AccessKeyId,
                    secretAccessKey: config.SecretAccessKey,
                    sessionToken: config.SessionToken
                });
            } catch (error) {
                console.log(error);
            }
        });

        upload.on('abort', () => {
            upStream.Abort();
        });

        upload.on('aborted', () => {
            try {
                //compress.unpipe(upStream.getStream());
                //read.unpipe(compress);
                upStream.getStream().destroy();
                //compress.destroy();
                read.destroy();
                // read.close();
                read = null;
            } catch (error) {
                console.log(error);
            }
        });

        upload.on('pause', (pause) => {
            // Escutar chamadas de pause
            if (pause) {
                upStream.pause();
            } else {
                upStream.resume();
            }
        });

        read.pipe(upStream.getStream());
        return upload;

    }`

**Comment by srchase** [comment]
Hello @leonetosoft,

Thanks for following up.

You could calculate and set your own MD5 checksum as metadata on the object, then verify that metadata when downloaded.

If you set the following param during upload:
```
 Metadata: {
   myMD5: myMD5CheckSum
 }
```

You could then get this header back when retrieving the object:
```x-amz-meta-mymd5```

**Comment by leonetosoft** [comment]
@srchase 
Thanks for the answer !!

Got it, I'll change the code so that it reports this header!
But I have several files already hosted without this heading ....
Would there be any way to change the old files with the correct header?

**Comment by srchase** [comment]
You can't update the metadata on an S3 Object outside the Console, but you can replace an object with using [copyObject](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property).  Use the same source (CopySource) and destination (Bucket/Key) and it will replace the object, allowing you to set new metadata:

```
const params = {
  CopySource: "/myBucket/myKey", 
  Bucket: "myBucket",
  Key: "myKey",
  Metadata: {
    myMD5: myMD5CheckSum
  },
  MetadataDirective: 'REPLACE'
}

s3.copyObject(params, function(err,data) {
  console.log(err,data);
})
```

**Comment by leonetosoft** [comment]
Thank you very much,

I will be doing this, however I have to download several files, read their bytes, generate MD5 and then perform Copy.

**Comment by srchase** [comment]
I'll close this issue for now.  Let us know if there are any further questions.
