### ISSUE TITLE
Redundant files shipped to npm

### ISSUE THREAD

**Issue by SimonSchick** [aws/aws-sdk-js#2341]
Related to #2247

I believe the following files don't really need to be shipped to npm:

```
.changes
.github
CHANGELOG.md
CONTRIBUTING.md
SERVICES.md
UPGRADING.md
dist-tools
scripts
```

You might want to use the `files` property inside `package.json` instead as it's opt in rather than opt-out.

**Comment by srchase** [comment]
Thanks for opening this issue.

We're getting this fixed.

We kept the scripts and dist-tools.  The browser-builder is shipped in dist-tools and there are some users of the scripts.

**Comment by srchase** [comment]
Closing out this issue as the changes have been merged and this will get fixed with the next release.
