### ISSUE TITLE
[Error Code: ConfigError] Region is set via aws.config.update, but still required {region}  options when calling function

### ISSUE THREAD

**Issue by gatsbyz** [aws/aws-sdk-js#2344]
import * as aws from 'aws-sdk';
     ...
     const awsConfigurationParmeters: ConfigurationOptions = {
        logger,
        maxRetries: 10,
        region
      };
    
      if (Object.keys(customHttpOptions).length > 0) {
        awsConfigurationParmeters.httpOptions = customHttpOptions;
      }
    
      const awsConfig = new aws.Config();
      awsConfig.update(awsConfigurationParmeters);

      return aws; // this is the object I will use to do calls to clients, like `new aws.S3()`

I am setting the region golabally via `aws.config.update`. However, when I tried to make DynamoDB/S3/Firehose/KMS calls, it results in a ConfigError.

    "before all" hook: Error calling new aws.KMS.listAliases - Error Code: ConfigError

The Fix is to put region in the call, so that - `new aws.KMS({region}).listAliases`. 

Should't aws.config.update take care of this?

**Comment by srchase** [comment]
If you want awsConfigurationParameters to be used globally, you'll need to update aws.config.  In your example, only a awsConfig is getting updated.

Try this instead:

```
 import * as aws from 'aws-sdk';
 ...
 const awsConfigurationParmeters: ConfigurationOptions = {
    logger,
    maxRetries: 10,
    region
  };

  if (Object.keys(customHttpOptions).length > 0) {
    awsConfigurationParmeters.httpOptions = customHttpOptions;
  }

  aws.config.update(awsConfigurationParmeters);
```

Once the global config is updated, any clients will use that config:
```
const kmsClient = new aws.KMS();
```

**Comment by gatsbyz** [comment]
Hi @srchase. The reason I was avoiding this option was that it causes a race condition with aws usage.

**Comment by srchase** [comment]
If you do not want to use the Aws.config.update, you could use the other options documented here:
[Setting Region](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html).

**Comment by srchase** [comment]
Great!  I'll close this issue for now.  Let us know if you have further questions.
