### ISSUE TITLE
throwing error for list objects v2.352.0 and 2.353.0

### ISSUE THREAD

**Issue by rohit1018** [aws/aws-sdk-js#2347]
<img width="710" alt="screen shot 2018-11-09 at 5 39 46 pm" src="https://user-images.githubusercontent.com/28265981/48292050-c9d7b200-e446-11e8-9ce4-c4ab189c6927.png">

**Comment by srchase** [comment]
@rohit1018 

Thanks for opening this issue.

Can you give us an example of the code you are using to get this error?

**Comment by Temkit** [comment]
Same issue !

**Comment by srchase** [comment]
I am able to successfully use listObjects with versions 2.352.0 and 2.353.0 with Node and the browser.

```
const aws = require('aws-sdk');

const s3 = new aws.S3();

const params = {
  Bucket: 'myBucket',
  Prefix: 'myPrefix' 
}

myPromise = s3.listObjects(params).promise()

myPromise.then(function(data) {
  console.log(data)
}).catch(function(err) {
  console.log(err)
})
```

Are there any other parts of your code that could be causing issues?

Which browser and version are you using?

**Comment by rohit1018** [comment]
No,
google chrome 70.0.3538.77 

I am able to successfully use listObjects with versions 2.349.0 with Node and the browser.

**Comment by srchase** [comment]
Which version of Angular are you using?

**Comment by Temkit** [comment]
Angular v7.0.3 and typescrpit 3.1.6

**Comment by rohit1018** [comment]
v2.352.0 !! added new feature !! this is breaking s3 listObject function and or more
"feature: Endpoint Discovery: Some services provide endpoint discovery operations (e.g. 'DescribeEndpoints()'). This SDK feature, if turned on, will automatically request endpoints from services if needed and cache the endpoints returned."
https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md

**Comment by AllanFly120** [comment]
Thank you @rohit1018. This is possibly related to the endpoint discovery feature. We are investigating this.

**Comment by AllanFly120** [comment]
Hey,
This issue is raised from [`isEndpointDiscoveryApplicable()`](https://github.com/aws/aws-sdk-js/blob/master/lib/discover_endpoint.js#L279) where the environmental variable `AWS_ENABLE_ENDPOINT_DISCOVERY` is inspected. Actually we shouldn't pull in env in browser platform. I have a PR out for review. Would you have a look at it? @rohit1018 @Temkit ?

**Comment by srchase** [comment]
@rohit1018 and @Temkit 

@AllanFly120's change to fix this issue has been merged in.  This will get fixed with the next release.  Thanks for bringing this to our attention.
