### ISSUE TITLE
AWS.transcribeService is not a constructor

### ISSUE THREAD

**Issue by portacha** [aws/aws-sdk-js#2349]
i have this problem 
"TypeError: AWS.transcribeService is not a constructor" when i try to create a object

var transcribeservice = new AWS.transcribeService({apiVersion: '2017-10-26'});

i use this lib

<script src="https://sdk.amazonaws.com/js/aws-sdk-2.383.1.min.js"></script>

**Comment by portacha** [comment]
Thank you very much in advance!

**Comment by srchase** [comment]
@portacha 

The current version of the SDK is 2.354.0

Can you try using this instead?

<script src="https://sdk.amazonaws.com/js/aws-sdk-2.354.0.min.js"></script>

**Comment by portacha** [comment]
Same error ( Uncaught TypeError: AWS.TranscribeService is not a constructor) i dont know if i doing something wrong i use that now :  https://sdk.amazonaws.com/js/aws-sdk-2.283.1.min.js and bower. 

This is my code:

`AWS.config.update({
  region: ***,
  credentials: new AWS.CognitoIdentityCredentials({
    IdentityPoolId: ***
  })
});

var transcribeservice = new AWS.TranscribeService();

function transcriber(){
    transcribeservice.startTranscriptionJob({
      LanguageCode: 'es-US', 
      Media: { 
        MediaFileUri: 'https://s3.amazonaws.com/****/output.wav'
      },
      MediaFormat: 'wav', 
      TranscriptionJobName: 'transcrpcion1',
    }, function(err, data) {
      if (err) console.log(err, err.stack);
      else     console.log(data);        
    });
  
  
    }`

**Comment by jstewmon** [comment]
Caused by `TranscribeService` being omitted from [`browser_default.js`](https://github.com/aws/aws-sdk-js/blob/master/clients/browser_default.js)?

**Comment by srchase** [comment]
@jstewmon is correct.  The TranscribeService does not support CORS (see [metadata.json](https://github.com/aws/aws-sdk-js/blob/master/apis/metadata.json)), which is why it is not included in the default browser package.

**Comment by portacha** [comment]
T_T . Any suggestions to solve this ?. Do I have to use a server-side language? Can I use node? or what language do you recommend to use the api of aws in frontend?

**Comment by srchase** [comment]
@portacha 

Yes, you will have to use the TranscribeService outside of the browser to get this to work.  You could use Node and do this server-side, or you could also use Lambda to make those calls instead.

**Comment by portacha** [comment]
thank you very much

**Comment by dominiceden** [comment]
You can still do this though:

```
import TranscribeService from "aws-sdk/clients/transcribeservice";
```

See https://github.com/aws/aws-sdk-js#in-nodejs-1

**Comment by SodaGremlin** [comment]
Is there any plan to include CORS support and allow this to be used? Thanks, Gregg

**Comment by srchase** [comment]
@SodaGremlin 

The Transcribe Service can best answer if/when CORS support is planned.  You can engage the Transcribe Service through the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=278) to provide the feedback that you would like to see that feature.
