### ISSUE TITLE
ExpiredToken is received while using shared credentials file

### ISSUE THREAD

**Issue by sashakorman** [aws/aws-sdk-js#2351]
In our production environment we have a process that rolling AWS credentials, i.e. generates access/secret/token and stores it under profile name in shared credentials file.
It does not work with the latest SDK (_ExpiredToken_ is received) since the file is loaded only once in the singleton _IniLoader_.
It works as expected using _2.336.0_ version.

How credentials rolling should be handled now?
Should we call _clearCachedFiles_ function explicitly?

**Comment by srchase** [comment]
Hello @sashakorman,

You are correct.  ```clearCachedFiles``` was added as part of the changes in [2.339.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#23390) to allow you to be able to explicitly refresh credentials for your exact use case.

**Comment by sashakorman** [comment]
Thanks @srchase 
I'll watch for the shared credentials file change and call to AWS.util.iniLoader.clearCachedFiles()

**Comment by srchase** [comment]
Great.  Let us know if you have any further questions.  Closing this issue.
