### ISSUE TITLE
React-Native with error [CredentialsError: Missing credentials in config]

### ISSUE THREAD

**Issue by truongluong1314520** [aws/aws-sdk-js#2357]
Hi everyone , I am researching about AWS S3 in React native app, can you please help me a little bit with the AWS Credentials? 

I follow the code from this closed issue: [Credentials in React-Native](https://github.com/aws/aws-sdk-js/issues/1531)

Code to config the AWS Credentials

    const AWS = require('aws-sdk/dist/aws-sdk-react-native');
    AWS.config.update({region: bucketRegion});
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: IdentityPoolId,
    });

    const s3 = new AWS.S3({
        apiVersion: '2006-03-01',
        params: {Bucket: albumBucketName}
    });

Later when I use `s3` to call a function `createMultipartUpload`:

    let params = {
        Bucket: bucketRegion,
        Key: "iPhoneX.mp4",
    };

    s3.createMultipartUpload(params, (err, data) => {

        console.log('error', err);
        console.log('data', data);

        if (typeof data !== 'undefined' && data !== null) {

            this._uploadId = data.UploadId;
        }
    });

The app throw me an error: `[CredentialsError: Missing credentials in config]`. If I put my `accessKeyId` and `secretAccessKey`, I am able to use `s3`.

As far as I know, we cannot put the `accessKeyId` and `secretAccessKey` to the app for client. I am willing to hear from you guys.

Thank you in advance!

**Comment by srchase** [comment]
@truongluong1314520 

Have you looked at this guide? [AWS Mobile React-Native Starter](https://github.com/aws-samples/aws-mobile-react-native-starter)

There's a specific section on authentication that would be helpful.

**Comment by truongluong1314520** [comment]
I checked, `aws-amplify` work with `aws-sdk` no conflict
