### ISSUE TITLE
getSignedUrl

### ISSUE THREAD

**Issue by pacopicon** [aws/aws-sdk-js#2358]
Scenario:  I have been testing `s3.getSignedUrl` in a simple Node.js program where I have been calling two different assets from two different AWS s3 accounts.  Both accounts (one belonging to my employer, the other one my own personal hobby one) are similar in that there are no CORS policies set, no Bucket policies set, and the buckets are set to private.  I have made sure to alternate all of the pertinent variables that I feed into the credentials used in the constructor `S3 = new AWS.S3(credentials)` and in the params used in the actual function `S3.getSignedUrl('getObject', params, function (err, url) {...}`.

However, though the link that `s3.getSignedUrl()` retrieves for the asset in my own personal bucket works when copied and pasted on the browser (from the console.log()) -- the link retrieved for the asset in my employer's bucket does not and instead calls up the following response from the s3 server: 

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>...access key...</RequestId>
<HostId>
...hostId...
</HostId>
</Error>
``` 

I have checked and re-checked the credentials, that the assets in question exist, and even played around with including the `signatureVersion: 'v4'` key-value in the credentials object: I am still unable to access my employer's asset.  When I showed this to my boss, he made the bucket public -- and it worked then.  But it won't work when the bucket is set to private.

Here is my code:

```
const callTest2 = async () => {

  try {

    let
      opt = false, 
      bucket = '',
      key = '',
      secret = '',
      file = '' 
      
      if (opt) {
        bucket =  'screener-dev'
        key =  process.env.MY_KEY
        secret =  process.env.MY_SECRET
        file =  'picture.jpg' 
      } else {
        bucket =  'pq7development'
        key =  process.env.WORK_KEY
        secret =  process.env.WORK_SECRET
        file =  'someFile.pdf' 
      }

    let 
      AWS = require('aws-sdk'),
      cred = { 
        accessKeyId: key, 
        secretAccessKey: secret
        // ,
        // signatureVersion: 'v4' 
      }

    S3 = new AWS.S3(cred)

    let params = {  
      Bucket: bucket, 
      Key: file, 
      Expires: 600
    }
      console.log('params = ', params)

      await S3.getSignedUrl('getObject', params, function (err, url) {
        if (err) {
          console.log(err)
        } else {
          console.log('url = ', url)
        }
      });

    //   new Promise((resolve, reject) => {
    //     S3.getSignedUrl('getObject',params, (err, data) => {
    //         if (err) {
    //             reject(err);
    //         } else {
    //             let d = resolve(data)
    //             console.log(d)
    //             return d
    //         }
    //     });
    // }).then( (d) => {
    //   if (d) {
    //     console.log('d in the then:', d)
    //   }
    // })

  } 
  catch (err) {
    console.log(err)
  }

}

callTest2()
```
I have made a video of this behavior accessible [here](https://youtu.be/dNmojRJywE0)

My questions are the following:

(1) Why am I observing this disparity?
(2) Would old (say older than 300 days) accessKeyId and secretAccessKey affect the access to s3 buckets?
(3) It doesn't seem like I need a CORS policy set up in order to activate the link from my Command Prompt console.  Would the CORS policy need to be set up if the link were sent and activated from a website?
(4) Would there be any difference observed in the behavior of `s3.getSignedUrl` depending on whether the s3 account called were a pay or free account?
(5) Are there any other settings besides Bucket policy, CORS policy, private/public settings, that could be at heart of this disparity?

Thank you,

Paco

**Comment by srchase** [comment]
@pacopicon 

How are you confirming that the credentials are valid?  Can you successfully do something simple like a [headObject](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headObject-property) call on the object you are attempting to create a signed URL for.

Per the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property), you must use static or previously resolved credentials when using getSignedUrl.

**Comment by pacopicon** [comment]
@srchase 

Very good question.  The problem ultimately lay in the fact that my employer has several aws credentials.  I tried `headObject` with all of them until and that is how I found the right set of keys.

Thanks for your help!
