### ISSUE TITLE
Cloudwatch Event Rule Target not working for SSM Automation Document

### ISSUE THREAD

**Issue by koladilip** [aws/aws-sdk-js#2360]
When I tried to attach SSM Automation document as a target for Cloudwatch event rule using Javascript sdk, I got this error:
ValidationException: Parameter RunCommandParameters is not valid for targetwindows-av-update-automation.

**Comment by srchase** [comment]
@koladilip 

Can you give us an example of the code you are using?

**Comment by koladilip** [comment]
```
const cloudWatchEvents = new AWS.CloudWatchEvents();

    try {
        await cloudWatchEvents.putTargets({
            Rule: cliArgs.ruleName,
            Targets: [{
                Id: cliArgs.targetId,
                Arn: cliArgs.ssmAutomationDocument,
                RoleArn: cliArgs.roleArn
            }]
        }).promise();
    } catch (error) {
        throw error;
    }
```

**Comment by srchase** [comment]
@koladilip 

That is an error returned directly from the CloudWatchEvents Service.

Have you followed up with the Service Team?  They would be better suited to answer questions regarding RunCommandParameters validation.

**Comment by koladilip** [comment]
@srchase How do I contact AWS service team? via support?

Is this package officially supported by AWS right?

**Comment by srchase** [comment]
@koladilip 

Yes, the SDK is officially supported by AWS.

GitHub issues on this repository are meant to be for tracking issues with the working of the SDK itself.

The error you are receiving is being returned from the CloudWatchEvents service.  As it is not an error raised by the SDK, I do not have reason to believe this is the SDK not working correctly, but is something that needs resolved with the CloudWatchEvents service.

If you have an AWS Support account, you can open a case through your [AWS Console](https://console.aws.amazon.com/support/home#/), or you can engage the CloudWatch team on their [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=138).

**Comment by koladilip** [comment]
@srchase Ok got it. Thanks.
