### ISSUE TITLE
`.promise` by default

### ISSUE THREAD

**Issue by andres-lowrie** [aws/aws-sdk-js#2361]
Apologies if there's a feature request already I wasn't able to find it, or If I did a poor job at reading the docs and missed something ... 

It would be real nice to have a setting that can be passed into the constructor that tells the library to use promises by default

So instead of having to do:

```javascript
resource.methodA({...}).promise()
// ...
resource.methodB({...}).promise()
// and so on and so on for each method being called
```

one would be able to do something like 

```javascript
const resource = new AWS.FooResource({
  region: 'us-east-1',
  ...
  usePromise: true
});
```

then all methods would be promises by default so a user wouldn't have to append the `.promise` bit to the end of the method.

TY

**Comment by srchase** [comment]
@andres-lowrie 

Thanks for submitting this feature request.

**Comment by chrisradek** [comment]
Just wanted to add that in [version 3](https://github.com/aws/aws-sdk-js-v3) of the JS SDK (currently in preview), you no longer have to call `.promise()`. Instead, operations will return a promise by default, unless you pass a callback function to an operation.

**Comment by srchase** [comment]
@chrisradek 

Thanks for chiming in!  I've added the 'needs-major-version' tag on this Feature Request.  As @chrisradek noted, this has already been addressed in [v3](https://github.com/aws-sdk-js-v3).

**Comment by srchase** [comment]
Opting to close this issue.  This change will not be made on V2 of the SDK.
