### ISSUE TITLE
React-native - SignatureDoesNotMatch when using pre-signed URL for PUT

### ISSUE THREAD

**Issue by truongluong1314520** [aws/aws-sdk-js#2362]
Hello everyone, I am trying to upload an image in React native to AWS s3 using pre-signed URL. Here is my pre-signed url generator:

    this._preSignedUrl = json.url + '/' + json.fields.key + "?" +
        "X-Amz-Expires=86400" +
        "&X-Amz-Date=" + json.fields["X-Amz-Date"] +
        "&X-Amz-Algorithm=" + json.fields["X-Amz-Algorithm"] +
        "&X-Amz-Credential=" + encodeURIComponent(json.fields["X-Amz-Credential"]) +
        "&X-Amz-Security-Token=" + encodeURIComponent(json.fields["X-Amz-Security-Token"]) +
        "&X-Amz-SignedHeaders=" + encodeURIComponent("content-type;host;x-amz-acl") +
        "&X-Amz-Signature=" + json.fields["X-Amz-Signature"];

Here is the configuration of my AWS:

    AWS.config.update({
        region: awsConfig.Storage.region,
        credentials: new AWS.Credentials(
            accessKeyId,
            secretKey,
            sessionToken
        ),
    });

    this._s3 = new AWS.S3({
        apiVersion: '2006-03-01',
        params: {Bucket: awsConfig.Storage.bucket},
        signatureVersion: 'v4',
    });

This is the uploading code using pre-signed URL:

    sendFile(presignedurl: string, file: { uri: string, type: string, name: string },
             onSuccess: () => void,
             onFail: () => void,
             onProgress: () => void) {

        // from http://blog.rudikovac.com/react-native-upload-any-file-to-s3-with-a-presigned-url/

        const xhr = new XMLHttpRequest();

        xhr.upload.addEventListener('progress', (e) => {

            console.log('progress');
            console.log(e);
            onProgress(e);
        }, false);

        xhr.onreadystatechange = function () {
            if (xhr.readyState === 4) {
                if (xhr.status === 200) {
                    // Successfully uploaded the file.
                    console.log('successfully uploaded presignedurl');
                    console.log(xhr);
                    onSuccess(file.uri);
                } else {
                    // The file could not be uploaded.
                    console.log('failed to upload presignedurl');
                    console.log(xhr);
                    onFail(file.uri);
                }
            }
        };

        xhr.open('PUT', presignedurl);
        xhr.setRequestHeader('x-amz-acl', 'public-read');
        // for text file: text/plain, for binary file: application/octet-stream
        xhr.setRequestHeader('content-type', file.type);
        xhr.send(file);
    }

The response is [SignatureDoesNotMatch] "The request signature we calculated does not match the signature you provided. Check your key and signing method."

If you have any idea or need any information, please let me know. Thank you in advance!

**Comment by srchase** [comment]
@truongluong1314520 

Are you having a specific issue with the SDK?

From the code you provided, I don't see where you are using the SDK.

**Comment by truongluong1314520** [comment]
Hi @srchase , thank you for your quick reply. The reason that I reply you late is because I got a fever few days ago.

Here is my code to get the pre-signed url: 

    createPreSignedPost = (key, success, fail) => {

        let params = {
            Bucket: awsConfig.Storage.bucket,
            Fields: {
                key: key,
            },
            Expires: 86400,
        };
        this._s3.createPresignedPost(params, function (err, data) {

            if (err) {

                fail(err);

            } else {

                success(data);
            }
        });
    };

Hope this can help you to find out why there is a [SignatureDoesNotMatch] error.

Thank you again @srchase .

**Comment by srchase** [comment]
@truongluong1314520 

I'm not seeing anything in your usage of the SDK to indicate the SDK is not working as expected.

Have you double-checked your credentials and bucket configuration?

**Comment by truongluong1314520** [comment]
Hi @srchase , it is strange, I am able to get signed url by using this function:

[getSignedUrl](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property)

However, when I come to this function:

[createPresignedPost](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createPresignedPost-property)

From what I know the error [SignatureDoesNotMatch] is come from `X-Amz-SignedHeaders` not match `xhr. setRequestHeader()`.

[signature doesn’t match the request headers](https://blog.rudikovac.com/react-native-upload-any-file-to-s3-with-a-presigned-url/)

Can you please tell me the difference between `getSignedUrl` and `createPresignedPost`. From the document, I see:

> Note: Not all operation parameters are supported when using pre-signed URLs. Certain parameters, such as SSECustomerKey, ACL, Expires, ContentLength, or Tagging must be provided as headers when sending a request. If you are using pre-signed URLs to upload from a browser and need to use these fields, see createPresignedPost()

However, I am able to set the ALC when using `getSignedUrl`, which make me confuse.

Thank you in advance!

**Comment by srchase** [comment]
@truongluong1314520 

createPresignedPost returns a pre-signed POST policy to support uploading to S3 directly from an HTML form.

getSignedUrl only returns a URL which can be used for getObject or putObject operations.

You're correct.  If you need to set an ACL, you'll need to use a pre-signed POST.

If you have something specific in the SDK that you think is not working, let us know.  If you have general usage questions, you will find better resources on Stack Exchange or the AWS Developer Forums.  These GitHub issues are reserved for resolving issues with the operation of the SDK itself.

**Comment by truongluong1314520** [comment]
Hi @srchase , I will use the getSignedUrl for now and research more about createPresignedPost.

Thank you for both your kindness and your time.
