### ISSUE TITLE
can you provide the change password angular 2,4,5,6,7 code what is the difference between change , reset and forgot password? please explain flow how cognito password works

### ISSUE THREAD

**Issue by hemanth-sp** [aws/aws-sdk-js#2363]

**Comment by srchase** [comment]
@hemanth-sp 

This GitHub repository is a place for resolving issues with the JavaScript SDK.

If you need general guidance on using AWS, you can refer to our [AWS Developer Forums](https://forums.aws.amazon.com/index.jspa).

Also refer to the [Cognito Developer Resources](https://aws.amazon.com/cognito/dev-resources/).

If you have a specific issue where you think the SDK is not working, let us know and we can re-open this issue.
