### ISSUE TITLE
useDualstack incorrectly capitalised in typings

### ISSUE THREAD

**Issue by tambry** [aws/aws-sdk-js#2364]
In [the typings it's `useDualStack`](https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/lib/config_use_dualstack.d.ts#L7), while in [the code using the option](https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/lib/region_config.js#L51) and [the documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html) it's `useDualstack`.

Since variable names are case sensitive, specifying the uppercased one doesn't actually affect anything, does it?

**Comment by srchase** [comment]
Thanks for opening this issue.

PR to fix in:
https://github.com/aws/aws-sdk-js/pull/2365
