### ISSUE TITLE
Origin DomainName does not refer to a valid S3 bucket

### ISSUE THREAD

**Issue by marshalld139** [aws/aws-sdk-js#2368]
When updating a **CloudFront Distribution** via the SDK that serves an **S3 bucket** you cannot configure the **Origin Domain Name** to be an **S3 Website Endpoint**, it only accepts an **S3 Bucket Endpoint**.
(i.e. CloudFront will only accept `<bucket_name>.s3.<region>.amazonaws.com` as an Origin Domain Name, which points at the bucket itself, whereas it should except `<bucket_name>.s3-website.<region>.amazonaws.com` which is the website endpoint for the bucket).

The resulting error is this:
```
An error occurred (InvalidArgument) when calling the UpdateDistribution operation: The parameter Origin DomainName does not refer to a valid S3 bucket.
```

The only solution I have found is that once the distribution is deployed (via Terraform), I need to manually change the Origin Domain Name in the AWS console myself.

I can confirm that this is also the case with the CLI.

Node Version: `v8.12.0`
SDK Version: `2.354.0`

**Comment by srchase** [comment]
@marshalld139 

Can you give an example of the SDK call you're making?  And the CLI command that is also resulting in the error?

**Comment by marshalld139** [comment]
The SDK is being called per the docs:
```
const params = {
    DistributionConfig : newConfig.DistributionConfig,
    Id: id,
    IfMatch: newConfig.ETag
  };

cloudfront.updateDistribution(params, function(err, data) {
  if (err) console.log(err, err.stack);
  else     console.log(data);
});
```

Essentially I have pulled down the Distribution config using `getDistributionConfig` and modified the value of `Origins`:
```
{ Quantity: 1,
  Items: 
   [ { Id: 'id',
       DomainName: <modified this value to point to the S3 website endpoint>,
       OriginPath: '',
       CustomHeaders: [Object],
       S3OriginConfig: [Object] } ]
 }

```
This is done as CloudFront requires a full config to be provided if any change is made to any of the config.

But when I tried to push up the new value I get that error.

The CLI command:
```
aws cloudfront update-distribution --id <id> --distribution-config file://cloudfront_config.json --if-match <ETag>
```
This gets the same error as the SDK.

**Comment by srchase** [comment]
@marshalld139 

Thanks for replying.

When switching to the S3 Website Endpoint, you're actually switching to CustomOrigin.

If you make the change in the Console, then inspect the response from ```getDistributionConfig```, you'll see that ```S3OriginConfig``` has been replaced with ```CustomOriginConfig```.

Even though it's actually an S3 Bucket, using the Website Endpoint requires configuration via a CustomOriginConfig.

**Comment by marshalld139** [comment]
@srchase 

Thanks for the response.

I did try and create a CustomOrigin in the past and it still did not work, but I will have a closer look today and try it out again. Thanks.

**Comment by srchase** [comment]
Sounds good.  Let us know if that gets it working, or if you have followup questions.
