### ISSUE TITLE
getting  The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by rainnaren** [aws/aws-sdk-js#2372]
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/testoboes/_search\n\nhost:lop3reyr72.execute-api.ap-northeast-1.amazonaws.com\nx-amz-date:20181122T195017Z\nx-amz-security-token:AgoGb3JpZ2luEAAaDmFwLW5vcnRoZWFzdC0xIoACFzKT/wmvVgIUA6KdeWMtnSmd4GwLSn4EvjVcYxEH1UjOglmqk6MjmkW/B8peGMZh7O/+bHVf7VqumN/Fn/qTrkMJptdVoBebjJ71Rau98yfW8730H8FdmADovsAjaIwfuR0JoMoAA7d2/kkixmRPt4bMB0+btzTvQawxDoj//8dmpEJRKIWCPJvlMY3IiW8ffZuM0gJkR/zBnhyOkaKUlPz5qrgL81C8HTdt3sHs/s3rT4koykBT3o+y+LJAo7+dJVfe035qwGrvq/W2aZEf7MwY1irRqN+RsA+cEg2Xwz1qbj5NgTkvSivG09/+wp5XSDUAectVlon+HYm/3pJ+0irNBQiV//////////8BEAEaDDgzOTA3NDIzNjk3MSIMQ+fCoUqd5SSO4oIyKqEFTd4mYRibdos0LyzpJ5/R9hl2QIqyjpjjuoYa7r6DssFhOsDA65KD8uV+E0z3+XYLBe+9ZChX334u+5V8I7v2aAXO9RCj3WEV7wxcf/YzGAmo6xHQoYGqOhpPeuMT+Qanohw18aMqR3mJDpA1JyxrNz1j+XWbaRwA85t6PkYtT2Hdm3VGNaNE5eraYLTKyGoKdy8sfk1Kcr92DwTZZuiL8+n6XhE8uvSOp4/esnZ4Qm4HT5zM7q2BBgLEmEvZ+XXY4YFLO0PeGciM4Bfgh59TR39xZj5UAZ7/xU71GVyTp/JKm1gEksz5AvGP2d98Os6Th3Ep6qO3KWn+CL6jrjSPyboDIFtYIn8K6+RQbzNHpKsWt5rIEbZgF1rM/iV6Vp+qlqTy/dcbu1aUD5zOrWjSG6DwrXulQSYJZZgT6cSqOWv513aGoTrau87JCN1nJmSrLVx9smex9pryPwhvsOyyJ/GudGBd+5Jfd4GPWZntaEMCSqujZlRdpJm6yuwFdg4BjGJP2007r8XUL1qCvoX+0zguwhcu0T6xIaKcrHUpB0I0kT0NHzn8yKG4UhcsXccCKyfzLBOriBGs1w6cX7to7iruwEt1zyzSEpIlI/9uRyqNK6pJr81iAJhcM9qYPcp6Bh4rrc9ToBZNYE4/7UWjVdr0BgqQtSQIHnSa6poBRLLQ7eFGInlHXS7KTK+ZuquNu/h5RfbOJVnLRHBkAgiyjKDENG4Q3iVixIYgzMyHV+f2rGQkiCGJ7O9dqe5MRZRc90WpHMhRgGaE9chkL1fDiAbsvkJqRxQVLkPeFjyZs7h3fKcIQAHkfbhtdHq2YNJntArtfZEurAxY9av5SZ6ZkRYr6KH+J9KMSHuonQ7rkpwWzzq6yadXTkO3YfRZcUaCoTD4kNzfBQ==\n\nhost;x-amz-date;x-amz-security-token\n717c99d00c609cc06409373535e437fd80def7c495e973d5af7f9dcc6e9cf09a'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20181122T195017Z\n20181122/ap-northeast-1/execute-api/aws4_request\nacaf2f9e3f430b4cf6e9e30986734843946353db948fbdff1f0fa40601704dca'\n"}

**Comment by srchase** [comment]
@rainnaren 

Please provide a full example of the code that will reproduce this issue, and an explanation of why you believe there is an issue with the operation of the SDK.

**Comment by rainnaren** [comment]
```
  var httpRequest = new AWS.HttpRequest(ElasticUrl +'/'+ elasticIndex, "ap-northeast-1");
                httpRequest.method = "POST";
      httpRequest.headers.host = "lop3reyr72.execute-api.ap-northeast-1.amazonaws.com";
      httpRequest.headers['Content-Type'] = "application/json";
 var v4signer = new AWS.Signers.V4(httpRequest, "execute-api", true);
      v4signer.addAuthorization(AWS.config.credentials, AWS.util.date.getDate());
```
using this i get the authorization header. here iam using Aws.signers which is in aws-sdk

**Comment by srchase** [comment]
@rainnaren 

Thanks for following up.

Please refer to this comment: https://github.com/aws/aws-sdk-js/issues/1247#issuecomment-264285589

Signers.V4 is not part of the public API.

There are Third-Party libraries available that can be useful for doing this signing.
