### ISSUE TITLE
Encoding: s3.getSignedUrl generates URL with different encoding than it`s on Amazon S3

### ISSUE THREAD

**Issue by tverney** [aws/aws-sdk-js#2373]
Hi,

I`m using aws-sdk for Node and I`m having the problem:

The file in S3 it`s with the right URL https://s3.amazonaws.com/radimagemdigital-imagens/Leti%CC%81cia_O._Pereira_Tomografia_da_regia%CC%83o_anterior_da_maxila_03_.08_.18_.pdf

With the %CC%81 and %CC%83 encoding. 

But generating an signed url with s3.getSignedUrl the function returns the URL:

https://radimagemdigital-imagens.s3.amazonaws.com/Let%C3%ADcia_O._Pereira_Tomografia_da_regi%C3%A3o_anterior_da_maxila_03_.08_.18_.pdf

This one gets a No Such Key response from s3. We can fix that signing URL with encoding in this package?

**Comment by srchase** [comment]
@tverney 

Thanks for opening this issue.  We need to review how the SDK is handling this encoding.

For now, doing NFD normalization on your keys will give you the right signed URL that matches S3.

```
const params = {
  Bucket: 'myBucket',
  Key: 'Letí'.normalize('NFD')
}

s3.getSignedUrl('getObject', params, (err,data) => {
  console.log(data) // https://myBucket.s3.us-west-2.amazonaws.com/Leti%CC%81?AWSAccessKeyId...
})
```

**Comment by tverney** [comment]
@srchase Great workaround! Just fixed for me!
