### ISSUE TITLE
Quesiton: is it possible to upload a video to the transcription service?

### ISSUE THREAD

**Issue by pietrop** [aws/aws-sdk-js#2374]
I was looking at [`Class: AWS.TranscribeService`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/TranscribeService.html#startTranscriptionJob-property) specifically at [`startTranscriptionJob`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/TranscribeService.html#startTranscriptionJob-property) and noticed that the `media` is described as `MediafileUri` string value only. Unless I missed something.

```js
 Media: { /* required */
    MediaFileUri: 'STRING_VALUE'
  },
```

So my question is, whether it possible to upload a video to the transcription service? eg through a multi-part form upload.

**Comment by srchase** [comment]
@pietrop 

Refer to the TranscribeService [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/TranscribeService.html#startTranscriptionJob-property).

The ```MediaFileUri``` must be an S3 location and must be in the same region as the API endpoint that you are calling.

Input filetypes are: mp3 | mp4 | wav | flac

You can upload the input file to S3 with a multi-part form and then call the TranscribeService on that uploaded file.
