### ISSUE TITLE
Trying to trigger AppSync query via lambda function. V4 signer.addauthorization not working. Error message: "Data must be a string or a buffer"

### ISSUE THREAD

**Issue by hagiosofori** [aws/aws-sdk-js#2375]
**Error Message**
`2018-11-23T14:37:03.533Z	3e0ff525-ef2d-11e8-8328-89b33f69a07f	TypeError: Data must be a string or a buffer
    at Hmac.update (crypto.js:99:16)
    at Object.hmac (/var/task/node_modules/aws-sdk/lib/util.js:399:50)
    at Object.getSigningKey (/var/task/node_modules/aws-sdk/lib/signers/v4_credentials.js:74:35)
    at V4.signature (/var/task/node_modules/aws-sdk/lib/signers/v4.js:98:36)
    at V4.authorization (/var/task/node_modules/aws-sdk/lib/signers/v4.js:93:36)
    at V4.addAuthorization (/var/task/node_modules/aws-sdk/lib/signers/v4.js:35:12)
    at AWS.config.credentials.get.err (/var/task/index.js:52:10)
    at Credentials.get (/var/task/node_modules/aws-sdk/lib/credentials.js:126:7)
    at exports.handler (/var/task/index.js:42:25)
END RequestId: 3e0ff525-ef2d-11e8-8328-89b33f69a07f
REPORT RequestId: 3e0ff525-ef2d-11e8-8328-89b33f69a07f	Duration: 103.19 ms	Billed Duration: 200 ms 	Memory Size: 128 MB	Max Memory Used: 60 MB	
RequestId: 3e0ff525-ef2d-11e8-8328-89b33f69a07f Process exited before completing request`

**Expected result**
The V4 signing should complete successfully.

**Current result**
it currently fails with the error message above. I did some digging, in the `hmac` function in `util.js`, and realized that it gets called 3 times while the lambda function runs. 
I only call `signer.addAuthorization(cred, date)` once.

the first 2 times `hmac` gets called, it has a correct `string` parameter, which allows the successful creation of a buffer used in the function to create a new hmac, and return it.

the third time, this `string` parameter is false. Thus, the Buffer isn't created, and the `hmac.update(string)` function fails with the error indicated above.

any help? Could this be a result of something I'm doing wrong?

**Comment by hagiosofori** [comment]
**lambda runtime**
Node 8.10

**Comment by BronxBombers** [comment]
I am encountering the same issue in an almost identical use case, when removing the signer.addAuthorization the call is successfully gets a not authenticated response, so the request is being sent correctly. Here is my code: `const env = require('process').env;
const fetch = require('node-fetch');
const URL = require('url');
const AWS = require('aws-sdk');

AWS.config.update({
    region: env.AWS_REGION,
    credentials: new AWS.Credentials(env.AWS_ACCESS_KEY_ID, env.AWS_SECRET_ACCESS_KEY, env.AWS_SESSION_TOKEN)
});

/**
 *  Amazon Cognito trigger for post-authentication
 *
 * @param {event} the details from the Amazon Cognito session about the user
 * @param {context} the AWS Lambda context
 * @param {callback} Function to call when we are done with processing.
 */
exports.handler = (event, context, callback) => {
    console.log(`Event = ${JSON.stringify(event, null, 2)}`);
    console.log(`Env = ${JSON.stringify(env, null, 2)}`);

    const createParentCompany = `mutation CreateParentCompany($input: CreateParentCompanyInput!) {
        createParentCompany(input: $input) {
          id
          name
          offices {
            items {
              id
              name
            }
            nextToken
          }
        }
      }
    `;

    const compInfo = {
        name: "company",
    }

    const post_body = {
        query: createParentCompany,
        operationName: 'CreateParentCompany',
        variables: compInfo
    };
    console.log(`Posting: ${JSON.stringify(post_body, null, 2)}`);

    // POST the GraphQL mutation to AWS AppSync using a signed connection
    const uri = URL.parse("https://l55crmfv5zbn5orke4beyces5q.appsync-api.us-east-1.amazonaws.com/graphql");
    const httpRequest = new AWS.HttpRequest(uri.href, env.REGION);
    httpRequest.headers.host = uri.host;
    httpRequest.headers['Content-Type'] = 'application/json';
    httpRequest.method = 'POST';
    httpRequest.body = JSON.stringify(post_body);
    console.log(`Event = ${JSON.stringify(httpRequest, null, 2)}`);
    console.log(AWS.config.credentials);
    AWS.config.credentials.get(err => {
        console.log(err);
        const signer = new AWS.Signers.V4(httpRequest, "appsync", true);
        console.log(AWS.config.credentials);
        signer.addAuthorization(AWS.config.credentials, new Date());


        const options = {
            method: httpRequest.method,
            body: httpRequest.body,
            headers: httpRequest.headers
        };

        fetch(uri.href, options)
            .then(res => res.json())
            .then(json => {
                console.log(`JSON Response = ${JSON.stringify(json, null, 2)}`);
                callback(null, event);
            })
            .catch(err => {
                console.error(`FETCH ERROR: ${JSON.stringify(err, null, 2)}`);
                callback(err);
            });
    });
}`

**Comment by srchase** [comment]
@hagiosofori 

Refer to @chrisradek's comment on an earlier issue: https://github.com/aws/aws-sdk-js/issues/1247#issuecomment-264285589

Also, check out [SignatureV4](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/signature-v4-node) in v3 of the SDK.  v3 is in preview, but would be a good solution once it's ready for production use.

**Comment by hagiosofori** [comment]
thanks @srchase ... will check it out

**Comment by srchase** [comment]
I'll close this issue for now.  If you have a followup, let us know and we can reopen.

**Comment by flyandi** [comment]
Same problem here - almost same code for the signing part. Also the signing part is used in tons of blogs, etc. So did anyone actually manage to use it?

**Comment by nireak** [comment]
In case it helps somebody...I had the same problem and the origin of it was that the region environment variable was empty ( I was typing env.REGION when mine was defined in lowercase: env.region)

**Comment by janhesters** [comment]
I'm also facing this problem @srchase. I'm trying to follow [this gist](https://gist.github.com/undefobj/abb8a42a5c59606fb4126f47a383c48a).
