### ISSUE TITLE
RDSDataService is not working

### ISSUE THREAD

**Issue by asyba** [aws/aws-sdk-js#2376]
RDSDataService is not working, is not doing nothing no errors, no logs.

Running aws lambda node js:
```
var rdsDataService = new AWS.RDSDataService({apiVersion: '2018-08-01'});
    var params = {
        awsSecretStoreArn: 'arn:xxxxx', /* required */
        dbClusterOrInstanceArn: 'arn:xxxxxxx', /* required */
        sqlStatements: 'select * from Member' /* required */
    };
    rdsDataService.executeSql(params, function(err, data) {
        console.log("log1");
        if (err)   { console.log("log2"); console.log(err, err.stack);  }// an error occurred
        else     {   console.log("log3");console.log(data);          } // successful response
    });
    console.log('End executeSql');
```

More info:
[https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#executeSql-property](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#executeSql-property)

**Comment by srchase** [comment]
@asyba 

Thanks for opening this issue.

Do you have a default region configured?

**Comment by srchase** [comment]
Can you try setting the region to 'us-east-1' explicitly?

```
var rdsDataService = new AWS.RDSDataService({apiVersion: '2018-08-01', region: 'us-east-1'});
```

**Comment by asyba** [comment]
Okey now I got this error:
```
 BadRequestException: ERROR: invalid cluster id: arn:aws:rds:us-east-1:xxxxx:db:xxxxxtest
    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
```

**Comment by asyba** [comment]
Second: can you create a feature to develop to use by default "AWS_REGION", if region not present? 
In Java SDK we have that feature.

**Comment by srchase** [comment]
Is your RDS a cluster?  Or a single instance?

There is a similar issue here for a customer receiving the same error when using an instance ARN: https://github.com/aws/aws-sdk-ruby/issues/1922

**Comment by asyba** [comment]
is a Single instance (mysql).
and my secret manager where created with  the template "Credentials for RDS database".

**Comment by asyba** [comment]
so is a bug like the other, ok

**Comment by srchase** [comment]
@asyba 

Regarding your feature request, the region can be configured a number of ways, including from AWS_REGION environmental variable or from a shared config file:

[Setting the AWS Region](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html)

**Comment by asyba** [comment]
But in Java SDK I can do this, without setting the region:
```
AmazonS3ClientBuilder.defaultClient()
```

* Using "Use the default credential provider chain (recommended)"
* https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
* https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/DefaultAwsRegionProviderChain.html

**Comment by svenmilewski** [comment]
I am using a cluster and maybe I am having the same issue. Setting the region manually didn't change anything. I am still getting 

`"errorMessage": "AWS.RDSDataService is not a constructor"` 

when using  

`new AWS.RDSDataService({apiVersion: '2018-08-01', region: 'us-east-1'});`

Any ideas?

**Comment by srchase** [comment]
@svenmilewski 

Refer to [Lambda Execution Environment and Available Libraries](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).

Lambda currently bundles 2.290.0, which does not have the RDSDataService included.

NPM has the latest version of the SDK.

You could manually bundle a current version of the SDK into your Lambda deployment package.

**Comment by svenmilewski** [comment]
@srchase 

Didn't know that page. Thanks. :-)  Is there atypical cycle where the SDK is updated in the Lambda Environment?

**Comment by srchase** [comment]
@svenmilewski 

Currently, there is not a set schedule.  

Per Lambda's [Best Practices](https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html), the SDKs are updated periodically.

Supplying a specific version of the SDK with your deployment package gives you full control over your dependencies.

**Comment by srchase** [comment]
@asyba 

The Service Team has indicated that only Aurora Clusters and Serverless Aurora are supported at this time.

**Comment by srchase** [comment]
Please refer to this documentation:

[https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html)

Note that the Data API is in beta for Aurora Serverless and is subject to change.
