### ISSUE TITLE
MediaConvert waitFor functionality is missing

### ISSUE THREAD

**Issue by yousharizvi** [aws/aws-sdk-js#2379]
Wait for a job created in MediaConvert is not available, although it has the callable function but missing the dependencies in the library to properly run it. Here's the PR #2378 .

**Comment by srchase** [comment]
Thanks for submitting this PR.  We will update you once we've had a chance to review.

**Comment by yousharizvi** [comment]
Follow PR #2378 for merging status from the maintainers.

**Comment by yousharizvi** [comment]
@srchase , any feedback on the PR?

**Comment by srchase** [comment]
@yousharizvi 

We've opened a request with the MediaConvert Team to review.  I'll update the PR, https://github.com/aws/aws-sdk-js/pull/2378, as there is additional feedback to share.

**Comment by srchase** [comment]
@yousharizvi 

The preferred way to monitor MediaConvert Jobs is via CloudWatch.

See [PART 2: Setup notifications when MediaConvert jobs finish](https://github.com/aws-samples/aws-media-services-vod-automation/blob/master/MediaConvert-WorkflowWatchFolderAndNotification/README-tutorial.md#part-2-setup-notifications-when-mediaconvert-jobs-finish) for an example and details on setting up CloudWatch and SNS to receive notifications.
