### ISSUE TITLE
Rekognition should really be able to access buckets in separate regions

### ISSUE THREAD

**Issue by edzillion** [aws/aws-sdk-js#2380]
This is a feature request.

Currently it seems AWS Rekognition cannot access buckets outside it's region. This would be less of an issue if Rekognition was available everywhere. 

For example, [from the SDK docs:](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Rekognition.html#detectModerationLabels-property) 
```
var params = {
  Image: { /* required */
    Bytes: new Buffer('...') || 'STRING_VALUE' /* Strings will be Base-64 encoded on your behalf */,
    S3Object: {
      Bucket: 'STRING_VALUE',
      Name: 'STRING_VALUE',
      Version: 'STRING_VALUE',
      Region: 'STRING_VALUE' <--- extra property for defining the bucket region
    }
  },
  MinConfidence: 0.0
};
rekognition.detectModerationLabels(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});

```

**Comment by srchase** [comment]
@edzillion,

Thanks for submitting this feature request.

This is a limitation of the Rekognition service: [see "Q: Can I use Amazon Rekognition with images stored in an Amazon S3 bucket in another region?" on the Rekognition FAQs](https://aws.amazon.com/rekognition/faqs/).

If the Rekognition service adds support for this feature, the SDK will be updated to make that available.

You're welcome to engage the Rekognition service on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=234).

**Comment by srchase** [comment]
I'm going to close out this issue, since it isn't actionable by the SDK without that change on the Service.  For anyone else that wants to express interest in this feature, @edzillion's forum post would be a good place to do that.
