### ISSUE TITLE
APIs need better error documentation

### ISSUE THREAD

**Issue by govindrai** [aws/aws-sdk-js#2382]
There are some APIs which return an empty object when there is nothing to be found, others throw an error. It's not always obvious which API will return what and twice this has thrown me for a loop because I did not expect an error. To make matters worse, the documentation does not state when an error will be thrown. Besides sending invalid params for which errors are expected, other errors should be documented. I think this would greatly help you sdk users. Something as simple as writing: if a policy does not exist for the lambda, an error will be returned would be a great first step.

**Comment by srchase** [comment]
@govindrai 

Thanks for opening this issue.

Are you referring to the getPolicy for the Lambda API specifically?

The [Lambda API Reference for getPolicy](https://docs.aws.amazon.com/lambda/latest/dg/API_GetPolicy.html) calls out that a ResourceNotFoundException will be returned when the resource (for example, a Lambda function or access policy statement) specified in the request does not exist.

Is there another getPolicy operation that is unclear?

**Comment by govindrai** [comment]
@srchase Thanks for the quick reply! Yes, I am specifically referring to the Lambda API, but I have gotten stuck like this, with other APIs as well, for example the same thing happened with SQS's getQueueUrl which behaves the same way. 

You're right the API reference does say so! Good to see it documented, but I never looked at this docs.. or even knew to look there.  Why isn't this information in the JS AWS SDK docs 😢 .. When I got the "ResourceNotFoundException" error, I started looking everywhere, thinking maybe my lambda doesn't exist, maybe my cloudwatch rule doesn't exist, etc and then finally (after much too long imo) realizing that if a policy doesn't exist an error will be returned. 

So yea, I'm wondering why that isn't documented on the SDK page.. it seems wrong to have to look in two areas... 

Another pain point is that when an error is returned, the error doesn't include information about which api call the error is coming from. This forces the developer to go through the logs and see where the code is breaking (sometimes it's easy to recognize if the error includes a certain keyword, but in this example, `the resource you requested does not exist` could not be more vague`. If it could include the API method, say a property as such attached on the error: `api: getPolicy`, that would also be a GREAT improvement to the api.

Thank you for listening to my woes haha

**Comment by srchase** [comment]
@govindrai 

Thanks for following up.  I'll tag this as a feature request.

For most services, the SDKs are programmatically generated from API resource models.  The SDK documentation is auto-generated at the same time from those resource models.  I can see how it would be useful if we were able to incorporate the documented errors within the SDK documentation.

For now, I would suggest checking the API Reference pages if you encounter any behavior in the that is not making sense.

**Comment by govindrai** [comment]
Thanks for listening. Will do, and sounds good to me. Appreciate your help!
