### ISSUE TITLE
SQS Message Counter

### ISSUE THREAD

**Issue by viamuli** [aws/aws-sdk-js#2383]
[Feature Request] (I do not know how to properly tag this)

It would be nice to have a method like "getQueueLength". I assume it can't be this hard to implement since you already provide auto scaling based on queue length and the management console also shows inflight and available message counters.

Keep up the good work!

**Comment by srchase** [comment]
@viamuli 

[getQueueAttributes](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#getQueueAttributes-property) returns a number of attributes about the queue, including counts of ```ApproximateNumberOfMessages```, ```ApproximateNumberOfMessagesDelayed``` and ```ApproximateNumberOfMessagesNotVisible```.

Do those attributes cover what you're looking for?

**Comment by viamuli** [comment]
Ahhh, perfect! Should have been looking at this method before. Thanks, it is exactly what we need.
