### ISSUE TITLE
Unexpected output from GetMetricWidgetImage

### ISSUE THREAD

**Issue by SocMinarch** [aws/aws-sdk-js#2385]
[https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatch.html#getMetricWidgetImage-property](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatch.html#getMetricWidgetImage-property)

Calling the `GetMetricWidgetImage` function using the following code:

```
cw.getMetricWidgetImage(params, function(err, data) {
	if (err)
		console.log(err, err.stack);
	else
		console.log(data);
});
```

where `params` is:
```
var MetricWidget = {
	"metrics": [
		[ "AWS/EC2", "CPUUtilization", "InstanceId", "***", { "period": 60 } ]
	],
	"view": "timeSeries",
	"stacked": false,
	"yAxis": {
		"left": {
			"min": 0,
			"max": 100
		}
	},
	"legend": {
		"position": "hidden"
	},
	"title": "CPU Usage",
	"period": 300,
	"width": 1840,
	"height": 250,
	"start": "-P1D",
	"end": "P0D"
}

MetricWidget = JSON.stringify(MetricWidget);

var params = {
	"MetricWidget": MetricWidget,
	"OutputFormat": "png"
}
```

 should return an output similar to the following, as described by the documentation:
```
<GetMetricWidgetImageResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">
<GetMetricWidgetImageResult>
<MetricWidgetImage>
iVBORw0KGgoAAAANSUhEUgAAAlgAAAGQEAYAAAAip...
</MetricWidgetImage>
</GetMetricWidgetImageResult>
<ResponseMetadata>
<RequestId>6f0d4192-4d42-11e8-82c1-f539a07e0e3b</RequestId>
</ResponseMetadata>
</GetMetricWidgetImageResponse>
```

Instead, the output is more like the following:
```
{
	MetricWidgetImage: Uint8Array(34056) [ 137, 80, 78, … ]
	ResponseMetadata: Object { RequestId: "*****" }
	<prototype>: Object { … }
}
```

The MetricWidgetImage isn't returned as a base64-encoded PNG as expected, instead it's a Uint8Array. 

This is with SDK version 2.366, API version 2010-08-01, on Windows 10 Version 1809, Firefox 63.0.3,

**Comment by srchase** [comment]
@SocMinarch 

Thanks for opening this issue.

The raw response body will look like the documented XML.  You could log that by doing the following:

```
var req = cw.getMetricWidgetImage(params)

req.on('success', (resp) => {
  console.log(resp.httpResponse.body.toString());
});

req.send();
```

The SDK un-marshalls the XML into the response object.
