### ISSUE TITLE
Is it possible include a custom header using AWS SDK with SQS service?

### ISSUE THREAD

**Issue by marceloneias** [aws/aws-sdk-js#2386]
I am using the AWS SDK SQS (with Nodejs) behind a router, to get through the router I need to include a custom header in the REQUEST.

I've seen this documentation (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#build-event) that talks about the .on('build') event in REQUEST:

```
var req = s3.putObject(params);
req.on('build', function() {
    req.httpRequest.headers['Custom-Header'] = 'value';
});
req.send(function(err, data) { ... });
```

However, using the SQS service is not working, no error has been thrown and the custom header is not included in the REQUEST, the build event is not triggered.

Is it possible include a custom header using AWS SDK with SQS service ? How make to make this work?

**Comment by srchase** [comment]
Can you provide the example of how you are using SQS?  Which version of the SDK are you using?

Doing the following will console.log the original request header set as 'bar':

```
const sqs = new AWS.SQS({region: 'us-west-2', http_wire_trace: true})

const params = {
  QueueName: 'foo',
}

var req = sqs.getQueueUrl(params);

req.on('build', () => {
  req.httpRequest.headers['Custom-Header'] = 'bar';
});

req.on('success', (resp) => {
  console.log(resp.request.httpRequest.headers)
})

req.send()
```

**Comment by marceloneias** [comment]
Thanks for your help, I was making a little mistake, your example helped me and it worked perfectly. Thank you!!!

**Comment by srchase** [comment]
@marceloneias 

You're very welcome.   Closing out this issue.
