### ISSUE TITLE
AWS-SDK issue w/ deleteMessageBatch, telling me MissingParameter but I'm not.

### ISSUE THREAD

**Issue by anwarhamr** [aws/aws-sdk-js#2388]
I see this issue that is closed and old.  Is there by chance a regression?  https://github.com/aws/aws-sdk-js/issues/40
I'm getting the following message:

***UnhandledPromiseRejectionWarning: MissingParameter: The request must contain the parameter DeleteMessageBatchRequestEntry.1.Id.***

I think I'm following the documentation to a `T` at [AWS-SDK/SQS][1]

I'm using this code
       

    var params = {
              Entries: _.map(_.uniqWith(data.Messages,d=>d.MessageId),d=>({
                Id: d.MessageId,
                ReceiptHandle: d.ReceiptHandle
              })),
              QueueUrl: xx.QueueUrl
            };
    await sqs.deleteMessageBatch(params).promise();

This is what params looks like at the time of sending; looks just like the docs if you ask me...

   

    { 
        Entries: [
          {
            Id: "83ba1e18-someid", 
            ReceiptHandle: "AQEB79CDI1Q+blablabla"
          }
        ]
        QueueUrl: "https://sqs.us-west-2.amazonaws.com/somequeeuurl"
    }

  [1]: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#deleteMessageBatch-property

My system:

    aws-sdk: "^2.367.0",
    MacOS - current
    node 8.12.0

**Comment by srchase** [comment]
@anwarhamr 

How are you confirming what params looks like at the time of sending?

**Comment by koneru9999** [comment]
@anwarhamr , I'm curious to know .. how did you solve this issue ?
I'm facing a similar issue but with `SendMessageBatch`

**Comment by anwarhamr** [comment]
```
function acknowledgeMessages(QueueUrl,messages) {
  //not sure why i have 'del' below, nothing in the docs mention it.  Delete this line if we see it's working.
  // var entries = _.map(messages,(m)=>({Id:'del'+m.MessageId,ReceiptHandle:m.ReceiptHandle})),
    var entries = _.map(_.uniqWith(messages,d=>d.MessageId),(m)=>({Id:m.MessageId,ReceiptHandle:m.ReceiptHandle})),
      params = {
        QueueUrl,
        Entries: entries,
      };
    // debug('acknowledgeMessages params', params);
    return sqs.deleteMessageBatch(params)
      .promise()
      .then(result => {
        // debug('acknowledgeMessages complete for params', params,result);
        return {result,params};
      });
  }
```
Where the messages parameter is the .Messages value of the object that receiveMessage passes us.
@koneru9999 I hope this helps.

**Comment by anwarhamr** [comment]
My above example is how I got it to work.
