### ISSUE TITLE
Documentation of AWS.Lambda.invoke FunctionName and Qualifier options doesn't match behavior with aliases

### ISSUE THREAD

**Issue by jmm** [aws/aws-sdk-js#2391]
# Repro

With aws-sdk@2.368.0, node@8.10.0, MacOS.

I attempt to invoke an alias of a lambda like:

```js
const alias = "someAlias";

const invokeConfig = {
  FunctionName: "someFunction",
  InvocationType: "RequestResponse",
  LogType: "Tail",
  Payload: JSON.stringify({}),
  Qualifier: alias,
};

const lambda = new AWS.Lambda;

lambda.invoke(invokeConfig, () => {});
```

# Expected Result

`someAlias` alias of `someFunction` is invoked.

# Actual Result

> AccessDeniedException: User: arn:aws:iam::... is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:...:...:function:someFunction

The [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property) of these options leads me to believe this should work.

> Specify just a function name to invoke the latest version of the function. To invoke a published version, use the `Qualifier` parameter to specify a version or alias.

> FunctionName — (String)
> The name of the Lambda function.
>
> Name formats
>
> Function name - `MyFunction`.
> Function ARN - `arn:aws:lambda:us-west-2:123456789012:function:MyFunction`.
> Partial ARN - `123456789012:function:MyFunction`.

> Qualifier — (String)
> Specify a version or alias to invoke a published version of the function.

In reality it seems that `Qualifier` is irrelevant and the alias must be appended to `FunctionName`, like:

```js
const invokeConfig = {
  FunctionName: `someFunction:${alias}`,
  InvocationType: "RequestResponse",
  LogType: "Tail",
  Payload: JSON.stringify({}),
};
```

Am I screwing something up or do the docs and behavior really not match?

**Comment by srchase** [comment]
@jmm 

Thanks for submitting this issue.

I'm able to execute the invoke operation using the alias successfully.  The error, returned by the Lambda service, indicates an issue with the permissions for the User invoking that function.

Did you verify that the user has permissions to invoke that Lambda function?

I'd suggest reviewing the [Using Identity-Based Policies (IAM Policies) for AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/access-control-identity-based.html#console-permissions-list-functions1) documentation.

**Comment by jmm** [comment]
Hi @srchase, thanks for your reply.

You're able to execute the operation with the alias only in `Qualifier`?

> Did you verify that the user has permissions to invoke that Lambda function?

Let me make sure I understand the question: permissions to invoke the unqualified function, or the particular alias? I'm able to invoke the alias by appending `:{aliasName}` to the `FunctionName` option as illustrated above.

The permissions policy I configured looks like:

```
{
    "Sid": "VisualEditor1",
    "Effect": "Allow",
    "Action": "lambda:InvokeFunction",
    "Resource": [
        "arn:aws:lambda:...:...:function:someFunction:*"
    ]
}
```

The permissions part was pretty confusing, as for example I saw comments online where people seemed to be saying they couldn't configure permissions per-alias, and in my experience it was _required_ to configure them per-alias or with a wildcard as I have here (though the policy editor acted like the wildcard is incorrect, yet that's what works).

**Comment by srchase** [comment]
@jmm 

Getting this working is a bit tricky:

If you use this as the resource in your policy:
```
arn:aws:lambda:...:...:function:someFunction
```

You can use the qualifier to invoke specific versions or aliases on that function (or leave out the qualifier, and invoke $LATEST).

If you need to restrict permissions on and only want to allow your policy permissions to a specific alias or version, the resource needs to be fully qualified:
```
arn:aws:lambda:...:...:function:someFunction:myAlias
```

or
```
arn:aws:lambda:...:...:function:someFunction:myVersion
```

When using the fully qualified resource in your policy, you _cannot_ use the qualifier and must invoke that function with the matching fully qualified ARN:

```
const invokeParams = {
  FunctionName: 'arn:aws:lambda:...:...:function:someFunction:myAlias'
}
  
lambda.invoke(invokeParams, (err,data) => {
  console.log(err,data)
})
```

This page has details on [Versioning, Aliases, and Resource Policies](https://docs.aws.amazon.com/lambda/latest/dg/versioning-aliases-permissions.html).

**Comment by jmm** [comment]
Thanks for your reply.

> Getting this working is a bit tricky

Agreed!

> When using the fully qualified resource in your policy, you cannot use the qualifier and must invoke that function with the matching fully qualified ARN:

Though I can't use `Qualifier`, it doesn't seem to be necessary to use the full ARN, rather I can do this:

```js
const invokeConfig = {
  FunctionName: "someFunction:someAlias",
};
```

In any case, for my money it's really counterintuitive that although the function name and alias names are configured in the lambda, and there is a `FunctionName` parameter and a separate `Qualifier` parameter that's advertised as specifying the alias, the permissions policy dictates how the alias must be referenced from the invoke call -- as part of `FunctionName` in this case.

Thanks for the link. It's hard to know exactly how that relates to making these invoke calls without knowing what happens under the hood (I haven't looked). And this part makes it sound like it would not be possible to invoke an alias at all using the policy:

> If you use an unqualified function name (such as `helloworld`), the permission is valid only for invoking the `helloworld` function using the unqualified function ARN (using any other ARNs will result in a permission error).

Whereas you're saying that's a prerequisite to using `Qualifier` to specify the alias (and I see that in my testing). I interpret that to mean permission has been granted only for the unqualified function and no aliases, so that description seems problematic in its own right. I guess the invoke operation using `Qualifier` does something other than append the alias to the ARN, but it's certainly not clear from that description that it'll be possible to invoke aliases somehow using that policy.

I think the most sensible thing would be if this could be implemented so that alias or version can consistently be specified with `Qualifier`. If that's not possible, I'd suggest the following documentation changes:

* Insert an explanation or link to an explanation of how configuration of permission policy affects applicability of `Qualifier`.

  It shouldn't make this blanket statement that's not always true:
  > To invoke a published version, use the Qualifier parameter to specify a version or alias.

* In the name formats examples for `FunctionName`, include the alias versions, e.g.:
  > Function name - `MyFunction`.
  > Function and alias name - `MyFunction:MyAlias`.

  And an explanation of when they're applicable.

* In the `Qualifier` documentation, explain when it is / isn't applicable.

* Improving that part in the [Versioning, Aliases, and Resource Policies](https://docs.aws.amazon.com/lambda/latest/dg/versioning-aliases-permissions.html) documentation would also make sense.

In the meantime, thanks for the help understanding what's happening!

**Comment by srchase** [comment]
I've passed along this feedback for the Lambda Service Team to review.

**Comment by jmm** [comment]
Ok thanks. Does that team maintain this documentation?

**Comment by srchase** [comment]
@jmm 

Yes, the majority of the documentation in the SDK is generated from the API models.

The Service Team is reviewing and would update their model, which would update the documentation in each of the SDKs.

You can build the documentation locally (from source) via the docs:api rake task:

```
bundle exec rake docs:api
```

**Comment by jmm** [comment]
Thanks! With this ticket being closed, is there anywhere it'll be tracked?

**Comment by srchase** [comment]
We'll update this thread with that progress.  It's tracked internally, but this is the best place for you to stay updated.

**Comment by jmm** [comment]
Thanks!
