### ISSUE TITLE
CredentialsError: "Missing credentials in config" with userpool/Identitypool authenticated user access to S3 file

### ISSUE THREAD

**Issue by muzab** [aws/aws-sdk-js#2406]
I am trying to run the code below through web java-script sdk in the browser to get authenticated access to an S3 file. Before doing that I wanted to ping the bucket to check if it exists. Currently the bucket is having a public access and it will be restricted to a userpool later. I assume my JWT tokens should be propagated further after login to get an authenticated access to the S3 bucket file (as a user belonging to a user/identity pools).

Code:
var cognitoUser = userPool.getCurrentUser();

if (cognitoUser != null) {
	cognitoUser.getSession(function(err, result) {
		if (result) {
			console.log('You are now logged in.');

			// Add the User's Id Token to the Cognito credentials login map.
			AWS.config.credentials = new AWS.CognitoIdentityCredentials({
				IdentityPoolId: 'YOUR_IDENTITY_POOL_ID',
				Logins: {
					'cognito-idp.<region>.amazonaws.com/<YOUR_USER_POOL_ID>': result.getIdToken().getJwtToken()
				}
			});
		}
	});
}

		var params = {
  				Bucket: 'bucket234567' /* required */
			     };
		s3control.waitFor('bucketNotExists', params, function(err, data) {
  			if (err) console.log(err, err.stack); // an error occurred
  			else     console.log(data);           // successful response
			});

Error: 
CredentialsError: "Missing credentials in config"
	r https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:52:25054
	getCredentials https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:52:25582
	Core https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:53:22414
	callListeners https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:21841
	emit https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:21578
	emitEvent https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:7534
	e https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:3210
	runTo https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:57:3782
	runTo https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:4858
	send https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:4756
	wait https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:11147
	waitFor https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:25767
	onload file:///home/ali/Desktop/Work/DesktopGuiAWSPortal/userDetails.html:112:3
 r@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:52:25054
getCredentials@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:52:25582
[285]</a.EventListeners.Core</<@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:53:22414
callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:21841
emit@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:21578
emitEvent@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:7534
e@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:3210
[336]</i.prototype.runTo@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:57:3782
runTo@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:4858
send@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:4756
wait@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:11147
waitFor@https://sdk.amazonaws.com/js/aws-sdk-2.358.0.min.js:55:25767
window.onload@file:///home/ali/Desktop/Work/DesktopGuiAWSPortal/userDetails.html:112:3
userDetails.html:113:15
Array(6) [ {…}, {…}, {…}, {…}, {…}, {…} ]
userDetails.html:79:5 

What am I missing here?
~/.aws/config
[default]
region=us-east-1

~/.aws/credentials
[default]
aws_access_key_id=XXXXXXXXXX
aws_secret_access_key=XXXXXXXXXX

~/.bash_profile
<empty>

**Comment by srchase** [comment]
@muzab 

The formatting of your code example is a bit difficult to decipher.

Where is ```s3control``` initialized?

Are you using trying to use the credentials in ~/.aws/credentials?
