### ISSUE TITLE
AWS SQS receiveMessage called sequentially though using parallel execution

### ISSUE THREAD

**Issue by nehagupta-itbhu** [aws/aws-sdk-js#2412]
I am using below code in Lambda and trying to receiveMessage from SQS parallely but its taking 3 secs to fetch 200 messages from SQS with a batch of 10, it seems the receiveMessage is being processed sequentially not parallely

`exports.handler = function(event, context, callback) {
let tasks = [];
        
        //Create 20 receive message tasks
for(let i=0; i<20; i++){
            tasks.push(function(callback) {collectMessages(callback);});
 } 
async.parallel(tasks,
        // optional callback
        function(err, results) {
             console.log('Start processing results');
             if (err) {
                    console.log('Error on Message Recieve');
                    console.log(err);
                    return callback(err);
                }
            results.forEach(data => { 
                    if (undefined === data.Messages) {
                        console.log('No Messages Object');
                    } else if (data.Messages.length > 0) {
                        console.log('Received Messages Count: ' , data.Messages.length);
                        for (var x=0;x<data.Messages.length;x++) {
                            // process
                            let event = JSON.parse(data.Messages[x].Body);
                            message_batch = message_batch.concat(event);
                            delete_batch.push({'Id':data.Messages[x].MessageId,'ReceiptHandle':data.Messages[x].ReceiptHandle});
                        }
                    } else {
                        console.log('No Messages Count');
                    }
            });
            console.log('After receive Messages Count: ' + message_batch.length, ", delete batch: ", delete_batch.length);

            if(message_batch.length == 0){
                console.log('Nothing to process');
                return callback(null,null);
            }
            
            return processMessage(message_batch, function(error, responseData){
                if(error){
                    return callback(error);
                }
                //Delete from SQS
                deleteProcessedMessagesFromSQS(delete_batch);
                return callback(null, successResponse);
            });
            
        });
};
function collectMessages(callback){
    sqs.receiveMessage({
                QueueUrl: QUEUE_URL,
                MaxNumberOfMessages: 10,
                WaitTimeSeconds: 0
            }, function(err, data) {
                callback(err, data);
    });
}`

**Comment by nehagupta-itbhu** [comment]
@srchase 
If I call collectMessages in a for loop of 20 iterations, the time taken is same as calling async.parallel for 20 tasks

**Comment by srchase** [comment]
@nehagupta-itbhu 

Refer to the Lambda documentation on [Managing Concurrency](https://docs.aws.amazon.com/lambda/latest/dg/concurrent-executions.html).

Rather than an individual function that makes multiple SQS calls, a better model would be to have multiple invocations of a Lambda function that makes a single SQS call.

If you have additional questions, post on the [AWS Lambda Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=186).  They are better suited to help answer Lambda specific questions and provide best practices beyond the documentation.
