### ISSUE TITLE
StepFunction: listExecutions Unexpected token in JSON

### ISSUE THREAD

**Issue by knalx** [aws/aws-sdk-js#2414]
Error during requesting execution list of existing step functions. Looks like AWS endpoint answers with invalid JSON. 

```javascript
stepfunctions.listExecutions( { stateMachineArn: mystatMachineArn }, function (err, data) ) {
...
}
```

Response from aws endpoint I debugged looks wired. It contains list of executions but at one moment JSON breaks:
```
{"executions":[{"executionArn":"arn:aws:states:eu-west-1:**********:execution:SubscriptionStateMachine-Production:271637-603e1d21-70c5-402a-a7ab-ce78af2ec4ee","name":"271637-603e1d21-70c5-402a-a7ab-ce78af2ec4ee","startDate":1.544436054212E9,"stateMachineArn":"arn:aws:states:eu-west-1:**********:stateMachine:SubscriptionStateMachine-Production","status":"RUNNING"}, 
...
{"executionArn":"arn:aws:states:eu-west-1:**********:execution:SubscriptionStateMachine-Production:244118-bd0351f4-d9d7-4bf8-8352-030023bf55fe","name":"244118-bd0351f4-d9d7-4bf8-8352-0300{"executions":[{"executionArn":"arn:aws:states:eu-west-1:**********:execution:SubscriptionStateMachine-Production:271637-603e1d21-70c5-402a-a7ab-ce78af2ec4ee","name":"271637-603e1d21-70c5-402a-a7ab-ce78af2ec4ee","startDate":1.544436054212E9,"stateMachineArn":"arn:aws:states:eu-west-1:**********:stateMachine:SubscriptionStateMachine-Production","status":"RUNNING"},
...
```
Broken part:
244118-bd0351f4-d9d7-4bf8-8352-0300{"executions"

"aws-sdk": "^2.373.0"

**Comment by srchase** [comment]
@knalx 

Thanks for opening this issue.

I'm not able to get any malformed responses from the Step Functions service in trying to reproduce this issue.

Do you get this error every time?  Or was it a single instance?

Are there any specifics of when this error occurs that could help narrow the issue?

**Comment by knalx** [comment]
I reproduced this error many times. Always JSON parsing error. But now it breaks at the different place.

```
{"executionArn":"arn:aws:states:eu-west-1:******:execution:Subscriptio{"executions":[{
```

My code just reading all running execution

**Comment by srchase** [comment]
Which 'symbol number 17268' are you referring to?

**Comment by knalx** [comment]
The length of the raw response string from your API. May be you have some network level balancers that messed up.

**Comment by srchase** [comment]
@knalx 

Are there any additional details you can provide that would help with a reliable reproduction of this error?  

If there is a malformed response being returned by the service, it would help if we could figure out exactly when that happens.
