### ISSUE TITLE
Promise doesn't complete or error when 'The security token included in the request is expired' error is thrown

### ISSUE THREAD

**Issue by Strydom** [aws/aws-sdk-js#2415]
When using `.promise` on the Request object the promise will not succeed or fail when the `security token has expired` error is thrown.

Example code:
```javascript
const response = await dynamo.getItem({
    TableName: table,
    Key: {
      databaseId: { S: databaseId }
    }
  }).promise();

console.log(response);
```

Never get's to `console.log(response);`

I would expect this error to fail the `Promise` and throw an error?
You can see the expected behaviour when using the callback style instead of promises.

```javascript
dynamo.getItem({
    TableName: table,
    Key: {
      databaseId: { S: databaseId }
    }
  }, (err, data) => {
    console.error(err);
  });
```

**Comment by Strydom** [comment]
@srchase 
I'm using `await` but have tested with `.then().catch()` and neither work

**Comment by srchase** [comment]
@Strydom 

If you run this with expired credentials:

```
const resp = dynamo.listTables().promise();

console.log(resp);  /// logged as Promise { <pending> }
```

You should eventually receive this error ```UnhandledPromiseRejectionWarning: ExpiredTokenException: The security token included in the request is expired```

Are you using await within another async function?

**Comment by Strydom** [comment]
Wow okay so it does throw it eventually, I didn't expect it to take longer than 10 seconds?

If you use a callback it fails almost immediately, why does it take so long when using a promise?

**Comment by srchase** [comment]
@Strydom 

Using Try/Catch outside of Async/Await will catch this issue earlier, rather than having to wait for the ```UnhandledPromiseRejectionWarning```.
