### ISSUE TITLE
Plans to support StartStreamTranscription for Amazon Transcribe?

### ISSUE THREAD

**Issue by dominiceden** [aws/aws-sdk-js#2416]
I watched the keynote recently where streaming was introduced for the Amazon Transcribe product. Looks really fantastic and I'd like to set up a prototype browser application in JS. But it seems like the SDK doesn't support the StartStreamTranscription function that is key for this?

https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartStreamTranscription.html

Are there any plans to introduce this into the SDK soon? I would have thought streaming from the browser would be a main use case.

**Comment by srchase** [comment]
@dominiceden 

Thanks for opening this feature request.   We're reviewing the best way to support this in the SDK.

**Comment by dominiceden** [comment]
@srchase Great, thanks for the quick response! I'll keep my eyes on this one then.

**Comment by kidplug** [comment]
Is any work being done on this? I'd love to get a look at it. thanks.

**Comment by taikim8484** [comment]
Looking forward too. Is there another way to use this feature for now? Thank you.

**Comment by OvidijusParsiunas** [comment]
Would enforcing the use of StartStreamTranscription not be applicable via the use of existing web-socket libraries? I am wondering what is the particular need for the use of HTTP2 in this regard. Thankyou.

**Comment by orgads** [comment]
Is there any package that supports this service on node.js?

**Comment by formigone** [comment]
Any progress on this? If not, could you please comment on a specific question about implementing this on my own: https://forums.aws.amazon.com/thread.jspa?messageID=896709

The question there is about the [event stream encoding](https://docs.aws.amazon.com/transcribe/latest/dg/streaming-format.html#event-stream), as well as the broad 200 response that simply says
```javascript
{
  "Output":{
    "__type":"com.amazon.coral.service#SerializationException"
  },
  "Version":"1.0"
}
```

**Comment by kevenleone** [comment]
> Any progress on this? If not, could you please comment on a specific question about implementing this on my own: https://forums.aws.amazon.com/thread.jspa?messageID=896709
> 
> The question there is about the [event stream encoding](https://docs.aws.amazon.com/transcribe/latest/dg/streaming-format.html#event-stream), as well as the broad 200 response that simply says
> 
> ```js
> {
>   "Output":{
>     "__type":"com.amazon.coral.service#SerializationException"
>   },
>   "Version":"1.0"
> }
> ```

Hi @formigone , i'm with this same problem, you found any solution ?

**Comment by Laxmikant04** [comment]
> Is there any package that supports this service on node.js?

I am also looking for the same . Please let me know if anyone found the solution.

**Comment by Laxmikant04** [comment]
Hi @srchase ,
 Referring to the official doc ,i am able to make a session with AWS streaming transcribe service and getting proper response .

Now when i am trying to pass audio chunk in eventMessage , i am getting error 
message-type aexception{"Message":"Could not process the audio stream that you provided. Try your request again."}

Please refer to my Code , Any help would be much appreciated

[aws_streaming_transcribe_demo.zip](https://github.com/aws/aws-sdk-js/files/3337745/aws_streaming_transcribe_demo.zip)

 .

**Comment by cag945** [comment]
I too am running into the same issue "Could not process the audio stream that you provided". Are there any solutions to this? Now that Google doesn't allow electron to use STT I fear I've run out of options.

**Comment by pietrop** [comment]
👋 
Would it be possible to implement this in the node SDK via web socket rather then HTTP2? 
As per the AWS example, [amazon-transcribe-websocket-static](https://github.com/aws-samples/amazon-transcribe-websocket-static)?

**Comment by qasim9872** [comment]
I had a similar requirement for using the AWS transcribe service with their WebSocket API in node js. Seeing as there was no support for this in the official package as of yet, I have gone ahead and written a package that is called AWS-transcribe and can be found [here](https://www.npmjs.com/package/aws-transcribe). I hope that helps. 

It provides a stream interface around the WebSocket, and can be used like the below example

    import { AwsTranscribe, StreamingClient } from "aws-transcribe"

    const client = new AwsTranscribe({
        // if these aren't provided, they will be taken from the environment
        accessKeyId: "ACCESS KEY HERE",
        secretAccessKey: "SECRET KEY HERE",
    })

    const transcribeStream = client
        .createStreamingClient({
            region: "eu-west-1",
            sampleRate,
            languageCode: "en-US",
        })
        // enums for returning the event names which the stream will emit
        .on(StreamingClient.EVENTS.OPEN, () => console.log(`transcribe connection opened`))
        .on(StreamingClient.EVENTS.ERROR, console.error)
        .on(StreamingClient.EVENTS.CLOSE, () => console.log(`transcribe connection opened`))
        .on(StreamingClient.EVENTS.DATA, (data) => {
            const results = data.Transcript.Results
    
            if (!results || results.length === 0) {
                return
            }
    
            const result = results[0]
            const final = !result.IsPartial
            const prefix = final ? "recognized" : "recognizing"
            const text = result.Alternatives[0].Transcript
            console.log(`${prefix} text: ${text}`)
        })

    someStream.pipe(transcribeStream)

**Comment by jnorris441** [comment]
Please add this to your SDK so I don't have to give IBM money

**Comment by ernestodossantos** [comment]
Any ETA you can share? We need to perform transcriptions in real time from a .NET Core application.

**Comment by kellertk** [comment]
Hi. This is available in v3 of the SDK. Please migrate to AWS SDK for JS v3.
