### ISSUE TITLE
S3 putObject puts object into folder for some reason

### ISSUE THREAD

**Issue by batrudinych** [aws/aws-sdk-js#2418]
**Verified on:**
**Node.js**: 6.10.0, 8.9.3, 10.11.0
**aws-sdk**: 2.373.0, 2.360.0
**ubuntu 16.04**

**Code:**
```
const aws = require('aws-sdk');
const s3 = new aws.S3();
const fs = require('fs');
const fileData = fs.readFileSync('./tmp/d');
const Key = 'dkoker';
s3.putObject({
  Bucket: 'dkoker-test',
  Body: fileData,
  Key,
}).promise().then(() => console.log('Object recorded')).catch(e => console.log(e));
```
**Issue description:**
Put object operation puts object into a folder with bucket name if bucket name contains Key value. 
* The result of this operation is the following: bucket `dkoker-test` has a folder `dkoker-test` with a file `dkoker` inside.
* The expected result: `dkoker` file lays inside bucket, no nested folders should exist

In example above: bucket name is `dkoker-test` (disregard what it means). Name of file is `dkoker` starts with the same characters as name of bucket: `dkoker-test`. Here is the list of tested Key values:
* `dkoker`
* `dkoke`
* `dkok`
* `d`
For all of them an intermediate folder was introduced for some reason
Once I've changed Key value to `m`, everything worked as expected

**Comment by gberdzenishvili** [comment]
+1

**Comment by srchase** [comment]
@batrudinych 

Thanks for opening this issue.  Appreciate the clear repro.

We're working to get this fixed and will update this issue when we get it resolved.

**Comment by Le0Michine** [comment]
just faced that issue, looks like version 2.296.0 was fine and the bug was introduced in v2.297.0

**Comment by srchase** [comment]
A fix for this was merged.  Closing this issue.
