### ISSUE TITLE
Feature request: Ability to set headers for an object

### ISSUE THREAD

**Issue by batrudinych** [aws/aws-sdk-js#2419]
There is a method `headObject`, which returns S3 object's metadata. Seems that `putObject` / `upload` are the only methods, which accept metadata to be set for an S3 object.
It would be helpful to have a separate method for setting metadata for already existing S3 object.
If I had a static website hosting configured with S3, it would be handy to be able to manipulate Cache-Control headers, etc. from the SDK.

**Comment by srchase** [comment]
Hello @batrudinych 

Thanks for opening this request.

On the [Object Key and Metadata](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html) documentation page, it's specified that:

> You can set object metadata at the time you upload it. After you upload the object, you cannot modify object metadata. The only way to modify object metadata is to make a copy of the object and set the metadata. 

You can use the [copyObject](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property) operation in the SDK and do something like this:

```
const params = {
  Bucket: 'myBucket',
  Key: 'myObjectKey',
  CopySource: '/myBucket/myObjectKey',
  MetadataDirective: 'REPLACE',
  Metadata: {
    'Cache-Control': 'max-age=86400'
  }
}

s3.copyObject(params, (err,data) => {
  console.log(err,data)
})
```

**Comment by batrudinych** [comment]
Hello @srchase 

I noticed that the metadata may be provided during upload or changed using copyObject operation. That's the reason I've made this request.
I am able to change existing object's metadata in S3 Management Console, but not able to do it through aws-sdk, which seems weird.

Is there any change the ability to modify existing object's metadata could be added? Would be very handy to have this in order to be able to control caching, etc. from the code omitting unnecessary copy operation

**Comment by srchase** [comment]
@batrudinych 

The S3 Service does not provide an API which allows metadata to be modified on an existing object.

The console sometimes provides capabilities that are not directly possible with an API call.

You're welcome to post on the [S3 AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) requesting they add this API operation.  If S3 makes that change, it will get added to the SDK.

**Comment by batrudinych** [comment]
@srchase 

Will raise a question with them and post a link to this thread, thanks.

**Comment by srchase** [comment]
@batrudinych 

Thanks for posting! 

As I mentioned before, this API addition would be up to the S3 Team.  I'll opt to close this issue here.  Anyone else with feedback is welcome to respond to your post.
