### ISSUE TITLE
ECS: Task start fails when using enableECSManagedTags

### ISSUE THREAD

**Issue by byF** [aws/aws-sdk-js#2425]
AWS SDK version: 2.376.0

`ECS.runTask({..., enableECSManagedTags: true},...)` executes, but the task does not get into `taskRunning` state. Stopped Reason is: `Unexpected EC2 error while attempting to tag the network interface: InvalidParameterValue`

`arn:aws:iam::aws:policy/aws-service-role/AmazonECSServiceRolePolicy` contains CreateTag permission.

**Comment by srchase** [comment]
@byF 

Thanks for opening this issue.

That error is returned by the ECS service and not the SDK itself.  Have you raised the issue with the ECS Service Team?

Have you referred to this documentation? [Tagging Your Amazon EC2 Resources](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html)

**Comment by byF** [comment]
@srchase Nope, I have not raised it with them yet. This is the relevant documentation:https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-using-tags.html; there is nothing apparent (my IAM user is enrolled into new ARN format for ECS)

Anyhow, where should I move this issue?

**Comment by srchase** [comment]
The [Amazon ECS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=187) is the best place to post this kind of question.

Have you tried using the AWS CLI run-task command?

**Comment by byF** [comment]
Nope, but I've just did the same config through the web console and it fails as well.

Thanks, I'm going to ask on that forum.

**Comment by srchase** [comment]
@byF 

Appreciate you following up on this issue!

**Comment by Gr1mR3aver** [comment]
So what is the bug?  I'm also hitting this issue - do you have a URL or incident# for reference?

**Comment by j1mb0jay** [comment]
Suffering same issue

**Comment by srchase** [comment]
@j1mb0jay and @Gr1mR3aver,

The [Amazon ECS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=187) is the best place to engage the ECS team.  

Have either one of you posted a question there?

**Comment by cleverguy25** [comment]
Suffering the same issue

**Comment by bentito** [comment]
Same here, is there a workaround?

**Comment by rfpludwick** [comment]
I'm experiencing the same issue, but not via the SDK - I'm getting the problem via the console. Additionally, @srchase, I cannot post the question in said forum because their forum is not allowing me to do so.

**Comment by srchase** [comment]
This issue is being worked on by the ECS and EC2 Service Teams.  Once it is resolved, I will update this issue.

**Comment by rfpludwick** [comment]
Thanks @srchase

**Comment by lucasltv** [comment]
Same issue here too

**Comment by axiomoixa** [comment]
Same issue as well

**Comment by mirhec** [comment]
I could solve the problem by opting out from the new ARN and resource id format:

<img width="1215" alt="grafik" src="https://user-images.githubusercontent.com/5173805/50342109-f42a8e00-0521-11e9-92e4-6a0bea928490.png">

Clicking on "Configure ECS ARN setting" and disabling all checkboxes solved the problem for me.

**Comment by tabascoterrier** [comment]
I'm also opted into the new ARN and resource format.  I was able to work round the issue in the GUI by unselecting "Enable ECS managed tags"

**Comment by srchase** [comment]
@byF 

The service team has indicated that this issue has been resolved.
