### ISSUE TITLE
S3 upload stream

### ISSUE THREAD

**Issue by sm2017** [aws/aws-sdk-js#2430]
I have an issue with `upload` method and `stream`
```js
await s3.upload({
    Bucket: 'buket',
    Key: 'key',
    Body: readableStream,
}).promise(),
```
As I await for upload promise , I expect it throws error in case of failure but when we have ` readableStream.emit('error', err);` , the promise is not rejected and we await for ever for a pending promise

I create a `myCustomPromise` that rejected on stream error and resolved on stream end

```js
await Promise.all([
    s3.upload({
        Bucket: 'buket',
        Key: 'key',
        Body: readableStream,
    }).promise(),
    myCustomPromise
]);
```

It works , But I am not sure about memory leakage

**Comment by AllanFly120** [comment]
Hi @sm2017 

Can you try using callback style and see if error can be supplied to callback?

```javascript
s3.upload({
    Bucket: 'buket',
    Key: 'key',
    Body: readableStream,
}, function(data, err) {
    if (err) console.log('error: ', err)
})
```

**Comment by sm2017** [comment]
@AllanFly120 I tried using callback style , it called and the console log is

```bash
error:  { ETag: '"b7876ff6d244133c31fb35a24f243157"',
  Location:
   'http://localhost:1000/test/bb7a994c-90d4-4f6d-8ae9-3b039b89cb01.jpg',
  key: 'bb7a994c-90d4-4f6d-8ae9-3b039b89cb01.jpg',
  Key: 'bb7a994c-90d4-4f6d-8ae9-3b039b89cb01.jpg',
  Bucket: 'test' }
```

**Comment by srchase** [comment]
@sm2017 

I assume you're using Node, but wanted to check that you're not trying to do this in a browser.

Is that correct?  Which version of the SDK are you using?

**Comment by sm2017** [comment]
Yes , I'm using node v10.13.0
SDK version : 2.375.0

**Comment by srchase** [comment]
@sm2017,

I'm able to do the following and the error is caught successfully:

```
const AWS = require('aws-sdk');
const s3 = new AWS.S3({region: myRegion});
const { Readable } = require('stream');
const readStream = new Readable();

async function doUpload(body) {
  try {
    const params = {
      Bucket: 'myBucket',
      Key: 'myKey',
      Body: body,
    }
  await s3.upload(params).promise()
  } catch (err) {
    console.log('err: ', err);
  }
}

doUpload(readStream)

readStream.push('some text');
readStream.emit('error', new Error('foo error'))
readStream.push(null);
```

returns:
```err:  Error: foo error```

Perhaps something else is going on outside the SDK?

**Comment by sm2017** [comment]
@srchase , I do very similar as you do, If your code works my code must works too

Currently my emitted error is not thrown by `await s3.upload(params).promise()` and this line await for ever

So I use
```js
await Promise.all([
    s3.upload(params).promise(),
   myPromise
])
```

`myPromise` rejected on stream error and resolved on stream end , So the `await Promise.all` is not await for ever because when we have an emitted error myPromise is rejected

>Perhaps something else is going on outside the SDK?

What can happens out side of SDK ?

**Comment by srchase** [comment]
@sm2017 

Is the error being emitted properly?  That would be the next place to check.
