### ISSUE TITLE
listUserTags missing in aws-sdk

### ISSUE THREAD

**Issue by highlander004** [aws/aws-sdk-js#2438]
I'm trying to retrieve tags associated to my users in IAM in a Lambda function with the function listUserTags (as described here : https://docs.amazonaws.cn/AWSJavaScriptSDK/latest/AWS/IAM.html#listUserTags-property).

But when I run my code, it gives me the following error : TypeError: iam.listUserTags is not a function

I checked in the source and listUserTags seems to be missing from aws-sdk.js

**Comment by highlander004** [comment]
@srchase 

I'm trying to do a Lambda function with NodeJS 8.10. For now, I'm just trying to make the example in the documentation work.

Here's the function I made:

```
var AWS = require('aws-sdk');

exports.handler = function(event, context, cb) {
    var iam = new AWS.IAM();
    var params = {
        UserName: "anika"
    };
    iam.listUserTags(params, function(err, data) {
        if (err) console.log(err, err.stack); // an error occurred
        else     console.log(data);           // successful response
    });
};
```
As you can see, it's pretty much the same as the documentation.

As for the source I checked, it's the lastest version (2.379.0).

Also, I found the function in aws-sdk-react-native.js, but not in aws-sdk.js

**Comment by srchase** [comment]
@highlander004 

Lambda is currently using 2.290.0.  Refer to this page for which version of the SDK that Lambda is currently using: [Lambda Execution Environment and Available Libraries](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)

In order to use this IAM operation, you'll need to include a more recent version of the SDK in your Lambda package.

**Comment by highlander004** [comment]
@srchase 

Thanks for the info.

Do you know when the new version will be added to Lambda?

**Comment by srchase** [comment]
@highlander004 

I do not have any information regarding when Lambda will move to a newer version of the SDK.

Your best bet is to include a specific version of the SDK in your Lambda package.  The Lambda provided version is largely for convenience, and including it yourself will give you greater control over when and how those updates are rolled out.
