### ISSUE TITLE
sdk issue

### ISSUE THREAD

**Issue by fuzzykarthik** [aws/aws-sdk-js#2439]
Dear team, 
I was using alexa sdk and aws sdk for my lambda function. I tried to upgrate that to version 2. But it is throwing error , not able to rollback my changes as well.
Can you please help me on this
i downloaded from the below link
https://developer.amazon.com/blogs/alexa/post/decb3931-2c81-497d-85e4-8fbb5ffb1114/now-available-version-2-of-the-ask-software-development-kit-for-node-js 
but existing modules also throwing error

**Comment by fuzzykarthik** [comment]
[ts]
Could not find a declaration file for module 'alexa-sdk'. 'd:/Node Projects/SampleInitial/alexa-mortgage/node_modules/alexa-sdk/index.js' implicitly has an 'any' type.
  Try `npm install @types/alexa-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module 'alexa-sdk';` [7016]
module "d:/Node Projects/SampleInitial/alexa-mortgage/node_modules/alexa-sdk/index"

**Comment by srchase** [comment]
@fuzzykarthik 

I believe you've opened this on the wrong repository.

You'll want to open this issue on the [alexa-skills-kit-sdk-for-nodejs](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues) repository.

**Comment by fuzzykarthik** [comment]
Ok I will work on it.
Kindly let me know your team support hours.

Thanks in advance
Regards
Karthik R
