### ISSUE TITLE
s3.copyObject causing ForwardAccessSessionError

### ISSUE THREAD

**Issue by NamelessHH** [aws/aws-sdk-js#2447]
On December 20th 1AM PST our automated tests picked up an issue with moving a file from one S3 bucket to another.
`
our code
  var s3 = new AWS.S3();
  s3.copyObject({
    Bucket: params.destBucket,
    CopySource: params.srcBucketAndKey,
    Key: params.destKey,
    ACL: params.destAcl || 'authenticated-read'
  }, cb);
`
where the params.srcBucketAndKey is a bucket from us-east-1 and params.destBucket is a bucket in us-west-2.  We pass the key and secret on init of the service through the config on initialization of the service

 `        
            "accessKeyId": "xxxx",
            "secretAccessKey": "xxxx"
`

we're seeing a strange error.  Its happening intermittently (average 5/7 times the endpoint is hit).  We've checked and the file is always in the the source bucket so we've determined that isn't the issue.

`
{
        "message": "Expecting FAS credential, but got null.",
        "name": "ForwardAccessSessionError",
        "stack": "ForwardAccessSessionError: Expecting FAS credential, but got null.\n    at Request.extractError (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/services/s3.js:328:35)\n    at Request.callListeners (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/sequential_executor.js:100:18)\n    at Request.emit (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/request.js:604:14)\n    at Request.transition (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/request.js:21:12)\n    at AcceptorStateMachine.runTo (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/request.js:22:9)\n    at Request.<anonymous> (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/request.js:606:12)\n    at Request.callListeners (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/sequential_executor.js:104:18)\n    at Request.emit (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/request.js:604:14)\n    at Request.transition (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/request.js:21:12)\n    at AcceptorStateMachine.runTo (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/request.js:22:9)\n    at Request.<anonymous> (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/request.js:606:12)\n    at Request.callListeners (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/sequential_executor.js:104:18)\n    at callNextListener (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/sequential_executor.js:90:14)\n    at IncomingMessage.onEnd (/home/app/node/mm-course-content/node_modules/mf-file-storage/node_modules/aws-sdk/lib/event_listeners.js:183:11)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)",
        "code": "ForwardAccessSessionError"
    }
`
I've tried searching for ForwardAccessSessionError and I can't find anything on it.

**Comment by NamelessHH** [comment]
We're using aws-sdk v2.0.23

**Comment by srchase** [comment]
@NamelessHH 

Thanks for opening this issue.  There appears to be an underlying issue with the S3 Service that is being investigated.  The error generated and returned by the S3 service, and not the SDK.

I will update this issue once there is additional information from the S3 Service Team.

**Comment by NamelessHH** [comment]
I don't know if you guys fixed it on your end or not but 5 min ago I update the sdk from v2.0.23 to v2.1.0 and it seemingly fixed the issue.

**Comment by NamelessHH** [comment]
We've made changes in our qa environment and updated to v2.1.0 and it seemly like its happening less often but it is certainly still happening.

**Comment by NamelessHH** [comment]
@srchase 
We've checked our nightly tests and it seems to be fixed.  If there is any further visibility on this issue we'd love to hear about it because the aws status page never even mentioned it.

**Comment by srchase** [comment]
@NamelessHH 

I'm awaiting on a public notice.

This S3 issue only impacted SigV2.  

Refer to this S3 notification regarding SigV2 deprecation as it's something that you should be aware of for 2019: [Announcement: AWS Signature Version 4 to replace AWS Signature Version 2 for signing S3 API requests ](https://forums.aws.amazon.com/ann.jspa?annID=5816).

**Comment by srchase** [comment]
@NamelessHH 

I don't have any further information to add.  You could raise the question on the [S3 Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=24).
