### ISSUE TITLE
Aws-sdk incompatibility with google-closure-compiler

### ISSUE THREAD

**Issue by Agorn** [aws/aws-sdk-js#2450]
There are 2 places where aws-sdk uses @abstract annotation:

(1) https://github.com/aws/aws-sdk-js/blob/2a872adac4f1c49d45feb5b368e72adf0c343cf4/lib/service.js#L11

(2) https://github.com/aws/aws-sdk-js/blob/2a872adac4f1c49d45feb5b368e72adf0c343cf4/lib/service.js#L431

Google closure compiler has a custom meaning for methods marked with @abstract attribute:
https://github.com/google/closure-compiler/wiki/@abstract-classes-and-methods

Currently attempt to use google-closure-compiler on aws-sdk results in stripping code that annotated with @abstract. Because of that and (1), aws-sdk stops working

Please address the issue of this incompatibility, since it is easy to remove these 2 lines from aws-sdk

**Comment by srchase** [comment]
@Agorn 

Thanks for opening this issue.

I'll take a look and see if there is a workaround for using that Yard tag.

Does google-clouser-compiler offer a configuration option for that could make this work as-is?

**Comment by srchase** [comment]
Fixing in https://github.com/aws/aws-sdk-js/pull/2452

**Comment by srchase** [comment]
Fix has been merged. Closing out this issue.
