### ISSUE TITLE
Add linkParameter to CognitoUserPoolTriggerEvent.request type

### ISSUE THREAD

**Issue by holtc** [aws/aws-sdk-js#2454]
A `linkParameter` field should be added to the `CognitoUserPoolTriggerEvent.request` object definition in the interface, similar to how `codeParameter` is used.

**Comment by srchase** [comment]
@holtc 

Thanks for opening this issue.

Are you referring to the ```CognitoUserPoolTriggerEvent.request``` on the [AWS Lambda on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/42e3741a35ebe4b181ea80089ee960fc7fb9ae59/types/aws-lambda/index.d.ts#L227) package?

**Comment by holtc** [comment]
@srchase yep!

**Comment by srchase** [comment]
@holtc 

That is a different repository.  You'll need to open an issue or PR there instead.
