### ISSUE TITLE
getSignedUrl is broken in version 2.382.0

### ISSUE THREAD

**Issue by andrewryan1906** [aws/aws-sdk-js#2455]
I've gotten the latest version of the SDK - which right now is 2.382.0 - and I'm experiencing an issue with *getSignedUrl*. The method always returns:

https://s3.us-east-2.amazonaws.com/

... no matter what. When I downgrade back to ^2.381.0, I have no problems.

Thanks,
Andrew

**Comment by AllanFly120** [comment]
Hi @andrewryan1906 

Can you share the code snippet of how you call the `getSignedUrl`?

**Comment by andrewryan1906** [comment]
```
let bucket = util.s3.resolveBucketName(config.s3.bucket_name);
    let timelineRetrievalParams = {Bucket: bucket, Key: timelineKey};

    console.log(timelineRetrievalParams);
    const timelineDownloadUri = s3Client.getSignedUrl('getObject', timelineRetrievalParams);

  ```

**Comment by AllanFly120** [comment]
@andrewryan1906 

This is a breaking change introduced in the PR I mentioned above. The default credential provider chain should be resolved synchronously but [this change](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/credential_provider_chain.js#L111) makes the default resolution unsynchronous. I will create a CR to address it.

**Comment by andrewryan1906** [comment]
So...

Am I correct in assuming the reason why I've never observed this behavior before is that this is the first time in my code that I happen to NOT precede this call with an async s3Client operation?

**Comment by AllanFly120** [comment]
Hi @andrewryan1906 

> Am I correct in assuming the reason why I've never observed this behavior before is that this is the first time in my code that I happen to NOT precede this call with an async s3Client operation?

This is correct. making API call will asynchronously load the credentials to the client so that the following `getSignedUrl` has resolved credentials

> so I have to use a callback, instead of the async/await

It depends on what credentials are you using. If you are using the default credentials provider chain, you can use `resolvePromise()` to load the credentials prior to get signed url:

```javascript
s3.config.credentials = await s3.config.credentialProvider.resolvePromise();
```

**Comment by AllanFly120** [comment]
mistakenly closed this

**Comment by srchase** [comment]
2.383.0 has been released with this issue resolved.
