### ISSUE TITLE
Error in Class: AWS.ApiGatewayV2 getApi operation

### ISSUE THREAD

**Issue by reefqi037** [aws/aws-sdk-js#2458]
Installed the latest aws-sdk in Lambda Node.js 8.10. 
Below error happened when calling getApi operation.
*Replaced real value with `<account-id>:<api-id>` in the error

```javascript
{
    "message": "Invalid API identifier specified <account-id>:<api-id>",
    "code": "NotFoundException",
    "time": "2018-12-26T02:44:43.813Z",
    "requestId": "331aa750-08b8-11e9-83ca-6b713e08a649",
    "statusCode": 404,
    "retryable": false,
    "retryDelay": 20.59791196733176
}
```
ApiId is properly set in string form.
```javascript
var params = {
  ApiId: 'STRING_VALUE' /* required */
};
apigatewayv2.getApi(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

**Comment by srchase** [comment]
@reefqi037 

Does your API show up in ```Items``` response of a request to ```getApis```?

```
apigatewayv2.getApis({}, function(err,data) {
  if (err) console.log(err, err.stack);
  else     console.log(data);
});
```

What kind of API are you using?

Which exact version are you using?

**Comment by reefqi037** [comment]
I got an empty array in the ```Items``` response of ```getApis``` request.
```javascript
{ Items: [] }
``` 
I used the example PetStore API with regional endpoint.
The SDK version is 2.382.0.

**Comment by srchase** [comment]
V2 is for creating and deploying WebSocket APIs.

You should use V1 for interacting with the PetStore API.

**Comment by reefqi037** [comment]
I see.

The one that I should use is ```getRestApi``` right?

```Javascript
var params = {
  restApiId: 'STRING_VALUE' /* required */
};
apigateway.getRestApi(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```
Sorry for my misunderstanding and thank you for  your guidance!

**Comment by srchase** [comment]
Yes, that's correct!  Closing out this issue.
