### ISSUE TITLE
aws-sdk with videojs http-streaming: how we can get fragment metadata for video.js player?

### ISSUE THREAD

**Issue by huynhtuanh** [aws/aws-sdk-js#2459]
Maybe this is not an issue, just a question. I'm sorry, if this post is not in correct location :). I've already asked on stackoverlow, but did not have any answer yet.

Now, I'm using video.js and http-streaming to play video from Kinesis Video Streams with AWSJavaScriptSDK.

On our streaming server, there are some metadata (text only) for each fragment (https://aws.amazon.com/vi/about-aws/whats-new/2018/10/kinesis-video-streams-fragment-level-metadata-support/).
I don't know how to get this data by videojs http-streaming or aws-sdk.

Many thanks for any support.

**Comment by srchase** [comment]
@huynhtuanh 

Have you raised this question on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=282)?

**Comment by huynhtuanh** [comment]
@srchase 
Thank you so much
