### ISSUE TITLE
config.credentials is null for SharedIniFileCredentials for latest version.

### ISSUE THREAD

**Issue by ramaguruprakash** [aws/aws-sdk-js#2461]
When I ran the following code in  2.382.0 I get this output

let aws = require('aws-sdk')
JSON.stringify(aws.config)
{"credentials":null,"credentialProvider":{"providers":[null,null,null,null],"resolveCallbacks":[]},"logger":null,"apiVersions":{},"apiVersion":null,"httpOptions":{"timeout":120000},"maxRedirects":10,"paramValidation":true,"sslEnabled":true,"s3ForcePathStyle":false,"s3BucketEndpoint":false,"s3DisableBodySigning":true,"computeChecksums":true,"convertResponseTypes":true,"correctClockSkew":false,"customUserAgent":null,"dynamoDbCrc32":true,"systemClockOffset":0,"signatureVersion":null,"signatureCache":true,"retryDelayOptions":{},"useAccelerateEndpoint":false,"clientSideMonitoring":false,"endpointDiscoveryEnabled":false,"endpointCacheSize":1000,"hostPrefixEnabled":true}

But when I run the same code in an older version say 2.376.0
'{"credentials":{"expired":false,"expireTime":null,"accessKeyId":"<value>","profile":"default","disableAssumeRole":true},"credentialProvider":{"providers":[null,null,null,null]},"logger":null,"apiVersions":{},"apiVersion":null,"httpOptions":{"timeout":120000},"maxRedirects":10,"paramValidation":true,"sslEnabled":true,"s3ForcePathStyle":false,"s3BucketEndpoint":false,"s3DisableBodySigning":true,"computeChecksums":true,"convertResponseTypes":true,"correctClockSkew":false,"customUserAgent":null,"dynamoDbCrc32":true,"systemClockOffset":0,"signatureVersion":null,"signatureCache":true,"retryDelayOptions":{},"useAccelerateEndpoint":false}'

Why are we getting the credentials as null in the lastest sdk when it is present in ~/.aws folder.

**Comment by srchase** [comment]
@ramaguruprakash 

This is a known issue with 2.382.0: https://github.com/aws/aws-sdk-js/issues/2455 

It has been resolved with a fix, but 2.383.0 has not yet been released.

Until 2.383.0 is available, you can rollback to 2.381.0, or see this post: https://github.com/aws/aws-sdk-js/issues/2455#issuecomment-450003493
