### ISSUE TITLE
API Gateway incorrectly returns HTTP 200 response when error message has a newline

### ISSUE THREAD

**Issue by andrewryan1906** [aws/aws-sdk-js#2466]
I've noticed for a while that the error regex feature for API gateway is inconsistent and often does not properly match errors up with return values. But recently I've encountered something even weirder; when an error message has a new line in it, the API gateway doesn't even catch the exception, and instead returns a 200 - making the caller think the POST/PUT completely successfully.

I was able to reproduce... as you can see here in the API Gateway test window, this response incorrectly is encoded as a 200:

![response-200](https://user-images.githubusercontent.com/37671394/50578184-0d75e900-0e04-11e9-84dd-dbf2147342d0.png)

I went into my code and replaced all of the \n newlines with spaces, and now look at how API gateway processes the response:

![response-500](https://user-images.githubusercontent.com/37671394/50578188-19fa4180-0e04-11e9-9660-85a9ce264cb0.png)

This is particularly challenging as I often rely on knowing that uncaught exceptions from helper libraries will bubble up as 500 errors. This appears to not be true if that exception has new lines in it (which, ironically, Cognito's library does).

Thoughts?

**Comment by andrewryan1906** [comment]
Chase,

I don't know if it's the SDK or not. But I'm running this through the Test apparatus provided by the AWS Console... so it feels like it's a problem in the transformation engine being used to modify lambda responses.

Hard to give code, since this happens deep inside of multiple layers of Node code... but this should be pretty easy to reproduce if you create a lambda that throws an error with newlines...
On 1/2/2019 11:30:00 AM, Chase Coalwell <notifications@github.com> wrote:
@andrewryan1906 [https://github.com/andrewryan1906]
Do you believe this an issue with the SDK? Can you provide a sample of your code?

**Comment by srchase** [comment]
@andrewryan1906 

This repository is reserved for issues with the SDK itself.

If you're having an issue with API Gateway and Lambda, you should contact the API Gateway service team: [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=199) or through AWS Support.
