### ISSUE TITLE
Transcribe job filtering not reliable

### ISSUE THREAD

**Issue by WilliamEddy** [aws/aws-sdk-js#2467]
Whenever I try to find a transcription via the Node SDK I am sometimes unable to retrieve the transcript that I am looking for. My transcription job names are a UUID and it doesn't seem to make sense when the lookup fails and when it is successful. All of the transcripts are available in the web console. 

For example, the following search returns a result:
`transcribeService.listTranscriptionJobs({ JobNameContains: '8cd68' })`

but this search does not return a transcript(and the transcript exists in the web console)
`transcribeService.listTranscriptionJobs({ JobNameContains: '805df' })`

This error is not localized to just this one record either, I have a multiple transcripts that this issue is occurring with. Any help would be very appreciated.

If you need any more details I can provide more information.

**Comment by srchase** [comment]
@WilliamEddy 

Do you get the same behavior from the AWS CLI?

[list-transaction-jobs](https://docs.aws.amazon.com/cli/latest/reference/transcribe/list-transcription-jobs.html)

**Comment by WilliamEddy** [comment]
Yes, I get the same behavior when running from the CLI
null

**Comment by srchase** [comment]
If the SDK and CLI return the same results, that would point to an issue with the underling Transcribe service.

Have you engaged the Transcribe Service team via the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=278) or through opening a support case?

Does ```getTranscriptionJob``` return the correct result if you use the job name for '8cd68'?

**Comment by WilliamEddy** [comment]
I have also posted a message on the forums. I was not sure if it was a code issue causing the strings in question to somehow not be sent to the service correctly.

**Comment by srchase** [comment]
@WilliamEddy 

Are you able to retrieve the job using ```getTranscriptionJob```?
