### ISSUE TITLE
ec2 start instance waitFor instanceRunning does not work

### ISSUE THREAD

**Issue by makoit** [aws/aws-sdk-js#2470]
Hi,

during starting or creating a new ec2 instance I want to use wait for function to wait until my instance is running then I will return the instance id to use the id in a other service to read out the public dns name.

This is my code:

```
public async startOneInstance(instanceId: string): Promise<any> {

        const startParameter = {
            InstanceIds: [instanceId],
        };

        const waitParams = {
            InstanceIds: [instanceId],
        };

        let startData: AWS.EC2.StartInstancesResult;
        return await this.ec2.startInstances(startParameter).promise()
            .then(async (data: AWS.EC2.StartInstancesResult) => {
                startData = data;
                return await this.ec2.waitFor("instanceRunning", waitParams);

            })
            .then((wait) => {
                console.log(wait);
                if (startData.StartingInstances) {
                    return startData.StartingInstances[0].InstanceId;
                }
                return new CouldNotStartInstanceError("Start Instance Error", "3009");
            })
            .catch((error) => {
                return new CouldNotStartInstanceError(error.toString(), "3010");
            });
    }
```

The problem is that `this.ec2.waitFor("instanceRunning", waitParams) `does not wait until the instance is running. So I return the instance id too early and my other services return a empty string instead my public dns name.

Any idea whats the problem could be?

Thanks for help

**Comment by srchase** [comment]
@makoit 

What state is given for the instance returned on ```return await this.ec2.waitFor("instanceRunning", waitParams)```?

Can you confirm the instance is in a running state when the subsequent call to get the public DNS name is made?

Which version of the SDK are you using?

**Comment by srchase** [comment]
The waitFor should be used with a ```.promise()```.  The request (for use with a callback) is being returned.

**Comment by makoit** [comment]
> The waitFor should be used with a .promise(). The request (for use with a callback) is being returned.

Ahh you're right! I changed my code to: `return await this.ec2.waitFor("instanceRunning", waitParams).promise();` . Now it's running correctly. The func waits until the instance is started.

Thank you very much for your competent and quick help!
