### ISSUE TITLE
SAML Redirect method signature support

### ISSUE THREAD

**Issue by mungojam** [aws/aws-sdk-js#2472]
It would be really great if the SDK (and presumably AWS itself) had support for passing the `Redirect` form of SAML response as well as the `Post` form. The main difference in the formats seems to be that the signature for 'Redirect' is based on the hash of the encoded query string, while for `Post` it is based on the digest of the underlying XML file.

The background is that I am attempting to get a serverless SAML solution up and running for a static S3 website, much like [the amazon blog post from 2017](https://aws.amazon.com/blogs/compute/saml-for-your-serverless-javascript-application-part-i/).

I have got it working with `Post` as described in the link, but this requires API Gateway and Lambda, just to convert the form-data from the `Post` call into the query string. If I could instead pass the standard `Redirect` version of `SAMLResponse`, `SigAlg` and `Signature` through to the AWS SDK, then I would no longer need these additional complexities and would have one fewer browser redirect too.

**Comment by srchase** [comment]
@mungojam 

Thanks for opening this request.

This feature-request would need to be handled by the API Gateway team, not the JavaScript SDK.

Have you contacted that team?  You're welcome to post on their [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=199).

I'm going to close this issue, as this repository is reserved for SDK issues and requests.

**Comment by mungojam** [comment]
Ok, I did expect it might need a change under the covers but I'm surprised that authorising with AWS auth involves API gateway as it feels more fundamental than that.

I'll have a go at finding a suitable forum though, thanks
