### ISSUE TITLE
DocumentClient constructor attempts mutating the options object

### ISSUE THREAD

**Issue by maghis** [aws/aws-sdk-js#2476]
This is really bad, especially because the `config` module started returning sealed objects.

If you pass a sealed object the current version will throw a completely unrelated validation error when calling any of the dynamo operations:
```
MultipleValidationErrors: There were 3 validation errors:
* MissingRequiredParameter: Missing required key 'TableName' in params
* MissingRequiredParameter: Missing required key 'Key' in params
* UnexpectedParameter: Unexpected key 'M' found in params
```

**Comment by srchase** [comment]
@maghis 

Thanks for opening this issue.  

Do you have a code sample that illustrates this issue?

**Comment by maghis** [comment]
sorry @srchase, I did not notice your message.
You can simply instantiate the client with:

```
const client = new DynamoDB.DocumentClient({ region: "us-east-1" });
```

and then call any of the methods.

This is the line where it's trying to set a value on the original `options` object: https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/document_client.js#L71

**Comment by alex-at-cascade** [comment]
This issue still exists, however, I only see it when using https://www.npmjs.com/package/config

**Comment by allumbra** [comment]
I'm seeing a similar message:

```
const docClient = new AWS.DynamoDB.DocumentClient(AWS.config.region);
var result = await docClient.get(params).promise();
```
where params = 
```
    {
      "TableName": "randomWordDictionary",
      "Key": {
        "entryIndex": "noun_test1",
        "dictionaryName": "noun_test"
      }
    }
```

And the resulting message is: 

> MultipleValidationErrors: There were 3 validation errors:    * MissingRequiredParameter: Missing required key 'TableName' in params
    * MissingRequiredParameter: Missing required key 'Key' in params
    * UnexpectedParameter: Unexpected key 'M' found in params 

I happen to be hitting "us-east-1" as well if that makes a difference.

**Comment by ajredniwja** [comment]
@maghis @alex-at-cascade,

Apologies for the late reply, are you guys still facing the issue using the latest version of SDK? 

Closing this issue for now, please re-open using the [issue template](https://github.com/aws/aws-sdk-js/issues/new/choose) to let us help you better.

**Comment by alex-at-cascade** [comment]
I worked around it, haven't checked recently.  But I'll open a new issue if I hit it again.
