### ISSUE TITLE
s3.upload randomly seems to return "key" property on occassion

### ISSUE THREAD

**Issue by niftylettuce** [aws/aws-sdk-js#2478]
for example, a simple file upload will sometimes return "key" lowercase property name and sometimes not:

```
const data = await s3.upload(obj).promise();
```

`data` is either:

```js
{
  Location: 'https://my-bucket.s3.amazonaws.com/some-file-name.jpg',
  Bucket: 'my-bucket',
  Key: 'some-file-name.jpg',
  key: 'some-file-name.jpg',
  ETag: '"some-etag"'
}
```

or 

```js
{
  Location: 'https://my-bucket.s3.amazonaws.com/some-file-name.jpg',
  Bucket: 'my-bucket',
  Key: 'some-file-name.jpg',
  ETag: '"some-etag"'
}
```

sporadically... so as you can see this is a weird issue with the API!

**Comment by srchase** [comment]
@niftylettuce 

See https://github.com/aws/aws-sdk-js/issues/918.

The 'key' returned on small files, =< 5mb and uploaded with a single part, was left in place for backward compatibility.
