### ISSUE TITLE
adminUpdateUserAttributes returning blank object on successful completion

### ISSUE THREAD

**Issue by Exitialis1** [aws/aws-sdk-js#2479]
I am trying to use the SDK to update a user's attributes and on successful completion, I am getting an empty object returned instead of anything that would make a useful and easy way to tell that it completed successfully. In case it matters I am only updating the email attribute. 

If this is intended behaviour could the documentation be updated to reflect this? Currently, it just says this about the return: 

err (Error) — the error object returned from the request. Set to null if the request is successful.
data (Object) — the de-serialized data returned from the request. Set to null if a request error occurs.

Alternatively, and ideally, could the API be updated to return something to confirm successful completion, please?

Further diagnosis here, though it primarily just trying the call with a promise vs callback and behaviour was the same each time: https://stackoverflow.com/questions/54075245/authenticate-as-admin-to-cognito-using-lambda-iam-role

**Comment by srchase** [comment]
@Exitialis1 

Refer to the [Cognito API Reference](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminUpdateUserAttributes.html):

>Response Elements
>If the action is successful, the service sends back an HTTP 200 response with an empty HTTP body. 

This is the expected behavior.  If ```data``` is null you can refer to the error.  Otherwise you can consider the operation a success.

What are you looking for in the data object to confirm that the action was successful?

**Comment by Exitialis1** [comment]
Ah, that reference is clearer, I was going from here: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminUpdateUserAttributes-property 

Where I was getting confused because the first line says that the return will be null where the next line says there will be data returned from the request. 

Now that I have confirmation that what I am seeing is intended behaviour it isn't so bad. But I would argue that when using the SDK directly I cannot see the HTTP 200 response so I have nothing explicit to say the operation worked. Normally in Javascript I associate a blank response with something went so badly wrong you didn't even catch the error. 

Just getting the attributes changed back would be really useful, it is explicit vs an explicit error message and is what I need to return through my GraphQL API anyway.

**Comment by srchase** [comment]
Take a look at [Using a Request Object Event Listener](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/using-a-response-event-handler.html).

The ```extractError``` and ```extractData``` listeners can be useful for debugging.  See the [Request](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html) documentation for all of the available listeners.

Changes to the underlying API would need to be made by the Cognito Service Team.  You're welcome to followup with them for that feature request on their [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=173).
