### ISSUE TITLE
XML parsing Dependency migration

### ISSUE THREAD

**Issue by amitguptagwl** [aws/aws-sdk-js#2485]
I would like to suggest to migrate to [fast-XML-parser](https://github.com/NaturalIntelligence/fast-xml-parser).

Benchmark

![FXP vs xml2js](https://raw.githubusercontent.com/NaturalIntelligence/fast-xml-parser/master/static/img/fxpv3-vs-xml2jsv0419_chart.png)

**Comment by srchase** [comment]
@amitguptagwl 

Thanks for the request.  We'll consider if this change makes sense for the SDK at this time.

**Comment by amitguptagwl** [comment]
Thanks @srchase 

Here is the tabular representation.

file size |  fxp 3.0 parser (rps) | xml2js 0.4.19 (rps)
-- |  -- | --
1.5k  | 14032.09323 | 4615.930805
1.5m  | 13.23366098 | 5.90682005
13m  | 1.135582008 | -1
1.3k with CDATA  | 43160.52342 | 8398.556349
1.3m with CDATA  | 52.68877009 | 7.966000795
1.6k with cdata,prolog,doctype  | 41433.98547 | 7872.399268
98m  | 0.2600104004 | -1

As you can notice, in case of large file xml2js gives an error.

**Comment by amitguptagwl** [comment]
Hi @srchase 
Have you get the chance to look into it?

**Comment by ajredniwja** [comment]
Hey @amitguptagwl,

Apologies for the late reply, would you like to try [JavaScript-SDK-V3](https://github.com/aws/aws-sdk-js-v3) which is under developer preview right now. One of the features in JS-SDK-v3 is: for a service that responds with JSON will no longer need XML parser as a dependency. Till the time this feature is under consideration you can always try version 3 of the SDK and give us reviews. For more information check out this [link](https://aws.amazon.com/blogs/developer/new-aws-sdk-for-javascript-developer-preview/).

**Comment by amitguptagwl** [comment]
Great. Then this advice is no longer needed.
