### ISSUE TITLE
DynamoDB converter unmarshall issue

### ISSUE THREAD

**Issue by ricardolpd** [aws/aws-sdk-js#2486]
When i export data from dataPipeline in dynamoDB, the data types in the json are in lowercase.

`{"id":{"s":"2ecd97a2-120c-49e2-a11a-2ed0eba4d3bc"},"domain":{"s":"14cc7794-8a6d-4eec-a3d0-99ca5eb4a8ec"},"intentFailedCount":{"n":"0"},"ttl":{"n":"1549558019"},"createdDate":{"s":"2018-11-09T16:46:59.428Z"},"messages":{"l":[{"m":{"returnedMessage":{"m":{"id":{"s":"4"},"events":{"l":[{"m":{"message":{"s":"You don't have any items eligible for tracking right now. I expect your order is still being processed."},"type":{"s":"data"}}}]}}},"watsonEntities":{"l":[]},"userMessage":{"m":{"intent":{"s":"wismoTrack"}}},"action":{"s":"GetTrackableOrders"},"date":{"s":"2018-11-09T16:46:59.452Z"}}},{"m":{"returnedMessage":{"m":{"id":{"s":"40"},"events":{"l":[{"m":{"message":{"s":"Thanks Credit, did I help you get the information you needed?"},"tone":{"s":"SDCUIAnimationWink"},"trackMessageID":{"s":"40"},"type":{"s":"converse"}}},{"m":{"type":{"s":"options"},"options":{"l":[{"m":{"message":{"s":"Yes"},"title":{"s":"Yes"},"nextIntent":{"s":"happyCustomer"},"action":{"m":{"id":{"s":"intentKnown"}}},"url":{"nULLValue":true}}},{"m":{"message":{"s":"No"},"title":{"s":"No"},"nextIntent":{"s":"unhappyCustomer"},"action":{"m":{"id":{"s":"intentKnown"}}},"url":{"nULLValue":true}}}]}}}]}}},"watsonEntities":{"l":[]},"userMessage":{"m":{"intent":{"s":"wismoTrack"}}},"action":{"s":"GetTrackableOrders"},"date":{"s":"2018-11-09T16:46:59.452Z"}}}]}}`

However when i use DynamoDB.Converter.unmarshall

`{
createdDate:undefined
domain:undefined
id:undefined
intentFailedCount:undefined
intents:undefined
messages:undefined
ttl:undefined
}`

they are all undefined, unless i put the DynamoDB types set in Caps.

**Comment by srchase** [comment]
@ricardolpd 

Can you provide an example of the code you are using, along with the SDK version and any other relevant environmental details?

**Comment by ricardolpd** [comment]
@srchase,

Sorry forgot to put those in:

the code used is here:

`const conversationUnmarshalled = JSON.parse(item);
      console.log(item);
      const options = {
        convertEmptyValues: true,
        wrapNumbers: false,
      };
      const conversation = converter.unmarshall(conversationUnmarshalled, options);
      conversations.push(conversation);`

The following example uses the marshalling example from the SDK page, and the same happens this last bit was run in the REPL.it website.
```

const converter = require('aws-sdk').DynamoDB.Converter;
const item = {
  string: {'s': 'foo'},
  list: { 'l': [{ 's': 'fizz'}, { 's': 'buzz'}, { 's': 'pop'}]},
  map: {
    'm': {
      nestedMap: {
        'm': {
          key: {'s': 'value'}
        }
      }
    }
  },
  number: { 'n': '123'},
  nullValue: { 'nULLValue': true},
  boolValue: { 'nULLValue': true}
};
const conversation = converter.unmarshall(item);
console.log(JSON.stringify(conversation));
```
the output is:  `{}`

The version of sdk in my machine is: "2.387.0"
I am on a MAC 10.14.2 (18C54) using node 9.2.0 for the debug session.

**Comment by srchase** [comment]
The unmarshall example uses capitalized types: [unmarshall](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/Converter.html#unmarshall-property).

Is there different documentation you are referring to?

**Comment by ricardolpd** [comment]
@srchase i created the pipeline through the console using the templates (as an initial measure)
the json generated is the following:

`{
  "objects": [
    {
      "bootstrapAction": "s3://#{myDDBRegion}.elasticmapreduce/bootstrap-actions/configure-hadoop, --yarn-key-value,yarn.nodemanager.resource.memory-mb=11520,--yarn-key-value,yarn.scheduler.maximum-allocation-mb=11520,--yarn-key-value,yarn.scheduler.minimum-allocation-mb=1440,--yarn-key-value,yarn.app.mapreduce.am.resource.mb=2880,--mapred-key-value,mapreduce.map.memory.mb=5760,--mapred-key-value,mapreduce.map.java.opts=-Xmx4608M,--mapred-key-value,mapreduce.reduce.memory.mb=2880,--mapred-key-value,mapreduce.reduce.java.opts=-Xmx2304m,--mapred-key-value,mapreduce.map.speculative=false",
      "name": "EmrClusterForBackup",
      "coreInstanceType": "m1.large",
      "coreInstanceCount": "1",
      "amiVersion": "3.9.0",
      "id": "EmrClusterForBackup",
      "masterInstanceType": "m1.large",
      "region": "#{myDDBRegion}",
      "type": "EmrCluster",
      "terminateAfter": "10 Minutes"
    },
    {
      "failureAndRerunMode": "CASCADE",
      "resourceRole": "DataPipelineDefaultResourceRole",
      "role": "DataPipelineDefaultRole",
      "pipelineLogUri": "s3://somebucket/",
      "scheduleType": "ONDEMAND",
      "name": "Default",
      "id": "Default"
    },
    {
      "output": {
        "ref": "S3BackupLocation"
      },
      "input": {
        "ref": "DDBSourceTable"
      },
      "maximumRetries": "2",
      "name": "TableBackupActivity",
      "step": "s3://dynamodb-emr-#{myDDBRegion}/emr-ddb-storage-handler/2.1.0/emr-ddb-2.1.0.jar,org.apache.hadoop.dynamodb.tools.DynamoDbExport,#{output.directoryPath},#{input.tableName},#{input.readThroughputPercent}",
      "id": "TableBackupActivity",
      "runsOn": {
        "ref": "EmrClusterForBackup"
      },
      "type": "EmrActivity",
      "resizeClusterBeforeRunning": "true"
    },
    {
      "readThroughputPercent": "#{myDDBReadThroughputRatio}",
      "name": "DDBSourceTable",
      "id": "DDBSourceTable",
      "type": "DynamoDBDataNode",
      "tableName": "#{myDDBTableName}"
    },
    {
      "directoryPath": "#{myOutputS3Loc}/#{format(@scheduledStartTime, 'YYYY-MM-dd-HH-mm-ss')}",
      "name": "S3BackupLocation",
      "id": "S3BackupLocation",
      "type": "S3DataNode"
    }
  ],
  "parameters": [
    {
      "description": "Output S3 folder",
      "id": "myOutputS3Loc",
      "type": "AWS::S3::ObjectKey"
    },
    {
      "description": "Source DynamoDB table name",
      "id": "myDDBTableName",
      "type": "String"
    },
    {
      "default": "0.25",
      "watermark": "Enter value between 0.1-1.0",
      "description": "DynamoDB read throughput ratio",
      "id": "myDDBReadThroughputRatio",
      "type": "Double"
    },
    {
      "default": "us-east-1",
      "watermark": "us-east-1",
      "description": "Region of the DynamoDB table",
      "id": "myDDBRegion",
      "type": "String"
    }
  ],
  "values": {
    "myDDBRegion": "eu-west-1",
    "myDDBTableName": "Conversation",
    "myDDBReadThroughputRatio": "0.25",
    "myOutputS3Loc": "s3://somebucket/"
  }
}`

**Comment by ricardolpd** [comment]
Thanks for checking this for me, so are you saying that the data pipeline doesnt use any of the DynamoDB sdks?
Its not just the lowercase that is the issue, the values are considerably different for null values, as i described above.
Will the issue be tracked here, also which api have an update? so i can track the issue, and remove the conversion code.

**Comment by ajredniwja** [comment]
Hey @ricardolpd,

Apologies for late reply!
Are you still facing the issue?

**Comment by auno** [comment]
@ajredniwja Don't know about @ricardolpd, but I am definitely still facing this issue. Also as in @ricardolpd's case, I'm not using the SDK directly, but instead have a default config DataPipeline backing up a DynamoDB table to S3.

**Comment by ricardolpd** [comment]
@ajredniwja Unfortunately i havent used this since and i have left the where i was working, then we end up forking the Mapper in the aws sdk and adjust the mapper to the output of the datapipeline? I think in the previous comments the data pipeline team was going to fix this.

**Comment by ajredniwja** [comment]
@auno @ricardolpd 

I can follow up with the data pipeline team, will update you guys.

**Comment by leemun1** [comment]
any update on this issue? I am facing the same issue after exporting a DynamoDB table with a Data Pipeline setup.

**Comment by andezzat** [comment]
Hey everyone. Since AWS don't wanna fix this yet.
I just created a pretty simple but (hopefully) performant way of converting the invalid DDB types to valid types ready for marshaling correctly!

```
const AWS = require('aws-sdk')

const ddbDoc = {"dueInvoicesCount":{"n":"0"},"trialEnd":{"s":"2020-05-27T22:59:59.000Z"},"planType":{"s":"b2c"},"providerCode":{"s":"chargebee_uk"},"billingDetails":{"m":{"countryCode":{"s":"AU"},"name":{"s":"Bernie Members"},"email":{"s":"my-email@mails.org"}}},"billingPeriod":{"s":"month"},"activatedAt":{"nULLValue":true},"cancelledAt":{"s":"2020-05-19T23:00:00.000Z"},"trialStart":{"s":"2020-05-19T23:00:00.000Z"},"providerCustomerId":{"s":"16CHMORzVRDOX14z"},"dueSince":{"nULLValue":true},"userId":{"s":"auth0|12345"},"createdAt":{"s":"2020-05-20T06:10:15.000Z"},"currentTermStart":{"nULLValue":true},"currentTermEnd":{"nULLValue":true},"paymentMethods":{"m":{"card":{"m":{"last4":{"s":"4242"},"expiryMonth":{"n":"5"},"id":{"s":"pm_16CHMORzVRDOX14z"},"expiryYear":{"n":"2021"},"brand":{"s":"visa"},"status":{"s":"valid"}}}}},"providerSubscriptionId":{"s":"16CHMORzVRDOX14z"},"providerPlanId":{"s":"membership-2020apr-usd-annual"},"cancelReason":{"nULLValue":true},"nextBillingAt":{"nULLValue":true},"status":{"s":"cancelled"},"updatedAt":{"s":"2020-05-20T06:10:49.701Z"}}

const VALID_DDB_TYPES = {
  s: 'S',
  l: 'L',
  m: 'M',
  n: 'N',
  nULLValue: 'NULL',
  bOOL: 'BOOL'
}

const pipe = (...fns) => x => fns.reduce((res, fn) => fn(res), x)

const getValidDDBObject = pipe(
  JSON.stringify,
  ...Object.entries(VALID_DDB_TYPES).map(
    ([invalidType, validType]) =>
      str => str.replace(new RegExp(`"${invalidType}":`, 'g'), `"${validType}":`)
  ),
  JSON.parse
)

console.log(
  AWS.DynamoDB.Converter.unmarshall(getValidDDBObject(ddbDoc))
)
```

Where
- `ddbDoc` is a sample single invalid DDB exported document object from DataPipeline
- `pipe()` is a utility function for functional composition (an easy way to chain functions)

**Comment by akashbits** [comment]
They might find a covid vaccine before AWS fixes this issue.

**Comment by akashbits** [comment]
This is more ridiculous than Trump's behavior towards Covid19

**Comment by martyncolmer** [comment]
I too an getting this issue, Any update on this??

**Comment by andezzat** [comment]
@martyncolmer @akashbits 

I can't believe this is still unresolved 🤦 
Please try to use my script & let me know if you have trouble :)

**Comment by akash87** [comment]
I'll have to escalate it to Jeff Bezos I guess

**Comment by ajredniwja** [comment]
Hey everyone, apologies as I lost track of the issue, I have recreated the issue with the DataPipeLine team and would have an update on this shortly.

**Comment by leemun1** [comment]
@akashbits and they did find a vaccine first LOL
@ajredniwja thank you for the update!

**Comment by ajredniwja** [comment]
The vaccine had to come first lol

**Comment by martyncolmer** [comment]
@ajredniwja Thanks for the update. 
It's a shame they have an option in the pipeline to create plain json, would make my life much easier.

**Comment by ajredniwja** [comment]
> @ajredniwja Thanks for the update.
> It's a shame they don't have an option in the pipeline to create plain json, would make my life much easier.

It would make a nice feature, I can open a feature request for the same.

**Comment by martyncolmer** [comment]
@ajredniwja if you could open a request that would be great.

**Comment by Eyads** [comment]
It is still an issue! I've just used the pipeline and it both consumed and produced data in the weird format described by the OP.

**Comment by gregg-allure4** [comment]
> Greetings! We’re closing this issue because it has been open a long time and hasn’t been updated in a while and may not be getting the attention it deserves. We encourage you to check if this is still an issue in the latest release and if you find that this is still a problem, please feel free to comment or open a new issue.





https://nodeer.space/questions/converting-dynamo-db-stream-data-into-json-format
