### ISSUE TITLE
Unable to putObjects from a browser worker context

### ISSUE THREAD

**Issue by CarsonMcKinstry** [aws/aws-sdk-js#2487]
#### Description

We have been trying to handle file uploads in the background on one of our applications. For this we are using a `service-worker` which doesn't have access to `XMLHttpRequest` and instead only has access to the `fetch` API

#### Expected Behavior

Switch which kind of request technique is being used based on context. If `XMLHttpRequest` is not present, try for the `fetch` API. OR default to the `fetch` API and fall back to the older `XMLHttpRequests` API.

#### Actual Behavior

Whenever you use the aws-sdk inside of a `service-worker` context, you get errors stating that window.XMLHttpRequest is undefined.

**Comment by srchase** [comment]
@CarsonMcKinstry 

Thanks for opening this issue.

This is a use case that we'd like to support in [V3](http://github.com/aws/aws-sdk-js-v3) of the SDK.  In V3, Fetch is available in the main browser, so it wouldn't be necessary to switch between XMLHttpRequest and Fetch depending on the context.

[V3](http://github.com/aws/aws-sdk-js-v3) is currently in developer preview.  We'd love for your feedback if you have time to check it out.

**Comment by CarsonMcKinstry** [comment]
Cool cool!

Which branch/package will the s3 functions be under? I can't seem to figure out which one.

**Comment by srchase** [comment]
Currently, not all of the packages are pre-built.

To build the s3 package, follow the steps on [CONTRIBUTING](https://github.com/aws/aws-sdk-js-v3/blob/master/CONTRIBUTING.md), including the test steps that build the base packages:

```
npm install
npm run bootstrap
npm test
node ./packages/package-generator/build/cli.js client --model models/s3/2006-03-01/service-2.json --runtime browser --smoke models/s3/2006-03-01/smoke.json
```

**Comment by yigaldviri** [comment]
Is there any estimation regarding when V3 will be in production?
