### ISSUE TITLE
Add Pinpoint Analytic Stream Types

### ISSUE THREAD

**Issue by Clete2** [aws/aws-sdk-js#2489]
The SDK does not provide TypeScript types for [Pinpoint Analytic Events](https://docs.aws.amazon.com/pinpoint/latest/developerguide/analytics-streaming.html#analytics-streaming-data) that come through Kinesis.

I found a similar type called [Pinpoint.Event](https://github.com/aws/aws-sdk-js/blob/master/clients/pinpoint.d.ts#L2423) but that appears to be the corresponding type that is returned by an event API query, not the type that is used as a Kinesis stream event.

**Comment by srchase** [comment]
@Clete2 

Thanks for opening this request.

Can you provide an example to make sure we can understand how you would want to use these types?

**Comment by Clete2** [comment]
@srchase absolutely. I’ll give you one first thing Monday morning when I boot up my laptop.

**Comment by Clete2** [comment]
I have a Lambda which consumes an event stream from Pinpoint. I will eventually use it for SMS, e-mail, and push. For now I am just using SMS. I need to consume those events emitted from Pinpoint and I want to use TypeScript.

Here's an example SMS event that we receive from Pinpoint into our Kinesis stream:
```
{
    "event_type": "_SMS.SUCCESS",
    "event_timestamp": 1547839009132,
    "arrival_timestamp": 1547839008948,
    "event_version": "3.1",
    "application": {
        "app_id": "<snip>",
        "sdk": {}
    },
    "client": {
        "client_id": "<snip>"
    },
    "device": {
        "platform": {}
    },
    "session": {},
    "attributes": {
        "sender_request_id": "<snip UUID>",
        "record_status": "DELIVERED",
        "iso_country_code": "US",
        "number_of_message_parts": "1",
        "message_id": "<snip>",
        "message_type": "Transactional"
    },
    "metrics": {
        "price_in_millicents_usd": 645
    },
    "awsAccountId": "<snip>"
}
```

If you look in the docs that I linked, you can see discrepancies between this event and the event that I've pasted above.

Something like this:
```
export interface PinpointSMSEvent {
  event_type: '_SMS.SEND' | '_SMS.SUCCESS' | '_SMS.FAIL' | '_SMS.OPTOUT';
  arrival_timestamp: number;
  event_timestamp: number;
  event_version: string;
  application: { app_id: string; sdk: object };
  client: { client_id: string };
  device: {platform: object};
  session: object;
  attributes: { [key: string]: any };
  metrics: { [key: string]: any };
  awsAccountId: string;
}
```

**Comment by AllanFly120** [comment]
Hey @Clete2,

The TypeScript definitions provided in the SDK are mainly the I/O shape of the API. Is the event shape you posted here retrieved by calling any PinPoint API? I cannot find any corresponding operation.

**Comment by Clete2** [comment]
@AllanFly120 No, it is not an API endpoint. It is a Kinesis stream event that Pinpoint generates for analytical purposes.

Are you thinking it belongs in `@types/aws-lambda`?

**Comment by AllanFly120** [comment]
@Clete2 Can you elaborate where the event is from? I assume the data comes from the Lambda function kinesis trigger, which originally generated from pinpoint. Am I right? In this case I don't think the feature request falls within the SDK scope. Because there is not API corresponds to this Typescript definition.

**Comment by Clete2** [comment]
@AllanFly120 Yes the event is from the Lambda Kinesis trigger which is generated from Pinpoint. You can find more info on [this page about Pinpoint Events via Kinesis](https://docs.aws.amazon.com/pinpoint/latest/developerguide/analytics-streaming.html#analytics-streaming-data).

If only API calls are in scope for the SDK I am thinking it should be added to `@types/aws-lambda` within DefinitelyTyped. They maintain types for all the lambda kinesis triggers -- at least as far as I can tell. Do you know anything about that project or whether it falls in their scope instead?

**Comment by AllanFly120** [comment]
Hi @Clete2 I think the package is publicly maintained, you are free to contribute. I'm closing this issue because it's not SDK related. Please open a new issue if you have further questions
