### ISSUE TITLE
PR #2410 broke S3 multipart-upload object tag values

### ISSUE THREAD

**Issue by thenickdude** [aws/aws-sdk-js#2490]
PR #2410 arbitrarily added URI escaping to the values of tags added to S3 objects in the multipart uploader. This breaks tag values that contain any special characters, such as the [allowed character](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/allocation-tag-restrictions.html) 
" " (space), because it causes that value to be URL-escaped, and that URL-escaped value is not actually used in a URL context. i.e. " " becomes "%20" in the XML *body* of the request to S3, where URL-escaping is meaningless, so S3 rightly complains that the value contains the illegal character "%", and returns the error "InvalidTag: The TagValue you have provided is invalid".

#2410 only intended to convert Number-typed values to strings, and nothing else. The correct code to achieve that would have been something like `self.tags[i].Value + ""`, or `String(self.tags[i].Value)`. Definitely not calling `uriEscape()`. 

The broken code shipped in version v2.379.0.

**Comment by thenickdude** [comment]
I think the confusion arose because in the single-part upload case, the tags are included in an HTTP header in [a PUT call](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html), where they must be URL-escaped, but in the multi-part case the tags are included in a call to [PUT object tagging](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUTtagging.html) where they appear in an XML body and must not be URL-escaped.

**Comment by thenickdude** [comment]
How does this "require further discussion"? In 2.378 it was possible to upload files with tags containing spaces, in both single and multi-part mode, because both of them used appropriate escaping. In 2.379, that became impossible.

**Comment by srchase** [comment]
@thenickdude 

Resolved this issue in #2492.

Thanks for pointing this out.
