### ISSUE TITLE
Support SDK - Region Not Supported

### ISSUE THREAD

**Issue by sajithvim** [aws/aws-sdk-js#2497]
Hi,

I have used the AWS support SDK inside a lambda function without specifying the region with the default settings as given below. 

`
 let support = new AWS.Support();
`

I get the following error. 

`
"errorMessage": "Inaccessible host: support.ap-southeast-2.amazonaws.com'. This service may not be available in the ap-southeast-2' region.",
  "errorType": "UnknownEndpoint",
`

It only works when I specifically specify `us-east-1` as the region. 

`
let support = new AWS.Support({region: 'us-east-1'});
`

I would expect it to work by default without having to specify any region. Or at least in the documentation, I didn't see it specifically mentioned. Could you kindly look into this issue. 

Thanks in advance,
Sajith Weerakoon

**Comment by sajithvim** [comment]
@srchase Thanks for your quick response. My lambda functions are running in the Sydney region. But I am setting the region forcibly due to the SDK limitation mentioned above.

**Comment by srchase** [comment]
@sajithvim 

Thanks for following up.

I'll opt to close this issue for now.  We're happy to re-open if you have additional concerns.
