### ISSUE TITLE
ImageExists event parameter says invalid for filter = "image-id"

### ISSUE THREAD

**Issue by tan31989** [aws/aws-sdk-js#2499]
Hi,

When we use the sdk to trigger some functionality of image being available or exists, the filter being passed gives error while testing.

For example:

```
var params = {
  // ... input parameters ...
};
ec2.waitFor('imageExists', params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

The documentation [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#imageExists-waiter) states that the `Filters — (Array<map>)` can have:

> image-id - The ID of the image.

But when we trigger the follow:
```
var params = {
   Filters: [{
       "image-id": "ami-xxxxxxxxx"
   }]
};
ec2.waitFor('imageExists', params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

The error states the key `image-id` is not a valid parameter.

**Comment by srchase** [comment]
@tan31989 

Can you try this instead?

```
const params = {
  Filters: [{ 
    Name: 'image-id', 
    Values: ['ami-xxxxxxxxxxx'] 
  }]  
}
```

**Comment by srchase** [comment]
The Array<map> is defined as having the following:

```
Name — (String)
The name of the filter. Filter names are case-sensitive.
    
Values — (Array<String>)
One or more filter values. Filter values are case-sensitive.
```

We'd be happy to review a PR.   Where are you interested in making a change?

**Comment by tan31989** [comment]
I thought the documentation has definitive one-liner example for those filters. So thought if raised a PR which would be showcasing how to use the filters.

How do you think that example bit would be for the PR?

**Comment by srchase** [comment]
@tan31989 

Each of the ```waitFor``` operations are merely wrappers for another operation.  The documentation for ```imageExists``` notes that it is actually a call to ```describeImages``` and uses the same params.  ```describeImages``` has more thorough [examples](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeImages-property).

I'll label this issue as a feature request to improve the documentation by pulling in the underlying operation examples into the documentation for each ```waitFor```.

**Comment by tan31989** [comment]
Great, @srchase . 
Thanks for the update. I will try to come up with a PR for this.

**Comment by tan31989** [comment]
@srchase how do we verify if the documentation generated has been updated properly?
Is there any procedure to create the document?

**Comment by tan31989** [comment]
Figured it out, we need to run the `bundle exec rake docs:api` to get it download

**Comment by tan31989** [comment]
@srchase I have raised a PR for this use case and also added details in CONTRIBUTION.md for how to implement this. Please let me know if there is anything more to add in here.

**Comment by srchase** [comment]
Thanks for following up on this.  I'll respond on that PR.

**Comment by tan31989** [comment]
@srchase I have updated the PR and also raised one question, let me know if that's even valid.

**Comment by tan31989** [comment]
The example can't be added to the it as it's not very generic. But the document generation step has been pushed.
