### ISSUE TITLE
AWS.ECS.describeServices version 2.233.1 stopped return `schedulingStrategy` field

### ISSUE THREAD

**Issue by shlomisas** [aws/aws-sdk-js#2507]
When using aws-sdk version 2.233 the request ti get `describeServices` stopped return the `schedulingStrategy` field for the services under `resuls.services` array items.

Rolled-back to version `2.286.2` and i'm getting it again.

**Comment by srchase** [comment]
@shlomisas 

Thanks for opening this issue.

2.233.1 is an older version.  Did you mean you upgraded to 2.286.2?

**Comment by shlomisas** [comment]
Weird. 2.233.1 installed by default today. I'll recheck it abd reply

**Comment by shlomisas** [comment]
Checked again, with version 2.233.1 I'm getting `undefined` but with a newer version or major 2 (2.286.2 or 2.395.0) it works fine.

Closing the bug.
