### ISSUE TITLE
Signature V4 sorting query parameters not implemented correctly

### ISSUE THREAD

**Issue by verandar** [aws/aws-sdk-js#2511]
https://github.com/aws/aws-sdk-js/blob/c84015036df0c614ac5df85d00ca811ad10a9b93/lib/util.js#L80-L83

Signature V4 requires that both parameter names and values are sorted before URL encoding. But in util.js, parameter values are sorted after URL encoding.

**Comment by ajredniwja** [comment]
Hey @verandar,

Apologies for late reply, is it a breaking change for you? 
Our team welcomes PRs, we would be happy to review if you can open one.
