### ISSUE TITLE
Missing properties in SQS SendMessageResult TypeScript definition

### ISSUE THREAD

**Issue by adanilev** [aws/aws-sdk-js#2512]
Seems there is an additional field, `ResponseMetadata`, being sent in the `sendMessage()` response which is not part of the TypeScript definitions. I've noticed additional fields being included in some of the API Gateway events as well but don't have the details at hand. Or am I misinterpreting something?

Actual response:
```js
{
    "ResponseMetadata": {
        "RequestId": "00000000-0000-0000-0000-000000000000"
    },
    "MD5OfMessageBody": "00000000000000000000000000000000",
    "MessageId": "00000000-0000-0000-0000-000000000000"
}
```

sendMessage def:
```ts
sendMessage(...): Request<SQS.Types.SendMessageResult, AWSError>;
```

SendMessageResult def:
```ts
  export interface SendMessageResult {
    MD5OfMessageBody?: String;
    MD5OfMessageAttributes?: String;
    MessageId?: String;
    SequenceNumber?: String;
  }
```

**Comment by klaytaybai** [comment]
Hi @adanilev,

You are correct that the RequestId is not present in the SendMessageResult TypeScript definition, but you can still access it when using promises.  Here is an example how:

```
import SQS = require('aws-sdk/clients/sqs');

const sqsClient = new SQS({region: 'us-west-2'});
var params = {
    MessageBody: 'sqs request id', /* required */
    QueueUrl: 'https://sqs.us-west-2.amazonaws.com/241846427436/TestQueue', /* required */
    DelaySeconds: 0
  };

async function sendMessageAsync(params: any) :Promise<void> {
    try {
        const sendMessageResponse = await sqsClient.sendMessage(params).promise();
        console.log(sendMessageResponse.$response.requestId);
    } catch(err) {
        console.log(err);
    }
}

sendMessageAsync(params);
```

**Comment by adanilev** [comment]
Thanks for the quick response @klaytaybai. The only reason I noticed this is we have test data files that we use for unit and stub tests. We specify the type for each piece of test data. In this case, I had to define as `any` rather than `SendMessageResponse` since I want to use a real response.

**Comment by kbradl16** [comment]
This probably shouldn't have been closed. This should be fixed!
