### ISSUE TITLE
AppStream createUser works locally but not on was console

### ISSUE THREAD

**Issue by othmankh** [aws/aws-sdk-js#2518]
Hi,

I am trying to create a lambda function that creates a user in the AppStream pool, so  logically I follow the documentation of aws-sdk to know how to do that. What is surprising is that it is working locally by using Serverless by on AWS console it is not. Here is my code:

``` const AWS = require("aws-sdk");

AWS.config.update({
    region: "eu-west-1"
});

AWS.config.apiVersions = {
  appstream: '2016-12-01'
};

module.exports.handler = async (event, context, callback) => {
    
    // create user account in AppStream
    var params = {
        AuthenticationType: "USERPOOL",
        UserName: event.userName,
        MessageAction: "SUPPRESS"
    };
    
    console.log("Attempting to create AppStream account for "+event.userName);
      
    var appstream = new AWS.AppStream({apiVersion: '2016-12-01'});
    
    appstream.createUser(params, (err, data) => {
        if(err){
            console.log("there was an error creating the account");
            console.log(err);
            callback(err);
        }else{
            console.log("Success");
            console.log(data);
            callback(data);
        }
    });
}; 


And here is the error I got:

 Response:
{
  "errorMessage": "appstream.createUser is not a function",
  "errorType": "TypeError",
  "stackTrace": [
    "module.exports.handler (/var/task/index.js:25:15)"
  ]
} 
Any help ?

**Comment by AllanFly120** [comment]
Hey, the `CreateUser` API is only available in 2.338.0 and so on but Lambda is still using 2.299.0. We are working with Lambda team to deliver more up-to-date SDK but for now you can follow [this document](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html) to deploy bundled SDK of the newer version to your Lambda environment.

**Comment by othmankh** [comment]
@AllanFly120 is there an estimation for that ?

**Comment by ajredniwja** [comment]
@othmankh, most of the times it takes time for lambda to incorporate the latest SDK. The issue should not be a problem now. 
Closing this issue now, please re-open for any additional questions.
