### ISSUE TITLE
ListReviewableHITs  Operation didn't return HIT Datastructure

### ISSUE THREAD

**Issue by sofather** [aws/aws-sdk-js#2522]
As mentioned here 
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/MTurk.html
and here 
https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ListReviewableHITsOperation.html
the expected response is a list of Hit Data structure. The sandbox requester server response with a list of HITids only. 

The declaration of this method is fine: 

    "ListReviewableHITs": {
      "input": {
        "type": "structure",
        "members": {
          "HITTypeId": {},
          "Status": {},
          "NextToken": {},
          "MaxResults": {
            "type": "integer"
          }
        }
      },
      "output": {
        "type": "structure",
        "members": {
          "NextToken": {},
          "NumResults": {
            "type": "integer"
          },
          "HITs": {
            "shape": "S2d"
          }
        }
      },
      "idempotent": true
    },
**S2d is an alias for HIT Data structure**

Actual Response :
```
{ 
"NextToken":
   'NEXT_TOKEN_VALUE',
  NumResults: 1,
  HITs: [ { HITId: '388FBO7JZT48TG61MZMH91GBEYPYNF' } ] 
}

```

**Comment by sofather** [comment]
No updates so far?

**Comment by klaytaybai** [comment]
@sofather, have you followed these instructions from the second link you posted?

> By default, ListReviewableHITs operation only returns the IDs of HITs in the status Reviewable.
> 
> If you used the UpdateHITReviewStatus Operation to set the status of the HIT to Reviewing, and want HITs in the status Reviewing, set the Status request parameter to Reviewing.

**Comment by sofather** [comment]
@klaytaybai I notice it. I thought it's by mistakes, since on the first & second link there's this description:

> Response Elements
A successful request returns a paginated list of HIT data structures.

**Comment by ajredniwja** [comment]
Hey @sofather,

Closing this issue for now, please reopen if you have any questions.
