### ISSUE TITLE
S3 putObject Unexpected key 'Tagging'

### ISSUE THREAD

**Issue by jono99** [aws/aws-sdk-js#2525]
As the title suggests, Tagging isn't accepted in params. This whole function works otherwise without it. I then tried putObjectTagging which also isn't recognized as a function. Am I missing something?

```
$scope.upload = function() {
	var bucket = new AWS.S3({ params: { Bucket: S3.BUCKET + '/' + accountId + '/' + companyId }});
	var files = $scope.files;

	if (files && files.length) {
		for (var i = 0; i < files.length; i++) {
			var file = files[i];
			var params = { Key: file.name, ContentType: file.type != '' ? file.type : 'application/octet-stream', Body: file, ServerSideEncryption: 'AES256', Tagging: 'archive=false' };
			var tag = { Tagging: { TagSet: [{ Key: 'archive', Value: 'false' }] }}

			if (!file.$error) {
				bucket.putObject(params, function(err, data) {
					if (err) {
						console.error(err.message, err.code);
						return false;
					} else {
						console.log('File Uploaded Successfully', 'Done');

						// Reset Progress Bar
						$timeout(function() {
							$scope.uploadProgress = 0;
						}, 500);
					}
				})
				.on('httpUploadProgress', function(progress) {
					$scope.uploadProgress = Math.round(progress.loaded / progress.total * 100);
					$scope.$digest();
				});
			} else {
				console.error('Please select a file to upload');
			}
		}
	}
}

```

**Comment by klaytaybai** [comment]
Hi @jono99, can you please provide an example of where and how you used putObjectTagging in the context of the above code?  This function must use an object that already exists within S3.

**Comment by jono99** [comment]
Hi @kaytaybai I can't right now, will try tomorrow, but to give an idea, it was in-between the else after putObject just before Reset Progress Bar. Will try clarify tomorrow.

**Comment by jono99** [comment]
```
bucket.putObject(params, function(err, data) {
		if (err) {
			console.error(err.message, err.code);
			return false;
		} else {
			console.log('File Uploaded Successfully', 'Done');

                        **bucket.putObjectTagging(tags, function(err, data) {  }**

			// Reset Progress Bar
			$timeout(function() {
				$scope.uploadProgress = 0;
			}, 500);
		}
	})
```
**Returns:** TypeError: bucket.putObjectTagging is not a function

**Comment by klaytaybai** [comment]
@jono99, the most likely explanation is that the version of the SDK you are using is very old.  I wasn't able to reproduce this.  Can you run `npm list aws-sdk` and let us know the value?

**Comment by klaytaybai** [comment]
Also, are you running this in Lambda?

**Comment by jono99** [comment]
@klaytaybai apologies for not replying to this.
Bit late now, but output was **aws-sdk@2.395.0**
And no, this isn't running in Lambda.
I sort of worked out another solution, so this isn't too important anymore.

**Comment by srchase** [comment]
@jono99 

I'll go ahead and close our this issue for now.  If you're interested in re-engaging, let us know and we can re-open.
