### ISSUE TITLE
In operator not worked on lambda function and GSI

### ISSUE THREAD

**Issue by thinkhard-j-park** [aws/aws-sdk-js#2527]
I used lambda function with nodejs 8.1.0 SDK

Create GSI for your partition key. e.g. I created GSI with uri, lastUpdatedDatetime
Do scan with below parameters.

```
    ...
    let uriParams =  Object.keys(attrValues).toString()
    params = {
        FilterExpression: "#uri IN (" + uriParams + ")",
        ExpressionAttributeNames: {
            "#uri": "uri"
        },
        ExpressionAttributeValues: attrValues,
        IndexName: "uri-lastUpdatedDatetime-index",
        TableName: "docs",
        ConsistentRead: false
    }
    ...
```

Result is 200 OK, but there is no records. 
It seems scan result are depends on uri data. It is really strange. Some records retrieved by above expressions but others not.

I tried to retrieved data with key condition expression using "uri" key one by one. It worked.

**Comment by ajredniwja** [comment]
Hey @thinkhard-j-park,

Apologies for late reply, is this still an issue if you use the latest version of the SDK?

I will go ahead and close the issue, please re-open and use the [issue template](https://github.com/aws/aws-sdk-js/issues/new/choose) if you have any additional questions.
