### ISSUE TITLE
s3.putBucketLifecycleConfiguration, Filter not marked as required in docs

### ISSUE THREAD

**Issue by worc** [aws/aws-sdk-js#2530]
in the docs for [`putBucketLifecycleConfiguration`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketLifecycleConfiguration-property) there are a number of params fields marked as required, but Filter is not.

If you don't have a Filter on a rule, you get a misleading error:

`MalformedXML: The XML you provided was not well-formed or did not validate against our published schema`

There's no XML here, it's JSON. The JSON is **well-formed** and there's no current, valid, correct, and published schema to check against.

In order to get past that MalformedXML error, all you have to do is add the Filter param with an empty Prefix:
```
  const params = {
    Bucket,
    LifecycleConfiguration: {
      Rules: [{
        ID: 'Expire objects older than 15 days',
        Status: 'Enabled',
        Expiration: {
          Days: expirationDays,
        },
        // this object is REQUIRED in a rule otherwise you trigger a MalformedXML error:
        Filter: {
          Prefix: '',
        },
      }],
    },
  }
```

**Comment by klaytaybai** [comment]
@worc, thank you for identifying this.  I was able to reproduce the problem.

**Comment by srchase** [comment]
@worc 

Thanks for raising this issue.  This is actually an issue with the underlying service.  S3's documentation does state that this field is required: [RESTBucketPUTlifecycle](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTlifecycle.html), however, the model use to generate this operation in the JavaScript SDK (and all of the other SDKs) does not have Filter marked as required.

I've escalated this to the S3 team to get it resolved.

**Comment by fpronto** [comment]
This is happening in putBucketReplication too
Should I open a new issue?

**Comment by liesislukas** [comment]
FYI, just ran into this issue. Filter is optional in general docs, it's optional in typescript declaration in aws v2 sdk too yet it's not optional like it's described in this issue.

![image](https://user-images.githubusercontent.com/2733862/188004582-9a07e7f1-e701-4f6a-8e9b-c6af727ff325.png)

![image](https://user-images.githubusercontent.com/2733862/188004698-d2d3aced-6d16-4371-8ec6-90b9dd1b9fd9.png)

https://docs.aws.amazon.com/AmazonS3/latest/API/API_LifecycleRule.html#AmazonS3-Type-LifecycleRule-Expiration


Only place where it mentions about required is in sdk docs but it's a bit tricky too, while it's optional when Prefix is set but Prefix is no longer in use, so it is not optional.

![image](https://user-images.githubusercontent.com/2733862/188005345-b4cc1a5c-6aae-40b6-b355-5348690d015b.png)


https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketLifecycleConfiguration-property
