### ISSUE TITLE
Typescript: Params in constructor are still required

### ISSUE THREAD

**Issue by chris-pardy** [aws/aws-sdk-js#2532]
Expected behavior:

The following code should pass typescript type checking.
```
const documentClient = new DynamoDB.DocumentClient({
  params: {
    TableName: 'my-table'
  }
});

const value = await documentClient.get({Key: {id: 'Test'}}).promise();
```

Actual behavior:
```
error TS2345: Argument of type '{ Key: object; }' is not assignable to parameter of type 'GetItemInput'.
  Property 'TableName' is missing in type '{ Key: object; }' but required in type 'GetItemInput'.
```

Using newer typescript features it's possible to express which parameters have been supplied in the constructor and are no longer required in the various method calls.

**Comment by klaytaybai** [comment]
Hi @chris-pardy, I'm having some trouble reproducing this.  Which version of the SDK are you using?

**Comment by chris-pardy** [comment]
@klaytaybai 2.149.0 let me upgrade to the latest and see if it goes away. To be clear the error occurs during type checking not during runtime.

**Comment by drexler** [comment]
@chris-pardy  i see what you're trying to do. Interesting. But `v2.403.0` still ships with a definition file expecting this interface as a parameter for `.get` calls on the documentClient:

```
export interface GetItemInput {
    TableName: TableName;
    Key: Key;
    AttributesToGet?: AttributeNameList;
    ConsistentRead?: ConsistentRead;
    ReturnConsumedCapacity?: ReturnConsumedCapacity;
    ProjectionExpression?: ProjectionExpression;
    ExpressionAttributeNames?: ExpressionAttributeNameMap;
  }
```

You're better off just explicitly referencing the table name in the parameters for each individual call - a bit ugly but necessary for now till its changed.

**Comment by chris-pardy** [comment]
@drexler hence why I filed this bug, Typescript is preventing me from using documented behavior of the API and it's possible to re-write the typescript types to allow it (using conditional types). I've already implemented it locally and would be happy to do so here as well but I'm not sure what the guideline for contributing is.

**Comment by AllanFly120** [comment]
Hey @chris-pardy I think this is a valid feature request. The the typescript definition doesn't take normal parameters from client construction into consideration. The TS definitions still need the `TableName` as required since many other users need type security when calling method with all it's parameters. If you have a better idea to solve the issue I'm more than happy to review it. 

IMHO the TS interface system doesn't offer a good way to validate the typing according to the runtime code.

**Comment by chris-pardy** [comment]
@AllanFly120 I can open a PR to improve the typing to handle this but I'll have to upgrade the typescript version to 2.8 (conditional type support) if you're comfortable with that I'd start with a PR to update one of the clients (Probably Dynamo) and if it looks good I could automate the updates to the other clients.

**Comment by chris-pardy** [comment]
@AllanFly120 see PR #2541 - This handles the case of parameters bound in the constructor. I've got examples of that in the `ts/dynamodb.ts` file. The types are pretty obtuse but it does the job.

**Comment by NMinhNguyen** [comment]
This is still an issue.

**Comment by octaneC8H18** [comment]
I am still getting this issue, I am using the 1.100.0
