### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by postama** [aws/aws-sdk-js#2533]
In the file `codedeploy-2014-10-06.normal.json`
On the line 2905
```    
"ECSTaskSet": {
      "type": "structure",
      "members": {
        "identifer": {
          "shape": "ECSTaskSetIdentifier",
          "documentation": "<p> A unique ID of an <code>ECSTaskSet</code>. </p>"
        },
```

The word 'identifier' is misspelled as 'identifer'. At first I thought it was an error in the type definition for ECSTaskSet but those are auto generated from this file.

I am unsure if this file is supposed to be updated, if so, I would be happy to create a pull request, but it is unclear if the misspelling is in the documentation and generated type definition or int he service itself.

**Comment by klaytaybai** [comment]
Hi @postama, thank you for catching this.  We appreciate the offer of a pull request, but we do need the service team to make the change.  I'll ask them to take care of it.

We prefer that this issues list is scoped to the responsibilities of the JavaScript SDK, so I'm going to close out this issue.
