### ISSUE TITLE
connect EHOSTUNREACH 169.254.169.254:80

### ISSUE THREAD

**Issue by LovikaJ** [aws/aws-sdk-js#2534]
Getting  connect EHOSTUNREACH 169.254.169.254:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14). 
Node Version : 9.11.1
npm : 5.6.0
aws-sdk : 2.170.0

I have tried to bump up the version of aws-sdk, though still getting connection error. Seems like aws-sdk is not able to read the endpoint of aws. I am running test cases jest when I encounter this error. It has been working fine till few days ago. I just switched to node version from 8.15.0 to 9.11.1.

The code doesn't have any issue as the same works fine on another machine.

What could be the possible cause of it?

**Comment by teroxik** [comment]
Where do you run the code? EC2 instance, Fargate instance, lambda?  169.254.169.254:80 is a metadata endpoint for the EC2 instance. I have some problems with running nodejs app on fargate using aws sdk javascript SDK as well.

**Comment by LovikaJ** [comment]
I am running it using npm test in lambdas and trying to connect to SES and S3. I checked my AWS credentials multiple times. the same configurations were working fine till 2-3 days ago.

**Comment by teroxik** [comment]
Don't want to hijack your issue, but have a similar problem. Running a nodejs 10.15 app, tried version 8 as well. Looking at the code in the credentials chain:

```
AWS.CredentialProviderChain.defaultProviders = [
  function () { return new AWS.EnvironmentCredentials('AWS'); },
  function () { return new AWS.EnvironmentCredentials('AMAZON'); },
  function () { return new AWS.SharedIniFileCredentials(); },
  function () {
    if (AWS.ECSCredentials.prototype.isConfiguredForEcsCredentials()) {
      return new AWS.ECSCredentials();
    }
    return new AWS.EC2MetadataCredentials();
  }
];```

the last EC2MetadataCredentilas() makes the call to that endpoint, which is not available. In my fargate process I have listed the `process.env` variables and there isn't the full or relative url variable set as described in here [remote_credentials](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/remote_credentials.js). Any advice on that? 

@LovikaJ would recommend you to do the same - to get the output.

**Comment by LovikaJ** [comment]
@teroxik Hi, I was able to resolve the issue by setting the aws credentials in environment variables and by updating the `aws-sdk `version, although had to keep it > than 2.305.0 as I get `async-suffix` error in the upper versions. Although good thing is issue has been resolved.

You could try to set the `AWS_ACCESS_KEY_ID `and `AWS_SECRET_ACCESS_KEY `in `process.env`

**Comment by teroxik** [comment]
@LovikaJ Thank you, that's what I have done already as a workaround. But I want to use the instance profile without using an explicit credentials as that works correctly with Java SDK for example. And I would like to understand where the problem is. If this is an expected behaviour. For example in lambdas the SDK is set up correctly without the need for using ENV credentials. That makes me wonder if there is something wrong with the fargate runtime or my setup.

**Comment by AllanFly120** [comment]
Hey @teroxik,

Both Lambda and Fargate JS SDK use metadata service for credential. This looks like a connection issue on the service side not the SDK itself. Maybe you can bring it to the service team on [Farget forum](https://forums.aws.amazon.com/tags/fargate) and give them some visibility on this issue.

**Comment by teroxik** [comment]
My stack trace is actually slightly different, but could be just different version of node:

```
{ Error: connect EINVAL 169.254.169.254:80 - Local (0.0.0.0:0) 
at internalConnect (net.js:964:16)
at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)
at net.js:1062:9
at _combinedTickCallback (internal/process/next_tick.js:132:7)
at process._tickDomainCallback (internal/process/next_tick.js:219:9)
message: 'Missing credentials in config',
errno: 'EINVAL',
code: 'CredentialsError',
syscall: 'connect',
address: '169.254.169.254',
port: 80,
time: 2019-02-13T12:46:53.403Z,
```

I will reach out to the forum, thanks for help.

**Comment by teroxik** [comment]
Sorry for inactivity, on hols this week. Opened an issue in the AWS Forum as suggested.

[](https://forums.aws.amazon.com/thread.jspa?threadID=299018)

**Comment by teroxik** [comment]
I'm OK if you close it. I will come back to it and update it here, reopen eventually.

**Comment by jaarandaz** [comment]
@teroxik We had a similar issue and the reason was that we forgot to set a taskRoleArn. Hope you found the solution or that this works for you too.
