### ISSUE TITLE
AWS S3 is not supporting for Universal Windows Platform (UWP).

### ISSUE THREAD

**Issue by cchakkaravarthi** [aws/aws-sdk-js#2535]
AWS S3 is not supporting for Universal Windows Platform (UWP).

**Comment by klaytaybai** [comment]
Hi @cchakkaravarthi, do you have a specific error message that you are getting?

Also, to make sure this issue is in the right place, can you please verify that you are using the AWS SDK for JavaScript and not the AWS SDK for .NET in your project?

**Comment by cchakkaravarthi** [comment]
Hi @klaytaybai,
I'm using AWS SDK in JavaScript while I got the error.
![aws_js_error](https://user-images.githubusercontent.com/42862845/53347393-fb658200-393e-11e9-922e-5f6725ca3d31.png)
If I use AWS SDK in .NET while I got the error is bellow ,

Inner Exception 1:
COMException: The text associated with this error code could not be found.

The server name or address could not be resolved

**Comment by srchase** [comment]
@cchakkaravarthi 

Can you please provide a detailed example of what you code and environment, including versions of the SDK?

**Comment by cchakkaravarthi** [comment]
Hi @srchase ,

Environment : 
---------------
Tools:
Visual Studio Code Version: 1.25.1 ,
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.6) Release
VisualStudio.15.Release/15.2.0+26430.6
Microsoft .NET Framework
Version 4.7.03190.

 "react": "16.3.1",
 "react-native": "^0.55.4","react-native-windows": "0.55.0-rc.0",
 "rnpm-plugin-windows": "^0.2.8"

  "@types/aws-sdk": "^2.7.0",
  "aws-sdk": "^2.401.0",

Example Of Code : 
--------------------
JavaScript  Code : 

        AWS.config.update({ accessKeyId: config.accessKeyId, secretAccessKey: config.secretAccessKey }); 
        AWS.config.region = config.region;

        var bucket = new AWS.S3({params: {Bucket: config.bucket}});
        bucket.getObject({Key: config.key},function(err:any,file:any){
        debugger;
        const data = file.Body;
        });

C# Code : 
            References : AWSSDK.S3 3.3.31.19

            var regionIdentifier = RegionEndpoint.GetBySystemName(region);
            using (var client = new AmazonS3Client(storageKeyId, storageSecret, regionIdentifier))
            {
                var response = await client.GetObjectAsync(AwsBucketName, AwsBucketFileName);
                var reader =response.ResponseStream))
            }

**Comment by srchase** [comment]
@cchakkaravarthi 

Can you get details on which headers are invalid?

It looks like there have been some UWP issues regarding the Authorization header specifically.

**Comment by cchakkaravarthi** [comment]
Hi @srchase ,
please refer this 
var params = {
  Bucket: "examplebucket", 
  Key: "HappyFace.jpg"
 };
 **s3.getObject**(params, function(err, data) {
   if (err) console.log(err, err.stack); // an error occurred
   else     console.log(data);           // successful response

 });

In AWS.HttpRequest(endpoint, region)  
header : { X-Amz-User-Agent: "aws-sdk-js-react-native/2.401.0" }

![image](https://user-images.githubusercontent.com/42862845/53548469-8c16aa80-3b57-11e9-986b-e04ad76202eb.png)

**Comment by srchase** [comment]
@cchakkaravarthi,

Does UWP provide details on which header is invalid?
