### ISSUE TITLE
aws pinpoint update-apns-channel: missing credentials

### ISSUE THREAD

**Issue by Jordan-McMillan101** [aws/aws-sdk-js#2537]
`aws --version`
`aws-cli/1.16.76 Python/2.7.10 Darwin/16.7.0 botocore/1.12.66`

I'm trying to programmatically add an APNS_SANDBOX channel to a pinpoint app. I'm able to do this successfully via the pinpoint console, but not with aws cli or a lambda function which is the end goal. Changes to our Test/Prod environments can only be made via the CodePipeline, but for testing purposes I'm trying to achieve this with the aws cli.

I've tried both aws cli (using the root credentials) and a lambda function -- both result in the following error:

`An error occurred (BadRequestException) when calling the UpdateApnsSandboxChannel operation: Missing credentials`

I have tried setting the Certificate field in the UpdateApnsSandboxChannel json object as the path to the .p12 certificate file as well as using a string value retrieved from the openssl tool.

Today I worked with someone from aws support, and they were not able to figure out the issue after trying to debug for a couple of hours. They said they would send an email to the pinpoint team, but they did not have an ETA on when they might respond.

Please help and thank you for your time.

**Comment by Jordan-McMillan101** [comment]
I ended up getting this to work successfully -- This is why it was failing:

I was originally making the cli call with the following request object as this is what is including in the documentation:
```

aws pinpoint update-apns-sandbox-channel --application-id [physicalID]  --cli-input-json file:///path-to-requestObject.json
```

```
{
    "APNSSandboxChannelRequest": {
        "BundleId": "com.bundleId.value", 
        "Certificate":"P12_FILE_PATH_OR_CERT_AS_STRING", 
        "DefaultAuthenticationMethod": "CERTIFICATE", 
        "Enabled": true, 
        "PrivateKey":"PRIVATEKEY_FILE_PATH_OR_AS_STRING",
        "TeamId": "",
        "TokenKey": "",
        "TokenKeyId": ""
    }, 
    "ApplicationId": "Pinpoint_PhysicalId"
}

```

After playing around with it some more I got it to work by removing BundleId, TeamId, TokenKey, and TokenKeyId. I believe these fields are needed when using a p8 certificate.

```

{
    "APNSSandboxChannelRequest": {
        "Certificate":"P12_FILE_PATH_OR_CERT_AS_STRING", 
        "DefaultAuthenticationMethod": "CERTIFICATE", 
        "Enabled": true, 
        "PrivateKey":"PRIVATEKEY_FILE_PATH_OR_AS_STRING"      
    }, 
    "ApplicationId": "Pinpoint_PhysicalId"
}

```

It would be very useful to add better error messages or more information in the documentation.

**Comment by klaytaybai** [comment]
Hi @Jordan-McMillan101, thank you for the update.  I'm glad you got it working.  Have you tried to get it to work with Lambda and the JS SDK?  @justnance, will probably be following up with you in your [CLI issue](https://github.com/aws/aws-cli/issues/3936).  She is trying to work with Premium Support to make this a better experience for you and others.

**Comment by Jordan-McMillan101** [comment]
@klaytaybai thanks for the reply, yes I was able to get it working with my lambda-backed custom resource (pinpoint app).

Are you able to confirm if the fields I removed are for different apns certificate types? In my case I have a .p12 for apns_sandbox and a .p12 for apns. I see pinpoint and mobileHub support .p8 as well as a universal certificate.
