### ISSUE TITLE
DynamoDB KeyType may have inappropriate definition

### ISSUE THREAD

**Issue by rambabusaravanan** [aws/aws-sdk-js#2538]
An Attribute's KeyType in DynamoDB can have only "HASH" or "RANGE", says [AWS documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_KeySchemaElement.html#DDB-Type-KeySchemaElement-KeyType)
 
> Valid Values: HASH | RANGE

But `dynamodb.d.ts` in "aws-sdk" has the type definition for `KeyType` as
```
export type KeyType = "HASH"|"RANGE"|string;
```
where the actual expectation is 
```
export type KeyType = "HASH"|"RANGE";
```

This forces us to declare some new types like `type StrictKeyType = "HASH" | "RANGE"` to use in our project

**Comment by AllanFly120** [comment]
Hey @rambabusaravanan,  the `string` here is to make the types backward-compatible. You can specify the API version in the client constructor and the old APIs may support different enum values. However, the TS definitions are generated based on the newest API version. If the `string` is remove, it may break other customers in the build time. I will tag this as feature request for now.
