### ISSUE TITLE
IoTJobsDataPlane#updateJobExecution has no effects

### ISSUE THREAD

**Issue by kevinresol** [aws/aws-sdk-js#2539]
consider this code:

```js
var jobs = new IoTJobsDataPlane({
	endpoint: '<xxxxxxxxx>.jobs.iot.ap-southeast-1.amazonaws.com',
	accessKeyId: '<xxxxxxxxx>',
	secretAccessKey: '<xxxxxxxxx>',
	region: 'ap-southeast-1',
});
jobs.updateJobExecution({
	jobId: jobId
	thingName: thingName,
	status: 'SUCCEEDED',
}, console.log);
```

It will print `null, {}` (i.e. no error)
However, the job is actually **not updated** when checked from the IoT console.
Note that the API config is correctly set up because other functions are working fine (e.g. `getPendingJobExecutions`, `describeJobExecution`)

I have checked the raw http response, it is `200 OK` with responseText:
```
{"Output":{"__type":"com.amazon.coral.service#UnknownOperationException","message":null},"Version":"1.0"}
```

Actually I think it is not a problem of the js sdk but a problem from the REST API itself.

**Comment by srchase** [comment]
@kevinresol 

Thanks for opening this issue.

I'm seeing the same behavior and have escalated this issue to the IoT team.

**Comment by kevinresol** [comment]
Is there a rough ETA? or how long on average for past issues like this get fixed? 

I need to decide whether wait for the fix or go for some alternatives.

Thanks.

**Comment by srchase** [comment]
@kevinresol 

I'm not able to provide an ETA.  We'll reply on this issue when there is an update to share.

**Comment by srchase** [comment]
@kevinresol 

The service made a fix for this issue.  Are you able to successfully update a job execution now?

**Comment by kevinresol** [comment]
I'm still getting `{"Output":{"__type":"com.amazon.coral.service#UnknownOperationException","message":null},"Version":"1.0"}`

**Comment by kevinresol** [comment]
Interestingly it is working now (or somewhat randomly). I assume the deployment was in progress back then. Closing now.
