### ISSUE TITLE
Issue with Cognito Identity Pool

### ISSUE THREAD

**Issue by skay973** [aws/aws-sdk-js#2540]
Hi there,

I'm trying to get an identity against Cognito Federated Identities to access DynamoDB.

The thing is, when it comes to call the get() on AWS.config.credentials, sounds like the function never executes... and I get no error...

here is some code sample : 

```
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'eu-west-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    Logins: {
        'cognito-idp.eu-west-1.amazonaws.com/eu-west-1xxxxxxxxxxx': id_token
    }
});

AWS.config.credentials.get((error) => {
    if(error) console.log(error);
    console.log(AWS.config.credentials.accessKeyId);
    console.log(AWS.config.credentials.sessionToken);
    console.log(AWS.config.credentials.identityId);
});
```

The last 3 logs stay undefined. My id_token is a token I got when authenticate against my users pool in cognito. And in Federated Identities, I put cognito as a provider with the right group id and the right client id.

Help ! :'(

**Comment by srchase** [comment]
@skay973 

Which version of the SDK are you using?  Is ```error``` null?

**Comment by ffxsam** [comment]
@skay973 You should probably be using AWS Amplify for authentication. Using the Cognito JS directly is rather painful.

https://aws-amplify.github.io/docs/js/authentication
