### ISSUE TITLE
How to search directly on S3

### ISSUE THREAD

**Issue by vladejs** [aws/aws-sdk-js#2543]
I just searched the entire Google and didn't find a solution for this (apparently simple) problem.

I need to return a list of filtered given a random text. Example:

Given the text: was. Return all this files:

bucketName/itwasfine.txt
bucketName/alreadyinthere.was.txt
And exclude everything else.

My goal is to create a client side table with a fuzzy search functionality on the bucket's keys, including incremental pagination.

How to achieve that without getting all objects on the bucket?

**Comment by srchase** [comment]
@vladejs 

There is not a direct way to do this.

[listObjectsV2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property) allows you to retrieve objects by key prefix, but would not be able to filter for 'was' in the key 'foowasbar'.

The AWS CLI gives you a the following operation:

```
aws s3api list-objects --bucket bucketName --query "Contents[?contains(Key, 'was')]"
```

That makes one or more API calls to retrieve all Objects in the bucket and filters the results locally.

**Comment by vladejs** [comment]
OMG, so what about  having one million items in my bucket?

Given your answer, is literally impossible to do a performant search on s3.

I'm then forced to download 1 million items locally and do the search. Is
that the approach I should take?

**Comment by srchase** [comment]
@vladejs 

Refer to this Whitepaper: [AWS Storage Services 
Overview](https://d0.awsstatic.com/whitepapers/Storage/AWS%20Storage%20Services%20Whitepaper-v9.pdf)

> Amazon S3 doesn’t offer query capabilities to retrieve specific objects. When you use Amazon S3 you need to know the exact bucket name and key for the files you want to retrieve from the service. Amazon S3 can’t be used as a data base or search engine by itself. Instead, you can pair Amazon S3 with Amazon DynamoDB, Amazon CloudSearch, or Amazon Relational Data base Service (Amazon RDS) to index and query metadata about Amazon S3 buckets and objects

The recommended solution is to pair S3 with an additional service.  With this approach, your index can return only the relevant keys.

**Comment by ffxsam** [comment]
@vladejs S3 should be for storing data, and if you want to search and find specific objects, you should have some sort of database to keep track.
