### ISSUE TITLE
Images are not being cached

### ISSUE THREAD

**Issue by KapilJethava** [aws/aws-sdk-js#2547]
Hi there,

In our application, we are using getSignedUrl  method to have signed url. This method adds up  couple of parameter in url query. Among those all parameters, X-Amz-Date and X-Amz-Signature gets changed with each partial re-rendering of page and new image request  downloads the same images again and again.
How can I restrict getSignedUrl to changes the    X-Amz-Date and X-Amz-Signature?
or 
Might be any other way around to cache images?

**Comment by srchase** [comment]
@KapilJethava 

The signature changes based off of when it is calculated.

How long are you wanting to cache the images?
