### ISSUE TITLE
s3.selectObjectContent and nodejs8.10

### ISSUE THREAD

**Issue by robermar2** [aws/aws-sdk-js#2548]
I have a Lambda function using nodejs8.10 runtime.

I am using aws sam and local debugging.

I am attempting to use the aws javascript sdk with nodejs8.10 to use the s3 selectObjectContent method.

Given the version of node I am using, I am attempting to use this pattern from the official documentation:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#selectObjectContent-property

// In browsers, events aren't processed until the response is fully buffered.
// Events will be accessible as an array.
s3.selectObjectContent({/** params **/}, function(err, data) {
  if (err) {
    // handle error
    return console.error(err);
  }

  var events = data.Payload;

  for (var event of events) {
    // Check the top-level field to determine which event this is.
    if (event.Records) {
      // handle Records event
    } else if (event.Stats) {
      // handle Stats event
    } else if (event.Progress) {
      // handle Progress event
    } else if (event.Cont) {
      // handle Cont event
    } else if (event.End) {
      // handle End event
    }
  }
});

on "for (var event of events)", the following exception is being thrown:
"TypeError: events is not iterable    at Response.<anonymous> (/var/task/index.js:305:51)    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:364:18)    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)"

**Comment by srchase** [comment]
@robermar2 

Since you're using Node (and not a Browser), does the suggested EventStream example work for you?

**Comment by robermar2** [comment]
@srchase It was a long day of troubleshooting. I copied in the wrong attempt.

The EventStream example did work once I wrapped it all in a promise as I need to work with async functions.
