### ISSUE TITLE
After updating version from 2.358.0 to latest, SES sendEmail hangs when SES permissions assigned via the IAM roles.

### ISSUE THREAD

**Issue by santriseus** [aws/aws-sdk-js#2551]
Recently we updated the asw-sdk from version 2.358.0 to version 2.407.0 and found out that ses.sendEmail callback never fires if we run code at the EC2 instance and assign permission via the IAM Role (AmazonSESFullAccess policy) to the instance.
We don`t have any errors in console.
If we run it at the local machines with the aws sdk configured via the aws cli using the access keys it works as before.

**Comment by AllanFly120** [comment]
Hey @santriseus 
Do you see any errors? If you don't see any error and the callback is never triggered, it's possible that the request and send but never responded. If you wait for more than 2 mins(default timeout, may varies according to your http config), you might see the callback being triggered. The errors in the callback is helpful to diagnose this issue.

**Comment by santriseus** [comment]
@AllanFly120 Thanks for your reply. I tried to inject the logger inside the ses config, but there is no any useful output from it during the hanging.

When we try to run it at our local machines, which utilize the developer credentials set via the cli (accessKeyId+secretAccessKey) everything works fine and we receive the following message from the sdk internal logging: 
"[AWS ses 200 0.655s 0 retries] sendEmail({ Destination: { ToAddresses: ..."

But when we run the same code at the EC2 instance with policies set via the IAM Role we don`t have any output from sdk internal logging. It just hangs: no callback is called. No information/errors in log. We also tried to use sendEmail(...).promise() but the situation is the same: promise never becomes resolved.
Is it possible to make internal sdk logging more verbose, to understand what cause the hanging?

For now we rolled back to version "2.358.0" and it works fine. Callback is called and we could see in internal sdk log: "AWS ses 200 0.147s 0 retries] sendEmail({ Destination: { ToAddresses: ... }) "

**Comment by AllanFly120** [comment]
The SDK in EC2 uses [`ec2 metadata service`](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/ec2_metadata_credentials.js) whereas the local machine uses credentials in shared credential file. Maybe the process hangs at credentials resolvation. Can you try calling the metadataservice and see if you can get correct credentials.

```javascript
const metadataService = new AWS.MetadataService(clientConfig);
metadataService.loadCredentials((err, creds) => {
    if (err)console.log(err);
    else console.log(creds);
})
```

If the credentials works, as a work around for this issue, you can explicitely set the AWS credentials with the credentials loaded.
