### ISSUE TITLE
S3 Upload file with stream takes a lot of memory

### ISSUE THREAD

**Issue by BenjD90** [aws/aws-sdk-js#2552]
Hello,

I'm trying to upload many file in parallel to S3 to not spend too much time to do it. 
While I'm uploading the memory usage explode as the chart below show it :
![image](https://user-images.githubusercontent.com/8216338/53335976-3b0b7a00-38fd-11e9-8cd7-32f759f71933.png)

The heap stay low (in red), I think it might be due to [backpreassure](https://nodejs.org/en/docs/guides/backpressuring-in-streams/).

Here is a memory snapshot while uploading to S3 :
![image](https://user-images.githubusercontent.com/8216338/53336275-211e6700-38fe-11e9-9edb-b55680c8f7f5.png)

### To reproduce
Here is a repository with two functions to reproduce this issue :
* One, classic, to save a file to the file system with stream
* One, using aws-sdk to save file to S3

https://github.com/BenjD90/aws-s3-ram-overconsumption

### Versions :
- aws-sdk : 2.409.0
- node.js: 10.15.1
- os : ubuntu 18.04

**Comment by mreinstein** [comment]
something that might help narrow down the cause: can you eliminate `promise-pool-executor` as a dependency, relying solely on `aws-sdk` and manual promise management to see if the problem goes away? I haven't looked at the implementation of `promise-pool-executor` internally but it's possible that it's doing something weird with promises and/or generators and gobbling up memory. 

Anyway, just a thought.

**Comment by BenjD90** [comment]
@mreinstein I've updated the project, and removed `promise-pool-executor` dependency. Il replaced it with a simple Promise.all on 100. So we upload many files at the same time, to simulate multiple concurrent calls to our api at the same time.

The result doesn't changed :cry: 

Here the part that has changed :
```js
await Promise.all(
      Array(100)
          .fill(0)
          .map(async (v, index) => {
            const fileStream = fs.createReadStream('media-sample.jpg');

            let uploadResult;
            if (storageType === 'fs') uploadResult = await saveToFileSystem(fileStream);
            else if (storageType === 's3') uploadResult = await saveToS3(fileStream);
            else throw new Error('unknown-storage-type');

            // printRAMUsage();
            // console.log(`DONE ${index} size: ${uploadResult.size} hash : ${uploadResult.hash}`);
          })
  );
```

**Comment by victorboissiere** [comment]
I have the same issue! Is it related to the way AWS sdk handles streams ?

**Comment by AllanFly120** [comment]
Hey @BenjD90 Thanks for the easy-to-reproduce cases! I will look into this issue. Interestingly the memory usage is mainly in rss and external. I suspect it has something to do with the streams as @victorboissiere points out, especially the stream buffering. When doing multi-part upload, the SDK buffers the stream until the buffer reaches the size of the `partSize` you specify(default 5MB) before making each `uploadPart` request. When you spin up 100 `s3.upload` streams, sdk will do the same thing to all these stream, so that you see SDK uses a lot of rss. But the buffer usage for each stream is fixed. I believe you will see less memory usage if you upload the same amount of data but concat them beforehand and use a single stream.

**Comment by BenjD90** [comment]
Hello @AllanFly120,

Thank you for investigating the issue !

**The purpose of the launch concurrently 100 `s3.upload` is to simulate 100 calls to my API that upload files to S3.**
The first part of the [reproduce project](https://github.com/BenjD90/aws-s3-ram-overconsumption) show how it reacts for the same task but saving to disk, with a slow disk writing NoeJS slows down the reading stream and do not use a lot of memory ([backpreasure solution in NodeJS](https://nodejs.org/en/docs/guides/backpressuring-in-streams/#lifecycle-of-pipe)).

1 - Do you know if I can avoid multi-part upload and upload my file in one part with a stream ? I'm thinking of something like this with [request](https://github.com/request/request#streaming) library :
```js
fs.createReadStream('file.json').pipe(request.put('http://mysite.com/obj.json'))
```
2 - If it is not possible, why there is a minimum of [5 MB for the multi-part buffer](https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L145) ?

3 - If I count, I upload 100 files each use a 5 MB buffer in memory, so I should use 200 MB (node idle) + 500 MB = 700 MB which not what I measure :disappointed:

**Comment by BenjD90** [comment]
@AllanFly120 Do you have some ideas about how to solve this issue ? Do you need more informations ?

**Comment by rfink** [comment]
Also having this issue, without parallelism.

**Comment by cesar3030** [comment]
I was having a memory issue because of aws-sdk.
I changed the way I imported the library and it went back to normal...
Before:

```javascript
import * as AWS from 'aws-sdk';
```

After:

```javascript
const AWS = require('aws-sdk');
```

**Comment by CognitiveClouds-Prasad** [comment]
I am facing this type of problem in web browser itself. I am using Firefox on Ubuntu 18.04. I am trying to upload images. It is taking more than 4GB of RAM and CPU is running at about 75% utilisation.

**Comment by brendanw** [comment]
I am seeing the same issue and have isolated the problem as coming from the aws sdk by swapping it with my own writable stream.

**Comment by ajredniwja** [comment]
Users are welcomed to use [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3) which is under developer preview right now and give their reviews. 

One of the features introduced in V3 is the use of modularized packages which lets you deploy functions in very less time.

Will keep this issue open for developers to share their use cases and workarounds, we'd also encourage any PRs for the fix.

**Comment by nestoru** [comment]
@ajredniwja is JS-SDK-V3 not having this memory issue?

@brendanw Did you mean that there is actually a workaround to this issue if "Using aws.s3.getSignedUrl and request.put().pipe"? If yes could you please share some statements as guidance so that we try this out on our end?

Thank you both!

**Comment by hharutyunov** [comment]
Dear community and @AllanFly120 @ajredniwja,
I'm using above mentioned all suggested methods, but still memory consumption is too big, do you have other ideas on how to solve it?

**Comment by ajredniwja** [comment]
@ajredniwja V3 is much lighter than the V2, it is under developer preview right now for a great community of developers and leaders like you to give feedback so we can get the best product for our customers.

**Comment by ajredniwja** [comment]
@nestoru JS-SDK-V3 is much lighter than the JS-SDK-V2 since it uses modularized packages, it is under developer preview right now for a great community of developers and leaders like you to give feedback so we can get the best product for our customers.

**Comment by ajredniwja** [comment]
@hharutyunov,

Can you please share what your use case is?

**Comment by brendanw** [comment]
This should be reopened as it has not been fixed. Mentioning an SDK that is in developer preview is not a fix. It only takes one Amazon engineer to fix this issue for the benefit of many developers. It takes a lot more work for all of us client developers to suffer through a buggy pre-1.0 library. We are paying customers, step up your game.

**Comment by brendanw** [comment]
```
    s3.getSignedUrl('putObject', s3_params, function(err, data) {
      startUpload(req, data, contentLength, res)
    });

  function startUpload(req, signedRequest, contentLength, res) {
    const busboy = new Busboy({headers: req.headers});
    var totalSize = 0;
    busboy.on('file', function pipeFile(fieldname, fileStream, filename, encoding, mimetype) {
      let contentType = mimetype;
      fileStream.on('data', function handleData(data) {
        totalSize += data.size
      });
      let writeStream = request.put(signedRequest, {
        headers: {
          'Content-Type': contentType,
          'Content-Length': contentLength,
        }
      }, function s3Callback(err, response, body) {
        updateACL(req.query.key, res)
      });
      let emitter = fileStream.pipe(writeStream);
      emitter.on('end', function() {
        console.log("finished reading file");
      });
    });
    req.pipe(busboy);
    busboy.on('end', function pipeEnd() {
      res.json({success: true});
    });
  }
```

@ajredniwja @nestoru Here is a code from an internal service that works around the issue. Note it's missing size checks. You will need the Busboy dependency.

**Comment by brendanw** [comment]
Here are some S3 alternatives for folks:

https://www.backblaze.com/b2/cloud-storage.html
https://cloud.google.com/storage/docs/
https://www.rackspace.com/cloud/files
https://azure.microsoft.com/en-us/

**Comment by mreinstein** [comment]
> ajredniwja added the closing-soon-if-no-response label 8 days ago

Why? The issue outlined here is pretty straightforward. Excessive memory consumption.

Honestly this is something that drives me nuts about modern software maintenance on github. Just because an issue has not been replied to in X period of time doesn't mean it's not an issue. Closing the ticket just sweeps the problem under the rug, in exchange for a short term good feeling of having less open tickets.

Having more open tickets that track real problems is more important than warm fuzzy good feelings. This is just basic post-education entry level software development.
