### ISSUE TITLE
"Network Failure" while describing EC2 instances in Firefox Extension

### ISSUE THREAD

**Issue by akefirad** [aws/aws-sdk-js#2555]
I've written a very simple script that just logs the list of EC2 instances:

```js
AWS.config.update({accessKeyId: 'id', secretAccessKey: 'secret', region: 'region'});
var ec2 = new AWS.EC2();
ec2.describeInstances({}, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
})
```

Added this script to an HTML file (with aws-sdk-2.409.0.js script). Everything works just fine if I open the file on my browser (BTW the response which is successful, has `Access-Control-Allow-Origin: *`). But when I use the same code in a FireFox extension I get:

```
NetworkingError: "Network Failure"
 handleRequest moz-extension://uuid/aws-sdk-2.409.0.js:155410 
 [300]</handleRequest/<@moz-extension://uuid/aws-sdk-2.409.0.js:155410:34
```

**Comment by srchase** [comment]
@akefirad 

Are there any notable differences in the headers being sent between the HTML and the Firefox Extension?

Which version of Firefox are you testing with?

**Comment by AllanFly120** [comment]
Hey @akefirad 
Have you added corresponding permissions for cross domain requests in the extension's manifest file?

**Comment by akefirad** [comment]
I'm sorry guys, it was permission entry in the manifest file.
