### ISSUE TITLE
AWS SDK step functions CORS error

### ISSUE THREAD

**Issue by nfchandu** [aws/aws-sdk-js#2560]
Hi,
I tried executing the state machine using AWS Javascript SDK but I am facing CORS issue using the SDK. Any help please?

**Comment by srchase** [comment]
Refer to this issue: https://github.com/aws/aws-sdk-js/issues/1334

The Step Functions Service does not support CORS.

There is a thread on their AWS Developer Forum if you'd like to add your feedback: [Request for CORS support](https://forums.aws.amazon.com/thread.jspa?messageID=770558)
