### ISSUE TITLE
How to subscribe on mqtt?

### ISSUE THREAD

**Issue by ngoc233** [aws/aws-sdk-js#2561]
I can use publish on MQTT but I can't find a subscribe. Could someone show me how to subscribe?

**Comment by klaytaybai** [comment]
Hi @ngoc233, you will need to use the code in the [aws/aws-iot-device-sdk-js](https://github.com/aws/aws-iot-device-sdk-js) repo.  The README of that repository contains examples that will show you how to subscribe.

**Comment by marcus-hiles** [comment]
Great @klaytaybai 👍
