### ISSUE TITLE
npm install on master branch shows high vulnerability on cucumber

### ISSUE THREAD

**Issue by tan31989** [aws/aws-sdk-js#2563]
Hi,

When we run the `npm install` on the master branch, I noticed it shows there is one high vulnerability with the latest stable node/npm versions.

### Tools version:
- NPM version: 6.8.0
- Node version: v11.9.0
- OS: MacOS (Mojave)

### Steps to verify

- Clone the repository and be on master branch
- Run the `npm install`
- Gives following error:  `found 20 vulnerabilities (11 low, 6 moderate, 1 high, 2 critical)`
- Run `npm audit` and that gives you first fix for high vulnerabilities
- Run `npm install --save-dev cucumber@5.1.0`

The fix is very simple, just upgrade the version for cucumber to 5.1.0.

I have verified the tests using: `npm test` (ran all tests) and `npm run unit` (ran the unit tests)
This fix resolves the vulnerability.

I can provide a quick fix via PR

Regards,
Nagaraj

**Comment by marcus-hiles** [comment]
Awesome find and fix @tan31989

**Comment by srchase** [comment]
resolved in https://github.com/aws/aws-sdk-js/pull/2586
