### ISSUE TITLE
Pre-signed URL gives error - signature does not match

### ISSUE THREAD

**Issue by iamzee** [aws/aws-sdk-js#2569]
const express = require ('express');
const bodyParser = require ('body-parser');

const AWS = require ('aws-sdk');
const s3 = new AWS.S3 ({
  accessKeyId: 'MY ACCESS ID',
  secretAccessKey: 'MY SECRET KEY',
  signatureVersion: 'v4',
  region: 'ap-south-1',
});

const app = express ();
app.use (bodyParser.json ());

app.get ('/generateUrl', (req, res) => {
  const signedUrlExpireSeconds = 60 * 60;
  const myBucket = 's3-test-19';
  const myKey = 'abc.pdf';

  const params = {
    Bucket: myBucket,
    Key: myKey,
    Expires: signedUrlExpireSeconds,
    ACL: 'bucket-owner-full-control',
    ContentType: 'application/pdf',
  };

  s3.getSignedUrl ('putObject', params, function (err, url) {
    if (err) {
      return res.status (400).json ({
        err,
        errorMessage: 'Unable to get url',
      });
    }

    res.status (200).json ({
      url,
    });
  });
});

app.listen (3000, () => {
  console.log ('Server started on port 3000');
});

**Comment by srchase** [comment]
Are you able to generate a valid URL directly (without Express being involved)?

**Comment by iamzee** [comment]
i dont know how to generate without express.
but with express i do get a presigned url.
when i open that url in the browser it shows signature does not match

**Comment by srchase** [comment]
Are you wanting to do a GET or a PUT?

Your code example has ```putObject```.  Is that correct?

**Comment by iamzee** [comment]
on client side, i will use PUT with pre signed url
