### ISSUE TITLE
truncated S3 read stream 

### ISSUE THREAD

**Issue by jfirebaugh** [aws/aws-sdk-js#257]
I have a test program that's creating a read stream from `getObject` and sometimes receiving incomplete results. That is, it receives an end event before the complete file has been read, and no error events.

Here is the test program: https://gist.github.com/jfirebaugh/3af5c9b2afd2583eb1ec

The expected size is 3723263 bytes. Typical output, when run as `./aws-sdk-truncation.js | grep -n1 wrong`:

```
13242-13: 1116220
13243:13: wrong size!
13244-18: 3723263
--
15573-3: 196980
15574:3: wrong size!
15575-23: 3723263
--
20279-20: 262640
20280:20: wrong size!
20281-9: 3723263
--
20749-10: 3151680
20750:10: wrong size!
20751-28: 3723263
--
21207-25: 459620
21208:25: wrong size!
21209-14: 3723263
--
22392-24: 2692060
22393:24: wrong size!
22394-27: 3723263
--
30223-5: 1904140
30224:5: wrong size!
30225-26: 3723263
```

The output indicates that no errors were emitted from the read stream.

This was run on a c3.8xlarge instance in us-east-1a using aws-sdk 2.0.0-rc13 on node v0.10.26.

The file in question is a CloudFront access log. I can't provide public access unfortunately, and so far I've been unable to reproduce the issue on similarly-sized files in other buckets. But it's easily reproducible on files in this bucket.

**Comment by dukeatcoding** [comment]
One year later and I still run into the same problems. I think the SDK should handle this issue, since it looks like S3.getObject does not make sense without a check for a complete Download.

**Comment by stsibel** [comment]
Some thing here. Whenever I am trying to download multiple images using s3.getObject, some of them randomly getting truncated/broken. Do I need to open new issue for this or there is a consistent way of doing things like this? (latest SDK, node 0.10.x, following s3GetObject example from documentation)

**Comment by simoncpu** [comment]
It's already March 2016 but I'm still encountering this problem. :-/

**Comment by chrisradek** [comment]
@simoncpu 
What version of node are you encountering this issue with?

**Comment by simoncpu** [comment]
@chrisradek I'm using AWS Lambda, which is running v0.10.36. I'm writing a Lambda function that is triggered as soon as a user uploads a PDF document to S3*. The function would then grab the PDF document for processing.

It looks like the read stream triggers a finish event even though the download from S3 is truncated (incomplete download? dunno). I wrote a similar Lambda function that is triggered from an API endpoint, but it works without problems.

My current work-around is to use http.get() to grab the PDF from S3.

*via HTML POST

**Comment by simoncpu** [comment]
Hurrrrh... I wrote a test script to show that the MD5 hashes don't match, but it seems that Lambda can download to S3 without truncating now:

```
'use strict';

var fs = require('fs');
var exec = require('child_process').exec;
var aws = require('aws-sdk');
var s3 = new aws.S3({ apiVersion: '2006-03-01' });

exports.handler = function(event, context) {
    var params = {
        Bucket: event.Records[0].s3.bucket.name,
        Key: event.Records[0].s3.object.key
    };

    var file_fn = '/tmp/test-' + Math.random().toString(36).slice(2) + '.pdf';
    var file = fs.createWriteStream(file_fn);
    var stream = s3.getObject(params).createReadStream().pipe(file);

    stream.on('finish', function() {
        exec('/usr/bin/md5sum ' + file_fn, function(err, stdout, stderr) {
            console.log('params', params);
            console.log('stdout', stdout);
            
            context.succeed('w00t!');
        });
    });
};

/* jshint node: true */
```

I'm confused why it didn't work last night. /me scratches head

**Comment by simoncpu** [comment]
Update: The S3 files are truncated again on AWS Lambda, but I can't replicate the problem using my sample code above.

**Comment by schoenwaldnils** [comment]
Same here

```
const S3 = require('aws-sdk/clients/s3');


const {
  aws: {
    region,
    s3: { bucket },
  },
} = require('../config.json');

const s3 = new S3({
  apiVersion: '2006-03-01',
  region,
});

function getKeyName(folder, filename) {
  return folder + '/' + filename;
}

module.exports = async (intl) => {
  const folder = 'timelineData';
  const filename = `timelineData-${intl}.json`;
  const keyName = getKeyName(folder, filename);

  const data = await s3.getObject({
    Bucket: bucket,
    Key: keyName,
  }, (err) => {
    if (err) {
      console.log(err);
    }
  }).promise();

  const result = data.Body.toString();

  return result;
};
```

**Comment by trivikr** [comment]
Locking this thread, as the issue was resolved in 2016 and there has not been any recent activity after it was closed. Please open a  [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
