### ISSUE TITLE
cognitoidentityserviceprovider listUsers does not return standard attributes

### ISSUE THREAD

**Issue by stayingcool** [aws/aws-sdk-js#2570]
**Query Standard Attributes**
I'm trying to query the standard attributes of the users in cognito user pool. 
```
  private params = {
    UserPoolId: this.cognitoUserPoolID,
    AttributesToGet: [
        'given_name',
      ],
  };
```
However, the following exception is thrown:
```
Error in getCognitoUsers:  InvalidParameterException: One or more requested attributes 
do not exist. at Request.extractError (http://localhost:4200/vendor.js:166383:27)
```

**Only email attribute is fetched successfully:**
I think the only attribute is being fetched by the API is email:
```
  private params = {
    UserPoolId: this.cognitoUserPoolID,
    AttributesToGet: [
         'email'
      ],
  };
```
![image](https://user-images.githubusercontent.com/31205483/54010479-059b4200-41c3-11e9-8cf9-2b1efaa2581a.png)

**Query with Empty Array (Should return all attributes)**
However, no attributes are returned:
```
  private params = {
    UserPoolId: this.cognitoUserPoolID,
    AttributesToGet: [],
  };
```
![image](https://user-images.githubusercontent.com/31205483/54010648-b86ba000-41c3-11e9-8a75-c4b35ded8f38.png)

**Code:**
I'm testing with code provided by **Preston** in **stackover flow** for this issue:
https://stackoverflow.com/questions/53597300/aws-cognito-services-apis-amplify-javascript-sdk-angular-app

**Observer Code**
```
public getCognitoUsers() {
        const getUsers$ = new Observable(observer => {
            Auth
                .currentCredentials()
                .then(user => {
                    // Constructor for the global config.
                    this.AWSconfig = new AWS.Config({
                        apiVersion: '2016-04-18',
                        credentials: user,
                        region: this.cognitoIdPoolRegion
                    });

                    const cognitoidentityserviceprovider = new CognitoIdentityServiceProvider(this.AWSconfig);
                    cognitoidentityserviceprovider.listUsers(this.params, function (err, userData) {
                        if (err) {
                            console.log('Error in getCognitoUsers: ', err);
                        } else {
                            observer.next(userData);
                        }
                    });

                });

        });
        return getUsers$;
    }
```

**Subscriber Code**
```
        this.getCognitoUsers()
            .subscribe(userData => {
                console.log('data in cognito component: ');
                console.log(userData);
            });
```

I feel like little lost as I'm not able to query specific standard attributes or even all attributes. Any feedback or suggestions would be very helpful.

**Comment by stayingcool** [comment]
Any feedback please?

**Comment by srchase** [comment]
@stayingcool 

Can you try this instead?

```
  private params = {
    UserPoolId: this.cognitoUserPoolID,
  };
```

```AttributesToGet``` should be removed entirely if you want all attributes returned.  Does that return given_name on the Users?

**Comment by stayingcool** [comment]
Thank you @srchase I removed **`AttributesToGet`** completely and I see all the attributes are returned. This is for good for now.
