### ISSUE TITLE
[Question] [Node] How assumeRole with temp credentials?

### ISSUE THREAD

**Issue by bodyslam** [aws/aws-sdk-js#2572]
Hello! In our current AWS setup we're required to switch roles before we can access our S3 buckets. In order to switch into the role we're required to pass in our MFA token. The following code works well but on a restart we're required to pass in the MFA code which is a PITA for development purposes.

The code below is my initial attempt with MFA
```
 public static switchToReadOnlyRole(TokenCode: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const sts: AWS.STS = new AWS.STS();
      const options: AssumeRoleRequest = {
        RoleArn: this.ROLE_ARN,
        RoleSessionName: `SwaggerS3ReadOnlySession${this.pid}`,
        SerialNumber: this.MFA_ARN,
        TokenCode,
      }

      sts.assumeRole(options, (err, data) => {
        if (err) {
          const errMsg: string = `AssumeRole failure! ${err.message}`;
          return reject(errMsg);
        } else {
          return resolve(AWS.config.update({
            accessKeyId: data.Credentials.AccessKeyId,
            secretAccessKey: data.Credentials.SecretAccessKey,
            sessionToken: data.Credentials.SessionToken
          }));
... // trailing closing brackets
```

I've had success generating temporary credentials via the aws-cli and storing the creds into environment vars but I have no idea how to inject these temp creds into the sdk's config object. I'd like to be able to use the temp creds (with a ttl of 12hrs) rather than ask for the MFA token every time.

Any ideas or pointers would be greatly appreciated.

**Comment by AllanFly120** [comment]
Hey @bodyslam 

> I've had success generating temporary credentials via the aws-cli and storing the creds into environment vars but I have no idea how to inject these temp creds into the sdk's config object

You can [`EnvironmentCredentials`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EnvironmentCredentials.html) explicitly to make use of the environment vars:

```javascript
const s3 = new AWS.S3({
    region: this.REGION,
    credentials: new AWS.EnvironmentCredentials('AWS')
//'AWS' is env prefix, if your env looks like 'AWS_ACCESS_KEY_ID'. 
});
//access your object
```
>but on a restart we're required to pass in the MFA code

You can automate this process by using a MFA token callback like below(if applicable). But you need to setup the role settings in shared credential files to use the MFA with [CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-mfa)

```javascript
const s3 = new AWS.S3({
    region: this.REGION,
    credentials: new AWS.SharedIniFileCredentials({
        profile: this.PROFILE_NAME
        tokenCodeFn: (mfaSerial, done) => {
            const token = fetchMFAToken();
            if (token) done(undefined, token);
            else done(new Error('cannot fetch token'));
        }
    });
});
//access your object
```

**Comment by bodyslam** [comment]
@AllanFly120 thank you so much, that tidbit really helped. I'm currently seeing 'Access Denied'.
I think the issue is that I'm generating the tokens as my own account; rather than as the 'readOnly' role.

I'm using the following bash script to setup the env vars:
```
awsTempToken()
{
  if [ ! -f ~/.aws/credentials ]; then
    echo "AWS credentials not configured!"
    return 1
  fi  

  AWS_TEMP_CREDS=`aws sts get-session-token --serial-number someARN  --token-code "$1" | jq -c '.Credentials'`
  export AWS_ACCESS_KEY_ID=`echo $AWS_TEMP_CREDS | jq -r '.AccessKeyId'`
  export AWS_SECRET_ACCESS_KEY=`echo $AWS_TEMP_CREDS | jq -r '.SecretAccessKey'`
  export AWS_SESSION_TOKEN=`echo $AWS_TEMP_CREDS | jq -r '.SessionToken'`
}
```

Would you know if it's possible to switch the role then get the creds as that new role? Something like
```
aws sts assume-role --role-arn someArnRole | aws sts get-session-token --serial-number someArnToken --token-code "$1"
```

**Comment by AllanFly120** [comment]
Hey @bodyslam 

Your approach looks reasonable to me. Can you elaborate how do you '`Autenticate` as myself', '`switch` to the readonly role' and '`get` the temp creds'?

**Comment by bodyslam** [comment]
Hey @AllanFly120 

So the issue I'd like to avoid right now is to provide a MFA token every time   'AWS.STS.assumeRole()'  is called. My thinking was that if save the tokens (generated via the aforementioned method) that I could just inject them for future use until the token TTL expires.  

So what I did next is my own bone-headed move; I tried to assumeRole with the store creds. I now realize that the creds were for the assumedRole so I didn't have to call assumeRole the 2nd time; just use the stored creds! 

Thanks again for your help!

**Comment by bodyslam** [comment]
Hey @AllanFly120 
One quick, related question I cant seem to fire off tokenCodeFn Lambda

```
  public static async getLocalCreds(): Promise<void> {
    console.log('--> start getLocal <---')
    AwsS3Tool.instance = new AWS.S3({
      region: 'us-east-2',
      credentials: new AWS.SharedIniFileCredentials({
        profile: 'readonly',
        tokenCodeFn: async (mfaSerial, cb) => {
          console.log('---> Inner fn call <---');
          cb(null, await AwsS3Tool.askForToken(mfaSerial));
        }
      })
    })
  }

  public static askForToken(serial?: string): Promise<string> {
    return new Promise((resolve) => {
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
      });

      rl.question(`Please enter your MFA token (${serial}):`, token => {
        rl.close();
        return resolve(token)
      })
    })
  }
```
The inner function never gets called; instead I'm seeing:

```
$ generate-swagger
$ node ./dist/index.js
--> start getLocal <---
2019-03-12T21:37:55.181Z [-] fatal [0] 'The following error occurred when starting the service: Missing credentials in config ["{ CredentialsError: Missing credentials in config\\n    at SharedIniFileCredentials.loadRoleProfile 
```

Any clues what I'm doing wrong?

**Comment by AllanFly120** [comment]
@bodyslam I don't think `tokenCodeFn` supports async functions, you should use callbacks in this case. Unfortunately the SDK needs to support very old node versions, so we use callbacks, but you can wrap the function with promise if you like. If you use this code in Lambda there's a chance that Lambda doesn't support the newer SDK versions, so you might need to bundle your SDK. 

The original PR provides an example for using the `tokenCodeFn`:#2126

**Comment by bodyslam** [comment]
@allanFly120 Thanks again for your help!

**Comment by bodyslam** [comment]
Ok the issue here is 2 fold: 

1. I needed to provide a callback to capture the error
```
  public static async getLocalCreds(profile: string = AwsS3Tool.DEFAULT_PROFILE): Promise<void> {
    const creds: SharedIniFileCredentials = await new AWS.SharedIniFileCredentials({
      tokenCodeFn: AwsS3Tool.tokenCodeFn,
      profile,
      disableAssumeRole: false,
      callback: (err) => {
        // This will provide useful error messages!!
        console.log(`SharedIniFileCreds Error: ${err}`)
      }
    });
    AWS.config.credentials = creds;
  }
```

2. I'm using typescript which the type definition wasn't updated; I've submitted a PR here
https://github.com/aws/aws-sdk-js/pull/2578

Hope this helps someone
