### ISSUE TITLE
Begins_With ConditionalExpression doesn't prevent duplicates

### ISSUE THREAD

**Issue by greg-peters** [aws/aws-sdk-js#2577]
When using the ConditionalExpression of "begins_with" and the "put" operation, duplicate items appear when there are a PK and SK(variable) define. 😮 

PK = user@email.com     <-------- HashKey
SK = account_(timestamp)   <----- RangeKey

There doesn't appear to be a way to prevent this composite key from inserting duplicates.

ConditionalExpression tried:
attribute_not_exists(PK) AND (NOT begins_with(SK,:acct))   .........where :acct is 'account_'

**Comment by srchase** [comment]
@greg-peters 

Can you provide a code example and which version of the SDK you're using?

**Comment by greg-peters** [comment]
The goal is to query all expired accounts in the future that have expired globally. It just seems like begins_with doesn't work on put operations.
```
const db = new AWS.DynamoDB.DocumentClient({apiVersion: '2012-08-10'});
...

    var expirationDate =  new Date();
    expirationDate.setDate(new Date().getDate() + 30); //30 day trial on new accounts
    var account = {
        PK: data.domain,
        SK: 'account_'+expirationDate.getTime(),
        plan_type: 'Trial'
    };

    db.put({
            TableName: process.env.TABLE_NAME,
            ConditionExpression: "attribute_not_exists(PK) AND (NOT begins_with(SK,'account_'))",
            Item: account
        },function(err,data) {
            callback(null,done(err,data));
        }); 
```

**Comment by srchase** [comment]
@greg-peters 

Have you tried the equivalent query with the AWS CLI?

**Comment by greg-peters** [comment]
I haven't tried this on the CLI, however, this still may be an issue. I redesigned my architecture to work around this perceived issue.
