### ISSUE TITLE
[typescript] 'Credentials' provide no match for the signature '(): Credentials'

### ISSUE THREAD

**Issue by bodyslam** [aws/aws-sdk-js#2579]
Hello! 

I'm trying to implement the CredentialProviderChain using the  [`API Example`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html#defaultProviders-property)

My typescript code:
```
  public setDefaultProviders(): void {
    const fileCreds: Credentials = new AWS.FileSystemCredentials('./creds.json');
    this.chain.providers.push(fileCreds); // <--- Error here
  }
```

Produces the following:

```
Argument of type 'Credentials' is not assignable to parameter of type 'provider & Credentials'.
  Type 'Credentials' is not assignable to type 'provider'.
    Type 'Credentials' provides no match for the signature '(): Credentials'.
```

I followed the typescript definition here: https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/credential_provider_chain.d.ts#L24

I got around this by redefining the [`line here`](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/credential_provider_chain.d.ts#L24)
```
type provider = Credentials;
```

Am I using CredentialsProviderChain incorrectly or should we update the definition?

**Comment by jordyjacob** [comment]
Has there been a resolution on this?

**Comment by hamid-r-shakibi** [comment]
I have the same problem. any solution?

**Comment by HippolyteJacque** [comment]
same problem here

**Comment by ajredniwja** [comment]
@HippolyteJacque for type safety I would recommend using the [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3) which has [first class typescript support](https://aws.amazon.com/blogs/developer/first-class-typescript-support-in-modular-aws-sdk-for-javascript/).

**Comment by HippolyteJacque** [comment]
> @HippolyteJacque for type safety I would recommend using the [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3) which has [first class typescript support](https://aws.amazon.com/blogs/developer/first-class-typescript-support-in-modular-aws-sdk-for-javascript/).

worked for me ! thanks @ajredniwja
