### ISSUE TITLE
TypeError Right-hand side of 'instanceof' is not an object 

### ISSUE THREAD

**Issue by cenjennifer** [aws/aws-sdk-js#2581]
I'm seeing this error logged in sentry (production only) and trying to figure out the cause of it. I believe it has to do with when the app tries to get an upload piece of content.  This error happens intermittently and usually outputs hundreds of these events to sentry.  Anyone have any idea what may be causing the issue?

Version:  2.419.0
```
TypeError: Object.computeSha256(aws-sdk.lib:util) error
Right-hand side of 'instanceof' is not an object
      if (body instanceof Stream) {}

```

**Comment by cenjennifer** [comment]
@srchase - Please let me know what additional info I can provide to get some guidance on this issue. Linked is the stack trace from where the error originated from: https://cl.ly/2154094641fb

This error only seems to happen on production and gets emitted intermediately (March 13 - 18 and March 27 - 31) was when these error got emitted the most.

**Comment by srchase** [comment]
@cenjennifer 

I apologize this got set to 'closing-soon' without a message asking for more details.

Can you share any additional details on what operation you're calling the SDK?  Have you gotten this error with any other version of the SDK?  Or just 2.419.0?

**Comment by chester-millisock-compass** [comment]
Pull Request for this fix: https://github.com/aws/aws-sdk-js/pull/2604

**Comment by cenjennifer** [comment]
@srchase - Thanks for responding back to me!

We `import AWS from 'aws-sdk'` and use `.S3`, `.CloudFront`,`.CredentialProviderChain` and `.SharedIniFileCredentials`

Also, it looks like the errors logged are all using `v2.419.0`

**Comment by chester-millisock-compass** [comment]
@srchase Any thoughts on my pull request? It is a one-line change that will fix this issue.

**Comment by chester-millisock-compass** [comment]
Here is a more robust pull request to fix this error:
https://github.com/aws/aws-sdk-js/pull/2620

**Comment by ajredniwja** [comment]
Closing this issue since it was resolved.
