### ISSUE TITLE
Issue uploading PDF with chinese text to s3

### ISSUE THREAD

**Issue by sawaikar-gauri** [aws/aws-sdk-js#2582]
I am trying to upload pdf file to s3 which contains Chinese text. Below is the implementation:

Node.js 8
Lambda Implementation

1. Fetch html of the text by using fetchUrl library
2. Convert html by using html-pdf library . Either use .toStream()  ( Also tried .toFile() to write to  /tmp file on Lambda server)
3. Upload to s3 using stream (Also tried upload using the tmp file)

The resulting file on s3 shows blank for the Chinese / Korean text. If i try to save the file locally , the PDF is proper.

One solution on stackoverflow was to use upload_file (python)  , I do not find JavaScript equivalent for this

Here is my code

**Comment by srchase** [comment]
@sawaikar-gauri 

Your last message did not include any code.  Did you mean to include that?

**Comment by sawaikar-gauri** [comment]
@srchase  Sorry, missed to include the link
https://github.com/sawaikar-gauri/html-to-pdf-serverless

Also, this was the solution proposed to use :
https://stackoverflow.com/questions/55141434/issue-writing-non-ascii-content-to-s3?noredirect=1#comment97090136_55141434

**Comment by srchase** [comment]
@sawaikar-gauri 

Is there a specific operation of the SDK that you think is not working correctly?

**Comment by sawaikar-gauri** [comment]
No, Can i get an example of s3 upload  with string containing Chinese or Korean text ?

Or Can we get upload_file python equivalent in the javascript sdk ? Wherein i can directly upload a local file to s3?

My query is regarding the encoding, and how to fix it.

Thanks for response.

**Comment by srchase** [comment]
In addition to ```putObject```, the SDK also has an ```upload``` operation: [S3 upload](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property).

Either of these will work:

```
const AWS = require('aws-sdk')
const s3 = new AWS.S3();

const params = {
  Body: '안녕',
  Bucket: 'myBucket',
  Key: 'myKey'  
}

s3.putObject(params, (err,data) => { 
  console.log(err,data) 
})

s3.upload(params, (err,data) => { 
  console.log(err,data) 
})
```

Are you certain that the issue is the SDK and not the upstream functions preparing the body that you're trying to send to S3?

**Comment by sawaikar-gauri** [comment]
M not sure that the issue is in the SDK.

The function that i am using for upload works fine for local file and not s3 . So I am not sure, what is going wrong

The upload i am using is with streams which fails

I will try the example

**Comment by srchase** [comment]
@sawaikar-gauri 

Ok.  Followup if there is something not working or documented properly with the SDK.

**Comment by sawaikar-gauri** [comment]
@srchase I tried uploading a local PDF file to s3 and it supports chinese text.
There seems to be some problem with pdf generation part on AWS lambda which is going different when i run on local vs when i execute on Lambda

Thanks for guidance. Sorry for the false alarm.
