### ISSUE TITLE
DynamoDB query take a long time irregularities, Help!!!

### ISSUE THREAD

**Issue by cocobiz** [aws/aws-sdk-js#2585]
Our business is very simple, just make a normal query from a dynamoDB table, like
```javascript
const tick = Date.now();
DB.docClient.query(pms, (err, data) => {
    const duration = Date.now() - tick;
    log.info(duration);
    // some businesses
});
```
**we found that it will take about 120s or 200s sometimes from our log**
Yes, it's always the above value when this issue occurred.

The endpoint configuration like below:
```javascript
AWS.config.update({
    endpoint: config.dynamoEndpoint,
    region: config.dynamoRegion,
    accessKeyId: config.dynamoAccessKeyId,
    secretAccessKey: config.dynamoSecretAccessKey,
    maxRetries: 2,
    httpOptions: {
        agent: new https.Agent({
            maxSockets: Infinity,
            keepAlive: true
        })
    }
});
```

Can someone give us some tips?
Thanks a lot!

**Comment by srchase** [comment]
@cocobiz 

Are you having issues with every query?  Or is it one specific query that is long-running?

**Comment by klaytaybai** [comment]
@cocobiz, are these long running queries eventually succeeding, or do they result in an error?

**Comment by cocobiz** [comment]
@srchase @klaytaybai Thanks for your replay.
These long queries have no issue and they are very simple (just query by index or primary key), because we can get the response immediately when retry the same query in local env.

Theses cases occurred in our Production Environment, and we can not debug it because these kind of problems are not reproducible.

There is a suspicion that it is the Production Environment which has a large concurrency, we have done some researches:
- increase the value of  UV_THREADPOOL_SIZE, but seem to has no effect.
- we guess if the event loop was blocked when long query occurred? but we found that there are lots of process logs when the long query occurred, in other words the event loop was not blocked by any other operations when the long query occurred.
- and we also did some profiling for the app, but get nothing useful info.

Finally, we have no idea about this issue.

**Comment by AllanFly120** [comment]
Hey @cocobiz 

What is this code running on? Instance or serverless service like Lambda? It's normal that when Node process is under high pressure and the bandwidth is limited, the callbacks will queue up in the event loop.

**Comment by AllanFly120** [comment]
Hey @cocobiz 

I suspected event loop blocking at first, but it seems like you have eliminated the suspect. Maybe you can provide the request id to the DynamoDB service team to see what happened on their end?

**Comment by carlnordenfelt** [comment]
It could be that you are being throttled and what you are seeing is the effect of the built-in retries the sdk does. This issue at least seems similar: https://github.com/aws/aws-sdk-js/issues/402
Note that you can get throttled without hitting your table limits if you have a hot partition.

If this is the cause the reason why I saw 25 second delays and you see ~120-200ms seconds delay is that you configure maxRetries: maxRetries: 2,

**Comment by cocobiz** [comment]
> Hey @cocobiz
> 
> I suspected event loop blocking at first, but it seems like you have eliminated the suspect. Maybe you can provide the request id to the DynamoDB service team to see what happened on their end?

Hey @AllanFly120 

thanks for your replay, but where i can get the request-id you mentioned, just like below:

```javascript
DB.docClient.query(pms, (err, data) => {
        //  get request-id here?
});
```

**Comment by cocobiz** [comment]
> It could be that you are being throttled and what you are seeing is the effect of the built-in retries the sdk does. This issue at least seems similar: #402
> Note that you can get throttled without hitting your table limits if you have a hot partition.
> 
> If this is the cause the reason why I saw 25 second delays and you see ~120-200ms seconds delay is that you configure maxRetries: maxRetries: 2,

hi @carlnordenfelt thanks for your reply
what did you mean "hot partition"? is this a dynamodb mechanism?
and how to calculate 25s by you mentioned built-in retries?
thank you again :)

**Comment by carlnordenfelt** [comment]
@cocobiz yes, Dynamo will split your data across partitions based on the PK.
The items are spread across these partitions but each partition does not get the full amount of provisioned r/w, the capacity is split across the partitions.

A simple case:
You have a table with 25 reads/s. The table has 5 internal partitions.
Each partition will have 5 reads/s. If a specific partition is hit more frequently than other those 5r/s may get exhausted and you will be throttled even though you are way below you total 25 r/s. 
You can see this in the metrics, if you are getting throttled but are below the threshold.

If this is the case, you can try setting the capacity to PAY_PER_REQUEST and see if that resolves the problem. In that case you can crunch some cost numbers and decide if that's a better setup or if you need to rethink the table design and continue with provisioned capacity.

As for the 25 seconds, it's the total exponential backoff for 10 failed retries in the javascript sdk using the default values. I don't have the exact number but the last wait time is 12.5 seconds. Just recursively divide by 2 10 times and you get the wait time for each retry 8unless they've updated the logic behind this).

All the above is based on . a hunch so I might be way off in your case, there could be something else wrong entirely :)

**Comment by AllanFly120** [comment]
Hey @cocobiz 
Can you get the request id by:
```javascript
const request = DB.docClient.query(pms);
request.send((err, data) => {
    console.log('request id: ', request.response.requestId);
})
```

**Comment by ajredniwja** [comment]
@cocobiz,

Is this still a persisting issue for you?

I will go ahead and close the issue due to inactivity, please reach out if it is still an issue for you or if you have additional questions.
