### ISSUE TITLE
[React Native] Consider refactoring to remove the need for a cycle

### ISSUE THREAD

**Issue by Bruno-Furtado** [aws/aws-sdk-js#2590]
## Environment

* React Native 0.57.5
* aws-sdk 2.425.0

## Description

I'm using the Amazon SDK in a React Native app.
When compiling the app in debug mode, the following warning is being displayed:

```
> Require cycle: node_modules/aws-sdk/lib/react-native-loader.js -> node_modules/aws-sdk/lib/credentials/temporary_credentials.js -> node_modules/aws-sdk/clients/sts.js -> node_modules/aws-sdk/lib/react-native-loader.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

```
> Require cycle: node_modules/aws-sdk/lib/react-native-loader.js -> node_modules/aws-sdk/lib/credentials/cognito_identity_credentials.js -> node_modules/aws-sdk/clients/cognitoidentity.js -> node_modules/aws-sdk/lib/react-native-loader.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

It's not a failure, it's just a warning, but it would be cool to fix.

## Solution

Refactoring to remove the need for a cycle.

**Comment by srchase** [comment]
Marking this as a feature-request for the time being.  It's an improvement, but not necessarily a bug.

**Comment by 10centmedialabs** [comment]
Still getting this warning. Any improvements on this?

**Comment by andreialecu** [comment]
@srchase require cycles can result in bugs that are almost impossible to debug. 

A similar require cycle in `aws-amplify` is responsible for various issues reported in the repository that were never resolved. See https://github.com/aws-amplify/amplify-js/pull/5372 and the issues linked.

It would be pretty important to get rid of all require cycles.

**Comment by billnbell** [comment]
Please work on removing require cycles! This is a professional API, I expect it!

**Comment by nayan27** [comment]
aws-sdk-js is an amazing library. We need it to be maintained :/
Would it be possible to get rid of the Require cycles warning please

**Comment by kellertk** [comment]
Greetings, this issue is very old so I will be closing it. You should migrate to AWS SDK for JavaScript v3, which has been substantially refactored.
