### ISSUE TITLE
API Gateway: Unknown error with 410 code

### ISSUE THREAD

**Issue by denismaster** [aws/aws-sdk-js#2591]
### Environment
Nodejs 8.x
aws-sdk 2.425.0

### Description
I'm using the API Gateway SDK with the Serverless in Lambda to push updates from DynamoDB to clients using websockets.
Today I found a bunch of errors in the CloudWatch:
![image](https://user-images.githubusercontent.com/4387098/54763677-756bec80-4c07-11e9-93b5-b1be4dc611bb.png)
And websockets are not working.

**Comment by srchase** [comment]
@denismaster 

Was there a change that coincided with this error starting to happen?

**Comment by denismaster** [comment]
@srchase no, I'd only changed the frontend code

**Comment by AllanFly120** [comment]
@denismaster SDK will use `UnknowError` when exception code is not provided. The SDK correctly parsed the error response. Maybe you can reach out the APIGateway team via the [forum](https://forums.aws.amazon.com/forum.jspa?forumID=199) for more information about 410 exception.

**Comment by denismaster** [comment]
@AllanFly120 thanks, I found that this issue was related to stale ws connections. It works well. Thanks for help!

**Comment by orengriffin** [comment]
@denismaster how did you solve this?
same is happenning to me

**Comment by purefan** [comment]
@denismaster Care to share how you fixed it?

**Comment by denismaster** [comment]
@orengriffin @purefan I found documentation section about 410 error. It told me that the issue was related to stale connections. To avoid this error, you need to catch 410 error and remove the stale connection from your list.

**Comment by pimfeltkamp** [comment]
Unfortunately API Gateway can also return a 410 when the connection is still active. 410 error is not always a stale connection...
