### ISSUE TITLE
InvalidSignatureException while calling Lambda functions

### ISSUE THREAD

**Issue by mlabouardyfox** [aws/aws-sdk-js#2598]
Hello,

**ISSUE**

we are receiving an error:InvalidSignatureException when invoking our Lambda function. The Lambda function is called from a Docker container running on an EC2 instance. (Some calls are successful, and after few minutes we receive the invalidSignature error)

`Error: native lambda error:InvalidSignatureException: Signature expired: 20190327T172525Z is now earlier than 20190327T172525Z (20190327T173025Z - 5 min.)`

**ATTEMPTS TO FIX**

* I tried setting `AWS.config.correctClockSkew = true;` but this does not seem to fix the issue
* I tried setting `new Lambda({ correctClockSkew: true })` in addition to item 1 above, and it still fails.
* I tried to sync the host machine based on the official documentation (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html), but still the same error.
* I tried to deploy the container to another AWS region, but still no success
* I even tried to run the service locally without docker, and still we get the error.

**Comment by mlabouardyfox** [comment]
We even upgraded to latest version (2.429.0) and tried an older version (2.389.0), but still the same issue raised

**Comment by srchase** [comment]
@mlabouardyfox 

Can you provide an example of your code?

**Comment by mlabouardyfox** [comment]
```
const AWS = require('aws-sdk')

AWS.config.logger = console
AWS.config.correctClockSkew = true

const Lambdas = {
    de: new AWS.Lambda({region: 'eu-central-1', correctClockSkew: true}),
    fr: new AWS.Lambda({region: 'eu-west-3', correctClockSkew: true})
}


const lambda = Lambdas[localization] || Lambdas.de  // default frankfurt
const functionName = process.env.ENVIRONMENT ? `${name}:${process.env.ENVIRONMENT}` : name // versioned with env
const params = {
    FunctionName: functionName,
    InvocationType: 'RequestResponse',
    Payload: JSON.stringify(payload) // stringify all
}

lambda.invoke(params, (error, result) => {

})
```

**Comment by AllanFly120** [comment]
Can you verify whether the clock offset stored in SDK is correct? Here is the documentation: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#systemClockOffset-property. SDK parses the server's time from the response and detect if there's a time difference to local time, and save the offset to service config. You can compare local time, service time and local clock offset side-by-side:

```javascript
const request = lambda.invoke(params);
const printTime = (response) => {
    cosnt headers = response.httpResponse.headers;
    const serviceTime = headers.date || headers.Date;
    console.log(`local time: ${Date.now()}, service time: ${serviceTime}`);
    //you can also access the request date header hear: request.httpRequest.headers['Date']
    //or lambda.config.systemClockOffset which is the time difference between local and remote detected by SDK
}
request.on('validateResponse', printTime);
request.send((err, result) => {...})
```

**Comment by nicolas-apertur** [comment]
Hello @AllanFly120,

I am working with @mlabouardyfox. I have tested your script, and it appears that the validation event is fired very lately.

From my computer, if I am calling the lambda only once, it takes 4 second delay to fire the `validateResponse` event.

If I try call the same lambda multiple times, the delay increases very quickly. If I call 1000 times the lambda, the delay becomes bigger than 5 minutes, and I got the `InvalidSignatureException: Signature expired` error.

It seems that the signature expiration is compared with the lambda calling time, not the validation event time?

Do you have an idea why the `validateResponse` takes so much time to succeed?

Tested on aws-sdk 2.432.0.

Regards,

**Comment by AllanFly120** [comment]
Hey @nicolas-apertur 

The 'validateResponse' happens when SDK gets the response and before executing potential 'retry'. Usually the SDK reget response very slow because of (1)retry or (2)slow connection. In this case even 'validateResponse' takes a long time, I think it might be in a very slow connection(or the lambda function itself takes a long time to execute). 

Then the other issues you are seeing make sense: when you make concurrent request, the callbacks are queued in the event loop before being sent out, so you see longer delay. And once the request waits in the queue for longer than 5 mins, the request can expire.

If you are using VPN can you try calling without it to see whether this mitigate the issue. You can also try using keep-alive agent setting. If your function execution time is actually long(seconds), can you try calling a simpler dummy function to see if the issue still happens?

**Comment by ajredniwja** [comment]
Is this still an issue for you @mlabouardyfox, will close this issue for now because of inactivity, please reach out if you have questions.
