### ISSUE TITLE
Proper working code for PreSigned URL

### ISSUE THREAD

**Issue by ctrljs** [aws/aws-sdk-js#2601]
Can Someone please provide proper working code to get presigned url for the  files in my s3 bucket.  I am getting error when i browse to the url i get in callback function of getPresignedURL.

<?xml version="1.0" encoding="ISO-8859-1"?>
<Error>
<Code>AccessDenied</Code>
<Message>There were headers present in the request which were not signed</Message>
<HeadersNotSigned>host</HeadersNotSigned>
<RequestId>E4DDBF5D48703DA2</RequestId>
<HostId>Bt/GNDdYAt2Bgv9u94rHRGLoo4BMie0gj/QNMjITmgEO6bUDA+8mihs6nC6pcZyQiCJ0TpfG8G4=</HostId>
</Error>
What could be the reason , THE IAM user has been given full access to s3. and also the bucket policy ,CORS has been set to *.

**Comment by srchase** [comment]
@ctrljs,

How are you using the presigned URL?  With a browser?  Curl?

**Comment by ctrljs** [comment]
@srchase , thank you for you reply , I got it working, I was doing it on javascript code on server side, in a graphql resolver function.
