### ISSUE TITLE
sendUsersMessages not defined on the Pinpoint service in 2.432.0

### ISSUE THREAD

**Issue by clowestab** [aws/aws-sdk-js#2602]
This is as simple as it sounds but has lead to a lot of banging of heads against walls / wasted time.

`sendUsersMessages` is not defined in the latest version of the SDK (2.432.0) on the Pinpoint service. I don't know if this is a bug or a deprecated method issue. I assume the former because there are still references to it within the codebase. The documentation still implies that this is an available method.

Rolling back (arbitrarily) to 2.420.0 fixed the issue.

**Comment by srchase** [comment]
@clowestab,

```
const AWS = require('aws-sdk')

const pinpoint = new AWS.Pinpoint({region: 'us-west-2'});

pinpoint.sendUsersMessages({}, (err,data) => {
  console.log(err,data)
})
```

Using this example returns the expected validation issues (due to the empty params getting passed to ```sendUsersMessages``` missing the required ApplicationId and SendUsersMessageRequest).

I get the same behavior using 2.420 and 2.432.0. ```sendUsersMessages``` is not deprecated.

Did you do a fresh ```npm install```?

**Comment by clowestab** [comment]
A fresh install @2.432.0 does in fact work. As does the latest version 2.435.0

Is there any obviously explainable reason what could have caused `sendUsersMessages` to be undefined yet other functions were working as expected. I am completely bemused and am curious for an explanation simply out of intrigue.

**Comment by srchase** [comment]
@clowestab,

Unfortunately, I don't have any strong theories.  Seems specific to your environment.  Anything that could've gone amiss in your environment?  Any chance an older version of the SDK was used instead?
