### ISSUE TITLE
Increased control over customUserAgent

### ISSUE THREAD

**Issue by awschristou** [aws/aws-sdk-js#2607]
In the v2 SDK, it looks like custom user agents are ultimately appended to the output of `util.userAgent()`.

I'd like to be able to prepend my customUserAgent to any internal user agent text.

**Comment by AllanFly120** [comment]
Hey @awschristou 

You can always override the useragent in the in the request header. You can access headers like below:

```javascript
const request = s3.putObject(params);
request.httpRequest.headers['User-Agent'] = costomAgent;
//in browsers the header should be 'X-Amz-User-Agent'
```
