### ISSUE TITLE
S3 copyObject doesn't seem to work in 2.0.0-rc13

### ISSUE THREAD

**Issue by dylanlingelbach** [aws/aws-sdk-js#261]
This was on Node.js 0.10.24.

When I try to use the copyObject api I get a NoSuchBucket error.  If I use a getObject followed by a putObject with the same parameters the call succeeds.

If I use s3cmd from the command line to issue the command it succeeds.

The name of the bucket I was trying to write to was 'fair-pricing'.

Let me know if you need any more information

**Comment by rfink** [comment]
I'm actually having this same problem, using a "copyObject" immediately following a "putObject".  Please advise.

**Comment by canvas-manik** [comment]
yupp, the conversation was helpful. Thanks!!!

**Comment by appu24** [comment]
May I know if we have a way to get back the URL of the copied object from the destination bucket?
(example - response.Location that we get in 'upload()')

Thanks in advance :)

**Comment by kaushikwavhal** [comment]
Introducing a new parameters called "sourceBucket" and removing the bucket-name prefix in the CopySource path would have been more developer friendly.
It took me a long time to reach to this issue as i had assumed that both source and destination paths would have identical conventions which is generally the case.

**Comment by imdadul** [comment]
```
cost bucket= 'mybucket';
const url = s3.getSignedUrl('copyObject', {
        Bucket: bucket,
        CopySource:bucket+'/'+oldFileName,
        Key: newName,
        Expires: signedUrlExpireSeconds
    });

```
In front end using this.
`$http.put(url)` -- Gives 200 but nothing in response.

When trying to get the file later, giving me a corrupted file.

Any idea why?

**Comment by damianobarbati** [comment]
@imdadul did you solve this? I get the same, an empty 200 response and no file copied.

```
const source = `/${s3Config.bucket}/${key}`;
const destination = '/test.docx';

try {
    const result = await s3Client.copyObject({
        Bucket: s3Config.bucket,
        CopySource: source,
        Key: destination,
    });
    console.log(result.response.data); //null
}
catch (error) {
    console.error(error.message);
}
```

**Comment by damianobarbati** [comment]
You have to:
```
const result = await s3Client.copyObject({
    Bucket: s3Config.bucket,
    CopySource: source,
    Key: destination,
}).promise();
```
