### ISSUE TITLE
fetching getObject createReadStream() using callback

### ISSUE THREAD

**Issue by kvv002** [aws/aws-sdk-js#2612]
Hi,
Is there a way to fetch stream data for getObject using callback, similar to the way we normally fetch data in responseBody using callback?
This is the sample code for fetching data without stream
```
var AWS = require('aws-sdk')

AWS.config.update(
  {
    accessKeyId: "xyz"
    secretAccessKey: "abc"
  }
);
// Create an S3 client
var s3 = new AWS.S3();
s3.getObject(params, function (err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else {
    console.log(data)
  }
})
```
This is for createReadStream
`s3.getObject(params).createReadStream().pipe(new Base64Encode());`

Is there any possibility to have createReadStream data in a callback?

**Comment by srchase** [comment]
@kvv002,

Is this what you're looking to achieve?

```
var readable = s3.getObject(params).createReadStream();

readable.on('data', function(chunk) {
  console.log(chunk);
});
```

As noted in the documentation, your application should handle stream failures.
