### ISSUE TITLE
StepFunction describeExection with promise

### ISSUE THREAD

**Issue by mohammedzamakhan** [aws/aws-sdk-js#2613]
When I save the promise and use setInterval, I always get the same response

![before](https://user-images.githubusercontent.com/2327532/55646904-fbf50200-57a1-11e9-8e43-c8bcd0d5e2fe.png)

But when I create promise inside setInterval, it works as intended, and returns a new status of the step functions

![after](https://user-images.githubusercontent.com/2327532/55646951-0f07d200-57a2-11e9-9b4e-0c50f6067af4.png)

**Comment by srchase** [comment]
@mohammedzamakhan,

Are you wanting to use ```setInterval``` or ```setTimeout```?

Your question referred to ```setTimeout```, but the attached code uses ```setInterval```.

**Comment by mohammedzamakhan** [comment]
setInterval, updated the description

**Comment by srchase** [comment]
```setInterval``` is intended to repeat the execution.

Can you add additional details of what you are trying to achieve?  Is the SDK not functioning as you would expect?

**Comment by AllanFly120** [comment]
@mohammedzamakhan 

The 2nd example you provided is the correct way to acheive your intend. When you construct a promise, you can understand it as the request has been sent out immediately but the response yet to come back. If you want to send the request repeatedly, you need to construct the promise within the `setInterval` callback.

**Comment by mohammedzamakhan** [comment]
@AllanFly120 promises are supposed to be lazy, they should only be sent out after they are subscribed using `.then`.

**Comment by AllanFly120** [comment]
@mohammedzamakhan 

Apology for the preview explanation. The reason for the issue is that one `request` can only be sent once. SDK uses stage machine internally, after the request lifecycle has completed, you cannot send it again.
