### ISSUE TITLE
multiple ec2 instances launched with promise()

### ISSUE THREAD

**Issue by dcarrion87** [aws/aws-sdk-js#2614]
Always getting 2 instead of 1 instances launched using async `await ec2.runinstances({..}).promise()`

If I remove the await and promise() only 1 instance is launched as expected.

Node: 8.10.0
aws-sdk: 2.401.0

**Comment by dcarrion87** [comment]
Able to workaround with async/wait by using util promisify.

Would be good if it worked with .promisify().

```
const {promisify} = require('util');
const AWS = require('aws-sdk');

const ec2 = new AWS.EC2();
const ec2RunInstancesAsync = promisify(ec2.runInstances).bind(ec2);

let result = await ec2RunInstancesAsync(runParams);
console.log(JSON.stringify(result));
```

**Comment by srchase** [comment]
@dcarrion87,

Can you give an example of how you used the SDK's ```.promise()``` with ```await```?

**Comment by dcarrion87** [comment]
`const AWS = require('aws-sdk');
const ec2 = new AWS.EC2();
var params = {
    LaunchTemplate: {
        LaunchTemplateId: 'lt-XXXXXXXXXXXX',
        Version: '1'
    },
    MaxCount: 1,
    MinCount: 1,
    SubnetId: "subnet-XXXXXXXXXXXXXX",
    TagSpecifications: [{
        ResourceType: "instance",
        Tags: [{
            Key: 'Name',
            Value: `XXXXXXXXXXX`
        }]
    }],
}
await ec2.runInstances(params).promise()`

**Comment by srchase** [comment]
@dcarrion87 

I wasn't able to reproduce this behavior.  Are there any other details of your setup that might help with reliable steps to reproduce?
