### ISSUE TITLE
Support for TimingAllowOrigin header

### ISSUE THREAD

**Issue by abhinavsingi** [aws/aws-sdk-js#2616]
How to set `Timing-Allow-Origin: *` in header?

Need to set it for [resource timing ](https://developers.google.com/web/fundamentals/performance/navigation-and-resource-timing/#the_gotchas)

[mdn link ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Timing-Allow-Origin)

**Comment by srchase** [comment]
@abhinavsingi 

Refer to the [Add a custom HTTP header to a request](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#build-event) documentation.

It shows the following example for setting a custom header:
```
var req = s3.putObject(params);
req.on('build', function() {
  req.httpRequest.headers['Custom-Header'] = 'value';
});
req.send(function(err, data) { ... });
```

**Comment by abhinavsingi** [comment]
I'm not using `putObject` API, using `upload` api:

`const client = AWS.S3(...); client.upload({..., TimingAllowOrigin: '*'})`

But this is not working as I see it's not an allowed header in `aws-sdk/clients/s3.d.ts` or maybe I'm understanding it incorrectly.

**Comment by srchase** [comment]
@abhinavsingi 

For S3, the request headers must be one of the [Common Request Headers](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html), or one of the [Request Headers for PUT](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html).

There is a request for S3 to add support for ```Timing-Allow-Origin```.  You can join that discussion on this thread of the [AWS Developer Forum](https://forums.aws.amazon.com/thread.jspa?messageID=515840).

**Comment by abhinavsingi** [comment]
I had gone through that link, but it seems there's not much update on it. 
Do you think you could give an estimate on making this available? Or will it not be added

**Comment by srchase** [comment]
S3 would need to provide any update on prioritization of this feature request for the service.

As this isn't a limitation of the SDK itself, I'll opt to close this issue.  Any further followup should be directed to S3 directly via the AWS Developer Forum.
