### ISSUE TITLE
MessageStructure: 'json' is buggy?

### ISSUE THREAD

**Issue by aichholzer** [aws/aws-sdk-js#262]
I am trying to send a JSON message to an iOS client. When I send the message as plain text it work just fine. However, setting the "MessageStructure: 'json'" and then the "Message" as a JSON object, as detailed in the AWS document I get a funny error: "InvalidParameterType: Expected params.Message to be a string"

If you want to send different messages for each transport protocol, set the value of the MessageStructure parameter to json and use a JSON object for the Message parameter. See the Examples section for the format of the JSON object. (From: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/frames.html)

I am sending:

```
params = {
  MessageStructure: 'json',
  Message: { 
      default: 'A notification from us!',
      APNS_SANDBOX: {aps:{alert:"Hello and have a good day."}}
   },
   TargetArn: '...'
};
```

(I have also tried sending the APNS_SANDBOX as an escaped string, same issue...)
To me this seems like a major bug.

Any ideas?

**Comment by ei02028** [comment]
Guys,

I'm trying my luck in this forum. I'm having an issue with Amazon SNS when I try to send a push notification to several devices at the same time.

I've explained my issue here: https://forums.aws.amazon.com/thread.jspa?threadID=171981

Any help?

**Comment by typemismatch** [comment]
@aichholzer wow, thanks! - the double stringify is what made it work, it's stupid but it's perfect, thanks!

**Comment by aichholzer** [comment]
@typemismatch anytime!

**Comment by robolivable** [comment]
This issue is still just as relevant as it was when it was posted. @lsegal There's still nothing in the documentation about JSON encoded strings. Your comment really helped me out.

**Comment by aichholzer** [comment]
Yes, I am not sure where the AWS team's priorities are.

**Comment by contractorwolf** [comment]
yes this is definitely weird behavior, it doesnt make sense to set it to json if you are then forced to pass a string.

**Comment by igor-yamshchykov** [comment]
Thanks a lot man! Wasted around two hours with that !

**Comment by DavidSunny** [comment]
@aichholzer Thank you!

**Comment by gsarfati** [comment]
@aichholzer  Thank you!

**Comment by aichholzer** [comment]
:+1:

**Comment by ir-fuel** [comment]
Same issue here. Serious issues with the documentation and would never have figured this json -> string stuff out myself.
Thanks, and please, someone fix those docs :/

**Comment by jnimis** [comment]
Thanks you so much for this answer!

**Comment by mdw19873** [comment]
@aichholzer You're still saving people hours and hours of headaches! Thanks!

**Comment by surf2day** [comment]
Thanks for the answer, never would have solved it without it!  Cheers.

**Comment by USSliberty** [comment]
That's incredible that still in 2017 we have to dig in such old issues. Why not mention this example on the docs?

Anyway thank you @aichholzer 👍

**Comment by malithjkmt** [comment]
For **GCM** the structure is like below, which is taken from [this](https://gist.github.com/tmarshall/6149ed2475f964cda3f5) gist 


```
    let payload = {
            GCM: {
                data: {
                    message:'Hello world'
                }
            }
    };
    // first have to stringify the inner GCM object...
    payload.GCM = JSON.stringify(payload.GCM);

    // then have to stringify the entire message payload
    payload = JSON.stringify(payload);

    var params = {
        MessageStructure: 'json',
        Message: payload,
        Subject: 'TEST SUBJECT',
        TargetArn: 'TargetArn'
    };
```

**Comment by builtbyproxy** [comment]
My GCM implementation is: 

```
const params = {
        Message: JSON.stringify({
            default: "This is the message for you...",
            GCM: JSON.stringify({ 
                data: {
                    message: "Hello World",
                }
            })
        }),
        MessageStructure: "json",
        TargetArn: 'arn:aws:...', // This is the endpointARN
    };

    const sns = new AWS.SNS();
    sns.publish(params as any, function(err, data) {
        if(err) {
            console.log('error occured: ', err, err.stack); 
        } else {
            console.log('Success: ', data);
        }
    });
```
