### ISSUE TITLE
backup.describeBackupVault fails with permission error if backup vault does not exist.

### ISSUE THREAD

**Issue by justengland** [aws/aws-sdk-js#2625]
When running a basic ___ command the command fails with an AccessDenied, it seems like this should fail with a different exception. Looks like it may be an API problem, but I am not sure. 

`var backup = new AWS.Backup();

var params = {
    BackupVaultName: 'fakename'
};
backup.describeBackupVault(params, function(err, data) {
    if (err) console.log(err, err.stack); // If the vault does not exsist it fails with a 403 exception
    else     console.log(data);           // if the name does exsist then it succeeds.
});`

`AccessDeniedException: Insufficient privileges to perform this action.`

Also the backup.describeBackupVault.promise function fails with this.makeRequest is not a function exception. I am unsure if they are related issues.

**Comment by srchase** [comment]
@justengland,

I wasn't able to reproduce the ```promise``` issue.

Can you provide an example of your code?

What exception are you expecting instead of ```AcessDenied```?

**Comment by justengland** [comment]
The promise issue appears to an issue in the way was due to some async await issues on my side. 

I would expect requesting a resource would yield a 404 response from the API and that would yield some sort of not found exception. Throwing a security exception, makes it seem like a security-related issue.

**Comment by srchase** [comment]
The ```AccessDeniedException``` is returned by the Backup Service.

The Backup Service Team would be best suited to answer why a 403 is being returned instead of a 404.  You can raise the issue on their [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=324).
