### ISSUE TITLE
CostExplorer constructor not available

### ISSUE THREAD

**Issue by jtomjack93** [aws/aws-sdk-js#2626]
After importing the aws-sdk in my React application, I receive the following error when trying to create a CostExplorer object: Unhandled Rejection (TypeError): aws_sdk__WEBPACK_IMPORTED_MODULE_8__.CostExplorer is not a constructor
After logging the AWS object in the console, I can see a list of constructors that does not include the cost explorer. I'm using version 2.437.

**Comment by srchase** [comment]
@jtomjack93,

Thanks for raising this issue.  I've opened a PR to get CostExplorer identified as service with CORS support that should be available in the default browser build of the SDK.

You can also create your own build of the SDK here: [SDK Builder](https://sdk.amazonaws.com/builder/js/).

**Comment by srchase** [comment]
@jtomjack93 

This change has been merged.   CostExplorer will get included in the default browser build starting with the next release.
