### ISSUE TITLE
TypeScript: ScanFilter Condition AttributeValueList type mismatch

### ISSUE THREAD

**Issue by yoavain-sundaysky** [aws/aws-sdk-js#2630]
I've tried to write a ScanInput with ScanFilter with "CONTAINS" or "BEGINS_WITH" ComparisonOperator.
If I put in the AttributeValueList an array, I get a DynamoDB error.
If I put in the AttributeValueList a single item I get a TypeScript error.

Ended up with the following workaround:
```js
// @ts-ignore
const attributeValueList: AttributeValue[] = { S: HEADER_SUFFIX };
let headerScanInput: ScanInput = {
	TableName: tableName,
	Limit: 100,
	ScanFilter: { key: { ComparisonOperator: "CONTAINS", AttributeValueList: attributeValueList } }
};
```

You need to either allow array of one item, or change the following
```js
export type AttributeValueList = AttributeValue[];
```
to
```js
export type AttributeValueList = AttributeValue[] | AttributeValue;
```

**Comment by srchase** [comment]
@yoavain-sundaysky 

Thanks for raising this issue.

```ScanFilter``` is considered a [Legacy Conditional Parameter](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.html).

Are you able to instead use ```FilterExpression```?
