### ISSUE TITLE
APIGateway updateUsagePlan Documentation missing value parameter when op is remove 

### ISSUE THREAD

**Issue by lceni** [aws/aws-sdk-js#2632]
Current aws-sdk-js version: 2.378.0

In order to delete an UsagePlan, the current list of apiStages linked to the UsagePlan must be removed by calling `APIGateway.updateUsagePlan(...)`

Documentation found [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#updateUsagePlan-property) and [here](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/usageplan-update/) doesn't mention the fact you must send also the **value**, containing the **API_ID:STAGE_NAME** as part of remove patchOperations.

The statement "The new target value of the update operation. It is applicable for the add or replace operation." found in the first link above, enforces that **value** param is not required for remove operation.

Also, calling the method with the following parameters below, returns an error message which doesn't mention the need of a **value** parameter at all:

- `{usagePlanId: id, patchOperations: [{op: 'remove', path: '/apiStages'}`
- `{usagePlanId: id, patchOperations: [{op: 'remove', path: '/apiStages/0'}`
- `
{usagePlanId: id, patchOperations: [{op: 'remove', path: '/apiStages/api
_id:stage_name'}
`
- `{usagePlanId: id, patchOperations: [{op: 'remove', path: '/apiStages/0/api_id:stage_name'}`

The message says: 
> Invalid patch path '/apiStages' specified for op 'remove'. Must be one of: [/apiStages, /quota, /throttle, /productCode, /apiStages/<apidId:stageName>/throttle/<resourcePath>/<httpMethod>, /apiStages/<apidId:stageName>/throttle]

After trying a while, I found that this request works:
```
APIGateway.updateUsagePlan({
  usagePlanId: 'my_plan_id',
  patchOperations: [{
    op: 'remove',
    path: '/apiStages',
    value: 'api_id:stage_name'
  }]
})
```

Please update the documentation and the returned message mentioning the need of **value** property for **remove** operations.

**Comment by srchase** [comment]
@lceni,

I've raised this issue with the API Gateway service team.  Thanks for pointing out this problem with the documentation.

As this issue is part of the API Gateway documentation, I'm going to close out this issue.  If they respond with any updates, I can pass them along on this issue still.
