### ISSUE TITLE
S3 fetch remote data to upload - Error: write EPROTO

### ISSUE THREAD

**Issue by 10001oleg** [aws/aws-sdk-js#2633]
**IMPORTANT ERROR BUT TREATED AS "INFO" TYPE**
**NodeJS 8**
**trying fetch request, data is missed, but "INFO" type**
**Please help ASAP**

"Error { Error: write EPROTO 47617330951040:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:../deps/openssl/openssl/ssl/s23_lib.c:177:

    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
  message: 'write EPROTO 47617330951040:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:../deps/openssl/openssl/ssl/s23_lib.c:177:\n',
  errno: 'EPROTO',
  code: 'NetworkingError',
  syscall: 'write',
  region: 'us-west-2',
  hostname: '*********.s3.us-west-2.amazonaws.com',
  retryable: true,
  time: 2019-04-18T02:42:09.066Z,
  statusCode: 400 }"

**Comment by srchase** [comment]
@10001oleg 

Can you please submit full details of how you got this error, including SDK version, Node version, code example and any other details of your environment that may be pertinent?

**Comment by 10001oleg** [comment]
**It works in 98% cases**

`const fetch = require('node-fetch');

//stream URL to S3
fetch(Fileurl)
	.then( res => {
s3.upload(
{
  Bucket: 'ocr-vision-result',
  Body : res.body,
  Key : filename
}, 
 (err, data)=> {
   //handle error
          if (err) {
            console.log('Error', err);
          }
          //success
          if (data) {
            console.log('Uploaded in:', data.Location);
          }
        }
      );
	})`

**Comment by 10001oleg** [comment]
**NEW ERROR under the same conditions**
**PLEASE PLEASE HELP ME HELP ME !!!**

`  "Error { Error: write ECONNRESET
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
  message: 'write ECONNRESET',
  errno: 'ECONNRESET',
  code: 'NetworkingError',
  syscall: 'write',
  region: 'us-west-2',
  hostname: '*****.s3.us-west-2.amazonaws.com',
  retryable: true,
  time: 2019-04-18T22:05:04.671Z,
  statusCode: 400 }`

**Comment by srchase** [comment]
@10001oleg,

Are all of your files only ~1mb?

If they're all less than 5mb, the ```upload``` operation is sending them as a single part.

Can you switch to using the ```putObject``` operation instead to see if that eliminates this issue?  You'll need to specify the content length.

**Comment by 10001oleg** [comment]
Do you know, what is the max allowed ContentLength ? from params
`s3.upload(params, options, function(err, data) {
  console.log(err, data);
});`

> ContentLength — (Integer)
> Size of the body in bytes. This parameter is useful when the size of the body cannot be determined automatically.

Thank you!

**Comment by 10001oleg** [comment]
Some files ~6Mb, ~15Mb and ~9Mb
Can I use ManagedUpload for my case?
`Creating an uploader with concurrency of 1 and partSize of 10mb
var upload = new AWS.S3.ManagedUpload({
  partSize: 10 * 1024 * 1024, queueSize: 1,
  params: {Bucket: 'bucket', Key: 'key', Body: stream}
});`

> Options Hash (options):
> 
> params (map) — a map of parameters to pass to the upload requests. The "Body" parameter is required to be specified either on the service or in the params option.
> queueSize (Number) — default: 4 — the size of the concurrent queue manager to upload parts in parallel. Set to 1 for synchronous uploading of parts. Note that the uploader will buffer at most queueSize * partSize bytes into memory at any given time.
> **partSize (Number) — default: 5mb** — the size in bytes for each individual part to be uploaded. Adjust the part size to ensure the number of parts does not exceed maxTotalParts. See minPartSize for the minimum allowed part size.

**Comment by srchase** [comment]
@10001oleg 

The ```upload``` operation uses the ManagedUpload.

Do you see errors on the 1mb files?  Or only on the larger files?

**Comment by 10001oleg** [comment]
only on the larger files. 

I added data destructuring, previously transforming them into JSON and then back into Buffer, and all this during the fetch request - **this solved my problem**, since the data size decreased from 6.7 MB to 0.046 MB.

`fetch(Fileurl)
    .then(res => res.json())
    .then(data => {
      const {responses} = data;
      const textResult = {text: []};
      responses.map(({fullTextAnnotation: {text}}) => {
        textResult.text.push(text);
      });
      dataResult = Buffer.from(JSON.stringify(textResult));
      s3.upload(
        {
          Bucket: '*****',
          Body: dataResult,
          Key: filename,
        },
        (err, data) => {
          //handle error
          if (err) {
            console.log('Error', err);
          }
          //success
          if (data) {
            console.log('Uploaded in:', data.Location);
          }
        }
      );
    });`

**Comment by srchase** [comment]
Thanks for following up.

I'll close out this issue for now, but can re-open if needed.
