### ISSUE TITLE
getSignedUrl params not corresponding to operation

### ISSUE THREAD

**Issue by awattez** [aws/aws-sdk-js#2634]
According to documentation for `getSignedUrl`
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property

```
params (map) — parameters to pass to the operation. See the given operation for the expected operation parameters. In addition, you can also pass the "Expires" parameter to inform S3 how long the URL should work for.
```

I try to give some params for `getObject` operation like `ResponseContentDisposition ` (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property)
and I encounter a beautiful `* UnexpectedParameter: Unexpected key 'ResponseContentDisposition' found in params`
```
aws-sdk: ^2.437.0
node: v10.14.2
npm: 6.9.0
```
The code to reproduce the error
```js
const aws = require('aws-sdk');

const s3 = new aws.S3({
    accessKeyId: "my evil id",
    secretAccessKey: "my good key",
    region: "my region"
});

    const params = {
        Bucket: 'buckbucket', 
        Key: 'file.jpg', 
        ResponseContentDisposition: 'attachment; filename="anotherfilename.jpg"',
        ResponseContentType: 'image/jpeg',
        Expires: 60
    };
    s3.getSignedUrl('getObject',params, function(s3Err, data) {
        if (s3Err) throw s3Err
        console.log(`Generate URL successfully at ${data}`)
    });
```

The error : 
```js
⇒   node src/myfunction   
/Users/.../node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

MultipleValidationErrors: There were 2 validation errors:
* UnexpectedParameter: Unexpected key 'ResponseContentDisposition' found in params
* UnexpectedParameter: Unexpected key 'ResponseContentType' found in params
    at ParamValidator.validate (/Users/.../node_modules/aws-sdk/lib/param_validator.js:40:28)
    at Request.VALIDATE_PARAMETERS (/Users/.../node_modules/aws-sdk/lib/event_listeners.js:126:42)
```

Thanks to help me

**Comment by srchase** [comment]
@awattez 

Which specific version of the SDK are you using?

I was able to use v2.437.0 and v2.439.0 to successfully generate a signed url using your code example.

**Comment by awattez** [comment]
Hi, thx for your quick reply !
I am using  `aws-sdk@2.437.0`
I remove node_modules retry `npm install` and execute my function same error

**Comment by srchase** [comment]
@awattez 

I ran your code as-is without getting the error.  When you're getting the error, is it run inside a function?

If it would be helpful, you could open a repository with a full example to illustrate how your function is being called.

**Comment by awattez** [comment]
Here 👍 https://github.com/awattez/aws-issue

**Comment by awattez** [comment]
Oups my bad ! pushing my code was helpful the error come from : 
```js
const signedURL = () => {
    const params = {
        Bucket: 'bucket', // pass your bucket name
        Key: 'bYwrT.png', // file will be saved as testBucket/contacts.csv
        //ACL: ‘bucket-owner-full-control’
        ResponseContentDisposition: 'attachment; filename="filename.jpg"',
        ResponseContentType: 'image/jpeg',
    };
    s3.waitFor('objectExists', params, function(s3Err) {
```
 `ResponseContentDisposition` is not allowed in params for `objectExists` operation
Thanks
