### ISSUE TITLE
add Typescript definition for Request.eachItem

### ISSUE THREAD

**Issue by monken** [aws/aws-sdk-js#2636]
Currently, code written in Typescript using the `eachItem` convenience method will fail to compile with `Property 'eachItem' does not exist on type 'Request<DescribeInstancesResult, AWSError>'.`.

I briefly had a look at the ts file `lib/request.d.ts` but I'm unsure how to locate the proper interface for the item in the result set.

**Comment by AllanFly120** [comment]
Hey @monken,

As it mentioned in the [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#eachItem-property), the feature is still experimental and we may drop the support in the future. The feature may not work in all applicable circumstances. Unfortunately we don't want to encourage more users to use the feature. You can still handle the traversing logic in your code.

**Comment by monken** [comment]
Thanks. I was hoping the experimental flag is just something you forgot to remove as `eachItem` is a really useful helper method that I'd like to keep using. Are there any known issues with `eachItem` that I should be aware of?

**Comment by ajredniwja** [comment]
@monken, Im not aware of any known issues at this point. It is still experimental, will update you if I happen to find any. 

Will go ahead and close the issue for now, please reach out if you have any additional questions.
