### ISSUE TITLE
make changes files include a newline at the end

### ISSUE THREAD

**Issue by gemal** [aws/aws-sdk-js#2638]
![image](https://user-images.githubusercontent.com/69105/56584010-22f16780-65db-11e9-873f-44ac3000591b.png)

I think the files in `.changes` should contain a ending newline

**Comment by srchase** [comment]
@gemal,

The screenshot you included is for aws-sdk-php.

Did you intend to open this issue under that repository?

**Comment by gemal** [comment]
Ups. Sorry :)
