### ISSUE TITLE
Documenation for DynamoDB DocumentClient methods transactWrite and transactGet list incorrect return types

### ISSUE THREAD

**Issue by tdurk93** [aws/aws-sdk-js#2639]
The function signatures listed in the documentation for [transactGet](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#transactGet-property) and [transactWrite](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#transactWrite-property) indicate that they do not have a return value. However, the typescript definition files (and manual usage of the APIs) indicate that they return a Request object, just as the other DocumentClient functions do.

I was not able to find how this information is determined by YARD, but it needs to be updated to reflect the correct return values.

**Comment by AllanFly120** [comment]
Hi @tdurk93 

Thank your for bringing this up. We will update the API reference soon!
