### ISSUE TITLE
AWS Transfer createServer responds 500 via sdk but not via CLI

### ISSUE THREAD

**Issue by SpainTrain** [aws/aws-sdk-js#2640]
Within a Lambda with sufficient privileges, attempting

```js
res = await transferClient.createServer(createServerParams).promise()
```

where `createServerParams` is 

```json
{
    "IdentityProviderDetails": {
        "InvocationRole": "arn:aws:iam::239844027862:role/sftp-gateway-alpha-SftpTransferServerInvocationRol-1ACCJZBQMYHMP",
        "Url": "https://8ozuhd5m0i.execute-api.us-east-1.amazonaws.com/v1/"
    },
    "IdentityProviderType": "API_GATEWAY",
    "LoggingRole": "arn:aws:iam::239844027862:role/sftp-transfer-to-cloudwatch"
}
```

Running `aws transfer create-server --cli-input-json` with the JSON pulled directly from the logging in the Lambda CloudWatch Logs works as expected.  Logging output from the AWS SDK client is

```
2019-04-24T00:45:22.624Z	0074b638-d583-441a-94b4-11e517e5c24b	[AWS transfer 500 1.045s 3 retries] createServer({ IdentityProviderDetails: 
{ InvocationRole: 'arn:aws:iam::239844027862:role/sftp-gateway-alpha-SftpTransferServerInvocationRol-1ACCJZBQMYHMP',
Url: 'https://8ozuhd5m0i.execute-api.us-east-1.amazonaws.com/v1/' },
IdentityProviderType: 'API_GATEWAY',
LoggingRole: 'arn:aws:iam::239844027862:role/sftp-transfer-to-cloudwatch' })
```

The error that the AWS SDK "throws" (via async `catch`) is 

```json
{
    "message": null,
    "code": "InternalFailure",
    "time": "2019-04-24T00:45:22.623Z",
    "requestId": "9eb2704a-f0af-4a1b-b178-eb62efd9032d",
    "statusCode": 500,
    "retryable": true
}
```

Other calls such as `listServers` are working in the same Lambda.

**Comment by SpainTrain** [comment]
Should have mentioned, this is all on latest version `aws-sdk@2.441.0`

**Comment by SpainTrain** [comment]
More troubleshooting.  It appears that the http request that the SDK creates lacks a body:

```js
const req = transferClient.createServer(createServerParams)
console.log('createServer httpRequest', req.httpRequest)
```

outputs

```
{
    "method": "POST",
    "path": "/",
    "headers": {
        "User-Agent": "aws-sdk-nodejs/2.441.0 linux/v8.10.0 exec-env/AWS_Lambda_nodejs8.10"
    },
    "body": "",
    "endpoint": {
        "protocol": "https:",
        "host": "transfer.us-east-1.amazonaws.com",
        "port": 443,
        "hostname": "transfer.us-east-1.amazonaws.com",
        "pathname": "/",
        "path": "/",
        "href": "https://transfer.us-east-1.amazonaws.com/"
    },
    "region": "us-east-1",
    "_userAgent": "aws-sdk-nodejs/2.441.0 linux/v8.10.0 exec-env/AWS_Lambda_nodejs8.10"
}
```

but the `createServerParams` is not empty if it is `console.log`ed:

```json
{
    "IdentityProviderDetails": {
        "InvocationRole": "arn:aws:iam::239844027862:role/sftp-gateway-alpha-SftpTransferServerInvocationRol-KQFKYATZHNTL",
        "Url": "https://8ozuhd5m0i.execute-api.us-east-1.amazonaws.com/v1/"
    },
    "IdentityProviderType": "API_GATEWAY",
    "LoggingRole": "arn:aws:iam::239844027862:role/sftp-transfer-to-cloudwatch"
}
```

**Comment by AllanFly120** [comment]
Hey @SpainTrain ,

Can you find the lambda log in cloudwatch to inspect the exact exception? I don't think the call fails because of lacking body. You can print the body like this: 

```javascript
const req = transferClient.createServer(createServerParams)
req.send(() => {
    console.log(req.httpRequest)
});
```

**Comment by SpainTrain** [comment]
Ah, you are right, I didn't realize that the `httpRequest` object was mutated after calling `.promise()`.

I will redact security headers and post the relevant contents of that object.

**Comment by SpainTrain** [comment]
Example `httpRequest`

```
{
method: 'POST',
path: '/',
headers: {
'User-Agent': 'aws-sdk-nodejs/2.441.0 linux/v8.10.0 exec-env/AWS_Lambda_nodejs8.10 promise',
'Content-Type': 'application/x-amz-json-1.1',
'X-Amz-Target': 'TransferService.CreateServer',
'X-Amz-Content-Sha256': '<sha>',
'Content-Length': 322,
Host: 'transfer.us-east-1.amazonaws.com',
'x-amz-security-token': '<token>',
'X-Amz-Date': '20190424T170956Z',
Authorization: 'AWS4-HMAC-SHA256 Credential=<20 digits A-z0-9>/20190424/us-east-1/transfer/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-target, Signature=<signature>'
},
body: '{"IdentityProviderDetails":{"InvocationRole":"arn:aws:iam::239844027862:role/sftp-gateway-alpha-SftpTransferServerInvocationRol-9HZBU4GSJ0G0","Url":"https://8ozuhd5m0i.execute-api.us-east-1.amazonaws.com/v1/"},"IdentityProviderType":"API_GATEWAY","LoggingRole":"arn:aws:iam::239844027862:role/sftp-transfer-to-cloudwatch"}',
endpoint: {
protocol: 'https:',
host: 'transfer.us-east-1.amazonaws.com',
port: 443,
hostname: 'transfer.us-east-1.amazonaws.com',
pathname: '/',
path: '/',
href: 'https://transfer.us-east-1.amazonaws.com/',
...}...}
```

Let me know if any of the truncated fields would be useful

**Comment by AllanFly120** [comment]
Just to help myself understanding your issue: you are calling this API from Lambda or locally? If in lambda, have you tried calling the SDK locally with sufficient permissions? It's possible that lambda function fails to execute, so the lambda execution's log from CloudWatch may be more helpful in this case.

**Comment by SpainTrain** [comment]
Yup, sorry for lack of clarity.  The logs I have posted are from the lambda's execution logs in CloudWatch.  I am currently working on running the code locally with my admin user to troubleshoot.  However, I have double checked the Role Policies via the web UI (first going to the Lambda, then following the link to its Execution Role.  It appears that it should have full access to AWS Transfer:

![image](https://user-images.githubusercontent.com/380032/56684344-8f349f80-669d-11e9-8ac2-d2770dccfbf2.png)

**Comment by SpainTrain** [comment]
I should also note that 

```
await transferClient.listServers().promise()
```

works correctly within the Lambda execution (I can log and see the correct response in cloudwatch logs), so the Lambda is able to execute and access AWS Transfer, just not the `createServer` action.

**Comment by AllanFly120** [comment]
Hey @SpainTrain, 

This looks to me like a service issue. Since you have the request Id, you can seek help from AWS Transfer team, they might have better sight for this issue. You can find them at their [forum](https://forums.aws.amazon.com/forum.jspa?forumID=323)

**Comment by SpainTrain** [comment]
Thank you for your help!  I have tracked down the issue - the Lambda requires a Policy that allows access to API Gateway.  It seems that AWS Transfer must check API Gateway for the RestApi Url provided in `IdentityProviderDetails.Url`.  However, instead of a 403 status and/or permission error message, it is an unhandled exception within AWS Transfer that results in 500 status.

I don't think there is anything the SDK can do about this.  Is there a good way to report bugs in the AWS API itself?  It seems like the correct behavior of the API is to respond with 403 status and/or a permission error message.

Thanks again!

**Comment by SpainTrain** [comment]
Sorry, just saw your previous comment.  Thanks! Closing!

**Comment by SpainTrain** [comment]
Great call, there is an existing thread about my exact issue - https://forums.aws.amazon.com/thread.jspa?threadID=301310&tstart=0 (linking here for posterity)

I should have done more research first! :confused:
