### ISSUE TITLE
Usage of ListUsersInGroup

### ISSUE THREAD

**Issue by achutkiran** [aws/aws-sdk-js#2643]
Hi all, Is there any way to get List of users in a group in cognito userpool who are enabled or disabled

**Comment by srchase** [comment]
@achutkiran 

The ```ListUsers``` operation allows for filtering, including based on the status of enabled or disabled.  Filtering is limited to specific standard attributes.  See [ListUsers API Examples](https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-manage-user-accounts.html#cognito-user-pools-searching-for-users-listusers-api-examples).

**Comment by achutkiran** [comment]
ListUsers will allow filtering but for only one attributes. What i need is list of users who are in particular group and enabled

**Comment by srchase** [comment]
@achutkiran 

As this is a question about the usage of those Cognito APIs, please followup with the Cognito team on the [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=173).  They can take the feature request or offer a suggestion for your specific use case.
