### ISSUE TITLE
`X-Amz-Content-Sha256` never checked on POST.

### ISSUE THREAD

**Issue by bebbi** [aws/aws-sdk-js#2649]
Bug?

When submitting files to S3 using a pre-signed post request, s3 accepts files that do not match the client-provided `X-Amz-Content-Sha256` value without complaining.

The lambda pre-signing code looks like this (signature version `v4`):

    const signPostFile = (knownSha256) => {
      const params = {
        Fields: {
          key: knownSha256
        },
        Conditions: [
          ['content-length-range', 0, 10000000],
          { 'X-Amz-Content-Sha256': knownSha256]
        ]
      }

      s3.createPresignedPost(params, callback)
    }

This should enforce the `knownSha256` to become the file's key also.
While this does force the client to send the `knownSha256` form field, S3 never checks the submitted files against the `sha256` provided in `X-Amz-Content-Sha256` and instead allows the client to send arbitrary files.
What piece is missing? - Is rejecting a file on invalid `X-Amz-Content-Sha256` not the purpose of that form field?

**Comment by AllanFly120** [comment]
Hey @bebbi 

I cannot find the AWS document mentioning that `X-Amz-Content-Sha256` can be presigned post condition element. Can you share me a link to it?

**Comment by bebbi** [comment]
Thanks @AllanFly120,
[This](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTForms.html) must be it and you're right there's a comment that constrains the available elements; `X-Amz-Content-Sha256` is not one of the allowed elements.

When you close this issue, can you confirm there's no solution to force the content of a `X-Amz-Content-Sha256` header, as the [other solution](https://github.com/aws/aws-sdk-js/issues/2642#issuecomment-488796532) doesn't work either?
Thanks!

**Comment by conord33** [comment]
@bebbi did you ever find a solution to this? I would also like to be able to enforce a SHA256 hash of an upload file using the js sdk.

**Comment by bebbi** [comment]
No I didn't. I am now checking the hash with a separate lambda function.

**Comment by bramevo** [comment]
Same issue here... I'm using POST form and setting X-Amz-Content-Sha256 during upload. When I upload a different file however, S3 does not reject the upload...
