### ISSUE TITLE
AWS RDSDataService not running

### ISSUE THREAD

**Issue by westlakem** [aws/aws-sdk-js#2650]
I'm trying to use RDSDataService to query an Aurora Serverless database.  When I'm trying to query, my lambda just times out (I've set it up to 5 minutes just to make sure it isn't a problem with that).  I have 1 record in my database and when I try to query it, I get no results, and neither the error or data flows are called.  I've verified executeSql is called by removing the dbClusterOrInstanceArn from my params and it throw the exception for not having it.

I have also run `SHOW FULL PROCESSLIST` in the query editor to see if the queries were still running and they are not.  I've given the lambda both the `AmazonRDSFullAccess` and `AmazonRDSDataFullAccess` policies without any luck either.  You can see by the code below, i've already tried what was recommended in #2376.

Not that this should matter, but this lambda is triggered by a Kinesis event trigger.

```
const AWS = require('aws-sdk');

exports.handler = (event, context, callback) => {
  const RDS = new AWS.RDSDataService({apiVersion: '2018-08-01', region: 'us-east-1'})
  for (record of event.Records) {
    const payload = JSON.parse(new Buffer(record.kinesis.data, 'base64').toString('utf-8'));
    const data = compileItem(payload);
    const params = {
      awsSecretStoreArn: 'arn:aws:secretsmanager:us-east-1:149070771508:secret:xxxxxxxxx,
      dbClusterOrInstanceArn: 'arn:aws:rds:us-east-1:149070771508:cluster:xxxxxxxxx',
      sqlStatements: `select * from MY_DATABASE.MY_TABLE`
      // database: 'MY_DATABASE'
    }
    console.log('calling executeSql');
    RDS.executeSql(params, (error, data) => {
      if (error) {
        console.log('error', error)
        callback(error, null);
      } else {
        console.log('data', data);
        callback(null, { success: true })
      }
    });
  }
}
```

**Comment by westlakem** [comment]
We've tried it through the AWS CLI and it returns results, so I'm thinking it has to be something in the executeSql method in the SDK

**Comment by matuella** [comment]
I know that this does not address your issue directly, but the RDSDataService docs say that:

> `executeSql(params = {}, callback) ⇒ AWS.Request`
> Runs one or more SQL statements.
> 
> **This operation is deprecated. Use the BatchExecuteStatement or ExecuteStatement operation.**
> 

You can check [it out here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#executeSql-property).

**Comment by endeavor85** [comment]
I was having a similar issue - worked with AWS CLI but Javascript SDK in Lambda just resulted in timeouts.

I resolved the issue by **removing the Lambda function from its VPC**. (i.e., don't put the function in any VPC)

Prior to Data API, the function needed to be in the VPC with the database, but that's no longer necessary with the Data API.  Revisiting [AWS Lambda VPC best practices](https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html#lambda-vpc) makes me think it's best to keep the function out of the VPC if we're only using the Data API.

It may be worth playing around with the VPC Network ACLs and Security Groups just to see if it is possible to use the Data API within the VPC anyways.

**Comment by westlakem** [comment]
it 100% was a VPC issue with the lambda being outside the VPC and the RDS inside.  You must move your lambda inside the VPC for it to hit the database
