### ISSUE TITLE
Lodash Dependency vulnerability via Karma

### ISSUE THREAD

**Issue by jeremiahwitt** [aws/aws-sdk-js#2651]
Versions of lodash lower than 4.17.11 have a security vulnerability (https://tools.cisco.com/security/center/viewAlert.x?alertId=59546). This is a transitive dependency, brought in by karma. By bumping karma to a version at least as recent as 4.0.1, this issue can be resolved.

**Comment by AllanFly120** [comment]
The update has been merged, it will be shipped in next release. Thanks a lot for the contribution!
