### ISSUE TITLE
node_modules/aws-sdk/index has no default export

### ISSUE THREAD

**Issue by borch84** [aws/aws-sdk-js#2654]
Hi, I am integrating aws-sdk into Angular2 application. I have installed aws-sdk with `npm install aws-sdk`
Also changed the file tsconfig.app.json as pointed here: https://www.npmjs.com/package/aws-sdk#with-angular
But when I serve my application I get this message:

`[ng] ERROR in src/app/home/home.page.ts(3,8): error TS1192: Module '"/home/borch/Documents/Ionic/aws-iot-mqtt-client/node_modules/aws-sdk/index"' has no default export.
`

I am importing aws-sdk with this line: `import AWS from 'aws-sdk'; `
Appreciate any feedback for understanding what is missing here? 
Thanks.

**Comment by shuhei-tagawa** [comment]
Hi, try to use below. 
`import * as S3 from 'aws-sdk/clients/s3';`
`import { S3 } from 'aws-sdk/clients/s3'; // I'm not sure but this would be working`
This is because we aren't using default exports in the SDK.

**Comment by ggriffin** [comment]
I ran into the same.
`aws-sdk-2.457.0`

The guidance [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/#In_Node_js1) seems to be incorrect:
```
// import entire SDK
import AWS from 'aws-sdk';
// import AWS object without services
import AWS from 'aws-sdk/global';
// import individual service
import S3 from 'aws-sdk/clients/s3';
```
This compiles:
`import { config, SecretsManager } from 'aws-sdk';`

**Comment by hassan-kassim** [comment]
use this mehod

import { config,  S3 , CognitoIdentityCredentials} from 'aws-sdk';

fileEvent(fileInput: any) {
    const region = '<region>';
    const bucketName = '<bucketName>';
    const IdentityPoolId = '<IdentityPoolId>';


    const file = fileInput.target.files[0];
      config.update({
        region: region,
        credentials: new CognitoIdentityCredentials({
          IdentityPoolId: IdentityPoolId
        }) 
      });

      const s3 = new S3({
        apiVersion: '2006-03-01',
        params: { Bucket: bucketName}
      });

      s3.upload({ Key: file.name, Bucket: bucketName, Body: file, ACL: 'public-read'}, function (err, data) {
       if (err) {
         console.log(err, 'there was an error uploading your file');
       }
     }); 
  }

**Comment by DonutRanger** [comment]
> I ran into the same.
> `aws-sdk-2.457.0`
> 
> The guidance [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/#In_Node_js1) seems to be incorrect:
> 
> ```
> // import entire SDK
> import AWS from 'aws-sdk';
> // import AWS object without services
> import AWS from 'aws-sdk/global';
> // import individual service
> import S3 from 'aws-sdk/clients/s3';
> ```
> 
> This compiles:
> `import { config, SecretsManager } from 'aws-sdk';`

I used `import * as AWS from "aws-sdk"` for this one. You're right, the guidance seems to be incorrect.

>
