### ISSUE TITLE
use native url

### ISSUE THREAD

**Issue by jimmywarting** [aws/aws-sdk-js#2655]
Any possibility to switch querystrnig and url for native URL & SearchParams?

https://github.com/aws/aws-sdk-js/blob/33e72cbf5085f4b8971df7e31ce2eccea6baf64b/package.json#L45-L47

**Comment by AllanFly120** [comment]
Hi @jimmywarting 

> switch querystrnig and url for natiive URL & SearchParams
I assume you mean using Node native `url` package here. We import these polyfills here to support browser SDK. We use them to keep the implement in Browser and Node consistent. Is there any issue you met has something to do with the dependencies?

**Comment by jimmywarting** [comment]
> I assume you mean using Node native `url` package here

yes, 
but there is no issue with the dependencies. 

I just think that it would be better to use something that exist natively in both environment. And use polyfill as a fallback. You could then later ditch that polyfill when you are no longer targeting older platforms. We have stop supporting older platforms so just being able to replace or ignore a package within webpack or browserify is neat. You can even use npm shrinkwrap to [override nested NPM dependency versions](https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions) to be something like `module.exports = globalThis.URL`

Gives fewer dependencies, faster boot up by using something that is already there

----

besides i don't like the that params behave differently when there is one or more keys 

`Array.isArray(params[key]) ? params[key].push(value) : params[key] = [params[key], value]`

just becomes `params.append(key, value)`

and getting it could be something like 

`values = Array.isArray(params[key]) ? params[key] : [params[key]]`

Here you can either just use `params.get()` or `params.getAll()`

**Comment by jimmywarting** [comment]
Well, look at that node also says the legency api is "Deprecated: Use the WHATWG URL API instead."
 https://nodejs.org/api/url.html#url_legacy_url_api

That is what i think you should do also

**Comment by ajredniwja** [comment]
Hey @jimmywarting is this still a persisting issue for you?
