### ISSUE TITLE
Problem Adding Rules to ALB Listeners - elbv2.createRule

### ISSUE THREAD

**Issue by MattCopenhaver** [aws/aws-sdk-js#2658]
Hi,

I'm trying to add rules to an ALB listener, and I'm not sure if I'm misunderstanding the documentation or if the documentation doesn't match the SDK's capabilities.

Here's the relevant page: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ELBv2.html#createRule-property
I'm sure it also applies to modifyRule, and maybe more.

In the `Conditions` input parameter, you specify an array of conditions.  The docs list about 8 different types of conditions.  This maps well to the ability to do this through the console, as seen in the IF section here: 
<img width="784" alt="Screen Shot 2019-05-07 at 6 15 30 PM" src="https://user-images.githubusercontent.com/12800786/57336567-53b1c080-70f4-11e9-8afe-28fd6bbf0453.png">

However, when trying to create a similar rule using the SDK, I get the following errors:

***
When any condition in the array does not have the `Field` key:
```js
Conditions: [
  {
    Field: 'path-pattern',
    PathPatternConfig: {
      Values: [
        '/demo',
      ],
    },
  },
  {
    HttpRequestMethodConfig: {
      Values: [
        'POST',
      ],
    },
  },
],
```
```Unhandled rejection ValidationError: A condition field must be specified```
***
When trying to specify `HttpRequestMethodConfig`, no matter the value of `Field:
```js
Conditions: [
  {
    Field: 'path-pattern',
    PathPatternConfig: {
      Values: [
        '/demo',
      ],
    },
    HttpRequestMethodConfig: {
      Values: [
        'POST',
      ],
    },
  },
],
```
```Unhandled rejection ValidationError: You cannot specify 'HttpRequestMethodConfig' for actions of type 'path-pattern'```
or
```js
Conditions: [
  {
    Field: 'host-header',
    HostHeaderConfig: {
      Values: [
        'something',
      ],
    },
    HttpRequestMethodConfig: {
      Values: [
        'POST',
      ],
    },
  },
],
```
```Unhandled rejection ValidationError: You cannot specify 'HttpRequestMethodConfig' for actions of type 'host-header'```
***
Any ideas?

**Comment by MattCopenhaver** [comment]
I figured out how to make this work, but it's completely undocumented.  

Instead of using `Field: 'host-header'` or `Field: 'path-pattern'`, the only two allowed values according to the doc, I (through shear luck) tried a different value of `Field: 'http-request-method'` and that allowed me to use the `HttpRequestMethodConfig` key.

I'm leaving the issue open as an update to include this in the documentation.  I still don't know what values to use for the other keys.

**Comment by AllanFly120** [comment]
Hey @MattCopenhaver 

Thank you for reporting this issue. 

The content of the [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ELBv2.html#createRule-property) is shipped by ELB service team. It seems to me that the service team needs to update their documentations for `Field`. We can ask the team to update their docs internally. At the same time you can also report it in the [EC2 service forum](https://forums.aws.amazon.com/forum.jspa?forumID=30).
