### ISSUE TITLE
ServerlessApplicationRepository.createCloudFormationTemplate is not a function

### ISSUE THREAD

**Issue by MinCheTsai** [aws/aws-sdk-js#2659]
I use ServerlessApplicationRepository and call createCloudFormationTemplate then get error
I list this object's properties and function, can't see createCloudFormationTemplate

Environment:
Lambda NodeJs8.10
API Version: 2017-09-08

**Comment by AllanFly120** [comment]
Hey @MinCheTsai 

Unfortunately it seems like the lambda is still using SDK at [version 2.290.0](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). The operation is introduced in the SDK from version 2.349.0. According to lambda document, it's more preferable to provide your own SDK(newer version) through a [deployment package](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html).

We have filed a ticket to the service team to update the runtime, but there will be some time before it is deployed.
