### ISSUE TITLE
TypeError: transcribeservice.deleteTranscriptionJob is not a function

### ISSUE THREAD

**Issue by bannostookaylo** [aws/aws-sdk-js#2660]
This is my first time using this transcribe when I use the method `transcribeservice.startTranscriptionJob` it works fine but when I use `transcribeservice.deleteTranscriptionJob` this is the error I receive. 

    TypeError: transcribeservice.deleteTranscriptionJob is not a function

Here is the version I have set at the top of my index.js file `var transcribeservice = new AWS.TranscribeService({apiVersion: '2017-10-26'});` as far as I can tell thats the most recent version.

Also these are the docs i've been referencing https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/TranscribeService.html

**Comment by AllanFly120** [comment]
Hey @bannostookaylo 

Can you elaborate where are you using the SDK and how do you import the transcribe client? I cannot reproduce the issue in Node SDK. The 2 services you mentioned were both introduced in version 2.332.0, you can try to re-install the SDK with a newer version.

**Comment by bannostookaylo** [comment]
i was importing at the top of one of my lambdas using C9 like this `var transcribeservice = new AWS.TranscribeService({apiVersion: '2017-10-26'});` 

I've decided however what I am doing I don't need this function. Perhaps I was doing something wrong but I've moved on without it. I'll go ahead and close this out.
