### ISSUE TITLE
aws-sdk returns path-style url when uploading files to S3

### ISSUE THREAD

**Issue by MarceloAplanalp** [aws/aws-sdk-js#2662]
Since amazon will deprecate path-style urls next year, the sdk should return virtual-hosted style urls.

Is there any configuration I can use to get the virtual hosted style url?
Currently using v2.452.0

**Comment by trivikr** [comment]
@MarceloAplanalp Any update on why this issue was closed?

**Comment by MarceloAplanalp** [comment]
@trivikr, the SDK only returns path-style URL's if the bucket name contains periods.
In my case, using a different bucket name solves the issue
