### ISSUE TITLE
Bulk file upload

### ISSUE THREAD

**Issue by iamfrntdv** [aws/aws-sdk-js#2665]
Is there any preferred way to bulk file upload? Unfortunately I couldn't find any example. Will appreciate any help.

**Comment by AllanFly120** [comment]
@iamfrntdv 

If you want to upload single big files or uploading files without knowing the length, you can use the [managed upload](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property). Unfortunately JS SDK itself doesn't provide functionalities that uploads directories. But there are some 3rd party libraries on NPM provide the ability. 

Some AWS SDKs for other languages also support uploading directory(aka s3 transfer manager) such as [boto s3transfer](https://github.com/boto/s3transfer)
