### ISSUE TITLE
SQS#sendMessage throws 400 without an actual error logged

### ISSUE THREAD

**Issue by Wintereise** [aws/aws-sdk-js#2666]
I'm using the latest SDK (2.453.0) with NodeJS 8.10.0 and TypeScript. This was actually working earlier, but randomly seems to have broken, and I've been unable to figure out what exactly is going on.

Invocation
```    
private static readonly _sqs = new SQS({
        apiVersion: "2012-11-05"
    });
``` 
(It's not an access denied error, I directly specified the access key ID and secret when invoking it to no avail)

I'm trying to send an EXTREMELY simple payload with no attributes.

```{"QueueUrl":"https://sqs.eu-west-1.amazonaws.com/<acc id>/<queue name>","MessageBody":"Test"}```

I've validated that the URL is correct.

If I try to send this via the CLI or the AWS Console to the same queue, everything works fine.

If I use the SDK however like this:

```
        const sqsParams: SendMessageRequest = {
            QueueUrl: <queue URL>,
            MessageBody: "Test" // serialize(payload)
        };

        log.debug("SQSEventBroadcaster: attempting to queue a payload.", {
            params: sqsParams,
            payload
        });
        return await this._sqs.sendMessage(sqsParams).promise();
```

I get hit with this error (my logger wrapped it in JSON, but it should be legible).

```
{"_logLevel":"error","msg":null,"ctx":{},"stack":"400: \n    at Request.extractError (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\protocol\\query.js:55:29)\n    at Request.callListeners (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\sequential_executor.js:106:20)\n    at Request.emit (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\sequential_executor.js:78:10)\n    at Request.emit (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\request.js:683:14)\n    at Request.transition (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\request.js:22:10)\n    at AcceptorStateMachine.runTo (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\state_machine.js:14:12)\n    at G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\state_machine.js:26:10\n    at Request.<anonymous> (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\request.js:38:9)\n    at Request.<anonymous> (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\request.js:685:12)\n    at Request.callListeners (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\sequential_executor.js:116:18)\n    at Request.emit (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\sequential_executor.js:78:10)\n    at Request.emit (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\request.js:683:14)\n    at Request.transition (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\request.js:22:10)\n    at AcceptorStateMachine.runTo (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\state_machine.js:14:12)\n    at G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\state_machine.js:26:10\n    at Request.<anonymous> (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\request.js:38:9)\n    at Request.<anonymous> (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\request.js:685:12)\n    at Request.callListeners (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\sequential_executor.js:116:18)\n    at callNextListener (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\sequential_executor.js:96:12)\n    at IncomingMessage.onEnd (G:\\xen\\manager\\node_modules\\aws-sdk\\lib\\event_listeners.js:299:13)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","_tags":["log","error"]}
```

I tried getting into `protocol\query.js` in an attempt to gain more information, but when this happens, `extractError` (quoted below) receives a response object whose httpResponse.body (Buffer) is in fact, totally empty.

```
function extractError(resp) {
  var data, body = resp.httpResponse.body.toString(); <-- This is EMPTY

   //...

  if (data.Code) {
    resp.error = util.error(new Error(), {
      code: data.Code,
      message: data.Message
    });
  } else {
    resp.error = util.error(new Error(), {
      code: resp.httpResponse.statusCode,
      message: null <-- We're hitting this
    });
  }
}
```

No idea what's happening (or the why of it), any assistance is appreciated.

**Comment by Wintereise** [comment]
I turned on debugging, the only line printed is this:

[AWS sqs 400 0.853s 0 retries] sendMessage({ QueueUrl: 'https://sqs.eu-west-1.amazonaws.com/62<>5/x<>eue',
  MessageBody: 'Test' })

**Comment by Wintereise** [comment]
So, we figured it out. The issue was the fact that AWS.SQS(config) <-- this config object assumed a bogus AWS_REGION value (due to Ref resolution not being available when running locally via the serverless framework).

Thanks to that, we ended up with a request object that looked like this (https://puu.sh/DrB37/722bdc3ad5.png), which appears to be due to an implicit toString call on an object.

I think the SDK should validate that the region object is actually a string and not garbage before proceeding for all services.

**Comment by AllanFly120** [comment]
Hey @Wintereise 

Good to hear you got the issue sorted out. Yea we currently only validate if region exists before firing the request. I think it makes sense to validate the region type to be string. Would you like to open a PR to contribute to this feature? The SDK does the validation [here](https://github.com/aws/aws-sdk-js/blob/master/lib/event_listeners.js#L91).

Feel free to comment here if you have further questions.

**Comment by Wintereise** [comment]
@AllanFly120 I'll take a look at making that PR happen.

**Comment by Wintereise** [comment]
> Yea we currently only validate if region exists before firing the request

Didn't seem to be the case based on my testing though, I'll take a look at this too.

**Comment by simranjeet2589** [comment]
@AllanFly120 I can have a look at this. Please let me know if this is not in development.
