### ISSUE TITLE
s3 upload hangs

### ISSUE THREAD

**Issue by nikiask** [aws/aws-sdk-js#2669]
I'm trying to upload data from a stream to s3, but s3.upload hangs. The stream is a string stream of unknown length.

```typescript
    const stream = streamOfUnkownLength;
    const key = uuid();
    const s3 = new S3({
      credentials: {
        accessKeyId: "my-access-key",
        secretAccessKey: "my-secret-access-key"
      }
    });
    console.log("uploading");
    const response = await s3
      .upload({
        Bucket: "my-bucket-name",
        Key: key,
        Body: stream
      })
      .promise();
    // this never gets called because the previous statement hangs
    console.log("response", response);
```

Here is the policy for the user with the access/secret keys.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::my-bucket-name/*"
        }
    ]
}
```

**Comment by AllanFly120** [comment]
Hey @nikiask,

Sorry for the late response, the first thing I noticed is that you are using `s3.upload` but set the policy as `s3:PutObject`. These are 2 different operations. `s3.upload` uses a series of s3 operations under the hood, you need to set them respectively. Here's the implement of `s3.upload`: https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js. At least these APIs are used: CreateMultipartUpload, UploadParts, CompleteMultipartUpload, PutObject

**Comment by nikiask** [comment]
@AllanFly120 Its been a while since I've worked with this code, but if I recall correctly it hangs, it doesn't produce an error. The code sample's comment describes where it hangs. I recall using async/await with try/catch in one of my attempts to get it working/debug, but the same thing happens, it hangs/blocks and never throws. That was my main issue, throwing an error saying something about not having enough policy permissions instead of hanging would be helpful.

I'm not currently working on this functionality so unfortunately I can't help with testing/debugging at the moment, however the code sample is self contained, all that's needed to run it is an access/secret key and the policy shown. Thank you for your advice about the policy permissions, I will try it when I get back to that section of the code.

**Comment by ajredniwja** [comment]
@nicks is this still a persisting issue for you?

**Comment by nicks** [comment]
@ajredniwja did you intend to ping @nikiask?
