### ISSUE TITLE
AWS.MetadataService is not a constructor  please help me !

### ISSUE THREAD

**Issue by baokeyu123** [aws/aws-sdk-js#2676]
hi, everybody
i have a question when i coding ' var metadata = new AWS.MetadataService();',it report a error 'AWS.MetadataService is not a constructor'.how to solve it .
thanks
kind regards

**Comment by lclghst** [comment]
Looking at the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/MetadataService.html) it says:

>  **Note:** This feature is not supported in the browser environment of the SDK.

**Comment by trivikr** [comment]
@baokeyu123 Are you trying in browser environment?
If yes, it's not supported as @lclghst mentioned

**Comment by baokeyu123** [comment]
> e browser environment of the SDK.

i user angularJS4. please tell me ,how to using new AWS.MetadataService();.i look for some document and  comments. 
  function getEC2Rolename(AWS){
        var promise = new Promise((resolve,reject)=>{

            var metadata = new AWS.MetadataService();

            metadata.request('/latest/meta-data/iam/security-credentials/',function(err,rolename){
                if(err) reject(err);
                console.log(rolename);            
                resolve(rolename);
            });
        });

        return promise;
    };
the code don't use too
thanks

**Comment by baokeyu123** [comment]
@trivikr 

i user angularJS4. please tell me ,how to using new AWS.MetadataService();.i look for some document and comments.
function getEC2Rolename(AWS){
var promise = new Promise((resolve,reject)=>{

        var metadata = new AWS.MetadataService();

        metadata.request('/latest/meta-data/iam/security-credentials/',function(err,rolename){
            if(err) reject(err);
            console.log(rolename);            
            resolve(rolename);
        });
    });

    return promise;
};
the code don't use too
thanks

**Comment by trivikr** [comment]
@baokeyu123 is your code rendered on the client side (browser) or server side (Node.js)?
Here are some results between CSR and SSR https://www.google.com/search?q=client+side+vs+server+side+rendering

**Comment by baokeyu123** [comment]
@trivikr 
            Thankyou very much for your sharing!

**Comment by trivikr** [comment]
@baokeyu123 Did you get answer to your question?

**Comment by baokeyu123** [comment]
@trivikr  i has used java to solve the question.
Thankyou very much for your sharing!!
