### ISSUE TITLE
CognitoIdentityServiceProvider.adminSetUserPassword is not a function in Lambda, how to change aws-sdk to a newer version in AWS Lambda to use it

### ISSUE THREAD

**Issue by syqrefind** [aws/aws-sdk-js#2680]
When using `cognitoIdentityServiceProvider.adminSetUserPassword` in the Lambda, got the following execution result
```
Response:
{
  "errorType": "TypeError",
  "errorMessage": "cognitoIdentityService.adminSetUserPassword is not a function",
  "trace": [
    "TypeError: cognitoIdentityService.adminSetUserPassword is not a function",
    "    at Runtime.exports.handler (/var/task/index.js:27:28)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:65:25)",
    "    at process._tickCallback (internal/process/next_tick.js:68:7)"
  ]
}

Request ID:
"a67215b9-7343-482e-8f61-9ba4e96632a1"
```
This is the code:
```
const AWS = require('aws-sdk');
const cognitoIdentityService = new AWS.CognitoIdentityServiceProvider({apiVersion: '2016-04-18', region: 'us-east-1'});

exports.handler = (event, context, callback) => {
    const userPoolId = event.userPoolId;
    const userName = event.userName;
    const password = event.password;
    
    if (!userPoolId) {
        return callback('Missing userPoolId in the request body.');
    }
    if (!userName) {
        return callback('Missing userName in the request body.');
    }
    if (!password) {
        return callback('Missing password in the request body.');
    }
    
    const params = {
       Password: password,
       Permanent: true,
       Username: userName,
       UserPoolId: userPoolId
    };
    
    cognitoIdentityService.adminSetUserPassword(params, (err, data) => {
        if (!err) {
            console.log('Successfull...');
            console.log(data);
            callback(null, {
                statusCode: 201,
            })
        } else {
            console.log('Error...');
            console.log(err, err.stack);
            callback(err);
        }
    });
};
```
Other Amazon Cognito Identity Provider services seem to work fine, I only get this error for `adminSetUserPassword`.

**Comment by dsandor** [comment]
@syqrefind update your aws-sdk to the latest version.  The function was added as of version 2.449.0.

**Comment by trivikr** [comment]
Confirmed that `cognitoIdentityService.adminSetUserPassword` was added in API 2.449.0
Changelog: https://github.com/aws/aws-sdk-js/blob/3f1e54f1da1b3a87f8ec19c8bb32ac1e66a7be75/.changes/2.449.0.json#L2-L6

Closing this issue, please reopen if you have any questions.

**Comment by syqrefind** [comment]
So since Lambda provides me with only the old version, how do I change it to the latest version?

**Comment by syqrefind** [comment]
btw I don't think I can reopen this issue

**Comment by trivikr** [comment]
Looks like GitHub doesn't have an option for original reporter to open closed issues.
This request has been open for 3+ years now, I've asked for an update https://github.com/isaacs/github/issues/583#issuecomment-495768980

**Comment by syqrefind** [comment]
> @syqrefind update your aws-sdk to the latest version. The function was added as of version 2.449.0.

Hey do you know how to upgrade the aws-sdk version in AWS Lambda Functions?

**Comment by dsandor** [comment]
@syqrefind When you say you want to update the aws-sdk version in AWS Lambda Functions what exactly do you mean? 

When executing a Lambda the version of the sdk is supplied by the dependencies you zipped up with your lambda code.  So update the reference in your code bundle and that is what is used by the Lambda in the execution context. 

So since it looks like you are using nodejs you would update your package.json like this:

npm i aws-sdk@latest

Then package and deploy the lambda and it will work.

**Comment by lyh1win** [comment]
I face the same problem, adminSetUserPassword work on local, but fail on lambda.
How do I know which version of sdk is running on lambda, seems serverless deploy striped the sdk and using the default sdk on lambda which is  older than 2.xx .

**Comment by AllanFly120** [comment]
Hi @syqrefind @lyh1win 

The SDK bundled in Lambda runtime is 'partly' updated. Please refer to the [lambda doc](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) for more information. To access the newest SDK in Lambda, it's preferable to use the [deployment package](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html) and bundle your local SDK.

**Comment by vanerleo** [comment]
Because of the package size, aws-sdk usually doesn't get shipped as part of the deployment. ( ie serverless project)
How often does lambda have its aws-sdk upgraded?

**Comment by trivikr** [comment]
Hi @vanerleo, you can view [AWS Lambda FAQs](https://aws.amazon.com/lambda/faqs/)
There's a [Contact Us](https://aws.amazon.com/contact-us/) link below

**Comment by GabrielNicolasAvellaneda** [comment]
> Because of the package size, aws-sdk usually doesn't get shipped as part of the deployment. ( ie serverless project)
> How often does lambda have its aws-sdk upgraded?

You can actually deploy aws-sdk using serverless framework if you include it as a normal dependency not as a dev dependency. Basically you must do npm i aws-sdk@latest and when you run serverless deploy you will see something like this:

`Serverless: Packing external modules: source-map-support@^0.4.18, aws-sdk@^2.499.0, babel-runtime@^6.26.0, uuid@^3.3.2
`
