### ISSUE TITLE
targetInService fails to fetch detail for some targets

### ISSUE THREAD

**Issue by shubhamkes** [aws/aws-sdk-js#2688]
**Describe the bug**
I have more than 10 targets but targetInService can not fetch details for two targets out of those list and these targets having instances attached to it.

**SDK version number**
2.465.0

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v10.15.3

**Current behavior**
Callback is never invoked incase of two targets.

**Expected behavior**
Should have return target detail and instances attached to it.

**Comment by klaytaybai** [comment]
Hi @shubhamkes, this operation will not do the callbacks for unhealthy targets.  Can you verify that the targets are in a healthy state via the Console or other SDK operations?

**Comment by shubhamkes** [comment]
Yup, Sorry forgot to mention all those instances are in healthy status. And instance count is more than 2

**Comment by shubhamkes** [comment]
By mistake i pasted wrong sdk version, Have updated now in the issue
2.465.0

**Comment by ajredniwja** [comment]
Hey @shubhamkes,

Apologies for the late reply, are you still facing the issue?

**Comment by shubhamkes** [comment]
I am using alternative method to fetch instance detail 
Thanks

**Comment by ajredniwja** [comment]
I will go ahead and close the issue, please reach out if you have any additional questions.
