### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by phanikumar252** [aws/aws-sdk-js#2691]
hi @AllanFly120 i am also getting th same issue like "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource." Can you please help on this.Thank you

**Comment by phanikumar252** [comment]
![image](https://user-images.githubusercontent.com/47655676/58744593-81bfc180-8462-11e9-9d7c-b40137580a76.png)

**Comment by phanikumar252** [comment]
![image](https://user-images.githubusercontent.com/47655676/58744606-a74ccb00-8462-11e9-8090-0bc73e6ddb19.png)

**Comment by AllanFly120** [comment]
Hey @phanikumar252, you might need to setup the S3 bucket's CORS config. Please refer to [this](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) document for more information. Let me know if you have set up them.

**Comment by phanikumar252** [comment]
ok @AllanFly120 , Thank you. I have already set up the CORS config. on S3 bucket anyhow i will check once and let you know.

**Comment by MehulBhatt45** [comment]
Hello @phanikumar252, I am also facing this issue when I am trying to list my folders from the bucket. I have already set up the CORS config in the bucket. But it still returning 403 Forbidden error.
