### ISSUE TITLE
Cannot read metadata from send email response

### ISSUE THREAD

**Issue by ORESoftware** [aws/aws-sdk-js#2696]
I have this:

```js
  return new AWS.SES({apiVersion: '2010-12-01'}).sendEmail(params).promise().then(console.log);
```

and I get this result:

```js
    {
      ResponseMetadata: [Object],
      MessageId: '0101016b24a7d404-32084805-c3b0-4152-be67-9432840330cb-000000'
    },
```

so I can't read the response metadata - any chance I get access to the response stream or http headers or anything?

**Comment by ajredniwja** [comment]
@ORESoftware is this still a persisting issue?

Closing this issue for now, please reach out if you have any questions.
