### ISSUE TITLE
use aws sts api with minio server and long-term user credentials

### ISSUE THREAD

**Issue by thomaslange24** [aws/aws-sdk-js#2697]
Hi, I am a bit confused about how to use sts in the aws-sdk-js. I have a minio server for which i want to get temporary security credentials using the credentials of a user i created previously. But i am not sure how to do that. I have the endpoint for the minio server "http://hostname:9000", username "demouser" and userpassword "demouser123". The user is connected to a policy that allows him to call PuObject() or GetObject() on a specific bucket. Now i want to get temporary security credentials using the long-term user credentials. This should kind of inherit the underlying policy of the user. How should i invoce the AWS.STS.getSessionToken() or AWS.STS.getFederationToken() function to achieve this?

**Comment by ajredniwja** [comment]
Hey @thomaslange24,

Thank-you for reaching out to us with your issue.

[Here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) is a complete guide with working examples that you can use for your specific case. 

Please reach out if you have any additional questions.
