### ISSUE TITLE
How to use sts.getFederationToken() with specific endpoint and longterm user credentials

### ISSUE THREAD

**Issue by thomaslange24** [aws/aws-sdk-js#2703]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I would like to get temporary security creddentials for my s3 compatible object storage using aws-sdk sts api. I am pretty new to javascript and aws-sdk. So i think sts.getFederationToken() is the right function to achieve that. Or maybe assumeRoel()? What confuses me is, that in the examples there is no specific endpoint and credentials set for accessing this api. So how do i use this when i want to address a specific endpoint with usercredentials i created before and receive temporary security credentials connected to the same policy as the long-term user used to call this function?

**Comment by thomaslange24** [comment]
for the user i just have the credentials. username and password.

**Comment by ajredniwja** [comment]
Hey @thomaslange24,

Thank-you for reaching out to us with your issue.

[Here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html#using-temp-creds-sdk) is a complete guide and an example written in python as well.

Please reach out if you have any additional questions.
