### ISSUE TITLE
CognitoIdentityServiceProvider.updateUserPool EmailSendingAccount and TemporaryPasswordValidityDays

### ISSUE THREAD

**Issue by mikvix** [aws/aws-sdk-js#2704]
**Describe the bug**
Cannot use the  CognitoIdentityServiceProvider.updateUserPool function to set EmailSendingAccount and TemporaryPasswordValidityDays.

It fails with error:
Unexpected key 'EmailSendingAccount' found in params.EmailConfiguration
and/or Unexpected key 'TemporaryPasswordValidityDays' found in params.Policies.PasswordPolicy

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v10.16.0

**SDK version number**
v2.470.0

**Expected behavior**
As far as I understood on this page https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html, I think it should be possible to update these fields properly, but maybe I missed something?

**Comment by trivikr** [comment]
As per [CognitoIdentityServiceProvider.updateUserPool documentation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html), `EmailConfiguration` takes the following values:
```
{ 
    "EmailSendingAccount": "string",
    "ReplyToEmailAddress": "string",
    "SourceArn": "string"
}
``` 

and Policies takes the following values:
```
{ 
  "PasswordPolicy": { 
    "MinimumLength": number,
    "RequireLowercase": boolean,
    "RequireNumbers": boolean,
    "RequireSymbols": boolean,
    "RequireUppercase": boolean,
    "TemporaryPasswordValidityDays": number
  }
}
```

The error received by @mikvix is:
* Unexpected key 'EmailSendingAccount' found in params.EmailConfiguration
* Unexpected key 'TemporaryPasswordValidityDays' found in params.Policies.PasswordPolicy

**Comment by trivikr** [comment]
As per AWS JS SDK documentation for [updateUserPool](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#updateUserPool-property), the following params are accepted:
* `EmailConfiguration.EmailSendingAccount`
* `Policies.PasswordPolicy.TemporaryPasswordValidityDays`

@mikvix Can you share the code you're running?

**Comment by mikvix** [comment]
Please find below the code I'm running.
The code works well when I remove TemporaryPasswordValidityDays and EmailSendingAccount, but when I use one or both of these keys, I get the "unexpected key" error message.

```
            let params: AWS.CognitoIdentityServiceProvider.UpdateUserPoolRequest = {
            UserPoolId: this.userPoolId,
            Policies: {
                PasswordPolicy: {
                    MinimumLength: CognitoService.MIN_PASSWORD_LENGTH,
                    RequireLowercase: true,
                    RequireNumbers: true,
                    RequireSymbols: false,
                    RequireUppercase: true,
                    TemporaryPasswordValidityDays: 30
                }
            },
            AutoVerifiedAttributes: ["email"],
            VerificationMessageTemplate: { 
                EmailSubject: verificationMessage.subject,
                EmailMessage: verificationMessage.body,
                DefaultEmailOption: "CONFIRM_WITH_CODE"
            },
            AdminCreateUserConfig: { 
                AllowAdminCreateUserOnly: false,
                InviteMessageTemplate: {
                    EmailSubject: invitationMessage.subject,
                    EmailMessage: invitationMessage.body,
                    SMSMessage: '{username} : {####}'
                }
            }
        };

        if(emailFrom) {
            params.EmailConfiguration = {
                SourceArn: `${process.env.SIMPLE_EMAIL_SERVICE_ARN}/${emailFrom}`,
                ReplyToEmailAddress: emailReplyTo,
                EmailSendingAccount: "DEVELOPER"
            }
        }
        
        await this.cognitoClient.updateUserPool(params).promise();
```

**Comment by trivikr** [comment]
The types from AWS SDK JS source code for function updateUserPool:
https://github.com/aws/aws-sdk-js/blob/4e239651cf2002466d41c2ec1277c82b481b509d/clients/cognitoidentityserviceprovider.d.ts#L777

The type of params is `CognitoIdentityServiceProvider.Types.UpdateUserPoolRequest` whose code can be viewed at https://github.com/aws/aws-sdk-js/blob/4e239651cf2002466d41c2ec1277c82b481b509d/clients/cognitoidentityserviceprovider.d.ts#L3859

Confirmed that `EmailConfigurationType` has `EmailSendingAccount`
https://github.com/aws/aws-sdk-js/blob/4e239651cf2002466d41c2ec1277c82b481b509d/clients/cognitoidentityserviceprovider.d.ts#L2304

Confirmed that `UserPoolPolicyType` has `PasswordPolicyType` which has `TemporaryPasswordValidityDays` https://github.com/aws/aws-sdk-js/blob/4e239651cf2002466d41c2ec1277c82b481b509d/clients/cognitoidentityserviceprovider.d.ts#L3094

**Comment by trivikr** [comment]
@mikvix Are you running this on Lambda?
If yes, I think your AWS version is `v2.437.0` as documented [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)

Can you confirm the AWS version by either:
* running command `npm list aws-sdk` from your root directory
* printing the output of `AWS.VERSION` in your code where `AWS = require("aws-sdk");`

**Comment by trivikr** [comment]
The parameter `EmailSendingAccount` is not present in `EmailConfigurationType` for v2.437.0 which is used by Lambda https://github.com/aws/aws-sdk-js/blob/36161b75ac9f3419269cf10ac78745d589aa4f75/clients/cognitoidentityserviceprovider.d.ts#L2276-L2285

**Comment by mikvix** [comment]
Oh ok, my code is running on lambda yes. So I need to wait until the AWS SDK runtime on lambda gets updated to be able to update these attributes.
Thank you very much for these explanations @trivikr !
