### ISSUE TITLE
cognitoIdentityService listUsers has Attributes.  adminGetUser has UserAttributes

### ISSUE THREAD

**Issue by pszabop** [aws/aws-sdk-js#2705]
**Describe the bug**
`cognitoIdentityService.listUsers` returns the user attributes as `Attributes`
`cognitoIdentityService.adminGetUser` returns the user attributes as `UserAttributes`

This makes comparing the two results with a deep compare not match, and makes it so one has to write wrapper functions to patch up the data structures to make them equivalent, for example when one wants to display the results using the same widget.

**Is the issue in the browser/Node.js?**
Both

**Details of the browser/Node.js version**
irrelevant

**SDK version number**
2.467.0

**To Reproduce (observed behavior)**
```
let username = `foo@example.com`;

let adminParams  = {
    Username: username,
    UserPoolId: cftOutputs.cognitoUserPool,
};

let adminData = await cognitoIdp.adminGetUser(adminParams).promise();

let findParams = {
    Filter: `username = \"${username}\"`,
    UserPoolId: cftOutputs.cognitoUserPool,
};

let let listData = await cog.listUsers(findParams).promise();
let foundUser = findData.Users[0];

assert(_.isEqual(adminData, foundUser); // fails
```

**Expected behavior**
The user data structure returned by `adminGetUser` and `listUsers` should be identical for the same user.

**Additional context**
The following patches up the data structure for the `listUser` results to he identical to the `adminGetUser` results:
```
foundUser.UserAttributes = foundUser.Attributes
delete foundUser.Attributes;
assert(_.isEqual(adminData, foundUser);   // succeeds
```

**Comment by trivikr** [comment]
Confirmed that the Response Syntax of User array of ListUsers and AdminGetUser is similar in the documentation:
* [ListUsers](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsers.html#API_ListUsers_ResponseSyntax)
* [AdminGetUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminGetUser.html#API_AdminGetUser_ResponseSyntax)

In the types file:
* adminGetUser returns Request<CognitoIdentityServiceProvider.Types.AdminGetUserResponse, AWSError> https://github.com/aws/aws-sdk-js/blob/3f1e54f1da1b3a87f8ec19c8bb32ac1e66a7be75/clients/cognitoidentityserviceprovider.d.ts#L105
  * AdminGetUserResponse is a type of it's own https://github.com/aws/aws-sdk-js/blob/3f1e54f1da1b3a87f8ec19c8bb32ac1e66a7be75/clients/cognitoidentityserviceprovider.d.ts#L1052-L1089
* listUsers returns Request<CognitoIdentityServiceProvider.Types.ListUsersResponse, AWSError> https://github.com/aws/aws-sdk-js/blob/3f1e54f1da1b3a87f8ec19c8bb32ac1e66a7be75/clients/cognitoidentityserviceprovider.d.ts#L105
  * Users array is of type UsersListType https://github.com/aws/aws-sdk-js/blob/3f1e54f1da1b3a87f8ec19c8bb32ac1e66a7be75/clients/cognitoidentityserviceprovider.d.ts#L2970-L2979

**Comment by ajredniwja** [comment]
@pszabop,

Closing this issue now, please re-open if you have any further questions.
