### ISSUE TITLE
Upload directory

### ISSUE THREAD

**Issue by RamK777** [aws/aws-sdk-js#2707]
why there is no api's to sync whole folder to aws-sdk in javascript. 

And how to upload a whole directory to s3 without using old school recursive for loop, is there any sync methods present in js sdk ?

If there no way to sync directory to s3 means , is there any way to upload multiple files at same time, because i have thousands of files with large size inside directory , so uploading one by one is too slow 

so how to do it ?

**Comment by AllanFly120** [comment]
Hey @RamK777 

Unfortunately JS SDK doesn't support this use case, you can refer to my [answer elsewhere](https://github.com/aws/aws-sdk-js/issues/2665#issuecomment-491875673) for the solutions to it.

**Comment by RamK777** [comment]
Ok, in future is there any plan ?

**Comment by AllanFly120** [comment]
@RamK777 Unfortunately it's not in our short-term plan. But we constantly re-evaluate the feature requests, it might get prioritized if we see further feature request for it.
