### ISSUE TITLE
Removing a thing from a dynamic group

### ISSUE THREAD

**Issue by janpoltan** [aws/aws-sdk-js#2709]
**Describe the bug**
Removing a thing from a dynamic group produces an error, but actually removes the thing from the dynamic group

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
Node 8.10

**SDK version number**
2.471.0

**Expected behavior**
It shouldnt throw an error

**Comment by ajredniwja** [comment]
Hey @janpoltan,

Apologies for late reply, are you still facing the issue?

Can you please share the minimal code to reproduce the issue?
