### ISSUE TITLE
Update ApiGateway stage using Javascript SDK

### ISSUE THREAD

**Issue by romafederico** [aws/aws-sdk-js#2710]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Doing the following using a lambda gives me a success message but the newly created deployment is not promoted to *current* deployment. What am I doing wrong?

```
const updateStage = apigateway.updateStage({
    restApiId: apiId,
    stageName: target,
    patchOperations: {
        op: "replace",
        path: "/deploymentId",
        value: deploymentId
    }
})
console.log("updateStage")
await Promise.resolve(updateStage)
    .then(response => {
        console.log("STAGE UPDATED", response)
    })
```

**Comment by ajredniwja** [comment]
Hey @romafederico, thank-you for reaching out to us with your issue and apologies for late reply, can you please make sure you are using the latest version of the SDK?

You can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

Please reach out if that doesn't solves the problem.
