### ISSUE TITLE
SNS tagResource and createTopic Tags not supported

### ISSUE THREAD

**Issue by LosD** [aws/aws-sdk-js#2712]
**Describe the bug**
When trying to tag SNS topics, it fails.

When using the Tags attribute in `SNS.createTopic`, the reported error message is
``` JSON
{
    "message": "Unexpected key 'Tags' found in params",
    "code": "UnexpectedParameter",
    "time": "2019-06-13T09:45:13.169Z"
}
```

When using `tagResource`, the SDK will throws this message instead: `TypeError: this.sns.tagResource is not a function`

**Is the issue in the browser/Node.js?**
Node.js (Lambda nodejs10.x)

**Details of the browser/Node.js version**

Node.js 10 | nodejs10.x | 10.15 | 2.437.0 | Amazon Linux 2
-- | -- | -- | -- | --

**SDK version number**
2.437.0

**To Reproduce (observed behavior)**

As part of `SNS.createTopic`:
``` TypeScript
const sns = new AWS.SNS({
    apiVersion: '2010-03-31'
});

await sns.createTopic({
  Name: 'some-topic',
  Tags: [{
    Key: 'some-tag',
    Value: 'some-value'
  }],
  Attributes: {
    DisplayName: 'some-display-name'
  }
}).promise();
```

As part of `SNS.tagResource`:
``` TypeScript
const sns = new AWS.SNS({
    apiVersion: '2010-03-31'
});
await this.sns.tagResource({
  ResourceArn: 'arn:aws:sns:some-region:some-accountid:some-topic',
  Tags: [{
    Key: 'some-tag',
    Value: 'some-value'
  }]
}).promise();
```

**Expected behavior**
Tags added. No errors

**Additional context**
The latest API version is from 2010, so I guess the problem is internal to the JS SDK (Or tags are REALLY underused for SNS topics :smile:)

TypeScript typechecking accepted the code without issue, so I don't think it's a mistake I made (though I cannot promise I didn't make any mistakes when converting to the reproduction code).
In the reproduction I used async/await for the promisified version in TypeScript, just in case any of that matters (which also means that it's not possible to just grab as-is without pushing into an async function, sorry about that).

**Comment by ajredniwja** [comment]
Hey @LosD,

Apologies for late reply, are you still facing the issue?

**Comment by LosD** [comment]
Hi @ajredniwja, I'm not sure, haven't tried since. I'll try again when I get to work, then I'll get back to you.

**Comment by LosD** [comment]
Tested again, and it works now. I'll close the issue :)
