### ISSUE TITLE
Files, images, PDFs corrupted and can not be opened.

### ISSUE THREAD

**Issue by tsdmrfth** [aws/aws-sdk-js#2713]
```
    s3Params.Key = `${request.user._id}/${uuid()}.${fileExtension}`
    s3Params.ContentType = contentType

    s3.getSignedUrl('putObject', s3Params, (error, uploadURL) => {
        if (error) {
            message.meta = error
            return response.status(500).send(message)
        }

        message.response = {
            uploadURL,
            key: s3Params.Key
        }
        response.status(200).send(message)
    })
```

I have an application which is written in React Native. I am trying to upload files to s3 with first calling getSignedURL like the above and then requesting the signedURL with FormData api. Some people say don't use FormData. I have tried to send file as base64 but still images are corrupted. I spent 2 days for this issue with many solutions but still could not solve it. Please help!

**Comment by tsdmrfth** [comment]
Is there any one who can help me?

**Comment by enesccinar** [comment]
Same issue. Please help!!

**Comment by trivikr** [comment]
@tsdmrfth What's the error you're getting?

**Comment by tsdmrfth** [comment]
@trivikr If I try to open image after downloading it from our s3 bucket I see this 
<img width="532" alt="Screen Shot 2019-06-19 at 12 05 15" src="https://user-images.githubusercontent.com/27639087/59752253-b0270480-928a-11e9-8d67-61261fb590ab.png">
then  if i try to open it as a text file some different header have been added to file

```
--PGg50W7gGlgD8RRok5RMQDo1iwR07KWKF7bYxMNvMtAg9tuCY5NKjUyplsBXeM-Or2qrN8
content-disposition: form-data; name="file"

file:///var/mobile/Containers/Data/Application/6F2F0297-458E-4755-8D1B-01AEEE6A2782/tmp/A8BD82D5-D5D0-4DAF-AEBE-4866A589BA41.jpg
--PGg50W7gGlgD8RRok5RMQDo1iwR07KWKF7bYxMNvMtAg9tuCY5NKjUyplsBXeM-Or2qrN8--
```

**Comment by ajredniwja** [comment]
Hey @tsdmrfth,

Thank-you for reaching out, this may happen when you are not using the correct params for the ```body```. You can refer to the comment [here](https://github.com/aws/aws-sdk-js/issues/396#issuecomment-60500661-permalink). 

Please reopen if this doesn't solve the problem and follow the [issue template](https://github.com/aws/aws-sdk-js/issues/new/choose) to re-open the issue.
