### ISSUE TITLE
How do I put AWS SDK for JavaScript into my AWS Java Web App Project in Eclipse with AWS Toolkit?

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [aws/aws-sdk-js#2715]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

How do I use AWS SDK for JavaScript with Eclipse using AWS Toolkit? I would like to use AWS SDK for JavaScript with my AWS Java Web App Project. How do I get the AWS SDK for JavaScript in Eclipse or in the project? Help->Install New Software doesn't seem to allow me to import the sdk that way.

**Comment by ajredniwja** [comment]
Hey @Shinehah-Gnolaum,

Thank-you for reaching out, you can use the [Set up guide](https://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/setup-install.html) to set up the the toolkit for eclipse IDE. 

Closing the issue now, please re open if you have any additional questions.
