### ISSUE TITLE
Optional callback incorrectly marked as optional

### ISSUE THREAD

**Issue by sdegutis** [aws/aws-sdk-js#2716]
This `doneCallback?` should simply be `doneCallback`. Adding an "optional" says to the function consumer that this may sometimes be undefined, when in fact it is always defined. Consumers of this function can just omit that optional parameter from their function definition, and TypeScript will not complain.

**Comment by sdegutis** [comment]
This issue was supposed to reference this line:

https://github.com/aws/aws-sdk-js/blob/master/lib/request.d.ts#L32

I clicked the ellipsis button on that line, clicked "Reference in New Issue" and assumed GitHub had a special way of associating this issue to that line, but don't see it anywhere.

**Comment by trivikr** [comment]
donCallback is optional as per documentation https://github.com/aws/aws-sdk-js/blob/c1fe5ba80142ac78eefb8e59c3e17c8f5663d848/lib/request.js#L478-L481

Is there something missing here?

**Comment by sdegutis** [comment]
Optional has two meanings:

a. The outer function might not give it to the inner function:

```typescript
function callback(done) {
  done!() // the ! is necessary in TypeScript since done may be undefined
}

function done() { /*...*/ }
callback(Math.random() < 0.5 ? done : undefined);
```

This is not the meaning intended by the documentation.

b. The outer function always gives it, but the inner function need not consume it:

```typescript
function callback() {
  // done is omitted from parameter list, but TypeScript allows that without type errors
}

function done() { /*...*/ }
callback(done);

// also, callback.length === 0 meaning it takes no parameters, so the line above could conditionally check, like so:

if (callback.length === 1) {
  const done = createAndPrepareAsyncDoneFn();
  callback(done);
}
else {
  const result = callback(); // use the result immediately
}

// the above is roughly equivalent code to what AWS.util.fn.makeAsync is doing.
```

This is the meaning intended by the AWS SDK documentation.

Thus the `?` should be removed.
