### ISSUE TITLE
SSM getParametersByPath doesn't return the parameter with certain words combination into the name

### ISSUE THREAD

**Issue by guilhermepozo** [aws/aws-sdk-js#2717]
**Describe the bug**
SDK doesn't return a parameter by path when I create with the name "/stage/leopardo/table-to-register-slot".

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v10.15.3

**SDK version number**
2.469.0

**To Reproduce (observed behavior)**
At first you must create the bellow parameters into AWS SSM 's service:
/stage/leopardo/table-to-slot-register	
/stage/leopardo/table-to-register_slot	
/stage/leopardo/table-to-register-slots	
/stage/leopardo/table-to-register-slot-	
/stage/leopardo/table-to-register-slot	
/stage/leopardo/table-to-register-slo	
/stage/leopardo/table-to-register-sl	
/stage/leopardo/table-to-register	
/stage/leopardo/table-to	

2 - Create a nodejs file to reproduce the behavior:

```
const AWS = require('aws-sdk');

const SSM_CLIENT = new AWS.SSM({
    apiVersion: '2014-11-06',
    accessKeyId: 'YOUR KEY',
    secretAccessKey: 'YOUR SECRET',
    region: 'YOUR REGION'
});

SSM_CLIENT.getParametersByPath({
    Path: '/stage/leopardo'
}, async (err, data) => {
    data.Parameters.map(param => {
        console.log(param.Name)
    });
})
```

OUTPUT (console.log):
/stage/leopardo/table-to
/stage/leopardo/table-to-register
/stage/leopardo/table-to-register-slot-
/stage/leopardo/table-to-register-slots
/stage/leopardo/table-to-slot-register

**Expected behavior**
OUTPUT (console.log):
/stage/leopardo/table-to-slot-register	
/stage/leopardo/table-to-register_slot	
/stage/leopardo/table-to-register-slots	
/stage/leopardo/table-to-register-slot-	
/stage/leopardo/table-to-register-slot	
/stage/leopardo/table-to-register-slo	
/stage/leopardo/table-to-register-sl	
/stage/leopardo/table-to-register	
/stage/leopardo/table-to	

**Screenshots**
![image](https://user-images.githubusercontent.com/18023489/59464523-07e2ed00-8dff-11e9-9759-5115cdbe84cc.png)
![export](https://user-images.githubusercontent.com/18023489/59464888-01a14080-8e00-11e9-88ab-8789222b6b44.png)

**Additional context**
This issue exist with this words combination/hierarchies, but can exist more examples/combinations.

EDIT (trivikr): added code inside code block

**Comment by AllanFly120** [comment]
Hey @guilhermepozo 

I tried the exact input you shared here but I cannot reproduce the issue. I created all the parameters using JS SDK `v2.485.0`'s `ssmm.putParameter()` API.

Can you remove all the existing parameters and create the parameters using SDK again?

**Comment by sharkguto** [comment]
Using awscli is working properly @guilhermepozo. You should try to upgrade you node sdk version :)

```
aws ssm get-parameters-by-path --path "/PRD/system_x" --region sa-east-1
{
    "Parameters": [
        {
            "Name": "/PRD/system_x/branch",
            "Type": "String",
            "Value": "master",
            "Version": 1,
            "LastModifiedDate": 1561628107.246,
            "ARN": "arn:aws:ssm:sa-east-1:xxxxxxxxxxxx:parameter/PRD/system_x/branch"
        },
...
```
