### ISSUE TITLE
AWS authorizer header case sensitive

### ISSUE THREAD

**Issue by anu-pareek** [aws/aws-sdk-js#2719]
Confirm by changing [ ] to [x] below:
- [ x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

I have 2 stages setup on same AWS account. One endpoint is edge endpoint and another one is regional endpoint. 

If i send Authorization header as 'Authorization', they are received as 'Authorization' at both stage authorizer via lambda. 
However, if i send header as 'authorization', it gets converted into 'Authorization' for edge endpoint but regional endpoint gets it as 'authorization'.

I want to understand how AWS treats request headers while sending them to lambda/authorizer. Seems AWS is making changes in request headers based on some configuration.

**Comment by ajredniwja** [comment]
@anu-pareek Apologies for the late reply. 

This was a known issue with header mapping functionality.

Should be fixed now.

Closing this issue, please reach out if you have any additional questions.
