### ISSUE TITLE
PersonalizeRuntime not supported despite announced in release note 2.472.0

### ISSUE THREAD

**Issue by yudho** [aws/aws-sdk-js#2723]
**Describe the bug**
PersonalizeRuntime not supported despite announced in release note 2.472.0

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
    Chrome: 74.0.3729.169
    Firefox: 67.0

**SDK version number**
v2.476.0
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.476.0.min.js"></script>

**To Reproduce (observed behavior)**
1. Include the script tag in HTML for AWS JavaScript SDK v2.476.0
2. Run var personalizeruntime = new AWS.PersonalizeRuntime();

**Expected behavior**
That line executes successfully and I can start calling PersonalizeRuntime operations/APIs

**Screenshots**
Browser console shows "TypeError: AWS.PersonalizeRuntime is not a constructor"

**Additional context**
The JS file for JavaScript SDK v2.476.0 does not seem to include Amazon Personalize API definitions, despite announced in release note 2.472.0

**Comment by AllanFly120** [comment]
Hey @yudho 

I did a quick test I find this survice doesn't support CORS. So it won't be available from browsers or any other runtime has CORS restriction. But it's still available in NodeJS. 

I have informed the service team to add the CORS support to their service. Unfortunately this is not a client-side issue, it's hard to mititgate on client side. I will reply here when I hear back from the service team.

**Comment by yudho** [comment]
CORS might be supported now already.

The issue is, the js file does not have APIs description and definition for personalize

Please check https://sdk.amazonaws.com/js/aws-sdk-2.482.0.js from browser and try to search for "personalize", there is not constructor definition nor API definition

**Comment by ajredniwja** [comment]
@yudho CORS is supported now for PersonalizeRuntime you may have a look at [the code here](https://github.com/aws/aws-sdk-js/blob/master/apis/metadata.json#L730).
