### ISSUE TITLE
Cloudwatch event rule not firing to target until I click through configuration on aws website

### ISSUE THREAD

**Issue by wswoodruff** [aws/aws-sdk-js#2724]
**Describe the bug**
Cloudwatch event rule not firing to target until I click through configuration on aws website

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
Issue happens with Node v11.13.0 && v12.4.0

**SDK version number**
v2.472.0
CloudWatchEvents v'2015-10-07'

**To Reproduce (observed behavior)**
- Create rule with `await awsSdk.CloudWatchEvents.putRule(rule).promise()`
  - `rule` looks like
```js
{
    Name: eventType,
    ScheduleExpression: 'cron('0/1 * * * ? *')',
    State: 'ENABLED'
}
```

- Attach sqs queue target to same rule with `await awsSdk.CloudWatchEvents.putTargets(target).promise()`
  - `target` looks like
```js
{
    Rule: eventType,
    Targets: [
        {
            Arn: mySqsArn,
            Id: mySqsId,
            Input: JSON.stringify({ details: 'some new details' })
        }
    ]
}
```

- Visit your AWS console and start watching events on your sqs queue, in my experience they
do not appear.
- Goto cloudwatch event rules in the aws console and find the event you created with the sdk.
- Click through configuration of it, not changing any values and click `Update Rule`
- The event starts firing to the sqs target now.

**Expected behavior**
Expected events to fire to sqs queue soon after I
created the rule and attached the target.

Did not expect clicking through the aws console would get things to work.

I did notice in the network tab this request when clicking `Update Rule` that a
request got fired off to
`https://console.aws.amazon.com/cloudwatch/CloudWatch/data/jetstream.SaveRule/20190616192608512-7174986858131180`
that included both `Rule` and `Targets`(array)

with all the same arguments I use. I know that's not part of the sdk but that request
with the same args I use in the sdk makes things work.

**Comment by wswoodruff** [comment]
I've tried waiting up to a full minute in-between adding `targets` to my new `rule`, to the same effect

**Comment by wswoodruff** [comment]
Has anyone been able to create a cloudwatch rule programmatically and successfully attach a target to it?

**Comment by sameer73** [comment]
Iam also facing same issue, can anyone help

**Comment by sameer73** [comment]
`$result = $client->putRule(array(
	        'Name' => 'SEND_MESSAGE'.$rule_name, // REQUIRED
	        'ScheduleExpression' => 'cron('.$cron.')',
	        'State' => 'ENABLED',
	    ));

$json = json_encode(array('filename'=>$new_file));

$result2 = $client->putTargets([
        'Rule' => 'SEND_MESSAGE'.$rule_name, // REQUIRED
        'Targets' => [ // REQUIRED
            [
                'Arn' => 'arn:aws:lambda:ap-south-1:XXXXX:function:reads3', // REQUIRED
                'Id' => 'lambda_function', // REQUIRED
		'Input'=> $json
            ],
        ],
]);`

**Comment by epeli** [comment]
I'm having this issue too. Here the code I use to add the rule and the target:

```ts
const cloudwatchevents = new AWS.CloudWatchEvents();
const lambda = new AWS.Lambda();

const fn = await lambda.getFunction({FunctionName}).promise();

await cloudwatchevents
    .putRule({
        Name: RuleName,
        ScheduleExpression: "cron(0/5 * * * ? *)",
    })
    .promise();

const functionArn =
    fn.Configuration && fn.Configuration.FunctionArn
        ? fn.Configuration.FunctionArn
        : null;

if (!functionArn) {
    throw new Error("Cannot find ARN for " + FunctionName);
}

const target = await cloudwatchevents
    .putTargets({
        Rule: RuleName,
        Targets: [
            {
                Id: "value-search-timerm-handler-lambda",
                Arn: functionArn,
                Input: JSON.stringify({manual: 123}),
            },
        ],
    })
    .promise();
```

The Rule and the Target properly appears in the CloudWatch Management Console as enabled. But when I navigate to the Lambda definition the CloudWatch Rule does not appear in the Lambda designer. But when I choose edit Actions -> Edit from the CloudWatch Rule, change nothing and just press Update Rule then the Rule appears in the Lambda Designer too and actually starts working.

**Comment by epeli** [comment]
Finally figured it out. This was an user error for me at least. You must add the permission too for the lambda function.

```ts
    await lambda
        .addPermission({
            Action: "lambda:invokeFunction",
            FunctionName: functionArn, // note that ARN is acceptable for FunctionName
            StatementId: "allow-rule-invoke-" + RuleName,
            Principal: "events.amazonaws.com",
            SourceArn: rule.RuleArn,
        })
        .promise();
```

**Comment by ajredniwja** [comment]
Hey @wswoodruff,

Thank-you for reaching out. Can you try adding permission for the lambda function as mentioned by @epeli. Please feel free to reach out if you still have any questions.
