### ISSUE TITLE
Lambda retries when awaiting promise returned from AWS sdk calls

### ISSUE THREAD

**Issue by hisankaran** [aws/aws-sdk-js#2726]
**Describe the bug**
Lambda retries when awaiting promise returned from AWS sdk calls

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
Lambda nodejs8.10 runtime

**SDK version number**
2.290.0 (https://docs.aws.amazon.com/lambda/latest/dg/programming-model.html)

**To Reproduce (observed behavior)**
```
const handler: Handler = async (event: S3Event, context: Context) => {
  await s3.deleteObject({
    Bucket: record.s3.bucket.name,
    Key: record.s3.object.key,
  }).promise();
  return;
};

export { handler };
```

this simple object created event handler (async) is invoked multiple times with in milliseconds for a single event.

**Expected behavior**
promise retuned from AWS sdk calls should wait for the completion. no retry should be made when there is an ongoing execution.

**Screenshots**
NA

**Additional context**
This happens across all services. eg: ```await lambda.invoke().promise();```

**Comment by AllanFly120** [comment]
Hey @hisankaran 
Are you saying this lambda is triggered multiple times by a single event? It would be helpful if you share the CloudWatch log for this event.

**Comment by hisankaran** [comment]
Yes @AllanFly120, let me get the log for you.

**Comment by ajredniwja** [comment]
Hey @hisankaran,

Will close the issue if no response, please re-open and reach out if you have you anymore questions.
