### ISSUE TITLE
SQS Message typing for ReceiptHandle and MessageId properties could be tighter

### ISSUE THREAD

**Issue by putnamp** [aws/aws-sdk-js#2727]
**Is your feature request related to a problem? Please describe.**

I think it might be nice to specify the typing of the SQS Message interface a bit more rigidly, specifically around ReceiptHandle (and any other attributes that don't seem like they should ever be undefined or otherwise optional):

```
 export interface Message {
...
    /**
     * An identifier associated with the act of receiving the message. A new receipt handle is returned every time you receive a message. When deleting a message, you provide the last received receipt handle to delete the message.
     */
    ReceiptHandle?: String;
```

Because ReceiptHandle can be `undefined`, when I write code to receive messages I have to use a typeguard around the existence of the property, which adds unnecessary cyclomatic complexity. It also makes it more complicated for me to build fallbacks for releasing unused messages in the case of e.g. early program exit when I don't know for sure that a message object actually has a ReceiptHandle.

**Describe the solution you'd like**
I'd like ReceiptHandle to be typed as a required String property, rather than an Optional one.

**Describe alternatives you've considered**
I suppose there could be circumstances where a Message ID and Receipt Handle might not exist, depending on how the sdk is implemented, but it feels like we lose out on some of the benefits of typing by being so loose about the nature of these properties.

**Additional context**
n/a

**Comment by AllanFly120** [comment]
Hey @putnamp,

I agree these optional types are annoying. Unfortunately the TS types are generated from the service model shipped from the service team. You can reach out to service team on [their forum](on [their forum]()) to get this fixed.

**Comment by putnamp** [comment]
@AllanFly120 Thanks for the response, but the link you gave me just links back to my own post. Can you point me in the right direction? Appreciate it!
