### ISSUE TITLE
Textract - Unable to import module in AWS Lambda in Nodejs

### ISSUE THREAD

**Issue by charles-ascentic** [aws/aws-sdk-js#2728]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I am working with a lambda function which needs to use aws textract (`node: 8.10, aws-sdk-2.477.0`), when I tried to create an instance of AWS Textract, I am getting an error saying 

`Unable to import module 'src/functions/routes/handler': Error`

My Code,
```
const AWS = require('aws-sdk');
const s3 = new AWS.S3();
const Textract = new AWS.Textract({apiVersion: '2018-06-27'});
```
I even tried some other ways like importing the textract file manually, `const Textract = require('aws-sdk/clients/textract');` still the output is same not sure what is the problem, I [asked some questions](https://stackoverflow.com/questions/56656555/unable-to-import-module-error-in-aws-lambda-nodejs) in the stackoverflow and in the gitter, but didn't got any answers. Any suggestions are appreciated.

**Comment by trivikr** [comment]
Please create a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) under Bug report.
The template has some questions which would be help debug/resolve this issue
