### ISSUE TITLE
SES custom endpoint signature is invalid

### ISSUE THREAD

**Issue by ryanoolala** [aws/aws-sdk-js#2729]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Using a custom endpoint URL for SES will result in invalid signature or 401 error

I've created a SES object as follows
```
 SES: new SES({
      apiVersion: '2010-12-01',
      endpoint: url,
      region,
      accessKeyId,
      secretAccessKey,
      signatureVersion: 'v4',
    }),
```
With `url` as a custom endpoint, say `https://myownserver.doman.com` as i have to send my API request through another web server for routing purposes. This webserver will then forward my request to `https://email.us-west-2.amazonaws.com`

However when this happens, i receive the following error message from amazonaws, 
`SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

I've verified that my credentials are correct as when url is instead `https://email.us-west-2.amazonaws.com`, my email will be sent successfully. Therefore i've narrowed the error down to the Host itself. I understand that V4 signature does not input host/endpoint url into the signature generation(correct me if i'm wrong, i can't find any reference in the code that shows otherwise) however amazon ses is verifying the signature using a fixed hostname based on the region, `email.us-west-2.amazonaws.com` to verify signatures?

In another experiment, i've explicitly set my Host headers from the web server.
url as `https://myownserver.doman.com`, and request.headers Host as `myownserver.doman.com` to see if SES will verify the signature using my custom host instead. 
What i receive in the end was a 401, null error message. Which is not something i could find as a documented error code, nor any other use cases that are similar to mine. 
```
{ e:
   { 401: null
       at Request.extractError ([REDACTED]/node_modules/aws-sdk/lib/protocol/query.js:55:29)
       at Request.callListeners ([REDACTED]/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
       at Request.emit ([REDACTED]/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
       at Request.emit ([REDACTED]/node_modules/aws-sdk/lib/request.js:683:14)
       at Request.transition ([REDACTED]/node_modules/aws-sdk/lib/request.js:22:10)
       at AcceptorStateMachine.runTo ([REDACTED]/node_modules/aws-sdk/lib/state_machine.js:14:12)
       at [REDACTED]/node_modules/aws-sdk/lib/state_machine.js:26:10
       at Request.<anonymous> ([REDACTED]/node_modules/aws-sdk/lib/request.js:38:9)
       at Request.<anonymous> ([REDACTED]/node_modules/aws-sdk/lib/request.js:685:12)
       at Request.callListeners ([REDACTED]/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
     message: null,
     code: 401,
     time: 2019-06-19T05:54:41.140Z,
     requestId: 'xxx',
     statusCode: 401,
     retryable: false,
     retryDelay: 6.681550808712666 } }

```

I've ran out of ideas to work around this now so i'm adding a post here, hopefully someone can advise me. Thank you :)

**Comment by AllanFly120** [comment]
Hey @ryanoolala 
The signature is generated from your custom endpoint string. So if your relay server forwards the request with the same signature but different endpoint string, you will get a mismatch between endpoint and signature. What you can do is making request and signing it as normal, and update the endpoint ofter signing the request. For example:

```javascript
const reqeust = ses.fooOperation(params);
request.on('sign', (request) => {
    request.httpRequest.endpoint.host = 'myownserver.doman.com';
});
request.send(callback);
```
In this way you signed the request as if you are sending to request to SES service. So when you relay the request to the different endpoint, the signature will match.
