### ISSUE TITLE
AWS STS compatible with any S3 Storage?

### ISSUE THREAD

**Issue by thomaslange24** [aws/aws-sdk-js#2730]
I want to use the aws sdk but be independent of the underlying s3 cloud storage. Currently i need to make use of AWS STS. For Minio i know that it supports Assume Role. But i am not sure whether other S3 storages like Dell ECS or Hitachi support it too. Do you know something about that?

**Comment by AllanFly120** [comment]
Hi @thomaslange24 

I'm not sure about Dell or Hitachi, but there are a bunch of [S3 compatible storage solution](https://www.google.com/search?q=s3+compatible+storage&rlz=1C5CHFA_enUS816US816&oq=s3+compat&aqs=chrome.0.0j69i57j69i61j0l3.2910j0j1&sourceid=chrome&ie=UTF-8) out there. I cannot guarantee that, but the S3 SDK client should be able to work with a subset of s3 operations provided by these providers, technically.
