### ISSUE TITLE
How to get real FragmentNumber from Kinesis Stream Server?

### ISSUE THREAD

**Issue by huynhtuanh** [aws/aws-sdk-js#2731]
**Describe the bug**
I've used aws-sdk.js with hls.js to show video from Amazone Kinesis Stream, it's working fine until some days ago. When HLS use getHLSMediaPlaylist request to get list of fragments from stream server, it returned a lists data with FragmentNumber from zero (0) like that:

> #EXTM3U
> #EXT-X-VERSION:7
> #EXT-X-TARGETDURATION:2
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-INDEPENDENT-SEGMENTS
> #EXT-X-DISCONTINUITY
> #EXT-X-MAP:URI="getMP4InitFragment.mp4?SessionToken=Ci...xkkNuJ1g~&TrackNumber=1"
> #EXTINF:1.01,
> getMP4MediaFragment.mp4?FragmentNumber=0&SessionToken=Ci...xkkNuJ1g~&TrackNumber=1
> #EXT-X-DISCONTINUITY
> #EXTINF:0.998,
> getMP4MediaFragment.mp4?FragmentNumber=1&SessionToken=CiCi...xkkNuJ1g~&TrackNumber=1

And we cannot use this number for any other command, ex: getMediaForFragmentList, because it's not real FragmentNumber.

Before, FragmentNumber was returned like that: "FragmentNumber": "91343852333181452204674451344167605934448957081" and everything worked fine.

I don't know why and when Kinesis apply this change and how I can get real fragment number as before?
Many thanks for any support :)

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
Chrome/Firefox

**SDK version number**
Version: <b>v2.478.0</b>

**To Reproduce (observed behavior)**
Go to this example site: https://aws-samples.github.io/amazon-kinesis-video-streams-hls-viewer/ 
Fill all expected value: stream name, secret key, access key... then click Start Playback 
View Network transfer data for detail.

**Screenshots**
https://drive.google.com/file/d/1GFTBSl7Z_iqFlL4YyBxAncNR-1LQMYpZ/view
<img src='https://drive.google.com/file/d/1GFTBSl7Z_iqFlL4YyBxAncNR-1LQMYpZ' alt='' />

**Comment by AllanFly120** [comment]
Hey @huynhtuanh,

Sorry, I'm not very familiar with HLS.js or Kinesis Video service. Can you should me your code snippet?What API are you calling? Is this an SDK client issue or Server side issue? 

From what I can see, this happens because Kinesis service returns an unexpected response. It's not because SDK parses it incorrectly right?

**Comment by huynhtuanh** [comment]
Thank you so much, @AllanFly120
