### ISSUE TITLE
S3 File Upload fails in Safari Browser (Zero Bytes Length) Using cognito-identity.amazonaws.com

### ISSUE THREAD

**Issue by pramod-salian-k** [aws/aws-sdk-js#2738]
Hi All,

I have used aws javascript sdk in my Angular 7 Project

My AWS SDK version :  2.403.0

I created simple html with input type file tag, i'm uploading chosen file to my S3 Bucket though cognito identity pools. 
What problem i'm facing?
Below code works fine in all browser but not in Safari browser, my application running in https mode, it uploads file (docx, images, pdf) to s3 bucket but stores as empty content(zero bytes). If i change my application url to http mode, then it works fine even in Safari browser with exact content uploads to S3 Bucket. Problem is, if applications runs in https mode safari fails to upload exact content to s3 bucket.

Here is my upload code
```javascript

return new Promise((resolve, reject) => {
      this.getAwsCognitoToken().then(({ data }) => {
        const cognitoData = data.getAwsCognitoToken;
        // configure conginto Identity
        config.update({
          region: cognitoData.region,
          credentials: new CognitoIdentityCredentials({
            IdentityPoolId: APP_CONSTANT.aws.identityPoolId,
            IdentityId: cognitoData.identityId,
            Logins: {
              'cognito-identity.amazonaws.com': cognitoData.cognitoToken
            }
          })
        });

        // check profile image or docs
        const folder = (docType ? cognitoData.documentDirectory : cognitoData.profileImageDirectory);

        // configure s3
        const s3 = new S3({
          apiVersion: '2006-03-01',
        });

        const buf = file;   // event.target.files[0] this i'm collected from html input type file using change event listener

        // file upload params
        const params = {
          Bucket: cognitoData.bucket,
          Key: folder + Guid.create() + '-' + 
              file.name.substring(file.name.lastIndexOf('/') + 1),
          Body: buf,
          // ACL: 'public-read'
        };
        // push to s3 server
        s3.upload(params, function (err: any, response: any) {
          if (err) {
            return reject(err);
          }
          if (response) {
            return resolve(response);
          }
        });

      }).catch((error) => {
        return reject(error);
      });
    });
```

**Comment by jayeshanandani** [comment]
experiencing the exact same issue.

**Comment by pramod-salian-k** [comment]
I got quick solution we need to disable service worker in angular.json
 "serviceWorker": false

then app.module.ts we need to comment service worker code

**Comment by AllanFly120** [comment]
@pramod-salian-k Thank you for this information! It will be helpful if you can share a reproduce repository so that we can get our hands on to figuring out whether this is caused by SDK.

**Comment by pramod-salian-k** [comment]
How can i escape aws s3 api calls from Angular Service Worker?

**Comment by pramod-salian-k** [comment]
Multipart Upload fails in IOS Safari browser if in angular service worker enbaled

**Comment by trivikr** [comment]
@pramod-salian-k Can you share a minimal repo or code to reproduce this issue?

**Comment by bkarv** [comment]
I can confirm I am experiencing the same problem for my hybrid app which uses Ionic 4.7.2 which uses angular 8.2.0. I have service workers enabled. Using Chrome browser no issues uploading but when I use desktop safari browser it uploads files with 0kb. 

Has anyone found a solution without disabling service workers?

**Comment by bkarv** [comment]
I can confirm @pramod-salian-k point if you disable service workers in angular, then uploading in safari works without error. Therefore angular service workers is causing the issue with the AWS SDK JS functionality but only in Safari. 

@trivikr I would share my minimal repo but the issue is there are private S3 credentials. Is there a sandbox S3 you can PM so I can share a repo with you based on this?

**Comment by bkarv** [comment]
Ok did some digging around. It looks like others using firebase uploads also are having the same issue when angular service worker is enabled and in safari. See below:

https://github.com/angular/angular/issues/23244

Seems like the workaround is to bypass the service worker when doing the S3 call. There is a feature here below to bypass:

https://angular.io/guide/service-worker-devops

> To bypass the service worker you can set ngsw-bypass as a request header, or as a query parameter. (The value of the header or query parameter is ignored and can be empty or omitted.)

Implementation of bypass here:
https://github.com/angular/angular/pull/30010

I tried doing the following in aws call:
```

this.bucket
          .on('build', (req) =>{ req.httpRequest.headers['ngsw-bypass']})
          .on('httpUploadProgress', (progress) => {
                 // progress code    
          })
          .send((err, data) => {
          //success response
        },
        err => {
        })
```

Still getting the issue. Any suggestion on how I can have implement the bypass feature for AWS s3 upload calls?

**Comment by bkarv** [comment]
Ok found the solution. As my previous comment angular service worker is causing the issue. There is an option to bypass service by adding 'ngsw-bypass'. However I did not find a way to add custom headers to S3.manageUploads ('build' method only applies to putObject). 

Therefore only work around is to manually add the following code AFTER build to the ngsw-worker.js file. 

Under onFetch(event) function add the following after const declarations:

`if (req.method==="PUT" && requestUrlObj.origin.indexOf('amazonaws.com')>-1){return;}`

It should look like this:
```
        /**
         * The handler for fetch events.
         *
         * This is the transition point between the synchronous event handler and the
         * asynchronous execution that eventually resolves for respondWith() and waitUntil().
         */
        onFetch(event) {
            const req = event.request;
            const scopeUrl = this.scope.registration.scope;
            const requestUrlObj = this.adapter.parseUrl(req.url, scopeUrl);
            if (req.method==="PUT" && requestUrlObj.origin.indexOf('amazonaws.com')>-1){return;}
            if (req.headers.has('ngsw-bypass') || /[?&]ngsw-bypass(?:[=&]|$)/i.test(requestUrlObj.search)) {
                return;
            }
            ....
```

Alternatively you can also add the following INSTEAD:
`if (req.method==="PUT" || !!req.headers.get('range')) return;`

For my project there is no need for PUT methods to go through service workers hence I am using the latter code as this also should avoid other issues such as video/audio not properly playing in Safari. More information on this see below:
https://github.com/angular/angular/issues/25865#issuecomment-443187935
https://philna.sh/blog/2018/10/23/service-workers-beware-safaris-range-request/

If anyone knows how to automate this during the build please let me know. but at least it is a solution now.

**Comment by ajredniwja** [comment]
@pramod-salian-k,

Is it possible for you to try the solution that @bkarv suggested? 

I would like to close the issue if no one has any further questions.
