### ISSUE TITLE
putBucketWebsite should not require RoutingRules, RedirectAllRequestsTo, or ErrorDocument

### ISSUE THREAD

**Issue by notslang** [aws/aws-sdk-js#274]
I'm trying to call `putBucketWebsite` with this configuration:

``` js
{
  Bucket: this._config.bucket,
  WebsiteConfiguration: {
    IndexDocument: {
      Suffix: 'index.html'
    }
  }
}
```

Using the Amazon S3 Console I can set just the `IndexDocument` without setting anything else. But when I call `putBucketWebsite` with only the configuration above, it throws `TypeError: Cannot read property 'hostname' of undefined`.

Also, according to @joshrowley, this worked in a previous version. I can't pin down the commit that caused this to break, though... perhaps d3763005de35eca3b49605dc448917858515761f?

**Comment by saadtazi** [comment]
@slang800 : I got stuck with the same issue.. The problem I had:
I was using [bluebird](https://github.com/petkaantonov/bluebird) `promisify` (which seams similar to `nodefn.call` from when.js) but I forgot to bind the method:

```
// this does not work and throw an exception "TypeError: Cannot read property 'hostname' of undefined"
var rawCreateBucket = Promise.promisify(bucket.createBucket);

// this works
var rawCreateBucket = Promise.promisify(bucket.createBucket.bind(bucket));
```

I hope it helps...
