### ISSUE TITLE
Documentation request for apiConfig when used for non-AWS endpoint

### ISSUE THREAD

**Issue by tvogel8570** [aws/aws-sdk-js#2740]
**Goal**
I want to minimize the external dependencies in my Lambda code (node.js) as much as possible.  I expect this to reduce the size, increase the speed and minimize regression when external libraries change.  

**Background**
My solution needs to call external to AWS REST endpoints, retrieve the results and do further processing on those requests.  I hope to use the AWS SDK method Service() to accomplish this rather than requiring the request nodejs module.

**Specific request**
I have been able to do a simple get with parameters but do not know the full capability as the constructor parameter (apiConfig) is only well documented for AWS services.  Please enhance / expand the documentation for Service constructor with full explanation of the apiConfig parameter and give comprehensive examples of calling external APIs.

**Comment by AllanFly120** [comment]
Hi @tvogel8570 

By `apiConfig`, do you mean [this](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html)? Other than API reference, we also have AWS doc available for configuring the SDK like [here](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/configuring-the-jssdk.html). We are always open to make our document better. Can you elaborate what kind of explanation on apiConfig parameter you like to see?

Actually API Gateway service(if you are using them), support generating JavaScript SDK from your custom API, here is the [doc](https://docs.aws.amazon.com/apigateway/latest/developerguide/genearte-javascript-sdk-of-an-api.html).

**Comment by tvogel8570** [comment]
Allan,
  Thanks for your quick response, I've been on holiday which delayed my response.

  I want to use AWS.Service to access **non**-AWS resources that are exposed as a REST API.    This will allow my Lambda functions to not require the node package Request which is quite large with all of its dependencies.  The apiConfig I'm referring to is the map parameter to the AWS.Service constructor that is [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Service.html#constructor-property).

The simple case is explained in this [blog post](https://boylesoftware.com/blog/calling-restful-apis-from-inline-aws-lambda-functions/) by Lev Gimelfarb.  In it he shows building a map to define the external API, passing it to ` new AWS.Service(apiConfig) ` and using a GET request against a REST API from Tibco.  As he notes, this is not documented (I confirmed with a developer support case).  I started reading the source files as he suggested but it is slow going.  

  Basic documentation would be a list of each option and possible values that can be sent into the AWS.Service constructor.  Ideal documentation would include examples of non-trivial use cases.  POST, PATCH, DELETE with authentication (Basic and JWT), body/headers with application/x-www-form-urlencoded, etc.

Thanks for considering my request!

**Comment by AllanFly120** [comment]
Hey @tvogel8570,

I think you meant documenting how to construct a service model, right? This is a model standard used to describe all the AWS services. You can find all of them in our [apis folder](https://github.com/aws/aws-sdk-js/tree/master/apis). All the files with `xxx-date.normal.json` name are service model. So you already have 160+ examples. Although these models are shared in all AWS SDKs and public every where, its syntax is not open-sourced/documented yet. 

But its interface is pretty stable, if you can find example from any existing service model, the SDK is able to support them.

**Comment by tvogel8570** [comment]
Allan,
  Thanks for the follow-up.  I'm currently on a UI sprint but have added researching this to a spike.

  I'll give you feedback in a couple of weeks.
Tim

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ajredniwja** [comment]
Closing this issue, because of lack of response.
