### ISSUE TITLE
React Native and AWS-SDK compatible versions?

### ISSUE THREAD

**Issue by Anshu8405** [aws/aws-sdk-js#2743]
![Screen Shot 2019-06-26 at 2 15 09 PM](https://user-images.githubusercontent.com/46955191/60165433-e5989880-981c-11e9-8ebb-430a5c28fbf0.png)

When running it from Xcode - build was successful but after 2 to 3 minutes it producing an error when I imported aws-sdk.

`import AWS from 'aws-sdk/dist/aws-sdk-react-native';
`

Error is looking like this
![Simulator Screen Shot - iPhone 6 - 2019-06-26 at 14 18 25](https://user-images.githubusercontent.com/46955191/60165779-8edf8e80-981d-11e9-92b7-1260a4118696.png)

![Screen Shot 2019-06-26 at 2 27 20 PM](https://user-images.githubusercontent.com/46955191/60166349-a408ed00-981e-11e9-8fbc-0a8410f81d26.png)

Previously I tried with old react native version there it worked.

`"aws-sdk": "^2.266.1",
    "react": "16.3.1",
    "react-native": "0.55.4"
`

But with new react native version of 0.59.9, it does not work.
How to solve this can anyone help?

**Comment by webmasterdragon** [comment]
Hi. I have same issue. Any solution?

**Comment by AllanFly120** [comment]
Hey @Anshu8405 Maybe you can refer to the discussion in #1877 and [my comment](https://github.com/aws/aws-sdk-js/issues/1877#issuecomment-357587472). An workaround is to increase the stack size.
