### ISSUE TITLE
S3 key and bucket vs uri conversion

### ISSUE THREAD

**Issue by renatomariscal** [aws/aws-sdk-js#2745]
**Is your feature request related to a problem? Please describe.**

S3 objects are represented as `Bucket` and `Key` in aws-sdk-js.
In `aws-cli` and  maybe other places, they it is represented as `s3://${Bucket$}/${Key}`.

Because of that, in our code we have multiple places doing the conversion.

**Describe the solution you'd like**
Expose a short helper function doing the conversion, ie:
```typescript
function uriToParams(uri: string): { Bucket: string, Key: string } {
    const matches = /(?:s3:\/\/)?([^/]+)\/(.*)/.exec(uri);
    if (!matches) {
        throw new AWSError(`Received invalid uri: '${uri}'`);
    }
    const params = {
        Bucket: matches[1],
        Key: matches[2],
    };

    return params;
}

function paramsToUri(params: { Bucket: string, Key: string }): string {
    return `s3://${params.Bucket}/${params.Key}`;
}
```

**Describe alternatives you've considered**

AWS.S3 functions to accept:
```typescript
{ Bucket:string, Key:string } | { uri: 'string' }
```

But I see value on having just a single way to pass the target object, accepting both kinds could cause confusion and extra complexity, like having to handle the situation of a sdk user passing both simultaneously.

**Additional context**
(none)

**Comment by mostafazh** [comment]
This feature is already in Java and .NET SDKs. At least someone built an [npm package](https://www.npmjs.com/package/amazon-s3-uri) just for that. I wish this was already part of the AWS SDK.
