### ISSUE TITLE
PutObjectLockConfiguration: Malformed XML Error

### ISSUE THREAD

**Issue by ycryptx** [aws/aws-sdk-js#2747]
My client: 
```
   const cli = new S3({
      signatureVersion: 'v4',
      apiVersion: '2006-03-01',
      region: process.env.AWS_REGION,
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
    })
```

The parameters for the request:
```
const params = { 
  Bucket: '5d15e6c6398528323b86db98',
  ObjectLockConfiguration:
     { ObjectLockEnabled: 'Enabled',
       Rule:
          { DefaultRetention: { Days: 3, Mode: 'COMPLIANCE', Years: 0 } } },
  }

params.ContentMD5 = hasha(JSON.stringify(params), { algorithm: 'md5' })
```

The call:
`await cli.putObjectLockConfiguration(params).promise()`

The error I'm getting:
```
  message:
   'The XML you provided was not well-formed or did not validate against our published schema',
  code: 'MalformedXML',
```

Also, my AWS_ACCES_KEY_ID  has AmazonS3FullAccess permissions set.
I'm getting this error even if I don't attach a ContentMD5 header. I'm following the [documentation here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObjectLockConfiguration-property)

**Comment by ycryptx** [comment]
The issue is with specifying 0 in the year/date and specifying both year AND date. It's only allowed to use 1 of these fields

**Comment by AllanFly120** [comment]
Looks like the request body is not recognized by service. Can you show what the request body looks like? You can print it by:

```javascript
const request = cli.putObjectLockConfiguration(params);
request.on('sign', (req) => {
    console.log('request body: ', req.httpRequest.body.toString());
});
await request.promise();
```
