### ISSUE TITLE
IamRole ValidationException in SSM createActivation

### ISSUE THREAD

**Issue by chunfengd** [aws/aws-sdk-js#2748]
**Describe the bug**
Got validation error when calling ssm.createActivation.

code:
```js
const AWS = require('aws-sdk');
const ssm = getSSM({ region: 'us-east-1' });
ssm.createActivation({
  IamRole: 'service-role/AmazonEC2RunCommandRoleForManagedInstances'
}, (...args) => console.log(args));
```

Error:
```
{ ValidationException: 1 validation error detected: Value 'service-role/AmazonEC2RunCommandRoleForManagedInstances' at 'iamRole' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[\p{L}\p{N}+=,.@\-_]*$
      at Request.extractError (/tetrascience/ts-service-datahub/node_modules/aws-sdk/lib/protocol/json.js:51:27)
      at Request.callListeners (/tetrascience/ts-service-datahub/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/tetrascience/ts-service-datahub/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/tetrascience/ts-service-datahub/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/tetrascience/ts-service-datahub/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/tetrascience/ts-service-datahub/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /tetrascience/ts-service-datahub/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/tetrascience/ts-service-datahub/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/tetrascience/ts-service-datahub/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/tetrascience/ts-service-datahub/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    message:
     '1 validation error detected: Value \'service-role/AmazonEC2RunCommandRoleForManagedInstances\' at \'iamRole\' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[\\p{L}\\p{N}+=,.@\\-_]*$',
    code: 'ValidationException',
    time: 2019-06-28T15:12:53.630Z,
    requestId: '4f10020c-8acd-470c-ade3-89d2046bb07c',
    statusCode: 400,
    retryable: false,
    retryDelay: 4.082470922819459 }
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v10.13.0

**SDK version number**
2.484.0

**To Reproduce (observed behavior)**
see the description

**Expected behavior**
No error.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by trivikr** [comment]
The error is:
```
1 validation error detected: Value \'service-role/AmazonEC2RunCommandRoleForManagedInstances\' at \'iamRole\' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[\\p{L}\\p{N}+=,.@\\-_]*$
```

This happens because incorrect `IamRole` is being passed in the following line:
```
IamRole: 'service-role/AmazonEC2RunCommandRoleForManagedInstances'
```

More info about [IAM roles](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html)

**Comment by chunfengd** [comment]
`service-role/AmazonEC2RunCommandRoleForManagedInstances` is a IAM role under the path `service-role`. I don't know how to specify the role name without using `/`. I tried `AmazonEC2RunCommandRoleForManagedInstances`, but it didn't work.

Based on the reference of AWS SSM API, there is no regex pattern constraint on the IamRole parameter. (https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateActivation.html)

**Comment by AllanFly120** [comment]
Hey @chunfengd 

From the stack trace I find the regex validation is returned from the server side(`at Request.extractError(XXX)`). This is not validated on client side within the SDK. Please check your configuration. If you have further question, you can reach out to the [SSM forum](https://forums.aws.amazon.com/forum.jspa?forumID=185)

**Comment by chunfengd** [comment]
> Hey @chunfengd
> 
> From the stack trace I find the regex validation is returned from the server side(`at Request.extractError(XXX)`). This is not validated on client side within the SDK. Please check your configuration. If you have further question, you can reach out to the [SSM forum](https://forums.aws.amazon.com/forum.jspa?forumID=185)

Thank you! @AllanFly120 I'll ask in the SSM forum.
