### ISSUE TITLE
Incorrect return type for .promise() methods on ecs task definitions

### ISSUE THREAD

**Issue by mjdavidson** [aws/aws-sdk-js#2750]
**Describe the bug**
When you add .promise to the end of ecs.registerTaskDefinition() and ecs.describeTaskDefinition() the return type is that of the callback definitions

**Is the issue in the browser/Node.js?**

**Details of the browser/Node.js version**
e v10.16.0

**SDK version number**
aws-sdk@2.478.0

**Comment by trivikr** [comment]
@mjdavidson Can you provide a sample code to repro this issue?

**Comment by mjdavidson** [comment]
https://github.com/dymajo/waka-server/blob/master/src/waka-orchestrator/adaptors/gatewayEcs.ts#L99..L101

![Screenshot from 2019-07-09 11-20-26](https://user-images.githubusercontent.com/12488396/60852605-b7af4d00-a23b-11e9-8a7a-6a4a5f8cd860.png)

**Comment by AllanFly120** [comment]
Hey @mjdavidson, can you show what your `taskDefinition.taskDefinition` looks like?

**Comment by mjdavidson** [comment]
it's of type:  AWS.ECS.TaskDefinition

**Comment by AllanFly120** [comment]
@mjdavidson  Are you still seeing this issue? Sometimes the intellisense doesn't infer the type overload correctly. But the compile can still complete.
