### ISSUE TITLE
Unable to copy using Aws sdk multi-part upload.

### ISSUE THREAD

**Issue by LamaBimal** [aws/aws-sdk-js#2754]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Currently, i am using copyObject to copy file from s3 to s3. Is there any way to use multipart upload from s3 Bucket to s3 Bucket in js?.

I have found the implementation on Java
https://docs.aws.amazon.com/AmazonS3/latest/dev/CopyingObjctsUsingLLJavaMPUapi.html

I am looking for the similar cases in aws sdk js, 

Since, Copy Files from S3 to S3 Bucket is performing by lambda function. I am unable to download and upload respectively. 

I like to direct copy with multipart from s3 Bucket to another Bucket.

I am getting error in copyObject method for large file size.
Could you please suggest in this scenario?

**Comment by AllanFly120** [comment]
Hi @LamaBimal 

Thank you for bringing this up. For JS SDK, with process is almost identical to Java SDK. Here the the code snippet I put together which is a interpretion of the Java code in the example:

```javascript
  const s3 = new aws.S3({region: 'us-west-2'});
  try {
    const {UploadId} = await s3.createMultipartUpload({
      Bucket: destBucket,
      Key: destKey
    }).promise();
  
    const {ContentLength} = await s3.headObject({
      Bucket: sourceBucket,
      Key: sourceKey
    }).promise();
  
    const partSize = 5 * 1024 * 1024 //Copy the object using 5 MB parts
    let bytePosition = 0;
    let partNum = 1;
    const copyRequests = [];
    while (bytePosition < ContentLength) {
      // The last part might be smaller than partSize, so check to make sure
      // that lastByte isn't beyond the end of the object.
      const lastByte = Math.min(bytePosition + partSize - 1, ContentLength - 1);
  
      // Copy this part
      const localPartNum = partNum;
      copyRequests.push(s3.uploadPartCopy({
        CopySource: `/${sourceBucket}/${sourceKey}`,
        Bucket: destBucket,
        Key: destKey,
        UploadId: UploadId,
        CopySourceRange: `bytes=${bytePosition}-${lastByte}`,
        PartNumber: partNum++
      }).promise().then(copyResponses => [copyResponses, localPartNum]));
      bytePosition += partSize;
    }
  
    const copyResponses = await Promise.all(copyRequests);
    const partETags = copyResponses.map(copyResponse => {
      return {
        ETag: copyResponse[0].CopyPartResult.ETag,
        PartNumber: copyResponse[1]
      }
    });

    //Complete the upload request to concatenate all uploaded parts and make the copied object available
    await s3.completeMultipartUpload({
      Bucket: destBucket,
      Key: destKey,
      MultipartUpload: {
        Parts: partETags
      },
      UploadId: UploadId
    }).promise();
    console.log('Multipart copy complete.');
  } catch(e) {
    console.log(e);
  }
```

**Comment by LamaBimal** [comment]
It works. Thanks @AllanFly120 . Closing this issue.
