### ISSUE TITLE
Mediaconvert error when using QvbrSettings parameter 

### ISSUE THREAD

**Issue by MaxQuezada** [aws/aws-sdk-js#2755]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I am receiving the following error when using QvbrSettings:

<pre><code>Unknown parameter in Settings.OutputGroups[0].Outputs[0].VideoDescription.CodecSettings.H264Settings: "qvbrSettings", must be one of: AdaptiveQuantization, Bitrate, CodecLevel, CodecProfile, EntropyEncoding, FieldEncoding, FlickerAdaptiveQuantization, FramerateControl, FramerateConversionAlgorithm, FramerateDenominator, FramerateNumerator, GopBReference, GopClosedCadence, GopSize, GopSizeUnits, HrdBufferInitialFillPercentage, HrdBufferSize, InterlaceMode, MaxBitrate, MinIInterval, NumberBFramesBetweenReferenceFrames, NumberReferenceFrames, ParControl, ParDenominator, ParNumerator, QualityTuningLevel, RateControlMode, RepeatPps, SceneChangeDetect, Slices, SlowPal, Softness, SpatialAdaptiveQuantization, Syntax, Telecine, TemporalAdaptiveQuantization, UnregisteredSeiTimecode</code></pre>

Per the aws sdk documentation the syntax should be correct 
https://docs.aws.amazon.com/mediaconvert/latest/apireference/jobtemplates.html#jobtemplates-model-h264qvbrsettings

So my question is, has anyone run in to a similar issue or could this be a be a bug?

Here is a snippet of what I'm talking about.

```json
"OutputGroups": [
      {
        "CustomName": "cengage",
        "Name": "Convert Group",
        "Outputs": [
          {
            "ContainerSettings": {
              "Container": "MP4",
              "Mp4Settings": {
                "CslgAtom": "INCLUDE",
                "FreeSpaceBox": "EXCLUDE",
                "MoovPlacement": "PROGRESSIVE_DOWNLOAD"
              }
            },
            "VideoDescription": {
              "Width": 320,
              "ScalingBehavior": "DEFAULT",
              "Height": 180,
              "TimecodeInsertion": "DISABLED",
              "AntiAlias": "ENABLED",
              "Sharpness": 50,
              "CodecSettings": {
                "Codec": "H_264",
                "H264Settings": {
                  "InterlaceMode": "PROGRESSIVE",
                  "NumberReferenceFrames": 3,
                  "Syntax": "DEFAULT",
                  "Softness": 0,
                  "FramerateDenominator": 1,
                  "GopClosedCadence": 1,
                  "GopSize": 3,
                  "Slices": 1,
                  "GopBReference": "DISABLED",
                  "MaxBitrate": 200000,
                  "SlowPal": "DISABLED",
                  "SpatialAdaptiveQuantization": "ENABLED",
                  "TemporalAdaptiveQuantization": "ENABLED",
                  "FlickerAdaptiveQuantization": "DISABLED",
                  "EntropyEncoding": "CABAC",
                  "FramerateControl": "SPECIFIED",
                  "RateControlMode": "QVBR",
                  "QvbrSettings": {
                    "QvbrQualityLevel": 7
                  },
                  "CodecProfile": "MAIN",
                  "Telecine": "NONE",
                  "FramerateNumerator": 15,
                  "MinIInterval": 0,
                  "AdaptiveQuantization": "HIGH",
                  "CodecLevel": "AUTO",
                  "FieldEncoding": "PAFF",
                  "SceneChangeDetect": "ENABLED",
                  "QualityTuningLevel": "SINGLE_PASS_HQ",
                  "FramerateConversionAlgorithm": "DUPLICATE_DROP",
                  "UnregisteredSeiTimecode": "DISABLED",
                  "GopSizeUnits": "SECONDS",
                  "ParControl": "INITIALIZE_FROM_SOURCE",
                  "NumberBFramesBetweenReferenceFrames": 2,
                  "RepeatPps": "DISABLED",
                  "DynamicSubGop": "STATIC"
                }
              },
```

**Comment by AllanFly120** [comment]
@MaxQuezada My guess is that you are using old SDK version and trying to request a newer API version. Can you try install the newest version of SDK and see if the issue persists.

**Comment by MaxQuezada** [comment]
That seemed to be the issue. Thanks for the help!
