### ISSUE TITLE
Typescript: Keys are upper cased typed but object comes lower cased

### ISSUE THREAD

**Issue by kwskii** [aws/aws-sdk-js#2756]
**Describe the bug**
Hey there,

It seems that when I get an event from SQS or even S3 all the keys are lower cased in reality which creates a problem when I try to type them since the definitions call for upper cased keys.

E.g. An event I got inside of a lambda function when triggered by an SQS message.

![image](https://user-images.githubusercontent.com/10780503/60617746-39f5c800-9d89-11e9-9137-6ca203536620.png)

And by typing it as SQS.Message it's expected to have :
```
 export interface Message {
    /**
     * A unique identifier for the message. A MessageIdis considered unique across all AWS accounts for an extended period of time.
     */
    MessageId?: String;
    /**
     * An identifier associated with the act of receiving the message. A new receipt handle is returned every time you receive a message. When deleting a message, you provide the last received receipt handle to delete the message.
     */
    ReceiptHandle?: String;
    /**
     * An MD5 digest of the non-URL-encoded message body string.
     */
    MD5OfBody?: String;
    /**
     * The message's contents (not URL-encoded).
     */
    Body?: String;
    /**
     * A map of the attributes requested in  ReceiveMessage  to their respective values. Supported attributes:    ApproximateReceiveCount     ApproximateFirstReceiveTimestamp     MessageDeduplicationId     MessageGroupId     SenderId     SentTimestamp     SequenceNumber     ApproximateFirstReceiveTimestamp and SentTimestamp are each returned as an integer representing the epoch time in milliseconds.
     */
    Attributes?: MessageSystemAttributeMap;
    /**
     * An MD5 digest of the non-URL-encoded message attribute string. You can use this attribute to verify that Amazon SQS received the message correctly. Amazon SQS URL-decodes the message before creating the MD5 digest. For information about MD5, see RFC1321.
     */
    MD5OfMessageAttributes?: String;
    /**
     * Each message attribute consists of a Name, Type, and Value. For more information, see Amazon SQS Message Attributes in the Amazon Simple Queue Service Developer Guide.
     */
    MessageAttributes?: MessageBodyAttributeMap;
  }
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
I will run this on AWS Lambda but I am including the latest aws-sdk and packing it from node

**Details of the browser/Node.js version**
v10.14.2

**SDK version number**
"2.487.0"

**Comment by AllanFly120** [comment]
Hey @kwskii,

The lambda event from event sources like SQS, S3 or SNS doesn't inline with corresponding API input interface. So you should not expect the event is the same shape as the SDK typings. For example, in your example, the input event has `eventSource` but it is not typed in `SQS.Message`.
