### ISSUE TITLE
AWS Lambda to S3 NodeJS image upload failure with no result

### ISSUE THREAD

**Issue by arahant** [aws/aws-sdk-js#2758]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

In my NodeJS program, I'm generating a very small image, converitng it into a Byte stream, and uploading it to my S3 bucket.
When I `npm start` and run it on my local system, to test it out, it works fine, and the upload happens as normal. But, on AWS, when the modules are invoked through Lambda functions, there are no results - neither any positive result or error. So, I'm not able to diagnose what the problem is.

**Comment by trivikr** [comment]
@arahant Can you share some sample code to reproduce the issue?

**Comment by arahant** [comment]
Thanks for replying, but I solved it.
It was due to a UnhandledPromiseRejection error.
