### ISSUE TITLE
Rekognition. MaxFaces. Unexpected key "MaxFaces" found in params

### ISSUE THREAD

**Issue by o-alexandrov** [aws/aws-sdk-js#2760]
**Describe the bug**
The MaxFaces param doesn't process.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes, we are.

**Details of the browser/Node.js version**
Lambda node's version is 8.10

**SDK version number**
- `v2.395.0`, however, we don't bundle SDK together with the Lambda function that has the code below. Therefore, we use the version of the SDK that's provided by the Lambda Node.js 8.10 function.

**To Reproduce (observed behavior)**
```ts
  const params = {
    CollectionId: "someid",
    Image: {
      S3Object: {
        Bucket: "bucket-name",
        Name: "object-name",
      },
    },
    MaxFaces: 1,
    DetectionAttributes: [],
    ExternalImageId: "someid",
  }

  const rekognitionPromise = rekognition.indexFaces(params).promise()
  const data = await rekognitionPromise
```
- Results in:
  - `Unexpected key "MaxFaces" found in params`

**Expected behavior**
- `MaxFaces` work (unfortunately, it doesn't)

**Comment by AllanFly120** [comment]
Hey @o-alexandrov 

Node8.1 runtime in Lambda still bundles `v2.290.0` SDK according to [this doc](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). Unfortunately you might need to bundle the newest SDK with you code to make use of this new API. You can refer to [this guidance](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html) about how to do it.

**Comment by o-alexandrov** [comment]
@AllanFly120 
Hey, yes, fixed the issue by using the `nodejs 10.x` runtime, fortunately, nothing else broke when upgrading :)a
