### ISSUE TITLE
Convert the source to TS?

### ISSUE THREAD

**Issue by ORESoftware** [aws/aws-sdk-js#2762]
I am impressed by this library - especially that the types are in sync with the JS code.
I am looking in the lib/ dir and the source appears to be written in .js not .ts. Just curious how you keep the types in sync and if you plan to convert the .js to .ts?

**Comment by trivikr** [comment]
The next major version update (called v3) is in Typescript
Repository: https://github.com/aws/aws-sdk-js-v3

**Comment by ORESoftware** [comment]
that is beautiful, bravo ty
