### ISSUE TITLE
AWS Elastic search: ES is not a constructor

### ISSUE THREAD

**Issue by ashwinthakre91** [aws/aws-sdk-js#2763]
**Describe the bug**

I have import node module aws-sdk as npm. Able to access services like S3. However not able to access ES(elastic search). Getting error like ES is not constructor. I am using Angular 7. However getting this error in all versions of Angular.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Browser - Chrome
Node.js - 10.15.3
Angular - 7

**SDK version number**
v2.490.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo):
```javascript
import { Component } from '@angular/core';
import {ES} from 'aws-sdk';
import {S3} from 'aws-sdk';

const es = new ES();
const s3 = new S3();
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'my-dream-app';
  constructor() {
    console.log(s3);
  }
}
```

Error:
```console
AppComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: AWS.ES is not a constructor
at new AppComponent (app.component.ts:15)
at createClass (core.js:27851)
at createDirectiveInstance (core.js:27673)
at createViewNodes (core.js:38309)
```

**Expected behavior**
It should not throw and error.

**Screenshots**
![](https://user-images.githubusercontent.com/17229061/61112567-c4d17380-a4a9-11e9-8eb2-64f4429a4782.png)

**Additional context**
N/A

EDIT(trivikr):
* Re-added questions from template
* Populated answers from https://github.com/aws/aws-sdk-js/issues/2763#issuecomment-510791928

**Comment by trivikr** [comment]
@ashwinthakre91 I've re-added questions from [bug report template](https://github.com/aws/aws-sdk-js/blob/master/.github/ISSUE_TEMPLATE/---bug-report.md)
Can you please answer them so that we can debug the issue?

**Comment by ashwinthakre91** [comment]
Hi,
Sure by EOD will answer.


Regards,
Ashwin

**Comment by ashwinthakre91** [comment]
Describe the bug A clear and concise description of what the bug is.
I have import node module aws-sdk as npm. Able to access services like S3. However not able to access ES(elastic search). Getting error like ES is not constructor. I am using Angular 7. However getting this error in all versions of Angular.
Please find the code snippet in previous comment.



Is the issue in the browser/Node.js? Browser/Node.js
Node.js aws-sdk.js 

If on Node.js, are you running this on AWS Lambda?
No

Details of the browser/Node.js version 
Browser - Chrome
Node.js - 10.15.3
Angular - 7


SDK version number Example: v2.490.0


For Node.js, get SDK version by
running command npm install --save aws-sdk

printing the output of AWS.VERSION in your code where AWS = require("aws-sdk");
PRINTING VERSION
app.component.ts:14 2.490.0
AppComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: AWS.ES is not a constructor
    at new AppComponent (app.component.ts:15)
    at createClass (core.js:27851)
    at createDirectiveInstance (core.js:27673)
    at createViewNodes (core.js:38309)
    at createRootView (core.js:38181)
    at callWithDebugContext (core.js:39710)
    at Object.debugCreateRootView [as createRootView] (core.js:38947)
    at ComponentFactory_.create (core.js:26815)
    at ComponentFactoryBoundToModule.create (core.js:22779)
    at ApplicationRef.bootstrap (core.js:35337)
View_AppComponent_Host_0 @ AppComponent_Host.ngfactory.js? [sm]:1
proxyClass @ compiler.js:19436
logError @ core.js:39645
handleError @ core.js:9162
(anonymous) @ core.js:35060
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:34121
(anonymous) @ core.js:35057
invoke @ zone-evergreen.js:359
onInvoke @ core.js:34195
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:34176
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
then @ zone-evergreen.js:955
bootstrapModule @ core.js:34951
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
AppComponent_Host.ngfactory.js? [sm]:1 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 1, nodeDef: {…}, elDef: {…}, elView: {…}}
View_AppComponent_Host_0 @ AppComponent_Host.ngfactory.js? [sm]:1
proxyClass @ compiler.js:19436
logError @ core.js:39645
handleError @ core.js:9167
(anonymous) @ core.js:35060
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:34121
(anonymous) @ core.js:35057
invoke @ zone-evergreen.js:359
onInvoke @ core.js:34195
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:34176
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
then @ zone-evergreen.js:955
bootstrapModule @ core.js:34951
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
main.ts:12 TypeError: AWS.ES is not a constructor
    at new AppComponent (app.component.ts:15)
    at createClass (core.js:27851)
    at createDirectiveInstance (core.js:27673)
    at createViewNodes (core.js:38309)
    at createRootView (core.js:38181)
    at callWithDebugContext (core.js:39710)
    at Object.debugCreateRootView [as createRootView] (core.js:38947)
    at ComponentFactory_.create (core.js:26815)
    at ComponentFactoryBoundToModule.create (core.js:22779)
    at ApplicationRef.bootstrap (core.js:35337)
(anonymous) @ main.ts:12
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
then @ zone-evergreen.js:955
bootstrapModule @ core.js:34951
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
client:52 [WDS] Live Reloading enabled.


To Reproduce (observed behavior) Steps to reproduce the behavior (please share code or minimal repo)
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'my-dream-app';
  constructor() {
    const AWS = require('aws-sdk');
    const s3 = new AWS.S3(); // THIS IS WORKING FINE
    console.log('PRINTING VERSION');
    console.log(AWS.VERSION); // THIS IS GIVING VERSION NUMBER.
    const es = new AWS.ES(); // THIS IS GIVING ERROR
  }
}


Expected behavior A clear and concise description of what you expected to happen.
It should not throw and error.

Screenshots If applicable, add screenshots to help explain your problem.
![Screenshot (15)](https://user-images.githubusercontent.com/17229061/61112567-c4d17380-a4a9-11e9-8eb2-64f4429a4782.png)


Additional context Add any other context about the problem here.
Nothing

**Comment by AllanFly120** [comment]
Hey @ashwinthakre91,

The browser SDK only supports a subset of the AWS servies. Whether or not they are supported depends on wether the service supports [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). But you can still import the service by using [NPM package of AWS SDK](https://www.npmjs.com/package/aws-sdk) and import the service directly(e.g. `const ES = require('aws-sdk/clients/es')`);

Let us know if the service does work in browsers, so that we can update our scripts to support this service in our browser SDKs

**Comment by ashwinthakre91** [comment]
Its still giving the same error. However I have checked your library, although you are exporting ES variable. Then also its given above mention error. Can you please update it for ES.

**Comment by ashwinthakre91** [comment]
Again I have seen the code for elasticsearch in the npm package as like S3. Then also getting the above error.
