### ISSUE TITLE
AWS:EC2 - waitFor modifies the params argument

### ISSUE THREAD

**Issue by ryan65** [aws/aws-sdk-js#2764]
**Describe the bug**
When calling waitFor , after returning , the params argument has a new property called state.
This is incorrect behaviour a function should not change the the input arguments.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `AWS.VERSION` in your code where `AWS = require("aws-sdk");`

**To Reproduce (observed behavior)**
call waitFor('spotInstanceRequestFulfilled', params, cb)
params will have a new property called state

**Expected behavior**
params should not be modified, should always call AWS.util.copy(params) , 
not only if params.$waiter

**Screenshots**

**Additional context**
The problem with current behaviour is that if you want to make multiple calls to wait with same params you will fail second time with unexpected state property on params.
Although this can be handled by caller the correct way is that the waitFor should not modify the input.

EDIT(trivikr): Re-added questions from [bug report template](https://github.com/aws/aws-sdk-js/blob/master/.github/ISSUE_TEMPLATE/---bug-report.md)

**Comment by trivikr** [comment]
@ryan65 I've re-added questions from [bug report template](https://github.com/aws/aws-sdk-js/blob/master/.github/ISSUE_TEMPLATE/---bug-report.md)
Can you please answer them, so that we can debug this issue?

**Comment by ryan65** [comment]
1. this happens in version2.294 however I looked at master branch and the same issue appears . no changes were made there.
2. Ive gone through forums , no mention. 
3. I am not running this in Lambda , but locally on my server.

As mentioned, all that needs to be done is use a copy of the params instead of changing the original.

**Comment by ajredniwja** [comment]
Hey @ryan65,

Apologies for late reply, are you still facing the issue? Do you still see the issue if you switch to the latest version of the SDK?
