### ISSUE TITLE
Assume role circular reference hard crashes application

### ISSUE THREAD

**Issue by awschristou** [aws/aws-sdk-js#2767]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
If you have a circular reference of assume role profiles in your `credentials` file, the application hard crashes.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v10.15.1

**SDK version number**
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
aws-sdk@2.491.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

* set up `credentials` file as follows. Notice that `aaa-a` and `aaa-b` reference each other
```
[default]
aws_access_key_id = some_valid_id
aws_secret_access_key = some_valid_key

[aaa-a]
role_arn=some_valid_role
source_profile=aaa-b

[aaa-b]
role_arn=some_valid_role
source_profile=aaa-a
```
* Make sample app
  * `npm init`
  * `npm i --save 'aws-sdk'`
* Place this in `app.js`
```
const aws = require('aws-sdk')

try {
    const p = new aws.SharedIniFileCredentials({
        profile: 'default'
    })

    const b = new aws.SharedIniFileCredentials({
        profile: 'aaa-a'
    })

    console.log('done')
} catch (err) {
    console.log('err', err)
}
```
* Set a breakpoint on the assignment to `p`
* Debug the program (I used VS Code)
* You can step over the assignment to `p`
* Trying to step over the statement assigning to `b` hard exits the app

**Expected behavior**
An error should be thrown that I can catch. Program does not crash.

**Comment by AllanFly120** [comment]
Hey @awschristou 

I change it to feature request because this is currently not blocking customers product. Now if users config the cyclic assume role, the SDK will step into the loop and eventually crush. Instead of crushing the app, we should detect the circular reference before ahead of execution and raise an exception.

It would simpler if we set a limit on the size of the stack so users cannot define their assume roles with too many recurrence. Is it a good enough solution?

**Comment by awschristou** [comment]
Hi @AllanFly120  

It would be the most ideal to perform the cyclical reference detection. I see the AWS CLI does this (but I'm unsure if the check is being performed in the CLI or the Python SDK).

If you take the approach where you limit the number of `source_profile` hops allowed, I recommend making this configurable, so that developers can adjust if needed. This does feel like an awkward approach however.

**Comment by awschristou** [comment]
This feature request is still relevant.
