### ISSUE TITLE
Typings for AWS Lambdas

### ISSUE THREAD

**Issue by raybooysen** [aws/aws-sdk-js#2768]
**Is your feature request related to a problem? Please describe.**
It looks like typescript definitions for Lambdas are missing.  I've searched the tree and can't find anything that resembles lambda typings.

In `lambda.d.ts`, this seems more around the interaction with Lambda as a service and not the actual lambda itself.

For example, in the following Javascript: 
```
exports.handler = async (event: any, context: any) => {}
```
It would be nice to have types for `event` and `context`.

**Comment by AllanFly120** [comment]
Hey, @raybooysen 

Thank you for the feature request. I have forwarded it to the service team.

**Comment by ajhool** [comment]
It would also be nice to have subtypes for the various Event Triggers. @aws-lambda/types currently provides some of these, but an official type set would improve productivity tremendously.

**Comment by KingDarBoja** [comment]
As ajhool pointed out, there is a DefinitelyTyped package called [@types/aws-lambda](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/index.d.ts) which has almost all possible lambda definition organized by events.

Should be great if this were included as part of this SDK.
