### ISSUE TITLE
Change to ubuntu user from user data (bash script) while opening an instance of ec2 with nodejs aws sdk

### ISSUE THREAD

**Issue by shedon85** [aws/aws-sdk-js#2769]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I have opened an EC2 instance with node aws sdk, it is working well. but if I try in data user (bash script) to exit the superuser and change to ubuntu user I have no luck , I have tried:
su -s /bin/bash ubuntu also su - ubuntu and also exit..
the bash script is running and I check the system log. So my question is it possible to change user from the data user bash script. thanks.

**Comment by shedon85** [comment]
I have opened an EC2 instance with node aws sdk, it is working well. but if I try in data user (bash script) to exit the superuser and change to ubuntu user I have no luck , I have tried: 
 su -s /bin/bash ubuntu also su - ubuntu and also exit.. 
the bash script is running and I check the system log. So my question is it possible to change user from the data user bash script. thanks.

**Comment by ajredniwja** [comment]
Hey @shedon85,

Can you please check if your script permissions are set to 755 instead of 744 or 700.


Also as a superuser do something like
```
cp scriptname /home/ubuntu 
cd /home/ubuntu
chone :ubuntu scriptname
```

Make sure that your script mentions user to be ubuntu user otherwise it will just run as superuser. 

Apologies for the late reply.
