### ISSUE TITLE
Add custom headers support to SES sendEmail

### ISSUE THREAD

**Issue by jiripospisil** [aws/aws-sdk-js#2770]
Hello everybody!

**Is your feature request related to a problem? Please describe.**

The [ses.sendEmail](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendEmail-property) method is very convenient and it's all I need most of the time. Sometimes, however, I need to add a custom header. Instead of me just specifying this one single header in an option, I need to *completely* change the way I send the email and use [ses.sendRawEmail](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendRawEmail-property), which requires me to assemble the message myself. It's great when I need the flexibility but it's annoying to have to use it just because of a single header.

**Describe the solution you'd like**

I would like the ability to specify extra headers in the `ses.sendEmail` method.

```
const params = {
  ...
  headers: {
    "X-Foo": "bar"
  }
};

ses.sendEmail(params, ...)
```

**Describe alternatives you've considered**

The alternative is to use `ses.sendRawEmail` but it's much more involved and 99% of the time I just emulate what `ses.sendEmail` does plus I push a bunch of additional headers.

**Comment by AllanFly120** [comment]
Hey @jiripospisil,

Have you tried sending custome header with the request? You can do this via the [SDK event listeners](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#build-event) like this:

```javascript
const request = ses.sendEmail(params);//no calllbacks here
request.on('build', (req) => {
    req.httpRequest.headers['X-Foo'] = 'something'
});
request.send(callback);
```
If it doesn't work, you might need to submit this feature reqeust to the service team on [their forum](https://forums.aws.amazon.com/forum.jspa?forumID=90).
