### ISSUE TITLE
Error accessing AWS.SharedIniFileCredentials when credentials file does not exist

### ISSUE THREAD

**Issue by awschristou** [aws/aws-sdk-js#2771]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
If you have a `config` file and no `credentials` file, you get an ENOENT error against the `credentials` file when attempting to load a shared credential.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v10.15.1

**SDK version number**
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
aws-sdk@2.491.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

* Set up shared credentials
  * Set up a valid `config` file
  * Have no `credentials` file
* Try to access a profile with the SDK
  * from a typescript file, I have 
```
new AWS.SharedIniFileCredentials({profile: profileName})
```
* Error occurs

**Expected behavior**
SDK handles this without error.

**Comment by AllanFly120** [comment]
Hey @awschristou,
 
This is intentional. You need to set `AWS_SDK_LOAD_CONFIG` environmental variable to be able to load credentials from `config` file. This is due to some backwards compatibility concern, see #1391 for more information. 
 
If you don't set it, SDK will assume there is no `config` file when loading the credentials. That's why you see credentials loading failed.
