### ISSUE TITLE
Add support for programmatic access to AWS SSO

### ISSUE THREAD

**Issue by ORESoftware** [aws/aws-sdk-js#2772]
This request mirrors the one for AWS SSO support for the AWS CLI:
https://github.com/aws/aws-cli/issues/3447

**Comment by manwaring** [comment]
Any updates on this feature?  Having it implemented would allow libraries that are built on top of the aws-sdk support developers whose organizations user SSO for auth

**Comment by cboileau** [comment]
This is a huge headache for my organization. We use SSO for the dev team, and it's a huge pain to have to update files manually every time I need to run an app locally

**Comment by leventov** [comment]
Dear aws-sdk-js maintainers, could you please fix this issue?

**Comment by Js-Brecht** [comment]
I rolled my own.  The APIs are all there; they just aren't documented very well, and there's no tooling that makes it easy (or accurate) to retrieve sso credentials generated by the aws cli.

Mine pretty much does the same thing as `aws sso login`.  I use it for running automated processes in a repo that interfaces with AWS.  Works well... but it would still be nice to have first-class SSO support for 3rd party libraries.

**Comment by thomasmichaelwallace** [comment]
As a workaround, this project https://github.com/benkehoe/aws-sso-credential-process works as a pretty seamlessly- just watch out for https://github.com/aws/aws-sdk-js/issues/3436

**Comment by oscarmorasu** [comment]
Any ETA/comment/roadmap regarding this?

AWS SSO is an amazing feature. It made my life so much easier, but all the SDKs and tooling need to fully embrace it.

The [Go-SDK ](https://github.com/aws/aws-sdk-go/pull/3755) already supports it, and tooling working on top of it like Terraform are [also up to speed](https://github.com/hashicorp/terraform/issues/24133).

**Comment by thomasmichaelwallace** [comment]
Worth noting this isn't fixed in v3 (https://github.com/aws/aws-sdk-js-v3/issues/1158).

With zero knowledge of AWS' intentions, I would be surprised if it gets fixed in v2, however.

**Comment by eduardomourar** [comment]
There is a NPM library that has this functionality: https://github.com/mhlabs/aws-sdk-sso. I believe that can be easily moved to the AWS SDK v2. I am happy to create a PR if that makes sense to the maintainers.

**Comment by FelipeNascimento** [comment]
Any update for this issue?

**Comment by yannick-fernand** [comment]
any update ?

**Comment by samanrj** [comment]
Any updates...?

**Comment by FilipPyrek** [comment]
+1

**Comment by benkehoe** [comment]
@FilipPyrek If you react with the 👍 button to the original issue, (click on the smiley face if you're the first reacting), your votes can be used to sort issues and determine priorities.

A comment will send a notification to everyone (participants and watchers), but cannot be easily counted as a vote for an issue. Thus it's generally better to vote than to comment with "+1". To keep up to date, you can also add yourself as a watcher with the "subscribe" button in the sidebar.
