### ISSUE TITLE
`executeBatchStatement` requires at least one parameter in order to work

### ISSUE THREAD

**Issue by DennisSkoko** [aws/aws-sdk-js#2775]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When using `executeBatchStatement` method, it will not run the statement unless there is at least one parameter in `parameterSets`.

**Is the issue in the browser/Node.js?**
No

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
`v11.14.0`

**SDK version number**
Example: v2.493.0

**To Reproduce (observed behavior)**
Here is the minimal code required (but you will to execute in a RDS Cluster)
```js
const db = new RDSDataService({
  region: 'eu-west-1'
});

const params = {
  resourceArn: '***',
  secretArn: '***',
  sql: 'CREATE TABLE Test (id INT PRIMARY KEY)'
  // sql: 'Invalid SQL',
};

db.batchExecuteStatement(params, (err, data) => {
  if (err) console.error(err);
  else console.log(data);
});
```

**Expected behavior**
I expect the statement to be executed and see the table in database server.
If you execute the statement that contains invalid SQL then I expect an error saying that it contains invalid SQL.

**Additional context**
Currently this is not blocking since there is a ugly workaround to make this work.
If you execute the following, you will see that throws saying that it contains invalid SQL. If you execute the statement that creates the table, you will then see the created table in the database server.

```javascript
const db = new RDSDataService({
  region: 'eu-west-1'
});

const params = {
  resourceArn: '***',
  secretArn: '***',
  sql: 'CREATE TABLE Test (id INT PRIMARY KEY)'
  // sql: 'Invalid SQL',
  parameterSets: [
    [
      {
        name: 'asd',
        value: { stringValue: 'asd' }
      }
    ]
  ],
};

db.batchExecuteStatement(params, (err, data) => {
  if (err) console.error(err);
  else console.log(data);
});
```

**Comment by trivikr** [comment]
Findings:
* `parameterSets` are optional in RDSDataService types definitions
https://github.com/aws/aws-sdk-js/blob/6fe7600403eab919e401795e40806aa226f35fa7/clients/rdsdataservice.d.ts#L144
* They were added in v2.466.0 in commit https://github.com/aws/aws-sdk-js/commit/6fe7600403eab919e401795e40806aa226f35fa7

**Comment by trivikr** [comment]
I was not able to reproduce error, as the query ran without passing `parameterSets`
* node v10.16.0
* AWS.VERSION '2.494.0'

@DennisSkoko Can you share the error code you received on running `executeBatchStatement` without passing `parameterSets`?

**Comment by DennisSkoko** [comment]
Hi and thank you for your time.

When reading the description of my issue, I forgot to mention that when executing the function, it does not throw any error, even if I pass in invalid SQL syntax. I just tested on version `2.494.0` and it still does not work correctly. Maybe it is worth mentioning I have only tested on a serverless Aurora.

**Comment by DennisSkoko** [comment]
@trivikr

**Comment by trivikr** [comment]
@DennisSkoko Can you give more details about "does not work correctly"?

**Comment by DennisSkoko** [comment]
@trivikr If I run `executeBatchStatement` with an invalid SQL then it does not throw any error. I run for example `CREATE TABLE Test (id INT PRIMARY KEY)`, I will not see the table in the database.

**Comment by DennisSkoko** [comment]
@trivikr Maybe this helps, I wrote a quick Jest test for this. If I don't pass in `parameterSets`, I don't get the error. If I do, then the errors occurs and the test succeeds.

```js
it('rejects with an error message', () => {
  const db = new AWS.RDSDataService({ region: 'eu-west-1' })

  const result = db
    .batchExecuteStatement({
      resourceArn: ARN_DB,
      secretArn: ARN_SECRET,
      sql: 'Invalid sql and this should very much fail',
      // parameterSets: [[{ name: 'what', value: { isNull: true } }]]
    })
    .promise()

  return expect(result).rejects.toThrow('SQL syntax')
})
```

**Comment by DennisSkoko** [comment]
@trivikr I took some time to create a minimal repo that showcases the problem. https://github.com/DennisSkoko/aws-bug

**Comment by DennisSkoko** [comment]
@trivikr Have you had the time to look at the repo or the bug?

**Comment by stonstad** [comment]
I can reproduce this behavior.  My batchExecuteStatement calls do not run, return results, or throw errors unless a parameterset is included.  I use an empty set, as follows: params.parameterSets = [[]] as  work-around.

**Comment by ajredniwja** [comment]
Hey @DennisSkoko,

I will reach out to the RDSDate service team internally, and will update you once I get any more information on the issue from the team.

**Comment by DennisSkoko** [comment]
Hi, been wanted to add some additional information but been busy.

I just want to mention that I understand why we don't get a SQL syntax error and that is because that we don't pass in any parameters. If there are no parameters, we don't send anything to the database.

However I think there should be another error saying that no parameters are not set. Maybe making the `parameterSets` required and check that it contains at least one element in the array. Otherwise, from my perspective, it doesn't do what it is supposed do, which is executing statements.

Regards

**Comment by ajredniwja** [comment]
@DennisSkoko,

I heard back from the team and found that this is the expected behavior by the SDK which they will update in their documentation as well, the solution or the best practice would be,

- provide at least one empty parameter set 
- use ``` executeStatement ``` instead of ``` batchexecuteStatement ```

**Comment by stonstad** [comment]
### 

> @DennisSkoko,
> 
> I heard back from the team and found that this is the expected behavior by the SDK which they will update in their documentation as well, the solution or the best practice would be,
> 
> * provide at least one empty parameter set
> * use `executeStatement` instead of `batchexecuteStatement`

No way.  Here is why it absolutely is an error.  The API method does _not run, return results, or throw an error_.  That is not proper behavior for any API, regardless of documented preconditions.  I assume you have actual software developers working on this project and not total hacks.

**Comment by returnzer0** [comment]
Wow, I can't believe that this isn't documented at all. I wasted quite a lot of time trying to figure out why my executeBatch statements were never going through. This should be documented in the official docs until an actual patch has been implemented.
