### ISSUE TITLE
Unable to use AWS.IoTAnalytics in web app (react)

### ISSUE THREAD

**Issue by patrick-239** [aws/aws-sdk-js#2777]
Hello,

I want to use a data from a DataSet in my app, but a line:
```javascript
var iotanalytics = new AWS.AWS.IoTAnalytics();
```
failed with: 
```
TypeError: undefined is not a constructor (evaluating 'new AWS.IoTAnalytics()')
```

Is it possible to use IoTAnalytics in a browser app?

**Comment by trivikr** [comment]
The code is incorrect as AWS.AWS is appearing twice

There is no error when the following code is run in Node.js:
```javascript
var iotanalytics = new AWS.IoTAnalytics();
```

Please check [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IoTAnalytics.html) for usage of `AWS.IoTAnalytics`
