### ISSUE TITLE
S3 excessive CPU usage using ceph

### ISSUE THREAD

**Issue by itaied246** [aws/aws-sdk-js#2779]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
 I'm using the S3 module to connect to my ceph instance.  
Monitoring the ceph, everything looks fine and its response time average at 60 ms.  
The problem I'm having is with the CPU usage of my node application.

My service execute 80 uploads per second at an average size of 300 kb.  
For this communication rate, my service uses 80% of the CPU.  
I'm using the `upload` function and the Body as a stream.

Has anyone experienced this?

**Comment by trivikr** [comment]
Can you please share a sample code to reproduce the issue?
