### ISSUE TITLE
Tricky use of "this" and better support for promisification

### ISSUE THREAD

**Issue by why-jay** [aws/aws-sdk-js#278]
Hi,

I was trying to promisify `dynamodb.scan` using the Q library's `Q.nfcall` method (I believe `nfcall` can be applied to AWS's methods because its methods follow the "Nodeback" style):

```
Q.nfcall(dynamodb.scan, params)
    .then(....)
```

But I kept getting the following cryptic error:

```
TypeError: Object #<Object> has no method 'makeRequest'
    at svc.(anonymous function) (/Users/chcokr/Desktop/code/yamm-image-server/node_modules/aws-sdk/lib/service.js:418:21)
```

So I was thinking, perhaps `Q.nfcall` doesn't work well on AWS's methods, so I created a custom promisifier:

```
 var qAWSPromise = function (func, params) {
            return Q.Promise(function (resolve, reject) {
                func(params, function (err, data) {
                    if (err) {
                        reject(err);
                        return;
                    }
                    resolve(data);
                });
            });
        };
```

But I still got the same error, with any AWS method for `func`. Confused, I tried the following code:

```
            return Q.Promise(function (resolve, reject) {
                dynamodb.scan(params, function (err, data) {
                    if (err) {
                        reject(err);
                        return;
                    }
                    resolve(data);
                });
            });
```

This time, it worked! So I started delving into AWS's code, and discovered that the issue was caused by the tricky use of `this` on line 418 of lib/service.js:

```
      svc.prototype[method] = function (params, callback) {
        return this.makeRequest(method, params, callback);
      };
```

With my code, that `this` was being set to `global` (which makes sense)! So I ended up fixing my promisifier to the following:

```
    var qAWSPromise = function (service, method, params) {
            return Q.Promise(function (resolve, reject) {
                service[method](params, function (err, data) {
                    if (err) {
                        reject(err);
                        return;
                    }
                    resolve(data);
                });
            });
        };
```

which is to be used as `qAWSPromise(dynamodb, "scan", params)`.

I could not come up with an easy, quick workaround for that line with the `this`. If you could provide more insight/fix into this (not so much of an) issue, it could save a few hours for those trying to use the AWS SDK with Promises/A+ !

Thanks :)

**Comment by billinghamj** [comment]
Worth noting another way to do this is:

```js
var AWS = require('aws-sdk');
var db = new AWS.DynamoDB();
var Q = require('q');

Q.ninvoke(db, 'listTables', {}).then(function(data) {
  console.log(data);
});
```

`ninvoke` ensures that `this` is correctly bound.
