### ISSUE TITLE
Why my AWS Lambda to S3 there is no result?

### ISSUE THREAD

**Issue by wtaiatella** [aws/aws-sdk-js#2784]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I'm starting with AWS Lambda and I'm trying to do a very simple code where lambda asks the buckets from S3 but is not working. I've read a lots of docs and couldn't find what's is wrong. I tryied as a web Lambda function and with node.js in Visual Studio Code.

To make this test, I created a S3 bucket and uploaded a text file.

Here is my Web Lambda function code:
```javascript
exports.handler = async (event, context) => {
  var AWS = require("aws-sdk");

  var s3 = new AWS.S3(
    { apiVersion: "2006-03-01" },
    { accessKeyId: "my key" },
    { secretAccessKey: "my secret key" }
  );

  s3.listBuckets(function(err, data) {
    if (err) {
      console.log("Error", err);
    } else {
      console.log("Bucket List", data.Buckets);
    }
  });
};
```
And it's response:
```
Response:
null

Request ID:
"f30a8834-9a3b-46a7-9510-970a24c1f6d8"

Function Logs:
START RequestId: f30a8834-9a3b-46a7-9510-970a24c1f6d8 Version: $LATEST
END RequestId: f30a8834-9a3b-46a7-9510-970a24c1f6d8
REPORT RequestId: f30a8834-9a3b-46a7-9510-970a24c1f6d8	Duration: 5158.25 ms	Billed Duration: 5200 ms 	Memory Size: 128 MB	Max Memory Used: 88 MB	
```
I tried also with IAM role but was the same result. Seems like its working but it don't show the list of buckets from S3.

First I would like to solve it, later i will ask about the node.js. Maybe it may solve the issue over node.js.

Can anyone help me with this? Thanks a lot!!

EDIT:
- (trivikr) beautified code and added javascript code block

**Comment by trivikr** [comment]
@wtaiatella 

What happens if you try:
```javascript
var s3 = new AWS.S3({
  apiVersion: "2006-03-01",
  accessKeyId: "my key",
  secretAccessKey: "my secret key"
});
```

In AWS S3 JS SDK documentation ([link](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor_details)) the constructor accepts just one Options hash.

S3 client typings: https://github.com/aws/aws-sdk-js/blob/01424ab8ae1f8a37e777bec91037f5cc410366d3/clients/s3.d.ts#L18

**Comment by wtaiatella** [comment]
The answer was the same:

```
Response:
null

Request ID:
"d3ada5a2-2f94-4b01-aa54-cae285d30bf7"

Function Logs:
START RequestId: d3ada5a2-2f94-4b01-aa54-cae285d30bf7 Version: $LATEST
END RequestId: d3ada5a2-2f94-4b01-aa54-cae285d30bf7
REPORT RequestId: d3ada5a2-2f94-4b01-aa54-cae285d30bf7	Duration: 5006.16 ms	Billed Duration: 5100 ms 	Memory Size: 128 MB	Max Memory Used: 90 MB
```

**Comment by trivikr** [comment]
Is the S3 bucket created in the same region as the one you're requesting from SDK?

**Comment by wtaiatella** [comment]
The Lambda and S3 are in Oregon and I'm programing a web function. I tried to use node.js but I got permition denied. Now I dno't know if was some mistake in configuration or something else.

I have an IAM function with full access to lambda, S3 and cloud watch.

**Comment by 51403223** [comment]
The problem is you missed the first argument. Your code should be
```
s3.listBuckets( {}, function(err, data) {
    if (err) {
      console.log("Error", err);
    } else {
      console.log("Bucket List", data.Buckets);
    }
  });
```
Docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listBuckets-property

**Comment by ajredniwja** [comment]
@wtaiatella,

Is this still a persisting issue?
