### ISSUE TITLE
s3.putObject Invalid Parameter Error

### ISSUE THREAD

**Issue by robert-hirsch-po** [aws/aws-sdk-js#2786]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Putting an object into an S3 bucket returns an error.
`InvalidParameterType: Expected params.getByIndex to be a string`

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v10.15.3

**SDK version number**
v2.499.0 

**To Reproduce (observed behavior)**
```
    const key = `profiles/${args.id}`;

    const params = {
      ACL: 'public-read',
      Key: key,
      Body: args.file.data,
      ContentEncoding: 'base64',
      ContentType: args.file.mimetype,
      Bucket: 'bucket-name'
    };

    await S3.putObject(params).promise();
```

The file is successfully uploaded with `paramValidation: false` on the S3 instance.

**Expected behavior**
The file should be successfully uploaded without turning off Param Validation.

**Comment by ajredniwja** [comment]
Hey @robert-hirsch-po 

I believe the ```async``` function that you are using doesn't get resolved and is treated like a promise rather than a string, can you try removing the ```async``` from the function?
