### ISSUE TITLE
s3.deleteObject with space and quote character in name: NotImplemented error

### ISSUE THREAD

**Issue by fubar** [aws/aws-sdk-js#2787]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

I've searched thoroughly and see lots of related issues but none that match this specifically:

An S3 object with a space AND a quote character (`"`) in its name cannot be deleted from a subdirectory (ie. when it has a prefix). Error: `NotImplemented: A header you provided implies functionality that is not implemented`

If there's no space character, or if the object is on the root level of a bucket, it succeeds.

Other special characters throw the same error; for example, objects with a precent sign (`%`) in it cannot even be deleted from the root level of a bucket.

I recognize that only a limited set of characters is recommended to be used with S3, but the reality is that S3 does not prevent those characters from being used and as a result we end up with files that cannot be deleted.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Node v11.10.1

**SDK version number**
2.501.0

**To Reproduce (observed behavior)**
```js
s3.deleteObject(
  {
    Bucket: 'foo',
    Key: 'bar/one two"three.jpg',
  },
  (error, result) => console.log(error, result),
);
```
```
[NotImplemented: A header you provided implies functionality that is not implemented], null
```

**Expected behavior**
Should succeed

**Screenshots**
n/a

**Additional context**

- Removing the space from the file and trying again succeeds: `Key: 'bar/onetwo"three.jpg'`
- URL encoding does not work. I tried encoding the entire string (`bar%2Fone%20two%22three.jpg`) as well as the path parts individually (`bar/one%20two%22three.jpg`) which leads to success responses but no action taken, consistent with the expected behaviour when referencing object names that don't exist.
- I've also tried adding a slash in front (`Key: '/bar/one two"three.jpg'`), which also returns a success response with no action taken (object not deleted)
- Deleting a file without a prefix works (`Key: 'one two"three.jpg'`)

**Comment by ajredniwja** [comment]
Hey @fubar,

Thank-you for reaching out, I was able to successfully delete an object with the following code example,
 ```JavaScript
var params = {
  Bucket: "bucketName", 
  Key: "bar/one two\"three.jpg" //using backslash before double quote and using double quote for the string as well. 
 };

 s3.deleteObject(params, function(err, data) {
   if (err) console.log(err, err.stack); // an error occurred
   else     console.log(data);           // successful respond
 });

```
I also tried something with '%' in the name without using any escape characters, it worked as well.

Can you try something similar to above example and updating the SDK?

Closing for now, please reach out if it is still an issue.
