### ISSUE TITLE
MediaStoreData putObject cannot set Transfer-Encoding to chunked for chunked object transfer

### ISSUE THREAD

**Issue by jienco** [aws/aws-sdk-js#2788]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
There is no way of setting the Transfer-Encoding HTTP header to **chunked**, in order to use the chunked object transfer feature (https://forums.aws.amazon.com/ann.jspa?annID=6738). According to the documentation (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/MediaStoreData.html#putObject-property), when setting **UploadAvailability** as **STREAMING**, it says "**you must also set the HTTP Transfer-Encoding header to chunked.**" However there is no way of passing that header in the params object passed to the putObject method.

If I just use UploadAvailability: 'STREAMING', when inspecting the request in Electron Dev Tools, I can see that the 'Transfer-Encoding' HTTP Request header is not being set.

**Is the issue in the browser/Node.js?**
Node.js (running on Electron)

**If on Node.js, are you running this on AWS Lambda?**
No.

**Details of the Node.js version**
v12.5.0

**SDK version number**
Example: v2.501.0

**To Reproduce (observed behavior)**

When trying this:

```javascript
    const fileContent = fs.readFileSync(filePath);
    const params = {
      Body: fileContent,
      Path: `test001/720p_0.ts`,
      CacheControl: 'max-age=6, public',
      ContentType: 'video/MP2T',
      StorageClass: 'TEMPORAL',
      UploadAvailability: 'STREAMING',
      headers: {
        'Transfer-Encoding': 'chunked',
      },
    };
    return new Promise<void>((resolve, reject) => {
      this.awsMediaStoreData.putObject(params, (error: AWS.AWSError, responseData: AWS.MediaStoreData.PutObjectResponse) => {
        if (error) {
          console.log(error);
          reject(error.message);
        }
        resolve();
      });
    });
```

This error is thrown: 

```
core.js:5847 ERROR Error: Uncaught (in promise): Unexpected key 'headers' found in params.
```

And when trying these params:

```javascript
  const params = {
      'Body': fileContent,
      'Path': `test001/720p_0.ts`,
      'CacheControl': 'max-age=6, public',
      'ContentType': 'video/MP2T',
      'StorageClass': 'TEMPORAL',
      'UploadAvailability': 'STREAMING',
      'Transfer-Encoding': 'chunked',
    };
```

This error is thrown:

```
UnexpectedParameter: Unexpected key 'Transfer-Encoding' found in params.
```

**Expected behavior**
There should be a way of setting the Transfer-Encoding HTTP header to chunked in order to use this important feature of MediaStore.

**Comment by paul-carron** [comment]
jienco Did you have any success with this?

**Comment by ajredniwja** [comment]
Hey @jienco,

Thank-you for reaching out. The headers needs to be set in the HTTP client using ```setHeader``` API which should look something like, 
```JavaScript

var http = require('http');

http.createServer(function (req, res) {
  //Use setHeader api for
      req.setHeader("TransferEncoding", "Chunked");
      //more code


}).listen(8080);
```

More information about setting the headers can be found [here](https://nodejs.org/docs/v0.4.0/api/http.html#http.request).

Closing this issue for now, please reach out if you have any questions.
