### ISSUE TITLE
DynamoDB DocumentClient does not paginate requests correctly

### ISSUE THREAD

**Issue by iwb-rubentytgat** [aws/aws-sdk-js#2789]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The DynamoDB DocumentClient does not paginate requests correctly. When `nextPage` is called it attempts to call the underlying service methods on the DocumentClient instead of the corresponding DocumentClient methods. I am using `batchGet` as an example as this is the method I was using when trying to use pagination, but this is probably applicable to all operations.

**Is the issue in the browser/Node.js?**
Browser/Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v10.15.3

**SDK version number**
v2.501.0

**To Reproduce (observed behavior)**
```javascript
const dynamodb = new DynamoDB.DocumentClient({ apiVersion: '2012-08-10' })
const results = await dynamodb.batchGet({
	RequestItems: {
		fooTable: {
			Keys: [{ barField: 5 }],
		},
	},
}).promise()

results.$response.nextPage()
```
results in
```
error: self[operation] is not a function
```

**Expected behavior**
Response is paginated correctly.

**Additional context**
The problem lies [on this line](https://github.com/aws/aws-sdk-js/blob/4d7c4a3cfdc0b2633daa3cb479ac735bbd4beddc/lib/dynamodb/document_client.js#L568) of the `lib/dynamodb/document_client.js` file. The document client creates the `nextPage()` method on the response object, and configures it so it would re-call the original operation. However, `self` here is the DocumentClient object, but the `operation` variable contains the underlying service operation name `batchGetItem` instead of the DocumentClient operation `batchGet`, resulting in a `self[operation] is not a function` error when I try to call the `nextPage()` method. The operation variable is read out from a property of the `request` object [here](https://github.com/aws/aws-sdk-js/blob/4d7c4a3cfdc0b2633daa3cb479ac735bbd4beddc/lib/dynamodb/document_client.js#L548), but this is just a service-level Request object, so it contains the service-level method name.

To fix this problem the service-level method name should first be converted back to the document client method name, for example using a mapping analogous to [the inverse one](https://github.com/aws/aws-sdk-js/blob/4d7c4a3cfdc0b2633daa3cb479ac735bbd4beddc/lib/dynamodb/document_client.js#L109) use to convert from DocumentClient names to service names.

**Comment by franz101** [comment]
Probably the same bug here.

**Comment by mwgamble** [comment]
Can confirm, I just ran into the exact same issue. Pagination simply doesn't work correctly at all.

**Comment by oliverdunk** [comment]
@trivikr I don't suppose you still plan on looking at this? DocumentClient looks appealing but this seems like a bad bug.

**Comment by mwgamble** [comment]
With the AWS SDK v3 being released near the end of last year, I don't see this getting fixed anytime soon. They also make you handle pagination yourself in the new SDK, but at least it's better than providing a broken implementation of pagination and pretending it works.

**Comment by mwgamble** [comment]
It's almost certainly still an issue. Seeing as there hasn't been even an acknowledgement that this issue exists by the maintainers, it should remain open for the time being.
