### ISSUE TITLE
Node S3 high cpu

### ISSUE THREAD

**Issue by natvaldev** [aws/aws-sdk-js#2791]
Hello

I'm using `aws-sdk` S3 module to upload to my `minio` service.
Executing 50 uploads per second of images in size of 3.5 MB drains all of my machine `cpu`.

I have tried using `upload` and `putObject`, both had the same result.

```js
const s3 = new aws.S3({
  params: {
    Bucket: 'my-bucket',
  }
  ...
}

const handler = () => {
  const start = moment()
  s3.upload({
    Key: '...',
    Body: '...' // image stream
  }).promise()
  .then(() => { ... })
  .catch(...)
}

const main = () => {
  setInterval(handler, 1000 / process.env.con)
}

main()
```

That's actually more or less what I do, nothing more for this simple script test.

I have run `--prof` and found the following:

total ticks 188204
57k (30%) ticks from node::crypto::Hash::HashUpdate(v8::FunctionCallbackInfo...)
53k (28%) ticks from syscall
12k (6.6%) ticks from __libc_writev

[Bottom up profile]

57k ticks from LazyCompile: *hash /opt/app/src/node_modules/aws-sdk/lib/util.js:411:19
and then I see `computeContentMd5` and `/usr/lib64/libcrypto.so`.

It seems that the `hash` validation uses too much cpu cycle (ticks).

What can I do?

**Comment by AllanFly120** [comment]
Hey @natvaldev 
Can you have a look on the value of your `s3.config.s3DisableBodySigning`? If it's true maybe you can profile the process after setting it to `false`. This config will prevent SDK from generating hash for the body.
