### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by alfasin** [aws/aws-sdk-js#2793]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When promisifying `listObjectsV2` it throws "TypeError: Cannot read property 'push' of undefined"

**Is the issue in the Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the Node.js version**
v10.15.3

**SDK version number**
2.124.0

**To Reproduce (observed behavior)**
```
const S3 = require('aws-sdk/clients/s3');
const params = {
        apiVersion: '2006-03-01',
        region: region
    };
const s3 = new S3(params)
    return s3.listObjectsV2({Bucket: bucket, Prefix: folder}, function (err, data) {
        if (err) {
            logger.alert('cannot list objects from', bucket, err);
            return null;
        }
        return data;
    }).promise(); // <-- I suspect that this is the issue
```

**Expected behavior**
Execute without throwing an error

**Additional context**
Issue: https://github.com/aws/aws-sdk-js/issues/1453
sounds to me like the same issue - but it got closed due to "being old" without a resolution.

**Comment by drexler** [comment]
@alfasin you're using both the callback and the promisified options. It should be one or the other. So something like this if you wanted the _promisified_ version:
```
const S3 = require("aws-sdk/clients/s3");
const params = {
  apiVersion: "2006-03-01",
  region: region
};

const s3 = new S3(params);
try {
    return await s3.listObjectsV2({
        Bucket: bucket,
        Prefix: folder,
    }).promise();
} catch(error) {
    logger.alert('cannot list objects from', bucket, error);
    return null;
}
```

**Comment by alfasin** [comment]
That worked - thanks!
