### ISSUE TITLE
[QuickSight] aws_sdk__WEBPACK_IMPORTED_MODULE_7__.QuickSight is not a constructor

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-sdk-js#2794]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

Cannot create an instance of QuickSight in browsers. The `QuickSight` key does not exists on the object exported from `aws-sdk`.

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**

Chrome 75

**SDK version number**
v2.503.0 via npm package `aws-sdk`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

```
import { QuickSight } from 'aws-sdk';

const qs = new QuickSight({
 ...
});

const url = await qs.getDashboardEmbedUrl({
  AwsAccountId: dashboard.accountId,
  DashboardId: dashboard.id,
  IdentityType: 'IAM',
}).promise();
```

**Expected behavior**

Should be able to use QuickSight in browser to get dashboard embed URLs.

**Comment by sr56** [comment]
Hi Chris,
 
I had come across similar error ( Using Angular8 and "aws-sdk": "^2.513.0",  ) when I didn't import Quicksight by itself, and tried to use

`new AWS.QuickSight();  `
 Error was:  
> "aws_sdk__WEBPACK_IMPORTED_MODULE_3__.QuickSight is not a constructor"

Forums indicated the issue to be about the way we import QuickSight.. . 
The below code finally worked 

```
import * as AWS from 'aws-sdk';
import * as Sts from 'aws-sdk/clients/sts';
import * as QuickSight from 'aws-sdk/clients/quicksight';
........
........
        AWS.config.update({
            region: 'us-east-1',
            credentials: quicksightCredentials
        });
        this.quickSight = new QuickSight();
```

Regards,

**Comment by cmckni3** [comment]
Oh I see it's due to the commonjs module exports and I found the article about using browserify.

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html

Thanks for the info! I ended up needing to use a Lambda anyways.
