### ISSUE TITLE
The AWS.RDS.Signer getAuthToken function is not correct

### ISSUE THREAD

**Issue by hyeoksuhan** [aws/aws-sdk-js#2798]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The result of AWS.RDS.Signer getAuthToken function is not correct when I call the function without callback function.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v10.16.0

**SDK version number**
aws-sdk@2.503.0

**To Reproduce (observed behavior)**
1. Run the below code on EC2 instance
```
const express = require('express');
const AWS = require('aws-sdk');

const app = express();

const signer = new AWS.RDS.Signer({
    region: <REGION>,
    hostname: <RDS HOST>,
    port: <RDS PORT>,
    username: <DB USER>,
});

app.get('/token', (req, res) => {
    const syncToken = signer.getAuthToken();

    return signer.getAuthToken((err, token) => {
        if (err) {
            return res.send({err});
        }

        res.send({token, syncToken});
    });
});

const port = process.env.PORT || 3333;

app.listen(port, () => {
    console.log(`server is listening on ${port}`);
});
```

2. I called the API /token on my browser.

3. Checked the result. `token` seems like correct but `syncToken` is just same as <RDS HOST> value.
 
**Expected behavior**
Both `token` and `syncToken` is the same as correct token.

**Screenshots**
<img width="1675" alt="screenshot" src="https://user-images.githubusercontent.com/39330938/62508137-8e390f80-b841-11e9-820b-19c3c91d58b4.png">

**Additional context**
.

**Comment by AllanFly120** [comment]
Hey @hyeoksuhan 
As the [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS/Signer.html#getAuthToken-property) suggests, you need to make sure your credentials are resolved in order to use `getAuthToken` without callback. Since you are calling it from browser, you are very likely to use a non-static credentials. So you can only use callback version of the API in this case.

**Comment by hyeoksuhan** [comment]
Thanks! I've read the all API reference except for  `Note`. It was totally my fault.
