### ISSUE TITLE
Support for SubscribeToShard Kinesis API Call

### ISSUE THREAD

**Issue by vinay-nadig-0042** [aws/aws-sdk-js#2799]
Request to support the SubscribeToShard API call on Kinesis client. This is available in other SDKs(boto3 for example).

[Link to API](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_SubscribeToShard.html)

**Comment by AllanFly120** [comment]
Hey @vinay-nadig-0042 

The command is not available in the SDK because it requires HTTP/2 support. Unfortunately the current SDK doesn't support HTTP/2 so far. 

I label this as feature-request. I will comment here when we have any news on HTTP/2 support.
