### ISSUE TITLE
SSM requests fail when using a non-existing region and a custom endpoint

### ISSUE THREAD

**Issue by lmgarret** [aws/aws-sdk-js#2800]
**Describe the bug**
When creating a SSM client and specifying both a fake region (```localhost```) and an endpoint ([localstack](https://github.com/localstack/localstack) mock SSM URL), any request fails.
Changing the region from ```localhost``` to ```us-east-1``` fixes it.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes.

**Details of the browser/Node.js version**
v10.16.1

**SDK version number**
v2.466.0

**To Reproduce (observed behavior)**
Here a small script that reproduces the issue, you can directly run it with [ts-node](https://www.npmjs.com/package/ts-node).

```typescript
import AWS from 'aws-sdk';

const ssm: AWS.SSM = new AWS.SSM({
    region: 'localhost',
    endpoint: 'http://localhost:4583',
    accessKeyId: 'someId',
    secretAccessKey: 'someSecret',
});

main();

async function main() {
    await ssm
        .putParameter({
            Name: 'someName',
            Type: 'String',
            Value: 'someValue',
        })
        .promise()
        .catch((err: AWS.AWSError) => {
            console.error(`Failed putting parameter: ${err.message}`);
        });

    await ssm
        .getParameter({
            Name: 'someName',
        })
        .promise()
        .catch((err: AWS.AWSError) => {
            console.error(`Failed getting parameter: ${err.message}`);
        });
}
```

**Expected behavior**
The above script should execute without any error. For other AWS clients that we use (DocumentClient, S3...), instantiating with: 
```typescript
region: 'localhost',
endpoint: '<localstack url>',
``` 
works flawlessly and allows to use ```localstack``` for local development. But for SSM, every request fails with an ```Internal Error```, unless you update the region to an existing one.

**Additional context**
A [similar issue](https://github.com/localstack/localstack/issues/1107) was posted on ```localstack```'s repository. I've commented it and added some missing information, but after further investigation I do believe that the issue lies with ```aws-sdk-js```.

**Comment by ajredniwja** [comment]
Hey @lmgarret,

Thank-you for reaching out, it is unlikely that it is a bug with the SDK if you are able to make it work using ```us-east-1``` as your region. For better information can you please provide the log messages.
```JavaScript
var SSM = new AWS.SSM({logger: console});
```
