### ISSUE TITLE
How to access(get uploaded file) the private bucket in aws s3 repo ? 

### ISSUE THREAD

**Issue by baladkb** [aws/aws-sdk-js#2801]
Hi,
We are using this plugin and it's useful for us 👍 💯 
We can able to upload files in private bucket in aws s3  but not able to get or access the uploaded files, can You please suggest some steps or code samples to archive this.

thanks :metal:

Confirm by changing [ ] to [x] below:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

**Comment by AllanFly120** [comment]
Hey @baladkb 

Do you have the permission to the bucket? I believe you need to update the bucket policy and users/role policy in order to get the files. This document maybe helpful: https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-access-control.html

**Comment by sivakumarbdu** [comment]
Hi @baladkb 
Please check this guidehttps://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html.  When  you access private bucket you need to add following params.

```
{ 
  ServerSideEncryption: AES256 
  Expires:  3600,
  ACL: private
}
```

Thanks

**Comment by baladkb** [comment]
> Do you have the permission to the bucket? I believe you need to update the bucket policy and users/role policy in order to get the files. This document maybe helpful: https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-access-control.html

thanks @AllanFly120,  
bucket has GetObject, PutObject, PutObjectAcl  in the bucket policy.  I could access it from aws cli and trying to access via Javascript SDK.

**Comment by baladkb** [comment]
> Hi @baladkb
> Please check this guide https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html. When you access private bucket you need to add following params.
> 
> ```
> { 
>   ServerSideEncryption: AES256 
>   Expires:  3600,
>   ACL: private
> }
> ```
> 
> Also make sure you have process acl.
> 
> Thanks

thanks @sivakumarbdu . Let me check with these configurations and get back.

**Comment by Thilagavathi1** [comment]
@baladkb We have fixed the issue we can able to get the s3 url using getobject method using @sivakumarbdu 💯 comment. For your reference we have added the screenshot, Please check.
![s3uploadprivate](https://user-images.githubusercontent.com/16552447/63170649-5d35b780-c057-11e9-9a0a-1cf2ae2f2998.png)
Thanks @sivakumarbdu 👍

**Comment by baladkb** [comment]
@AllanFly120 @sivakumarbdu @Thilagavathi1 working fine! 👌

Thanks all  :octocat:
