### ISSUE TITLE
Missing type SQS SendMessageResult TypeScript definition is missing properties.

### ISSUE THREAD

**Issue by kbradl16** [aws/aws-sdk-js#2804]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

Missing typescript definition for **SendMessageResult** An error occurs for the following:
```
const sendMessageResponse: SendMessageResult = {
  ResponseMetadata: { RequestId: '1234' },
  MD5OfMessageBody: '1234',
  MessageId: '1234'
}

```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
yes

**SDK version number**
 v2.503.0

**Expected behavior**
To have the types defined correctly

**Comment by AllanFly120** [comment]
Hey @kbradl16 The`ResponseMetadata` is not in the SendMessageResult public interface. Do you think the requestId should be added? RequestId in defined in Response: https://github.com/aws/aws-sdk-js/blob/7b3f128ca748ee39081948be741f5774e60ffd4c/lib/response.d.ts#L25 but you don’t have access to it directly from SendMessageResult. 

For example you can access the request id from `request.response.requestId` like:
```
const request = sqs.sendMessage(params, (err, data) => {
    console.log(`request id is ${request.response.requestId}`);
});
```

**Comment by kbradl16** [comment]
I'm seeing this response (redacted numbers)
```
messageResponse { ResponseMetadata: { RequestId: '123' },
  MD5OfMessageBody: '123',
  MessageId: '123' }
```

from this request and log:

```
   const messageResponse: SendMessageResult = await sqs
      .sendMessage({
        QueueUrl: 'url'
        MessageBody: 'messageBody'
      })
      .promise();

    console.log("messageResponse", messageResponse);
```

**Comment by kbradl16** [comment]
response

**Comment by AllanFly120** [comment]
@kbradl16 
You should be able to do:
```
const request = sqs..sendMessage({
        QueueUrl: 'url'
        MessageBody: 'messageBody'
      });
const messageResponse: SendMessageResult = await request.promise();

console.log("messageResponse", messageResponse);
console.log("requestId: ", request.response.requestId);
```

**Comment by kbradl16** [comment]
@AllanFly120 was there an update to the types? This had caused an error in typescript before.

**Comment by kbradl16** [comment]
Seems to still be an issue. In my response from SQS I get this key/value ` ResponseMetadata: { RequestId: '123' },` but the type does not have that. So when I try to use ResponseMetadata I have to type coerce my code for it to work correctly.
The `SendMessageResult` type does not seem to be accurate and missing the ResponseMetadata field:

<img width="656" alt="SendMessageResult type is not correct" src="https://user-images.githubusercontent.com/3843423/76693682-b68eb500-663f-11ea-8958-d757ccc64090.png">

I would expect this to not error:
```
import {SendMessageResult} from 'aws-sdk/clients/SQS';
import {SQS} from 'aws-sdk';

async function sendSqsMessage(){
    const messageResponse: SendMessageResult = await new SQS()
    .sendMessage({
      QueueUrl: 'url',
      MessageBody: 'messageBody'
    })
    .promise();

    console.log("messageResponse", messageResponse.ResponseMetadata);
}

const exampleResult: SendMessageResult  = { 
    ResponseMetadata: { RequestId: '123' },
    MD5OfMessageBody: '123',
    MessageId: '123'
}
```
<img width="490" alt="Screen Shot 2020-03-14 at 10 08 13 PM" src="https://user-images.githubusercontent.com/3843423/76693721-649a5f00-6640-11ea-9638-6fec82d94c70.png">
