### ISSUE TITLE
Please re-open issue #1981

### ISSUE THREAD

**Issue by bush** [aws/aws-sdk-js#2806]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

I would like to re-open issue #1981.  I see it was recently closed but it still a problem.  I am using the latest aws-sdk npm - version 2.507.0

**Is the issue in the browser/Node.js?**
Browser/Node.js

No

**If on Node.js, are you running this on AWS Lambda?**

Yes

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v10.14.2

**SDK version number**
v2.507.0

**To Reproduce (observed behavior)**

I am issuing a query on a GSI with the Limit set to N.  When there are exactly N items in the database I still get a non-empty LastEvaluatedKey.  If I do a query with this key as the ExclusiveStartKey I get 0 results as expected because there are no more items that could possibly match the query.  The interesting thing is that I only see this behaviour when there are exactly N items in my GSI where N is also the limit of the query.  If there are more items in my GSI (but the extra items won't match my query) when I perform the query I don't see the LastEvaluatedKey as expected.

**Expected behavior**

Should only see a non-empty LastEvaluatedKey when there are more items to retrieve from the query.

**Screenshots**

**Additional context**

**Comment by klaytaybai** [comment]
Hi @bush, as noted by Srchase in #1981, the behavior that you describe to be troubling is documented and intended behavior.  You may need to do the extra call to finish your pagination even if you specify a limit that matches your query matches.
