### ISSUE TITLE
xmlhttprequest is not defined - nodejs

### ISSUE THREAD

**Issue by zzzxtreme** [aws/aws-sdk-js#2807]
hello guys. I'm using aws-sdk via npm install. for lambda, it works like a charm.
but when I try to use it with cloudflare worker, it returns error "NetworkingError: XMLHttpRequest is not defined"

Does anyone know any workaround? I apologize in advanced if my question is too vague or if I have posted in the wrong forum

**Comment by june07** [comment]
Same deal here.

**Comment by AllanFly120** [comment]
Hey @zzzxtreme 

Can you make sure `XMLHttpRequest` is defined in the Cloudflare worker like browser? I find they only mention using `fetch` in their [docs](https://developers.cloudflare.com/workers/recipes/post-requests/).

**Comment by zzzxtreme** [comment]
thanks for the response. 

I have added xmlhttprequest via npm install, is that what you mean? It did cause more errors to appear


solution I found is to replace the xhrclient part in lib\http\xhr.js with this code. I have only tested this with S3 upload (putObject)


AWS.XHRClient = AWS.util.inherit({
  handleRequest: function handleRequest(httpRequest, httpOptions, callback, errCallback) {
    var self = this;
    var endpoint = httpRequest.endpoint;
    var emitter = new EventEmitter();
    var href = endpoint.protocol + '//' + endpoint.hostname;
    if (endpoint.port !== 80 && endpoint.port !== 443) {
      href += ':' + endpoint.port;
    }
    href += httpRequest.path;
 
    callback(emitter);
    var headers = new Headers();
 
    AWS.util.each(httpRequest.headers, function (key, value) {
      if (key !== 'Content-Length' && key !== 'User-Agent' && key !== 'Host') {
        headers.set(key, value);
      }
    });
     
    var credentials = 'omit';
 
    if (httpOptions.xhrWithCredentials) {
      credentials = 'include';
    }
 
    var request = new Request(href, {
      method: httpRequest.method,
      headers: headers,
      body : httpRequest.body
    });
 
    fetch(request).then(function(response) {
        if (!response.ok) {
            throw Error(response.statusText);
        }
        return response;
    }).then(function(response) {
      emitter.statusCode = response.status;
	  new Error(response.headers)
      emitter.headers = self.parseHeaders(response.headers);
      emitter.emit('headers', emitter.statusCode, emitter.headers);
      response.text().then(function(res){
         console.log(res);
         self.finishRequest(res, emitter);
      }).catch(function(err){
         console.log(err);
      });
 
    }).catch(function(err) {
       errCallback(AWS.util.error(new Error('Network Failure' + err), {
        code: 'NetworkingError'
      }));
 
    });
 
    return emitter;
  },
 
  parseHeaders: function parseHeaders(rawHeaders) {
    var headers = {};
    rawHeaders.forEach(function(val,key){
       headers[key] = val;
    });
     
    return headers;
  },
 
  finishRequest: function finishRequest(res, emitter) {
    var buffer;
    try {
       buffer = new AWS.util.Buffer(res);
    } catch (e) {}
 
    if (buffer) emitter.emit('data', buffer);
      emitter.emit('end');
  }
});

**Comment by qgicup** [comment]
@zzzextreme can you post the full code how you've integrated that with the standard aws-sdk code ?

**Comment by zzzxtreme** [comment]
> @zzzextreme can you post the full code how you've integrated that with the standard aws-sdk code ?

browse your node modules folder, search for xhr.js

**Comment by ajredniwja** [comment]
@zzzxtreme is this still a persisting issue with the latest version of the SDK?

**Comment by MickL** [comment]
@ajredniwja Yes this is still persistent and very urgent. The whole module does not work in Cloudflare Worker:

Any request that I want to make results in an error: `XMLHttpRequest is not defined` in my serverless environment (Cloudflare Worker). This should be the case for Amazon Lambda, too.

Example:

```
const s3 = new S3({
  // credentials
});

s3.getObject({
          Bucket: 'myBucket',
          Key:    'myKey',
        },
        (error, data) => {
             // Error: XMLHttpRequest is not defined
        }
);
```

Solution is mentioned in #1902 to use `fetch`. He did not make a PR but maybe someone could?
