### ISSUE TITLE
Question: s3 client multiple endpoints

### ISSUE THREAD

**Issue by Arun-KumarH** [aws/aws-sdk-js#2808]
According the documentation we can provide only one storage endpoint.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property
```
endpoint (String) —
The endpoint URI to send requests to. The default endpoint is built from the configured region. The endpoint should be a string like 'https://{service}.{region}.amazonaws.com'.
```
Doesn't S3 client support multiple end point configurations ?

**Comment by 51403223** [comment]
How about creating one S3 client for each endpoint

**Comment by AllanFly120** [comment]
@Arun-KumarH 

Can you refer to advice from @51403223? Creating different clients on different endpoints is a reasonable solution for your usecase.

**Comment by Arun-KumarH** [comment]
Alright, thanks for the update.
