### ISSUE TITLE
RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.

### ISSUE THREAD

**Issue by doronin** [aws/aws-sdk-js#281]
I'm getting this error once in a while when making a `putObject` call.

What is the root cause of the error and what's the best way to avoid it?
According to API response looks like this error is non-retryable. Is there a way to configure `aws-sdk` to make a retry when this type of error happens?

example response:
{"message":"Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.","code":"RequestTimeout","time":"2014-05-21T00:50:25.709Z","statusCode":400,"retryable":false,"_willRetry":false}

**Comment by wuethrich44** [comment]
I use a stream to upload a war file to s3 and set the content length with the file size. On slow internet connections (1 Mbps upload) I get this error:
```
Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
```
I am using version 2.1.33 so the workaround doesn't work for me.

@lsegal Could you explain me a fix for a stream?

**Comment by mig82** [comment]
Hi,
I'm using aws-sdk for Node.js and I ran into the same issue. I seem to have found what the problem is. This is what I was originally doing:

	form.on('part', function(part) {
		var opts = {
			Bucket: myBucket,
			Key: myDestPath,
			ACL: 'public-read',
			Body: part,
			ContentLength: part.byteCount,
		};

		s3.putObject(opts, function(err, data) {
			if (err) throw err;
			console.log("File upload completed!", data);
			res.writeHead(200, {'content-type': 'text/plain'});
			res.end('Ok');
		});
	});
I realized the console.log message was being printed three times instead of one. Two of them for a couple of fields in the form from which I do the upload. Fields are parts as well as files. So then I tried this:

    form.on('part', function(part) {
    	if (part.filename) {
    		console.log("Received a part %o", part);
    		var opts = {
    			Bucket: myBucket,
    			Key: myDestPath,
    			ACL: 'public-read',
    			Body: part,
    			ContentLength: part.byteCount,
    		};
    
    		s3.putObject(opts, function(err, data) {
    			if (err) throw err;
    			console.log("File upload completed!", data);
    			res.writeHead(200, {'content-type': 'text/plain'});
    			res.end('Ok');
    		});
    	}
    });
The new if(part.filename) statement ensures I only attempt the upload for the file and not for the other fields in the form. The timeout error never occurred again.
I hope this helps.

**Comment by armw4** [comment]
[as mentioned](https://github.com/aws/aws-sdk-js/issues/281#issuecomment-43798354), turned out to be a slightly off `Content-Length` header for me. if you don't pass it, it'll just read the stream through to the end (and work fine).

**Comment by PeppeL-G** [comment]
I don't have time to debug this, but I got the error as well. I uploaded a file from a website to my server using Ajax, and then uploaded it to S3 with code looking like this:

```javascript
var stream = fs.createReadStream(pathToFile)

s3.putObject({
	Bucket: bucketName,
	Key: key,
	Body: stream
}, function(err, data){ /* Do stuff... */ })
```

The funny thing is that it always fails for the first Ajax request I send, but it works for all that comes after. I don't know if this is a bug in the AWS SDK or the package `multer` (with express) I use to receive the uploaded file on my server (although I receive the file perfectly well as far as I can tell; it's saved on my server).

However, when I change my code to:

```javascript
fs.readFile(pathToFile, function(err, data){
	if(err){
		// Handle fail...
	}else{
		s3.putObject({
			Bucket: bucketName,
			Key: key,
			Body: data
		}, function(err, data){ /* Do stuff... */ })
	}
})
```

It works for all my Ajax request.

I might have done a mistake somewhere (I'm not an experience Node programmer), but hopefully this will help someone.

**Comment by vsmori** [comment]
Anybody fixed this?

**Comment by felipemarques** [comment]
Anybody fixed this?

**Comment by felipeteodoro** [comment]
Anybody fixed this?

**Comment by jeskew** [comment]
As mentioned above, the SDK is not able to automatically retry uploads of streams. S3 will automatically close connections that are idle for too long, and when uploading streaming data you will need to react to this error by re-initializing your input stream and retrying the `PutObject` operation.

**Comment by PeppeL-G** [comment]
@jeskew, there shouldn't be any need for a retry if it would work as it should, right? Something is wrong and needs to be fixed? Or am I missing something?

**Comment by jeskew** [comment]
@PeppeL-G If a socket remains idle for too long a period of time, then S3 will close the connection and the operation will need to be retried. Common causes of socket timeouts include slow source streams, saturated event loops, and HTTP agents juggling too many concurrent connections.

**Comment by fikriauliya** [comment]
I encountered this issue on the latest npm version: `2.82.0`
It works ok on `2.63.0`

I have re-tested this on both version so many times, very less likely the root issue is somewhere else

**Comment by fikriauliya** [comment]
Now I have pinned point the issue on `2.68.0`
`<=2.67.0` have no problems.

Further investigation:

The release change on `2.68.0` is:

> feature: S3: Switches S3 to use signatureVersion "v4" by default. To continue using signatureVersion "v2", set the signatureVersion: "v2" option in the S3 service client configuration. Presigned URLs will continue using "v2" by default.

Setting `signatureVersion` to `v2` solve this problem:
`const s3 = new AWS.S3({signatureVersion: 'v2'});`

The followings don't work:
`const s3 = new AWS.S3();` => `RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.`
`const s3 = new AWS.S3({signatureVersion:'v4');` => `RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.`
`const s3 = new AWS.S3({signatureVersion:'v3');` => `AccessDenied: Access Denied`

**Comment by subugupta** [comment]
I had the same issue. changing the signatureVersion to 'v2' fixed the problem for me.

**Comment by syberkitten** [comment]
Have the same issue, But when i try signature v2:
I get:
```The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256```

**Comment by syberkitten** [comment]
It's quite unbelievable that such commonly used features
are faulty after so many years!!! 👎 

Is there any work around?

I can only use putObject 
as the upload method upload 0 byte files (corrupt)

But putObject timeouts if the file is larger then 100 kb.

Is this useless?

**Comment by hamxabaig** [comment]
Okay the funny thing is i was trying it with Postman and i didn't put `multipart/form-data` in header. Silly me.

**Comment by chrisbeyer** [comment]
> Setting signatureVersion to v2 solve this problem:
const s3 = new AWS.S3({signatureVersion: 'v2'});

Thanks fikriauliya, this worked for me :)

**Comment by syberkitten** [comment]
If i may suggest, instead of breaking your teeth ...

this is a very stable and good library utilizing the amazon s3 multipart upload
mechanism, with low memory footprint, chunks, and allows you to upload GB's of data.

works like charm even for files that take more then 1 hour of upload, and can resume
broken uploads.

[https://github.com/nathanpeck/s3-upload-stream](url)

**Comment by paulduthoit** [comment]
Any update? :(

**Comment by paulduthoit** [comment]
Just use `s3.upload` instead of `s3.putObject` method. ;)

**Comment by livey0u** [comment]
@paulduthoit Worked! Thanks!

**Comment by cortezcristian** [comment]
Difference between upload() and putObject() for uploading a file to S3?
https://stackoverflow.com/questions/38442512/difference-between-upload-and-putobject-for-uploading-a-file-to-s3

**Comment by Ishank-dubey** [comment]
It doesn't think work still?
