### ISSUE TITLE
Elastic Transcoder - createJob not working

### ISSUE THREAD

**Issue by ShubhangPlexusMD** [aws/aws-sdk-js#2810]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I am new in using AWS Elastic Transcoder services. My configuration are as follows: 

Node version - v10.16.0
aws sdk version - v2.509.0

While calling for createJob function I am getting following error - 
   'There were 8 validation errors:\n* UnexpectedParameter: Unexpected key \'key\' found in params.Outputs[2]\n* UnexpectedParameter: Unexpected key \'ThumbnailPatternkey\' found in params.Outputs[2]\n* UnexpectedParameter: Unexpected key \'Rotatekey\' found in params.Outputs[2]\n* UnexpectedParameter: Unexpected key \'PresetIdkey\' found in params.Outputs[2]\n* UnexpectedParameter: Unexpected key \'key\' found in params.Outputs[3]\n* UnexpectedParameter: Unexpected key \'ThumbnailPatternkey\' found in params.Outputs[3]\n* UnexpectedParameter: Unexpected key \'Rotatekey\' found in params.Outputs[3]\n* UnexpectedParameter: Unexpected key \'PresetIdkey\' found in params.Outputs[3]',
  code: 'MultipleValidationErrors',

Please do suggest me if I am doing anything wrong. All the help regarding this matter will be appreciated.
 
**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**

**Details of the Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v10.16.0

**SDK version number**
Version - v2.509.0
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `AWS.VERSION` in your code where `AWS = require("aws-sdk");`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
<pre>
const fs = require("fs");
const request = require("request");
const csv = require("csv");
const createCsvWriter = require("csv-writer").createObjectCsvWriter;
const AWS = require("aws-sdk");

AWS.config = {
  accessKeyId: "accessKeyId",
  secretAccessKey: "secretAccessKey",
  region: "ap-south-1"
};
const s3 = new AWS.S3();
const elastictranscoder = new AWS.ElasticTranscoder();

const csvFilePath = "data.csv";
const csvWriter = createCsvWriter({
  path: "output.csv",
  header: [
    { id: "videoaccountid", title: "Surname" },
    { id: "videoid", title: "Name" },
    { id: "title", title: "Surname" },
    { id: "videourl", title: "Age" }
  ]
});

const headers = [
  "speciality",
  "sn",
  "presentingdoctor",
  "doctorsinformation",
  "venue",
  "year",
  "topicname",
  "subtopics",
  "link",
  "categoryofvideo"
];

const stream = fs.createReadStream(csvFilePath);

const checkHeader = (headers, inputHeaderArray) => {
  return new Promise((resolve, reject) => {
    if (headers.length == inputHeaderArray.length) {
      resolve(inputHeaderArray.every(item => headers.indexOf(item) !== -1));
    } else {
      reject("Headers not present");
    }
  });
};
const validateLink = link => {
  return /(\.|\/)(mp3|mp4)$/i.test(link);
};
const uploadFile = (link, fileName) => {
  return new Promise((resolve, reject) => {
    var options = {
      uri: link,
      method: "GET",
      encoding: null
    };
    request(options, function(error, response, body) {
      if (error || response.statusCode !== 200) {
        console.log("failed to get file");
        console.log(error);
        reject(error);
      } else {
        s3.upload(
          {
            Body: body,
            Key: fileName,
            Bucket: "saarthivideo"
          },
          function(error, data) {
            if (error) {
              console.log("error uploading image to s3");
              reject(error);
            } else {
              console.log("success uploading to s3", data);
              const key = data.Key;
              const pipelineid = "pipelineid";
              transcodeFile(data, key, pipelineid)
                .then(res => resolve(res))
                .catch(err => reject(err));
            }
          }
        );
      }
    });
  });
};
const transcodeFile = (data, key, pipelineid) => {
  console.log(data, key, pipelineid);
  const params = {
    Inputs: [
      {
        Key: key,
        FrameRate: "auto",
        Resolution: "auto",
        AspectRatio: "auto",
        Interlaced: "auto",
        Container: "mp4"
      }
    ],
    OutputKeyPrefix: key,
    Outputs: [
      {
        Key: "hls_2m_",
        ThumbnailPattern: "thumb_2m-{count}",
        Rotate: "auto",
        PresetId: "1351620000001-200010",
        SegmentDuration: "10"
      },
      {
        Key: "hls_1m_",
        ThumbnailPattern: "thumb_1m-{count}",
        Rotate: "auto",
        PresetId: "1351620000001-200030",
        SegmentDuration: "10"
      },
      {
        key: "hls_600k_",
        ThumbnailPatternkey: "thumb_600k-{count}",
        Rotatekey: "auto",
        PresetIdkey: "1351620000001-200050",
        SegmentDuration: "10"
      },
      {
        key: "hls_400k_",
        ThumbnailPatternkey: "thumb_400k-{count}",
        Rotatekey: "auto",
        PresetIdkey: "1351620000001-200050",
        SegmentDuration: "10"
      }
    ],
    Playlists: [
      {
        Format: "HLSv3",
        Name: "index.m3u8",
        OutputKeys: ["hls_2m_", "hls_1m_", "hls_400k_"]
      }
    ],
    PipelineId: pipelineid
  };
  new Promise((resolve, reject) => {
    elastictranscoder.createJob(params, (error, response) => {
      if (error) {
        reject(error);
      } else {
        resolve(response);
      }
    });
  });
};
try {
  stream.on("data", data => {
    csv.parse(data, (err, inputArray) => {
      if (err) {
        throw err;
      } else {
        const headerRow = inputArray[0].map(formatHeader =>
          formatHeader.trim().toLowerCase()
        );
        checkHeader(headers, headerRow)
          .then(response => {
            if (response) {
              inputArray.splice(0, 1);
              inputArray.map((eachRow, index) => {
                const link = eachRow[headerRow.indexOf("link")];
                if (validateLink(link)) {
                  const extension = link.substr(
                    link.lastIndexOf("."),
                    link.length
                  );
                  const fileName = `${eachRow[headerRow.indexOf("year")]}/${
                    eachRow[headerRow.indexOf("topicname")]
                  }/${
                    eachRow[headerRow.indexOf("presentingdoctor")]
                  }/${Date.now().toString()}${extension}`;
                  console.log(link, fileName);
                  return uploadFile(link, fileName);
                } else {
                  console.log("Please upload valid link. Error in row ", index);
                  throw new Error("Please upload valid link. Error in row");
                }
              });
            } else {
              console.error("False headers found!! Please check headers");
              throw new Error("False headers found!! Please check headers");
            }
          })
          .then(uploadSuccess => {
            console.log("File", uploadSuccess);
            console.log("is accessible", inputArray);
          })
          .catch(console.error);
      }
    });
  });
} catch (error) {
  console.log("Error ---- ", error);
}
</pre>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by AllanFly120** [comment]
Hey @ShubhangPlexusMD It looks you have some typos in later 2 `Outputs` members of your `createJob`'s parameters: the `key` should be `Key`, `ThumbnailPatternkey` should be `ThumbnailPattern`,  `Rotatekey` should be `Rotate`, and `PresetIdkey` should be `PresetId`
