### ISSUE TITLE
Cannot connect to CloudFront in China region

### ISSUE THREAD

**Issue by aunpongsit** [aws/aws-sdk-js#2811]
**Describe the bug**
According to [CloudFront in China](https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-cloudfront-is-now-available-in-mainland-china), I tried to use the SDK to connect to CloudFront in China region but it failed due to invalid endpoint.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v8.11.3

**SDK version number**
v2.510.0

**To Reproduce (observed behavior)**
See the code below
```
import AWS from 'aws-sdk';

const credentials = new AWS.SharedIniFileCredentials({profile: 'china'});
const cloudfront = new AWS.CloudFront({
  region: 'cn-north-1',
  credentials,
});

cloudfront.listDistributions({}, (err, data) => {
  if (err) {
    console.error(err);
  } else {
    console.log(data);
  }
});
```
Error: `UnknownEndpoint: Inaccessible host: 'cloudfront.cn-north-1.amazonaws.com.cn'. This service may not be available in the 'cn-north-1' region.`

Am I doing something wrong?

**Additional context**
The aws-cli seems to be working fine with AWS CloudFront in China

**Comment by AllanFly120** [comment]
Hi @aunpongsit 

I tried aws-cli with `--debug` flag, it shows the request is actually sent out to `cloudfront.cn-northwest-1.amazonaws.com.cn` endpoint in `cn-northwest-1` region. I suspect `cn-north-1` doesn't provide Cloudfront yet, so you will see `cn-north-1` is an invalid host. You can try set the region to `cn-northwest-1` or supply the endpoint directly in the config.

**Comment by aunpongsit** [comment]
Using `cn-northwest-1` solves the problem. Thank you so much!
