### ISSUE TITLE
Proxy-agent not fully compatible with AWS service (missing protocol property)

### ISSUE THREAD

**Issue by guenogu** [aws/aws-sdk-js#2815]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
In your documentation <https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html>, you reference the usage of `proxy-agent` package to manage http_proxy for AWS services.

`proxy-agent` allow 2 ways to manage the usage of the http_proxy:
- by configuring the agent, and all request will be through the proxy, independently of the url targetted
- by calculated if a proxy is needed, at each request. In this case, the librairy used another librairy to `getProxyForUrl` (librairy `proxy-from-env`)

In this second way, the librairy used the `protocol` property of the request to determine which environment variables used (`{protocol}_proxy`)

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the Node.js version**
`node -v`
v10.15.3

**SDK version number**
* For Node.js, get SDK version by running command `npm list aws-sdk` from your root directory
`- aws-sdk@2.493.0`

**To Reproduce (observed behavior)**
Behind a corporate proxy, set the environment variable `http_proxy` and `https_proxy` to your corporate proxy (ex: `https://127.0.0.1:3128`)

```js
const proxy = require('proxy-agent');
const S3 = require('aws-sdk/clients/s3');

const client = new S3({
  httpOptions: { agent: new ProxyAgent() }
});

client.getObject({ Bucket: 'xxxx', Key: 'xxxx' })
```

**Expected behavior**
The AWS client, S3 in this cases, can connect to AWS service and retrieve the key in the bucket parameters.
Make the usage of `proxy-agent` fully compatible with AWS-SDK.

**Screenshots**

**Additional context**

**Suggestion to fix it**

Add the `protocol` property to the options object (https://nodejs.org/api/http.html#http_http_request_options_callback)
In the lib/http/node.js
```js
    var options = {
      protocol: endpoint.protocol,    // <-- added line of code
      host: endpoint.hostname,
      port: endpoint.port,
      method: httpRequest.method,
      headers: httpRequest.headers,
      path: pathPrefix + httpRequest.path
    };
```

**Comment by ajredniwja** [comment]
Hey @guenogu,

Thank-you for reaching out, can you open a PR for the issue, we welcome PRs.
