### ISSUE TITLE
AWS.DynamoDB.Converter.unmarshall() fails to maintain escaped characters in string contained in the JSON object being unmarshalled.

### ISSUE THREAD

**Issue by nfegard** [aws/aws-sdk-js#2817]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When using AWS.DynamoDB.Converter.unmarshall() Strings containing escaped characters are not unmarshalled correctly. 
Example: "1/xxxxxxxxxxx/*********/something with inches 14\"" is parsed out as -
1/xxxxxxxxxxx/*********/something with inches 14

**Is the issue in the browser/Node.js?**
no

**If on Node.js, are you running this on AWS Lambda?**
Yes.

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v8.16.0

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `AWS.VERSION` in your code where `AWS = require("aws-sdk");`
v2.514.0

**To Reproduce (observed behavior)**
Try to unmarshal any object containing a string with escaped characters.

**Expected behavior**
Escaped characters and the escaping characters should be maintained when unmarshalling.

**Screenshots**
N/A

**Additional context**

**Comment by nfegard** [comment]
This behavior is inconsistent and only affect some objects. I have not determined a pattern however I believe it has to the with the escaped character being the last character in the string being unmarshalled.

**Comment by ajredniwja** [comment]
Hey @nfegard,

Thank-you for reaching out, I was not able to reproduce this, can you specify your test case where you are trying to use it or provide with some more context. 
Also can you try to switch to latest version of SDK?
