### ISSUE TITLE
ServiceConfigurationOptions.endpoint type should allow AWS.Endpoint

### ISSUE THREAD

**Issue by kyle-johnson** [aws/aws-sdk-js#2822]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
`ServiceConfigurationOptions.endpoint` [is defined](https://github.com/aws/aws-sdk-js/blob/19a5b5936f2356441d9fc02de2c2ca1409439f54/lib/service.d.ts#L74) as type `string`, but [the AWS.Endpoint documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Endpoint.html) suggests an `AWS.Endpoint` object is valid as well:

```js
var ep = new AWS.Endpoint('awsproxy.example.com');
var s3 = new AWS.S3({endpoint: ep});
```

**SDK version number**
v2.518.0

**Expected behavior**
Seems the type should be:
```js
endpoint?: string | Endpoint;
```

**Comment by ajredniwja** [comment]
Hey @kyle-johnson,

Thank-you for reaching out, it can be marked as a feature request, you are welcomed to open a PR about this.

**Comment by esilkensen** [comment]
Hi @ajredniwja, I opened a PR for this here: #2923

**Comment by ajredniwja** [comment]
Hey @esilkensen,

Thank-you for the PR, the team will review the PR and make a decision on merging it or not.

**Comment by esilkensen** [comment]
I think this issue is still valid, though it has been a year and my PR was never reviewed.

**Comment by ajredniwja** [comment]
Apologies for the delay, I merged the PR @esilkensen.
