### ISSUE TITLE
cognito call took too long, ultimately cancelled by the browsers

### ISSUE THREAD

**Issue by funnykanth** [aws/aws-sdk-js#2826]
During authorization process, Aws SDK makes api calls to the following API's:
cognito-idp.us-east-1.amazonaws.com
cognito-identity.us-west-2.amazonaws.com

but these API's fail, during a specific time of the day i.e (19.30 to 20.00 hr IST), other than this time frame the api has no issue.

Error log:
{"message":"Network Failure","code":"NetworkingError","time":"2019-08-27T14:14:20.537Z","region":"us-west-2","hostname":"cognito-identity.us-west-2.amazonaws.com","retryable":true}
20.chunk.js:1 ERR in login component from service callback::  NetworkingError: Network Failure

**Comment by AllanFly120** [comment]
Hi @funnykanth,

Will the requests eventually success? If so, you can increase the [maxRetries configuration](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#maxRetries-property). The default value is 3, you can set it to a higher value so the SDK will retry the `Network Failure` more times.
