### ISSUE TITLE
SNS publish API sned SMS, but the message suffix comes with an [AWS]

### ISSUE THREAD

**Issue by Pinlv** [aws/aws-sdk-js#2834]
import { SNS } from 'aws-sdk'
import { region } from '../env'

const sns = new SNS({ region })

const sendSMS = ({ to, text }) => {
  return sns.publish({
    PhoneNumber: to,
    Message: text
  }).promise()
}
![image](https://user-images.githubusercontent.com/26834369/64151701-875fe580-ce5d-11e9-98c1-64cd54f431b9.png)

**Comment by AllanFly120** [comment]
Hey @Pinlv 

The SDK doesn't add this suffix. Have you tried with other SDKs or [AWS CLI](https://github.com/aws/aws-cli)? 
If the issue persists, it must be a server-side issue. Then you can bring it to the service team on [SNS forum](https://forums.aws.amazon.com/forum.jspa?forumID=72)
