### ISSUE TITLE
Copy individual database using RDS SDK

### ISSUE THREAD

**Issue by ORESoftware** [aws/aws-sdk-js#2836]
I asked this question on SO:
https://stackoverflow.com/questions/57418489/copy-rds-database-not-server-instance-using-sdk

we are using Postgres and Oracle on RDS. I am looking to backup individual databases, using Postgres I am using pg_dump/pg_restore/createdb to do backups, but it would be nice if there were an AWS RDS SDK option that could copy/backup individual databases instead of just the whole db instance.

**Comment by AllanFly120** [comment]
This seems to me a feature request. Can you specify your use case and describe what API are you expecting? We have a [feature request issue template](https://github.com/aws/aws-sdk-js/blob/master/.github/ISSUE_TEMPLATE/---feature-request.md) for this kind of issue. You may need to edit your issue following the issue template.
