### ISSUE TITLE
TS types are not modular enough

### ISSUE THREAD

**Issue by Swatinem** [aws/aws-sdk-js#2846]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

When doing some profiling of TypeScript, I noticed that **a lot** of its memory usage is due to parsing (and keeping all the source in memory) of `aws-sdk`, see the screenshot below…

So I tried changing imports from `import AWS from "aws-sdk";` to `import S3 from "aws-sdk/clients/s3";`, but was surprised that this didn’t help anything for TS performance.

So digging through the code, I found the culprit here:

https://github.com/aws/aws-sdk-js/blob/72aa5bad8bd64598a975f832c92cf6f283bd0bda/lib/config_service_placeholders.d.ts#L1

Those config types are imported from the focused imports, but in turn import *the whole world*, which is not that good.

See below for more detailed performance figures.

**Is the issue in the browser/Node.js?**

node / tsc

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**

node 12.10, tsc 3.7.0 nightly (with custom changes)

**SDK version number**
Example: v2.483.0

**To Reproduce (observed behavior)**

run `tsc --diagnostics` for just a single `import "aws-sdk";` as `import "aws-sdk/clients/s3";`

**Expected behavior**

Using focused imports should help with `tsc` performance.

**Screenshots**

![Bildschirmfoto von 2019-09-13 10-13-24](https://user-images.githubusercontent.com/580492/64906435-d112c080-d6e6-11e9-8baa-12bbc576d3f3.png)

**Additional context**

I did some measurements before and after just basically setting everything in `config_service_placeholders` to `any`:

```
# before

Files:          4728
Lines:        711769
Nodes:       2389311
Identifiers:  830256
Symbols:     1009845
Types:        307990
Memory used: 990893K
I/O read:      0.32s
I/O write:     0.00s
Parse time:    6.02s
Bind time:     2.40s
Check time:   21.04s
Emit time:     0.00s
Total time:   29.45s

# after

Files:          4519
Lines:        414337
Nodes:       1517882
Identifiers:  508685
Symbols:      824693
Types:        307998
Memory used: 756315K
I/O read:      0.21s
I/O write:     0.00s
Parse time:    4.35s
Bind time:     1.64s
Check time:   21.37s
Emit time:     0.00s
Total time:   27.36s
```

As you can see, this is **huge (!!!)**. This basically means that a single `aws-sdk` import pulls in ~200 files, with ~800k parse nodes, leading to **¼** of the total memory usage of `tsc`.

**Comment by Swatinem** [comment]
> tsc 3.7.0 nightly (with custom changes)

btw, those are here: https://github.com/microsoft/TypeScript/pull/33431

**Comment by ajredniwja** [comment]
Hey @Swatinem,

Thank-you for reaching out, this is not necessarily a bug but SDK behavior since it packages all of the services in a single package. While we strive to make JS-SDK-V2 better you can give [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3) a try and give your reviews which uses modularized packages and is under developer preview right now, more information found [here](https://aws.amazon.com/blogs/developer/new-aws-sdk-for-javascript-developer-preview/). 
If you would like some hands on experience you can try the [workshop](https://github.com/aws-samples/aws-sdk-js-v3-workshop) which takes you through some drastic memory differences between v2 and v3.

I will close the issue for now, please reach out if you have any additional questions.
