### ISSUE TITLE
Relaxed versions?

### ISSUE THREAD

**Issue by daveisfera** [aws/aws-sdk-js#2847]
**Is your feature request related to a problem? Please describe.**
Specific versions of dependencies are used

**Describe the solution you'd like**
`^` is used to specify version to make it more likely that a single version is installed and allow updates to be applied

**Describe alternatives you've considered**
Use `~` to allow at least some flexibility

**Comment by trivikr** [comment]
@daveisfera Can you be more explicit?
The `~` and `^` in our npm versions works as described in https://semver.npmjs.com/

**Comment by daveisfera** [comment]
Currently, `dependencies` is as follows in `package.json` and it's all specific versions:
```
"dependencies": {
    "buffer": "4.9.1",
    "events": "1.1.1",
    "ieee754": "1.1.8",
    "jmespath": "0.15.0",
    "querystring": "0.2.0",
    "sax": "1.2.1",
    "url": "0.10.3",
    "uuid": "3.3.2",
    "xml2js": "0.4.19"
  }
```

I'm requesting that they be changed to use `^` instead of being specific versions

**Comment by trivikr** [comment]
Is there an issue you're facing because of using specific versions?

**Comment by daveisfera** [comment]
Currently, I end up with multiple versions of the above dependencies and/or the installation of a bug/security fix is prevented without updating updating `aws-sdk`. Using `^` (or at least `~`) allows flexibility on the users end and allows the update to be installed without updating `aws-sdk`.

**Comment by trivikr** [comment]
Can you give an example of how installation of bugfix/security fix was prevented by aws-sdk because of using using pinned versions?

**Comment by daveisfera** [comment]
If you run `yarn outdated` on the current `package.json` file, then you get the following output and `ieee754`, `sax`, `uuid`, and `xml2js` all have point releases that can't be used without an update to `aws-sdk` and `url` also has a minor release with the same thing going on:
```
buffer  4.9.1   4.9.1  5.4.3  dependencies https://github.com/feross/buffer                
events  1.1.1   1.1.1  3.0.0  dependencies https://github.com/Gozala/events#readme         
ieee754 1.1.8   1.1.8  1.1.13 dependencies https://github.com/feross/ieee754#readme        
sax     1.2.1   1.2.1  1.2.4  dependencies https://github.com/isaacs/sax-js#readme         
url     0.10.3  0.10.3 0.11.0 dependencies https://github.com/defunctzombie/node-url#readme
uuid    3.3.2   3.3.2  3.3.3  dependencies https://github.com/kelektiv/node-uuid#readme    
xml2js  0.4.19  0.4.19 0.4.22 dependencies https://github.com/Leonidas-from-XIV/node-xml2js
```

**Comment by ajredniwja** [comment]
Hi @daveisfera,

I apologize for a late reply, but the best practice is to use the latest version of the SDK, since the team keeps striving to make the SDK better. Running ```yarn outdated``` doesn't indicate me with any files, I would highly recommend to use the latest version of the SDK. 

Closing this issue now, please re open if you have any additional input.

**Comment by daveisfera** [comment]
I agree that using the latest version is best, but even if we updated to the latest version of of `aws-sdk` the instant that it came out, it wouldn't address the problem of multiple versions being installed of dependencies and releases of dependencies not be used.

**Comment by jpaas** [comment]
I'm using the latest version `2.559.0` and I am also having a problem with it not being able to resolve `xml2js`

**Comment by jpaas** [comment]
In my case I have another module that has a dependency on `xml2js "^0.4.17"`, which resolves as `0.4.22` instead of `0.4.19`

**Comment by jpaas** [comment]
Sorry I made a mistake on the version I'm using `2.518.0`. I'm still struggling with this issue. Even if I pin the desired version of xml2js to `0.4.19` using resolutions, it is still not found.

**Comment by jpaas** [comment]
Its looking for `./dist/xml2js.js`, but the installed node module for `0.4.19` does not have a `dist` folder, just a `lib` folder.
```
Resolving ./dist/xml2js.js...
error: bundling failed: Error: Unable to resolve module `xml2js` from `../node_modules/aws-sdk/lib/xml/node_parser.js`: xml2js could not be found within the project.
```

**Comment by jpaas** [comment]
I think this must related to a combination of using yarn workspaces, and using `@sentry/webpack-plugin` which ultimately has another dependency on xml2js `^0.4.17`. I tried `nohoist` on it, but still no luck.

**Comment by daveisfera** [comment]
This should be something specific to your setup. `node` can handle multiple versions of a module being installed (even with yarn workspaces because we're using them). The issue is just keeping bundles and node_modules small and this won't cause anything to break, so you have something in your setup that is causing the breakage

**Comment by trivikr** [comment]
Reopening as there are open questions.

@daveisfera @jpaas can you create issues (or even better - Pull Requests) for the dependencies which you want to update?

Note that JS SDK v2 currently support Node.js versions from v0.10 onwards

**Comment by jpaas** [comment]
Actually, after continuing to try and debug this, I'm less convinced this has anything to do with my yarn workspace setup now, but rather the fact that the require ends up looking for `dist/xml2js.js`...
```
 BUNDLE  [ios, dev] ./index.ts ▓▓▓▓▓▓▓▓░░░░░░░░ 51.0% (442/619)>>> Resolving xml2js from /Users/jpaas/Documents/osaaru/ts-hockey/node_modules/aws-sdk/lib/xml/node_parser.js
[
  '/Users/jpaas/Documents/osaaru/ts-hockey/node_modules/aws-sdk/lib/xml/node_modules/dist/xml2js.js',
  '/Users/jpaas/Documents/osaaru/ts-hockey/node_modules/aws-sdk/lib/node_modules/dist/xml2js.js',
  '/Users/jpaas/Documents/osaaru/ts-hockey/node_modules/aws-sdk/node_modules/dist/xml2js.js',
  '/Users/jpaas/Documents/osaaru/ts-hockey/node_modules/node_modules/dist/xml2js.js',
  '/Users/jpaas/Documents/osaaru/ts-hockey/node_modules/dist/xml2js.js',
  '/Users/jpaas/Documents/osaaru/node_modules/dist/xml2js.js',
  '/Users/jpaas/Documents/node_modules/dist/xml2js.js',
  '/Users/jpaas/node_modules/dist/xml2js.js',
  '/Users/node_modules/dist/xml2js.js'
]
[]
error: bundling failed: Error: Unable to resolve module `xml2js` from `../node_modules/aws-sdk/lib/xml/node_parser.js`: xml2js could not be found within the project.
```
