### ISSUE TITLE
Migrate istanbul to nyc

### ISSUE THREAD

**Issue by tnir** [aws/aws-sdk-js#2851]
You could see the following deprecation warning during `npm install`:
```
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
```

**Comment by ajredniwja** [comment]
@tnir We need to test the code base since this is based on very old node version and NYC is not compatible with those versions. We'd be happy to merge the PR if the PR passes all the tests. I will close the issue and can monitor the PR. Please re-open if you have any questions.
