### ISSUE TITLE
Typescript interface definition wrong for Request onAsync events

### ISSUE THREAD

**Issue by iamatypeofwalrus** [aws/aws-sdk-js#2855]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm writing an application that is putting data to CloudWatch via the `PutMetricData` API in Lambda. The code itself is written in Typescript. My payloads are large so I am trying to take advantage of gzip compression by following along with the suggestions in #2297, specifically [this comment](https://github.com/aws/aws-sdk-js/issues/2297#issuecomment-429405253).

The Typescript compiler won't allow me to to use a function with a signature like `(req, done) => {...}` because [the interface described in the typescript interface file does not include a doneCallback](https://github.com/aws/aws-sdk-js/blob/41c9d5a2ca0c455bea55c98bb99e647eed2c8781/lib/request.d.ts#L201). According to [this code async listeners are passed a `doneCallback`](https://github.com/aws/aws-sdk-js/blob/cb1604ca89a077ffdb86127884292d3b18c8b4df/lib/sequential_executor.js#L102)

**Is the issue in the browser/Node.js?**
Node.js + Typescript

**If on Node.js, are you running this on AWS Lambda?**
Yes.

**Details of the browser/Node.js version**
```
$ node --version
v10.16.0
```

**Typescript version**
```
"typescript": "^3.3.4000"
```

**SDK version number**
```
"aws-sdk": "^2.427.0",
```

**To Reproduce (observed behavior)**
n/a

**Expected behavior**
Expect Typescript interface definitions for Request.onAsync methods to have a signature that includes the `doneCallback`.

**Comment by ajredniwja** [comment]
Hey @iamatypeofwalrus,

Thank-you for reaching out. I have reached to the SDK team, they will try to work on it. It will be great if you can open a [PR](https://github.com/aws/aws-sdk-js/compare), we always welcome PRs.

**Comment by mhart** [comment]
This is still an issue FWIW – we've just run into this too (also `req.httpRequest.body` is typed as a string, whereas it can actually also be a Stream or a Buffer)

**Comment by jeromecovington** [comment]
Here's an example of the kind of casting necessary without these typings in the codebase.
```typescript
// Casting event callback as any because the signature in the typescript types does not
// define the done() argument. See the following for more.
// https://github.com/aws/aws-sdk-js/issues/2855
const buildCallback: any = (req: any, done: any) => {
  const result = gzipSync(req.httpRequest.body)
  req.httpRequest.headers['Content-Encoding'] = 'gzip'
  req.httpRequest.headers['Content-Length'] = result.length
  // Casting result as any because there is some misunderstanding between the typescript
  // types and the javascript source (string vs string|Buffer). See the following for more.
  // https://github.com/aws/aws-sdk-js/blob/14e9bf0abab009e2f34f11623949375b7bd07d2a/lib/http_request.d.ts#L21
  // https://github.com/aws/aws-sdk-js/blob/14e9bf0abab009e2f34f11623949375b7bd07d2a/lib/http/node.js#L115-L142
  req.httpRequest.body = result as any
  done()
}

// Other code...

await cloudwatch
  .putMetricData({
    MetricData: metricData,
    Namespace: 'MyNamespace',
  })
  .onAsync('build', buildCallback)
  .promise()
```

**Comment by drodil** [comment]
Seems like the #3511 is not merged. For some reason I am getting HTTP error 500 when trying to send gzipped content in putMetricData:
`
cloudWatch.putMetricData(r).on('build', (request) => {
      request.httpRequest.headers['Content-Encoding'] = 'gzip';
      zlib.gzip(request.httpRequest.body, function (err, result) {
        if (err) {
          throw err;
        }
        request.httpRequest.body = result;
      });
    });
`
Might need to try adding the Content-Length header but not sure if that fixes the problem
