### ISSUE TITLE
Incomplete documentation of shield.associateDRTRole

### ISSUE THREAD

**Issue by adclark1** [aws/aws-sdk-js#2856]
The documentation here:

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Shield.html

Under the associateDRTRole method, it says: "You must have the iam:PassRole permission to make an AssociateDRTRole request." I have discovered that the following permissions are also necessary and should be documented:

- iam:GetRole (often required when using iam:PassRole)
- iam:ListAttachedRolePolicies (presumably needed for Shield to ensure that the AWSShieldDRTAccessPolicy managed policy is attached)

These can safely be scoped down to the role that is being passed. I imagine this is not necessarily missing documentation in the SDK, but in the core API docs. Such was the case in this ticket as well: https://github.com/aws/aws-sdk-js/issues/2809

This should be documented somewhere. It should also be captured in the Errors section under AccessDeniedForDependencyException on this page:

https://docs.aws.amazon.com/waf/latest/DDOSAPIReference/API_AssociateDRTRole.html

**Comment by ajredniwja** [comment]
Hey @adclark1,

Thank-you for reaching out, I can reach out to the docs team and have them work on it. Closing the issue,  please re-open if you have additional queries.
