### ISSUE TITLE
Horizontal Scaling for SQS Producers

### ISSUE THREAD

**Issue by sfeldkamp** [aws/aws-sdk-js#2857]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

**Environment:**
aws-sdk@2.531.0
node v8.15.0

**Goal:** 
Send about 600,000 SQS messages in a relatively short amount of time.

**What I'm doing now:**

1) Chunk array of data for messages into batches of 10
2) Loop over chunks and call sqs.sendBatchMessage

**What is happening:**

Out of memory errors and _none_ of the messages ever arrive to SQS.

**Research**

I've limited the number of batches to an amount that can run to completion without OOM errors.
I've attached event listeners to the Request objects 'build' and 'send' events that are created before sending and then log those out.  

The output always looks like this.

```
build
build
build
build
... builds until all batches are processed
send
send
send
send
...sends until all batches are processed
```

This occurs no matter how I iterate over the batches.  No matter how many batches there are.  I've tried a sleep in between calls to sqs.sendMessageBatch.  I've tried constructing an entirely new SQS client for each batch.  I've even required the aws-sdk lib in each iteration.

**Questions**

Why are none of the requests 'send' events occurring until all of the calls to sqs.sendBatchMessage are complete?

If this is expected behavior, is there a way to horizontally scale the solution?  This article recommends that, but all of the examples are Java.
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-throughput-horizontal-scaling-and-batching.html

**Comment by ajredniwja** [comment]
Hey @sfeldkamp, thank-you for reaching out and your patience, can you please share the code you are using ?

**Comment by godtaehee** [comment]
Is there any PR or Feature Adding related with this issue????

Is still existed in only Java Examples like [this reference](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-throughput-horizontal-scaling-and-batching.html)???
