### ISSUE TITLE
ssm.listDocuments Filters not working

### ISSUE THREAD

**Issue by kingkenmark** [aws/aws-sdk-js#2858]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
ssm.listDocuments Filters not working.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?** 
No

**Details of the browser/Node.js version**
v10.16.3

**SDK version number**
v2.532.0

**To Reproduce (observed behavior)**
1. Create ssm document and add tag key: 'branch', value: 'prod'.
2. Write up javascript file(test.js) contains following code:
```JavaScript
const ssm = aws('SSM');

var params = {
    Filters: [
        {
            Key: 'tag:branch',
            Values: [
                'prod'
            ]
        }
    ]
};

ssm.listDocuments(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});

```
3. node test.js

**Expected behavior**
return DocumentIdentifiers which is not empty

**Screenshots**

**Additional context**
If use aws cli to run aws ssm list-documents --filters Key=tag:branch,Values=prod, it works

**Comment by ajredniwja** [comment]
hey @kingkenmark,

Thank-you for reaching out, can you please explain more about the error that you are getting?
You can do something like: 

```JavaScript
const ssm = new AWS.SSM({logger: console}); 
```
