### ISSUE TITLE
(MediaConvert) Is it possible to wait for job in promise? 

### ISSUE THREAD

**Issue by sizovilya** [aws/aws-sdk-js#2859]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Hello everyone! I would like to add an option for users to upload videos to a website. 
I am using the aws sdk, I can submit a job to aws Elemental MediaConvert for transcoding video. 
`const endpointPromise = await mediaConvert.createJob(params).promise();`
**Is it possible to wait for transcoding ?**  I mean, without using CloudWatch and SNS. I need more simple way.

**Comment by thelebdev** [comment]
Can you elaborate a bit more on your question? @sizovilya
