### ISSUE TITLE
Calling lambda.createFunction on an existing function deletes tags on the function.

### ISSUE THREAD

**Issue by Kasmilos** [aws/aws-sdk-js#2860]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
In a Lambda function I call lambda.createFunction(params) to create a new function. If that function already exists, it deletes the tags on that function.

**Is the issue in the browser/Node.js?**
Node.js in Labmda environment

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
nodejs10.x

**SDK version number**
Version current in Lambda environement

**To Reproduce (observed behavior)**
Execute lambda.createFunction(params) where params.Tags.SomeKey = "SomeValue"
Observe the function is created and has the expected tag.
Execute the same function again with the same values. An exception is thrown (Function already exist)
Observe the function stil exists but no longer has the tag.

**Expected behavior**
The tags should exist after the second call

**Comment by ajredniwja** [comment]
Hey @Kasmilos,

I have reached to the lambda team internally, and will update you once I hear back from them.

**Comment by ajredniwja** [comment]
Now the issue will only happen when all of the following conditions are met:

1). An AWS account tries to create Lambda Functions concurrently
2). The concurrent create requests try to create Lambda Functions with the same ARN
3). The concurrent requests provide tag information

Would just need to avoid any of these situations. 

Closing this now, let me know if you have additional questions.
