### ISSUE TITLE
node-pre-gyp broke

### ISSUE THREAD

**Issue by charliekump-wf** [aws/aws-sdk-js#2861]
https://github.com/mapbox/node-pre-gyp/issues/477

Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

**Is the issue in the browser/Node.js?**
Browser/Node.js

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `AWS.VERSION` in your code where `AWS = require("aws-sdk");`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by thewebninja** [comment]
Looks like someone messed up :/ can't build anything with Docker at the moment.

**Comment by AllanFly120** [comment]
Hey @charliekump-wf I don't get this issue when installing in local(Mac) or docker. I'm installing the newest version(v2.534.0). Can you provider detailed triggering condition?

**Comment by charliekump-wf** [comment]
Seems to only happen in our dockerized linux environments, doesn't reproduce locally for me either.

Here are the package combos:

``` "dependencies": {
    "codeceptjs": "2.3.1",
    "codeceptjs-resemblehelper": "1.7.0",
    "mocha": "6.2.0",
    "mocha-junit-reporter": "1.23.1",
    "mocha-multi": "latest",
    "puppeteer": "1.19.0",
    "shelljs": "0.8.3",
    "unit.js": "2.1.0"
  }
}```

**Comment by charliekump-wf** [comment]
@AllanFly120 We can close this issue, appears to be an issue in minipass. When I added a pin to 2.7.0, it resolved. Thanks for looking

https://github.com/lovell/sharp/issues/1882#issuecomment-534266128
