### ISSUE TITLE
S3 Uploading file incomplete, files damaged

### ISSUE THREAD

**Issue by jonathanbrenman** [aws/aws-sdk-js#2865]
I'm trying to upload files pdf and the files are damaged and the size it is smaller than the original this is the code.

```
fs.readFile(file_location, function (err, data) {
            if (err) {
                console.log(err);
            }
            s3.putObject({
                Bucket: "files.bdin.me",
                Key: filename,
                Body: data,
                ContentType: contentType
            }, function (resp) {
                console.log(resp);
            });
        });
```

When I download the s3 file I receive the error in the attachment
<img width="744" alt="Screen Shot 2019-09-25 at 1 24 10 AM" src="https://user-images.githubusercontent.com/24918136/65569388-d3211e80-df33-11e9-881a-8f3984ecf4b6.png">

**Comment by trivikr** [comment]
@jonathanbrenman what's the reason for closing this issue?

**Comment by jonathanbrenman** [comment]
Hi trivik, the issue was not on the s3 sdk side.
The problem was that I use mutter with node and when you upload the file mutter put in a specific directory that you tell him to do it. the issue with that was that I was uploading the file and the watcher intercepted the file and uploaded before the file finished to be written so obviously when the files were in s3 they were damaged.

I fix that by uploading the file to a tmp folder how it is supposed to be and when it finish I move into my watcher folder and now its working fine.
