### ISSUE TITLE
Missing SQS Send message on Timers

### ISSUE THREAD

**Issue by LRagji** [aws/aws-sdk-js#2869]
**Is your feature request related to a problem? Please describe.**
We are trying to ingest SQSMessage with Delay, We are using Node.js with AWS lambda, though this [documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-send-message-with-timer.html) talks its possible. we couldn't find the appropriate method in SDK

**Describe the solution you'd like**
Either the missing method "setDelaySeconds" is implemented or a way to achieve similar functionality or if we have missed the said functionality in the SDK.

**Describe alternatives you've considered**
1)After looking into JAVA SDK it feels its just a param [LINK](https://github.com/aws/aws-sdk-java/blob/5106b4a75d8c4d882ebda5c718e58acb1a1c200e/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/model/transform/SendMessageRequestMarshaller.java) in the request but i cannot find where has this to be set..
2)Use a new que with is inherently delayed..

**Additional context**
We are using this in AWS Lambda so setinterval or any other method of this type will not work for us

**Comment by ajredniwja** [comment]
Hi @LRagji,

Thank-you for reaching out. The functionality for a delayed message can be achieved by setting it in the params during the call to the API. There are examples [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#sendMessage-property) on how to set it for a particular call, you can look for the attribute DelaySeconds which should be an Integer value with valid values: 0 to 900. Maximum: 15 minutes. Note : When you set FifoQueue, you can't set DelaySeconds per message. You can set this parameter only on a queue level. Please reach out if you have any additional questions.

**Comment by LRagji** [comment]
Thanks for the link, not sure how i missed it, Anyways will close this request if i encounter anything will reach back..
