### ISSUE TITLE
CloudFront.Signer.getSignedCookie() returns invalid cookies with used with url and expires options

### ISSUE THREAD

**Issue by zolaemil** [aws/aws-sdk-js#2870]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The cookies returned by `CloudFront.Signer.getSignedCookie()`, when using with `url` and `expires` options, cannot be used to access restricted content.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No.

**Details of the browser/Node.js version**
```
$ node --version
8.11.1
```

**SDK version number**
v2.532.0

**To Reproduce (observed behavior)**
```
  const privateKey = readFileSync(path.resolve(__dirname, './etc/cf-key.pem')).toString();
  const signer = new AWS.CloudFront.Signer(keypairId, privateKey);

  const options = {
    url: 'https://cloudfront.example.com/foo',
    expires: Math.round(new Date().getTime() / 1000) + 3600,
  };

  const cookies = signer.getSignedCookie(options);
```

The returned `cookies` object has the following keys:
```
Expires
Signature 
Key-Pair-Id
```

Then send the values as the following cookies along with the request to `https://cloudfront.example.com/foo`:
```
CloudFront-Expires
CloudFront-Signature
CloudFront-Key-Pair-Id
```
This results in a `403 Forbidden` response from CloudFront.

**Expected behavior**
I expect that, sending the returned values as the cookies described above, I should be able to access the resource `https://cloudfront.example.com/foo`

**Additional context**
It may be that CloudFront does not actually authorise the access based on the following cookies:
```
CloudFront-Expires
CloudFront-Signature
CloudFront-Key-Pair-Id
```
but it _always_ requires the generated `Policy`:
```
CloudFront-Policy
CloudFront-Signature
CloudFront-Key-Pair-Id
```

If so, a possible fix would be to return the generated `Policy` instead of `Expires` in https://github.com/aws/aws-sdk-js/blob/master/lib/cloudfront/signer.js#L35. I've verified this fix, I could indeed use the returned cookies to access the restricted resource. Happy to send PR if it's welcome.

If not (i.e. CloudFront should indeed accept `Expires` cookie and the `Signature` without providing a `Policy` in the cookies) then it may be a bug in CloudFront itself, not in this SDK. In this case, please feel free to port this bug report over there.

**Comment by zolaemil** [comment]
This is essentially a re-submission of https://github.com/aws/aws-sdk-js/issues/2169 which had been closed due to inactivity on the thread.

**Comment by ajredniwja** [comment]
Hey @zolaemil,

Thank-you for reaching out, you are welcomed to open a PR for the issue for the SDK team to have a look at.
