### ISSUE TITLE
 This service may not be available in the `eu-west-1' region.

### ISSUE THREAD

**Issue by anshnagrath** [aws/aws-sdk-js#2873]
var costexplorer = new AWS.CostExplorer({region: 'eu-west-1'})
UnknownEndpoint: Inaccessible host: `ce.eu-west-1.amazonaws.com'. This service may not be available in the `eu-west-1' region

**Comment by trivikr** [comment]
Please create a new issue by following [existing templates](https://github.com/aws/aws-sdk-js/issues/new/choose) which asks for important details like versions.
It helps triage/debug the issue faster.

**Comment by trivikr** [comment]
To resolve this specific query, CostExplorer provides only `us-east-1` service endpoint
User Guide: https://docs.aws.amazon.com/en_pv/awsaccountbilling/latest/aboutv2/ce-api.html

**Comment by anshnagrath** [comment]
All the regions are supported in boto3 (python3 aws sdk)
