### ISSUE TITLE
New issue for #1895: "S3 cannot handle connection interruption; weird ?max-keys=0 requests"

### ISSUE THREAD

**Issue by simonbuchan** [aws/aws-sdk-js#2875]
Re-opening #1895 as suggested by bot lock message.

Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
If there is a network interruption before trying to perform an S3 operation then `S3.reqRegionForNetworkingError` will go into a strange retry behavior sending a "list objects" request with max keys=0 in order to determine the bucket region, which is fine, but without a retry limit or delay or backoff. This is regardless of if a region was provided in S3 options.

**Is the issue in the browser/Node.js?**
Browser (It does not attempt this in node for some reason).

**Details of the browser/Node.js version**

**SDK version number**
Code still present, in `lib/clients/s3.js`, git blame attributes the change back to #992

**To Reproduce (observed behavior)**
From original comments there are several causes, all essentially seem to be in the form of:
- Make a successful request to bucket
- Do something that causes a `NetworkError`:
  - unplug / disable internet or fake in dev tools
  - abort a multipart upload

**Expected behavior**
Ideally, wouldn't try to determine region if it were provided, but that's probably a back-compat issue now.

Normal retry limit and backoff behavior should apply.

Network Error should be reported after normal retry behavior fails.

**Screenshots**

**Additional context**

**Comment by AllanFly120** [comment]
Thank you @simonbuchan I can identify this is a rough edge in the SDK. Ideally the `listObject` call should take the retry configs from the original S3 client. So by default it will only have max retry of 3 times. Maybe some logic is convoluted together. We need to take a closer look at it.

**Comment by ajredniwja** [comment]
Hey @simonbuchan, Apologies for a late reply, is this still a persisting issue?

I was not able to reproduce the behavior.
