### ISSUE TITLE
[SQS] message attributes [11] exceeds the allowed maximum when I actually send only 5 messageAttributes

### ISSUE THREAD

**Issue by ilan-deepreach** [aws/aws-sdk-js#2876]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)

**Describe the bug**
When I post a message with 5 messageAttributes AWS js sdk tells me that I actually have 11 message attributes and therefore won't send my message.

```
    const data = await sqs
      .sendMessage({
        MessageBody: payload,
        QueueUrl: campaignQ.QueueUrl,
        MessageAttributes: {
          actionType: { DataType: 'String', StringValue: 'a' },
          channel: { DataType: 'String', StringValue: 'a' },
          campaignId: { DataType: 'Number', StringValue: '1' },
          jobId: { DataType: 'String', StringValue: 'e' },
          actionId: { DataType: 'String', StringValue: 'o' },
        },
      })
      .promise();
```
Sending with 4 MessageAttributes works fine.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
10.X (running in a lambda)

**SDK version number**
2.538.0

**To Reproduce (observed behavior)**
See code above

**Expected behavior**
I expect sendMessage with 5 messageAttributes to work instead of telling me that I sent 11 message attributes (which exceeds the limit).

**Screenshots**
I don't feel like it is necessary.

**Additional context**
Nothing to declare.

**Comment by ajredniwja** [comment]
Hi @ilan-deepreach,

Thank-you for posting your issue. I wasn't able to reproduce this behavior. Are there any other details of your setup that might help with reliable steps to reproduce?

**Comment by ilan-deepreach** [comment]
When I have time I'll try to setup an isolated AWS environment with only SQS and nothing else to check if I still have this problem.

**Comment by ajredniwja** [comment]
@ilan-deepreach, I will be closing this issue for now if you still see this problem or have any questions you can reopen the the issue to reach out.
