### ISSUE TITLE
TimeoutError: Connection timed out after 120000ms

### ISSUE THREAD

**Issue by kishor1221** [aws/aws-sdk-js#2880]
I am seeing above time out error while downloading the file having size 6mb using below lines of code from s3. its a Nodejs environment. I tried multiple ways that were discussed in web, in earlier threads but nothing is working. Please help me find a solution.

creating s3 stream using below line of code :
const aReadStream = s3(s3Config.accessKeyId, s3Config.secretAccessKey).getObject(downloadParams).createReadStream();

making use of it while uploading it using ssh2-sftp-clint library.

sftp.put(contentStream, filePathOnSftpServer, { autoClose: true });

**Comment by ajredniwja** [comment]
Hi @kishor1221,

Thank-you for reaching out. Is it possible for you to follow the [issue template](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug+report&template=---bug-report.md&title=) since there would be more information required.
