### ISSUE TITLE
Pass Callback Function in AWS.ApiGatewayManagementApi.postToConnection Send Duplicate Data to the Client

### ISSUE THREAD

**Issue by SLYJason** [aws/aws-sdk-js#2883]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm using Lambda function which is the consumer of Kinesis stream to send data continously from Kinesis to the API WebSocket Gateway. What I found was pass callback function in `AWS.ApiGatewayManagementApi.postToConnection` will send duplicate value to the client. If I don't pass, all good.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
Node.js 10.x

**SDK version number**
2.488.0

**To Reproduce (observed behavior)**
Pass the callback function in the `postToConnection` cause the duplicates:
```
await apigwManagementApi.postToConnection({
    ConnectionId: connectionId,
    Data: rawLog
}, function(err, data) {
    if (err) {
        console.log(`postToConnection error: ${JSON.stringify(err)}`);
    } else {
        // console.log(`Successful response: ${JSON.stringify(data)}`);
    }
}).promise();
```
Do not pass the callback function in the `postToConnection` will not cause the duplicates:
```
await apigwManagementApi.postToConnection({
    ConnectionId: connectionId,
    Data: rawLog
}).promise();
```

**Expected behavior**
Should get unique data payload from the API Gateway when pass the callback function in the `postToConnection` method.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by AllanFly120** [comment]
Hi @SLYJason 
This is intended behavior. If you take a look at [the SDK user guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/using-promises.html), you will find using callback and promise are different 2 ways to make requests. They are not supposed  to be used together.
