### ISSUE TITLE
Does Elasticsearch service support percolator queries ?

### ISSUE THREAD

**Issue by wildwilder** [aws/aws-sdk-js#2885]
I'm not sure if AWS ES supports percolator, but I'm following ES documentation to create a percolator query
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-percolate-query.html

I've created a domain and being able to successfully create a percolator index and even add a query to it, but when I try to run my document example against it I'm getting this error:

Request ID:
"1401fcbb-eebd-44f6-b005-f70431ed92c4"

Function Logs:
START RequestId: 1401fcbb-eebd-44f6-b005-f70431ed92c4 Version: $LATEST
2019-10-05T12:44:46.173Z	1401fcbb-eebd-44f6-b005-f70431ed92c4	INFO	403 Forbidden
2019-10-05T12:44:46.174Z	1401fcbb-eebd-44f6-b005-f70431ed92c4	INFO	Response body: {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
END RequestId: 1401fcbb-eebd-44f6-b005-f70431ed92c4

Here is a lambda function code I'm using:

var AWS = require('aws-sdk');

var region = 'us-east-1';
var domain = '<es domain>';

var endpoint = new AWS.Endpoint(domain);

exports.handler = (event, context) => {
    indexDocuments();
};

function indexDocuments() {
    var request = new AWS.HttpRequest(endpoint, region);

    // To create an index
    // request.method = 'PUT';

    // request.path = '/my_query';
    // request.body = JSON.stringify({
    //     "mappings": {
    //         "properties": {
    //             "message": {
    //                 "type": "text"
    //             },
    //             "query": {
    //                 "type": "percolator"
    //             }
    //         }
    //     }
    // });

    // To add query
    // request.path = '/my_query/_doc/1?refresh';

    // request.body = JSON.stringify({
    //     "query": {
    //         "match": {
    //             "message": "world"
    //         }
    //     }
    // });

    // To perform match
    request.method = 'GET';

    request.path = '/my_query/_search';

    request.body = JSON.stringify({
        "query": {
            "percolate": {
                "field": "query",
                "document": {
                    "message": "Hello world",
                }
            }
        }
    });

    request.headers['host'] = domain;
    request.headers['Content-Type'] = 'application/json';
    // Content-Length is only needed for DELETE requests that include a request
    // body, but including it for all requests doesn't seem to hurt anything.
    // request.headers['Content-Length'] = Buffer.byteLength(request.body);

    var credentials = new AWS.EnvironmentCredentials('AWS');
    var signer = new AWS.Signers.V4(request, 'es');
    signer.addAuthorization(credentials, new Date());

    var client = new AWS.HttpClient();
    client.handleRequest(request, null, function(response) {
        console.log(response.statusCode + ' ' + response.statusMessage);
        var responseBody = '';
        response.on('data', function(chunk) {
            responseBody += chunk;
        });
        response.on('end', function(chunk) {
            console.log('Response body: ' + responseBody);
        });
    }, function(error) {
        console.log('Error: ' + error);
    });
}

**Comment by trivikr** [comment]
@wildwilder can you please share reason for closing? What was the issue?
