### ISSUE TITLE
SharedIniFileCredentials doesnt seem to work with profile/source profile

### ISSUE THREAD

**Issue by OlafConijn** [aws/aws-sdk-js#2887]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Hi, i am trying to use the `SharedIniFileCredentials` on a profile that uses a source profile.
aws config:
```
[profile]
output = json
region = eu-central-1

[profile profile-mfa]
role_arn = arn:aws:iam::xxxx:role/AdminRole
source_profile = profile
mfa_serial = arn:aws:iam::xxxx:mfa/admin
```
aws credentials:

```
[profile]
aws_access_key_id = AKIAxxxxx...
aws_secret_access_key = aabccddeeff...
```

If i use the aws commandline tool, e.g. `aws sts get-caller-identity --profile profile-mfa` i get a prompt to enter an MFA code for the serial configured in `profile profile-mfa`. This is where i assume my config/credentials are configured properly.

However, if i try to use `SharedIniFileCredentials` to use profile `profile-mfa` it does not seem to work. I get an error that indicate the credentials are missing `CredentialsError: Missing credentials in config`. and in the callback of the `SharedIniFileCredentialsOptions` i get an error: `SharedIniFileCredentialsProviderFailure: Profile profile-mfa not found`.

If i do this by parsing the credentials/config myself, loading the credentials from `profile` and assuming the role in `profile-mfa` (and pass the serial & token) it does work.

the way i use the `SharedIniFileCredentials` is as follows:
```JavaScript
const options: SharedIniFileCredentialsOptions = {
    profile: 'profile-mfa',
    disableAssumeRole: false,
    callback:  (err) => {
        // outputs: SharedIniFileCredentialsProviderFailure: Profile profile-mfa not found
        console.log(`SharedIniFileCreds Error: ${err}`)
      },
    tokenCodeFn: (mfaSerial, done)  => {
        //never called :-(...
        console.log(`serial: ${mfaSerial}`);
        done(null, '123123');
    }
};
const credentials = new AWS.SharedIniFileCredentials(options);
AWS.config.credentials = credentials;
const sts = new STS();
sts.getCallerIdentity({}, (err, x) => {
    //outputs: CredentialsError: Missing credentials in config
    console.log(err); 
})
```

the aws sdk version i use is 2.543.0

**Comment by ajredniwja** [comment]
Hey @OlafConijn,

Thank-you for reaching out, since it is not able to find the profile that you are mentioning can you try,
1. Using the credentials file directly. 
2. If you still get an error, save the credential information to a file and use the local path to use it.

```JavaScript
var creds = new AWS.SharedIniFileCredentials({profile: profile-name, filename: 'path to profile file'});

AWS.config.credentials = creds; 
```

Please reach out if that doesn't solve the issue.
