### ISSUE TITLE
aws-sdk gives error with TypeScript 3.5

### ISSUE THREAD

**Issue by ajit-kumar-azad** [aws/aws-sdk-js#2893]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I am using was-sdk to integrate with SQS in my Angular application that uses TypeScript 3.5.3. The application builds. However, in the browser it shows the following error trace:
```
[Error] ReferenceError: Can't find variable: global
	./node_modules/buffer/index.js (vendor.js:181862)
	__webpack_require__ (runtime.js:80)
	./node_modules/aws-sdk/lib/browserHashUtils.js (vendor.js:169404)
	__webpack_require__ (runtime.js:80)
	./node_modules/aws-sdk/lib/browserHmac.js (vendor.js:169480)
	__webpack_require__ (runtime.js:80)
	./node_modules/aws-sdk/lib/browserCryptoLib.js (vendor.js:169356)
	__webpack_require__ (runtime.js:80)
	./node_modules/aws-sdk/lib/browser_loader.js (vendor.js:170179)
	__webpack_require__ (runtime.js:80)
	./node_modules/aws-sdk/browser.js (vendor.js:169250)
	__webpack_require__ (runtime.js:80)
	./src/services/sqs.service.ts (main.js:11753)
	__webpack_require__ (runtime.js:80)
	./src/components/header/header.component.ts (main.js:5806:99)
	__webpack_require__ (runtime.js:80)
	./src/app/app.module.ts (main.js:1957:114)
	__webpack_require__ (runtime.js:80)
	./src/main.ts (main.js:9882:93)
	__webpack_require__ (runtime.js:80)
	(anonymous function) (main.js:12182)
	__webpack_require__ (runtime.js:80)
	checkDeferredModules (runtime.js:46)
	Module Code (main.js:1)
	evaluate
	moduleEvaluation
	(anonymous function)
	promiseReactionJob
``
**Is the issue in the browser/Node.js?**
Browser

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 12.1.1

**SDK version number**
v2.545.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
***Install aws-sdk
*** add the following to a typescript file:
declare var require : any;
var AWS = require('aws-sdk');
*** run `ng serve`

**Expected behavior**
No error

**Comment by ajredniwja** [comment]
Hey @ajit-kumar-azad,

This particular error occurs because the app tries to find the variable global. 

Can you try to adding the following code to your index.html file?
```html
<script type="text/javascript">
window.global = window;
</script>
```

You can read this comment [here](https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814) for more information.

Please reach out if you have any additional questions.

**Comment by ajit-kumar-azad** [comment]
@ajredniwja thanks for the response. I switched to including sdk js in the application and using window.AWS object for API calls. It is working fine for now.
