### ISSUE TITLE
Shortcut in customBackoff based on error

### ISSUE THREAD

**Issue by nullren** [aws/aws-sdk-js#2896]
**Is your feature request related to a problem? Please describe.**
It is frustrating when I add a custom backoff function and must wait for all retry attempts for errors I know will repeat if retried. Specifically, if I receive a `NetworkingError: Invalid character in header content ["x-amz-copy-source"]` error, I know this will be the same error for each request, there's no need for me to wait for all backoff attempts.

**Describe the solution you'd like**
Pass the error through to the [customBackoff function](https://github.com/aws/aws-sdk-js/blob/a203c0e23010e256c88092a0be1e66a7a392eedf/lib/util.js#L857) and [allow some return value to signal shortcutting the retry attempts](https://github.com/aws/aws-sdk-js/blob/a203c0e23010e256c88092a0be1e66a7a392eedf/lib/util.js#L878-L879), eg, returning negative value or throwing an Error. [Example logic change](https://github.com/nullren/aws-sdk-js/commit/a7375492b74f414c4d87bdb727a8dac5d82e2515), happy to open PR with remaining repo changes.

**Describe alternatives you've considered**
Not using built-in retry logic and handling it all ourselves.

**Comment by ajredniwja** [comment]
Hey @nullren,

It can be frustrating at times, we would welcome any PRs to the repo. 
This can be tracked in the PR so closing this issue.
Please re-open and reach out if you any additional questions.
