### ISSUE TITLE
Add support for enterprise SSL interception certificates

### ISSUE THREAD

**Issue by mungojam** [aws/aws-sdk-js#2902]
Our company uses SSL interception with their own certificate which is trusted by windows.

When using aws-cdk, this leads to the inevitable error as node doesn't natively use windows cert store:

> ?  Bootstrapping environment ###/eu-west-1...
?  Environment ###/eu-west-1 failed bootstrapping: Error: self signed
certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1260:34)
    at TLSSocket.emit (events.js:196:13)
    at TLSSocket.EventEmitter.emit (domain.js:471:20)
    at TLSSocket._finishInit (_tls_wrap.js:737:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:569:12) {
  message: 'self signed certificate in certificate chain',
  code: 'NetworkingError',
  region: 'eu-west-1',
  hostname: 'cloudformation.eu-west-1.amazonaws.com',
  retryable: true,
  time: 2019-05-06T16:46:50.195Z
}
self signed certificate in certificate chain

With our own node tools, we have circumvented this by using either [syswide-cas](https://www.npmjs.com/package/syswide-cas) or [win-ca](https://www.npmjs.com/package/win-ca). VS Code recently integrated a win-ca fork as well so that no longer has the problem. This hasn't been possible with cdk as I don't seem able to inject the `win-ca` import early enough I think.

Please consider adding an integrated solution/option so that we can use CDK internally without having to mess with global environment variables.

I've worked around it for now setting the `NODE_EXTRA_CA_CERTS` environment variable to a snapshot of the certs extracted with `win-ca` but that's not a sustainable approach and would be messy to set up for other devs.

**Comment by ajredniwja** [comment]
Hey @mungojam,

It'd be great if you can follow the [issue template](https://github.com/aws/aws-sdk-js/issues/new/choose) so that I can have more information about the issue.

**Comment by mungojam** [comment]
I probably won't get a chance to follow up on this as we've now moved to terraform rather than CDK. Happy to close unless others can follow up with reproductions

**Comment by ajredniwja** [comment]
@mungojam,

Thank-you for the update, I will go ahead and close the issue, if anyone has further questions, please re-open or create a new issue.
