### ISSUE TITLE
Upload to s3 with presigned url- Angular

### ISSUE THREAD

**Issue by raghu2333** [aws/aws-sdk-js#2905]
How to upload image to s3  with presigned url in angular 7.

**Comment by ajredniwja** [comment]
hey @raghu2333,

Thank-you for reaching out, I am not sure what specifically you are looking for, but I would like to suggest that you can simply use JS-SDK api in your component with some JS code using the methods described [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property). Additionally if you need help with configuring, you can refer to this [link](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/#With_Angular) which also describes how to use AWS Amplify Library which may come in handy when working with Angular components and CLI. 
I will go ahead and close this issue for now, please reach out if you have any additional questions.
