### ISSUE TITLE
Use S3 with multiple IAM Accounts simultaneously

### ISSUE THREAD

**Issue by piyushkantm** [aws/aws-sdk-js#2910]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

How can i have multiple instances of SDK since the accessKeyId is static now? 

Detailed Description:
I have a specific use case where my backend application deals with multiple buckets (background: Some buckets are shared with multiple applications). But in order to perform operations on all of those buckets, i am forced to created an IAM user with access to all of the buckets i am interacting with. 

I want to create multiple AWS instances in my node code with different IAM users and perform operations on multiple buckets simultaneously!

What I am doing right now:

```
        AWS.config.update({
            accessKeyId: 'common-key-id',
            secretAccessKey: 'common-key-secret'
        })

        const commonS3Agent = new AWS.S3();

        commonS3Agent.putObject({
            Key: "test",
            Bucket: "First",
            Body: "xyz"
        })

        commonS3Agent.putObject({
            Key: "test",
            Bucket: "Second",
            Body: "xyz"
        })

        commonS3Agent.putObject({
            Key: "test",
            Bucket: "Third",
            Body: "xyz"
        })

```

*What i intend to do*:
```
        const firstS3Agent = new AWS.S3({
            accessKeyId: 'common-key-id',
            secretAccessKey: 'common-key-secret'
        });

        firstS3Agent.putObject({
            Key: "test",
            Bucket: "First",
            Body: "xyz"
        })

        const secondS3Agent = new AWS.S3({
            accessKeyId: 'common-key-id',
            secretAccessKey: 'common-key-secret'
        });

        secondS3Agent.putObject({
            Key: "test",
            Bucket: "Second",
            Body: "xyz"
        })

        const thirdS3Agent = new AWS.S3({
            accessKeyId: 'common-key-id',
            secretAccessKey: 'common-key-secret'
        });

        thirdS3Agent.putObject({
            Key: "test",
            Bucket: "Third",
            Body: "xyz"
        })

```

But since passing the access key and id is deprecated now, can anyone suggest me how can i achieve what i want to do?

**Comment by piyushkantm** [comment]
From the official code examples (https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javascript#running-the-examples => AWS.config.credentials = credentials;
):

```
AWS.config.credentials = credentials;
```

It is mentioned that user can have multiple profiles but at a time node can use only one profile. Is it a limitation?

**Comment by piyushkantm** [comment]
Or AWS SDK is built with keeping in mind that for one running application, there needs to be *one* IAM Account that has authorization to perform all the operations that's been written in code.

**Comment by ajredniwja** [comment]
Hey @piyushkantm,

Thank-you for reaching out, you can try to use AWS.ProcessCredentials which would look like:

```JavaScript

var creds = new AWS.ProcessCredentials({profile: 'profile1'});
var creds2 = new AWS.ProcessCredentials({profile: 'profile2'});

var firstS3agent = new AWS.S3(creds);
var firstS3agent2 = new AWS.S3(creds2);

//use different clients for different processes.

```

You can create profiles in your credentials file found at ```~/.aws/credentials```.

Please reach out if that doesn't solve the issue.

**Comment by piyushkantm** [comment]
Thanks
