### ISSUE TITLE
How to fetch AWS-SDK retry logs

### ISSUE THREAD

**Issue by bhasksr** [aws/aws-sdk-js#2912]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

We are using aws-sdk in javascript and currently running into a situation where there are 3 retries that happens in aws-sdk. There is no easy way for us to currently find out what happened in those first two attempts. aws-sdk currently returns the response of the 3rd attempt which we are able to get log for, but not for first two attempts. 

Is there a way we can enable logging to find out the reason for the failures?

**Comment by bladepop** [comment]
We're also interested in knowing how to do it

**Comment by ajredniwja** [comment]
Hey @bhasksr and @bladepop,

You can achieve this for a service like S3 using the example below :

```JavaScript
const AWS = require('aws-sdk');

AWS.S3.prototype.on('apiCall', console.log);
AWS.S3.prototype.on('apiCallAttempt', console.log);

var s3 = new AWS.S3();

var params = {
    Body: 'body',
    Bucket: 'bucket-name',
    Key: 'key'
};

s3.putObject(params, function(err, data) {
   if (err) console.log(err, err.stack); 
   else     console.log(data); 
 });
```

Closing the issue now, please reopen if you have any other questions.
