### ISSUE TITLE
Rook ceph listing Objects in a bucket

### ISSUE THREAD

**Issue by xueyongg** [aws/aws-sdk-js#2913]
Confirm by changing [ ] to [x] below:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Ive managed to PUT and GET objects into a rook-ceph bucket (thus its a private access bucket).

however i understand that s3 have a listObjectsV2 function to list the objects in a specific bucket. But that did not seem to return anything that we wanted. Wish to check if there's such an issue before and if so what is the resolution?

It returns me empty array for Contents and CommonPrefixes

**Comment by ajredniwja** [comment]
Hey @xueyongg,

Thank-you for reaching out, I am not familiar with ceph, but can you share the code that you are using for the call?
