### ISSUE TITLE
headObject does not honor milliseconds for 'IfModifiedSince'

### ISSUE THREAD

**Issue by sidiliu** [aws/aws-sdk-js#2915]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
when calling S3 headObject with 'IfModifiedSince' option,
if set time = new Date(), which is the current time, it works as expected
if set time = new Date().getTime(), which is the current time in milliseconds, it seems the call does not honor it.

my object last modified time in S3 bucket: 1571696292000  "2019-10-21T22:18:12.000Z"
new Date().getTime() = 1571781366480   it returns the object metadata, which should not be
new Date() = "2019-10-22T21:59:08.125Z"  it return error 'NotModified', which is as expected

AWS version: "aws-sdk": "^2.514.0"

**Comment by ajredniwja** [comment]
Hey @sidiliu,

Thank-you for reaching out to us with your issue. Can you please share how you are using the method/function for your application since you can pass ```new date``` format date for the ```IfModifiedSince``` param which will be of the format ```2019-11-12T22:56:56.657Z``` accounting milliseconds as well.
