### ISSUE TITLE
getSignedUrl returns "https://s3.<region>.amazonaws.com/" before a request is performed

### ISSUE THREAD

**Issue by nicgirault** [aws/aws-sdk-js#2918]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

getSignedUrl returns `https://s3.<region>.amazonaws.com/` when:

- no request to s3 has been done before
- policy is attached to the EC2 where the node code runs (no .aws/credentials)

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v10.16.3

**SDK version number**
v2.554.0

**To Reproduce (observed behavior)**

1. start an EC2 and attach a policy with full rights on s3
2. run this code on the instance:

```javascript
const s3 = new S3({
    region: 'eu-west-3',
    useAccelerateEndpoint: true,
  })

console.log(s3.getSignedUrl('putObject', {
    Bucket: 'some-bucket',
    Key:'some-file',
    Expires: 60 * 10,
    ContentType: contentType,
    ACL: 'public-read',
  }))
// output: "https://s3.eu-west-3.amazonaws.com/"

  // dummy call to initialize signature
  await s3
    .getObject({
      Bucket: 'some-bucket',
      Key: 'some-key',
    })
    .promise()

console.log(s3.getSignedUrl('putObject', {
    Bucket: 'some-bucket',
    Key:'some-file',
    Expires: 60 * 10,
    ContentType: contentType,
    ACL: 'public-read',
  }))
// output: signed url
```

**Expected behavior**
I would like to remove the dummy call and that it still works

**Comment by winsome** [comment]
The docs state 
>Note: You must ensure that you have static or previously resolved credentials if you call this method synchronously (with no callback), otherwise it may not properly sign the request. If you cannot guarantee this (you are using an asynchronous credential provider, i.e., EC2 IAM roles), you should always call this method with an asynchronous callback.

I think your issue here is that you're calling getSignedUrl synchronously rather than with a callback. Either add a callback like:

```
s3.getSignedUrl('putObject', {
    Bucket: 'some-bucket',
    Key:'some-file',
    Expires: 60 * 10,
    ContentType: contentType,
    ACL: 'public-read',
  }, url => {
    console.log(url)
  }))
```

or use the Promise version

```
let signedUrl = await s3.getSignedUrlPromise({
    Bucket: 'some-bucket',
    Key:'some-file',
    Expires: 60 * 10,
    ContentType: contentType,
    ACL: 'public-read',
});

console.log(signedUrl);
```

**Comment by nicgirault** [comment]
Thanks and sorry for this noisy issue. I indeed mis-read the documentation.

However throwing an error instead of returning an inaccurate URL would seems to me as a better developer experience.
