### ISSUE TITLE
Intermittent "cloudWatchEvent.putEvents" is not a function

### ISSUE THREAD

**Issue by Bexanderthebex** [aws/aws-sdk-js#2921]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
We sometimes get "cloudWatchEvents.putEvents() is not a function" error in our servers and is mainly solved by only restarting the server 

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
nope

**Details of the browser/Node.js version**
v10.16.0

**SDK version number**
2.307.0

**To Reproduce (observed behavior)**
We do not know how to reproduce it. 

**Expected behavior**
We should not experience the kind of error as the function is really listed in the documentation and it works most of the time

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @Bexanderthebex,

Thank-you for reaching out, can you provide the logs using

 ```JavaScript 
var cloudwatchevents = new AWS.CloudWatchEvents({logger: console});
```
