### ISSUE TITLE
CloudFront invalidation doesn`t work for javaScript API

### ISSUE THREAD

**Issue by AdletAzhibek** [aws/aws-sdk-js#2926]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  

**Describe the bug**
after deleting file from bucket I'm trying to invalidate Cloudfront cache, then error acurs:

{ TypeError: Cannot set property 'Timestamp' of undefined
    at addAuthorization (/opt/nodejs/backend/node_modules/aws-sdk/lib/signers/v2.js:14:24)
    at /opt/nodejs/backend/node_modules/aws-sdk/lib/event_listeners.js:236:18
    at finish (/opt/nodejs/backend/node_modules/aws-sdk/lib/config.js:349:7)
    at /opt/nodejs/backend/node_modules/aws-sdk/lib/config.js:367:9
    at Credentials.get (/opt/nodejs/backend/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/opt/nodejs/backend/node_modules/aws-sdk/lib/config.js:361:24)
    at Config.getCredentials (/opt/nodejs/backend/node_modules/aws-sdk/lib/config.js:381:9)
    at Request.SIGN (/opt/nodejs/backend/node_modules/aws-sdk/lib/event_listeners.js:212:22)
    at Request.callListeners (/opt/nodejs/backend/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at callNextListener (/opt/nodejs/backend/node_modules/aws-sdk/lib/sequential_executor.js:96:12) retryDelay: 67.35441836652538 } 

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Node.js version**
v6.17.1

**SDK version number**
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
├┬ aws-cloudfront-invalidate@0.1.3
│    └── aws-sdk@2.6.9
└── aws-sdk@2.534.0
  * printing the output of `AWS.VERSION` in your code where `AWS = require("aws-sdk");`
AWS.VERSION:  2.534.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

1. you should have already uploaded file or just upload new one to aws bucket
2. delete this file from bucket by file name and required keys for authentication to aws (AccessKey, SecretKey)
3. after deleting try to invalidate cloudfront cache (just deleting from bucket is not enough, because file would be still available from cache)
4. at this point error occurs

**Expected behavior**
After invalidation of cloudfront cache deleted file should not be available

**Screenshots**
my code snippet:
![1](https://user-images.githubusercontent.com/55197950/67651132-d875ec80-f969-11e9-9236-851c810884e1.png)

/aws-sdk/lib/signers/v2.js:14:24 is following:
![2](https://user-images.githubusercontent.com/55197950/67651137-e461ae80-f969-11e9-8e34-b66a148ae182.png)

**Comment by ajredniwja** [comment]
Hi @AdletAzhibek,

Thank-you for reopening the issue using the issue template, I was able to successfully call the method. I didnt include the ```signatureVersion: 'v2';``` for the params. Is it possible for you to not use sig v2 and use sig v4 instead?
