### ISSUE TITLE
codebuild.listBuilds() - Unexpected key 'nextToken' found in params

### ISSUE THREAD

**Issue by ShantanuNair** [aws/aws-sdk-js#2927]
[x] I've gone though Developer Guide and API reference
[x] I've checked AWS Forums and StackOverflow for answers
[x] I've searched for previous similar issues and didn't find any solution

Describe the bug
listBuilds() method in the AWS.codebuild service is broken. Under-the-hood a parameter nextToken is passed but this fails a paramValidator check.

Is the issue in the browser/Node.js?
Node.js

If on Node.js, are you running this on AWS Lambda?
No

Details of the browser/Node.js version
v10.16.3

SDK version number
v2.558.0

To Reproduce (observed behavior)

```
import * as AWS from 'aws-sdk'
let builds = await codebuild.listBuilds({}).promise()
```

Throws:
```
UnexpectedParameter: Unexpected key 'nextToken' found in params
    at ParamValidator.fail (~/Dev/EXM/cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (~/Dev/EXM/cli/node_modules/aws-sdk/lib/param_validator.js:77:14)
    at ParamValidator.validateMember (~/Dev/EXM/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (~/Dev/EXM/cli/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (~/Dev/EXM/cli/node_modules/aws-sdk/lib/event_listeners.js:126:42)
    at Request.callListeners (~/Dev/EXM/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (~/Dev/EXM/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at ~/Dev/EXM/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (~/Dev/EXM/cli/node_modules/aws-sdk/lib/config.js:357:7)
    at ~/Dev/EXM/cli/node_modules/aws-sdk/lib/config.js:375:9
```

**Comment by ajredniwja** [comment]
Hey @ShantanuNair,

Thank-you for reaching out, can you provide the ```async``` function that you are using this with?
I was not able to reproduce it, do you still see the error if you just try to do  ```codebuild.listBuilds()``` without await and promise?

**Comment by ShantanuNair** [comment]
Hey, thanks for taking the time out! How do you call listBuilds() without a .promise()? If I remove the await and .promise(), then codebuild.listBuilds() returns an AWS.request object.

I'm calling listBuilds in the async function run() which I'm using for building a custom AWS CLI for our platform. Here is a part of the async run():

```
async run(){
...
  if (project == 'all') {
        const spinner = ora({ text: 'Fetching builds\n', stream: process.stderr }).start()
        let builds = await codebuild.listBuilds().promise()
        let table = await this.getTableFromBuildIDs(builds, defaultQuery, defaultColHeaders)
        spinner.stop()
        this.log(table.toString())
      }
}
```

**Comment by ShantanuNair** [comment]
The odd thing is that this was working fine 2 weeks back. It failed recently and so I assumed something changed/broke on AWS's end.

**Comment by ajredniwja** [comment]
@ShantanuNair, 

I was not able to reproduce this locally, can you update your SDK to the latest version and see if that works as a fix?

**Comment by ShantanuNair** [comment]
I'm on 2.561, the latest release of aws-sdk for Node.js. I'll try and set up an environment where the bug is reproducible.

**Comment by ajredniwja** [comment]
Hey @ShantanuNair,

Is this still a persisting issue? 

Do you still see the error?
