### ISSUE TITLE
Adding user to cognito from lambda function 

### ISSUE THREAD

**Issue by dahersoftware** [aws/aws-sdk-js#2928]
**Describe the bug**
I am trying to use Amplify Javascript SDK to add a user into cognito. When I do the same operation from my local machine by running function it works perfectly.
On the other hand when I use the same code inside node lambda function it doesn't show any error neither it adds the user.

Regarding Lambda permission to cognito:
1. "Amplify add function" command gives CRUD permissions to access cognito to lambda function.
2. Document says that:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#constructor-property 
It is a admin operation and we need developer credential. I passed my accessKeyId and secretAccessKey inside the constructor object but it doesn't do the job.

May be I am missing something or there is another way to do this.

```JavaScript
function addUserToCognito(event) {
  let email = 'vdfgtr@gamil.com';
  var cognitoIdentityServiceProvider = new aws.CognitoIdentityServiceProvider({                                                         
    region: region1,
    accessKeyId: <my developer acces key>,
    secretAccessKey: <my developer access key>,                                                                        
  });                                                                                                                                   
  
  var params = {
    UserPoolId: 'eu-west-1_uyhhjafgwluie',                                                                                                  
    Username: email,
    DesiredDeliveryMediums: ['EMAIL'],                                                                                                  
    ForceAliasCreation: false,
    TemporaryPassword: tempPass,                                                                                              
    UserAttributes: [ 
      { Name: 'name', Value: 'dysxcf' + ' ' + 'ghyujp' },                                                                                 
      { Name: 'email', Value: email },                                                                                                  
    ],                                                                                                                                  
  };
  console.log('Sending params to cognito: ' + JSON.stringify(params));
  cognitoIdentityServiceProvider.adminCreateUser(params, function(error, data) {                                                        
    if (error) {
      console.log('Error adding user to cognito: ' + error, error.stack);                                                               
    } else {
      console.log('Data:', data);                                                                                                       
    }                                                                                                                                   
  });                                                                                                                                   
} 
```

**Comment by ajredniwja** [comment]
Hey @dahersoftware,

Thank-you for reaching out, the code looks good, is it possible for you to provide with clear reproducing steps?

**Comment by dahersoftware** [comment]
@ajredniwja 
Steps:
amplify add function 
Use this function with one of my data field in graphql schema
**userData: UserData @function(name: "appSyncAddUserToCognito-${env}")**
In my app user logged in and call Graphql mutation which invokes the lambda function. This lambda function contains the code previously shown here. As part of this function I was expecting to see a
user addition inside Cognito but function runs without any error and nothing happens in Cognito.

Below code doesn't log any error or success message and it is confusing to me as exact reason is unknown.
cognitoIdentityServiceProvider.adminCreateUser(params, function(error, data) {                                                        
    if (error) {
      console.log('Error adding user to cognito: ' + error, error.stack);                                                               
    } else {
      console.log('Data:', data);                                                                                                       
    }                                                                                                                                   
  });

**Comment by dahersoftware** [comment]
@ajredniwja  Any update on this.. 
I investigated it more and I am using the same credential and my http request is same from my local machine and on cloud using lambda still only local machine request gets successful but lambda request doesn't. 
**Headers from local machine:**
`headers:
   { 'User-Agent': 'aws-sdk-nodejs/2.518.0 darwin/v11.15.0 callback',
     'Content-Type': 'application/x-amz-json-1.1',
     'X-Amz-Target': 'AWSCognitoIdentityProviderService.AdminCreateUser',
     'X-Amz-Content-Sha256':
      '13e199ce1030a6aee50bba372528cbf5ff2897f5988856210ca84d840cb4fca3',
     'Content-Length': 245,
     Host: 'cognito-idp.eu-west-1.amazonaws.com',
     'X-Amz-Date': '20191031T142042Z',
     Authorization:
      'AWS4-HMAC-SHA256 Credential=<Developer id>/20191031/eu-west-1/cognito-idp/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=ccee85c55b8239c8971ad9b0e122d449112ead6d17bb7ef62312dd651e5ef4aa' },
`
**Headers from lambda function:**
`headers:
{ 'User-Agent':
'aws-sdk-nodejs/2.488.0 linux/v10.16.3 exec-env/AWS_Lambda_nodejs10.x callback',
'Content-Type': 'application/x-amz-json-1.1',
'X-Amz-Target': 'AWSCognitoIdentityProviderService.AdminCreateUser',
'X-Amz-Content-Sha256':
'13e199ce1030a6aee50bba372528cbf5ff2897f5988856210ca84d840cb4fca3',
'Content-Length': 245,
Host: 'cognito-idp.eu-west-1.amazonaws.com',
'X-Amz-Date': '20191031T143654Z',
Authorization:
'AWS4-HMAC-SHA256 Credential=<same as above request>/20191031/eu-west-1/cognito-idp/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=28256c1cc185924e0adfdac8a107367ce686fcbd11fd01a5c40daf7e175dceeb' },`
