### ISSUE TITLE
Node SDK should prefer AWS_DEFAULT_REGION over AWS_REGION environment variables

### ISSUE THREAD

**Issue by amancevice** [aws/aws-sdk-js#2929]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

The AWS docs on [Environment Variables](https://docs.aws.amazon.com/en_pv/cli/latest/userguide/cli-configure-envvars.html) for the Amazon CLI state that the environment variable `AWS_DEFAULT_REGION` should be used to specify the default region for clients when not explicitly passed into the constructor.

However, it looks like the NodeJS SDK prefers the older-style `AWS_REGION` variable and requests will error of only the `AWS_DEFAULT_REGION` is set.

**Is the issue in the browser/Node.js?**

Node.js

**If on Node.js, are you running this on AWS Lambda?**

No, on Lambda this value would be preconfigured by the Lambda runtime environment.

**Details of the browser/Node.js version**

`v12.12.0`

**SDK version number**

`aws-sdk@2.554.0`

**To Reproduce (observed behavior)**

```bash
unset AWS_REGION
export AWS_ACCESS_KEY_ID=<redacted>
export AWS_SECRET_ACCESS_KEY=<redacted>
export AWS_DEFAULT_REGION=us-west-2
node -e "
  const {SNS} = require('aws-sdk'); 
  const sns = new SNS(); 
  sns.listTopics().promise().catch(console.error);
"
{ ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:92:45)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:349:7)
    at /var/runtime/node_modules/aws-sdk/lib/config.js:367:9
    at EnvironmentCredentials.get (/var/runtime/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/var/runtime/node_modules/aws-sdk/lib/config.js:361:24)
    at Config.getCredentials (/var/runtime/node_modules/aws-sdk/lib/config.js:381:9)
    at Request.VALIDATE_CREDENTIALS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:81:26)
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2019-10-30T14:22:03.220Z }
```

**Expected behavior**

the SDK should pull the region from the environment variable `AWS_DEFAULT_REGION`

**Screenshots**

N/A

**Additional context**

N/A

**Comment by ajredniwja** [comment]
Hey @amancevice,

Thank-you for reaching out and opening a PR for the issue, this is not necessarily a bug but a feature request because of recent updates to the variable names. I will go ahead and reach out the team to review the PR.

**Comment by amancevice** [comment]
Thanks, @ajredniwja — I wasn't sure how to file it, but I can see how it's not a bug. Thanks!

**Comment by trivikr** [comment]
Similar request is aws-sdk-go was rejected https://github.com/aws/aws-sdk-go/issues/2103
Although it's documented in https://github.com/aws/aws-sdk-go/search?q=AWS_DEFAULT_REGION&unscoped_q=AWS_DEFAULT_REGION
