### ISSUE TITLE
Calling Glue API to updateTable from Lambda Node.js 10 AWS SDK

### ISSUE THREAD

**Issue by RohitKumarKhatri** [aws/aws-sdk-js#2934]
Hi
I am using AWS lambda inline with Node.js 10.x runtime as shown in screenshot.

![image](https://user-images.githubusercontent.com/34018015/68128245-5ecb9900-ff3d-11e9-9c88-dd87c5edae3e.png)

According to https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Glue.html#updateTable-property

it supports: Parameters in Columns.

![image](https://user-images.githubusercontent.com/34018015/68128435-bbc74f00-ff3d-11e9-8983-d4ebfab3d337.png)

but while saving JSON using SDK, it shows unexpected key.

![image](https://user-images.githubusercontent.com/34018015/68128575-f7621900-ff3d-11e9-8857-1cb36cbca369.png)

AWS APIs are updating constantly, you might be calling a new API with an older version is SDK. In
    this case you should try installing the newest `aws-sdk` like: 

    `npm install aws-sdk@latest`

    If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled
    SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
    You can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

If you still like to open an issue, change [ ] to [x] below:
- [x] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

**Comment by ajredniwja** [comment]
Hey @RohitKumarKhatri,

Thank-you for reaching out, can you please share how are you calling the ```updateTable``` where you set the ```params``` and pass it to the function?

**Comment by RohitKumarKhatri** [comment]
Hi @ajredniwja 

Please check below screenshot code, I have already shared JSON data above which is being used as tableParam below:
![image](https://user-images.githubusercontent.com/34018015/68263817-f8de2f00-006c-11ea-8e60-a207999741c5.png)

**Comment by RohitKumarKhatri** [comment]
Hi @ajredniwja ..
could you please check this once...

**Comment by RohitKumarKhatri** [comment]
@ajredniwja 
any high level update, is it bug or just my bad... ?

**Comment by RohitKumarKhatri** [comment]
Hi @ajredniwja 
could you please check this once....

**Comment by RohitKumarKhatri** [comment]
Hi @ajredniwja 
could you please check this once...

**Comment by RohitKumarKhatri** [comment]
hi @ajredniwja 
could you please check this once...?

**Comment by ajredniwja** [comment]
Hey @RohitKumarKhatri,

Apologies for late reply, the SDK team tries to ship the latest SDK to the Lambda team, sometimes it takes time for them to update however you can use the latest SDK for you Lambda functions using these [instructions](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).
