### ISSUE TITLE
Not working with Angular8x and Nodev10.x application

### ISSUE THREAD

**Issue by ashokkumarjuly** [aws/aws-sdk-js#2936]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I have been implemented aws-sdk to angular 8x application and it throws compilation errors while compiling with the command` "ng serve" or "ng build --prod",` please help

In typescript file i have imported like below, 
`import {config, CognitoIdentityCredentials} from 'aws-sdk/global';`

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No,

**Details of the browser/Node.js version**
 
![e1](https://user-images.githubusercontent.com/4641914/68219337-d5cf6300-000b-11ea-9bd9-db61f8a1c9c1.png)

**SDK version number**
aws-sdk@2.563.0

**To Reproduce (observed behavior)**
New angular application generated via angular cli and added aws-sdk package.

**Expected behavior**
Have to compile without errors

**Screenshots**
After running "D:\NodeApp\lambda-angular>ng serve" , below are the errors,
![e2](https://user-images.githubusercontent.com/4641914/68219701-6e65e300-000c-11ea-8293-4bdd25823fb6.png)

**Additional informations**
*package.json*
![e3](https://user-images.githubusercontent.com/4641914/68220148-3b701f00-000d-11ea-8ad3-c82f4d866c1c.png)

*tsconfig.json*
![e4](https://user-images.githubusercontent.com/4641914/68220156-3f9c3c80-000d-11ea-8f48-2c0da4866785.png)

**Comment by ajredniwja** [comment]
Hey @ashokkumarjuly,

Thank-you for reaching out, you can follow the instructions found [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/#With_Angular), please reach out if its still an issue.

**Comment by ashokkumarjuly** [comment]
Thanks resolved by adding "types": ["node"] to the project's tsconfig.app.json file, now its working.
