### ISSUE TITLE
Return CloudWatchLog using EventId

### ISSUE THREAD

**Issue by blazestudios23** [aws/aws-sdk-js#2938]
**Is your feature request related to a problem? Please describe.**

I want to retrieve one log event by eventId, there seems to be no way to do so. 

I've created:

```
filterPattern: { ( $.log_level = "ERROR" || $.log_level = "WARNING" || $.log_level = "INFO" ) && ($.eventId = "${eventId}" )} 
```

Which always returns { events: [] }
I know I'm sending the correct eventId and can return all events if I remove the "&& ($.eventId = ${eventId} ) " part. 

**Describe the solution you'd like**

Honestly it would make the most sense to just allow the following search:

```
cloudWatchLogs.filterLogEvents(
      {
        logGroupName,
        logStreamNames,
        eventId
      }) 
```

I would think that many people creating a dashboard to view logs would want to be able to easily pull log data with just an eventId and logGroupName. 

**Describe alternatives you've considered**

The filterPattern parameter could be set up to take this data as is show in the documentation, but doesn't seem to currently work. 

**Additional context**

I'm making a dashboard where people can filter by event types and then click on an event. I'm using GraphQL to connect other data to these events. Which allows users to see what triggered the log event. But being able to pull in individual log items is an important part of this app.

**Comment by ajredniwja** [comment]
@blazestudios23 thank-you for reaching out to us with your request, I have marked it as a feature request and will let the team review it on when they can work on it, you are always welcomed to open a PR if you can work on it.
