### ISSUE TITLE
Wrong TS typing for `NumberAttributeValue`

### ISSUE THREAD

**Issue by aprat84** [aws/aws-sdk-js#2939]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Typescript typings for `NumberAttributeValue` are wrong in many files, IMHO.
It's described as `string` where it should be `number`.
Example file:
https://github.com/aws/aws-sdk-js/blob/a0010e6fde102c86496ecd9683f50554f3493c3f/clients/dynamodb.d.ts#L1555

**SDK version number**
2.1046.0

**To Reproduce (observed behavior)**
Write some `updateItem` dynamoDB code in TS, and see TS linter complain:
```
TS2769: No overload matches this call.
``` 
```ts
        await dynamodb.updateItem({
            TableName: 'MyTable',
            Key: {...},
            UpdateExpression: "SET ...",
            ExpressionAttributeNames: {...},
            ExpressionAttributeValues: {
                ':n': {
                    N: 123,
                }
            }
        }).promise();
```

**Expected behavior**
Should be typed as a native JS number.

**Comment by ajredniwja** [comment]
Hey @aprat84, thank-you for reaching out to us with your issue. 

It would be really great if you can open a PR for this, the JS-SDK team would welcome a PR to review.

**Comment by aprat84** [comment]
Tried. `npm run test` crashes because some `S3` error. I don't have time to solve this.

Moreover, there's more than one file where this typing is wrong. And I can change every `*.d.ts`, but I don't know what should I put in the JSON files.

This search gives all files where appears `NumberAttributevalue`:
https://github.com/aws/aws-sdk-js/search?q=NumberAttributeValue&unscoped_q=NumberAttributeValue

**Comment by aprat84** [comment]
Well, IMHO Amazon is a large enough company with enough profits to be able to solve this incident without the help of third parties. Specially when this can be solved in less than half an hour.

I'm not using it anymore, and as I said, don't have time for this.

@ajredniwja

**Comment by aprat84** [comment]
Is no one ever going to fix this issue?

**Comment by 0xtawa** [comment]
Any update on this?

**Comment by aprat84** [comment]
Looks like WE have to make a PR for one of the world's richest company's library ...

**Comment by zshzbh** [comment]
Hey @aprat84,

I'm soooo sorry for this long wait. I apologize for any challenges or struggles you may have faced during this process and I totally understand it!  I just checked the source code in sdk to find that 
there's a specific reason that we are using string - 

[NumberAttributeValue](https://github.com/aws/aws-sdk-js/blob/a0010e6fde102c86496ecd9683f50554f3493c3f/clients/dynamodb.d.ts#L351) is an attribute of type Number. For example:  "N": "123.45"  Numbers are sent across the network to DynamoDB as strings, to **maximize compatibility across languages and libraries**, as we have other sdk that might not support number.  However, DynamoDB treats them as number type attributes for mathematical operations.

And it's not only on JS SDK, the Amazon dynamoDB uses string as you can see `"N": "456"`[here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html#Expressions.ConditionExpressions.ConditionalExamples)

As we are approaching the maintenance mode for AWS JS v2, AWS will limit SDK releases to address critical bug fixes and security issues only.  We recommend that you migrate to [AWS SDK for JavaScript v3](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html).

I hope you understand it. And at the same time, I will bring this up to the team and dynamo team to see if there's a better way to approach it in V3 to avoid the confusion. 


Thanks! 
Maggie

**Comment by zshzbh** [comment]
Hey @aprat84,

I just got back from the dynamoDB team -

It seems that we are using low level DynamoDB here. DynamoDB JSON and thus all low level clients use String. If you want to use Numbers, use a higher level client which allows you to talk to DynamoDB in native JSON. 

 Ref : https://aws.amazon.com/blogs/database/exploring-amazon-dynamodb-sdk-clients/

High-level & Low-level clients options: 

Programming language | High-level clients | Low-level clients
-- | -- | --
JavaScript/Node V2 | [DocumentClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html) | [DynamoDBClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html)
JavaScript/Node V3 | [DocumentClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_lib_dynamodb.DynamoDBDocumentClient.html)	 | [DynamoDBClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_lib_dynamodb.html)


Please let us know if you have any other questions! 

Thanks! 
Maggie
