### ISSUE TITLE
listObjects, sorted by lastModified param is needed.

### ISSUE THREAD

**Issue by roman-122** [aws/aws-sdk-js#2944]
I am always frustrated with getting some recently created or modified Objects.
Let's assume that I need 5 recently uploaded objects.
For now, I need to fetch all data and sort by lastModified. At that time, most of objects are useless.
As you know, there's `MaxKeys` param to get limited Objects by name.
But when I need to get some recently created objects, `MaxKeys` is helpless at all.

I think it could be better if there's a new param to determine sort by name or other options.
Thanks!

**Comment by ajredniwja** [comment]
@roman-122 Apologies for late reply you can use something like mentioned in https://github.com/aws/aws-sdk-js/issues/3521 

Which you can use if you know the date to look after, let me know if that solves the problem.

**Comment by osvaldokalvaitir** [comment]
It would be very important if had something like filtering the latest records.

In some cases have to make a lot of requests, which ends up hindering the performance with many records.
