### ISSUE TITLE
S3 preassigned url signature mismatch using contentDisposition flag

### ISSUE THREAD

**Issue by torretoo** [aws/aws-sdk-js#2946]
Hello AWS SDK Developer,

I am using pre-signed url to directly upload from browser to s3 but I am getting signature mismatch at the time of upload If I remove ContentDisposition prams this is uploaded without any error.

```
` public async generateUploadAssetUrl() {           
        const params = {
            Bucket: bucket-name
            Key: key,
            Expires: 30 * 60, // 30 minutes,
            ContentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
            ContentDisposition: 'attachment;filename=fileName.xlsx' 
          };    
          const signedURL = await (new Promise((resolve, reject) => {
            self.s3.getSignedUrl('putObject', params, (err, data) => { if (err) {
                reject(err)
              } else {
                resolve(data)
              }
              });
          }));
          return signedURL;
    }`
```

 I have tested it by using below combination 

- With Headers
-  Without headers and
- Only using pre-signed url and query parameters. 

If I am including content disposition in presigned url it causes signature mismatch ideally this should work.  Let me know if you need more details

**Comment by ajredniwja** [comment]
Hey @torretoo,

Thank-you for reaching out, can you please refer to #1703 and refer to @AllanFly120 comment in which he tells how you can set content-disposition in the request header.

**Comment by torretoo** [comment]
> Hey @torretoo,
> 
> Thank-you for reaching out, can you please refer to #1703 and refer to @AllanFly120 comment in which he tells how you can set content-disposition in the request header.

Hello @ajredniwja 
Thanks for your quick response.
Yes I have tried this before posting, same result "Signature Mismatch" my aws sdk version is  **"aws-sdk": "^2.224.1",**  may be this is a reason  also suggestion suggested by @AllanFly120 looks like a hack

**Comment by ajredniwja** [comment]
Closing this issue now, please reach out if you have additional questions.
