### ISSUE TITLE
bigint rounding issue in postgresql

### ISSUE THREAD

**Issue by kpbird** [aws/aws-sdk-js#2947]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I am using postgresql serverless with bigint as primary key (id), when I try to insert or select bigint value node js sdk does rounding

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
v10.15.0

**SDK version number**
aws-sdk@2.568.0 

**To Reproduce (observed behaviour)**
1. create a table with bigint datatype in PostgreSQL
2. insert data from PostgreSQL (psql)
3. use data API to retrieve data (select * from <table>)

** Wrong Response **
```
{
    "numberOfRecordsUpdated": 0,
    "records": [
        [
            {
                "longValue": **2116623750278415400**
            },
            {
                "stringValue": "KP"
            },
            {
                "stringValue": "KP"
            },
            {
                "stringValue": "2019-08-23 06:20:35.236881"
            },
            {
                "stringValue": "2019-08-23 06:20:35.236881"
            },
            {
                "longValue": -1
            },
            {
                "longValue": -1
            },
            {
                "booleanValue": false
            },
            {
                "longValue": 1
            },
            {
                "booleanValue": true
            }
        ]
    ]
}
```

**Expected behavior**

```
{
    "numberOfRecordsUpdated": 0,
    "records": [
        [
            {
                "longValue": **2116623750278415361**
            },
            {
                "stringValue": "KP"
            },
            {
                "stringValue": "KP"
            },
            {
                "stringValue": "2019-08-23 06:20:35.236881"
            },
            {
                "stringValue": "2019-08-23 06:20:35.236881"
            },
            {
                "longValue": -1
            },
            {
                "longValue": -1
            },
            {
                "booleanValue": false
            },
            {
                "longValue": 1
            },
            {
                "booleanValue": true
            }
        ]
    ]
}
```

**Additional context**
full source code

```
const AWS = require('aws-sdk')
const RDS = new AWS.RDSDataService({ "region": "eu-west-1" })
var DBSecretsStoreArn = "<ARN>"

var DBAuroraClusterArn = "<ARN>";
var DatabaseName = "<DB NAME>";
var select = "select * from <TABLE NAME>"

var sqlStatement = select
async function test() {
    const params = {
        secretArn: DBSecretsStoreArn,
        resourceArn: DBAuroraClusterArn,
        sql: sqlStatement,
        database: DatabaseName,
        includeResultMetadata: true
    }
    try {

        data = await RDS.executeStatement(params).promise()
        console.log(data.records[0])
    }
    catch (err) {
        console.log(err)
    }

}
test()
```

**Comment by ajredniwja** [comment]
Hey @kpbird,

Thank-you for reaching out, unfortunately the SDK doesn't support the feature, it is not necessarily a bug but a feature request. 
You are always welcome to open a PR for the feature request for our team to review.

**Comment by kpbird** [comment]
Hello

The issue is not fixed yet

**Comment by kpbird** [comment]
@ajredniwja 

I found the root cause of the problem. It's because of parseInt function used in Shape.js ParseInt function truncate bigint  

https://github.com/aws/aws-sdk-js/blob/master/lib/model/shape.js

`
function IntegerShape() {
  Shape.apply(this, arguments);

  this.toType = function(value) {
    if (value === null || value === undefined) return null;
    return parseInt(value, 10);
  };
  this.toWireFormat = this.toType;
}
`

**Comment by ajredniwja** [comment]
Hey @kpbird glad that you found it, I also found https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt which has a little more information, you are welcome to open a PR or the team can take it up according to the priority of this feature.
