### ISSUE TITLE
RDSDataService Parameterising Date or JSON fields

### ISSUE THREAD

**Issue by chrisbarbour** [aws/aws-sdk-js#2949]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Could you provide an example of how to execute sql that sets fields that are not one of string, int, blob, long, double, boolean, array or null? for example a date / timestamp or a JSON field.

**Comment by ajredniwja** [comment]
Hey @chrisbarbour,

Thank-you for reaching out to us with your issue.

Data types such as date / time are accounted as String as well as mentioned [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html#w814aac13c33c29c19c19). The [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#executeSql-property) shows how you can make a call using ```executeStatement```.

Closing this issue for now, please reach out if you have any additional questions.
