### ISSUE TITLE
How can I mock using a API Gateway Event for a Lambda and invoke it

### ISSUE THREAD

**Issue by grbknr1996** [aws/aws-sdk-js#2951]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
This is create function and it has post event associated with it how can i mock test it
```
const jobs=[
    { id: 1,title: 'NodeJS Developer'},
    {id: 2, title:'Angular Developer'}
];


var AWS = require('aws-sdk');
AWS.config.region = 'ap-south-1';

  
let lambda = new AWS.Lambda({
    region: 'ap-south-1',
    //endpoint: 'http://localhost:3000'
})
module.exports.handler=async(evt,ctx)=>{
    
    console.log(evt.body);
    jobs.push(JSON.parse(evt.body));
    var lambda_args={};
    lambda.invoke({
        FunctionName: 'sls-demo-dev-listJobs',
        InvocationType: 'Event',
        Payload:JSON.stringify(lambda_args)    
    },function(err,data){
        console.log('No error');
        if(!err)
        console.log(data);
        else
        console.log(err);
    
    })
    
    //console.log(response);
    return {
        statusCode :200,
        body:JSON.stringify({
            jobs
        })
    }
}

```

**Comment by grbknr1996** [comment]
"use strict";
const init= require ('./utils/init');
const steps=require('./utils/steps');
const axios=require('axios');
const AWSMock=require('aws-sdk-mock');
const AWS=require('aws-sdk');
//MOCK FILE
const jobs=[
    { id: 1,title: 'NodeJS Developer'},
    {id: 2, title:'Angular Developer'}
];
describe('when we invoke the API',()=>{
    beforeAll(()=>{
        init();
    });
    test('With a name', async () => {
        const response = await axios.get(process.env.BASE_URL + '/jobs');
        
         expect(response.status).toBe(200);
        console.log(response.data);
        console.log(response.data.jobs);
        expect(response.data.jobs).toEqual(jobs);
    });
    test('Create Job Test cases',()=>{
        
        const lambda = new AWS.Lambda();
        AWSMock.mock('sls-demo-dev-createJobs', 'event', (params, callback) => {
          const awsResponse = {
            LogResult:'some-data',
            Payload:'{"id":"3","title":"vue js"}',
            StatusCode:200
          };
          callback(null,awsResponse);
          console.log(awsResponse);
        expect(awsResponse).toEqual(jobs);
    })
})
})

**Comment by ajredniwja** [comment]
@grbknr1996 than-you for reaching out to us, is this still something you need help with, seems like you have found a solution.

**Comment by grbknr1996** [comment]
No, @ajredniwja  I am still unable to mock the lambda.invoke function .I am able to go to the function by passing a dummy event and ctx as null .But could nt mock the lambda.invoke function in it.Actually I want to do a integration test where I test lambda A and inside lambda A lambda gets invoked (all i want is to mock the lambda B's invokement)

**Comment by ajredniwja** [comment]
Hey @grbknr1996 apologies for the late reply, I lost track of the issue. 

let me test on my local environment and get back to you.

**Comment by trivikr** [comment]
Example unit test for lambda can be viewed here: https://github.com/trivikr/cdk-typescript-workshop/blob/95570683713b504c40c95d0603d53eee14aa5095/src/lambda/hello.spec.ts#L5-L25
It uses community support [aws-event-mocks](https://www.npmjs.com/package/aws-event-mocks) package
