### ISSUE TITLE
Cloudfront Signer not works with UTF-8 filenames in content-disposition

### ISSUE THREAD

**Issue by rysi3k** [aws/aws-sdk-js#2952]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I want to sign url by Cloudfront.Signer but filename could contain special or diacritic characters. 
On S3 file is stored on random name, but I want to download it in proper name so need to use "response-content-dispostion" query parameter.
I tried to sign it using this code:
```js
function urlEncode(str) {
        return encodeURIComponent(str)
            .replace(/!/g, '%21')
            .replace(/'/g, '%27')
            .replace(/\(/g, '%28')
            .replace(/\)/g, '%29')
            .replace(/\*/g, '%2A')
            .replace(/~/g, '%7E');
    }
const filename = 'abc def.mp4'; // for simple example, not works for this as well
const s = new AWS.CloudFront.Signer(....);
const signedUrl = s.getSignedUrl({
                expires: ~~(Date.now() / 1000) + expirationSeconds,
                url: `https://my-url.com/folder/file.mp4?response-content-disposition=${this.urlEncode(`attachment;filename*=UTF-8''${urlEncode(filename)}`)}`,
            });
```
In result, i get signed url with not works - cloudfront return AccessDenied message.
```
https://my-url.com/folder/file.mp4?response-content-disposition=attachment%3Bfilename*%3DUTF-8''abc%2520def.mp4&Expires=1573653786&Key-Pair-Id=....&Signature=....
```
There is not encoded `*` `'` (and maybe more?) chars.
In PHP version of sdk everything works.
```php
$client = new Aws\CloudFront\CloudFrontClient([
    'region' => 'eu-central-1',
    "version" => "2019-03-26"
]);

$resourceKey = 'https://my-url.com/folder/file.mp4?response-content-disposition='.urlencode('attachment;filename*=UTF-8\'\''.rawurlencode('abc def.mp4'));
$expires = time() + 300;

// Create a signed URL for the resource using the canned policy
echo($client->getSignedUrl([
    'url' => $resourceKey,
    'expires' => $expires,
    'private_key' => 'key.pem',
    'key_pair_id' => '...'
])."\n");
```
returns:
```
https://my-url.com/folder/filemp4?response-content-disposition=attachment%3Bfilename%2A%3DUTF-8%27%27abc%2520def.mp4&Expires=1573643427&Signature=...&Key-Pair-Id=...
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
12.12.0

**SDK version number**
2.548.0

**To Reproduce (observed behavior)**
see above

**Expected behavior**
SDK should return proper encoded url.

**Screenshots**

**Additional context**
Workaroud which works is additional replace (to revert original response-content-disposition) after generating signed url:
```js
const s = new AWS.CloudFront.Signer(...);

        const preparedUrl = `https://my-url.com/folder/file.mp4?response-content-disposition=${this.urlEncode(`attachment;filename*=UTF-8''${urlEncode(filename)}`)}`
        const signedUrl = s.getSignedUrl({
                expires: ~~(Date.now() / 1000) + expirationSeconds,
                url: preparedUrl,
            }).replace(/\?response-content-disposition=(.*?)&/, (matched) => {
                return '?response-content-disposition=' + (preparedUrl.match(/\?response-content-disposition=(.*?)(?:&|$)/) || [matched]).pop() + '&';
            });
```

**Comment by ajredniwja** [comment]
Hey @rysi3k, apologies for late reply.

I can look into it, if it is still a persisting issue. 

Additionally we would welcome a PR for the fix if it doesn't break anything.

**Comment by rysi3k** [comment]
Yes, problem still persists.
To be honest, i have no good idea (and time right now) how to fix it in good way :)

**Comment by alex-sh-li** [comment]
Hi, any update on this Issue?

**Comment by bbrown-extensis** [comment]
I am seeing this issue as well. Seems pretty straightforward to repro. Here's an example url: https://xxxxxx.com/737d5867-af87-43f6-aada-c430739112cd/Thumbnail?response-content-disposition=inline%3B%20filename%3D%22bernstein-firebird%3F.jpg-Thumbnail.png%22%3B%20filename*%3DUTF-8%27%27bernstein-firebird%25E4%25BC%25A0.jpg-Thumbnail.png&Expires=1611354894&Key-Pair-Id=APKAJRJSTNY6G6ZJ2I4A&Signature=Fe1ki1PV-8To1X6~vPw-4LyZQ8N6W79TDcXsvT6hnihsCp1NttGu~QK2i9BEVA7orHbZXZRjqTGFUzIsL7L8Y01H3qDlDNXh1Jtvy3EbFE5lESgDH22Wer-FrkmlfbyRdZmlSr6Kzd7H~w-luLWwfTfjhCJjqkgELVU~ZhqVXZhU5aK2ISE2EUbCNdpIehdZ1akSgzkIZlyT4KvlUT1xBAGLEK0XBy6IGsccEEBTtTY-dKPnQo7HIA0e71xopDClnZRZUCftekEIz5nMSXyGU5TexKbCldcUXIqfUNPqF-tdUYxVDKnJSJcERF8xo4TcbUxmtdcoipaMVb0G7U54cg__ The actual filename is bernstein-firebird传.jpg-Thumbnail.png. Seems to be encoded correctly in the content-disposition.

**Comment by bbrown-extensis** [comment]
Looking at this further, it seems that this is a somewhat different issue. The failure I have is with non-ascii characters.

**Comment by realies** [comment]
@bbrown-extensis, can't get it to work anywhere for some reason, can you post an example of how you sign a  URL that works in the browser? When I try, CloudFront replies with:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied</Message>
</Error>
```

Tried patching `aws-sdk-js`'s  CloudfFrontt signer.js file, to see if preserving the encoding would help, but see the same AccessDenied error. Here's the patch:
```diff
diff --git a/lib/cloudfront/signer.js b/lib/cloudfront/signer.js
index 4c1a8788..2e7d39a8 100644
--- a/lib/cloudfront/signer.js
+++ b/lib/cloudfront/signer.js
@@ -180,10 +180,20 @@ AWS.CloudFront.Signer = inherit({
             return handleError(err, cb);
         }

-        var parsedUrl = url.parse(options.url, true),
-            signatureHash = Object.prototype.hasOwnProperty.call(options, 'policy')
-                ? signWithCustomPolicy(options.policy, this.keyPairId, this.privateKey)
-                : signWithCannedPolicy(resource, options.expires, this.keyPairId, this.privateKey);
+        var parsedUrl = url.parse(options.url, true);
+        if (parsedUrl.query && parsedUrl.query['response-content-disposition']) {
+            parsedUrl.query['response-content-disposition'] = encodeURIComponent(parsedUrl.query['response-content-disposition'])
+                .replace(/!/g, '%21')
+                .replace(/'/g, '%27')
+                .replace(/\(/g, '%28')
+                .replace(/\)/g, '%29')
+                .replace(/\*/g, '%2A')
+                .replace(/~/g, '%7E');
+        }
+
+        var signatureHash = Object.prototype.hasOwnProperty.call(options, 'policy')
+            ? signWithCustomPolicy(options.policy, this.keyPairId, this.privateKey)
+            : signWithCannedPolicy(resource, options.expires, this.keyPairId, this.privateKey);

         parsedUrl.search = null;
         for (var key in signatureHash) {
```
Could it be that it doesn't work because `var resource` is already called with a potentially non-encoded url?
https://github.com/aws/aws-sdk-js/blob/307e82673b48577fce4389e4ce03f95064e8fe0d/lib/cloudfront/signer.js#L175-L180

**Comment by ankit2049** [comment]
Any update on this?

I am facing a similar issue. There's `’` in filename. Filename is `test’s.pdf`. Encoding seems to be correct since I get the following url after signing
```
https://xxx.cloudfront.net/612bbf1374c6a055aa542a09%2F5bf9542eb8bbff7015ac97edb9b8ad10%2Ftest%E2%80%99s.pdf?response-content-disposition=attachment%3B%20filename%3Dtest%E2%80%99s.pdf&Expires=1633320146&Key-Pair-Id=xxx&Signature=xxx
```

But on accessing this url, I get the following error from cloudfront
```
<Code>InvalidArgument</Code>
<Message>Header value cannot be represented using ISO-8859-1.</Message>
<ArgumentName>response-content-disposition</ArgumentName>
<ArgumentValue>attachment; filename=test’s.pdf</ArgumentValue>
<RequestId>xxx</RequestId>
<HostId>xxx</HostId>
```

Similar error for the file names with some special characters - `Munkaköri`. Encoding seems to be correct though

Is there a workaround I can follow to resolve this?

**Comment by omarioffline** [comment]
UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/mjpolak/Documents/company/project/node_modules/@aws-sdk/client-kinesis/protocols/Aws_json1_1.ts:4020:19
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at Object.deserializeAws_json1_1SubscribeToShardCommand (/home/mjpolak/Documents/company/project/node_modules/@aws-sdk/client-kinesis/protocols/Aws_json1_1.ts:2583:21)
    at /home/mjpolak/Documents/company/project/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:18
    at /home/mjpolak/Documents/company/project/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22
    at StandardRetryStrategy.retry (/home/mjpolak/Documents/company/project/node_modules/@aws-sdk/middleware-retry/src/defaultStrategy.ts:125:38)
    at /home/mjpolak/Documents/company/project/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:21:20
    at /home/mjpolak/Documents/company/project/kinesis-subscribe.ts:85:29

**Comment by realies** [comment]
Fix this issue. There's a PR fixing it.

**Comment by RanVaknin** [comment]
Hi Everyone,

Apologies that this was never addressed. v3 SDK has its own Cloudfront signer that handles this encoding correctly.

Example:

```js
import { getSignedUrl } from '@aws-sdk/cloudfront-signer';
import { generateKeyPairSync } from 'crypto';

// Generate a temporary RSA key pair
const { privateKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: {
    type: 'spki',
    format: 'pem'
  },
  privateKeyEncoding: {
    type: 'pkcs8',
    format: 'pem'
  }
});

const keyPairId = 'KXXXXXXXXXXXXXXXXXXX';

// complex filename:
const baseUrl = `https://example.com/file.mp4?response-content-disposition=attachment;filename*=UTF-8''My File Name$@?.mp4`;
const signedUrl = getSignedUrl({
  url: baseUrl,
  keyPairId,
  privateKey,
  dateLessThan: new Date(Date.now() + 300 * 1000).toISOString()
});

console.log('Signed URL (v3):', signedUrl);
```

Results in the URL correctly getting encoded (formatted for better readability):

```
Signed URL (v3):
https://example.com/file.mp4?
response-content-disposition=attachment%3Bfilename*%3DUTF-8%27%27My%20File%20Name%24%40%3F.mp4&
Expires=1719865996&
Key-Pair-Id=KXXXXXXXXXXXXXXXXXXX&
Signature=REDACTED
```

Since v2 is on the road to deprecation, and this specific issue has a workaround in v2, and the issue does not persist to v3 , I'm inclined to close this issue since it is not going to get prioritized.

Thanks again for your engagement on the thread. If there is an issue with the v3 cloudfront signer, please open a new issue on the v3 repo where we are more actively looking at new issues.

Thanks,
Ran~

**Comment by realies** [comment]
@RanVaknin,, I made a PR which fixes this a long time ago. Nobody bothered to have a look. v2 is deprecated in a while.
