### ISSUE TITLE
Cannot find module 'cfn-response': AWS Lambda nodejs10.x

### ISSUE THREAD

**Issue by RLThomaz** [aws/aws-sdk-js#2955]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When updating my Lambda functions from nodejs8.10 to nodejs10.x - as per request from AWS 
Lambda operational notification - I get the error "Cannot find module 'cfn-response'", which completely breaks my CloudFormation deployment. If I rollback the same deployed lambda to nodejs8.10 it works again.

**Is the issue in the browser/Node.js?**
AWS Labmda using Node.js 10.x

**If on Node.js, are you running this on AWS Lambda?**
Yes!

**Details of the browser/Node.js version**
nodejs10.x

**SDK version number**
The one used by AWS Lambda - I guess always the latest.

**To Reproduce (observed behavior)**

```nodejs
var cfnresp = require('cfn-response')

exports.handler = async (event) => {
    // TODO implement
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};
```

**Expected behavior**

```json
Response:
{
  "statusCode": 200,
  "body": "\"Hello from Lambda!\""
}

Request ID:
"565f6238-fd8c-4b9c-bfab-bebca1dd0e2d"
```

**Screenshots**

```json
Response:
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'cfn-response'",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'cfn-response'",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}

Request ID:
"f5fe7e20-65c6-4cb6-adb2-e2a80bfb9968"

Function Logs:
START RequestId: f5fe7e20-65c6-4cb6-adb2-e2a80bfb9968 Version: $LATEST
2019-11-14T04:27:27.919Z	undefined	ERROR	Uncaught Exception	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'cfn-response'","stack":["Runtime.ImportModuleError: Error: Cannot find module 'cfn-response'","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
END RequestId: f5fe7e20-65c6-4cb6-adb2-e2a80bfb9968
REPORT RequestId: f5fe7e20-65c6-4cb6-adb2-e2a80bfb9968	Duration: 1905.42 ms	Billed Duration: 2000 ms	Memory Size: 128 MB	Max Memory Used: 24 MB	
Unknown application error occurred
Runtime.ImportModuleError
```

**Comment by RLThomaz** [comment]
It seems that in Node.js 10.x we need to specify the relative path to actually find cfn-response.
So this code snipet below should work just fine:

```js
var cfnresp = require('./cfn-response')

exports.handler = async (event) => {
    // TODO implement
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};
```
If that is the issue/solution, can you please close this ticket and update the documentation? The documentation actually tells us to use it like the first example.

**Comment by ajredniwja** [comment]
Hey @RLThomaz,

Thank-you for reaching out to us, unfortunately the Lambda doesn't run on the latest SDK. It might be the reason that you're running into the issue. 

You can import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

Please reach out to us if you continue run into this problem.

**Comment by RLThomaz** [comment]
I'm sorry, I now believe this issue does not relate to the AWS-SDK-JS at all. I think it is an issue for the AWS Lambda and CloudFormation staff to take care of. 

For reference, if you take a look at the [documentation](https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html) you'll that their example will not work on nodejs10.x since it does not add the relative folder `./` before the module name.

**Comment by prashantalhat** [comment]
thanks @RLThomaz you saved my day. I was facing this issue when updating my nodejs runtime from 8 to 10.
