### ISSUE TITLE
aws-sdk-js amplify missing startDeployment method.

### ISSUE THREAD

**Issue by Sanj718** [aws/aws-sdk-js#2957]
In AWS Lambda function I was trying to call a function to deploy to amplify files from s3 bucket as its shown on amazon articles 

https://aws.amazon.com/blogs/mobile/deploy-files-s3-dropbox-amplify-console/#

However, its seems to that amplify.startDeployment() function doesnt exist. I tried to console all available function inside amplify but could not find startDeployment method. 

```
INFO	[ 'MONITOR_EVENTS_BUBBLE',
  'CALL_EVENTS_BUBBLE',
  'constructor',
  'createApp',
  'createBranch',
  'createDomainAssociation',
  'deleteApp',
  'deleteBranch',
  'deleteDomainAssociation',
  'deleteJob',
  'getApp',
  'getBranch',
  'getDomainAssociation',
  'getJob',
  'listApps',
  'listBranches',
  'listDomainAssociations',
  'listJobs',
  'startJob',
  'stopJob',
  'updateApp',
  'updateBranch',
  'updateDomainAssociation',
  'initialize',
  'validateService',
  'loadServiceClass',
  'getLatestServiceClass',
  'getLatestServiceVersion',
  'customizeRequests',
  'makeRequest',
  'makeUnauthenticatedRequest',
  'waitFor',
  'addAllRequestListeners',
  'apiCallEvent',
  'apiAttemptEvent',
  'attemptFailEvent',
  'attachMonitoringEmitter',
  'setupRequestListeners',
  'getSignerClass',
  'serviceInterface',
  'successfulResponse',
  'numRetries',
  'retryDelays',
  'retryableError',
  'networkingError',
  'timeoutError',
  'expiredCredentialsError',
  'clockSkewError',
  'getSkewCorrectedDate',
  'applyClockOffset',
  'isClockSkewed',
  'throttledError',
  'endpointFromTemplate',
  'setEndpoint',
  'paginationConfig',
  'listeners',
  'on',
  'onAsync',
  'removeListener',
  'removeAllListeners',
  'emit',
  'callListeners',
  'addListeners',
  'addNamedListener',
  'addNamedAsyncListener',
  'addNamedListeners',
  'addListener',
  '__defineGetter__',
  '__defineSetter__',
  'hasOwnProperty',
  '__lookupGetter__',
  '__lookupSetter__',
  'isPrototypeOf',
  'propertyIsEnumerable',
  'toString',
  'valueOf',
  'toLocaleString' ]

```

Error getting: 

```
> {
>     "errorType": "TypeError",
>     "errorMessage": "amplify.startDeployment is not a function",
>     "stack": [
>         "TypeError: amplify.startDeployment is not a function",
>         "    at Runtime.exports.handler (/var/task/index.js:22:18)",
>         "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
>     ]
> }
> 
```

**Comment by ajredniwja** [comment]
Hey @Sanj718,

Thank-you for reaching out to us, most likely the reason behind this can be Lambda not operating on the latest SDK. 

You can import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

Please reach out to us if you continue run into this problem.

**Comment by Sanj718** [comment]
> Hey @Sanj718,
> 
> Thank-you for reaching out to us, most likely the reason behind this can be Lambda not operating on the latest SDK.
> 
> You can import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).
> 
> Please reach out to us if you continue run into this problem.

Thank you! 

I've created local index.js with package.json, installed latest version of aws-sdk then uploaded it instead of inline functions in Lambda console. 

Works fine for me now.
