### ISSUE TITLE
Transcribe newly added languages with Amplify?

### ISSUE THREAD

**Issue by sorokinvj** [aws/aws-sdk-js#2958]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Guys, can I use ru-RU language with Amazon Transcribe via Amplify? The language was added just recently (August) so in Amplify docs, there are only "en-US", "en-GB", "fr-FR", "fr-CA", "es-US". I asked this in Amplify [github](https://github.com/aws-amplify/amplify-js/issues/4367), but no one replied.

Another words, is Amplify just a wrapper around SDK and if something works in SDK it will be in Amplify?

**Comment by ajredniwja** [comment]
Hey @sorokinvj,

Thank-you for reaching out to us with your issue, I can reach out to the Amplify team internally and can update you once I have a response from them.

**Comment by sorokinvj** [comment]
@ajredniwja Thanks Ajwinder! I really want to implement Amplify, but don't want to spend time on learning if it's not an option
