### ISSUE TITLE
CloudFront.getDistribution returns uppercase value for HttpVersion

### ISSUE THREAD

**Issue by iann0036** [aws/aws-sdk-js#2962]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
CloudFront getDistribution returns uppercase value for HttpVersion, docs show this should be impossible and state the possible values are "http1.1" or "http2".

**Is the issue in the browser/Node.js?**
Both

**If on Node.js, are you running this on AWS Lambda?**
N/A

**Details of the browser/Node.js version**
N/A

**SDK version number**
2.569

**To Reproduce (observed behavior)**
Create a HTTP2 CloudFront distribution and call getDistribution on it. The response will show "HTTP2".

**Expected behavior**
The response should be "http2" as per the docs.

**Screenshots**
N/A

**Additional context**
Discovered via https://github.com/iann0036/former2/issues/32

**Comment by ajredniwja** [comment]
Hey @iann0036,

Thank-you for reaching out to us with your issue, can you please confirm how you are using the create distribution? Do you specify the ```httpVersion``` in it?

**Comment by iann0036** [comment]
Hi @ajredniwja 

The one I tested with was created in the console, however I doubt the way it was created would make a difference.

**Comment by ajredniwja** [comment]
Hey @iann0036 

I wanted to check if it happens when you use SDK to make a request however this is not necessarily a bug with the SDK since SDK returns the response that is provided by the service team. 

I can reach out to the service team and update you once I hear back from them.

**Comment by iann0036** [comment]
Bump. Awaiting response from service team.

**Comment by ianmckay-vha** [comment]
Bump. Awaiting response from service team.

**Comment by iann0036** [comment]
Bump. Awaiting response from service team.

**Comment by aBurmeseDev** [comment]
Apologies for the prolonged delay in responding. Upon further investigation, it appears that the observed behavior is related to the CloudFront service rather than the AWS SDK. Since the service team has been notified about this issue and there are no outstanding action items for the SDK team, I will proceed with closing this issue. However, please feel free to reach out directly to the service team via [AWS Support](https://aws.amazon.com/contact-us/) if you need further assistance.
