### ISSUE TITLE
file transfer from ES2 production to S3 not working

### ISSUE THREAD

**Issue by grinono** [aws/aws-sdk-js#2966]
When in development I can send files to a S3 bucket. Though when pushing the nodejs app to elastic beanstalks pipeline to an production ES2 instance. The file uploading part to S3 stops working.  Any idea how to debug this? Did some tests with CORS configs but no luck. On Heroku it works just fine in production.

I checked the Privileges according the the following URL
https://aws.amazon.com/premiumsupport/knowledge-center/elastic-beanstalk-s3-bucket-instance/

**Comment by ajredniwja** [comment]
Hey @grinono,

Can you please check the permissions for S3? 

You can find more information on how to attach specific permissions to your environment instances [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/nodejs-dynamodb-tutorial.html#nodejs-dynamodb-tutorial-role).

Please reach out if that doesn't solve your problem.

**Comment by grinono** [comment]
Issue was related to max file size of NGINX. in production this error was not returned in graphql file upload. Moved to Express file upload and figured the origin.
