### ISSUE TITLE
InvalidSignatureException on app using IAM instance profile with no clock skew found

### ISSUE THREAD

**Issue by helmutkian** [aws/aws-sdk-js#2971]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

I am intermittently getting an `InvalidSignatureException` on application that is using an IAM instance profile. No clock skew was found on the instance.

````
InvalidSignatureException","stack":"InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n 
````
**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**

Not on AWS Lambda

**Details of the browser/Node.js version**

v10.17.0

**SDK version number**

aws-sdk@2.437.0 

**Expected behavior**
Not get an error

**Comment by ajredniwja** [comment]
Hey @helmutkian,

Thank-you for reaching out to us with your issue.

While this may be caused to several things,

Have you added clockskew correction [(guidlines)](https://aws.amazon.com/blogs/developer/clock-skew-correction/).

Please share your use case or minimal repro code if possible.

**Comment by norve** [comment]
I am encountering the same exact issue, I have set the clockskew correction to true, but it makes no difference. I'm using aws-sdk@2.578.0, nodejs-8.10.0.
The IAM role has been given "mediastore:*" permissions.
I'm able to call methods like MetaStoreData.listItems() with success, but I get the "InvalidSignatureException" error when I use putObject().
Code:
```
var AWS = require('aws-sdk'),
        fs = require('fs'),
        path = require('path');

AWS.config.update({
        region: 'us-west-2',
        correctClockSkew: true
});

var mediastoredata = new AWS.MediaStoreData({
        apiVersion: '2017-09-01',
        endpoint: 'https://<endpoint>.data.mediastore.us-west-2.amazonaws.com'
});

var text = fs.readFileSync(path.join(__dirname, './test.txt'));

var upload = mediastoredata.putObject({
        Path: '/TrainingData/test.txt',
        Body: text,
        ContentType: 'text/plain'
});

upload.on('httpUploadProgress', (progress) => {
        console.log(progress);
});

upload.send((err, result) => {
        if (err) {
                console.error(err);
        } else {
                console.log('success');
                console.log(result);
        }
});
```

Error:
```
{ loaded: 36, total: 36 }
{ loaded: 36, total: 36 }
{ loaded: 36, total: 36 }
{ loaded: 36, total: 36 }
{ InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
    at Object.extractError (/home/norve/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/norve/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/norve/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/norve/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/norve/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/norve/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/norve/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/norve/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/norve/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/norve/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.',
  code: 'InvalidSignatureException',
  time: 2019-11-24T01:42:40.863Z,
  requestId: 'EQDSR2M5UJZMPBWUCPVE6PEBHWL33WI6LUZ6SANHSYNL7RC7373XHJCCJHAVIFLDVYSUGRQ4IHMBECT5T6N6SVQ',
  statusCode: 403,
  retryable: true }
```

**Comment by ajredniwja** [comment]
@norve apologies for late reply, I can try to find the root cause of it if it is still a persisting issue.
