### ISSUE TITLE
TypeScript: DynamoDB ScanOutput not typed correctly

### ISSUE THREAD

**Issue by dbartholomae** [aws/aws-sdk-js#2980]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The ScanOutput interface describes `Items` as being optional, but it seem they aren't. I haven't encountered a situation yet where the value wasn't set, and e. g. [in the Java SDK it is not described as optional](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/ScanResult.html#getItems--).

**Is the issue in the browser/Node.js?**
Both

**SDK version number**
Example: v2.398.0

**To Reproduce (observed behavior)**
Typing can be found in aws-sdk/lib/dynamodb/document_client.d.ts line 1838:
```
 export interface ScanOutput {
    /**
     * An array of item attributes that match the scan criteria. Each element in this array consists of an attribute name and the value for that attribute.
     */
    Items?: ItemList;
```

**Expected behavior**
Typing should be
```
 export interface ScanOutput {
    /**
     * An array of item attributes that match the scan criteria. Each element in this array consists of an attribute name and the value for that attribute.
     */
    Items: ItemList;
```
Potentially more types are affected.

**Comment by ajredniwja** [comment]
Hey @dbartholomae thank-you for reaching out to us with your issue. While all the SDKs don't follow the same pattern however in this particular case of making ```Items``` a required field can be a breaking change for many customer's, where me and you may not be familiar with such cases.

Wont incorporate this change in the SDK, please reach out if you have any additional questions.

**Comment by dbartholomae** [comment]
Just to make sure there is no misunderstanding: I am talking about making the return value typing required. For consumers this would be a non-breaking change as code that worked for both a defined and undefined return value will continue to work for a return value that is always defined. The only thing that could break is a library that implements a mock for the scan method.

**Comment by ajredniwja** [comment]
@dbartholomae, you're right, I still think it would be out of the scope of team to implement this since it is not a breaking error however the team can review a PR if you can submit one.

**Comment by dbartholomae** [comment]
I'm happy to provide a PR. Most of the work isn't writing the PR, though (that's just removing a couple `?`), but having a domain expert check whether there are any cases where the value actually CAN be undefined.
Easiest solution would be if one of the developers who knows most about the code checks which ones should not be optional, write me the list and I will prepare the PR.
I can also prepare the PR based on my knowledge and then adapt it after feedback, if that is easier for you.

**Comment by ajredniwja** [comment]
Talking to the servicce team I was able to confirm that this will be backwards incompatible. Items in Scan output is not a required parameter. It is possible that the table have not items which would then return an empty list.
