### ISSUE TITLE
sqs temporary queues client

### ISSUE THREAD

**Issue by GustavoEmmel** [aws/aws-sdk-js#2981]
Hi,

Do we have a NodeJs library for supporting temporary queues functionality.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-temporary-queues.html

**Comment by hsw48** [comment]
Yes I am also looking for support for Virtual Queues. Here is Amazon's Java SDK repo for handling virtual queues: https://github.com/awslabs/amazon-sqs-java-temporary-queues-client/blob/master/src/main/java/com/amazonaws/services/sqs/AmazonSQSVirtualQueuesClient.java

**Comment by ajredniwja** [comment]
Hey @GustavoEmmel Apologies for the late reply.

Unfortunately the JS-SDK doesn't support the functionality yet. It's an open source project for java and not yet in JavaScript. 

Going to mark it as a feature request and will reach back when the feature is introduced.

**Comment by you-fail-me** [comment]
Is there any way to track the status of this feature request?

**Comment by zhaoyi0113** [comment]
Is there any progress on this feature?

**Comment by AndriiMz** [comment]
any changes here ?

**Comment by USSliberty** [comment]
+1 for this feature!

**Comment by tulsidas** [comment]
+1 for this feature!

**Comment by GustavoEmmel** [comment]
I think the best solution overall is to use RabbitMQ
:(

**Comment by joffarex** [comment]
Still no support for this? It's been almost two years since this issue was opened. I think it is really crucial feature to have in an official SDK

**Comment by Sampson8x** [comment]
+1 for this feature!

**Comment by rachelpopa** [comment]
This would be a really great feature to have

**Comment by regilynFeliciano** [comment]
+1 for this feature!

**Comment by Kinjalrk2k** [comment]
+1 for this feature!

**Comment by debashishkumar** [comment]
+1 for this feature!

**Comment by geekdroid07** [comment]
+1 for this feature!

**Comment by tvacherat** [comment]
+1 for this feature

**Comment by hammadali6096** [comment]
+1 for this feature

**Comment by geisbruch** [comment]
+1 for this feature

**Comment by phongvuhyuet** [comment]
+1 for this feature

**Comment by miekassu** [comment]
+1 for this feature

**Comment by breadweb** [comment]
Also went looking for this as a replacement for our costly RabbitMQ broker and was sad to see it is not available in the JavaScript SDK. Hoping it will be prioritized soon!

**Comment by kuhe** [comment]
The same request in AWS SDK JavaScript v3: https://github.com/aws/aws-sdk-js-v3/issues/2748
