### ISSUE TITLE
Unable to configure TokenFileWebIdentityCredentials

### ISSUE THREAD

**Issue by HitkoDev** [aws/aws-sdk-js#2982]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
`TokenFileWebIdentityCredentials` doesn't allow to set `DurationSeconds` or other params for `assumeRoleWithWebIdentity` 
https://github.com/aws/aws-sdk-js/blob/86cfbd7b1796a145b4075741c1a2ea287c67c0f5/lib/credentials/token_file_web_identity_credentials.js#L167-L172

**Comment by ajredniwja** [comment]
Hey @HitkoDev, thank-you for reaching out to us with your issue.

i found that you can set the params using [these](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#assumeRoleWithWebIdentity-property) guidelines. 

Please reach out if that doesn't solve your problem.

**Comment by HitkoDev** [comment]
@ajredniwja I know pretty well how to extend a one-time STS session duration, but that's not what's the problem here. `TokenFileWebIdentityCredentials` is a full service which takes care of loading OIDC token from file, credentials expiration, renewal, error handling, etc. on top of `STS.assumeRoleWithWebIdentity`, and it already allows to fully configure the underlying STS service, except for `SessionDuration`.

**Comment by trivikr** [comment]
This is how the TokenFileWebIdentityCredentials is designed in all AWS SDKs.

It only passes the following essential params to assumeRoleWithWebIdentity:
* WebIdentityToken
* RoleArn
* RoleSessionName

https://github.com/aws/aws-sdk-js/blob/86cfbd7b1796a145b4075741c1a2ea287c67c0f5/lib/credentials/token_file_web_identity_credentials.js#L168-L172

**Comment by trivikr** [comment]
The code for other AWS SDKs which also pass the three params:
* Ruby https://github.com/aws/aws-sdk-ruby/blob/fd8545751093bd1b90688cc3f28af545ec78e25d/gems/aws-sdk-core/lib/aws-sdk-core/assume_role_web_identity_credentials.rb#L23
* Go https://github.com/aws/aws-sdk-go/blob/d8409ae3d9dc0db826357792070dd69e9133bbb5/aws/credentials/stscreds/web_identity_provider.go#L79-L83
