### ISSUE TITLE
S3.upload Body property also accepts JS File type on client-side (Cognito), but undocumented

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js#2984]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

```
Body — (Buffer, Typed Array, Blob, String, ReadableStream) 
```

This should be modified to be:

```
Body — (Buffer, Typed Array, Blob, String, ReadableStream, JS File) 
```

since it's actually possible to pass an JS `File` object resulting from an HTML `<input type="file">` element:

Code example from https://aws-amplify.github.io/docs/js/storage#put
```jsx
class S3ImageUpload extends React.Component {
  onChange(e) {
      const file = e.target.files[0];
      Storage.put('example.png', file, {
          contentType: 'image/png'
      })
      .then (result => console.log(result))
      .catch(err => console.log(err));
  }

  render() {
      return (
          <input
              type="file" accept='image/png'
              onChange={(e) => this.onChange(e)}
          />
      )
  }
}
```

Under the hood, `Storage.put` is just calling `s3.upload`.

**Comment by ajredniwja** [comment]
Hey @ffxsam, thank-you for reaching out to to us with your issue, I can reach out to the docs team internally and ask them to update it.

**Comment by ffxsam** [comment]
Much appreciated!

**Comment by brmur** [comment]
@ajredniwja This was assigned to documentation team, but the SDK team are responsible for generating the API documentation.
