### ISSUE TITLE
Unexpected key 'Engine' found in params  of polly.synthesizeSpeech

### ISSUE THREAD

**Issue by binarythinktank** [aws/aws-sdk-js#2985]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
"Engine" is an unknown parameter in polly.synthesizeSpeech even though the documentation indicates it as valid: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Polly.html#synthesizeSpeech-property

I want to use the neural engine, the default is standard. neural engine works fine on the polly service page and the output is certainly different to the synthesizeSpeech output if i exclude the "engine" parameter (so i need it if i want a neural result). 

I am using the us-east-1 region

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
yes

**Details of the browser/Node.js version**
10.x 

**SDK version number**
2.488.0

**To Reproduce (observed behavior)**
const AWS = require('aws-sdk');
const polly = new AWS.Polly({apiVersion: '2016-06-10'});

polly.synthesizeSpeech({
      OutputFormat: "mp3",
      SampleRate: "24000",
      Text: "<speak>hello world</speak>",
      TextType: "ssml",
      Engine: "neural",
      VoiceId: "Matthew"
    }, function(err, data) {
      
    });

**Expected behavior**
I would expect err to be null and data to contain the speech data

**Additional context**
console.log(err) : 
{ UnexpectedParameter: Unexpected key 'Engine' found in params
    at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:77:14)
    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:126:42)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:349:7)
    at /var/runtime/node_modules/aws-sdk/lib/config.js:367:9
  message: 'Unexpected key \'Engine\' found in params',
  code: 'UnexpectedParameter',
  time: 2019-12-03T12:14:44.568Z }

**Comment by ajredniwja** [comment]
Hey @binarythinktank thank-you for reaching out to us with your issue can you make sure you are using the latest SDK with Lambda, You can import the latest version of SDK by using [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

**Comment by binarythinktank** [comment]
@ajredniwja many thanks, that resolved it. the issue is not present in version 2.583.0
