### ISSUE TITLE
The dynamoDB table `aws-sdk-js-integration-test` is not cleaned up in integration tests

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js#2986]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
* While moving dynamodb integ tests from v2 to v3 in https://github.com/aws/aws-sdk-js-v3/pull/480, I didn't find code which cleans up table `aws-sdk-js-integration-test`
* When I opened AWS account which is used for integration tests, the table `aws-sdk-js-integration-test` was present with creation date `November 30, 2019 at 3:12:32 PM UTC-8`

**To Reproduce (observed behavior)**
Run integration tests, and notice that table `aws-sdk-js-integration-test` is not deleted

**Expected behavior**
The table `aws-sdk-js-integration-test` is deleted after integration tests are done - if possible, after running dynamodb tests

**Comment by trivikr** [comment]
There is a step definition for table deletion https://github.com/aws/aws-sdk-js/blob/2b5e3170811a3996dda33b1b7d7d29e20679b621/features/dynamodb/step_definitions/dynamodb.js#L81-L84

However, it's not defined in features (probably it was deleted) https://github.com/aws/aws-sdk-js/blob/2b5e3170811a3996dda33b1b7d7d29e20679b621/features/dynamodb/tables.feature#L1-L69

**Comment by trivikr** [comment]
The step to delete table was added in https://github.com/aws/aws-sdk-js/commit/b3f7d454845b0385f90648b8e69663ac59a446ad
The commit which removed the deletion step to speed up tests https://github.com/aws/aws-sdk-js/commit/8a1c7c4f297a90ab70022615093ecc8fecdccc84

**Comment by AllanFly120** [comment]
This test implementation works as intended.

**Comment by trivikr** [comment]
Reopening.
The fix in v2 should be similar to that in v3 https://github.com/aws/aws-sdk-js-v3/pull/492
