### ISSUE TITLE
STS fails with AWS_STS_REGIONAL_ENDPOINTS = regional

### ISSUE THREAD

**Issue by sambanks** [aws/aws-sdk-js#2991]
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The latest version of the sdk fails to assume roles if the `AWS_STS_REGIONAL_ENDPOINTS` environment variable is set to `regional`

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Breaks on both Lambda and ECS (Fargate)

**Details of the Node.js version**
v10.15.3

**SDK version number**
v2.580.0

**To Reproduce (observed behavior)**
Add `AWS_STS_REGIONAL_ENDPOINTS` environment variable with a value of `regional` 

**Expected behavior**
Business as usual

**Actual behaviour**
```2019-12-03T07:53:06.726Z [error]	com.stackchat.aws-convenience.sts	Unable to assume role with parameters: {"RoleArn":"arn:aws:iam::XXXXXXXXXXXXX:role/AppDataReadWriteRole-1EBNR4SZI6G2C","DurationSeconds":3600,"RoleSessionName":"AwsConvenienceLib_createDynamoDBClient-Cached"} { UnknownEndpoint: Inaccessible host: `https://sts.ap-southeast-2.amazonaws.com'. This service may not be available in the `ap-southeast-2' region.```

`Error: getaddrinfo ENOTFOUND https://sts.ap-southeast-2.amazonaws.com https://sts.ap-southeast-2.amazonaws.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)`

**Additional context**
It appears to be trying to do a dns lookup but with the `https://` in the hostname

It was previously working until a recent dependency triggered an update of the aws-sdk.

We can't be sure which version was working as npm shows many versions of the aws-sdk, via dependencies. But it is definitely broken on v2.580.0 and is reproducable

**Comment by AllanFly120** [comment]
Hey @sambanks I have verified this is a bug in the feature we recently shipped. Here's the PR fixing it: #2994 It will be shipped later today

**Comment by sambanks** [comment]
Brilliant thanks Allan!
