### ISSUE TITLE
How to identify the cause for error loading images (CORS)

### ISSUE THREAD

**Issue by nlevari** [aws/aws-sdk-js#2992]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

We have a webapp where a user can enter its s3 credentials in order to see his files.
We are running:
```
const bucketKey = {
          Bucket : bucketKeyEndpoint.Bucket,
          Key    : bucketKeyEndpoint.Key,
          Expires: 60 * 60 * 24 * 4
        };
        let signedURL = s3Service.getSignedUrl('getObject', bucketKey);
```
and setting signedURL as the src of an image tag `<img src="signedURL" onerror="onError">`. 
This way we avoid CORS issues.
While the credentials are correct and the file exists, all works perfectly.

**The Question is:**
How can we know whay the image isn't loaded, is it because wrong credentials or file doesn't exist or any other reason?

What we tried:
- Can't make xhr calls due to CORS
- onerror event won't have useful information like status code

Please help me resolve this issue,
Thanks

**Comment by ajredniwja** [comment]
Hey @nlevari, thank-you for reaching out to us with your issue. You can use the logs to see where the error is coming from. 

To do you can do something like following:

```
var s3 = new AWS.S3({logger: console});
```

Please reach out if that doesn't solve your problem.

**Comment by nlevari** [comment]
OK. Thanks.

**Comment by ajredniwja** [comment]
Closing this issue for now, please reach out if you have any other questions.
