### ISSUE TITLE
ec2.describeInstanceStatus returns blank for stopped instances

### ISSUE THREAD

**Issue by AyushyaChitransh** [aws/aws-sdk-js#3000]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
 ec2.describeInstanceStatus does not include status of stopped instances

**Is the issue in the browser/Node.js?**
Node.js

**Details of the Node.js version**
`node -v`: v8.9.4

**SDK version number**
aws-sdk@2.585.0

**To Reproduce (observed behavior)**
```
//The params include one running and one stopped instance
var params = {
  InstanceIds: [
     "i-1234567890abcdef0", "i-0987654321abcdef0"
  ]
 };
 ec2.describeInstanceStatus(params, function(err, data) {
   if (err) console.log(err, err.stack); // an error occurred
   else     console.log(data);
```

**Expected behavior**
```
{
  "InstanceStatuses": [
    {
      "AvailabilityZone": "us-east-1d",
      "InstanceId": "i-1234567890abcdef0",
      "InstanceState": {
        "Code": 16,
        "Name": "running"
      },
      "InstanceStatus": {
        "Details": [
          {
            "Name": "reachability",
            "Status": "passed"
          }
        ],
        "Status": "ok"
      },
      "SystemStatus": {
        "Details": [
          {
            "Name": "reachability",
            "Status": "passed"
          }
        ],
        "Status": "ok"
      }
    },
    {
      "InstanceId": "i-0987654321abcdef0",
      "InstanceState": {
        "Code": 80,
        "Name": "stopped"
      },
      "AvailabilityZone": "us-east-1d",
      "SystemStatus": {
        "Status": "not-applicable"
      },
      "InstanceStatus": {
        "Status": "not-applicable"
      }
    }
  ]
}
```

**Additional context**
It has been mentioned in [this comment](https://github.com/aws/aws-cli/issues/3182#issuecomment-372853579) that AWS CLI has an additional parameter to support this query `--include-all`.

**Comment by ajredniwja** [comment]
Hey @AyushyaChitransh,

Thank-you for reaching out to us with your issue. 

This is expected behavior by the SDK as the [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeInstanceStatus-property) state that ```describeInstanceStatus``` method only returns the status of running instances. However like the CLI you can specify the param ```IncludeAllInstances``` to true. 

Example : 

```
var params = {
  IncludeAllInstances: true,
  InstanceIds: [
    '123xyz',
    /* more items */
  ]
};

ec2.describeInstanceStatus(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

Please re-open if you have more questions.
