### ISSUE TITLE
pinpoint listTemplates method is not returning all documented fields

### ISSUE THREAD

**Issue by microapps-machine-user** [aws/aws-sdk-js#3001]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
According to the [pinpoint.listTemplates](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#listTemplates-property) description in the docs it should return the following fields

```
Arn — (String)
The Amazon Resource Name (ARN) of the message template.
 
CreationDate — required — (String)
The date when the message template was created.
 
DefaultSubstitutions — (String)
The JSON object that specifies the default values that are used for message variables in the message template. This object is a set of key-value pairs. Each key defines a message variable in the template. The corresponding value defines the default value for that variable.
 
LastModifiedDate — required — (String)
The date when the message template was last modified.
 
tags — (map<String>)
A string-to-string map of key-value pairs that identifies the tags that are associated with the message template. Each tag consists of a required tag key and an associated tag value.
 
TemplateDescription — (String)
The custom description of the message template.
 
TemplateName — required — (String)
The name of the message template.
 
TemplateType — required — (String)
The type of channel that the message template is designed for.
 
Possible values include:
"EMAIL"
"SMS"
"VOICE"
"PUSH"
```

But in fact this method only returns:

```
CreationDate, LastModifiedDate, TemplateName, TemplateType
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
12.x

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `AWS.VERSION` in your code where `AWS = require("aws-sdk");`

v2.585.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

Run:
```
pinpoint.listTemplates()
```

**Expected behavior**
The request should return all documented fields

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @microapps-machine-user,

Thank-you for reaching out to us about the issue, I can reach out to the documentation team to make the updates.

**Comment by microapps-machine-user** [comment]
we actually need `tags` and `TemplateDescription` in the `listTemplates` call. Will it be implemented or the documentation is incorrect?

**Comment by ajredniwja** [comment]
@microapps-machine-user I have reached out to both the teams, and will update you once I have feedback from them.

**Comment by jimmyn** [comment]
@ajredniwja hi, is there any update on this? Will those props be added to the api or this is just a documentation issue and we should not expect them?

**Comment by leonardobork** [comment]
@ajredniwja same thing needed here. need the tags!

**Comment by ajredniwja** [comment]
Would need service team to audit this and make the changes, pinging them again.

**Comment by jimmyn** [comment]
Hi @ajredniwja any update on this issue? Having tags in `pinpoint.listTemplates()` would really simplify our lives.
