### ISSUE TITLE
await s3.upload().promise() stuck pending

### ISSUE THREAD

**Issue by jburnham96** [aws/aws-sdk-js#3004]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Hi,

I'm trying to insert a new PDF into an S3 bucket through the s3.upload() method. When awaiting the upload with `await s3.upload(params).promise();` it hangs. This is my code here:

```
const pass = new stream.PassThrough();

const params = { Bucket: `Bucket name`, Key: `File.pdf`, Body: pass };
await s3.upload(params).promise();
```
and this is my s3 config:

```
const s3 = new AWS.S3({
    accessKeyId: AWS_ACCESS_KEY,
    secretAccessKey: AWS_SECRET_ACCESS_KEY,
    signatureVersion: 'v4',
    region: 'eu-west-2'
});
```

**Comment by jk1z** [comment]
It could be because your stream has been consumed or your stream is empty. It happened to me once when I passed in a consumed stream. The AWS SDK upload just hangs there...took me ages to debug

**Comment by ajredniwja** [comment]
Hey @jburnham96,

Thank-you for reaching out to us with your issue, I agree with @jk1z that it might be the case that your stream might be empty. Can you please check on that?

**Comment by jburnham96** [comment]
@ajredniwja @jk1z thanks, I'll double check this

**Comment by jburnham96** [comment]
@ajredniwja @jk1z that was the problem :smile: thanks!
