### ISSUE TITLE
`VersionId` is untyped in `clients/mediastoredata.d.ts`

### ISSUE THREAD

**Issue by Ratniex** [aws/aws-sdk-js#3007]
**Describe the bug**
According to specification there is VersionId in many S3 related responses.
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html

**Is the issue in the browser/Node.js?**
types only

**SDK version number**
Example: v2.588.0

**Additional context**
This is one of the many places where `VersionId` is missing.
```
diff --git a/clients/mediastoredata.d.ts b/clients/mediastoredata.d.ts
index fd35cafb..3d81d5ec 100644
--- a/clients/mediastoredata.d.ts
+++ b/clients/mediastoredata.d.ts
@@ -231,6 +231,10 @@ declare namespace MediaStoreData {
      * Unique identifier of the object in the container.
      */
     ETag?: ETag;
+    /**
+     * Unique identifier of the object in the container.
+     */
+    VersionId?: ETag;
     /**
      * The storage class where the object was persisted. The class should be “Temporal”.
      */
```

**Comment by ajredniwja** [comment]
Hey @Ratniex, thank-you for reaching out to us with your issue. 

It would be really great if you can open a PR for this, the JS-SDK team would welcome a PR to review.
