### ISSUE TITLE
TypeScript: DynamoDB ScanOutput not typed correctly

### ISSUE THREAD

**Issue by dbartholomae** [aws/aws-sdk-js#3009]
Seems the old issue was locked by accident. I'm still happy to add a PR, just want to align on how to best do it:
https://github.com/aws/aws-sdk-js/issues/2980#issuecomment-562839150

**Comment by ajredniwja** [comment]
Hey @dbartholomae,

Apologies for the thread getting locked, the team would be happy to review a PR. 
You can look into some of the old PRs like [this one.](https://github.com/aws/aws-sdk-js/pull/1345/files)

**Comment by dbartholomae** [comment]
Ok, I dove into the code a bit now. It seems that the typing this is related to is auto-generated based on the json files in `/apis`. To change the typing I would need to add `required: true` to the entries that are not optional in `apis/dynamodb-2012-08-10.normal.json`, and potentially also to `apis/dynamodb-2011-12-05`? I am unsure though whether this file is autogenerated as well from some external source, e. g. by the APIs themselves. A bit of guidance would be appreciated :)

**Comment by dbartholomae** [comment]
Any news on this? It's also fine if there is no one how can guide me and I postpone this for now, I just would like to know :)

**Comment by ajredniwja** [comment]
Hey @dbartholomae,

Apologies for misunderstanding here, you're right these are autogenerated by the service team and you're right about ```Items``` should be optional, however this has to be done by the service team, I will reach out to them internally and ask them to fix the issue. 

Thank-you for your patience.

**Comment by dbartholomae** [comment]
Thanks! I have already taken the time to go through the types and check which based on my understanding should be changed. Maybe this helps to minimize work for the team :)
https://github.com/dbartholomae/aws-sdk-js/commit/6414ed0ce9e7ae2f7e6435393d58e27d72e8beae
