### ISSUE TITLE
Memory overload with ts-node

### ISSUE THREAD

**Issue by Vahan23** [aws/aws-sdk-js#3010]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
when I run empty file with ts-node where I use aws-sdk, the memory is getting up to ~430-450 mb
```
import 'aws-sdk';

const run = () => {
    setTimeout(() => {
        console.log('123');
    }, 100000);
};
run();
```
**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**

`node  v10.16.3`
`ts-node v8.3.0`

**SDK version number**
 v2.555.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
run this code with ts-node and check your memory usage 
```
import 'aws-sdk';

const run = () => {
    setTimeout(() => {
        console.log('123');
    }, 100000);
};
run();
```
**Expected behavior**

memory usage should be ~180 mb but it's ~450mb
**Screenshots**

![image](https://user-images.githubusercontent.com/42969243/70903983-a7d13b80-2019-11ea-87ce-1c04ba2b4c58.png)

**Comment by ajredniwja** [comment]
Hey @Vahan23, thank-you for reaching out to us with your issue.

Can you provide me with repro steps on how to use hTop to isolate a certain process?

Since I was not able to reproduce it.

**Comment by Vahan23** [comment]
Hey @ajredniwja , thank you for your answer,
Type htop in your terminal, after type Shift + h , and filter the processes with F4.

**Comment by ajredniwja** [comment]
Hey @Vahan23, are the instructions correct it doesn't work. 

I use a MacBook: just in case they are different for windows.

**Comment by Vahan23** [comment]
Hey @ajredniwja can you please check your ram memory usage when you run some kind of code with aws-sdk  with ts-node .

**Comment by var77** [comment]
Same here.

**Comment by ajredniwja** [comment]
Hey @Vahan23 @var77 

I was able to run it successfully with the steps you provided but I didn't see any spike in the memory usage or overload. 

I am using:

```node v12.14.0```
```ts-node v8.4.1```
```aws-sdk v2.603.0```

can you retry with the latest versions?
