### ISSUE TITLE
Docs: S3 putObjectTagging reference documentation breaks HTML rendering

### ISSUE THREAD

**Issue by ankon** [aws/aws-sdk-js#3011]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

Formatting of the reference documentation starts to be broken starting from https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObjectTagging-property

**SDK version number**
Unknown ("latest").

**To Reproduce (observed behavior)**

Open the referenced link.

**Expected behavior**

Docs look proper.

**Comment by ajredniwja** [comment]
Hey @ankon, thank-you for reaching out to us with your issue. 

I am not able to see any broken links in there, I can navigate to the link that you provided and can scroll all the way. If I understand correctly that is what you mean when you say "broken", can you please provide more details?

**Comment by ankon** [comment]
![screen-aws-docs-putObjectTagging](https://user-images.githubusercontent.com/1210641/71087988-b5afc980-219d-11ea-820a-239aa275cbb7.png)

Clicking on the 'GetObjectTagging' related resource doesn't do anything, and the cursor there is a input cursor, not a hand.

Note that from here on everything seems to be "bold" in style:
![screen-aws-docs-putObjectTagging-2](https://user-images.githubusercontent.com/1210641/71088098-f9a2ce80-219d-11ea-9365-8ccd6fd7958a.png)

**Comment by ajredniwja** [comment]
I understand what you mean now, I will reach out to the docs team and let them fix it.

**Comment by ankon** [comment]
FWIW: Problem seems to have been fixed since filing the issue.
