### ISSUE TITLE
No indication of failure when a SMS message delivery fails

### ISSUE THREAD

**Issue by kaitlynbrown** [aws/aws-sdk-js#3012]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When sending a SMS message, if delivery fails (for instance, due to the Spend Limit being reached), no exception is thrown, and the response provides no indication whatsoever that the delivery failed

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
10.16.0

**SDK version number**
2.585.0

**To Reproduce (observed behavior)**
Attempt to send an SMS to a valid phone number via `aws-sdk` after reaching the SMS spend limit for an account

**Expected behavior**
An exception should be thrown, indicating delivery failure, including the reason for failure

**Comment by ajredniwja** [comment]
Hey @kaitlynbrown, thank-you for reaching out to us with your issue. 

I was able to reproduce this behavior locally as well, this is a bug on the service side, I will reach to the team internally and update you once they address it.

Meanwhile if you know what your limits are you can change those using [these](https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-awssupport-spend-threshold.html) guidelines.

**Comment by ajredniwja** [comment]
Hey @kaitlynbrown,

I reached out to the service team, while this is the expected behavior for ```publish``` operation, the service team suggested that best practice to check for the delivery of messages is to enable CloudWatch logs/alarms. 

Please reach out if you have any other questions.
