### ISSUE TITLE
The createBucket method is mutating the object passed as parameter

### ISSUE THREAD

**Issue by eaviles** [aws/aws-sdk-js#3013]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The `createBucket` method in AWS.S3 is mutating the object passed as parameter.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.13.0

**SDK version number**
v2.585.0

**To Reproduce (observed behavior)**
```js
const params = { Bucket: 'sample' };
await client.createBucket(params).promise();
```
After running the above core, the value of `params` is now:
```js
{
  Bucket: 'sample',
  CreateBucketConfiguration: { LocationConstraint: 'us-east-1' }
}
```
Which causes problems if someone is reusing the same object in a different call, for example:

```js
await client.waitFor('bucketExists', params).promise();
// which throws: [UnexpectedParameter] Unexpected key 'CreateBucketConfiguration' found in params
```

**Expected behavior**
After calling `createBucket`, the original object used as parameter shouldn't be mutated.

**Workaround**
Freezing the object before passing it as parameter seems to stop this behavior.
```js
const params = Object.freeze({ Bucket: 'sample' });
await client.createBucket(params).promise();
await client.waitFor('bucketExists', params).promise();
```
As modules don't run in strict mode by default, the attempt to change the original object won't throw an exception and will just be ignored.

**Comment by ajredniwja** [comment]
Hey @eaviles, thank-you for reaching out to us with your issue. 

I was not able to reproduce behavior can you please share how you are providing the ```region``` for your use case?
