### ISSUE TITLE
CodePipeline putJobSuccessResult Unexpected key 'outputVariables'

### ISSUE THREAD

**Issue by mathieubrd** [aws/aws-sdk-js#3015]
- [x] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

I am using AWS Lambda with CodePipeline.
I want to put a success job result with output variables.
I tried with the Node 8.10, Node 10.x, and Node 12x runtimes.

Here is my piece of code:
```
return await CodePipeline.putJobSuccessResult({
  jobId: event["CodePipeline.job"].id,
  outputVariables: {
    'testKey': 'testValue'
  }
}).promise()
```
Here is the error:
```
Response:
{
  "errorType": "UnexpectedParameter",
  "errorMessage": "Unexpected key 'outputVariables' found in params",
  "trace": [
    "UnexpectedParameter: Unexpected key 'outputVariables' found in params",
    "    at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)",
    "    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:77:14)",
    "    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)",
    "    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)",
    "    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:126:42)",
    "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)",
    "    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9",
    "    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:349:7)",
    "    at /var/runtime/node_modules/aws-sdk/lib/config.js:367:9"
  ]
}
```
Do you have any idea?

Thank you.

**Comment by ajredniwja** [comment]
Hey @mathieubrd, thank-you for reaching out to us with your issue. 

Can you make sure that you are using the latest version of the SDK with Lambda?

You can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

**Comment by mathieubrd** [comment]
> Hey @mathieubrd, thank-you for reaching out to us with your issue.
> 
> Can you make sure that you are using the latest version of the SDK with Lambda?
> 
> You can import the latest version of SDK by following
> [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

Hi @ajredniwja
It worked!

I will open a ticket to the AWS support to ask them to update the AWS SDK version.

Thank you for your support.
