### ISSUE TITLE
Stacks are being swallowed by improper use of util.error()

### ISSUE THREAD

**Issue by mikeal** [aws/aws-sdk-js#3020]
**Describe the bug**

`util.error()` is a nice function you’ve written to bind useful error information to an Error instance. When it’s throw at the same time that it’s called it works great `throw AWS.util.error(new Error())` but there are several instances in which an error is prepared and then returned to a caller. You can see several of them in [this search](https://github.com/aws/aws-sdk-js/search?q=util.error&unscoped_q=util.error).

When this function is called to prepare an error and then thrown later the stack for the error is captured in the preparation and loses the proper call stack from where the error actually occurs, which makes debugging far more difficult.

**Is the issue in the browser/Node.js?**

This bug is all over.

**SDK version number**

Current `master` branch.

**Comment by ajredniwja** [comment]
Hey @mikeal thank-you for reaching out to us with your issue. 

The team also acknowledged that it is frustrating many a times to not have a proper stack trace where it makes it really difficult to debug sometimes. 

While I can not certainly talk about when this will be fixed for the current version of the SDK, I can tell you that this is a feature that the team worked on [version 3](https://github.com/aws/aws-sdk-js-v3) of the the SDK, which is under developer preview now. You can try [JS-SDK-v3](https://github.com/aws/aws-sdk-js-v3) and let us know your reviews about that.
