### ISSUE TITLE
AccessDeniedException when using logGroupNames with startQuery

### ISSUE THREAD

**Issue by jonathan-palumbo** [aws/aws-sdk-js#3022]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Attempting to use `logGroupNames` as opposed to `logGroupName` when invoking the the cloud watch client method `startQuery` throws an `AccessDeniedException` exception.

```
User: arn:aws:sts::***********:assumed-role/application-name-us-east-2-lambdaRole/message-handler is not authorized to perform: logs:StartQuery on resource: arn:aws:logs:us-east-2:***********:log-group:null:log-stream:
```
It seems as if the ARN is not properly being formatted and contains `null` where the `logGroupName` should be.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
Node 10.x

**SDK version number**
v2.594.0

**To Reproduce (observed behavior)**
```typescript

 const client = new CloudWatchLogs();
 
 const params: StartQueryRequest = {
    logGroupNames: [
      "/aws/lambda/group1",
      "/aws/lambda/group2",
      "/aws/lambda/group3",
    ],
    queryString: `fields @timestamp, @message | filter @message like "foo" | sort @timestamp desc`,
    startTime: 1576776494489,
    endTime: 1576797754 }
  };
 
 const queryId: QueryId | undefined = (await client
      .startQuery(params)
      .promise()).queryId;
```

**Expected behavior**
For the ARN(s) to be valid.

**Comment by ajredniwja** [comment]
Hey @jonathan-palumbo, thank-you for reaching out to us with your issue.

Are you using a Lambda Layer?

**Comment by jonathan-palumbo** [comment]
Nope no lambda layer is in use to my knowledge.

**Comment by ajredniwja** [comment]
@jonathan-palumbo, I highly doubt that your version of the SDK is not the latest if you are not using a lambda layer,   you can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).
