### ISSUE TITLE
Relax versions to allow for efficient installs & deduplication

### ISSUE THREAD

**Issue by G-Rath** [aws/aws-sdk-js#3027]
#2847 requested the version constraints for `aws-sdk-js` be relaxed, which was actioned by https://github.com/aws/aws-sdk-js/pull/2933. Sadly this was later reverted by https://github.com/aws/aws-sdk-js/pull/2988 b/c the latest version of `xml2js` broke CI, and the author chose to revert the entire change rather than tighten the constraint of `xml2js`.

The actual issue for `xml2js` was due to a [dependency](https://github.com/Leonidas-from-XIV/node-xml2js/commit/882ec6b202ad8a69219d9ac0f67ef778dcd3e403) & has since been [reverted](https://github.com/Leonidas-from-XIV/node-xml2js/issues/533).

Currently `aws-sdk-js` forces exact versions to be used, resultings in trees like this:

```
terraporter@0.0.0 /c/Users/G-Rath/workspace/projects-personal/terraporter
├─┬ aws-sdk@2.596.0
│ └── uuid@3.3.2
├─┬ jest@24.9.0
│ └─┬ jest-cli@24.9.0
│   └─┬ jest-config@24.9.0
│     └─┬ jest-environment-jsdom@24.9.0
│       └─┬ jsdom@11.12.0
│         └─┬ request@2.88.0
│           └── uuid@3.3.3  deduped
└── uuid@3.3.3
```

In addition, this also means that if a security vulnerability for any dependency that `aws-sdk-js` uses is posted, we have to wait for a new version to be released, and *all* versions prior to that version of `aws-sdk-js` are effectively burned & unusable, since they will forever be dependent on the now-vulnerabile version of the library.

While it possible that new versions of packages could break CI, this can be avoided by using a `package-lock.json`, and by placing some trust in semver: packages such as `uuid`, which is on version 3 and one of most downloaded packages on npm (to the point that there is a TC39 proposal open to pull it into node core itself, in part to reduce world bandwidth) can safely be dependent on (I feel) to not publish breaking changes under minor versions.

Meanwhile on the other side of the fence, `xml2js` is technically in the right as semver states that `0.x.x` carry no promises on how breaking minor & patch versions should or shouldn't be. As such, it makes perfect sense to keep them contained to exact version numbers.

------

tl;dr proper use of version constraints & a `package-lock.json` would reduce the maintenance of `aws-sdk-js` & allow for more efficient deduplication downstream.

I'm happy to answer any questions, and provide further details on why this would be a nice win for everyone 🙂

**Comment by cesarfd** [comment]
> tl;dr proper use of version constraints & a `package-lock.json` would reduce the maintenance of `aws-sdk-js` & allow for more efficient deduplication downstream.

No, you should never use `package-lock.json` in libraries, that would make the problem even worse.

And yes, all the dependencies listed in this project's `package.json` are wrong:

```
"dependencies": {
    "buffer": "4.9.2",
    "events": "1.1.1",
    "ieee754": "1.1.13",
    "jmespath": "0.15.0",
    "querystring": "0.2.0",
    "sax": "1.2.1",
    "url": "0.10.3",
    "uuid": "3.3.2",
    "xml2js": "0.4.19"
  }
```

This is a library so all of them should use `^` like pretty much every single JS library out there.

**Comment by G-Rath** [comment]
> No, you should never use package-lock.json in libraries, that would make the problem even worse.

Yes, you should always use a `package-lock.json`, even in libraries. By not doing so, you have no way of knowing what versions of dependencies you were using the last time the library was in a healthy state should it break due to an upstream change.

Additionally you can't perform audit checks without a lock, since that requires knowing what versions were previously installed.

[Please, always commit your lock files](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/).

**Comment by cesarfd** [comment]
If we are complaining that aws-sdk uses specific versions for its dependencies, how on Earth would be helpful that they include a lock file in their project?

Lock files are good practice and very recommended for _final projects_, not libraries. Libraries need to relax their dependencies accordingly which is what we are complaining about here. Final projects are responsible for 1) test every release to make sure everything works _now_, 2) Commit the lock file to make sure they get the same behavior in production. Period.

Almost every single JS library uses relaxed versions _and_ they _don't_ include lock files. And even when they do (mostly because the developers forgot to `.gitignore` them) they are _completely ignored_ by the package managers (both npm and yarn, look at your link) because package managers only care about the _top level lock file_, aka the final project's one.

The only thing aws-sdk needs to do is add a `^` in every dependency version and call it a day.

**Comment by G-Rath** [comment]
> how on Earth would be helpful that they include a lock file in their project?

If you look at the PRs I've linked to, you'll see that the reason the original change was reverted was because another PR failed due to new dependency versions being pulled in, which wouldn't happen if you used a lock file.

You've conflating two different aspects of a problem.

Lock files are recommended for *both* applications and libraries, for the reasons I've mentioned above and that are detailed in the article I linked. I never said the lock file should be shipped with the library, because as you & article state: they don't mean anything when being consumed as a dependency.

> Almost every single JS library uses relaxed versions and they don't include lock files.

That's not true - I know many libraries that include a lock file in their repo.

> The only thing aws-sdk needs to do is add a ^ in every dependency version and call it a day.

This would result in the situation that happened the first time around, where CI failed due to an untested dependency update caused by a lack of lock.

**Comment by cesarfd** [comment]
Again: lock files at the dependency level _are ignored by the package managers_.

**Comment by G-Rath** [comment]
Again: *I'm not saying the lock file should be included in the published package*

**Comment by cesarfd** [comment]
> Again: _I'm not saying the lock file should be included in the published package_

Yeah, but _now_, not during the rest of the conversation. You've said several times that lock files should be used even in libraries. Well, aws-sdk happens to be a library.

Anyway, flames aside, please mantainers include the `^` in the dependencies section.

**Comment by G-Rath** [comment]
> Yeah, but now, not during the rest of the conversation.

No, during the whole conversation I've always said the lock should not be published.

> You've said several times that lock files should be used even in libraries. Well, aws-sdk happens to be a library.

Yes, and I will keep saying it, because it's true. "Using" does not meant publishing.

-------

I'm glad we've cleared this misunderstanding up :)

As I said in my original post:

> please maintainers include the ^ in the dependencies section.

This will only resolve one half of the problem - in order to do this without causing issues for other PRs, a lockfile must be committed to the repo.
