### ISSUE TITLE
Create a service for creating the certificate and the thing

### ISSUE THREAD

**Issue by ViniciusDS** [aws/aws-sdk-js#3032]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I would like to create a service for creating the certificate and the thing.
I am preparing a step by step for the team to perform, but I am not finding all the services in the API.

Request Syntax:
```
POST /new-device HTTP/1.1
Content-type: application/json
{
  "macAddress": "string"
}
```

- [x] 1) Generate Certificate Key::
$
```
openssl ecparam -name prime256v1 -genkey -out macAddress.key
```
- [x] 2) Create certificate:
$
```
openssl req -new -sha256 -key macAddress.key -nodes -out macAddress.csr
```
- [x] 3) Create certificate on AWS:

Send macAddress.csr to the API and receive the certificate in PEM format:
```
https://docs.aws.amazon.com/iot/latest/apireference/API_CreateCertificateFromCsr.html
```
- [ ] 4) Attaches certificate to an AWS policy:
```
???
```
- [x] 5) Create thing on AWS:
```
https://docs.aws.amazon.com/iot/latest/apireference/API_CreateThing.html
```

- [ ] 6) Attach certificate to thing on AWS:
```
???
```

- [x] 7) Convert certificate key to base64 (TLSKey1)
$
```
openssl ec -in macAddress.key -inform PEM -outform DER | openssl asn1parse -inform DER | head -3 | tail -1 | awk -F':' '{ print $4 }' | xxd -r -p | base64 | echo "$(</dev/stdin)"
```

- [x] 8) Convert certificate to base64 (TLSKey2)
$
```
openssl x509 -in macAddress.cert.pem -inform PEM -outform DER | base64 | echo "$(</dev/stdin)"
```

Response Syntax:
```
HTTP/1.1 200
Content-type: application/json

{
   "TLSKey1": "string",
   "TLSKey2": "string"
}
```

Could someone help me with this please?

**Comment by ajredniwja** [comment]
Hey @ViniciusDS, thank-you for reaching out to us with your issue.

I believe the JS-SDK is not directly or indirectly used in your case.

You can still information on how to attach a certificate to a [here](https://docs.aws.amazon.com/iot/latest/developerguide/attach-cert-thing.html).

**Comment by ViniciusDS** [comment]
@ajredniwja Thanks, but I would need this in a webservice because I want to automate. Don't have any APIs that cover this?

**Comment by ajredniwja** [comment]
I am not sure about it since I don't see using the AWS CLI or the SDK.

If you're trying to use AWS CLI in the process you can find IOT CLI api reference [here](https://docs.aws.amazon.com/cli/latest/reference/).
