### ISSUE TITLE
Download files from s3 private bucket in angular

### ISSUE THREAD

**Issue by vishal-kayosys123** [aws/aws-sdk-js#3033]
Hi,
I have files uploaded in my s3 private bucket, I can't access any file by hitting file url directly. I want to load image file in my angular app, the only thing I have is User Pool Id, so used this process : 

            AWS.config.update({
                region: 'bucket_region',
                credentials: new AWS.CognitoIdentityCredentials({
                    IdentityPoolId: '******:****-*****-*****-****-**********'
                })
            });

            let s3 = new AWS.S3()
            let params = {
                Bucket: 'bucket-name',
                Key:"file_key"
            }
            return s3.getObject(params)..then((data) => {
            let img1: any = data.Body;
            let str = img1.reduce(function (a, b) { return a + String.fromCharCode(b) }, '');
            this.img = "data:image/jpeg;base64," + btoa(str).replace(/.{76}(?=.)/g, '$&\n');
            }).catch(err => {
                 return;
            });

This process is too slow and also the process I am using to call this function is very big junk code.
This sdk call aws-congnito api in background, which first goes in error 401 and second in success.
Can I have any other process to get files from s3 private bucket?

**Comment by ajredniwja** [comment]
hey @vishal-kayosys123 thank-you for reaching out to us with your issue.

I would recommend [cloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html) which is designed actually to reduce latency.

**Comment by vishal-kayosys123** [comment]
thanks @ajredniwja for reply, My bucket is private if we hit url directly, it will error like this :

**Comment by ajredniwja** [comment]
@vishal-kayosys123 have you tried 

> hey @vishal-kayosys123 thank-you for reaching out to us with your issue.
> 
> I would recommend [cloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html) which is designed actually to reduce latency.

Have you tried using CloudFront? You'd be able to access your private bucket when you create a distribution with CloudFront.
