### ISSUE TITLE
Too much memory used for typescript compilation

### ISSUE THREAD

**Issue by inian** [aws/aws-sdk-js#3034]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Too much memory used for typescript compilation. Duplicate of https://github.com/aws/aws-sdk-js/issues/2846. 

Bringing this up again since I think it is a serious enough problem that we can't compile even the hello world of the SDK in a EC2 linux t3.micro machine. Running it with --max-old-space-size=4096 and 1 GB swap works, but I don't think it should take so much memory to compile just this small program. 

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.13.0

**SDK version number**
Example: 2.597.0

**To Reproduce (observed behavior)**
Just trying to compile this one line TS file results in a out of memory error on a t3.micro AWS instance with nothing else running on it!
```
import  CloudFront from "aws-sdk/clients/cloudfront";
```

**Expected behavior**
I wanted the program to compile

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @inian thank-you for reaching out to us with your issue.

As mentioned before in my comment in #2846 this would need a major-version in order to make it the importation more modular. Right now it imports around 200 files when using ```import aws-sdk``` which increases the memory usage. The [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3) will be able to address this problem which is under developer preview right now. 

Since it is not necessarily a bug with the SDK I will mark it as a feature-request for now.

**Comment by inian** [comment]
Any idea when the JS-SDK-V3 would be GA?

**Comment by ajredniwja** [comment]
@inian the beta is out now. It's hard to estimate the GA yet.

**Comment by emmanuelsio** [comment]
@inian  you could get a better performance compiling with --skipLibCheck
It is not, the best solution, but I think the only one, till a stable version 

the source is here : https://swatinem.de/blog/optimizing-tsc/

**Comment by eltonio450** [comment]
even with the skipLibCheck tag activated, the memory overhead is ~300Mo

it should be considered as a bug IMO: we have a 5-10 microservices using aws-sdk, and opening the repo with those microservices literally freezes any IDE using tsserver

it's not only a matter of deployment, but also developer experience

we are currently testing v3, but it still lacks documentation, so it's a bit tricky :)

Cheers

**Comment by emmanuelsio** [comment]
> even with the skipLibCheck tag activated, the memory overhead is ~300Mo
> 
> it should be considered as a bug IMO: we have a 5-10 microservices using aws-sdk, and opening the repo with those microservices literally freezes any IDE using tsserver
> 
> it's not only a matter of deployment, but also developer experience
> 
> we are currently testing v3, but it still lacks documentation, so it's a bit tricky :)
> 
> Cheers

yes. I have the same problem. A tiny app, but when I added the aws-sdk the ec2 never compile, and consume all my credits

**Comment by trivikr** [comment]
Verified that this issue is fixed in `aws-sdk@2.740.0` by updating dependency in repro repo https://github.com/JakeGinnivan/aws-sdk-deep-imports

**Comment by ramsanath** [comment]
@trivikr thanks!
I had a unused devdependency of aws-sdk which was making tsc eat all my ram!
