### ISSUE TITLE
Docs for DynamoDB.DocumentClient.createSet([...]) state return type void.

### ISSUE THREAD

**Issue by smartinspereira** [aws/aws-sdk-js#3035]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
[Docs for `DynamoDB.DocumentClient.createSet([...])`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#createSet-property) state return type void. 

**SDK version number**
v2.598.0

**To Reproduce (observed behavior)**
See: [Docs for `DynamoDB.DocumentClient.createSet([...])`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#createSet-property)

**Expected behavior**
Return should be of type: `DynamoDB.DocumentClient.DynamoDbSet`

**Additional context**
The code is correct and returns type of `DynamoDB.DocumentClient.DynamoDbSet`. It was fixed in this [issue / pr](https://github.com/aws/aws-sdk-js/issues/1234), the docs were not updated as it seems.
I would fix the docs in a pr myself, but I just can not understand how the docs are generated.
I found a .js and .ts file, which show only the correct examples but not the wrong lines in the docs.
If somebody could point me to it I will fix it.

**Comment by ajredniwja** [comment]
Hey @smartinspereira, thank-you for reaching out to us with your issue. 

The docs you are referring to come from the service side which is autogenerated. 

I can reach out to them internally to and ask them to make the changes.

Will update once they are updated.

**Comment by smartinspereira** [comment]
Hey @ajredniwja I see. Sounds good!
