### ISSUE TITLE
Is it possible to upload/list object of a public bucket without credentials?

### ISSUE THREAD

**Issue by Esteban26** [aws/aws-sdk-js#3036]
Confirm by changing [ ] to [x] below:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Hello everyone, I'm new using the aws and the aws-sdk, and I have a question about the skd,  I'm trying to get the list of objects of a bucket, the bucket is supposed to be public, so I'm trying to initialize the s3 interface without the access key and the secret key. This is my code 

```
const AWS = require('aws-sdk');

const s3 = new AWS.S3(); 
params = {
    Bucket: "bucket_name"
};

s3.listObjects(params, function (err, data) {
    console.log('hello world');
    if (err) console.log(err, err.stack); // an error occurred
    else console.log(data);           // successful response
});
```

And this is the output in the console, so I think this is a problem caused due to the missing credentials

```
/download_360_images/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^
TypeError: Cannot read property 'Location' of undefined`

```
Could you please confirm that?

**Comment by ajredniwja** [comment]
Hey @Esteban26, thank-you for reaching out to us with your issue. 

I wrote a code that works perfectly fine for a public bucket, you can see if that works for you.

```
var s3 = new AWS.S3({region: 'us-west-2'}); //add your bucket region here

AWS.config.update({
    credentials: null
});

var params = {
    Bucket: 'ryft-public-sample-data', //change bucket name to your bucket name
};

s3.listObjects(params, function(err, data) {
    if (err) console.log(err, err.stack); 
    else     console.log(data);      
});
```

**Comment by ajredniwja** [comment]
Please reach out if you have any additional questions.
