### ISSUE TITLE
Getting EBUSY when trying to connect to dynamodb using aws-sdk-js over node12

### ISSUE THREAD

**Issue by ashishjhanwar-bst** [aws/aws-sdk-js#3038]
Confirm by changing [ ] to [x] below:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API Reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

We have a service written in Node that batch updates a few records in dynamodb,  after a couple of hours we start get the following error:

```
error: getaddrinfo EBUSY dynamodb.us-east-2.amazonaws.com {"errno":-16,"code":"NetworkingError","syscall":"getaddrinfo","hostname":"dynamodb.us-east-2.amazonaws.com","region":"us-east-2","retryable":true,"time":"2020-01-08T12:08:20.485Z"}
```

The error resolves after restarting the service but comes again in a couple of hours.

We haven't found a reason yet in the forums, and in the developer guide.

**Comment by ajredniwja** [comment]
Hey @ashishjhanwar-bst, thank-you for reaching out to us with your issue.

I believe that the error doesn't come from the SDK but the Node. 

Can you please try updating to the latest version of the Node?

Also do a ```npm cache clean``` and ```npm update```.

Also it will be a good idea to open the issue at https://github.com/nodejs/node/issues.
