### ISSUE TITLE
SQS create virtual queue with HostQueueURL attribute; unknown attribute error

### ISSUE THREAD

**Issue by hsw48** [aws/aws-sdk-js#3040]
I am trying to create a virtual queue on top of an SQS queue using the createQueue function along with the "HostQueueURL" attribute as outlined here: https://aws.amazon.com/blogs/compute/simple-two-way-messaging-using-the-amazon-sqs-temporary-queue-client/

The problem is that it returns an error message "Unknown Attribute HostQueueURL" so it seems virtual queue creation is not yet supported in the nodejs aws-sdk.

Can I get some guidance on how to proceed with this or any ideas when this might be supported? Thanks.

**Comment by ajredniwja** [comment]
Hey @hsw48, thank-you for reaching out to us with your issue. 

I saw your comment on #2981 which is a similar issue of this one.

The repo you mention in the comment is not an SDK repo for Java, it is an open source project done in java which can be used to work with virtual queues. 

Unfortunately we don't have such a client for JavaScript yet.

This would be a nice feature and will track this using the other issue to avoid duplicate issues. 

Would close this issue now, please reach out if you have any additional questions.
