### ISSUE TITLE
Custom endpoint is not compatible with access point ARN

### ISSUE THREAD

**Issue by bradennapier** [aws/aws-sdk-js#3041]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L451-L456

Note that when I comment the above code out everything does work as expected! So it appears it just needs to actually check if the endpoint is custom rather than whether any endpoint exists at all.

This code is running for me when I try to upload a stream to an access point.  I am in no way setting any custom endpoints here.  When I check what the value of `service.endpoint` is, it is `s3.amazonaws.com` which I never set manually at any point.

I can retrieve data fine through the endpoint without this error so it is only when I try to run `s3.upload(params)`

```js
const S3 = new AWS.S3({
  accessKeyId: config.get('compliance.s3SecretID'),
  secretAccessKey: config.get('compliance.s3SecretKey'),
});

async function uploadComplianceDocument(
  Key: string,
  Body: readable$Stream,
  MetaData?: { [string]: string },
) {
  const params = {
    ACL: 'bucket-owner-full-control',
    Bucket: COMPLIANCE_BUCKET,
    Key,
    Body,
    MetaData,
  };

  const result = await S3.upload(params)
    .promise()
    .catch(err => {
      console.error('[ERROR] | Failed to upload file to S3: ', params, err);
      throw err;
    });

  return result;
}
```

In this case "COMPLIANCE_BUCKET" is an access point arn which i can upload to without problem using the aws-sdk cli via something similar to below (copied from [documentation page](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-access-points.html))

```
aws s3api put-object --bucket arn:aws:s3:us-west-2:123456789012:accesspoint/prod --key my-image.jpg --body my-image.jpg
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
no

**Details of the browser/Node.js version**

```
$ node -v
v10.15.1
```

**SDK version number**

```
$ npm list aws-sdk
└── aws-sdk@2.600.0
```

**To Reproduce (observed behavior)**

See code above, I am retrieving a stream using `https` then giving it to s3 as `Body` which I have done in past.  Same instance of S3 works fine for other operations through the access point.

**Expected behavior**
Should work

**Apparent Solution**

https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L451-L456

From running tests it would appear this could potentially be fixed by changing the code in the URL above to 

```js
if (req.service._originalConfig.endpoint && req.service._originalConfig.endpoint !== 's3.amazonaws.com') {
      throw AWS.util.error(new Error(), {
        code: 'InvalidConfiguration',
        message: 'Custom endpoint is not compatible with access point ARN'
      });
    }
```

Although this also probably needs to take into account region when creating the S3 instance.

**Comment by ajredniwja** [comment]
Hey @bradennapier thank-you for reaching out to us with your issue and also opening the PR for it, would need additional review on it by the team.

**Comment by evelynStraigt** [comment]
I am running into the same issue, hopefully this can be resolved sometime in the near future.

**Comment by watchforstock** [comment]
Also running into the same issue - currently preventing us adopting access points...

**Comment by AllanFly120** [comment]
Hi @bradennapier I created a PR fixing this issue: https://github.com/aws/aws-sdk-js/pull/3109 Would like to review it?
