### ISSUE TITLE
Is this project still accepting PRs?

### ISSUE THREAD

**Issue by thomasmichaelwallace** [aws/aws-sdk-js#3043]
I was wondering if this project was still accepting pull-requests?

I'm asking because I authored a PR (#2931) two months ago, and despite other people also saying they want the fix- it still hasn't progressed past review. From the Open PRs there's quite a lot of people in a similar situation to me (some as far back as June last year); having made contributions months ago that are now stuck.

Looking at the last few months, it seems that the only PRs that are being accepted are all originating from maintainers.

I appreciate there's a lot to do (you've got the v3 sdk to work on!), but is there anything we can do? It seems a shame that this work is going to waste.

**Comment by ajredniwja** [comment]
Hey @thomasmichaelwallace sorry for the delay. The PR has been merged.

**Comment by ajredniwja** [comment]
Closing this now, please reach out if you have any additional questions.

**Comment by thomasmichaelwallace** [comment]
Thanks - although the point wasn't just about mine (how about #2963 ? - also open for nearly two months...)

I'm just wondering if there's anything we can do to get things through faster?
