### ISSUE TITLE
IE11 NetworkingError when uploading to S3 bucket

### ISSUE THREAD

**Issue by ElVisPL** [aws/aws-sdk-js#3044]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

It works on all other browsers

On IE11 I am getting `{ code:  "NetworkingError", description: "Network Failure" }`, in `send` function's callback.
IE is making only GET requests to not valid endpoint 
**https://bucket-name.s.3./..a.m.a.z.o.n.a.w.s...c.o.m/prefix/direct_uploads/111111/bd0b0659-8f8a-49c0-8925-fa9f238720fa-file.png**
**Note dots between amazonaws.com** 

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
IE 11 v11.535.18362.0

**SDK version number**
Example: v2.600.0, tested also on v.2.150.0

**To Reproduce (observed behavior)**
Standard usage
```
AWS.config.update({
...
})

this.uploader = new S3.ManagedUpload({
    params: {
      Bucket: "VALUE
      Key: "VALUE"`,
      Body: origFile,
      ContentType: "VALUE"
    }
})

this.uploader.send((err, resultData) => {
   console.log(err)
    ...
})
```

**Expected behavior**
Upload works as expected

**Comment by ajredniwja** [comment]
Hey @ElVisPL, thank-you for reaching out to us with your issue. 

I can corner this issue not coming from the SDK. The issue might be with the IE CORS settings. This article may guide you further on what you can add to your headers when you are working with IE. 

Please reach out if you have any other questions regarding the SDK.

**Comment by ElVisPL** [comment]
Hey @ajredniwja, thank you for response, could you share link which you mentioned?

**Comment by ajredniwja** [comment]
Forget to mention the link.

Here:

 https://www.webdavsystem.com/ajax/programming/cross_origin_requests
