### ISSUE TITLE
Latency increased after updating aws-sdk@2.600.0

### ISSUE THREAD

**Issue by wjsc** [aws/aws-sdk-js#3045]
After updating the module to version 2.600.0 we notice an increasement in the API latency from 100 ms to 4/5 seconds (Percentile 95). After rolling back the update, the latency normalized.
We are only using the SDK for S3 requests.

<img width="554" alt="Screen Shot 2020-01-09 at 16 38 39" src="https://user-images.githubusercontent.com/30275211/72099125-b5b76b00-32fe-11ea-8ee6-25da084abafe.png">

**Comment by wjsc** [comment]
Cc @lukillo

**Comment by ajredniwja** [comment]
Hey @wjsc, can you please provide some reproduction steps how you got these metrics?

**Comment by jeksmith** [comment]
This is a real problem, but it started before v2.600.0. We have a project that was using v2.586.0 and found that SSM and S3 aws calls (and probably for all aws services) took 4+ seconds to execute. Here are the log statements generated from the aws sdk v2.586.0:

[AWS ssm 200 4.583s 0 retries] getParameter({
  Name: '/services/parameter1',
  WithDecryption: true
})
[AWS ssm 200 4.388s 0 retries] getParameter({
  Name: '/services/parameter2',
  WithDecryption: true
})
[AWS ssm 200 4.551s 0 retries] getParameter({
  Name: '/services/parameter3',
  WithDecryption: true
})
[AWS s3 200 4.604s 0 retries] getObject({
  Bucket: 'our-bucket',
  Key: 'our-key'
})

After downgrading to v2.507.0 (same as one of our other projects), we get these times. The only change we did was change the aws sdk version.

[AWS ssm 200 0.067s 0 retries] getParameter({
  Name: '/services/parameter1',
  WithDecryption: true
})
[AWS ssm 200 0.077s 0 retries] getParameter({
  Name: '/services/parameter2',
  WithDecryption: true
})
[AWS ssm 200 0.035s 0 retries] getParameter({
  Name: '/services/parameter3',
  WithDecryption: true
})
[AWS s3 200 0.225s 0 retries] getObject({
  Bucket: 'our-bucket',
  Key: 'our-key'
})

We're running in kubernetes pods in EC2. This is a big issue and at some point we'll want to move to newer versions of the sdk.

**Comment by wjsc** [comment]
@ajredniwja I tried to reproduce this bug in an isolated codebase, but I couldn't. Seems to work fine in local.

We're running kubernetes in EKS. 

In our case we rollback aws-sdk to v2.562.0

**Comment by lukiano** [comment]
Is this one the same as https://github.com/aws/aws-sdk-js/issues/3024 ?

**Comment by jeksmith** [comment]
@lukiano Sure looks like it could be.

**Comment by ajredniwja** [comment]
This problem wont be because of the SDK, I have reached out to EKS service team, since they recently made some changes on how they evaluate credentials logic. Will update once I hear back from them.

**Comment by nckturner** [comment]
@wjsc are you using IAM roles for service accounts?

**Comment by phillycheeze** [comment]
Any update on this? Facing the same exact issue in our EKS clusters.

**Comment by phillycheeze** [comment]
I'm adding workarounds we found for anyone else suffering from this

1. Set the metadata timeout to be much lower

```
AWS.config.credentials = new AWS.EC2MetadataCredentials({
  httpOptions: { timeout: 500 }, // 1/2 second or whatever you want
  maxRetries: 1
});
```

2. Downgrade to aws-sdk-js version 2.574.0 before the commit was introduced to use the new signed IMDSv2 metadata flow.

3. Use an alternative credentials source before it attempts to hit the metadata api. (harcoded, env variables, config files, etc). The metadata credential source defaults to being the last source to check, so using any other source will temporarily solve this problem.

**Comment by mmdonaldson** [comment]
+1 also having 4-5 second latency for SSM getParameter callls from ECS. Any updates on this?

**Comment by JCFerrerG** [comment]
+1 also having 4-5 second latency for Lambda.invoke() from Elastic Beanstalk platform `Docker running on 64bit Amazon Linux 2/3.2.6`

@phillycheeze's [workaround #1](https://github.com/aws/aws-sdk-js/issues/3045#issuecomment-617969801) was super helpful. Thanks!
