### ISSUE TITLE
Worm won

### ISSUE THREAD

**Issue by shannawhaley0** [aws/aws-sdk-js#3046]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
A clear and concise description of what the bug is.nonvierfydeable the ones that is put to a stop because of lack of token

**Is the issue in the browser/Node.js?**
Browser/Node.js
games and Android apps 

**If on Node.js, are you running this on AWS Lambda?** Android 

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v` 
Android git hub 

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `AWS.VERSION` in your code where `AWS = require("aws-sdk");` AWS

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo) 1

**Expected behavior**
Still screen

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Closing because it is irrelevant.
