### ISSUE TITLE
Delay problem sending hundred of small images to S3 bucket. 20 minutes instead of few seconds.

### ISSUE THREAD

**Issue by Aarbel** [aws/aws-sdk-js#3047]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Hi AWS teams,

I have a treatment Nodejs server which produces .png tiles for Leaflet maps, and then upload them to a S3 bucket.
My server has to upload very quickly about 900 images of 100 kb to S3 bucket. Here is one example of tile image: 
![image](https://user-images.githubusercontent.com/25119847/72228557-fede1800-35a7-11ea-9786-4079f56d96b7.png)
**My problem**: it takes a huge time to upload the 900 tiles images (about 20 minutes), even if the upload is done from an EC2 server.

I tried to parallelise my s3.upload() processes in my nodejs app with Promise.all() but it doesn't solve anything.

Is that an S3 limitation or am i doing things wrong ? (like using the wrong methods s3.upload ?)

Thanks a lot for your help !

Here is an extract of my code : 
```JS
const aws = require('aws-sdk');
const s3 = new aws.S3({
    httpOptions: {
        timeout: 60 * 1000,
    },
});

... one more code later

await Promise.all(
    files.map((file) => s3.upload({
                Bucket: myBucket,
                ACL: 'public-read',
                Key: file.s3Path,
                Body: file.stream,
                ContentType: 'image/png',
                CacheControl: 'max-age=31556926',
            })
            .promise()
            .then(() => {
                console.log('Success');
            })
            .catch(err => console.error(err))
    ),
).then(function(result) {
    console.log('upload finished :', result);
}).catch(err => console.error(err));
```

**Comment by Aarbel** [comment]
An alternative could be to upload a folder like a tar.gz on AWS s3 with all the inages, the main problem is that i would to treat it the tar.gaz file again to directly have access to one image of its content.

**Comment by franzwong** [comment]
Did you try to do that in multiple batches? Considering you need to create hundreds of http connections, I don't think you can do that all at the same time.

**Comment by AllanFly120** [comment]
@Aarbel 
Can you try enable [`s3DisableBodySigning config`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#s3DisableBodySigning-property)? SDK hashing the body might take sometimes.
