### ISSUE TITLE
Pagination via async generators

### ISSUE THREAD

**Issue by Thom1729** [aws/aws-sdk-js#3049]
**Is your feature request related to a problem? Please describe.**

When a Request is pageable, it would be natural to iterate over those pages using an async generator. However, there is no built-in way to do this.

The Request class does offer various pagination helpers, and it offers a `.promise()` method for use in async code, but there are no helpers to facilitate async iteration.

**Describe the solution you'd like**

Example code:

```js
const S3 = new AWS.S3();
const request = S3. listObjectsV2({
    bucketName: 'MyBucket',
});
for await (const data of request.pages()) {
  for (const object of data.Contents) {
    // Do something with object
  }
}
```

In this minimal example, the existing `.eachPage(callback)` method could be used instead. But async generators are a standard JavaScript type and can be easily and idiomatically manipulated:

```js
import { mapMany, filter } from './async-utils'; // Implementation omitted.

const S3 = new AWS.S3();
const request = S3. listObjectsV2({
    bucketName: 'MyBucket',
});
const objects = mapMany(request.pages(), data => data.Contents);
const filtered = filter(objects, object => object.Size > 1000);
for await (const object of filtered) {
  // Do something with object
}
```

I used S3 in the above examples because it's simple and ubiquitous, but the applications extend to any pageable API.

The `.pages()` method name is a placeholder; any number of names would work.

**Describe alternatives you've considered**

The obvious alternative is not using async iterators. The existing helpers could be used to solve the same problems in a callback-oriented style, just as the `.promise()` method could be replaced with callback-oriented code.

Another alternative would be writing my own function to turn a Request into an async generator. The implementation is not especially complicated. However, this seems like the sort of low-level functionality that would benefit from a standardized, well-tested implementation at the SDK level. In addition, a method is likely to read more naturally in code.

A similar helper could be used to iterate over individual items, like the experimental `.eachItems(callback)` method.

**Comment by solidsnack** [comment]
It does seem like we can take advantage of the uniformity of `$response.data` and `$response.nextPage()` to write a generic async paginator for AWS requests.

**Comment by ajredniwja** [comment]
Hey @Thom1729 apologies for the delayed response here, this should be fixed in V3 of the SDK. Can you give it a try? 

The [version 3.x](https://github.com/aws/aws-sdk-js-v3) of the AWS SDK for JavaScript is generally available. For more information see the [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/) or [API Reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html).

**Comment by trivikr** [comment]
The blog post on [Pagination using Async Generators](https://aws.amazon.com/blogs/developer/pagination-using-async-iterators-in-modular-aws-sdk-for-javascript/) covers how it works in v3.

**Comment by Thom1729** [comment]
I've tried it out and it seems to meet the use case.
