### ISSUE TITLE
MalformedACLError: The XML you provided was not well-formed or d id not validate against our published schema

### ISSUE THREAD

**Issue by ampProjects** [aws/aws-sdk-js#3051]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I am trying to set diferente ACL when I use the putBucketAcl api. Regarding documentacion, this is how params look like:

```
const params = {
        Bucket: "graphql-aws",
        AccessControlPolicy: {
          Grants: [
            {
              Grantee: {
                Type: "Group",
                URI: "http://acs.amazonaws.com/groups/global/AllUsers"
              },
              Permission: "READ"
            },
            {
              Grantee: {
                Type: "Group",
                URI: "http://acs.amazonaws.com/groups/s3/LogDelivery"
              },
              Permission: "READ_ACP"
            },
            {
              Grantee: {
                Type: "Group",
                URI: "http://acs.amazonaws.com/groups/s3/LogDelivery"
              },
              Permission: "WRITE"
            }
          ]
        }
      };
```

I have check with stackflow, and params are correct, but when I use the putBucketAcl(params) api, I have the following error:

> "MalformedACLError: The XML you provided was not well-formed or did not validate against our published schema"

Any suggestion? I have checked millions of times and I don see where I am wrong.

Thanks.

**Comment by ajredniwja** [comment]
Hey @ampProjects, thank-you for reaching out to us with your issue. The S3 XML errors are passed directly from the service side where SDKs don't generate these, however errors are generally vague. 

A workaround can be to use ```GrantRead, GrantReadAcp, GrantWrite``` 
Like ```GrantRead: "uri=http://acs.amazonaws.com/groups/s3/LogDelivery"```

Which will also reduce the whole code down to 4 lines. 

Can reach out to the service team if that doesn't solve your problem for better assistance.

**Comment by ampProjects** [comment]
Hi @ajredniwja,
Thanks for your response, I was on holiday for that I am late in reply you.
I have tried you are telling me, but when you use `GrantRead: "uri=http://acs.amazonaws.com/groups/s3/LogDelivery"` it just can update por LogDelivery. I would like to update Server Delivery and and Public acces at the same time.
I am saying this, because de putBucketAcl method, update everything, so if your have ACL for public, it is remove it.

Thanks

**Comment by ajredniwja** [comment]
Hey @ampProjects, apologies, I lost track of the issue, can you please share your use case?
