### ISSUE TITLE
Error with imagebuilder.createImageRecipe() due to incorrect constructor definition

### ISSUE THREAD

**Issue by JKCT** [aws/aws-sdk-js#3052]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
It appears that the constructor for the imagebuilder.createImageRecipe() is incorrect in the aws-sdk for javascript, which causes an error when calling this method.  
SDK Documentation for : https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Imagebuilder.html#createImageRecipe-property

VSCode seems to indicate this may be a problem with the constructor for this method needing a  clientToken but not having one:
```
Argument of type '{ components: { componentArn: string; }[]; name: string; parentImage: string; semanticVersion: string; }' is not assignable to parameter of type 'CreateImageRecipeRequest'.
  Property 'clientToken' is missing in type '{ components: { componentArn: string; }[]; name: string; parentImage: string; semanticVersion: string; }' but required in type 'CreateImageRecipeRequest'.ts(2345)
imagebuilder.d.ts(742, 5): 'clientToken' is declared here.
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
12.14.1

**SDK version number**
v2.602.0

**To Reproduce (observed behavior)**
```
  const AWS = require("aws-sdk");
  const imagebuilder = new AWS.Imagebuilder({region: 'us-west-2'});
   var params = {
    components: [
      {
        componentArn: 'arn:aws:imagebuilder:us-west-2:aws:component/php-7-3-linux/1.0.0'
      },
    ],
    name: 'TestRecipe',
    parentImage: 'arn:aws:imagebuilder:us-west-2:aws:image/amazon-linux-2-x86/2020.1.8',
    semanticVersion: '1.0.0',
  };
  imagebuilder.createImageRecipe(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
  });
```

Produces generic error in log/traceback:
```
{
  "errorType": "ServiceException",
  "errorMessage": "An internal error occurred while processing your request.",
  "trace": [
    "ServiceException: An internal error occurred while processing your request.",
    "    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
    "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
    "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
    "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
    "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
    "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
    "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)"
  ]
}
```

**Expected behavior**
Successful sdk response as defined in https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Imagebuilder.html#createImageRecipe-property

**Additional context**
Replacing the method with another method for example: `imagebuilder.listImagePipelines()`
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Imagebuilder.html#listImagePipelines-property
Works fine so this issue seems to be isolated to the `imagebuilder.createImageRecipe()` method

**Comment by ajredniwja** [comment]
Hey @JKCT, thank-you for reaching out to us with your issue.

Are you using a lambda layer for your application as mentioned [here](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

**Comment by JKCT** [comment]
Hi @ajredniwja !
I'm not using a lambda layer for this application, but I am installing the dependencies (aws-sdk) to the root of the deployment zip directly just as described in your link (npm install aws-sdk).  

Interestingly I'm able to run the code from the unzipped lambda deployment package locally:
```
 $ node test.js
{
  requestId: '25c17735-d3a3-46ed-9817-6da28c2bfe4b',
  clientToken: '8bfbe676-1e9b-4c2d-aee8-1cb13530b8a9',
  imageRecipeArn: 'arn:aws:imagebuilder:us-west-2:634669247018:image-recipe/testrecipe/1.0.0'
}
```
This makes me wonder if there is some conflict with lambda choosing an older version of the aws-sdk that is native to the lambda Node 12.X environment instead of the one I package in the 'node_modules' directory.  I notice that the pre-installed sdk for the lambda environment is significantly older: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by ajredniwja** [comment]
Hey @JKCT you're exactly right, the Lambda doesn't import the latest SDK so that is why the best practice is to use a Lambda layer. 

https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

**Comment by JKCT** [comment]
Thank you for your response.  I've refactored the lambda function to use a layer to import the node_modules as specified in the above documentation.  I've also ensured that the aws-sdk module is latest version when packaging the layer:
```
 $ npm install aws-sdk@2 --production --no-package-lock --no-save --prefix ./layer/nodejs
+ aws-sdk@2.603.0
added 14 packages from 66 contributors in 1.784s
found 0 vulnerabilities
```

It appears that `var AWS = require("aws-sdk");` is now correctly referencing the packaged module in the layer (path is now /opt/nodejs/node_modules/aws-sdk since layers are stored in the /opt directory) however I am unfortunately still getting a very similar error from lambda except with the new /opt path being referenced:
```
{
  "errorType": "ServiceException",
  "errorMessage": "An internal error occurred while processing your request.",
  "trace": [
    "ServiceException: An internal error occurred while processing your request.",
    "    at Object.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
    "    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
    "    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
    "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:683:14)",
    "    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)",
    "    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)",
    "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:685:12)"
  ]
}
```
So this issue definitely seems to be unique running the code in lambda (specifically nodejs12.x runtime) and this specific API call but not sure what the issue is since it seems to be using the correct latest aws-sdk module from the layer.  Please let me know if there is additional information I can provide to help track down the issue.

Thank you!

**Comment by ajredniwja** [comment]
@JKCT I can corner this issue coming from the service and not the SDK. 

I was also able to run it successfully from my local machine. 

Can you follow a step found [here](https://docs.aws.amazon.com/step-functions/latest/dg/bp-lambda-serviceexception.html) to handle the exception.

**Comment by JKCT** [comment]
As you confirmed this issue is with the Lambda environment and not an issue with the aws-sdk. I have opened a case with AWS support and I am closing this issue.

Thank you for your assistance in troubleshooting!
