### ISSUE TITLE
In Angular not able to upload base64 file

### ISSUE THREAD

**Issue by mustafakunwa** [aws/aws-sdk-js#3053]
I have been trying to upload a scanned image which I get from TWAIN scanner I convert that to base64 and uploading via presigned URL but not able to upload it properly
 ```
   this.http
      .put<any>(Url, base64Result, {
        headers: {
          'Content-Type': "image/jpeg",
          'Content-Encoding': 'base64'
        }
      }).subscribe();

```
![image](https://user-images.githubusercontent.com/45129618/72427114-15a38b00-37b1-11ea-984f-d7be9d20478f.png)
 
this is my base64 data:
```
{
stwain: c.html5.STwain {config: {…}, clientId: "890103618", _bNoUI: false, _customIP: false, _ssl: false, …}
_md5: "9BCA8089F0AF236732A38F068223B8AA"
_length: 131352
_content: "/9j/4AAQSkZJRgABAQEAyADIAAD/2wCEAAYEBQYFBAYGBQYHBw".....
}
```

**Comment by ajredniwja** [comment]
Hey @mustafakunwa thank-you for reaching out to us with your issue?

Can you provide me steps to reproduce the issue?

Also it would be helpful if you could provide me what error you see when uploading the file?

Can you please answer the questions found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug+report&template=---bug-report.md&title=)

**Comment by mustafakunwa** [comment]
There is no error image uploaded as shown above

**Comment by ajredniwja** [comment]
@mustafakunwa can you share your use case and how you are generating the ```presignedURL```
