### ISSUE TITLE
Missing 'aws-exec-read' and 'log-delivery-write' canned bucket ACLs in s3.d.ts

### ISSUE THREAD

**Issue by ankon** [aws/aws-sdk-js#3054]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The `BucketCannedACL` type could/should list the `aws-exec-read` and `log-delivery-write` values to match the documentation:

https://github.com/aws/aws-sdk-js/blob/eb36c972d7dfa729c8e9c7e2d2c806b76ffc071a/clients/s3.d.ts#L892

See https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

**Is the issue in the browser/Node.js?**
Both (TypeScript definitions)

**SDK version number**
v2.603.0

**Comment by ajredniwja** [comment]
Hey @ankon thank-you for reaching out to us with your issue.

The docs that you have mentioned specify canned ACLs for object related operations found [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property).

The code below imports typings for BucketCannedACL
 https://github.com/aws/aws-sdk-js/blob/eb36c972d7dfa729c8e9c7e2d2c806b76ffc071a/clients/s3.d.ts#L892


For objects:

https://github.com/aws/aws-sdk-js/blob/eb36c972d7dfa729c8e9c7e2d2c806b76ffc071a/clients/s3.d.ts#L3603


The typings are imported differently for objects and buckets. 

The [documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl) specifies whether it applies to a bucket or an object in the applies to section. 

Would be closing this issue, please re-open if you have any additional questions.

**Comment by ankon** [comment]
Sorry, I'm not understanding what you're saying.

The docs you reference clearly say that `aws-exec-read` and `log-delivery-write` are for buckets _and_ objects, and so I would expect these to be listed explicitly here in `BucketCannedACL` _in addition to_ being listed in `ObjectCannedACL`.

**Comment by ankon** [comment]
Btw, @ajredniwja I cannot re-open this issue, could you please do that?

**Comment by ajredniwja** [comment]
@ankon Apologies, I didn't look at the correct section, let me mark it as a feature request.

You are welcomed to open a PR for the issue, I just need to test if the docs are wrong or we need to change the code in the SDK.

**Comment by ajredniwja** [comment]
The fix would be have to be implemented by the service team since they generate the file. 

Would reach service team internally and have them change it.

**Comment by ankon** [comment]
https://github.com/aws/aws-sdk-js/blob/2dae0666ba912e0aa8f534d5291af8aafc0ca397/clients/s3.d.ts#L970


You know what's awesome? In the time this has been open the GitHub mobile experience has evolved so much that I can find that new link on my phone.

**Comment by aBurmeseDev** [comment]
Hi there - apologies for the extended delay in providing a response. It appears that this issue needs to be addressed by the service team, as these models are generated upstream by their respective teams. We had previously notified the S3 team about this, but unfortunately, no progress has been made thus far. Please feel free to reach out directly to the service team via [AWS Support](https://aws.amazon.com/contact-us/) for further updates and assistance.

Since there are no pending action items for the SDK team, and we aim to dedicate this repository solely for SDK-related issues, I will proceed with closing this case.
