### ISSUE TITLE
Update stack containing `AWS::Lambda::EventSourceMapping` is not recognising changes if only MaximumRetryAttempts are changed.

### ISSUE THREAD

**Issue by ramaguruprakash** [aws/aws-sdk-js#3058]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Update stack containing Type": `AWS::Lambda::EventSourceMapping` is not recognizing changes if only MaximumRetryAttempts are changed.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
% node -v                                                                                                                                                 ✹ ✭
v12.13.0

**SDK version number**
% cat node_modules/aws-sdk/package.json
{
  "name": "aws-sdk",
  "description": "AWS SDK for JavaScript",
  "version": "2.606.0",
 .......
}
**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
1. create a CF stack with lambda + kinesis.
2. change the CF template with `MaximumRetryCount` in the AWS::Lambda::EventSourceMapping
3. update the stack.

**Expected behavior**
The `MaximumRetryCount` doesnot changed in the lambda kinesis mapping.

**Screenshots**
<img width="447" alt="Screen Shot 2020-01-20 at 9 01 49 AM" src="https://user-images.githubusercontent.com/30412742/72696856-c5874880-3b63-11ea-8be2-de152cc6f652.png">
<img width="866" alt="Screen Shot 2020-01-20 at 9 01 31 AM" src="https://user-images.githubusercontent.com/30412742/72696863-ce781a00-3b63-11ea-91a8-841e85ce0412.png">

See that the CF template change has not reflected in Lambda Kinesis mapping.

**Comment by ajredniwja** [comment]
Hey @ramaguruprakash thank-you for reaching out to us with your issue.

Are you creating CF stack with lambda + kinesis using the JS-SDK? If yes can you please share the code that you're using?
