### ISSUE TITLE
TypeScript type definitions wrong order for overloaded methods

### ISSUE THREAD

**Issue by coyoteecd** [aws/aws-sdk-js#3059]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
TypeScript definitions for overloaded API methods are generated in the wrong order. This breaks some advanced type inference due to the assumption the TypeScript folks have made, that [the most permissive overload is placed last](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#type-inference-in-conditional-types).

**Is the issue in the browser/Node.js?**
Node.js (but doesn't matter)

**If on Node.js, are you running this on AWS Lambda?**
It's a compile-time thing

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
6.13.4

**SDK version number**
v2.601.0

**To Reproduce (observed behavior)**
I am trying to write a type that extracts the input type of an AWS SDK service API method that follows the request/response format, relying on the convention that all API methods take a "params" input with an optional callback and return a Request object. For example:
```
type FunctionType<T> = T extends Function ? T : never;

type AwsServiceMethodInputType<TMaybeMethod> =
  FunctionType<TMaybeMethod> extends (params: infer TInput, callback?: (err: AWSError, out: any) => void) => any ? TInput : never;
```

This works fine, except for the overloaded methods that do not need any input. In that case, TypeScript infers TInput to the callback type. While reading the docs, I've figure out the cause is they look at the order of methods in the type definitions file, which in AWS SDK is the opposite they expect, for example:
```
  /**
   * Lists the users in the Amazon Cognito user pool.
   */
  listUsers(params: CognitoIdentityServiceProvider.Types.ListUsersRequest, callback?: (err: AWSError, data: CognitoIdentityServiceProvider.Types.ListUsersResponse) => void): Request<CognitoIdentityServiceProvider.Types.ListUsersResponse, AWSError>;
  /**
   * Lists the users in the Amazon Cognito user pool.
   */
  listUsers(callback?: (err: AWSError, data: CognitoIdentityServiceProvider.Types.ListUsersResponse) => void): Request<CognitoIdentityServiceProvider.Types.ListUsersResponse, AWSError>;
```
I've verified by manually swapping the order of methods and type inference then works correctly, matching the params type.

**Expected behavior**
The overloaded SDK methods should be generated in the opposite order they're now, so that the version with both params and callback comes last (after the variant with callback-only).

**Comment by trivikr** [comment]
Confirmed that the first overloaded function shown is the one which just accepts callback

Tested with the following code:
```javascript
const IAM = require("aws-sdk/clients/iam");

(async () => {
  const client = new IAM({ region: "us-west-2" });
  client.listUsers(); // IntelliSense suggestion will appear when cursor is post opening bracket
})();
```

Screenshot on VSCpde 1.41.1 with TypeScript 3.4.1:
![Screen Shot 2020-01-22 at 1 31 04 PM](https://user-images.githubusercontent.com/16024985/72936190-8b60a700-3d1b-11ea-8f8e-b14400de0883.png)

Users can click on arrows to switch to first option as follows:
![Screen Shot 2020-01-22 at 1 29 48 PM](https://user-images.githubusercontent.com/16024985/72936151-7e43b800-3d1b-11ea-9d58-966454204a88.png)

The request is to show definition with params first.

**Comment by trivikr** [comment]
Type definitions for clients are updated by release scripts
Example commit history for chime.d.ts https://github.com/aws/aws-sdk-js/commits/master/clients/chime.d.ts

This requires investigating internal release scripts.

**Comment by coyoteecd** [comment]
@trivikr thanks for reviewing. 
Can you please investigate your release scripts and see if they can be adjusted? The point of having typings is to help typescript users, so I'd expect the typings follow the expectations of the typescript compiler....

**Comment by coyoteecd** [comment]
@trivikr @ajredniwja on a closer look, it's not just the order that's broken in the typings, some of the overloads are downright incorrect. See for example accessanalyzer.d.ts:

```
  /**
   * Creates an analyzer for your account.
   */
  createAnalyzer(params: AccessAnalyzer.Types.CreateAnalyzerRequest, callback?: (err: AWSError, data: AccessAnalyzer.Types.CreateAnalyzerResponse) => void): Request<AccessAnalyzer.Types.CreateAnalyzerResponse, AWSError>;
  /**
   * Creates an analyzer for your account.
   */
  createAnalyzer(callback?: (err: AWSError, data: AccessAnalyzer.Types.CreateAnalyzerResponse) => void): Request<AccessAnalyzer.Types.CreateAnalyzerResponse, AWSError>;
```

while at the same time see the documentation in [AWS SDK here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/AccessAnalyzer.html#createAnalyzer-property). You can see there a bunch of parameters marked as "required". So, what  purpose does the second overload serve, and *why is this not a bug*???

**Comment by cklam2** [comment]
Yup, exactly. Same for Cognito's [adminGetUser](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminGetUser-property).

```
/**
   * Gets the specified user by user name in a user pool as an administrator. Works on any user. Calling this action requires developer credentials.
   */
  adminGetUser(params: CognitoIdentityServiceProvider.Types.AdminGetUserRequest, callback?: (err: AWSError, data: CognitoIdentityServiceProvider.Types.AdminGetUserResponse) => void): Request<CognitoIdentityServiceProvider.Types.AdminGetUserResponse, AWSError>;
  /**
   * Gets the specified user by user name in a user pool as an administrator. Works on any user. Calling this action requires developer credentials.
   */
  adminGetUser(callback?: (err: AWSError, data: CognitoIdentityServiceProvider.Types.AdminGetUserResponse) => void): Request<CognitoIdentityServiceProvider.Types.AdminGetUserResponse, AWSError>;
  ```
Really don't know how the second overload would know which user to get. But in TypeScript this is the one that pops up. So besides the wrong order these incorrect typings are also definitely a bug.

**Comment by coyoteecd** [comment]
@trivikr Any progress on those internal scripts??

**Comment by coyoteecd** [comment]
@trivikr @ajredniwja any progress here?

**Comment by ajredniwja** [comment]
Hey @coyoteecd, while I am not sure when this will be prioritized, you might want to check out the [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3) which solves this problem.

**Comment by Nevon** [comment]
I would love to see a resolution to this. One example of when this becomes a real problem is when trying to mock methods on the AWS SDK clients, as the inferred signature will be that of the last overload. For example with jest:

```ts
import AWS from 'aws-sdk';
jest.mock('aws-sdk');

const mockedSSM = AWS.SSM as jest.MockedClass<typeof AWS.SSM>;

// this will not work because "params" is expected to be a callback due to that overload being the last one
mockedSSM.prototype.getParameter.mockImplementation((params) => {
  return {
    promise: async () => ({ Name: params.name, Value: 'foo' })
  } as Request<SSM.Types.GetParameterResult, AWSError>
});
```

**Comment by Nevon** [comment]
Hello bot. Yes, this is still an issue.

**Comment by Nevon** [comment]
Nice to see you again, bot.

**Comment by kellertk** [comment]
Hello, v3 of the SDK is now the preferred version to use, and everyone should migrate to v3. Typescript definitions in v3 should be much clearer. I will be closing this issue here, but if you are still having problems, please create an issue in the v3 repository.
