### ISSUE TITLE
Amazon s3 storage upload file using presigned Url android

### ISSUE THREAD

**Issue by asif-ashraf** [aws/aws-sdk-js#3063]
I am working on an amazon s3 storage client. I want to upload a file using presigned URL but when uploading file using Retrofit or other utility library file uploaded successfully but file being corrupted I have read my article but failed to find any proper solution. If anyone has resolved this issue please give me proper channel  
Your help is appreciable
Thanks

**Comment by ajredniwja** [comment]
Hey @asif-ashraf thank-you for reaching out to us with your issue. 

Can you please answer the questions found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug+report&template=---bug-report.md&title=).
