### ISSUE TITLE
Update AWS SDK JavaScript NodeJS 12 Runtime

### ISSUE THREAD

**Issue by CNoetzel** [aws/aws-sdk-js#3069]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Hi folks,

according to https://docs.aws.amazon.com/lambda/latest/dg/programming-model.html NodeJS 12 Runtime of AWS Lamda is using version 2.585.0 of aws-sdk-js.

This version causes a lot of error messages in cloud watch as mentioned in issue #2979 .

Are there any news when the lamda team plan to update the sdk version?

**Comment by ajredniwja** [comment]
Hey @CNoetzel thank-you for reaching out to us with your issue.

While Lambda team strives to provide the latest version there is no a set ETA on when they will update to the latest version. You can import the latest version using [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

Closing this issue now, please re-open/reach out if you have any additional questions.
