### ISSUE TITLE
adminCreateUser appears to be running twice when called

### ISSUE THREAD

**Issue by DoctorWhich** [aws/aws-sdk-js#3070]
I have been calling adminCreateUser, but _almost_ every time I call it, I get a UsernameExistsException - even though I know for a fact that the username hasn't been used - but it does create the user. I have found that changing the UserPool to one that doesn't need a Username _and_ an email attempts to create two separate users, so for some reason the call must be running twice.

```
const AWS = require('aws-sdk');

exports.handler = async (event) => {
    console.log(JSON.stringify(event));
    if (!event.hasOwnProperty('email')) {
        throw new Error("No email address provided");
    }
    let email = "my@email.com";
    
    var params = {
        UserPoolId: [REDACTED],
        Username: email.replace("@","_"),
        DesiredDeliveryMediums: ["EMAIL"],
        UserAttributes: [
          { Name: "email", Value: email}
        ] 
    };
    
    var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();
    await cognitoidentityserviceprovider.adminCreateUser(params, function(err, data) {
      if (err) console.log(err, err.stack); // an error occurred
      else {
        console.log(data);
        return "Success!";
     }
    }).promise();
};

```

Just to throw a spanner in the works, every so often - maybe one in twenty attempts - I don't get the error. It doesn't matter what email address is supplied, or whether I provide a specific username.

This is in an AWS Lambda function.

**Comment by ajredniwja** [comment]
Hey @DoctorWhich thank-you for reaching out to us with your issue, can you please confirm that you're using the latest version of the SDK? If not you can import the latest version of SDK by following  [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

**Comment by DoctorWhich** [comment]
Hi. Yes, I imported the latest version, and the problem still persists.

**Comment by DoctorWhich** [comment]
I managed to fix it by doing it like this: 
```
let error = false;
    let result = await cognitoidentityserviceprovider
    .adminCreateUser(params)
    .promise()
    .catch((err) => {console.log(err, err.stack); error = true;});
    
    if (!error) {
      console.log(result);
      return "Success";
    }
```
