### ISSUE TITLE
Put back relaxed version

### ISSUE THREAD

**Issue by daveisfera** [aws/aws-sdk-js#3072]
The relaxation of the dependencies (#2847) was reverted (#2988) because of a CI failure in a version of node that was EOLed over 3 years ago? That seems odd

**Comment by ajredniwja** [comment]
Hey @daveisfera, thank-you for reaching out to us.

The JS-SDK still supports the version of the node mentioned as we don't follow any deprecation policy. While it is debatable that whether the version that are EOLed should be supported or not, or if SDK should follow a certain deprecation policy. I would like to have your take on it, as more of the customers feedback we have more we can work towards it.

**Comment by daveisfera** [comment]
From my experience, the node/npm community tries to respect the release schedule of node itself and retires support for versions as they're EOLed, so I'd prefer that `aws-sdk-js` do the same. It allows the current version of the module to be kept simpler and more efficient in most cases.
Another way to think about it is mixing versions that are so separate by time. For example, is there really a reasonable use case for someone that is using a version of `node` that was EOLed 3.5+ years ago but that just absolutely has to have latest version of `aws-sdk-js`?

**Comment by ajredniwja** [comment]
Hey @daveisfera thank-you for your feedback, that maybe a great way to handle things from SDK side as well. The team is aware of it as well and I will convey your feedback to the team. I would also like to follow what node does, but would need team to decide on it. The V3 maybe able to have a different policy and not support so old version.  

Closing this issue now, please reach out if you have any additional questions.
