### ISSUE TITLE
Callbacks (and promises) not resolved if request.abort() is called too early.

### ISSUE THREAD

**Issue by kbkk** [aws/aws-sdk-js#3075]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Callbacks (and promises) not resolved if request.abort() is called too early.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
`v12.13.1`

**SDK version number**
v2.604.0, v2.606.0

**To Reproduce (observed behavior)**
```
const aws = require( 'aws-sdk' );

const wait = ms => new Promise( _ => setTimeout( _, ms ) );
const ORDER_PLACED_QUEUE_URL = 'http://localhost:4576/queue/warehouse-orders-order_placed-queue';

const sqs = new aws.SQS( {
	endpoint: 'http://localhost:4576',
	region: 'us-east-1'
} );

const orders = [];

let receiveMessageRequest;

( async function SqsConsumer() {
	while ( true ) {
		const params = {
			QueueUrl: ORDER_PLACED_QUEUE_URL,
			VisibilityTimeout: 3, // seconds
			WaitTimeSeconds: 5
		};

		receiveMessageRequest = sqs.receiveMessage( params );
		console.log( 'Request created' );
		try {
			console.log( 'Obtaining request promise' );
			const promise = receiveMessageRequest.promise();
			console.log( 'Request promise obtained' );
			const response = await promise;
			console.log( 'Request post-await' );
		} catch ( error ) {
			console.log( 'Request error' );
			console.error( error );
		}
		const messages = response.Messages;

		if ( !messages ) {
			console.log( 'No new messages, waiting...' );

			continue;
		}

		for ( const message of messages ) {
			const body = JSON.parse( message.Body );
			const order = body.Message;

			console.log( `Received order: "${ body.Message }"` );
			orders.push( body.Message );
		}

		const batchDeleteParams = {
			Entries: [],
			QueueUrl: ORDER_PLACED_QUEUE_URL
		};

		for ( const message of messages ) {
			batchDeleteParams.Entries.push( {
				Id: message.MessageId,
				ReceiptHandle: message.ReceiptHandle
			} );
		}

		sqs.deleteMessageBatch( batchDeleteParams ).promise();
	}
} )();

( async function shutdown() {
	if ( receiveMessageRequest ) {
		console.log( 'Aborting request' );
		receiveMessageRequest.abort();
	}
} )();

( async function keepProcessAlive() {
	// If you comment out this function the process will exit immediately
	while ( true ) {
		await wait( 1000 );
	}
} )();
```

**Expected behavior**
The promise should be immediately resolved with `RequestAbortedError: Request aborted by user`.

Output of above code is:
```
Request created
Obtaining request promise
Request promise obtained
Aborting request
<SqsConsumer loop hangs>
```

**Additional context**
This has caused me a lot of headache because my program just hang.

It works fine if you put the `shutdown` function body in a setTimeout() with 0ms delay (causes microtasks to resolve).

**Comment by ajredniwja** [comment]
Hey @kbkk thank-you for reaching out to us with your issue. For this particular case if the shutdown function works with ```setTimeout()``` with 0ms delay would mean that the SDK hangs in the node event loop. ```setTimeout(() => {receiveMessageRequest.abort()});``` should be the workaround. 

Related issue before commented by one of the maintainers: https://github.com/aws/aws-sdk-js/issues/133#issuecomment-20904317

**Comment by kbkk** [comment]
Yes, like you mentioned it's a *workaround*. So I assume the bug report label is correct, as this behavior is not mentioned in the docs.

**Comment by ajredniwja** [comment]
Marking it as a documentation issue.

**Comment by bsdahl** [comment]
I too have observed this issue.
