### ISSUE TITLE
Missing Typescript definitions for NodeHttpClient/HttpClient and Signers.

### ISSUE THREAD

**Issue by ankitch89** [aws/aws-sdk-js#3079]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Typescript definitions are missing for NodeHttpClient/HttpClient and Signers.

**Is the issue in the browser/Node.js?**
Node.js w/ Typescript

**If on Node.js, are you running this on AWS Lambda?**
NA

**Details of the browser/Node.js version**
Node v12.14.1

**SDK version number**
aws-sdk@2.610.0 

**To Reproduce (observed behavior)**
In Typescript:
import AWS = require('aws-sdk');
let client = AWS.NodeHttpClient() throws error.

**Expected behavior**
Typescript definitions should be present for these. The documentation for ElasticSearch suggests using these to make signed requests: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-node

**Comment by ajredniwja** [comment]
Hey @ankitch89 thank-you for reaching out to us with your issue. 

The correct way to use the constructor would be
 
```let client = AWS.NodeHttpClient(endpoint: Endpoint, region: string);```

 https://github.com/aws/aws-sdk-js/blob/fb9e50e7d74bea4c79ccf72e0f585235771943a5/lib/http_request.d.ts#L9

The typings are meant to match the publicly documented APIs of the SDK. The HttpRequest class shouldn't be instantiated directly, but is generated by the SDK and is a member of AWS.Request objects.

Closing this issue now please reach out if you have any additional questions.

**Comment by ankitch89** [comment]
@ajredniwja The code you have referenced above is for the HttpRequest class and not NodeHttpClient. There is no .d.ts file corresponding to AWS.NodeHttpClient or AWS.HttpClient or AWS.Signers which is what this issue is about.

Using AWS.HttpClient and AWS.Signers is recommended by the official documentation here 
 https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-node

**Comment by ajredniwja** [comment]
@ankitch89, apologies, I forgot to remove my first part of my comment, I was looking at httpRequest earlier but forgot to remove it from the final comment. Edited. 

Similar issue closed before #1729
