### ISSUE TITLE
Access denied QLDB when SourceIp is set. 

### ISSUE THREAD

**Issue by shushutochako** [aws/aws-sdk-js#3081]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I want to limit access to QLDB to a single IP address
However, when trying to StartTransaction from the aws-sdk-js, the error occurs.

**Error**
```
{ AccessDeniedException: User: arn:aws:iam::657973376774:user/qldb_nofilter_user_1 is not authorized to perform: qldb:SendCommand on resource: arn:aws:qldb:us-east-2:657973376774:ledger/vehicle-registration
・
・
・
  message:
   'User: arn:aws:iam::657973376774:user/qldb_nofilter_user_1 is not authorized to perform: qldb:SendCommand on resource: arn:aws:qldb:us-east-2:657973376774:ledger/vehicle-registration',
  code: 'AccessDeniedException',
  time: 2020-01-30T08:55:00.113Z,
  requestId: 'GzwyfTqG6Sv8meS4GpmuLW, GzwyfTqG6Sv8meS4GpmuLW',
  statusCode: 400,
  retryable: false,
  retryDelay: 17.69658028615979 }
```

**Code**
```

## main flow

const qldbsession = new AWS.QLDBSession();
const res1 = await startSession(qldbsession);
console.log("Success startSession");

const sessionToken: string = res1.StartSession.SessionToken;
const res2 = await startTransaction(qldbsession, sessionToken);

## functions

function startSession(session: AWS.QLDBSession) {
  return new Promise((resolve, reject) => {
    session.sendCommand({
      StartSession: {
        LedgerName: 'vehicle-registration'
      },
    }, function (err, data) {
      if (err) {
        console.log("Error on startSession");
        return reject(err);
      } else {
        return resolve(data);
      }
    });
  })
}

function startTransaction(session: AWS.QLDBSession, sessionToken: string) {
  return new Promise((resolve, reject) => {
    session.sendCommand({
      SessionToken: sessionToken,
      StartTransaction: {}
    }, function (err, data) {
      if (err) {
        console.log("Error on startTransaction");
        return reject(err);
      } else {
        return resolve(data);
      }
    });
  })
}
```

My iam policy settings are as follows.

**not works**
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "qldb:*",
            "Resource": "*",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": "{My Static IP Address}/32"
                }
            }
        }
    ]
}
```

**works correctly**
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "qldb:*",
            "Resource": "*"
        }
    ]
}
```

What is the cause?

## My environment

node.js: v10.15.3
amazon-qldb-driver-nodejs: 0.1.1-preview.2
aws-sdk: 2.610.0
ion-js: 3.1.2

**Comment by ajredniwja** [comment]
Hey @shushutochako, thank-you for reaching out to us with your issue. 

Your IAM policy with condition looks correct as I got something similar when I generated one using the console as well. Can you try passing your ip address in IPv6 format?

**Comment by shushutochako** [comment]
Hi @ajredniwja.

Thank you for your reply.
Unfortunately I do not have an ipv6 address.

SourceIp also supports ipv4, right?

**Comment by ajredniwja** [comment]
> Hi @ajredniwja.
> 
> Thank you for your reply.
> Unfortunately I do not have an ipv6 address.
> 
> SourceIp also supports ipv4, right?

It supports ipv4, but I wasnt able to reproduce the same, reached out to the service team as well, will update you once I have an update from them.

**Comment by ajredniwja** [comment]
Reached out to the service team, waiting for the response, will update once I get an update.

**Comment by ajredniwja** [comment]
Soft update, the service team recognizes this issue and is working on a fix.

**Comment by ajredniwja** [comment]
The issue was fixed, please reach out if you have any other questions.
