### ISSUE TITLE
proxy property of httpOptions for AWS.Config

### ISSUE THREAD

**Issue by franzwong** [aws/aws-sdk-js#3084]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

From the [SDK documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property) of AWS.Config, it says we can set the proxy property of httpOptions to proxy the request. On the other hand, there is another [SDK documentation](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html) saying we need to set the agent property.

I tried the first method but it doesn't work (There is XMLParserError if I set the proxy property). I would like to use the second method. However, proxy-agent doesn't support setting CA like [this](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-registering-certs.html).

I just want to know what is the proxy property used for.

**Comment by ajredniwja** [comment]
Hey @franzwong I am not sure if I understand your question. 

[Commit](https://github.com/aws/aws-sdk-js/commit/589d3b570e8cbf24976b7ce4606952be3363e2a0) adds the feature where you can add proxy to ```AWS.Config.httpOptions```. The second way you mentioned should also work but I am assuming that was added before the commit I mentioned. 

Can you please share your use case so I can try to help you better.

**Comment by franzwong** [comment]
@ajredniwja Thanks for the reply. Today I tried it again and got different errors. It looks like AWS proxy implementation doesn't support authentication. e.g. proxy path is "http://bob:password@proxy.com

**Comment by ajredniwja** [comment]
Can you please share your use case i.e code to reproduce and also the errors that you are getting?

**Comment by franzwong** [comment]
I am trying to send a S3 request from my machine which is behind a proxy. This proxy requires user name and password.

It is not a full example, but it should show what I am trying to do.

```
const proxyPath = `http://${userName}:${encodeURIComponent(password)}@${proxyDomain}`;

const certs = [
    fs.readFileSync(certPath),
];

AWS.config.update({
    httpOptions: {
        proxy: proxyPath,
        rejectedUnauthorized: true,
        ca: certs,
    }
});

const s3 = new AWS.S3();

async function main() {
    try {
        const buckets = await s3.listBuckets({}).promise(); // It complains Proxy Authentication is missing
    } catch (err) {
        console.error(err);
    }
}

main();
```

**Comment by ajredniwja** [comment]
can you try following the steps mentioned here. 

https://aws.amazon.com/blogs/developer/using-the-aws-sdk-for-javascript-from-behind-a-proxy/

**Comment by franzwong** [comment]
I tried that way and it solves the problem. However it means the proxy implementation provided by AWS SDK is not capable to handle authentication. Perhaps it can be a feature request.

**Comment by ajredniwja** [comment]
You'd need to have a proxy agent to pass to the ```agent``` in ```httpOptions to handle authentication. You can use any proxy agent it doesn't have to be specifically from node.

**Comment by franzwong** [comment]
I think I will create another feature request ticket to support authentication without using 3rd party library.
