### ISSUE TITLE
Unable to get referenced shared credential profile for china partition

### ISSUE THREAD

**Issue by awschristou** [aws/aws-sdk-js#3088]
**Describe the bug**

Using the AWS JS SDK v2, I'm trying to load and use shared credentials profiles for an account in the China partition. I'm unable to get credentials when there is a profile reference.

Sample Profiles in ~/.aws/credentials :

```
[cn]
aws_access_key_id = xxx
aws_secret_access_key = yyy
region = cn-northwest-1

[cn-assume]
role_arn = arn:aws-cn:iam::zzz:role/admin_assume
source_profile = cn
region = cn-northwest-1

[cn-mfa]
role_arn=arn:aws-cn:iam::zzz:role/admin_assume
mfa_serial = arn:aws-cn:iam::zzz:mfa/admin
source_profile = cn
region = cn-northwest-1
```

Sample code:

```javascript

    try {
        const profileName = 'xxx'
        const creds = new AWS.SharedIniFileCredentials({
            profile: profileName,
            tokenCodeFn: async (mfaSerial, callback) => await getMfaTokenFromUser(mfaSerial, profileName, callback)
        })

        await creds.getPromise()
    } catch (err) {
        getLogger().error(err as Error)
    }
```

Using the AWS CLI, I can use all three profiles successfully. With the sample code above, if I set `profileName` to `cn-assume` or `cn-mfa`, the getPromise call throws an Error:

```
code:"InvalidClientTokenId"
message:"The security token included in the request is invalid."
name:"InvalidClientTokenId"
```

Using the `cn` profile works successfully.

The program I'm using this in potentially switches profiles for accounts using different partitions (eg: 'aws' and 'aws-cn').

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
10.16.3

**SDK version number**
 aws-sdk@2.587.0

**Comment by ajredniwja** [comment]
@awschristou Thank-you for reaching out, its a known issue with the SDK, created a ticket for the team to have a look at it.
