### ISSUE TITLE
httpOptions.agent configuration is ignored

### ISSUE THREAD

**Issue by seifertd** [aws/aws-sdk-js#3089]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When configuring the SDK to use an HTTP proxy using the documented methods, the proxy configuration is bypassed and instead a direct connection is made to AWS API servers.

**Is the issue in the browser/Node.js?**
node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v10.16.3

**SDK version number**
v2.614.0

**To Reproduce (observed behavior)**
```
const proxy = require('proxy-agent')
const awsOptions = {
    accessKeyId: <REDACTED>,
    secretAccessKey: <REDACTED>,
    region: 'us-west-2',
    httpOptions: {
       agent: proxy("http://localhost:8080") // Note, no server is listening on port 8080 on localhost
    }
}
AWS.config.update(awsOptions)
const s3 = new AWS.S3({signatureVersion: 'v4'}),
const signedUrl = s3.getSignedUrl('getObject', {
      Bucket: <REDACTED>,
      Key: "uploads/" + key,
      Expires: 3600
});

signedUrl is returned directly from AWS service endpoint, bypassing proxy configuration.
```
**Expected behavior**
In the above example, with no service listening on port 8080 on localhost, the getSignedUrl call should attempt to pass the request through the proxy and return an error, not a valid signed S3 url.

**Screenshots**
N/A

**Additional context**
This was reported before and closed by the bot, thanks for looking: https://github.com/aws/aws-sdk-js/issues/2531

**Comment by ajredniwja** [comment]
Hey @seifertd thankyou for reaching out to us with your issue.

The ```getSignedUrl``` request that you make doesn't actually talks to any service but just creates a URL that can be used to reach a service. This is an expected behavior. 

Please reach out if you have any additional questions.
