### ISSUE TITLE
ListUsers AttributesToGet fails if user is missing an attribute

### ISSUE THREAD

**Issue by BrentonWatt** [aws/aws-sdk-js#3091]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When using cognitos listUsers API and making use of the AttributeToGet parameter, if one or more of the users in the returned list does not have one of the attributes requested, the call fails with the response that one or more of the attributes does not exist.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `AWS.VERSION` in your code where `AWS = require("aws-sdk");`

**Expected behavior**
When using this API I'd expect that when using the AttributesToGet parameter that if one of the users does not have an attribute the call should not fail.

**Comment by ajredniwja** [comment]
Hey @BrentonWatt thank-you for reaching out to us with your issue.

Can you please share the code that you are using and also the version of the SDK?

**Comment by BrentonWatt** [comment]
@ajredniwja Please see the code snippet below. In this scenario if everyone in the block of 10 has a custom:roles then the call will successfully return, however, if one person is missing this attribute the call fails. Our AWS SDK version is: 2.545.0

```
        const params = {
            AttributesToGet: ['name', 'family_name', 'phone_number', 'custom:roles',],
            Limit: 10,
            UserPoolId: process.env.COGNITO_POOL_ID,
            Filter: "username = \"" + username + "\"",
            PaginationToken: null
        };

        return cognito.listUsers(params).promise();
```

**Comment by ajredniwja** [comment]
Hey @BrentonWatt I was able to reproduce this behavior, however this is not potentially a bug with the SDK since it throws an error when a particular attribute is not present.

I will mark this as a feature request and let team work on it.

For the workaround which I believe you may have already implemented, you can pass null for ```AttributesToGet``` which will return all the attributes for a user and filter your required results from there. Please reach out if you'd need help with that.
