### ISSUE TITLE
DynamoDB PutItem consuming all heap memory

### ISSUE THREAD

**Issue by garyholiday13** [aws/aws-sdk-js#3092]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
DynamoDB PutItem has a memory leak and is consuming all heap memory

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.16.0

**SDK version number**
2.615.0

**To Reproduce (observed behavior)**
I have a csv file with 1.3 million lines. I can loop through the file just fine, however, when I try to call dynamodb putItem for every line, node runs out of heap memory after about 17k calls. My dynamodb table has over 500 write throughput. 

```
let insertIntoDynamoDB = async () => {
  const file = './file.csv';
  let index = 0;

  const readLine = createInterface({
    input: createReadStream(file),
    crlfDelay: Infinity
  });

  readLine.on('line', async (line) => {
    let record = parse(`${line}`, {
      delimiter: ',',
      skip_empty_lines: true,
      skip_lines_with_empty_values: false
    });

    await dynamodb.putItem({
      Item: {
        "Id": {
          S: record[0][2]
        },
        "newId": {
          S: record[0][0]
        }
      },
      TableName: "My-Table-Name"
    }).promise();

    index++;
    if (index % 1000 === 0) {
      console.log(index);
    }
  });
  // halts process until all lines have been processed
  await once(readLine, 'close');

  console.log('FINAL: ' + index);
}
```

**Expected behavior**
DynamoDB PutItem to not run out of heap memory

**Comment by ajredniwja** [comment]
Hey @garyholiday13 thank-you for reaching out to us with your issue. 

Can you please look at https://github.com/aws/aws-sdk-js/issues/1777#issuecomment-339398912, it seems to be a similar issue and the comment can explain what is happening.
