### ISSUE TITLE
Rejected promises dont contain useful stack traces

### ISSUE THREAD

**Issue by devshorts** [aws/aws-sdk-js#3093]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Modern javascript uses async await in conjunction with promises. The AWS sdk rejects promises in the aws request prototype via this block:

```
AWS.Request.addPromisesToClass = function addPromisesToClass(PromiseDependency) {
  this.prototype.promise = function promise() {
    var self = this;
    // append to user agent
    this.httpRequest.appendToUserAgent('promise');
    return new PromiseDependency(function(resolve, reject) {
      self.on('complete', function(resp) {
        if (resp.error) {
          reject(resp.error);
        } else {
          // define $response property so that it is not enumberable
          // this prevents circular reference errors when stringifying the JSON object
          resolve(Object.defineProperty(
            resp.data || {},
            '$response',
            {value: resp}
          ));
        }
      });
      self.runTo();
    });
  };
};
```
But because the promise is rejected using an event emitter and not async await the root stack trace is totally lost.

A really simple tweak would be to capture the stack at the _call site_ by capturing an instance of an error object and then throwing a new error with the original errors stack.

Otherwise the stacks are totally useless and free-floating.

I am using the default node native promise library 

**Is the issue in the browser/Node.js?**
Node.js

**SDK version number**
2.539.0

**Comment by ajredniwja** [comment]
Hey @devshorts thank-you for reaching out to us with your issue.

Marking this as a feature request and work or have team work on it as time permits. 

Please feel free to open a PR for the team to review if you'd like to work on it.

**Comment by kasvtv** [comment]
I would like to emphasize the importance of having this fixed. Pretty much any modern JavaScript app that uses the aws-sdk will be doing so in nearly all cases by:
```js
await someServiceObject.someMethod(params).promise()
```

If for any reason the call fails, **there will never be a stack trace back to the line where the method was called**. This heavily increases the amount of time it takes to debug and is in my entire team's opinion the number one pain point of the aws-sdk.

**Comment by cmawhorter** [comment]
this is a [**very.**](https://github.com/aws/aws-sdk-js/issues/307) [old.](https://github.com/aws/aws-sdk-js/issues/385) issue. that has nothing to do with promises and the aws sdk js team just refuses to address it for some unknown reason.

here i am today... sprinkling "console.log(1) ... 2 ... 3" through my code -- like i'm developing for IE6 -- because yet again, aws-sdk is spitting out a useless stack.

on my long list of things i hate about aws-sdk. this is on top by a large margin. a very large margin.

**Comment by ajredniwja** [comment]
This has changed in the JS-SDK-V3 which is modularized and provides much better stack trace.
Please check it at https://github.com/aws/aws-sdk-js-v3
