### ISSUE TITLE
Download of image from S3 bucket in Chrome has incorrect md5-hash. Does not happen with Safari.

### ISSUE THREAD

**Issue by Paperone80** [aws/aws-sdk-js#3094]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Download of image from S3 bucket in Chrome has different md5-hash than Safari.

**Is the issue in the browser/Node.js?**
Browser

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
  Browsers:
    Chrome: 80.0.3987.100
    Firefox: 72.0.2
    Safari: 13.0.5

**SDK version number**
Example: v2.611.0

**To Reproduce (observed behavior)**
1. Uploaded 100 images via AWS console (each image between 5MB -25MB)
2. Download image into browser and run md5
3. Different md5 hashes between Safari and Chrome
4. Safari is correct as validated with local and S3 md5 hash
5. Under Chrome, it seems the bits are altered when downloading from S3.

**Expected behavior**
- md5 hash consistent at least from S3 bucket downloaded into Chrome browser

**Screenshots**
n/a

**Additional context**
Using:
```
s3.getObject(
    {Bucket: "my-bucket", Key: item.Key}, 
    function (err, file) {
         console.log(file);
         console.log("data:image/jpeg;base64," + encodeToB64(file.Body)); }
);

```

Probably a Chrome issue but hopefully there is a workaround. Thanks.

**Comment by ajredniwja** [comment]
Hey @Paperone80 thank-you for reaching out to can you share some more information on how did you calculate the md5-hash. 

Might be helpful https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/
