### ISSUE TITLE
TypeError: Cannot redefine property prevents use of valid profiles

### ISSUE THREAD

**Issue by awschristou** [aws/aws-sdk-js#3098]
**Describe the bug**

A scenario is outlined in https://github.com/aws/aws-toolkit-vscode/issues/934 where improperly configured shared credentials files can prevent programmatic use/access of *any* profile.

To reproduce:

In ~/.aws/credentials

```
[default]
aws_access_key_id = something valid
aws_secret_access_key = something valid

```

In ~/.aws/config

```
[hello]
role_arn=something valid
source_profile=default

[profile hello]
region = us-west-2
```

In code:
```typescript

                process.env.AWS_SDK_LOAD_CONFIG = 'true'
                const c = new AWS.SharedIniFileCredentials({
                    profile: 'default'
                })

```

Calling the SharedIniFileCredentials constructor will cause an Error "TypeError: Cannot redefine property: hello" even when you try to use a profile with valid configuration.

The existence of an improperly configured profile should not prevent an application from using properly configured profiles.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
`node -v` -- 10.16.3

**SDK version number**
  * running command `npm list aws-sdk` from your root directory
2.587.0

**Comment by justinmk3** [comment]
still an issue

**Comment by huyphan** [comment]
This is still an issue with the latest release of SDK v2 (version `2.1417.0`).
