### ISSUE TITLE
Generating incorrect pre-signed url

### ISSUE THREAD

**Issue by srasthapuram9621** [aws/aws-sdk-js#3099]
Trying to generate presigned url using typescript  and running as api in ECS Cluster. The pre-signed 
 URL generated is "https://s3.amazonaws.com/". 

Example:
const preSignUrl: string = s3Client.getSignedUrl("getObject", parameters);

**Comment by ajredniwja** [comment]
Hey @srasthapuram9621 thank-you for reaching out to us with your issue.

Can you please check if your credentials are set in your config file? 
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

Or you can update it in your code using something like mentioned [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property).

Please reach out if you have additional questions.
