### ISSUE TITLE
IoT Lambda Rule Action not create lambda trigger

### ISSUE THREAD

**Issue by h3w8529** [aws/aws-sdk-js#3100]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Hi, I facing some issue when use aws-sdk(new AWS.Iot({ apiVersion: '2015-05-28' })) to trigger the API **createTopicRule** and want the mqtt payload to trigger lambda, but I found that when I use the SDK to create the rule, is not tigger when the mqtt payload is published.  

I only able to receive the payload by manually create on the aws console.

**Comment by ajredniwja** [comment]
Hey @h3w8529, thankyou for reaching out to us with your issue.

Can you please share minimal code to reproduce the behavior? 

Also can you check what version of the SDK you are using?
