### ISSUE TITLE
new EC2().describeVpcs() is throwing error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by iAbhishek91** [aws/aws-sdk-js#3101]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

new EC2().describeVpcs() is failing with error Cannot read property '0' of undefined. 

Verison: "aws-sdk": "^2.610.0",

```js
const describeVpcsParam = {
  Filters: [{
    Name: 'state',
    Values: ['available'],
  }],
};

// the below line is wrapped inside an async function.
const securityGrpsDesc = await ec2.describeVpcs(describeVpcsParam).promise();
```

I have tried many different combinations of filters, it end-up in same error. Please help

**Comment by ajredniwja** [comment]
Hi @iAbhishek91 thankyou for reaching out to us with your issue.

Can you please share the minimum code to reproduce this behavior?
