### ISSUE TITLE
How to list objects in a date range?

### ISSUE THREAD

**Issue by slim-hmidi** [aws/aws-sdk-js#3102]
Confirm by changing [ ] to [x] below:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I'm looking to list all the objects stored in S3 bucket between two dates using aws s3 javascript sdk. According to [ListObjects ](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects) there is no parameter allowing to do that except a prefixor delimiter but in my case they are useless. 
Is there any solution to do that or I have to get the returned data then filter them according to LastModified?

**Comment by ajredniwja** [comment]
@slim-hmidi Thank-you for reaching out to us with your issue.

You are right, unfortunately we currently don't have any params to specify a range. 
You can use the LastModified object returned from the list objects and write a customized function. 
Please reach out if you need help writing that.

**Comment by slim-hmidi** [comment]
Thanks for your answer. I did it manually.
Is there any intention to add a parameter or new api for that in the next version or there is no use case for that?

**Comment by ajredniwja** [comment]
The support for an additional param has to come from the service side, so I can open a ticket with them, but due to lack of requests for this particular feature  it might sit at the backlog for a while.

**Comment by phdunham** [comment]
Interesting #3103 was opened as a feature request for this issue, but then it was closed as a duplicate.
I am adding my +1 to this request. Looping through all of the filenames and then filtering by date is very slow for large buckets. We use S3 for access logs and the number of files is huge after only 3 days.

**Comment by pontusvision** [comment]
Can we please re-open this issue?  I'll need this feature soon!

**Comment by montoyadamien** [comment]
Yes please, this feature could help us to improve performances. Thanks.

**Comment by rbrt** [comment]
We would also really like to have this feature!

**Comment by rufinoNL** [comment]
Yes please!

**Comment by PositiveControl** [comment]
Last modified isn't very useful for us to filter by, as it doesn't always match the upload+storage date.

Ability to filter by date range would be very useful.

**Comment by alexandr2110pro** [comment]
+1 Very much needed. How can we otherwise process files uploaded since the previous batch processing date without moving files around?

**Comment by vini-delascio-fmg** [comment]
Yes, this would be very helpful for us as well.

**Comment by gonzalovilaseca** [comment]
+1

**Comment by khanhnguyendev** [comment]
+1

**Comment by kellertk** [comment]
Hello, this is not something that's supported by the S3 API, and we are unable to implement the functionality in the JavaScript SDK. You can instead try a `HeadObject` request with an `If-Modified-Since` conditional.
