### ISSUE TITLE
Random network errors when calling dynamoDB

### ISSUE THREAD

**Issue by yorah** [aws/aws-sdk-js#3107]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
We are encountering random, very rare (~0.0001% of the calls) network errors when calling DynamoDB from a nodeJS lambda. We are using the latest version of the aws-sdk. We opened a business support case on our AWS account, and they recommended that we open an issue here.

The errors we get are:
- {"message":"write ECONNRESET","errno":"ECONNRESET","code":"NetworkingError","syscall":"write","region":"eu-west-3","hostname":"dynamodb.eu-west-3.amazonaws.com","retryable":true,"time":"2020-02-11T14:07:00.761Z"}
- {"message":"socket hang up","code":"NetworkingError","region":"eu-west-3","hostname":"dynamodb.eu-west-3.amazonaws.com","retryable":true,"time":"2020-02-11T10:58:12.461Z"}
- "error":{"message":"write EPIPE","errno":"EPIPE","code":"NetworkingError","syscall":"write","region":"eu-west-3","hostname":"dynamodb.eu-west-3.amazonaws.com","retryable":true,"time":"2020-02-11T10:59:46.447Z"}
- "error":{"message":"write ETIMEDOUT","errno":"ETIMEDOUT","code":"NetworkingError","syscall":"write","region":"eu-west-3","hostname":"dynamodb.eu-west-3.amazonaws.com","retryable":true,"time":"2020-02-11T15:33:21.007Z"}
- "error":{"message":"Connection timed out after 2000ms","code":"TimeoutError","time":"2020-02-11T15:51:22.954Z","region":"eu-west-3","hostname":"dynamodb.eu-west-3.amazonaws.com","retryable":true}

One important thing we discovered:
- with AWS_NODEJS_CONNECTION_REUSE_ENABLED set to 1, we get those errors at random intervals (sometimes grouped together, sometimes not)
- with AWS_NODEJS_CONNECTION_REUSE_ENABLED set to 0, we get absolutely 0 errors
We tested for several days with both setup.

This env variable is the one described in the official documentation: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html

Also, we have a lot of concurrent instances of the same lambda executing, and the issue does not happen for all instances. It is as if some instance are losing connection to DynamoDB, and they can't manage to restore the connectivity. We have the following retry/timeout configuration, but changing it doesn't improve the situation:
```
AWS.config.update({
  maxRetries: 2,
  httpOptions: {
    timeout: 2000,
    connectTimeout: 1000
  }
});
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
Runtime nodejs12.x on AWS Lambda

**SDK version number**
We tested several version, actually using 2.616.0

**To Reproduce (observed behavior)**
Very hard to provide a reproducible scenario, as it happens at an extremely low rate. AWS Business Support (DynamoDB team) told us it doesn't seem related to DynamoDB outages (no latency > 1s).
The erratic behavior seem however linked to the keepalive env variable (setting it to 0 removes any occurence of the error).

**Expected behavior**
No errors. We can get this behavior by having the AWS_NODEJS_CONNECTION_REUSE_ENABLED  set to 0, however it means we are losing some performance due to not using the keepalive on the socket connections.

**Additional context**
In the concerned lambdas, we are also publishing messages to SQS, and invoking other lambdas. However, calling these services has never shown any network errors so far. However, this may also be because we are making more DynamoDB calls when compared to the SQS/Lambda invoke calls.

We are looking for advices on how we can help pinpoint the exact issue.

**Comment by AllanFly120** [comment]
Hi @yorah Thank you for the detailed description. Given I don't have more solid evidence, I can only provide my speculation. 

I'm wondering whether it's the `agent.timeout` config that's killing the connection. A socket is kept alive until the `timeout` arrives, and it will break a request. According to your config 1% request will fail because of the timeout, since each request will make another 2 retries, we will see 1% ^ 3 = 0.0001% error rate. This is just my theory. You can validate it by examining whether you see fewer errors if you set timeout to hours OR remove the timeout and set `maxSockets` instead of you are concern about the resource usage.

**Comment by ajredniwja** [comment]
Closing this issue due to lack of inactivity, please reach out if you still have questions.
