### ISSUE TITLE
SNS publish not accepting standard MessageAttributes

### ISSUE THREAD

**Issue by rodmaz** [aws/aws-sdk-js#3110]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Standard message attributes such as `AWS.SNS.SMS.SenderId` and `AWS.SNS.SMS.SMSType` are not being accepted in `publish` method of SNS.
The SDK logs the following error:
`Message attribute names starting with 'AWS.' or 'Amazon.' are reserved for use by Amazon.`

The following snipped is being used to reproduce the problem.

```nodejs
  const params = {
    PhoneNumber: cellphone,
    Message: 'Hello there!',
    MessageAttributes: {
      'AWS.SNS.SMS.SenderId': { DataType: 'String', StringValue: 'Test' },
      'AWS.SNS.SMS.SMSType': { DataType: 'String', StringValue: 'Promotional' },
    },
  };
  try {
    const result = await snsInstance.publish(params).promise();
    const { messageId } = result;
    console.info({ notice: `SMS to (${cellphone}) sent successfully; messageId: ${messageId}` });
    return messageId;
  } catch (snsErr) {
    console.error({
      notice: `an error occurred while sending SMS to ${cellphone}`,
      error: snsErr.message,
    });
    return snsErr;
  }
```

**Is the issue in the browser/Node.js?**
Node.js (v12.13.1)

**If on Node.js, are you running this on AWS Lambda?**
Yes. SAM w/ lambdas.

**Details of the browser/Node.js version**
Node.js (v12.13.1)

**SDK version number**
v2.624.0

**Comment by ajredniwja** [comment]
Hey @rodmaz thank-you for reaching out to us with your issue.

The SNS Message Attributes documentation found [here](https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html#idSNSMessageAttributesNTV) state that the name cannot start with "AWS." or "Amazon." It also provides various validation that you should take care about during the naming process. 

Please reach out if you have any additional questions.

**Comment by srounce** [comment]
@ajredniwja 
AWS's own documentation specifies this:
https://docs.aws.amazon.com/sns/latest/dg/sms_publish-to-phone.html#sms_publish_sdk

Amazon's own example code for other SDKs uses these attributes: https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/dotnet/example_code/SNS/SNSSample1/SNSSample1/Program.cs

In fact this aws-cli invocation:
```bash
aws sns publish \
  --phone-number <phone number> \
  --message 'Hello Recipient :)' \
  --message-attributes '{ "AWS.SNS.SMS.SenderID" : { "DataType": "String", "StringValue": "SENDERID" } }'
```

**Comment by rodmaz** [comment]
@ajredniwja As @srounce commented above (good job!), AWS documentation shows these exact same keys are completely valid and acceptable in the examples.
Right now in order to bypass the error, I am using for keys `SNS.SMS.SenderId` and `SNS.SMS.SMSType`, which I assume are wrong and get completely ignored.

**Comment by srounce** [comment]
> Right now in order to bypass the error, I am using for keys SNS.SMS.SenderId and SNS.SMS.SMSType, which I assume are wrong and get completely ignored.

Yeah, I've many variations of these and they don't get picked up at all unless they're the `AWS.*` form specified in the docs (which cause the JS SDK to throw the aforementioned error).

**Comment by ErezShahaf** [comment]
Hello, I am experiencing the same issue when trying to assign a senderID. Any solutions?

**Comment by srounce** [comment]
Please check the capitalization of the properties, `AWS.SNS.SMS.SenderID` must have capital S on 'Sender' also, I & D of 'ID' must also be caps.

**Comment by ajredniwja** [comment]
Still a persisting issue?
