### ISSUE TITLE
Uncaught Error: DelayedStream#maxDataSize of 2097152 bytes exceeded.

### ISSUE THREAD

**Issue by kaykhan** [aws/aws-sdk-js#3111]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I'm trying to fire and forget an upload request to s3. However i get the following error:

>   Uncaught Error: DelayedStream#maxDataSize of 2097152 bytes exceeded.
>       at FormData.CombinedStream._checkDataSize (node_modules/combined-stream/lib/combined_stream.js:166:19)
>       at Readable.EventEmitter.emit (domain.js:476:20)
>       at Readable.source.emit (node_modules/delayed-stream/lib/delayed_stream.js:30:21)
>       at Readable.read (_stream_readable.js:520:10)
>       at ManagedUpload.fillStream (node_modules/aws-sdk/lib/s3/managed_upload.js:422:25)
>       at Readable.<anonymous> (node_modules/aws-sdk/lib/s3/managed_upload.js:188:44)
>       at Readable.EventEmitter.emit (domain.js:476:20)
>       at Readable.source.emit (node_modules/delayed-stream/lib/delayed_stream.js:30:21)
>       at emitReadable_ (_stream_readable.js:570:12)
>       at processTicksAndRejections (internal/process/task_queues.js:77:11
> 

**Controller**

``` 
console.log(image)
this.storageModule.upload(`${requestId}-${type}.jpg`, image)
```

> Readable {
>   _readableState: ReadableState {
>     objectMode: false,
>     highWaterMark: 16384,
>     buffer: BufferList { head: null, tail: null, length: 0 },
>     length: 0,
>     pipes: null,
>     pipesCount: 0,
>     flowing: null,
>     ended: false,
>     endEmitted: false,
>     reading: false,
>     sync: true,
>     needReadable: false,
>     emittedReadable: false,
>     readableListening: false,
>     resumeScheduled: false,
>     paused: true,
>     emitClose: true,
>     autoDestroy: false,
>     destroyed: false,
>     defaultEncoding: 'utf8',
>     awaitDrain: 0,
>     readingMore: false,
>     decoder: null,
>     encoding: null
>   },
>   readable: true,
>   _read: [Function: read],
>   _events: [Object: null prototype] {},
>   _eventsCount: 0,
>   _maxListeners: undefined
> }

**StorageModule**
```
import Config from "../../config/config";
import S3 from "aws-sdk/clients/s3";

class StorageModule {

    public config: Config;
    public s3: S3;
    public bucket: string;

    constructor() {
           this.config = new Config();

            const credentials: S3.ClientConfiguration = {
                accessKeyId: this.config.aws.AWS_S3_ACCESS_KEY_ID,
                secretAccessKey: this.config.aws.AWS_S3_SECRET_ACCESS_KEY,
                region: this.config.aws.AWS_S3_REGION,
            };

            this.s3 = new S3(credentials);
            this.bucket = "<removed>";
    }

    public upload = (key, body) => {

        const params = {
            Bucket: this.bucket,
            Key: key,
            Body: body
        }


        return this.s3.upload(params).promise();

    }

}

export default StorageModule;
```

The above fails however the below test passes.

```
import StorageModule from "./storage.module";
import fs from "fs";
import { expect } from "chai";

describe("StorageModule", () => {

    it("should upload file to s3", async () => {

        const storageModule = new StorageModule();

        const stream = await fs.createReadStream(process.cwd() + "/test/resources/" + "id/front.jpg");

        const key = "test/productId/sessionId/requestId-front.jpg"

        const response = await storageModule.upload(key, stream);

        expect(response.Location).to.equal(`${url}/${key}`)
    });
});
```

It seems like this error occurs when i make a http call via axios to another service directly after initiating an upload() request to s3.

**Comment by kaykhan** [comment]
It seems like this error occurs when i make a http call via axios to another service directly after initiating an upload() request to s3.

**Comment by ajredniwja** [comment]
Hey @kaykhan, apologies for the delayed response here, I was not able to reproduce this, due you still see the error with the latest version of the SDK and NODE?
