### ISSUE TITLE
 LocaleValue must be null when used with the EqualTo comparator

### ISSUE THREAD

**Issue by holtc** [aws/aws-sdk-js#3116]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The documentation says I can use the `In` or `EqualsTo` operator with `LocaleValues`, but I get the following error when creating a HIT type: 
```
Error [ParameterValidationError]: The value "US,CA" is not valid for the parameter LocaleValue. LocaleValue must be null when used with the EqualTo comparator
```

Here is the text copied and pasted from the docs [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/MTurk.html#createHITType-property):

```
The kind of comparison to make against a Qualification's value. You can compare a Qualification's value to an IntegerValue to see if it is LessThan, LessThanOrEqualTo, GreaterThan, GreaterThanOrEqualTo, EqualTo, or NotEqualTo the IntegerValue. You can compare it to a LocaleValue to see if it is EqualTo, or NotEqualTo the LocaleValue. You can check to see if the value is In or NotIn a set of IntegerValue or LocaleValue values. Lastly, a Qualification requirement can also test if a Qualification Exists or DoesNotExist in the user's profile, regardless of its value.
```

I checked https://github.com/aws/aws-sdk-js/issues/3008, and it has nothing to do with single vs. double quotes. I also tried using `QualificationTypeId: '00000000000000000071'` as suggested in the link on that issue, also to no avail.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.10.0

**SDK version number**
aws-sdk@2.625.0

**To Reproduce (observed behavior)**
```
const params = {
  AssignmentDurationInSeconds: 60,
  Description: 'Pick which type of room is in the photo.',
  Reward: '1.00',
  Title: 'Which room is this?',
  AutoApprovalDelayInSeconds: 0,
  Keywords: 'home,image tagging,house,image,tagging',
  QualificationRequirements: [
    {
      Comparator: 'EqualTo',
      QualificationTypeId: '3FWSYHGAEIT5EXX57Y8PV0YXJLTR7L',
      ActionsGuarded: 'DiscoverPreviewAndAccept',
      LocaleValues: [
        {
          Country: 'US'
        },
        {
          Country: 'CA'
        }
      ]
    }
  ]
}
mTurkClient.createHitType(params, (err, data) => {
  if (err) throw err

  console.log(data)
})
```

**Expected behavior**
I expect that an error will not be thrown because the documentation says I should be able to use the `EqualTo` operator with `LocaleValues`

**Comment by ajredniwja** [comment]
Hey @holtc thank-you for reaching out with your issue.

The code looks fine to me, reaching out to the service to have some more inputs on the issue, will update here once I hear back from them.

**Comment by ajredniwja** [comment]
Hey @holtc confirmed with the service team that you can not use multiple local values when using the EqualTo comparator. If the use case is to have multiple locale values then you can use the comparator 'In'. 

I have asked them to mention this in their docs to avoid confusion. 

Please reach out if you have any more questions.

**Comment by holtc** [comment]
@ajredniwja I have also tried with the `In` operator and was receiving the same error, but swap out the `EqualTo` in the error message with `In`

**Comment by ajredniwja** [comment]
@holtc please reach out if you have additional questions, closing this issue now.
