### ISSUE TITLE
The typings for AWS.config.retryDelayOptions.customBackoff appear to be wrong.

### ISSUE THREAD

**Issue by caruso-billfire** [aws/aws-sdk-js#3117]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

The typings for AWS.config.retryDelayOptions.customBackoff appear to be wrong.

For typing err, it is using Error not AWSError
When you look at the test for the file the author uses err.code
.code doens't exist on Error but it does on AWSError.

Types:
https://github.com/aws/aws-sdk-js/blob/534033a2edb638252d0030f27b9d6297283aa507/lib/config.d.ts#L149

Test in question: 
https://github.com/aws/aws-sdk-js/blob/1ca7b9894d72b01425852c079cb47e378e206886/test/services/dynamodb.spec.js#L73

**Comment by jgehrcke** [comment]
Also see https://github.com/aws/aws-sdk-js/issues/2611
