### ISSUE TITLE
Documentation says `CredentialProviderChain` extends `Credentials`, TypeScript file disagrees

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-sdk-js#3122]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

I have an extension to the bug that I reported 1.5 years ago here: https://github.com/aws/aws-sdk-js/issues/2235

Apparently the resolution to that was removing the `extends Credentials` from the `.d.ts` file, but the docs still proudly claim that `CredentialProviderChain` inherits from `Credentials`:

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html

https://github.com/aws/aws-sdk-js/blob/f5a34820a3aec353a6869414f3e5319fafa8a4af/lib/credentials/credential_provider_chain.d.ts#L3

![image](https://user-images.githubusercontent.com/524162/75560563-b25e7700-5a45-11ea-8fc3-8e6fb5eed04c.png)

**Comment by dougmoscrop** [comment]
Hmm.. still technically extends Credentials: https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/credential_provider_chain.js#L45

I don't understand why this needs to be more complicated than just adding:

```js
refresh: function (callback) {
    var self = this;
    self.resolve(function (err, creds) {
      if (err) {
        callback(err);
      } else {
        AWS.Credentials.call(self, creds);
        callback();
      }
    });
  },
```

To credential_provider_chain.js
