### ISSUE TITLE
Node Upload file to S3 error InvalidArgument: null

### ISSUE THREAD

**Issue by afamorim** [aws/aws-sdk-js#3125]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I have this error with aws-sdk library and I didn't found the reason.

I have tried any possibilities for many days but without success and no clue of what's happen It's a Status code 400 but I have checked for many examples in web and everything is fine to me.

Here is the code
```
var AWS = require('aws-sdk');
AWS.config.update({ region: 'nyc3' });

var uuid = require('node-uuid');
var fs = require('fs');

// Create an S3 client
var s3 = new AWS.S3({
  apiVersion: '2006-03-01',
  secretAccessKey: '*****',
  accessKeyId: '*****',
  endpoint: 'https://nyc3.digitaloceanspaces.com',
  region: 'nyc3'
});

AWS.config.region = 'nyc3';

const fileName = 'hello_world.txt';

// Create a bucket and upload something into it
var bucketName = 'my-bucket';
var keyName = fileName;

fs.readFile(fileName, (err, data) => {
  if (err) throw err;
  var params = {
    ACL: 'private',
    Bucket: bucketName,
    Key: keyName,
    Body: JSON.stringify(data, null, 2),
    ContentLength: data.length
  };
  s3.putObject(params, function(err, data) {
    if (err) console.log(err);
    else
      console.log(
        'Successfully uploaded data to ' + bucketName + '/' + keyName
      );
  });

  // s3.upload(params, function(s3Err, data) {
  //   if (s3Err) console.log(s3Err);
  //   else console.log(`File uploaded successfully at ${data.Location}`);
  // });
});
```

You can see that I have tried with the putObject and upload methods and have the same error in both of them

`{ InvalidArgument: null
    at Request.extractError (/home/antonio/desenvolvimento/projetos/aws-nodejs-sample/node_modules/aws-sdk/lib/services/s3.js:816:35)
    at Request.callListeners (/home/antonio/desenvolvimento/projetos/aws-nodejs-sample/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/antonio/desenvolvimento/projetos/aws-nodejs-sample/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/antonio/desenvolvimento/projetos/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/antonio/desenvolvimento/projetos/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/antonio/desenvolvimento/projetos/aws-nodejs-sample/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/antonio/desenvolvimento/projetos/aws-nodejs-sample/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/antonio/desenvolvimento/projetos/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/antonio/desenvolvimento/projetos/aws-nodejs-sample/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/antonio/desenvolvimento/projetos/aws-nodejs-sample/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: null,
  code: 'InvalidArgument',
  region: null,
  time: 2020-02-28T03:20:24.289Z,
  requestId: 'tx00000000000016f648fab-005e5886f8-3359f-nyc3b',
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 38.29641987933954 }`

I don't have any more idea of what I can do to fix this. Any one can help?

Here the link of the question in stakoverflow: https://stackoverflow.com/questions/60444970/node-upload-file-to-s3-error-invalidargument-null

**Comment by ajredniwja** [comment]
Hey @afamorim thank-you for reaching out to us with you issue, I used the exact code snippet with some small changes:

```
var AWS = require('aws-sdk');
var fs = require('fs');

// Create an S3 client
var s3 = new AWS.S3({
    region: 'us-west-2'
});


const fileName = 'path to file.txt';

var bucketName = 'bucket_Name';
var keyName = "file2.txt";

fs.readFile(fileName, (err, data) => {
    if (err) throw err;
    var params = {
        ACL: 'private',
        Bucket: bucketName,
        Key: keyName,
        Body: JSON.stringify(data.toString(), null, 2),
        // ContentLength: data.length
    };

    s3.putObject(params, function(err, data) {
        if (err) console.log(err);
        else
            console.log(
                'Successfully uploaded data to ' + bucketName + '/' + keyName
            );
    });

    // s3.upload(params, function(s3Err, data) {
    //   if (s3Err) console.log(s3Err);
    //   else console.log(`File uploaded successfully at ${data.Location}`);
    // });
});

```

**Comment by ajredniwja** [comment]
I wasn't able to get similar errors, also I was not able to understand the reason you updating the region multiple times and I believe ```nyc3``` is not a valid region according to https://docs.aws.amazon.com/general/latest/gr/s3.html

Can you try running the above code snippet with correct variable values.

**Comment by afamorim** [comment]
Hi @ajredniwja ,
This regions is from digital ocean spaces service.
When I try your code I have this error log
`Error: connect EHOSTUNREACH 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
  message: 'Missing credentials in config',
  errno: 'EHOSTUNREACH',
  code: 'CredentialsError',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2020-03-10T03:13:04.867Z,
  originalError: {
    message: 'Could not load credentials from any providers',
    errno: 'EHOSTUNREACH',
    code: 'CredentialsError',
    syscall: 'connect',
    address: '169.254.169.254',
    port: 80,
    time: 2020-03-10T03:13:04.867Z,
    originalError: {
      message: 'EC2 Metadata roleName request returned error',
      errno: 'EHOSTUNREACH',
      code: 'EHOSTUNREACH',
      syscall: 'connect',
      address: '169.254.169.254',
      port: 80,
      time: 2020-03-10T03:13:04.866Z,
      originalError: [Object]
    }
  }
}`
In this same space I can save files with the aws java sdk

Let me ask you a question.
- with this log error can you say to me what is the IvalidArgument?

**Comment by ajredniwja** [comment]
The error I suspect is because you don't have credentials configured, the error in your initial report was because of the region, while now it doesn't have credentials at all, you can try to configure credentials using the CLI https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html.
You may also want to test it using the region that is available by S3 https://docs.aws.amazon.com/general/latest/gr/rande.html.

Please reach out if that doesn't solve the problem.

**Comment by afamorim** [comment]
Hi @ajredniwja ,

I have resolved the problem, Thanks for your help.
This is what I have changed in my code
the endponit https://nyc3.digitaloceanspaces.com/ with "/" in the end
I changed my key with a folder in my space and and take out the first "/" and the variable stay like 'systems/thesearch/photos/test.jpg'

I have tried this way because I have programmed another system in java and take a simillary mistake.

Thanks again for all help
