### ISSUE TITLE
using boto3, can we specify 'number of copies to be created ' while adding object in to S3 Bucket , like a custom header 'x-copy-count:50' and try to upload the object which creates 50 copies of the object.

### ISSUE THREAD

**Issue by YathirajVani** [aws/aws-sdk-js#3129]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @YathirajVani apologies for delayed response here, seems like a boto3 feature requests, I can forward it to them, or you can open a new request at: 
https://github.com/boto/boto3

**Comment by YathirajVani** [comment]
Yeah please forward the request to concerned team, Thanks
