### ISSUE TITLE
Uncatchable and rethrowable error in request.js (ECONNREFUSED) - reposted

### ISSUE THREAD

**Issue by sjmittal** [aws/aws-sdk-js#3130]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
This is related to:
https://github.com/aws/aws-sdk-js/issues/1010
However since that is closed I am opening new issue.

As mentioned I am able to handle `ECONNREFUSED` using

```
var s3Stream = s3.getObject({/*params*/}).createReadStream();
s3Stream.on('error', function(err) {
  console.log(err); // Prints the ECONNREFUSED error
  //but how do I rethrow it so that the application calling it is able to catch it
  //note throw err is again not caught
});
```
Is there any way we can actually catch `ECONNREFUSED` and rethrow some error.
So adding on error callback simply does not allow me to return any value or throw any error when the above block is wrapped inside a function. 
eg:
```
const handler = async (event, options) => {
  .....
  const s3 = new aws.S3(/* s3 options */);
  ....
  try {
    // Read the file
    const stream = await s3.getObject(/*params*/).createReadStream();
    stream .on('error', err => {
        .......
       //unable to rethrow it
    });
    ......
    const /* processed data */ = await collectData(stream, ....);
    .....
    await s3.putObject(/*object params*/).promise();

    return { /*return object*/ };
  } catch (e) {
    .....
    throw e;
  }
}
```

So when I call `handler` from my application it neither returns any value nor any surrounding try/catch block is invoked. It seems to just get stuck.

**Comment by trivikr** [comment]
s3.createReadStream API reference https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#createReadStream-property

**Comment by sjmittal** [comment]
@trivikr The read stream is created exacatly as suggest. It just looks like the on error event when handled does not allow that error to be re-thrown.
It gets caught at application level as uncaught exception, but never in the surrounding try/catch block, and hence is not notified to the immediate caller.

Anyway we can catch such exceptions?
