### ISSUE TITLE
Paginated version of S3.listObjectsV2

### ISSUE THREAD

**Issue by julien-c** [aws/aws-sdk-js#3131]
I see references to a Paginator in the code but haven't found any doc on how to use it.

My use case is I want to list all objects from my S3 bucket (which has more than 1_000 keys)

Thank you!

**Comment by julien-c** [comment]
Any news? Thanks :)

**Comment by abhilash1in** [comment]
This is my guess:

If data is paginated, results of the [`S3.listObjectsV2(params, callback)`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property) call will have `IsTruncated` set to true and will have a value in `NextContinuationToken`. For your next call to [`S3.listObjectsV2(params, callback)`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property), set the `ContinuationToken` property of the params object to the `NextContinuationToken` value from the previous token. You need to keep doing this recursively until `IsTruncated` is false.

Refer to [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property) for more info on the properties of request params and response of [`S3.listObjectsV2(params, callback)`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property) .

**Comment by marceloavf** [comment]
In listObjects there is a .eachPage method, seems that it's available too in listObjectsV2 but not documented, that's really confusing.

**Comment by Abhishek-Kaudare** [comment]
What is the Validity of NextContinuationToken from pagination as I tend to use it after days to restart processing

**Comment by julien-c** [comment]
unstale

**Comment by alshdavid** [comment]
`s3.paginateListObjectsV2()` is no longer in the latest SDK version, is there an alternative?
