### ISSUE TITLE
I have started using Aws sns service and I found that the service is not consistent. For some phone number it works fine but for some phone number it shows an error  "providerResponse": "Phone carrier is currently unreachable/unavailable", "phone has blockde sms"

### ISSUE THREAD

**Issue by jatin-nandwani-swaas** [aws/aws-sdk-js#3133]
Confirm by changing [ ] to [x] below:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

**Comment by ajredniwja** [comment]
Hey @jatin-nandwani-swaas thank-you for reaching out to us with your issue. 

Looking at the information about CloudWatch logs associated with SMS messaging [found here](https://github.com/awsdocs/amazon-sns-developer-guide/blob/master/doc_source/sms_stats_cloudwatch.md), there might be a case from the following: 

* Blocked as spam by phone carrier
* Destination is blacklisted
* Invalid phone number
* Message body is invalid
* Phone carrier has blocked this message
* Phone carrier is currently unreachable/unavailable
* Phone has blocked SMS
* Phone is blacklisted
* Phone is currently unreachable/unavailable
* Phone number is opted out
* This delivery would exceed max price
* Unknown error attempting to reach phone

The best practice now would be to have a test batch of messages for the phone numbers which returns this error. You may have to verify with the end user if any of the above reasons is the case. 

Closing this issue now, please reach out if you have any additional questions.
