### ISSUE TITLE
Shorten the pre-signed URL after generated

### ISSUE THREAD

**Issue by srasthapuram9621** [aws/aws-sdk-js#3134]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
The limit on url restricted to is 120 characters and using typescript code to create presigned url.

**Comment by ajredniwja** [comment]
Hey @srasthapuram9621, thank-you for reaching out.
 I am not sure if I understand the question that you're asking, can you please elaborate on it?
