### ISSUE TITLE
SES sendBulkTemplatedEmail worked unexpected

### ISSUE THREAD

**Issue by mswbecod** [aws/aws-sdk-js#3137]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
AWS Lambda

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v12.15.0

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `AWS.VERSION` in your code where `AWS = require("aws-sdk");`
"aws-sdk": "^2.628.0"

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

```javascript
await ses.sendBulkTemplatedEmail({
    "Destinations": [
        {
            "Destination": {
                "ToAddresses": [
                    "<EMAIL>"
                ]
            }
        },
        {
            "Destination": {
                "ToAddresses": [
                    "<EMAIL2>"
                ]
            }
        }
    ],
    "Source": "no-reply@DOMAIN,
    "Template": "template",
    "DefaultTemplateData": JSON.stringify({
        title: "...."
    })
}).promise();
```

Trying to send bulk templated email, but never worked with this example

According to [AWS Document](https://docs.aws.amazon.com/ses/latest/APIReference/API_BulkEmailDestination.html)

<img width="1324" alt="Screenshot of Chrome (2020-03-08 6-38-48 PM)" src="https://user-images.githubusercontent.com/46880771/76160279-11ba3680-616c-11ea-8aef-aa25e69d7859.png">

ReplacementTemplateData is not required

So example provided should work.

I tried `ReplacementTemplateData: ""`, but not worked

only `ReplacementTemplateData: "{}"` worked
so final example which is working is

```javascript
await ses.sendBulkTemplatedEmail({
    "Destinations": [
        {
            "Destination": {
                "ToAddresses": [
                    "<EMAIL>"
                ]
            },
            "ReplacementTemplateData": "{}"
        },
        {
            "Destination": {
                "ToAddresses": [
                    "<EMAIL2>"
                ]
            },
            "ReplacementTemplateData": "{}"
        }
    ],
    "Source": "no-reply@DOMAIN,
    "Template": "template",
    "DefaultTemplateData": JSON.stringify({
        title: "...."
    })
}).promise();
```

Did I misunderstood? or AWS Documentation is wrong?

**Comment by LFerronato** [comment]
I think this issue should be open again, 
the documentation is outdated
