### ISSUE TITLE
Import key problem

### ISSUE THREAD

**Issue by simon-p-r** [aws/aws-sdk-js#314]
Hello

I keep getting this error when trying to import key;

{ [InvalidKey.Format: Key is not in valid OpenSSH public key format]
  message: 'Key is not in valid OpenSSH public key format',
  code: 'InvalidKey.Format',
  time: Fri Jul 04 2014 18:39:02 GMT+0100 (GMT Summer Time),
  statusCode: 400,
  retryable: false }

My code is as following;

var AWS = require('aws-sdk');

AWS.config.loadFromPath('./config.json');

var ec2 = new AWS.EC2();

var key = {
    KeyName: 'test', // required
    DryRun: false
};

var keyImport = {
    KeyName: 'amazon', // required
    PublicKeyMaterial: 'file://path/to/key.pub',
    DryRun: false
};

ec2.createKeyPair(key, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(datae);           // successful response
        ec2.importKeyPair(keyImport, function(err, data) {
            if (err) console.log(err, err.stack); // an error occurred
            else     console.log(data);
        });
});

I have tried converting key file to base64 and still get same error.

Any help for a total novice will be greatly appreciated!

Simon

**Comment by laddi** [comment]
Yes, updating the documentation would be EXTREMELY helpful since I've now spent half a day trying to figure out why my base64 encoded PublicKeyMaterial wasn't working properly.  But thanks for the clarification! :smiley:
