### ISSUE TITLE
Cannot find module '../config_regional_endpoint' using npm install on linux

### ISSUE THREAD

**Issue by ammadakhtar** [aws/aws-sdk-js#3141]
Using node version 12.0
AWS-SDK version 2.104.0 and also latest.
A very strange kind of behaviour is seen when installing aws-sdk using npm install on linux machine. 
Upon debug the file sts.js on line 2 says
```javascript
var resolveRegionalEndpointsFlag = require('../config_regional_endpoint');
```

Which is not present in linux machine. A screenshot of ls command is attached for reference;

<img width="1577" alt="Screen Shot 2020-03-10 at 4 04 54 PM" src="https://user-images.githubusercontent.com/26001327/76306676-2b34bd00-62e9-11ea-9503-fba6b377ca90.png">

**Comment by ajredniwja** [comment]
Hey @ammadakhtar, thank-you for reaching out to us with your issue.

I am not completely able to understand what your issue is, can you please follow the [issue template](https://github.com/aws/aws-sdk-js/issues/new/choose)?

**Comment by ajredniwja** [comment]
Can you retry installing the SDK because I have different findings:

<img width="1361" alt="Screen Shot 2020-03-20 at 3 33 37 PM" src="https://user-images.githubusercontent.com/34409186/77211162-4b6e3400-6ac0-11ea-9df8-64ef38b9b7e8.png">
