### ISSUE TITLE
config/credentials file not used on clean Mac install

### ISSUE THREAD

**Issue by jayheavner** [aws/aws-sdk-js#3143]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Set my credentials using CLI `aws configure`.
Confirmed config and credentials files written to ~/.aws with correct values.
ran `npm i aws-sdk`.

Within the following code, AWS.config.region is null and AWS.config.getCredentials() throws "No credentials to load" error.

```
var AWS = require('aws-sdk');

export default {
  async load() {
    debugger;
    console.log('Region: ', AWS.config.region);
    AWS.config.getCredentials(function (err) {
      if (err) console.log(err.stack);
      // credentials not loaded
      else {
        console.log('Access key:', AWS.config.credentials.accessKeyId);
        console.log('Secret access key:', AWS.config.credentials.secretAccessKey);
      }
    });
  }
}
```

I've verified my HOME environment variable is present and correct. I've followed the documentation very carefully. I'm clearly missing something.

**Comment by ajredniwja** [comment]
Hey @jayheavner thank-you for reaching out, 

While this could be very vague to narrow down can you see if any env variables are set to anything using the command ```printenv | grep AWS```

Can you use operations from the CLI using something simple like:

```aws s3api list-buckets --query "Buckets[].Name"```

Do you see any errors when you run something on CLI?

Also can you provide me with the full stack trace that you are getting?

**Comment by awbacker** [comment]
I am having a similar issue, and adding the `AWS_SDK_LOAD_CONFIG` env var solved it for me.  You can do this at the command line, or in the js itself.  I'm curious if it works for you.  
```
process.env['AWS_SDK_LOAD_CONFIG'] = 'yes';
# or
$> AWS_SDK_LOAD_CONFIG=1 node myscript.js
```

My issue is it's ignoring all the env vars that should be controlling this behavior (mine lives in `~/config/aws`), even though the docs state that it reads them.

**Comment by jayheavner** [comment]
So I found the same environment var requirement after some digging. It would be nice if the documentation were updated to reflect.
