### ISSUE TITLE
DynamoDB DocumentClient constructor throws internal 'is not a function error'

### ISSUE THREAD

**Issue by ncrothers** [aws/aws-sdk-js#3144]
AWS APIs are updating constantly, you might be calling a new API with an older version is SDK. In
    this case you should try installing the newest `aws-sdk` like: 

    `npm install aws-sdk@latest`

    If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled
    SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
    You can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

If you still like to open an issue, change [ ] to [x] below:
- [x] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

---

When I call `AWS.DynamoDB.DocumentClient()`, it throws the error below:
```
"TypeError: self.configure is not a function",
"at Function.DocumentClient (/var/task/node_modules/aws-sdk/lib/dynamodb/document_client.js:61:10)"
```

I have tried reinstalling all of my node modules multiple times but that doesn't appear to fix the issue. This occurs both on the AWS Lambda and locally on my machine.

The following is an excerpt from `aws-sdk/lib/dynamodb/document_client.js` containing line 61, taken directly from `master` in the repo.

```
AWS.DynamoDB.DocumentClient = AWS.util.inherit({

  /**
   * Creates a DynamoDB document client with a set of configuration options.
   *
   * @option options params [map] An optional map of parameters to bind to every
   *   request sent by this service object.
   * @option options service [AWS.DynamoDB] An optional pre-configured instance
   *  of the AWS.DynamoDB service object to use for requests. The object may
   *  bound parameters used by the document client.
   * @option options convertEmptyValues [Boolean] set to true if you would like
   *  the document client to convert empty values (0-length strings, binary
   *  buffers, and sets) to be converted to NULL types when persisting to
   *  DynamoDB.
   * @see AWS.DynamoDB.constructor
   *
   */
  constructor: function DocumentClient(options) {
    var self = this;
    self.options = options || {};
    self.configure(self.options); /* ======= LINE 61 ======== */
  },

  /**
   * @api private
   */
  configure: function configure(options) {
    var self = this;
    self.service = options.service;
    self.bindServiceObject(options);
    self.attrValue = options.attrValue =
      self.service.api.operations.putItem.input.members.Item.value.shape;
  },
```

Versions:
Node.js v12.13.0
aws-sdk v2.636

**Comment by ajredniwja** [comment]
Hey @ncrothers any chance you are running this on Lambda?

**Comment by ncrothers** [comment]
Yes I am @ajredniwja.

**Comment by ajredniwja** [comment]
You are likely using old SDK version. AWS Lambda bundled SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
    You can import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

**Comment by ncrothers** [comment]
I'm deploying the Lambda through the SAM CLI, so the SDK version being used is what's in my `node_modules` folder, which is the latest version of the SDK.

**Comment by ajredniwja** [comment]
Hey @ncrothers can you please recheck the version by printing the output of AWS.VERSION in your code where `AWS = require("aws-sdk");`

**Comment by ncrothers** [comment]
@ajredniwja , I ran the code again and the version printed is `AWS-SDK Version: 2.636.0`.

**Comment by devsatishm** [comment]
I see the same error. AWS VERSION: 2.585.0

**Comment by devsatishm** [comment]
> I see the same error. AWS VERSION: 2.585.0

Had to go back to DynamoDB client directly for now.

**Comment by ajredniwja** [comment]
Hey guys, while trying to reproduce I ran into the same error:
```
var dbclient = AWS.DynamoDB.DocumentClient();
Thrown:
TypeError: self.configure is not a function
```

Because I was not using `new`,

Works perfectly: 

`var dbclient = new AWS.DynamoDB.DocumentClient();`

Can you guys check if thats the case with you all?

**Comment by ncrothers** [comment]
That fixed it, thanks! @ajredniwja
