### ISSUE TITLE
SharedIniFileCredentials not reading from AWS_SHARED_CREDENTIALS_FILE

### ISSUE THREAD

**Issue by awbacker** [aws/aws-sdk-js#3146]
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

When using the default SDK configuration it appears that the  `AWS_SHARED_CREDENTIALS_FILE` and/or `AWS_HOME` process env vars are ignored.  This causes relocated configurations to be missed, and a "Missing credentials in config (CredentialsError)" to be raised. 

My settings are:
* Running the script locally as `node repro.js`
* `AWS_HOME=/Users/andrew/.config/aws`
* `AWS_CONFIG_FILE=/Users/andrew/.config/aws/config`
* `AWS_SHARED_CREDENTIALS_FILE=/Users/andrew/.config/aws/credentials`

```
node: v12.14.0
npm: 6.13.4
aws-sdk: ^2.637.0
```

I am able to reproduce using this sample code, but the final failure happens when its looking in another location (since it didn't find it in the local file, see the `SharedIniFileCredentials` notes at the bottom.

```
const AWS = require('aws-sdk');
AWS.config.region = 'eu-west-1';

const s3 = new AWS.S3();
s3.listBuckets((err, data) => { console.log(err);});

$> node repro.js
Error: connect EHOSTUNREACH 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  message: 'Missing credentials in config',
  errno: 'EHOSTUNREACH',
  code: 'CredentialsError',
```

#### Workaround

The only way I have found to work around this is to set the `AWS_SDK_LOAD_CONFIG` env variable, either from the CLI or in code.  I've opted to set it in code for now.

```
process.env['AWS_SDK_LOAD_CONFIG'] = 'any-value-here';
```

#### Using SharedIniFileCredentials

This shows the same issue, but just fails faster since it never tries to connect to 169.x.  The [documention states](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html)

> Represents credentials loaded from shared credentials file (defaulting to ~/.aws/credentials or defined by the AWS_SHARED_CREDENTIALS_FILE environment variable).

```
var creds = new AWS.SharedIniFileCredentials();
AWS.config.credentials = creds

# result:
  message: 'Missing credentials in config',
  errno: -2,
  syscall: 'open',
  code: 'CredentialsError',
  path: '/Users/andrew/.aws/credentials',
```

**Comment by ajredniwja** [comment]
Hey @awbacker thank-you for reaching out with your issue.

I believe this is taken care of in the PR https://github.com/aws/aws-sdk-js/pull/2907

Have you tried setting AWS_SDK_LOAD_CONFIG=1

**Comment by awbacker** [comment]
Yes, I've set that variable, I mentioned it as my workaround.  Found reference to it in bug reports (the js way :D) and at the end dug up some documentation that I can't find again.

I've read the PR and while it is nice to have that slightly better message, it doesn't really fix anything.  Also, should that message reference `AWS_SHARED_CREDENTIALS_FILE` instead?

IMO the SDK should read from the correct location without prompting, in line with the python sdk and others.  The `aws` cli itself documents these variables, and of course uses them. 

I'm guessing the JS version has a good reason for ignoring them, but for now I've dropped it for writing aws related scripts and moved to other languages.  

For reference, the GO sdk says this (with no reference to relocated configs, haven't tested it):

> By default NewSession will only load credentials from the shared credentials file (~/.aws/credentials). If the AWS_SDK_LOAD_CONFIG environment variable is set to a truthy value the Session will be created from the configuration values from the shared config (~/.aws/config) and shared credentials (~/.aws/credentials) files. Using the NewSessionWithOptions with SharedConfigState set to SharedConfigEnable will create the session as if the AWS_SDK_LOAD_CONFIG environment variable was set. 

I was able to run the go example at https://github.com/aws/aws-sdk-go/blob/master/example/service/s3/listObjects/listObjects.go after minor modification to set the 'region' when creating the session.  It appears the go sdk (in addition to python) does not require this AWS_SDK_LOAD_CONFIG env variable to function and read from the relocated files.

**Comment by ajredniwja** [comment]
Hey @awbacker looking at the PRs that were made to introduce these variables, I found the [change log](https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/.changes/2.44.0.json) which mentions in order to use the `AWS_CONFIG_FILE` env variable the `AWS_SDK_LOAD_CONFIG` should be set to a truthy value.

**Comment by awbacker** [comment]
Thats great.  I guess this is only an issue for people writing local node scripts (me!) to do stuff.  As mentioned, python/go pick these up without a flag.  

I suppose this is something I'll just have to live with, honestly.  It makes sense for the expected use cases for a JS sdk;  it was just unexpected.  

The error message mentioned, while not a fix, will at least let people know of the problem. 

Feel free to close this if its not something that will be addressed (e.g. by making the behavior automatic, rather than the AWS_SDK_LOAD_CONFIG var).

**Comment by ajredniwja** [comment]
@awbacker I understand your concern, I believe that AWS_SDK_LOAD_CONFIG var enables more options, while I can totally discuss it with the team and have their say on this, I believe this will be a breaking change for many customers who may have these vars(for conifg and shared creds file) set and still be dependent on the default locations of the config and the credentials files as they might not be using the AWS_SDK_LOAD_CONFIG var. 

I would like to close this issue, thank-you for your patience and immediate responses. Please reach out if you have any additional questions.
