### ISSUE TITLE
[Error] Cognito:ListUsers when filter with character special

### ISSUE THREAD

**Issue by loongdefect** [aws/aws-sdk-js#3147]
I perform an email check exist on cognito. Code as below
`const paramsCheckEmail = {`
`            UserPoolId: '************',`
`           AttributesToGet: [`
`                'email',`
`            ],`
`           Filter: 'email ^= \""."@gmail.com\"',`
`           Limit: 10,`
`        };`
`        const checkEmail = await common_1.cognitoProvider.listUsers(paramsCheckEmail).promise();`
`        console.info(checkEmail);`
When running the code on lambda, I get the following response:
"errorType": "InvalidParameterException",
 "errorMessage": "Error while parsing filter."

I can filter users by email '"."@gmail.com'? 

Nodejs: 10.x
Aws lambda

**Comment by ajredniwja** [comment]
@loongdefect thank-you for reaching out, can you please share what version of the SDK is the Lambda using? 
 If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). You can import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

Please reach out if updating that doesn't solve the problem.

**Comment by loongdefect** [comment]
Hi @ajredniwja, 
I was upgrade lambda function as bellow:
runtime: Nodejs 12.x
SDK:  2.639.0
The error still appears. I doing filter in AWS Console, same error appears:
![image](https://user-images.githubusercontent.com/8251888/76612166-4d7b4480-654e-11ea-8407-483be2772399.png)
![image](https://user-images.githubusercontent.com/8251888/76612202-5e2bba80-654e-11ea-964d-3e7c060b4228.png)

**Comment by ajredniwja** [comment]
@loongdefect can you try ```\"\".\"@gmail.com\"```, the doc https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#listUsers-property states:  "Quotation marks within the filter string must be escaped using the backslash () character. For example, "family_name = \"Reddy\""."

Please reach out if that doesn't solve your problem.

**Comment by loongdefect** [comment]
Hi @ajredniwja ,
Today, i searching and no errror appears. But, search working incorrect.
![image](https://user-images.githubusercontent.com/8251888/76818955-8ad71f00-6839-11ea-8227-7c5fe203724a.png)
![image](https://user-images.githubusercontent.com/8251888/76819042-c245cb80-6839-11ea-8551-59bd25999a82.png)

**Comment by ajredniwja** [comment]
What is your use case? are you trying to filter gmail emails? 

The problem lies in the the key you are using to search, you need to escape all characters correctly. You can try https://www.the-art-of-web.com/javascript/escape/ to get a little bit extra help when checking if you're escaping everything correctly.

**Comment by loongdefect** [comment]
Hi @ajredniwja 
This problem can be solved with escape/unescape.
Thank for support
