### ISSUE TITLE
call to updateUserPool automatically assigns SMS role - which i can't revert from!!

### ISSUE THREAD

**Issue by yashutanna** [aws/aws-sdk-js#3148]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
there is no way to set the invitation message for new messages on cloudformation. so i decided to update it dynamically every time a new user is created by calling `updateUserPool` (with updates to the InviteMessageTemplate property) before a new user is created. 

a side effect of this (which makes no logical sense to me) is the existing settings of my Userpool were reset as opposed the the config in the `updateUserPool` being applied on top of existing settings. 

I can now no longer switch MFA off and revert back to the previously working state as I cannot remove the SMS role assigned:
![image](https://user-images.githubusercontent.com/6696871/76522218-e63a9300-646e-11ea-8cdd-800ddcdfa200.png)

I tried deleting the role in IAM and am now stuck on this error

![image](https://user-images.githubusercontent.com/6696871/76522265-010d0780-646f-11ea-8e91-486f96b6015c.png)

so yea - im completely stuck now and there are no resources out there to get me out of this scenario

**SDK version number**
Example: v2.638.0

**To Reproduce (observed behavior)**
call updateUserPool with updates to InviteMessageTemplate property on an existing userpool that has MFA set to OFF. the SMS role will be automagically assigned

**Expected behavior**
the config provided in updateUserPool should be applied to the userpool without changing anything else

**Comment by ajredniwja** [comment]
Hey @yashutanna thank-you for reaching out, can you please the share the code to reproduce the issue and how you are consuming the JS-SDK?
