### ISSUE TITLE
Cannot get credentials using credential_process in config file

### ISSUE THREAD

**Issue by TheRyanBurke** [aws/aws-sdk-js#3156]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ X ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ X ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ X ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Cannot create AWS client with credentials from credential_process that is defined in ~/.aws/config file. Error returned is:

```
CredentialsError: Could not load credentials from SharedIniFileCredentials
    at SharedIniFileCredentials.load (/Users/burkery/projects/aws-js-sdk-w-credentialprocess/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:144:11)
...
{
  message: 'Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1',
  code: 'CredentialsError',
  time: 2020-03-17T18:55:28.129Z,
  originalError: {
    message: 'Could not load credentials from SharedIniFileCredentials',
    code: 'CredentialsError',
    time: 2020-03-17T18:55:28.129Z,
    originalError: {
      message: 'Credentials not set for profile dev',
      code: 'SharedIniFileCredentialsProviderFailure',
      time: 2020-03-17T18:55:28.128Z
    }
  }
}
```

config file has profile like:

```
[profile dev]
region = us-west-2
account = redacted
role = redacted
credential_process = redacted
```
Environment variable AWS_SDK_LOAD_CONFIG is set to 1 (validated from node.js code).

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.16.1

**SDK version number**
v2.640.0

**To Reproduce (observed behavior)**
From terminal:

$ export AWS_SDK_LOAD_CONFIG=1
$ node index.js

Config file:

```
[profile dev]
region = us-west-2
account = redacted
role = redacted
credential_process = redacted
```

A file exists at ~/.aws/credentials but has no profile specified for 'dev'.

index.js:

```
const aws = require('aws-sdk')

const credentials = new aws.SharedIniFileCredentials({profile: 'dev'});
aws.config.update({region: 'us-west-2'});
aws.config.credentials = credentials;

aws.config.getCredentials(function(err) {
  if (err) console.log(err.stack);
  // credentials not loaded
  else {
    console.log("Access key:", aws.config.credentials.accessKeyId);
    console.log("Secret access key:", aws.config.credentials.secretAccessKey);
  }
});
```

**Expected behavior**
Expect AWS SDK to fetch credentials from the credential_process specified in the .aws/config file. Support for this path was merged in PR https://github.com/aws/aws-sdk-js/pull/2559

**Additional context**
Originally trying to use AWS CDK with credential_process and landed on this issue: https://github.com/aws/aws-cdk/issues/3008 Saw the PR in aws-sdk-js that merged in credential_process support and wanted to test out a basic nodejs app attempting to use credential_process first.

**Comment by ajredniwja** [comment]
Hey @TheRyanBurke thank-you for reaching out, can you try and remove the profile prefix? 

Can you also share the code that you are using for your use case?
