### ISSUE TITLE
Unfortunate cache interactions when S3 bucket with same name exists on Govcloud and non-govcloud account

### ISSUE THREAD

**Issue by tomdee** [aws/aws-sdk-js#3166]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
S3 client changes the region when it should not.

I'm using the same node process to connect to two AWS accounts. One is on Govcloud and one isn't. There's an S3 bucket that has the same name on both accounts.

Although I create two different S3 clients, they end up polluting each other because the same S3 bucket is found on two different accounts. I think it's this code which has the bug - it doesn't take into account the fact that a Govcloud has its own namespace for S3 buckets.

https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L934

**Is the issue in the browser/Node.js?**
Node JS

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Node 12

**SDK version number**
v2.633.0

**To Reproduce (observed behavior)**
Create two accounts, one on govcloud and one not.
Create a bucket with the same name in both accounts.
Create two S3 clients each with their own credentials.
Use each client to list the buckets in each account and then make some S3 API cals.
Observe that one of the clients starts sending requests to the wrong region

**Expected behavior**
I should be able to use a single node process to access S3 buckets from multiple S3 accounts, even if those accounts have bucket names in common.

**Screenshots**

**Additional context**

**Comment by tomdee** [comment]
Looks like this issue has already been raised, but never got fixed - https://github.com/aws/aws-sdk-js/issues/2802

**Comment by ajredniwja** [comment]
Hey @tomdee, thank-you for reaching out to us with your issue.

It is recommended to not use two clients in single application. 

For the issue #2802, the customer solved it for his use case that is why it was closed. 

Were you able to do something similar?

I can help you rewrite your code if you can share it.

**Comment by tomdee** [comment]
>It is recommended to not use two clients in single application.

This requires a complete rearchitecture of our application.

If you can't fix that restriction, could you at least add it to the documentation?
