### ISSUE TITLE
Can't list Repositories

### ISSUE THREAD

**Issue by jwerre** [aws/aws-sdk-js#3173]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
CodeCommit [`listRepositories`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CodeCommit.html#listRepositories-property) does not list repositories. 

**Is the issue in the browser/Node.js?**
Node.js (v10.16.0)

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v10.16.0

**SDK version number**
v2.378.0

**To Reproduce (observed behavior)**

The CLI works just fine:
```bash
$ aws codecommit list-repositories --region us-east-1
{
 "repositories": [
        {
            "repositoryName": "XXX", 
            "repositoryId": "XXXX"
        }, 
...
        {
            "repositoryName": "ZZZ", 
            "repositoryId": "ZZZ"
        }
]
}
```

When I run the following in Node.js there is no output:

```js
const AWS = require('aws-sdk');

const cc = new AWS.CodeCommit({region:'us-east-1'});

// setting the region here does not help
// AWS.config.update({
// 	region: 'us-east-1',
// });

cc.listRepositories().promise()
	.then( console.log )
	.catch( console.error );

// Using a standard callback does not help
// cc.listRepositories((err, data) => {
//   if (err) {
//     console.error(err);
//   } else {
//     console.log(data);
//   }
// });	
```

**Expected behavior**
I expect a list of my repos but there is no output

**Comment by ajredniwja** [comment]
Hey @jwerre thank-you for reaching out with your issue.

I was successfully able to list repositories using the code snippet: 
```
codecommit.listRepositories(function (err, data) {
    if (err) console.log(err);
    else console.log(data);
});
```
Can you make sure that you have repositories listed using the console and are in the correct region?

**Comment by jwerre** [comment]
Very strange. I ran the same code this morning and it works as expected. ¯\_(ツ)_/¯

**Comment by ajredniwja** [comment]
That is strange, would like to close this issue.

Please reach out if you have any additional questions.
