### ISSUE TITLE
ssm.GetParametersByPath not working as expected

### ISSUE THREAD

**Issue by ANTGOMEZ** [aws/aws-sdk-js#3174]
Confirm by changing [ ] to [x] below:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

the function ssm.getParametersByPath is not working for me, I have the follwoing code and all I get is an empty array despite having params defined for the path passed in.

```
async function getParamsByPath({path})
{
     var params = {
        Path: path,
        WithDecryption: true
    };
    var ssm = new aws.SSM();
    var pp = await ssm.getParametersByPath(params).promise();

    return pp.Parameters; //this returns empty array despite having params defined
}
```
I have tried passing in the path both ways: "/my/path" and "/my/path/".

Just to check if it was maybe the client I tried the single param call: 

   `var p = await ssm.getParameter(params).promise();`

And this works as expected using one of the params I'm trying to get in the getParametersByPath call.

All the examples I have seen show that the two parameters defined for the call are all I need. BUT, do I need others?

Why is this not working?

Thanks!

**Comment by ANTGOMEZ** [comment]
I believe this is a bug. And it is due to having a dash in the name, which is allowed according to; https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-parameter-name-constraints.html

In my example above all the parameters I'm trying to retrieve have a dash under the path I'm passing in.

What I did is I created 2 more parameters under the path I used and they don't have dashes in the name, I then I ran above code, and it works, return both new params that don't have dashes.

Note, when I call the single getParameter method, getting a param with a dash, it also works.

So unless I'm missing something, this is a bug in this method, it cannot handle names with dashes.

**Comment by ANTGOMEZ** [comment]
After some fiddling I rolled my own, below. But the method above isn't working as advertised, maybe not a bug, but not as straight forward.

Here's mine, that IS working:

`async function getParamsByPath({path})
{
    var params = 
    {
        ParameterFilters: [
          {
            Key: 'Name',
            Option: 'BeginsWith',
            Values: [path]
          }
        ]
      };

      var ssm = new aws.SSM();
      let parameters = [];
      try
      {
     
        let allParameters = [];
        let data =  await ssm.describeParameters(params).promise();
        allParameters.push.apply(allParameters, data.Parameters);
        while(data.NextToken) {
            params.NextToken = data.NextToken;
            data =  await ssm.describeParameters(params).promise();
            allParameters.push.apply(allParameters, data.Parameters);
        }

        let pp = allParameters.map(a => a.Name);

        var temparray=[];
       
        var i,j,temparray,chunk = 10;
        for (i=0,j=pp.length; i<j; i+=chunk) 
        {
            temparray = pp.slice(i,i+chunk);
           
            var params = {
                Names: temparray,
                WithDecryption: true
            };
            
            let dat =  await ssm.getParameters(params).promise();
            parameters.push.apply(parameters, dat.Parameters);
            while(data.NextToken) 
            {
                params.NextToken = dat.NextToken;
                dat =  await ssm.getParameters(params).promise();
                parameters.push.apply(parameters, dat.Parameters);
            }            
        } 
    }
    catch (err) 
    {
        return Promise.reject(err);
    }

    try
    {
      let jparms = parameters.map(p => JSON.parse(p.Value));
      return jparms;
    }
    catch(erro)
    {
        return Promise.reject(erro);
    };  
}`

**Comment by ajredniwja** [comment]
Hey @ANTGOMEZ thank-you for reaching out, this is definitely frustrating. Reached out to service team to fix this, documentation or fixing the backend code. Will update once they do it.

**Comment by ajredniwja** [comment]
Hey @ANTGOMEZ, tried working with the dashes, it works fine. 

Can you describe what exactly is the problem?
