### ISSUE TITLE
Pinpoint removeAttributes not deleting the user attributes

### ISSUE THREAD

**Issue by deepakpc** [aws/aws-sdk-js#3175]
I have been trying the removeAttributes API for Pinpoint to remove a specific user attribute from all the endpoints. But, whenever I call this API, I get a response with blacklisted attributes which are all the fields except for what I have given in the request. But, when I get the endpoint using getEndpoint, I can see all the attributes intact.

I tried updating to the latest version of the SDK. But nothing changed. 
This is my request object:
{
        ApplicationId: "appid", /* required */
        AttributeType: 'endpoint-user-attributes', /* required */
        UpdateAttributesRequest: { /* required */
            Blacklist: ["id1", "id2"]
        }
}
Is this a bug or am I using it incorrectly? Please help

**Comment by ajredniwja** [comment]
Hey @deepakpc can you please follow the issue template found [here](https://github.com/aws/aws-sdk-js/issues/new/choose).

**Comment by deepakpc** [comment]
@ajredniwja Reported as a bug.

**Comment by ajredniwja** [comment]
Closing this, tracking in #3180
