### ISSUE TITLE
browserify failed due to missing dist-tools

### ISSUE THREAD

**Issue by aws-kens** [aws/aws-sdk-js#3177]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
[This commit](https://github.com/aws/aws-sdk-js/commit/98c40e64cb7d60927c6a0cec49592fc1fcaa59d7#diff-0fd4ef892d9d4990033701887c2f9bcc) removes **dist-tools** from npm package breaks **browserify**

**Is the issue in the browser/Node.js?**
Browser

**If on Node.js, are you running this on AWS Lambda?**
n/a

**Details of the browser/Node.js version**
v10.16.3

**SDK version number**
2.644.0

**To Reproduce (observed behavior)**
* Create a simple **package.json**
```
{
  "name": "aws-sdk-browserify-issue",
  "version": "1.0.0",
  "description": "reproduce aws-sdk browserify issue",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "aws-sdk": "^2.644.0"
  }
}
```
* Create a simple  **index.js**
```
const AWS = require('aws-sdk');
module.exports.AWS = AWS;
```
* Run **npm install**
* Error occurs
```
Error: Cannot find module './dist-tools/transform.js' from '/.../temp/node_modules/aws-sdk'
    at /.../browserify/node_modules/resolve/lib/async.js:128:35
    at load (/.../browserify/node_modules/resolve/lib/async.js:147:43)
    at onex (/.../browserify/node_modules/resolve/lib/async.js:172:17)
    at /.../browserify/node_modules/resolve/lib/async.js:13:69
    at FSReqWrap.oncomplete (fs.js:153:21)
```

**Expected behavior**
Should include **dist-tools** back in the npm package.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by ajredniwja** [comment]
@aws-kens working on the fix.

**Comment by ajredniwja** [comment]
fixed in https://github.com/aws/aws-sdk-js/pull/3178

**Comment by aws-kens** [comment]
awesome! Thanks @ajredniwja for quick response!
