### ISSUE TITLE
Waiters do not retry non-2xx Service errors

### ISSUE THREAD

**Issue by arnulfojr** [aws/aws-sdk-js#3181]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Waiter will not retry API calls if the response received from the service was a non-2xx and unmatched by the configured acceptors.

**Is the issue in the browser/Node.js?**
At least in Node.JS but most probably in Browser as well.

**If on Node.js, are you running this on AWS Lambda?**
Yes.

**Details of the browser/Node.js version**
`node -v` I really don't have the version at hand, but we are running Node.JS 12.x in lambda.

**SDK version number**
`2.610.0`
by running command `npm list aws-sdk` from your root directory

**To Reproduce (observed behavior)**
If a service waiter does not have mapped an InternalServerError or an error that it's explicitly set to retry the waiter will not set the response as retry-able and the waiter will set the Resource is not ready.
This may be common in some cases when the Service APIs have blips or their availability goes down for a while.
I can't really reproduce it in a controlled environment due to the dependency of the APIs.

**Expected behavior**
Much like the SDK does the retries with normal requests (applying the SDK's retry policy to normal requests), I expect the waiters execute the retries in a per request basis or at least to continue consuming from the left attempts based from the maxAttempts configuration, if a non-terminal state was "explicitly" configured in the waiters configuration.

**Screenshots || Additional context**
I do not have any screenshots but I have links to the code that help me prove the case.

Going down from the waiter's entrypoint, we have the [waitFor](https://github.com/aws/aws-sdk-js/blob/cc29728c1c/lib/service.js#L239-L242) public api which essentially creates an `AWS.ResourceWaiter` instance and waits for the state to match one of the acceptors or until it times out.
When the waiter starts "wait"ing, the waiter overrides the operation configuration with the configuration specified in the waiter's configuration, such `delay` and `maxAttempts` end up in the `service.makeRequest` call which returns a request instance. Which then, the waiter will add it's [own request Listeners](https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/lib/resource_waiter.js#L149-L170).
this listeners will attach themselves to the `retry`, [`extractData`, and `extractError`](https://github.com/aws/aws-sdk-js/blob/cc29728c1c/lib/request.js#L214-L225) events.
The interesting part is when handling the `extractError`. The CHECK_ERROR listener will get called and invoke the `CHECK_ACCEPTORS` function, which will check over all the configured acceptors but since `InternalServerError` is not specified in any waiter configuration, there's no acceptor matched and the response will include an error, the `CHECK_ACCEPTORS` function will set the `state = 'failure'` when evaluating the [if expression](https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/lib/resource_waiter.js#L39).
Since the state is in failure, the waiter will `setError` to the response and have the state `"non-retryable"`, [waiter.setError(resp, state === 'retry')](https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/lib/resource_waiter.js#L44).
What the setError function will do is set the response's error to a non-retryable state.
which will make the action non-retryable based on the [`retry event`](https://github.com/aws/aws-sdk-js/blob/cc29728c1c/lib/request.js#L185-L194). this will make the waiter to end prematurely and throw the AWS Error with the ResourceNotReady code.

**Personal note**

Although this case may be not so common, in case of a blip or a service having some issues that do not affect resources (e.g., the control-plan just having some issues) the waiter will end and not retry anymore.
I'm also new to the SDK and I'm trying to understand much of the internals, so if I'd be to be wrong, any further guidance would be deeply appreciated!

**Comment by ajredniwja** [comment]
Hey @arnulfojr thank-you for reaching out with your, can you please share for what service and what ‘InternalServerError’ are you seeing?

Marked this a feature request as it is not a bug with a SDK but a feature/enhancement that can be implemented in future.
