### ISSUE TITLE
Downloading Large CSVs with Express

### ISSUE THREAD

**Issue by jmmadsen** [aws/aws-sdk-js#3182]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Hello,

I am storing large CSV files in a bucket (anywhere from 40k - 5M rows), and I am attempting to download them from my React app. I am using an Express API, but cannot seem to stream and initiate the download on the browser successfully. Any advice would be appreciated.

Below is a snippet of my code. I attempt to log the stream to get a view of it, but it always seems to freeze around 500 rows or so. Additionally, the download never seems to initiate on the browser - I am using Chrome, so I would imagine it would start the circle download bar once it begins receiving stream data.

```
s3.getObject({
                Bucket: 'example-bucket-csvs',
                Key: 'example_name.csv'
            })
            .on('httpData', (chunk => {
                console.log(chunk.toString());
                res.writeHead(200, {
                    'Content-Type': 'text/csv',
                    'Content-Disposition': 'attachment; example_name.csv'
                })
                chunk.pipe(res);
            }))
```

**Comment by ajredniwja** [comment]
Hey @jmmadsen Thank-you for reaching out, do you see any error? Or can you please share the stack trace?

**Comment by jmmadsen** [comment]
Hi @ajredniwja,

So I actually went in a different direction with this last Friday, and am now using `s3.getSignedURL()` to just expose the file for the end user, as opposed to trying to recreate the functionality. I don't have the stack traces anymore, so I will go ahead and shut this issue for now. Thanks for getting back to me.
