### ISSUE TITLE
sqs.sendMessageBatch(...) does not provide an informative / useful error message.

### ISSUE THREAD

**Issue by rajuashok** [aws/aws-sdk-js#3187]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When making a request to `sqs.sendMessageBatch(...)` a mostly useless error message is provided on Failure:

`{
    "ResponseMetadata": {
        "RequestId": "f50d67b0-4546-508a-9d60-314b729a6ef0"
    },
    "Successful": [],
    "Failed": [
        {
            "Id": "de52eea0-7218-11ea-a003-cd38c8498fb8",
            "SenderFault": true,
            "Code": "InvalidParameterValue",
            "Message": "The request include parameter that is not valid for this queue type"
        }
    ]
}
`

This resulted in hours of debugging, guessing which parameter was incorrect.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes this is a deployed lambda that is using sqs.sendMessageBatch(...)

**Details of the browser/Node.js version**
v11.5.0

**SDK version number**
"aws-sdk": "2.568.0",

**To Reproduce (observed behavior)**
In our case we were accidentally sending MessageGroupId as part of the params for a non-FIFO queue.

**Expected behavior**
Indication of which parameter was incorrect. I believe AWS provides this?

**Comment by ajredniwja** [comment]
Hey @rajuashok thank-you for reaching out to us with your issue, I understand that it might be frustrating at times but at the moment the JS-SDK doesn't mention the incorrect param name. 
This is not necessarily a bug with the SDK but potentially a good enhancement, marking it as a feature request. The team would welcome any PRs, if you'd like to work on it.

**Comment by rajuashok** [comment]
Ah yes, that's a good point. Thanks for updating it and appreciating you looking at it. Wish I had time to work on this - maybe in a few weeks!
