### ISSUE TITLE
MaxRetriesExceeded set to 1 when final retry succeeds

### ISSUE THREAD

**Issue by DRNagar** [aws/aws-sdk-js#3189]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

The maxRetriesExceeded metric is set to 1 when the API call is successful.

This occurs if the call is successful on the final retry. This is due to the associated responses retryCount being equal to the maxRetries. [This sets the MaxRetriesExceeded to 1 as retryCount >= maxRetries](https://github.com/aws/aws-sdk-js/blob/master/lib/service.js#L435-L441).

**Research on the bug**

The responses retryCount is incremented in two places: 
1. A request is [restarted] (https://github.com/aws/aws-sdk-js/blob/master/lib/event_listeners.js#L196) due to failing in the state [build or afterBuild](https://github.com/aws/aws-sdk-js/blob/master/lib/request.js#L45-L46).
2. After a retry[retry] (https://github.com/aws/aws-sdk-js/blob/master/lib/event_listeners.js#L462-L484)

In both these cases the retryCount is incremented after a failing call on the condition that retryCount<maxRetries. This implies that on the final retry the retryCount is equal to the maxRetries.

**Is the issue in the browser/Node.js?**
The issue should be in both

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the Node.js version**
v12.13.1

**SDK version number**
v2.597.0

**To Reproduce (observed behavior)**
The observed behavior in evident in our metrics
```
{ 
   ...
   MaxRetriesExceeded: 1,
   StatusCode2xx: 1
   ...
}
```

Using the test framework, adding the following case to the unit tests succeeds:
```
    {
      'description': 'Test if final retry succeeds maxRetriesExceeded is not set',
      'configuration': {
        'accessKey': 'myaccesskey',
        'region': 'us-west-2',
        'environmentVariables': {
          'AWS_CSM_ENABLED': 'true'
        },
        'sharedConfigFile': {},
        'maxRetries': 1
      },
      'apiCalls': [
        {
          'serviceId': 'CSM Test',
          'operationName': 'TestOperation',
          'params': {},
          'attemptResponses': [
            {
              'httpStatus': 503,
              'responseHeaders': {},
              'errorCode': 'ServiceUnavailable',
              'errorMessage': 'Service is unavailable'
            },
            {
              'httpStatus': 200,
              'responseHeaders': {},
            }
          ]
        }
      ],
      'expectedMonitoringEvents': [
        {
          'Version': 1,
          'Type': 'ApiCallAttempt',
          'Service': 'CSM Test',
          'Api': 'TestOperation',
          'ClientId': '',
          'Timestamp': 'ANY_INT',
          'AttemptLatency': 'ANY_INT',
          'Fqdn': 'csmtest.us-west-2.amazonaws.com',
          'Region': 'us-west-2',
          'UserAgent': 'ANY_STR',
          'AccessKey': 'myaccesskey',
          'HttpStatusCode': 503,
          'AwsException': 'ServiceUnavailable',
          'AwsExceptionMessage': 'Service is unavailable'
        },
        {
          'Version': 1,
          'Type': 'ApiCallAttempt',
          'Service': 'CSM Test',
          'Api': 'TestOperation',
          'ClientId': '',
          'Timestamp': 'ANY_INT',
          'AttemptLatency': 'ANY_INT',
          'Fqdn': 'csmtest.us-west-2.amazonaws.com',
          'Region': 'us-west-2',
          'UserAgent': 'ANY_STR',
          'AccessKey': 'myaccesskey',
          'HttpStatusCode': 200
        },
        {
          'Version': 1,
          'Type': 'ApiCall',
          'Service': 'CSM Test',
          'Api': 'TestOperation',
          'ClientId': '',
          'Timestamp': 'ANY_INT',
          'Latency': 'ANY_INT',
          'AttemptCount': 2,
          'MaxRetriesExceeded': 1,
          'UserAgent': 'ANY_STR',
          'Region': 'us-west-2',
          'FinalHttpStatusCode': 200
        }
      ]
    }
```

**Expected behavior**
I expect that when an API call is successful, we do not see any metrics for maxRetriesExceeded.

**Comment by ajredniwja** [comment]
Hey @DRNagar thank-you for reaching out to us with your issue and opening a PR too for the issue, will let the team review/discuss it and get back to you.

**Comment by trivikr** [comment]
Closed in https://github.com/aws/aws-sdk-js/pull/3196
