### ISSUE TITLE
SSM.getParamater promise Typescript

### ISSUE THREAD

**Issue by kinbald** [aws/aws-sdk-js#3191]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [*] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [*] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [*] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

Hello,

While using `getParameter` in TS, I noticed that I couldn't access the data response without having to check if they are set or not. 
I mean if there's an error while retrieving the parameter (empty, not fund), It goes to the error condition so why `Parameter`can be `undefined` ? 

Best regards,

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
I would like.

**Details of the browser/Node.js version**
`node -v` : v12.16.1

**SDK version number**
v2.650.0

**To Reproduce (observed behavior)**

While accessing a parameter from a single call to `getParameter`. I have to check that the parameter is set.

```typescript
import {
    Callback,
    CognitoUserPoolEvent,
    Context
} from "aws-lambda"
import {
    SSM
} from 'aws-sdk'

const ssmProvider = new SSM({
    apiVersion: '2014-11-06'
})

export const handler = (event: CognitoUserPoolEvent, context: Context, callback: Callback) => {
    const params = {
        Name: 'test'
    }

    const paramRequest = ssmProvider.getParameter(params, (err, data) => {
            if (err) {
                console.log(err)
            } else {
                console.log("=== Param get ===")
                console.log(data.Parameter.Value) // Not working without the non null assertion
                if (data.Parameter && data.Parameter.Value) {
                    // Work with the value without issue (could be replaced by !! assertion)
                }
                console.log('Success')
                context.succeed(event)
            }
        }
        // Return to Amazon Cognito
        callback("Can't find key")
    })
}
```

**Expected behavior**
I can't compile my typescript because data.Parameter object is possibly of type `undefined` so I can't get the value.

**Additional context**
I tried to reproduce the code presented in this comment : [#2245](https://github.com/aws/aws-sdk-js/issues/2245#issuecomment-419661167) but same issue happens while compiling TS.

**Comment by ajredniwja** [comment]
Hey @kinbald thank-you for reaching out to us with your issue, can you please use async await instead of callbacks?

**Comment by mdrijwan** [comment]
> Hey @kinbald thank-you for reaching out to us with your issue, can you please use async await instead of callbacks?

same issue with async await

here's my code:

```
import { SSM } from '@aws-sdk/client-ssm'
const ssm = new SSM({
  region: process.env.AWS_REGION,
})

export const getSecret = async () => {
  const params = { Name: process.env.SSM_PARAM }
  const data = await ssm.getParameter(params)
  const secrets = JSON.parse(data.Parameter.Value)

  return secrets
}
```
throws error:
```
'data.Parameter' is possibly 'undefined'.ts(18048)
Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
Type 'undefined' is not assignable to type 'string'.ts(2345)
```
