### ISSUE TITLE
IAM calls failing for gov cloud region

### ISSUE THREAD

**Issue by trriplejay** [aws/aws-sdk-js#3192]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
when configuring an IAM service with region `us-gov-east-1`, I am unable to perform a `list-roles` call, receiving the following error:
```
Error SignatureDoesNotMatch: Credential should be scoped to a valid region, not 'us-gov-east-1'.
```
My keys are associated with a govcloud user who has the following policy attached (or this is the relevant piece at least:
```
        {
            "Action": [
                "iam:PassRole",
                "iam:ListRoles"
            ],
            "Resource": "arn:aws-us-gov:iam::*:*",
            "Effect": "Allow"
        }
```
I found one similar issue with a workaround suggestion of manually setting the endpoint, in case the default was not being correctly selected.  That workaround looked something like this:
```
var iam = new AWS.IAM({apiVersion: '2010-05-08', endpoint: 'https://iam.us-gov.amazonaws.com' });
```
however, this also did not work, and yielded the same error.

Finally, I have performed the same call with the same keys using the awscli, and it succeeded, returning the list of roles as expected. I've also tried the latest `v3` javascript-sdk client, and it works there as well.

I would prefer to not have to switch to the v3 client just for this call.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
no

**Details of the browser/Node.js version**
v10.18.0

**SDK version number**
v2.651.0

**To Reproduce (observed behavior)**
```
var AWS = require('aws-sdk');
// Set the region
AWS.config.update({region: 'us-gov-east-1'});
// Create the IAM service object
var iam = new AWS.IAM({apiVersion: '2010-05-08'});
iam.listRoles({},function(err, data){
    if (err) {
        console.log("Error", err);
    } else {
        console.log("Success", data);
    }
});
```

**Expected behavior**
I expect list-roles to succeed, and to list the available roles from my gov-cloud account

**Additional context**

**Comment by avicloud720** [comment]
This normally happens for **global resources**. 

I faced similar issue for `Route53` > `Hosted Zone`. It worked for me by passing both `region` & `endpoint` specifically for GOV (as default values were `region: us-east-1` and `endpoint: https://route53.amazonaws.com` which will not work in GOV)

I passed something like this:

```
  connParams.region = "us-gov-west-1";
  connParams.endpoint = "https://route53.us-gov.amazonaws.com";
```

I think there is a mismatch in the `region` parameter in your case. Hence the error,
`Error SignatureDoesNotMatch: Credential should be scoped to a valid region, not 'us-gov-east-1'.`

Below command helped to fetch the value of `region` and `endpoint` for GOV environment
`aws --profile xyz route53 list-hosted-zones --debug`

where `xyz` profile contains GOV credentials.

**Comment by trriplejay** [comment]
@avicloud720 interesting, that actually appears to have worked! 

I don't really understand why on this "global" resource, it requires that I specify `us-gov-west-1` instead of `us-gov-east-1`. That still seems like a bug to me. Shouldn't the client see that my region contains "us-gov" and set the global endpoint appropriately?

I'm setting the region in my aws client, and only some small percentage of the calls i make are for the IAM endpoint. The rest actually need to go to `us-gov-east-1`. I get that I can configure the IAM client separately from others with its own region, but it's not clear to me why I should have to pick `us-gov-west-1` in that case.

At the very least it seems like it should be in documentation somewhere.. "when using the iam client on govcloud, make sure to specify the `us-gov-west-1` region, as that is the underlying region of this global resource". or am I misunderstanding?

**Comment by workeitel** [comment]
Similar problem happens for China region as well.

For us-gov partition the region config specifies the global endpoint to be `iam.us-gov.amazonaws.com` which is the correct endpoint:

https://github.com/aws/aws-sdk-js/blob/master/lib/region_config_data.json#L30

But for China that's missing. the endpoint should be `iam.cn-north-1.amazonaws.com.cn`: https://docs.aws.amazon.com/general/latest/gr/iam-service.html

Adding the endpoint like

```diff
--- a/lib/region_config_data.json
+++ b/lib/region_config_data.json
@@ -27,6 +27,7 @@
       "globalEndpoint": true
     },
     "*/waf": "globalSSL",
+    "cn-*/iam": "globalIamChina",
     "us-gov-*/iam": "globalGovCloud",
     "us-gov-*/sts": {
       "endpoint": "{service}.{region}.amazonaws.com"
@@ -61,9 +62,12 @@
     "globalGovCloud": {
       "endpoint": "{service}.us-gov.amazonaws.com"
     },
+    "globalIamChina": {
+      "endpoint": "iam.cn-north-1.amazonaws.com.cn"
+    },
     "s3signature": {
       "endpoint": "{service}.{region}.amazonaws.com",
       "signatureVersion": "s3"
     }
   }
```

works but on top the right region needs to be specified. The endpoint is per aws cloud partition but the signature used for Auth must include the region the service expects.

For the normal `aws` partition it's hard-coded to be us-east-1 for global services:

https://github.com/aws/aws-sdk-js/blob/38bf84c144281f696768e8c64500f2847fe6f298/lib/request.js#L316-L317

It's probably hard to make a general assumption for other partitions as well. I assume the easiest is to extend `region_config_data.json` to include signing region as an additional field for global services.

In comparison the config for the aws-sdk-go:

https://github.com/aws/aws-sdk-go/blob/master/aws/endpoints/defaults.go#L6393-L6404

**Comment by workeitel** [comment]
Same applies to other global endpoints like Route53
