### ISSUE TITLE
How to use Cognito for handle (Auth)

### ISSUE THREAD

**Issue by andrefedev** [aws/aws-sdk-js#3193]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I don't know about you, but Cognito is the only Amazon service that seems impossible to understand. I am using aws-cdk to create the infrastructure and aws-sdk on the client side with React.

I know that amplifyjs exists, but I want to take advantage of the knowledge I already have of (aws-cdk / aws-sdk), the most difficult thing is to know how to authenticate a user anonymously, then log in with a flow like Facebook or Inclusive I have implemented a system of authentication with WhatsApp, but Cognito is so complex.

For example, the authentication system that MongoDB Atlas Stitch has is clean and simple, but I have been in the process of moving to Amazon definitively, but the transition has come with many stumbles.

**Comment by ajredniwja** [comment]
Hey @andrefedev thank-you for reaching out to us with your issue.

To learn how to authenticate an anonymous user, you can find a scenario [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-scenarios.html)

Please reach out if that doest solve your problem.
