### ISSUE TITLE
DocumentClient returns value has data type is Sets is not an array.

### ISSUE THREAD

**Issue by zcmgyu** [aws/aws-sdk-js#3194]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

DocumentClient returns value has data type is Sets is not an array.
I tried with StringSet, NumberSet, and List, just data type is list return an array.
I made a workaround by using JSON to convert to string and parse again to object.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**

Yes

**Details of the browser/Node.js version**

NodeJS: v12.16.0

**SDK version number**

 aws-sdk: 2.651.0

**To Reproduce (observed behavior)**

If you notice that just only `list` returns array type, `stringSet`, and `numberSet` are not.
Workaround by converting and parsing helped in convert `stringSet` and `numberSet` to an array

* DynamoDB record:

<img width="1146" alt="Screen Shot 2020-04-02 at 14 13 59" src="https://user-images.githubusercontent.com/13638569/78212966-41026000-74ec-11ea-8c64-b8181ab12e38.png">

* Lambda:

```
const AWS = require('aws-sdk');

const docClient = new AWS.DynamoDB.DocumentClient({
  convertEmptyValues: true,
});

exports.handler = async (event) => {
  const client = await docClient.get({
    TableName: 'table-name',
    Key: {
      'PK': 'abc_123',
      'SK': 'meta'
    }
  }).promise();

  const { stringSets, numberSets, list } = client.Item;

  const convertedStringSets = JSON.parse(JSON.stringify(client.Item.stringSets));

  const response = {
    statusCode: 200,
    body: JSON.stringify({
      stringSets,
      typoOfStringSets: typeof stringSets,
      stringSetsIsArray: Array.isArray(stringSets),
      numberSets,
      typoOfNumberSets: typeof numberSets,
      numberSetsIsArray: Array.isArray(numberSets),
      list,
      typoOfList: typeof list,
      listIsArray: Array.isArray(list),
      convertedStringSets,
      typoOfConvertedStringSets: typeof convertedStringSets,
      convertedStringSetsIsArray: Array.isArray(convertedStringSets),
    }),
  };
  return response;
};
```

* Response: 

```
{
  "stringSets": [
    "hello",
    "world"
  ],
  "typoOfStringSets": "object",
  "stringSetsIsArray": false,
  "numberSets": [
    2,
    1
  ],
  "typoOfNumberSets": "object",
  "numberSetsIsArray": false,
  "list": [
    "Hello",
    "World"
  ],
  "typoOfList": "object",
  "listIsArray": true,
  "convertedStringSets": [
    "hello",
    "world"
  ],
  "typoOfConvertedStringSets": "object",
  "convertedStringSetsIsArray": true
}
```

**Expected behavior**

StringSet, NumberSet, BinarySet data types could return an array without parsing.

**Comment by ajredniwja** [comment]
Hey @zcmgyu thank-you for reaching out to us with your issue, I don't think this is necessarily a bug with the SDK, this change would need a change in the  service model on what is returned from the service, making that change can be a breaking change for many customers hence I don't think it will be implemented. 

Since you have already extracting the data correctly, please reach out if you have any other questions, would like to close the issue now.
