### ISSUE TITLE
Updating Angular Material progress-bar based on the upload progress.

### ISSUE THREAD

**Issue by Alsmith141510** [aws/aws-sdk-js#3199]
Confirm by changing [ ] to [x] below:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Issues with updating Angular Material progress-bar based on the progress. The progress is reported to the console.log but the progress-bar doesn't reflect the progress
My Stack

Angular CLI: 7.3.9
Node: 10.15.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/fire                     5.2.3
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

I am uploading files to the AWS s3 bucket and the upload works fine. I am getting a return of the upload progress in the cosole.log.

Unfortunately I cannot figure out the reason why the Angular material progress bar doesn't refresh according to the 'fileUploadProgress'. I tried initalizing it at 10 and it displays the bar but does not indicate the progress.
Appreciate any help and guidance. The component code and HTML for mat-progress-bar is given below.

```
export class FileuploadComponent implements OnInit {
constructor(private uploadService: UploadFileService) {}
showSummary = false;
selectedFile: File = null;
image: boolean;
showimage = false;
previewUrl: any = null;
displayUrl: any = null;
displayFile: File = null;
locationUrl: any = null;
fileUploadProgress = 10;
uploader: any;
progress: any;
key: string;
upload1(): void {
const params = {
Key: this.selectedFile.name,
Bucket: environment.amazons3.bucket,
Body: this.selectedFile,
ACL: 'private'
};
this.fileuploading = true;
// tslint:disable-next-line:only-arrow-functions
this.uploadService.getAWSparameters().upload(params, function(err, data) {
if (err) {
console.log('There was an error uploading your file: ', err);
return false;
} else {
// this.fileuploading = false;
this.locationUrl = data.Location;
this.progress = data.progress;
this.serviceBucketName = data.Bucket;
this.s3response = data;
}
}).on('httpUploadProgress', function(e) {
this.fileUploadProgress = Math.round(100.0 * (e.loaded / e.total));
console.log('% completed is ' + this.fileUploadProgress + '%' + '. Loading' + e.loaded + ' of ' + e.total);
}
);
}
}
```
on the FileuploadComponent.html

```
<div>
<mat-progress-bar progressbarId="pbar" mode="determinate" height="20px" [value]="this.fileUploadProgress" [bufferValue]="this.fileUploadProgress"</mat-progress-bar>
<div> Upload progress: {{ this.fileUploadProgress }} </div>
</div>
```
The value doesn't change if the modificationis inside the 'httpUploadProgress' but if i reset to any value outside it (in the upload1 function) the vlaue is displayed.

**Comment by ajredniwja** [comment]
Hey @Alsmith141510 Thank-you for reaching out to us with your issue, correct me if I am wrong, you are trying to access the value of `fileUploadProgress` in a separate HTML file? 

At that point I don't think it will be an SDK related issue but how the value is accessed using the SDK since `httpUploadProgess` is emitted once when the entire payload has already been loaded into memory. 

Please refer to the conversation in https://github.com/aws/aws-sdk-js/issues/1323 and https://github.com/aws/aws-sdk-js/issues/1945

Please reach out if you have additional questions.
