### ISSUE TITLE
CredentialsError: Could not load credentials from CognitoIdentityCredentials

### ISSUE THREAD

**Issue by codeztech-atique** [aws/aws-sdk-js#3200]
AWS CredentialsError S3: Could not load credentials from CognitoIdentityCredentials

AWS SDK Version -  "aws-sdk": "^2.286.2",

I am using the logged AWS Cognito. After making the Logging I am trying to upload the image into s3 bucket. I don't wanna pass my accessKey and accessId in code. What I am doing -

**I am using Angular 8+**

```
import * as AWS from 'aws-sdk';


AWS.config.update({
      region: Config.settings.userPool.region,
      credentials: new AWS.CognitoIdentityCredentials({
        IdentityPoolId: Config.settings.userPool.identityPoolId,
      }),
    });

const params = {
      Bucket: Config.settings.buckets3.imageS3,
      Key: this.FOLDER + file.name,
      Body: file,
      ContentEncoding: Config.settings.buckets3.contentEncoding,
      ContentDisposition: Config.settings.buckets3.contentDisposition,
      ContentType: Config.settings.buckets3.contentType,
    };
    const s3Bucket = new AWS.S3({});

return new Promise((resolve, reject) => {
      s3Bucket.upload(params, function (err, data) {
        if (err) {
          const print = console.log;
          print('There was an error uploading your file: ', err);
          reject(err);
        } else {
          const print = console.log;
          print('Successfully uploaded file.', data);
          data.Location = data.Location.replace('s3.ap-south-1.amazonaws.com/', '');
          resolve(data);
        }
    });
```

**Testing purpose - For Checking the credential is correct or not**

```
AWS.config.getCredentials(function (err) {
      if (!err) {
        console.log(AWS.config.credentials.accessKeyId);
      } else {
        console.log(err);
      }
    });
```

**Comment by ajredniwja** [comment]
Hey @codeztech-atique thank-you for reaching out with your issue.

A few things to check and answer, 

1. Can you try `AWS.config.credentials.refresh();` since the Cognito token expires in 60 minutes. 
2. Did you change the UserId recently?
3. Can you provide with the stack trace and update to a newer version of the SDK?

**Comment by codeztech-atique** [comment]
Hi, tried with AWS.config.credentials.refresh()
Also tried with sdk new version. But same issue.

**Comment by ajredniwja** [comment]
Can you provide the stack trace?

**Comment by codeztech-atique** [comment]
Issue resolved. I am closing it.
