### ISSUE TITLE
Connect CORS - sdk javascript

### ISSUE THREAD

**Issue by nicosli** [aws/aws-sdk-js#3206]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for previous similar issues and didn't find any solution

I have this code in my vue project:

```
AWS.config.region = 'us-west-2'; // Región
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'IDENTIFY_POOL_ID',
})

// Create a new service object
this.connect = new AWS.Connect({
    apiVersion: '2017-08-08',
    params: {
        signatureVersion: 'v4'
    }
});

var params = {
    InstanceId: 'INSTANCE_ID', /* required */
    MaxResults: 10,
};
this.connect.listUsers(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
})
```

And the result is

`Access to XMLHttpRequest at 'https://connect.us-west-2.amazonaws.com/users-summary/INSTANCE_ID?maxResults=10' from origin 'https://local.project.mx:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Response Header
```
content-length: 259
content-type: application/json
date: Thu, 09 Apr 2020 03:08:24 GMT
status: 403
x-amz-apigw-id: KsuyQFeXPHcF84g=
x-amzn-errortype: AccessDeniedException
x-amzn-requestid: bfef631b-582b-4e61-9d82-b1d8a5064d61
```

**SDK version number**
aws-sdk@2.656.0

Thank you in advance

**Comment by ajredniwja** [comment]
Hey @nicosli thank-you for reaching out to us with your issue, I am seeing the similar error while reproducing this, let me confirm with the service team if they support CORS for connect or not.

**Comment by nicosli** [comment]
> Hey @nicosli thank-you for reaching out to us with your issue, I am seeing the similar error while reproducing this, let me confirm with the service team if they support CORS for connect or not.

Hi, do you have news?

**Comment by ddo88** [comment]
Same problem here but with datasync 


` AWS.config.region = 'us-east-1'; 
  AWS.config.credentials = new AWS.CognitoIdentityCredentials({IdentityPoolId: 'MyPoolId'});
  var datasync = new AWS.DataSync();
  var params = {
	TaskExecutionArn: 'taskARN' 
  };
  datasync.describeTaskExecution(params, function(err, data) {
		if (err) console.log(err, err.stack); // an error occurred
		else     console.log(data);           // successful response
  });`


result
![imagen](https://user-images.githubusercontent.com/885227/92264227-86fc8f00-eea3-11ea-84a3-1b458fa00fa8.png)

**Comment by josefyendif** [comment]
How to solve this, i am also facing same issue

**Comment by ajredniwja** [comment]
To solve the issue you might want to use, [API https://aws.amazon.com/api-gateway/](https://aws.amazon.com/api-gateway/). 
Which is basically creating a proxy which will call the Connect or datasync API and then the browser can make calls to that.
