### ISSUE TITLE
How to set the AWS Credentials ONCE?

### ISSUE THREAD

**Issue by denchp** [aws/aws-sdk-js#3207]
Confirm by changing [ ] to [x] below:
- [ X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I'm trying to set up a React web app with the sdk using a React context to provide access to the SDK via components.  In the context declaration I have this code:
```
export default class AWSContext {
    constructor() {
        AWS.config.credentials = new AWS.Credentials(awsconfig.accesskey, awsconfig.secretkey);
    }

    getMenuItems = (itemIds) => {
        var lambda = new AWS.Lambda({ region: 'us-east-2', apiVersion: '2015-03-31 ' });
    
        return lambda.invoke({
            FunctionName : 'getMenuItemsForUser-dev',
            InvocationType : 'RequestResponse',
            LogType : 'None'
        }, (err, data) => console.log(data));
    }
}
```

We're simply using the key/secret for development, so that gaping security hole aside...

When a component attempts to call getMenuItems() the credentials are null. 

Is it possible to do this?

**Comment by ajredniwja** [comment]
Hey @denchp thank-you for reaching out to us with your issue, please refer to https://github.com/aws/aws-sdk-js/issues/1531 as this seems to be a similar issue. 

You'd have to set up credentials as you'd do in a browser script.
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-browser.html

Closing the issue now, please reach out if that doesn't solve the problem or if I am missing anything.
