### ISSUE TITLE
Get S3 object metadata using a signed url

### ISSUE THREAD

**Issue by karimi** [aws/aws-sdk-js#3208]
Confirm by changing [ ] to [x] below:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Is it possible to get the metadata of an S3 object using a signed url?

I'm creating the url using `var url = s3.getSignedUrl("getObject", params);` , returned url just downloads the object, is there a way to get the metadata of the object using this url?

**Comment by ajredniwja** [comment]
Hey @karimi thanks for reaching out, unfortunately the `getSignedUrl` call only returns a string of the URL. 

If you like you can get the metadata using something like:
```
s3.getObject(params, function (err, data) {
    if (err) console.log(err);
    else
        console.log(this.httpResponse.headers);
});
```

Closing this issue now, please reach out if you have any additional questions or if I am missing anything.
