### ISSUE TITLE
Pagination with Filtering in DynamoDB Template

### ISSUE THREAD

**Issue by tahafarooqui** [aws/aws-sdk-js#3209]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution.
  
**Describe the bug**

I would like to implement a DynamoDB Scan OR Query with the following logic:

`Scanning -> Filtering(boolean true or false) -> Limiting(for pagination)`

However, I have only been able to implement a Scan OR Query with this logic:

`Scanning -> Limiting(for pagination) -> Filtering(boolean true or false)`

I would like to be able to filter a pagination result before the limit is taken into consideration. 

I have already tried Global Secondary Index but it didn't work in my case  Because I have 5 different attributes to filter and limit.

**Note:** Fix this issue OR Create any feature that will apply limit after filter.

**Comment by ajredniwja** [comment]
Hey @tahafarooqui thank-you for reaching out, I am not able to really understand your use case, can you provide some code samples.
