### ISSUE TITLE
SQS receiveMessage not working

### ISSUE THREAD

**Issue by pratik007kumar** [aws/aws-sdk-js#3212]
Confirm by changing [ ] to [x] below:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
**SQS receiveMessage not working**
```
const AWS = require("aws-sdk");
var sqs = new AWS.SQS({apiVersion: '2012-11-05'});
var queueURL = "https://sqs.eu-west-1.amazonaws.com/00000000000/XYZ";

var params = {
 AttributeNames: [
    "SentTimestamp"
 ],
 MaxNumberOfMessages: 1,
 MessageAttributeNames: [
    "All"
 ],
 QueueUrl: queueURL,
 VisibilityTimeout: 0,
 WaitTimeSeconds: 0
};
 
module.exports.getMessage = async (event, context, callback) => {
  
console.log('SQS response');
let response= sqs.receiveMessage(params, function(err, data) {
console.log('Fetch SQS');
 console.print(err);
 console.print(data);
  
});
}
```
 it is not showing any error message or any response

**Comment by KnupMan** [comment]
Can you also provide an example of the messages? I also don't have any error message or response, but only if my message is `" "` (has just empty space).

**Comment by ajredniwja** [comment]
> Can you also provide an example of the messages? I also don't have any error message or response, but only if my message is `" "` (has just empty space).


@pratik007kumar have you confirmed this?
