### ISSUE TITLE
InvalidSignatureException error when call iot.attachPolicy

### ISSUE THREAD

**Issue by GrowingCompany** [aws/aws-sdk-js#3213]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Hi,

I'm developing react-native app with amplify-js
I working on attach policy to PubSub
I used this code(https://gist.github.com/pveller/fc7660bdfaf19eed4b29b2e9415c3917)

It's working on Android platform
but, in iOS return error
error is:
`message:"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."
name:"InvalidSignatureException"`

I don't know why return error only in iOS
Please give me advice
Thank you!

**Comment by ajredniwja** [comment]
Hey @GrowingCompany thank-you for reaching out to us with your issue, I think this should be an issue for the amplify team, I am not able to transfer the issue to their repo directly, feel free to open an issue at https://github.com/aws-amplify/amplify-js. 

Please reach out if you have questions or you think differently.
