### ISSUE TITLE
Before await S3 upload promise finishes, it moves to next statement.

### ISSUE THREAD

**Issue by iamrahulroy** [aws/aws-sdk-js#3216]
Confirm by changing [ ] to [x] below:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
`notifyService` is getting called before s3 upload finishes even though await is being used. How do I ensure completion of s3 upload before the execution of `notifyService`? 

Code Snippet:
```
module.exports.fileConverterHandler = async function(event, context, callback) {
  await downloadFile();
  await convertFile(inputFile, outputFile);
  await uploadConvertedFileToS3();
  await notifyService()
  return success({ message: 'success'});
};

function convertFile(inputFile, outputFile) {
  return new Promise(async (resolve, reject) => {
    gm(inputFile)
      .setFormat()
      .resize()
      .quality()
      .write(outputFile, function(error){
        if (!error) {
          resolve();
        } else {
          reject();
        }
      });
  });
}

function uploadConvertedFileToS3({ outputFilePath }) {
  const outputFileBuffer = readFileSync(outputFilePath);
  const uploadParams = {
    Bucket: ...,
    Key: ...,
    Body: outputFileBuffer,
    ContentType: ...
  }
  const s3 = new S3();

  return s3.upload(uploadParams).promise();
}
```

**Comment by ajredniwja** [comment]
@iamrahulroy Thank-you for reaching to us with your issue, I am not able to reproduce the case in my tests, I don't think the problem is related to the SDK.

**Comment by iamrahulroy** [comment]
@ajredniwja thanks for the response. Can you at least point me in the right direction? Maybe doc link? does the method from the above snippet `uploadConvertedFileToS3` has any flaw?

_PS: I understand this might not be the right place to ask the question. Perhaps AWS forum would a better choice?_

**Comment by ajredniwja** [comment]
@iamrahulroy nothing looks wrong with the method you mentioned, I tested using the similar code:

```
function uploadConvertedFileToS3() {
    const uploadParams = {
        Bucket: "abc-abc",
        Key: "docImagewoho",
        Body: fs.createReadStream("/Documents/workspace/abc.dmg") ,
    };
    
    return s3.upload(uploadParams).promise();
}
```

**Comment by iamrahulroy** [comment]
@ajredniwja thanks for the confirmation.

**Comment by rsibanez89** [comment]
I experience the same issue await is not waiting until upload finishes:
I try to upload a file from an external URL to my S3
```
async uploadFileFromUrl(url: string, fileName: string): Promise<boolean> {
    const image = (
      await this.httpService.axiosRef({
        url: url,
        method: 'GET',
        responseType: 'arraybuffer',
      })
    ).data as Buffer;

    await this.s3Client
      .upload({
        Bucket: this.bucketName,
        Key: fileName,
        ACL: 'public-read',
        Body: image,
      })
      .promise();

    return true;
  }
```
