### ISSUE TITLE
Unexpected token 'const' on Windows Safari 5.1, ts-lib dependency.

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws/aws-sdk-js#3219]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Running Angular 9 app build to es5 on Windows Safari 5.1 is throwing `unexpected token 'const'` and when I build it without optimisation, I see it is happening in the tslib.es6 library. 
Firstly, I don't understand why Safari doesn't support const, but that is a different story.

**Is the issue in the browser/Node.js?**
Safari 5.1 on Windows (browser stack)

**SDK version number**
V2.632.0

**To Reproduce (observed behavior)**
Run an Angular 9 app with amplify and you should probably get this issue

**Expected behavior**
I didn't expect any error. I have been adding polyfills:
```
import 'promise-polyfill/src/polyfill';
import 'core-js/es/typed-array/uint32-array';
import 'core-js/es/array/find';
import 'core-js/es/object/assign';
import 'core-js/es/object/entries';
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5285035/79536030-5ff31b80-80c2-11ea-8b55-2d44cfb7cda8.png)

**Additional context**
So it looks like one of the AWS dependencies loads  loads the tslib.es6.js, but it doesn't get converted to es5. So maybe I have to manually convert it with babel??

**Comment by mattiLeBlanc** [comment]
Possible not related to AWS

**Comment by mattiLeBlanc** [comment]
Actually I just build a standard Angular 9 app and deployed it and I am not getting these issues.
So maybe it is not  Angular causing this. Could any of the AWS packages use tslib.es6?

**Comment by mattiLeBlanc** [comment]
I am also having issues with IE11:

![image](https://user-images.githubusercontent.com/5285035/79737832-3e529800-833f-11ea-845e-1d24af7b95be.png)


![image](https://user-images.githubusercontent.com/5285035/79737805-3692f380-833f-11ea-98be-f4da1201209a.png)

Apparently it doesn't like the fat arrow, and I think that is coming from the same es6 file.
So do we need to babel this file ourselves to es5?

**Comment by ajredniwja** [comment]
Hey @mattiLeBlanc thank-you for reaching out to us with your issue, I am not sure how this problem might be related to the SDK at all, can you share your thoughts on how it might be related to the SDK? 
I would also check the package.json

**Comment by mattiLeBlanc** [comment]
Hi @ajredniwja ,

If you look at the screenshot above it is the tslib file, and one of the AWS packages is loading this, it might actually be Amplify. So maybe not SDK.

**Comment by ajredniwja** [comment]
@mattiLeBlanc I actually don't see SDK using that file, it should be Amplify then. Thanks
