### ISSUE TITLE
Organizations() is missing from aws-sdk

### ISSUE THREAD

**Issue by bhaveshbarskar** [aws/aws-sdk-js#3222]
Hey,

Organizations() constructor is not added under aws-sdk, I installed aws sdk but not able access Organizations. 

Cannot call AWS.Organization({params}) it says Organization  in not a constructor but it is available in aws documentation.
importing AWS from "aws-sdk" for my JS code.

**Comment by ajredniwja** [comment]
Hey @bhaveshbarskar thank-you for reaching out to us with your issue, can you please share the code that you are using to instantiate the constructor?

Can you please make sure that you're using `new` keyword?

`const orgs = new AWS.Organization({params})`

**Comment by bhaveshbarskar** [comment]
Hey @ajredniwja , here is the code I am using to instantiate the cons.

const org = new AWS.Organizations({ 'prams like cred, region, etc' })

Here is the following error I get in my console : 
environment.tsx:28 Uncaught TypeError: aws_sdk__WEBPACK_IMPORTED_MODULE_0___default.a.Organizations is not a constructor

I also tried to console.log(AWS) to see the list of available constructors, I dont see the Organizations() in that list as well, but the AWS API guide says it is available.

**Comment by ajredniwja** [comment]
I am able to instantiate the constructor,

I have installed `aws-sdk` using `npm`: `npm install aws-sdk`
npm is automatically installed when you download node please refer to: https://www.npmjs.com/get-npm

To get started with the JS-SDK: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/getting-started-nodejs.html

Can you please follow the steps mentioned in above links, reach out if you still have any questions.

**Comment by rjjaeger** [comment]
Hello,

I've also encountered this bug today. Here's sample code to reproduce. Copy and paste it into a file and open with FireFox with Developer tool bar.
```
<html>
<head>
    <title>AWS SDK for JavaScript - Sample Application</title>
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.662.0.min.js"></script>
</head>
<body>

    <script type="text/javascript">

    var organizations = new AWS.Organizations({apiVersion: '2016-11-28'});

    </script>

</body>
</html>
```

**Comment by ajredniwja** [comment]
Able to reproduce it, not sure what is the cause meanwhile you can use 

https://sdk.amazonaws.com/builder/js/

To build your own SDK and I have confirmed that it works.

**Comment by ajredniwja** [comment]
Only services that have CORS: TRUE are bundled with that link i.e https://sdk.amazonaws.com/js/aws-sdk-2.662.0.min.js

 https://github.com/aws/aws-sdk-js/blob/a8ada345c45e145720b36969a882b4e04a2467a6/apis/metadata.json

I have already mentioned how to build your own customized browser in my last comment.

**Comment by bhaveshbarskar** [comment]
Found the Organizations inside other folder, need to import it from 
--- import Organizations from "aws-sdk/clients/organizations" it works. 

Thanks @ajredniwja
