### ISSUE TITLE
DynamoDB Streams ApproximateCreationDateTime format does not match examples

### ISSUE THREAD

**Issue by RossWilliams** [aws/aws-sdk-js#3225]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
ApproximateCreationDateTime is returned in ISO8601 format when using AWS.DynamoDBStreams.getRecords from a shard, but documentation suggests it should be a number. Documentation around code needs to specify that returned value is ISO8601 string. Annoyingly, when accessing records in a DynamoDB Stream Lambda destination, the value is in fact a unix timestamp number.
The examples and documentation specify this is a unix timestamp [here](https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/apis/streams.dynamodb-2012-08-10.examples.json#L83) and [here](https://github.com/aws/aws-sdk-js/blob/55a97ad8726b14f228a9182768680c2051386593/apis/streams.dynamodb-2012-08-10.min.json#L111) and [here](https://github.com/aws/aws-sdk-js/blob/67081dcf5c07bd26cd06e9262149b522430c5e12/clients/dynamodbstreams.d.ts#L331)

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes, and Local
**Details of the browser/Node.js version**
v12

**SDK version number**
2.624.0
**To Reproduce (observed behaviour)**
```
// pseudo code
let client = new AWS.DynamoDBStreams()
let stream = await client.describeStream();
let records = await stream.shards.map(shard => client.getShardIterator(shard)).map(iterator => iterator.getRecords());
records.forEach(r => console.log(r))
```

notice ApproximateCreationDateTime is a string in IS8601 format
**Expected behaviour**
Record items have ApproximateCreationDateTime in unix timestamp format, or documentation is updated to specify it as an ISO8601 string

**Comment by ajredniwja** [comment]
Hey @RossWilliams thank-you for reaching out and submitting this report, reached out to the service team as these docs are generated by the service team.

Will update once the changes are made.
