### ISSUE TITLE
Message arrives with ApproximateReceiveCount increased

### ISSUE THREAD

**Issue by garrydias** [aws/aws-sdk-js#3227]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When performing Javascript SQS SDK receiveMessage function over a queue created with redeliveryPolicy, sometimes the message is not received.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
1- Sometimes the application does not receive any message, but the message is sent to dlq with ReceiveCount property set to 3 (as I checked in aws sqs console)

2- Sometimes the application receives the message, but the ApproximateReceiveCount is  set to 2 instead of 1

3- Sometimes the application receives the message with ApproximateReceiveCount set to 1, does NOT receive the same message with ApproximateReceiveCount set to 2, but the message is sent to dlq instead and its ReceiveCount property is set to 3

4- Sometimes the application receives the message with ApproximateReceiveCount set to 1,  receives the same message with ApproximateReceiveCount set to 2 and is sent to DLQ with its ReceiveCount property set to 3, as expected

PS: the dlq sending is managed by RedeliveryPolicy. The application does not manage retrials.

**SDK version number**
2.653.0

**To Reproduce (observed behavior)**
Run receiveMessage but do not delete the message after an always failing consumption

**Expected behavior**
- start receiveMessage in a while(true) loop with VisibilityTimeout set to 10
- send a json body through aws sqs console: { "id": "1" }
- each 10 seconds, receiveMessage callback should log data.Messages[0].Attributes.ApproximateReceiveCount value. The output should be like this: 
```
console.log src/services/messaging/SqsService.ts:91
    1
console.log src/services/messaging/SqsService.ts:91
    2
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7189779/80200431-01b1c580-85f9-11ea-8782-f0fab00a72d3.png)
In this screenshot, I've performed a console.log(data.Messages). As we can see, I started the receiveMessage, sent a message and when it was fetched the ApproximateReceiveCount is 2 instead of 1.

In order to ensure no lost process could be consuming my message, I always run  **sudo pkill node** before run my application

Appreciate any help

**Comment by ajredniwja** [comment]
Hey @garrydias apologies for late reply, can you please provide a code example for repro? 

I was not really able to reproduce this.

**Comment by charlescapps** [comment]
Isn't that why it's called "Approximate"? I assume this is due to the nature of distributed systems/queues.
