### ISSUE TITLE
Fix ==> Getting 'CredentialsError: Missing credentials in config' when using assume role

### ISSUE THREAD

**Issue by moussouba** [aws/aws-sdk-js#3230]
The solution is to import the .env config at the firts line before all

const dotenv = require('dotenv');
dotenv.config();
const AWS = require('aws-sdk');

AWS.config.update({
    accessKeyId: process.env.AWS_ACCESS_KEY,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
});

const s3 = new AWS.S3();
...

**Comment by klsetzer** [comment]
Note: @klsetzer == @swa-ti-ci 

I also tried with and without `export AWS_SDK_LOAD_CONFIG=1`.  That had no effect.

**Comment by ajredniwja** [comment]
Hey guys, @moussouba thank-you for providing a workaround, I believe other people may have different questions as well, please post an issue with your use case using the [issue template](https://github.com/aws/aws-sdk-js/issues/new/choose). 

To track the issue I am going to keep it open.

**Comment by ajredniwja** [comment]
> listbuckets-error.txt

Can you share how your config files look and the list of all AWS env vars you can do that by using the command `printenc | grep AWS`
