### ISSUE TITLE
SDK looks for credential file although account is set to leverage IAM Roles

### ISSUE THREAD

**Issue by davcevski** [aws/aws-sdk-js#3233]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**The error**

While deploying to AWS, I am getting the following error:

```
Error: ENOENT: no such file or directory, open '/root/.aws/credentials'
```

Using `aws-sdk 2.610.0` and working with dynamodb.

However as explained in the title, my account is set to leverage IAM roles, and according to this [documentation](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-iam.html) I should not provide the credential file.

**What I have**

I had many iterations of the code, however in order to debug this I went bare minimum, and basically the code looks like:

```
dynamodb = new AWS.DynamoDB({
        apiVersion: '2012-08-10',
        region: 'eu-west-1'
    });
```

I also have ENV variable `AWS_REGION` in my docker set to the default region. 

**What I tried**

Tried assuming the role trough STS -> no luck
Tried setting up `AWS_SDK_LOAD_CONFIG=true` along with `AWS_PROFILE=assume-role-profile` -> no luck as well

**Comment by klsetzer** [comment]
I see you set AWS_REGION, but the docs indicate it should be AWS_DEFAULT_REGION.  Have you tried that?

[https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.htmll)

**Comment by davcevski** [comment]
> I see you set AWS_REGION, but the docs indicate it should be AWS_DEFAULT_REGION. Have you tried that?

**Comment by davcevski** [comment]
> I see you set AWS_REGION, but the docs indicate it should be AWS_DEFAULT_REGION. Have you tried that?

I have not. Good catch, I will try this. However, the link you've sent returns 404

**Comment by ajredniwja** [comment]
> I have not. Good catch, I will try this. However, the link you've sent returns 404

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

**Comment by rrrix** [comment]
This bug is really, really old, has been happening to me for a long time. I automated my work-around for it a very long time ago in all of my containers, it's simple :) 

```bash
$ touch ~/.aws/credentials
```

Doesn't fix the bug, definitely fixes the symptom though. 

Also you can set your Credential Provider explicitly, if you know what it will be. I _think_ this also is a workaround, without touching the credentials file. 

```javascript
const AWS = require('aws-sdk');
AWS.config.update({ region: 'eu-west-1' });
AWS.config.credentials = new AWS.EC2MetadataCredentials();
```

P.S. You can set your default region using `AWS.config.update({region: 'eu-west-1'})` - this will default every new client you create _after_ that to using your new default region.

> ... Service-specific configuration data is applied after applying the global configuration settings. ([Creating Service Objects](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/creating-and-calling-service-objects.html#creating-service-objects))

P.P.S You can typically omit the API Version for a given client and it will automatically use the latest version. ([Locking API Versions](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/locking-api-versions.html))

**Comment by davcevski** [comment]
Thanks for the responses, this issue got solved for me. It ended up being a k8 issue. The deploy was somehow stuck to an older version that had this issue. I did some code changes meanwhile so to be honest, I am not sure which one fixed the issue, since there were few deploys in-between that were not picked up. However, I can tell that barebone dynamodb setup works now.

**Comment by ajredniwja** [comment]
@davcevski closing this issue now, please reach out if you have any further questions.

Please leave a comment if you find out what fixed the issue for you thanks.
