### ISSUE TITLE
in event-stream, callback can be called multiple times

### ISSUE THREAD

**Issue by motizharfati** [aws/aws-sdk-js#3234]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Callback called multiple times in "EventUnmarshallerStream.prototype._transform" method
It happens when i try to download a 1.8GB CSV file that generated from athena.
I guess it happens after "return callback()" line cause an error for some reason,
the exact error is:
Unhandled rejection Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
at EventUnmarshallerStream.afterTransform (_stream_transform.js:87:31)

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
It's running in EC2

**Details of the browser/Node.js version**
v.12.14.1

**SDK version number**
2.619.0

**Expected behavior**
I expected that on error on this line: "return callback();" the "catch" will not call
the callback again

**Comment by ajredniwja** [comment]
Hey @motizharfati thank-you for reaching out to us with your issue, can you please share the code you are using to reproduce the error?

**Comment by motizharfati** [comment]
HI @ajredniwja , Actually i think it's not a bug of aws because when i tried to download the file (using node js) without additional pipes than everything worked. I think the error is in different area, however i don't understand why node js producing the error stack on aws-sdk line.
