### ISSUE TITLE
Allow empty Dynamodb Sets to be instantiated

### ISSUE THREAD

**Issue by lintal** [aws/aws-sdk-js#3235]
**Is your feature request related to a problem? Please describe.**
I want to create a script to initialise documents in a clean/empty DynamoDB environment.
One of these documents should contain a StringSet however with no values initially.

I wish to run something like:

```js
const DynamoDBSet = require('aws-sdk/lib/dynamodb/set');

const mySet = new DynamoDBSet([]);
```

The above however returns an exception reading: `InvalidSetType: Sets can contain string, number, or binary values`
(Comes from: https://github.com/aws/aws-sdk-js/blob/b6d3eba/lib/dynamodb/set.js#L36-L41)

I would like to be able to create this object without an exception being thrown, however being able to specify the set type on instantiation.

**Describe the solution you'd like**

Support for an interface similar to the following will be ideal:

```js
const DynamoDBSet = require('aws-sdk/lib/dynamodb/set');

const mySet = new DynamoDBSet([]);
mySet.setType('String');

console.log(mySet);
// Set { wrapperName: 'Set', values: [ ], type: 'String' }
```

**Describe alternatives you've considered**
My workaround is as follows:

```js
const DynamoDBSet = require('aws-sdk/lib/dynamodb/set');

function createEmptyStringset() {
  const set = new DynamoDBSet(['temp_value']);
  set.values = [];

  return set;
}
```

**Additional context**
No.

**Comment by lintal** [comment]
I realise now that saving an empty stringset is also not possible, so for now I am setting in a wanted value and persisting that instead.

**Comment by abhilash1in** [comment]
DynamoDB service doesn't allow storing empty sets (irrespective of type). From [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html):

> An attribute value cannot be an empty string or empty set (string set, number set, or binary set). However, empty lists and maps are allowed. For more information, see [Attributes](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-attributes).

And it indeed works this way:
![Screen Shot 2020-05-06 at 10 15 30 PM](https://user-images.githubusercontent.com/9111980/81257057-26d60900-8fe7-11ea-977e-4fcce22f64eb.png)

I don't think there's anything the AWS JS SDK can do about it.

**Comment by lintal** [comment]
I agree. Thanks for looking.
