### ISSUE TITLE
postText doesn't return sessionAttributes for dialogAction type 'Delegate'

### ISSUE THREAD

**Issue by plotic** [aws/aws-sdk-js#3243]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm trying to build a chatbot infrastructure by using AWS API Gateway and AWS Lex. I have attached for API and Lex bot a separate lambda function. When invoking the Lex with lexruntime.postText i trigger the Lex lambda function. In this lambda function i want to set some sessionAttributes and return the response with DialogAction's type "Delegate". The bug is that sessionAttributes are not being 
returned. But if DialogAction's type is "Close" the sessionAttributes is getting returned.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
YES, AWS almbda

**Details of the browser/Node.js version**
v12.12.0

**SDK version number**
2.631.0
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
 Lambda 1 (AWS API Gateway)
```
  var params = {
        botAlias: '$LATEST',
        botName: 'SampleBot',
        inputText: "hey", 
        sessionAttributes: {},
        userId: "userId"
    };
  
    return await lexruntime.postText(params, function(err, data) {
        if (err) { 
            console.log(err.errorMessage)
        }
        else {     
            console.log('Lambda invoked')
        }
    }).promise();
```

Lambda 2
```

  const welcomeIntent = (intentRequest, callback) => {
    const sessionAttributes = intentRequest.sessionAttributes;        
    if (intentRequest.invocationSource === 'DialogCodeHook') {
        sessionAttributes.someAttribute = "someValue"  
         callback(delegate(sessionAttributes, intentRequest.currentIntent.slots));    
        return
    }
    callback(close(sessionAttributes, 'Fulfilled', { contentType: 'PlainText', content: 'Thanks' }));
  };

  const delegate = (sessionAttributes, slots) => ({
    sessionAttributes,
    dialogAction: {
      type: 'Delegate',
      slots      
    },
  });
```
lexruntime.postText returns an empty sessionAttributes

**Expected behavior**
lexruntime.postText should return sessionAttributes with data set in Lex's Lambda 

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @plotic Apologies for late reply, I was not able to reproduce this locally, can you make sure you are using the guidelines mentioned [here](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html#nodejs-package-dependencies) to ship the latest version of the SDK.
