### ISSUE TITLE
502 Bad Gateway / No response

### ISSUE THREAD

**Issue by Schoko19961** [aws/aws-sdk-js#3244]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm running a Nodejs server with Fastify which I use to get data from the s3-Bucket with the getObject function.

When I request a file via Fastify, two things can happen (randomly):
1. File loads successfully
2. Request is stuck in Pending for a long time and I get a "502 Bad Gateway" error. This error however is only appearing in the frontend. In the backend, neither the callback is called, nor is the promise being resolved. I don't get any error messages.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No, Fargate.

**Details of the browser/Node.js version**
Running inside "node:12-alpine" Docker

**SDK version number**
"aws-sdk": "^2.670.0"

**To Reproduce (observed behavior)**
```typescript
    const s3client = new AWS.S3({
      endpoint: this.configService.get<AwsConfig>('aws').endpoint,
      s3ForcePathStyle: true,
    });
    this.logger.debug('This log is called');
    await s3client.getObject({
        Bucket: this.configService.get<AwsConfig>('aws').Bucket,
        Key: url,
      }).promise();
    this.logger.debug('This log is not called');
```

**Expected behavior**
Expected promise to be rejected, callback to be called with an error or any other kind of error.

**Additional context**
It is running in a VPC. There seem to be problems with the proxy, but nevertheless I would expect the aws-sdk to throw an error.
Same issue with adminGetUser from CognitoIdentityServiceProvider.

The proxy is configured with the proxy-agent package(v3.1.1) as follows.
```typescript
      const agent: any = new ProxyAgent(
        process.env.HTTPS_PROXY ? process.env.HTTPS_PROXY : process.env.HTTP_PROXY,
      );
      AWS.config.update({
        httpOptions: {
          agent,
          timeout: 60000,
        },
        sslEnabled: true,
      });
```

**Comment by philipwigg** [comment]
I don't see any callbacks or catching of errors in the code you supplied?

What happens if you wrap the call to `getObject()` in a try/catch?
