### ISSUE TITLE
Duplicating #3156 - "Cannot get credentials using credential_process in config file"

### ISSUE THREAD

**Issue by corrjo** [aws/aws-sdk-js#3247]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
#3156 Should probably be reopened. 

I'm trying to get it working with aws-cdk 

boto3 is able to use credential_process just fine, but the js sdk doesn't seem to run it.

**Comment by corrjo** [comment]
Unless @TheRyanBurke was able to solve his issue and would like to share?

**Comment by ajredniwja** [comment]
Hey @corrjo thank-you for reaching out to us with your issue, wanted to mention that profile prefix had nothing to do with it, let me get back to you after I reproduce it.

**Comment by corrjo** [comment]
Thanks @ajredniwja, I appreciate the help. I'll update the issue if I find anything else out.

**Comment by lstatro** [comment]
I'm having a similar issue, but maybe this isn't a supported feature of the aws-sdk-js?

I've tried using a provider in either the `~/.aws/config` or the `~/.aws/credentials`  file and got the same behavior.  I can run cli commands just fine using those profiles.  So it's only an issue when I'm using the sdk to call my profile. 

Poking at the aws [docs](https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-credential_process.html), maybe aws-sdk-js doesn't support using `credential_process`?  The docs callout boto3, .net, php but not js.  So maybe this is a "hey we don't support this" kind of thing? 

For what here are some specific details.  Also, I'm using aws-vault as my provider.

```
# in ~/.aws/config
[profile my-Profile]
credential_process = aws-vault exec my-Profile --json
```

also tried this and got similar results

```
# in ~/.aws/credentials
[my-Profile]
credential_process = aws-vault exec my-Profile --json
```

sdk version: `"aws-sdk": "^2.787.0",`

```typescript
  /** here's how i'm calling the profile */
    this.options = {
      credentials: new SharedIniFileCredentials({
        profile: profile,
      }),
      region: region,
    }
```

**Comment by justinmk3** [comment]
Is this fixed v3 ? https://github.com/aws/aws-sdk-js-v3

**Comment by DanyC97** [comment]
@ajredniwja any chance you can comment on the state of this issue please? is it fixed in v3 or maybe can be fixed in this version ? Asking cause the vscode-toolkit is failing big time using this method

**Comment by ajredniwja** [comment]
I believe it is fixed in V3 of the SDK, I would need to run some code to verify that.
