### ISSUE TITLE
validateStructure should skip validation if the underlying value is null or undefined

### ISSUE THREAD

**Issue by hirochachacha** [aws/aws-sdk-js#3248]
AWS APIs are updating constantly, you might be calling a new API with an older version is SDK. In
    this case you should try installing the newest `aws-sdk` like: 

    `npm install aws-sdk@latest`

    If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled
    SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
    You can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

If you still like to open an issue, change [ ] to [x] below:
- [x] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

I'm calling s3.getSignedUrlPromise inside my lambda function, something like following
```
const aws = require('aws-sdk')

const s3 = new aws.S3()

const getSignedUrl = async (operation, bucket, key, contentType) => {
  const url = await s3.getSignedUrlPromise(operation, {
    Bucket: bucket,
    Key: key,
    ContentType: contentType,
  })
}

getSignedUrl('deleteObject', 'test-bucket', 'test-key')

```
Then I saw 
```
(node:33046) UnhandledPromiseRejectionWarning: UnexpectedParameter: Unexpected key 'ContentType' found in params
```
That's because https://github.com/aws/aws-sdk-js/blob/251eeee8de7f8fb27f81ba84678c63b4e1d21dc0/lib/param_validator.js#L76-L79 doesn't care about underlying values. I think it's too strict validation for developers.
So I propose following patch.
```
diff --git a/lib/param_validator.js b/lib/param_validator.js
index 8c9530cd..b16103e7 100644
--- a/lib/param_validator.js
+++ b/lib/param_validator.js
@@ -74,8 +74,10 @@ AWS.ParamValidator = AWS.util.inherit({
         var memberContext = [context, paramName].join('.');
         this.validateMember(memberShape, paramValue, memberContext);
       } else {
-        this.fail('UnexpectedParameter',
-          'Unexpected key \'' + paramName + '\' found in ' + context);
+        if (paramValue !== undefined && paramValue !== null) {
+          this.fail('UnexpectedParameter',
+            'Unexpected key \'' + paramName + '\' found in ' + context);
+        }
       }
     }
```

**Comment by reillymarkowitz** [comment]
Am I allowed to open a PR for this? I’m a new contributor

**Comment by hirochachacha** [comment]
I'm OK with that, but I'm not sure whether this proposal will be accepted.

**Comment by ajredniwja** [comment]
This would need more discussion from the team and the community, since it can be a breaking change for some customers. 

@reillymarkowitz you are allowed to open a PR for any feature as long as you follow the contributing guidelines, found at: https://github.com/aws/aws-sdk-js/blob/master/CONTRIBUTING.md

**Comment by reillymarkowitz** [comment]
I have my changes in a local branch called `issues-3248`, but I don't have write access to the repo.

**Comment by ajredniwja** [comment]
Apologies for the delay, merged the PR.
