### ISSUE TITLE
Policy Parameter of Schemas/putResourcePolicy has wrong type in Typescript bindings

### ISSUE THREAD

**Issue by bobthemighty** [aws/aws-sdk-js#3249]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Documentation for the Schemas class is out of sync with the generated typings.

The [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Schemas.html#putResourcePolicy-property) states that the Policy parameter of the putResourcePolicy method is of type `any` but the [generated bindings](https://github.com/aws/aws-sdk-js/blob/master/clients/schemas.d.ts#L807) require a string. 

The following code sample fails to compile, because `Policy` expects a string, not an object, unless I manually hack the file `node_modules/aws_sdk/clients/schemas.d.ts` to correct the type.

```js
import { Schemas, config } from "aws-sdk";

config.logger = console;

const accountId = process.env.ACCOUNT_ID || "missing-account-id";
const registryName = process.env.REGISTRY_NAME || "my-events";
const orgId = process.env.CORGANISATION_ID || "missing-org-id";

const schemas = new Schemas();

async function createRegistry() {
  try {
    await schemas
      .createRegistry({
        RegistryName: registryName,
      })
      .promise();
  } catch (e) {
    if (e.code === "ConflictException") {
      return;
    }
    throw e;
  }
}

async function updatePolicy() {
  const policy = {
    Version: "2012-10-17",
    Statement: [
      {
        Sid: "ReadOnlyOrg",
        Effect: "Allow",
        Action: [
          "schemas:DescribeRegistry",
          "schemas:ListSchemas",
          "schemas:SearchSchemas",
          "schemas:DescribeSchema",
          "schemas:ListSchemaVersions",
          "schemas:DescribeCodeBinding",
          "schemas:GetCodeBindingSource",
        ],
        Principal: "*",
        Condition: {
          StringEquals: {
            "aws:PrincipalOrgID": [orgId],
          },
        },
        Resource: [
          `arn:aws:schemas:eu-west-1:${accountId}:registry/${registryName}`,
          `arn:aws:schemas:eu-west-1:${accountId}:schema/${registryName}/*`,
        ],
      },
    ],
  };
  await schemas
    .putResourcePolicy({
      Policy: policy,
      RegistryName: registryName,
    })
    .promise();
}

(async () => {
  await createRegistry();
  await updatePolicy();
})();

```

Passing a string to satisfy the compiler yields ` BadRequestException: Provided registry policy is invalid: This policy contains invalid Json.` because the underlying code is JSON.stringifying the parameter.

**Is the issue in the browser/Node.js?**
No :)

**If on Node.js, are you running this on AWS Lambda?**
Irrelevant, this is a compile-time issue.

**SDK version number**
v2.673.0

**Comment by ajredniwja** [comment]
Hey @bobthemighty thank-you for reaching out to us with your issue, the typings mentioned [here](https://github.com/aws/aws-sdk-js/blob/master/clients/schemas.d.ts#L807) are generated by the service team, I have reached out to them regarding this, will update you once I hear back from them.

**Comment by ajredniwja** [comment]
Hey @bobthemighty This was fixed in V3 of the SDK, would you like to try it? https://github.com/aws/aws-sdk-js-v3
