### ISSUE TITLE
AWS SQS Message: Message not reaching to SQS intermittently when sending using Lambda NodeJS in Lambda

### ISSUE THREAD

**Issue by vatsvivek** [aws/aws-sdk-js#3253]
S3 bucket on Create event triggers the lambda function. Thelambda function needs to send message to an existing SQS on photo upload.  I am using NodeJS in the lambda definition. 
**Problem:**
Messages are reaching to SQS but not always. It is intermittent. 
For Example, If I upload 5 photos, 5 messages should be sent to SQS but only 2 gets send. The pattern is not fixed. Sometimes all messages are sent. Sometimes none and sometimes few.  I do not see any error in Cloud Watch and viewing the logs it appears every line of code is running well. Just messages are failing to send silently.

**Below is the function in index.js file:**
_async function SendSQSMessage(sqsPayload, sqsUrl)
{
			
		var sqsSendMessage = await sqs.sendMessage(sqsPayload).promise().then(
		  function(data) {
			console.log("=======Success - sending message to SQS " + sqsUrl + " - Message ID: ", data.MessageId);
		  },
		  function(error) {
			console.log("=========Error sending message to SQS " + sqsUrl + " : ", err);
		  }
		);		
		
		
}_

**Above method is being called as:**
		SendSQSMessage(sqsPayload, sqsUrl);

**Comment by ajredniwja** [comment]
Hey @vatsvivek thanks for opening this and I was not really able to reproduce it, can you try it with a newer version and see if that helps?
