### ISSUE TITLE
Unexpected key 'environmentFiles' : Failed to register task definition in ECS

### ISSUE THREAD

**Issue by gaurav-agarwal27** [aws/aws-sdk-js#3255]
If you still like to open an issue, change [ ] to [x] below:
- [] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

I am using Github Actions to automate deploy the task to ECS. Passed S3 ARN as `environmentFiles` in ECS console, and it seems to work fine. But the same task-definition JSON doesn't work when using `aws-actions/amazon-ecs-deploy-task-definition@v1`

`environmentFiles` reference pull requests on `aws/amazon-ecs-agent` repo: [#2420](https://github.com/aws/amazon-ecs-agent/pull/2420), [#2421](https://github.com/aws/amazon-ecs-agent/pull/2421)

I have added environmentFiles in my containerDefinitions of `task-definition.json` as:
```
"environmentFiles": [{
    "type": "s3",
    "value": "arn:aws:s3:::ltl-environments/.stg.env"
}],
```
Getting the following error: 
```
##[error]Failed to register task definition in ECS: There were 5 validation errors:
* UnexpectedParameter: Unexpected key 'environmentFiles' found in params.containerDefinitions[0]
* UnexpectedParameter: Unexpected key 'environmentFiles' found in params.containerDefinitions[2]
* UnexpectedParameter: Unexpected key 'environmentFiles' found in params.containerDefinitions[3]
* UnexpectedParameter: Unexpected key 'environmentFiles' found in params.containerDefinitions[4]
* UnexpectedParameter: Unexpected key 'environmentFiles' found in params.containerDefinitions[5]```

**Comment by ajredniwja** [comment]
Hey @gaurav-agarwal27 thank-you for reaching out, how are you consuming the JS-SDK in this?
Should be an issue for https://github.com/aws/amazon-ecs-agent

**Comment by gaurav-agarwal27** [comment]
Hi @ajredniwja, like I mentioned I am using Github Action `aws-actions/amazon-ecs-deploy-task-definition@v1` for automated deployment to ECS. This action is using `aws-sdk-js` to determine which keys are valid in `task-definition.js`.

I checked in `aws-sdk-js` but couldn't find anything related to `environmentFiles` either.

**Comment by clareliguori** [comment]
Hi @gaurav-agarwal27, that feature is not fully released yet, which is why it isn't yet in the SDK.  Please watch this roadmap issue for updates on when it is released: 
https://github.com/aws/containers-roadmap/issues/371
