### ISSUE TITLE
CORS problem with AppConfig

### ISSUE THREAD

**Issue by darko-dev** [aws/aws-sdk-js#3262]
Confirm by changing [ ] to [x] below:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I am trying to use AWS AppConfig Service within my ReactJS App but I am having problem with CORS.

When I try to fetch my configuration with

```AppConfig.getConfiguration({
  Application: 'XXXXXXX', /* required */
  ClientId: 'XXXXXXX', /* required */
  Configuration: 'XXXXXXX', /* required */
  Environment: 'XXXXXX', /* required */
  ClientConfigurationVersion: '1'
}, (err, data) => {
  console.log("err = ", err);
  console.log("data = ", data);
})
```

I am getting:`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

If it matters, I am using Amazon System Manager document as configuration source.

I am guessing there is a CORS policy configuration for AppConfig/System Manager service just like for the S3 and API Gateway services but I can't find it.

Any help appreciated!

**Comment by ajredniwja** [comment]
Hey @darko-dev apologies for late response, the AppConfig service doesn't support CORS at the moment. 

Also check the comment:
https://github.com/aws/aws-sdk-js/issues/2657#issuecomment-491902749

**Comment by darko-dev** [comment]
Thanks @ajredniwja !

Is there a guide/ tutorial on how to use this particular service from web apps? Is there a way to combine other AWS service with AppConfig to be able fetch the configuration from browser?

**Comment by ajredniwja** [comment]
There are different ways depending upon your use case, can you share what you are trying to do?

**Comment by darko-dev** [comment]
The idea was to use it as way to control a set of feature flags for the app done in ReactJS. Feature flags would control show/hide parts of the app and menus, for example.

**Comment by ajredniwja** [comment]
Yes, that can be used to overcome the problem, which would mean to create a proxy, which would call the AppConfig API. The browser client would then call the proxy instead of AppConfig API directly.
