### ISSUE TITLE
Not able to generate documentation

### ISSUE THREAD

**Issue by bkpatel3108** [aws/aws-sdk-js#3266]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Followed instructions given in https://github.com/aws/aws-sdk-js/blob/master/CONTRIBUTING.md#testing-the-documentation-changes

However, running "bundle exec rake docs:api" fails with following error

```
bundler: failed to load command: yard (/local/home/myuser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/yard)
NoMethodError: undefined method `[]' for nil:NilClass
  doc-src/templates/api-versions/plugin.rb:52:in `block in <top (required)>' 
```

Browser/Node.js
NA

**If on Node.js, are you running this on AWS Lambda?**
NA

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
NA
**SDK version number**
v2.681.0

**To Reproduce (observed behavior)**
Ran following command to generate doc
bundle install
bundle exec rake docs:api

**Expected behavior**
As described in CONTRIBUTING.md, it should generate documentation in (doc/latest/_index.html)

**Screenshots**
NA

**Additional context**
Initially "bundle install" just fails with error following error

```
NoMethodError: undefined method `[]' for nil:NilClass
An error occurred while installing yard (0.8.7.6), and Bundler cannot continue.
Make sure that `gem install yard -v '0.8.7.6'` succeeds before bundling.
```

To get around this issue, I had to use bundled with 2.x.x in Gemfile.lock.

**Comment by ajredniwja** [comment]
Hey @bkpatel3108 thank-you for reaching out to us with your issue, I was not able to reproduce it, I see that you already worked around with it, another thing that I could think of might be the version of rake, so maybe updating rake can help in this case. 

<img width="930" alt="Screen Shot 2020-05-20 at 2 22 28 PM" src="https://user-images.githubusercontent.com/34409186/82498765-63a10600-9aa5-11ea-8274-413345ff87b7.png">

**Comment by bkpatel3108** [comment]
Hi @ajredniwja, I don't see you ran "bundle install" and "bundle exec rake docs:api" as described in CONTRIBUTING.md to generate documentation. Could u please run them.
I am getting error on running this command. 
The workaround I did to solve error I was getting on "bundle install".
I am still getting mentioned error while running "bundle exec rake docs:api".

**Comment by ajredniwja** [comment]
> Hi @ajredniwja, I don't see you ran "bundle install" and "bundle exec rake docs:api" as described in CONTRIBUTING.md to generate documentation. Could u please run them.
> I am getting error on running this command.
> The workaround I did to solve error I was getting on "bundle install".
> I am still getting mentioned error while running "bundle exec rake docs:api".

I ran the commands, without running them you can not get build the docs and the index.html file.
Can you retry using a fresh clone of the repo?
