### ISSUE TITLE
support list (L) in AttributeType in dynamodb createTable

### ISSUE THREAD

**Issue by mr-kapoor** [aws/aws-sdk-js#3267]
List (L) is not supported in AttributeType in dynamodb createTable. Can you please help me in this, how can I store array of objects or array of strings in dynamodb

**Comment by ajredniwja** [comment]
Hey @mr-kapoor thank-you for reaching out to us with your issue, I am not sure what your use case is but to store you can follow the steps [here](https://stackoverflow.com/questions/51087022/how-can-i-store-the-array-of-objects-in-dynamodb/52606211) with attribute type of String when creating the table. 

Please reach out if you have any additional questions.
