### ISSUE TITLE
Bytes: UnsupportedDocumentException

### ISSUE THREAD

**Issue by rajal2009** [aws/aws-sdk-js#3271]
I am getting this error **UnsupportedDocumentException: Request has unsupported document format extractError** with analyzeDocument (javascript textract sdk function) in react native when I am trying to make the request with a byte param

**I also tried with :**
Buffer
Blob
Typed Array

But not getting success and all display same error 

 var params = {
      Document: {
        Bytes: base64String
      },
      FeatureTypes: [
        'FORMS', 'TABLES'
      ]
    };

textract.analyzeDocument(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});

Please help me to resolve this issue If anyone knows about that which type of image bytes accept

**Comment by msd117** [comment]
why was this closed @rajal2009 Did you ever found the solution
 to your issue
