### ISSUE TITLE
Give DynamoDB DocumentClient ability to marshall Set<string>

### ISSUE THREAD

**Issue by Birowsky** [aws/aws-sdk-js#3275]
I was surprised to see that marshalling of `Set<string>` is not supported as I got the following error:

> ValidationException: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes

I found [this workaround](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#createSet-property) to this feature, but I'm wondering, since javascript supports sets natively, what are the plans to bring that support to the `marshall`/`unmarshall` as well?

**Comment by Birowsky** [comment]
Attention

**Comment by Birowsky** [comment]
Nudge

**Comment by ajredniwja** [comment]
Hey @Birowsky apologies this was never picked up. This fell out of the queue and had very low visibility. 
With that being said the behavior is documented at: [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html) which has a section on Support for Sets as well which links to the workaround you have mentioned.

**Comment by Birowsky** [comment]
I understand. Thanks. But the question is still relevant, I would say. Do you intend to provide support for native sets?

**Comment by ajredniwja** [comment]
Unfortunately there is currently no plans to implement it in this repo. To implement, I believe a customization can be written to use `createSet()` but the team wont be working on it. Most of the features are prioritized in V3 of the repo currently based on different factors used to set priority. 

We are formalizing our plans to enter AWS SDK for JavaScript v2 into maintenance mode in 2023. For more details, check our README in [Version 2.x Support](https://github.com/aws/aws-sdk-js#version-2x-support).

**Comment by Birowsky** [comment]
Not sure why this is closed. Native Sets are not supported even in SDK v3
