### ISSUE TITLE
Use fixed IAM endpoint for China regions

### ISSUE THREAD

**Issue by zxkane** [aws/aws-sdk-js#3279]
**Is your feature request related to a problem? Please describe.**
Currently SDK is using below rules to set the endpoint of IAM in China bjs(cn-north-1) and zhy(cn-northwest-1) regions by default.

```json
"cn-*/*": {
      "endpoint": "{service}.{region}.amazonaws.com.cn"
    },
```

Per the [IAM doc](https://docs.amazonaws.cn/en_us/general/latest/gr/iam-service.html), both bjs and zhy are using same IAM endpoint `iam.cn-north-1.amazonaws.com.cn`.

**Describe the solution you'd like**
When using the JS JDK in region zhy, the SDK automatically uses the correct endpoint `iam.cn-north-1.amazonaws.com.cn` of IAM without explicitly overriding the endpoint/region.

**Describe alternatives you've considered**

**Additional context**
It's also the default behavior of `aws-cli` to choose the right endpoint of IAM when running IAM commands in region zhy, region conf of awscli and env `AWS_REGION` to zhy.

**Comment by ajredniwja** [comment]
Closing this in favor of #3274.
