### ISSUE TITLE
resourceGroupsTaggingAPI.getResources paginates results non-predictably

### ISSUE THREAD

**Issue by francescosalvi** [aws/aws-sdk-js#3280]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
We found `resourceGroupsTaggingAPI.getResources` to paginate groups of _very few_ `ecs:service` resources, even when omitting `ResourcesPerPage`/`TagsPerPage` (or passing as the max supported value), in a non-predictable way. The same parameter/query payloads, when used with `awscli` binary, do _not_ ever paginate.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
yes

**Details of the browser/Node.js version**
Lambda runtime is set to Node.js 10.x

**SDK version number**
as declared in package-lock.json: 2.673.0

**To Reproduce (observed behavior)**
In the specific case we witnessed, the number of resources matched by the filters was 3, and the sdk was _always_ paging the first 2 results where `ServiceType !== cron` on the first page, and the `cron` on the second page. This, regardless of the order of the items in the filter for `ServiceType`, without setting `ResourcesPerPage`/`TagsPerPage`, or even with `ResourcesPerPage = max = 100`, or `TagsPerPage = max = 500`.
This is the kind of query:
```
{
  "ResourceTypeFilters": [
    "ecs:service"
  ],
  "TagFilters": [
    {
      "Key": "App",
      "Values": [
        "foo"
      ]
    },
    {
      "Key": "ServiceType",
      "Values": [
        "web",
        "cron",
        "queueconsumer"
      ]
    },
    {
      "Key": "Environment",
      "Values": [
        "stage"
      ]
    },
    {
      "Key": "AppInstanceId",
      "Values": [
        "foo.bar.baz"
      ]
    }
  ]
}
```

**Expected behavior**
Although the doc at https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ResourceGroupsTaggingAPI.html#getResources-property states that 
>  Queries occasionally return fewer results on a page than allowed

it kind of looks ridiculous to me that such a few results should be paginated, moreover considering  that when providing the very same request payload to `awscli` this doesn't happen hints at some issue with the JS client code rather than with the upstream APIs.

**Comment by ajredniwja** [comment]
@francescosalvi apologies for late reply as this is very service specific, comparing to the other SDKs like Ruby, they exhibit similar behavior as well. I believe this was a known issue and was addressed using a comment about it in the API reference and it was advised to use the `PaginationToken` response parameter as a workaround. 

I would like to close this, please feel free to comment if you think differently.
