### ISSUE TITLE
TypeError: AWS.ApiGatewayV2 is not a constructor when aws-sdk is bundled using Webpack

### ISSUE THREAD

**Issue by vinitshahdeo** [aws/aws-sdk-js#3282]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

**ApiGatewayV2** is not bundled for browser support while using webpack for building applications using `aws-sdk` (Installed using npm : `npm i aws-sdk`)

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
Chrome: `81.0.4044.138`
Node: `v10.17.0`

**SDK version number**
v2.685.0

**To Reproduce (observed behavior)**
As mentioned in the [docs](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/webpack.html#webpack-importing-services), I'm using `weback` for bundling my web app. 

> Note: Since **webpack >= v2.0.0**, importing of JSON files will work by default so `json-loader` is no longer required in `webpack.config.js` 

The following script returns an error in browser: **`TypeError: AWS.ApiGatewayV2 is not a constructor`**.

```js

var AWS = require("aws-sdk");

var apigatewayv2 = new AWS.ApiGatewayV2({apiVersion: '2018-11-29'});

var params = {
    MaxResults: '20',
};

apigatewayv2.getApis(params, function (err, data) {
    if (err) 
       console.log(err); 
    else 
       console.log(data);
});
```

In browser's console, I tried to log `window.AWS` which contains `APIGateway` but not `ApiGatewayV2`.

PS: The same snippet runs as expected in **Node.js**  environment.

**Expected behavior**
The [methods](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayV2.html) of `ApiGatewayV2` should also work in browser like the [methods](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html) of `APIGateway` are working.

**Screenshots**
![Screenshot 2020-05-28 at 2 16 33 AM](https://user-images.githubusercontent.com/20594326/83070555-482b9180-a089-11ea-98fb-936bfdadd95a.png)

**Additional context**
Not sure, if it's a bug or expected behaviour(not to support `ApiGatewayV2` service in the browser); **am I missing something?**

**Comment by ajredniwja** [comment]
Hey @vinitshahdeo thank-you for reaching out to us with your issue, not all the services are included in the web-pack as not all of them support CORS. 

To check what services support CORS please refer to [metadata.json](https://github.com/aws/aws-sdk-js/blob/4b8bcd0d6a8b42cfaa263d0e2b2340cf99e55539/apis/metadata.json) 

To build your custom version of the SDK use https://sdk.amazonaws.com/builder/js/

Enable all the services that you want, build and attach it in your application.

**Comment by vinitshahdeo** [comment]
Hey @ajredniwja,
Thanks for your quick response.

I am able to solve the above issue(_**`TypeError: AWS.ApiGatewayV2 is not a constructor`**_) by building specific service i.e. `ApiGatewayV2`. 

```js

var AWS = require('aws-sdk/clients/apigatewayv2');

var apigatewayv2 = new AWS({
    apiVersion: '2018-11-29',
    credentials: {
        accessKeyId: 'XXXXXXXXX',
        secretAccessKey: 'XXXXXXXXX',
    },
    region: 'us-east-1'
});

apigatewayv2.getApis({}, function (err, data) {
    if (err) 
        console.log(err, err.stack);
    else 
        console.log(data);
});

```

But it ended up giving CORS error: 

```

Access to XMLHttpRequest at 'https://apigateway.us-east-1.amazonaws.com/v2/apis' from origin
'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't
pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested
resource.

```

Is there any workaround to resolve this other than creating a custom build of **AWS SDK** and plugging it into web app using `<script> </script>` tag?

**Comment by ajredniwja** [comment]
Can you refer to :

https://github.com/aws/aws-sdk-js/issues/2657#issuecomment-491902749

**Comment by ajredniwja** [comment]
@vinitshahdeo 

Can you refer to :
https://github.com/aws/aws-sdk-js/issues/2657#issuecomment-491902749
