### ISSUE TITLE
Hi Any updates on this? We experienced similar but rather strange behavior.

### ISSUE THREAD

**Issue by limubai123** [aws/aws-sdk-js#3290]
Hi Any updates on this? We experienced similar but rather strange behavior. 
If we set limit to 1 and we know there is only 1 item for that query, the query will not return `lastEvaluatedKey`. Which is not what the documentation says.

fyi @srchase

_Originally posted by @wjrjerome in https://github.com/aws/aws-sdk-js/issues/1981#issuecomment-510685027_

**Comment by limubai123** [comment]
hi we set limit to 1, and there are three records, but stil i am getting LastEvaluatedKey is none

**Comment by ajredniwja** [comment]
Hey @limubai123 thank-you for reaching out to us, can you please share the code sample that you are using and paste or screenshot the response that you get.
