### ISSUE TITLE
TypeError: AWS.PinpointSMSVoice is not a constructor

### ISSUE THREAD

**Issue by maheshvadada** [aws/aws-sdk-js#3292]
I am using "aws-sdk": "^2.302.0" in my node api. 
Please find my code below

```
var pinpointsmsvoice = new AWS.PinpointSMSVoice({apiVersion: '2018-09-05'});

var params = {
	Content: {
		SSMLMessage: {
			LanguageCode: "en-US",
			Text: <MY_Template>,
			VoiceId: "Matthew"
		}
	},
	DestinationPhoneNumber: <destinationNumber>,
	OriginationPhoneNumber: <OriginationPhoneNumber>
};

//Try to send the message.
pinpointsmsvoice.sendVoiceMessage(params, function (err, data) {
	if (err) {
		log.error(err);            
	} else {
		log.info("Voice Message is sent successfully");
	}
});
```

Earlier it was working now I am getting an error as `TypeError: AWS.PinpointSMSVoice is not a constructor`

Can some help me anything missed?

**Comment by philipwigg** [comment]
I get the same error as you if I use `2.302.0` but with the latest version of the SDK it works fine.

Is it possible for you just to upgrade the SDK?

**Comment by ajredniwja** [comment]
@maheshvadada yeah, can you please use the latest version of the SDK?

**Comment by maheshvadada** [comment]
@philipwigg, Thank you. Its working with the latest version (2.689.0). 

@ajredniwja, Need to verify that how the other services are effected with the latest version of aws-sdk. Hope all features in 2.302.0 should work in 2.689.0.

**Comment by ajredniwja** [comment]
> @ajredniwja, Need to verify that how the other services are effected with the latest version of aws-sdk. Hope all features in 2.302.0 should work in 2.689.0.

They all should work please reach out if you have any troubles.
