### ISSUE TITLE
Does not work on node 8 because of semver

### ISSUE THREAD

**Issue by RaulTsc** [aws/aws-sdk-js#3293]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Cannot do yarn install on node 8 because semver 7.3.2 requires node >10. As far as I know it's bad practice to use '*' for the dependency version. https://github.com/aws/aws-sdk-js/blob/master/package.json#L38

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Node 8.11.1

**SDK version number**
2.149.0

**To Reproduce (observed behavior)**
Should be enough to do yarn install on node 8.11.

**Expected behavior**
It should work

**Comment by philipwigg** [comment]
Related to https://github.com/npm/node-semver/issues/327 and https://github.com/npm/node-semver/commit/d61f828e64260a0a097f26210f5500e91a621828#r37027980

**Comment by ajredniwja** [comment]
Hey @RaulTsc Thank-you for reaching out to us with your issue, as @philipwigg mentioned as well, this should not be an issue for the JS-SDK but node-semver, it has already been raised there and they are not working on it I believe and I think the SDK should be tied to that decision as well. 

I would suggest to bump up the node version in this case.
