### ISSUE TITLE
How to delete a linked Cognito user account?

### ISSUE THREAD

**Issue by kimfucious** [aws/aws-sdk-js#3297]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

I have a web-app that will create linked users to an existing username/password user, in a Cognito user pool, using `adminLinkProviderForUser()`

So, for example, the user after having created a Cognito user with username and password, can use federated login with Amazon, Apple, Facebook, and or Google.

Let's keep it simple, by saying I'm only allowing Google.

This will result in two user accounts:  one that is username/password and one that is Google_xxxxxxx.

I am working on the process to delete users from the user pool, for when a user requests their account to be deleted.

I can delete a single username/password user in a Cognito userpool via Amplify pretty easily, but that does not remove the linked users.

In an attempt to remove the linked users, I've created a lambda, that receives a username as a POST parameter via an API gateway path and uses the aws-sdk CognitoIdentityServiceProvider `adminDeleteUser()` method.

The username is pulled and concatenated from the attributes => identities, into an actual username in the app and sent to the lambda, in the form of `{username: 'Google_xxxxxxx'}`, in the body of the post.

If I `adminDeleteUser()`, with the aforementioned `username` and a correct `userPoolId`, the username/password user is deleted from the userpool, yet the linked (i.e. Google_xxxxxxxx) user remains.

**Question**:  How can I get rid of the linked users?

FYI:  The behavior is the same in the Cognito Userpool UI, in that if select the `Google_xxxxx` user, disable, and delete it, the username/password user is deleted and the `Google_xxxxx` user remains.

I then need to manually delete the `Google_xxxxx` user to make it go away.

I guess I could write the code so that the delete process runs twice, but I thought I'd ask here first.

Any guidance here will be appreciated!

Thanks!  🌮

**Comment by kimfucious** [comment]
Okay, sharing a solution here in the hopes that someone can validate it.  It does seem a bit convoluted, so perhaps someone can propose something better.

A couple notes:
1. When Cognito users are linked, the behavior that I mentioned above, where performing a delete action on linked user actually deletes the username/password user, leaving the provider user in tact, holds true. 
2. I started dabbling with `adminDisableProviderForUser()`, but found it redundant in my end-solution.

Solution
1. Delete the username/password user first.  This can be done using Amplify with:
```js
...
const user = await Auth.currentAuthenticatedUser();
user.deleteUser(async (error) => {
  if (error) {
    // handle error
  }
  // call lambda to delete linked provider users
  // sign the user out globally
...
```
2. In the callback, call a lambda function to delete the linked provider users, using the `adminDeleteUser()` method off aws-sdk `CognitoIdentityServiceProvider()`, with user names like `Google_xxxx`, `SignInWithApple_xxxxxx_xxxxxxxxxxxxxxx_xxxx`, etc.

Note: The lambda role associated with the lambda function will need permissions to allow `adminDeleteUser()` to be run on the user pool resource.

Because the "original" username/password user has been deleted prior, running the `adminDeleteUser()` on the Provider user, will now actually delete it.

**Comment by ajredniwja** [comment]
Verified the solution.

**Comment by kimfucious** [comment]
Thanks @ajredniwja for the verification.
