### ISSUE TITLE
DynamoDB scan and DynamoDB.DocumentClient scan return different results

### ISSUE THREAD

**Issue by zachary-D** [aws/aws-sdk-js#3299]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Scans with DynamoDB.DocumentClient don't return any values, while scans with identical parameters on DynamoDB return the proper items.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
serverless framework / AWS lambda, nodejs12.x runtime

**SDK version number**
v2.689.0

**To Reproduce (observed behavior)**

```
const dbDoc = new DynamoDB.DocumentClient({apiVersion: "2012-08-10"});
const db = new DynamoDB({apiVersion: "2012-08-10"});

const filter: DynamoDB.DocumentClient.ScanInput = {
    TableName: "locations-table-here",
    FilterExpression: `LHash = :hash`,
    ExpressionAttributeValues: {
        ":hash": {"S": escapeSpecialCharactersForDynamoDB(hash)}
    }
};

console.log(await dbDoc.scan(filter).promise());
console.log(await db.scan(filter).promise());

```
**Expected behavior**
Both scans should return the same items, with the different formatting intended for each.  As shown in the screenshot, the doc-scan returns no items.

**Screenshots**
![image](https://user-images.githubusercontent.com/16283501/84169769-03b7d280-aa47-11ea-9732-982bf576d3d5.png)

**Additional context**
Similar to #1187, if not the same issue

**Comment by ajredniwja** [comment]
Hey @zachary-D, thank-you for reaching out to us with your issue, is there an actual test case that you can provide me? 

I scanned a table with around 11000 items and got the same result for the both.

**Comment by RossWilliams** [comment]
Your expression attribute values for document client should be a different shape, since document client handles marshalling and un-marshalling for you. You are filtering on a map rather than a string, and not getting any results.

When using the document client change ':hash' value to a string, rather than the object you currently have.

**Comment by zachary-D** [comment]
I'll give that a try, thanks!
