### ISSUE TITLE
target group name convention

### ISSUE THREAD

**Issue by nnvgm** [aws/aws-sdk-js#3300]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
**Details of the browser/Node.js version**
v12.16.2

**SDK version number**
2.690.0

**To Reproduce (observed behavior)**

1. call api create new targetgroup with params name: "new--targetgroup"
```
async createTargetGroup(name: string): Promise<ELBv2.Types.CreateTargetGroupOutput> {
    const params: ELBv2.Types.CreateTargetGroupInput = {
      Name: name,
      Protocol: 'HTTP',
      Port: 80,
      VpcId: process.env.VPC_ID,
      HealthCheckProtocol: 'HTTP',
      HealthCheckPath: '/',
      HealthCheckEnabled: true,
      HealthCheckIntervalSeconds: 30,
      TargetType: 'instance',
    }

    return await this.elbv2.createTargetGroup(params).promise()
}
```

2. go to the aws ec2 manager target group console, new target group with name "new--targetgroup" was be created

3. in aws console, create new target group
![action](https://i.imgur.com/yBUmOG2.jpg)
one validate error will be show in the form

**Expected behavior**
no validate error in form create target group

**Comment by ajredniwja** [comment]
Hey @nnvgm thank-you for reaching out to us with your issue, this might be a bug on the console side, I have reached out to the service team to address it. This is not particularly a bug with the SDK.
