### ISSUE TITLE
Support : describeTrustedAdvisorCheckResult does not return timestamp for some checks

### ISSUE THREAD

**Issue by pasan9** [aws/aws-sdk-js#3301]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Calling `describeTrustedAdvisorCheckResult` should return a response (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Support.html#describeTrustedAdvisorCheckResult-property) which includes the `timestamp` attribute (which is the the time of the last refresh of the check). For **some** checks this attribute is not available. This usually happens when the pirticular check is not applicable, but I have cross checked with the AWS console and CLI and both of them are giving the last update time for these particular checks, but I'm unable to retrieve that time from the SDK.

I faced this issue with two kinds of checks (as of now, there could be more) across multiple accounts : 
- Amazon RDS Public Snapshots (ID : rSs93HQwa1)
- Amazon EBS Public Snapshots (ID : ePs02jT06w)

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.16.3

**SDK version number**
aws-sdk@2.480.0

**To Reproduce (observed behavior)**
```
import AWS from "aws-sdk";


const region = "us-east-1";

var trustedAdvisorClient = new AWS.Support({region});

(async function () {
  try {

    const violationResults = await trustedAdvisorClient
      .describeTrustedAdvisorCheckResult({
        checkId: "ePs02jT06w"
      })
      .promise();

    console.log(JSON.stringify(violationResults));
  } catch (e) {
    console.log(e);
  }
})();

```
**Expected behavior**
Expecting applicable checks to return last refreshed timestamps.

**Screenshots**
Result I get from SDK : 
![sdk-result](https://user-images.githubusercontent.com/19402786/84248117-9bd8b900-ab26-11ea-873d-6bc6aead0e3e.png)

The result I get on CLI with the command `aws support describe-trusted-advisor-check-result --check-id ePs02jT06w`
![cli-result](https://user-images.githubusercontent.com/19402786/84248136-a430f400-ab26-11ea-9f7e-6741d4a09aa1.png)

Notice the timestamp is there in CLI response, and it's there in the console as well.

**Comment by ajredniwja** [comment]
Hey @pasan9 thank-you for reaching out to us with your issue. 

Have you tried using the latest version of the SDK? 

While it should not be the case from looking at 

 https://github.com/aws/aws-sdk-js/blob/660859097ce1aa0cea23155f3040079c1fe261d2/clients/support.d.ts

and

https://github.com/aws/aws-sdk-js/blob/660859097ce1aa0cea23155f3040079c1fe261d2/apis/support-2013-04-15.normal.json#L1186

The SDKs are not entitled to match the functionality of the CLI but the response from the service should be the same. I was not able to reproduce it since I don't have a premium account, I can reach out to the service team and PS team if its still and issue with the latest version of the SDK.

**Comment by pasan9** [comment]
Hey @ajredniwja , yes I was able to reproduce this with the latest version of SDK as well (aws-sdk@2.696.0).
