### ISSUE TITLE
Add Support for ECS.updateService

### ISSUE THREAD

**Issue by jmclean-cnexus** [aws/aws-sdk-js#3310]
**Is your feature request related to a problem? Please describe.**
Per [this article](https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-ecs-supports-in-preview-updating-placement-strategy-and-constraints-for-existing-ecs-services/), the ECS Update Service API supports modifying the placement strategy, however the SDK does not. I receive the below error when I try in lambda:

```
{
  "errorType": "MultipleValidationErrors",
  "errorMessage": "There were 2 validation errors:\n* UnexpectedParameter: Unexpected key 'placementStrategy' found in params\n* UnexpectedParameter: Unexpected key 'placementConstraints' found in params",
  ...
}
```

**Describe the solution you'd like**
Update the SDK to support what the API supports (as well as corresponding type definitions

**Describe alternatives you've considered**
This is added support by AWS that is not yet available in the AWS SDK

**Additional context**
NA

**Comment by ajredniwja** [comment]
Hey @jmclean-cnexus apologies for the delayed response here, the API should have been updated as seen at:

https://github.com/aws/aws-sdk-js/blob/d2b89643b8ffda1f4a88e87f25da5bc3e0f3a042/apis/ecs-2014-11-13.normal.json#L6174
