### ISSUE TITLE
How to get Cognito User Pool Name by Pool Id

### ISSUE THREAD

**Issue by maheshvadada** [aws/aws-sdk-js#3314]
For my Multi tenant Application I am creating Cognito user pools for each tenant with a special naming convention using Javascript SDK.  

When creating adding a user in Cognito User Pool for a tenant, an email notification will be sent.
I created a lambda function with custom email message and configured it as a trigger in Custom Messages in Cognito User Pool.
Ref: https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/cognito-user-pool-settings-message-templates.html

Now my concern here is I need to prepare a link and logo by the tenant name, for that purpose I need to get the Cognito User Pool Name. From the Lambda function I can get the pool Id. 

Can anyone help, how to get the Cognito User Pool Name by pool Id or how to pass dynamic custom parameters to my lambda function when it is triggered from Cognito User Pool.??

**Comment by ajredniwja** [comment]
Hey @maheshvadada thank-you for reaching out to us with your issue. 

You can do something like: 

```
var AWS = require('aws-sdk');

var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider({region: 'us-west-2'});

cognitoidentityserviceprovider.describeUserPool({UserPoolId: 'xyz'}, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data.UserPool.Name);    
});
```

Docs for `describeUserPool` :

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#describeUserPool-property

Closing this issue now, please reach out if you have any other questions.
