### ISSUE TITLE
S3 HeadObject doesn't parse Metadata

### ISSUE THREAD

**Issue by Diluka** [aws/aws-sdk-js#3324]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
`headObject` doesn't parse header into `Metadata`

**Is the issue in the browser/Node.js?**
Browser

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
Edge: 83.0.478.45

**SDK version number**

2.703.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
```ts
await s3.putObject({
...,
Metadata:{key:'value'}
}).promise()

info = await s3.headObject({...}).promise()

// info.Metadata is empty
```

**Expected behavior**
`info.Metadata` has values

**Screenshots**

**Additional context**
I checked requests headers, the metadata is present. But sdk is not parse it into `Metadata`.

relate #27

**Comment by ajredniwja** [comment]
Hey @Diluka thank-you for reaching out to us with your issue, can you please share what attributes of metadata are you looking for?

**Comment by Diluka** [comment]
@ajredniwja Thanks for answering. I use STS to upload and retrieve metadata, the file is larger than 10MB mp4
```ts
  Policy: JSON.stringify({
        'Version': '2012-10-17',
        'Statement': [
          {
            'Effect': 'Allow',
            'Action': [
              's3:GetObject',
              's3:PutObject',
              's3:PutObjectAcl',
            ],
            'Resource': 'arn:aws:s3:::a-bucket/*',
          },
        ],
      }),

```


```ts
  private createS3Client(token: AwsUpToken) {
    const {
      AccessKeyId: accessKeyId,
      SecretAccessKey: secretAccessKey,
      SessionToken: sessionToken,
    } = token.Credentials;

    return new S3({ region: 'ap-southeast-1', credentials: { accessKeyId, secretAccessKey, sessionToken } });
  }
```

```typescript
  async upload(token: AwsUpToken, file: UploadFile, Bucket: string, Key: string, extraReq?: Partial<S3.Types.PutObjectRequest>, progress?: (progress: S3.ManagedUpload.Progress) => void) {
    const s3 = this.createS3Client(token);

    const upload = s3.upload({
      ...extraReq,
      Key,
      Bucket,
      Body: file,
      ContentType: file.type,
      ACL: 'public-read',
    });

    if (progress) {
      upload.on('httpUploadProgress', progress);
    }

    return upload.promise();
  }
```


```ts
const OriginalFilenameMetaKey = 'original-filename';


 customRequest: ({ file, onProgress, onSuccess, onError }) => {
            return forkJoin({
              md5: this.md5Service.fromFile(file, (progress) => {
                onProgress({ percent: progress * 20 }, file);
              }),
              token: this.awsService.getToken(),
            }).pipe(mergeMap(({ md5, token }) => {
              const ext = file.name.split('.').pop();
              return this.awsService.upload(
                token,
                file,
                Bucket,
                `${md5}.${ext}`,
                {
                  Metadata: {
                    [OriginalFilenameMetaKey]: file.name,
                  },
                },
                ({ loaded, total }) => onProgress({ percent: loaded / total * 80 + 20 }, file),
              );
            })).subscribe(
              result => onSuccess(result, file, undefined),
              error => onError(error, file),
            );
          },
```

is anything wrong?

**Comment by ajredniwja** [comment]
@Diluka thanks for sharing the code, this looks fine but however how are you using the API? Am I missing anything here?

**Comment by Diluka** [comment]
I want to save the original filename for further display. Is there a better solution?

**Comment by ajredniwja** [comment]
You mention it in the `Metadata` that should be the best option if the the key is different from the original filename.

**Comment by Diluka** [comment]
I tried `original_filename`, `x-original-filename`, `origin-name`, `originame` and `key1` and none of them works.

**Comment by ajredniwja** [comment]
The Metadata property will stay `{}` if it is not set, can you make sure if the `Metadata` is actually getting set.

To test `Metadata` you can simply try a `putObject` call and use any values for the `Metadta{}` and afterwards you can see it in the `headObject` call.

**Comment by Diluka** [comment]
https://codesandbox.io/s/aws-sdk-issue-3324-m119k

**Comment by ajredniwja** [comment]
> https://codesandbox.io/s/aws-sdk-issue-3324-m119k

What is this about, not able to open it.

**Comment by Diluka** [comment]
it is the reproduction

**Comment by Diluka** [comment]
any updates?

**Comment by Diluka** [comment]
I found this https://github.com/aws/aws-sdk-js/issues/232#issuecomment-53990022

should set `CORSRule`
