### ISSUE TITLE
In case this helps anyone: I was getting this same signature failure, but the mistake I was making was including an extra HTTPS header (Content-type) which is apparently used to calculate the signature.

### ISSUE THREAD

**Issue by anubhav-bss** [aws/aws-sdk-js#3326]
In case this helps anyone: I was getting this same signature failure, but the mistake I was making was including an extra HTTPS header (Content-type) which is apparently used to calculate the signature. 

Frustrating to track down, for sure, but ultimately my fault.

_Originally posted by @krilnon in https://github.com/aws/aws-sdk-js/issues/86#issuecomment-133234836_

**Comment by ajredniwja** [comment]
Can not be tracked as an issue. Closing this now.
