### ISSUE TITLE
AWS.Pricing - getProducts method results in InvalidParameterException

### ISSUE THREAD

**Issue by dn0912** [aws/aws-sdk-js#3329]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Based on the documentation of the getProducts method of the AWS Price List Service API (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pricing.html#getProducts-property) the example shown there is not working. The error `InvalidParameterException` is thrown:
`InvalidParameterException: Input Parameters are invalid. serviceCode cannot be null or empty`

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Node.js v10.19.0

**SDK version number**
v2.705.0

**To Reproduce (observed behavior)**
Try out the example code in the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pricing.html#getProducts-property):
```
 var params = {
  Filters: [
     {
    Field: "ServiceCode", 
    Type: "TERM_MATCH", 
    Value: "AmazonEC2"
   }, 
     {
    Field: "volumeType", 
    Type: "TERM_MATCH", 
    Value: "Provisioned IOPS"
   }
  ], 
  FormatVersion: "aws_v1", 
  MaxResults: 1
 };
 pricing.getProducts(params, function(err, data) {
   if (err) console.log(err, err.stack); // an error occurred
   else     console.log(data);           // successful response
 });
```

**Expected behavior**
Retrieve the data about the service as shown in the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pricing.html#getProducts-property):
```
data = {
    FormatVersion: "aws_v1", 
    NextToken: "57r3EXAMPLEujbzWfHF7Ciw==:ywSmZsD3mtpQmQLQ5XfOsIMkYybSj+vAT+kGmwMFq+K9DGmIoJkz7lunVeamiOPgthdWSO2a7YKojCO+zY4dJmuNl2QvbNhXs+AJ2Ufn7xGmJncNI2TsEuAsVCUfTAvAQNcwwamtk6XuZ4YdNnooV62FjkV3ZAn40d9+wAxV7+FImvhUHi/+f8afgZdGh2zPUlH8jlV9uUtj0oHp8+DhPUuHXh+WBII1E/aoKpPSm3c=", 
    PriceList: [
       "{\"product\":{\"productFamily\":\"Storage\",\"attributes\":{\"storageMedia\":\"SSD-backed\",\"maxThroughputvolume\":\"320 MB/sec\",\"volumeType\":\"Provisioned IOPS\",\"maxIopsvolume\":\"20000\",\"servicecode\":\"AmazonEC2\",\"usagetype\":\"CAN1-EBS:VolumeUsage.piops\",\"locationType\":\"AWS Region\",\"location\":\"Canada (Central)\",\"servicename\":\"Amazon Elastic Compute Cloud\",\"maxVolumeSize\":\"16 TiB\",\"operation\":\"\"},\"sku\":\"WQGC34PB2AWS8R4U\"},\"serviceCode\":\"AmazonEC2\",\"terms\":{\"OnDemand\":{\"WQGC34PB2AWS8R4U.JRTCKXETXF\":{\"priceDimensions\":{\"WQGC34PB2AWS8R4U.JRTCKXETXF.6YS6EN2CT7\":{\"unit\":\"GB-Mo\",\"endRange\":\"Inf\",\"description\":\"$0.138 per GB-month of Provisioned IOPS SSD (io1)  provisioned storage - Canada (Central)\",\"appliesTo\":[],\"rateCode\":\"WQGC34PB2AWS8R4U.JRTCKXETXF.6YS6EN2CT7\",\"beginRange\":\"0\",\"pricePerUnit\":{\"USD\":\"0.1380000000\"}}},\"sku\":\"WQGC34PB2AWS8R4U\",\"effectiveDate\":\"2017-08-01T00:00:00Z\",\"offerTermCode\":\"JRTCKXETXF\",\"termAttributes\":{}}}},\"version\":\"20170901182201\",\"publicationDate\":\"2017-09-01T18:22:01Z\"}"
    ]
   }
```

**Comment by ajredniwja** [comment]
Hey @dn0912 thank-you for reaching out to us with your issue. 

The `seviceCode` is required as mentioned [here](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_pricing_GetProducts.html). 
 
However, I understand the frustration the [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pricing.html#getProducts-property) not being concise, reached out to the service team to work on a fix.

**Comment by dn0912** [comment]
Hi @ajredniwja 
Thank you for clarification!

**Comment by ajredniwja** [comment]
Softupdate, pricing team is working on it

**Comment by tim-finnigan** [comment]
Linking related issue: https://github.com/aws/aws-sdk/issues/51

**Comment by aBurmeseDev** [comment]
Service team updated their docs and change is now in [API reference docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pricing.html#getProducts-property). Closing issue.
