### ISSUE TITLE
Unable to add tags to a Chime meeting

### ISSUE THREAD

**Issue by bangersandflash** [aws/aws-sdk-js#3334]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When creating a Chime meeting I cannot add tags to the meeting either at the time of creation or once the meeting has been created. If I pass tags when creating the meeting it throws the following error:
`UnexpectedParameter: Unexpected key 'Tags' found in params`

If I try to add them after the meeting has been created the error is:
`"errorMessage": "chime.tagMeeting is not a function",`

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
This is running on Lambda

**Details of the browser/Node.js version**
Node 12.x

**SDK version number**
v2.631.0

**To Reproduce (observed behavior)**
The code to reproduce the error is below:
`
const AWS = require('aws-sdk');
const chime = new AWS.Chime(
    {
        region: 'us-east-1',
        accessKeyId: 'xxx,
        secretAccessKey: 'xxx'
    }
);
chime.endpoint = new AWS.Endpoint('https://service.chime.aws.amazon.com/console');
exports.handler = async (event) => {
    let token = "_" + String(new Date().getTime())
   
    let meeting = await chime.createMeeting({
                ClientRequestToken: token
            }).promise();
    
    let tagParams = {
        MeetingId:meeting.Meeting.MeetingId,
        Tags:[
            {
                Key:"foo",
                Value:"bar"
            }
        ]
    }
    
    await chime.tagMeeting(tagParams).promise()
    
    console.log(meeting)
    let tags = await chime.listMeetingTags({MeetingId:meeting.Meeting.MeetingId}).promise();
    console.log("tags:", tags)

    const response = {
        statusCode: 200,
        body: JSON.stringify(meeting)
    };
    return response;
};
`

**Expected behavior**
I should be able to add tags to a meeting as per the documentation.

**Comment by ajredniwja** [comment]
Hey @bangersandflash thank-you for reaching out to to us with your issue can you make sure you are using the latest version of the SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

**Comment by bangersandflash** [comment]
Thanks @ajredniwja 

To clarify, Lambda uses v2.631.0 by default so I need to manually include v2.712.0 and use that instead?

**Comment by ajredniwja** [comment]
By default Lambda uses the SDK version mentioned in https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html which is 2.631.0, so you are correct with your statement. 

You might want to use that and see if the problem persists. 

Also, I would suggest to try run the code locally and test that the SDK is working fine.

**Comment by ajredniwja** [comment]
Closing this issue, please reach out if you want it re-opened.
