### ISSUE TITLE
SDK v2 Usage and AWS Authentication with shared credentials in react-native apps

### ISSUE THREAD

**Issue by elliotmrodriguez** [aws/aws-sdk-js#3335]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Are there any updated examples that demonstrate a working authentication flow for react-native (0.62) and the v2 of the SDK using credentials in the shared config/credentials files?

The closest I could find is this:
https://aws.amazon.com/blogs/developer/react-native-support-in-the-aws-sdk-for-javascript/

However, this example does not work.

The closest working example I could come up with was this:

```javascript
let AWS = require("aws-sdk");

const credentials = new AWS.SharedIniFileCredentials({profile: "MyProfile"});
AWS.config.credentials = credentials;

const s3 = new AWS.S3({apiVersion: '2006-03-01'})

const bucketParams = {
    Bucket: 'mybucket',
    Key: 'mifile.json'
}

const getFile = async(arg) => { 
    const { Body } = await s3.getObject(bucketParams).promise();
    return JSON.parse(Body.toString())[arg];
}
```

And it fails immediately with an undefined constructor error on SharedIniFileCredentials. However, manually invoking the script (`node blah.js` where this code is in `blah.js` works correctly)

According to the SDK documentation on this:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html

> Note: This feature is not supported in the browser environment of the SDK.

Does the SDK for react-native treat it as a browser app then? 

Importing the react-native libraries from the dist directories did not address the issue.

**Comment by ajredniwja** [comment]
Hey @elliotmrodriguez thank-you for reaching out to us with your issue. 
Please check out https://github.com/aws/aws-sdk-js/issues/1531#issuecomment-304932416

Please reach out if you still have any questions.
