### ISSUE TITLE
SSM client ListAssociations does not respect all filters provided when multiple filters are defined

### ISSUE THREAD

**Issue by kyleboucherlancom** [aws/aws-sdk-js#3338]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
SSM client `ListAssociations` call does not respect all filters provided to the `AssociationFilterList` parameter when multiple filters are defined. This occurs in both the aws-sdk and the aws-cli. 

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Lambda and locally through the aws-cli. 

**Details of the browser/Node.js version**
`node -v` -> `v8.16.0`

**SDK version number**
Locally: aws-sdk@2.707.0
Cli: aws-cli/1.16.40
Lambda: 2.631.0

**To Reproduce (observed behavior)**
From Cli: 
Run command with single date filter
```aws ssm list-associations --association-filter-list "key=LastExecutedBefore,value=2017-05-01T01:00:00.000Z" --max-items 20```
Run command with 2 filters
```aws ssm list-associations --association-filter-list "key=LastExecutedBefore,value=2017-05-01T01:00:00.000Z" "key=AssociationStatusName,value=Pending" --max-items 20```
Date filter is overridden in the second step and it returns results that do not match the date filter. 

From Sdk: 
This will return associations AFTER the date specified (eg. today, yesterday, etc). 
```
    const dateNow = new Date();
    dateNow.setDate(dateNow.getDate() - 30);
    const params = {
        AssociationFilterList: [
            {
                key: "LastExecutedBefore",
                value: dateNow.toISOString(),
            },
            {
                key: "AssociationStatusName",
                value: "Pending"
            }
        ],
    };
    let associations = await Ssm.listAssociations(params).promise();
    console.log(associations);
```

This returns the correct results matching the date filter: 
```
    const dateNow = new Date();
    dateNow.setDate(dateNow.getDate() - 30);
    const params = {
        AssociationFilterList: [
            {
                key: "LastExecutedBefore",
                value: dateNow.toISOString(),
            },
        ],
    };
    let associations = await Ssm.listAssociations(params).promise();
    console.log(associations);
```

**Expected behavior**
The filters defined in `AssociationFilterList` to work together rather than individually. 

**Screenshots**
Cli testing:
![image](https://user-images.githubusercontent.com/22062255/86704068-a1171e00-c068-11ea-8635-50049d42038e.png)

Lambda logs: 
![image](https://user-images.githubusercontent.com/22062255/86705674-3a92ff80-c06a-11ea-9c97-70578003cff9.png)

**Additional context**
Problem was found in a Lambda we wrote using the AWS SDK in Javascript, confirmed error also exists through the AWS CLI.

**Comment by ajredniwja** [comment]
@kyleboucherlancom Thank-you for reaching out to us with your issue, I have reached out to the service team for a fix or clarification, will update once I hear back from them.

**Comment by shepherdjerred** [comment]
Thanks for the report @kyleboucherlancom, this issue should be fixed now.
