### ISSUE TITLE
Web socket connection closed immediately after open

### ISSUE THREAD

**Issue by SyedHaris94** [aws/aws-sdk-js#3340]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I use Amazon-sdk to convert speech to text using base-64, when i send data through socket to server it opens the connection but after opening it immediately closed the connection and did not send any result.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v10.16.3

**SDK version number**
^2.707.0

**To Reproduce (observed behavior)**

Here is my server code:
```javascript
const awsSignature = require("./aws-signature-v4");
const WebSocket = require("ws");
const { EventStreamMarshaller } = require("@aws-sdk/eventstream-marshaller");
const { toUtf8, fromUtf8 } = require("@aws-sdk/util-utf8-node");
const eventStreamMarshaller = new EventStreamMarshaller(toUtf8, fromUtf8);

function convertAudioToBinaryMessage(audioChunk) {
  // downsample and convert the raw audio bytes to PCM
  let downsampledBuffer = downsampleBuffer(audioChunk);
  let pcmEncodedBuffer = pcmEncode(downsampledBuffer);

  // add the right JSON headers and structure to the message
  let audioEventMessage = getAwsEventMessage(Buffer.from(pcmEncodedBuffer));

  //convert the JSON object + headers into a binary event stream message
  let binary = eventStreamMarshaller.marshall(audioEventMessage);

  return binary;
}

function downsampleBuffer(
  buffer,
  inputSampleRate = 44100,
  outputSampleRate = 16000
) {
  if (outputSampleRate === inputSampleRate) {
    return buffer;
  }

  var sampleRateRatio = inputSampleRate / outputSampleRate;
  var newLength = Math.round(buffer.length / sampleRateRatio);
  var result = new Float32Array(newLength);
  var offsetResult = 0;
  var offsetBuffer = 0;

  while (offsetResult < result.length) {
    var nextOffsetBuffer = Math.round((offsetResult + 1) * sampleRateRatio);

    var accum = 0,
      count = 0;

    for (var i = offsetBuffer; i < nextOffsetBuffer && i < buffer.length; i++) {
      accum += buffer[i];
      count++;
    }

    result[offsetResult] = accum / count;
    offsetResult++;
    offsetBuffer = nextOffsetBuffer;
  }

  return result;
}

function pcmEncode(input) {
  var offset = 0;
  var buffer = new ArrayBuffer(input.length * 2);
  var view = new DataView(buffer);
  for (var i = 0; i < input.length; i++, offset += 2) {
    var s = Math.max(-1, Math.min(1, input[i]));
    view.setInt16(offset, s < 0 ? 0x8000 : 0x7fff, true);
  }
  return buffer;
}

function getAwsEventMessage(buffer) {
  return {
    headers: {
      ":message-type": {
        type: "string",
        value: "event",
      },
      ":event-type": {
        type: "string",
        value: "AudioEvent",
      },
    },
    body: buffer,
  };
}

function speechToText(io, config) {
  let ws;
  io.on("start", () => {
    console.log("---------start");
    let awsURL = awsSignature.createPreSignedUrl({
      region: config.region,
      sampleRate: 16000,
      languageCode: "en-US",
      accessKeyId: config.accessKeyId,
      secretAccessKey: config.secretAccessKey,
    });

    ws = new WebSocket(awsURL);

    //open up our WebSocket connection
    // socket = new WebSocket(url);
    ws.binaryType = "arraybuffer";

    ws.on("open", () => console.log("open"));
    ws.on("message", () => console.log("message"));
    ws.on("error", () => console.log("err"));
    ws.on("close", () => console.log("close"));
  });

  io.on("speech_to_text", (stream, data) => {
    console.log("write-----");

    if (ws.readyState === ws.OPEN) {
      console.log("ssssssssssssssssss data-0-----------");

      ws.send(convertAudioToBinaryMessage(stream));
    }
  });
}

```

**Screenshots**

<details>
<summary>Screenshot</summary>

<img width="601" alt="Screenshot 2020-07-07 at 11 55 02 AM" src="https://user-images.githubusercontent.com/16894018/86731171-b3815f80-c048-11ea-8533-a3df8497e84f.png">

</details>

**Comment by ajredniwja** [comment]
Hey @SyedHaris94 thank-you for reaching out to us with your issue, can you please share how you are consuming the aws-sdk-js in your application?

**Comment by SyedHaris94** [comment]
Hi @ajredniwja for speech-to-text i have provided the code and i use awsSignature for speech-to-text from aws-sdk

**Comment by ajredniwja** [comment]
> Hi @ajredniwja for speech-to-text i have provided the code and i use awsSignature for speech-to-text from aws-sdk

Hey @SyedHaris94, the WebSockets are not natively supported in JS-SDK-v2 however I would recommend you to try the [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3) gamma.3 version as it supports it natively. 

Thee source code using it:
https://github.com/AllanFly120/amazon-transcribe-websocket-static/tree/test/sdk-client

Closing this issue now, please reach out if you have any other questions.
