### ISSUE TITLE
request.js throws error instead of returning error as callback

### ISSUE THREAD

**Issue by vrunoa** [aws/aws-sdk-js#3341]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When using `lambda.invoke` every now and then we encounter an issue where request.js raises an exception that cant be easily handle using callbacks. This line:
https://github.com/aws/aws-sdk-js/blob/master/lib/request.js#L31

Why is this considered fatal and not returning an error as a callback?

Code
```
lambda.invoke(params, function(err, data) {`
```

Error stack:
```
/sauce/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^
prepareStackTrace (internal/errors.js:30:29),formatError (internal/util/inspect.js:873:19),formatRaw (internal/util/inspect.js:681:14),formatValue (internal/util/inspect.js:569:10),inspect (internal/util/inspect.js:223:10),formatWithOptions (internal/util/inspect.js:1651:40),Object.Console.<computed> (internal/console/constructor.js:277:10),Object.warn (internal/console/constructor.js:287:61),Object.con.<computed> [as error] (/sauce/node_modules/console-stamp/main.js:35:24),Response.<anonymous> (/sauce/api/lambda.js:12:15),Request.<anonymous> (/sauce/node_modules/aws-sdk/lib/request.js:364:18)
```

What workaround do you recommend?

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
We're using this on ECS tasks

**Details of the browser/Node.js version**
node - v12.3.1 - ubuntu 14:04 docker container

**SDK version number**
aws-sdk 2.212.1

**To Reproduce (observed behavior)**
Is not easy to reproduce, as the issue is flaky. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @vrunoa thank-you for reaching out to us with your issue, can you please share your code and the use case?

Have you considered using Promises?

**Comment by vrunoa** [comment]
Hi @ajredniwja thanks for reaching out. Cant share full code, but its basically this:

```javascript
var invoke = function(params, onFailure, callback) {
  lambda.invoke(params, function(err, data) {
    if (err) {
      console.error('lambda.invoke error', err);
      return onFailure();
    }
    if (data.StatusCode !== 200 || data.FunctionError) {
      // do something
      // retry on failure
      onFailure();
    } else {
      // lambda function success
      if (data.Payload) {
        callback(null, JSON.parse(data.Payload));
      } else {
        callback();
      }
    }
  });
};
```
what I would like to understand, if possible, is why the `throw error` could be triggered as this doesn't happen very often, it's flaky.

We can try to use promises on throw and retry.

**Comment by ajredniwja** [comment]
Can you use the lates version of the SDK?
