### ISSUE TITLE
Cognito Idp - listGroups UserPoolId invalid

### ISSUE THREAD

**Issue by MinCheTsai** [aws/aws-sdk-js#3344]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

CognitoIdentityServiceProvider -> listGroups -> UserPoolId

InvalidParameterException: 1 validation error detected: Value ' ap-northeast-1_xxx' at 'userPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\w-]+_[0-9a-zA-Z]+

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes, Lambda, this bug is urgent

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v12.18.2

**SDK version number**
v2.713.0

* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
```
const AWS = require('aws-sdk')
try {
  const cognitoIdp = new AWS.CognitoIdentityServiceProvider()
  await cognitoIdp.listGroups({
    UserPoolId:  'ap-northeast-1_xxx'
  }).promise()
} catch(error) {
  console.log(error)
  // InvalidParameterException: 1 validation error detected: Value ' ap-northeast-1_xxx' at 'userPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\w-]+_[0-9a-zA-Z]+
}
```

** The  [\\w-]+_[0-9a-zA-Z]+ can't validate UserPoolId, \\w is correctly or \w?*

**Expected behavior**
Return cognito user groups

**Screenshots**
none

**Additional context**
none

**Comment by philipwigg** [comment]
```
// InvalidParameterException: 1 validation error detected: Value ' ap-northeast-1_xxx' at 'userPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\w-]+_[0-9a-zA-Z]+
```

There seems to be a space just before the ```ap-northeast-1_xxx``` in your error message above. I think that's your issue.

**Comment by ajredniwja** [comment]
@MinCheTsai Can you please check what @philipwigg mentioned in his comment?

**Comment by MinCheTsai** [comment]
@philipwigg @ajredniwja I removed space then work correct, Thank you for help.
