### ISSUE TITLE
SenderID specified using "publish(params)" not shown

### ISSUE THREAD

**Issue by tehjnito** [aws/aws-sdk-js#3345]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Messages I send via this sdk are not received with the SenderID I specify, instead the sender is labeled 'NOTICE'.
I've sent SMS messages from the AWS console to the same phone numbers as I've used with the sdk and those messages are received with the SenderID I specified in the console.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v14.4.0

**SDK version number**
aws-sdk@2.713.0

**To Reproduce (observed behavior)**
I've tried using these params:

```
// Create publish parameters
    var params = {
        MessageAttributes: {
            'SenderID': {
                DataType: 'String', /* required */
                StringValue: sender,
            }
        },
        Message: msg,
        PhoneNumber: number,
    };
```
and this: 
```
// Create publish parameters
    var params = {
        MessageAttributes: {
            'SNS.SMS.SenderID': {
                DataType: 'String', /* required */
                StringValue: sender,
            }
        },
        Message: msg,
        PhoneNumber: number,
    };
```
and this (which throws an error about "AWS/Amazon" reserved words):
```
// Create publish parameters
    var params = {
        MessageAttributes: {
            'AW.SNS.SMS.SenderID': {
                DataType: 'String', /* required */
                StringValue: sender,
            }
        },
        Message: msg,
        PhoneNumber: number,
    };
```

**Expected behavior**
Expected to received a message from the SenderID I specified, not "NOTICE" - similar to what I achieved using the AWS console.

**Comment by ajredniwja** [comment]
Hey @tehjnito Thank-you for reaching out to us with your issue, I have tried using both console and the SDK and I was not able to reproduce this. Maybe this is because `senderId` is not supported in the US. 

You can find more information why notice is used [here](https://docs.aws.amazon.com/sns/latest/dg/sms_publish-to-phone.html).

Can you try using `AWS.SNS.SMS.SenderID` as I saw `s` missing from the attributes in your example. 

With something like:

```JavaScript
 const params = {
    PhoneNumber: cellphone,
    Message: 'Hello there!',
    MessageAttributes: {
      'AWS.SNS.SMS.SenderId': { DataType: 'String', StringValue: 'Test' },
    },
  };
```

**Comment by tehjnito** [comment]
@ajredniwja Hey, 
I've tried using `AWS.SNS.SMS.SenderID` as you've suggested, however this error gets thrown `ParameterValueInvalid: Message attribute names starting with 'AWS.' or 'Amazon.' are reserved for use by Amazon.`

I've also, tried to set the `SMSType` which does not seem to change anything.
I'm now thinking that the `MessageAttributes` value is just straight up being ignored.

Also, Ive been unable to receive messages for a little over a day now, even though method returns a successful value with a message id.

**Comment by ajredniwja** [comment]
Thankyou for your response, taking this to the service team.

**Comment by tehjnito** [comment]
@ajredniwja Thank you
