### ISSUE TITLE
"Forbidden: null" error on HeadObject request

### ISSUE THREAD

**Issue by Gricardov** [aws/aws-sdk-js#3346]
Confirm by changing [] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Framework Core: 1.71.3
Plugin: 3.6.12
SDK: 2.3.1
Components: 2.30.11

**Describe the question**

Hi chamos!
I'm having a very bad time trying to find a solution. I get a "Forbidden: null" error when my lambda does a s3:headobject request. The lambda gets triggered on a s3:CreatedObject event and then is supposed to update a dynamodb table with Metadata values. The error doesn't have any further explanation. I've already checked my CloudFormation template and gave it all the possible permissions. Even, I checked and re-checked the resources were specified correctly.

I have followed this tutorial and it was working fine for a while, then suddenly stopped working: https://serverlessfirst.com/serverless-photo-upload-api/

*This is my lambda configuration*

procesarArchivoSubido:
    handler: fuente/manejadores/procesarArchivoSubido.manejador
    iamRoleStatements:
            -   Effect: Allow
                Action:
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                Resource: ${self:custom.TablaEvento.arn}
            -   Effect: Allow
                Action:
                    - s3:ListBucket
                    - s3:GetObject
                    - s3:HeadObject
                Resource:
                    - arn:aws:s3:::${self:custom.BaldeRecursosPublicos.nombre}/*
                    - arn:aws:s3:::${self:custom.BaldeRecursosPublicos.nombre}
    events:
      - s3:
          bucket: ${self:custom.BaldeRecursosPublicos.nombre}
          event: s3:ObjectCreated:*
          rules:
            - prefix: subidas/
          existing: true

*This is where the error happens* (I already checked the values were not null or something like that)

async function procesarArchivoSubido(event, context) {
  const registro = event.Records[0].s3;
  try {
    const objetoS3 = await s3.headObject({ Bucket: registro.bucket.name, Key: registro.object.key }).promise();
... }

*This is the only error I receive*

Forbidden: null

*I hope you can help me.* I would also like to know if there is a way to specifiy a maximum allowed size for presigned s3 urls. I don't find a suitable solution for React Native.

Thanks in advance!

**Comment by ajredniwja** [comment]
@Gricardov thank-you for reaching out to us with your issue. 

`Forbidden: null` error is always because of lack of permissions. 

Have you followed the step found [here](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-execution-role-s3-bucket/).

Can you also bump up the SDK version by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies)

And can you elaborate on the question about the size? Are you talking about the size of the object?

**Comment by Gricardov** [comment]
Thanks, for your response, @ajredniwja. I followed the tutorials but it still doesn't work. Based on the coded I showed you, is there any error?

**Comment by ajredniwja** [comment]
Were you able to bump up the SDK version?

**Comment by justindra** [comment]
FYI, if anyone else runs into it, I found out that the key provided is encoded and spaces replaced with `+`. So just have to do this before processing it

```ts
const srcKey = decodeURIComponent(event.Records[0].s3.object.key.replace(/\+/g, " "));

// use srcKey instead of the given object key
```

**Comment by hassanmehdi98** [comment]
Something that I was missing was this piece of information from the [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#:~:text=Permissions,code%20403%20error.)
![image](https://github.com/aws/aws-sdk-js/assets/59412352/0189e9d2-60f2-4418-8f98-e02c47c0c158)

If the object you want to "Head" does not exist, then you might need to add the `s3:ListBucket` permission as well
