### ISSUE TITLE
EC2 Metadata roleName request returned error 169.254.169.254  port: 80

### ISSUE THREAD

**Issue by vrathore18** [aws/aws-sdk-js#3348]
`aws-sdk@2.656.0`
Using network Policy I restricted my pod's egress ports. Initially, all the ports were open and everything was working fine and after the restriction, I started getting this error 

```
Error: connect ETIMEDOUT 169.254.169.254:80\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) 
{\n  message: 'Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1',\n  
errno: 'ETIMEDOUT',\n  code: 'CredentialsError',\n  
syscall: 'connect',\n  address: '169.254.169.254',\n  port: 80,\n  time: 2020-07-15T08:28:51.595Z,\n  originalError: {\n    
message: 'Could not load credentials from any providers',\n    errno: 'ETIMEDOUT',\n    code: 'CredentialsError',\n    syscall: 'connect',\n    
address: '169.254.169.254',\n    port: 80,\n    time: 2020-07-15T08:28:51.595Z,\n    originalError: {\n      
message: 'EC2 Metadata roleName request returned error',\n      errno: 'ETIMEDOUT',\n      code: 'ETIMEDOUT',\n      syscall: 'connect',\n      
address: '169.254.169.254',\n      port: 80,\n      time: 2020-07-15T08:28:51.595Z,\n      originalError: [Object]\n    }\n  }\n}","time":"2020-07-15T08:28:51.603Z",
"src":{"file":"/app/sharedmodule/library/ServiceManager.ts","line":306,"func":"myEventPool.ch.consume.noAck"},"v":0}
```

Even though I have allowed port 80 and some other ports but still getting this issue. what extra ports do I need to open? I am trying to connect s3 and SES service by assuming roles in AWS.  Right now this all ports are open.

`  egress:
  - to:
    ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 5000
      protocol: TCP
    - port: 5000
      protocol: UDP
    - port: 27017
      protocol: TCP
    - port: 443
      protocol: TCP
    - port: 443
      protocol: UDP
    - port: 6379
      protocol: TCP
    - port: 8080
      protocol: TCP
    - port: 80
      protocol: TCP
    - port: 80
      protocol: UDP
    - port: 5672
      protocol: TCP
    - port: 943
      protocol: TCP
    - port: 1194
      protocol: TCP`

**Comment by ajredniwja** [comment]
Hey @vrathore18 can you please follow the issue template found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=).

As I would need more information.
