### ISSUE TITLE
Lets say if I have https proxy server, do i just simply specify agent: proxy(https://proxyserver:port) ??

### ISSUE THREAD

**Issue by hamzakhawaja27** [aws/aws-sdk-js#3351]
AWS NodeJs SDK only has httpOptions for configuring proxy.
Lets say if I have https proxy server, do i just simply specify agent: proxy(https://proxyserver:port) ??
Your NodeJS SDK is not clear at all.

Please provide guidance on how to use https proxy in AWS NODEJS SDK. 

Any guidance will be appreciated.

**Comment by ajredniwja** [comment]
Hey @hamzakhawaja27 thank-you for reaching out to us, you can follow the guidelines below:

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html

Closing this, please reach out if you have any additional questions.
