### ISSUE TITLE
Node package size large increase due to checked-in binary file (aws-sdk-2.714.0.tgz)

### ISSUE THREAD

**Issue by devpow112** [aws/aws-sdk-js#3352]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Looks like the `aws-sdk-2.714.0.tgz` got checked into the source code for the repo and is deployed as part of the npm package. Is this correct? Wasn't doing this in `2.713`. Noticed this cause we have package size limits when deploying and this blew the size way up.

**Is the issue in the browser/Node.js?**
Node.js.

**If on Node.js, are you running this on AWS Lambda?**
Yes, using serverless for deployment.

**Details of the browser/Node.js version**
v12.16.2

**SDK version number**
v2.714.0

**To Reproduce (observed behavior)**
Observe file being present is repository that wasn't there with previous version.

**Expected behavior**
I expect the `aws-sdk-2.714.0.tgz` file to not be there

**Screenshots**
![image](https://user-images.githubusercontent.com/9043211/87682761-3d6ab000-c74e-11ea-8a16-0539e9e4223d.png)

**Additional context**
None

**Comment by BardiaN** [comment]
Same problem here

**Comment by ajredniwja** [comment]
Thank you for bringing this up. The file should be removed from the package. The change should be reflected soon in 2.714.1

**Comment by devpow112** [comment]
@ajredniwja awesome! Thanks for the fast response

**Comment by trivikr** [comment]
Update: v2.714.1 is released with the fix https://github.com/aws/aws-sdk-js/releases/tag/v2.714.1
The file `aws-sdk-2.714.0.tgz` is no longer in root folder https://github.com/aws/aws-sdk-js/tree/v2.714.1

**Comment by ajredniwja** [comment]
Closing the issue now.

**Comment by devpow112** [comment]
Unfortunately it is still there https://github.com/aws/aws-sdk-js/blob/v2.714.1/aws-sdk-2.714.0.tgz :(

**Comment by ajredniwja** [comment]
> @ajredniwja @trivikr Unfortunately it is still there https://github.com/aws/aws-sdk-js/blob/v2.714.1/aws-sdk-2.714.0.tgz :(

Checking with the team

**Comment by ajredniwja** [comment]
@devpow112 done now. Apologies for the confusion.

**Comment by ajredniwja** [comment]
Fixed in https://github.com/aws/aws-sdk-js/releases/tag/v2.714.2
