### ISSUE TITLE
Route53.listResourceRecordSets requires MaxItems to be a string -- shouldn't it be a number?

### ISSUE THREAD

**Issue by jedwards1211** [aws/aws-sdk-js#3354]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
Title says it all.

**Comment by jedwards1211** [comment]
@ajredniwja is it not a bug that it requires a stringified number?

**Comment by ajredniwja** [comment]
@jedwards1211 sorry lost track of the issue,
 https://github.com/aws/aws-sdk-js/blob/f1c69ef7606a53f143f70c9da5f6e9737be4b060/apis/route53-2013-04-01.normal.json#L5010
 
 Looking here, it is set by the service to be a string which wasnt marked as a bug originally because it wasnt a bug with the SDK itself, with that being said, I believe it'll be a breaking change for many customers if it is changed to a number.

**Comment by jedwards1211** [comment]
So you're saying you'll release a fix with the next major version right?

**Comment by ajredniwja** [comment]
The json for models that we are talking about is generated by the service, I can take the request to them as a bug, but since it will be a breaking change and the docs mention it to be a string, I'd personally feel this should not be changed. 

I'll update you once I hear back from them.

**Comment by jedwards1211** [comment]
Just because something is documented doesn't make it right.  If it were right to use a string for the page size then all AWS APIs would use it for paging, but I'm not aware of any others that do.  The only legitimate reason to use a string for an integer value would be to support very large numbers, but that would mean ludicrously huge pages, so there's no valid reason to use a string for a page size field.  Which makes me think the string page sizes in the Route53 API came from either a strange case of leaky abstraction, or deranged reasoning.

**Comment by ajredniwja** [comment]
@jedwards1211 My bad, I wanted to mention docs in context of people already using it, I am more concerned about the breaking change but I have let the Route53 team know and will share what reasoning they have and if they want to make this change. Thanks

**Comment by jedwards1211** [comment]
And as far as breaking changes go, maybe they could add support for passing numbers but continue to allow string values.

**Comment by omarioffline** [comment]
const AWS = require("aws-sdk");
const ecr = new AWS.ECRPUBLIC({
  region: process.env.AWS_REGION,
  apiVersion: '2020-10-30'
})

await ecr.getAuthorizationToken().promise();
[amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc (1).zip](https://github.com/aws/aws-sdk-js/files/7287907/amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc.1.zip)
