### ISSUE TITLE
createPresignedPost callback to upload get AccessDenied

### ISSUE THREAD

**Issue by wfk007** [aws/aws-sdk-js#3357]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
invoke createPresignedPost function
in callback get the data map
send post http request and get AccessDenied

```js
s3.createPresignedPost(
  {
    Bucket: 'bucketName',
    Fields: {
      key: key, // use Date.now() here
    },
    Expires: 60 * 60,
  },
  (err,data)=>{
    // send post request
      const form = new FormData();
      for (const field in data.fields) {
        form.append(field, data.fields[field]);
      }
      fetch(data.url, {
        method: 'post',
        body: form,
      })
        .then(function(response) {
          return response.json();
        })
        .then(function(myJson) {
          console.log(myJson);
        });
  }
);
```

thx i reeeeeeeeally need your help

**Comment by ajredniwja** [comment]
@wfk007 Thank-you for reaching out to us with your issue, I am not sure if I understand your question here.

Are you able to use `createPresignedPost` API alone? 

You can make additional requests in another function once you are able to achieve that.
