### ISSUE TITLE
DynamoDB.DocumentClient scan returns unexpected-order properties in JSON result 

### ISSUE THREAD

**Issue by kasamachenkaow** [aws/aws-sdk-js#3358]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
We tried to scan all the item in the table with something like `new DynamoDB.DocumentClient().scan()`
and the order of properties inside the JSONs returned by `scan()` was different than the data in the table in AWS

e.g. data in production is -> 
```json
{
  "a": 1,
  "b": 20,
}
``` 
instead it returned -> 
```json
{
  "b": 20,
  "a": 1,
}
``` 

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.14.1

**SDK version number**
2.714.2

**To Reproduce (observed behavior)**
We use something like this fucntion
```js
const getDynamoItems = async ({ region, tableName }) => {
  const dynamoClient = new DynamoDB.DocumentClient({ region, maxRetries: 3 })
  const items = []
  let lastEvaluatedKey
  do {
    const result = await dynamoClient.scan({ TableName: tableName, ExclusiveStartKey: lastEvaluatedKey }).promise()
    lastEvaluatedKey = result.LastEvaluatedKey
    result.Items && items.push(...result.Items)
  } while (lastEvaluatedKey)
  return items
}
```

**Expected behavior**
The `scan()` should return the exact same data resides in the the AWS table

**Additional context**
My OS is OSX Catalina 10.15.5 (19F101)

**Comment by ajredniwja** [comment]
Hey @kasamachenkaow Thank-you for reaching out to us with your issue. The scan operation doesn't return or promise to return the results in any specific order. You can however use Sort Keys to organize the data as found [here](https://aws.amazon.com/blogs/database/using-sort-keys-to-organize-data-in-amazon-dynamodb/). Any change to this functionality would have to come from the service team. 

Closing this now, feel free to add a comment if you feel differently.

**Comment by kasamachenkaow** [comment]
Hey, @ajredniwja 

Thanks for answering

but we don't have problems with the order of the documents instead we get the order issue with the properties within the document itself

like if the document in the DDB table is
```
{
  a: 1,
  b: 2,
}
```
the actual result we get from the library is
```
{
  b: 2,
  a: 1,
}
```

also I think the problem might be in the client because in the `cli` the order of them is correct.
