### ISSUE TITLE
multiple files Upload via aws-sdk has considerable amount of delay

### ISSUE THREAD

**Issue by Naveenkumar36** [aws/aws-sdk-js#3360]
Confirm by changing [ ] to [x] below:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Specification :
Language : Typescript 
Plugin name: "AWS-SDK" 
Plugin version: "2.519.0"

Brief Introduction:
1. We are developing Typescript application which interacts with AWS S3  via AWS-SDK plugin.
2. For uploading object we use manageUpload object (for more details https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html )
3. we subscribe to callback to obtain file upload progress 'httpUploadProgress' and manage upload 'send' function has callback function to return error/ success.
4. even after httpUploadProgress is completed (i.e loaded = total), send function taking considerable delay to get callback to know final status of file uploading

Question i have 
* How long does it take for AWS S3 to save and load an item, even after httpUploadProgress is complete? 
* Is there a function to calculate time taken b/w  'httpUploadProgress' and 'send' function based on item size?
* Is the time taken b/w  'httpUploadProgress' and 'send' function gonna be different if I choose multiples files to be uploaded.
* Is there any document regarding delay b/w httpUploadProgress  and send function callback that i can refer to

**Comment by ajredniwja** [comment]
Hey @Naveenkumar36 Thank-you for reaching out to us with your issue. 

>* How long does it take for AWS S3 to save and load an item, even after httpUploadProgress is complete? 

There is no set time that can be provided, it is almost immediate.
>* Is there a function to calculate time taken b/w  'httpUploadProgress' and 'send' function based on item size?

No, unfortunately there is no function to track that. Everything on S3 environment is happening asynchronously. 
It should be almost immediate.  

>* Is the time taken b/w  'httpUploadProgress' and 'send' function gonna be different if I choose multiples files to be uploaded.

That will specifically depend on how you are sending the files. However if you are sending multiple files, every file will need to go through the upload function and that point it will regarded as a single upload. You might not wanna kick all of them at once but do them one by one to not kill the process(if there are a lot of files).
>* Is there any document regarding delay b/w httpUploadProgress  and send function callback that i can refer to

I was not able to find any documents regarding that as I was able to reproduce the delay, once the `total` and `loaded` is equal it does the send operation and callback returns the success response pretty immediately. 

It might be how you are using the function in your code which might cause the delay.

**Comment by Naveenkumar36** [comment]
Thank you for looking into this issue and for your response.

Hi Ajwinder,

In your response u mentioned, the success response was "almost immediate", can u provide more details on that.
i mean, what's the exact delay, what's the file size and system/server specification.

I ran test data, i found the below results.

1. when i upload one 2.5gb file, it took around 2.4 sec to receive success response.

2. when i uploaded multiple file (20 files) of size 2.5gb each, i got below results.

****$$** FILENAME****2.5gbdata1.mf4******UPLOAD TIME***** 153.798
****$$** FILENAME****2.5gbdata2.mf4******UPLOAD TIME***** 39.273
****$$** FILENAME****2.5gbdata5.mf4******UPLOAD TIME***** 42.338
****$$** FILENAME****2.5gbdata3.mf4******UPLOAD TIME***** 37.643
****$$** FILENAME****2.5gbdata7.mf4******UPLOAD TIME***** 34.687
****$$** FILENAME****2.5gbdata9.mf4******UPLOAD TIME***** 31.389
****$$** FILENAME****2.5gbdata8.mf4******UPLOAD TIME***** 28.377
****$$** FILENAME****2.5gbdata13.mf4******UPLOAD TIME***** 20.581
****$$** FILENAME****2.5gbdata6.mf4******UPLOAD TIME***** 33.204
****$$** FILENAME****2.5gbdata11.mf4******UPLOAD TIME***** 26.945
****$$** FILENAME****2.5gbdata10.mf4******UPLOAD TIME***** 24.006
****$$** FILENAME****2.5gbdata12.mf4******UPLOAD TIME***** 19.194
****$$** FILENAME****2.5gbdata4.mf4******UPLOAD TIME***** 22.326
****$$** FILENAME****2.5gbdata17.mf4******UPLOAD TIME***** 13.674
****$$** FILENAME****2.5gbdata14.mf4******UPLOAD TIME***** 16.313
****$$** FILENAME****2.5gbdata15.mf4******UPLOAD TIME***** 11.245
****$$** FILENAME****2.5gbdata16.mf4******UPLOAD TIME***** 10.36
****$$** FILENAME****2.5gbdata18.mf4******UPLOAD TIME***** 7.627
****$$** FILENAME****2.5gbdata20.mf4******UPLOAD TIME***** 4.791
****$$** FILENAME****2.5gbdata19.mf4******UPLOAD TIME***** 3.362

Note: upload time is in seconds and upload time is calculated by considering the time difference b/w httpProgress (when it's completed) and success event.
system specifications on which above test case ran:  
Processor: Intel i7-4790 CPU @ 3.60GHz
Ram: 16
Internet speed: upload = 300Mbps, download = 500Mbps


back to the issue, as u can see the delay kept on decreasing.
what contributes to the delay?
is there a way to decrease the delay?

Thanks in advance

**Comment by ajredniwja** [comment]
@Naveenkumar36,

Unfortunately I believe the total time can be around that time. 

I am using the code mentioned below:

```JavaScript
var AWS = require('aws-sdk');
var fs = require('fs');

var s3 = new AWS.S3({region: 'us-west-2', logger: console});

const fStream = fs.createReadStream('file');

var params = {Bucket: 'xxx', Key: 'xxx', Body: fStream};

var upload = s3.upload(params);

upload.on("httpUploadProgress", function (evt) {
    console.log(evt.total, evt.loaded);
});

upload.send(function (err,data) {
    console.log(err, data)
});
```

Once `evt.total` and `evt.loaded` are equal, i.e all the parts are loaded, the send request is immediate. 

The time taken is to upload all the individual 5mb parts, if you use the code above you'd be able to see time it takes to upload every single part. 

You can try [Transfer Acceleration](https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html) which provides faster uploads.

**Comment by Naveenkumar36** [comment]
@ajredniwja 

I think u got confused, i agree it takes time for any file to upload to s3.
But in my "Note" i mentioned "Upload time"  is time difference b/w send callback and httpUploadProgress (when total == loaded).

i request you to upload multiple files (in GB) to recreate this issue.

**Comment by ajredniwja** [comment]
Hey @Naveenkumar36 I was still not able to reproduce the issue, is there any additional context? 

Is it possible to have a look at the code that you are using?
