### ISSUE TITLE
Access point ARN is not DNS compatible error when S3 Access point ARN is passed with empty accountID

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js#3363]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Access point ARN is not DNS compatible error when S3 Access point ARN is passed with empty accountID

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v14.5.0

**SDK version number**
aws-sdk@2.717.0

**To Reproduce (observed behavior)**

<details>
<summary>Code</summary>

```javascript
const AWS = require("aws-sdk");

(async () => {
  const region = "us-west-2";
  const logger = console;

  const s3Client = new AWS.S3({ region, logger });
  const stsClient = new AWS.STS({ region, logger });
  const s3ControlClient = new AWS.S3Control({ region, logger });

  const Bucket = `test-${Math.ceil(Math.random() * 10 ** 10)}`;

  await s3Client.createBucket({ Bucket }).promise();
  await s3Client.waitFor("bucketExists", { Bucket }).promise();

  const { Account } = await stsClient.getCallerIdentity().promise();
  const Name = "blahblah";

  try {
    await s3ControlClient
      .createAccessPoint({
        AccountId: Account,
        Name,
        Bucket,
      })
      .promise();
  } catch (error) {
    console.log(error);
  }

  try {
    await s3Client
      .listObjectsV2({
        Bucket: `arn:aws:s3:${region}::accesspoint/${Name}`,
      })
      .promise();
  } catch (error) {
    console.log(error);
  }

  try {
    await s3ControlClient
      .deleteAccessPoint({
        AccountId: Account,
        Name,
      })
      .promise();
  } catch (error) {
    console.log(error);
  }

  await s3Client.deleteBucket({ Bucket }).promise();
  await s3Client.waitFor("bucketNotExists", { Bucket }).promise();
})();

```

</details>

<details>
<summary>Output</summary>

```console
[AWS s3 200 0.775s 0 retries] createBucket({
  Bucket: 'test-4060189556',
  CreateBucketConfiguration: { LocationConstraint: 'us-west-2' }
})
[AWS s3 200 0.389s 0 retries] headBucket({ Bucket: 'test-4060189556' })
[AWS sts 200 0.414s 0 retries] getCallerIdentity({})
[AWS s3control 200 0.137s 0 retries] createAccessPoint({
  AccountId: '930809265900',
  Name: 'blahblah',
  Bucket: 'test-4060189556'
})
[AWS s3 undefined 0.002s 0 retries] listObjectsV2({ Bucket: 'arn:aws:s3:us-west-2::accesspoint/blahblah' })
InvalidAccessPointARN: Access point ARN is not DNS compatible. Got blahblah
    at Request.validateAccessPointArn (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/aws-sdk/lib/services/s3.js:226:28)
    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/aws-sdk/lib/request.js:408:15)
    at /Users/trivikr/workspace/aws-sdk-js-tests/node_modules/aws-sdk/lib/request.js:797:12
    at new Promise (<anonymous>)
    at Request.promise (/Users/trivikr/workspace/aws-sdk-js-tests/node_modules/aws-sdk/lib/request.js:783:12) {
  code: 'InvalidAccessPointARN',
  time: 2020-07-21T23:39:22.362Z
}
[AWS s3control 204 0.098s 0 retries] deleteAccessPoint({ AccountId: '930809265900', Name: 'blahblah' })
[AWS s3 204 0.304s 0 retries] deleteBucket({ Bucket: 'test-4060189556' })
[AWS s3 404 5.169s 1 retries] headBucket({ Bucket: 'test-4060189556' })
```

</details>

**Expected behavior**
Should return error about accountID not present

**Comment by trivikr** [comment]
Verified that the error thrown is:

```console
InvalidAccessPointARN: Access point ARN accountID does not match regex "[0-9]{12}"
```

in `aws-sdk@2.718.0`

**Comment by paul-uz** [comment]
I'm seeing this error with SDK v3. Any idea how to fix it?

**Comment by reedcozart** [comment]
I am also seeing this error when I supply a normal Bucket ARN (there are no access points defined on the bucket whatsoever). It feels like the AWS Javascript SDK is interpreting regular S3 Bucket ARNs as 'access point' and then returning 400 errors. 


RAW JSON of my PutObjectCommand captured from logs. 
`PutObjectCommand:  
{
    "middlewareStack": {},
    "input": {
        "Body": {
            "_readableState": {
                "objectMode": true,
                "highWaterMark": 16,
                "buffer": {
                    "head": null,
                    "tail": null,
                    "length": 0
                },
                "length": 0,
                "pipes": null,
                "pipesCount": 0,
                "flowing": null,
                "ended": false,
                "endEmitted": false,
                "reading": false,
                "sync": true,
                "needReadable": false,
                "emittedReadable": false,
                "readableListening": false,
                "resumeScheduled": false,
                "emitClose": true,
                "autoDestroy": false,
                "destroyed": false,
                "defaultEncoding": "utf8",
                "awaitDrainWriters": null,
                "multiAwaitDrain": false,
                "readingMore": false,
                "decoder": {
                    "encoding": "utf8"
                },
                "encoding": "utf8"
            },
            "readable": true,
            "_events": {},
            "_eventsCount": 0
        },
        "Bucket": "arn:aws:s3:::someNameOfMyBucket",
        "ACL": "bucket-owner-full-control",
        "ContentLength": 9909,
        "Key": "SomePath/someNameOfSomeFile.tsv"
    }
}`
