### ISSUE TITLE
Is it possible to use S3.ManagedUpload in browser with presigned post from server? (CredentialsError: Missing credentials in config)

### ISSUE THREAD

**Issue by hughlomas** [aws/aws-sdk-js#3365]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Trying to implement uploads from a browser to a private S3 bucket.
I'm creating a presigned post on the server, where my AWS secrets are, and fetching that from the client browser.
I was hoping to use S3.ManagedUpload but it complains about missing credentials. Obviously I don't want to have my secrets in the client.

I've looked through the documentation, google, SO, AWS forums, and the code here.

Is there some way to get S3.ManagedUpload to send using the result of S3.createPresignedPost?

**Comment by ajredniwja** [comment]
Hey @hughlomas, thank-you for reaching out to us with your issue.

See example at https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html

Which also uses the `managedUpload` to upload pictures.

Closing this now, please reach out if you have any other questions.

**Comment by jagwire16** [comment]
The example linked above does not answer the question that hughlomas posted. He was asking about having the server sign the requests so that the secrets are not exposed to the end users. The example totally ignores security and allows unauthenticated uploads.

> This security posture is useful in this example to keep it focused on the primary goals of the example. In many live situations, however, tighter security, such as using authenticated users and object ownership, is highly advisable.

Please provide an example where the client is sending an authorization request to the server to have it sign the request so that the credentials are not exposed to the user and so the bucket does not allow unauthenticated uploads.

**Comment by ajredniwja** [comment]
@jagwire16 Apologies there, you are right about the credentials getting exposed there. The preferred way is to do it on the server side or use [temporary credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html). This is a know issue, you can tweak some of the comments for some workarounds [here](https://github.com/aws/aws-sdk-js/issues/1603).
