### ISSUE TITLE
PersonalizeEvents PutEvents silently fails after providing sessionId value as 'null'

### ISSUE THREAD

**Issue by PatrykMilewski** [aws/aws-sdk-js#3371]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
After calling PersonalizeEvents PutEvents API:
```
var params = {
  eventList: [ /* required */
    {
      eventType: 'STRING_VALUE', /* required */
      properties: any /* This value will be JSON encoded on your behalf with JSON.stringify() */, /* required */
      sentAt: new Date || 'Wed Dec 31 1969 16:00:00 GMT-0800 (PST)' || 123456789, /* required */
      eventId: 'STRING_VALUE'
    },
    /* more items */
  ],
  sessionId: 'STRING_VALUE', /* required */
  trackingId: 'STRING_VALUE', /* required */
  userId: 'STRING_VALUE'
};
```
with `sessionId: 'null'`, event is ignored and doesn't affect Personalize Dataset.

PutEvents response is always 200 in this case.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
v12.18.1

**SDK version number**
v2.631.0

**To Reproduce (observed behavior)**
1. Setup working AWS Personalize with working HRNN campaign and Event Tracker.
2. Create Personalize Filter for already interacted with items based on this doc: https://docs.aws.amazon.com/personalize/latest/dg/filter.html
3. Get recommendations for user with id "123" and use filter created before.
4. Call PersonalizeEvents PutEvents for user with id "123" with itemId matching any of the items returned in recommendations using `sessionId: 'null'` as one of params value.
5. Get recommendations for user with id "123" and notice, that item was not filtered out, which means, interaction injected with PutEvents was not recognized correctly.
6. Call PersonalizeEvents PutEvents for user with id "123" with itemId matching any of the items returned in recommendations using `sessionId: '0'` as one of params value.
7. Get recommendations for user with id "123" and notice, that item was filtered out correctly this time, which means PutEvents call was successful.

**Expected behavior**
API reference mentions, that 'null' value is not allowed for `sessionId` param or events sent with PutEvents works correctly for  `sessionId: 'null'`.
Also having bad request response would be fine.

**Comment by ajredniwja** [comment]
Hey @PatrykMilewski thank-you for reaching out to us with your issue.

However I was not able to find anything related to sessionId: 'null'  in the [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/PersonalizeEvents.html#putEvents-property).

Would you be able to point me towards the link where you found the information?

**Comment by PatrykMilewski** [comment]
@ajredniwja Hey, sure!

In PutEvents params you can have to provide required `sessionId` parameter, which should be String. If you set it to `sessionId='null'` (normal String with value 'null'), then it causes the problems, described above.

**Comment by PatrykMilewski** [comment]
I believe this should have bug label, since this case is not covered in docs and due to this Personalize was not working for us on production environment.

**Comment by ajredniwja** [comment]
@PatrykMilewski I understand that, but I believe that will be expected behavior since `sessionId` is a required param and it which should indicate that it should not be null. 

The API reference mentions that `session ID` to be "The session ID associated with the user's visit."

Do you think docs should mention values which should not be null? That would nearly apply to almost every param.

**Comment by PatrykMilewski** [comment]
@ajredniwja I agree on that, but I wouldn't expect it to behave this way, when I simply provide a string "null" not null itself.

**Comment by ajredniwja** [comment]
@PatrykMilewski I did some research and found out the SDK would not send anything if only `null` is passed but would send `"null"` is passed as it is. While it is not advised to use it that way, I can reach out to the service team to get more insight on how they would want to handle or fix it.
