### ISSUE TITLE
How to use getMedia() response payload in video tag

### ISSUE THREAD

**Issue by Sheshan-sheshu** [aws/aws-sdk-js#3373]
I have used kinesisvideomedia.getMedia() in JavaScript and im receiving payload as a response from aws kinesis.
I want to use this payload in a video tag to play video fetched from aws kinesis.
How to convert payload into video and play it in a html5 video tag?

**Comment by ajredniwja** [comment]
@Sheshan-sheshu 

Thank-you for opening an issue with us.

You may need a library to do that, you can use something like (Kinesis video steams) https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/hls-playback.html

Please let me know if that doesnt work for you. I will reopen the issue.

**Comment by Sheshan-sheshu** [comment]
@ajredniwja Thanks for the reply, i'm already using the steps and playing the videos mentioned in URL given by you.
However,in aws docs it has been mentioned that if we use getMedia() latency will be less compared to what we using now (https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-playback.html).
So i'm trying with getMedia() and getting the payload as response however i'm not getting proper JS examples to convert this payload into video.

**Comment by ajredniwja** [comment]
Apologies that the issue got closed, can you share your code?
