### ISSUE TITLE
Building specific services for SDK getting error on browser

### ISSUE THREAD

**Issue by mahdiridho** [aws/aws-sdk-js#3375]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm developing a litelement based webcomponent to work with aws-sdk. The element needs both services cognito-identity and cognito-idp only. So I built specific services into the sdk following this link : 

[Building Specific Services and API Versions](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html)

I run this command line : 

`MINIFY=1 node dist-tools/browser-builder.js cognitoidentity,cognitoidentityserviceprovider > aws-cognito-sdk.min.js`

It succeed to build the file, then on my element import it like so : 

`import './aws-cognito-sdk.min';`

Serve the element and run it on browser, then I got this error on the browser : 

![Screenshot from 2020-08-03 13-26-28](https://user-images.githubusercontent.com/10230037/89152258-fb829c00-d58c-11ea-9ad6-824beb546846.png)

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser version**
Browsers:
    Chrome: 81.0.4044.129
    Firefox: 79.0

**SDK version number**
Example: v2.725.0

**To Reproduce (observed behavior)**
[https://github.com/mahdiridho/AwsSdkBundleIssue](https://github.com/mahdiridho/AwsSdkBundleIssue)

**Expected behavior**
I want to reduce the aws-sdk size by specific services bundling. It should work as dependency module for my litelement based webcomponent.

**Additional context**
So far I do simple import of the entire services of aws-sdk. It's so big and spend hours to build a production version

**Comment by ajredniwja** [comment]
Hey @mahdiridho thank-you for reaching out to us with your issue. 

Can you just try adding it to script tag and then use it? 

`<script src="aws-cognito-sdk.min.js"></script>`

or alternatively you can use browserify as well. 

Please reach out if you have any questions.

**Comment by mahdiridho** [comment]
> Hey @mahdiridho thank-you for reaching out to us with your issue.
> 
> Can you just try adding it to script tag and then use it?
> 
> `<script src="aws-cognito-sdk.min.js"></script>`
> 
> or alternatively you can use browserify as well.
> 
> Please reach out if you have any questions.

It works by load the sdk in common script, not as module. My expectation, I'm able to load the specific bundling file on ES based module like so :

`import './specific-sdk-api.js`

I have tried generate with browserify as well, but no lucky :

`AWS_SERVICES=cognitoidentity,cognitoidentityserviceprovider browserify index.js > aws-cognito-sdk.min.js`

It shows me "undefined" for AWS variable

**Comment by ajredniwja** [comment]
@mahdiridho I think that is totally because of the services you are importing not having an export artifact which will result in your code not workin the way you want. 

I think using the script tag is the recommended way to import.

**Comment by mahdiridho** [comment]
Yes, I'm doing that at the moment

While waiting for new feature to support es module import, is it on your plan in the future? I have several webcomponent based UI for implementing AWS client like dynamodb, cognito, sqs, s3, lambda, sns, etc. So if we build a specific sdk for my specific class/component it would be good then we can do : 

`import "./<specific_service_sdk>"`

Thanks

**Comment by ajredniwja** [comment]
That is something that the team has worked on in [JS-SDK-V3](https://github.com/aws/aws-sdk-js-v3). You can check it out which is still under development on a gamma release but still a good starting point for services that you are interacting with and your particular application. 

Will be closing this now, please reach out if you have any other questions.
