### ISSUE TITLE
mediaPackageVod.createAsset(params) is throwing "InternalServerErrorException: internal server error" Exception

### ISSUE THREAD

**Issue by abdullah432** [aws/aws-sdk-js#3376]
**Describe the bug**
`const response = await mediaPackageVod.createAsset(params).promise();`
above line of code start throwing following error. Some days ago the same line of code worked perfectly. This line is from lambda function (Nodejs)
```
{
    "errorType": "InternalServerErrorException",
    "errorMessage": "internal server error",
    "code": "InternalServerErrorException",
    "message": "internal server error",
    "time": "2020-08-03T17:52:50.905Z",
    "requestId": "1eacd66e-85f0-411e-b607-b9f4c30e813e",
    "statusCode": 500,
    "retryable": true,
    "stack": [
        "InternalServerErrorException: internal server error",
        "    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
        "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
        "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)"
    ]
}
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
yes 

**To Reproduce (observed behavior)**
This is the code that works before but suddenly starts throwing an exception. I'm not sure that I did some mistake or there is so issue in server.
```
const handler = async (event) => {
    console.log(`REQUEST:: ${JSON.stringify(event, null, 2)}`);

    const mediaPackageVod = new AWS.MediaPackageVod();
    const randomId = crypto.randomBytes(16).toString('hex').toLowerCase();

    try {
        const params = {
            Id: randomId,
            PackagingGroupId: process.env.GroupId,
            SourceArn: buildArnFromUri(event.hlsPlaylist),
            SourceRoleArn: process.env.MediaPackageVodRole,
            ResourceId: randomId
        };

        console.log(`Ingesting asset:: ${JSON.stringify(params, null, 2)}`);
	console.log(`before response:::::::::`);
        const response = await mediaPackageVod.createAsset(params).promise();
	console.log(`response:: ${JSON.stringify(response)}`);

        event.egressEndpoints = await cloudfrontHelper.convertEndpoints(
            process.env.DistributionId,
            event.cloudFront,
            response.EgressEndpoints
        );

        console.log(`ENDPOINTS:: ${JSON.stringify(event.egressEndpoints, null, 2)}`);
    } catch (err) {
        await error.handler(event, err);
        throw err;
    }

    return event;
};
```

**Comment by ajredniwja** [comment]
@abdullah432 can you test what version of the SDK you are using ?

You can SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
    
You can import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

**Comment by abdullah432** [comment]
ok, I will do that and back to you soon. 
Some info I want to give you, the above code is not written by me. It's written by amazon team. Here is the source code: https://github.com/awslabs/video-on-demand-on-aws
So I delete previous files in my aws console and try to recreate with help of this guide: https://aws.amazon.com/solutions/implementations/video-on-demand-on-aws/
I'm trying to add Video On Demand cloudformation template.

I'm getting same "InternalServerErrorException: internal server error". Here is the detail issue: https://github.com/awslabs/video-on-demand-on-aws/issues/98

**Comment by abdullah432** [comment]
It seems like there is an issue with us-east-1 region. After changing region to us-west-1 (Oregon), issue resolved.
https://stackoverflow.com/questions/63252043/video-on-demand-on-aws-cloudformation-template-failed-to-create

**Comment by dilraj-vidyard** [comment]
Yes. Dec. 7th. AWS had an outage in the region: us-east-1 (Ohio) (and like many others).
