### ISSUE TITLE
AWS SES : Server Error (500)

### ISSUE THREAD

**Issue by adarshnbidari** [aws/aws-sdk-js#3378]
aws email sdk is not working properly sometimes it sends emails and sometimes not!....
please fix it ASAP.

"500: Server Error\n    at Request.extractError (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\protocol\\query.js:50:29)\n    at Request.callListeners (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\sequential_executor.js:106:20)\n    at Request.emit (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\sequential_executor.js:78:10)\n    at Request.emit (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\request.js:683:14)\n    at Request.transition (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\request.js:22:10)\n    at AcceptorStateMachine.runTo (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\state_machine.js:14:12)\n    at C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\state_machine.js:26:10\n    at Request.<anonymous> (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\request.js:38:9)\n    at Request.<anonymous> (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\request.js:685:12)\n    at Request.callListeners (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\sequential_executor.js:116:18)

**Comment by ajredniwja** [comment]
I wont be able to address this issue due to lack of information. Can you please fill out an issue template found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)

Closing this issue now, please open a new issue following the issue template.
