### ISSUE TITLE
AWS SES: Server Error (500) -SDK

### ISSUE THREAD

**Issue by adarshnbidari** [aws/aws-sdk-js#3379]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I have been using the aws-sdk for AWS SES for node.js.
I am calling this api in a node/express server.
It works when i call it independently but when i integrate it with my node/express sever  it sometimes it successfully sends email but sometimes it shows Server Error:500 error.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
i am running it on my local machine

**Details of the browser/Node.js version**
v12.16.2

**SDK version number**
2.726.0

**To Reproduce (observed behavior)**

    @const sendEmailOtp = (user_email, otp) => {

    var AWS = require('aws-sdk');

    AWS.config.update({

        region: "ap-south-1",
        accessKeyId: 'ACCESS_ID',
        secretAccessKey: 'SECRET_KEY'

    });

    var ses = new AWS.SES();

    var params = {

        Destination: {

            ToAddresses: [

                user_email

            ]

        },

        Message: {

            Body: {

                Text: {

                    Charset: "UTF-8",

                    Data: `your otp is ${otp}`

                }

            },

            Subject: {

                Charset: "UTF-8",

                Data: "otp for account verification"

            }

        },

        Source: "no-reply@techslaim.in"

    };
    return ses.sendEmail(params).promise();

};
module.exports = sendEmailOtp;

**Expected behavior**

This code works when i call it independently , but when i integrate it into my node/express server it doesn't works!
So i expect it to work in my node/express server with my api's.

**Additional context**

500: Server Error\n    at Request.extractError (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\protocol\\query.js:50:29)\n    at Request.callListeners (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\sequential_executor.js:106:20)\n    at Request.emit (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\sequential_executor.js:78:10)\n    at Request.emit (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\request.js:688:14)\n    at Request.transition (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\request.js:22:10)\n    at AcceptorStateMachine.runTo (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\state_machine.js:14:12)\n    at C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\state_machine.js:26:10\n    at Request.<anonymous> (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\request.js:38:9)\n    at Request.<anonymous> (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\request.js:690:12)\n    at Request.callListeners (C:\\Users\\wwwad\\Desktop\\account_operations\\node_modules\\aws-sdk\\lib\\sequential_executor.js:116:18)"

**Comment by ajredniwja** [comment]
Hey @adarshnbidari, thank-you for reaching us to us with your issue, the description indicates that the SDK might not be the problem as it runs perfectly when you run it locally. 

Would you be able to share how you are integrating it with your node app?

**Comment by stuckinaboot** [comment]
Reopening as I’m having this same issue on localhost

**Comment by stuckinaboot** [comment]
Use the `node-ses` npm module. That worked for me (where aws-sdk gave me 500 error)

**Comment by adarshnbidari** [comment]
> Use the `node-ses` npm module. That worked for me (where aws-sdk gave me 500 error)

It works , thank you @stuckinaboot  ❤.

**Comment by jaruanbell** [comment]
Same error with `@aws-sdk/client-sesv2`
```js
import { SESv2Client, BatchGetMetricDataCommand } from '@aws-sdk/client-sesv2';

const client = new SESv2Client({
    credentials: {
        accessKeyId: 'id',
        secretAccessKey: 'key'
    },
    region: 'eu-central-1'
});

async function sendMail() {
    const params = {
        Destination: { ToAddresses: ['xyz@gmail.com'] },
        Message: {
            Source: 'Sign-up <noreply@hhh.com>',
            Subject: {
                Charset: 'UTF-8',
                Data: 'Hello'
            },
            Body: {
                Html: {
                    // HTML Format of the email
                    Charset: 'UTF-8',
                    Data: '<html><body><p style="color:#000;">HHH email verification code: 54DRWQB7</p></body></html>'
                },
                Text: {
                    Charset: 'UTF-8',
                    Data: 'HHH email verification code: 54DRWQB7'
                }
            }
        }
    };

    const command = new BatchGetMetricDataCommand(params);
    console.log(command);

    try {
        const data = await client.send(command);
        console.log(data);
    } catch (error) {
        console.log(error);
    } finally {
        console.log('--- DONE ---');
    }
}

sendMail();
```
```
InternalFailure: UnknownError
    at throwDefaultError (/var/www/ses/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_restJson1BatchGetMetricDataCommandError (/var/www/ses/node_modules/@aws-sdk/client-sesv2/dist-cjs/protocols/Aws_restJson1.js:1995:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/www/ses/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/www/ses/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /var/www/ses/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /var/www/ses/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
    at async sendMail (file:///var/www/ses/index.js:49:22) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 500,
    requestId: 'bf6397fb-c261-4896-911f-a321a582f748',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 4,
    totalRetryDelay: 579
  }
}
```

**Comment by jaruanbell** [comment]
@ajredniwja

**Comment by jaruanbell** [comment]
Same error with `@aws-sdk/client-sesv2`.
Tested on Node.js `v18.12.1`.
```js
import { SESv2Client, BatchGetMetricDataCommand } from '@aws-sdk/client-sesv2';

const client = new SESv2Client({
    credentials: {
        accessKeyId: 'id',
        secretAccessKey: 'key'
    },
    region: 'eu-central-1'
});

async function sendMail() {
    const params = {
        Destination: { ToAddresses: ['xyz@gmail.com'] },
        Message: {
            Source: 'Sign-up <noreply@hhh.com>',
            Subject: {
                Charset: 'UTF-8',
                Data: 'Hello'
            },
            Body: {
                Html: {
                    // HTML Format of the email
                    Charset: 'UTF-8',
                    Data: '<html><body><p style="color:#000;">HHH email verification code: 54DRWQB7</p></body></html>'
                },
                Text: {
                    Charset: 'UTF-8',
                    Data: 'HHH email verification code: 54DRWQB7'
                }
            }
        }
    };

    const command = new BatchGetMetricDataCommand(params);
    console.log(command);

    try {
        const data = await client.send(command);
        console.log(data);
    } catch (error) {
        console.log(error);
    } finally {
        console.log('--- DONE ---');
    }
}

sendMail();
```
```
InternalFailure: UnknownError
    at throwDefaultError (/var/www/ses/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_restJson1BatchGetMetricDataCommandError (/var/www/ses/node_modules/@aws-sdk/client-sesv2/dist-cjs/protocols/Aws_restJson1.js:1995:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/www/ses/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/www/ses/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /var/www/ses/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /var/www/ses/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
    at async sendMail (file:///var/www/ses/index.js:49:22) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 500,
    requestId: 'bf6397fb-c261-4896-911f-a321a582f748',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 4,
    totalRetryDelay: 579
  }
}
```
@ajredniwja

**Comment by GuillermoPena** [comment]
Exactly same error with @aws-sdk/client-sesv2.
Any news?

**Comment by vasusuccessive** [comment]
Did anyone get a solution? Getting same error

**Comment by vasusuccessive** [comment]
> Same error with `@aws-sdk/client-sesv2`. Tested on Node.js `v18.12.1`.
> 
> ```js
> import { SESv2Client, BatchGetMetricDataCommand } from '@aws-sdk/client-sesv2';
> 
> const client = new SESv2Client({
>     credentials: {
>         accessKeyId: 'id',
>         secretAccessKey: 'key'
>     },
>     region: 'eu-central-1'
> });
> 
> async function sendMail() {
>     const params = {
>         Source: 'Sign-up <noreply@hhh.com>',
>         Destination: { ToAddresses: ['xyz@gmail.com'] },
>         Message: {
>             Subject: {
>                 Charset: 'UTF-8',
>                 Data: 'HHH'
>             },
>             Body: {
>                 Html: {
>                     Charset: 'UTF-8',
>                     Data: '<html><body><p style="color:#000;">HHHemail verification code: 54DRWQB7</p></body></html>'
>                 },
>                 Text: {
>                     Charset: 'UTF-8',
>                     Data: 'HHH email verification code: 54DRWQB7'
>                 }
>             }
>         }
>     };
> 
>     const command = new BatchGetMetricDataCommand(params);
>     console.log(command);
> 
>     try {
>         const data = await client.send(command);
>         console.log(data);
>     } catch (error) {
>         console.log(error);
>     } finally {
>         console.log('--- DONE ---');
>     }
> }
> 
> sendMail();
> ```
> 
> ```
> InternalFailure: UnknownError
>     at throwDefaultError (/var/www/ses/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
>     at deserializeAws_restJson1BatchGetMetricDataCommandError (/var/www/ses/node_modules/@aws-sdk/client-sesv2/dist-cjs/protocols/Aws_restJson1.js:1995:51)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async /var/www/ses/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
>     at async /var/www/ses/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
>     at async /var/www/ses/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
>     at async /var/www/ses/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
>     at async sendMail (file:///var/www/ses/index.js:49:22) {
>   '$fault': 'client',
>   '$metadata': {
>     httpStatusCode: 500,
>     requestId: 'bf6397fb-c261-4896-911f-a321a582f748',
>     extendedRequestId: undefined,
>     cfId: undefined,
>     attempts: 4,
>     totalRetryDelay: 579
>   }
> }
> ```
> 
> @ajredniwja

Hi @jaruanbell,
Did you find any solution to the above problem? As me and @GuillermoPena getting the same issue

**Comment by vasusuccessive** [comment]
Hi @adarshnbidari,
Please reopen this issue

**Comment by divyasatharasi** [comment]
Hi @ajredniwja @jaruanbell @vasusuccessive 
Any update on this issue ? I am also facing this issue.
Thanks.

**Comment by ajredniwja** [comment]
Hi everyone, the original issue mentions using V2 of the SDK.
The examples mentioned above seem to use [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3).
Anyone facing the problem, can you please open a new issue in the [V3 repo](https://github.com/aws/aws-sdk-js-v3/issues) with all the required information specific to your use case.
 
 Thankyou
