### ISSUE TITLE
Uncatchable error in request.js (ERR_SOCKET_CANNOT_SEND)

### ISSUE THREAD

**Issue by joaomallmann** [aws/aws-sdk-js#3384]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Description**
In a Node.js Lambda that is configured to reuse connections with Keep-Alive, if it is kept warm, after around two hours an Uncaught Exception is thrown, not being possible to catch it in order to recreate the connection.
The connection seems being closed due to the linux tcp_keepalive_time, that is by default 7200 seconds.

**Versions**
Node.js version: 12.X
SDK version: 2.725.0

**Code snippet**
```
const sslAgent = new HttpsAgent({
    keepAlive: true,
    maxSockets: 50,
});
AWS.config.update({
    httpOptions: {
        agent: sslAgent
    }
});

const documentClient = new AWS.DynamoDB.DocumentClient();

export function dynamoDbQuery(key) {
     try {
        const request = documentClient.get({
            TableName: getDynamoDBTablename(),
            Key: { 'key': key }
        });

        request.onAsync('error', (error, response) => {
           console.log(error);
        });
        request.on('error', (error, response) => {
           console.log(error);
        });

        return request.promise();
     } catch (error) {
        console.log(error);
        throw error;
     }
}
```
**Error**
```
Uncaught Exception  {
  'errorType': 'Error',
  'errorMessage': 'Unable to send data',
  'code': 'ERR_SOCKET_CANNOT_SEND',
  'stack': [
    'Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data',
    '    at Socket.onListenError (dgram.js:511:22)',
    '    at Object.onceWrapper (events.js:422:26)',
    '    at Socket.emit (events.js:315:20)',
    '    at Socket.EventEmitter.emit (domain.js:482:12)',
    '    at dgram.js:340:14',
    '    at processTicksAndRejections (internal/process/task_queues.js:85:21)'
  ]
}
```

**Expected behavior**
The error should be catchable so the connection could be recreated.

**Comment by ajredniwja** [comment]
Hey @joaomallmann thank-you for opening this, would you be able to share your use case?

**Comment by joaomallmann** [comment]
Hi @ajredniwja,

We have a Lambda that is used to retrieve information from a DynamoDB table, this is the only responsibility of this Lambda.
This reduces the total request time by keeping the TCP connections open, so after the Lambda cold start the connections are already in place to be reused on the following requests, avoiding the costs of creating new connections for a DynamoDB request that is faster than 2ms, as [recommended by AWS itself](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html).
This reduces the total request time considerably and it works really well if the Lambda is discarded before 2 hours of its cold start.
If the same Lambda instance is used for more than 2 hours of the cold start, due to constant requests, the TCP connection seems to be closed and when handling a request after the connection/socket closure, this error is thrown.
The idea was to catch this error and retry the DynamoDB request after recreating the TCP connections and DynamoClient instead of just failing the request due to an Uncaught Exception.

I hope the use case is clear now, please let me know if you need more information.

Thank you for your support,

**Comment by AllanFly120** [comment]
Hi @joaomallmann, Thank you for providing detailed stack trace. 
It might not caused by the linux `tcp_keepalive_time` because it just:
> the interval between the last data packet sent (simple ACKs are not considered data) and the first keepalive probe;

Do you know which `console.log` clause prints the error? Or is it printed by Lambda?

**Comment by joaomallmann** [comment]
Hi @AllanFly120,

It is being printed directly by the Lambda, we were not able to catch the error or to receive any error event.

**Comment by olegario96** [comment]
Same here

**Comment by AntonBazhal** [comment]
We just had the same issue in production. Not sure whether it was caused by `keepAlive`, but changing lambda config (thus recreating instances) fixed it.

**Comment by JonHX** [comment]
Same issue here.

**Comment by lolJS** [comment]
I see this all the time in our logs the lambda in question is an API Gateway authorizer
