### ISSUE TITLE
InvalidArgument error on cloudfront createDistribution

### ISSUE THREAD

**Issue by marioch5** [aws/aws-sdk-js#3388]
Confirm by changing [ ] to [x] below:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Node.js version**
v12.16.2

**SDK version number**
v2.727.0

**Describe the question**
When i try to create a new Cloudfront distribution through the api, i receive an error saying that MinTTL is a required field but, looking at the sdk docs, it says that the property is deprecated. When i put the MinTTL on the DefaultCacheBehaviour field, it says that ForwardedValues is required, wich is another deprecated property. I am doing this with Typescript, so i also have type checking telling me that is all good. I am also specifying the latest api version on the constructor. Am i doing something wrong? Thanks! 

```
  import * as AWS from 'aws-sdk';

  constructor() {
    this.cloudfront = new AWS.CloudFront({
      credentials: {
        accessKeyId: awsConfig.accessKeyId,
        secretAccessKey: awsConfig.secretAccessKey,
      },
      region: awsConfig.cloudfront.region,
      signatureVersion: 'v4',
      apiVersion: '2020-05-31',
    });
  }

  public createDistribution(param: ICreateDistributionParam) {
    const { domain, certificateArn } = param;

    const uniqueId = `${domain}${v1()}`;

    return new Promise((resolve, reject) => {
      this.cloudfront.createDistribution(
        {
          DistributionConfig: {
            CallerReference: v1(),
            Enabled: true,
            Comment: `${domain} Production Distribution`,
            Aliases: {
              Quantity: 2,
              Items: [domain, `www.${domain}`],
            },
            Origins: {
              Quantity: 1,
              Items: [
                {
                  Id: uniqueId,
                  DomainName: awsConfig.ec2.prodLoadBalancer,
                  CustomOriginConfig: {
                    // custom origin config data
                  },
                },
              ],
            },
            ViewerCertificate: {
              ACMCertificateArn: certificateArn,
              CloudFrontDefaultCertificate: false,
              SSLSupportMethod: SSLSupportMethod.SNI_ONLY,
              MinimumProtocolVersion: MinimumProtocolVersion.TLSv1_2016,
            },
            DefaultCacheBehavior: {
              TargetOriginId: uniqueId,
              TrustedSigners: {
                Enabled: false,
                Quantity: 0,
              },
              AllowedMethods: {
                Quantity: 7,
                Items: ['GET', 'HEAD', 'OPTIONS', 'PUT', 'PATCH', 'POST', 'DELETE'],
              },
              ViewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
            },
            IsIPV6Enabled: true,
          },
        },
        (err, data) => {
          if (err) {
            return reject(err);
          }

          resolve(data);
        },
      );
    });
  }
```

Returns

`
{
  message: "The parameter MinTTL is required.",
  code: "InvalidArgument",
  statusCode: 400,
}
`

**Comment by ajredniwja** [comment]
@marioch5, thank-you for reaching out to us with your issue, do you get same results with aws-cli as well? When you use the same params?

**Comment by marioch5** [comment]
Hey, @ajredniwja thanks for answering but someone on stackoverflow already figured it out. Aparentelly if you don't want to use those defaults cache properties that are deprecated, you have to specify a CachePolicyId or a OriginRequestPolicyId. I didn't know about that. 

Just as a suggestion, the sdk docs on `createDistribution` says this:

`This field is deprecated. We recommend that you use a cache policy or an origin request policy instead of this field.`

I don't think that it should be phrased as a suggestion since you are obligated to use it if you don't use the field.

But anyway thank you for reaching out!
