### ISSUE TITLE
Error: “message”: “Missing credentials in config” after setting up credentials using Amazon Cognito

### ISSUE THREAD

**Issue by yuchen-lu** [aws/aws-sdk-js#3389]
`[Proposed Label]: Guidance`

Hello all,

I'm trying to avoid hard-coding my aws credentials in Javascript when accessing DynamoDB. I followed all steps [in the official document][1] to configure credentials using Amazon Cognito. However, when I try to access DynamoDB, I kept getting error: 

```
  "message": "Missing credentials in config",
  "code": "CredentialsError"
  ......
```
My code looks like:
```
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: "MyPoolID",
      RoleArn: "MyARN"
    });

    AWS.config.region = 'us-east-1'; // Region
    AWS.config.update({
      endpoint: "MyEndPoint"
    });


    var docClient = new AWS.DynamoDB.DocumentClient();

```

The code works fine if I hard-coded my credentials like below:
```
   AWS.config.update({
      accessKeyId: "MyID",
      secretAccessKey: "MyKey"
    });

```

Additional setup information that might be helpful:

sdk: `aws-sdk-2.7.16.min.js`

my ` ~/.aws/config`:
```
[default]
region = us-east-1

```

my `~/.aws/credentials`:
```



[default]

aws_access_key_id = MY ACCESS KEY

aws_secret_access_key = MY SCERET KEY
```

Any help would be appreciated!

  [1]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Cognito.Credentials.html

**Comment by ajredniwja** [comment]
Hey @lsegal thank-you for opening this issue, can you quickly run: 

`console.log(AWS.config.credentials);`

To see your credentials are set correctly and if they are not, can you run the command `aws configure` from your terminal and fill in the values?

**Comment by yuchen-lu** [comment]
@ajredniwja thanks for replying. By adding `console.log(AWS.config.credentials);` I can see my IdentityPolId and RoleArn are configured correctly. Since I'm not hardcoding credentials, accessID and secretAccessKey are `undefined`.

I also double checked `aws configure` and it was configured correctly.

**Comment by ajredniwja** [comment]
> @ajredniwja thanks for replying. By adding `console.log(AWS.config.credentials);` I can see my IdentityPolId and RoleArn are configured correctly. Since I'm not hardcoding credentials, accessID and secretAccessKey are `undefined`.

Do you see the same when you don't add to your code? 

```
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: "MyPoolID",
      RoleArn: "MyARN"
    });
```
