### ISSUE TITLE
High sendMessage latency

### ISSUE THREAD

**Issue by kushagrasingh-cf** [aws/aws-sdk-js#3391]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Hi,

We use `aws-sdk/clients/sqs :: sendMessage` to push messages to a queue. We usually see a P99 of 200 ms for this, however, sometimes (8-10 times a day) this shoots up to an unusually large number (3-4 minutes). 

- AWS support confirmed that the actual processing time on their servers is between 5-10 ms, so that confines the problem to our service / aws sdk.
- Tried passing a timeout of 30000 to the `httpOptions.timeout` config (as suggested in a few issues/SO discussions). We see the spikes despite this timeout.

We're using version `2.7.0`. Would really appreciate any pointers on how to debug this further.

Thanks!

**Comment by ajredniwja** [comment]
Hey @kushagrasingh-cf, thanks for brining this up, is there anything in specific that I can look at since the issue is intermittent and I am not quite able to reproduce it, also if you could collect some logs, that would be really helpful.

**Comment by kushagrasingh-cf** [comment]
Hey @ajredniwja! 

Sorry for such a delayed response, I missed this notification.

From our end the only logs which can be added are pertaining to the time taken by sqs itself. The sdk itself does not throw any error. Essentially we are profiling it as 

```
// begin timer
AWS.SQS.sendMessage
// end timer
```

So very ambiguous for us as well. Could you suggest some way we can further identify what could be causing this? We don't see any failures, just very high latencies.

On a side not, when we reduced the sqs conf timeout to 15000ms, our receiveMessages consumers stopped processing any message. We saw a lot of timeout errors from `SQS.receiveMessage`. Our method call is
```
this.SQS.receiveMessage({
                QueueUrl: this.createUrl(resource),
                MessageAttributeNames: ["All"],
                MaxNumberOfMessages: batchSize || 1,
                WaitTimeSeconds: waitTimeInSeconds
            } ... 
```

Here `waitTimeInSeconds` is 20, could this be a reason for consumers not receiving any messages?

**Comment by throrin19** [comment]
Same problem here, we have very high latencies with `AWS.SQS.sendMessage` randomly (in one lambda it's 13x/days, in another it's 1x/hour)

**Comment by kushagrasingh-cf** [comment]
@throrin19 This issue just got resolved for us one day, no changes from our end. I would attribute this to aws black magic

**Comment by throrin19** [comment]
This is really annoying :(. This is my second black magic problem with AWS (I think to make an AWS black magic bingo)

**Comment by ajredniwja** [comment]
Apologies here, I tried it several times and was not able to isolate the problem here, was anyone able to find any certain situations where error occurs every time?
