### ISSUE TITLE
retryDelayOptions.customBackoff function called for non-retryable errors

### ISSUE THREAD

**Issue by jgehrcke** [aws/aws-sdk-js#3401]
**SDK version number**
v2.730

I noticed that `retryDelayOptions.customBackoff()` is being called once for non-retryable (e.g., 404-style) errors. The return value is subsequently ignored (no retry is going to happen).

For non-retryable errors there is one call too much which often times is not a problem but of course it can be for side effects triggered by the `customBackoff()` implementation.

Docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#retryDelayOptions-property

That problem was introduced with https://github.com/aws/aws-sdk-js/pull/2898:

### Before #2898:

```javascript
if (err && err.retryable && retryCount < maxRetries) {
    retryCount++;
    var delay = util.calculateRetryDelay(retryCount, options.retryDelayOptions);
    setTimeout(sendRequest, delay + (err.retryAfter || 0));
}
```
Note that here `calculateRetryDelay()` was only ever called when error information was available (`err` was set) and when `err.retryable` was true.

### After #2898:
```javascript
var delay = util.calculateRetryDelay(retryCount, options.retryDelayOptions, err);
if (err && err.retryable && retryCount < maxRetries && delay >= 0) {
    retryCount++;
    setTimeout(sendRequest, delay + (err.retryAfter || 0));
}
```
Note that `util.calculateRetryDelay()` is always called, w/o inspecting `err.retryable`.

Notably, it is even getting called when `err` is not set (which seems to be the case for 404-style API responses!).

However, the actual retry is then only triggered when `err && err.retryable` -- just like _before_ the patch. That is, in that case the return value of `util.calculateRetryDelay()` (calling `retryDelayOptions.customBackoff()`) is ignored. 

### Proposal:

- Call `retryDelayOptions.customBackoff()` only when the library internals have determined that `err && err.retryable`.
- Document that behavior.

Future direction:
If if is up for dispute whether or not a specific error is retryable and custom code should have a word then maybe another hook is required. For example, a hook where calling code can inspect the API response in detail and set `err` and/or `err.retryable`. All that happening _before_ `retryDelayOptions.customBackoff()` gets invoked.

I'd be happy to work on a patch, and in fact might get to doing so still today.

**Comment by ajredniwja** [comment]
Hey @jgehrcke, thank-you for bringing this up, your initial PR looks good, can you complete all the tests?

**Comment by jgehrcke** [comment]
Hey! Thanks for picking this up. Are you asking to run tests locally? Can
try that tomorrow (is the Travis CI feedback not sufficient?). Or are you
asking to add tests?

**Comment by ajredniwja** [comment]
@jgehrcke I mean all the checklist tests in your PR

**Comment by jgehrcke** [comment]
> You're good, I'll have a look at the PR?

Thanks and yes, please :-).

**Comment by jgehrcke** [comment]
@ajredniwja would appreciate if we could move this forward!! Thank you :-) Anything I can still do?

**Comment by jgehrcke** [comment]
@ajredniwja @AllanFly120 would love for this to not stall. Any help is appreciated. Thank you!

**Comment by jgehrcke** [comment]
@trivikr is that something you can push forward? Thank you!

**Comment by springmeyer** [comment]
Another aws-sdk user / premium aws customer who is watching this issue and looking forward to the fix landing (since I use the `customBackoff` and noticed this PR fixing the inefficiency. Thanks for the work here @jgehrcke!

**Comment by ajredniwja** [comment]
The PR was merged. Apologies for the delay.

**Comment by jgehrcke** [comment]
Thank you @ajredniwja and thanks for chiming in @springmeyer !

**Comment by peterlundberg** [comment]
Have noticed that there is still a problem with customBackoff being called also for errors that are not retryable (such as 404 from S3). 

In that case event_listeners will trigger `Request.RETRY_CHECK -> service.retryDelays -> calculateRetryDelay -> customBackoff`.

Thus one needs a `if (error.retryable) {}` guard to avoid inefficiencies like calculating the delay or logging the retry attempt. This should at least be documented if true?
