### ISSUE TITLE
_xamzrequire is not defined (Custom package)

### ISSUE THREAD

**Issue by ioannist** [aws/aws-sdk-js#3403]
**Describe the bug**
I create a custom package at https://sdk.amazonaws.com/builder/js/ with the following services
AWS.CognitoIdentity
AWS.CognitoIdentityServiceProvider
AWS.S3
AWS.SQS

I import the local custom package to package.json using npm inside an Angular8 project
I compile the app (success) and open it. I get the following error in my browser:

```
Uncaught ReferenceError: _xamzrequire is not defined
    at Object../local_modules/aws-sdk/aws-sdk-2.736.0.js (main.js:10)
```

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
Chrome: 84.0.4147.125

**SDK version number**
Example: v2.736.0

**To Reproduce (observed behavior)**
Download
[custom aws-sdk.zip](https://github.com/aws/aws-sdk-js/files/5094390/custom.aws-sdk.zip)
Install it using npm install ../file-location in an angular app, import from aws-sdk in the app, and run the app

**Expected behavior**
The app runs fine when we import aws-sdk from npm repository. It should also run when importing a custom package.

**Comment by ioannist** [comment]
I was able to get past this problem by editing the first line of the custom aws-sdk js file from
`_xamzrequire = function() {`
to
`var _xamzrequire = function() {`

**Comment by ajredniwja** [comment]
Hey @ioannist Thank-you for providing the solution here.

**Comment by ioannist** [comment]
No problem. Unfortunately, I did run into more issues trying to make the custom aws-sdk library work in Angular Universal (meaning the package would have to work both in Browser and Nodejs modes). I gave up :)

**Comment by ajredniwja** [comment]
That is a bit tricky to do, you would need to work with different packages. 

For simpler implementation check https://aws.amazon.com/mobile/AWS-Amplify-landing-angular/
