### ISSUE TITLE
Loading/Reading the Video from Private S3 Bucket

### ISSUE THREAD

**Issue by darshak-gosar** [aws/aws-sdk-js#3405]
Hi,
I had a query, Could you outline a way in which I can load/read the video which is stored on Private S3 bucket and view it on UI. I have tried using getObject but it consumes lot of time for larger files to load and also the body return a invalid format to display on UI. Could you think of an efficient way to load/read video from Private S3 bucket ?

Thanks :)

**Comment by ajredniwja** [comment]
Hey @darshak-gosar,

Thank-you for reaching out to us with your issue, you can use [cloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/on-demand-streaming-video.html) to achieve your needs. 

Also helpful: https://stackoverflow.com/questions/29794050/amazon-s3-and-node-js-video-streaming-and-thumbnail

Closing this now, please reach out if you have any questions.

**Comment by darshak-gosar** [comment]
Hi @ajredniwja ,
Is there any other way, other then cloudfront we can implement ?

**Comment by darshak-gosar** [comment]
Hi @ajredniwja ,
Is there any update ?

**Comment by ajredniwja** [comment]
You can use preSigned urls but cloudFront is the recommended way to do it. 

In HTML you can just use preSigned urls as your src for video tags.

**Comment by darshak-gosar** [comment]
Okay could you point me to example for preSigned video URL ?

**Comment by ajredniwja** [comment]
PreSigned url: 
```
var AWS = require("aws-sdk");

var s3 = new AWS.S3({region: "us-west-2"});
var params = {
    Bucket: "xyz",
    Key: "video.mov"
}
const preSignUrl = s3.getSignedUrl("getObject", params);

console.log(preSignUrl);
```
HTML code that I used: 

```HTML
<!DOCTYPE html>
<body>

<video width="400" controls>
    <source src="<preSignedURL>" type="video/mp4">
<!--    <source src="<preSignedURL>" type="video/ogg">-->
</video>


</body>

```

**Comment by darshak-gosar** [comment]
Thanks. But in PreSigned URL we can be able to see the accesskey and bucket name in url so how can we avoid it ?
Example: https://XXBucketXX.s3.amazonaws.com/uploads/file.mp4?AWSAccessKeyId=XXXXX&Expires=1598513745&Signature=XXXX

**Comment by ajredniwja** [comment]
Unfortunately that is not possible, you can create another user for the purpose of creating preSigned urls and then limit the second users access. 

Alternatively you can encrypt your HTML code.

**Comment by darshak-gosar** [comment]
Thanks for quick response. Okay but then for viewing the video it would contain actual URL through which the key could be seen.

**Comment by ajredniwja** [comment]
You can use a separate IAM user for this purpose.

Also refer to: 

https://github.com/aws/aws-sdk-js/issues/1780#issuecomment-339726280
