### ISSUE TITLE
multipart upload using s3.getSignedUrl api

### ISSUE THREAD

**Issue by armaansharma786** [aws/aws-sdk-js#3406]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
HI . i need some help. i try to upload multipart video to s3 bucket but once i get presigned url and try to put presigned url to s3 , the request are getting failed. i think i have issue in my presigned url .kindly pelase help 

Something like this i am getting as presigned url 

https://classes-videos.s3.ap-south-1.amazonaws.com/Suit%20Punjabi%20Jass%20Manak%20-%20HDYaar.Com.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAZLREPQO

**Comment by ajredniwja** [comment]
Hey @armaansharma786 thankyou for reaching out to us with your issue, 

If I understand correctly you are trying to do a `multiPartUplaod` and then get `preSignedUrl` using `s3.getSignedUrl`

I believe you are missing a lot of things in your `preSignedUrl`, see here for [more information](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html)

You can share your code here and I can help you from there if the problem still persists.
