### ISSUE TITLE
"Invalid login token. Couldn't verify signed token." error while obtaining AWS credentials

### ISSUE THREAD

**Issue by bkchy** [aws/aws-sdk-js#3408]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Hi,

We are having an issue where intermittently the API call to obtain AWS credentials in exchange for Cognito User Pool issued ID token is failing with "Invalid login token. Couldn't verify signed token." (not authorized) error. Here's the code that we are using

```
import * as AWS from 'aws-sdk'
const issuer = `cognito-idp.${region}.amazonaws.com/${userPoolId}`
const credentials = new AWS.CognitoIdentityCredentials(
    {
      IdentityPoolId: identityPoolId,
      Logins: {
        [issuer]: idToken,
      },
    },
    {
      region: region,
    },
)

await credentials.getPromise()
```
The ID token (idToken) is obtained by signing into Cognito User Pool immediately prior to above call and we have verified that the token is valid. We have also verified that the identity pool point to by `identityPoolId` above is correctly configured to point to the Cognito User Pool as a authentication provider. As mentioned before, this code works most of the time but occasionally fails with "Invalid login token. Couldn't verify signed token.". I was wondering whether this is an expected behaviour due to how Cognito is designed (eventual consistency related perhaps) or a bug in AWS SDK or in Cognito.

Thanks in advance for any insight that you could offer with regards to this.

**Comment by RaviDesai** [comment]
I can confirm that this is happening, and even created the following AWS Forum post outlining the issue a couple of days back.  https://forums.aws.amazon.com/thread.jspa?threadID=326418&tstart=0

We conducted testing on our system that issued calls every 30 seconds, and that showed close to a 5% failure rate in the calls.  Calls that failed would be immediately preceded by and followed by identical calls that succeeded WITH EXACTLY THE SAME PARAMETERS.

**Comment by ajredniwja** [comment]
As this was recognized a bug by the cognito team and a workaround is already mentioned by @RaviDesai, I would like to close this issue. Please reach out if you have any additional questions.

**Comment by bkchy** [comment]
Thanks for investigating this @ajredniwja . Is there a link to the bug that the cognito team is tracking?
