### ISSUE TITLE
Route53 changeResourceRecordSets Failing for delete operation when same data is used from the listResourceRecordSets

### ISSUE THREAD

**Issue by kirananto** [aws/aws-sdk-js#3411]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

I'm trying to delete a route53 record, for the same, I am first querying the records using `listResourceRecordSets` Operator
![image](https://user-images.githubusercontent.com/12209601/90875904-72a69580-e3bf-11ea-8fad-54341ee9ba83.png)

Now that I get the `ResourceRecordSet` from this response, I do basic validations and now try to call delete on the same using this `resourceRecordSet` as the input like the image below.
![image](https://user-images.githubusercontent.com/12209601/90876175-dc26a400-e3bf-11ea-9d80-ab7d3063919e.png)

So technically everything should be working just fine, but then I'm faced with an error that says like the below

```
InvalidInput: Invalid XML ; cvc-complex-type.2.4.b: The content of element 'ResourceRecords' is not complete. One of '{"https://route53.amazonaws.com/doc/2013-04-01/":ResourceRecord}' is expected.
    at Request.extractError (/Users/kirananto/Projects/express-docker/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/Users/kirananto/Projects/express-docker/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
```

I was stuck with this issue for around a day, unable to find any solutions. Tried a couple of different changes, but since it's straightforward there was nothing to try out. But later came to know that the response from the first list query had `resourceRecords` as `[]` instead of undefined, which was the cause of all the issue

`Note: If you're creating an alias resource record set, omit ResourceRecords.`

So naturally, since I'm expecting only AliasTargets I changed my code to this 
![image](https://user-images.githubusercontent.com/12209601/90876700-a46c2c00-e3c0-11ea-866a-02d6d7874756.png)

And everything started working, So shouldn't this be very natural, as in when we call list, the response that we get, we should be able to pass the same object without modification to other APIs which has the input as those. Also if that's not the case, shouldn't that be documented somewhere? 

I'm raising this bug so that someone facing the same issue could refer to this for the fix. 

FYI: This bug is not visible in other clients, I tried with the python client and it just works fine. So I guess it's just very specific to js client.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v13.14.0

**SDK version number**
2.737.0

**To Reproduce (observed behavior)**
Use the code as in the above description, You'll come across the same issue.

**Expected behavior**
The value of `resourceRecords` should be undefined, if not handled properly by the delete. Either it has to be handled by the delete Functionality or it has to be sent as undefined in the list output.

**Screenshots**
Not applicable, screenshots posted in the above description

**Additional context**
N/A

**Comment by ajredniwja** [comment]
@kirananto Thank-you for raising it, I will take a look at it if the second request where you get `resourceRecords as []` whether it is serialized like that from the SDK or the service team and go from there.

**Comment by jgehrcke** [comment]
Ran into the same issue. Definitely a complication of mild annoyance :).

**Comment by kirananto** [comment]
Yep that works @jgehrcke 
Ideally it user shouldn't be annoyed by this, we expect all sdks to work similarly

**Comment by kirananto** [comment]
@ajredniwja  Hi Ajwinder, Did you get a chance to look into the issue ?

**Comment by kyler-hyuna** [comment]
Had this same issue. Thanks so much @jgehrcke. Had me a good 2 days on this.

**Comment by ajredniwja** [comment]
@kirananto, apologies I lost track of this issue, mainly because I saw a workaround available. I believe this will be more of a usage issue for which we can add something to the documentation regarding this. I can take your suggestions on what you'd like.
