### ISSUE TITLE
SESV2: Unexpected key 'TemplateName' found in params.Content.Template

### ISSUE THREAD

**Issue by CanRau** [aws/aws-sdk-js#3413]
AWS APIs are updating constantly, you might be calling a new API with an older version is SDK. In
    this case you should try installing the newest `aws-sdk` like: 

    `npm install aws-sdk@latest`

    If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled
    SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
    You can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

If you still like to open an issue, change [ ] to [x] below:
- [x] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

I was very hopeful that the above tip would fix my issue, but as marked by the [x] it didn't 😅
I've upped `"aws-sdk": "2.738.0"` and even set 
```json
"resolutions": {
    "aws-sdk": "2.738.0"
},
```

Locally, in a `sestest.js`, doing

```js
const {SESV2, config} = require("aws-sdk");
config.update({region: "eu-central-1"});

(async () => {
  const params = {
    ConfigurationSetName: "newsletter-ses-configurationset",
    FromEmailAddress: "VERIFIED_MAIL",
    Destination: {
      ToAddresses: ["bounce@simulator.amazonses.com"],
    },
    Content: {
      Template: {
        TemplateName: "ses-confirmation-template",
        TemplateData: JSON.stringify({
          subject: "strings.subject",
          title: "strings.title",
          ctaLabel: "strings.ctaLabel",
          orCopy: "strings.orCopy",
          note: "strings.note",
          unsubscribe: "strings.unsubscribe",
          privacyUrl: "strings.privacyUrl",
          privacyTitle: "strings.privacyTitle",
          legalUrl: "strings.legalUrl",
          legalTitle: "strings.legalTitle",
          lang: "subscriber.lang",
          confirmationLink: "confirmationLink",
          unsubscribeLink: "unsubscribeLink",
        }),
      },
    },
  };

  new SESV2({apiVersion: "2019-09-27"})
    .sendEmail(params)
    .promise()
    .then(console.log)
    .catch(console.error);
})();
```

works as expected, calling the Lambda works fine until it reaches the aforementioned code (almost the same, just proper variables), which then returns `Unexpected key 'TemplateName' found in params.Content.Template`

I'm on Node v12.14.1
The Lambda is on Node 12.x

Uh and I'm using [Pulumi](https://www.pulumi.com/)'s CLI & SDK for IaC (Infrastructure as Code).

Anything else I can provide?

**Comment by philipwigg** [comment]
Strange it's working locally - can you double-check you're definitely bundling the latest aws-sdk in with your lambda?

What happens locally if you downgrade the aws-sdk to ```2.721.0``` which is the current lambda runtime version? Do you get the same error?

**Comment by CanRau** [comment]
Thanks for taking the time @philipwigg 🙏 

Don't know how to double check, but downgrading locally leads to the same error so it's very likely the bundled version is not correct.

Not sure how to change that, as I already pinned it to `2.738.0` via `dependencies` and `resolutions` as mentioned above. Maybe Pulumi is doing something behind the scenes then? Even though yarn `resolutions` should only allow `2.738.0` 🤷‍♂️

Any advice?
And I'd love to know how to double check the version used in the lambda. I thought the `aws-sdk` provides some `version` property I could just `console.log` but it doesn't seem so?

**Comment by philipwigg** [comment]
Do you have other dependencies or is the `aws-sdk` the only one?

I'm wondering if you're including your node_modules folder inside the `.zip` file artefact that's uploaded to AWS Lambda? If you're not then your `dependencies` inside `package.json` will have no effect except locally.

Either way, looking at your build pipeline and the contents of the `.zip` artefact will probably point you in the right direction.

Hope that helps!

**Comment by CanRau** [comment]
Just found this https://aws.amazon.com/de/premiumsupport/knowledge-center/lambda-layer-aws-sdk-latest-version/ which even shows that the SDK indeed provides a `VERSION` property 😅
which outputs `2.712.0` 😲

Okay thank you than I have to find out what Pulumi is uploading, couldn't find the actual zip on my machine so far 🤷‍♂️
Uh, no it's by far not the only dependency and all other dependencies work so I'd expect that Pulumi is bundling them then.

**Comment by CanRau** [comment]
Am I understanding the **Referencing `aws-sdk`** note at the very bottom of [Serializing Functions](https://www.pulumi.com/docs/tutorials/aws/serializing-functions/#determining-the-appropriate-node-modules-packages-to-include-with-a-lambda) correctly, that Pulumi might not bundle the `aws-sdk` at all?

Think that's kind of strange as I'd expect it to bundle my dependencies.

I think I can provide my desired version via a [layer](https://aws.amazon.com/de/premiumsupport/knowledge-center/lambda-layer-aws-sdk-latest-version/) then, I guess 🤷‍♂️ at least as a workaround for now.

**Comment by philipwigg** [comment]
Don't totally understand the comment in [this code](https://github.com/pulumi/pulumi-aws/blob/96a856ed11314bec542cd860851b3cc05711aaab/sdk/nodejs/lambda/lambdaMixins.ts#L352-L357) but might be relevant?

**Comment by CanRau** [comment]
Interesting, not sure how to use `extraIncludePackages` though 😬

[Here](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/runtime/closure/#computeCodePaths) it's saying to use `runtimeDependencies` in `package.json`, unfortunately that didn't seem to work for me.

And I tried like so
```js
pulumi.runtime.computeCodePaths({
  extraIncludePackages: ["aws-sdk"],
});
```
in my `index.ts` infrastructure file which doesn't seem to work either as trying to deploy this didn't lead to a code change so no updates where made 🤷‍♂️

**Comment by philipwigg** [comment]
I'm a novice but it seems like [you might be able](https://www.pulumi.com/docs/intro/concepts/project/) to specify the options in ```Pulumi.yaml```?

I guess it would need to say ```"aws-sdk": "2.739.0"``` so you might need to escape the quotes? Not sure!

**Comment by CanRau** [comment]
Hm not sure, why you think it can be used for dependencies?
However I tried
```yaml
runtime:
  name: nodejs
  options:
    "aws-sdk": "2.740.0"
```
which resultes in the CLI erroring `flag provided but not defined: -aws-sdk`

**Comment by philipwigg** [comment]
Sorry, I meant something like:-

```
runtime: 
  name: nodejs
  options: 
    extraIncludePackages: "\"aws-sdk\": \"2.740.0\""
```

**Comment by CanRau** [comment]
^^ Yeah that looks indeed better, unfortunately yields the "same" error
`flag provided but not defined: -extraIncludePackages`

For now I've used a custom layer as explained in the AWS docs on [how to integrate latest SDK version](https://aws.amazon.com/de/premiumsupport/knowledge-center/lambda-layer-aws-sdk-latest-version/), which works.

Closing it in favor of https://github.com/pulumi/pulumi/issues/5239 as it's not AWS related.

Thanks a lot for your efforts @philipwigg, very much appreciated 🙏
