### ISSUE TITLE
Is there a way to get ProvisioningArtifactParameters in order specified in the CloudFormation template?

### ISSUE THREAD

**Issue by svalio** [aws/aws-sdk-js#3415]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I am using AWS API(version 2015-12-10, javascript) to fetch Service Catalog products. `describeProvisioningParameters` method returns an object with `ProvisioningArtifactParameters` field which contains parameters, but these parameters sorted in a way different from the way provided in the CloudFormation template. 

Parameters part of CloudFormation template: 

```
{
        "Parameters": {
            "DBInputCIDR": {
                
            },
            "DBName": {
                
            },
            "DBPortNumber": {
    
            },
            "DBMasterUsername": {
    
            },
            "DBMasterUserPassword": {
            
            },
            "DBBackupRetentionPeriod": {
                
            },
            "DBAllocatedStorage": {
            
            },
            "DBEngineVersion": {
            
            },
            "DBInstanceClass": {
                
            },
            "MultiAZ": {
               
            }
        }
    }
```

Parameters part of API response: 

```
    {
        "ProvisioningArtifactParameters": [
            {
                "ParameterKey": "DBBackupRetentionPeriod"
            },
            {
                "ParameterKey": "DBEngineVersion"
            },
            {
                "ParameterKey": "DBPortNumber"
            },
            {
                "ParameterKey": "DBAllocatedStorage"
            },
            {
                "ParameterKey": "DBMasterUserPassword"
            },
            {
                "ParameterKey": "DBInstanceClass"
            },
            {
                "ParameterKey": "DBInputCIDR"
            },
            {
                "ParameterKey": "DBMasterUsername"
            },
            {
                "ParameterKey": "DBName"
            },
            {
                "ParameterKey": "MultiAZ"
            }
        ]
    }
```
Is there any way to sort API response as specified in the CloudFormation template?

**Comment by ajredniwja** [comment]
This is a feature request for the serviceCatalog team, closing this in favor of #3416 

Reached out to the the team to convey the feature request.
