### ISSUE TITLE
List ProvisioningArtifactParameters in order specified in the CloudFormation template

### ISSUE THREAD

**Issue by svalio** [aws/aws-sdk-js#3416]
**Is your feature request related to a problem? Please describe.**
I am using AWS API(version 2015-12-10, javascript) to fetch Service Catalog products. describeProvisioningParameters method returns an object with the ProvisioningArtifactParameters field which contains parameters, but these parameters sorted in a way different from the way provided in the CloudFormation template. I would like to receive the ProvisioningArtifactParameters in the order specified in the CloudFormation template

**Describe the solution you'd like**
I would like to have an option something like ProvisioningArtifactParametersOrder: 'CFN template' | 'default' in the parameters section. 
<img width="1310" alt="Screen Shot 2020-08-25 at 2 34 19 PM" src="https://user-images.githubusercontent.com/36510050/91169564-40a77300-e6e0-11ea-93e4-a6379a15a03c.png">

**Describe alternatives you've considered**
none 

**Additional context**
I have configured CFN template for Postgres RDS and Parameters part looks like: 
```
{
        "Parameters": {
            "DBInputCIDR": {
                
            },
            "DBName": {
                
            },
            "DBPortNumber": {
    
            },
            "DBMasterUsername": {
    
            },
            "DBMasterUserPassword": {
            
            },
            "DBBackupRetentionPeriod": {
                
            },
            "DBAllocatedStorage": {
            
            },
            "DBEngineVersion": {
            
            },
            "DBInstanceClass": {
                
            },
            "MultiAZ": {
               
            }
}
```
And when I am making an API call to fetch provisioning parameters I receive these parameters in the wrong order: 
```
{
        "ProvisioningArtifactParameters": [
            {
                "ParameterKey": "DBBackupRetentionPeriod"
            },
            {
                "ParameterKey": "DBEngineVersion"
            },
            {
                "ParameterKey": "DBPortNumber"
            },
            {
                "ParameterKey": "DBAllocatedStorage"
            },
            {
                "ParameterKey": "DBMasterUserPassword"
            },
            {
                "ParameterKey": "DBInstanceClass"
            },
            {
                "ParameterKey": "DBInputCIDR"
            },
            {
                "ParameterKey": "DBMasterUsername"
            },
            {
                "ParameterKey": "DBName"
            },
            {
                "ParameterKey": "MultiAZ"
            }
        ]
    }
```

**Comment by svalio** [comment]
Hello, @ajredniwja could you please confirm is this feature-request feasible? What is the current status of this ticket?

**Comment by svalio** [comment]
Hello, @ajredniwja is there is any queue for the feature requests?
If this feature is not feasible I would like to consider some other options to fetch provisioning parameters in the right order. Can you assist me with this?

**Comment by ajredniwja** [comment]
I reached out the the team as mentioned in https://github.com/aws/aws-sdk-js/issues/3415

However, I have not received any information from them. Not sure if they will prioritize this issue or not thats why I can promise you any date.
