### ISSUE TITLE
AWS Amplify: After confirmSignUp, what is the best practice to automatically Sign In a user?

### ISSUE THREAD

**Issue by jefelewis** [aws/aws-sdk-js#3417]
**Is your feature request related to a problem? Please describe.**
Authentication (confirmSignUp)

**Describe the solution you'd like**
After the user receives a Verification Code, the user enters the Verification Code, and the `Account Status` becomes `CONFIRMED`. Now that the sign up process is completed, I want to automatically sign in the user in after. It seems inefficient and redundant to redirect the user to the Sign In page to have user enter their information and sign in.

_**Possible Solutions:**_
1. Create a `confirmSignUpAndSignIn` method that does what `confirmSignUp` does, but signs in the user after.
2. With the [AWS Amplify Hub (Auth Listener)](https://docs.amplify.aws/lib/utilities/hub/q/platform/js), emit a `confirmSignUp` event to keep track of the user confirms the sign up process.

**Describe alternatives you've considered**
 1. Use the `email` and `password` from the sign up process and then dispatch the `signIn` action to sign in the user.
 2. Find a way combined method for both `confirmSignUp` and `signIn`, which would be something along the lines of `confirmSignUpAndSignIn` (If a method exists). I have looked through the [AWS Docs](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js) and through the issues Amplify-js Github Repo, but have only found that others have had a similar dilemma with no apparent resolution.
 3. Use the [AWS Amplify Hub (Auth Listener)](https://docs.amplify.aws/lib/utilities/hub/q/platform/js), but there aren't any events emitted when the user confirms sign up. It would make sense that `confirmSignUp` would emit an event, but it doesn't. (See Below)

**Additional context**
I'm using the [AWS Amplify Hub (Auth listener) ](https://docs.amplify.aws/lib/utilities/hub/q/platform/js) and the only events that are emitted are the following from the docs:

```javascript
    case 'signIn':
        logger.error('user signed in'); //[ERROR] My-Logger - user signed in
        break;
    case 'signUp':
        logger.error('user signed up');
        break;
    case 'signOut':
        logger.error('user signed out');
        break;
    case 'signIn_failure':
        logger.error('user sign in failed');
        break;
    case 'configured':
        logger.error('the Auth module is configured');
```

**Comment by rgupta-varicent** [comment]
@jefelewis did you find a solution to this?
