### ISSUE TITLE
Support JS sets with DocumentClient.createSet

### ISSUE THREAD

**Issue by IsaiahJTurner** [aws/aws-sdk-js#3420]
Currently, using a javascript Set will produce the error `Sets can contain string, number, or binary values` because of (i think) this: https://github.com/aws/aws-sdk-js/blob/e9bdef5da8555a51c19aa1548cfa513eb0e87e75/lib/dynamodb/set.js#L27

From what I can tell, changing that code to this would fix that quirk with no side effects:
```js
self.values = []
list.forEach((value) => self.values.push(value))
```

**Comment by ajredniwja** [comment]
Hey @IsaiahJTurner, thanks for opening this issue, you can open a PR for our team to review or I can make the PR soon.
