### ISSUE TITLE
S3.headObject doesn't return StorageClass

### ISSUE THREAD

**Issue by mosmabro** [aws/aws-sdk-js#3423]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
S3.headObject doesn't return StorageClass although it is returned in 'x-amz-storage-class' header

**Is the issue in the browser/Node.js?**
Browser

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
Browsers:
    Chrome: 84.0.4147.135
    Firefox: 68.8.0
    Safari: 13.1.2

**SDK version number**
 v2.739.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
```javaScript
var params = {
        Bucket: "photo-albums-2020-08-25", 
        Key: "No virus allowed.jpg"
       };
       s3.headObject(params, function(err, data) {
        if (err)
         {
          console.log(err, err.stack); // an error occurred
         }
        else
         {
            console.log(data);           // successful response: No StorageClass is returned
            console.log(data.StorageClass);
         }
      });
```
**Expected behavior**
StorageClass should be retuned

**Screenshots**
Looking into the Network traffic, I can see that the storage class is returned, but the API doesn't return the value in S3.headObject response
![image](https://user-images.githubusercontent.com/66446496/91513480-c36e3f00-e927-11ea-919d-7db0210c4ce0.png)

**Additional context**

**Comment by philipwigg** [comment]
I wrote this very simple test case...

```html
<!DOCTYPE html>
<html>

<head>
  <script src="https://sdk.amazonaws.com/js/aws-sdk-2.739.0.min.js"></script>
</head>

<body>
  <script type="text/javascript">

    var s3 = new AWS.S3({ apiVersion: '2006-03-01', accessKeyId: 'XXXXXXXXX', secretAccessKey: 'XXXXXXXXX', region: 'eu-west-1' });

    var params = {
      Bucket: "philstestbucket87498",
      Key: "test.txt"
    };

    s3.headObject(params, function (err, data) {
      if (err) console.log(err, err.stack);
      else console.log(data.StorageClass);
    });
  </script>
</body>
</html>
```

I have created an object and uploaded it using the Glacier storage class just using the CLI.

```bash
aws s3api put-object --bucket philstestbucket87498 --key test.txt --body test.txt --storage-class GLACIER
```

I also needed to set a CORS policy on the S3 bucket. Here it is for completeness:-

```json
{
    "CORSRules": [
        {
            "AllowedHeaders": [
                "*"
            ],
            "AllowedMethods": [
                "GET",
                "POST",
                "DELETE",
                "HEAD",
                "PUT"
            ],
            "AllowedOrigins": [
                "*"
            ],
            "ExposeHeaders": [
                "x-amz-version-id",
                "x-amz-website-redirect-location",
                "x-amz-server-side-encryption",
                "x-amz-server-side-encryption-customer-algorithm",
                "x-amz-server-side-encryption-customer-key-MD5",
                "x-amz-server-side-encryption-aws-kms-key-id",
                "x-amz-storage-class",
                "x-amz-request-charged",
                "x-amz-replication-status",
                "x-amz-mp-parts-count",
                "x-amz-object-lock-mode",
                "x-amz-object-lock-retain-until-date",
                "x-amz-object-lock-legal-hold"
            ],
            "MaxAgeSeconds": 3000
        }
    ]
}
```

For me, it seems to work fine.

![image](https://user-images.githubusercontent.com/244059/91908076-e17acd00-eca2-11ea-998e-738996847cba.png)

I realise this doesn't solve your issue but should give you some confidence that the SDK is working - there must be something else going on at your side? Can you paste the full output of what's logged by the `console.log(data)`?

**Comment by philipwigg** [comment]
Actually, after more consideration, I wonder if the CORS settings are your issue?

The `x-amz-storage-class` header is still sent with the response but unless you have the header listed in `ExposeHeaders` in your S3 bucket's CORS settings then the SDK cannot read it.

**Comment by mosmabro** [comment]
@philipwigg That is correct. Thanks for your response.
Cheers
