### ISSUE TITLE
Is there a way to filter or sort objects that come from AWS before returning a response, like Prefix and Delimiter?

### ISSUE THREAD

**Issue by pedrohenriiz** [aws/aws-sdk-js#3425]
I'm kinda new to AWS in general and specific with S3 and I would like to know if there is a way to filter or order the objects that come from my Bucket before returning a response, in the same way that Prefix and Delimiter work.

Currently I'm using listObjectsV2 method to list my objects and I know that exists the Prefix and Delimiter params but they aren't enough from what my project need. Also, I've made some researchs but didn't find anything that say that such feature exists or not.

My case is specific because I will have a lot of users with a bunch of files and don't want to retrieve all their files. For example, user 1 has 100 files. I want to return only the 10 newest ones instead of everything because they won't be necessary .

If something like that doesn't exist, what is the best case that I could implement in my project? Thanks.

**Comment by ajredniwja** [comment]
@pedrohenriiz Thank-you for opening this issue, unfortunately there is not predefined API to perform this function. 

This is a known feature request: https://github.com/aws/aws-sdk-js/issues/2944 which has to come from the S3 team. 

The only way to achieve this right now would be to get all the objects and sort by `lastModified` in your code manually. 

Would be closing this issue in favor of https://github.com/aws/aws-sdk-js/issues/2944
