### ISSUE TITLE
SecretsManager throws crypto error on Ubuntu 20.04 EC2, but works on MacOS and Docker

### ISSUE THREAD

**Issue by sean256** [aws/aws-sdk-js#3426]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The same code works in Docker and on macOS, but fails on Ubuntu 20.04 running on an EC2. I installed the modules using `npm ci` to ensure the installed versions are locked in.

Error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:304:11)
    at new Hmac (internal/crypto/hash.js:113:9)
    at Object.createHmac (crypto.js:143:10)
    at Object.hmac (/var/app/tst/node_modules/aws-sdk/lib/util.js:423:30)
    at Object.getSigningKey (/var/app/tst/node_modules/aws-sdk/lib/signers/v4_credentials.js:62:8)
    at V4.signature (/var/app/tst/node_modules/aws-sdk/lib/signers/v4.js:98:36)
    at V4.authorization (/var/app/tst/node_modules/aws-sdk/lib/signers/v4.js:93:36)
    at V4.addAuthorization (/var/app/tst/node_modules/aws-sdk/lib/signers/v4.js:35:12)
    at /var/app/tst/node_modules/aws-sdk/lib/event_listeners.js:242:18
    at finish (/var/app/tst/node_modules/aws-sdk/lib/config.js:386:7) {
  code: 'ERR_INVALID_ARG_TYPE',
  retryDelay: 20.307687997107028
}
```

**Is the issue in the browser/Node.js?**
NodeJS

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.18.3

**SDK version number**
v2.733.0

**To Reproduce (observed behavior)**

```js
const { SecretsManager } = require('aws-sdk');

(async () => {
	const secrets = new SecretsManager({ apiVersion: '2017-10-17', region: 'us-west-2' });
	try {
		const { SecretString } = await secrets.getSecretValue({ SecretId: 'some-secret-id' }).promise();
		console.log(SecretString);
	} catch (error) {
		console.error(error);
	}
})();
```

**Expected behavior**
To not throw this error

**Comment by sean256** [comment]
I just launched a brand new instance with Ubuntu 18 and installed Node 12.x and the bug replicates there as well

**Comment by philipwigg** [comment]
It's probably still a bug but I wonder if this relates to permissions (just guessing here).

When you're running the code locally, you're authenticated using your own IAM user? What about when it's running on the EC2 instance? Is it running as an attached IAM role?

If so, does the attached IAM role have the minimum permissions specified [in the docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SecretsManager.html#getSecretValue-property)?

```
To run this command, you must have the following permissions:

secretsmanager:GetSecretValue

kms:Decrypt - required only if you use a customer-managed AWS KMS key to encrypt the secret. You do not need this permission to use the account's default AWS managed CMK for Secrets Manager.
```

**Comment by sean256** [comment]
It does have an IAM role with the correct permissions. I know it has the correct permissions because it works in docker running in Fargate with the same role.

**Comment by philipwigg** [comment]
It seems like it's related to the credentials. Are you setting them on the EC2 instance using environment variables or anything like that?

**Comment by sean256** [comment]
I am not setting any env vars or doing anything weird with credentials. I am simply relying on the instance and the SDK to do their thing like I always do.

I will write up another test script to perform some other AWS actions with the SDK to see if creds become an issue anywhere else.

**Comment by sean256** [comment]
So no commands are working, so I think you are right, it must be a credential issue. Both ec2's have a role attached so I have no idea at this point. I guess I need to debug a different issue, thanks anyway!
