### ISSUE TITLE
JS SDK copyObject appears to fail silently

### ISSUE THREAD

**Issue by Eric24** [aws/aws-sdk-js#3427]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Calling copyObject appears to work, but the copied file does not show up in the destination bucket. In fact, if it was there before the copyObject call, it is deleted. I'm not sure this is a bug--it may be a configuration issue on the source and/or destination buckets, but I've looked at everything I can think of in that regard.

The destination bucket seems to be the issue. I have an example of a bucket that works and one that fails. The only difference is that the one that fails has a bucket policy that allows CloudFront to read from it. The two destination buckets are otherwise identical. And the source bucket is the same bucket in both cases.

I've been combing the various on-line places, but haven't found anything useful on this topic.

- Has anyone else seen this behavior?
- How can I debug it? The copyObject call is clearly doing something to the destination folder.
- Any suggestions on what else I might look at?

**Comment by ajredniwja** [comment]
Hey @Eric24 Thank-you for opening this issue, I was not able to reproduce the issue. 

Is it possible for your to share the version of the SDK and the bucket policy that you using.

**Comment by Eric24** [comment]
Thank you, but I figured out the problem. It was not an issue with the bucket policy, but a case where we were deleting the old object _after_ copying the new one. In other places that we've used this same code, it didn't matter because the object name was always different. But in this case, the object name was the same. Changing the order to delete then copy fixed the problem.
