### ISSUE TITLE
AWS.Lightsail is not a constructor

### ISSUE THREAD

**Issue by jburnham96** [aws/aws-sdk-js#3428]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Hi,

I'm creating an electron app to get various AWS service information. I was originally using the [SimulatedGREG](https://github.com/SimulatedGREG/electron-vue) boiler plate and everything was working fine, but I switched to using the vue-cli with [electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder) to build the application and now I'm getting back a few errors when initially trying to load in the AWS services:

![image](https://user-images.githubusercontent.com/8777345/91664848-b9943980-eae9-11ea-9a24-6f3852f9ae33.png)

I've definitely got my credentials set up correctly as it was working previously, I'm unsure as to what exactly could be causing this issue. would you be able to help?

**Comment by ajredniwja** [comment]
@jburnham96 Thanks for opening this up, can you point me towards how you are consuming the AWS SDK? 

Can you share the steps to reproduce this?

**Comment by jburnham96** [comment]
Hi @ajredniwja, [here](https://github.com/jburnham96/sshec2/blob/feature/upgrade/src/renderer/helpers/aws.helper.js) is an example of how I've implemented the API **before** I switched to the electron-builder package and [here](https://github.com/jburnham96/sshec2/blob/upgrade_latest_electron/src/helpers/aws.helper.js) is an example **after** where I'm running into issues. 

From what I can see there's not much difference between the actual aws.helper.js file. I'm thinking it could be webpack related as I'm not entirely sure on how I can force the AWS sdk into loading the node version as I'm pretty sure it's being built as the web version, if that could be the issue

**Comment by ajredniwja** [comment]
@jburnham96 I believe you might be right, as I was not able to reproduce this locally. What you can do is, you can build your own custom SDK using the steps found [here](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html). Hopefully that will solve the problem.

**Comment by jburnham96** [comment]
@ajredniwja Thanks, I've taken a look into that and I believe that will cause the same issue as I have now. If I understand correctly it will build it into the web version that by default is missing some services such as lightsail which is causing one of the errors.

If I've read correctly the sdk has three versions, node-js, web and react. Is it possible to force the sdk into loading the "node" version? I need to be able to grab the credentials from a shared location as well which was working nicely to begin with which I think is only available in the node sdk

**Comment by jburnham96** [comment]
@ajredniwja I've got this working now, I had to add the aws-sdk as an external in the electron-builder config within the vue.config.js file. Thank you for your help 😃
