### ISSUE TITLE
AWS.Pricing - getProducts returning PriceList as Array<object> instead of Array<string>

### ISSUE THREAD

**Issue by impadalko** [aws/aws-sdk-js#3437]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When using the method `getProducts` from the `AWS.Pricing` class, the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pricing.html#getProducts-property) states that the expected return type is an object with one of the keys being `PriceList` and its respective value being an array of strings. However, when using this method, the type of the value associated with the `PriceList` key is, actually, an array of objects. This does not impact our ability of using this method, however, it does affect the type checking provided by Typescript.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v14.8.0

**SDK version number**
2.740.0

**To Reproduce (observed behavior)**
Code to reproduce the behavior:
```
const AWS = require('aws-sdk')

const pricing = new AWS.Pricing({ region: 'us-east-1' })

const params = {
  Filters: [{
    Field: 'location',
    Type: 'TERM_MATCH',
    Value: 'US East (N. Virginia)'
  },
  {
    Field: 'preInstalledSw',
    Type: 'TERM_MATCH',
    Value: 'NA'
  },
  {
    Field: 'operatingSystem',
    Type: 'TERM_MATCH',
    Value: 'Linux'
  },
  {
    Field: 'tenancy',
    Type: 'TERM_MATCH',
    Value: 'Shared'
  },
  {
    Field: 'usageType',
    Type: 'TERM_MATCH',
    Value: `BoxUsage:g4dn.12xlarge`
  }],
  FormatVersion: 'aws_v1',
  MaxResults: 1,
  ServiceCode: 'AmazonEC2'
}

pricing.getProducts(params, (err, data) => {
  if(err) console.log(err)
  else console.log(data)
})
```

Output:
```
{
  FormatVersion: 'aws_v1',
  PriceList: [
    {
      product: [Object],
      serviceCode: 'AmazonEC2',
      terms: [Object],
      version: '20200825215021',
      publicationDate: '2020-08-25T21:50:21Z'
    }
  ],
  NextToken: 'vJJa+Vb2+2uBtIJHi3L58A==:4AUHa89lAtUYd6VwJB4KZVOC1zVwWEzLMfA/iEB6Hf3ubDdiCpqm2JKMBzZFgtjXjRWdj0w2MgOecpGmltvW+gaEs3h1GLQ6f1l6/R11dpPFr9BwEna/ej6MGemeTrHe3B8u414Ab9mfCgTuB8AaiuUl3CzvFbF3+XG/GwdILGru4UgxU1V4KiYNuyLMRwBt'
}
```

**Expected behavior**
We expect either the documentation to state that `PriceList` is an array of objects (with its corresponding type being set this way in the type definition for Typescript) or for `PriceList` being returned as a JSON-encoded string.

**Screenshots**
NA

**Additional context**
NA

**Comment by ajredniwja** [comment]
@impadalko Thanks for reporting this, the documentation is generated by the `AWS.Pricing` team, reaching out to them for a possible fix.
