### ISSUE TITLE
"receiveMessage" skipped with no errors

### ISSUE THREAD

**Issue by alfiafit** [aws/aws-sdk-js#3439]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The "receiveMessage" function appears not to be executed but there are no errors

**Is the issue in the browser/Node.js?**
Working in AWS

**Observed behavior**
I have a queue with a message in it (from SQS):
![image](https://user-images.githubusercontent.com/46226962/92308547-ac21f800-ef9e-11ea-9feb-d6ef03b1ed22.png)
which is well-formed (downloaded by a Lambda that logs the messages):
```
{
    Records: [ 
        {
        messageId: 'f71e5689-76e1-4d74-a530-618d2015744c',
        receiptHandle: 'AQEBJx61SvYBwQnozAX9TM1spjsRT4IswiNg6yAAAnQvPeT8ZABZqH3XbAIGHFtoRoOU4VJmts3idLFW1vf89ioeDlqoOFDjywQIMntmvwbehmBmZD360q27NicI4pwPLWV9Muq1GzLUWI59nyf4RVVpgF0wOizQXyZeUwSz0eMpniIFKoZdePjFvtwGEDO65gDqaVsmlJKWecde+wPpfbHxC5+7G1Fo5hsVfDmi+LSC95JQEaLPD9AYAqrKmAUejIbf4DhamSVTSTL4TO2n1sMUvc0EZBRjRTYna8Jw9bijOmw=',
        body: 'Dear, your registration has been successfully received!',
        attributes: [Object],
        messageAttributes: [Object],
        md5OfMessageAttributes: '2055c0718283abc4c0f76ef1c17610be',
        md5OfBody: '61a6d26831b93dcc4c605be49a6c53c4',
        eventSource: 'aws:sqs',
        eventSourceARN: 'arn:aws:sqs:eu-xxxxxxx:47xxxxxxxxxx:FromEvents.fifo',
        awsRegion: 'eu-xxxxxxx'
        }
    ]
}
```
There are no restrictions on access to the queue (from IAM):
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sqs:ListQueues",
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "sqs:*",
            "Resource": "arn:aws:sqs:eu- xxxxxxx:47 xxxxxxxxxx:FromEvents.fifo"
        }
    ]
}
```
This is the code of the Lambda that has to read the message (with some more test log):
```
    ...
    const sqs = new AWS.SQS({apiVersion: '2012-11-05'});
    const queueName = 'FromEvents.fifo';
    const queueUrl = `https://sqs.${region}.amazonaws.com/${accountId}/${queueName}`;
    
    let responseBody = "";
    
    console.log(queueUrl);
    console.log("at the beginning");

    const params = {
        QueueUrl: queueUrl, 
        AttributeNames: [
            "All"
        ],
        MessageAttributeNames: [
            "All"
        ], 
        MaxNumberOfMessages: 1
    };
    
    console.log("before 'receiveMessage': " + JSON.stringify(params) );
    
    sqs.receiveMessage(params, function(err, data){
        if (err) {
            console.log("Receive Error", err);
            responseBody = JSON.stringify(err);
        }
        else { 
            console.log("Receive message", data);
            responseBody = data;
        };
    });    
    
    console.log("after 'receiveMessage': " + responseBody);
    
    const resplog = {
        "body": responseBody
    }

    const response = {
        "headers": { 
            "content-type": "application/json"
        },
        "body": responseBody
    }
    
    console.log(resplog);
    
    return response;
};
```
When I try to receive the message with this Lambda, this is what I get:
```
2020-09-05T15:58:25.838+02:00	START RequestId: 00305d11-1df5-43c6-87af-634b50d80a76 Version: $LATEST

2020-09-05T15:58:25.963+02:00	2020-09-05T13:58:25.945Z
00305d11-1df5-43c6-87af-634b50d80a76	INFO	https://sqs.eu-xxxxxxx.amazonaws.com/47xxxxxxxxxx/FromEvents.fifo

2020-09-05T15:58:25.963+02:00	2020-09-05T13:58:25.963Z	
00305d11-1df5-43c6-87af-634b50d80a76	INFO	at the beginning

2020-09-05T15:58:25.963+02:00	2020-09-05T13:58:25.963Z	
00305d11-1df5-43c6-87af-634b50d80a76	INFO	before 'receiveMessage': 
{
    "QueueUrl": "https://sqs.eu-xxxxxxx.amazonaws.com/47xxxxxxxxxx/FromEvents.fifo","AttributeNames":["All"],"MessageAttributeNames":["All"],"MaxNumberOfMessages":1
}

2020-09-05T15:58:26.424+02:00	2020-09-05T13:58:26.424Z	
00305d11-1df5-43c6-87af-634b50d80a76	INFO	after 'receiveMessage': 

2020-09-05T15:58:26.445+02:00	2020-09-05T13:58:26.445Z	
00305d11-1df5-43c6-87af-634b50d80a76	INFO	{ body: '' }

2020-09-05T15:58:26.485+02:00	END RequestId: 00305d11-1df5-43c6-87af-634b50d80a76

2020-09-05T15:58:26.485+02:00	REPORT RequestId: 00305d11-1df5-43c6-87af-634b50d80a76	
Duration: 646.86 ms	Billed Duration: 700 ms	Memory Size: 128 MB	Max Memory Used: 86 MB	Init Duration: 388.02 ms
```
As you can see, the parameters are right, but between ‘before receiveMessage’ and ‘after receiveMessage’ no log exists, even though both paths (ok and error) should log something.
And if I intentionally alter the name of the queue in ‘params’ before ‘receiveMessage’, no error due to not existing queue is given.
In both cases (queue name correct and altered), Lambda exits without errors.
It looks like the function is simply skipped. Is there something wrong with my code?

**Comment by philipwigg** [comment]
It looks like you're expecting the code to wait whilst the `receiveMessage` method runs and returns a value. Javascript is synchronous. So actually the execution of the code carries on immediately and `receiveMessage` will run in the background. I think the main body of your code has finished before `receiveMessage` has actually returned a value and called your callback function.

You can use asynchronous code instead which will pause and wait for `sqs.receiveMessage` to return a value which is what I think you are expecting to happen. Do this by using try/catch and async/await instead of passing in a callback. You will also need to chain the `receiveMessage` method with `.promise()`.

Here's [an example](https://gist.github.com/apal21/80c2cfe3606d30ae7d1c655ba6100ea4) which is for S3 and not SQS but should give you an idea of the structure.

**Comment by alfiafit** [comment]
Thank you very much, Philip, it worked fine!

**Comment by alfiafit** [comment]
Maybe I missed something, but it looks strange to me that in "https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sqs-examples-send-receive-messages.html" they don't put in evidence the fact Philip showed and the examples seems to be synchronous
