### ISSUE TITLE
Cors error - sdk js  and datasync

### ISSUE THREAD

**Issue by ddo88** [aws/aws-sdk-js#3442]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

i have this code.

```
AWS.config.region = 'us-east-1'; 
AWS.config.credentials = new AWS.CognitoIdentityCredentials({IdentityPoolId: 'MyPoolId'}); 

var datasync = new AWS.DataSync(); 
var params = { TaskExecutionArn: 'taskARN' }; 
datasync.describeTaskExecution(params, function(err, data) { if (err) console.log(err, err.stack); // an error occurred else console.log(data); // successful response });

```

the CognitoIdentityCredentials work´s without problem, return the user session info.

but when call datasync describeTaskExecution method, return this error

![92264227-86fc8f00-eea3-11ea-84a3-1b458fa00fa8](https://user-images.githubusercontent.com/885227/92610052-e16b6600-f27c-11ea-8683-10e37b904d92.png)

the IAM Policies already have permission to datasync methods, but whyt cors?, where i config datasync cors

for the sdk js library I use https://sdk.amazonaws.com/builder/js/ with CognitoIdentify and aws DataSync

**Comment by philipwigg** [comment]
According to https://github.com/aws/aws-sdk-js/blob/master/SERVICES.md, this service doesn't allow CORS. I'm not sure this will work.

**Comment by ddo88** [comment]
thanks

**Comment by ajredniwja** [comment]
Closing this issue now, please reach out if you have any additional questions.
