### ISSUE TITLE
Instructions how to implement --grant-full-control   into aws-SDK with NodeJS express.

### ISSUE THREAD

**Issue by andersontechnetverrum** [aws/aws-sdk-js#3444]
Instructions how to implement this CLI into aws-SDK with NodeJS express.
aws s3api put-object --bucket bucketname --key file.txt --grant-full-control id=CannonicalIDofrootaccount --grant-read id=CannonicalIDofprodaccount

## Expected Behavior
I am seeking how to implement the aws cli below using 'aws-sdk' with Node.JS express.  
	
aws s3api put-object --bucket bucketname --key file.txt --grant-full-control id=CannonicalIDofrootaccount --grant-read id=CannonicalIDofprodaccount

## Current Behavior

While my application uploading the objects to my  Root account bucket from stagging account  the I can't I access an object that was uploaded to the Staging account  Amazon S3 bucket by another AWS production account  - further information here: 
https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-owner-access/ 

## Possible Solution
I  can add the "--grant-full-control" acl by allowing your root account full access and then "--grant-read" acl for prod account's cannonical ids in the command, so that they can only read the object. 

how to do that in the using aws-sdk with NodeJS express?

**Comment by philipwigg** [comment]
There is `GrantFullControl` parameter you can pass to the S3.putObject method.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property

**Comment by ajredniwja** [comment]
Also refer to the comments in https://github.com/aws/aws-sdk-js/issues/256

Closing this now, feel free to reach out if you have any additional questions.
