### ISSUE TITLE
Ios archive not successful  include  aws-sdk but working fine in debug mode please help how to archive successful ? i am got struck in last4 days

### ISSUE THREAD

**Issue by kobagapu** [aws/aws-sdk-js#3445]
Confirm by changing [ ] to [x] below:
- [ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

**Comment by ajredniwja** [comment]
@kobagapu Im not sure if I understand your questions can you please answer the questions found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)?

**Comment by kobagapu** [comment]
Environment :- ReactNative
aws-sdk version --2.743.0,
xcode version :- 11.6
 i am using aws-sdk for uploading images to s3 bucket its working fine in android and ios but when i try to  upload to testflight in ios build archive is not successful or not failure its coming FATAL error heap memory

**Comment by ajredniwja** [comment]
Can you share minimal repro code?

**Comment by kobagapu** [comment]
I updated the latest version of aws-sdk issue resolved
