### ISSUE TITLE
Use of the term 'master' and 'slave'

### ISSUE THREAD

**Issue by shiftbreak** [aws/aws-sdk-js#3452]
Several files include the term 'master' and 'slave' which is considered to be oppressive language by the IETF:

https://tools.ietf.org/id/draft-knodel-terminology-00.html

**Comment by ajredniwja** [comment]
Hey @shiftbreak thanks for bringing this up, @trivikr one of our maintainers pointed it out as well, while we want to get it done as soon, this task will be prioritized after [re:invent](https://reinvent.awsevents.com/).
