### ISSUE TITLE
IE11 cannot parse Endpoint correctly

### ISSUE THREAD

**Issue by a1029563229** [aws/aws-sdk-js#3454]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [-] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [-] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [-] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
IE11 cannot parse Endpoint correctly.
I do this in IE11
```js
console.log(new AWS.Endpoint("https://www.baidu.com"));
```

It cause like this:

![image](https://user-images.githubusercontent.com/18710641/93550044-2b4efd00-f99d-11ea-97ea-1bf3ef3fafa5.png)

**Is the issue in the browser/Node.js?**
Browser IE11

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
Example: v2.755.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/18710641/93550044-2b4efd00-f99d-11ea-97ea-1bf3ef3fafa5.png)

**Comment by ajredniwja** [comment]
Hey @a1029563229 Thanks for opening the issue, I tested with the latest [Microsoft Edge](https://www.microsoft.com/en-us/download/internet-explorer.aspx), I didn't encounter any problems is it possible for you to upgrade to that?
