### ISSUE TITLE
ListObjectsV2 returns MalformedXML when prefix doesn't exist on the bucket specified

### ISSUE THREAD

**Issue by ChelseaRong** [aws/aws-sdk-js#3459]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When using the ListObjectsV2 function with prefix, the request returns 
`
{"errorType":"MalformedXML","errorMessage":"The XML you provided was not well-formed or did not validate against our published schema","trace":["MalformedXML: The XML you provided was not well-formed or did not validate against our published schema","    at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/s3.js:837:35)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)","    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}
`
when listed prefix doesn't exist on the bucket.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
v12.x

**SDK version number**
Example: v2.756.0

**To Reproduce (observed behavior)**
```  const params = { Bucket: bucket, Prefix: 'folderName' };

  const keys = await s3
    .listObjectsV2(params)
    .promise()
    .then((data) => data.Contents.map((c) => ({ Key: c.Key })))
    .catch((err) => {
      log(err, params);
      throw err;
    });
```

**Expected behavior**
Return unexpected prefix, or prefix doesn't exist on specified bucket, rather than returning MalformedXML, since the parameters used for listObjectsV2 is in the correct format.

**Comment by ajredniwja** [comment]
Hey @ChelseaRong thanks for opening this issue, I was not able to reproduce the behavior with latest version of the SDK. 

<details>
<summary>When prefix is present</summary>

```
{
  IsTruncated: false,
  Contents: [
    {
      Key: 'xyz',
      LastModified: 2020-09-22T00:02:01.000Z,
      ETag: '"31175863727365c3fd64c71070a6-3"',
      Size: 13710800,
      StorageClass: 'STANDARD'
    },
    {
      Key: 'xyz1',
      LastModified: 2020-09-23T06:08:23.000Z,
      ETag: '"c3557ca22ada1cca3f8013ef0251"',
      Size: 4,
      StorageClass: 'STANDARD'
    },
    {
      Key: 'xyz2',
      LastModified: 2020-09-23T06:08:41.000Z,
      ETag: '"c3557ca22ada1cc43f8013ef0251"',
      Size: 4,
      StorageClass: 'STANDARD'
    },
    {
      Key: 'xyz3',
      LastModified: 2020-09-23T06:08:49.000Z,
      ETag: '"c3557ca22ada1cc43f8013ef0251"',
      Size: 4,
      StorageClass: 'STANDARD'
    },
    {
      Key: 'xyz4',
      LastModified: 2020-09-23T06:08:56.000Z,
      ETag: '"c3557ca22ada1cc43f8013ef0251"',
      Size: 4,
      StorageClass: 'STANDARD'
    }
  ],
  Name: 'myBucket',
  Prefix: 'xyz',
  MaxKeys: 1000,
  CommonPrefixes: [],
  KeyCount: 5
}
```

</details>

<details>
  <summary>when prefix is not present</summary>

```
{
  IsTruncated: false,
  Contents: [],
  Name: 'myBucketr',
  Prefix: 'abc',
  MaxKeys: 1000,
  CommonPrefixes: [],
  KeyCount: 0
}
```

</details>

I see you are running on Lambda, can you make sure you are using the latest version of the SDK? 

AWS Lambda bundled SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

 You can import the latest version of SDK by following  [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

**Comment by ChelseaRong** [comment]
Hi @ajredniwja, thanks for the reply, I have upgraded the sdk to the latest version, this error is still reproduced and the full stack trace is as below, this only happens when prefix doesn't exist on the bucket
```
2020-09-23T11:14:59.926Z	0f291c91-d12c-4a81-ae31-664cc07f6434	INFO	handler | MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/s3.js:831:35)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'MalformedXML',
  region: null,
  time: 2020-09-23T11:14:59.887Z,
  requestId: '6EA631FAF8F84FCB',
  extendedRequestId: 'iDtkcpTygYxOD4uwzIZOQBBaaB8BJjOQbFwIjHCS2OK5jvzR3H3lFBhD5GCIUVKiHJpILNqfu+I=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 82.98223773948916
} { Bucket: 'nate-imgix-store', Prefix: 'abc' }
```
when I called s3 like below:
```
await s3
    .listObjectsV2({ Bucket: 'image-store', Prefix: 'abc' })
    .promise()
    .then((data) => data.Contents.map((c) => ({ Key: c.Key })))
    .catch((err) => {
      log(err, params);
      throw err;
    });
```
and if the prefix do exist the response is like below 
```
[
  {
    Key: '88e/2.jpg',
    LastModified: 2020-09-23T11:30:13.000Z,
    ETag: '"c6670461642b73432a631fbc275bc224"',
    Size: 23367,
    StorageClass: 'STANDARD'
  },
  {
    Key: '88e/3.png',
    LastModified: 2020-09-23T11:30:14.000Z,
    ETag: '"e08f8b00704d429c90e151bad272dc28"',
    Size: 1246129,
    StorageClass: 'STANDARD'
  }
]
```

**Comment by ajredniwja** [comment]
Do you get the same response when you run your code locally?

**Comment by ChelseaRong** [comment]
@ajredniwja below was the response for running locally, it does seem like it runs locally fine but only get the error _MalformedXML_ when running on the lambda
```
{
  IsTruncated: false,
  Contents: [],
  Name: 'image-store',
  Prefix: 'abc',
  MaxKeys: 1000,
  CommonPrefixes: [],
  KeyCount: 0
}
```
do you have an idea as why this could be?

**Comment by ajredniwja** [comment]
You might want to check the version of the SDK by printing the output of `AWS.VERSION` where ever you have 
```const aws = require('aws-sdk');``` and make sure you have gone through the steps [here](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html#nodejs-package-dependencies)
