### ISSUE TITLE
how to set `AWS.config.correctClockSkew = true`

### ISSUE THREAD

**Issue by crypto-maria** [aws/aws-sdk-js#3460]
how do it set `AWS.config.correctClockSkew = true`

_Originally question is at https://github.com/aws/aws-sdk-js/issues/1652

trying to resolve this issue

**Comment by ajredniwja** [comment]
Hey @crypto-maria thanks for opening this issue, 

You can set `correctClockSkew` to true using the code:

`AWS.config.correctClockSkew = true;`

Where AWS would be something like :

`var AWS = require('aws-sdk')`

More information found [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#correctClockSkew-property).

Closing this issue now, please reach out if you have any other questions.

**Comment by crypto-maria** [comment]
I get this error everywhere how do I resolve it in cli?????

**Comment by crypto-maria** [comment]
> Hey @crypto-maria thanks for opening this issue,
> 
> You can set `correctClockSkew` to true using the code:
> 
> `AWS.config.correctClockSkew = true;`
> 
> Where AWS would be something like :
> 
> `var AWS = require('aws-sdk')`
> 
> More information found [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#correctClockSkew-property).
> 
> Closing this issue now, please reach out if you have any other questions.

?

**Comment by crypto-maria** [comment]
@ajredniwja
