### ISSUE TITLE
Connect CreateContactFlow and UpdateContactFlow Content Parameter Does Not Match Exported JSON

### ISSUE THREAD

**Issue by cplankey** [aws/aws-sdk-js#3461]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

When creating a contact flow or updating an existing contact flow, there is a required parameter for Content. There are no docs on what this needs to look like. I assumed I could use an exported JSON file from the Connect UI, however it gets rejected (I have stringified it first). 

I see when Describing Contact flows that the same flow's content is in a completely different JSON format. 

I am trying to build a Lambda Custom CFT Resource to support CI/CD for our contact flows but am blocked by this format. 

Are there any docs showing what the contact flows should be formatted as and is there any way to take an exported Contact Flow and pass it through these APIs?

Thanks! 

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Connect.html#createContactFlow-property

**Comment by ajredniwja** [comment]
@cplankey thanks for opening this issue, can you share the code that you are using, The [docs](https://docs.aws.amazon.com/connect/latest/APIReference/API_CreateContactFlow.html#API_CreateContactFlow_RequestSyntax) here mention they can accept data in JSON format so using stringify should work.

**Comment by cplankey** [comment]
Attached is a repo outlining the issue: https://github.com/cplankey/aws-sdk-issue-3461

The function named `doesntWork` is using a JSON contact flow exported via the Connect UI. The function named `works` uses JSON retrieved by the `describeContactFlow` API. 

The root of this problem is that the API is expecting `Content` that follows the [Amazon Connect Flow language](https://docs.aws.amazon.com/connect/latest/adminguide/flow-language.html) for both the create and update API calls but this is not documented in the API docs. 

Furthermore, it would be great if the APIs could accept JSON in the same format as the Connect UI exports.

**Comment by ajredniwja** [comment]
Hey @cplankey Thanks for putting up the repo, I agree that the format is not entirely clear but there is a link to [ Amazon Connect Flow language](https://docs.aws.amazon.com/connect/latest/adminguide/flow-language.html) right below [createContactFlowAPI](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Connect.html#createContactFlow-property). 

I have requested to re evaluate the Docs there and provide with a clearer explanation. 
Will update once I hear back from the team that works on it.

**Comment by yogarasu** [comment]
I am suffering from the same problem
At first I thought it was a character issue that needed to be escaped
