### ISSUE TITLE
Signed s3 url contains a dot instead of a dash

### ISSUE THREAD

**Issue by kongeor** [aws/aws-sdk-js#3462]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

We are using signed urls to s3 files but we are observing the following issue in the last couple of weeks, the urls appear to have dot but in the aws console they seem to have a dash.
For example, the signed url looks like:
`https://<bucket>.s3.eu-west-1.amazonaws.com/foo.txt`
but the file on s3 is:
`https://<bucket>.s3-eu-west-1.amazonaws.com/foo.txt`

can't see something obviously wrong with the code.
thanks!

**Comment by ajredniwja** [comment]
Hey @kongeor Thanks for opening this request, is there any limitation you are facing because of that? I have checked it with the CLI and it appears to be the same and the URL works.

**Comment by kongeor** [comment]
Yup, sorry, it was working fine. The problem was an extra IP restriction that I didn't knew of. Turning this off resolved the issue.

Thanks!
