### ISSUE TITLE
getSignedUrlPromise behaves different compared to amazonS3.generatePresignedUrl (Java)

### ISSUE THREAD

**Issue by seppevs** [aws/aws-sdk-js#3463]
Confirm by changing [ ] to [x] below:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Hi,

I have an issue with creating a pre-signed URL to upload files to an s3 bucket.

In our old implementation, we used the Java AWS SDK inside a AWS Lambda function. 
There, we made use of the following method:

`amazonS3.generatePresignedUrl(bucketName, key, expiration, HttpMethod.PUT)`
-> see: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#generatePresignedUrl-java.lang.String-java.lang.String-java.util.Date-com.amazonaws.HttpMethod-

This works great. We have several clients, and they can all upload their files to our bucket by doing an HTTP PUT request to the URL generated by above method.

Now, we want to implement the same thing in a Node.js lambda function. This is the implementation I currently have:

```
const s3 = new AWS.S3();
const uploadUrl = await s3.getSignedUrlPromise('putObject', {
    Bucket: config.videoUploadBucketName,
    Expires: 3600, // 1 hour
    Key: videoId,
  });
return uploadUrl;
```

This snippet generates an url which I can use to upload files to our bucket using an HTTP PUT call.

BUT, we've found out that the browser(s) of our clients also send an 'Content-Type' header when they perform the HTTP PUT operation to upload their files.
When they do this, they receive a HTTP 403 Forbidden response.

It seems that the Content-Type has impact on the signature (?), because we can bypass this HTTP 403 Forbidden error when we pass the contentType in the params when signing:

```
  const s3 = new AWS.S3();
  const uploadUrl = await s3.getSignedUrlPromise('putObject', {
    Bucket: config.videoUploadBucketName,
    Expires: 3600, // 1 hour
    ContentType: 'application/x-www-form-urlencoded; charset=UTF-8',
    Key: videoId,
  });
  return uploadUrl;
```

But, this is something we want to avoid. We don't want to hardcode this contentType (or pass it from our clients browsers upfront in some way).

We want zero impact to our client when we change our backend from Java to Node.js

So the main question is:
How can we avoid the HTTP 403 Forbidden error when our clients upload their files to our bucket and their HTTP PUT Request contains (any) Content-Type?
It works just fine with the Java SDK. How can we have the same effect with the JavaScript AWS S3 SDK?

Thank you kindly

**Comment by ajredniwja** [comment]
@seppevs Thanks for opening this issue, I think it is based on the browser and how the requests are passed through them since both Java and JS SDK would create a similar `signedUrl` do you mind sharing what library/framework you were using with JAVA and what are you using right now to use the URL to upload the file?
