### ISSUE TITLE
Switching between profiles during runtime

### ISSUE THREAD

**Issue by hammadzz** [aws/aws-sdk-js#3464]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
What is the best way to switch between profiles during runtime when using the AWS JS SDK? 

I can explicitly set the profile as follows:
```js
const foo_creds = AWS.SharedIniFileCredentials({profile: 'foo_profile'})
const ec2_client = new AWS.EC2({credentials: foo_creds })
```

I have considered the following options:
1. Lazily create service client for each profile and store it in a singleton object (memory issues?)
1. If profile changes recreate the service client (a bit slow but speed isn't an issue)
     - is there an api to check the current profile on a service client?
1. Any other suggestions?

This issue relates most closely to GH-2181 but I don't mind default profile selected on startup, I just want to be able to change between profiles easily.

**Comment by ajredniwja** [comment]
Hey @hammadzz thanks for opening the issue, yes that is actually some good options to switch profiles, a new client with the profile would be need to be created. I would prefer option 2, the way to check the profile would be: 

Example for S3 service client: 

`console.log(S3.config.credentials.profile);`

I would close this issue now, please feel free to reach out if you have any questions.
