### ISSUE TITLE
Cross-Origin Request Blocked - https://connect.us-west-2.amazonaws.com/users-summary/instanceID

### ISSUE THREAD

**Issue by josefyendif** [aws/aws-sdk-js#3465]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

i have using the connect SDK Method 
var params= {
	InstanceId:"xxxx"
 };
connect.listUsers(params, function (err, data) {
)};

But i am always getting an CORS Error

**Comment by ajredniwja** [comment]
Hey @josefyendif Thanks for opening this issue, CORS is not currently supported for `connect` API. Please refer to https://github.com/aws/aws-sdk-js/issues/3206#issuecomment-699180087 for a workaround.
