### ISSUE TITLE
When using RDS, how can I send a value that can be null?

### ISSUE THREAD

**Issue by Ricardo1980** [aws/aws-sdk-js#3467]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Hello, 
I have a small issue.

When using RDS, how can I send a value that can be null?

This is my code:
  ```
const params = {
    secretArn: secretStoreARN,
    resourceArn: clusterIdentifierARN,
    database: databaseName,
    sql: `INSERT INTO UserReaction (senderUserId, receiverUserId, type) VALUES(UNHEX(:reactionSenderProfileUserId), UNHEX(:reactionReceiverProfileUserId), :reactionType) ON DUPLICATE KEY UPDATE updatedAt = NOW(3), type = :reactionType;`,
    parameters: [
      {
        name: 'reactionSenderProfileUserId',
        value: {
          "stringValue": reactionSenderProfileUserId
        }
      },
      {
        name: 'reactionReceiverProfileUserId',
        value: {
          "stringValue": reactionReceiverProfileUserId
        }
      },
      {
        name: 'reactionType',
        value: {
          "stringValue": reactionType
        }
      }
    ]
  }  
  try {
    let dbResponse = await RDS.executeStatement(params).promise();
    return true;
  } catch (error) {
    throw error;
  }
```

If reaction type is a string, then everything works fine.
But if reaction type is null (which is allowed in my data model), then I see this error from the lambda function:
`BadRequestException: Parameter "reactionType" has value with no field set`

So, reading this:
https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteStatement.html
Perhaps I should use "isNull", not sure how.

I don't really know how to create a parameter for RDS.executeStatement that can be a string or null, I think that is the problem.

The solution I see right know is to create 2 params, but that is not scalable if I have more parameters that can be null.

What should I do?
Thanks a lot.

**Comment by ajredniwja** [comment]
Hey @Ricardo1980 apologies for relayed reply, you can set `isNull` to `true`. You can find an example here:

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#executeStatement-property

Closing this now, please reach out if you have any other questions.

**Comment by Ricardo1980** [comment]
Thanks for reply! I will try that.
