### ISSUE TITLE
completeMultipartUpload  Location '/' is encoded

### ISSUE THREAD

**Issue by SummerJoan3** [aws/aws-sdk-js#3468]
The Location in the data returned by completeMultipartUpload, '/'  is encoded
example:
I get:"https://example.com/test%2Fvideos%2F16013508454466583824.mp4"
I hope:"https://example.com/test/videos/16013508454466583824.mp4"

**Comment by ajredniwja** [comment]
Hey @SummerJoan3 thanks for opening this issue, can you please fill out the required information found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=guidance%2C+needs-triage&template=---questions---help.md&title=).

**Comment by topwebtek7** [comment]
@xjq7 this issue is resolved? I'm facing exactly same issue now

**Comment by xjq7** [comment]
@topwebtek7 You can decode your URL
