### ISSUE TITLE
CloudWatch getMetricWidgetImage wrong 'bar' graph with 'sum' statistic for given time range

### ISSUE THREAD

**Issue by ostashkevych** [aws/aws-sdk-js#3470]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Hello
I am using CloudWatch getMetricWidgetImage to get graph snapshots of my metrics stored in cloudwatch.
when in params I set view to 'bar' and stat to 'Sum' I expected to get graph of summed metrics for given time range, but instead I received graph for first available data.
lets say during last few hours I have metrics data spreaded as shown in the screenshot
one data set at 8 A.M and second at 12 A.M.
for orange bar its 275 metrics and 166 respectively (in total 441)
![image](https://user-images.githubusercontent.com/47977684/94566885-89b88d00-0273-11eb-9c78-2c04250061ce.png)
timeSeries graph works fine
but when I set view to 'bar' I received this image (below)
as you can see it shows only first data set for 8 A.M  (275 metrics for orange bar)
![image](https://user-images.githubusercontent.com/47977684/94567668-63472180-0274-11eb-830c-b666f615ebe7.png)

I experimented with 'period' and other parameters but without success.
doing the same in aws UI gives me graph that I expected (sum statistic for given time range)

![image](https://user-images.githubusercontent.com/47977684/94568759-99d16c00-0275-11eb-8a95-db607c82fcef.png)

**Is the issue in the browser/Node.js?**
Browser

**SDK version number**
v2.752.0
apiVersion 2010-08-01

**Expected behavior**
show 'sum' statistic for given time range

**Comment by ajredniwja** [comment]
Hey @ostashkevych thanks for opening this issue, can you please share code/steps to reproduce the issue?
