### ISSUE TITLE
Using cognito/amplify to authenticate a kinesis video stream in a react application.

### ISSUE THREAD

**Issue by istranic** [aws/aws-sdk-js#3472]
Confirm by changing [ ] to [x] below:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I'm creating a web app using react that will display a kinesis video stream. I'm struggling to understand how I can use the authentication using amplify/congito to authenticate and display the kinesis video stream. Here's an overview of what I've done so far.

I successfully created the app login using the Prebuilt UI components [here ](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#configure-your-application)

I'm able to stream from kvs using kinesisVideoArchivedContent.getHLSStreamingSessionURL by authenticating using hard-coded access & secret keys from my account AWS.KinesisVideo(options...containing the keys).

Now I'm trying to figure out how to pass the amplify/cognito credentials to AWS.KinesisVideo(options)?

I also updated the amplify_auth_role to include kinesisvideo:GetHLSStreamingSessionURL and kinesisvideo:GetDataEndpoint in its permission policy.

Any guidance is highly appreciated!

**Comment by ajredniwja** [comment]
Hey @istranic, thanks for opening the issue, you can use `cognito` like mentioned in the docs [here](https://docs.aws.amazon.com/cognito/latest/developerguide/getting-credentials.html)
