### ISSUE TITLE
IAM Roles using CloudFormation

### ISSUE THREAD

**Issue by amicming** [aws/aws-sdk-js#3483]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I'm currently adding Amazon Connect Participant Service in my one of the application and need to create instance of ConnectParticipant as per below way.

`const connectparticipant = new AWS.ConnectParticipant();`

I can not use config as per below (For development purpose is ok).

```
const AWS = require("aws-sdk");
AWS.config.update({
  accessKeyId: ENV.ACCESS_KEY,
  secretAccessKey: ENV.SECRET_ACCESS_KEY,
  region: "us-east-1"
});
```

My Question is, Can I use aws-sdk-js configuration properties in IAM Roles using CloudFormation?
Can I have direction or any links please?

**Comment by philipwigg** [comment]
Is this what you mean? https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-iam.html

**Comment by ajredniwja** [comment]
The link provided by should solve the problem or point you in the right direction, closing this issue now, please reach out if you have any other questions.
