### ISSUE TITLE
403 Forbidden error with aws-sdk v2.769.0 

### ISSUE THREAD

**Issue by kim00kim** [aws/aws-sdk-js#3484]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and
![403](https://user-images.githubusercontent.com/9582956/95418926-7abc9380-0973-11eb-9e82-2b333331749d.PNG)
 [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When I'm trying to download the latest aws-sdk, I get a 403 forbidden error on v2.769.0. But I don't get an error when I download the v2.768.0.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v11.15.0

**SDK version number**
v2.769.0

**To Reproduce (observed behavior)**
In package json, "aws-sdk": "^2.732.0" is set in dependencies.
On npm install, I get the 403 Forbidden error.

**Expected behavior**
Can download to latest version with no problems.

**Screenshots**

**Comment by ajredniwja** [comment]
Hey @kim00kim thanks for opening this, how are you downloading the SDK? 
I didnt have trouble installing the lates 2.771 

Can you please share the steps that you are using and your use case?
