### ISSUE TITLE
createPresignedPost triggers the callback twice and crashes when credentials are not provided

### ISSUE THREAD

**Issue by slifty** [aws/aws-sdk-js#3486]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When calling `createPresignedPost` with a callback and invalid credentials, my callback is called and node also crashes.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.18.3

**SDK version number**
v2.763.0

**To Reproduce (observed behavior)**

In an environment *with no configured credentials*:

```
import { S3 } from 'aws-sdk';
try {
  const s3 = new S3();
  s3.createPresignedPost({}, (err, data) => {
    console.log('sup dog');
  });
} catch (err: Error) {
  console.log('KABOOM!');
}
```

Running this causes the following output:

```
sup dog
./node_modules/aws-sdk/lib/services/s3.js:1241
      throw new Error('Unable to create a POST object policy without a bucket,'
      ^

Error: Unable to create a POST object policy without a bucket, region, and credentials
    at features.constructor.preparePostFields (./node_modules/aws-sdk/lib/services/s3.js:1241:13)
    at finalizePost (./node_modules/aws-sdk/lib/services/s3.js:1204:22)
    at ./node_modules/aws-sdk/lib/services/s3.js:1221:24
    at finish (./node_modules/aws-sdk/lib/config.js:386:7)
    at ./node_modules/aws-sdk/lib/config.js:428:9
    at Object.<anonymous> (./node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:111:13)
    at Object.arrayEach (./node_modules/aws-sdk/lib/util.js:516:32)
    at resolveNext (./node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:110:20)
    at ./node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:126:13
    at ./node_modules/aws-sdk/lib/credentials.js:124:23
error Command failed with exit code 1.
```

I looked into the code and what's happening is that my callback is being called twice.  Specifically, it is being called [once to pass the credential error](https://github.com/aws/aws-sdk-js/blob/4fd99d087f245f23b164219fba62156af060770e/lib/services/s3.js#L1081), and then it is being [called a second time](https://github.com/aws/aws-sdk-js/blob/4fd99d087f245f23b164219fba62156af060770e/lib/services/s3.js#L1084).

The second call does not actually complete, because `finalizePost` calls `preparePostFields` which then [throws an error](https://github.com/aws/aws-sdk-js/blob/4fd99d087f245f23b164219fba62156af060770e/lib/services/s3.js#L1104) due to invalid configuration. 

**Expected behavior**
I would expect the error to be passed to the callback directly (using `err`) without terminating the process.

**Screenshots**
N/A

**Additional context**
The partial solution is to update [L1080](https://github.com/aws/aws-sdk-js/blob/4fd99d087f245f23b164219fba62156af060770e/lib/services/s3.js#L1081) to be `return callback(err);` instead of just `callback(err);`

The fully defensive solution would be to ALSO wrap [L1084](https://github.com/aws/aws-sdk-js/blob/4fd99d087f245f23b164219fba62156af060770e/lib/services/s3.js#L1084) in a try catch block:

```
try {
        callback(null, finalizePost());
} catch (err) {
        callback(err);
}
```

**Comment by slifty** [comment]
A note that I have I can submit a PR for this but I'm having trouble writing a unit test.

The error itself is being triggered outside of the call stack / callback flow, which means I'm not able to actually detect it within mocha (in the same way I'm not able to detect it in my sample application).  Unfortunately the unhandled error happens *after* a valid callback, which means I call `done` and the test runner moves along and apparently ignores the unhandled error.

I'm going to open a PR with the fix (not test) for now, but would love any guidance on how to nail down this one.

## Side note

I tried catching unhandled errors, as part of an R&D test, and uncovered another unhandled error that is triggered by [this test](https://github.com/aws/aws-sdk-js/blob/9bab986c0ab1b9a4f33ba92823daee738d3761a7/test/s3/managed_upload.spec.js#L992).  It looks like that test actually exposes a potential bug that it isn't testing: the handler seems to be called *twice* but the first call passes (and invokes `done`) and the second call creates an assertion failure which occurs after `done()` was called, and therefore is going unnoticed.

**Comment by slifty** [comment]
Following up here -- if I submit a patch without a failing test would that be helpful?

**Comment by ajredniwja** [comment]
@slifty I can have someone take a look at the PR if you would like to work on it.

**Comment by jasonaowen** [comment]
This is still an issue.

I work with @slifty, and while I don't mean to speak for him, it seems unlikely to me that we'll have bandwidth to work on fixing this in the near future. We ended up working around the bug, but it would be better if we didn't have to.

**Comment by slifty** [comment]
Just a note -- I'll have a PR for this very shortly.
