### ISSUE TITLE
await adminCreateUser().promise() results in two requests

### ISSUE THREAD

**Issue by thedrivendev** [aws/aws-sdk-js#3487]
Similar to issue #3070 

I am attempting to create a new user in a Cognito userpool using the adminCreateUser API with async / await & .promise(). The code below returns an error code UsernameExistsException which seems to indicate that the unique username constraint is being violated by the request. Prior to triggering the request, I've confirmed that the username isn't assigned to a user in the userpool leading me to believe that the request is being sent twice. Any tips on resolving this?

```
const AWS = require('aws-sdk');
const Cognito = new AWS.CognitoIdentityServiceProvider();

module.exports = async event => {
  try {
    const { username, email_address } = JSON.parse(event.body);

    const cognitoParams = {
      UserPoolId: 'us-east-1_XXXXXXXXX',
      Username: username,
      DesiredDeliveryMediums: ['EMAIL'],
      ForceAliasCreation: true,
      MessageAction: 'SUPPRESS',
      TemporaryPassword: 'TEMPpass1@3',
      UserAttributes: [
        {
          Name: 'email',
          Value: email_address,
        },
        {
          Name: 'custom:id',
          Value: '100001',
        },
      ],
    };

    // await with .promise()
    const cognitoResponse = await Cognito.adminCreateUser(
      cognitoParams
    ).promise();

    return {
      statusCode: 201,
      body: JSON.stringify(cognitoResponse.user),
    };
  } catch (error) {
    console.log(error);
  }
};
```

**Comment by philipwigg** [comment]
I haven’t tested but the code looks fine to me. Are you sure you’re not calling the whole function twice? Maybe put some logging in to check?

**Comment by bpred754** [comment]
@thedrivendev I am seeing similar behavior. Were you able to figure it out?

**Comment by thedrivendev** [comment]
@bpred754 I believe I found that the Cognito client had been updated to promises so the additional .promise() method was the underlying issue.

**Comment by bpred754** [comment]
@thedrivendev thanks for the quick response! I actually just found our particular issue, I will explain here for anyone else who comes across something similar. We had the CognitoIdentityServiceProvider timeout option set to 10 seconds. The create user request was timing out and the CognitoIdentityServiceProvider was retrying under the hood. The original request had never failed, it was just taking longer than our configured timeout. So when the retry request was sent, the user already existed, thus we received the UsernameExistsException.
