### ISSUE TITLE
Resend MFA Code for login process

### ISSUE THREAD

**Issue by Deepesh316** [aws/aws-sdk-js#3488]
**Is your feature request related to a problem? Please describe.**
I have been searching for resending mfa code (via SMS) for login process in aws-sdk. But not able to find any possible method for implementing the same.

Requirement:
1) MFA is set to required in cognito.( through SMS )
2) User enters Login username and password
3) User is redirected to Verify MFA code page
4) Now comes the edge case where user doesn't receives code on phone due to network issues or some other issues. Hence we need to provide user with option to resend MFA code

As per my understanding from the documentation, resend OTP is possible for signup. [resend-otp-for-signup](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ResendConfirmationCode.html)

**Describe the solution you'd like**
A way to re-send MFA Code due to some edge case a user does not receive code in the initial signIn flow. We need a similar functionality like resendConfirmationCode.

**Comment by Stone2517** [comment]
Try resending login details.

**Comment by s1mrankaur** [comment]
is there a solution? Cognito seems very immature and committing to it a mistake.

**Comment by omarioffline** [comment]
MissingRequiredParameter: Missing required key 'retentionInDays' in params
    at ParamValidator.fail (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (webpack-internal:///./node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (webpack-internal:///./node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (webpack-internal:///./node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at eval (webpack-internal:///./node_modules/aws-sdk/lib/event_listeners.js:86:9)
    at finish (webpack-internal:///./node_modules/aws-sdk/lib/config.js:386:7)
[Uploading amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc (1).zip…]()

    at eval (webpack-internal:///./node_modules/aws-sdk/lib/config.js:404:9)

**Comment by omarioffline** [comment]
AWS Forums

**Comment by Nxtra** [comment]
With OTP codes we work around it like this.

We send a custom challenge answer that contains metadata which indicates the code should be resend.
```
  const askToResendOtpCode = async () => {
      const cognitoUser = await Auth.sendCustomChallengeAnswer(session, '0', {'resend': 'yes'})
      alert("OTP code has been resend. Give it a minute.")
  }
```

Then in your create challenge trigger lambda function check the metadata on the request:
```
const shouldResendCode = event.request.clientMetadata?.resend === 'yes' ? true : false;
...
      if(shouldResendCode){
        console.log("Asked to resend the code, will do")
        await sendSms(phoneNumber, secretLoginCode)
      }
...
```

This way the client has the option to ask for the code to be send again.

**Comment by mandeepm91** [comment]
@Nxtra Which AWS cognito API endpoint did you use for this? The logic that you shared, did you write this in the lambda triggers?

**Comment by StephenOkeleke97** [comment]
2 years later and this hasn't been resolved

**Comment by cunguyen-agilityio** [comment]
Any update, guys?

**Comment by jmnProcom** [comment]
Same, would appreciate a method like resendMFaCode. Right now have to reauthenticate the user to trigger another code.

**Comment by samsiis** [comment]
The feature is being worked upon by the cognito team as detailed  #6676

**Comment by dvargas10Pearls** [comment]
+1

**Comment by kennydifiore** [comment]
+1 Following
