### ISSUE TITLE
The security token included in the request is invalid - IoT SDK in NodeJS

### ISSUE THREAD

**Issue by matwerber1** [aws/aws-sdk-js#3490]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

When running `iotdata.updateShadow()` from NodeJS on an AWS Cloud9 instance in us-west-2, I am receiving an unauthorized error.

I am running the Cloud9 with the "AWS Managed Credentials" feature enabled, meaning the instance should inherit the IAM permissions of the user that created the Cloud9. I created the Cloud9 with an admin role (has `AdministratorAccess` AWS-managed policy) and that is the same role I am using to access the Cloud9. 

My issue seems eerily similar to the issue described below, in which a backend AWS error was acknowledged in this region for IoT:
https://github.com/aws/aws-sdk-js/issues/1710

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**

```
v10.22.1
```

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

```
└── aws-sdk@2.747.0 
```

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

Abbreviated code, below:

```
const AWS = require('aws-sdk');
const iot = new AWS.Iot();

async function main() {
  var describeEndpointResponse = await iot.describeEndpoint({ endpointType: 'iot:Data-ATS' }).promise();  
  const IOT_DATA_ENDPOINT = describeEndpointResponse.endpointAddress;
  const iotdata = new AWS.IotData({ endpoint: IOT_DATA_ENDPOINT, region: IOT_REGION });  
  await updateShadow('thing123', {power: 100} );
}

async function updateShadow(thingName, reportedShadow) {

    var payload = {
      state: {
        reported: shadowValue
      }
    };

  var params = {
    payload: JSON.stringify(payload),
    thingName: thingName
  };

  await iotdata.updateThingShadow(params).promise();
}
```

**Expected behavior**
Given that I'm using an admin role / credentials from Cloud9, I'd expect the `iotdata.updateThingShadow()` API call to work. 

Further, its odd that the `iot.describeEndpoint()` API call succeeds, but the `iotdata` call fails.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ajredniwja** [comment]
Hey @matwerber1, apologies for delayed response here, not able to quite reproduce it when running locally, is there anything you might be doing differently than the code provided? 
If not I can reach out to internal teams to get more information on it.
