### ISSUE TITLE
Problem receiving messages from FIFO queue.

### ISSUE THREAD

**Issue by MinhNguyen41092** [aws/aws-sdk-js#3491]
Confirm by changing [ ] to [x] below to ensure that it's a bug:

* [x]  I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
* [x]  I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
* [x]  I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution

**Describe the bug**
While polling messages from a FIFO queue on console, I get the correct order of messages. But when I use the `receiveMessage` method of the SDK the order is all over the place. 

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
v10.x
> 
**SDK version number**
v2.712.0

**To Reproduce (observed behavior)**

This code demonstrates the polling process using the SDK:

```js
const params = {
    AttributeNames: [],
    MaxNumberOfMessages: 10,
    MessageAttributeNames: ['All'],
    QueueUrl: process.env.TEST_FIFO_QUEUE,
    VisibilityTimeout: 30,
    WaitTimeSeconds: 20
  }

  const {
    Messages: messages
  } = await sqs
    .receiveMessage(params)
    .promise()

  const messageAttributes = messages.map(message => ({
    id: message.MessageId,
    attributes: message.MessageAttributes
  }))
  console.log('==> Message attributes: ', messageAttributes)
 ```

==> Message attributes:
```==> Message attributes:
[ { id: '6f8df891-741d-4598-a6e1-96b1b43e5c21',
    attributes: undefined },
  { id: '16056f3f-3550-49ed-8fbc-ecb7ee1c1e45',
    attributes: undefined },
  { id: 'c3f4e887-9d0f-4b2b-af88-6f5327d86e90',
    attributes: undefined },
  { id: 'daf09d69-5e42-4ae8-830a-199fe97af276',
    attributes: undefined },
  { id: '2c74beb1-4b1b-48c9-a784-ff3ae0b26bad',
    attributes: undefined } ]
```

**Expected behavior**
Results from AWS console: Message IDs
```
6f8df891-741d-4598-a6e1-96b1b43e5c21
16056f3f-3550-49ed-8fbc-ecb7ee1c1e45
2c74beb1-4b1b-48c9-a784-ff3ae0b26bad
c3f4e887-9d0f-4b2b-af88-6f5327d86e90
daf09d69-5e42-4ae8-830a-199fe97af276
```

**Comment by MinhNguyen41092** [comment]
I noticed that this behavior happens when I set unique, random message group id for each message. May be this is the root cause?

Excerpt from documentation:
```
FIFO queue logic applies only per message group ID. Each message group ID represents a distinct ordered message group within an Amazon SQS queue. For each message group ID, all messages are sent and received in strict order. However, messages with different message group ID values might be sent and received out of order. You must associate a message group ID with a message. I
```

**Comment by ajredniwja** [comment]
Hey @MinhNguyen41092 thanks for opening this issue, I found [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#receiveMessage-property)
That 
> "The tag that specifies that a message belongs to a specific message group. Messages that belong to the same message group are processed in a FIFO manner (however, messages in different message groups might be processed out of order). To interleave multiple ordered streams within a single queue, use MessageGroupId values (for example, session data for multiple users). In this scenario, multiple consumers can process the queue, but the session data of each user is processed in a FIFO fashion."

So messages in different groups may be received out of order. 

Messages from same group should be ordered correctly, so I believe this is the intended behavior of the SDK.

Please let me know if you have more questions?

**Comment by MinhNguyen41092** [comment]
@ajredniwja Thanks for your answer. We've changed implementation to using the same MessageGroupId for the same batch of messages and they are ordered correctly. I'll close the issues.
