### ISSUE TITLE
ReferenceError: Cannot access uninitialized variable. In Ionic Capacitor project.

### ISSUE THREAD

**Issue by Abhi0725** [aws/aws-sdk-js#3494]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I am using this package in Ionic (Capacitor) project.

This is how I import it in one of my page.ts file:

`import AWS from "aws-sdk";`

I have added the required "types" key in `compilerOptions` in the tsconfig.app.json file like below:

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": ["node"]
  },
  "files": ["src/main.ts", "src/polyfills.ts"],
  "include": ["src/**/*.ts", "src/**/*.d.ts"],
  "exclude": ["src/**/*.spec.ts"]
}

```
Now, when I run the code and if I access AWS any where then that module stops loading. The compilation is success but app screen is blank with following error (works fine when I uncomment the AWS code from page.ts):

`ReferenceError: Cannot access uninitialized variable.`.

I have tried doing it as:

`let AWS = require('aws-sdk')` too nut no luck.

**Is the issue in the browser/Node.js?**
Browser/Node.js
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v10.15.3

**SDK version number**
2.771.0

**Comment by ajredniwja** [comment]
Hey @Abhi0725 thanks for opening the issue, can you setup a minimal reproduction repo?

**Comment by ajredniwja** [comment]
Glad that you found the solution. Closing this issue now.
