### ISSUE TITLE
error:060A80A3:digital envelope routines:FIPS_DIGESTINIT:disabled for fips

### ISSUE THREAD

**Issue by motionreboot** [aws/aws-sdk-js#3496]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
NodeJS version 8, built with fips open ssl and using aws-sdk 2.771.0 to upload files to the us-gov-east-1 region fails with the error **error:060A80A3:digital envelope routines:FIPS_DIGESTINIT:disabled for fips ... at new Hash (crypto.js:81:18)** - downloading files works fine.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No. AWS Linux AMI 2

**Details of the browser/Node.js version**
v8.9.4

**SDK version number**
2.771.0

**To Reproduce (observed behavior)**
Deploy a Linux AMI 2 on an EC2 instance in the us-gov-east-1 region on gov cloud. Enable the EC2 instance for FIPS. Build from source NodeJS with FIPS support as described in the readme and BUILD on Node version 8. Attempt to upload any text file using S3 with example code below:

```
const AWS                = require('aws-sdk');
AWS.config.region   = 'us-gov-east-1';
const s3                    = new AWS.S3();

const u1  = {Key:'any'};
u1.Body   = 'test';
u1.Bucket = 'yourbucket/yoursubbucket'

s3.putObject(u1, function(err, data)
{
    console.log("the error is", err); 
});
```

**Expected behavior**
I expect to get a null error response from the s3.putObject callback function and also to see my file uploaded into my S3 bucket when i visit the amazon s3 website. 

**Additional information**
`sysctl crypto.fips_enabled ` returns  **crypto.fips_enabled = 1**
`openssl version`  returns **OpenSSL 1.0.2k-fips  26 Jan 2017**
`openssl sha | grep fips` returns **140223502632864:error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips:digest.c:256**
`ssh localhost 2>&1 | grep FIPS` returns **FIPS mode initialized**

**Additional Resources**
From the additional information above, the error about digital envelope routines being disabled seems to be the most relevant because it directs attention to an OpenSSL error and resolution here:
https://github.com/ansible/ansible/issues/67213
and how that 3rd party resolved the issue with OpenSSL here: https://github.com/ansible/ansible/pull/67515 

You will note in the comments that "MD5 isn't possible there"

It may also be valuable to look at the NIST standards on FIPS 140-2 page 16, table 6 for confirmation of types of MD5. 
https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp1675.pdf

You'll note that: MD5 using TACACS+ and RADIUS, as well as HMAC‐MD5‐96 are both not approved.

**Comment by ajredniwja** [comment]
Hey @motionreboot thanks for opening this, I believe this error is not related to the SDK but node, can you try upgrading to a more recent version?

**Comment by motionreboot** [comment]
Hi I actually can’t. NodeJS version 8 appears to be the only version that can be built from source with FIPS 140-2 level 1 compliance

**Comment by ajredniwja** [comment]
Thanks for updating.

**Comment by kkochubey1** [comment]
@motionreboot we run into the same issue. Does it mean md5 is allowed by nist standard on FIPS 140-2? Which OpenSSL we should use to be fips compliant and work with s3/sqs?

**Comment by jb00ster** [comment]
hi @kkochubey1  we run also into the same issue and MD5 is not allowed
we have added the flag 
`new AWS.S3({
    ...., 
    s3DisableBodySigning: false,
    signatureVersion: 'v4'
})
`
within S3 configuration and this worked for us 
hope this will help
