### ISSUE TITLE
Including Full AWS SDK in NodeJS Project

### ISSUE THREAD

**Issue by ntownsend80** [aws/aws-sdk-js#3499]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

I am trying to include the full AWS SDK in my NodeJS project. I’ve been able to download and build the full SDK following https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html#using-command-line-tools. However, I have not been able to figure out how to include the SDK in my Node project. Running `npm pack` seems to build the same SDK as is available on the npm registry and including the aws-sdk-full.js directly in my project results in the file being printed to the console in an infinite loop.

What is the correct process for including the full AWS SDK in a NodeJS project.

**Comment by ajredniwja** [comment]
Hey @ntownsend80 thanks for opening this, you can simply follow the steps here:
https://github.com/aws/aws-sdk-js#in-nodejs

A more well defined project: 
https://github.com/aws-samples/aws-nodejs-sample

* Simply add the SDK version in your `package.json`
* `npm install` 
* `npm pack`

Closing this issue now, please reach out if that doesn't solve your problem.
