### ISSUE TITLE
Timeout documentation appears to be incorrect

### ISSUE THREAD

**Issue by julrich1** [aws/aws-sdk-js#3504]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
In the export of the HTTPOptions interface there are several comments regarding timeouts along with comments describing their functionality. Along with these the SDK documentation also has comments that do not match the TypeScript comments.
In my testing, neither of these is correct. The timeout is the actual transaction timeout when waiting for a response from Dynamo, nothing related to inactivity of the connection. When tuning timeouts and retries it is very important for this functionality to be well documented, otherwise the default value of two minutes for a timeout can cause extremely long transaction times.

TypeScript comments:
`    /**
     * The number of milliseconds to wait before giving up on a connection attempt.
     * Defaults to two minutes (120000).
     */
    timeout?: number;`

SDK comments (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html):
`timeout [Integer] — Sets the socket to timeout after timeout milliseconds of inactivity on the socket. Defaults to two minutes (120000).`

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.14.1

**SDK version number**
2.769.0

**Expected behavior**
I would expect proper documentation on this functionality so that tuning retries and timeouts behaves as expected.

**Comment by ajredniwja** [comment]
Hey @julrich1 Thanks for opening this issue, 

My findings: 

<details>

<summary>
Setting timeout lower than the time it needs to get a response from the service i.e 2ms:
</summary>

I get error: 

```
  message: 'Connection timed out after 2ms',
  code: 'TimeoutError',
  time: 2020-10-30T22:54:33.282Z,
  region: 'us-west-2',
  hostname: 'dynamodb.us-west-2.amazonaws.com',
  retryable: true
```

</details>


<details>

<summary>
Setting timeout to any number but without a connection:
</summary>


I get error: 

```
message: "Inaccessible host: `dynamodb.us-west-2.amazonaws.com'. This service may not be available in the `us-west-2' region.",
    code: 'UnknownEndpoint',
    region: 'us-west-2',
    hostname: 'dynamodb.us-west-2.amazonaws.com',
    retryable: true,
    originalError: Error: getaddrinfo ENOTFOUND dynamodb.us-west-2.amazonaws.com
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
    message: 'getaddrinfo ENOTFOUND dynamodb.us-west-2.amazonaws.com',
        errno: 'ENOTFOUND',
        code: 'NetworkingError',
        syscall: 'getaddrinfo',
        hostname: 'dynamodb.us-west-2.amazonaws.com',
        region: 'us-west-2',
        retryable: true,
        time: 2020-10-30T22:46:17.668Z
},
time: 2020-10-30T22:46:17.668Z
```
</details>


<details>

<summary>
Code used:
</summary>

```
const AWS = require('aws-sdk');

var dynamodb = new AWS.DynamoDB({region: 'us-west-2', apiVersion: '2012-08-10', logger: console, httpOptions: {timeout: 2}});

const params = {
    TableName: "xyz"
};

dynamodb.scan(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
```
</details>

I believe your findings are right, while the [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html) is generated code, I can fix the typescript comment and then make a request to match that comment in the API reference.

**Comment by ajredniwja** [comment]
I have made the changes in the repo, will get someone working on the API reference as well. 

Closing this issue now, please reach out if you have any other questions.
