### ISSUE TITLE
connect.getContactAttributes is not a function

### ISSUE THREAD

**Issue by sivac47123** [aws/aws-sdk-js#3508]
AWS APIs are updating constantly, you might be calling a new API with an older version is SDK. In
    this case you should try installing the newest `aws-sdk` like: 

    `npm install aws-sdk@latest`

    If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled
    SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
    You can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

If you still like to open an issue, change [ ] to [x] below:
- [x] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

Hi Team,

Am using aws-sdk-2.775.0.min.js for AWS.Connect()
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.775.0.min.js"></script>

Am getting the connectAPI.getContactAttributes is not a function.

    AWS.config.region = 'us-xxxx-1'; // Region
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx',
    });
    AWS.config.update({
      accessKeyId: "YOURKEY",
      secretAccessKey: "YOURSECRET"
    }); 

    const connectAPI = new AWS.Connect({apiVersion: '2017-08-08'});

    const params = {
      InitialContactId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      InstanceId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    };

    connectAPI.getContactAttributes(params, function (err, data) {
      if (err) console.log(err, err.stack); // an error occurred
      else console.log(data);           // successful response
    });

Appreciate your help.

**Comment by ajredniwja** [comment]
Hey @sivac47123 thanks for opening this the connect service is not a part of the default package. What you can do is, use the [SDK builder](https://sdk.amazonaws.com/builder/js/) and include all the services that you'd be using with Connect service included as well and that should solve the problem

Please reach out if you have any other questions.
