### ISSUE TITLE
SNS: Request could not be completed

### ISSUE THREAD

**Issue by randomhash** [aws/aws-sdk-js#3518]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution

**Describe the bug**
Random failures while publishing SNS event

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes, it is AWS lambda

**Details of the browser/Node.js version**
12 lambda

**SDK version number**
Lambda integrated. v2.712.0

**To Reproduce (observed behavior)**
```
sns.publish({
    TopicArn,
    Message: JSON.stringify(message)
  });
```

**Expected behavior**
Publish without problems

**Additional context**
```
InternalError: Request could not be completed
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

Request failing randomly, few times per day

**Comment by philipwigg** [comment]
Do you want to run this code synchronously? If so, pass in a callback and check for an error.

More likely you could run it async by try using a async/await instead?

**Comment by randomhash** [comment]
it is wrapped up into async function, more looks like a 

`
const sns = new SNS({region: 'us-east-1'});

export async function publish(params: PublishInput): Promise<PublishResponse> {
  return sns.publish(params).promise();
}

`

sorry for misdirection

**Comment by philipwigg** [comment]
Hard to tell but I suspect the error is caused because you need to `await` the call to ```sns.publish``` so that you always return a fulfilled promise.

**Comment by randomhash** [comment]
@philipwigg It is called on the publish function. Totally enough, I don't need to catch an error in scope of function wrapper for sdk. If it would be the case, 10k before fail would also failed

**Comment by ajredniwja** [comment]
@randomhash apologies for delayed response here, is there any pattern that you see because I am not able to reproduce it. 
The error itself is not helpful, is it possible for you to collect more logs to check if we can get something off it?

**Comment by randomhash** [comment]
Hello, there were no any pattern that can be traced. For the last month - no errors. I suspect aws infra problems that were solved, therefore issue can be closed. Thank you.

**Comment by Edweis** [comment]
I am having the same issue right now. I believe AWS SNS is having issues.
