### ISSUE TITLE
What is the initial value setting of NextToken in cloudformation.ListExports?

### ISSUE THREAD

**Issue by ANTGOMEZ** [aws/aws-sdk-js#3519]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**It is not clear here: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#listExports-property what the initial value of NextToken should be, should it be null or empty string?**

It is unclear what the initial value ought to be in: {NextToken: "???'} params object, should it be null or "", or...??

Thanks!

**Comment by ajredniwja** [comment]
Hey @ANTGOMEZ thanks for opening this issue. `NextToken` is an optional parameter, if you don't have a `NextToken` value you can make a call to `listExports` without any params or you can mark it as null. 

For example: 

Without params:
```
cloudformation.listExports( function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
```
OR

With params:
```
var params = {
    NextToken: null
};
cloudformation.listExports(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});

```

Closing this issue now, please reach out if you have any other questions.

**Comment by ANTGOMEZ** [comment]
Thank you for the quick reply Ajwinder.

I have a last question on this api call. Can this method be called in async form?

Like this: `await cf.listExports(params).promise();` ?
