### ISSUE TITLE
Pass on If-Modified-Since, when calling getObject

### ISSUE THREAD

**Issue by hbi99** [aws/aws-sdk-js#3521]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Is it possible to pass header-data, such as *If-Modified-Since* when calling **getObject**. Using the SDK, all is fine by passing **Bucket** and **Key** as params, though I'd like to execute the call by providing *If-Modified-Since* and get the result as described in the document below, I.E. status code 304, if the object has not been modified since provided date.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax

Apologies if I've missed information regarding this somewhere in the documentation.

Thanks in advance

**Comment by ajredniwja** [comment]
Hey @hbi99 Thanks for opening this issue, the information you are looking for is mentioned at: 
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#httpHeaders-event

I have put together an example for your use case:

```
var AWS = require('aws-sdk');

var s3 = new AWS.S3({region: 'us-west-2'});

var params = {
    Bucket: "bucketName",
    Key: "key"
};

var req = s3.getObject(params);

req.on('build', function() {
    req.httpRequest.headers['If-Modified-Since'] = 'Sun, 06 Nov 2019 08:49:37 GMT';
});

req.send(function(err, data) { console.log(data)});
```


Closing this issue now, please reach out if you have any additional questions.
