### ISSUE TITLE
CORS Issue using Chime Service

### ISSUE THREAD

**Issue by kuajia** [aws/aws-sdk-js#3522]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

I am using Amazon Chime Javascript SDK in order to create a basic Meeting.

Reffering to [Basic Tutorial](https://aws.github.io/amazon-chime-sdk-js/modules/gettingstarted.html)
I use the AWS SDK, getting the credentials from a custom web service which use Cognito Pool Identity. The User I create is Authorized to use all Chime services on all resources.

Once I try to create the Meeting using

```
AWS.config.update({

  region          : this.region                   ,
  accessKeyId     : this.credentials.accessKeyId  , 
  secretAccessKey : this.credentials.secretKey    ,
  sessionToken    : this.credentials.sessionToken
});

const chime     = new Chime   ({ 
  region: region
});
chime.endpoint  = new Endpoint('https://service.chime.aws.amazon.com');

await chime.createMeeting({
        ClientRequestToken: uuidv4(),     
        MediaRegion: this.region,
}).promise();
```

I got CORS error like

```
Access to XMLHttpRequest at 'https://service.chime.aws.amazon.com/meetings' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

Failed to load resource: net::ERR_FAILED

How can I avoid this kind of problem ? Is there something I am missing on AWS configuration side ?

**Comment by ajredniwja** [comment]
Hey @kuajia Thanks for opening this issue, CORS is not supported by Chime service as mentioned [here](https://github.com/aws/aws-sdk-js/blob/master/SERVICES.md). 

To work around CORS issues from JS SDK see https://github.com/aws/aws-sdk-js/issues/3465

However I believe this issue should be opened in https://github.com/aws/amazon-chime-sdk-js

Closing this issue, please reach out if you have any other questions.
