### ISSUE TITLE
Lazy load aws-sdk in Angular App

### ISSUE THREAD

**Issue by Zaky7** [aws/aws-sdk-js#3523]
Confirm by changing [ ] to [x] below:
- [✔️ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [✔️ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I am using aws sdk in my angular App. Since, I am only using S3 Service I have only included S3 in my code. 

```typescript
import { Component } from '@angular/core';
import * as S3 from 'aws-sdk/clients/s3';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'AwsSDKDemo';

  async clickButton() {
    await this.loadLibrary();
  }

  async loadLibrary() {
    const s3 = new S3({});
    console.log(s3);
  }
}
```

Recently I have checked my bundle it has very huge due to aws-sdk S3. I heard that we can lazy load the things in webpack. Therefore I tried to create a seperate chunk of aws-sdk  and lazy load it suppose for eg. on click of a button but it is not working as expected.

```typescript
 async loadLibrary() {
    const s3 = await import('aws-sdk/clients/s3')
    console.log(s3);
  }
```
I am getting entirely different object which not equivalent to the one returned by statically loaded syntax.
How can I dynamically load aws-sdk?

**Comment by ajredniwja** [comment]
Hey @Zaky7 Thanks for opening this issue, would you wanna try [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3) which is the modularized version of the SDK and has much lower bundle sizes.

**Comment by Zaky7** [comment]
@ajredniwja I give it a try thanks
