### ISSUE TITLE
 "Property 'on' does not exist on type" for type SelectObjectContentEventStream

### ISSUE THREAD

**Issue by matt-cree-instil** [aws/aws-sdk-js#3525]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I am following the documentation for the aws-js-sdk's `selectObjectContent` [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#selectObjectContent-property).

The type returned by this is SelectObjectContentOutput which has a Payload of type SelectObjectContentEventStream

I am using typescript in my project, and when I try to use the example from the documentation, I get the error `Property 'on' does not exist on type 'EventStream<{ Records?: RecordsEvent | undefined; Stats?: StatsEvent | undefined; Progress?: ProgressEvent | undefined; Cont?: ContinuationEvent | undefined; End?: EndEvent | undefined; }>'`

I can `fix` this by upcasting the Payload to a `ReadableStream`, but obviously I want to understand why the type definitions are wrong for this type.

![Screenshot 2020-11-10 at 13 20 36](https://user-images.githubusercontent.com/60224764/98679214-942c7300-2357-11eb-9733-d5bea61ff7c6.png)

Any help is appreciated. I'm assuming it boils down to using this union type here ```export type EventStream<Events> = StreamingEventStream<Events> | Events[];``` which is one of the parent types of SelectObjectContentEventStream.

**Comment by matt-cree-instil** [comment]
I think I might've answered my own question on the last line... god. Well, hopefully someone else finds this because it wasted a good hour of my time on Google -- lessons learned (read the types...).

**Comment by ajredniwja** [comment]
@matt-cree-instil Thanks for opening this and yess you are right, you can use union type there, I will close this issue now but it can still help someone in future.

**Comment by cyberwombat** [comment]
I really wish you had posted an answer... V3 gives a slightly different message so its very unclear to me what to do.

**Comment by cyberwombat** [comment]
Ok did my hour of searching. The examples on AWS don't work for V3. Here's how it works now:
```
const query =
    'Select s.InvoiceID, s.ProductCode, s.UsageQuantity, s.CurrencyCode, s.TotalCost from s3Object s limit 5'

  const input: SelectObjectContentCommandInput = {
    Bucket: 'myBucket',
    Key: ...,
    Expression: query,
    ExpressionType: 'SQL',
    ...    
  }

  const command = new SelectObjectContentCommand(input)
  const data = await client.send(command)

  const eventStream =  data.Payload! // Ideally check if undefined and handle that

  for await (const event of eventStream) {
    console.log(event.Records)
  }
  ...
```
Hope that helps someone
