### ISSUE TITLE
Inaccessible host: `execute-api.us-east-1.amazonaws.com'. This service may not be available in the `us-east-1' region.

### ISSUE THREAD

**Issue by ak-mcoderz** [aws/aws-sdk-js#3528]
Confirm by changing [ ] to [x] below:
- [ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Hi Team,

I'm trying to send data from the Lambda function(node.js) to connected clients using the WebSocket API gateway.

I am using the `sendMessage` method in the below code 

```js
const createWS = (domainName, stage) => {
  const endPoint = '${domainName}/${stage}';
  return new AWS.ApiGatewayManagementApi({
    apiVersion: '2018-11-29',
    endPoint
  });
};

const sendMessage = (domainName, stage, connectionId, message) => {
  const ws = createWS(domainName, stage);

  const postParams = {
    Data: JSON.stringify(message),
    ConnectionId: connectionId
  };
  return ws.postToConnection(postParams).promise();
};
```

**Comment by ajredniwja** [comment]
Hey @ak-mcoderz Thanks for opening this issue, I was not able to reproduce this, however it seems to be a DNS resolution error, I have seen this error reported a few times but was not related to the SDK for the most times, can you try something like mentioned in https://github.com/aws/aws-sdk-js/issues/528#issuecomment-404720666

**Comment by raja17king** [comment]
thank you
