### ISSUE TITLE
wait for cloudformation.deleteStack() to finish the deletion

### ISSUE THREAD

**Issue by adriantaut** [aws/aws-sdk-js#3530]
Hello, is there any way of waiting for stack deletion after calling the `cloudformation.deleteStack()` method?

```ts
  public async deleteStacks(stackNames: string[]): Promise<void> {
    try {
      for (let i in stackNames) {
        await this.cloudformation.deleteStack({ StackName: stackNames[i] }).promise();

        this.cloudformation.waitFor('stackDeleteComplete', { StackName: stackNames[i] }, function(err, data) {
          if (err) console.log(err, err.stack); // an error occurred
          else     console.log(data);           // successful response
        });
      }
    } catch (e) {
      console.error(e);
      process.exit(1);
    }
  }
```

I've tried several methods, but it looks the response from this call returns an AWS request which is always successful. However, I would like waiting for stack deletion to finish, so I can make sure there won't remain hanging stacks. 

Do you guys know any method of achieving this?

Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

**Comment by guysqr** [comment]
CloudFormation operations can take a long time to complete and you need to monitor the stack events to know what state your stack is in once you issue any stack creation or deletion operations. What you are after would require a long running process on the AWS side that could time out, so you are better off polling the APIs to check your stack's state until it stabilises to one of the end states DELETE_COMPLETE or DELETE_FAILED
