### ISSUE TITLE
Sporadic slow sendMessage calls to SQS via lambda

### ISSUE THREAD

**Issue by sean-daley** [aws/aws-sdk-js#3532]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
We've recently switched from using the Java SDK to the Javascript SDK when sending messages to SQS. Since we've done that, we've noticed that sometimes some of our requests are taking awhile to return. Not a huge amount, maybe 1 in every 1000 or so calls but it's noticeable in various aspects of our product.

We are a lambda based Node 10 project using aws-sdk 2.784.0. Here's an example of one of our logs:
```
@message | 2020-11-15T00:30:13.036Z-info : "Finished posting next message for run 5fb075bed23530000700a3cd and node sixxim in 11127(ms)"
```

So that finished in 11 seconds. The other 999 entries in this log (which spans 12 hours so it's not a lot per minute) all finished in about 50ms.

Our code to send messages is pretty simple:
```
const agent = new https.Agent({
  timeout: 5000,
})

export class SQSHelper {
  readonly sqs: SQS

  constructor(sqs?: SQS) {
    this.sqs =
      sqs ||
      new SQS({
        httpOptions: {
          timeout: 5000,
          connectTimeout: 3000,
          agent: agent,
        },
      })
  }

  public async postMessage(queue: string, message: string): Promise<SendMessageResult> {
    return new Promise((resolve, reject) => {
      this.sqs.sendMessage({ QueueUrl: queue, MessageBody: message }, (err, data) => {
        if (err) {
          reject(err)
        } else {
          resolve(data)
        }
      })
    })
  }
}

const sqsHelper = new SQSHelper()
export default sqsHelper
```

I guess what i'm hoping for info on is:
1) What could possibly cause this?
2) Is there anyway to add handling to our typescript code so that we can log what errors are causing the hangs?

I've found https://github.com/aws/aws-sdk-js/issues/2912 which allows us to see when we retried but I can't seem to find out why we retried.

Any help would be greatly appreciated. Thanks.

**Comment by celcoder** [comment]
We have a similar issue. Currently using aws-sdk: 2.302.0.

**Describe the question**
In our current environment, our lambda times out via default 6 sec.  Within the lambda we use 

`const sqsResponse = await sqs.sendMessage(params).promise();`

This operation very randomly takes longer than 6 sec before lambda times out.  

Due to the inconsistency and the rare occurrence of this happening we are not able to debug the issue properly.

Any help or feedback would be helpful.  Thank you.

**Comment by ajredniwja** [comment]
Hey @sean-daley @celcoder Thanks for reporting this, while the error is not reproducible on my end, I am trying to include people from SQS and Lamda teams to debug this further since I have seen this a error previously as well(https://github.com/aws/aws-sdk-js/issues/3391). 

Will keep you guys updated.

**Comment by mschfh** [comment]
We have a similar issue, increased latency (up to 4-5s) and sometimes timeouts (this could be related to sudden increases in concurrent requests), lambda isn't in a VPC.

I tried to find any documentation regarding the defaults for `connectTimeout` / `Timeout ` and MaxRetries, the only documented value is the default `timeout` of 120 seconds.

<br>

Could it be related to how node handles DNS lookups and the packet limit for Amazon DNS resolvers?
https://nodejs.org/api/dns.html#dns_implementation_considerations
> Because libuv's threadpool has a fixed size, it means that if for whatever reason any of these APIs takes a long time, other (seemingly unrelated) APIs that run in libuv's threadpool will experience degraded performance
<br>

Enabling keep-alive might help in that case:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html
<br>
`maxSockets` has a default value of 25 concurrent connections per service, could be necessary to increase it for some workloads?
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-maxsockets.html. 

<br>
If you have an Enterprise Support Subscription you could enable sdk-metrics to see if it provides any insights:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/metrics.html (if you set the environment variables, also add `AWS_CSM_CLIENT_ID` to distinguish multiple applications)

**Comment by ajredniwja** [comment]
@sean-daley @celcoder @mschfh 

Is it possible to get:

- RequestID
- Timestamp
- AccountID
- Queue Name
- Region Name

**Comment by sean-daley** [comment]
> @sean-daley @celcoder @mschfh
> 
> Is it possible to get:
> 
> * RequestID
> * Timestamp
> * AccountID
> * Queue Name
> * Region Name

I don't know if it's still happening to us. In our case, we set the connectTimeout to 2 seconds and the socketTimeout to 3 seconds and that pretty much hid the problem for our workload as the retry would kick in after those 3 seconds and then succeed on the second try. But because it was no longer impacting our workflow noticeably, I stopped paying attention. I just checked our Cloudwatch logs for the month of December though and did not find a single incident of this happening there. That encompassed probably about 40,000 sqs calls during that time.

**Comment by ajredniwja** [comment]
> > @sean-daley @celcoder @mschfh
> > Is it possible to get:
> > 
> > * RequestID
> > * Timestamp
> > * AccountID
> > * Queue Name
> > * Region Name
> 
> I don't know if it's still happening to us. In our case, we set the connectTimeout to 2 seconds and the socketTimeout to 3 seconds and that pretty much hid the problem for our workload as the retry would kick in after those 3 seconds and then succeed on the second try. But because it was no longer impacting our workflow noticeably, I stopped paying attention. I just checked our Cloudwatch logs for the month of December though and did not find a single incident of this happening there. That encompassed probably about 40,000 sqs calls during that time.

Thanks for your reply, I would wait for others for a reply before closing this issue.

**Comment by celcoder** [comment]
@ajredniwja 

It seems like this is still happening on our end.  We are not using custom options for SQS.  Everything is set to default. We are currently running the lambdas within VPC with subnets.

As per your request:
RequestID: ac092267-c67d-4c9b-9f1f-d5f920c50c39
Timestamp: 1607366453087
AccountID: 627596591329
Queue Name: prod-rewards-create-user
Region Name: us-east-1

**Comment by celcoder** [comment]
> > > @sean-daley @celcoder @mschfh
> > > Is it possible to get:
> > > 
> > > * RequestID
> > > * Timestamp
> > > * AccountID
> > > * Queue Name
> > > * Region Name
> > 
> > 
> > I don't know if it's still happening to us. In our case, we set the connectTimeout to 2 seconds and the socketTimeout to 3 seconds and that pretty much hid the problem for our workload as the retry would kick in after those 3 seconds and then succeed on the second try. But because it was no longer impacting our workflow noticeably, I stopped paying attention. I just checked our Cloudwatch logs for the month of December though and did not find a single incident of this happening there. That encompassed probably about 40,000 sqs calls during that time.
> 
> Thanks for your reply, I would wait for others for a reply before closing this issue.

@ajredniwja

It seems like this is still happening on our end. We are not using custom options for SQS. Everything is set to default. We are currently running the lambdas within VPC with subnets.

As per your request:
RequestID: ac092267-c67d-4c9b-9f1f-d5f920c50c39
Timestamp: 1607366453087
AccountID: 627596591329
Queue Name: prod-rewards-create-user
Region Name: us-east-1

Thanks for looking into this issue.

**Comment by ajredniwja** [comment]
I would close this issue now, could follow up with the SQS team if any one has any questions later.

**Comment by celcoder** [comment]
@ajredniwja 

Why is this issue being closed? I'm still seeing high latency with SQS sendmessage?

**Comment by ajredniwja** [comment]
@celcoder for some reason I missed the last comment, let me pass that information to the SQS team.

**Comment by ajredniwja** [comment]
From SQS team: 

```
SELECT raw
FROM timber_fe_debug_logs
WHERE RequestId::String = 'ac092267-c67d-4c9b-9f1f-d5f920c50c39'
  AND StartTime >= datetime('2020-12-07T18:40:00Z')
  AND StartTime <= datetime('2020-12-07T18:42:00Z');
  ```
  
  "Didn't get any result for that request id and timestamp."

Can you confirm that the request ID is correct? @celcoder

**Comment by celcoder** [comment]
> From SQS team:
> 
> ```
> SELECT raw
> FROM timber_fe_debug_logs
> WHERE RequestId::String = 'ac092267-c67d-4c9b-9f1f-d5f920c50c39'
>   AND StartTime >= datetime('2020-12-07T18:40:00Z')
>   AND StartTime <= datetime('2020-12-07T18:42:00Z');
> ```
> 
> "Didn't get any result for that request id and timestamp."
> 
> Can you confirm that the request ID is correct? @celcoder

Just for clarity the requestId you guys are referring is the cloudwatch log requestId?

**Comment by ajredniwja** [comment]
> @ajredniwja Just for clarity the requestId you guys are referring to is the cloudwatch log requestId?

@celcoder 
They needed request ID from SQS, when an operation is ran, they can also use `messageID` if you can share that.

**Comment by celcoder** [comment]
> > @ajredniwja Just for clarity the requestId you guys are referring to is the cloudwatch log requestId?
> 
> @celcoder
> They needed request ID from SQS, when an operation is ran, they can also use `messageID` if you can share that.

@ajredniwja correct me if I'm wrong but doesn't the requestId only comeback as a part of the response from sqs.sendMessage? In my case when I use await sqs.sendMessage().promise() it just hangs without a response.

**Comment by ajredniwja** [comment]
> Currently using aws-sdk: 2.302.0. Node version 12.

You are right with your last reply, I was still looking at just `sendMessage`, but I read the original post again, to start with can you update the SDK to the latest version?

**Comment by celcoder** [comment]
> > Currently using aws-sdk: 2.302.0. Node version 12.
> 
> You are right with your last reply, I was still looking at just `sendMessage`, but I read the original post again, to start with can you update the SDK to the latest version?

Okay, I will update the SDK to the latest version and will check if the problem still persists.

**Comment by celcoder** [comment]
@ajredniwja We've upgraded to the aws-sdk 2.816.0 and still seeing the same issue. = T

**Comment by ajredniwja** [comment]
That is weird, technically you should get a response once a promise is settled, I feel it maybe some race condition or a case of hitting some edge case where the credentials might be an issue, is there any other input I can get since I am not quite able to reproduce the behavior, or would you consider a workaround with retrying the request, if it takes longer?

**Comment by celcoder** [comment]
To give you additional context, lambdas currently live in a VPC in a private subnet, with API GATEWAY hooked up to it.  
Below is the code that's giving us issues:

`export async function sendToQueue(url, newUser, option) {
	try {
		const sqs = new SQS({
			apiVersion: '2012-11-05',
			region: 'us-east-1',
		});
		const params = {
			QueueUrl: url,
			MessageBody: JSON.stringify(newUser),
			MessageAttributes: option
		};

		const sqsResponse = await sqs.sendMessage(params).promise();
		return sqsResponse;
	} catch (error) {
		log.error(
			'Failed to send to create user queue',
			{ newUser, option },
			error
		);
		throw error;
	}
}


export const handler = async (event, context) => {
	context.callbackWaitsForEmptyEventLoop = false;

	if (event.source === 'serverless-plugin-warmup') {
		log.info(`WarmUp - ${process.env.STAGE} createUser Lambda is warm!`);
		/** Slightly delayed (25ms) response to ensure concurrent invocation */
		await new Promise(r => setTimeout(r, 25));
		return `${process.env.STAGE} createUser Lambda is warm!`;
	}

	log.info('Received create new user request', event);
	const request = JSON.parse(event.body);
         
        // JSON validation
	const { isValid, errors } = isValidRequest(createUserRequestSchema, request);
	if (!isValid) {
		log.warn('Invalid request', null, errors);
		return {
			statusCode: 400,
			headers: {
				'Access-Control-Allow-Origin': '*',
				'Access-Control-Allow-Credentials': true
			},
			body: JSON.stringify(
				`Invalid request: ${errors.dataPath} ${errors.message}`
			)
		};
	}

	try {
		log.info('New user request to be sent to SQS', event);
         
         	const sqsOption = {
	        	issuer: {
		        	DataType: 'String',
			        StringValue: request.referringPartner
		        }
	        };

		await sendToQueue(
			'https://url to our `queue',`
			request,
			sqsOption
		);

		log.info('New user successfully sent to SQS', event);

		return {
			statusCode: 201,
			headers: {
				'Access-Control-Allow-Origin': '*',
				'Access-Control-Allow-Credentials': true
			},
			body: JSON.stringify('New user event sent for processing')
		};
	} catch (error) {
		log.error('Failed to process new user event', event, error);
		return {
			statusCode: 500,
			headers: {
				'Access-Control-Allow-Origin': '*',
				'Access-Control-Allow-Credentials': true
			},
			body: JSON.stringify('Server Error - Please Try Again Later!')
		};
	}
};
`

We recently added httpOtipons, with timeout, connectTimeout, and maxRetries to see if would remedy our issues.  
Please advise as to what would be the best practice.

**Comment by celcoder** [comment]
To provide additional context our lambdas live in VPC in a private subnet, with API GATEWAY attached.

From what I can observe, it looks like the connection to the SQS is not being made or there's a connection delay that exceeds our lambda timeout.  For now, we made changes with these options:

`const sqs = new SQS({
			apiVersion: '2012-11-05',
			region: 'us-east-1',
			httpOptions: {
				timeout: 2000,
				connectTimeout: 2000,
				maxRetries: 2
			}
		});`

Please advise as to if the above settings will kick off retry?

**Comment by ajredniwja** [comment]
Yes, this should kick off the retry. You see it hanging intermittently right?

**Comment by drexler** [comment]
We previously had the issue occurring intermittently with version `2.31.0` of the SDK on inserts into SQS queues. On upgrading to `2.805.0`, the frequency of these errors dropped but it's back again.  @celcoder  did the `maxRetries` help at all?

**Comment by celcoder** [comment]
> We previously had the issue occurring intermittently with version `2.31.0` of the SDK on inserts into SQS queues. On upgrading to `2.805.0`, the frequency of these errors dropped but it's back again. @celcoder did the `maxRetries` help at all?

The maxRetries did alleviate most of our issues.  During the course of 2 + months, we only observed 2-3 requests being timed out with the retry.

**Comment by ajredniwja** [comment]
Is it possible to get some updates ? Did the solutions/workarounds mentioned solved the problem?

**Comment by anujsinghaniya** [comment]
We are seeing high latency with go sdk for sendmessage.

**Comment by betocode** [comment]
Still having this issue with nodejs and aws-sdk 2.830.0

**Comment by abhinavj13** [comment]
We are getting the same issue for version 2.1209.0

Kindly assist.

**Comment by mbutan** [comment]
We've been struggling with the same issues for the javascript "2.1249.0" version. Our lambda is running within VPC with subnets. What's more, I noticed a similar problem with pushing events to the Event Bridge service.

**Comment by mbutan** [comment]
Hey @ajredniwja could you reopen the ticket, sounds like the issue still happens to people.

**Comment by mbutan** [comment]
I could isolate the issue and turned out that XRay causes all the problems. Then I started searching for similar cases and found the following issue on GitHub. I've already made a bunch of tests and this comment below resolved all our problems. Maybe it will helpful for you.

https://github.com/aws/aws-xray-sdk-node/issues/476#issuecomment-1017522341
