### ISSUE TITLE
"InvalidToken: The provided token is malformed or otherwise invalid." when trying to upload objects to s3 bucket

### ISSUE THREAD

**Issue by anniestudent** [aws/aws-sdk-js#3534]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I provide credentials via service account for a fargate pod to access s3. I can upload objects to the bucket locally but when uploading object from the DEV pod, an error is returned from the sdk saying `InvalidToken: The provided token is malformed or otherwise invalid.` I am pretty sure that the sdk loaded the credentials successfully because another error saying missing credentials when I comment out the line in the deployment yaml which is used to specify the deployment service account.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the Node.js version**
v10.21.0

**SDK version number**
v2.794.0

I found this [issue](https://github.com/s3tools/s3cmd/issues/297) but I haven't touched anything named s3cmd. So I guess that's probably not the reason.

**Comment by ajredniwja** [comment]
Hey @anniestudent, thanks for opening this issue, I believe this is most likely client side error, how do you provide credentials? Can you share code to reproduce issue? 

The issue that you shared, is a Command line tool for managing Amazon S3 and CloudFront services. It has nothing to do with the JS SDK.

**Comment by irenakovalyova** [comment]
> @anniestudent

Hi,
I see it's been a while, but I'm having the same issue. Have you solved yours back then? What was causing it?
I would be very grateful for any clue :) Thanks!
