### ISSUE TITLE
node v15 s3.upload bug

### ISSUE THREAD

**Issue by meold** [aws/aws-sdk-js#3535]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
After upgrade to node v15.2.1 s3.upload stop working properly.  httpUploadProgress event doesn't fires after s3.upload.send() call. But sometimes (1 of 10 tries) all works correctly. We use the same 30Mb file for the tests.

All is ok with node v14.15.1.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v15.2.1

**SDK version number**
├── aws-sdk@2.794.0
└─┬ s3-upload-stream@1.0.7
  └── aws-sdk@2.794.0

**Comment by ajredniwja** [comment]
Hey @meold Thanks for opening the issue, I tried firing the event and it seems to work fine, can you please share your code? 

Code I used: 

```
var aws = require('aws-sdk');
var fs = require('fs');

const s3 = new aws.S3();

const params = {
    Bucket: 'xyz',
    Key: 'abcd',
    Body: fs.createReadStream('abc.mov') //1GB
};

var req = s3.upload(params);

req.on('httpUploadProgress', httpP =>{
    console.log("Loaded: " + httpP.loaded  + " Total: " + httpP.total)
});


req.send(function (err, data) {
    if (err) console.log(err);
    console.log(data);
});
```
```
node -v
v15.2.1
```
