### ISSUE TITLE
UnknownEndpoint: Inaccessible host  This service may not be available in the `ap-south-1' region.

### ISSUE THREAD

**Issue by jayanthrajpramuk** [aws/aws-sdk-js#3536]
Not able to upload files to S3 bucket 

 const S3 = new AWS.S3({
    accessKeyId: 'XX',
    secretAccessKey: 'XX',
    region: 'ap-south-1'
  });

Inaccessible host: `cbucketName.s3.ap-south-1.amazonaws.com'. This service may not be available in the `ap-south-1' region.

i have tried providing enpoints as part of config object as well . But it throws same error.

If i try the same uploading feature  using Angular code works correctly , but when i try using NodeJS it fails.
Am using same version in both environments. 2.771.0

I am behind Office proxy.

Regards,
Jayanth

**Comment by ajredniwja** [comment]
Hey @jayanthrajpramuk thanks for opening this issue, I was not able to reproduce this can you share your complete code and use case? and any additional details?

**Comment by jayanthrajpramuk** [comment]
Hello @ajredniwja , 
Thank you very much for the reply.

Background  : I am using Angular for FrontEnd and NodeJS as backend. We have upload all the file present the C://upload/file  to AWS. I have created a rest service which will be called by Angular 

I have tried using streams , using FileSync as well. It tries to give me the same Error. 


import AWS from "aws-sdk";
import fs from "fs";

function uploadToFileSystem() {

    const S3 = new AWS.S3({
    accessKeyId: 'XXX',
    secretAccessKey: 'XXX',
    region: 'ap-south-1'
  });

     fs.readFile(pathoffile,  function (err, data) {
     if (err) { throw err; }
    const params = {
         Bucket: 'customer-files-bucket', 
         Key: location, 
         Body: data // file 
          };
     S3.upload(params, function(err, data) {
         if (err) {
             console.log(err)
         } else {
             console.log("Successfully uploaded data to myBucket/myKey");
         }
      });
       });
}

**Comment by ajredniwja** [comment]
@jayanthrajpramuk I ran the exact same code with exact same region and was not able to reproduce the error.

Can you isolate the code and just run the code and see if its running fine to check there is no client side error?

can you also check for any DNS issues see https://github.com/aws/aws-sdk-js/issues/528
