### ISSUE TITLE
AWS.Credentials.expiryWindow is not a static property

### ISSUE THREAD

**Issue by unarist** [aws/aws-sdk-js#3546]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

[The documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html#expiryWindow-property) says `AWS.Credentials.expiryWindow` is static, and shows this code as a default value:

```
AWS.Credentials.expiryWindow = 15
```

However, it behaves like a non-static property.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.13.1

**SDK version number**
2.572.0

**To Reproduce (observed behavior)**

```
const AWS = require('aws-sdk');
console.log(AWS.Credentials.expiryWindow); // => undefined
console.log(new AWS.Credentials().expiryWindow); // => 15
AWS.Credentials.expiryWindow = 30;
console.log(new AWS.Credentials().expiryWindow); // => 15
```

**Expected behavior**

If the property is static, it should be like this:

```
const AWS = require('aws-sdk');
console.log(AWS.Credentials.expiryWindow); // => 15
console.log(new AWS.Credentials().expiryWindow); // => undefined or 15
AWS.Credentials.expiryWindow = 30;
console.log(new AWS.Credentials().expiryWindow); // => undefined or 30
```

... or the document should be fixed.

**Comment by ajredniwja** [comment]
Hey @unarist thanks for opening this issue, defined in https://github.com/aws/aws-sdk-js/blob/c175cb2b89576f01c08ebf39b232584e4fa2c0e0/lib/credentials.js
It suggests it should work with something like: 

```
const AWS = require('aws-sdk');
var credentials = new AWS.Credentials();

console.log(credentials.expiryWindow); // => 15

credentials.expiryWindow = 30;

console.log(credentials.expiryWindow);// => 30
```

Please share your on thought on what changes would you like in the documentation?

**Comment by unarist** [comment]
> Please share your on thought on what changes would you like in the documentation?

* It shouldn't be marked as **static**
![image](https://user-images.githubusercontent.com/705555/102742906-795b0e80-4399-11eb-83c4-a36d70067f6c.png)
* The code in `Default Value:` also confuses me, but I don't know how other non-static properties is described about default values.
