### ISSUE TITLE
Await on Request objects without promise conversion should throw

### ISSUE THREAD

**Issue by yuatpocketgems** [aws/aws-sdk-js#3547]
**Is your feature request related to a problem? Please describe.**
It's easy to forget calling promise() to get a promise object to be `await`ed. For example,
```javascript
await dynamodb.createTable(...)
```
executes with no errors in ES6, but table is not created until after the call finished.

**Describe the solution you'd like**
When the promise API is attached to the `Request` class, the Request class should also be converted to be a thenable, which always rejects on `await`, so that code like above would cause a runtime error.

It seems like adding
```javascript
this.prototype.then = (resolve, reject) => {
  throw new Error('Must call promise() to get a Promise object')
}
```
to line 782 of
https://github.com/aws/aws-sdk-js/blob/3e8a7bfafbcffd1ff026a9ee45f94553ebf851f4/lib/request.js#L778-L800
should suffice.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ajredniwja** [comment]
Hey @yuatpocketgems, thanks for opening this issue, this problem should have been addressed in [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3).

The [version 3.x](https://github.com/aws/aws-sdk-js-v3) of the AWS SDK for JavaScript is generally available. For more information see the [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/) or [API Reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html).

**Comment by yuatpocketgems** [comment]
That's great to know! Will see if we can migrate soon.
