### ISSUE TITLE
Resume upload after internet connection is interrupted using S3 JS SDK

### ISSUE THREAD

**Issue by projects-mindiii** [aws/aws-sdk-js#3549]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

I am trying to upload large files (usually greater than 5GB) using AWS S3 JS SDK via its multipart upload API. Files are getting successfully uploaded but I have one issue when the internet connection is lost, when the upload is in progress and when the connection resumes then the upload process halt and I have to re-upload the file from the beginning. Is there a way to automatically resume the upload process when the lost internet connection resumes? Below is the sample js code I am using for upload:
![qsq22](https://user-images.githubusercontent.com/57938391/100189636-af2fe300-2f12-11eb-956d-ae09986a01a4.png)

s3.upload({
    Key: filePath,
    Body: file,
    ACL: 'public-read'
}, options, function(err, data) {

    if(err) {`enter code here`
        // handle your error here
    }else{
        // handle successful upload action here
    }
}).on('httpUploadProgress', function (progress) {
    // Show upload progress bar / loader here
    var uploaded = parseInt((progress.loaded * 100) / progress.total);
});

**Comment by ajredniwja** [comment]
Hey @projects-mindiii, thanks for opening this issue, please look at https://github.com/aws/aws-sdk-js/issues/3071 as I did some research on the issue back then. 

One possible solution for this could be to bump up the `connectTimeout and maxRetries`
You can see how to change those in the issue I mentioned above and also in https://github.com/aws/aws-sdk-js/issues/3504#issuecomment-719836680

Please let us know if that doesn't solve the problem.
