### ISSUE TITLE
Cannot set property 2011-06-15 of #<Object> which has only a getter

### ISSUE THREAD

**Issue by misogihagi** [aws/aws-sdk-js#3555]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
***Uncaught TypeError: Cannot set property 2011-06-15 of #<Object> which has only a getter***
when  I tried 
`node dist-tools/browser-builder.js s3,ec2 > aws-sdk-s3-ec2.js
`

and saw this index.html,

```index.html
<!DOCTYPE html>
<html>
  <head>
    <script type="module">
    import AWS from './aws-sdk-s3-ec2.js'
    console.log(AWS)
</script>
  </body>
</html>

```
occurs:

>     aws-sdk-s3-ec2.js:54153 Uncaught TypeError: Cannot set property 2011-06-15 of #<Object> which has only a getter
>     at Object.115.../apis/ec2-2016-11-15.min (aws-sdk-s3-ec2.js:54153)
>     at o (aws-sdk-s3-ec2.js:4)
>     at r (aws-sdk-s3-ec2.js:4)
>     at aws-sdk-s3-ec2.js:4

**Is the issue in the browser/Node.js?**
Browser

**SDK version number**
v2.799.0

**Comment by ajredniwja** [comment]
Hey @misogihagi thanks for opening this issue and submitting a pull request: can you please address build failures for the PR.

**Comment by misogihagi** [comment]
Phew, fixed as test succeed. check it up!

**Comment by jcorteza** [comment]
Is there a resolution to this? I'm running into the same problem

**Comment by ctwomblyamzn** [comment]
Our package [amazon-connect-streams](https://github.com/amazon-connect/amazon-connect-streams) is affected by this bug. Can we please get some attention to this?

**Comment by ahmedyounis** [comment]
Our dev team is getting the same error when integrating https://github.com/amazon-connect/amazon-connect-streams into our angular project.

**Comment by ctunna** [comment]
Our team is also experiencing this issue.

**Comment by jonatandmapser** [comment]
any news about this?

**Comment by apdarshan** [comment]
Facing the same issue #https://github.com/amazon-connect/amazon-connect-streams/issues/577#issue-1286412028 

Currently blocked on it, any short-term fix for this ?

**Comment by SatoshiTomita** [comment]
It's not a pretty solution, but I solved the error by downloading the following [amazon-connect-streams release file](https://raw.githubusercontent.com/amazon-connect/amazon-connect-streams/master/release/connect-streams.js) and commenting out the code below.
`AWS.apiLoader.services['sts']['2011-06-15'] = require('../apis/sts-2011-06-15.min');`

I have not checked in detail, so there may be some impact.

**Comment by yenfryherrerafeliz** [comment]
Hi, we are currently investigating this, and we may come up with a solution as soon as possible. However, in the meantime you could do the following:
- Open the generated js file
- Search for:
 ```js
 AWS.apiLoader.services['sts']['2011-06-15'] = require('../apis/sts-2011-06-15.min');
 ```
- And then, replace the text above with:
```js
Object.defineProperty(AWS.apiLoader.services['sts'], '2011-06-15' , {
  value: require('../apis/sts-2011-06-15.min'),
  enumerable: false,
  configurable: true
});
```
That solution came from the following [PR](https://github.com/misogihagi/aws-sdk-js/commit/3ad53c098023505feb457b86142fb83e07414224), so thank you @misogihagi for it.

Thanks!
