### ISSUE TITLE
connect.createInstance returns success, but actually fails

### ISSUE THREAD

**Issue by Caoimhin89** [aws/aws-sdk-js#3557]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When I run the following code:
```
await connect.createInstance({
     InstanceAlias: 'my-connect-instance', 
     IdentityManagementType: 'CONNECT_MANAGED', 
     InboundCallsEnabled: true, 
     OutboundCallsEnabled: true}).promise();
```

I get back a response that looks like this:
```
{
    "Id": "fx5c4558-****-4742-n365-f817e7018752",
    "Arn": "arn:aws:connect:us-east-1:***********:instance/fx5c4558-****-4742-n365-f817e7018752"
}
```
So it seems like it has succeeded. However, when I open up the AWS Console and check the Connect dashboard, I see this:

`
Unknown |   | No telephony | Unknown | Create error
-- | -- | -- | -- | --

`

And if I run `await connect.listInstances().promise()` then I get back the following response:

```
{
    "InstanceSummaryList": [
        {
            "Id": "fx5c4558-****-4742-n365-f817e7018752",
            "Arn": "arn:aws:connect:us-east-1:************:instance/fx5c4558-****-4742-n365-f817e7018752",
            "IdentityManagementType": null,
            "InstanceAlias": null,
            "CreatedTime": null,
            "ServiceRole": null,
            "InstanceStatus": "CREATION_FAILED",
            "InboundCallsEnabled": null,
            "OutboundCallsEnabled": null
        }
    ]
}
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes, it is running in Lambda

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
node: v12.18.3

**SDK version number**
aws-sdk: v2.799.0

**To Reproduce (observed behavior)**
Code snippets above should do the trick.

**Expected behavior**
When I run connect.createInstance(), it should either a) actually create an instance, or b) return an error

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @Caoimhin89 thanks for opening this issue, the API you are using is in preview release. 
See https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Connect.html#createInstance-property

However, running the same operation on v2.801 results in success, 

I used the code that you provided and doing a `listInstances` my output is something like:

```
{ Id: '2e28d650-6de5-458f-bf4c-0c437dfc8c95',
       Arn:
        'arn:aws:connect:us-west-2::instance/2e28d650-6de5-45',
       IdentityManagementType: 'CONNECT_MANAGED',
       InstanceAlias: 'my-connect-instance271',
       CreatedTime: 2020-12-03T00:49:29.000Z,
       ServiceRole:
        'arn:aws:iam:::role/aws-service-role/connect.amazonaws.com/AWSServiceRoleForAmazonConnec',
       InstanceStatus: 'ACTIVE',
       InboundCallsEnabled: true,
       OutboundCallsEnabled: true }
```

Can you please update the version of your SDK using the instructions found [here](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html#nodejs-package-dependencies).

Closing this issue now, please reach out if you have any additional questions.

**Comment by Caoimhin89** [comment]
@ajredniwja Ah, I see. Thank you!!
