### ISSUE TITLE
Specify `SnsTopicArn` on FIFO SNS Topics on AWS Polly and other services

### ISSUE THREAD

**Issue by yura415** [aws/aws-sdk-js#3563]
**Is your feature request related to a problem? Please describe.**
Amazon introduced [SNS FIFO Topics in October 2020](https://aws.amazon.com/blogs/aws/introducing-amazon-sns-fifo-first-in-first-out-pub-sub-messaging/). As of today it's [still impossible](https://github.com/aws/aws-sdk-js/blob/5eed9f6e2868f685c5cdc9295fd6c0f471dc9913/apis/polly-2016-06-10.normal.json#L692) to subscribe on a FIFO Topic from other AWS Services like AWS Polly. Currently you get validation error:

```
1 validation error detected: Value 'arn:aws:sns:us-east-1:000000000000:sns-topic-name.fifo' at 'snsTopicArn' failed to satisfy constraint: Member must satisfy regular expression pattern: ^arn:aws(-(cn|iso(-b)?|us-gov))?:sns:[a-z0-9_-]{1,50}:\\d{12}:[a-zA-Z0-9_-]{1,256}$
```

**Describe the solution you'd like**
Expand RegExp validation on `SnsTopicArn` to allow for `.fifo` suffix.

**Describe alternatives you've considered**
As an alternative I could manually redirect SNS notifications from regular on FIFO topics using scripting.

**Comment by ajredniwja** [comment]
@yura415 thanks for opening this request, Will forward the request to the SNS team as the code is generated by them. Can update you once I hear back from the team.
