### ISSUE TITLE
AWS Cognito send invalid devicename in authevents

### ISSUE THREAD

**Issue by Fomin2402** [aws/aws-sdk-js#3564]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Bug description**
I used [CognitoIdentityServiceProvider.adminListUserAuthEvents](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminListUserAuthEvents-property) for getting user auth events but received an invalid result. I logged in from **Opera** but Cognito displays that I used **Chrome 8** (this is a mistake).

I could fix that if I get original `navigator.userAgent` (for example: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 OPR/72.0.3815.400`), but I only received data like that:

```json
 {
    "EventId": {EVENT_ID},
    "EventType": "SignIn",
    "CreationDate": {CREATION_DATE},
    "EventResponse": "Pass",
    "EventRisk": {
      "RiskDecision": "AccountTakeover",
      "RiskLevel": "Low",
      "CompromisedCredentialsDetected": false
    },
    "ChallengeResponses": [
      {
        "ChallengeName": "Password",
        "ChallengeResponse": "Success"
      }
    ],
    "EventContextData": {
      "IpAddress": {MY_IP_ADDR},
      "DeviceName": "Chrome 8, Linux",
      "City": {MY_CITY},
      "Country": {MY_COUNTRY}
    }
  }
```

I wouldn't like to make the crutch, to clarify this information, like creating `preauth` Cognito trigger which will log this information in another Table and handle this flow by myself.

Crutch for detection browser I found [here](https://stackoverflow.com/questions/5916900/how-can-you-detect-the-version-of-a-browser)

**Is the issue in the browser/Node.js?**
I got this data from `CognitoIdentityServiceProvider.adminListUserAuthEvents` in my Lambda function

**If on Node.js, are you running this on AWS Lambda?** 

Yes

**Details of the browser/Node.js version**
**local sh**:

```sh
node -v
v12.16.1
```
**serverless config**:

```yml
...
runtime: nodejs12.x
...
```

**SDK version number**

dependencies:

```sh
yarn list v1.22.10
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @aws-amplify/core@1.3.3
│  └─ aws-sdk@2.518.0
└─ aws-sdk@2.796.0
Done in 0.95s.
```

**To Reproduce (observed behavior)**

- create a login from **Opera** like `testUser`
- get `adminListUserAuthEvents` of its user
- you can see in the result, that instead of `Opera` `Chrome` is displayed

**Expected behavior**
I expect to get a valid name of the browser which the user uses for login, or getting the original `userAgent` field

**Screenshots**
none

**Additional context**
Duplicate this issue/bug on [stackoverflow](https://stackoverflow.com/questions/65133610/aws-cognito-send-invalid-devicename-in-authevents)

TT: V292264332

**Comment by uncodable** [comment]
Opera is based on Chromium, this could be why.

**Comment by Fomin2402** [comment]
@uncodable 
> Opera is based on Chromium, this could be why.

I know that, but there are [some hacks](https://stackoverflow.com/questions/5916900/how-can-you-detect-the-version-of-a-browser) on how to avoid this mistake

For example, my `userAgent` from **Opera** on **Ubuntu**:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 OPR/72.0.3815.400`

So, this string includes `OPR/72.0.3815.400` for detecting that this is the **Opera**.

So, **what I want?**:
I want to get the **correct** name of the browser.

For example, I see some ways to solve this problem:

 - AWS will add **original** `userAgent` field to the answer from  [CognitoIdentityServiceProvider.adminListUserAuthEvents](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminListUserAuthEvents-property)
- AWS will update his method of browser detecting

**Comment by ajredniwja** [comment]
Thanks for opening this issue, this does seem to be a Cognito issue and not SDK, let me forward a request to them, will update the issue once I have a response from the team.

**Comment by ajredniwja** [comment]
Soft update: The Cognito team has acknowledged the issue, they are working on the fix, while there is not a fixed ETA on it, it should be in January.

**Comment by Fomin2402** [comment]
@ajredniwja 
any news?

**Comment by ajredniwja** [comment]
A fix was pushed, it should be seen implicated across all the regions in a couple fo days. @Fomin2402

**Comment by Fomin2402** [comment]
@ajredniwja Great!
Seems like smth is updated.
I took a short look and see that at UI base features look good
![image](https://user-images.githubusercontent.com/37749241/107651714-e18aea00-6c90-11eb-9112-3876c4199efe.png)
