### ISSUE TITLE
Will we see PartiQL in dynamoDB getItem?

### ISSUE THREAD

**Issue by QAnders** [aws/aws-sdk-js#3565]
Query'ing data from DynamoDB cam be a challenge and the new PartiQL console in AWS Console is great and it is so easy to find data.

Would we ever see PartiQL as an option in the SDK to be able to "get"/"set" data using PartiQL from the SDK?

**Comment by ajredniwja** [comment]
@QAnders Thanks for opening this issue, can forward the request to DynamoDB team.

**Comment by QAnders** [comment]
Any update on this?

**Comment by ajredniwja** [comment]
https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#27980

Seems like it was implemented, I will close this issue now. 

Please reach out if you have any other questions.
