### ISSUE TITLE
_awsSdk.default.CognitoIdentityServiceProvider is not a constructor

### ISSUE THREAD

**Issue by steelx** [aws/aws-sdk-js#3567]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
TypeError: _awsSdk.default.CognitoIdentityServiceProvider is not a constructor

**Is the issue in the browser/Node.js?**
Issue only during `jest test`. works fine if open in browser.

**If on Node.js, are you running this on AWS Lambda?**
No. Running with next-js `"next": "latest"`

**Details of the browser/Node.js version**
`node -v` v14.15.0

**SDK version number**
2.701.0

**Screenshots**
![image](https://user-images.githubusercontent.com/3184210/101453290-2030bb00-3955-11eb-9170-07f21b1daa8a.png)

**CODE**
```
import AWS from "aws-sdk";
const REGION = "eu-west-1";
AWS.config.update({ region: REGION });

console.log(AWS.VERSION);//2.701.0
const cognitoIdentityServiceProvider = new AWS.CognitoIdentityServiceProvider();
```

error:
```
TypeError: _awsSdk.default.CognitoIdentityServiceProvider is not a constructor
```

This used to work, but suddenly stopped working now.

**Comment by steelx** [comment]
issue was with jest

**Comment by ajredniwja** [comment]
@steelx thanks for opening this, but I am not able to reproduce this with the latest version of the SDK. 

Can you explain your use case a but more?

**Comment by ajredniwja** [comment]
Ignore the last comment, Im glad you were able to resolve your issue. Please reach out if you have any other questions.
