### ISSUE TITLE
Unable to use createApiKey

### ISSUE THREAD

**Issue by rubfergor** [aws/aws-sdk-js#3571]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
ApiGateway throws a signature validation on its requests

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
v15.3.0

**SDK version number**
2.805.0

**To Reproduce (observed behavior)**
I create an endpoint that calls the following function with a valid API Gateway endpoint (https://XXXX.execute-api.us-east-1.amazonaws.com/dev or without the stage) as the endpoint parameter.
```
export const createApiKey = async (endpoint: string) => {
  const apiGateway = new APIGateway({endpoint});
  return apiGateway.createApiKey().promise();
};
```
The endpoint throws the error:
```
{
        "message": "Credential should be scoped to correct service: 'execute-api'. ",
        "code": "InvalidSignatureException",
        "time": "2020-12-08T20:17:55.833Z",
        "requestId": "2f42a058-228f-4a9e-b91c-5c73d4aa86ee",
        "statusCode": 403,
        "retryable": false,
        "retryDelay": 77.55772691763818
    }
```
The lambda has full IAM permissions

**Expected behavior**
It should create an API Key (or at least complains about missing parameters for the creation, however I tried also with parameters as described in the docs with the same result).

**Comment by ajredniwja** [comment]
Hey @rubfergor thanks for opening this and apologies for delayed response, while I was not really able to reproduce this, can you check out this post which has much more information on it:
https://forums.aws.amazon.com/thread.jspa?threadID=220648&tstart=0

**Comment by rubfergor** [comment]
Thanks! I haven't tried, but I decided to go with another route instead of API Gateway keys. Thanks anyway!
