### ISSUE TITLE
SecretsManager ListSecrets does not work via JS when applying Filter (0 results returned)

### ISSUE THREAD

**Issue by mrowles** [aws/aws-sdk-js#3572]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Providing a `Filters` param for `ListSecretsRequest` when using SecretsManager SDK does _not_ work.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.x

**SDK version number**
v2.807.0

**To Reproduce (observed behavior)**
```
import { SecretName } from './secret-name';
import { AWSError, SecretsManager } from 'aws-sdk';
import {
  FiltersListType,
  ListSecretsRequest,
  ListSecretsResponse,
  SecretListEntry,
} from 'aws-sdk/clients/secretsmanager';
import { PromiseResult } from 'aws-sdk/lib/request';

const options: ClientConfiguration = {
  region: `${AWS_REGION}`,
  credentials: {
    accessKeyId: `${AWS_ACCESS_KEY_ID}`,
    secretAccessKey: `${AWS_SECRET_ACCESS_KEY}`,
  },
  apiVersion: '2017-10-17',
};
const secretsManager: SecretsManager = new SecretsManager(options);

...

const listSecretsRequestFilter: FiltersListType = [{
    // 'name' is correct according to the types. I have also tried 'Name', 'secretName', 'SecretName'
    // I have additionally tried 'tag-key' and provided correct values, to no avail
    Key: 'name',
    Values: [`/${APP_NAME}/${BRANCH_NAME}`],
}];
const listSecretsRequest: ListSecretsRequest = {
    Filters: listSecretsRequestFilter,
};
let listSecretsResponse: PromiseResult<
    ListSecretsResponse,
    AWSError
    > = await secretsManager.listSecrets(listSecretsRequest).promise();

let existingSecrets: SecretListEntry[] = [];
if (listSecretsResponse.SecretList) {
    existingSecrets = [...existingSecrets, ...listSecretsResponse.SecretList];
}
while (listSecretsResponse.NextToken !== undefined) {
    console.log('Checking the next page...');

    listSecretsResponse = await secretsManager
        .listSecrets({
            ...listSecretsRequest,
            NextToken: listSecretsResponse.NextToken,
        })
        .promise();

    if (listSecretsResponse.SecretList) {
        existingSecrets = [
            ...existingSecrets,
            ...listSecretsResponse.SecretList,
        ];
    }
}

console.log(
    `${existingSecrets.length} existing secrets found matching the filter`,
);
```

This returns zero secrets.

**Expected behavior**
The list is filtered with the params I provide it, as it does when using the CLI (See **Additional Context**). 

Everything works in the function including creating and updating secrets, so the SecretsManager API and the integration is working fine, it's literally just the filter function through AWS SDK JS which fails.

**Screenshots**
N/A

**Additional context**
The CLI works with a range of the values I have tried:

```
// works
aws secretsmanager list-secrets --filter '[{"Key": "name", "Values": ["/some-stack/prod/"]}]'

// works
aws secretsmanager list-secrets --filter '[{"Key": "tag-key", "Values": ["/some-stack/prod/"]}]'

// works
aws secretsmanager list-secrets --filter '[{"Key": "name", "Values": ["/some-stack/prod/specific-key"]}]'
```

**Comment by mrowles** [comment]
As a fix for now, I am manually filtering...this does not scale and I hope this gets fixed soon 👍

```

// as above

let listSecretsResponse: PromiseResult<
    ListSecretsResponse,
    AWSError
    > = await secretsManager.listSecrets().promise();

let existingSecrets: SecretListEntry[] = [];
if (listSecretsResponse.SecretList) {
    existingSecrets = [
        ...existingSecrets,
        ...listSecretsResponse.SecretList.filter((secret: SecretListEntry) =>
            secret?.Name?.includes(`/${APP_NAME}/${BRANCH_NAME}/`),
        ),
    ];
}
while (listSecretsResponse.NextToken !== undefined) {
    console.log('Checking the next page...');

    listSecretsResponse = await secretsManager
        .listSecrets({
            NextToken: listSecretsResponse.NextToken,
        })
        .promise();

    if (listSecretsResponse.SecretList) {
        existingSecrets = [
            ...existingSecrets,
            ...listSecretsResponse.SecretList.filter((secret: SecretListEntry) =>
                secret?.Name?.includes(`/${APP_NAME}/${BRANCH_NAME}/`),
            ),
        ];
    }
}

console.log(
    `${existingSecrets.length} existing secrets found matching the filter`,
);
```

**Comment by ajredniwja** [comment]
Hey @mrowles thanks for opening this issue, I wrote a simple code to test this out and seems to be that the `Filters` param is working as expected. 

Scenario: I have two secretes named `abc` and `xyz`

Code I used: 

```JavaScript
var params = {
    Filters: [
      {
        Key: "name",
        Values: [
          'x',
        ],
      }
    ],
  };

  client.listSecrets(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
  });
```

Output:
```
 { SecretList:
   [ { ARN:
        'arn:aws:secretsmanager:us-west-abc',
       Name: 'xyz',
       LastChangedDate: 2020-12-19T01:00:35.685Z,
       Tags: [],
       SecretVersionsToStages: [Object],
       CreatedDate: 2020-12-19T01:00:35.629Z } ] }
```


Would you be able to quickly run a quick test like this?

**Comment by mrowles** [comment]
Thanks :) It's essentially the same code though, and I totally believe that it works for you, so I'm wondering if it's something like the slashes? Their examples suggest to namespace using them, but maybe we have to escape them or something? Or we can use wildcards, I don't know.

**Comment by ajredniwja** [comment]
> Thanks :) It's essentially the same code though, and I totally believe that it works for you, so I'm wondering if it's something like the slashes? Their examples suggest to namespace using them, but maybe we have to escape them or something? Or we can use wildcards, I don't know.

Thanks for the response there, It should be the same code but just wanted run tests with simpler code. Anyway, I did run something with `params` as:

```
var params = {
    Filters: [
      {
        Key: "name",
        Values: [
          '/some-stack/prod/a',
        ],
      }
    ],
  };
  ```
  
  I get: 
  
  ```
{ SecretList:
   [ { ARN:
        'arn:aws:secretsmanager:us-west-2:021102071791:secret:/some-stack/prod/alksflsk',
       Name: '/some-stack/prod/abc',
       LastChangedDate: 2020-12-21T22:04:25.769Z,
       Tags: [],
       SecretVersionsToStages: [Object],
       CreatedDate: 2020-12-21T22:04:25.716Z } ] }
  ```
  
  
  That is when I stored secrets named:
  `/some-stack/prod/abc`
  `/some-stack/prod/xyz`
  
  When I just use the value `/some-stack/prod/` in params I do get both the secrets. 
  
  Are you sure you are on the latest version of the SDK?
