### ISSUE TITLE
CredentialProviderChain swallows errors in an inconvenient way

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-sdk-js#3573]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution

  
**Describe the bug**
The way the `CredentialProviderChain` works today, it treats all errors the same and proceeds to the next provider in the chain. This seems nice in theory, but is unhelpful in practice because it leads to swallowing errors that could be actionable.

For example, if a `CredentialProviderChain` is configured like this:

```ts
return new AWS.CredentialProviderChain([
    () => new AWS.SharedIniFileCredentials({ profile }),
    () => new AWS.ProcessCredentials({ profile }),
]);
```

And my profile looks like this:

```
[profile myProfile]
role_arn=arn:aws:iam::111111111111:role/someRole
source_profile=otherProfile
```

But let's say I've misconfigured my `otherProfile` and the `AssumeRole` call fails for some reason. The error I get from this is:

```
ProcessCredentialsProviderFailure: Profile myProfile did not include credential process
```

Bottom line: I *clearly* intended to do `AssumeRole` credentials. Instead of  telling me something was wrong with the assume role call though, the `CredentialProviderChain` happily swallows that error and continues down the chain, finally ending with an error that completely does not apply to me, saying that this particular profile section was not set up with a `credential_process` clause.

So the error that would have been useful to me is swallowed and replaced with an error that is completely useless.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.12.0

**SDK version number**
2.804.0

**To Reproduce (observed behavior)**
Reproduction steps included above.

**Expected behavior**
I would expect the `CredentialProviderChain` to make a distinction between "this provider has no work to do" and "this provider did work but it failed".

**Comment by ajredniwja** [comment]
Hey @rix0rrr, thanks for opening this issue and apologies for delayed response, yes you are right and it is frustrating. This should be fixed in https://github.com/aws/aws-sdk-js-v3

While this is frustrating, I believe this is not necessarily a bug with the SDK but a feature request, what do you think?

**Comment by rix0rrr** [comment]
It's a tough call. I would argue the current behavior is unexpected and undesirable, so I would classify it as a bug.

But ultimately the call on how to classify this yours.
