### ISSUE TITLE
Setting AWS SDK credentials in Node

### ISSUE THREAD

**Issue by ravishrawal** [aws/aws-sdk-js#3574]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I am having trouble setting the aws credentials for a react app that needs the aws sdk for s3 uploads & . I have set up my credentials file in the '~/.aws/credentials' path, and I know this file path & file is setup okay. However, I don't know how to go about this in my jsx file. My understanding was that the SDK checks this credentials file on its own, however on logging config, I see credentials are null.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v14.15.1

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
/Users/ravishrawal
└── (empty)
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
2.807.0
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
process.env.AWS_SDK_LOAD_CONFIG = true; 
var AWS = require("aws-sdk");
const s3 = new AWS.S3({})
		var params = {
		  Body: e.target[0].files[0], 
		  Bucket: "rav-viren-photos", 
		  Key: "test.jpg"
		 };
		s3.putObject(params, (err, data)=> {
					if(err) console.log(err, err.stack)
					else console.log(data)
					}
			)

**Expected behavior**
CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

**Screenshots**
![image](https://user-images.githubusercontent.com/26351259/101962462-3bf8c300-3bda-11eb-9f58-110c8f6eabb0.png)
![image](https://user-images.githubusercontent.com/26351259/101962633-ac9fdf80-3bda-11eb-84c6-090c69bb40df.png)

**Additional context**

**Comment by ajredniwja** [comment]
Hi @ravishrawal, thanks for opening this issue, can you be sure that there are credentials present in the file? 

You can quickly install AWS CLI using https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html

Then run `aws configure` and enter the information. 

Also if you could share your use case that can help me further. 

In general `SharedIniFIleCredentials` are not supported in browser environment. 

To get started with React see this tutorial: 
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/getting-started-react-native.html
