### ISSUE TITLE
[Polly] startSpeechSynthesisTask: allow to await task

### ISSUE THREAD

**Issue by BjoernRave** [aws/aws-sdk-js#3576]
I would like to await the synthesis task, so I can act on the generated audio after creation in the same call and I don't need another function listening on the creation.

**Comment by ajredniwja** [comment]
Hey @BjoernRave, thanks for opening this issue, is it possible for you to use the feature request template? 
https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=feature-request&template=---feature-request.md&title=
