### ISSUE TITLE
Partial data loss when the read stream is paused for too long

### ISSUE THREAD

**Issue by GeorgianStan** [aws/aws-sdk-js#3577]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Pausing the read stream and then resuming after a while will lead to partial data loss

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v14.15.1

**SDK version number**
v2.809.0

**To Reproduce (observed behavior)**
```
const AWS = require("aws-sdk");
const fs = require("fs");

const s3Client = new AWS.S3({
  endpoint: "",
  secretAccessKey: "",
  accessKeyId: "",
});
const Bucket = "";

const writeStream = fs.createWriteStream(`image.jpg`);
const readStream = s3Client
  .getObject({
    Bucket,
    Key: "image.jpg",
  })
  .createReadStream();

readStream.pipe(writeStream);

setTimeout(() => {
  readStream.unpipe(writeStream);
  readStream.pause();
}, 2000);

setTimeout(() => {
  readStream.pipe(writeStream);
  readStream.resume();
}, 35000);
```

**Expected behavior**
I would expect to download the entire object without any data loss.
If the time frame between pause() and resume() is short, then the file is downloaded correctly

**Screenshots**
-

**Additional context**
-

**Comment by ajredniwja** [comment]
Hey @GeorgianStan, thanks for opening this issue, I was not quite able to reproduce this, can you please share what your use case is so I can help you further? 

Also how do you verify that there has been a data loss?

**Comment by GeorgianStan** [comment]
Hi @ajredniwja the problem was at my end. The behavior was that the image was partially dowloaded. From ~14MB it would get only ~7MB. This value was always different at each execution.
I think that the problem was with my previous USB WiFi adapter. Now I changed it with a new one and same as you I'm not able to reproduce the problem anymore.

Thank you for your help and sorry for this false positive bug.
