### ISSUE TITLE
Inconsistent GSI query result between DynamoDB query and DynamoDB DocumentClient with pagination

### ISSUE THREAD

**Issue by JustinLiang90** [aws/aws-sdk-js#3578]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
- Get **duplicate results** when using `DocumentClient` to query Dynamodb base on GSI and pagination, and **confirmed there are no duplicates in the database**. However, no issue when using `AWS.DynamoDB` directly. 
- Here is the example code by using `DocumentClient`: 
```js
const dynamoDB = new AWS.DynamoDB({region: "us-east-1", credentials})
const ddbDocClient = new AWS.DynamoDB.DocumentClient({maxRetries: 3, service: dynamoDB})
const params = {
    ExpressionAttributeValues: { ":status": `${status}` },
    IndexName: "statusGSI",
    KeyConditionExpression: "status = :status",
    Limit: 9,
    TableName: tableName
}

let result
do {
  result = await ddbDocClient.query(params).promise()
  if (result.Items && result.Items.length) {
    for (const item of result.Items) {
      console.log("entryID", item["id"])
    }
  }
  console.log(result.LastEvaluatedKey)
  params.ExclusiveStartKey = result.LastEvaluatedKey
} while (result.LastEvaluatedKey)
```
- Here is the output base on the above code, as you can see, sometimes, **the LastEvaluatedKey/ExclusiveStartKey appears in the first item of the next batch**. 
It's quite often if specify the limit in the query request, and won't that often without limit as only start pagination if data exceeds 1MB, but the problem still exists.
```js
...
entryID a6081646-5e55-40b5-adb6-f66170ce6b86
entryID af4615c2-c095-4db8-b52e-368929de5eeb
entryID 3ccf6a6b-1c4e-4604-abe2-e41e2064c9c8 <--- here
{
  id: '3ccf6a6b-1c4e-4604-abe2-e41e2064c9c8',
  status: 'XXX'
}
entryID 3ccf6a6b-1c4e-4604-abe2-e41e2064c9c8 <---- here
entryID 4cae5df4-f4d1-42d6-87ec-f278da3e7454
...

entryID 8d22d8d4-c5e6-41e7-9934-f93de968ef6d
entryID 3c1fd642-b03a-4051-9002-b3ffabab224a
{
  id: '3c1fd642-b03a-4051-9002-b3ffabab224a',
  status: 'XXX'
}
entryID d684967c-a0be-4080-b51b-83f0a5cd2f40
...
```
- Here is the example code base just use `AWS.DynamoDB` and **no issue**.
```js
const dynamoDB = new AWS.DynamoDB({region: "us-east-1", credentials})
const params = {
    ExpressionAttributeValues: { ":status":  { S: `${status}` } },
    IndexName: "statusGSI",
    KeyConditionExpression: "status = :status",
    Limit: 9,
    TableName: tableName
}

let result
do {
  result = await dynamoDB.query(params).promise()
  if (result.Items && result.Items.length) {
    for (const item of result.Items) {
      const data = AWS.DynamoDB.Converter.unmarshall(item)
      console.log("entryID", data["id"])
    }
  }
  console.log(result.LastEvaluatedKey)
  params.ExclusiveStartKey = result.LastEvaluatedKey
} while (result.LastEvaluatedKey)
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes, and tested on the local machine. (same as running on AWS Lambda)

**Details of the browser/Node.js version**
v12.13.0

**SDK version number**
v2.809.0

**To Reproduce (observed behavior)**
- Prepare a large number of data that needs pagination to get all results.
- Query data by GSI and use `DocumentClient`.
- Refer to the sample code provided in the **Describe the bug** section.

**Expected behavior**
Should no duplicates data between the last item in the first batch and the first item in the next batch.

**Comment by ajredniwja** [comment]
Hey @JustinLiang90, Thanks for opening this issue and apologies for late reply, I agree with your analysis however I was not able to reproduce the issue. Do you see any pattern or anything?

**Comment by JustinLiang90** [comment]
Hey @ajredniwja, I also created an AWS support ticket on it and recorded a video. Unfortunately, I didn't notice some pattern, it happened really randomly.

**Comment by ajredniwja** [comment]
@JustinLiang90, I am aware of the ticket, I replied to the ticket with the same today, it becomes very difficult for us to debug the issue if we can not reproduce it, however I was not able to access the video so I have asked the owners of the ticket to provide me with that video. If needed we'll add dynamoDB team for extensive investigation.

**Comment by trivikr** [comment]
Verified that the DynamoDB DocumentClient just translates JavaScript object to DynamoDB record (aka marshalling) and vice versa (aka unmarshalling).
* The internal code which sends the request https://github.com/aws/aws-sdk-js/blob/140740509d70c45099daf1b1c6c34ab6633b4a09/lib/dynamodb/document_client.js#L98-L107
* The function `setupRequest` which performs translation for input https://github.com/aws/aws-sdk-js/blob/140740509d70c45099daf1b1c6c34ab6633b4a09/lib/dynamodb/document_client.js#L523-L532
* The function `setupResponse` which performs translation for output https://github.com/aws/aws-sdk-js/blob/140740509d70c45099daf1b1c6c34ab6633b4a09/lib/dynamodb/document_client.js#L537-L576

On quick look, if duplicate data is being returned it should be returned by the DynamoDB service and not added by DocumentClient.

**Comment by trivikr** [comment]
For DynamoDB DocumentClient to return duplicate results, it should preserve data from previous request somehow while returning results for new request - which doesn't seem to be the case from the internal code.

```js
do {
  result = await ddbDocClient.query(params).promise() // <-- New request is created here.
  if (result.Items && result.Items.length) {
    for (const item of result.Items) {
      console.log("entryID", item["id"])
    }
  }
  console.log(result.LastEvaluatedKey)
  params.ExclusiveStartKey = result.LastEvaluatedKey // <-- ExclusiveStartKey updated in params for new request in the next loop iteration.
} while (result.LastEvaluatedKey)
```

Is there a pattern in DynamoDB DocumentClient output which is not seen in DynamoDB output? For example:
* Is only one duplicate item being returned between pages? As per the issue description, that seems to be the case.
* Are there any specific number of pages after which duplicate items start appearing? Is this number reproducible in subsequent runs.
* Do number of duplicate items being returned increase/decrease? As per issue description, once duplicated every subsequent page has duplicate items?

**Comment by Shadowstep33** [comment]
I'm also having this happen. Can't tell the pattern but it seems to be related to using GSI. My first query looks like this:

```
{
    "TableName": "...",
    "Limit": 15,
    "ExpressionAttributeNames": {
        "#STATUS": "status",
        "#ADOPTORFOSTER": "adoptOrFoster",
        "#ISINCONTRACT": "isInContract"
    },
    "ExpressionAttributeValues": {
        ":status": {
            "S": "APPROVED"
        },
        ":adoptOrFoster": {
            "S": "ADOPT"
        },
        ":isInContractneq": {
            "BOOL": true
        }
    },
    "FilterExpression": "#STATUS = :status and #ADOPTORFOSTER = :adoptOrFoster and #ISINCONTRACT <> :isInContractneq",
    "IndexName": "status-index"
}
```

and my second query is this:

```
{
    "TableName": "..",
    "Limit": 15,
    "ExpressionAttributeNames": {
        "#STATUS": "status",
        "#ADOPTORFOSTER": "adoptOrFoster",
        "#ISINCONTRACT": "isInContract"
    },
    "ExpressionAttributeValues": {
        ":status": {
            "S": "APPROVED"
        },
        ":adoptOrFoster": {
            "S": "ADOPT"
        },
        ":isInContractneq": {
            "BOOL": true
        }
    },
    "FilterExpression": "#STATUS = :status and #ADOPTORFOSTER = :adoptOrFoster and #ISINCONTRACT <> :isInContractneq",
    "ExclusiveStartKey": {
        "uuid": {
            "S": "3cb37260-38fc-47a0-88c0-c3970526a8db"
        }
    }
}
```

so what I can observe is the 2nd query doesn't use the Index. Additionally, no new data was actually returned in the second call so it makes me think the ExclusiveStartKey has become irrelevant due to the index not being used.
