### ISSUE TITLE
Method not implemented : ssoadmin.describeInstanceAccessControlAttributeConfiguration is not a function

### ISSUE THREAD

**Issue by rocket-power** [aws/aws-sdk-js#3579]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The function `describeInstanceAccessControlAttributeConfiguration` as documented at https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SSOAdmin.html#describeInstanceAccessControlAttributeConfiguration-property returns describeInstanceAccessControlAttributeConfiguration is not a function error.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
I am running on AWS Lambda - Node 12.x

**SDK version number**
v2.771.0

**To Reproduce (observed behavior)**
Follow the code example in the documentation.

```
var params = {
  InstanceArn: 'STRING_VALUE' /* required */
};
ssoadmin.describeInstanceAccessControlAttributeConfiguration(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

**Expected behavior**
Function to return as per documentation

I have been through the SDK code and I can see the method definition in ssoadmin.d.ts but I am unable to find any implementation.

**Comment by ajredniwja** [comment]
If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). You can import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

**Comment by rocket-power** [comment]
Hi, I’m using the version of the SDK that comes installed with Lambda using Node 12.x. I downloaded the AWS JavaScript SDK and searched for the missing function but I can’t find it in the source code. Are you 100% sure it’s there and available before closing the issue as I really can’t see it.

________________________________
