### ISSUE TITLE
ExpiredToken is retryable, but should not be

### ISSUE THREAD

**Issue by pwrmiller** [aws/aws-sdk-js#3581]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Using expired tokens results in retries. I've seen long runtimes of `sts.getCallerIdentity`, for example, retrying with an expired credential. 

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No. 

**Details of the browser/Node.js version**
`v15.3.0`

**SDK version number**
`aws-sdk@2.601`

**To Reproduce (observed behavior)**
Use an expired credential, call sts.getCallerIdentity, observe that it retries using the expired credential

**Expected behavior**
Expired credentials should not be retried (since presumably they can never become un-expired). Or, if this is to account for clock skew or something nuanced like that, perhaps a sensible number of retries should be used (maybe just one?) 

**Additional context**
This was observed in AWS CDK, on which I raised a bug [here](https://github.com/aws/aws-cdk/issues/11920#issuecomment-740651224). There, @rix0rrr asserts that retrying *retryable* requests is appropriate, but that a request using an expired credential should not be retryable. 

The offending code seems to be [here](https://github.com/aws/aws-sdk-js/blob/4fd99d087f245f23b164219fba62156af060770e/lib/event_listeners.js#L423).

Can you explain the logic of having expired tokens be explicitly retryable if this is intentional?

**Comment by ajredniwja** [comment]
Hey @pwrmiller, thanks for opening this and apologies for delayed response, I am quite confused myself here with the logic, I have taken this up with the team, will discuss and let you know the logic behind it.

**Comment by ajredniwja** [comment]
The change was made addressing this: https://github.com/aws/aws-sdk-js/issues/80

**Comment by ajredniwja** [comment]
As a workaround can you manually provide the retry count?

**Comment by ajredniwja** [comment]
https://github.com/aws/aws-sdk-js/blob/5c14d6b1447a44454189bacd1ab5351433746a4e/lib/credentials.js#L16-L19

If the credentials are expired, the SDK tries to refresh them from the source if they can be refreshed.

**Comment by rix0rrr** [comment]
Right, but if the credentials are from environment variables for example, they cannot be refreshed (yet some loop somewhere still assumes they have been and retries the API call)

**Comment by pwrmiller** [comment]
Agreed that credentials are used on EC2 instances as in #80 are retryable - but it seems to be that desktop users on mac using credentials from environment variables (here, `AWS_PROFILE`, but also `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` as noted by @rix0rrr), are not retryable - they are static. It seems that the SDK considers these static credentials as retryable?

**Comment by ajredniwja** [comment]
I do understand what you mean, I can bring this up with the team but not sure if this will be prioritized soon.

**Comment by AllanZhengYP** [comment]
Hi @rix0rrr @pwrmiller 

This is a valid feature request. As @ajredniwja has pointed out, at `ExpiredToken` SDK will reload the credentials and retry the request. However, some credentials should not be retried, like credentials file, and environmental variable. I think I can add a logic in these providers that compare the expired credentials and *newly* loaded credentials, if they are the same, SDK should stop retrying.
