### ISSUE TITLE
 when i use pre-signed URLs，it‘s ok in Chrome and Firefox, but 403 in IE11

### ISSUE THREAD

**Issue by li7228166** [aws/aws-sdk-js#3583]
Using pre-signed URLs to upload a file to a private S3 bucket

![image](https://user-images.githubusercontent.com/7393574/102301571-ff3e1a80-3f91-11eb-9363-d651f7ae11fd.png)

**Comment by ajredniwja** [comment]
@li7228166 thanks for opening this issue, should be a CORS issue with IE. You can follow my comments on https://github.com/aws/aws-sdk-js/issues/3044

Closing this issue now, please reach out if you have any other questions.
