### ISSUE TITLE
SSM getParameters doesn't return the latest version of a parameter

### ISSUE THREAD

**Issue by fadmorenoPluto** [aws/aws-sdk-js#3586]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
If a create a new SSM parameter, the getParameters method returns the correct value, but if I change it, the getParameters method returns the old version.
Even if I removed the SSM parameter the getParameters method still returning that old value. 

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.18.1

**SDK version number**
2.815.0

**To Reproduce (observed behavior)**

1. Create a new SSM parameter, the getParameters method returns the correct value,
2.  Change the value, the getParameters method returns the old version.
3. Delete the  SSM parameter getParameters method still returning the old value. 

Code example:
import { SSM } from 'aws-sdk';

private composeHeaders(headers: { [key: string]: string }): { [key: string]: string } {
    const additionalHeaders = {
       'x-access-token': 'token',
       'X-Service-Name': 'service',
       'X-Service-Version': 'version',
       'X-Environment-Name': 'environment',
       'X-Cluster-Name': 'cluster'
    }

    return { ...headers, ...additionalHeaders };
}

const request = this.ssm.getParameters({
    Names: ['testservice/testvalue'],
    WithDecryption: true,
 });

request.on('build', () => {
    request.httpRequest.headers = this.composeHeaders(request.httpRequest.headers);
});

const { Parameters } = await request.promise();

console.log(Parameters);

**Expected behavior**
Need to return the latest version of the SSM parameter

**Comment by eamarce** [comment]
Hi, good afternoon!

Any progress on this issue? We are facing the same behavior.

Thanks!
