### ISSUE TITLE
new AWS.CodePipeline().putJobFailureResult is not a function

### ISSUE THREAD

**Issue by atrick-speedline** [aws/aws-sdk-js#3588]
AWS APIs are updating constantly, you might be calling a new API with an older version is SDK. In
    this case you should try installing the newest `aws-sdk` like: 

    `npm install aws-sdk@latest`

    If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled
    SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
    You can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

If you still like to open an issue, change [ ] to [x] below:
- [x] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

The actual error message I get is `TypeError: (intermediate value).putJobFailureResult is not a function`. The code in question looks like:

```
return new AWS.CodePipeline()
  .putJobFailureResult({
    failureDetails: {
      message: `Exited with error: ${details}`,
      type: "JobFailed",
    },
    jobId: event["CodePipeline.job"].id,
  })
  .promise();
```

Elsewhere, I have almost identical code with `putJobSuccessResult`, and that seems to work fine. I don't know why. I've updated aws sdk to 2.820.0 (latest) and still get this.

**Comment by ajredniwja** [comment]
Hey @atrick-speedline thanks for opening this issue, seems like you are running this on Lambda, I was not able to reproduce this, can you make sure you are using the latest version of the SDK? How are you importing the SDK?

**Comment by atrick-speedline** [comment]
So, the sdk is listed as an dependency and we're importing it with an ESM style import in TypeScript code. We're using [parcel](https://v2.parceljs.org/) to bundle our code before we throw it on Lambda. It's a possiblity that parcel is pruning the putJobFailureResult, but I certainly wouldn't expected it to. I'll try to look at the bundle to see if I can make any sense of it.

I tried looking at the source code, but it seems to be mostly generated from json files.

**Comment by ajredniwja** [comment]
Its a bit weird since I see the model to be correct as mentioned here: 
https://github.com/aws/aws-sdk-js/blob/8e776616ec4ef4bcb8d74dd99ea022870a2c6d1a/apis/codepipeline-2015-07-09.normal.json#L647

Can you import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).
