### ISSUE TITLE
Mocking DynamoDB Client with Jest

### ISSUE THREAD

**Issue by tnorlund** [aws/aws-sdk-js#3589]
I'd like to start testing the client I have that interacts with my DynamoDB table. I currently have it organized such that the '.js' files in the `data` dir interact with the SDK:

```javascript
// createBlog.js
const AWS = require( `aws-sdk` )
const dynamoDB = new AWS.DynamoDB()
console.log( dynamoDB )

/**
 * Adds a Blog to a DynamoDB table
 * @param   {String} tableName The name of the DynamoDB table.
 * @param   {Blog}   blog      The blog object added.
 * @returns {Map}              Whether the blog was added to the DB.
 */
const createBlog = async ( tableName, blog ) => {
  try {
    await dynamoDB.putItem( {
      TableName: tableName,
      Item: blog.toItem(),
      ConditionExpression: `attribute_not_exists(PK)`
    } ).promise()
```

I'm using Jest for the unit tests, but I'd like to continue to use Jest for the integration. 

I currently have docker running locally, and can interact with the local DB.
```javascript 
// createBlog.test.js
const AWS = require( `aws-sdk` )
AWS.config.update( {
  region: `local`,
  endpoint: `http://localhost:8000`,
} )
const dynamoDB = new AWS.DynamoDB()
```

How do I 'mock' the call in `createBlog.js` to use the object created in `createBlog.test.js`?

**Comment by ajredniwja** [comment]
Hey @tnorlund, thanks for opening this issue, I am a little confused here, correct me if I am wrong I dont have much knowledge about jest but shouldn't you be testing the call from `createBlog.js` in `createBlog.test.js`?

**Comment by tnorlund** [comment]
I ended up mocking the instantiation of the entire 'aws-sdk' library. 

I wanted to do integration testing using the docker container for DynamoDB-local. I was able to mock the instantiation by calling the config function in the mock.

I'll close the issue.

**Comment by markuspxpx** [comment]
> I ended up mocking the instantiation of the entire 'aws-sdk' library.
> 
> I wanted to do integration testing using the docker container for DynamoDB-local. I was able to mock the instantiation by calling the config function in the mock.
> 
> I'll close the issue.

 Could you share the code please?
