### ISSUE TITLE
Support `.promise()` pattern for RDS.Signer.getAuthToken

### ISSUE THREAD

**Issue by willfarrell** [aws/aws-sdk-js#3595]
**Is your feature request related to a problem? Please describe.**
Currently I need to do the following:
```javascript
const signer = new RDS.Signer(config)
    return new Promise((resolve, reject) => {
      signer.getAuthToken({}, (err, token) => {
        if (err) {
          reject(err)
        }
        resolve(token)
      })
    })
    ```

**Describe the solution you'd like**
I would like to do:
```javascript
const signer = new RDS.Signer(config)
    return  signer.getAuthToken({}).promise()
```

**Describe alternatives you've considered**
See top of issue for current workaround. I looked into using v3 but `RDS.Signer` is not supported.

**Additional context**
This API is inconsistent with how other API are handled.

**Comment by ajredniwja** [comment]
Hey @willfarrell thanks for opening this feature request. 

Note: The [version 3.x](https://github.com/aws/aws-sdk-js-v3) of the AWS SDK for JavaScript is generally available.
For more information see the [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/)
or [API Reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html).

**Comment by willfarrell** [comment]
I would consider using the v3 SDK, however `RDS.Signer` isn't supported. https://github.com/aws/aws-sdk-js-v3/issues/1823

**Comment by ajredniwja** [comment]
Thanks for mentioning that issue, It would more likely be implemented in V3 first as that is the SDK that is being actively being worked on.

**Comment by clafollett** [comment]
I know I could definitely use the functionality of RDS.Signer in v3!!!
