### ISSUE TITLE
getMetricData Math Expression Cannot read property 'Metric' of undefined

### ISSUE THREAD

**Issue by kellertobias** [aws/aws-sdk-js#3599]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
If I am using the "Expression" as stated in the docs, I get the error:
```
Error [TypeError]: Cannot read property 'Metric' of undefined
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Local Node JS, not (yet) Lambda

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v14.7.0

**SDK version number**
Example: v2.826.0

**To Reproduce (observed behavior)**

```js
var AWS = require('aws-sdk'),
    region = "eu-central-1";

var cw = new AWS.CloudWatch({
    region: region
});

cw.getMetricData({
  "StartTime": "2021-01-12T00:43:24.858Z",
  "EndTime": "2021-01-13T00:43:24.858Z",
  "MetricDataQueries": [
    {
      "Id": "all",
      "MetricStat": {
        "Metric": {
          "MetricName": "RequestCount",
          "Namespace": "AWS/ApplicationELB",
          "Dimensions": [...]
        },
        "Period": 60,
        "Stat": "Sum"
      }
    },
    {
      "Id": "errors",
      "MetricStat": {
        "Metric": {
          "MetricName": "HTTPCode_ELB_5XX_Count",
          "Namespace": "AWS/ApplicationELB",
          "Dimensions": [...]
        },
        "Period": 60,
        "Stat": "Sum"
      }
    },
    {
      "Id": "success_rate",
      "Label": "success_rate",
      "Expression": "100 * (1 - FILL(errors, 0) / FILL(all,1))"
    }
  ]
}, (err, ret) => {
    if(err) {
        console.log(err)
        return
    }
    console.log(ret)
})
```

**Expected behavior**
Return Aggregated Metrics from Math Expression

**Comment by ajredniwja** [comment]
Hey @kellertobias, thanks for opening this issue, can you make sure that you are using the latest version if the SDK?

**Comment by kellertobias** [comment]
We are using `aws-sdk 2.826.0`

```
"aws-sdk": {
      "version": "2.826.0",
      "resolved": "https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.826.0.tgz",
      "integrity": "sha512-fuNWmD9gfqrxxPbIIbbTeyEDGaKLqFG9kTXqdaPVpEZhH1xc2UwVJQRA7m+SwfQOcQd6hdS1ii0102DrPiFEdg==",
     "...":"..."
}
```

**Comment by ajredniwja** [comment]
Hi @kellertobias, Apologies I lost track of the issue, I was not able to reproduce the issue with the code provided, it'll be helpful to see the stack trace and use [this](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDataQuery.html) for reference.
