### ISSUE TITLE
Auth.signup()  throws "A client attempted to write unauthorized attribute" error if we have "email_verified" attribute 

### ISSUE THREAD

**Issue by minkasu-kuppusamy** [aws/aws-sdk-js#3603]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Trying to create user using Auth.signup() , it throws "A client attempted to write unauthorized attribute" error since i have "email_verified" and "phone_number_verified" attributes during user creation. By removing those 2 i can able to create user !

**Is the issue in the browser/Node.js?**
Browser/Node.js

**If on Node.js, are you running this on AWS Lambda?**
No
**Details of the browser/Node.js version**
v10.15.3

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
```JavaScript
try {
              const { user } = await Auth.signUp({
                  'username': userDetails.email,
                  'password':"Temp@1234",
                  attributes: {
                      "email":userDetails.email, 
                      "email_verified":"true",
                      "phone_number_verified":"true",         
                      "phone_number":userDetails.phone,
                      "custom:org_id":userDetails.org_id,
                       "custom:fullname":userDetails.user_fullname,
                       "custom:org_type":userDetails.org_type,
                       "custom:config_params":userDetails.config_params,
                       "custom:time_created":userDetails.org_live_date,
                       "custom:org_name":userDetails.org_name,
                       "custom:billing_start_date":userDetails.billing_start_date    
                  }
              });
              console.log JSON.stringify(user));
          } catch (error) {
              console.log('error signing up:', error);
          }
```

**Expected behavior**
User must be created,.

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @minkasu-kuppusamy, can you please share the version of the SDK you are using?

**Comment by minkasu-kuppusamy** [comment]
@ajredniwja  :: "email_verified" flag can not be updated via signup api,. it can be done through create user using cognito or through lambda function ,. So closing this ticket. Thanks
