### ISSUE TITLE
The getBucketLocation API is returning incorrect response when connecting to Google Cloud Storage(GCS) endpoint

### ISSUE THREAD

**Issue by prashanthmadduri** [aws/aws-sdk-js#3607]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
We are using getBucketLocation API available here - https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getBucketLocation-property  for retrieving the Google Cloud Storage bucket location but it is returning results with tag "<LocationConstraint>" at the beginning.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
node -v
v10.16.3

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 
aws-sdk@2.802.0 

**To Reproduce (observed behavior)**

Steps to reproduce the behavior (please share code or minimal repo)
Below is the code sample:

```
var AWS = require('aws-sdk')

var s3client = new AWS.S3({ endpoint: 'https://storage.googleapis.com/ ', secretAccessKey: '<<GCS Secret Access Key>>', accessKeyId: '<<GCS Access Key Id>>' })

var params = {
  Bucket: '<<GCS Bucket Name>>'
}

s3client.getBucketLocation(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
  });
```

**Output:**

`{ LocationConstraint: '<LocationConstraint>US' }`

**Expected behavior**
Expected Output:
`{ LocationConstraint: 'US' }`

**Screenshots**

**Additional context**

Below are the supporting resource for using "aws-sdk" for other storage endpoint like Google Cloud Storage(GCS).
1. As per the issue here https://github.com/aws/aws-sdk-ruby/issues/1616 , we can use "aws-sdk" with other storage endpoints.
2. Please find Stack Exchange thread with more information for the https://devops.stackexchange.com/questions/145/can-you-use-aws-sdk-to-store-objects-in-google-storage .

It is returning results as below when executing the same "Get Location" from GCS XML API available here - https://cloud.google.com/storage/docs/xml-api/get-bucket-location 

```
<?xml version='1.0' encoding='UTF-8'?>
<LocationConstraint>US</LocationConstraint>
```

The response from `aws-sdk` is coming as below:

```
<LocationConstraint>US
```

Based on the above responses, we feel the `aws-sdk` is failing to handle response for the `getBucketLocation` call to return only `US` instead  `<LocationConstraint>US`.

**Comment by gshondal** [comment]
Hello,

According to the S3 API docs, https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html, the response from the service must be in the format:


```
HTTP/1.1 200
<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint>
   <LocationConstraint>string</LocationConstraint>
</LocationConstraint>
```

It looks like the Google Cloud API is missing some information in order to be valid with the AWS SDK.

**Comment by prashanthmadduri** [comment]
Hi @gshondal 

Thank you for your inputs. I have tried with S3 API for retrieving the bucket location. The response is as below:

The request to Amazon S3 is as below from `Postman`:
```
var request = require('request');
var options = {
  'method': 'GET',
  'url': 'https://<<Amazon S3 Bucket Name>>.s3.amazonaws.com/?location',
  'headers': {
    'X-Amz-Content-Sha256': '<<Generated X-Amz-Content-Sha256>>',
    'X-Amz-Date': '20210125T050922Z',
    'Authorization': 'AWS4-HMAC-SHA256 Credential=<<Access Key ID>>/20210125/us-east-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=<<Generated Signature>>'
  }
};
request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});
```

The response is as below:

```
<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/">us-east-2</LocationConstraint>

```

Here, I am using Amazon S3 API mentioned above and hitting the Amazon S3 endpoint, my bucket is available in `Amazon S3` not in `Google Cloud Storage`.

Based on this the response from the `Amazon S3` and `Google Cloud Storage` is not changing much.

**Comment by ajredniwja** [comment]
Hey @prashanthmadduri thanks for opening this issue, using the API with AWS, it works perfectly fine, while the comment that you mentioned from Ruby repo mentions it may work with something like GSC but we unfortunately do not provide support for third party storage clouds. 

I also wanted to mention that it has to be compatible with AWS which is mentioned in the original comment as well.
