### ISSUE TITLE
return a promise if no callback supplied

### ISSUE THREAD

**Issue by jonathanong** [aws/aws-sdk-js#361]
for es6+

**Comment by egeland** [comment]
About a year on from the initial ticket, is there support for promises in this SDK? (I skimmed the docs and see only callbacks and Request objects in the examples)

Promises will be hugely important with both ES2015 and ES2016 (see `async`/`await` for ES2016, especially), and if I've just missed the doco, would really appreciate a quick pointer.

**Comment by ash2k** [comment]
Maybe a workable approach would be to add an additional method that returns a promise to the `Request` object? Take a look at https://github.com/lightsofapollo/aws-sdk-promise/blob/master/index.js (but it should use native `Promise` probably).
