### ISSUE TITLE
Documentation: Retries and Timeouts unclear

### ISSUE THREAD

**Issue by jfang531** [aws/aws-sdk-js#3611]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

The documentation is very unclear about the default values for retries and timeouts for calls. Case in point, in examining the documentation, try to determine what the default values are for DynamoDB, S3, and SNS for: connection timeout, number of retries, retries timeout, and general timeout.

Some specific items:
1) The developer guide has no discussion of retries and timeouts. (e.g. no mention of exponential backoff, jitter, or even that retrying as a whole exists)
2) The API lists parameters for each, but the default values for the parameters are not listed. Notably, for maxRetries, connectTimeout, and timeout
3) The "maxRetries" entry references to something which can't be found (or is self-referential, which is recursive and thus not helpful): maxRetries (Integer) - the maximum amount of retries to attempt with a request. See AWS.DynamoDB.maxRetries for more information.

Additionally, the Amazon best practices section discusses the idea of having a retry-token-bucket as a strategy, but the SDK doesn't seem to implement this. 

**Is the issue in the browser/Node.js?**
Browser/Node.js

Both/N/A

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @jfang531, thanks for opening this issue, I can understand how frustrating that can be, while I agree that it should be added to the documentation here are a few workarounds. 

For `defaultRetryCount`:

If there are no customizations are done to the client the `defaultRetryCount` can be found at:
https://github.com/aws/aws-sdk-js/blob/54f8555bd94d33a1754a44a35286f1d9e31c28a3/lib/service.js#L153

For services where the services with customization like `dynamoDBb`:
https://github.com/aws/aws-sdk-js/blob/54f8555bd94d33a1754a44a35286f1d9e31c28a3/lib/services/dynamodb.js#L44

For `timeout` it is set in the `httpOptions`:

https://github.com/aws/aws-sdk-js/blob/2f68b291e1aa3137c2389bf48ac3d251f18c61f5/lib/config.js#L540

You can even use the code to find those out for example:

For `maxRetries`:

```
var request = s3.listBuckets();

var response = request.send();

console.log(response.maxRetries)
```

For 'timeOuts`

```var request = s3.listBuckets();

console.log(request.service.config.httpOptions)
```

I can reach out to the documentation team to maybe add default values in the developer guide and maybe see if there is a way to add those to the API reference as those are all owned by different services. Usually if you read SDK comment, most of the times they will mention the default values in the SDK code.

**Comment by davidtheclark** [comment]
I have the same question for v3, and I don't think the above workarounds apply to v3's code. Where should we find default retries and timeouts in v3, and how do we configure them if we don't want the defaults?

**Comment by Kikobeats** [comment]
The @ajredniwja's comment is outdated since `.send()` is returning a Promise these days.

**Comment by aBurmeseDev** [comment]
Hi everyone - apologies for the long silence here. 

Here are requested default values for maxRetries I could gather:
```
DynamoDB:
maxRetries: 10 (maximum number of retry attempts)
httpOptions.connectTimeout: 1000 ms (1 second)
httpOptions.timeout: no default value (no general timeout)

S3:
maxRetries: 3
httpOptions.connectTimeout: 1000 ms (1 second)
httpOptions.timeout: no default value (no general timeout)

SNS:
maxRetries: 3
httpOptions.connectTimeout: 1000 ms (1 second)
httpOptions.timeout: no default value (no general timeout)
```
We will pass this feedback along service teams. Since there's no action item for SDK, I'm going to close the issue.
