### ISSUE TITLE
Lex v2 updating with new APIs getting permissing issue

### ISSUE THREAD

**Issue by vishalmarakana** [aws/aws-sdk-js#3612]
## Describe the bug
I'm using the following SDK for lex v2, to send the message I'm using `recognizeText` but I'm receiving the fowling error:
{"Message":"User: arn:aws:sts::xxxxxxxxxx:assumed-role/Cognito_XXXXXChatbotPoolUnauth_Role/CognitoIdentityCredentials is not authorized to perform: lex:RecognizeText on resource: arn:aws:lex:us-east-1:xxxxxxxx:bot-alias/xxxxxxxxx/xxxxxxxx"}

I'm also trying to add new permissing role for `recognizeText` but i can't find it in actions list: 
<img width="891" alt="Screenshot 2021-01-28 at 12 04 12 PM" src="https://user-images.githubusercontent.com/38314221/106099723-28d98c80-6161-11eb-9bad-4e5320fe3d72.png">

#### SDK version number
`@aws-sdk@2.831.0`

#### Issue
{"Message":"User: arn:aws:sts::XXXXXXXX:assumed-role/Cognito_XXXXXChatbotPoolUnauth_Role/CognitoIdentityCredentials is not authorized to perform: lex:RecognizeText on resource: arn:aws:lex:us-east-1:XXXXXXXXX:bot-alias/XXXXXXXXX/TSTALIASID"}

Even I'm not able to find `recognizeText` action in the lex documentation(Service Authorization Reference
Feedback 
): https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonlex.html#amazonlex-actions-as-permissions

**Comment by ajredniwja** [comment]
Hey @vishalmarakana thanks for opening this issue, this seems to be some disconnect between IAM and lex services, it can be because the API was just recently released. I have reached out to the Lex team to know more about it and can update here once I hear back from them.

**Comment by ajredniwja** [comment]
I have a conformation from the Lex team that it is a Bug with the service that they are actively working on, will update you once it has been fixed.

**Comment by vishalmarakana** [comment]
@ajredniwja  Thanks for the update and take it initiative.

**Comment by ajredniwja** [comment]
This was fixed, please reach out if that is not the case.
