### ISSUE TITLE
sns + baiduCloudPush notification

### ISSUE THREAD

**Issue by zhangjiancheng** [aws/aws-sdk-js#3613]
It seems only work on in-app-message. Notification doesn't work.
MessageAttributes
 While I set AWS.SNS.MOBILE.BAIDU.MessageType = 1, the message can't be sended.
In CloudWatch Logs, it also can not  found record.

Using 
apigateway + Lambda
aws-sdk.js with baidu cloud push

**Comment by zhangjiancheng** [comment]
Paste my code.

`                params = {
                    MessageStructure: 'json',
                    TargetArn: xxxx,
                    Message: JSON.stringify({
                        default: message,
                        [apns]: JSON.stringify({
                            aps: {
                                alert: message,
                                sound: 'default',
                                badge: 0,
                                action: action,
                            }
                        }),
                        GCM: JSON.stringify({
                            notification: {
                                title: message,
                                body: message,
                                sound: 'default'
                            },
                            data: {
                                action: action
                            }
                        }),
                        BAIDU: JSON.stringify({  
                            title: 'hello' ,  
                            description: 'hello world',
                            body: message
                        })
                    }),
                    MessageAttributes: {
                        'AWS.SNS.MOBILE.BAIDU.MessageKey': {
                            DataType: 'String',
                            StringValue: message
                        },
                        'AWS.SNS.MOBILE.BAIDU.DeployStatus': {
                            DataType: 'String',
                            StringValue: '2'
                        },
                        'AWS.SNS.MOBILE.BAIDU.MessageType': {
                            DataType: 'String',
                            StringValue: '1'
                        }
                    }
                };`

**Comment by ajredniwja** [comment]
Hey @zhangjiancheng thanks for your patience here, can you please follow the [issue template](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=) found here, as I would need some more information.
