### ISSUE TITLE
Describe the AWS regions using ApiGatewayV2 service

### ISSUE THREAD

**Issue by vinitshahdeo** [aws/aws-sdk-js#3623]
**Is your feature request related to a problem? Please describe.**
My use-case is to list down all the available AWS regions for [ApiGatewayV2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayV2.html) service programmatically. The config already requires `region` parameter to use this service.

```js
new AWS.Config({
    accessKeyId: 'XXXXXXXXXX',
    secretAccessKey: 'XXXXXXXXXX',
    region: 'us-east-1'
});
```

**Describe the solution you'd like**
Like we have [describeRegions](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeRegions-property) for EC2, **can we also have similar list regions operation for ApiGatewayV2?**

```js

const apiGatewayV2 = new AWS.ApiGatewayV2();

apiGatewayV2.describeRegions({}, function(err, data) {
  if (err) {
    console.log("Error", err);
  } else {
    console.log("Regions: ", data.Regions);
  }
});
```

**Describe alternatives you've considered**
We can consider [EC2.describeRegions()](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeRegions-property) property but the problem here is that _IAM user's credentials used for ApiGatewayV2 service might not have permission to access Amazon EC2._

**Additional context**
The end goal is listing all the available AWS regions using the same credentials(`accessKeyId` and `secretAccessKey`) which is used to list all the available AWS API Gateway resources using [getApis](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayV2.html#getApis-property) operation of [ApiGatewayV2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayV2.html) service.

_PS: Is there any existing API endpoint to serve the purpose? Couldn't find one._

**Comment by ajredniwja** [comment]
Hey @vinitshahdeo thanks for opening this Feature Request, currently I am not aware of any such function like one for EC2 or an endpoint. It would have to implemented by the API Gateway team.
