### ISSUE TITLE
schemas typescript code bindings can't manage optional fields

### ISSUE THREAD

**Issue by fabio-vitali-docebo** [aws/aws-sdk-js#3629]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
typescript schema code bindings don't support optional schema properties

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.13.0

**SDK version number**
v2.819.0

**To Reproduce (observed behavior)**
- in AWS console, go to EventBridge service, create a new schema registry
- create a "JSON Schema Draft 4" schema with this content:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "Test": {
      "type": "object",
      "properties": {
        "required_property": {
          "type": "string"
        },
        "optional_property": {
          "type": "string"
        }
      },
      "required": ["required_property"]
    }
  },
  "type": "object",
  "properties": {
    "test": {
      "$ref": "#/definitions/Test"
    }
  }
}
```
- save the schema and download its TypeScript code bindings
- in the Test class both fields are rendered in the same way
```
export class Test {
  'optionalProperty': string;
  'requiredProperty': string;
  ...
```

**Expected behavior**
I would expect something like this
```
export class Test {
  'optionalProperty'?: string;
  'requiredProperty': string;
  ...
```

**Screenshots**
-

**Additional context**
-

**Comment by ajredniwja** [comment]
Hi @fabio-vitali-docebo, thanks for opening this issue, is it still a persisting issue, apologies I lost track of this issue, but I am not sure how you are consuming the SDK in your use case.

**Comment by fabio-vitali-docebo** [comment]
hi @ajredniwja I use the sdk to interact with the EventBridge api. but you're right, it's not the right thread, I should open an issue at the EventBridge service level. thanks!

**Comment by emassimi** [comment]
Hi @fabio-vitali-docebo,

As I'm facing the same issue, and I agree that this should be handled at EventBridge service level, do you have a public link to the request you might have made to the EventBridge support channel? 

Thanks!
