### ISSUE TITLE
LookoutVision detectAnomalies always returns a ValidationException:

### ISSUE THREAD

**Issue by julianpitt** [aws/aws-sdk-js#3631]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The detectAnomalies function in the LookoutVision client always returns `ValidationException: content-type must be one of the following. image/jpeg, image/png`

I have already tried the same projectName, ModelVerions, ContentType and image using the AWS CLI, AWS Python SDK Boto3, and the AWS SDK for JS.

Only the AWS SDK for JS is raising the exception.
All other sdks and commands are working as expected with the same image

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes but also on my own local machine

**Details of the browser/Node.js version**
`node -v`
v12.18.3

**SDK version number**
aws-sdk@2.842.0

**To Reproduce (observed behavior)**
First follow this repo to train a model in lookout vision https://github.com/aws-samples/amazon-lookout-for-vision
Then take any image from https://github.com/aws-samples/amazon-lookout-for-vision/tree/main/circuitboard and keep it in the local directory while running the code below. (Change region and filename in code to suit your test)

```javascript
const AWS = require('aws-sdk');
const fs = require('fs');

const lv = new AWS.LookoutVision({ region: 'us-east-1' });
(async () => {
    try {
        const bitmap = fs.readFileSync('./test-normal_2.jpeg');
        const anomalies = await lv
            .detectAnomalies({
                ProjectName: 'circuitproject',
                ModelVersion: '1',
                Body: bitmap,
                ContentType: 'image/jpeg',
            }).promise();
        console.log(anomalies);
    } catch (e) {
        console.error(e);
    }
    return
})()
```

**Expected behavior**
A response with the Anomaly status and confidence score

**Screenshots**
![Screen Shot 2021-02-12 at 3 28 14 pm](https://user-images.githubusercontent.com/8890146/107730474-a1d30980-6d47-11eb-8166-fff9f2c6ca10.png)
![Screen Shot 2021-02-12 at 3 30 18 pm](https://user-images.githubusercontent.com/8890146/107730482-a8618100-6d47-11eb-9bfe-b364796d1cb8.png)

**Additional context**

**Comment by physcx** [comment]
Hi Julian, I noticed there was a bug in the javascript SDK generator automatically mixing values for content-type and Content-Type headers. Lookout for Vision should have this issue fixed in their latest JavaScript SDK versions. Can you try using the aws-sdk@2.846.0 or newer and hopefully your issue with invalid content-type will be resolved.

**Comment by ajredniwja** [comment]
@julianpitt can you check if the problem still persists with the latest version of the SDK?

**Comment by julianpitt** [comment]
Confirmed working in v2.852.0. Thank you :)
