### ISSUE TITLE
Getting Access Denied when trying to connect S3.

### ISSUE THREAD

**Issue by vrathore18** [aws/aws-sdk-js#3632]
Docker version: node:14.15.5-alpine3.12
Kubernetes version: 1.18

We are getting an "Access Denied" error from a AWS-SDK library installed by NPM just after we upgraded our Docker image from "node" to "node-alpine".
Curiously - the same image is working fine when is consumed by Docker-Compose, AWS library is able to authenticate and upload files to S3.
The same image is giving us an "Access Denied" error when used by Kubernetes.

So - we are guessing that there is no issue with the image since it works fine with Docker-Compose. The issue only exists while using the image with Kubernetes.

**Comment by ajredniwja** [comment]
Hey @vrathore18 can you please follow the issue template found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)
