### ISSUE TITLE
APIGateway: Add support for connection close reason

### ISSUE THREAD

**Issue by andyrichardson** [aws/aws-sdk-js#3636]
**Is your feature request related to a problem? Please describe.**

The [websocket spec](https://tools.ietf.org/html/rfc6455#section-7.4.1) supports providing a _close code_ and data to provide semantic reasoning as to why the socket is being closed.

The [deleteConnection](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayManagementApi.html#deleteConnection-property) method doesn't support any attributes to support this functionality.

> Note: This may be a limitation on the APIGateway API itself

**Describe the solution you'd like**

Something like this would be great

```js
const api = new AWS.ApiGatewayManagementApi();
api.deleteConnection({
  ConnectionId: /* */,
  CloseCode: 1000,
  Message: `Some message`,
});
```

**Describe alternatives you've considered**
No alternatives have crossed my mind!

**Additional context**
If this is an APIGateway API limitation, it would be greatly appreciated if this feature request could be forwarded to the appropriate team 🙏

**Comment by yunusemrealtiner** [comment]
yes something like this would be really cool i need this to report why disconnected clients get disconnected and if they need to reconnect

**Comment by yunusemrealtiner** [comment]
yes something like this would be really cool i need this to report why disconnected clients get disconnected and if they need to reconnect

**Comment by adrian-skybaker** [comment]
Still a large gap . eg, the https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md specifies code to distinguish a standard close (eg just rotating connnection) vs close-with-error-and-reason.
