### ISSUE TITLE
aws-ses: SendTemplatedEmail uses unexpected IAM policy

### ISSUE THREAD

**Issue by s-dschro** [aws/aws-sdk-js#3641]
Hey guys,

when using `SendTemplatedEmail` from `aws-ses` in the following way:

```
    // ...
    const request: ses.Types.SendTemplatedEmailRequest = {
      Source:       source,
      Destination:  { ToAddresses: ["test@gmail.com"] },
      Template:     template,
      TemplateData: JSON.stringify(data),
    };
    try {
      await this.client.sendTemplatedEmail(request).promise();
    } catch(e) {
      console.error("SES failed: %s", e);
      throw e;
    }
```
it expects my lambda to have the following policy/permissions:

```
arn:aws:sts::<accountId>:assumed-role/<serviceRole>/<lambda>' is not authorized to perform `ses:SendTemplatedEmail' on resource `arn:aws:ses:<region>:<accountId>:identity/test@gmail.com'
```

Is this a known bug? Or is there something wrong in my config?

The docs say, that I have to put my `source` mail-address into the resource-arn ...
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-policy-examples.html

**Comment by ajredniwja** [comment]
Hey @s-dschro, thanks for opening this issue, seems to be an authorization issue, you can use the guide found [here](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-send-email-ses/) to configure it correctly. 

Would be happy to answer if you have any other questions.

**Comment by s-dschro** [comment]
This link is not very helpful as they use a wildcard `*` as their resource-arn ...

**Comment by ajredniwja** [comment]
But does that work for you? 

You can also create policies using https://awspolicygen.s3.amazonaws.com/policygen.html

**Comment by Prafull1Kumar** [comment]
Hey, I am also suffering from the same issue. 
Yes, It is working by making "Resource":"*" but I need to know what actually we have to put in recourse.

**Comment by jwoffindin** [comment]
This is not related to the JS SDK but an incorrect IAM policy on the lambd.

For anybody else who hits this issue, according to the [AWS SES permissions reference page](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonses.html#amazonses-template), this API call requires access to at least the SES identity and template that you're using with SendTemplatedEmail. 

E.g. you'll need an IAM policy like:

            - Effect: Allow
              Action:
                - ses:SendTemplatedEmail
                - ses:SendEmail
              Resource:
                - arn:${Partition}:ses:${Region}:${Account}:identity/example.com
                - arn:${Partition}:ses:${Region}:${Account}:template/invoice-due-template

**Comment by aditya-passbird** [comment]
> This is not related to the JS SDK, but an incorrect IAM policy on the lambda.
> 
> For anybody else who hits this issue, according to the [AWS SES permissions reference page](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonses.html#amazonses-template), this API call requires access to at least the SES identity and template that you're using with SendTemplatedEmail.
> 
> E.g. you'll need an IAM policy like:
> 
> ```
>         - Effect: Allow
>           Action:
>             - ses:SendTemplatedEmail
>             - ses:SendEmail
>           Resource:
>             - arn:${Partition}:ses:${Region}:${Account}:identity/example.com
>             - arn:${Partition}:ses:${Region}:${Account}:template/invoice-due-template
> ```

does this work for cross account? I am trying to use idenity and template of some other account but its not working

**Comment by Qix-** [comment]
I'm hitting this too. This seems wrong, and I believe this ticket should be re-opened.

Even via CDK, `grantSendEmail` from an email identity adds an IAM permission `ses:SendEmail` for the identity itself, which has `identity/<verified domain>`. That looks correct.

Why, then, is the client using the **destination email address** as the `identity/<...>` IAM role lookup? This feels like a bug to me, unless I'm woefully misunderstanding how IAM roles work.

The guide linked to above states you should set `"Resource": "*"` in the IAM definition. This _feels_ very wrong from a security standpoint. Is that really the correct way to do things?

More specifically, it appears specifying the `SourceArn` makes no difference; it doesn't appear to be performing a lookup even when I explicitly specify the verified email identity ARN.

Can someone from AWS please clarify how the IAM permissions are **really** supposed to work here?

---

Looking into this a bit more, it appears this is only the case under **Sandbox Mode**. Once you're out of sandbox mode, it _looks like_ you can just add the permission for the verified identity. Haven't gotten that far personally, so don't quote me.

Whilst in sandbox mode, you'll have to do the `*` resource hack. You'll also need to go to the _Identities_ page in the console, go to _Create Identity_, specify the _Email address identity_ type, enter in an address you want to send to, and then verify it using the link in the email that AWS sends.

Then you'll be able to send just to that address until you're out of sandbox mode.

I could be wrong here, but that's my understanding of it. Might help someone else. I understand the safeguards in place - that's not the problem - but why IAM roles are used for this is beyond me. The error messages surrounding this part are absolutely abysmal, and I worry about production configurations that miss this and just allow `*` everywhere even after sandbox mode has been lifted.
