### ISSUE TITLE
createSign is not implemented in the browser ---- (react native)

### ISSUE THREAD

**Issue by voxspot** [aws/aws-sdk-js#3643]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I'm using aws-sdk version 2.848.0 in react-native version v0.63
I'm trying to get a signed URL from cloudfront with the following code (see below) but it throws me an error instead
"createSign is not implemented in the browser". The credentials (keyid and private key both matches the actuals from the AWS cloudfront console). The setup for cloudfront and s3 bucket are both fine - no issues:

Sample code:
`
const cloudfrontAccessKeyId = "CLOUD-FRONT-ACCESS-KEY-ID" //e.g "APSFDSLHFSLKFJ5A"
const cloudfrontPrivateKey = "CLOUD-FRONT-PRIVATE-KEY" //string e.g. "-----BEGIN RSA PRIVATE KEY-----MIIEpQ ....zd8eo=-----END RSA PRIVATE KEY-----"

const AWS = require('aws-sdk/dist/aws-sdk-react-native')
const signer = new AWS.CloudFront.Signer(cloudfrontAccessKeyId, cloudFrontPrivateKey)
const options = {
        url: "https://xxx.cloudfront.net/test.png",
        expires: 200000,
      }
signer.getSignedUrl(options, (e, url) => {
          console.log('Your generated pre-signed URL is', url)
          console.log('error ' + e)
})
`

If i try to get a pre-signed url from s3 bucket direct (and not cloudfront), i'm able to get the pre-signed url without issues. But that is not what i want - i need the signed url from cloudfront (as my files have restricted access).

**Comment by sundragontech** [comment]
I am having the same issue.

**Comment by ajredniwja** [comment]
Hey @voxspot and @sundragontech, thanks for opening this issue, as the error states getSigned URL is not implemented in the browser since it requires to expose the keys to the client. I found an old issue which talks about different approaches you can take https://github.com/aws/aws-sdk-js/issues/231

Closing this issue now, please reach out if you have any other questions.
