### ISSUE TITLE
Single Upload progress for Multiple files (S3-managedupload)

### ISSUE THREAD

**Issue by SenthilManickavel** [aws/aws-sdk-js#3644]
When I try to upload multiple files, I am getting the progress for individual files. I would like to show the consolidated/single progress. Is there a way to do that?

Need to show one progress indicator for multiple file upload

**Comment by ajredniwja** [comment]
Hey @SenthilManickavel thanks for opening this issue, I am not sure if that is currently possible, however you can pragmatically track all the progresses and have a single counter to check the total progress.
