### ISSUE TITLE
I want to check weather the S3 bucket is available ( healthy ) or not , but couldn't find anything for this

### ISSUE THREAD

**Issue by 4nkitd** [aws/aws-sdk-js#3645]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I want to check weather the S3 bucket is available ( healthy ) or not , but couldn't find anything for this. Is this even possible, if yes , is their a way to do it with SDK, thanks

**Comment by ajredniwja** [comment]
Hey @4nkitd thanks for opening this issue, are you trying to check if the bucket exists in S3? 

For that you can use the `headBucket` function.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headBucket-property

**Comment by 4nkitd** [comment]
I want to check the bucket health like it's not under maintenance and available for transfer.

**Comment by ajredniwja** [comment]
I am not exactly sure what you mean by bucket health, if the head bucket returns a 200 response it should be available for transferring data. 

With that being said can you tell me steps on how you get the bucket health right now? using the console?
