### ISSUE TITLE
Dynamodb Encryption SDK for Nodejs (Come on Guyz! ) 

### ISSUE THREAD

**Issue by waleedshkt** [aws/aws-sdk-js#3648]
I know this sdk in nodejs version had been requested 3-4 years ago. But yet it has not been available. 

I myself am using dynamodb in projects requiring putting and getting of sensitive personal data. Therefore encryption in transit is a must.

A working solution currently is to use general aws encryption sdk. But it's not very neat. 

Therefore, please build a nodejs sdk for dynamodb encryption client

**Comment by ajredniwja** [comment]
Hey @waleedshkt thanks for opening this feature request. I can bring this up with our team to discuss the priority based on our customers reaction.

**Comment by waleedshkt** [comment]
Appreciated your response

Plus, @ajredniwja, I have also filled a bug report regarding dynamodb query key condition expression parsing. I think it's really urgent to resolve it. Here is the link: https://github.com/aws/aws-sdk-js-v3/issues/2079#issue-815705624

**Comment by fab-mindflow** [comment]
Any news on this?
It seems there is no Javascript / Typescript alternative after years, right?

**Comment by waleedshkt** [comment]
Yeah, sadly looks like so
