### ISSUE TITLE
S3 GetObjectCommand response does not return what the docs say it returns

### ISSUE THREAD

**Issue by adamjc** [aws/aws-sdk-js#3649]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Using the v3 sdk like so:

```
const s3 = new S3Client()
const s3Params = {
  Bucket: $MY_BUCKET_NAME,
  Key: $MY_PATH,
}
const command = new GetObjectCommand(s3Params)
const s3Data = await s3.send(command)
```

According to the docs, s3Data.Body should be a `Blob, Readable Stream, Readable` (https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/modules/getobjectoutput.html#body), but it's actually `IncomingMessage`? Googling gives nothing. I'm not sure what to actually do to get the data out of the response. The status is all 200s, OK.

Running the response through `Buffer.from(...)` gives:

```
(node:5564) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of IncomingMessage
    at Function.from (buffer.js:333:9)
```

A snippet of the response I get back on the `Body` prop:

```
IncomingMessage {
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: false,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: true,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] { end: [Function: responseOnEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
```

**Comment by ajredniwja** [comment]
Hey @adamjc thanks for opening this issue, this is an ongoing issue in V3 of the SDK for your specific problem you can use the example mentioned by @trivikr https://github.com/aws/aws-sdk-js-v3/issues/1877#issuecomment-755387549

Apart from that there is clear explanations on how the response is formatted. 

I would close this issue as this specific repo belongs to V2 of the SDK. 

This issue will be tracked with https://github.com/aws/aws-sdk-js-v3/issues/1877

**Comment by adamjc** [comment]
Thank you!

**Comment by DevRithm** [comment]
is this issue still persisting?

**Comment by smarzism** [comment]
I had a problem with the image sent from a3 GetObjectCommand and received by axios and I solved it here : 
https://stackoverflow.com/questions/70534780/convert-weird-image-characters-for-use-in-image-src
