### ISSUE TITLE
Problem with CORS Single Sign On

### ISSUE THREAD

**Issue by Konfront** [aws/aws-sdk-js#3651]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I am configuring the javascript SDK to be able to obtain the SSO information and be able to access the platforms associated with my users as well as to be able to register users among other functionalities. The error that appears in the browser console is that CORS is not enabled. Next I put the code that I have to be able to initialize the registration method of a client:
```JavaScript
var ssooidc = new AWS.SSOOIDC ({region: 'us-east-1'});
console.log (ssooidc);
     var params = {
   clientName: 'David', / * required * /
   clientType: 'Test', / * required * /
   scopes: [
     'scope',
     / * more items * /
   ]
};
ssooidc.registerClient (params, function (err, data) {
   if (err) {
        console.log ("Error:" + err);
       } else {
       console.log ("data:" + data);
       }
});
```

I also put a screenshot about the error that appears in the browser when running the code and the request headers.

![image](https://user-images.githubusercontent.com/79924698/109672043-3d32ef80-7b3a-11eb-8acc-fd7c14988a4f.png)
![image](https://user-images.githubusercontent.com/79924698/109672175-60f63580-7b3a-11eb-8754-9395c95a2826.png)

**Comment by ajredniwja** [comment]
Hey @Konfront, thanks for opening this issue, I believe CORS is not enabled for SSOIDC. 

I mentioned a workaround in https://github.com/aws/aws-sdk-js/issues/3431#issuecomment-699177820

**Comment by ajredniwja** [comment]
For a service with CORS enabled, it'll `cors:true`.

https://github.com/aws/aws-sdk-js/blob/5ee52b9c07b9959a24104c8788236efc6cf64547/apis/metadata.json#L785-L788

**Comment by prasanthnarasimha** [comment]
Hey @ajredniwja , are there plans to support CORS for SSO OIDC api? Using AWS SSO Auth in web applications is extremely common in many organizations , so it would be good to not maintain an endpoint for proxy purposes. Thanks!

**Comment by joelawm** [comment]
Ran into this issue as well, would be super helpful to keep token on the client and not passed through a middleman layer.
