### ISSUE TITLE
Route 53 does not retry ListResourceRecordSets when throttled

### ISSUE THREAD

**Issue by tjunnone** [aws/aws-sdk-js#3652]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The Route 53 client does not retry the listResourceRecordSets API call when it receives a ThrottlingException, throwing the error. This behavior is inconsistent with other Route 53 client APIs, such as listTagsForResource, which do retry on throttling, as well as the documented retry behavior of the SDK.

**Is the issue in the browser/Node.js?**
Browser & Node.js

**SDK version number**
v2.854.0

**To Reproduce (observed behavior)**
Issue a large number of concurrent Route53.listResourceRecordSets requests, a throttling error will be thrown.

**Expected behavior**
The SDK should retry the call when receiving a throttling error response that has the retryable flag. This is handled by middleware, but it appears the API must be opted in for this. 

**Additional context**
- This is the original PR + issue that added retry logic to Route 53: https://github.com/aws/aws-sdk-js/pull/1168
- This is the API definition block that is missing the ThrottlingException case:
https://github.com/aws/aws-sdk-js/blob/b26bcf25910909b51ca272343370139ecc55feeb/apis/route53-2013-04-01.normal.json#L1394
- It is likely that other Route53 client APIs are also missing proper throttling handling in the SDK, however listResourceRecordSets is the only case I've run into personally. The documentation at https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests states that all requests are limited to 5 req. / sec. Looking at the SDK, I believe only the tag APIs of the Route 53 client are handling this correctly.

**Comment by ajredniwja** [comment]
Hey @tjunnone apologies that I lost track of this issue, I will take this to the Route53 team as I am not sure why this particular  API is left out, thanks for your patience on this. Will update you soon.

**Comment by tjunnone** [comment]
This is still an issue.

**Comment by aBurmeseDev** [comment]
Hi there - apologies for the long silence here. I have notified Route 53 service team about this reported behavior. (ref: _P149607489_).  

Since there are no pending action items for the SDK team, and we aim to dedicate this repository solely for SDK-related issues, I will proceed with closing this case. Please feel free to reach out directly to the service team via [AWS Support](https://aws.amazon.com/contact-us/) for further updates.
