### ISSUE TITLE
InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: xxxxxx

### ISSUE THREAD

**Issue by surya-pipra** [aws/aws-sdk-js#3655]
I'm getting (InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: xxxxx) and we handled this exception like getting sequence token from the error message but can anyone please help me what is the root cause of it or what are the possible scenarios to getting InvalidSequenceToken issue in cloud watcher PutLogEvents method

i'm following below document 
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html

**Comment by ajredniwja** [comment]
@surya-pipra apologies I lost track of this issue, The [doc](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html) you must include the sequence token obtained from the response of the previous call. An upload in a newly created log stream does not require a sequence token. So might want to try to include the token you receive in the response you get initially. 

I'd be happy to help you if that doesn't solve the issue, would like more details on your use case, the version of the SDK you are using and repro code if possible.
