### ISSUE TITLE
how to add custom params in s3 presigned url

### ISSUE THREAD

**Issue by xuetaofeng** [aws/aws-sdk-js#3656]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
By aws dotnet sdk, I could add custom params in s3 presigned url by following sample code:
```
            // Create a CopyObject request
            GetPreSignedUrlRequest request = new GetPreSignedUrlRequest
            ...
            request.Parameters.Add("userEmail", "hello@c.c"); // here I can add custom parameter "userEmail"

            // Get path for request
            return client.GetPreSignedURL(request);
```
And I saw this feature is also supported in aws go sdk (https://github.com/aws/aws-sdk-go/issues/3380)
But I did not find a method to do this in nodejs:
```
const params = {
    Bucket: 'xxx',
    Key: 'xxx',
    Expires: 60 * 5
  };

const url = s3.getSignedUrl('getObject', params); // how to add a custom parameter ?
```

Could anyone help me on this?

**Comment by ajredniwja** [comment]
Hey @xuetaofeng thanks for opening this issue, one way to add those would be to use something like:

```Javascript
var aws = require('aws-sdk');

var s3 = new aws.S3({region: 'us-west-2', signatureVersion: 'v4'});

const params = {
    Bucket: 'test',
    Key: 'test.jpg',
    // Expires: 60 * 5
  };

var req = s3.getObject(params);

req.on('build', () => { 
    req.httpRequest.path += '?key=val';
 });

var url = req.presign(120); //120 is expiration param in milliseconds
console.log(url);
```

Closing this issue now, please reach out, if you have more questions.

**Comment by febg11** [comment]
Can you do this without calling getObject?
