### ISSUE TITLE
DynamoDB Data Mapper support in AWS SDK v3

### ISSUE THREAD

**Issue by kennu** [aws/aws-sdk-js#3658]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

In https://github.com/awslabs/dynamodb-data-mapper-js/issues/138 and https://github.com/aws/aws-sdk-js/issues/2637 it was said that the DynamoDB Data Mapper for JavaScript, which greatly simplifies typical DynamoDB use cases, will be incorporated into AWS SDK v3. Where can I find it?

I have looked into

* https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/index.html
* https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_lib_dynamodb.html
* https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_util_dynamodb.html

but I have not found a reference to the Data Mapper library.

I have quite many projects using the old dynamodb-data-mapper-js library, so I'm anxiously waiting to upgrade them to AWS SDK v3.

**Comment by ajredniwja** [comment]
Hey @kennu, thanks for reaching out and for your patience, there is a [feature request](https://github.com/aws/aws-sdk-js-v3/issues/1085) open in [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3/). I have had a word with the team, while there is no definite timeline for the feature, it will be added to V3 at some point in future. There are many reactions on the request there, I would definitely weigh in favor of it as well. Hope we see it soon. 

I would close this issue in favor of the above mentioned feature request as it will be tracked in the same.

**Comment by kennu** [comment]
Thanks @ajredniwja, I missed the existing issue while searching. I'll follow it from here on.

**Comment by d1bya** [comment]
Is there any update on DynamoDB Data Mapper support in AWS SDK v3?
