### ISSUE TITLE
TokenFileWebIdentityCredentials provider returns incorrect credentials during refresh when using assume role chaining.  

### ISSUE THREAD

**Issue by gabelazo** [aws/aws-sdk-js#3660]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
TokenFileWebIdentityCredentials provider returns incorrect credentials during refresh when using assume role chaining.  

Example credentials file:
```
[default]
source_profile = web-token
role_arn=arn:aws:iam::222222222222:role/account-b-role

[web-token]
web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token 
role_arn=arn:aws:iam::111111111111:role/account-a-role
```

During refresh the provider updates the credentials object every time it assumes the role, this is nonblocking, during this time the provider may return credentials for web-token profile instead of default profile.

We're traced issue to this function:
https://github.com/aws/aws-sdk-js/blob/309d053672af4b0b6a480d54960a402501f5c823/lib/credentials/token_file_web_identity_credentials.js#L125

it recursively traverses the role chain and updates the credentials each time.

Under a lot of load this causes IAM permission issues every hour during the credentials refresh.

**Is the issue in the browser/Node.js?**
Node.Js

**If on Node.js, are you running this on AWS Lambda?**
No,  we're running this on EKS.

**Details of the browser/Node.js version**
v12.21.0

**SDK version number**
v2.736

**Expected behavior**
Credentials should only be updated to the at the end of the assume role chain.

**Comment by vudh1** [comment]
Hi @gabelazo thanks for reaching out. Can you provide a reproducible code that you use?
