### ISSUE TITLE
Amazon Chime issue: "This service may not be available in the `eu-central-1' region"

### ISSUE THREAD

**Issue by A-Kazakova** [aws/aws-sdk-js#3661]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
Hi. I am trying to create a meeting with Amazon Chime using `aws-sdk`.

I am using the latest SDK version: `2.862.0`.

My flow of creating a meeting is the following:
- user clicks a button on the frontend;
- request is sent to the backend, where I handle it and call the `createMeeting` method of the `chime`;
- meeting is created via the AWS-SDK.

Unfortunately I am getting the following error:

```
code: "UnknownEndpoint"
hostname: "chime.eu-central-1.amazonaws.com"
message: "Inaccessible host: `chime.eu-central-1.amazonaws.com'. This service may not be available in the `eu-central-1' region."
originalError: {
  code: "NetworkingError"
  errno: -3008
  hostname: "chime.eu-central-1.amazonaws.com"
  message: "getaddrinfo ENOTFOUND chime.eu-central-1.amazonaws.com"
  region: "eu-central-1"
  retryable: true
  syscall: "getaddrinfo"
  time: "2021-03-12T07:21:58.023Z"
}
region: "eu-central-1"
retryable: true
time: "2021-03-12T07:21:58.024Z"
```

My Chime setup on the backend looks like this:

```typescript
AWS.config.credentials = {
  accessKeyId: AWS_KEYS.AWS_ID_KEY,
  secretAccessKey: AWS_KEYS.AWS_ACCESS_SECRET,
};
AWS.config.apiVersions = {
  chime: '2018-05-01',
};
const chime = new AWS.Chime({ region: 'eu-central-1' });
chime.endpoint = new AWS.Endpoint('https://chime.eu-central-1.amazonaws.com');
```

I call the `createMeeting` method like this:

```typescript
export const createMeeting = (token: string) => chime.createMeeting({
  ClientRequestToken: token,
  MediaRegion: AWS_KEYS.AWS_REGION,
}).promise();
```

I tried the Chime service with the default region (`us-east-1`), and **it works fine**.

I tried to remove the endpoint and / or API version from the AWS configuration, but it didn't help.

According to the documentation, the Amazon Chime service is supported in the region I am using (`eu-central-1`)

I am not running Amazon Lambda, just a Node server on EC2.

Node version is `14.16.0`.

AWS-SDK version is `2.862.0`.

**Comment by ajredniwja** [comment]
Hi @A-Kazakova, https://docs.aws.amazon.com/general/latest/gr/chime.html suggests that there is only a single endpoint. You might want to mentions `mediaRegion` see https://docs.aws.amazon.com/chime/latest/dg/chime-sdk-meetings-regions.html

I would recommend you to use the [Chime SDK](https://github.com/aws/amazon-chime-sdk-js) for chime related apps.
Check: https://aws.amazon.com/blogs/business-productivity/building-a-meeting-application-using-the-amazon-chime-sdk/

Please reach out if you have any other questions.
