### ISSUE TITLE
Version 2.863.0 has a bug

### ISSUE THREAD

**Issue by tl2chen** [aws/aws-sdk-js#3662]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Hi, I have components that have a dependency on `aws-sdk` in package.json with `^`, starting this afternoon, the latest version `2.863.0` was pulled into those packages and this error occurs when building these components:
```
14:36:33  Error: Cannot find module '.../node_modules/aws-sdk/lib/aws.js'. Please verify that the package.json has a valid "main" entry
```

We had to pin a specific `aws-sdk` version `2.862.0` to bypass this error and allow our builds to go through.

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v14.15.4

**SDK version number**
v2.862.0

**Comment by ajredniwja** [comment]
Hey @tl2chen thanks for opening this issue, I was not able to reproduce the problem. Looking at the [change log](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#28630), no changes were made that may cause this issue. Are you still seeing the problem with the latest version?
