### ISSUE TITLE
getSignedUrl sets the expiration time is invalid in Chrome

### ISSUE THREAD

**Issue by hongdeyuan** [aws/aws-sdk-js#3664]
**getSignedUrl expires  **
getSignedUrl sets the expiration time. If you don’t clear the browsing cache or quit browsing, the Chrome browser’s automatic caching mechanism will cause the generated url to not expire and always be available.

```
 s3.getSignedUrl("getObject", {
    Bucket: bucket,
    Key: key,
    Expires: expires,
    ResponseContentDisposition: 'attachment',
    VersionId: versionid ,
  })
  
  
```
Need to set now Date?

But, you clear Clear browsing data/cached pictures and files; next, Enter the URL again and it will expire? why?

**Comment by hongdeyuan** [comment]
has resolve ; set the ResponseCacheControl: 'no-store'；can resolved

**Comment by ajredniwja** [comment]
Hey @hongdeyuan glad that you found the solution, I would close this issue.
