### ISSUE TITLE
How about an AWS.S3.ManagedDownload method (Similar to the AWS.S3.ManagedUpload method)

### ISSUE THREAD

**Issue by rsryanstephen** [aws/aws-sdk-js#3668]
**Is your feature request related to a problem? Please describe.**
Given that there is a [2 Gb limit](https://github.com/aws/aws-sdk-js/issues/2916) on files that can be downloaded from an s3 bucket, we have a problem with performing multi-part downloads of large files from s3 to an Angular application hosted on the browser using `getObject()`. I know it is supposed to support multi-part downloads, but there are [outstanding bugs](https://github.com/aws/aws-sdk-js/issues/3667) on it (I've linked just one issue, there are others that I haven't had time to report). Even if the bugs get resolved and we manage to download the streams, I tested some downloaded streams by byte-range to see if I could combine them again into one file, but it doesn't play nicely with rxjs to combine the separate streams together again. For example, the rxjs `concat` method causes only the first range of bytes to be downloaded from the resulting Observable, and the rest of the concatenated stream gets cut off. I see that there are others experiencing this problem as well, as evidenced by this (still unanswered) [stack-overflow question](https://stackoverflow.com/questions/61099414/mulit-part-download-from-s3-bucket-with-angular) - No one has even attempted an answer, which is saying something..

**Describe the solution you'd like**
Since there is already an `AWS.S3.ManagedUpload` method available, could we not get an `AWS.S3.ManagedDownload` method to help with multi-part downloads > 2Gb?

**Describe alternatives you've considered**
I am aware of [this library](https://github.com/awslabs/s3-managed-download-js) created to manage multi-part downloads on Node.js, and there are others, but none of them [work on the browser](https://github.com/awslabs/s3-managed-download-js/issues/13) as far as I can tell, and I've tried a few of them.

**Comment by furick1** [comment]
+1
