### ISSUE TITLE
Javascript SDK has no anonymous way to call S3 APIs

### ISSUE THREAD

**Issue by dermidgen** [aws/aws-sdk-js#3669]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
https://github.com/aws/aws-sdk-js/issues/206

Has returned for v3 of the SDK.

**Comment by ajredniwja** [comment]
@dermidgen apologies for being late, you mean to use V3 of the SDK?

**Comment by dermidgen** [comment]
Yes, that project is pinned to v3 for ... "reasons" 🤷

**Comment by ajredniwja** [comment]
I was confused as this is V2 repo:

but with V3 you can do something like: 

```js
(async () => {
    const { S3 } = require("@aws-sdk/client-s3");
    const client = new S3({ region: "us-west-2" });
    
    client.middlewareStack.remove("awsAuthMiddleware");

    try {
        var resp = await client.listObjects({Bucket: 'bucket'});
        console.log(resp);
    }
    catch (error) {
        console.log(error)
    }
})();
```

**Comment by dermidgen** [comment]
@ajredniwja Derp! ZOMG; didn't realize it was a separate repo.  Thank you.
