### ISSUE TITLE
Vite apps will not build or run while using Amplify libraries with AWS-SDK

### ISSUE THREAD

**Issue by ErikCH** [aws/aws-sdk-js#3673]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Customers using the Amplify library are not able to use Vite, a native ESM no-bundle dev server, for Vue, React and Preact. After installing the package customers trying to run the dev server will get this error. 

```
Uncaught ReferenceError: global is not defined
    at index.js:43
    at aws-amplify.js?v=b14c5c6f:14
    at AuthenticationHelper.js:17
```

Users trying to build their app will get this error.

```
2: import { ProviderError } from "@aws-sdk/property-provider";
3: import { Buffer } from "buffer";
4: import { request } from "http";
            ^
5: /**
6:  * @internal
error during build:
Error: 'request' is not exported by __vite-browser-external, imported by node_modules/@aws-sdk/credential-provider-imds/dist/es/remoteProvider/httpRequest.js
    at error ...
```

After further research with the Amplify team we have found a workaround as illustrated in [7499](https://github.com/aws-amplify/amplify-js/issues/7499). 

This workaround explicitly tells Vite, which uses rollup, to alias the `runtimeConfig` to the `runtimeConfig.browser` file. 

We believe the problem is that Vite doesn't respect the `browser` field in `@aws-sdk/client-` package.json. This is a deliberate action made on the maintainers behalf, as outlined here.

[vitejs/vite#2329](https://github.com/vitejs/vite/issues/2329)
[okta/okta-auth-js#641](https://github.com/okta/okta-auth-js/issues/641)

This is what we learned as discussed from this comment [here](https://github.com/aws-amplify/amplify-js/pull/7970#issuecomment-803042026).

1. `@aws-sdk/credential-provider-imds` is only required by `@aws-sdk/credential-provider-node`
2. `@aws-sdk/credential-provider-node` is defined in `runtimeConfig.ts` within the `@aws-sdk/client-* ` packages.`

Is it possible for the `@aws-sdk/client` libraries to update their package.json's so Vite, and other ESM bundlers would correctly use the correct browser packages, and not the Node built-ins, since it's not respecting the `browser` field? The maintainer has recommended using `exports` as one possible solution.

Anecdotally, this issue might also exist with Snowpack, another ESM dev server, however, it has a workaround by using the `--polyfill-node` pollyfill argument, that Vite does not have. 

**Is the issue in the browser/Node.js?**
Browse

**SDK version number**
Example: latest

**To Reproduce (observed behavior)**
I have a repo with the work around [here](https://github.com/ErikCH/amplify-js/tree/hotfix/error-with-vite/.github/actions/bundle-size-action/vite). 
To reproduce the issue remove the alias from the vite config, and the `<script>` tag in the index.html.

Or create a new vite app

```
$ yarn create @vitejs/app
$ cd new-vite-app
$ yarn
```

Install amplify
```
yarn add aws-amplify
```

Add amplify to main.js file
```
import Amplify, { Auth } from 'aws-amplify';

Amplify.configure({});
```

Run the server and then try to build the server

```
yarn run dev
yarn run build
```

**Expected behavior**
Dev server and builds should run without errors, or needing to add global and exports into script tag for HTML.

**Comment by half2me** [comment]
any update on this? I have the exact same issue using SvelteKit

**Comment by woniupapa** [comment]
@ErikCH 
` <script>
    var global = global || window;
    var Buffer = Buffer || [];
    var process = process || {
      env: { DEBUG: undefined },
      version: []
    };
  </script>`

please add these code to index.html,maybe can fix it.

**Comment by woniupapa** [comment]
@ErikCH [https://stackoverflow.com/questions/66912795/in-vite-vue3-ts-project-aws-amplify-failed-to-resolve-components](url)

**Comment by sodatea** [comment]
Vite actually respects the `browser` field. But it only reads from the package root.

However, these problematic packages have more than one `package.json`.

For example, the `@aws-sdk/client-cognito-identity` has a `package.json` under the `dist/es/` directory. https://unpkg.com/browse/@aws-sdk/client-cognito-identity@3.20.0/dist/es/package.json
And that's what it expects the bundlers to read. It is respected in webpack but not in vite.

To be fair, this is undocumented behavior. The [browser field spec](https://github.com/defunctzombie/package-browser-field-spec) never says which `package.json` a bundler should read.

The SDK can fix this issue by removing the nested `package.json`s and use the full path in the root `package.json`:

```
"./dist/cjs/runtimeConfig": "./dist/cjs/runtimeConfig.browser",
"./dist/es/runtimeConfig": "./dist/es/runtimeConfig.browser"
```

**Comment by hkjpotato** [comment]
@sodatea thank you for the sync up and update on this.

attached the screenshot for reference:
![Screen Shot 2021-07-09 at 11 40 24 AM](https://user-images.githubusercontent.com/9324418/125103593-811aa000-e0aa-11eb-9e34-66e60edf27f0.png)

**Comment by half2me** [comment]
Any update on this?

**Comment by ajredniwja** [comment]
Related to https://github.com/aws/aws-sdk-js-v3/issues/2564

**Comment by 24jr** [comment]
I'm having this issue trying to build sveltekit site with vite and aws-amplify

**Comment by kaleabmelkie** [comment]
@24jr Have you tried these three steps mentioned in https://github.com/aws-amplify/amplify-ui/issues/268#issuecomment-953231595

This workaround for aws-amplify in SvelteKit has been working for me for sometime now. Let me know if I can help if you're facing any specific issues afterwards.

**Comment by 24jr** [comment]
@kaleabmelkie well that is for vue do you know how I do that in svelte?
this is what svelte.config.js was by default
```
/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte'
	}
};

export default config;
```

then I add the adapter like this
```
/** @type {import('@sveltejs/kit').Config} */
import adapter from '@sveltejs/adapter-node';

export default {
	kit: {
    target: '#svelte',
		adapter: adapter({
			// default options are shown
			out: 'build',
			precompress: false,
			env: {
				host: 'HOST',
				port: 'PORT'
			},
		})
	}
};
```
now I need to add the resolve part 
```
/** @type {import('@sveltejs/kit').Config} */
import adapter from '@sveltejs/adapter-node';

export default {
	kit: {
    target: '#svelte',
		adapter: adapter({
			// default options are shown
			out: 'build',
			precompress: false,
			env: {
				host: 'HOST',
				port: 'PORT'
			},
      resolve: {
        alias: {
          './runtimeConfig': './runtimeConfig.browser',
        },
      },
		})
	}
};
```
this is not working but something like this do you by chance know?

**Comment by kaleabmelkie** [comment]
The 'resolve.alias' should not go inside the adpater's options. It should be directly inside the 'kit' object.

**Comment by kaleabmelkie** [comment]
@24jr Here's how it might look for your config:

```cjs
/** @type {import('@sveltejs/kit').Config} */
import adapter from '@sveltejs/adapter-node'

export default {
  kit: {
    target: '#svelte',

    adapter: adapter({
      // default options are shown
      out: 'build',
      precompress: false,
      env: {
        host: 'HOST',
        port: 'PORT'
      },
    }),

    vite: {
      resolve: {
        alias: {
          './runtimeConfig': './runtimeConfig.browser',
        },
      },
    },
  },
}
```

**Comment by 24jr** [comment]
@kaleabmelkie Wow extremely helpful. I'm not well versed on what adapter is other than that is translates svelte code to a simple clean build of what is actually used. When you say without any adapters is there a built in default and dont need to import others necessarily? Like such? (which still gave `'request' is not exported by __vite-browser-external, imported by node_modules/@aws-sdk/credential-provider-imds/dist/es/remoteProvider/httpRequest.js` )

```
/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte'
	},
  vite: {
    resolve: {
      alias: {
        './runtimeConfig': './runtimeConfig.browser',
      },
    },
  },
};

export default config;
```
Now using adapter-node how you did successfully created the build files however there must be issue with how I'm using amplify-configure getting red 'Amplify.configure is not a function'
```
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-node
> Amplify.configure is not a function
```
which I am using in my __layout.svelte file like 
```
<script context="module">
  import "../app.css";
  import Layout from "$lib/views/Layout/index.svelte";
  import Amplify from "aws-amplify";
  import awsExports from "../aws-exports";
  Amplify.configure({ ...awsExports, ssr: true });
  import { initAuth } from "$lib/components/Auth/store";
  initAuth();
</script>
```
Is that how you did yours? there isnt like a main.js or anything

**Comment by kaleabmelkie** [comment]
I used a named `Amplify` import (instead of the default import) for the 'Amplify.configure is not a function' issue during previews.

See the last part of this comment: https://github.com/aws-amplify/amplify-ui/issues/268#issuecomment-953231595

**Comment by 24jr** [comment]
@kaleabmelkie I absolutely appreciate you. Everything is working great. Stay gold

**Comment by yogarasu** [comment]
I'm using vite + react + amplify and I'm having the same phenomenon.
I tried the script but it didn't improve.
Is there an effective solution or workaround?
```
 <script>
      var global = global || window;
      var Buffer = Buffer || [];
      var process = process || {
        env: { DEBUG: undefined },
        version: []
      };
</script>
```

**Comment by 24jr** [comment]
@yogarasu this is how mine is not sure if will work different than yours
```
<script>
  // Need this for aws amplify to not give error...idk
	// https://github.com/aws-amplify/amplify-js/issues/7499#issuecomment-804386820
	const isBrowser = () => typeof window !== 'undefined';
	const isGlobal = () => typeof global !== 'undefined';
	var exports = {};
	if (!isGlobal() && isBrowser()) {
		var global = window;
	}
</script>
```

**Comment by jiahao-c** [comment]
> <script>
>   // Need this for aws amplify to not give error...idk
> 	// https://github.com/aws-amplify/amplify-js/issues/7499#issuecomment-804386820
> 	const isBrowser = () => typeof window !== 'undefined';
> 	const isGlobal = () => typeof global !== 'undefined';
> 	var exports = {};
> 	if (!isGlobal() && isBrowser()) {
> 		var global = window;
> 	}
> </script>


It should not do `var exports = {};` It is irrelevant and may cause unknown issues.  Only the following will suffice. 
```html
<script>
  // Amplify need this to work. See https://github.com/aws/aws-sdk-js/issues/3673
  const isBrowser = () => typeof window !== 'undefined';
  const isGlobal = () => typeof global !== 'undefined';
  if (!isGlobal() && isBrowser()) {
    var global = window;
  }
</script>
```

**Comment by jiahao-c** [comment]
@ErikCH  Hi Erik, thanks for posting this issue, but it seems like the aws-sdk-js team have not had any fixes or updates for a while.  Maybe it is because they moved to the new repo https://github.com/aws/aws-sdk-js-v3 . Could you please repost/forward this issue in the new repo, so they can be more aware about this? 
Thanks so much!

**Comment by eric-2d** [comment]
Going to a year with this issue?
Considering switching to firebase as a much quicker resolution.

**Comment by youssef-mahdi** [comment]
> I'm getting this error:
> 
> `> 'request' is not exported by __vite-browser-external, imported by node_modules/@aws-sdk/credential-provider-imds/dist/es/remoteProvider/httpRequest.js`
I have the same problem did you manage to solve it ?

**Comment by mikhael28** [comment]
This works `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import resolve from "@rollup/plugin-node-resolve";
import { visualizer } from 'rollup-plugin-visualizer';

export default defineConfig({
    plugins: [
      react(),
      {
        ...resolve({
          preferBuiltins: false,
          browser: true,
        }),
        enforce: 'pre',
        apply: 'build',
      },
      visualizer()
  ],
});`

**Comment by Nizari** [comment]
I solved this issue thanks to this post:  https://stackoverflow.com/questions/70938763/build-problem-with-react-vitejs-and-was-amplify

In vite.config.js add:


```js
resolve: {
    alias: {
      './runtimeConfig': './runtimeConfig.browser',
    },
}

```

**Comment by wcheek** [comment]
> I solved this issue thanks to this post: https://stackoverflow.com/questions/70938763/build-problem-with-react-vitejs-and-was-amplify
> 
> In vite.config.js add:
> 
> ```js
> resolve: {
>     alias: {
>       './runtimeConfig': './runtimeConfig.browser',
>     },
> }
> ```

Thanks! This is actually what fixed the problem for me.

**Comment by justinfarrelldev** [comment]
Still having the issue even after trying all of the rest of the solutions. I've been using Vite@2.7.13 (but tried with Vite@latest as well) and React and it appears that Vite and the AWS SDK simply don't work together.

**Comment by elilambnz** [comment]
> I solved this issue thanks to this post: https://stackoverflow.com/questions/70938763/build-problem-with-react-vitejs-and-was-amplify

Using the full config in this answer also adds the necessary polyfills for `Error: AMQJS0010E WebSocket is not supported by this browser.` related errors when using the Amplify PubSub library.

**Comment by shinspiegel** [comment]
I'm having the same issue with this one, 
None of the work arounds helped me. My issue is related to the Cognito cannot find global object.
Does anyone have any insight on how to deal with this issue?

**Comment by clintfoster** [comment]
@shinspiegel I don't want to muddy the waters since so many good workarounds and descriptions have already been posted here, and my understanding of exactly what is going wrong is minimal. However, the following `index.html` hack from an earlier commenter worked for me in iterative Quasar/Vue3/Vite **dev** builds:

- https://github.com/aws/aws-sdk-js/issues/3673#issuecomment-1004521760

For **release** builds I had to implement a separate hack adapted from the following:

- https://github.com/aws-amplify/amplify-js/issues/9639#issuecomment-1049158526
- https://stackoverflow.com/questions/70938763/build-problem-with-react-vitejs-and-was-amplify

Since I'm using Quasar I had to make the change in `quasar.config.js` instead of directly in `vite.config.js`:

```
extendViteConf(viteConf, { isServer, isClient }) {
        viteConf.resolve.alias['./runtimeConfig'] = './runtimeConfig.browser'
      },
```

Periodically I see comments indicating the problem might have been fixed in amplify. I regularly update `aws-amplify`, `@aws-amplify/ui-components` and `@aws-amplify/ui-vue`. But the problem always returns if I remove the hacks.

The same goes for Vite. For example, over time I've seen comments saying a particular version fixes the problem, e.g. `2.9.9`. But when I remove the hacks the problem returns.

Note: I don't have a direct dev dependency on Vite since I'm using it within Quasar's build system. Instead, I depend on `@quasar/app-vite`. Thus, whenever it is updated I check to see if its transitive dependency on Vite was also updated. I haven't tried directly depending on a newer version of Vite.

**Comment by bilal-korir** [comment]
This solution worked for me. In case you're using Astro, which uses Vite, edit `astro.config.mjs` as follows:

```
import {defineConfig} from 'astro/config'
import rollupNodePolyFill from 'rollup-plugin-node-polyfills'
import react from '@astrojs/react'
import tailwind from '@astrojs/tailwind'
import {Amplify} from 'aws-amplify'
import awsExports from './src/aws-exports.cjs'

Amplify.configure(awsExports)

export default defineConfig({
  integrations: [react(), tailwind()],
  vite: {
    optimizeDeps: {
      esbuildOptions: {
        define: {
          global: 'globalThis',
        },
      },
    },
    build: {
      rollupOptions: {
        plugins: [rollupNodePolyFill()],
      },
    },
    resolve: {
      alias: {
        './runtimeConfig': './runtimeConfig.browser',
      },
    },
  },
}) 
```

Orginal answer can be found [here](https://stackoverflow.com/a/71064726/9343563)

**Comment by ccdilan** [comment]
add alias ` './runtimeConfig': './runtimeConfig.browser',` into `vite.config.ts`.

Then my `vite.config.ts` looks like this

```export default defineConfig({
plugins: [vue()],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
      "./runtimeConfig": "./runtimeConfig.browser",
    },
  },
});

**Comment by aliHamid98** [comment]
any one have a solution for this problem please this is very bad thing and amazon aws must solve it

**Comment by elilambnz** [comment]
@aliHamid98 a workaround has been posted above your comment for Vite which you can use until this has been resolved

**Comment by tinaboyce** [comment]
I have recently encountered the issues and attempted to try the solution above but it did not work. What worked for me is the following with a different polyfill module.

```
import { nodePolyfills } from 'vite-plugin-node-polyfills'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      './runtimeConfig': './runtimeConfig.browser',
    },
  },
  build: {
    rollupOptions: {
      plugins: [nodePolyfills()],
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      define: {
        global: 'globalThis',
      },
    },
  },
})
```

**Comment by lbowes** [comment]
I solved this by swapping

```var AWS = require('aws-sdk');```

with

```var AWS = require("@aws-sdk/client-s3");```

based on information from [this stackoverflow post](https://stackoverflow.com/questions/70931104/different-aws-sdks-and-the-use-of-in-require).

**Comment by hephaistos-trading** [comment]
Hello,

Is there any update on this ? 

I tried EVERY SOLUTION mentionned in this post, and none of them seem to work...

at first I had the following error:
`RollupError: node_modules/ccxt/js/src/static_dependencies/node-fetch/body.js (13:27): "promisify" is not exported by "__vite-browser-external", imported by "node_modules/ccxt/js/src/static_dependencies/node-fetch/body.js".
file: /codebuild/output/src2381540473/src/amplify-vite-react-template/node_modules/ccxt/js/src/static_dependencies/node-fetch/body.js:13:27`

And after implementing the solution from tina above, I still get:

`RollupError: node_modules/ccxt/js/src/static_dependencies/node-fetch/utils/referrer.js (7:9): "isIP" is not exported by "node_modules/node-stdlib-browser/esm/mock/empty.js", imported by "node_modules/ccxt/js/src/static_dependencies/node-fetch/utils/referrer.js".`

I'm honestly gettign desperate.

I spent hours on this, and nothing seems to work , any help would be amazing !!

**Comment by RanVaknin** [comment]
Hi everyone, 
This issue seems to be solved with a config option for Vite, and not something we can do on the SDK side. Please upgrade to JS SDK v3 where there is an ESM distribution for bundlers. 

Thanks,
Ran~
