### ISSUE TITLE
PropagateTags in the Service struct can sometimes also have the value of `NONE`, not just `TASK_DEFINITION` and `SERVICE`

### ISSUE THREAD

**Issue by thelmuxkriovar** [aws/aws-sdk-js#3677]
https://github.com/aws/aws-sdk-js/blob/2296bcd3dc3fb80d8df3f817ec063be44a02a377/apis/ecs-2014-11-13.normal.json#L4635-L4641

**Comment by ajredniwja** [comment]
Hey @thelmuxkriovar thanks for opening this issue, I am not sure if I understand the ask here correctly can you please follow one of the [issue templates](https://github.com/aws/aws-sdk-js/issues/new/choose)?
