### ISSUE TITLE
What is exact the expectation in which the aws-sdk will work inside webworker in React apps or other JS framework UI apps 

### ISSUE THREAD

**Issue by pradeeptakhatoi** [aws/aws-sdk-js#3678]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Hi, I am using AWS SDK to upload files to AWS S3 from my React App, the code working fine from the main thread but its not working from the webworker. I am getting below error 

```
var AWS = require("aws-sdk");

const { accessKeyId, secretAccessKey, region, bucket } = awsCredentials;
AWS.config.update({ accessKeyId, secretAccessKey });
AWS.config.region = region;
const s3Client = new AWS.S3();

const params = {
  Bucket: bucket,
  Key: directory + remainingFiles[i].name,
  Body: file,
};
await s3Client.upload(params, async function (err, data) {
  console.log("err", err);
  console.log("data", data);
});
```

![aws-sdk-error-inside-webworker](https://user-images.githubusercontent.com/6735669/112529230-0ebbd380-8dcb-11eb-9f80-d2f4ef0c716c.PNG)

I am read some articles but got no clear answer whether it's supported for the webworker or not.

Thank you!
Pradeepta

**Comment by pradeeptakhatoi** [comment]
Can someone please reply? It's a really important for my project.

**Comment by ajredniwja** [comment]
Hey @pradeeptakhatoi thanks for opening the issue and apologies for the delay here, the error you are getting is not from the SDK, I was able to run a react app and upload a file using the similar code, I didnt use WebWorker tho. 

You can check this [StackOverflow post](https://stackoverflow.com/questions/35374257/error-window-not-defined-in-node-js) if that solves the issue.

**Comment by pradeeptakhatoi** [comment]
Hi @ajredniwja sorry for the late reply. Its working absolutely fine from the main thread for all scenario but not working from the webworker on below scenario. 

When file size exceeds 5MB AWS SDK trying to use multipart upload instead of a straight forward upload. There we are facing the issue because for this the SDK using some method of window object but the window object is not available inside a webworker.

**Comment by ajredniwja** [comment]
Hi @pradeeptakhatoi again, I can try to narrow down the issue or find a workaround if you can set up some kind of reproduction repo. Would you be able to do that?
