### ISSUE TITLE
S3.upload with node to S3 bucket with cloudfront getting SignatureDoesNotMatch

### ISSUE THREAD

**Issue by danjiro** [aws/aws-sdk-js#3680]
I have a cloudfront distribution in front of my s3 bucket mapping the bucket to a subdomain.
In node I am trying to upload images to the bucket using the custom subdomain but am getting `The request signature we calculated does not match the signature you provided. Check your key and signing method`

AWS keys are set in another file

code: 
```
AWS.config.update({ region: config.aws.region });

const S3 = new AWS.S3({
  apiVersion: '2006-03-01',
  endpoint: 'assets.development.mydomain.com',
  s3BucketEndpoint: true,
  signatureVersion: 'v4',
  signatureCache: false,
});

S3.upload({
      Bucket: config.aws.userImagesBucketName,
      Key: s3filePath,
      Body: req.file.watermarkedImageBuffer,
      ACL: 'public-read',
      ContentType: req.file.mimetype,
    }, (error, data) => {
      if (error) {
        logger.error(error);

        return ResponseService.sendError(res, 422, error);
      }

      req.file.location = data.Location;
      req.file.key = data.Key;

      return next();
    });
  } catch (error) {
    logger.error(error);

    ResponseService.sendError(res, 422, error);
  }
```

For my cloudfront distribution ive set:
Allow HTTP methods: GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE 
A custome cach policy to forwards query strings and headers
Same with origin policy

If i get rid of `endpoint` and `s3BucketEndpoint` everything works fine. Just not sure where I'm going wrong...

Confirm by changing [ ] to [x] below:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

**Comment by peter-strauss** [comment]
If you have Origin Shield enabled, make sure you select "Managed-CORS-S3Origin" for Origin Request Policy under Behaviors.
