### ISSUE TITLE
AWS SDK upload file to S3 from webworker not working for large files

### ISSUE THREAD

**Issue by pradeeptakhatoi** [aws/aws-sdk-js#3687]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  

Hi I am using AWS SDK 2 to upload files to S3 from my ReactJs application using webworker. It's working fine for small files but started getting below error if file size exceed 5MB.

![aws-sdk-error-inside-webworker-2](https://user-images.githubusercontent.com/6735669/112931583-11575980-913a-11eb-804c-800779c54403.PNG)

**Comment by inaw-tihor** [comment]
i am also facing the same issue.

**Comment by pradeeptakhatoi** [comment]
Upload to S3 is really import for me & I am blocked due to above issue. Can someone please suggest any solution or workaround for this?

**Comment by ajredniwja** [comment]
Hey @pradeeptakhatoi thanks for opening this issue, I was able to successfully upload bigger files in a react project. Doesnt seem to be SDK error, can you share the code that you are using?

**Comment by ravindra-bytecipher** [comment]
> File upload to S3 is really important for my project & I am blocked due to above issue. Can someone please suggest any solution or workaround for this?

same issue
