### ISSUE TITLE
How to use DynamoDB Global Table with NodeJS?

### ISSUE THREAD

**Issue by MeRahulAhire** [aws/aws-sdk-js#3698]
I was looking for DDB global tables and wanted to know is there any way in to dynamically select the closest region in the SDK itself? Do we need Lambda edge for it?

**Comment by vudh1** [comment]
Hi @MeRahulAhire there is no specific way to auto select the closest region in SDK. You can check that [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-regions).
