### ISSUE TITLE
callback error parameter incorrectly typed as always an error

### ISSUE THREAD

**Issue by jribbens** [aws/aws-sdk-js#3699]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The typescript definition for the first parameter to callback functions for things like `S3.getObject()` says it is an `AWSError`. This is obviously wrong as when the call succeeds this parameter is not an error, it is `null`, so the typescript type should presumably be `AWSError | null`.

**SDK version number**
2.880.0

**To Reproduce (observed behavior)**
With code such as the below, eslint complains "Unexpected object value in conditional. The condition is always true."

```javascript
  s3.getObject({ ... }, function (err, data) {
    if (err) { ... }
  })
```

**Comment by ajredniwja** [comment]
Hi @jribbens, "The version 2 of the SDK is written in vanilla JavaScript. The type definition files were added in late 2016, when AWS SDK customers requested support after Angular 2 started recommending TypeScript as a primary language for application development. The internal components of the SDK are still written in vanilla JavaScript, and type definitions can go out of date this was the motivation to have [first class TypeScript support](https://aws.amazon.com/blogs/developer/first-class-typescript-support-in-modular-aws-sdk-for-javascript/) in [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3) and solve the problem in the same. Do give it a try and let us know what you think.

**Comment by jribbens** [comment]
> Hi @jribbens, "The version 2 of the SDK is written in vanilla JavaScript. The type definition files were added in late 2016, when AWS SDK customers requested support after Angular 2 started recommending TypeScript as a primary language for application development. The internal components of the SDK are still written in vanilla JavaScript, and type definitions can go out of date this was the motivation to have [first class TypeScript support](https://aws.amazon.com/blogs/developer/first-class-typescript-support-in-modular-aws-sdk-for-javascript/) in [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3) and solve the problem in the same. Do give it a try and let us know what you think.

I can't use v3 as it's not available in lambda functions.
