### ISSUE TITLE
How to implement AWS Signature V4 on managed blockchain (Ethereum) on browser

### ISSUE THREAD

**Issue by billyadelphia** [aws/aws-sdk-js#3701]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

Hello, I have followed the tutorial of how to implement the Ethereum Websocket url on aws managed blockchain to web3 using this doc. 
https://docs.aws.amazon.com/managed-blockchain/latest/ethereum-dev/ethereum-json-rpc.html 

But that doc only explain of how to implement it on node.js.
I need the node to be accessible on a browser.
But since native Websocket on browser doesn't have custom headers, I'm trying to implement the Auth using [Query](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html) but with no luck.
So how to implement  AWS Signature V4 using query on managed blockchain (Ethereum) on browser ?
Especially on Websocket connection ..

**Comment by ajredniwja** [comment]
Hi @billyadelphia thanks for opening this issue. SigV4 requires the credentials which should not be exposed in the browser. 
[The doc](https://docs.aws.amazon.com/managed-blockchain/latest/ethereum-dev/ethereum-json-rpc.html) mentions that. See the important section. It also mentions how you can use API Gateway for browser use. 

I'd close this issue now, please reach out if you have any other questions.
