### ISSUE TITLE
$./aws/config should not be read if AWS_CREDENTIAL_PROFILES_FILE points to a different location

### ISSUE THREAD

**Issue by pablodcar** [aws/aws-sdk-js#3702]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Having the environment variables set as `AWS_SDK_LOAD_CONFIG=1` and `AWS_CREDENTIAL_PROFILES_FILE=/some/path/.aws/config`, an error saying `Error: ENOENT: no such file or directory, open '$HOME/.aws/config'` is thrown.
Expected behavior: When `AWS_SDK_LOAD_CONFIG` env variable is set, config must be read from  `$AWS_CREDENTIAL_PROFILES_FILE` and `$HOME/.aws/config` is not required.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
```
node -v
v14.16.0
```

**SDK version number**
2.882.0

**To Reproduce (observed behavior)**
Having a configured ~/.aws directory:

1. Move the directory to somewhere else: `mv ~/.aws-bkp`
2. Execute
```
AWS_SDK_LOAD_CONFIG=1 \
AWS_CREDENTIAL_PROFILES_FILE=$(pwd)/.aws-bkp/config \
AWS_SHARED_CREDENTIALS_FILE=$(pwd)/.aws-bkp/credentials \
node -e 'require("aws-sdk")'
```
3. An error is thrown
```
$PROJECTS_DIR/node_modules/aws-sdk/lib/node_loader.js:106
          if (fileInfo.isConfig) throw err;
                                 ^

Error: ENOENT: no such file or directory, open '$HOME/.aws/config'
...
```
4. After creating an empty file in ~/.aws/config, it works as expected and the credentials in AWS_SHARED_CREDENTIALS_FILE (pointing to a different directory) are used.

**Expected behavior**
Not trying to read `$HOME/.aws/config` if AWS_CREDENTIAL_PROFILES_FILE and AWS_SHARED_CREDENTIALS_FILE are pointing to a different location.

**Comment by JadenSimon** [comment]
I believe the correct variable is `AWS_CONFIG_FILE` for changing the config file location ([reference](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html#setting-region-config-file)). Try using that instead of `AWS_CREDENTIAL_PROFILES_FILE` and see if it works.

**Comment by pablodcar** [comment]
@JadenSimon Thanks! my bad, AWS_CREDENTIAL_PROFILES_FILE should point to the credentials file and not to a config file. 
Maybe a minor bug then, but Is that an expected behavior? or should not try to load `~/.aws/confg` if it doesn't exist?

**Comment by JadenSimon** [comment]
@pablodcar 
You're welcome! Setting `AWS_SDK_LOAD_CONFIG` to 1 means the SDK will always expect a config file to exist. This is because it gives the config file a higher priority than the credentials file (so the credentials file does not need to exist). If you do not plan on using a config file, then you do not need to worry about changing `AWS_SDK_LOAD_CONFIG`.

**Comment by ajredniwja** [comment]
Closing this issue now, please let us know if you have any other questions.
