### ISSUE TITLE
S3 PresignedPost fails on Fargate when other read/write ops work fine

### ISSUE THREAD

**Issue by CaptainChemist** [aws/aws-sdk-js#3704]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I am running a Fargate container and notice that although I have full read/write access to a bucket using the node library, it will not let me create a presigned POST with the aws-sdk package but it does work with the @aws-sdk/s3-presigned-post package. The aws-sdk throws the error:

Error: Unable to create a POST object policy without a bucket, region, and credentials

I do not get this locally on my computer, I can run read/write and presigned POSTS using permissions that exactly match the IAM that I use on the task role for the container. Here is the policy that I'm creating with CDK:

```
    taskRole.attachInlinePolicy(
      new iam.Policy(this, `${clientPrefix}-task-policy`, {
        statements: [
          new iam.PolicyStatement({
            effect: iam.Effect.ALLOW,
            actions: ['s3:*'],
            resources: ['*'],
          }),
        ],
      })
    );
```

Here's how I call the function, I'm positive that the `bucket` and `key` are populated with sane values.
```
import aws from 'aws-sdk';

    const s3 = new aws.S3();
    const post: aws.S3.PresignedPost = await s3.createPresignedPost({
      Bucket: bucket,
      Fields: { key },
      Expires: 60,
      Conditions: [['content-length-range', 0, 5242880]],
    });
```

Interestingly, I can fix this by using the `@aws-sdk/s3-presigned-post` and `@aws-sdk/client-s3` libraries. Here's what that code looks like:

```
import { S3Client } from '@aws-sdk/client-s3';
const { createPresignedPost } = require('@aws-sdk/s3-presigned-post');

    const client = new S3Client({ region: 'us-east-1' });
    const s3 = new aws.S3();

    const post: aws.S3.PresignedPost = await createPresignedPost(client, {
      Bucket: bucket,
      Key: key,
      Expires: 60,
      Conditions: [['content-length-range', 0, 5242880]],
    });
```

**Is the issue in the browser/Node.js?**
Node.js 

**If on Node.js, are you running this on AWS Lambda?**
No, I'm running it in an ECS Fargate container

**Details of the browser/Node.js version**
Node 15 buster docker container

**SDK version number**
v2.863.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**
I expect that these two sdk libraries should behave the same- that is the aws-sdk should properly run the presigned POST function even without setting IAM keys using aws.configure().

**Comment by ajredniwja** [comment]
Hi @CaptainChemist, thanks for opening this issue, I am not quite able to reproduce this, I suspect that the credentials are not getting resolved, can you share what credentials you use? 

With that being said, the other two libraries that you use are from the [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3).  Its not ideal to mix both of those even though it works in this use case. Here is a [blog post](https://aws.amazon.com/blogs/developer/generate-presigned-url-modular-aws-sdk-javascript/) on how you can use presigned urls using V3 of the SDK.

**Comment by maxb94** [comment]
For anybody else that may be having this issue running the sdk on Fargate, I found that the following works:

```
  const post = await new Promise<S3.PresignedPost>((resolve, reject) => {
      this.S3Client.createPresignedPost(signingParams, (err, data) => {
        if (err) {
          return reject(err);
        }
        return resolve(data);
      });
  });
```
