### ISSUE TITLE
Transcribe StartTranscriptionJob Function bad OutputKey pattern

### ISSUE THREAD

**Issue by ZakariaNaaija** [aws/aws-sdk-js#3706]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The attribute OutputKey in the params of StartTranscriptionJob function requires the pattern [a-zA-Z0-9-_.!*'()/]{1,1024}$ where is not logic. the AWS amplify has a feature that allows you to upload a file to the S3 Storage using the cognito auth with a  protected level, that means it will add the file in a prefix like "protected/{cognito_id}" where cognito_id is REGION:GUID.

I have a requirement that I need to upload the transcription result in prefix of REGION:GUID, so the outputKey pattern will not allows me to do that. please reconsider this issue.

**Is the issue in the browser/Node.js?**
Browser/Node.js

**If on Node.js, are you running this on AWS Lambda?**
YES

**To Reproduce (observed behavior)**
OutputKey:"region:guid"

**Expected behavior**
It will accept the format.

**Comment by ajredniwja** [comment]
Hi @ZakariaNaaija thanks for opening this issue, unfortunately the SDK doesn't control the pattern for the params, it is validated by the Transcribe service itself, I can open a request with them internally to see if they can modify the pattern. 
Since this is documented [here](https://docs.aws.amazon.com/transcribe/latest/dg/API_StartTranscriptionJob.html) and is expected behavior I would like to mark this as a feature request.

**Comment by ajredniwja** [comment]
@ZakariaNaaija talking to Transcribe team they mentioned that the Transcribe follows the S3 recommendation of safe characters as mentioned [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) which do not include any colons. So unfortunately we wont able to accept this feature request. On another note I believe this may also break existing users and implementations. 

Please reach out if you have any other questions.
