### ISSUE TITLE
Adding X-Amz-Content-Sha256 to presigned URL

### ISSUE THREAD

**Issue by bhumilsarvaiya** [aws/aws-sdk-js#3708]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**How can I add `X-Amz-Content-Sha256` to presigned URL for `putObject` operation?**
 Previously, I've used `Content-MD5` with presigned URL and it works perfectly fine. This is similar to #2642. Just like mentioned in the issue, I'm too getting `SignatureDoesNotMatch` error every time! Please let me know if I'm doing something wrong here.

```js
let s3 = new AWS.S3({apiVersion: '2006-03-01', signatureVersion: 'v4'});

let sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

s3.setupRequestListeners = (request) => {
  request.on('build', (req) => {
    req.httpRequest.headers['X-Amz-Content-Sha256'] = sha256;
  });
}

function generateUploadURL() {
    return s3.getSignedUrlPromise('putObject', {
        Bucket: "",
        Key: "testing",
        // ContentMD5: "1B2M2Y8AsgTpgAmY7PhCfg=="
    })
}

generateUploadURL().then(function(url) {
  axios({
    method: "put",
    url,
    headers: {
      "X-Amz-Content-Sha256": sha256,
      // "Content-MD5": "1B2M2Y8AsgTpgAmY7PhCfg=="
    },
    data: ""
  }).catch(err => console.error(err.response.data));
}).catch(console.error);
```

**Comment by AllanZhengYP** [comment]
I think the existing logic it overly strict, the SDK should allow users to specify the SHA256 hash of the content. 

However, this is likely to be a breaking change for customers that include a request body when they generate the presigned url. The working URL will be broken suddenly because the presigned url consumer sends a different body than specified in presigned url.
