### ISSUE TITLE
S3 Upload consistent swallowing of stream without error

### ISSUE THREAD

**Issue by andrewcharnley** [aws/aws-sdk-js#3712]
Node v14.16, latest aws library.

I have a series of streams which end up piping data either to fs (for test) or to an s3 bucket. I'm testing with a 32Mb file. When using fs the process works, when using aws s3 it hangs at 327447 bytes. All I can think is that the S3 stream has corked somehow.

Since the fs equivalent is working my attention is in my equivalent wrapper for the s3. The credentials/zone are correct.

```
      /**
       * Given S3 SDK doesn't pipe initial async errors into the stream, wrapping is required.
       * In addition, sync errors in the SDK must always go to the stream.
       * @private
       */
      writeStream: fD => {
        const myStream = new stream.PassThrough()
        s3
          .upload({
            Bucket: bucket,
            Key: makeKeyName(fD.path, fD.name),
            Body: myStream
          }, (err) => {
            if (err) {
              myStream.emit('error', err)
            }
          })
        return myStream
      },
```

**Comment by andrewcharnley** [comment]
Looks like I've solved it, I'd removed the callback function by accident. I guess the upload function threw and because I'm not wrapping it it didn't get pushed onto the stream.

**Comment by ajredniwja** [comment]
Hi @andrewcharnley thanks for opening this issue, Is is possible for you to fill out the [issue template](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=guidance%2C+needs-triage&template=---questions---help.md&title=) in order for me to help you better? Im looking for code which I can use to reproduce the issue and the version of the SDK you are using.
