### ISSUE TITLE
Document S3 timeout and real-life usage

### ISSUE THREAD

**Issue by andrewcharnley** [aws/aws-sdk-js#3715]
The fs read stream uses autoClose:true and once the requested start:end has been read or file descriptor ends fires the end event. With the S3 library this doesn't happen and instead a timeout of 120s fires which causes an interesting problem when streaming data out.

https://github.com/aws/aws-sdk-js/blob/master/lib/http/node.js#L79-L85

Because the headers are already written I have to swallow the error. It doesn't make sense to log it as it's just noise that will happen on every connection. Although I could selectively inspect I'm writing generic code which should work with fs so I'm against doing this.

It's not clean though. If readStream fails to open the error will be swallowed with no return to the user (ideally should 500 etc). As this condition is imposed by the AWS implementation I think the correct usage should be documented otherwise it's open to interpretation, as I have done.

```
    const stream = readStream(file)

    // AWS has a 2m timeout, if this occurs we drop the error and destroy the stream
    // however it does mean real errors are swallowed as well.
    stream
      .on('error', e => {
        res.destroy()
      })
      .once('open', () => {
        res.writeHead(httpCode, headers)
      })
      .pipe(res)
```

**Comment by ajredniwja** [comment]
@andrewcharnley thanks for opening this issue, reached out to the docs team to review this. 
V474410264
