### ISSUE TITLE
The SDK is not suitable to run on any user's browser

### ISSUE THREAD

**Issue by nuthinking** [aws/aws-sdk-js#3718]
If for whatever reason the system using the library has the clock not in sync with the Network Time Protocol, the APIs start to fall apart.

- S3 generates `RequestTimeTooSkewed` and requires a bit of a [hack-ish solution](https://stackoverflow.com/questions/67183857/aws-s3-requesttimetooskewed-from-browser).
- MediaConvert generates network errors.

I assume other services will fail too. 

It's ok if AWS requires the system to have the clock in sync, but this only makes it suitable to run on controlled systems (i.e. servers) not directly in the final users browsers.

Until the SDK can't manage something as simple as an unsynced clock automatically, I would add a big warning in the Readme.

Steps to reproduce:
1. Change the computer date manually to 1 day before
2. Use the SDK

**Comment by ajredniwja** [comment]
The workaround mentioned here https://github.com/aws/aws-sdk-js/issues/399#issuecomment-233057244 should be used which should be a default in V3, but there is an ongoing issue (mentioned above) which the team is looking at.
