### ISSUE TITLE
Be able to easily query if an SNS topic exists given a topic name.

### ISSUE THREAD

**Issue by noam-alchemy** [aws/aws-sdk-js#3720]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to check if an SNS topic exists given it's name. Unfortunately the only way to get ARN from name is to call CreateTopic. I'd like to prevent bugs where I accidentally create new topics so I want to check if it exists beforehand. However, the only way to currently do that is to query for all topics and see if the one you're looking for is included. If there's more than 100 topics you have to paginate. It would be much more convenient to simply issue one request for this.

**Describe the solution you'd like**
A new endpoint in the SNS API such as GetTopicByName or CheckTopicExistsByName

**Describe alternatives you've considered**
Paginating across the ListTopics endpoint

**Additional context**

**Comment by rrrrrg** [comment]
Same issue.
