### ISSUE TITLE
s3.getObject slow compared to boto3.get_object on retrieving medium sized JSON files

### ISSUE THREAD

**Issue by loretoparisi** [aws/aws-sdk-js#3722]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The api `s3.getObject` is extremely slow respect to `boto3.get_object` on the same `(Bucket,Key, Region)` when retrieved a medium size `JSON` file (about ~3MB). This does not happen for small sized `JSON` (less than ~ 100K) file. See the code below.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
`v12.16.1`

**SDK version number**
`aws-sdk@^2.850.0`

**To Reproduce (observed behavior)**
```python
import boto3
import json
from time import time
from sys import getsizeof

s3 = boto3.client('s3')

bucket='xxxx'
key='xxxx'

start = time()
obj = s3.get_object(Bucket=bucket, Key=key)
objStr = obj['Body'].read()
end = time() - start
print('get_object took {} sec size {}'.format(end, getsizeof(objStr)))
```

and

```javascript
var AWS = require('aws-sdk');
var s3 = new AWS.S3();

var bucket='xxxx'
var key='xxxx'

var StartTime = new Date();
s3.getObject({ Bucket: bucket, Key: key },  function(err, data) {
    if(err) {
        console.error(err);
    } else {
     var contents = data.Body.toString('utf-8');
     console.log("s3.getObject took ", ((new Date()).getTime() - StartTime.getTime()), " msec size ", Buffer.byteLength(contents, 'utf8'), " B");  
   }
});
```

and the execution results are:

```bash
mbploreto:s3 loretoparisi$ python boto.py 
get_object took 101.2 sec size 1656345
mbploreto:s3 loretoparisi$ node aws.js 
s3.getObject took  90354  msec size  1656312  B
JSON.parse took  27
```

**Expected behavior**
Both the apis take almost the same download time on the same `(Bucket,Key, Region)` tuple.

**Screenshots**
-

**Additional context**
For a smalled sized `JSON` file, this issue is less relevant:

```bash
mbploreto:s3 loretoparisi$ python boto.py 
get_object took 1.59 sec size 4396
mbploreto:s3 loretoparisi$ node aws.js 
s3.getObject took  944  msec size  4363  B
JSON.parse took  0
```

**Comment by ajredniwja** [comment]
Hey @loretoparisi, thanks for opening this issue, is this behavior consistent? I was not able to reproduce the issue. I used a `4mb` file for the test. My results were: 

```
s3.getObject took  978  msec size  7250263  B

s3.getObject took  1296  msec size  7250263  B

s3.getObject took  865  msec size  7250263  B

s3.getObject took  820  msec size  7250263  B

s3.getObject took  1015  msec size  7250263  B
```

I also used logger like: `var s3 = new AWS.S3({logger: console});
`to try and do the same and got similar results.

**Comment by loretoparisi** [comment]
@ajredniwja thank you, did you get the same results for the python script?

**Comment by alexcasalboni** [comment]
Hey @loretoparisi 👋  

From the execution results, it looks like the Python script took `101.2 sec` (100+ seconds), while the Node.js script took `90354 msec` (90+ seconds). So it seems the Node.js is actually faster, isn't it?

**Comment by loretoparisi** [comment]
@alexcasalboni thanks Alex, I have corrected the test case, for the same JSON object I did N tests, and get the mean value of download time (and JSON parsing time):

```javascript
var metrics_download=[], metrics_parse=[], contents, start_time, elapsed_time;
  for(const it of [...Array(10).keys()]) {
    start_time = new Date();
    contents = await getObjectAsync(bucket, key);
    elapsed_time=((new Date()).getTime() - start_time.getTime()) / 1000.0;
    metrics_download.push(elapsed_time);
    start_time = new Date();
    JSON.parse(contents);
    elapsed_time=((new Date()).getTime() - start_time.getTime()) / 1000.0;
    metrics_parse.push(elapsed_time);
  }
  console.log("s3.getObject took ", arrayStatistics(metrics_download).mean, " sec, size ", contents.length, " B");
  console.log("JSON.parse took ", arrayStatistics(metrics_parse).mean, " sec");
```

Now, we have

```
s3.getObject took  2.5999000000000003  sec, size  1656299  B
JSON.parse took  0.0195  sec
```

while in Python

```
get_object took 3.0599112510681152 sec size 1656345
decoding took 0.05240511894226074 sec 
```

so it confirms what you noticed.

**Comment by alexcasalboni** [comment]
Thanks for sharing! And glad I could help :)
