### ISSUE TITLE
How to add headers with Managed Upload?

### ISSUE THREAD

**Issue by riku22** [aws/aws-sdk-js#3728]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Hello.

I'm uploading a file from a browser with Managed Upload.
I would like to add a header at this time, what should I do?
I wrote the following source with reference to the [PutObject example], but it doesn't work.

```
var s3client = new AWS.S3({
endpoint: <Endpoint URL>,
credentials: new AWS.Credentials(<AccessKey>, <SecretKey>, <SessionToken>),
region: <Region>
});
var uploadRequest = new AWS.S3.ManagedUpload({
partSize: 5*1024*1024,
queueSize: 2,
params: {
Bucket: <Bucket name>,
Key: <File name>,
Body: <Object of the file selected in the form>
},
computeChecksums: true,
service: s3client
});

uploadRequest.on('build', function() {
console.log("Add header");
uploadRequest.httpRequest.headers['X-My-Custom-Header'] = 'Test_header';
});

uploadRequest.send(function(err) {
if (err){
console.log('UPLOAD ERROR: ' + JSON.stringify(err, null, 2));
alert("Upload failed.");
}else{
alert("Successful upload.");
}
});
```

I would appreciate any advice.
Best regards.

[PutObject example]: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#build-event

**Comment by ajredniwja** [comment]
Hey @riku22 thanks for opening this issue, this doesn't work because `ManacgedUpload` is a class which is not of type `AWS.Request` where as `putObject` is of type `AWS.Request` as you can check [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property). Which means when the `build' listener is added nothing gets built into the request.
