### ISSUE TITLE
Use same environment variables as AWS CLI to pickup region/profile (or vice versa)

### ISSUE THREAD

**Issue by shafdog** [aws/aws-sdk-js#373]
The JS SDK uses `AWS_REGION` and `AWS_PROFILE` currently to set the default AWS region and credential profile. However, the AWS CLI uses a different set `AWS_DEFAULT_REGION` and `AWS_DEFAULT_PROFILE`. There is seemingly no other overlapping ones that work with both. 

Meaning if you use both the CLI and JS SDK, you have 4 environment variable to set. Maybe this intentional and certainly not a huge deal (since now I know which variables are used by what). But be nice if there were one set to work since its easy to forget to reset one when switching between the CLI and programming. And it is not obvious looking at `set | grep AWS` to know the `AWS_DEFAULT_*` ones are the CLI and `AWS_*` are for the JS SDK.

> Even better would be if the region default could be stored within with the profile file (`~/.aws/credentials`) so there be only one environment variable (or `AWS.config.profile` variable or `--profile` to set) to get a working configuration.

**Comment by lsegal** [comment]
@shafdog I would recommend opening an issue against the [aws/aws-cli](https://github.com/aws/aws-cli) to push for feature support for the `AWS_PROFILE` and `AWS_REGION` environment variables, as all other SDKs seem to be standardized around these variables. I don't think we would be going the other way (to `_DEFAULT_`). I'm going to mark this as closed for the env var support itself, but feel free to open a new issue for that last feature request at the end-- it would make things easier than tracking two different things in one issue.

Thanks for reporting!

**Comment by acinader** [comment]
man this one threw me for a loop.  should really document better that it is AWS_PROFILE and not AWS_DEFAULT_PROFILE
