### ISSUE TITLE
S3 ListBuckets Paginator Defined, but DNE

### ISSUE THREAD

**Issue by mattBrzezinski** [aws/aws-sdk-js#3731]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

I was looking through the [S3 Paginators](https://github.com/aws/aws-sdk-js/blob/82a02c317e2b71afec4eb379292855a07cbdfdd7/apis/s3-2006-03-01.paginators.json#L3) JSON definitions, and saw that it listed a paginator for `ListBuckets`. However it doesn't seem to be used, nor necessary anymore? Looking at the Boto3 definitions for paginators in the [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#paginators) it does not list one for `ListBuckets`.

**Comment by ajredniwja** [comment]
Hey @mattBrzezinski thanks for opening this issue, the one you look at for JS is simply a place holder to use whenever waiters are implemented. Will mark this is as a feature request.

**Comment by mattBrzezinski** [comment]
Ah I see, I'm more so curious as to why a placeholder exists if this functionality doesn't, and/or won't ever be implemented.

**Comment by mattBrzezinski** [comment]
Still relevant.
