### ISSUE TITLE
The support for Node.js <10.x in the AWS SDK for JavaScript (v2) will end on 2021-10-31

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js#3734]
Starting November 1 2021, the AWS SDK For JavaScript (v2) will no longer support the following end of life (EOL) Node.js runtime versions:

* Node.js 0.10 – EOL on 2016-10-31
* Node.js 0.12 – EOL on 2016-12-31
* Node.js 4.x – EOL on 2018-04-30
* Node.js 6.x – EOL on 2019-04-30
* Node.js 8.x – EOL on 2019-12-31

We encourage you to upgrade to Node.js 10.x or later. We recommend Node.js 14.x which was released on 2020-04-21 and became active LTS on 2020-10-27.

Modular AWS SDK for JavaScript (v3) is [generally available](https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available/), and it supports Node.js 10.x or later. You can also refer our [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html) to move your code to use v3, or visit our [self-guided workshop](https://github.com/aws-samples/aws-sdk-js-v3-workshop) which builds a simple note taking application using v2 and provides step-by-step migration instructions to v3.

More details in blog post [Announcing the end of support for Node.js <10.x in the AWS SDK for JavaScript (v2)](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-runtimes-10-x-in-the-aws-sdk-for-javascript-v2/)

**Comment by trivikr** [comment]
Closing as this issue was created as an announcement to be pinned.

**Comment by trivikr** [comment]
Used a short title, as previous title was cut in pinned post.

<details>
<summary>Before</summary>

![before](https://user-images.githubusercontent.com/16024985/116429405-b6795680-a7fa-11eb-98cc-92c2ff963034.png)

</details>

<details>
<summary>After</summary>

![after](https://user-images.githubusercontent.com/16024985/116429454-c133eb80-a7fa-11eb-91aa-bc32b4b7c7a6.png)


</details>

**Comment by NatPDeveloper** [comment]
Hm I'm on 12 and getting errors, unsure if this is related.

```
/root/.nvm/versions/node/v12.20.0/bin/zeus -> /root/.nvm/versions/node/v12.20.0/lib/node_modules/@liquidapps/zeus-cmd/index.js
> aws-sdk@2.894.0 postinstall /root/.nvm/versions/node/v12.20.0/lib/node_modules/@liquidapps/zeus-cmd/node_modules/aws-sdk
> node scripts/check-node-version.js
sh: node: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! aws-sdk@2.894.0 postinstall: `node scripts/check-node-version.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the aws-sdk@2.894.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-28T18_23_48_207Z-debug.log
```

**Comment by trivikr** [comment]
The error is:
```console
sh: node: command not found
```

@NatPDeveloper It looks like node is not installed in your workspace. Can you verify if node installed by running the following command?

```console
$ node -v
```

Search results https://www.google.com/search?q=postinstall+%22node%3A+command+not+found%22

**Comment by NatPDeveloper** [comment]
It's installed using nvm, I do not think this fix supports node version manager.  In my container node works fine:

```
docker run -m 8192m -it liquidapps/ci-builder:ubuntu
```

**Comment by rajatjain3289** [comment]
Hi @trivikr ,

I am facing same error as NatPDeveloper on 2.980. Any resolutions to this?

**Comment by omarioffline** [comment]
Error: Module not found: Error: Can't resolve 'util' in '/Users/hinddeeppurohit/Documents/battle-of-brands/node_modules/aws-sdk/lib' Did you mean './util'? Requests that should resolve in the current directory need to start with './'. Requests that start with a name are treated as module requests and resolve within module directories (/Users/hinddeeppurohit/Documents/********, node_modules). If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
[README.md](https://github.com/aws/aws-sdk-js/files/7280353/README.md)
