### ISSUE TITLE
Report an athena issue with React

### ISSUE THREAD

**Issue by simon-zhangmuye** [aws/aws-sdk-js#3738]
HI guys, I already imported the aws-sdk NPM package in my React app and then when I import Athena like this,
```
var AWS = require('aws-sdk');
var athena = new AWS.Athena();
```
As the documentation specified, but it will show an error like this:
`TypeError: AWS.Athena is not a constructor`
What is the solution to this?

**Comment by simon-zhangmuye** [comment]
It does not have an object of Athena
![image](https://user-images.githubusercontent.com/10706610/116804532-bfec2100-ab62-11eb-9160-1ca6bafea88e.png)

**Comment by AllanZhengYP** [comment]
Hi, I will close this as it duplicates with https://github.com/aws/aws-sdk-js/issues/3741. I will post more updates on that ticket.
