### ISSUE TITLE
Missing credentials on newly started EC2 instance

### ISSUE THREAD

**Issue by carlnordenfelt** [aws/aws-sdk-js#374]
Hi,

I am not at all sure if this is related to an issue in the SDK or if it comes from somewhere in AWS EC2/IAM and I have an ongoing case with the AWS support regarding the issue but I wanted your input on it as well as I haven't gotten anywhere with the AWS support as yet.

I have an EC2 instance that is spawned as part of an AutoScalingGroup.
The instance has an IAM role associated with it.
I am using version 2.0.18 of the aws-sdk.

On start up I run a node script from the LaunchConfiguration UserData that uses the nodejs aws-sdk to download files from S3. When the script is run I get an error message saying "Missing credentials in configuration" indicating that the instance has no credentials at all. I get the same result if I login to the instance and run the script directly from the shell.
At the same time another node script runs as a service and is launched automatically from rc.d and this script also downloads files from S3 and it works perfectly.

Now, to make this even more confusing, if I wait roughly 9 minutes and run the first script manually from the shell it works like a charm, no issues with credentials. 

I have experimented quite a lot with this issue and I am able to replicate it every time an instance launch.

I really don't know what to make out of this.
Clearly the IAM role gives sufficient permissions to download files from the bucket since I can download the files if I wait for 9 minutes and since one of the scripts works immediately after launch it appears as if the instance correctly recognizes the role it's been given.
I have also asked the meta data service for iam info and it return the assigned role excepted.

Any ideas, suggestions, troubleshooting tips are welcome here.
I am going to debug the inner workings of the S3 request (i.e. dig into "this" within the callback) first thing tomorrow morning and can add any findings from that.

For reference, the sdk and the S3 client are initiated like this in both scripts:
var AWS = require('aws-sdk');
AWS.config.update({ region: 'eu-west-1' });
var s3 = new AWS.S3({ apiVersion: '2006-03-01' });
s3.listObjects(...)

Cheers,
Carl

**Comment by thundergolfer** [comment]
@carlnordenfelt 

I've run into basically the same situation. What did AWS say? [What did you see?!](https://xkcd.com/979/)

**Comment by carlnordenfelt** [comment]
@thundergolfer This was a long time ago. I'm sorry to day that I can't recollect where this ended and I no longer have access to the environment nor the support case with AWS. I'm guessing it was resolved but I really don't know :(
