### ISSUE TITLE
How to verify the origin of a request from EventBridge

### ISSUE THREAD

**Issue by sinoz** [aws/aws-sdk-js#3740]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I have built a relatively simple service that exposes an API endpoint for AWS EventBridge to forward events to in the case of a new image having been pushed to AWS ECR. However, I was unable to find any documentation on verifying that the given request actually originates from EventBridge (what if an attacker tries to invoke this public endpoint with a potentially malicious request?).

To give an example of a request, it would be something like this:

```json
{
    "id": "123",
    "version": "0",
    "detail-type": "ECR Image Action",
    "source": "aws.ecr",
    "account": "123",
    "time": "1619170433421",
    "region": "eu-central-1",
    "resources": [],
    "detail": {
        "result": "SUCCESS",
        "repository-name": "my-image",
        "action-type": "PUSH",
        "image-tag": "0.0.1"
    }
}
```

It would be more ideal to query AWS for the existence of a request using the unique `id` field of this request. I have looked into EventBridge archives but having a bad time figuring out how to ask EventBridge for the existence of a request in one of its archives. Is this possible and if so, how?

**Comment by vudh1** [comment]
Hi @sinoz , thanks for reaching out. Can you clarify more what expected behavior you are looking for?
