### ISSUE TITLE
Unable to override httpOptions.connectTimeout in v2.894.0

### ISSUE THREAD

**Issue by ronit-chakraborty** [aws/aws-sdk-js#3743]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

I'm trying to upgrade the aws-sdk node package from [v2.68.0](https://github.com/aws/aws-sdk-js/tree/v2.68.0) to [v.2894.0](https://github.com/aws/aws-sdk-js/tree/v2.894.0) and I can't seem to override the `httpOptions.connectTimeout` property successfully. 

I'm attempting to instantiate a dynamoDb service object with the connectTimeout set to 0 but when we hit the condition checking the presence of the connectTimeout in [this](https://github.com/aws/aws-sdk-js/blob/a3312b18ede4022ab30e0985008f2596e9d76773/lib/http/node.js#L60) line of the AWS.NodeHttpClient#handleRequest method, the connectTimeout value is logged to be a value of 1000ms. It's not obvious to me why it resets or defaults and where that value of a 1000ms is set. Would appreciate some help in figuring out how to set the connectTimeout value to 0. 

`
const dynamoDb = new AWS.DynamoDB({
    region: 'us-east-1',
    httpOptions : { connectTimeout: 0 }
});
`

**Comment by ajredniwja** [comment]
Hi @ronit-chakraborty, thanks for opening this issue, I was not able to reproduce this. 
Can you try something like: 
```js
AWS.config.update({
    httpOptions: {
        connectTimeout: 0
    }
  })
  ```
 after instantiating the client.
