### ISSUE TITLE
AWS-SDK types Error while using s3 in Angular 6 

### ISSUE THREAD

**Issue by chetanapadmane1** [aws/aws-sdk-js#3745]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I am trying to use AWS-SDK in the Angular 6 project.

Install the below packages:
1. "aws-sdk": "^2.860.0"
2. "@aws-sdk/types": "^3.13.1"

Added tsconfig.json configurations mentioned at https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/#With_Angular
tsconfig.json File:
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "src",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "module": "commonjs",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es5",
      "es2015.promise",
      "es2017",
      "dom"
    ],
    "types": ["node"]
  }
}

Getting below types error while compiling the angular application:
![image](https://user-images.githubusercontent.com/47378267/116983559-e4253a80-ace7-11eb-96e0-d3893bbbb255.png)

**Comment by ajredniwja** [comment]
Hey @chetanapadmane1 thanks for opening this issue, I would suggest to use the [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3) as it is written in typescript to provide type safety. The types in V2 were hand written later. 

For this case, I can help you if you provide me with a reproduction code that I can use.
