### ISSUE TITLE
Environment variable AWS_NODEJS_CONNECTION_REUSE_ENABLED does not affect RDS Data API

### ISSUE THREAD

**Issue by IhostVlad** [aws/aws-sdk-js#3746]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Environment variable AWS_NODEJS_CONNECTION_REUSE_ENABLED does not affect RDS Data API

**Is the issue in the browser/Node.js?**
NodeJS 12

**If on Node.js, are you running this on AWS Lambda?**
AWS Lambda + Nodejs 12

**SDK version number**
2.890.0

**To Reproduce (observed behavior)**
1) Set Environment variable AWS_NODEJS_CONNECTION_REUSE_ENABLED to 1
2) Run sequential queries to RDS Data API via executeStatement https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#executeStatement-property
3) See that every sequential query have independent TCP connection
4) See that behaviour AWS_NODEJS_CONNECTION_REUSE_ENABLED does not work at all

**Expected behavior**
RDS Data API should respect AWS_NODEJS_CONNECTION_REUSE_ENABLED mode

**Comment by vudh1** [comment]
Hi @IhostVlad please confirm if this is still persisting with the latest version of SDK?
