### ISSUE TITLE
Does not install as root through NVM since v2.894.0

### ISSUE THREAD

**Issue by HughNobleBJSS** [aws/aws-sdk-js#3747]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When installing as root when NPM is installed through NVM this fails the following permissions error.

```
> aws-sdk@2.899.0 postinstall /root/.nvm/versions/node/v10.16.0/lib/node_modules/aws-sdk
> node scripts/check-node-version.js

sh: 1: node: Permission denied
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! aws-sdk@2.899.0 postinstall: `node scripts/check-node-version.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the aws-sdk@2.899.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

If I clone the repo and attempt to run the script manually this works fine.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v10.16.0

**SDK version number**
v2.894.0

**To Reproduce (observed behavior)**
It can be replicated by attempting to build the following Dockerfile

```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash \
    && export NVM_DIR="$HOME/.nvm" \
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && nvm install v10.16.0 \
    && nvm alias default v10.16.0 \
    && nvm use default \
    && npm install -g aws-sdk
```

**Comment by ajredniwja** [comment]
Hi @HughNobleBJSS thanks for opening this issue, from the error it seems to be a permissions issue with the NPM. I believe this happens when you run this from root and NPM creates a pseudo account to run it which off-course wont have permission. Might wanna check permissions or a couple of solutions can be found on stack on how to overcome this issue.
