### ISSUE TITLE
secretsmanager describeSecret returns empty result

### ISSUE THREAD

**Issue by martinerko** [aws/aws-sdk-js#3749]
As previously discussed in #3307 calling `describeSecret` in AWS lambda environment returns a different result than expected.
In my case, it's an empty object, no error raised, just an empty object without any properties.

@ajredniwja the original issue has been closed, but I can't find any resolution to this.
Any clues?

**Comment by ajredniwja** [comment]
@martinerko thanks for opening this issue, is it possible for you to fill out the [issue template](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=guidance%2C+needs-triage&template=---questions---help.md&title=)? 

The root cause in that case was different.
