### ISSUE TITLE
EndpointCache evicts the entire cache entry when one of the Endpoint expires

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js#3750]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
EndpointCache evicts the entire cache entry when one of the Endpoint expires.

https://github.com/aws/aws-sdk-js/blob/0dad03e9424e4c46ed9f10fe6b33e14bf58b2d85/vendor/endpoint-cache/index.js#L31-L40

**Is the issue in the browser/Node.js?**
All, tested in Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
`v14.16.1`

**SDK version number**
`v2.900.0`

**To Reproduce (observed behavior)**
Code:
```js
import AWS from "aws-sdk";

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const endpointCache = new AWS.EndpointCache(1000);
endpointCache.put("key", [
  // First endpoint expires in 3 seconds
  { Address: "expires-in-3-seconds", CachePeriodInMinutes: 0.05 },
  // First endpoint expires in one minute
  { Address: "expires-in-1-minute", CachePeriodInMinutes: 1 },
]);

// prints both endpoints
console.log(endpointCache.get("key"));

// Wait for 5 seconds.
await sleep(5000);
// prints undefined, as both endpoints are removed after first endpoint expires.
console.log(endpointCache.get("key"));

```

Output:
```console
[
  { Address: 'expires-in-3-seconds', Expire: 1620242083750 },
  { Address: 'expires-in-1-minute', Expire: 1620242140750 }
]
undefined
```

**Expected behavior**
```console
[
  { Address: 'expires-in-3-seconds', Expire: 1620242031694 },
  { Address: 'expires-in-1-minute', Expire: 1620242085694 }
]
[
  { Address: 'expires-in-1-minute', Expire: 1620242085694 }
]
```

**Additional context**
This issue was noticed while implementing Endpoint Discovery for AWS SDK for JavaScript (v3) in https://github.com/aws/aws-sdk-js-v3/issues/2211

**Comment by AllanZhengYP** [comment]
For context, the current behavior was to align with Java V1 SDK behavior, back when endpoint discovery only returns 1 endpoint.
