### ISSUE TITLE
PutObject on IOS 8

### ISSUE THREAD

**Issue by mihapirnat** [aws/aws-sdk-js#376]
I have problems with upload to S3 on IOS 8 Safari. This code works on desktop and android:

bucket.putObject(params, function (err, data) {
 ..
}

When I print variables to console, I get:
params:{\"Key\":\"somepath/.../somefilename\",\"Body\":\"...some text...\"}
(i removed data from Key and Body myself for this post, both are non-empty and look ok to me)

putObject returns error:
err:{\"message\":\"A header you provided implies functionality that is not implemented\",\"code\":\"NotImplemented\",\"time\":\"2014-10-06T11:16:17.545Z\",\"statusCode\":501,\"retryable\":true}"

I found  https://github.com/aws/aws-sdk-ios/issues/40  and in comments there: https://forums.aws.amazon.com/thread.jspa?messageID=571835&tstart=0

Using https://sdk.amazonaws.com/js/aws-sdk-2.0.18.min.js

What can I do about this?

Thank you for your reply....

**Comment by lsegal** [comment]
We've filed a Radar with Apple on this detailing the incorrect behaviors occurring in Safari, but at this point there is not much else we can do from the SDK side of things, so I am going to have to mark this as closed as a third-party issue. I would recommend filing a bug against Safari if you are still interested in pursuing this further and/or using one of the workarounds provided above. Thanks for bringing this to our attention!

**Comment by dland512** [comment]
I was having this problem when trying to delete an S3 object in a cordova app using the aws javascript sdk `deleteObject` method. Adding `ResponseCacheControl: 'no-cache'` when initially pulling the file down did the trick. Surprising that this issue still exists in iOS 3 years later.
