### ISSUE TITLE
Error: Connection timed out after 120000ms

### ISSUE THREAD

**Issue by BhargaviGadiraju** [aws/aws-sdk-js#3760]
Hello Team,

we are receiving "Error: Connection timed out after 120000ms" error in the below part of the node js code
 const stream = s3.getObject(options).createReadStream();
                                            stream.on('error', err => {
                                                loggerLevel.log('error', "stream error while s3.getobject" + err);
                                            }

This code was working from last 3years and now we got alert to upgrade ibm-cos-sdk npm version from 1.4.1 to 1.10.x and  also upgraded express from 4.16.3 to 4.17.1 please look in to this issue as high priority as it is impacting production.

Thanks
Bhargavi

Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

**Is the issue in the browser/Node.js?**
Browser/Node.js

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by BhargaviGadiraju** [comment]
Describe the bug
we are receiving "Error: Connection timed out after 120000ms" 


Is the issue in the browser/Node.js?
Node.js

If on Node.js, are you running this on AWS Lambda?
IBMCLOUD s cloudfoundry application

Details of the browser/Node.js version
NOdejs 10


To Reproduce (observed behavior)
Steps to reproduce the behavior (please share code or minimal repo)

const stream = s3.getObject(options).createReadStream();
stream.on('error', err => {
loggerLevel.log('error', "stream error while s3.getobject" + err);
}
1.connect to COS
2.pass the param for options bucket and object name
3.create stream to download file
4.while stream we observed Error: Connection timed out after 120000ms

Expected behavior
1.connect to COS
2.pass the param for options bucket and object name
3.create stream to download file
4.file will be downloaded

**Comment by Sunil6591** [comment]
I am facing the same issue, any luck fixing it @BhargaviGadiraju

**Comment by vudh1** [comment]
Hi @BhargaviGadiraju are you still experiencing this with the latest version of SDK. I am not able to reproduce this issue. Please check if your configuration for initializing S3 client is correct and comment with a sample of reproducible code that we can use to investigate this more.

**Comment by AnkitNassa** [comment]
> I am facing the same issue, any luck fixing it @BhargaviGadiraju

@BhargaviGadiraju facing the same. Could you share the fix if this was resolved.

**Comment by bmulcahy** [comment]
I am also facing the same issue. Manually uploading via console access to s3 works just fine. Uploading via aws-sdk does not. I am running the most recent version of the aws-sdk. File size is about 1 gb.

**Comment by allanjsx** [comment]
@vudh1 Why this issue is closed, and if there's a fix, can you please share the link to the version that contains the fix? Thanks!
