### ISSUE TITLE
Type not being inferred when calling data result of DynamoDB

### ISSUE THREAD

**Issue by edilson** [aws/aws-sdk-js#3761]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm using the DynamoDB with the AWS sdk but when I do a scan operation the response result it is not inferred, I'm also using Typescript.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
14.4.0

**SDK version number**
v2.905.0

**To Reproduce (observed behavior)**
```TS
const findFollowing = await dynamo
      .scan({
        TableName: this.tableName,
        FilterExpression: 'profile_main_id = :profile_main_id',
        ExpressionAttributeValues: {
          ':profile_main_id': profile_main_id,
        },
      })
      .promise();

    const { Items } = findFollowing.$response.data;

    const following = plainToClass(
      FollowingProfile,
      Items as FollowingProfile[]
    );

    return following;
```

The error says ```Property 'Items' does not exist on type 'void | ScanOutput'.```

**Expected behavior**
The Items attribute to be inferred on the respective type.

**Comment by ajredniwja** [comment]
Hey @edilson thanks for opening this issue. "The version 2 of the SDK is written in vanilla JavaScript. The type definition files were added in late 2016, when AWS SDK customers requested support after Angular 2 started recommending TypeScript as a primary language for application development. The internal components of the SDK are still written in vanilla JavaScript, and type definitions can go out of date.' I would recommend if you are using typeScript, you should check out [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3). Also a blog post on [First-class TypeScript support in modular AWS SDK for JavaScript](https://aws.amazon.com/blogs/developer/first-class-typescript-support-in-modular-aws-sdk-for-javascript/).

**Comment by edilson** [comment]
Thanks @ajredniwja , I'll switch the version then.
