### ISSUE TITLE
Random timeout while invoking long running lambda (cont.)

### ISSUE THREAD

**Issue by michaeltarleton** [aws/aws-sdk-js#3762]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Hi,

We are having this random timeout problem in our amazon Lambda that runs a node script that in turn uses aws-sdk (2.706.0) to invoke another lambda which takes ~6min.

Our lambda 1 will randomly timeout after 15 mins (900s) despite the lambda 2 having a log saying it ran successfully:

So looks like Lambda 2 completes successfully but Lambda 1 never gets the response (only if Lambda 2 takes ~6 mins or longer).

(seems to be related to https://github.com/aws/aws-sdk-js/issues/2558)

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Node 12_x (using cloudformation through CDK)

**SDK version number**
Example: v2.706.0

**To Reproduce (observed behavior)**

1. Create Lambda 1 that calls a Lambda 2
2. Create a 6 minute delay in Lambda 2, then respond w/ success
3. Run Lambda 1 (with timeout set to 15 mins)

**Expected behavior**

Lambda 1 should get the success response from Lambda 2.

**Additional context**

We have tried:
- adding keepAlive: true
- increasing timeouts

**Comment by vudh1** [comment]
Hi @michaeltarleton thanks for reaching out. Are you still experiencing this with the latest version of the SDK?

**Comment by michaeltarleton** [comment]
I have since changed companies but at the time I left this was still an issue.

**Comment by vudh1** [comment]
Feel free to reopen this issue if the problem is still persisting with the latest version of SDK.
