### ISSUE TITLE
aws-sdk@2.906.0 postinstall script fails when run via npx

### ISSUE THREAD

**Issue by koresar** [aws/aws-sdk-js#3763]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Run `npx s3-deploy` in your terminal. Fails.

```
npx s3-deploy './dist/**' --cwd './dist/' --region $AWS_DEFAULT_REGION --bucket $MY_BUCKET --filePrefix $MY_PREFIX
module.js:550
    throw err;
    ^
Error: Cannot find module '/root/.npm/_npx/42/lib/node_modules/s3-deploy/node_modules/aws-sdk/scripts/check-node-version.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-sdk@2.906.0 postinstall: `node scripts/check-node-version.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-sdk@2.906.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-13T09_58_26_026Z-debug.log
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
In Docker 
docker.io/library/node@sha256:a681bf74805b80d03eb21a6c0ef168a976108a287a74167ab593fc953aac34df

**Details of the browser/Node.js version**

It's inside a CI environment I don't have control of. But the Docker Hub image used is `node:8`.
UPD: Reproduced using `node:10` too.

**SDK version number**
2.906.0

**To Reproduce (observed behavior)**
Run `npx s3-deploy` in docker `node:10`. Fails in install aws-sdk.

**Expected behavior**
Does not fail.

**Additional info**
Running this way works fine:
```
npm i -g s3-deploy
s3-deploy ...params...
```

**Comment by misterjoshua** [comment]
I can reproduce this when trying to run AWS CDK (AWS SDK is a transitive dependency):

`docker run --rm -it node:14 npx -p aws-cdk cdk --version`

`docker run --rm -it node:12 npx -p aws-cdk cdk --version`

`docker run --rm -it node:10 npx -p aws-cdk cdk --version`

All fail with `MODULE_NOT_FOUND` when running `scripts/check-node-version.js` in the `aws-sdk` package `postinstall` script.

Here's an output:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/1/lib/node_modules/aws-cdk/node_modules/aws-sdk/scripts/check-node-version.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-sdk@2.903.0 postinstall: `node scripts/check-node-version.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aws-sdk@2.903.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-02T18_41_55_245Z-debug.log
Install for aws-cdk@latest failed with code 1
```

**Comment by phantomwhale** [comment]
I have this problem too - works fine running locally (as non-root user) but fails when running inside docker (as root)

In my situation I'm trying to run `elasticdump` which has dependency on aws-sdk,  and seeing the same stacktrace as @misterjoshua has written above (expect with version `2.920.0` now)

**Comment by sothychan** [comment]
Running into this too.  Any thoughts on how to resolve it?

**Comment by rix0rrr** [comment]
I would still recommend the JS SDK team fix this (especially since the JS SDK v3 uses the same mechanism and will fail in the same way).

A missing part of the story is that it fails when run via `npx` in a **Docker container**, when the NPX files are trying to be installed into `/root`.

As a workaround, setting the following environment variable seems to fix it:

```
NPM_CONFIG_UNSAFE_PERM=true
```

**Comment by akash1810** [comment]
Also running into this issue.

https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/ has helped me understand why setting the `NPM_CONFIG_UNSAFE_PERM` environment variable solves the issue within a Docker container.

After reading https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user, it looks like the `node` Docker image includes a `node` user.

We can use this to create working examples for @misterjoshua:

```console
➜ docker run -it --rm -u node node:14 npx -p aws-cdk cdk --version
1.113.0 (build 61e1f65)
```

Quite a few hoops, I'll admit. I'd love to see this resolved in a more obvious way, but not sure how.
