### ISSUE TITLE
opsworks.rebootInstance function is not working.

### ISSUE THREAD

**Issue by ankursachdeva11** [aws/aws-sdk-js#3764]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
opsworks.rebootInstance function is not working. EC2 instance should get restart.

**Is the issue in the browser/Node.js?**
Node.js

**To Reproduce (observed behavior)**
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/OpsWorks.html#rebootInstance-property
```js
var params = {
  InstanceId: 'STRING_VALUE' /* required */
};
opsworks.rebootInstance(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```
This method does not trigger reboot instance.

**Expected behavior**
It should reboot EC2 instance

**Comment by vudh1** [comment]
Hi @ankursachdeva11 thanks for reaching out. I cannot reproduce your problem. Are you still experiencing this with the latest version of SDK?
