### ISSUE TITLE
How can I implement unit test case for S3 callback function using JEST

### ISSUE THREAD

**Issue by BhattMeet98** [aws/aws-sdk-js#3765]
I have one s3 function and in this s3 function I have an another callback function.

Please refer below screenshot for better understanding.
![DD](https://user-images.githubusercontent.com/81350109/118276430-46025300-b4e5-11eb-8d3b-fa8f70f6e9b2.PNG)

So how can I write the test case for above both functions?

Anyone can help me for this?

Thanks in advance

Thanks & Regards
Meet Bhatt

**Comment by ajredniwja** [comment]
Hey @BhattMeet98 thanks for opening this issue can you please refer to https://github.com/aws/aws-sdk-js/issues/3076, which mentions a couple of recommendations on how you can mock the SDK.
