### ISSUE TITLE
Multipart upload progression seems returning wrong size for a piped stream

### ISSUE THREAD

**Issue by vincentwinkel** [aws/aws-sdk-js#3766]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Trying to upload a stream on S3 works well, but if we pipe another stream, the `httpUploadProgress` event returns a wrong size.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Node v8.11.2
Npm v5.6.0

**SDK version number**
v2.543.0

**To Reproduce (observed behavior)**
```js
const AWS = require('aws-sdk');
const fs = require('fs');
const path = require('path');
const { Transform } = require('stream');

(function() {
  // AWS configuration

  function getBucket() {
    return '...';
  }
  AWS.config.update({
    region: '...',
    accessKeyId: '...',
    secretAccessKey: '...',
    signatureVersion: '...',
  });

  const s3 = new AWS.S3({
    apiVersion: '2006-03-01',
    params: { Bucket: getBucket() }
  });

  // Create a stream from a file

  const stream = fs.createReadStream(path.join(__dirname, '/image.jpg'));

  // Pipe another stream?

  const transform = new Transform({
    transform: (chunk, encoding, done) => {
      done(); // Same issue with: done(null, chunk);
    }
  });
  stream.pipe(transform); // <---------- issue caused by this line

  // Upload to AWS S3

  const upload = s3.upload({
    ACL: 'public-read',
    Bucket: getBucket(),
    Key: 'image.jpg',
    Body: stream
  });

  upload.on('httpUploadProgress', function (e) {
    console.log('httpUploadProgress', e);
  });

  upload.send(function (err, result) {
    console.log('result', result);
  });
})();
```

**Expected behavior**
When the line `stream.pipe(transform);` above is commented, this is the expected behaviour. I receive 40002 that is the right size, as follow:
```
httpUploadProgress { loaded: 40002, total: 40002, part: 1, key: 'image.jpg' }
result { ETag: '"..."',
  Location: '...',
  key: 'image.jpg',
  Key: 'image.jpg',
  Bucket: '...' }
```
When the same line is uncommented, the size is wrong, as follow:
```
httpUploadProgress { loaded: 0, total: 0, part: 1, key: 'image.jpg' }
result { ETag: '"..."',
  Location: '...',
  key: 'image.jpg',
  Key: 'image.jpg',
  Bucket: '...' }
```

The weird thing is that at the end, I can see the uploaded file is **complete**.

**Additional context**
Here, the size is always 0, but on some context (coupled with [multer](https://github.com/expressjs/multer)) I may receive 0, or 16243. which is _quite_ similar to the multer highWaterMark, as follow (I log the file stream provided by multer):
```
FileStream {
_readableState: 
 ReadableState {
   objectMode: false,
   highWaterMark: 16384,
   buffer: BufferList { head: null, tail: null, length: 0 },
   length: 0,
   pipes: [ [Object], [Object] ],
   pipesCount: 2,
   flowing: true,
   ended: false,
   endEmitted: false,
   reading: true,
   sync: false,
   needReadable: true,
   emittedReadable: false,
   readableListening: false,
   resumeScheduled: false,
   destroyed: false,
   defaultEncoding: 'utf8',
   awaitDrain: 0,
   readingMore: true,
   decoder: null,
   encoding: null },
readable: true,
domain: null,
_events: 
 { end: [ [Function], [Object], [Object] ],
   error: [Function],
   limit: [Function],
   data: [ [Function: ondata], [Function: ondata] ] },
_eventsCount: 4,
_maxListeners: undefined,
truncated: false,
_read: [Function] }
```
I found this doc, don't know if it helps: https://nodejs.org/api/stream.html#stream_highwatermark_discrepancy_after_calling_readable_setencoding

I think this case occures when the stream is piped after the writeStream piped by multer.
I made a test with the multer local storage (also using a file stream), and I don't have any issue about the size.

**Comment by vincentwinkel** [comment]
Subsidiary request: it can be really nice to include the total size uploaded in the `send()` result object, avoiding to listen `httpUploadProgress` if we dont need to track the progress.

**Comment by ajredniwja** [comment]
Hey @vincentwinkel looking at it I think you might be right about stream getting piped after writeStream by multer. I would need to try to reproduce it and check whats going on.

**Comment by vincentwinkel** [comment]
I know you have a lot of tickets to proceed, but may I have an update about this potential issue, in order to find an alternative if needed, as we use this package on Production and it's blocking. Many thanks

**Comment by vincentwinkel** [comment]
It seems working by replacing this code:
```js
  const upload = s3.upload({
    Bucket: getBucket(),
    Key: 'private/image.jpg',
    Body: stream
  });
```
by this one:
```js
  const stream2 = new PassThrough();
  const upload = s3.upload({
    Bucket: getBucket(),
    Key: 'private/image.jpg',
    Body: stream2
  });
  stream2.on('error', console.log);
  stream.pipe(stream2);
```
