### ISSUE TITLE
Trying to stub an instance of an AWS client via SinonJS results in missing methods

### ISSUE THREAD

**Issue by eyalroth** [aws/aws-sdk-js#3767]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

Trying to create a stub instance of an AWS client using [Sinon.JS](https://github.com/sinonjs/sinon) fails to create the clients' class methods.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No (this is a test code)

**Details of the browser/Node.js version**
Node 14.16.1

**SDK version number**
2.825.0

**To Reproduce (observed behavior)**

Run the following mocha test:
```js
const sinon = require('sinon');
const AWS = require('aws-sdk');

describe('Foo', () => {
  const stubAwsClient = sinon.createStubInstance(AWS.Lambda);
  console.log(stubAwsClient.invoke); // undefined
});
```

**Expected behavior**

I expected Sinon to stub the `invoke` method of `AWS.Lambda`; instead, the stub has no such property (`undefined`).

I somehow managed to come up with this workaround:
```js
const stubAwsClient = sinon.createStubInstance(Object.getPrototypeOf(new AWS.Lambda()).constructor);
console.log(stubAwsClient.invoke); // [Function (anonymous)]
```

But I'm not really sure if this solution is appropriate, and it also requires the instantiation of an actual instance of the class.

**Additional context**

Sinon version: 9.2.4
Mocha version: 8.2.1

I Posted this earlier in Sinon.JS's repository (https://github.com/sinonjs/sinon/issues/2374). One of the contributors replied:
> Hi, I had a quick look at the source code for AWS Lambda and my quick impression is that this is a specific problem for this library, as it does some pretty funky stuff. We only assume a simple prototypal modal, and that does not seem to apply in this case.

**Comment by ajredniwja** [comment]
Hey @eyalroth thanks for opening this issue, I see this might be inconvenient but I am not sure if this can be treated as SDK bug, more of like a usage issue. What do you think? Any proposed fix? I can also discuss this with the team.

**Comment by eyalroth** [comment]
@ajredniwja I'm really not at liberty to decide whether this is a bug or a usage issue. That's up to whomever is working on this project :)

I'm not familiar with the internals of the SDK and I'm also relatively new to JS, so I can't really say what would be a potential fix and what would be the effort to implement it.

What I can do, perhaps, is to elaborate a bit about the usage issue here: I come from a statically-typed OOP background -- JVM languages mostly -- and in that kind of setting I expect to be able to stub/mock any kind of class, thanks to excellent mocking libraries such as [Mockito](https://site.mockito.org/). I had hoped to have the same ability in JS, however it seems that the class/hierarchy model is not as complete, or perhaps it is the mocking libraries that do not cover all the cases.

**Comment by ninthclowd** [comment]
I've been fighting this same issue all day trying to mock AWS.XRay.  I'm not sure whether this is an issue with sinon or AWS, but I can confirm that workaround @eyalroth posted does work.

**Comment by omarioffline** [comment]
var AWS = require('../core');
var fs = require('fs');
var STS = require('../../clients/sts');
var iniLoader = AWS.util.iniLoader;

/**
 * Represents OIDC credentials from a file on disk
 * If the credentials expire, the SDK can {refresh} the credentials
 * from the file.
 *
 * ## Using the web identity token file
 *
 * This provider is checked by default in the Node.js environment. To use
 * the provider simply add your OIDC token to a file (ASCII encoding) and
 * share the filename in either AWS_WEB_IDENTITY_TOKEN_FILE environment
 * variable or web_identity_token_file shared config variable
 *
 * The file contains encoded OIDC token and the characters are
 * ASCII encoded. OIDC tokens are JSON Web Tokens (JWT).
 * JWT's are 3 base64 encoded strings joined by the '.' character.
 *
 * This class will read filename from AWS_WEB_IDENTITY_TOKEN_FILE
 * environment variable or web_identity_token_file shared config variable,
 * and get the OIDC token from filename.
 * It will also read IAM role to be assumed from AWS_ROLE_ARN
 * environment variable or role_arn shared config variable.
 * This provider gets credetials using the {AWS.STS.assumeRoleWithWebIdentity}
 * service operation
 *
 * @!macro nobrowser
 */
AWS.TokenFileWebIdentityCredentials = AWS.util.inherit(AWS.Credentials, {

  /**
   * @example Creating a new credentials object
   *  AWS.config.credentials = new AWS.TokenFileWebIdentityCredentials(
   *   // optionally provide configuration to apply to the underlying AWS.STS service client
   *   // if configuration is not provided, then configuration will be pulled from AWS.config
   *   {
   *     // specify timeout options
   *     httpOptions: {
   *       timeout: 100
   *     }
   *   });
   * @see AWS.Config
   */
  constructor: function TokenFileWebIdentityCredentials(clientConfig) {
    AWS.Credentials.call(this);
    this.data = null;
    this.clientConfig = AWS.util.copy(clientConfig || {});
  },

  /**
   * Returns params from environment variables
   *
   * @api private
   */
  getParamsFromEnv: function getParamsFromEnv() {
    var ENV_TOKEN_FILE = 'AWS_WEB_IDENTITY_TOKEN_FILE',
        ENV_ROLE_ARN = 'AWS_ROLE_ARN';
    if (process.env[ENV_TOKEN_FILE] && process.env[ENV_ROLE_ARN]) {
      return [{
        envTokenFile: process.env[ENV_TOKEN_FILE],
        roleArn: process.env[ENV_ROLE_ARN],
        roleSessionName: process.env['AWS_ROLE_SESSION_NAME']
      }];
    }
  },

  /**
   * Returns params from shared config variables
   *
   * @api private
   */
  getParamsFromSharedConfig: function getParamsFromSharedConfig() {
    var profiles = AWS.util.getProfilesFromSharedConfig(iniLoader);
    var profileName = process.env.AWS_PROFILE || AWS.util.defaultProfile;
    var profile = profiles[profileName] || {};

    if (Object.keys(profile).length === 0) {
      throw AWS.util.error(
        new Error('Profile ' + profileName + ' not found'),
        { code: 'TokenFileWebIdentityCredentialsProviderFailure' }
      );
    }

    var paramsArray = [];

    while (!profile['web_identity_token_file'] && profile['source_profile']) {
      paramsArray.unshift({
        roleArn: profile['role_arn'],
        roleSessionName: profile['role_session_name']
      });
      var sourceProfile = profile['source_profile'];
      profile = profiles[sourceProfile];
    }

    paramsArray.unshift({
      envTokenFile: profile['web_identity_token_file'],
      roleArn: profile['role_arn'],
      roleSessionName: profile['role_session_name']
    });

    return paramsArray;
  },

  /**
   * Refreshes credentials using {AWS.STS.assumeRoleWithWebIdentity}
   *
   * @callback callback function(err)
   *   Called when the STS service responds (or fails). When
   *   this callback is called with no error, it means that the credentials
   *   information has been loaded into the object (as the `accessKeyId`,
   *   `secretAccessKey`, and `sessionToken` properties).
   *   @param err [Error] if an error occurred, this value will be filled
   * @see AWS.Credentials.get
   */
  refresh: function refresh(callback) {
    this.coalesceRefresh(callback || AWS.util.fn.callback);
  },

  /**
   * @api private
  */
  assumeRoleChaining: function assumeRoleChaining(paramsArray, callback) {
    var self = this;
    if (paramsArray.length === 0) {
      self.service.credentialsFrom(self.data, self);
      callback();
    } else {
      var params = paramsArray.shift();
      self.service.config.credentials = self.service.credentialsFrom(self.data, self);
      self.service.assumeRole(
        {
          RoleArn: params.roleArn,
          RoleSessionName: params.roleSessionName || 'token-file-web-identity'
        },
        function (err, data) {
          self.data = null;
          if (err) {
            callback(err);
          } else {
            self.data = data;
            self.assumeRoleChaining(paramsArray, callback);
          }
        }
      );
    }
  },

  /**
   * @api private
   */
  load: function load(callback) {
    var self = this;
    try {
      var paramsArray = self.getParamsFromEnv();
      if (!paramsArray) {
        paramsArray = self.getParamsFromSharedConfig();
      }
      if (paramsArray) {
        var params = paramsArray.shift();
        var oidcToken = fs.readFileSync(params.envTokenFile, {encoding: 'ascii'});
        if (!self.service) {
          self.createClients();
        }
        self.service.assumeRoleWithWebIdentity(
          {
            WebIdentityToken: oidcToken,
            RoleArn: params.roleArn,
            RoleSessionName: params.roleSessionName || 'token-file-web-identity'
          },
          function (err, data) {
            self.data = null;
            if (err) {
              callback(err);
            } else {
              self.data = data;
              self.assumeRoleChaining(paramsArray, callback);
            }
          }
        );
      }
    } catch (err) {
      callback(err);
    }
  },

  /**
   * @api private
   */
  createClients: function() {
    if (!this.service) {
      var stsConfig = AWS.util.merge({}, this.clientConfig);
      this.service = new STS(stsConfig);

      // Retry in case of IDPCommunicationErrorException or InvalidIdentityToken
      this.service.retryableError = function(error) {
        if (error.code === 'IDPCommunicationErrorException' || error.code === 'InvalidIdentityToken') {
          return true;
        } else {
          return AWS.Service.prototype.retryableError.call(this, error);
 
[amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc.zip](https://github.com/aws/aws-sdk-js/files/7287174/amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc.zip)

**Comment by omarioffline** [comment]
import { __assign, __awaiter, __generator } from "tslib";
import { SignatureV4 } from "@aws-sdk/signature-v4";
/**
 * A SigV4-compatible signer for S3 service. In order to support SigV4a algorithm according to the operation input
 * dynamically, the signer wraps native module SigV4a signer and JS SigV4 signer. It signs the request with SigV4a
 * algorithm if the request needs to be signed with `*` region. Otherwise, it signs the request with normal SigV4
 * signer.
 * Note that SigV4a signer is only supported in Node.js now because it depends on a native dependency.
 * @private
 */
var S3SignatureV4 = /** @class */ (function () {
    function S3SignatureV4(options) {
        this.sigv4Signer = new SignatureV4(options);
        this.signerOptions = options;
    }
    S3SignatureV4.prototype.sign = function (requestToSign, options) {
        if (options === void 0) { options = {}; }
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
[amazon-ecs-deploy-task-definition-master.zip](https://github.com/aws/aws-sdk-js/files/7287230/amazon-ecs-deploy-task-definition-master.zip)

                    case 0:
                        if (!(options.signingRegion === "*")) return [3 /*break*/, 2];
                        if (this.signerOptions.runtime !== "node")
                            throw new Error("This request requires signing with SigV4Asymmetric algorithm. It's only available in Node.js");
                        return [4 /*yield*/, this.getSigv4aSigner()]
                    case 1: return [2 /*return*/, (_a.sent()).sign(requestToSign, options)]
                    case 2: return [2 /*return*/, this.sigv4Signer.sign(requestToSign, options)]
