### ISSUE TITLE
s3.createReadStream timeout behaviour not consistent.

### ISSUE THREAD

**Issue by ryan65** [aws/aws-sdk-js#3771]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
we have code that streams data from an s3 file , using read/write stream objects and pipe.
the read stream is created by aws s3 sdk  `s3.createReadStream()`.
We encountered recently a case where we got an error from readStream due to timeout 
`"Connection timed out after 120000"`, and the error callback of the read stream was called, 
but then immediately got 'finish' event on the write stream and this seems to be inconsistent behavior.
I looked into your code and saw the reason
request.js  `createReadStream` function , 
in the `stream.on('error'... callback `
you call `lengthAccumulator.emit(end)`  which eventually causes `stream.end()` to be called which causes the writeStream finish event to be called. 

It looks like this is misleading behavior because finish should not be called after any errors.
Also , the behavior is not consistent, it doesn't always happen, sometimes finish event doesn't occur.
It Depends on timing, and if I received the headers.

**Is the issue in the browser/Node.js?**
No this is in server side nodejs.

**If on Node.js, are you running this on AWS Lambda?**
NO not running lambda.
**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
sdk version : v2.892.0

**To Reproduce (observed behavior)**
create small timeout.

**Expected behavior**
should call finish event on writeStream.

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @ryan65 thanks for opening this issue, can you please share a complete reproducible code as I was not able to really reproduce it on my end. Also would like to see what errors you get. We'll be open to making changes if it is a problem. Thanks
