### ISSUE TITLE
API gateway websocket postToConnection gets 410 but is successful

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws/aws-sdk-js#3773]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

I have done some research but I could not find the answer so far, I've already seen the posts on the forum and also a closed ticket here, so I'm opening this issue.

I am doing:

```js
apiGateway
  .postToConnection({
    ConnectionId: connectionId,
    Data: JSON.stringify(data)
  })
  .promise()
```

on a function that gets invoked. So what I do is when a user connects to the websocket, I save his/her connection id to the database so I know where to send web socket events later on. For some reason, I get the error:

```js
{
    "errorType": "GoneException",
    "errorMessage": "410",
    "code": "GoneException",
    "message": "410",
    "statusCode": 410,
    "time": "2021-05-20T12:20:39.812Z",
    "requestId": "9983a360-03e2-4f58-9f19-7145cd6ad088",
    "retryable": false,
    "retryDelay": 17.888389880377396,
    "stack": [
        "GoneException: 410",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)"
    ]
}
```

but the catch is the client actually receives the web socket event, therefore, the sending was successful, so I don't know whre the 410 is coming from.

**Is the issue in the browser/Node.js?**
Browser/Node.js

No.

**If on Node.js, are you running this on AWS Lambda?**

N/A

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

N/A

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

Latest, I think. I am using the aws-sdk that is available to all lambda functions instead of installing my own version.

**To Reproduce (observed behavior)**

1. Create websocket api gateway
2. When a user connects to the websocket, save the connection id to the database.
3. Few seconds later, send an event to that socket.
4. You'll get 410

**Expected behavior**

I should not get an error since the operation was actually successful.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by aprilmintacpineda** [comment]
Okay, I think I've figured it out.

**Comment by ajredniwja** [comment]
Quickly @aprilmintacpineda can you also share your findings here for someone who ever runs into this?

**Comment by aprilmintacpineda** [comment]
@ajredniwja the problem was I was not deleting stale connections from the database, so I when retrieve all connection ids related to a user, I also retrieve stale connections. You need to handle it and delete stale connections.
