### ISSUE TITLE
Cognito Identity Provider - Why can I get user pool users with sub/email/username but external providers only with username?

### ISSUE THREAD

**Issue by boy51** [aws/aws-sdk-js#3774]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I am using [AdminGetUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminGetUser.html) in my API to get information about users.

For users signed up directly in user pool, I can get users using their email, `sub` (from jwt) or cognito username. Its often necessary for me to get a user via their email.

However, I cannot get users signed up through federation like google through email, it responds with `User does not exist`.

I figured out that it will get me the user if I request it with `cognito:username`. This is inconvenient for me because I use email to get users with this method often.

I believe it has something to do with confirming the user, since their status is `EXTERNAL_PROVIDER` instead of `CONFIRMED`? I tried several things, such as confirming with Pre-signup hook, or confirming with AdminConfirmUser (which respons with `User cannot be confirmed. Current status is EXTERNAL_PROVIDER`). I can see external users already have confirmed email. I tried disabling phone number attribute mapping so that user wouldn't have unconfirmed phone number. Or mapping Username to something else.

I'm not sure what the solution is, am I supposed to use cognito username everywhere?  Or do I have to sign up the user differently?

Help is much appreciated, thanks

**Comment by alopezsanchez** [comment]
Hi @boy51! Did you get any conclusion? Can you share it? Thanks!
