### ISSUE TITLE
How to modify AWS Cognito JWT Tokens?

### ISSUE THREAD

**Issue by JayShamani** [aws/aws-sdk-js#3775]
Confirm by changing [ ] to [x] below:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I am using AWS Cognito for user management. I am getting too much information in JWT Token (in payloads). I do not want to pass it on to receiving API Client. So my question is how do I reduce the data or get the data which is only necessary for the user. Sending that much data is a security issue.

For example, I only want: 
```
"exp": 0000000000,
"at":  0000000000,
"username":"exampleUsername"
```
I don't find any documentation or console controls to modify the same.

**Comment by ajredniwja** [comment]
Hey @JayShamani can you please share a code example that you are using?
