### ISSUE TITLE
Allow JSON objects and arrays as Substitution values in Amazon Pinpoint API requests

### ISSUE THREAD

**Issue by HaydenMacDonald** [aws/aws-sdk-js#3776]
**Is your feature request related to a problem? Please describe.**
I find it frustrating that Amazon Pinpoint's API [only accepts substitution values that are arrays of strings](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#sendMessages-property). This prevents Pinpoint customers from being able to submit complex structures (e.g. array of objects) as substitution values for Pinpoint templates. 

**Describe the solution you'd like**
Allow Amazon Pinpoint to accept multiple types of input (i.e. objects, arrays, etc) in the `params.MessageRequest.Addresses[toAddress].Substitutions` property of `sendMessages()` request parameters. This would allow substitutions to be extremely flexible without having to update user endpoints or destructure complex data into arrays of strings (which may result in substitution/validation errors).

**Additional context**
I want to be able to submit API requests in the following structure:
![pinpointstructure](https://user-images.githubusercontent.com/30080315/119527290-16bad400-bd78-11eb-8532-8e8714b0c06b.png)

Unfortunately, submitting a request with this structure results in the following error:

```
2021-05-25T14:59:37.140Z
INFO There were 2 validation errors:
* InvalidParameterType: Expected params.MessageRequest.Addresses['jb46@dispostable.com'].Substitutions['errors'][0] to be a string
* InvalidParameterType: Expected params.MessageRequest.Addresses['jb46@dispostable.com'].Substitutions['errors'][1] to be a string
```

Please let me know if there is a known solution/problem related to this issue.

**Comment by gakinson** [comment]
+1 for this

**Comment by trustthe27** [comment]
+1 for this, too.

**Comment by trustthe27** [comment]
While we are waiting for this to be implemented, there is a workaround that can be applied with some Handlebars magic (see [Using message template helpers](https://docs.aws.amazon.com/pinpoint/latest/userguide/message-template-helpers.html)).

You have to prepare your data, by padding the parts to a fixed length with a character you don't use within the values (for this example I use a #).

```javascript
[
  '2###Senseo Mild 36 Pads 250g##########################Senseo##############',
  '4###Reibekäse leicht##################################Hofburger###########',
  '1###Chocochips Kuchen, Schoko#########################Bahlsen#############',
  '1###sebamed Duschgel Sportdusche######################Sebapharma##########'
]
```

With a combination of the Handlebars helpers `cut` and `substring` you can then extract your data in your Pinpoint Message Template again:

```html
<tr>
  <th>Quantity</th>
  <th>Name</th>
  <th>Brand</th>
</tr>
{{#each List.Items}}
<tr>
  <td>{{cut (substring this 0 3) "#"}}</td>
  <td>{{cut (substring this 4 53) "#"}}</td>
  <td>{{cut (substring this 54 74) "#"}}</td>
</tr>
{{/each}}
```

Hope that helps!

**Comment by rasharab** [comment]
+1 for this!

**Comment by Northduck** [comment]
+1. Couldn't believe it hasn't been implemented

**Comment by extemersonsantos** [comment]
Me too don't believe.

**Comment by trtin** [comment]
This would be reopened as we couldn't find a good solution....

**Comment by Northduck** [comment]
Our team attempted to fix it several times during these years, but we ended up with rendering a template using mustache.js beforehand

**Comment by trtin** [comment]
> Our team attempted to fix it several times during these years, but we ended up with rendering a template using mustache.js beforehand

Yep, our team stick with HandleBars hence we can migrate back to AWS pinpoint if they "upgrade" it sometime later.

```javascript
  const template = await client.send(
    new GetEmailTemplateCommand({
      TemplateName: templateName,
      Version: 'latest',
    }),
  );
  const _template = Handlebars.compile(template.EmailTemplateResponse.HtmlPart);

  const html = _template(templateData);
```
