### ISSUE TITLE
Why does selectObjectContent's payload for await loop forever when inside an async generator?

### ISSUE THREAD

**Issue by cdebergh** [aws/aws-sdk-js#3780]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I’m using the s3 aws-sdk to get multiple records in multiple files and upload the final result as one large file to s3. So the returned stream from getS3SelectObjectsStreams is given to s3.upload to create one file from the filtered events of tens of thousands of s3 files. the s3.selectObjectContent call returns a readable stream. I used .map to return a list of these read streams (tried just for looping and adding to an array but same result) then await all promises to that list in order to get the list of all readable streams. I then tried to for await loop through all the streams to get the chunks and return as one async iterable list of chunks in order to make a single read stream of all chunks (merge multiple read streams into one read stream).
Now, this for await works when inside the .map but once I do it outside after the map returns then it infinitely loops.

```
    async function* concatenateStreamsOrdered(streams) {
      for (const stream of streams) {
        for await (const chunk of stream) {
          yield chunk
        }
      }
    }
    async function getS3SelectObjectsStreams(bucket, sourceKeys, expression) {
      let readStreamPromises = 
        sourceKeys.map(
          async sourceKey => {
            let selectParameters = {
              Bucket: bucket,
              Key: sourceKey,
              Expression: expression, 
              ExpressionType: 'SQL', 
              InputSerialization: { 
                JSON: {
                  Type: 'DOCUMENT'
                }
              },
              OutputSerialization: {
                JSON: {
                  RecordDelimiter: ','
                }
              }
            };
            let result = await s3.selectObjectContent(selectParameters).promise();
            // for await (const event of result.Payload) {}
            return result.Payload;
          }
        );
      let readStreams = await Promise.all(readStreamPromises);
      const iterableStreams = await concatenateStreamsOrdered(readStreams);
      return stream.Readable.from(iterableStreams);
    }
```

So when I uncomment the for await that’s commented above, it works with immediate response no problem. When I comment it out like it is, the for await inside the concatenateStreamsOrdered function loops forever. My goal is just to merge these streams into one so if there's another way to accomplish that then I'd be happy doing so. As is, it works with the for await uncommented but then it loads all events into memory. I need to stream it so as not to exceed memory limitations of the nodejs 12 lambda.

Why does the for await loop forever? Does the stream from selectObjectContent not support use with async generators?

**Comment by vudh1** [comment]
Hi @cdebergh what SDK version are you using, do you still experience this with the latest version of SDK?

**Comment by vudh1** [comment]
closing this for no response.

**Comment by pankti-0627** [comment]
I am getting an error of "Object is not async iterable" while using Select Object Content on React native
any idea how to resolve error?
