### ISSUE TITLE
bucket name added incorrectly before endpoint during s3.HeadObject request (404 error)

### ISSUE THREAD

**Issue by Todd-SI** [aws/aws-sdk-js#3783]
Confirm by changing [ ] to [x] below:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

This issue I'm experiencing has similarly been experienced by aws-sdk-php users here: https://github.com/aws/aws-sdk-php/issues/2209, but I've not seen any discussions for js. 

I'm trying to perform a s3.headObject operation to determine/confirm if a file exists before then proceeding to do a deleteObject on the file. However, in the console I keep getting a 404 HEAD error that says (Not Found) at specified URL. 

This would be correct. There is in fact nothing at THAT url because the url is wrong. Somehow the bucket is being inserted before the endpoint in the url, not after as it should be, but I know the file exist because it's still being displayed on current screen from the correct url.

In the console, it reads >>> https://[my bucket].s3.us-east-1.wasabisys.com/[file key].png 

when it should be https://s3.us-east-1.wasabisys.com/[my bucket]/[file key].png 

![Screen Shot 2021-05-29 at 5 21 57 PM](https://user-images.githubusercontent.com/85038463/120085108-63b5e780-c0a3-11eb-953e-1726987d0e10.png)

I've double checked my parameters, bucket permissions and can't find a resolution. From the php discussion, it seems like they just reverted to a different version of aws-sdk that didn't generate the error. How or where would I go to figure out which previous version of aws-sdk didn't create this bug? 

Thanks in advance,

-T

**Comment by ajredniwja** [comment]
Hey @Todd-SI, thanks for opening this issue can you please share the code that you are using?

**Comment by Todd-SI** [comment]
My apologies for the tardy reply. Playing catchup. Your message came through while I was out of town. 

I'm using AWS SDK for JavaScript v2.1017.0. 

I did a little more investigating after I posted and I think I've identified the source of the issue, but I'd like another set of eyes to confirm. Searching the code, I discovered the HeadObject uses "requestUri" to build the url.  I think the issue is coming form 'Populate URI: function"  and the "else if (!service.config.s3BucketEndpoint)" block. 

Currently, as shown below, the endpoint is defined as:  _endpoint.host name = b + '.' + endpoint.hostname_
whereas, I think it should be: _endpoint.host name = endpoint.hostname + '/' + b_ 

![Screen Shot 2021-12-05 at 12 18 36 PM](https://user-images.githubusercontent.com/85038463/144756717-1b00bd3d-4999-4061-9ba0-68a7c1dcc08a.png)

When I manually revised the code to what I think, it appears to work as intended in the console, returning no errors, but I'm not sure if this will cause issues/errors elsewhere in other commands, given the populateURI function appears to be foundational to the code. Any thoughts or suggestions would be appreciated. 


Thanks! 

> Hey @Todd-SI, thanks for opening this issue can you please share the code that you are using?

**Comment by jcpage** [comment]
I am getting the same issue with the SDK when I set "forcePathStyle: true" in the S3ClientConfig.  Basically it is adding the bucketname twice to the path, ie ENDPOINT/BUCKETNAME/BUCKETNAME/KEY.

When I don't set forcePathStyle the path is correct, but the host becomes BUCKETNAME.ENDPOINT/KEY - since I am trying to use a local endpoint for testing this doesn't work.

It's definitely a bug since no matter what the setting is, adding the bucket to the path twice would never work.

**Comment by Todd-SI** [comment]
@jcpage  Ok, I think I've figured it out. The url construction we're trying to achieve is called path-style: https://s3.Region.amazonaws.com/bucket-name/key-name. (or wasabisys.com in this case). However, AWS is moving to a default virtual-hosted style url construction: https://bucket-name.s3.Region.amazonaws.com/key-name. From this doc, it looks like they plan to eventually deprecate path-style. >>>  Ref: https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html

So you can set forcePathStyle to true, but I think (*I think*) you also need to add the outposts parameter to explicitly format the endpoint uri to the desired url construction . 

AWS.config.s3outposts = { endpoint: 'https://{service}.{region}.amazonaws.com' };

Ref: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#outposts-property

Funny, I found this after deciding to cancel my wasabi account and go with AWS S3 because I was running into CORS issues with Wasabi. Really frustrating. I really wanted to like it, but I couldn't figure out how to make it work to meet my needs. Perhaps this note will help you realize a break through. 

Best
