### ISSUE TITLE
I am facing an issue(i.e. 4401 Error: Unauthorized) while establishing a connection to a web socket.

### ISSUE THREAD

**Issue by akash4chandran** [aws/aws-sdk-js#3786]
Created CreateAppInstanceUser using aws javascript SDK(v2.916.0).

I am facing an issue(i.e. 4401 Error: Unauthorized) while establishing a connection to a web socket on the client-side as a postman(v8.5.1), after creating AppInstanceUser.

![Screenshot 2021-06-02 at 17 52 20](https://user-images.githubusercontent.com/35295545/120479304-6bd79500-c3cb-11eb-980b-7d24e73241de.png)

_Originally posted by @akash4chandran in https://github.com/aws/amazon-chime-sdk-js/issues/1284#issuecomment-852981875_

**Comment by Bharathkumar1601** [comment]
I too facing the same issue using javascript.

> **JavaScript code:**
`const socket = new WebSocket(
  "wss://node001.ue1.ws-messaging.chime.aws/connect?userArn=arn:aws:chime:us-east-1:48559298****:app-instance/a5ca6551-e4f2-47e0-9d47-f685901a4bf9/user/Ak"
);
socket.onopen = function (e) {
  alert("[open] Connection established");
  alert("Sending to server");
  socket.send("My name is John");
};

socket.onmessage = function (event) {
  alert([message] Data received from server: ${event.data});
};

socket.onclose = function (event) {
  if (event.wasClean) {
    console.log(
      [close] Connection closed cleanly, code=${event.code} reason=${event.reason}
    );
  } else {
    // e.g. ser ver process killed or network down
    // event.code is usually 1006 in this case
    alert("[close] Connection died");
  }
};

socket.onerror = function (error) {
  alert([error] ${error.message});
};
`
![Screenshot 2021-06-02 at 18 05 43](https://user-images.githubusercontent.com/85233884/120480994-48154e80-c3cd-11eb-9cdd-6adfd8ad2e6a.png)

**Comment by vudh1** [comment]
Hi @akash4chandran, please follow [this template](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=) to help us understand better about this issue.
