### ISSUE TITLE
When using AWS_SDK_LOAD_CONFIG, incorrect credentials are selected when ~/.aws/credentials contains a default entry

### ISSUE THREAD

**Issue by Shogan** [aws/aws-sdk-js#3787]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

When using the environment variable `AWS_SDK_LOAD_CONFIG` set to a truthy value, and my config and credential files are configured as below:

**~/.aws/config**
```
[default]
region = eu-west-1
output = json

[profile test1]
region = eu-west-1
source_profile = testaccess
role_arn = arn:aws:iam::123456789012:role/Developer

[profile test2]
region = eu-west-1
source_profile = testaccess
role_arn = arn:aws:iam::123456789012:role/Developer

[profile testaccess]
region = eu-west-1
```

**~/.aws/credentials**
```
[testaccess]
aws_access_key_id = EXAMPLEACCESSKEY
aws_secret_access_key = examplesecretkey

[default]
aws_access_key_id = EXAMPLEACCESSKEY
aws_secret_access_key = examplesecretkey
```

Then aws-sdk service calls fail to execute operations with AccessDeniedException exceptions. For example:

```
AccessDeniedException: User: arn:aws:iam::123456789012:user/me@example.com is not authorized to perform: secretsmanager:GetSecretValue on resource: example-resource
```

To confirm, my code sets the process env vars like so:

```
process.env.AWS_SDK_LOAD_CONFIG = "true";
process.env.AWS_PROFILE = "test1";
```
If you remove the [default] entry from the ~/.aws/credentials file then everything works as expected.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No, running locally.

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v14.14.0

**SDK version number**
v2.896.0

**To Reproduce (observed behavior)**

Configure your ~/.aws/config and credentials files as above, where a source_profile in a profile configuration is used for an assumed role.

Set env vars your environment to:

```
process.env.AWS_SDK_LOAD_CONFIG = "true";
process.env.AWS_PROFILE = "test1";
```

Make any service call (ensure the service constructor is called/instantiated after setting the above environment variables).

The call should fail with an AccessDeniedException, but if you then modify your credentials file to remove the unused [default] credentials entry, then the call will succeed.

**Expected behavior**
Even if credentials file contains a [default] credentials entry, the credentials marked under the named profile in ~/.aws/credentials should be used. E.g. `test1` in the example above.

**Comment by ajredniwja** [comment]
Hi @Shogan thanks for opening this, one reason for this could be to include the source_profile of a profile with credentials that have permissions to assume the IAM role so that should look like something: see an example [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_profiles.html)
