### ISSUE TITLE
When InvocationType is Event, ClientContext is undefined

### ISSUE THREAD

**Issue by kaykhancheckpoint** [aws/aws-sdk-js#3792]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
Does anyone know why when you invoke a lambda function that has `InvocationType: Event` the ClientContext is dropped?

https://github.com/aws/aws-sdk-js/issues/1388#issuecomment-403466618

**Comment by vudh1** [comment]
Hi @kaykhancheckpoint , thanks for reaching out. Please make sure to use the latest version of SDK `2.1033.0.` Can you send a sample of code that you experienced `ClientContext is dropped`?
