### ISSUE TITLE
s3.getObject not returning up to date latest version of file

### ISSUE THREAD

**Issue by ewyllie** [aws/aws-sdk-js#3793]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When using getObject to retrieve a file from an S3 Bucket in a React Native app, the file returned is not up to date. The Bucket does not have versioning enabled. The file returned by the SDK has a 'LastModified' value of 2021-06-06T11:10:29.000Z.
When inspecting the same object using the AWS S3 web browser app, the last modified value reflects the most recent changes and shows June 9, 2021, 20:05:14 (UTC+01:00):

**Is the issue in the browser/Node.js?**
React Native

**SDK version number**
Example: v2.925.0

**To Reproduce (observed behavior)**
This React Native app is used to edit documents stored in S3, and an auto-save feature means that S3 objects can be updated frequently with multiple putObject requests in quick succession, although this happens via a REST API and Lambda Function. This seems to start happening when a lot of updates are made in a single day, but it's an intermittent and difficult to reproduce issue.

**Expected behavior**
S3 getObject should return the most up to date objects. The behaviour in the SDK should be the same as in the web browser app. If I can see that a file has been updated successfully and can view the changes in the AWS S3 web app then I expect those changes to be returned when using the SDK as well.

**Screenshots**

<img width="321" alt="Screenshot 2021-06-09 at 20 52 47" src="https://user-images.githubusercontent.com/52719982/121420166-abbaf100-c964-11eb-84a5-7290d9573030.png"> 
<img width="267" alt="Screenshot 2021-06-09 at 20 50 42" src="https://user-images.githubusercontent.com/52719982/121420075-947c0380-c964-11eb-92a7-ad9785bb4ab1.png">

**Comment by ajredniwja** [comment]
@ewyllie can you please share the code that you are using?
