### ISSUE TITLE
Node JS queries on Dynamo DB hangs forever using IAM roles

### ISSUE THREAD

**Issue by eugeniosegala** [aws/aws-sdk-js#3806]
I'm trying to connect my Node JS app to Dynamo DB from a EKS instance using IAM roles.

As you probably know, credentials should be passed automatically to the container in this case. As a prove of that, I tried to install the `aws-cli` within the same container and it's perfectly working (so the issue looks specific to `aws-sdk-js`). 

However, my Node JS script is hanging forever when I try to execute it and no errors are returned.

I checked few things: proxy, permissions (OS user), etc.. Nothing seemed related to this problem.

```
const { DynamoDBClient, QueryCommand } = require("@aws-sdk/client-dynamodb");

const ddbClient = new DynamoDBClient({
  region: "eu-west-1",
});

// Set the parameters
const params = {
  KeyConditionExpression: "itemRef = :itemRef",
  ExpressionAttributeValues: {
    ":itemRef": { S: "ABC" },
  },
  TableName: "my-sandbox",
};

const run = async () => {
  try {
    const data = await ddbClient.send(new QueryCommand(params));
    data.Items.forEach(function (element, index, array) {
      console.log(element);
      return data;
    });
  } catch (err) {
    console.error(err);
  }
};

run();
```

Any ideas?

**Comment by ajredniwja** [comment]
@eugeniosegala, are you using the latest version of the SDK in V3? Can you please fill out the [issue template?]( https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)

I'd also look at these [examples](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/dynamodb-examples.html)

Will transfer it to [V3 repo](https://github.com/aws/aws-sdk-js-v3) as this is V2 repo.
