### ISSUE TITLE
`AWS.ApiGatewayV2` / `AWS.APIGateway` method to filter out the deployments based on the stages

### ISSUE THREAD

**Issue by vinitshahdeo** [aws/aws-sdk-js#3809]
**Is your feature request related to a problem? Please describe.**

[AWS.ApiGatewayV2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayV2.html) & [AWS.APIGateway](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#getDeployments-property) has [methods](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#getDeployments-property) to list all the deployments for given `ApiId` and [list all the stages](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#getStages-property). But there isn't any way to get the stage specific deployments.

**Describe the solution you'd like**

Currently the parameters passed to the method supports `ApiId` , `limit` and pagination info. **Introducing a `stage` param to fetch the deployments for the input `stage` will be helpful.**

> **For REST APIs**
```js
var params = {
  restApiId: 'XXXXXXX',
  limit: 'XXXXXXXX',
  position: 'XXXXXX',
  stage: 'beta'
};
apigateway.getDeployments(params, function(err, data) {
  if (err) console.log(err, err.stack);
  else     console.log(data); // deployments for given stage 
});
```
> **For HTTP APIs**

```js
var params = {
  ApiId: 'XXXXXXXX',
  MaxResults: '100'
  NextToken: 'XXXXXX',
  Stage: 'Beta'
};
apigatewayv2.getDeployments(params, function(err, data) {
  if (err) console.log(err, err.stack);
  else     console.log(data);           // deployments for given stage
});
```

**Describe alternatives you've considered**
Can you also suggest any alternative for the same? My use-case is to filter out the deployments based on the stages.

**Additional context**
I'm using `aws-sdk` [v2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#getDeployments-property).

**Comment by ajredniwja** [comment]
Hey @vinitshahdeo thanks for bringing this up, the param has to be introduced by `API Gateway` team, i can forward this request to them but not sure about how soon it will be taken up. Will post updates as it moves forward. 

The alternative can only be to do it manually when you get the result, not tested it but just the idea to filter it by stage manually when you get all the data.
