### ISSUE TITLE
A method to filter out the deployments based on the stage

### ISSUE THREAD

**Issue by vinitshahdeo** [aws/aws-sdk-js#3810]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
[AWS.ApiGatewayV2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayV2.html) & [AWS.APIGateway](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#getDeployments-property) has methods to list all the deployments for given `ApiId` and list all the stages. But there isn't any way to get the stage specific deployments.

Is there any workaround(or API) for the same?

> Learn more at #3809

**Comment by ajredniwja** [comment]
Closing in favor of https://github.com/aws/aws-sdk-js/issues/3809

Please reach out if you have any other questions.
