### ISSUE TITLE
path

### ISSUE THREAD

**Issue by Tapetape** [aws/aws-sdk-js#3811]
Confirm by changing [ ] to [x] below:
- [ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

**Comment by ajredniwja** [comment]
Closing this due to lack of information.
