### ISSUE TITLE
Deperecated subpackages in aws-sdk 2.937.0

### ISSUE THREAD

**Issue by debdeep-das** [aws/aws-sdk-js#3812]
npm install aws-sdk installs the version 2.937.0
The package contains deprecated subpackages

npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The

While i could go inside aws-sdk package and change the version of uuid, buy querystring is deprecated, will the package query-string work?

**Comment by jimmywarting** [comment]
I think you should just use `URLSearchParams` instead

**Comment by debdeep-das** [comment]
> I think you should just use `URLSearchParams` instead

Thanks, but the issue here is dependencies within the aws-sdk package. If some component of aws-sdk package is referring to deprecated dependencies, there remains a question whether everything is working within the package

**Comment by JoeChapman** [comment]
> Install log:
> 
> ```
> npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> 
> npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> ```

This is still an issue, are there any plans to upgrade?

**Comment by gustawdaniel-acaisoft** [comment]
This is current state

```
  ├─┬ aws-sdk@2.1000.0
  │ └── uuid@3.3.2
  └── uuid@8.3.2
```

**Comment by jrencz** [comment]
@DigitalSeat-JJohnson merge of #3924 should make those warnings go away

**Comment by ajredniwja** [comment]
Closing this issue now. 
https://github.com/aws/aws-sdk-js/pull/3924

**Comment by ctepeo** [comment]
It's 2.1181.0 now and it still in dependence of the querystring, so it's not really solved

**Comment by davecarlson** [comment]
I just migrated to v3 as was sick of waiting

**Comment by ctepeo** [comment]
I would like to switch to the next major version as well, but we have an agreement on the project to follow only the latest official versions for production, so not a solution for me

**Comment by davecarlson** [comment]
> I would like to switch to the next major version as well, but we have an agreement on the project to follow only the latest official versions for production, so not a solution for me

v3 has been in GA since December: 

https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available/

**Comment by rmikhael** [comment]
Even after moving to v3, I am still getting the `npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
`

Here is my "npm list --depth=3"
`├─┬ aws-sdk@2.1276.0
│ ├─┬ buffer@4.9.2
│ │ ├── base64-js@1.5.1
│ │ ├── ieee754@1.1.13 deduped
│ │ └── isarray@1.0.0
│ ├── events@1.1.1
│ ├── ieee754@1.1.13
│ ├── jmespath@0.16.0
│ ├── querystring@0.2.0
│ ├── sax@1.2.1
│ ├─┬ url@0.10.3
│ │ ├── punycode@1.3.2
│ │ └── querystring@0.2.0 deduped
`

**Comment by davecarlson** [comment]
You are still including v2 that's why: 
```
Here is my "npm list --depth=3"
├─┬ aws-sdk@2.1276.0
```

If you have correctly installed v3, you should have something like:
 @aws-sdk/client-s3                  3.186.0
