### ISSUE TITLE
URL to access Dashboard / Metrics / Logs for `HTTP` & `REST` APIs

### ISSUE THREAD

**Issue by vinitshahdeo** [aws/aws-sdk-js#3816]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

- **I couldn't find an API which returns the URL to access associated dashboard/metrics/logs for a given REST/HTTP API.**
  - For logs, we receive Destination ARN but not the CloudWatch URL
  - For dashboard/metrics, I didn't receive any URL in the API response

- **Any link to access the all deployments or stage-specific deployments?**

As a workaround for the dashboard, I'm constructing the URL by looking at the pattern:
- REST APIs: `https://console.aws.amazon.com/apigateway/home?region=us-east-1#/apis/{{apiId}}/dashboard`
- HTTP APIs: `https://console.aws.amazon.com/apigateway/main/monitor/metrics?api={{apiId}}&region=us-east-1&routeKey=&stage=beta`

_Am I missing anything here?
Can you please suggest me the correct API/workaround for the same?_

**Comment by ajredniwja** [comment]
Related: https://github.com/aws/aws-sdk-js/issues/3818
