### ISSUE TITLE
URL to view CloudWatch Log Group

### ISSUE THREAD

**Issue by vinitshahdeo** [aws/aws-sdk-js#3818]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I couldn't find an [API](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_Operations.html) which can give us a link to access the logs for a given log group. **Is there a way to get a URL for given ARN of CloudWatch Log Group.**  

As a workaround, I can form the URL by looking at the pattern for given ARN.

ARN: `arn:aws:logs:us-east-1:XXXXXXXXXXXXXX:log-group:dummy:*`
URL: `https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/dummy`

Please suggest any workaround/API which can be helpful.

**Comment by ajredniwja** [comment]
Hey @vinitshahdeo I believe there is no API that'll return an URL with all the logs, the workaround you are using shoyld work. To get the data without the URL I would use [`filterLogEvents `](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatchLogs.html#getLogEvents-property) and filter using a pattern. https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html

Would mark this as a feature request and do some more research in the meantime.
