### ISSUE TITLE
getSignedUrlPromise/getSignedUrl in cn-north-1 region does not work as expected

### ISSUE THREAD

**Issue by ZhouLihua** [aws/aws-sdk-js#3820]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
In cn-north-1 region,
Call s3 service getSignedUrlPromise api to generate a signed url.  But when using the url in web browser, I get below error.
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>900</X-Amz-Expires>
<Expires>2021-07-07T10:28:15Z</Expires>
<ServerTime>2021-07-07T10:32:56Z</ServerTime>
<RequestId>5AV2DZN4VRCXRM9H</RequestId>
<HostId>
CRkr8f9FFLSOnKkhYN1+9dDvGQIbYa+zut0JMFBB+ev0FFktXIYvXcjlrnCpvzithBCyqRP4sB8=
</HostId>
</Error>

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
v14.12.0

**SDK version number**

* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
   aws-sdk@2.940.0
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**
When calling s3 getSignedUrlPromise/getSignedUrl, get a signed url. And when I type the url in web browsers,  I can get the s3 object show in the browser.

**Screenshots**

**Additional context**

**Comment by ZhouLihua** [comment]
Update the error message.
`<Error>
<Code>UnauthorizedAccess</Code>
<Message>You are not authorized to perform this operation</Message>
<RequestId>GM1DCVZQMJA06W21</RequestId>
<HostId>/HB7dJMw4MxrL2rAh1v6Nmbg60dXhBqd8nj0s1IIabAtDNFp0v0iCFtl1OhBAm9nYs6oUtdFv+I=</HostId>
</Error>`

**Comment by ajredniwja** [comment]
Can you share the code that you use and your use case? and how you set up your credentials and if they have the permissions.

**Comment by ZhouLihua** [comment]
`var AWS = require("aws-sdk");

import {
    AccessKeyId,
    SecretAccessKey
} from "../../consts";

var credentials = new AWS.Credentials({
    accessKeyId: AccessKeyId,
    secretAccessKey: SecretAccessKey
});

AWS.config.credentials = credentials;
AWS.config.update({
    region: 'cn-north-1',
    maxRetries: 3
});

var s3Client = new AWS.S3({
    apiVersion: '2006-03-01',
    correctClockSkew: true,
});

var params = {
    Bucket: 'bucket',
    Key: 'key'
};
s3Client.getSignedUrlPromise('getObject', params).then((data: any) => {
    console.log(data);
}).catch((error: any) => {
    console.log(error);
});`

**Comment by ZhouLihua** [comment]
It generates the signed url, but when using the url in web browser, it returns permission problem.

I tried the same code in region us-east-1, both the code and the url work fine.

**Comment by ZhouLihua** [comment]
> Can you share the code that you use and your use case? and how you set up your credentials and if they have the permissions.

I want to generate a signed url, and share it with others so I don't want to make my s3 bucket public.

**Comment by omarioffline** [comment]
this.sqs
      .sendMessage({
        QueueUrl: queueUrl,
        MessageBody: messageBody,
      })
      .promise();

**Comment by vudh1** [comment]
Hi @ZhouLihua thanks for reaching out. Want to check if this is persisting with the latest version of SDK?
