### ISSUE TITLE
Parse and allow client to access all API response error fields

### ISSUE THREAD

**Issue by wangchj** [aws/aws-sdk-js#3821]
**Is your feature request related to a problem? Please describe.**

Our API response error objects have extra fields that the client need to access. For example, the follow is an error response HTTP body. The `settingsValidationErrorsJsonBlob` is the extra field the caller needs to access.

```
{
    "errorType": "BadRequestException",
    "httpStatus": 400,
    "requestId": "...",
    "message": "...",
    "settingsValidationErrorsJsonBlob": "..."
}
```

When the caller gets the error from the SDK, it can only access standard fields like `message`, but cannot access custom fields like `settingsValidationErrorsJsonBlob`

**Describe the solution you'd like**

Please allow caller/client to access all error fields. We really just need to copy the fields into the error object.

**Describe alternatives you've considered**

Due to the fact that we have to maintain backward compatibility of public API, it's very hard for us to change the format of error objects. We're also unable to use SDK v3 due to other technical reasons. We have very limited options

**Additional context**

Please let me know if more info is needed. Thanks

**Comment by ajredniwja** [comment]
Hi there @wangchj, do you mean `settingsValidationErrorsJsonBlob` not returned or you cant access it? 

Can you share your code example?

**Comment by wangchj** [comment]
Hi @ajredniwja, please see code sample for AWS MediaConvert below. Note, this assumes AWS CLI credential is already configured.

```javascript
const MediaConvert = require('aws-sdk/clients/mediaconvert');

let job = {
  "Role": "arn:aws:iam::511591261676:role/service-role/MediaConvert_Default_Role",
  "Settings": {"Inputs": [{"FileInput": "s3://fake/fake.mp4"}]}
};

let client = new MediaConvert({region: 'us-west-2'});

client.describeEndpoints().promise()
.then(response => {
  let endpoint = response.Endpoints[0].Url;
  console.log(`API endpoint is ${endpoint}\n`);
  return endpoint;
})
.then(endpoint => {
  client.endpoint = endpoint;
  return client.createJob(job).promise();
})
.then(response => {
  console.log('Create job succeeded', response);
})
.catch(error => {
  console.log('Create job failed');
  console.log(`Error JS data type is ${typeof error}`);
  console.log(JSON.stringify(error, null, 2));
});
```

Running this script in `node` will print out the service API endpoint and the error response from the API. You can submit the same job without using the AWS JS-SDK (e.g., using Postman) and see the difference between the error object returned by the SDK and the raw error object returned from the API

**Comment by wangchj** [comment]
@ajredniwja could you check https://github.com/aws/aws-sdk-js/pull/3822 ?
