### ISSUE TITLE
stsConfig option for ChainableTemporaryCredentials is undocumented

### ISSUE THREAD

**Issue by Nevon** [aws/aws-sdk-js#3832]
**Describe the bug**
#2803 introduced the ability to override the default STS config from the `ChainableTemporaryCredentials` by adding a new `stsConfig` parameter to the `ChainableTemporaryCredentials` constructor. This additional parameter is present in the Typescript types, but not present in [the documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ChainableTemporaryCredentials.html#constructor-property)

Took me quite a bit of digging to figure out how I could use an HTTP proxy when assuming a role via `ChainableTemporaryCredentials`, until I started reading the implementation.

**Comment by ajredniwja** [comment]
@Nevon, thanks for bringing this up, reached out to the documentation team to make the appropriate changes. 

V441608905

**Comment by Nevon** [comment]
This is still an issue.

**Comment by aBurmeseDev** [comment]
Hi there - the documentation team has informed me that they do not plan to incorporate this minor change, as the JavaScript SDK v2 will soon be entering maintenance mode. They recommend upgrading to version 3 of the SDK. Please reach out on https://github.com/aws/aws-sdk-js-v3 if you have any questions. Closing this issue.
