### ISSUE TITLE
Got 'invalid_grant' when call Cognito API

### ISSUE THREAD

**Issue by thienna** [aws/aws-sdk-js#3836]
Confirm by changing [ ] to [x] below:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I am using AWS amplify SDK to connect to AWS Cognito. I have configured "App client settings" on User Pool, after using Amplify to log in successfully, I get 3 tokens: "id token, refresh token, access token". Then I use the "refresh token" to call API with Postman to "oauth2/token" to get new tokens but I got an error: 
HTTP 400
```
{
    "error": "invalid_grant"
}
```
My curl (does not have authen header because i dont use "client secret"):
```
curl --location --request POST 'https://my-domain.auth.ap-southeast-1.amazoncognito.com/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=refresh_token' \
--data-urlencode 'client_id=abcxyz' \
--data-urlencode 'refresh_token=my_refresh_token'
```
Docs links:
- https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html
- https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js#sign-in
Please help.

**Comment by ajredniwja** [comment]
@thienna thanks for opening this issue, seems similar to https://github.com/aws-amplify/amplify-js/issues/6041

Amplify-js repo would be the right place to ask more specific questions. 

Thanks
