### ISSUE TITLE
s3 interface initialization inside or outside the function

### ISSUE THREAD

**Issue by s1mrankaur** [aws/aws-sdk-js#3840]
Confirm by changing [ ] to [x] below:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

We currently have

```
export function s3Call(action: string, params: any): Promise<any> {
const s3 = new AWS.S3();
return s3[action](params).promise();
}
```

I tried to change it to

```
    const s3 = new AWS.S3();
    export function s3Call(action: string, params: any): Promise<any> {
    return s3[action](params).promise();
    }
```

but on running the unit test, ran into the following error

`> failed to get the current sub/segment from the context new s3
`
[![enter image description here][1]][1]

The unit test itself is pretty simple:
```

    describe("uploadImage tests", () => {
    it("should return correct image url", async () => { process.env.IMAGE_UPLOAD_BUCKET_NAME = 'TestBucket'; process.env.AWS_REGION = 'us-west-2';
    const putObject = jest.fn().mockImplementation(() => Promise.resolve({})); 
    AWSMock.mock('S3', 'putObject', putObject);
    const bucketUrl = https://${process.env.IMAGE_UPLOAD_BUCKET_NAME}.s3-${process.env.AWS_REGION}.amazonaws.com/; 
    const result = await uploadImage(imageData, bucketUrl); expect(result).toContain(process.env.IMAGE_UPLOAD_BUCKET_NAME); 
expect(result).toContain(process.env.AWS_REGION); 
AWSMock.restore('S3');   }); });

```
How can the s3 interface be initialized once? and why do we see this error once when s3 initialization is taken out of the function?

  [1]: https://i.stack.imgur.com/COmaw.png

**Comment by vudh1** [comment]
Hi @s1mrankaur thanks for reaching out. S3 interface needs to be initialized inside the function in this case because the test function needs to use the instance created.
