### ISSUE TITLE
Delete a usage plan using the SDK

### ISSUE THREAD

**Issue by zgheibali** [aws/aws-sdk-js#3841]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I tried to create a usage plan using the SDK, and then After that, I tried to delete the usage plan using the ID generated by the previous call. However, I keep on getting an error

BadRequestException: Cannot delete Usage Plan USAGE_PLAN_ID_HERE because there are API Stages associated with it, including API_ID_HERE:test

**Is the issue in the browser/Node.js?**
Browser/Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
1- create a usage plan with the params below
  
name: "my_usage_plan",
apiStages: [
apiId: "API_ID_HERE",
stage: "test"
]
  
2- delete the usage plan 

usagePlanId: USAGE_PLAN_ID
  
I kept getting an error in step #2 saying: 
BadRequestException: Cannot delete Usage Plan USAGE_PLAN_ID_HERE because there are API Stages associated with it, including API_ID_HERE:test

**Expected behavior**

the expected behavior is to be able to delete the newly created usage plan using the usage plan id

**Screenshots**

**Additional context**

what I tried to fix this issue:
1- I tried deleting the test stage on the API gateway
2- I ran the delete usage plan function with the same usage plan id 

the usage plan got deleted successfully without any error, however, I should be able to delete it without the need to delete a stage and re-creating it after.

**Comment by ajredniwja** [comment]
Hi @zgheibali thanks for opening this issue, you'd need to use: `updateUsagePlan` with `op: 'remove'` to remove the API stages and then call the `deleteUsage` function. 

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#updateUsagePlan-property

Closing this issue now, feel free to reach out/tag me/re-open if you have any other questions.
