### ISSUE TITLE
The EC2 requestSpotInstances documentation in V2 is wrong

### ISSUE THREAD

**Issue by JoseRolles** [aws/aws-sdk-js#3842]
The underlying EC2 [RequestSpotInstances API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestSpotInstances.html) property `TagSpecification` only supports tagging the `spot-instances-request` itself and not the instances or volumes that get created.

However, the [AWS SDK for JavaScript V2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#requestSpotInstances-property) documentation is saying that the `TagSpecifications`'s `ResourceType` property supports multiple types such as `instance`, `volume`, and others which is wrong. Only `spot-instances-request` was valid based on my test of version `2.955.0`.

The [AWS SDK for JavaScript V3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/requestspotinstancescommandinput.html#tagspecifications) correctly states that only tagging the `spot-instance-request` is the allowed value.

Please correct the V2 documentation.

**Comment by ajredniwja** [comment]
@JoseRolles, thanks for brining this up, have reached out to the team that manages the API reference for the changes.

**Comment by omarioffline** [comment]
const data = {
        Bucket: 'aj-bar',
        Key: "xyz.xlsx",
        Body: fs.createReadStream('pathToExcel'),
        ContentType: 'application/vnd.ms-excel',
      };
Let me know if that doesn't solve the issue.
