### ISSUE TITLE
Problem sending SMS in sandbox

### ISSUE THREAD

**Issue by iannisacksson** [aws/aws-sdk-js#3843]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

Good evening,

I'm having a problem sending SMS inside the Sandbox. I already have the phone numbers registered and whenever I try to send an SMS it shows the ids of the messages, but it doesn't send. I went to check the logs and the error message is "Your account requires additional review prior to being able to send SMS messages".

can anybody help me?

```
{
    "notification": {
        "messageId": "5f0369b1-54a2-5f8b-81d9-30cc413c4566",
        "timestamp": "2021-07-29 20:45:17.609"
    },
    "delivery": {
        "destination": "+5524982121212",
        "smsType": "Transactional",
        "providerResponse": "Your account requires additional review prior to being able to send SMS messages. Please create a support ticket with an explanation of your use case. https://console.aws.amazon.com/support/cases#/create?issueType=service-limit-increase&limitType=service-code-sns-text-messaging",
        "dwellTimeMs": 59
    },
    "status": "FAILURE"
}
```

**Comment by ajredniwja** [comment]
HI @iannisacksson, thanks for opening this issue and apologies for late reply.

You'd need to ask for service limit increase, see:
https://aws.amazon.com/premiumsupport/knowledge-center/sns-sms-spending-limit-increase/

Or open the ticket mentioned in the message. 

This is not SDK related issue but with SNS service. 

Closing this issue now, please reach out if you have any questions or want me to re-open the issue.
