### ISSUE TITLE
View image instead of downloading

### ISSUE THREAD

**Issue by Glutch** [aws/aws-sdk-js#3844]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
When clicking on my generated links, the image is downloaded instead of simply viewed.
I have googled a ton and i need to change the Content-Type to image/png but i can't seem to find the correct place to do this.

On the server, it looks like this
```
import aws from 'aws-sdk'

  aws.config.update({
    accessKeyId: process.env.S3_ACCESS_KEY,
    secretAccessKey: process.env.S3_SECRET_KEY,
    region: process.env.S3_REGION,
    signatureVersion: 'v4',
  })

  const s3 = new aws.S3()
  const post = await s3.createPresignedPost({
    Bucket: process.env.S3_BUCKET,
    Fields: {
      key: req.query.file,
      ContentType: 'image/png', // tried this
    },
    Expires: 60, // seconds
    Conditions: [
      ['content-length-range', 0, 1048576 * 10], // (up to 1 MB) * 10
      ['starts-with', '$Content-Type', 'image/'], // tried this
    ],
  })
}

```

And on the client

```
const filename = `${Date.now()}.png`
const blob = await getCroppedImg(crop, filename)
const file = new File([blob], filename)
const res = await fetch(`/api/upload_aws?file=${filename}`)
const {url, fields} = await res.json()
const formData = new FormData()

Object.entries({...fields, file}).forEach(([key, value]) => {
  formData.append(key, value)
})

formData.append('Content-type', 'image/png') // tried this

const upload = await fetch(url, {
  method: 'POST',
  body: formData,
  headers: {
    'Content-Type': 'image/png' // tried this (this actually does something, it stops working with error 412. "ERR_CONNECTION_RESET 412 (Precondition Failed)")
  },
})
```
      

Any help greatly appreciated!

**Comment by Glutch** [comment]
Finally figured out it should be
```
Fields: {
  key: req.query.file,
  'Content-Type': 'image/png', // tried this
},
```

and not
```
Fields: {
  key: req.query.file,
  ContentType: 'image/png', // tried this
},
```

**Comment by ajredniwja** [comment]
@Glutch thanks for sharing the solution here, apologies could not get to you earlier. 

Closing this issue now, please reach out and feel free to tag me if you have any other questions.

**Comment by omarioffline** [comment]
const AWS = require("aws-sdk");
const ecr = new AWS.ECRPUBLIC({
  region: process.env.AWS_REGION,
  apiVersion: '2020-10-30
