### ISSUE TITLE
Send Message Fails Silently When SQS URL is Omitted

### ISSUE THREAD

**Issue by jeffbernst** [aws/aws-sdk-js#3845]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

In one of our services, we're using the JavaScript SDK to send messages to an SQS queue. After some troubleshooting, we realized that we weren't including the account number in the SQS URL, but this never caused the SDK to throw any errors. Instead, it seems as if sometimes the messages would go through and other times they would just fail silently.

**Is the issue in the browser/Node.js?**

Node.js

**If on Node.js, are you running this on AWS Lambda?**

Yes

**Details of the browser/Node.js version**

v12.18.2

**SDK version number**

2.860.0

**To Reproduce (observed behavior)**

Here's are some code snippets to illustrate the issue. We instantiate the SQS class like this:
```
    const sqs = new SQS({
      region,
    });
```
And then use `sendMessage` like this:
```
    this.sqs
      .sendMessage({
        QueueUrl: queueUrl,
        MessageBody: messageBody,
      })
      .promise();
```
Where the `QueueUrl` is something like this:

`https://sqs.us-east-1.amazonaws.com/service-${process.env.DEVELOPMENT_STAGE}-queue-name`

Even though we would expect the account number is needed here:

`https://sqs.us-east-1.amazonaws.com/ACCOUNT_ID/service-${process.env.DEVELOPMENT_STAGE}-queue-name`

**Expected behavior**

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#sendMessage-property 
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-queue-message-identifiers.html 

From the above docs, I would assume that the request would throw an error without the account number in the QueueUrl, but with some manual testing it appears that the request succeeds both with and without the account number and I can't reproduce the issue we were seeing in production.

After adding the account number to the `QueueUrl`, we found that the issue was resolved. Before confirming this, I submitted an AWS support ticket and received the following response (Case ID 8576232751):

> My understanding is that in  one of your services making use of the JavaScript SDK to send messages to SQS queue(s), you are troubleshooting why sometimes the messages aren't getting processed. From your case notes, I see in the process, you have observed that you are omitting your AWS account number in the QueueUrl [1] request parameter required to make the SendMessage API request [2]. As the API call is successful, you would like to know why the request succeeds without the account number in the QueueUrl and is there a reason that without the account number sometimes these messages would succeed, but sometimes they would fail silently. Please correct me if I have misunderstood your case. 
>
> To investigate the shared behaviour, I have attempted to make use of the SQS SendMessage API in my environment and I was able to successfully send messages to an SQS queue using both the account number and excluding the account number in the QueueUrl without any error(s). From this, looks like not including the account number in the QueueUrl in the SendMessage should not impact the ability to send messages to the SQS queue. 
>
> To study the behaviour more closely, I have used the debug flag [2], [3] and called the API using the CLI. When making use of the SQS SendMessage command with the debug flag, I have observed that the SDK seems to make use of Client configuration to retrieve request related parameters such as account number before the request is signed and sent to the service. This looks like to be the cause of the behaviour observed in your environment and in my tests where the messages are reaching the respective destination queue(s) even when the account number is not included in the QueueUrl part of the request. I am including sample debug output for both cases obtained by making use of the API in the attachment of this email.
>
> As the observed behaviour is not clearly discussed in the documentation, I am reaching out to the internal SQS team to share this behaviour. However, it is worth noting Premium Support doesn’t have visibility into aspects such as changes in documentation and I am unable to share an estimate as to by when the observed behaviour would also be covered in the documentation. 
>
> Having said that, as the SQS messages still reach the SQS queue when the account number is not included in the QueueUrl request parameter, for troubleshooting why sometimes the messages aren't getting processed, it would be best to look at the SQS CloudWatch metrics [4] for the affected queue(s) and also look at the component(s) of your application pulling and consuming the messages from the SQS queue(s). 

So it does seem like the SDK is able to pull the account number from the client configuration sometimes if it’s omitted, but it silently fails sometimes as well.

**Comment by ajredniwja** [comment]
Hey @jeffbernst, thanks for opening this issue, unfortunately I am not able to reproduce the issue. Also thanks for providing the case number, I can check with the team. With that being said, it seems cloudWatch metrics can help but I'd still need a reproducible case. Its unlikely that SDK is swallowing errors for this. Is there anything that is not mentioned? Any race conditions or hitting the limits?

**Comment by jeffbernst** [comment]
Yeah, unfortunately I wasn't able to reproduce either, but it was pretty clear that adding the account number fixed the issue for us because the problem went away after we merged that change. I added all of the information I had in this ticket, but I'll be sure to add anything if it comes up down the road.
