### ISSUE TITLE
How do I use or import xml2js directly from the preinstalled modules in lambda

### ISSUE THREAD

**Issue by ShivamJoker** [aws/aws-sdk-js#3847]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
I tried everything but couldn't get any help without including the whole library itself, if is there any way we can directly import it, please let me know.

Some stackoverflow answers suggested directly importing but now it's not working at all.

**Comment by ajredniwja** [comment]
@ShivamJoker hi there thanks for opening this issue, can you share how you are consuming the SDK? I might not be able to understand the question but it might not be related to the SDK.

**Comment by ajredniwja** [comment]
Closed by mistake

**Comment by ShivamJoker** [comment]
I am using the AWS CDK and the application is being deployed to lambda.

I had to install the package separately to get it to work.

**Comment by ajredniwja** [comment]
> I am using the AWS CDK and the application is being deployed to lambda.
> 
> I had to install the package separately to get it to work.

Glad its working for you, I was confused as this is the JS repo. For future CDK issues you can use: https://github.com/aws/aws-cdk

Closing this issue now, feel free to reach out and tag me if you have any other questions. 

Thank you.
