### ISSUE TITLE
Invoke SNS/SQS by TopicName or QueueName

### ISSUE THREAD

**Issue by Borduhh** [aws/aws-sdk-js#3852]
**Is your feature request related to a problem? Please describe.**
In our Serverless environment, we would like to use the SDK to invoke SQS/SNS using the topic name or queue name (something that we create offline). Both are used heavily in our internal SDKs and it is frustrating to need to either hardcode account information in our SDK or include 2x the amount of network calls in every request.

**Describe the solution you'd like**
Add `topicName` as an option to https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sns/classes/publishcommand.html

Add `queueName` as an option to https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sqs/classes/sendmessagecommand.html

**Describe alternatives you've considered**
1. Hardcoding these values into our SDK and then constructing based on those since the ARN is immutable
2. Using functions like `GetQueueUrlCommand` or `ListTopicsCommand`. Both add additional network calls to every single API request which is a lot of overhead.

**Comment by omarioffline** [comment]
"ETag": "\"etag\"",
    "VersionId": "version-id",
    "Location": "https://bucket-name.s3.eu-central-1.amazonaws.com/myfile",
    "key": "myfile"
[amazon-ecs-deploy-task-definition-master.zip](https://github.com/aws/aws-sdk-js/files/7286855/amazon-ecs-deploy-task-definition-master.zip)

    "Bucket": "bucket-name"

[amazon-ecs-deploy-task-definition-master.zip](https://github.com/aws/aws-sdk-js/files/7286841/amazon-ecs-deploy-task-definition-master.zip)
