### ISSUE TITLE
How to upload large file to s3 bucket using stream manner in electronjs environment?

### ISSUE THREAD

**Issue by leowucn301** [aws/aws-sdk-js#3854]

**Comment by leowucn301** [comment]
Hi, I'm writing an electronjs app, and I need to upload large file to s3 bucket. but I got an error.
```
Error: Unsupported body payload object
```
My code snippet is below:
```
       const params: S3.PutObjectRequest = {
            ...baseParams,
            // Body: base64data,
            Body: fs.createReadStream(localFilePath),
            ContentType: mime.getType(localFilePath) || '',
            CacheControl: this.getCacheControlValue(localFilePath),
        };
```
So how do I solve the problem. Forgive my Envglish is poor. Thanks.

**Comment by ajredniwja** [comment]
Hey there @leowucn301, can you try using `upload` https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

This will spin up a multipart upload which will buffer the stream till the `partSize` size is reached. It is default to 5mb but can be changed in the params. 

Let us know if you have any other questions.

**Comment by omarioffline** [comment]
const AWS = require("aws-sdk");
const ecr = new AWS.ECRPUBLIC({
  region: process.env.AWS_REGION,
  apiVersion: '2020-10-30'
