### ISSUE TITLE
Upload xlsx files to an Amazon S3 bucket using the aws-sdk and express generate a corrupt file

### ISSUE THREAD

**Issue by nexun** [aws/aws-sdk-js#3855]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I am trying to upload an XLSX file to my Amazon S3 bucket using the aws-sdk and express but I cannot understand why it is generated in a corrupt way. Initially I receive my file in base64 format (which I already checked and is correct) and transformed it into a buffer to send it to sdk. The operation is successful, it prints in the console a link that it generated at the time to test the upload and it downloads a file that is corrupt, even if I try to open it from the amazon interface it is also corrupt. Sorry if this topic is very repetitive but I look at all the similar questions and I can't solve the problem, maybe I am lacking knowledge about handling files in node.

![image](https://user-images.githubusercontent.com/18318851/129759414-c671aa20-dc92-4cd0-9a74-d9b788b5ca66.png)

[codeExample.txt](https://github.com/aws/aws-sdk-js/files/7001399/codeExample.txt)
the code is in the txt because I format it wrong when I insert it

**Comment by ajredniwja** [comment]
Hi @nexun thanks for opening this issue can you use something like(using a file stream) :

```
      const data = {
        Bucket: 'aj-bar',
        Key: "xyz.xlsx",
        Body: fs.createReadStream('pathToExcel'),
        ContentType: 'application/vnd.ms-excel',
      };
```

Let me know if that doesn't solve the issue.

**Comment by omarioffline** [comment]
import { __assign, __awaiter, __generator } from "tslib";
import { SignatureV4 } from "@aws-sdk/signature-v4";
/**
 * A SigV4-compatible signer for S3 service. In order to support SigV4a algorithm according to the operation input
 * dynamically, the signer wraps native module SigV4a signer and JS SigV4 signer. It signs the request with SigV4a
 * algorithm if the request needs to be signed with `*` region. Otherwise, it signs the request with normal SigV4
 * signer.
 * Note that SigV4a signer is only supported in Node.js now because it depends on a native dependency.
 * @private
 */
var S3SignatureV4 = /** @class */ (function () {
    function S3SignatureV4(options) {
        this.sigv4Signer = new SignatureV4(options);
        this.signerOptions = options;
    }
    S3SignatureV4.prototype.sign = function (requestToSign, options) {
        if (options === void 0) { options = {}; }
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        if (!(options.signingRegion === "*")) return [3 /*break*/, 2];
                        if (this.signerOptions.runtime !== "node")
                            throw new Error("This request requires signing with SigV4Asymmetric algorithm. It's only available in Node.js");
                        return [4 /*yield*/, this.getSigv4aSigner()]
                    case 1: return [2 /*return*/, (_a.sent()).sign(requestToSign, options)]
                    case 2: return [2 /*return*/, this.sigv4Signer.sign(requestToSign, options)]

**Comment by vudh1** [comment]
Hi @nexun, safe way to do it is to have it locally and use `fs.createReadStream`.
