### ISSUE TITLE
Getting SignatureMismatchError for a AWS created signed URL with rook ceph as objectstore

### ISSUE THREAD

**Issue by Bcharishma** [aws/aws-sdk-js#3858]
I am using rook ceph (v15.2.9) as objectstore deployed in kubernetes environment as a cluster. Using the below code snippet to generate a signed url to download the image.
```js
req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
		Bucket: aws.String(bucketName),
		Key:    aws.String(objID),
	})
	urlStr, err := req.Presign(expiry)
	if err != nil {
		log.Errorf("Unable to generate signed URL %v", err)
		return nil, err
	}
	logger.Infof("url %s", urlStr)
	genURL, err := url.Parse(urlStr)
	if err != nil {
		log.Errorf("Unable to parse signed URL %v", err)
		return nil, err
	}
	host := viper.GetString("storage_config.url_host")
	logger.Infof("url host is %s", host)
	genURL.Host = host
	genURL.Scheme = "https"
	logger.Infof("generated url is %s", genURL.String())
	return genURL, nil
```

I have added an ambassador annotation to rook-ceph-rgw-object-store so that the generated url can be used from outside the cluster.
root@dv2-master:~# kubectl get svc -n rook-ceph rook-ceph-rgw-object-store -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: rook-host-mapping
      prefix: /rookstore/
      rewrite: /
      service: rook-ceph-rgw-object-store.rook-ceph:80
      host_rewrite: rook-ceph-rgw-object-store.rook-ceph:80
      timeout_ms: 1800000

Same genrated url looks like: "https://10.54.239.52/rookstore/my-bucket-598e6746-50ce-4a0e-942b-ce184869f0c1/jinstall-ppc-18.2R3.4-signed.tgz?X-Amz-Date=20210817T091752Z&X-Amz-Expires=7200&X-Amz-Signature=341a6c4e9676a2b93fee955cd44a46f93d6aa6af9b603ccc51a669526e52109d&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=2HQ0WD5YHC7206NDL7B3%2F20210817%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host"

But I am getting the below error when I try to access download the image using this url.
<Error>

<Code>SignatureDoesNotMatch</Code>
<RequestId>tx0000000000000000028e4-006119f680-b535a-object-store</RequestId>
<HostId>b535a-object-store-object-store</HostId>

</Error>

Can someone please help me with this.

**Comment by ajredniwja** [comment]
@Bcharishma thanks for opening this issue, I am not sure how you are consuming the SDK and JS SDK, hence if you can give me some more details which are asked in the [issue template](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)
