### ISSUE TITLE
Error when "npm install aws-sdk"?

### ISSUE THREAD

**Issue by vladimirteddy** [aws/aws-sdk-js#3860]
I'm run npm install aws-sdk on service EC2 AWS (Centos)
And my logs:
582 error aws-sdk@2.943.0 postinstall: `node scripts/check-node-version.js`
582 error spawn ENOENT
583 error Failed at the aws-sdk@2.943.0 postinstall script.
583 error This is probably not a problem with npm. There is likely additional logging output above.
Use:
- node version: v14.17.0
- npm version: 6.14.13

<img width="918" alt="Screen Shot 2021-08-22 at 01 42 41" src="https://user-images.githubusercontent.com/29521357/130331931-aa7c1742-cad7-45b4-9705-cef8d5c8454b.png">

**Comment by prasanna3000** [comment]
@vladimirteddy , any fix you found for this?
I am facing the same issue. Any kind of help would be appreciated

**Comment by vladimirteddy** [comment]
> @vladimirteddy , any fix you found for this?
> I am facing the same issue. Any kind of help would be appreciated

You will build image and use it.

**Comment by prasanna3000** [comment]
> > @vladimirteddy , any fix you found for this?
> > I am facing the same issue. Any kind of help would be appreciated
> 
> You should build image and use it.

In mu case, it is happening because of the improper installation of nodejs. I removed the existing nodejs and installed the latest lts version. It's resolved for me

**Comment by vladimirteddy** [comment]
> > > @vladimirteddy , any fix you found for this?
> > > I am facing the same issue. Any kind of help would be appreciated
> > 
> > 
> > You should build image and use it.
> 
> In mu case, it is happening because of the improper installation of nodejs. I removed the existing nodejs and installed the latest lts version. It's resolved for me
> 
> By the way, thanks for the suggestion!

Great
