### ISSUE TITLE
`finishSinglePart` is overwriting data.Location attribute

### ISSUE THREAD

**Issue by edwinveldhuizen** [aws/aws-sdk-js#3862]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
We're using the library for a custom endpoint containing tenant details.
The data.Location from the server is correct e.g. `objectstore.true.nl/{tenant}:{bucket}/{file}.mp4`
Multi-part uploads are working since `finishMultiPart` is not overwriting data.Location, but finishSinglePart is:

```
/**
   * @api private
   */
  finishSinglePart: function finishSinglePart(err, data) {
    var upload = this.request._managedUpload;
    var httpReq = this.request.httpRequest;
    var endpoint = httpReq.endpoint;
    if (err) return upload.callback(err);
    data.Location =
      [endpoint.protocol, '//', endpoint.host, httpReq.path].join('');
    data.key = this.request.params.Key; // will stay undocumented
    data.Key = this.request.params.Key;
    data.Bucket = this.request.params.Bucket;
    upload.callback(err, data);
  },
```

Therefore for single part uploads I'm ending up with a url like `https://{bucket}.objectstore.true.nl/{file}.png` instead of `objectstore.true.nl/{tenant}:{bucket}/{file}.png`

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**SDK version number**
v2.961.0

**Comment by ajredniwja** [comment]
Hi @edwinveldhuizen, thanks for opening this issue, can you please share complete repro code?

**Comment by omarioffline** [comment]
├─┬ aws-cdk@1.102.0
│ ├── aws-sdk@2.866.0
│ └─┬ cdk-assets@1.102.0
│   └── aws-sdk@2.866.0 deduped
├── aws-sdk@2.989.0
├─┬ serverless-domain-manager@3.3.2
│ └── aws-sdk@2.989.0 deduped
├─┬ serverless-offline@6.9.0
│ └── aws-sdk@2.989.0 deduped
└─┬ serverless@2.51.0
  └── aws-sdk@2.989.0 deduped

**Comment by omarioffline** [comment]
AWS Forums.png
