### ISSUE TITLE
S3 DeleteObject Api call breaking change

### ISSUE THREAD

**Issue by cristian-marinescu** [aws/aws-sdk-js#3864]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When using signatureVersion "s3" the call to `s3.deleteObjects()` fails with `InvalidRequest: Missing required header for this request: Content-MD5`

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.10.0

**SDK version number**
2.974.0

**To Reproduce (observed behavior)**
```
const AWS = require('aws-sdk');

const s3 = new AWS.S3({
  signatureVersion: 's3',
});

const params = {
  Bucket: "test-bucket",
  Delete: {
    Objects: [
      {
        Key: "file1"
      },
    ],
    Quiet: false
  }
};

s3.deleteObjects(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});

```

**Expected behavior**
The API call works. 

**Additional context**
The change was introduced in this PR https://github.com/aws/aws-sdk-js/pull/3799/files. When a request transitions to the `build` state an event handler is triggered that will not place the `Content-MD5` header to the request. Prior to this PR, it would have always set it. The new behaviour seems wrong because for any other s3 operation besides `s3.deleteObjects()` that needs to set this header, the event handler does set it. When extracting the rules in https://github.com/aws/aws-sdk-js/blob/223bd5902dd0050404ffbdab29a3f9cac0133932/lib/services/s3.js#L458, `rules.ContentMD5` is undefined, because, for this operation, it is not present in the S3 Service Model.

After https://github.com/aws/aws-sdk-js/blob/223bd5902dd0050404ffbdab29a3f9cac0133932/lib/event_listeners.js#L135, it will also remain unset, because of the signature version.

I am aware that I may be wrong and this may be intended. I searched the docs in order to get an answer and found nothing. Would you be so kind to provide an explanation or maybe point me to some docs I have missed?

**Comment by AllanZhengYP** [comment]
@cristian-marinescu Thank you for reporting this issue and the detailed analytics. The root of this issue is that `ContentMD5` is not reset in the `DeleteObjects` model, so the code believe the header is not applicable, even if models says it requires contentMD5 header. I will put up a fix soon

**Comment by AllanZhengYP** [comment]
@cristian-marinescu I find this error only affects SignatureV2 signer. As an workaround you can remove `signatureVersion: 's3',` in constructor. 

SignatureV2 [has been deprecated in AWS](https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/), is there any reason you still need SignatureV2?

**Comment by omarioffline** [comment]
{
    "ETag": "\"etag\"",
    "VersionId": "version-id",
    "Location": "https://bucket-name.s3.eu-central-1.amazonaws.com/myfile",
    "key": "myfile",
    "Key": "myfile",
    "Bucket": "bucket-name"
}
[README.md](https://github.com/aws/aws-sdk-js/files/7279990/README.md)

**Comment by omarioffline** [comment]
{
    "ETag": "\"etag\"",
    "VersionId": "version-id",
    "Location": "https://bucket-name.s3.eu-central-1.amazonaws.com/myfile",
    "key": "myfile",
    "Key": "myfile",
    "Bucket": "bucket-name"
}
[README.md](https://github.com/aws/aws-sdk-js/files/7280087/README.md)
