### ISSUE TITLE
Lex V2 Runtime does not unzip information in headers

### ISSUE THREAD

**Issue by esoler-sage** [aws/aws-sdk-js#3872]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Lex V2 Runtime PutSession (and I suspect RecognizeUterrance too) returns information gzipped on many fields (sessionState, messages). My guess is that shape is not set up to be decompressed in the https://github.com/aws/aws-sdk-js/blob/307e82673b48577fce4389e4ce03f95064e8fe0d/apis/runtime.lex.v2-2020-08-07.normal.json file.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**

Yes

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

Node 14 Lambda

**SDK version number**
v2.963.0

**To Reproduce (observed behavior)**

```javascript
await putSession({
  responseContentType: 'text/plain; charset=utf-8',
  botId: '',
  botAliasId: '',
  localeId: 'en_US',
  sessionId: '',
  sessionState: {
    dialogAction: { type: 'Delegate' },
    intent: { name: 'Intent', state: 'InProgress' },
    sessionAttributes: { test: 'test' }
  }
}).promise()
```
returns 
```json
{
    "contentType": "text/plain; charset=utf-8",
    "messages": "gzipped",
    "sessionState": "gzipped",
    "sessionId": "",
    "audioStream": {
        "type": "Buffer",
        "data": []
    }
}
```

**Expected behaviour**

I would expect messages and sessionState to be a JS object

**Workaround**

```
const { deflate, unzip } = require('zlib');
const { promisify } = require('util');

const do_unzip = promisify(unzip);

const unzipMessages = async (str) => {
  const buffer = Buffer.from(str, 'base64');
  const resultBuff = await do_unzip(buffer);

  return JSON.parse(resultBuff.toString());
};
```

**Comment by ajredniwja** [comment]
@esoler-sage, thanks for opening this issue, I'd need to have a word with the Lex V2 team as they return this data. 
Will get back to you as soon as I hear back.

**Comment by esoler-sage** [comment]
Awesome, thanks! In the mean time, I will try also with the V3 version to see if it happens the same or if it works there
