### ISSUE TITLE
Why AWS.config.credentials.accessKeyId , IdentityId is always null or undefined? How can I found it? 

### ISSUE THREAD

**Issue by minchch** [aws/aws-sdk-js#3884]
Hello, 
My modules version is same as below. 
 "aws-sdk": "^2.7.21",
"amazon-cognito-identity-js": "^2.0.9"

[ history]
1. When I use API 'AssociateSoftwareToken', these errors were occured. 
`CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1`
2. and I need to find out where is 'accessKeyId'. 
so I would like to get below results. 

`Config.credentials.get(function(){

            // Credentials will be available when this function is called.
            var accessKeyId = Config.credentials.accessKeyId;
            var secretAccessKey = Config.credentials.secretAccessKey;
            var sessionToken = Config.credentials.sessionToken;
            console.log(accessKeyId,secretAccessKey,sessionToken);
        });
`
but in console.log is 'undefied' or 'null'. 
How do I fix this >? please help

* **this.options  is fixed cognito { region, UserpoolId, ClientId }**

**Comment by ajredniwja** [comment]
Hey @minchch thanks for opening this issue, you can find the necessary information in [this doc](https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html). With a section for best practices as well. 

What I can guess is that you havent configured credentials which usually are set using one of the methods mentioned in the [doc](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html). 

Please reach out if you need any additional help.
