### ISSUE TITLE
Lambda Invocation fails to return result

### ISSUE THREAD

**Issue by jonnyfux** [aws/aws-sdk-js#3888]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When invoking a lambda function that takes a long time to finish (10min but does so successfully) the return value of the lambda function is not returned, even if the connection timeout is sufficient. So the Lambda Function will finish and return the value, but the invoke method from the SDK still waits for a response and then eventually times out. 

I think its time-related. I tested it with the same lambda function and below code but with a faster response (~2mins) and it printed the response like expected. 

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No
**Details of the browser/Node.js version**
v12.14.1

**SDK version number**
2.906.0

**To Reproduce (observed behavior)**

1. Create Lambda function which finishes after 10-15mins
2. Invoke the function from node.js
3. A TimeoutError will be thrown
```

{
  message: 'Connection timed out after 840000ms',
  code: 'TimeoutError',
  time: 2021-09-15T18:24:57.416Z,
  region: 'eu-central-1',
  hostname: 'lambda.eu-central-1.amazonaws.com',
  retryable: true
}
```

**Expected behavior**
The Lambda response is returned, 

```
{
  StatusCode: 200,
  ExecutedVersion: '$LATEST',
  Payload: '"my-return-value"'
}
```

**Additional context**
Code Snippets of the implementation: 

```
try {
     const lambda = new AWS.Lambda({ region: 'eu-central-1', maxRetries: 0, httpOptions: { connectTimeout: 840000, timeout 840000 } }); // 840000ms = 14min
    const params = {
      FunctionName: 'function-name',
      Payload: JSON.stringify({
        myPayload
      })
    };
      const res = await lambda.invoke(params).promise();
      console.log(res);
      if (res.FunctionError) {
        throw new Error('function error' + res.FunctionError);
      }
    } catch (error) {
      // here the TimeoutError is caught
      console.log(error);
   }
```

**Comment by ajredniwja** [comment]
Hey @jonnyfux thanks for opening the issue, I see the `timeout` missing `:` not sure if its a type with that being mentioned please see the trouble shooting guide found [here](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-function-retry-timeout-sdk/) and let me know if the solution there doesn't work for you. Would be happy to help.
