### ISSUE TITLE
SQS `[TimeoutError: socket hang up]` Error

### ISSUE THREAD

**Issue by vikasingh95** [aws/aws-sdk-js#3889]
Hi,

Recently, we've been getting `socket hang up` errors while sending messages to the SQS queue. After doing some research found an issue that might be related to this. (https://github.com/aws/aws-sdk-js/issues/367) 
Tried the solution mentioned in the thread i.e. to set the timeout for the SDK, still no luck.

Node version - v10.17.26
SDK version - V2.695.0

The code snippet that is being used to send messages to SQS can be found below. 
The error message that we are getting in response - `[TimeoutError: socket hang up]`
```node
var AWS = require('aws-sdk');
var sqs = new AWS.SQS({httpOptions: {timeout: 10000}});
sqs.sendMessage(obj, function(err, body) {
  if (err) {
    console.log(err);
  } else {
    console.log(body);
  }
});
```

**Comment by ajredniwja** [comment]
Hey @vikasingh95 can you please check if `sslEnabled` param is set true in your code. I was not able to reproduce a simple `SQS.sendMessage` request. Also would recommend to update the version of the SDK to latest. 

Please fill out the [issue template](https://github.com/aws/aws-sdk-js/issues/3889) with complete information for me to be able to help you better.

**Comment by vikasingh95** [comment]
Thanks! @ajredniwja. After enabling the `sslEnabled` flag the issue got resolved.
