### ISSUE TITLE
EC2 RunInstancesRequest potential improperly named parameter

### ISSUE THREAD

**Issue by mattBrzezinski** [aws/aws-sdk-js#3892]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

---

I have a repository [AWS.jl](https://github.com/JuliaCloud/AWS.jl) which implements an SDK for AWS in [JuliaLang](https://julialang.org/) which we use the JSON definitions of this project to generate our code from. We ran into an issue with the EC2 RunInstances request, and was wondering if this is either a bug or my misunderstanding.

The [RunInstancesRequest](https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/ec2-2016-11-15.normal.json) (cannot direct link since file is too large) has a parameter `ClientToken` defined as,

```julia
"ClientToken": {
  "shape": "String",
  "documentation": "<p>Unique, case-sensitive identifier you provide to ensure the idempotency of the request. If you do not specify a client token, a randomly generated token is used for the request to ensure idempotency.</p> <p>For more information, see <a href=\"https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Run_Instance_Idempotency.html\">Ensuring Idempotency</a>.</p> <p>Constraints: Maximum 64 ASCII characters</p>",
  "idempotencyToken": true,
  "locationName": "clientToken"
},
```

When we submit requests we [auto-generate a UUID4](https://github.com/JuliaCloud/AWS.jl/blob/d2ad97aa9034a212726184513cfafd8339a8373d/src/services/ec2.jl#L21187) for this parameter and call it `clientToken` because it has a `locationName` in its definition.

However when we submit requests with this default parameter we get the response back,

```
<Response><Errors><Error><Code>UnknownParameter</Code><Message>The parameter clientToken is not recognized</Message></Error></Errors><RequestID>de17cd6b-0614-495a-a476-53c6fb9f9884</RequestID></Response>""")
```

When we set this value to `ClientToken`, with a capital `C`. The request is successful. My understanding so far has been, use the top-level parameter name (in this example `ClientToken`) as the parameter name when making requests. However if a `locationName` (in this example `clientToken`)is present in the JSON object use that instead of the top-level name.

I'm wondering if my understanding is correct here and this is just a bug, or if I'm misunderstanding and there is more to `locationName` values in parameters.

Thanks!

cc: https://github.com/JuliaCloud/AWS.jl/issues/444

**Comment by ajredniwja** [comment]
Hi @mattBrzezinski thanks for opening this issue, I believe your understanding is correct, as for the SDK there are no customizations around EC2 meaning all the logic is done by the EC2 team and SDK validates it against the model provided. With that being said, the `clientToken` is being used at several positions which makes it very unlikely to be a bug but I can stil check with the EC2 team if thats an issue. 

Thanks

**Comment by mattBrzezinski** [comment]
Thanks for the reply! It seems that there are various other requests which run into this issue. Another example is the `ModifyInstanceAttribute` with the `instanceId` parameter.

**Comment by ajredniwja** [comment]
@mattBrzezinski Let me reach-out to the EC2 team to have more clarity, this may take a while.

**Comment by mattBrzezinski** [comment]
Just wanted to follow up on this issue as it's been two weeks.

**Comment by iamed2** [comment]
botocore actually special-cases EC2 for this: https://github.com/boto/botocore/blob/c920c8f40c6fb61b9b3f3b1d76ff3c14fdad3490/botocore/serialize.py#L319

**Comment by aBurmeseDev** [comment]
Hi everyone - sorry for the long silence here. 

As previously mentioned, the discrepancy with the `ClientToken` parameter in the EC2 `RunInstances` request appears to be a deviation from the standard naming conventions specified in the AWS JSON service definitions.

Since this matter requires changes or clarification from the EC2 service team and there haven't been any updates or resolutions provided on their end, we don't have any pending action items for the SDK team at this time.

Given that this repository is specifically dedicated to issues related to the AWS SDK, we will be closing this issue.

Feel free to contact service team directly via [AWS Support](https://aws.amazon.com/contact-us/) for future updates.
