### ISSUE TITLE
 v2 relies on "@aws-sdk/signature-v4"; But it doesnt take it as a dependency.

### ISSUE THREAD

**Issue by alexforsyth** [aws/aws-sdk-js#3894]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When installing and using the latest version of aws-sdk, it seems to be broken out of the box.

aws-sdk relies on `import { SignatureV4 } from "@aws-sdk/signature-v4";` but doesn't take it as a dependency, as a result, people get this following error (or similar).
```
ERROR in ../../../node_modules/@aws-sdk/middleware-sdk-s3/dist/es/S3SignatureV4.js 58:45-80
Module not found: Error: Can't resolve '@aws-sdk/signature-v4-crt' in '/..../node_modules/@aws-sdk/middleware-sdk-s3/dist/es'
resolve '@aws-sdk/signature-v4-crt' in '/.../node_modules/@aws-sdk/middleware-sdk-s3/dist/es'
  Parsed request is a module
  using description file: /..../node_modules/@aws-sdk/middleware-sdk-s3/package.json (relative path: ./dist/es)
    resolve as module
```

The issue is in this file:
```js
import { __assign, __awaiter, __generator } from "tslib";
import { SignatureV4 } from "@aws-sdk/signature-v4";
/**
 * A SigV4-compatible signer for S3 service. In order to support SigV4a algorithm according to the operation input
 * dynamically, the signer wraps native module SigV4a signer and JS SigV4 signer. It signs the request with SigV4a
 * algorithm if the request needs to be signed with `*` region. Otherwise, it signs the request with normal SigV4
 * signer.
 * Note that SigV4a signer is only supported in Node.js now because it depends on a native dependency.
 * @private
 */
var S3SignatureV4 = /** @class */ (function () {
    function S3SignatureV4(options) {
        this.sigv4Signer = new SignatureV4(options);
        this.signerOptions = options;
    }
    S3SignatureV4.prototype.sign = function (requestToSign, options) {
        if (options === void 0) { options = {}; }
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        if (!(options.signingRegion === "*")) return [3 /*break*/, 2];
                        if (this.signerOptions.runtime !== "node")
                            throw new Error("This request requires signing with SigV4Asymmetric algorithm. It's only available in Node.js");
                        return [4 /*yield*/, this.getSigv4aSigner()];
                    case 1: return [2 /*return*/, (_a.sent()).sign(requestToSign, options)];
                    case 2: return [2 /*return*/, this.sigv4Signer.sign(requestToSign, options)];
                }
            });
        });
    };
    ...

```

**Is the issue in the browser/Node.js?**
Browser/Node.js

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by AllanZhengYP** [comment]
@alexforsyth I cannot reproduce this issue. Can you confirm this from a freshly intalled package? This dependency might have been brought in by V3 clients, and might be related to https://github.com/aws/aws-sdk-js-v3/issues/2806

**Comment by omarioffline** [comment]
import { __assign, __awaiter, __generator } from "tslib";
import { SignatureV4 } from "@aws-sdk/signature-v4";
/**
 * A SigV4-compatible signer for S3 service. In order to support SigV4a algorithm according to the operation input
 * dynamically, the signer wraps native module SigV4a signer and JS SigV4 signer. It signs the request with SigV4a
 * algorithm if the request needs to be signed with `*` region. Otherwise, it signs the request with normal SigV4
 * signer.
 * Note that SigV4a signer is only supported in Node.js now because it depends on a native dependency.
 * @private
 */
var S3SignatureV4 = /** @class */ (function () {
    function S3SignatureV4(options) {
        this.sigv4Signer = new SignatureV4(options);
        this.signerOptions = options;
    }
    S3SignatureV4.prototype.sign = function (requestToSign, options) {
        if (options === void 0) { options = {}; }
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
[amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc.zip](https://github.com/aws/aws-sdk-js/files/7287200/amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc.zip)

                        if (!(options.signingRegion === "*")) return [3 /*break*/, 2];
                        if (this.signerOptions.runtime !== "node")
                            throw new Error("This request requires signing with SigV4Asymmetric algorithm. It's only available in Node.js");
                        return [4 /*yield*/, this.getSigv4aSigner()];
                    case 1: return [2 /*return*/, (_a.sent()).sign(requestToSign, options)];
                    case 2: return [2 /*return*/, this.sigv4Signer.sign(requestToSign, options)

**Comment by yukha-dw** [comment]
Please fix bug on `@aws-sdk/signature-v4` before make it the main dependency of `@aws-sdk/middleware-sdk-s3`. I had problem when doing upload test using `@awsk-sdk/client-s3` on `supertest/ava`.

Unfortunately i forgot what's the error is, and it's only happened on linux.
