### ISSUE TITLE
AWS-SDK intergration in angular

### ISSUE THREAD

**Issue by Emmanuel-Nika** [aws/aws-sdk-js#3895]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

I'm using Angular 12.1.4 and I get this error when I import the library in one of my ts files

./node_modules/aws-sdk/lib/event_listeners.js:595:21-44 - Error: Module not found: Error: Can't resolve 'util' in '/Users/apple.inc/Documents/Angular/Personal/ofm-web/node_modules/aws-sdk/lib'
Did you mean './util'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (/Users/apple.inc/Documents/Angular/Personal/ofm-web, node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }

**Comment by ajredniwja** [comment]
HI @Emmanuel-Nika, thanks for opening this issue, as mentioned in the issue, webpack does not pollyfill for core node modules anymore. So the workaround would be to pollyfill manually. Have seen this issue [here](https://github.com/angular/angular-cli/issues/20819) with workarounds, I have personally used [this](https://www.npmjs.com/package/node-polyfill-webpack-plugin) module in the past to get things working. Please reach out if you have any questions.

**Comment by omarioffline** [comment]
Properties aren't for sale
