### ISSUE TITLE
Add waiter for ECS ExecuteCommand / ManagedAgent to be RUNNING

### ISSUE THREAD

**Issue by blimmer** [aws/aws-sdk-js#3898]
**Is your feature request related to a problem? Please describe.**

I love using the new [ECS Exec](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html) behavior to be able to run arbitrary commands against my ECS Fargate tasks. However, my main ECS `Task` reports that it's `RUNNING` before the Managed SSM Container is `RUNNING` and ready to accept `executeCommand` tasks.

For example, consider the following code:

```ts
import { ECS } from "aws-sdk";

export async function main() {
  const ecs = new ECS();
  const clusterArn = process.env.CLUSTER_ARN!;

  const { tasks } = await ecs
    .runTask({
      cluster: clusterArn,
      taskDefinition: process.env.TASK_DEF_FAMILY!,
      count: 1,
      enableExecuteCommand: true,
      launchType: "FARGATE",
    })
    .promise();

  const taskArn = tasks![0].taskArn!;

  // This waits for the Task to be running, but not the managed container
  await ecs
    .waitFor("tasksRunning", {
      tasks: [taskArn],
      cluster: clusterArn,
    })
    .promise();

  // This will fail because the SSM container is PENDING:
  // InvalidParameterException: The execute command failed because execute command was not enabled when the task was run or the execute command agent isn’t running. Wait and try again or run a new task with execute command enabled and try again.
  await ecs
    .executeCommand({
      task: taskArn,
      cluster: clusterArn,
      command: "echo 'hi",
      interactive: true,
    })
    .promise();
}
```

I can work around this issue by checking the `managedAgents` containers from `describeTask`, as this script does:

https://github.com/aws-containers/amazon-ecs-exec-checker/blob/ab51f1e6cfb9de8edb2924bb7386a63ff39e881a/check-ecs-exec.sh#L404-L434

However, it would be great if there were a `waiter` exposed to do this for me.

**Describe the solution you'd like**

It would be great if there were a `waiter provided. For instance:

```ts
await ecs.waitFor("managedAgentsReady", {
  tasks: [taskArn],
  cluster: clusterArn
});
```

Under the hood, aws-sdk would be checking for the state as they're doing here: https://github.com/aws-containers/amazon-ecs-exec-checker/blob/ab51f1e6cfb9de8edb2924bb7386a63ff39e881a/check-ecs-exec.sh#L404-L434

**Describe alternatives you've considered**

For now, I'm just waiting for 30 seconds, which seems to work for now. It's just not as deterministic as a waiter.

```ts
await new Promise((resolve) => setTimeout(resolve, 30_000));
```

**Comment by omarioffline** [comment]
[CODE_OF_CONDUCT.md](https://github.com/aws/aws-sdk-js/files/7280406/CODE_OF_CONDUCT.md)

**Comment by blimmer** [comment]
This is still relevant

**Comment by kellertk** [comment]
We do not have any plans to implement changes to the ECS client for AWS JS v2. Instead, please migrate to AWS SDK for JS v3.
