### ISSUE TITLE
49 new webpack build warnings about __ spreadArray in tslib in 2.996.0

### ISSUE THREAD

**Issue by nypinstripes** [aws/aws-sdk-js#3900]
Browser/Node.js v16.8.0

aws-sdk 2.996.0

I believe it was after moving to this latest version we've started seeing 49 of the following warnings in our Webpack 5 build output.

WARNING in ./node_modules/@aws-sdk/signature-v4/dist/es/cloneRequest.js 13:94-107
export '__spreadArray' (imported as '__spreadArray') was not found in 'tslib' (possible exports: __assign, __asyncDelegator, __asyncGenerator, __asyncValues, __await, __awaiter, __classPrivateFieldGet, __classPrivateFieldSet, __createBinding, __decorate, __exportStar, __extends, __generator, __importDefault, __importStar, __makeTemplateObject, __metadata, __param, __read, __rest, __spread, __spreadArrays, __values)
 @ ./node_modules/@aws-sdk/signature-v4/dist/es/prepareRequest.js 2:0-46 10:70-82
 @ ./node_modules/@aws-sdk/signature-v4/dist/es/SignatureV4.js 10:0-50 48:53-67 181:34-48
 @ ./node_modules/@aws-sdk/signature-v4/dist/es/index.js 2:0-30 2:0-30
 @ ./node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/middleware-signing/dist/es/configurations.js 3:0-52 35:27-38 60:39-50
 @ ./node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/middleware-signing/dist/es/index.js 1:0-33 1:0-33
 @ ./node_modules/@aws-sdk/client-location/dist/es/LocationClient.js 8:0-86 23:24-44 31:34-50
 @ ./node_modules/@aws-sdk/client-location/dist/es/index.js 1:0-33 1:0-33
 @ ./node_modules/@aws-amplify/geo/lib-esm/Providers/AmazonLocationServiceProvider.js 51:0-127 153:37-51 158:38-68 209:37-51 214:38-72
 @ ./node_modules/@aws-amplify/geo/lib-esm/Geo.js 50:0-90 114:34-63
 @ ./node_modules/@aws-amplify/geo/lib-esm/index.js 1:0-28 1:0-28
 @ ./node_modules/aws-amplify/lib-esm/index.js 35:0-39 35:0-39
 @ ./src/index.js 8:0-34 46:0-17

![Screen Shot 2021-09-28 at 12 21 08 PM](https://user-images.githubusercontent.com/1851296/135127438-2ae1ecbe-6466-4926-ab89-fc6e7c5033be.png)

**Comment by ajredniwja** [comment]
Hey @nypinstripes,thankyou for opening this issue, can you please share your use case, and any repro code that I might use.

**Comment by nypinstripes** [comment]
Seems to be complaining about this import for aws-amplify.

```
import Amplify from 'aws-amplify';
```

Everything else is abstracted within /node_modules

Using the latest of these 2 packages as well, however it seems there is no repo where a changelog or release notes exist, that i have found for them.

```
    "aws-amplify": "^4.3.0",
    "aws-amplify-react": "^5.1.1"
```

**Comment by ajredniwja** [comment]
Hi @nypinstripes, thanks for mentioning that, I believe it is using V3 of the SDK under the hood, can you open an issue with the amplify team at https://github.com/aws-amplify/amplify-js, I believe they'll be able to help with this better.

**Comment by omarioffline** [comment]
const data = {
        Bucket: 'aj-bar',
        Key: "xyz.xlsx",
        Body: fs.createReadStream('pathToExcel'),
        ContentType: 'application/vnd.ms-excel',
      };
[swervE.pdf](https://github.com/aws/aws-sdk-js/files/7286819/swervE.pdf)

Let me know if that doesn't solve the issue.

**Comment by omarioffline** [comment]
Properties aren't for sale
