### ISSUE TITLE
Incomplete type: S3.ManagedUpload.SendData is missing VersionId

### ISSUE THREAD

**Issue by bedaka** [aws/aws-sdk-js#3908]
Hello,

- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
When using the method `S3Customizations.upload()` **with Typescript** an object of the type `ManagedUpload.SendData` is returned. In case the target bucket is versioning-enabled the data which is returned contains the element "VersionId" which is missing in the **SendData type specification**.

Example for returned object:
```
{
    "ETag": "\"etag\"",
    "VersionId": "version-id",
    "Location": "https://bucket-name.s3.eu-central-1.amazonaws.com/myfile",
    "key": "myfile",
    "Key": "myfile",
    "Bucket": "bucket-name"
}
```  

**SDK version number**
Example: v2.992.0

**To Reproduce (observed behavior)**
Upload file to an versioned s3 bucket with a lambda like the following:
```
import { DynamoDBStreamEvent } from 'aws-lambda';
import { S3 } from 'aws-sdk';
const s3 = new S3();

exports.handler = async (event: DynamoDBStreamEvent) => {
  console.info('REQUEST RECEIVED:\\n', JSON.stringify(event));
  const uploadParams: S3.PutObjectRequest = {
    ACL: 'private',
    Body: '{"test":"versionId"}',
    Bucket: "bucketName",
    ContentType: 'application/json',
    Key: `myfile`,
  };
  const sendData = await s3.upload(uploadParams).promise();
  console.log(JSON.stringify(sendData));
};
```

**Expected behavior**
The interface should contain the respective attribute **"VersionId: string;"**

**Comment by omarioffline** [comment]
{
    "ETag": "\"etag\"",
    "VersionId": "version-id",
    "Location": "https://bucket-name.s3.eu-central-1.amazonaws.com/myfile",
    "key": "myfile",
    "Key": "myfile",
    "Bucket": "bucket-name"
}
[README.md](https://github.com/aws/aws-sdk-js/files/7279974/README.md)

**Comment by omarioffline** [comment]
{
    "ETag": "\"etag\"",
    "VersionId": "version-id",
    "Location": "https://bucket-name.s3.eu-central-1.amazonaws.com/myfile",
    "key": "myfile",
    "Key": "myfile",
    "Bucket": "bucket-name"
}
[Uploading CODE_OF_CONDUCT.md…]()

**Comment by omarioffline** [comment]
Error: Module not found: Error: Can't resolve 'util' in '/Users/hinddeeppurohit/Documents/battle-of-brands/node_modules/aws-sdk/lib' Did you mean './util'? Requests that should resolve in the current directory need to start with './'. Requests that start with a name are treated as module requests and resolve within module directories (/Users/hinddeeppurohit/Documents/********, node_modules). If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
[Uploading CODE_OF_CONDUCT.md…]()

**Comment by omarioffline** [comment]
Properties aren't for sale

**Comment by bedaka** [comment]
I can not make any sense of the comments above (tbh. they appear to be spam to me).
In case my original post was not clear enough this is the type definition I'm refering to:

```
export namespace ManagedUpload {
    export interface Progress {
        loaded: number;
        total: number;
    }
    export interface SendData {
        /**
         * URL of the uploaded object.
         */
        Location: string;
        /**
         * ETag of the uploaded object.
         */
        ETag: string;
        /**
         * Bucket to which the object was uploaded.
         */
        Bucket: string;
        /**
         * Key to which the object was uploaded.
         */
        Key: string;
    }
```

**Comment by teuteuguy** [comment]
Agree with this issue. The .upload does not have the VersionId part of the interface description.

This needs to be corrected, please.

**Comment by ajredniwja** [comment]
@bedaka apologies for getting to this late, originally the V2 was not written with types and types were indeed added later, the problem was solved by [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3) which provides first class typescript support.
