### ISSUE TITLE
Complete response examples

### ISSUE THREAD

**Issue by mattBrzezinski** [aws/aws-sdk-js#3909]
Confirm by changing [ ] to [x] below:
- [x] This is a feature with version 2.x of the SDK

**Is your feature request related to a problem? Please describe.**
The example responses are incomplete. For example, [ECR DescribeRepositories](https://github.com/aws/aws-sdk-js/blob/3fab34806cab239cfb4bcf221327c1ef480670d7/apis/ecr-2015-09-21.examples.json#L137-L139) only provides back three fields, `registryId, repositoryArn, repositoryName`. However [Repository objects](https://github.com/aws/aws-sdk-js/blob/3fab34806cab239cfb4bcf221327c1ef480670d7/apis/ecr-2015-09-21.normal.json#L2805) contain various other fields such as `repositoryUri`.

**Describe the solution you'd like**
Include all fields in an example response.

**Comment by mattBrzezinski** [comment]
Hi Mario,

More background information. We use these example files to generate mock objects for testing purposes.

**Comment by omarioffline** [comment]
@MarioBrzezinski Try again

**Comment by omarioffline** [comment]
[amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc (1).zip](https://github.com/aws/aws-sdk-js/files/7297522/amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc.1.zip)
