### ISSUE TITLE
S3: NoSuchBucket Error when AWS.S3 is configured inside a test

### ISSUE THREAD

**Issue by shreddish** [aws/aws-sdk-js#3918]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x ] This is an issue with version 2.x of the SDK

**Describe the bug**
I am seeing the same issue as this "closed" ticket - the ticket was marked as closed but seems like all the trouble shooting was done offline and there wasn't any solution posted for the problem  https://github.com/aws/aws-sdk-js/issues/1577

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Possibly - the issue is occuring on our build server - running locally i can't seem to replicate

**Details of the browser/Node.js version**
its happening on our build server so can't access that terminal easily

**SDK version number**
Example: v2.850.0

**To Reproduce (observed behavior)**
see linked ticket - although i dont think my issue is exactly the same

**Expected behavior**
No Such Bucket is not thrown

**Screenshots**

**Additional context**

**Comment by vudh1** [comment]
Hi @shreddish , thanks for reaching out. Can you confirm if you are still experiencing this with the latest version `v2.1033.0
`, and if possible, please send a sample of reproducible code that you are using since you mentioned that your issue is not the same as the other ticket?
