### ISSUE TITLE
Cannot use "host.docker.internal" as SQS endpoint

### ISSUE THREAD

**Issue by dragondgold** [aws/aws-sdk-js#3922]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
When using an endpoint like `http://host.docker.internal:9324` to connect to a local SQS queue the queue URL is resolved to `localhost` instead of `host.docker.internal`

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
14.17.4

**SDK version number**
aws-sdk@2.1011.0

**To Reproduce (observed behavior)**
Run the following code:

```js
const AWS = require('aws-sdk');

const accessKey = '';
const secretKey = '';

const sqs = new AWS.SQS({
    region: 'us-west-1',
    apiVersion: '2012-11-05',
    accessKeyId: accessKey,
    secretAccessKey: secretKey,
    endpoint: 'http://host.docker.internal:9324'
});

sqs.getQueueUrl(
    {
        QueueName: 'local-test-queue'
    },
    (error, data) => {
        if (error) {
            console.error(error);
        } else {
            console.log(data.QueueUrl);
        }
    }
);
```

It will output `http://localhost:9324/000000000000/local-test-queue` when it should be `http://host.docker.internal:9324/000000000000/local-test-queue`

**Expected behavior**
The returned queue URL should preserve the hostname, in this case, it should be `http://host.docker.internal:9324/000000000000/local-test-queue`

**Comment by jenni** [comment]
+1

**Comment by yenfryherrerafeliz** [comment]
Hi @dragondgold, thanks for opening this issue.

@dragondgold, @jenni could you please let me know if this is a persistent issue for you all?, if so, could you please test with the latest minor version and see if the problem also happens there?. I did test on my local environment and I did not get any issues.
Please see my code below:
```js
import AWS from "aws-sdk";

const client = new AWS.SQS({
    region: 'us-east-2',
    endpoint: 'http://host.docker.internal:9324',
});
client.getQueueUrl(
    {
        QueueName: 'local-test-queue'
    },
    (error, data) => {
        if (error) {
            console.error(error);
        } else {
            console.log(data.QueueUrl);
        }
    }
);

```
And here is my output:
```console
UnknownEndpoint: Inaccessible host: `host.docker.internal' at port `undefined'. This service may not be available in the `us-east-2' region.
    at Request.ENOTFOUND_ERROR (PROJECT_DIR/node_modules/aws-sdk/lib/event_listeners.js:611:46)
    at Request.callListeners (PROJECT_DIR/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (PROJECT_DIR/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (PROJECT_DIR/node_modules/aws-sdk/lib/request.js:686:14)
    at error (PROJECT_DIR/node_modules/aws-sdk/lib/event_listeners.js:443:22)
    at ClientRequest.<anonymous> (PROJECT_DIR/node_modules/aws-sdk/lib/http/node.js:99:9)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketErrorListener (node:_http_client:490:9)
    at Socket.emit (node:events:513:28) {
  code: 'UnknownEndpoint',
  region: 'us-east-2',
  hostname: 'host.docker.internal',
  retryable: true,
  originalError: Error: getaddrinfo ENOTFOUND host.docker.internal
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3008,
    code: 'NetworkingError',
    syscall: 'getaddrinfo',
    hostname: 'host.docker.internal',
    region: 'us-east-2',
    retryable: true,
    time: 2023-01-25T13:36:02.609Z
  },
  time: 2023-01-25T13:36:02.609Z
}
```

As you could see, even when I am getting an error, the sdk is not resolving the given host as localhost. 

So please let me know.

Thanks!
