### ISSUE TITLE
Presigned URL PUT fails with S3 bucket which enforces bucket-owner-full-control

### ISSUE THREAD

**Issue by HaaLeo** [aws/aws-sdk-js#3925]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
When uploading a file with a presigned URL to a S3 bucket which enforces `bucket-owner-full-control` as described [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html#ensure-object-ownership) the upload fails.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
yes

**Details of the Node.js version**
v14

**SDK version number**
2.952.0

**To Reproduce (observed behavior)**
1. Create an s3Bucket called `myBucket` with the following bucket policy:
    ```json
    {
        "Version": "2012-10-17",
        "Id": "SSEAndSSLPolicy",
        "Statement": [
           
            {
                "Sid": "BackendWriteAccess",
                "Effect": "Allow",
                "Principal": {
                    "AWS": "myAccountId"
                },
                "Action": "s3:PutObject",
                "Resource": [
                    "arn:aws:s3:::myBucket",
                    "arn:aws:s3:::myBucket/*"
                ],
                "Condition": {
                    "StringEquals": {
                        "s3:x-amz-acl": "bucket-owner-full-control"
                    }
                }
            }
        ]
    }
    ```
1. Create a Lambda function to retrieve a pre-signed URL in the same AWS account:
    ```typescript
    const s3 = new S3({ region: process.env.REGION ?? 'eu-central-1' });
    const params = {
        Bucket: 'myBucket',
        Key: 'myKey.json',
        ACL: 'bucket-owner-full-control'
    };
    
    const signedUrl = await this.s3.getSignedUrlPromise(action, params);
    return signedUrl;
    ```
1. Try to upload some file with the retrieved Signed URL

**Expected behavior**
The file is uploaded

**Actual behavior**
A 403 forbidden response is returned.

**Comment by ajredniwja** [comment]
@HaaLeo thanks for reaching out, looking at the comment https://github.com/aws/aws-sdk-js/issues/1335#issuecomment-276425181, let me reach out to the S3 team and see what should be the right way to do this.

**Comment by HaaLeo** [comment]
@ajredniwja any update on this?

**Comment by AbraaoAlves** [comment]
I remove 'x-amz-acl' header from the upload request and it works. This looks like an AWS docs problem ...

**Comment by aBurmeseDev** [comment]
Hi all - checking in here. Sorry for the long wait. I wanted to confirm if the issue you previously reported is still persisting. Unfortunately, I was unable to reproduce the problem on my end using the recent version of the SDK. Could you please verify with recent version?
