### ISSUE TITLE
AWS SDK for Multi-part Upload "; charset=UTF-8" appended to content type by default

### ISSUE THREAD

**Issue by abrown92** [aws/aws-sdk-js#3927]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] This is an issue with version 2.x of the SDK

Hi,

We are experiencing issues with using the AWS SDK for Javascript for multi-part upload for our application. We are using v2.983.0 and we are working in AngularJS. The AWS SDK by default is adding "; charset=UTF-8" to the content type of any request that has a body of String.

When doing Multipart Upload, there is an initial request to set it up which has no body. This is seen to have a body of type String therefore the charset is being appended. There doesn't appear to be anything we can do to stop this as it is all AWS SDK methods and not our own. Do you know if its possible to get around this or has anyone else had issues where they require the charset not to be appended as could not see any workarounds online? We have Single Part Upload working since it does not have the charset appended and the internal API we are calling does not accept content types with charset appended on.

![plainTextContentType](https://user-images.githubusercontent.com/15984694/138467343-9ac23796-0539-4d74-b365-cd91acc919cf.png)

The following code is what I am referring to in the SDK:

if("string"!=typeof t.body||r.match(/;\\s*charset=/)) { var a=function(e,t,r) { return t+r.toUpperCase() }; t.headers["Content-Type"]=r.replace(/(;\\s*charset=)(.+)$/,a)}
else
{
t.headers["Content-Type"]+="; charset=UTF-8"
}

An example of how we set up our S3 objects:

function getS3Object(credentials,s3BucketName)
        {
            return new AWS.S3({
                credentials: credentials,
                params : {
                    Bucket : s3BucketName
                }
            });
        }
        function getS3FileUploader(s3, key, file)
        {
            return s3.upload({
                Key : key, 
                Body : file,
                ContentType : file.type
            },{
                queueSize : 10,
                partSize : 1024 * 1024 * 50
            });
        }

We have tried using both the .send and .promise on what is returned from getS3FileUploader but get the same result - the file gets uploaded to the S3 bucket but with the "; charset=UTF-8".

We make another service call after this to update metadata and the content type of this type above with the charset included causes it to fail.

Would be grateful if someone is able to help on this as I've saw a few other articles (https://github.com/aws/aws-sdk-js/issues/2510) and (https://github.com/aws/aws-sdk-js/issues/1011 ) that look similar to our problem but the proposed solutions do not help unfortunately as we want to send a content type in the request without the charset appended on. This issue occurs on all browsers for us as well, so isn't browser specific.

Thanks,
Andrew

**Comment by abrown92** [comment]
Hey @ajredniwja, I am just wondering if you had a chance to review my ticket? Is there any way around "; charset=UTF-8" being appended on to the content type or anything else that could be utilised to get around that problem? Thanks, Andrew.

**Comment by ajredniwja** [comment]
Hi @abrown92 the issue was commented on by @AllanZhengYP 

The comment holds true: https://github.com/aws/aws-sdk-js/issues/2510#issuecomment-538546023

This is done so the request doesn't break on some browsers. Changing this might be a breaking change.
