### ISSUE TITLE
`getSignedUrl` does not error if temporary credentials are invalid

### ISSUE THREAD

**Issue by glentakahashi** [aws/aws-sdk-js#3937]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
When using `getSignedUrl` and `TemporaryCredentialsProvider`, whenever the credentials expire, `getSignedUrl` will not error while the credentials are being refreshed.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v14.17.5

**SDK version number**
aws-sdk@2.836.0

**To Reproduce (observed behavior)**
```
import { ChainableTemporaryCredentials, Credentials, S3 } from "aws-sdk";

async function main() {
  const credentials = new ChainableTemporaryCredentials({
    params: {
      RoleArn: "somerole",
      RoleSessionName: "getPresignedUrlTest",
    },
    stsConfig: {
      region: "us-east-2",
    },
    masterCredentials: new Credentials({
      accessKeyId: "somekey",
      secretAccessKey: "somesecret",
    }),
  });
  const s3Config: S3.Types.ClientConfiguration = {
    credentials,
    signatureVersion: "v4",
    region: "us-east-2",
  };

  const s3 = new S3(s3Config);

  for (let i = 1; i <= 5; i++) {
    console.log(`URL ${i}`);

    console.log(
      await s3.getSignedUrl("getObject", {
        Bucket: "mybucket",
        Key: "25cbf06d-[...]",
      }),
    );
    await new Promise((r) => setTimeout(r, 500));
  }
}
main();
```

Without "sleep" await:
```
URL 1
https://s3.us-east-2.amazonaws.com/
URL 2
https://s3.us-east-2.amazonaws.com/
URL 3
https://s3.us-east-2.amazonaws.com/
URL 4
https://s3.us-east-2.amazonaws.com/
URL 5
https://s3.us-east-2.amazonaws.com/
```

With "sleep" await:
```
URL 1
https://s3.us-east-2.amazonaws.com/
URL 2
https://mybucket.s3.us-east-2.amazonaws.com/25cbf06d-[...]&X-Amz-SignedHeaders=host
URL 3
https://mybucket.s3.us-east-2.amazonaws.com/25cbf06d-[...]&X-Amz-SignedHeaders=host
URL 4
https://mybucket.s3.us-east-2.amazonaws.com/25cbf06d-[...]&X-Amz-SignedHeaders=host
URL 5
https://mybucket.s3.us-east-2.amazonaws.com/25cbf06d-[...]&X-Amz-SignedHeaders=host
```

**Expected behavior**
Error is thrown while credentials are invalid.

**Screenshots**

**Additional context**
The above code works fine if I swap out for `getSignedUrlPromise` or use the `getSignedUrl` + `callback` signature, which we have since moved to, however this should still throw an error to prevent accidental misuse.

**Comment by ajredniwja** [comment]
Hi @glentakahashi thanks for bringing this to our attention. While we can track this as a bug with a workaround available this problem should be solved in [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3).

**Comment by aBurmeseDev** [comment]
Hello @glentakahashi - apologies for the long silence here. After a thorough discussion with our team, we have decided not to proceed with the change. This decision was made considering the availability of a workaround and the fact that version 3 already addresses the issue. Additionally, as we [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-javascript-v2/), the AWS SDK for JavaScript v2 will enter maintenance mode in September. Therefore, we will close this request as not planned for implementation.
