### ISSUE TITLE
DynamoDB: Cannot read property 'push' of undefined: DynamoDB.scan.promise()

### ISSUE THREAD

**Issue by ahmednkhan24** [aws/aws-sdk-js#3938]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
-  [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
- I have an existing AWS Serverless API Gateway V1 using NodeJS that communicates with a DynamoDB table via query, put, update, delete, etc.
- I am writing a Lambda event to scan the database on a dataset that is >1MB and I am following the official [AWS documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.04.html#GettingStarted.NodeJs.04.Scan). 
-  When I invoke my Lambda, I get this error in the CloudWatch logs:
   ```json
   {
    "message": "Cannot read property 'push' of undefined",
    "code": "TypeError",
    "time": "2021-11-01T23:07:15.026Z",
    "statusCode": 200,
    "retryable": false,
    "retryDelay": 43.05237873541141
}
- I found a [similar issue on GitHub](https://github.com/aws/aws-sdk-js/issues/1453#issuecomment-397649406) that had a recommended workaround of not using the built-in `scan.promise()` and resolving the promise manually.
- This workaround did work for the first 1MB of data, however it does not solve my problem entirely because my dataset is >1MB and the scan needs to be called again with the last evaluated key. However this recursive part of scan is not possible using the recommended workaround. I need to be able to use the built-in `scan.promise()` in order to wait for my entire dataset to be available. 


**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
Node v14.17.6

**SDK version number**
2.726.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
```javascript
const AWS = require('aws-sdk');
AWS.config.update({ region: 'us-east-1' });
const dynamo = new AWS.DynamoDB.DocumentClient();
TABLE_NAME = 'my_test_table';

const onScan = async (err, data) => {
  if (err) {
    console.error('Unable to scan the table. Error: ', JSON.stringify(err));
    return;
  }

  console.log('Scan succeeded! Data: ', JSON.stringify(data));

  if (typeof data.LastEvaluatedKey !== 'undefined') {
    console.log('Scanning for more...');
    const params = {
      TableName: TABLE_NAME,
      ExclusiveStartKey: data.LastEvaluatedKey,
    };
    dynamo.scan(params, onScan);
  }
};

const scanAllDatabaseItems = async () => {
  console.log(`starting scan on the ${TABLE_NAME} database table...`);
  const params = {
    TableName: TABLE_NAME,
  };
  await dynamo.scan(params, onScan).promise();
  console.log('Finished scanning all database items.');
};

const handler = async () => {
    await scanAllDatabaseItems();
    return {
      statusCode: 200,
      body: JSON.stringify({ hello: 'world' }),
    };
};
```

**Expected behavior**
- DynamoDB data should be returned instead of an error being outputted.

**Screenshots**

**Additional context**
- I am unable to update the aws-sdk to to 3.x.x.

**Comment by ajredniwja** [comment]
Hi @ahmednkhan24, thanks for reaching out, I think the problem occurs because you use a promise which somehow ends up in a race condition and is not fulfilled. 

I was able to get it working using something like:

```js
    try {
        console.log(`starting scan on the ${TABLE_NAME} database table...`);
        const params = {
          TableName: TABLE_NAME,
        };
         docClient.scan(params, onScan);
        console.log('Finished scanning all database items.');

    } 
    catch (err) {
        console.log(err)
    }
```

Would also like to know why you were not able to update to version 3 of the SDK.

**Comment by ahmednkhan24** [comment]
Thanks for the speedy response, @ajredniwja! 

I am also able to scan the database in the manner you are. 
The problem is there are processes I need to run once all of the data has been scanned.
To my understanding, the only way to wait for all data to be scanned is by `await`ing the `scan.promise()`. 
We are taking a similar approach with other dynamo options like query, put, batchWrite, etc. 

Is there another way I can wait to execute my code once all of the data is scanned?

I guess I should have worded version 3 update better. It's not that I am failing to update to version 3 of the SDK. We are doing things like this in our existing code with the current package version:
```javascript
const dynamoResponse = await dynamo.query(params).promise();
return dynamoResponse;
...
await dynamo.delete(params).promise();
...
await dynamo.batchWrite(params).promise();
```
So I am hoping there should be a way to use the `.promise()` chain on `dynamo.scan()` without having to update to the latest version of the SDK.

**Comment by ahmednkhan24** [comment]
I was able to solve the problem while still achieving my goal by doing this instead of the [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.04.html#GettingStarted.NodeJs.04.Scan).

```javascript
    const baseDbParams = {
      TableName: TABLE_NAME,
    };

    let data = await dynamo.scan(baseDbParams).promise();
    let databaseItems = [...data.Items];

    // scan maxes out at 1MB of data. continue scanning if there is more data to read
    while (typeof data.LastEvaluatedKey !== 'undefined') {
      console.log('Scanning for more...');
      const params = {
        ...baseDbParams,
        ExclusiveStartKey: data.LastEvaluatedKey,
      };
      data = await dynamo.scan(params).promise();
      databaseItems = [...databaseItems, ...data.Items];
    }

   console.log('all databaseItems: ', JSON.stringify(databaseItems));
```
