### ISSUE TITLE
DocumentClient query() method rejects ExpressionAttributeValues without FilterExpression even when KeyConditionExpression is present

### ISSUE THREAD

**Issue by jmathes** [aws/aws-sdk-js#3941]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] This is an issue with version 2.x of the SDK

I believe this is a bug report, but the submission criteria for those are too onerous. I'm willing to let you know there's an issue, but not when you make it that difficult.

Dynamodb's DocumentClient query() method documentation suggests using KeyConditionExpression with value substitutions from ExpressionAttributeValues, but rejects this usage:
```
  ValidationException (Error) {
    code: 'ValidationException',
    message: 'ExpressionAttributeValues can only be specified when using expressions: FilterExpression is null',
    requestId: '8db870c0-61b4-4098-a11e-715db180c9cc',
    retryDelay: 25.85736148675448,
    retryable: false,
    statusCode: 400,
    time: Date 2021-11-03 13:44:05 119ms UTC {},
  }
```
This seems like an error message leftover from scan(), which doesn't accept KeyConditionExpressions.

**Comment by ajredniwja** [comment]
Hi @jmathes, can you please share the code that you are using?
