### ISSUE TITLE
For AWS-SDK, uuid package out of date may cause problems with random numbers

### ISSUE THREAD

**Issue by ConzumexGame** [aws/aws-sdk-js#3943]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [] This is an issue with version 2.x of the SDK

**Describe the bug**
I get several warnings when installing aws-sdk package using npm. It is complaining about the version of uuid used. Which is significantly behind the current version. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.

**Is the issue in the browser/Node.js?**
Browser/Node.js

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
v16.13.0

**SDK version number**
aws-sdk@2.1023.0

**To Reproduce (observed behavior)**
npm i aws-sdk

**Expected behavior**
No warnings

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @ConzumexGame thanks for bringing this up, can you please share what warnings you get?

**Comment by SchmitzChristian** [comment]
Hi @ajredniwja this is what i get:

`uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`

**Comment by purejgleason** [comment]
Same issue here problem is...

    "uuid": "3.3.2",

**Comment by purejgleason** [comment]
Also getting 

    querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
    
 Thanks to the dep on url...
 
     "url": "0.10.3",
     
 Should be `0.11.0`

**Comment by robahtou** [comment]
Any updates on this? getting same warnings
```
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.  
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Comment by ezequiel454** [comment]
I will follow this thread with same errors

`npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`

**Comment by jeremychone** [comment]
I really hope this can be fixed soon. 

Now, uuid is at version > 8.x, and having such an old deprecated version in our builds is worrisome and makes our security team nervous. 

AWS-SQK team, your library is great, and we use it for big enterprise applications with high compliance requirements, but  this issue has been a problem in our context.

**Comment by ajredniwja** [comment]
Closing this issue now. https://github.com/aws/aws-sdk-js/pull/3924
