### ISSUE TITLE
documentClient with LSI returns LastEvaluatedKey for last record

### ISSUE THREAD

**Issue by jatinmehrotra** [aws/aws-sdk-js#3955]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
I am trying pagination with LSI, my table has 3 LSI. Upon reaching the last record it should not return LastevaluatedKey, however it returns LastEvaluatedKey which makes it difficult to paginate backward.
Other 2 LSI index are working fine and keeps LastEvaluatedKey as null for last records

**If on Node.js, are you running this on AWS Lambda?**
yes i am running on AWS Lambda

**Details of the browser/Node.js version**
v16.1.0

**SDK version number**
v2.970.0
**To Reproduce (observed behavior)**
```
params.ScanIndexForward = false;
  response = await dynamoDb.query(paramsForQuery).promise();
  console.log('response', response);
  const arrayLength = response.Items.length;
  LastEvalSortKey = {
    pk: userId,
    originalUrl: response.Items[0].originalUrl,
  };
  if (sortBy === 'createdAt')
    LastEvalSortKey[sortBy] = response.Items[0].createdAt;
  if (sortBy === 'updatedAt')
    LastEvalSortKey[sortBy] = response.Items[0].updatedAt;
  if (sortBy === 'convertedUrl')
    LastEvalSortKey[sortBy] = response.Items[0].convertedUrl;
  return {
    items: response.Items,
    nextToken: arrayLength
      ? Base64.encodeURI(JSON.stringify(LastEvalSortKey))
      : prevToken,
    prevToken: response.LastEvaluatedKey
      ? Base64.encodeURI(JSON.stringify(response.LastEvaluatedKey))
      : undefined,
  };

```
**Expected behavior**
response.LastEvaluatedKey should be null for last record which is not, how to determine last record for reverse pagination.

**Comment by vudh1** [comment]
Hi @jatinmehrotra thanks for reaching out. According to [this documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-response-LastEvaluatedKey), `LastEvaluatedKey` being empty means that there is no more data to be retrieved, but if it is not empty, it does not **necessarily** mean that there is more data. A way you can try to workaround is to query for `page + 1` items, then check how many items the query return would help to paginate backward.
