### ISSUE TITLE
missing SourceFile value in S3 putObject parameter

### ISSUE THREAD

**Issue by programming-kid** [aws/aws-sdk-js#396]
I have used php sdk a while ago and it had this SourceFile key where you can give path of tmp file on your disk to upload to S3 in putObject function but i find it missing in node sdk. 

is there a reason for that ??

i am currently using `connect-multiparty` which create tmp files that i use to upload to S3 bucket . As i was familiar with php sdk i thought there would be Sourcefile parameter to be passed to putObject function , but there is not mention of it in node sdk api docs.

so i am using `createReadStream` to pass Stream to `Body` key is this the right way to pass value to Body or am i missing something , is there a chance of memory leaks , although i will only uploading images within 5 MB

Thanks

**Comment by jdoavila** [comment]
You've been able to solve this problem?, I could not send a picture of $cordovaCamera to Amazon S3. Help me, maybe you can show me the final code.
