### ISSUE TITLE
createPresignedPost - access denied error

### ISSUE THREAD

**Issue by vieirai** [aws/aws-sdk-js#3975]
Confirm by changing [ ] to [x] below:
- [ ] This is a feature with version 2.x of the SDK

**Is your feature request related to a problem? Please describe.**
A lambda without `s3:putObject` permissions can do `s3.createPresignedPost` and will receive what appears to be a valid upload config.
However, once we try to use the parameters returned by `createPresignedPost` to upload anything, we're faced with a `403` - `Access Denied` error and it's really confusing where the access problem actually is.

**Describe the solution you'd like**
If a lambda without `s3:putObject` permissions tries to generate s3 signed POST URLs, then a permissions error should be thrown right then and there.

**Describe alternatives you've considered**
Maybe a better error message as opposed to the very generic `Access denied`?

**Additional context**
N/A

**Comment by jo-sip** [comment]
Thanks for bringing this up, you saved me more hours on already many wasted!
