### ISSUE TITLE
[Question] deviceMinutes total doesn't match with it's children

### ISSUE THREAD

**Issue by huzaifaAhmedTestlio** [aws/aws-sdk-js#3978]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] This is an issue with version 2.x of the SDK

**Describe the question**

While running AWS device farm we get the results something like 
`  "billingMethod": "METERED",
  "deviceMinutes": { "total": 83.35, "metered": 75.69, "unmetered": 0 },`

Can someone please elaborate on why there is a difference between total and metered numbers? Thanks

**Comment by huzaifaAhmedTestlio** [comment]
https://docs.aws.amazon.com/devicefarm/latest/APIReference/API_DeviceMinutes.html

Does 'total' includes other minutes as well (like setting up devices) ?

**Comment by ajredniwja** [comment]
@huzaifaAhmedTestlio thanks for opening this issue, the response is returned by the service and the docs indeed do not specify why there is a difference, reaching out to the team to know more.

**Comment by huzaifaAhmedTestlio** [comment]
> @huzaifaAhmedTestlio thanks for opening this issue, the response is returned by the service and the docs indeed do not specify why there is a difference, reaching out to the team to know more. (V482818763)

Thank you @ajredniwja. Looking forward for the updates.

**Comment by huzaifaAhmedTestlio** [comment]
@ajredniwja @aws-sdk-js-automation  @awstools any updates on this thread please?

**Comment by ajredniwja** [comment]
@huzaifaAhmedTestlio Apologies I lost track of it total in deviceMinutes includes setup time for devices as well. Customer is only charged for either metered or unmetered minutes .

**Comment by aBurmeseDev** [comment]
Here's response from service team:

>`total` in `deviceMinutes` includes setup time for devices as well. Customer is only charged for either metered or unmetered minutes.

Since there's no action item for SDK team and no further follow up question, I'm going to close this issue. Feel free to open a new issue if there are any other questions.
