### ISSUE TITLE
`exportApi` returns `400 BadRequestException` error when schema is empty

### ISSUE THREAD

**Issue by vinitshahdeo** [aws/aws-sdk-js#3980]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
The `exportApi` returns **400 BadRequestException** error. Kindly refer the API [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayV2.html#exportApi-property).

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
`v12.18.3`

**SDK version number**
`aws-sdk@2.1012.0`

**To Reproduce (observed behavior)**
- Create a new HTTP API without a schema
- Copy the API Id
- Export API that will return **400 BadRequestException** error with a misleading message

```js
const AWS = require('aws-sdk'),
  apigatewayv2 = new AWS.ApiGatewayV2({
        accessKeyId: 'XXXXXXX',
        secretAccessKey: 'XXXXXXXXX',
        region: 'us-east-1'
    }),
    params = {
      ApiId: 'Replace with your API Id', // this API shouldn't contain any route
      OutputType: 'JSON',
      Specification: 'OAS30'
    };

apigatewayv2.exportApi(params, function (err, data) {
    if (err) {
      console.log(err);
    }
    else {
      console.log(data.body.toString('utf-8'));
    }
});
```
This will return the following error:

```
message: 'Unable to deploy API because no routes exist in this API',
code: 'BadRequestException'
```

**Expected behaviour**
The returned error message seems misleading as we're trying to export the API not deploy the API.

**Comment by ajredniwja** [comment]
Hey @vinitshahdeo, thanks for opening this issue, unfortunately as the messages are returned by the service itself there is not a lot that SDK can do, I will reach out to API gateway team to know more about this and see if they can fix this.
