### ISSUE TITLE
CloudWatch PutmetricData request size

### ISSUE THREAD

**Issue by shidaying** [aws/aws-sdk-js#3984]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatch.html#putMetricData-property
 request size limit to 40kb, now i limit my params below 40kb, but it returns error with request size more than 40kb
 
```
Buffer.byteLength(JSON.stringify(params), 'utf8')

this.cloudwatch.putMetricData(
            params,
            (err) => {})
```

i think it should tell me what's the limit size of params and what's the coding when compuing size

**Comment by vudh1** [comment]
Hi @shidaying thanks for reaching out. I am not able to reproduce this. Can you send reproducible code (with more information about what is your `params`)? How do you check that your request is 40KB or under?

**Comment by shidaying** [comment]
params = {
namespace,
MetricData
}

just use `Buffer.byteLength(JSON.stringify(params), 'utf8')` to compute size

**Comment by vudh1** [comment]
Hi @shidaying can you send more details on how you limit your params under 40KB? also a screenshot/copy of log would be helpful? I use this code below and it works:
```js
const AWS  = require('aws-sdk');
const zlib = require('zlib');

const cloudwatch = new AWS.CloudWatch({region : "us-west-2"});

cloudwatch.putMetricData(zippedData, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});

```
