### ISSUE TITLE
Using s3.upload for upload from iPhone when it's in the sleep mode

### ISSUE THREAD

**Issue by contactBetterplay** [aws/aws-sdk-js#3989]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] This is an issue with version 2.x of the SDK

I have a Web App (not a mobile app) which runs under a browser. Users upload large files (videos). The pseudocode:

function upload_to_s3 (k) {

const s3 = new AWS.S3();
const upload_params = {...};

s3.upload(upload_params,(err) => {error_callback (err);}
               ).on("httpUploadProgress", 
                    (evt) => { update_upload (evt, k); }
                   ).send((evt) => { after_video_completion(k); });
}

This works well when uploading from PC or from a smartphone which is not in the sleep mode. However, when in the sleep mode, it's stuck until the device is awaken. Once alive again, it proceeds to the next steps. 

My major issue is how to enable the upload of the videos even when iPhone is in the sleep mode.

**Comment by ajredniwja** [comment]
@contactBetterplay apologies for losing track of this issue, I believe this not to be an SDK issue but how SDK behaves. I phone sleeping and not having enough time to recover for connection is what causes the upload to fail.
