### ISSUE TITLE
RequestTimeTooSkewed error with S3 upload

### ISSUE THREAD

**Issue by fkjaekel** [aws/aws-sdk-js#399]
Sorry to post this here, but as I didn't get feedback on the forum I'd like to check the possibility of a SDK bug.

I have a JavaScript client for multipart uploads to Amazon S3 that is based on this code: https://gist.github.com/sevastos/5804803

About two weeks ago I stared to get complaints about a RequestTimeTooSkewed error on the start of the upload process.

Googling about I saw a lot of solutions to correct the server time for server side uploads, but as I'm using the JavaScript SDK (version 2.0.22), I assume that the client's computer time is going to be used for the request right? In that case, coincidentally the complaints started after Brazilians daylight saving, where the clock was forwarded 1 hour in some states.

I'm able to simulate this error if I backward my computer clock in one hour, but my client is on the same state that I am and he sent me a print screen right after the error happened, so I could see that his clock was right.

Is it possible to set the request time programmatically, so I could query Amazon's server and set the correct time?

Thanks in advance

**Comment by ostaptan** [comment]
So this piece of code is tested and works correctly if someone needs
`AWS.events.on('retry', function(response) {
      if (response.error.name === 'RequestTimeTooSkewed') {
        console.error('User time is not correct. Handling error!');
        console.log('AWS systemClockOffset:', AWS.config.systemClockOffset);

        var serverTime = Date.parse(response.httpResponse.headers['date']);
        var timeNow = new Date().getTime();

        console.log('AWS timestamp:', new Date(serverTime));
        console.log('Browser timestamp:', new Date(timeNow));

        AWS.config.systemClockOffset = Math.abs(timeNow - serverTime);
        response.error.retryable = true;

        console.log('Setting systemClockOffset to:', AWS.config.systemClockOffset);
        console.log('Retrying uploading to S3 once more...');
      }
    });`

You should add  this one to your CORS AWS setup: `Access-Control-Expose-Headers: Date` so that this one works properly
`var serverTime = Date.parse(response.httpResponse.headers['date']);`

**Comment by lonormaly** [comment]
Thanks for sharing! 

Can you please show a general use case of this code? Should it be ran only after a first try?

**Comment by vhmth** [comment]
https://www.opentest.co/share/5a54713059cd11e69680a3b55516ed77

**Comment by ostaptan** [comment]
@lonormaly It will run as many times as you allow it to retry. General use case is actually just a one more protection of bug, if user's computer is not synched with time. 

Regarding `systemClockOffset is not being set` just provide some code in jsfiddle for me to help you.

**Comment by imouaddine** [comment]
I was able to fix this issue by using using `correctClockSkew` config.

```
 AWS.config.update({
    correctClockSkew: true,
  });
```

**Comment by vhmth** [comment]
@imouaddine is that new to the API?

**Comment by imouaddine** [comment]
@vhmth not sure. 

Reference: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html

**Comment by vhmth** [comment]
@imouaddine 🙏
