### ISSUE TITLE
error: node_modules\aws-sdk\dist\aws-sdk-react-native.js: Call retries were exceeded

### ISSUE THREAD

**Issue by shakeel0581** [aws/aws-sdk-js#3990]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [ ] This is an issue with version 2.x of the SDK

**Describe the bug**

**Is the issue in the browser/Node.js?**
Browser/Node.js

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vudh1** [comment]
Hi @shakeel0581 thanks for reaching out. Can you confirm if this problem is still persisting with the latest version of SDK `2.1046.0`? Also, if yes, please provide a sample of reproducible code that you use that we can investigate this problem more?

**Comment by maximusblade** [comment]
I am currently experiencing this exact problem. I've tried a few things but cant figure it out.

**Comment by mauricekleine** [comment]
@vudh1 This happens for me too, but only when I use Expo's `eas` to build the app (using `eas build`). Locally and using Expo Go, the app runs just fine, but as soon as I start a new app build with EAS, the build fails with the error above (Call retries were exceeded). When I change the import to `import AWS from "aws-sdk"` the app build succeeds, but I'm unable to run the app locally. I don't have a reproducable code example at the moment, but maybe this helps already.
