### ISSUE TITLE
GitHub releases are no longer created after v2.1048.0

### ISSUE THREAD

**Issue by tobilg** [aws/aws-sdk-js#4003]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [ ] This is an issue with version 2.x of the SDK

**Describe the bug**

Since version v2.1048.0 there are no more GitHub releases being published in this Repo. npm has already v2.1050.0, see npmjs.com/package/aws-sdk

**Comment by tobilg** [comment]
Seems like it’s working again with v2.1051.0

**Comment by ajredniwja** [comment]
Closing this issue now, please reach out if there are any questions. Thanks
