### ISSUE TITLE
Support SigV4 unsigned headers configuration

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-sdk-js#4007]
Confirm by changing [ ] to [x] below:
- [x] This is a feature with version 2.x of the SDK

**Is your feature request related to a problem? Please describe.**
Related to https://stackoverflow.com/questions/64693442/wrong-aws-request-signature-caused-by-opentelemetry-https-plugin

For 3rd party tools that mutates the headers, they are likely to break the SigV4 signature because v2 SDK uses a blocklist of unsigned headers. So arbitrary headers from these tools are signed, hence it breaks the signature. 

https://github.com/aws/aws-sdk-js/blob/37dd81b98c88d25e6a568ddf3411d9d13937863c/lib/signers/v4.js#L191-L199

**Describe the solution you'd like**
Without breaking the backwards compatibility, we should add a new client config `sigv4UnsignedHeaders: string[]`. When set, the SigV4 signer will stop signing specified headers. 

**Additional context**
P58320462

**Comment by mugli** [comment]
Is there any chance to reopen this?
