### ISSUE TITLE
Kinesis video streaming takes 21-40s latency to stablish video

### ISSUE THREAD

**Issue by fredhii** [aws/aws-sdk-js#4010]
Confirm by changing [ ] to [x] below:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [] This is an issue with version 2.x of the SDK

**Describe the question**
Video stream signaling channels takes avg 24seconds to establish a video connection between a master and a viewer
the issue was mentioned in the previous [kinesis js library](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/53) but never got solved

We tried different configurations as mentioned in the previous issue but got the same results of waiting time

Also, we notice that the Bitrate arrives in the kinesis console but the video takes time to be present
![image](https://user-images.githubusercontent.com/57413945/149412524-bbd23b0d-a841-410b-8be6-83876fb1dfa1.png)

**Comment by vudh1** [comment]
Hi @fredhii thanks for reaching out. Please open an issue with [amazon-kinesis-video-streams-webrtc-sdk-js](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js) as this is not SDK issue.
