### ISSUE TITLE
S3.upload Content-Encoding header disappeared

### ISSUE THREAD

**Issue by hellopeera** [aws/aws-sdk-js#4013]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] This is an issue with version 2.x of the SDK

**Describe the question**
Uploading a large file (> 5MB - larger than the default part size) to S3 using S3.upload results in an empty Content-Encoding header which is explicitly set. 

The Content-Encoding header won't be affected if 
- the uploaded file is smaller than 5MB
- the part size were to configured to a number larger than the size of the file.

**Example code**
```
const uploadParams: PutObjectRequest = {
  Body: file.stream,
  Bucket: 'bucket-name',
  Key: 'key',
  ContentType: 'text/csv',
  ContentEncoding: 'gzip',
}
const uploadOpts: S3.ManagedUpload.ManagedUploadOptions = {
  partSize: 5*1024*1024,
}
s3.upload(uploadParams, uploadOpts);
```

**SDK version**
2.1060.0

**Comment by vudh1** [comment]
Hi @hellopeera thanks for reaching out. Is this still persting with the latest version of SDK? I am not able to reproduce this.
