### ISSUE TITLE
Cognito Identity service provider returning different cognito error for Refresh Token API from Jan 21st, 2022

### ISSUE THREAD

**Issue by Suvab-rently** [aws/aws-sdk-js#4016]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
I have a single userPool under which I have two client apps.

Using: amazon-cognito-identity-js, aws-sdk

Previously before (Jan 21, 2022 IST), when we signed in using one client app and then used the refresh token api to refresh the access token by passing another client app Id we were getting the error NotAuthorizedException: Invalid Refresh Token.

But since Jan 21, 2022 IST we are receiving a different error for the same scenario - NotAuthorizedException: Refresh Token has different Client.

I also tried with an updated amazon-cognito-identity-js library but the issue persists.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
v12.18.4

**SDK version number**
+-- amazon-cognito-identity-js@1.31.0
| `-- aws-sdk@2.177.0 

**To Reproduce (observed behavior)**
Let us consider a userPoolId - UserPoolA
and two client app within the userpool - clientApp1 and clientApp2.

Login using clientApp1.
Use the refresh token received from step (1) to refresh the access token but this time pass the clientId as clientApp2
Initial Error Message: **NotAuthorizedException: Invalid Refresh Token** (Expected)
New Errror Message: **NotAuthorizedException: Refresh Token has different Client** (Unexpected, happening since January 21, 2022 IST)

**Expected behavior**
When we signed in using one client app and then used the refresh token api to refresh the access token by passing another client app Id we should be getting the error **NotAuthorizedException: Invalid Refresh Token.**

**Additional context**
Code Snippet:
```
// Let us consider a userPoolId -  UserPoolA
// and two client app -  clientApp1 and clientApp2.

const AmazonCognitoIdentity = require('amazon-cognito-identity-js');
const { CognitoUserPool } = AmazonCognitoIdentity;
const aws = require(aws-sdk);
const cognitoidentityserviceprovider = new aws.CognitoIdentityServiceProvider();

// For logging in: 
const params = {
          AuthFlow: "ADMIN_NO_SRP_AUTH"
          ClientId: **clientApp1**
          UserPoolId: **UserPoolA**
          AuthParameters: {
            USERNAME: username,
            PASSWORD: password
          }
        }
        cognitoidentityserviceprovider.adminInitiateAuth(params, function (err, data) { }

// For refreshing the token: 

const params = {
    AuthFlow: 'REFRESH_TOKEN_AUTH',
    ClientId: **clientApp2** ,
    UserPoolId: **UserPoolA**
    AuthParameters: {
      REFRESH_TOKEN: **refreshToken received from step 1 Login.**
    }
  }
  cognitoidentityserviceprovider.adminInitiateAuth(params, function (err, data) { }

```
**P.S: We hadn't updated any version of the aws package before we started observing this change in message**

**Comment by Suvab-rently** [comment]
Can anyone please check this and provide some insights. Thanks

**Comment by AliOatley** [comment]
I would like to know about this as well
