### ISSUE TITLE
Add ConditionExpression to DynamoDB batch write

### ISSUE THREAD

**Issue by ocdinvstr** [aws/aws-sdk-js#4018]
I would like to put a bunch of items with batchWrite if my condition validates, even putItem is supporting ConditionExpressions for that purpose, DynamoDB batchWrites do not support ConditionExpressions. For that I have to make many parallel calls to DynamoDB which could be solved with batchWrite if it had ConditionExpressions support. If we had it in batchWrite that would save me a lot.

**Comment by shihuayong** [comment]
Same question!!!

**Comment by JohnnyUFT** [comment]
same here!

**Comment by d3vCr0w** [comment]
I have the same problem, it took me hours to figure it out.

**Comment by danny-zegel-zocdoc** [comment]
does the DDB API even support batch writes with conditional expressions?

**Comment by kellertk** [comment]
Hello. This is not something that's supported by the DynamoDB API, and is called out in the [DynamoDB documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html).
