### ISSUE TITLE
Next Js production build uploader not working

### ISSUE THREAD

**Issue by vusaalab** [aws/aws-sdk-js#4019]
Confirm by changing [ ] to [x] below:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] This is an issue with version 2.x of the SDK

This code working properly on next js development but not working on production build, any idea what is going on

        let s3 = new S3({
            accessKeyId: 'key',
            secretAccessKey: 'secret,
            region: 'ap-southeast-1',
        });

        let params = {
            ACL: 'public-read',
            Bucket: 'blockstars.io',
            Key: file.name,
            Body: file,
            CacheControl: 'max-age=630720000, public',
            ContentType: file.type,
        };

        console.log('Uploading1...');
        s3.upload(params, function(err, data) {
            console.log(err, data); // production build file is not uploading ...
        });
        console.log('Uploading1... done');

There was no error event but the file is not uploading ...

**Comment by vudh1** [comment]
Hi @vusaalab thanks for reaching out. Is this problem still persisting? I checked and the code works, and you said that it is also working with next js dev so I suspect something is not correctly set up in production build.
