### ISSUE TITLE
Issue in uploading to S3

### ISSUE THREAD

**Issue by UmerEdava** [aws/aws-sdk-js#4021]
Inaccessible host '  ' at port undefined: This service may not available in the 'us-east-1' region 

One of my co-worker getting this error while uploading to s3.......

**Comment by ajredniwja** [comment]
This error message can be because of multiple issues:

Please fill out: https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=
