### ISSUE TITLE
AWS SDK Translate translateText sometimes throws Timeout in Lambda

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [aws/aws-sdk-js#4034]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**

We've been using Lambda and the SDK for a few months, we are doing some translations on background with SQS, so we push some IDs we get the info and then we use AWS Translate with the SDK.

We have a wait time of 1 hour on Lambda, the lambda role has the needed permissions, we know that because sometimes it works, the VPC Subnets have access to internet too.  

The main issue its with ther Translate Client it self, sometimes it throws the next:

```
TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
    errno: -110,
    code: 'TimeoutError',
    syscall: 'connect',
    address: '3.226.59.1',
    port: 443,
    time: 2022-02-17T18:40:28.230Z,
    region: 'us-east-1',
    hostname: 'translate.us-east-1.amazonaws.com',
    retryable: true
  }

```
**Is the issue in the browser/Node.js?**

Node.js

**If on Node.js, are you running this on AWS Lambda?**

Yes

**Details of the browser/Node.js version**
 Lambda Version

**SDK version number**
Lambda SDK Node v14.x

**To Reproduce (observed behavior)**

```
var AWS = require("aws-sdk");
AWS.config.update({region: "us-east-1"});

class Translate{

    constructor(trans){
        this.locale = null;
        this.phraseProxy = null;
        this.objTranslate = new AWS.Translate();
    }
    async translateText(text, sourceLangCode, targetLangCode){
        
        if(!text) return null;

        var params = {
        SourceLanguageCode: (sourceLangCode) ? sourceLangCode:'auto',
        TargetLanguageCode: targetLangCode,
        Text: text.toString('utf-8')
        };
     
        const objTrans = this.objTranslate;
        console.log("objecttrans --->",objTrans);
        return new Promise((resolve, reject) => {
             
             objTrans.translateText(params, function (err, data) {
                if (err){
                    console.log("error translation ", err)
                    resolve(err);
                } 
                else{
                    resolve(data); 
                }   
            });

        });
    }
}
       
```

**Expected behavior**

Finish the translate the SDK Translate Client function without timeout.

**Comment by ulisescarreonalvarez** [comment]
We try to do the next:

* Use only private subnets (at the end it doesn't matter if we use public the lambda has internet access)
* We change the httpOptions to KeepAlive the connections
* We tried to change the code to split the requests on multiple batches.

But at the end it doesn't work as expected, AWS Translate SDK suddenly shows TimeOut.
It happens sometimes, its the only service that we are facing that error.

The documentation tell us about the timeout and we tried to configure the client like this:

`https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html`

We need some advice with this issue.

**Comment by ajredniwja** [comment]
Can you also share what version of the SDK you are using?

**Comment by ulisescarreonalvarez** [comment]
@ajredniwja It's the same version as the Node JS Lambda Function, we don't upload a certain version

**Comment by ajredniwja** [comment]
I see a lot of changes to translate after the current version that is shipped with Lambda, can you please update the SDK to the latest version? 
You can follow [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies)

**Comment by lfvillavicencio** [comment]
Facing the same issue with python runtime 3.9 on Lambda.
Calling from `boto3`
