### ISSUE TITLE
UnknownEndpoint: Inaccessible host: `localhost' at port `8002'. This service may not be available in the `us-east-1' region.

### ISSUE THREAD

**Issue by nikhilpatilTR** [aws/aws-sdk-js#4035]
UnknownEndpoint: Inaccessible host: `localhost' at port `8002'. This service may not be available in the `us-east-1' region.

I am getting this error when trying to access local-dynamo using http://localhost:8000

**Comment by ajredniwja** [comment]
Can you please follow the [issue template](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)?

**Comment by fancywriter** [comment]
@nikhilpatilTR did you try 127.0.0.1 instead of localhost?
