### ISSUE TITLE
Add JavaScript examples for SDKv3

### ISSUE THREAD

**Issue by TrueWill** [aws/aws-sdk-js#4036]
Confirm by changing [ ] to [x] below:
- [x] This is a feature with version 2.x of the SDK

**Is your feature request related to a problem? Please describe.**

Please consider including JavaScript / TypeScript examples for AWS SDK for JavaScript v3 (specifically SES in my case). I can't find anything that references @aws-sdk/client-sesv2, uses `Content` instead of `Message`, etc.

**Describe the solution you'd like**

Include examples in (or linked from) the documentation for (at least) SES for the current version of the API / SDK in (at least) JavaScript.

**Describe alternatives you've considered**

n/a - I've looked all over for this, including in aws-doc-sdk-examples. I've had to figure it out based on the typedefs. If I weren't using TypeScript I'd be totally lost.

**Additional context**

All of your examples are for older versions of the API or SDK, or are in other languages such as Rust or Python.

**Comment by ajredniwja** [comment]
Thanks for providing the feedback, we are trying to prioritize the docs for V3.
