### ISSUE TITLE
how can i solve this error when i tried to play the audio stored in S3 bucket.

### ISSUE THREAD

**Issue by tortuc** [aws/aws-sdk-js#4040]
![image](https://user-images.githubusercontent.com/65579678/155908238-824b24d8-ea35-4f96-ba79-743564a4fab3.png)

const s3ObjectUrl = parseUrl(`${window.location.protocol}//${Bucket}.s3.${region}.amazonaws.com/${content.Key}`);
const preSigner = new S3RequestPresigner({
    credentials,
    region,
    sha256: Sha256 // In browsers
});
// Create a GET request from S3 url.
const url = await formatUrl( await preSigner.presign(new HttpRequest(s3ObjectUrl), { expiresIn: S3_config.expiresIn }));

**Comment by ajredniwja** [comment]
https://forums.aws.amazon.com/thread.jspa?messageID=914773

Closing this issue as it is not related to the SDK.
