### ISSUE TITLE
Invalid signature when key is encoded in a presigned url generated for object lambda access point

### ISSUE THREAD

**Issue by DeekshaPandit** [aws/aws-sdk-js#4041]
Confirm by changing [ ] to [x] below:
- [ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ ] This is an issue with version 2.922.0 of the SDK
 
I am generating presigned url for an [Object Lambda Access Points]. 
There are two different object keys on the bucket, One is Singapore and  another one is Singapore West.
When I access for Singapore, Call goes to Object lambda and response is 200.
but for Singapore West, it says <Error><Code>InvalidSignature</Code><Message>Invalid signature.</Message></Error>
  
Below is working
https://<accesspoint-name>-<account-id>.s3-object-lambda.us-east-1.amazonaws.com/Singapore?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=%2Fus-east-1%2Fs3-object-lambda%2Faws4_request&X-Amz-Date=20220228T193947Z&X-Amz-Expires=30&X-Amz-Security-Token=<token>&X-Amz-Signature=<signature>&X-Amz-SignedHeaders=host

the one not working:
https://<accesspoint-name>-<account-id>.s3-object-lambda.us-east-1.amazonaws.com/Singapore%20West?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=%2Fus-east-1%2Fs3-object-lambda%2Faws4_request&X-Amz-Date=20220228T193947Z&X-Amz-Expires=30&X-Amz-Security-Token=<token>&X-Amz-Signature=<signature>&X-Amz-SignedHeaders=host

Please suggest something to debug.

**Comment by ajredniwja** [comment]
HI @DeekshaPandit, can you please fill all the info in [issue template](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=).
