### ISSUE TITLE
AWS_SDK_LOAD_CONFIG being handled as truthy value is confusing as AWS_SDK_LOAD_CONFIG=0 is truthy

### ISSUE THREAD

**Issue by PierreBeucher** [aws/aws-sdk-js#4043]
Confirm by changing [ ] to [x] below:
- [x] This is a feature with version 2.x of the SDK

**Is your feature request related to a problem? Please describe.**

[Documentation](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-configured-credential-process.html) mentions the use of `AWS_SDK_LOAD_CONFIG` being handled as per _truthy_ value:

> if the AWS_SDK_LOAD_CONFIG environment variable is set to a truthy value, the SDK will prefer the process specified in the config file over the process specified in the credentials file (if any).`

However when setting  `AWS_SDK_LOAD_CONFIG=0` in JS app the value is still interpreted as _truthy_ because JS interpret any environment variable as a _string_ and string `"0"` is truthy.

Easy to reproduce:

```
docker run --network host -it node:alpine sh 

$ mkdir foo && cd /foo
$ npm i aws-sdk

$ export AWS_SDK_LOAD_CONFIG=0
$ node
Welcome to Node.js v17.4.0.
Type ".help" for more information.
> require('aws-sdk')
Uncaught Error: ENOENT: no such file or directory, open '/root/.aws/config'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.readFileSync (/foo/node_modules/aws-sdk/lib/util.js:95:26)
    at IniLoader.parseFile (/foo/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:6:47)
    at IniLoader.loadFrom (/foo/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at getRegion (/foo/node_modules/aws-sdk/lib/node_loader.js:116:32)
    at Config.region (/foo/node_modules/aws-sdk/lib/node_loader.js:171:18)
    at Config.set (/foo/node_modules/aws-sdk/lib/config.js:524:39) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/root/.aws/config'
}
```

Setting `AWS_SDK_LOAD_CONFIG=""` or not setting var at all works just fine. 

We lost a few hair on this one. Almost reported this as bug, but behavior _does_ correspond to what is documented.

**Describe the solution you'd like**

Considering that any environment variable is a _string_ in JS, instead of 

   _"if the AWS_SDK_LOAD_CONFIG environment variable is set to a truthy value [...]"_

a much clearer sentence like

  _"If AWS_SDK_LOAD_CONFIG is set to anything other than `""` [...]_ 

which is exactly the same in this context: the only non-_truthy_ value for a string is the empty string `""`

Also, showing a clear error message and/or putting a warning when `AWS_SDK_LOAD_CONFIG` is set with potentially _intended false_ but _in-fine truthy_ values (`"0"`, `"false"` or such) may be helpful

 
**Describe alternatives you've considered**

Not setting `AWS_SDK_LOAD_CONFIG` at all is also possible, but in our case we did not control how this variable was set and naturally expected when seeing it's value `0` that it would not cause it to be considered true. 

**More context**

In our case we were running a NodeJS (Typescript) app in Docker, but I guess this applie to any JS environment.

**Comment by adriencaccia** [comment]
Thanks you so much for the issue @PierreBeucher 🙏 

I was losing a few hairs myself on this until I stumbled on this issue. Setting `AWS_SDK_LOAD_CONFIG=""` solved it for me.

I completely agree with your proposed solution to make the documentation clearer.

**Comment by BenDenney** [comment]
Wow, I've just spent an entire day banging my head against a brick wall with this error, thank you @PierreBeucher 👍 

Running a cucumber test via yarn in an ECS container: the task definition environmental variable setting `AWS_SDK_LOAD_CONFIG=true` or `AWS_SDK_LOAD_CONFIG=false` clearly made this "truthy", but setting it to `AWS_SDK_LOAD_CONFIG=""` in my Jenkinsfile worked.

Definitely needs a document change here please!

**Comment by kellertk** [comment]
Thank you for the feedback! I've provided it to the documentation team for an update.
