### ISSUE TITLE
STS service do not use region's endpoint

### ISSUE THREAD

**Issue by Psycholive** [aws/aws-sdk-js#4050]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x ] This is an issue with version 2.x of the SDK

**Describe the bug**
When using STS client, the region parameter is ignored and sts.amazonaws.com endpoint is always called.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.22.10

**SDK version number**
2.1089.0

**To Reproduce (observed behavior)**
```
const sdk = require('aws-sdk');
const sts  = new sdk.STS({
    region: 'eu-west-3',
});

sts.getCallerIdentity((err,data) => console.log("ok",err,data));
```
The called endpoint is `https://sts.amazonaws.com/`

**Expected behavior**
The called endpoint should be `https://sts.eu-west-3.amazonaws.com`. It is the case for other services like cloudformation or secretsmanager.

**Additional context**
The code is executed in an EC2 linux instance in eu-west-3 region and this VM cannot reach sts.amazonaws.com endpoint so the code hangs.

**Comment by ajredniwja** [comment]
Hi there, there might be something else affecting this as I am able to run it just fine, using the code above. 
I get:
```
ok null {
  ResponseMetadata: { RequestId: '98328' },
  UserId: 'PO',
  Account: '22',
  Arn: 'arn'
}
```
