### ISSUE TITLE
Swagger grouping operations (tags) are ignored

### ISSUE THREAD

**Issue by gmartenscb** [aws/aws-sdk-js#4058]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
We have the `DefinitionBody` in our `AWS::Serverless::Api` with the `openapi: '3.0.0'` definition.
In there we define the paths and use the `x-amazon-apigateway-integration` to call our lambda functions.
The paths use tags to group operations, as defined by the [Swagger Specifications](https://swagger.io/docs/specification/grouping-operations-with-tags/).

When we use the `GetExport` function from the `@aws-sdk/client-api-gateway: "^3.54.0"` these tags are no longer there,
and everything is grouped under the `default` key.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
Node 14

**SDK version number**
_If running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html):_
It's Node 14, so that would then mean `v2.1001.0`.

**To Reproduce (observed behavior)**
<details>
<summary>cloudformation.yaml</summary>

Extract from large cloudformation file

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    CodeUri: .
    Runtime: nodejs14.x
    Timeout: 15
    
Resources:
  GetSwaggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: "dist/src/index.getSwagger"
      FunctionName: !Sub "${AppGroup}-get-swagger"
      Tags:
        Name: !Sub "${AppGroup}-get-swagger"

  PrivateServerlessApi:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: !Ref "Environment"
      DefinitionBody:
        openapi: "3.0.0"
        info:
          title: "Sample API"
          version: "1.0.0"
        paths:
          /:
            get:
              tags: ["OpenApi"]
              responses:
                "200":
                  description: "OK"
                  content:
                    text/html:
                      schema:
                        type: "string"
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: "arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${GetSwaggerFunction.Arn}/invocations"
                credentials:
                  Fn::ImportValue:
                    Fn::Sub: "${AppGroup}-iam-role"
```
</details>

<details>
<summary>Handler</summary>

The following `result` no longer contains the `tags` per `operation`.

```ts
    const options = {
      restApiId: this.restApiId,
      stageName: this.stageName,
      exportType: 'oas30',
    };

    const command = new GetExportCommand(options);
    const result = await this.client.send(command);
```
</details>

**Expected behavior**
That the paths are correctly grouped, as by the Swagger Specification (and Editor).

**Screenshots**
*Swagger Editor*
![image](https://user-images.githubusercontent.com/79847451/159777929-2f45bf5e-edfd-43c3-8f53-773460674b7d.png)

*Exported API*
![image](https://user-images.githubusercontent.com/79847451/159778196-2909963d-11a5-4efa-8d73-b8d3993f7f14.png)

**Comment by ajredniwja** [comment]
Hi there, V2(this repo) is default for Lambda Node.js environment. See [examples](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/lambda-examples.html) here on how to bundle V3 of the SDK correctly.
