### ISSUE TITLE
[Typings][DynamoDB] putItem - .d.ts is missing null for callback parameters

### ISSUE THREAD

**Issue by NicoVIII** [aws/aws-sdk-js#4059]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [X] This is an issue with version 2.x of the SDK

**Describe the bug**
If you use the aws-sdk with TypeScript in strict mode, the parameters of the definitions for DynamoDBs putItem method (and I would guess of many others) is not correct.

The documentation states that error and data parameters of the callback function can be null:

> Parameters:
    err (Error) — the error object returned from the request. Set to null if the request is successful.
    data (Object) — the de-serialized data returned from the request. Set to null if a request error occurs. The data object has the following properties:

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#putItem-property

But the dynamodb.d.ts states:

> putItem(params: DynamoDB.Types.PutItemInput, callback?: (err: AWSError, data: DynamoDB.Types.PutItemOutput) => void)

https://github.com/aws/aws-sdk-js/blob/v2.1099.0/clients/dynamodb.d.ts#L284

Here the null case is missing. This only is a problem with strict mode, without it `| null | undefined` is assumed by TS.

**Is the issue in the browser/Node.js?**
-

**If on Node.js, are you running this on AWS Lambda?**
-

**Details of the browser/Node.js version**
-

**SDK version number**
e.g. v2.1099.0

**To Reproduce (observed behavior)**
-

**Expected behavior**
The .d.ts file states the correct types for parameters to avoid errors / confusion.

**Screenshots**
-

**Additional context**
-

**Comment by AllanZhengYP** [comment]
Hi @NicoVIII, 

Thank you for bringing this to us. I agree this is a miss in the type definition. But I don't think there's a way to add correct type annotation without breaking exiting users that rely on the assumption that the data would exists. I will label it as wont fix, but feel free to comment below.

**Comment by NicoVIII** [comment]
Yeah, I understand why you consider this a breaking change.
But another error like this was resolved without a new major version, so I hoped it would be possible here as well.
https://github.com/aws/aws-sdk-js/issues/3184

But thanks for the feedback, I will close then here and have a look at v3 and reopen there, if this still applies in that version :)
