### ISSUE TITLE
AWS SigV4 signature fails when endpoint passed has redundant port number

### ISSUE THREAD

**Issue by renatorroliveira** [aws/aws-sdk-js#4062]
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [X] This is an issue with version 2.x of the SDK

**Describe the bug**
When you instantiate a service using AWS SDK and provide an endpoint that has redundant port numbers (443 for HTTPS) and use the AWS SigV4 authentication, the signature sent on the `Authorization` header won't match the signature calculated at the service, causing an invalid signature exception to be returned.

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
Chrome 90

**SDK version number**
Tested various versions up to 2.1077.0

**To Reproduce (observed behavior)**
- Instantiate a new Service from the SDK using sigV4 credentials and provide a valid endpoint with redundant port number, for example `https://theservice.us-east-1.amazonaws.com:443/`:
```javascript
const client = new AWS.TheService({
      endpoint: "https://theservice.us-east-1.amazonaws.com:443/",
      credentials: new Credentials({
        accessKeyId: "...",
        secretAccessKey: "...",
        sessionToken: "...",
      }),
      region: "us-east-1",
});
```
- Call any operation in the client and you will get an invalid signature 400 error.
- This is caused because the SDK signs the request headers *including the port number in the Host header*. However the browser will remove the redundant port number from the URL and the Host header when the request is dispatched. That causes the backend service to wrongly calculate the expected signature based on a different value of the Host header.

**Expected behavior**
On browsers, the SDK needs to remove redundant port numbers from the URL and Host header before signing the request so the signature matches the end value of the Host header sent by the browser.

**Additional context**
Logged the request headers upon the "sign" event:
```
Endpoint: "https://theservice.us-east-1.amazonaws.com:443/public/"
{
    "X-Amz-User-Agent": "aws-sdk-js/2.1077.0 promise",
    "Content-Type": "application/x-amz-json-1.1",
    "X-Amz-Target": "TheService.SomeOperation",
    "X-Amz-Content-Sha256": "114a6e8f5c43bea09a4a73b24b44b030440a6f3be212bbe943becdb363f15e29",
    "Content-Length": 17,
    "Host": "theservice.us-east-1.amazonaws.com:443",
    "X-Amz-Date": "20220330T210206Z",
    "x-amz-security-token": "...",
    "Authorization": "AWS4-HMAC-SHA256 Credential=.../20220330/us-east-1/theservice/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-target;x-amz-user-agent, Signature=39ad1ca5d84b9ec011d2c309d94c6862f159f0be7fcf548a80d217f2758685cb"
}
```

The actual headers sent (from the Network tab):
```
Request URL: https://theservice.us-east-1.amazonaws.com/public/
Request Method: POST
Host: theservice.us-east-1.amazonaws.com
Content-Length: 17
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"
DNT: 1
sec-ch-ua-mobile: ?0
Authorization: AWS4-HMAC-SHA256 Credential=.../20220330/us-east-1/theservice/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-target;x-amz-user-agent, Signature=39ad1ca5d84b9ec011d2c309d94c6862f159f0be7fcf548a80d217f2758685cb
Content-Type: application/x-amz-json-1.1
X-Amz-Content-Sha256: 114a6e8f5c43bea09a4a73b24b44b030440a6f3be212bbe943becdb363f15e29
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
x-amz-security-token: ...
X-Amz-Target: TheService.SomeOperation
X-Amz-Date: 20220330T210206Z
X-Amz-User-Agent: aws-sdk-js/2.1077.0 promise
sec-ch-ua-platform: "macOS"
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
```

Note: I've redacted sensitive information.

**Comment by ajredniwja** [comment]
Hey @renatorroliveira thanks for opening this issue and apologies it fell out of queue, I'd need to dive deeper and see what causes that in from the SDK side, I can open a similar PR mentioned above based on the investigation.

**Comment by aBurmeseDev** [comment]
Hi @renatorroliveira - apologies for the delay in response. Before proceeding with further investigation, I wanted to check if this issue is still occurring in your environment. One potential solution I can suggest is to remove the port number from the endpoint URL when instantiating the service. Instead of using the URL with the port number `https://theservice.us-east-1.amazonaws.com:443/`, try instantiating the service with the URL without the port number `https://theservice.us-east-1.amazonaws.com/`. Please let us know if the issue persists after making this change.
