### ISSUE TITLE
Default maxretries values for different AWS services

### ISSUE THREAD

**Issue by sharnage** [aws/aws-sdk-js#4065]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] This is an issue with version 2.x of the SDK

**Describe the question**
Is there any documentation around default maxRetries set for different AWS services. I have read conflicting values across different sources, some say its 3 for all the services and some say it's different for different services. Even on AWS documentation it's been mentioned that it depends on the service. But I need to know what those default values are for different services so that I can configure them accordingly.

**Comment by ajredniwja** [comment]
Hi @sharnage thanks for opening this issue, https://github.com/aws/aws-sdk-js/issues/3611
The above issue should resolve your query. Please let us know if it doesnt. Thanks
