### ISSUE TITLE
Upgrade your uuid dependency package version to >= 7 

### ISSUE THREAD

**Issue by saloni137** [aws/aws-sdk-js#4066]
**Describe the bug**
Upgrade your UUID package version to >= 7 . Current Dependency of UUID package 3.3.2 is deprecated.

**Comment by raejoonee** [comment]
This issue has been raised several times over the past year. Older versions of uuid may cause problems with random numbers. Now, uuid is at version over 8.x and I really hope this can be fixed as soon as possible.

**Comment by passos** [comment]
`warning aws-sdk > uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`

**Comment by ajredniwja** [comment]
Fixed in https://github.com/aws/aws-sdk-js/pull/3924.
Closing this issue now.
