### ISSUE TITLE
No resend verification code API for SMS MFA

### ISSUE THREAD

**Issue by viveksdf** [aws/aws-sdk-js#4068]
I am trying to implement resend OTP functionality in my application but there is no API available to do so. Here I am raising it as an enhacement so that we can be resend the OTP.

**Comment by ajredniwja** [comment]
Hey @viveksdf I believe you are looking for something like this. 
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sns-examples-sending-sms.html

I would close this issue, please reopen the issue using the [issue template](https://github.com/aws/aws-sdk-js/issues/new/choose), if you have any other questions. thanks
