### ISSUE TITLE
amazon s3 Bucket: Inaccessible host: "xxxxxxxxxxx"at port `undefined'. This service may not be available in the `us-west-1' region.

### ISSUE THREAD

**Issue by doverradio** [aws/aws-sdk-js#4079]
I have an issue similar to the one mentioned in [#2618](https://github.com/aws/aws-sdk-js/issues/2618).

I had successfully loaded about 11 images to my amazon S3 bucket (which I created on the same day as the issues began).

Afterward, I tried to upload the 12th image and got the error:
```
Inaccessible host: "xxxxxxxxxxx"at port `undefined'. This service may not be available in the `us-west-1' region.
```
I waited for an hour or so, and then tried making the call again, which worked.

Why this behavior? 

Can I do anything to make sure this call is stable from now?

**Comment by ajredniwja** [comment]
Hey @doverradio apologies for late reply can you please share your code and some of the details about your environment. 
https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug-report.yml&title=%28short+issue+description%29

**Comment by doverradio** [comment]
Hello,

Here is my code:

```
// express.js controller...
exports.imageUrlToAmazonS3Url = async ( req, res ) => 
{
    let { url } = req.body;
    console.log(url);
    AmazonS3.findOne({ Original: url }, function ( error, prior_amazonS3_doc ) {
        if ( error || !prior_amazonS3_doc )
        {
            
            request({ url, encoding: null }, (err, resp, buffer) => {
                // Use buffer
                getAwsUrl()
                .then(response => {
                    // console.log('d: ', d);
                    console.log('Here is the response: ', response)
                    // Setting up S3 upload parameters
                    console.log(`response.key: ${response.key}`);
                    const params = {
                        ContentType: 'jpeg',
                        Bucket: 'myimages',
                        Key: response.key, // File name you want to save as in S3
                        Body: buffer
                    };

                    s3.upload(params, function(err, data) {
                        if(err) {
                            console.log(`err`, err);
                            res.json(err);
                        } else {
                            console.log(`File uploaded successfully. ${data.Location}`);
                            console.log(`data: `, data);
                            data.Original = url
                            let new_amazon_s3_doc = new AmazonS3( data )
                            new_amazon_s3_doc.save()
                            .then( amazon_s3_doc => {
                                let { Location } = amazon_s3_doc
                                res.json( { url: Location } )
                            })
                            .catch( e => log( `new_amazon_s3_doc e: `, e ) )
                        }
                    })
                })
        });
        } else {
            let { Location } = prior_amazonS3_doc
            res.json( { url: Location } )
        }
    })
}

```

**Comment by alexcroox** [comment]
Did you get to the bottom of this? I have a super simple example and I get the same error:

```
const AWS = require('aws-sdk')

const test = async () => {
  const s3 = new AWS.S3({
    accessKeyId: 'xxx',
    secretAccessKey: 'xxx',
    region: 'eu-west-2'
  })

  const params = {
    Bucket: 'pawpaddock-assets',
    Key: 'test.txt',
    Body: 'test'
  }

  console.log(params)

  await s3.putObject

  console.log('saved!')
}

test()

```

```
{ Bucket: 'pawpaddock-assets', Key: 'test.txt', Body: 'test' }
/Users/alex/Projects/paw-paddock/node_modules/aws-sdk/lib/event_listeners.js:547
        this.response.error = AWS.util.error(new Error(message), {
                                             ^

UnknownEndpoint: Inaccessible host: `pawpaddock-assets.s3.eu-west-2.amazonaws.com' at port `undefined'. This service may not be available in the `eu-west-2' region.
```

**Comment by doverradio** [comment]
Never got to the bottom of this.  

It sucks because to convert an array of image urls, it takes hours sometimes.  

The reason is because it will certainly work on the _initial_ call.  Then it **snaps right back into that error**.

**Comment by nakashkumar** [comment]
For me, this was happening when accessing local s3 server. I got around it by enabling `s3ForcePathStyle` in s3 config.

```
const s3 = new AWS.S3({
      endpoint: "http://localhost:9090",
      ...
      s3ForcePathStyle: true
});
```

**Comment by tnwanna** [comment]
@nakashkumar The `s3ForcePathStyle: true` is the key to this working properly and recognizing the port!

**Comment by aal89** [comment]
I had the same problem when my server was on ipv6 and bucket endpoint(s) were ipv4.

If you use dualstack setting something like this, when initialising the SDK you should be good;

```
const s3 = new AWS.S3({
  useDualstackEndpoint: true,
  ...
});
```

I guess you could also just use this setting in `AWS.config.update`.

**Comment by lutzklai** [comment]
I randomly run into this error a few times a week. I have a lambda function which takes a snapshot of a webpage and uploads the snapshot to s3.

I haven't been able to see any patterns for when the error occurs. At times the lambdas could be uploading 300 or so images to the bucket around the same time. Maybe that has something to do with it?

I'm thinking I just need to add some retry logic to the upload. I can see the lambdas where I get the error have successful uploads 2-5 seconds later.

**Comment by akbarjon2000** [comment]
i got the same issue on mediastore

**Comment by dheeraj-deb** [comment]
Please make sure that the "Region" and "Bucket Name" is correct.

**Comment by aBurmeseDev** [comment]
Hi everyone - thanks for chiming in. The error 'This service may not be available' typically occurs when SDK is unable to connect to the specified endpoint or service in the given region due to various factors, such as temporary network or service disruptions, configuration issues, or rate-limiting mechanisms. I noticed that in previous comments, some users have identified the culprit to be related to their specific configurations. As the root cause can vary on a case-by-case basis, we'll need to understand your individual configuration and environment details to troubleshoot effectively.

If you are still experiencing this error, please create a new issue and provide your configuration details and environment information. This will help us better understand and investigate the problem specific to your setup.

**Comment by himanshusain0** [comment]
i got the same error in my imagegram
