### ISSUE TITLE
S3.copyObject cross region.

### ISSUE THREAD

**Issue by allthetime** [aws/aws-sdk-js#408]
I have written a backup script for our S3 buckets using S3.copyObject and I want to use a bucket in a separate region than the source bucket (east vs. west). When I attempt to initialize the copy from east to west I get:

Error: Hostname IP doesn't match certificate's altnames

Is there a way around this?

**Comment by kunagpal** [comment]
@allthetime I'm experiencing a similar issue. Could you share a complete working example?

**Comment by kurt343** [comment]
@kunagpal did you happen to hear back from @allthetime or solve this in the end?

I'm very new to S3 and have not come across many examples for copying/moving across regions.

**Comment by kunagpal** [comment]
@kurt343 Yes, I was able to figure this out as follows:
```js
var sdk = reqiure('aws-sdk'),
    s3 = new AWS.S3(); // the lack of any options is important here. You could use a fixed api version, though.

s3.copyObject({
    Bucket: 'full name of the target bucket', //
    CopySource: 'full name of the source bucket' + '/' + 'full path to the file being copied',
    Key: 'full path to the file being copied'
}, function (err, data) {
    // further handling logic goes here
});
```

The bottom line here is that S3 is pseudo region agnostic, so specifying complete bucket names and file paths is sufficient. If you've worked with ElasticBeanstalk before, you would have also noticed how S3 bucket names for ElasticBeanstalk version bundles include the region name as well.

**Comment by kurt343** [comment]
Thank you very much @kunagpal. That got me across the line and was much easier than I anticipated.
