### ISSUE TITLE
Allow response-cache-control header in S3 headObject

### ISSUE THREAD

**Issue by Digized** [aws/aws-sdk-js#4095]
Confirm by changing [ ] to [x] below:
- [X] This is a feature with version 2.x of the SDK

**Is your feature request related to a problem? Please describe.**
I am using [Last-Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) as an optimistic concurrency mechanism. I am calling the headObject api every ~2s. Although this works as expected on Chrome, Firefox caches this result, and responds with an old time when headObject is invoked again.  

**Describe the solution you'd like**
I would like to be able to specify [Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) as `no-cache` for my request for all the browsers to behave the same. 

The getObject has a [response-cache-control](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax) header that can be provided to achieve this result and I would prefer if that was added to the headObject api as well. https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax

**Describe alternatives you've considered**
The alternative is that I set metadata of each s3 object as `cache-control: no-cache`, which works fine for newly created objects. but unfortunately we already have objects in customer accounts that do not have this metadata set, and we will now require additional permissions i.e CopyObject from the customer.

**Comment by trivikr** [comment]
The [headObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html) request docs from S3 does not document `response-cache-control` header.

**Comment by Digized** [comment]
I wasn't able to repro this since it seems to pass cache-control: max-age=0 in the request headers

https://github.com/Digized/aws-sdk-js-tests

internal ticket V569765586

internal diff ar3iq57k
