### ISSUE TITLE
Node.js aws-sdk opensearch issue with associating packages

### ISSUE THREAD

**Issue by SofyaNadesan** [aws/aws-sdk-js#4099]
I have been working on a node.js project, which uploads a file to the S3 bucket, and imports a package in Opensearch based on the newly uploaded file, which is working fine. However, when I try to associate a domain with the package, using the associatePackage function provided by the aws-sdk, I can see it appearing on the aws Opensearch portal, with a status of 'Associating', but after a about five to ten minues, the status becomes 'Association failed'.  

Please note that when I do this manually through the portal, it does start of saying 'Associating', but then take about 2-3 minutes, before it turns to 'Active'.

Also, I have noticed there is no function that allows us to apply the update to the associated domain.

I was wondering whether this issue is something to do with the aws-sdk itself, and whether there is a workaround to it. 

Thanks

**Comment by KaidiMohammed** [comment]
Hello, 
Are you using the same user aws credentials in CLI and in SDK ? 
and also if the package is already associated, I think it should be dissociated first and then associate it again.

**Comment by ajredniwja** [comment]
@SofyaNadesan thanks for opening this issue, can you please share the code you are using? Or maybe the HTTP request is used? I would also try to disassociating it first too.
