### ISSUE TITLE
DynamoDB updateItem parsing strings as numbers?

### ISSUE THREAD

**Issue by sturadnidge** [aws/aws-sdk-js#410]
Hiya,
I am trying to update an existing item in DynamoDB, however everytime I'm getting an insert of a new item rather than an update to old.
For example, lets say I have object { 'a': {'S': '11111111111111111'}, 'b': {'S': '22222222222222222'}, {'c': {'S': '3333'}, 'd': {'N': '1'} } where 'a' is a hash key and 'b' is a range key. The following will result in a brand new record with a range key of '22222222222222224' rather than updating the existing 'd' key to '2'.

``` javascript
'use strict';

var AWS = require('aws-sdk');
var ddb = new AWS.DynamoDB();

var params = {
  Key: {
    a: {S: '11111111111111111'},
    b: {S: '22222222222222222'}
  },
  AttributeUpdates: {
    d: {
      Action: 'PUT',
      Value: {N: '2'}
    }
  },
  TableName: 'thisdontwork',
  ReturnValues: 'ALL_NEW'
};

ddb.updateItem(params, function(err, data) {
  if (err) { return console.log(err); }
  console.log(data);
});
```

However if I create an item that does _not_ have a 'c' attribute, the update works as expected.

Any ideas? I've been combing the documentation for a while and I can't see that I am doing something wrong. I also tried with the 'newer' UpdateExpression operator, which also fails.

**Comment by shushantarora** [comment]
How does dynamo db stores number internally ?Does dynamodb stores number datatype as string only. Whats the size of number say with value 123456. will it be 6 bytes or 4 bytes - stored as string or int in dynamodb table ?
