### ISSUE TITLE
KinesisVideoArchivedMedia return wrong error when using PRODUCER_TIMESTAMP for end timestamp that is outside of retention period

### ISSUE THREAD

**Issue by elizatlawy** [aws/aws-sdk-js#4102]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [ x] This is an issue with version 2.x of the SDK

**Describe the bug**
Using `PRODUCER_TIMESTAMP` with either `KinesisVideoArchivedMedia` or `GetClip` for end timestamp that is out of the stream retention period returns a wrong error: 

`ResourceNotFoundException No fragments found in the stream for the clip request. (404)
`

although the video existed before it reached the retention period.

When requesting the same stram using `SERVER_TIMESTAMP` return the correct error of: 

` InvalidArgumentException End timestamp XXXXXXXXXXX is outside of the stream retention period. (400)
`

The expected behavior is to get the `InvalidArgumentException` with the correct error description. 

This issue is also reproducible using the Kinesis download media clip UI (which uses the getClip API).

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v14.18.0

**SDK version number**
2.1127.0

**To Reproduce (observed behavior)**
Use `PRODUCER_TIMESTAMP` with either `KinesisVideoArchivedMedia` or `GetClip` for end timestamp that is out of the stream retention period returns a wrong error.

**Expected behavior**

`InvalidArgumentException End timestamp XXXXXXXXXXX is outside of the stream retention period`  is returned for requesting end timestamp that is out of the stream retention period when using `PRODUCER_TIMESTAMP`

**Screenshots**
Wrong behavior:  (Using `PRODUCER_TIMESTAMP` )
![image](https://user-images.githubusercontent.com/17687074/166638257-6714eea8-51ae-477f-a61a-84e201c92ffa.png)

Correct behavior:  (Using `SERVER_TIMESTAMP` )
![image](https://user-images.githubusercontent.com/17687074/166638383-867263f5-745e-4a6c-be8e-f8011add0516.png)

**Comment by ajredniwja** [comment]
Hey @elizatlawy thanks for opening this issue, can you please share the code you are using to consume the SDK?

**Comment by elizatlawy** [comment]
@ajredniwja here is a minimal example: 

```
// fragmentSelectorType is either 'PRODUCER_TIMESTAMP' or 'SERVER_TIMESTAMP'
const getHLSStreamingSessionURL = async (streamARN, dataEndpoint, timeRange, fragmentSelectorType) => {
    try {
        let TimestampRange = null;
        TimestampRange.StartTimestamp = timeRange.startTimestamp;
        TimestampRange.EndTimestamp = timeRange.endTimestamp;

        const fragmentSelector = {
            FragmentSelectorType: fragmentSelectorType,
            TimestampRange
        };
        const kinesisVideoArchivedMedia = new AWS.KinesisVideoArchivedMedia({ region: process.env.AWS_RESOURCES_REGION, endpoint: dataEndpoint });
        const playbackMode = 'ON_DEMAND';
        const params = {
            StreamARN: streamARN,
            PlaybackMode: playbackMode,
            Expires: SESSION_DURATION_SEC,
            HLSFragmentSelector: fragmentSelector,
            DisplayFragmentTimestamp: 'ALWAYS'
        };
        const data = await kinesisVideoArchivedMedia.getHLSStreamingSessionURL(params).promise();
        return data.HLSStreamingSessionURL;
    } catch (err) {
        return Promise.reject(err);
    }
};
```

**Comment by aBurmeseDev** [comment]
Hi there - sorry for the long silence here. Are you still experiencing this reported behavior?

I understand that when using the `PRODUCER_TIMESTAMP` with the `KinesisVideoArchivedMedia` or `GetClip` operations for an end timestamp that is outside the stream's retention period, you're receiving an incorrect error message `ResourceNotFoundException` instead of the expected `InvalidArgumentException`.

Since this appears to be an issue related to the Kinesis Video Streams service itself, rather than the SDK, it would be best to report this directly to the AWS Kinesis Video Streams service team. They are better equipped to investigate and address service-specific issues like this.

Please feel free to contact the service team directly through [AWS Support](https://aws.amazon.com/contact-us/) for further assistance. 

As there are no pending action items for the SDK team, and this repository is dedicated solely to SDK-related issues, I will close this case.
