### ISSUE TITLE
CredentialProviderChain.resolve() may not call its callback on a reentrant call

### ISSUE THREAD

**Issue by vanilla-lake** [aws/aws-sdk-js#4104]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
When the `EC2MetadataCredentials` provider is used, calling `CredentialProviderChain.resolve()` from a callback passed to that same method causes the callback for the second invocation not to be called.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v18.0.0

**SDK version number**
2.1128.0

**To Reproduce (observed behavior)**
```javascript
const AWS = require('aws-sdk');

const credentialProvider = new AWS.CredentialProviderChain();

credentialProvider.resolve(err => {
    if (err) return console.error(err);

    console.log(credentialProvider.resolveCallbacks.length); // -> 1

    credentialProvider.resolve(() => console.log('This is never called'));
});
```

In this code snippet, "This is never called" is not printed.

**Expected behavior**
The callback passed to `CredentialProviderChain.resolve()` should always be called.

In the code snippet above, "This is never called" should be printed to the console.

**Additional context**
It looks like this is due to the `CredentialProviderChain.resolveCallbacks` array being emptied after its callbacks are called:
https://github.com/aws/aws-sdk-js/blob/912af6e4538aca26fcb0354a4a1b4227aea37f31/lib/credentials/credential_provider_chain.js#L110-L113

**Comment by RanVaknin** [comment]
Hi,

I'm able to reproduce your code, however Im pretty sure it is the intended behavior (the same behavior happening even when you are loading credentials from a file, not only via ec2Metadata) 

The question is, what are you trying to do here?

Thanks,
Ran~

**Comment by vanilla-lake** [comment]
Hi @RanVaknin,

This is not something I am trying to do directly. I actually discovered that behaviour while investigating tilelive-s3 (https://github.com/mapbox/tilelive-s3) hanging when trying to write tiles to an S3 bucket from an EC2 instance. tilelive-s3 calls `AWS.config.getCredentials()` here: https://github.com/mapbox/tilelive-s3/blob/774094b16059db27408662a0ee100c1d21bb2f57/lib/index.js#L475

The callback passed to `AWS.config.getCredentials()` is defined here: https://github.com/mapbox/tilelive/blob/6277fe09bfedd51737e767e6a5a499ed3798cacc/lib/stream-put.js#L52

If I recall correctly, the issue happened because that callback calls `s3.getObject`, and that function call never invoked its callback because of the behaviour described above, and thus the command line application appeared to hang: https://github.com/mapbox/tilelive-s3/blob/774094b16059db27408662a0ee100c1d21bb2f57/lib/index.js#L402.

I ended up working around this issue by patching tilelive-s3 so that the following statement: https://github.com/mapbox/tilelive-s3/blob/774094b16059db27408662a0ee100c1d21bb2f57/lib/index.js#L475.
becomes:
```javascript
AWS.config.getCredentials((...args) => queueMicrotask(() => callback(...args)));
```

**Comment by RanVaknin** [comment]
v2 is going into maintenance mode therefore we will not be furthering investigating this. 
Using v3, I see that this issue does not persist:

```js
import { defaultProvider } from '@aws-sdk/credential-provider-node';

async function simulateNestedCredentialCalls() {
    const credentialsProvider = defaultProvider();

    credentialsProvider().then(credentials1 => {
        console.log('First call credentials:', credentials1);

        credentialsProvider().then(credentials2 => {
            console.log('Nested call credentials:', credentials2);
        }).catch(nestedError => {
            console.error('Error during nested credential call:', nestedError);
        });

    }).catch(error => {
        console.error('Error during first credential call:', error);
    });
}

simulateNestedCredentialCalls();
/*
First call credentials: {
  accessKeyId: 'REDACTED',
  secretAccessKey: 'REDACTED',
  sessionToken: undefined,
  credentialScope: undefined
}
Nested call credentials: {
  accessKeyId: 'REDACTED',
  secretAccessKey: 'REDACTED',
  sessionToken: undefined,
  credentialScope: undefined
}
*/
```

Thanks,
Ran~
