### ISSUE TITLE
EndpointId parameter required for EventBridge Global Endpoints is not supported with v2 SDK

### ISSUE THREAD

**Issue by aal80** [aws/aws-sdk-js#4115]
### Describe the bug

According to [v2 JS SDK Docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EventBridge.html#putEvents-property), it is possible to supply the EndpointId parameter required to use EventBridge Global Endpoints 

According to the [AWS SDKs and Tools maintenance policy](https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html) 
```
General Availability (GA) (Phase 1) - During this phase, SDKs are fully supported. AWS will provide regular 
SDK releases that include support for new services, API updates for existing services, as well as bug and 
security fixes. For Tools, AWS will provide regular releases that include new feature updates and bug fixes. 
AWS will support the GA version of an SDK for at least 24 months.
```

However despite the above, it looks like v2 JS SDK does not support specifying the EndpointId parameter, and throwing the following error `InvalidParameter: EndpointId is not supported in current SDK.`

### Expected Behavior

The SDK successfully dispatches event to EventBridge

### Current Behavior

```console
/Users/me/dev/event-bridge-global-endpoint-test/node_modules/aws-sdk/lib/services/eventbridge.js:11
        throw new AWS.util.error(new Error(), {
        ^

InvalidParameter: EndpointId is not supported in current SDK.
You should consider switching to V3(https://github.com/aws/aws-sdk-js-v3).
    at features.constructor.setupRequestListeners (/Users/antonaws/dev/event-bridge-global-endpoint-test/node_modules/aws-sdk/lib/services/eventbridge.js:11:34)
    at features.constructor.addAllRequestListeners (/Users/antonaws/dev/event-bridge-global-endpoint-test/node_modules/aws-sdk/lib/service.js:295:10)
    at features.constructor.makeRequest (/Users/antonaws/dev/event-bridge-global-endpoint-test/node_modules/aws-sdk/lib/service.js:222:10)
    at features.constructor.svc.<computed> [as putEvents] (/Users/antonaws/dev/event-bridge-global-endpoint-test/node_modules/aws-sdk/lib/service.js:704:23)
    at Object.<anonymous> (/Users/antonaws/dev/event-bridge-global-endpoint-test/index.js:20:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'InvalidParameter',
  time: 2022-06-01T02:46:48.550Z
}
```

### Reproduction Steps
```js
const AWS = require( 'aws-sdk'); // 2.1141.0
const eventBridgeClient = new AWS.EventBridge();

const event = {
    EventBusName:'global-endpoint-test-bus',
    Source: 'GlobalEndpointTestSource',
    DetailType: 'GlobalEndpointTestDetailType',
    Detail: JSON.stringify({foo:'bar'})
}

const putEventsParams = {
    Entries: [event],
    EndpointId:'jdaaaaaaaa.veo'
}

eventBridgeClient.putEvents(putEventsParams, function(err, data){
    if (err) console.error(err);
    else console.log(data);
});
```
### Possible Solution

v2 JS SDK supports EndpointId parameter. 

### SDK version used

2.1141.0

### Environment details (OS name and version, etc.)

MacOS, latest, Nodejs 16.13.0

**Comment by ajredniwja** [comment]
@aal80 thanks for opening this issue two of the features which are co related were implemented in V3 of the SDK. 
More information:
Changes made: https://github.com/aws/aws-sdk-js/pull/4067
V3 implementation: 
https://github.com/aws/aws-sdk-js-v3#known-issues
https://github.com/aws/aws-sdk-js-v3/pull/2796

https://github.com/aws/aws-sdk-js-v3/pull/3518

**Comment by vjaykumar-v** [comment]
Do we have any update on this issue, Facing the same issue and blocks to send the events using endpointId

**Comment by RanVaknin** [comment]
Hi there,

When support for EvenBridge and MRAP operation were introduced, the JS SDK v3 did not have first part support for it, instead it had to use [npmjs.com/package/@aws-sdk/signature-v4-crt](https://www.npmjs.com/package/@aws-sdk/signature-v4-crt) in order for it to work. That package is not available for use in v2 and since v2 is now in maintenance mode there is no plan to support it going forward. 

If you want to take advantage of those features, please migrate your application to v3. 

Thanks,
Ran~
