### ISSUE TITLE
ValidationException: The provided key element does not match the schema

### ISSUE THREAD

**Issue by donghoon-song** [aws/aws-sdk-js#4118]
### Describe the bug

![스크린샷 2022-06-03 오후 4 27 57](https://user-images.githubusercontent.com/32301380/171824084-8d8b7190-bdff-44db-b8aa-36d6ef8e1326.png)
![스크린샷 2022-06-03 오후 4 28 07](https://user-images.githubusercontent.com/32301380/171824106-182fd984-f802-4418-9a56-07c26876fa44.png)
![Pasted_image_at_22-06-03-16-35](https://user-images.githubusercontent.com/32301380/171824332-3d68e11a-86fd-4c1b-a463-4a7e08a01d96.png)

My table have the partition key "name". and I think there is no problem in my request format but the error occurs.

### Expected Behavior

API should return the document without the error.

### Current Behavior

![Pasted_image_at_22-06-03-16-35](https://user-images.githubusercontent.com/32301380/171824332-3d68e11a-86fd-4c1b-a463-4a7e08a01d96.png)

### Reproduction Steps

Create a dynamodb table with string partition key and call get item api.

### SDK version used

2.1148.0

### Environment details (OS name and version, etc.)

macos

**Comment by ajredniwja** [comment]
Hey @donghoon-song thanks for opening this issue, can you please share your minimal reproducible code? Possibly text version. I am able to use the API fine using the example found [here](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/dynamodb-example-table-read-write.html).

**Comment by donghoon-song** [comment]
@ajredniwja Thank you. Let me provide reproducible code in a few days.

**Comment by donghoon-song** [comment]
@ajredniwja I'm so sorry for late reply. But I found that the partition key of the table is "name" and the range key of the table is the "createdAt" so that I need to provide both keys to get item.
