### ISSUE TITLE
uuid pinned dependency has import issues

### ISSUE THREAD

**Issue by bencooper222** [aws/aws-sdk-js#4120]
### Describe the bug

aws-sdk no longer works with certain bundlers.

Trying to bundle aws-sdk using Serverless framework for an AWS lambda is failing with an error.

This was an issue with uuid that was resolved in 8.1.0 (see below link) but the latest version of aws-sdk is pinned to version 8.0.0. https://github.com/uuidjs/uuid/issues/444#issuecomment-631663778

Please upgrade uuid to resolve this

### Expected Behavior

Not to see the an error when bundling aws-sdk

### Current Behavior

I saw the below error

```
  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/benc/code/convoyinc/repo-checks-service/node_modules/aws-sdk/node_modules/uuid/package.json
```

### Reproduction Steps

This is a downstream library problem, AWS should just pull in the downstream library. 

### Possible Solution

Pull in this fix https://github.com/uuidjs/uuid/issues/444#issuecomment-631663778

### SDK version used

2.1149.0

### Environment details (OS name and version, etc.)

MacOS Monterrey

**Comment by ajredniwja** [comment]
Hi @bencooper222, the 8.0.0 version was used in https://github.com/aws/aws-sdk-js/pull/3924, we had problems with later version as mentioned there.

**Comment by bencooper222** [comment]
Gotcha, sounds like the ball is in uuid's court then

**Comment by MarkFarmiloe** [comment]
uuid has released v9. Is it worth revisiting this?

**Comment by RanVaknin** [comment]
Hi there,

Since the v2 SDK is being put into maintenance mode, I'm going to go ahead and close this.

Please consider upgrading to v3 as it uses uuid v9.

Thanks,
Ran~
