### ISSUE TITLE
SES sendRawEmail - InvalidParameterValue: Empty header names are illegal.

### ISSUE THREAD

**Issue by ilrein** [aws/aws-sdk-js#4121]
### Describe the issue

I'm currently getting an error msg when using SendRawEmailCommand: `InvalidParameterValue: Empty header names are illegal.`

I wish it would tell me which header is illegal, so I could fix it. Alas, I am stuck and could use some help.

My command object looks like this:

```
SendRawEmailCommand2 {
  middlewareStack: {
    add: [Function: add],
    addRelativeTo: [Function: addRelativeTo],
    clone: [Function: clone],
    use: [Function: use],
    remove: [Function: remove],
    removeByTag: [Function: removeByTag],
    concat: [Function: concat],
    applyToStack: [Function: cloneTo],
    resolve: [Function: resolve]
  },
  input: {
    Destinations: [ 'ilia.reingold@gmail.com' ],
    Source: 'hello@condobeaver.com',
    RawMessage: {
      Data: 'Content-Type: text/plain;charset=utf-8\r\n' +
        'From: Admin <hello@condobeaver.com>\r\n' +
        'To: ilia.reingold@gmail.com\r\n' +
        'Subject: Customer service contact info\r\n' +
        '\r\n' +
        'hello world'
    }
  }
}
```

Any idea why it would fail?

### Links

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/ses-examples-sending-email.html

Should include an example for `sendRawEmail`

**Comment by ajredniwja** [comment]
Hey @ilrein thanks for opening this issue can you please share your use case and complete code for me to  better help understand the issue. 
For information on code example using V2 you can see: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendRawEmail-property
