### ISSUE TITLE
Customer seeing expiredtoken error even if the credentials have been rotated. Customer indicates that they are only seeing this error when using the createPresignedPost function. Customer wants to know why there is this behavior on the method

### ISSUE THREAD

**Issue by lzzuma** [aws/aws-sdk-js#4131]
### Describe the bug

<img width="979" alt="Screen+Shot+2022-06-09+at+5 15 54+PM" src="https://user-images.githubusercontent.com/107913033/174759533-7c9b48de-38e5-4f87-97cb-ac9ff07c0467.png">

### Expected Behavior

The createPresignedPost function to work as expected. As soon as the credentials are rotated, the method should continue as normal.

### Current Behavior

ExpiredToken error. As soon as credentials are rotated, the method returns the error.

### Reproduction Steps

No code provided by the customer. 

### SDK version used

AWS-SDK for Js Version2

### Environment details (OS name and version, etc.)

AWS-SDK for Js Version2,

**Comment by ajredniwja** [comment]
Hey @lzzuma thanks for opening this issue, however can you please share SDK version and reproduction steps as well?
