### ISSUE TITLE
S3: ManagedUpload.abort() yields "reqRegionForNetworkingError"(short issue description)

### ISSUE THREAD

**Issue by ZengTianShengZ** [aws/aws-sdk-js#4134]
### Describe the bug

I found a similar question and this problem （[Upload.abort() yields "reqRegionForNetworkingError"](https://github.com/aws/aws-sdk-js/issues/1592)） has been solved. But in the `ManagedUpload.abort()` scenario, this problem has not been solved.

when i execute 

```js
const upload = managedUpload(options)
```
and
```js
upload.abort()
```
the Request aborted
```
RequestAbortedError: Request aborted by user
    at ManagedUpload.abort (managed_upload.js:256:35)
    at index.ts:343:36 'log' 'RequestAbortedError'
``` 
But still initiate max-keys check request
![image](https://user-images.githubusercontent.com/15622519/175197439-79052cdd-cfb8-4b4f-b924-29f56d5f58d4.png)

### Expected Behavior

Maybe calling the `ManagedUpload.abort() ` method should not raise a NetworkingError in the first place.

### Current Behavior

ManagedUpload.abort() yields "reqRegionForNetworkingError"

### Reproduction Steps

```js
var upload = new AWS.S3.ManagedUpload(options);


window.setTimeout(function() {
    upload.abort();
}), 1000);
```

### SDK version used

"aws-sdk": "2.828.0"

### Environment details (OS name and version, etc.)

mac m1 , chrome version 102.0.5005.115 (arm64)

**Comment by aBurmeseDev** [comment]
Hi @ZengTianShengZ - thanks for reaching out and apologies for not getting back sooner as this fell off our team radar. 

I'm not sure if you're still having issue but just wanted to check in and provide some guidance. I attempted to reproduce this a few times and found out this's only reproducible when file size is smaller than 5MB. When the file is smaller than 5MB, the managed uploader does a single putObject request behind the scenes. There isn't a way to abort that from our end once it's been sent. Anything larger than 5 MB will be uploaded as a multi-part upload. Any uploadPart requests that have already been sent won't abort, but any future requests should never get sent, in theory.

That's what ManagedUpload differs from the Upload, refer to this [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html).

>partSize (Number) — default: 5mb — the size in bytes for each individual part to be uploaded. Adjust the part size to ensure the number of parts does not exceed [maxTotalParts](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#maxTotalParts-property). See [minPartSize](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#minPartSize-property) for the minimum allowed part size.

Hope that helps and again sorry for the long wait.
Best,
John
