### ISSUE TITLE
How to achieve "bucket.presigned_post" in ruby sdk with node/js sdk?

### ISSUE THREAD

**Issue by luccasmaso** [aws/aws-sdk-js#414]
In ruby sdk I can return a map of fields to perform a directly s3 upload POST:

```
  def fields
    s3 = AWS::S3.new
    bucket = s3.buckets[S3_CONFIG["bucket"]]
    form = bucket.presigned_post(options)
    form.fields
  end

  def options
    {
      key: key,
      acl: 'public-read',
      content_length: min_file_size..max_file_size,
      content_type: @content_type,
      success_action_status: 201
    }
  end
```

However, in the nodejs sdk there is no such method for POST, instead only a `getSignedUrl` for a PUT request, retuning a signed url (that misses the policy field):

```
bucket.getSignedUrl("putObject"...`
```

How do I get this same method of ruby sdk in js?

**Comment by vitorbaptista** [comment]
Are there plans on adding this functionality? I'm trying to generate a policy to limit the uploaded file size and accept any `Content-Type` with direct uploads, and it seems I can't do that simply with `getSignedUrl()`.
