### ISSUE TITLE
List contacts does not respect FilteredStatus

### ISSUE THREAD

**Issue by cbelsole** [aws/aws-sdk-js#4143]
### Describe the bug

I have a contacts list with a single OPT_OUT email. Testing with the AWS CLI the OPT_IN filter status does not return this email. When I am using the JS client the same parameters returns the email.

### Expected Behavior

For the list contacts route.

```
  {
    ContactListName: "<contact list name>",
    Filter: {
      FilteredStatus: "OPT_IN",
      TopicFilter: {
        TopicName: "<topic name>",
        UseDefaultIfPreferenceUnavailable: true,
      },
    },
  }
```
Should filter out all `OPT_OUT` contacts.

### Current Behavior

No `OPT_OUT` contacts are filtered.

### Reproduction Steps

1. Create a contact list and topic.
2. Add an `OPT_OUT` contact to the topic.
3. Use the JS client to get the `OPT_IN` contacts.
4. See the `OPT_OUT` contacts are returned.

### SDK version used

"aws-sdk": "^2.1167.0",

### Environment details (OS name and version, etc.)

macOS Big Sur v11.6, node v16.13.1

**Comment by RanVaknin** [comment]
Hi @cbelsole ,

Can you please provide a little more code for your repro? Imports, Client config etc. 

Additionally, you say that the CLI code is working as expected but the SDK code isnt. Are you sure you are running the same command? Can you please add the `--debug` flag at the end of your CLI command, and share the results here (make sure you redact any sensitive info like Account ID and Secret) 

Thanks,
Ran~
