### ISSUE TITLE
querystring package is deprecated.  Use URLSearchParams instead.

### ISSUE THREAD

**Issue by filipjakubowski** [aws/aws-sdk-js#4150]
### Describe the bug

Library depends on "querystring" that is being deprecated.

https://www.npmjs.com/package/querystring

### Expected Behavior

"new code should use the URLSearchParams API instead"

### Current Behavior

npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

### Reproduction Steps

`npm install`

### SDK version used

2.1171.0

### Environment details (OS name and version, etc.)

OS

**Comment by ajredniwja** [comment]
@filipjakubowski thanks for opening this issue, I'll discuss this with team and probably open a PR for it.

**Comment by EvHaus** [comment]
`awk-sdk` also has `url@0.10.3` as dependency, which also relies on the deprecated `querystring` package. Would be great to find a way to remove both of those dependencies.

**Comment by jimmywarting** [comment]
👍 

should just use `globalThis.URL` and `globalThis.URLSearchParams` instead.

**Comment by weepy** [comment]
come on guys - this should be fixed !

**Comment by rohanrajpal** [comment]
+1, happy to make a PR if someone isn't working on this. It's hacktoberfest :)

**Comment by ajredniwja** [comment]
Apologies I wasnt able to pick it up, feel free to open a PR for us to review thanks.

**Comment by samuelfullerthomas** [comment]
I've added a PR to remove the dep on querystring

**Comment by samirbrkovic** [comment]
Hey Guys. What is the status of this PR. When it is going to be merged?

**Comment by charlesivie** [comment]
Any news on this one?

**Comment by RanVaknin** [comment]
Hello everyone, 

Thanks for your patience. From looking at querystring, there are no CVEs associated with it this older version. These are warnings and not errors.  We are not inclined to patch this unless there's an inherent security risk. 

JS SDK v2 is about to enter maintenance mode. The solution here is to upgrade to JS SDK v3.

Thanks,
Ran~

**Comment by mehrdad-shokri** [comment]
2 years later, and still this is not resolved.

**Comment by GoldenBilly** [comment]
yeah...

**Comment by FtxDante** [comment]
Im here to say, why this is'nt fixed yet?

**Comment by brunoleonpuca** [comment]
Im also here to say not fixed yet. Its funny but funny of sad

**Comment by mehrdad-shokri** [comment]
Ok an update here, If you use JS [sdk v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/) you will get rid of this error. The upgrade is pretty much straightforward. instead of shipping all aws products under 1 package, each service is being separated into it's own package. decide what you wanna use and imports are almost the same. for example to use dynamodb use ``npm install @aws-sdk/client-dynamodb``
