### ISSUE TITLE
Overlapping definition of string literals

### ISSUE THREAD

**Issue by soulman-is-good** [aws/aws-sdk-js#4155]
### Describe the bug

Generating typescript from enum shape creates overlapping string literal definitions which renders them useless. No type autocomplete, no type checking works.

https://github.com/aws/aws-sdk-js/blob/49d4c27f224b7f84665e413de6069171323408bf/scripts/lib/ts-generator.js#L342-L345

### Expected Behavior

Script generates proper string literals from enum shape:

```
@enum([
    {name: "Pending", value: "Pending"},
    {name: "Failed", value: "Failed"},
    {name: "Success", value: "Success"},
])
string Status
```
should generate
```ts
export type Status = "Pending"|"Failed"|"Success";
```

### Current Behavior

Following structure in smithy:
```
@enum([
    {name: "Pending", value: "Pending"},
    {name: "Failed", value: "Failed"},
    {name: "Success", value: "Success"},
])
string Status
```
currently generates following definition file:
```ts
export type Status = "Pending"|"Failed"|"Success"|string;
```

### Reproduction Steps

1. have aws-sdk lib installed in the project
2. run node v8 or grater in interactive mode from within the project dir. (just `node`)
3. paste the following code:
```
const TSGenerator = require("aws-sdk/scripts/lib/ts-generator");

console.log(new TSGenerator({}).generateTypingsFromShape({}, "Status", {
    "type": "string",
    "enum": [
        "Pending",
        "Failed",
        "Success"
    ]
}));
```
See the output:
```
export type Status  = "Pending"|"Failed"|"Success"|string;
```

### Possible Solution

Remove `|string;` postfix if this is enum, though this is a breaking change and I'm not sure if v3 healed that.

### SDK version used

2.1174.0

### Environment details (OS name and version, etc.)

MacOS 11.6.6, Amazon Linux 2

**Comment by paul-vd** [comment]
Fixed by https://github.com/aws/aws-sdk-js/pull/4482
