### ISSUE TITLE
Auth Token refresh does not return updated refresh token

### ISSUE THREAD

**Issue by anz000** [aws/aws-sdk-js#4156]
### Describe the bug

The refresh token that is generated initially works to generate new access tokens while the refresh token has not expired. But the refresh process does not give back an updated refresh token. As a result, the user are forced to re-login after refresh token expires.

### Expected Behavior

When the access tokens are refreshed using a valid refresh token, it would return a new refresh token (with the updated expiration time). Ideally, it would be nice to invalidate the old refresh token once a new one is issued, but that is not big of a concern.

### Current Behavior

The access tokens can be refreshed, but no new refresh tokens are issued. The end-user have to go through the login workflow again to be able to get access and refresh token.

### Reproduction Steps

const refreshParams: InitiateAuthRequest = {
			ClientId: cognitoClientId,
			AuthFlow: "REFRESH_TOKEN_AUTH",
			AuthParameters: {
				REFRESH_TOKEN: refreshToken
			}
		};

const CISP = new CognitoIdentityServiceProvider();
const refresh = await CISP.initiateAuth(refreshParams).promise();

console.log(refresh.AuthenticationResult); // no refresh token here

### Possible Solution

Return a new refresh token with an updated expiration whenever the refresh process was successful. Invalidate the old one. This would not force an end-user to re-login again after the time period that the initial refresh token was issued for.

### SDK version used

2.547.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04 | Node v14.18.1

**Comment by ajredniwja** [comment]
Hey @anz000 thanks for opening this issue, do you see the same issue with latest version of the SDK?

**Comment by TomBell-Trove** [comment]
Hi can this be re-opened please - or directed to the right place - it appears to be an issue with the cognito API itself, not just this SDK.  According to the docs `InitiateAuth` should return a new refresh token but it is missing from the payload.

https://stackoverflow.com/questions/55069851/how-to-get-refresh-token-auth-request-to-return-refreshtoken

**Comment by mwenko** [comment]
> Hi can this be re-opened please - or directed to the right place - it appears to be an issue with the cognito API itself, not just this SDK. According to the docs `InitiateAuth` should return a new refresh token but it is missing from the payload.
> 
> https://stackoverflow.com/questions/55069851/how-to-get-refresh-token-auth-request-to-return-refreshtoken

I'm running into the same issue using `amplify-js`. I'm interested in solutions to this as welll.

**Comment by mikerjacobi** [comment]
I was able to work around this by retaining the original RefreshToken.

```
refreshedToken = handleRefresh(staleToken)
refreshedToken.RefreshToken = staleToken.RefreshToken
```
