### ISSUE TITLE
AWS JavaScript SDK v2 proxy options do not seem to work

### ISSUE THREAD

**Issue by blspeiser** [aws/aws-sdk-js#4159]
### Describe the bug

According this [AWS JavaScript SDK v2 documentation](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html), the AWS SDK should use a proxy when configured using the following code example:

`var proxy = require('proxy-agent');
AWS.config.update({
  httpOptions: { agent: proxy('http://internal.proxy.com') }
});`

The documentation implies that the httpOptions parameter should cover both HTTP and HTTPS proxies. This seems to be the case, as the [official SDK reference guide for AWS.config](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#httpOptions-property) is the only field for providing a proxy; there is no additional httpsOptions parameter or anything like that. 

However, this does not seem to work - according to what we see in our tcpdump output, the SDK does not seem to use the proxy. We are using the same proxy-agent library listed in the example code. 

**When we spoke with AWS representatives, they indicated that this was a possible defect in the AWS JavaScript SDK v2 and that we should submit a ticket.**

### Expected Behavior

We expect that, once configured as per the documentation, all requests by the AWS SDK v2 will route through the proxy.

### Current Behavior

We can see that there are TLS connections terminated because they aren't going through the proxy:

`Error with fetch Data Source Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1570:19)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'NetworkingError',
  path: null,
  host: '[monitoring.us-east-1.amazonaws.com](http://monitoring.us-east-1.amazonaws.com/)',
  port: 443,
  localAddress: undefined,
  region: 'us-east-1',
  hostname: '[monitoring.us-east-1.amazonaws.com](http://monitoring.us-east-1.amazonaws.com/)',
  retryable: true,
  time: 2022-07-13T18:28:05.128Z
}`

### Reproduction Steps

In an environment with a proxy, configure the SDK to use that proxy and then perform any SDK operation that requires data from AWS. 

### Additional Information/Context

We also attempted to set environment variables HTTPS_PROXY and HTTP_PROXY in our Linux environment, but that did not seem to help. 

### SDK version used

"aws-sdk": "2.868.0"

### Environment details (OS name and version, etc.)

nodejs:14-alpine container running on AWS Linux for EC2

**Comment by blspeiser** [comment]
Seems to be a previous ticket that indicates this has been an issue: https://github.com/aws/aws-sdk-js/issues/2531

**Comment by ajredniwja** [comment]
Hey @blspeiser thanks for opening this issue. Do you see the error with the latest version? Can you also share the code that you are using?
