### ISSUE TITLE
New docs rendering errors

### ISSUE THREAD

**Issue by jlarmstrongiv** [aws/aws-sdk-js#4162]
### Describe the issue

The new docs don’t render the content properly

<img width="839" alt="image" src="https://user-images.githubusercontent.com/20903247/180827081-378d6223-4a58-4be4-aa9c-2515c5e8ef0c.png">

<img width="882" alt="image" src="https://user-images.githubusercontent.com/20903247/180826886-57b1b61f-765b-499d-bc02-bf6d2830e151.png">

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/s3.html

**Comment by ajredniwja** [comment]
Hey @jlarmstrongiv thanks for opening this issue, this seems to be a duplicate of https://github.com/aws/aws-sdk-js-v3/issues/3665.

**Comment by jlarmstrongiv** [comment]
Whoops!  Thanks @ajredniwja
