### ISSUE TITLE
New docs search bar disappears on scroll

### ISSUE THREAD

**Issue by jlarmstrongiv** [aws/aws-sdk-js#4163]
### Describe the issue

If I scroll in the new docs, the header disappears.  When I focus the search with `/`, the search bar is still hidden

<img width="845" alt="image" src="https://user-images.githubusercontent.com/20903247/180828138-58c8350a-4122-4eb1-b06b-2e9dff350bb9.png">

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/s3.html

**Comment by ajredniwja** [comment]
Hey @jlarmstrongiv thanks for opening this issue, I do still see the search bar after a search. Would you be able to explain more? I will transfer this issue to V3 repo after some more information.

**Comment by jlarmstrongiv** [comment]
@ajredniwja Sure!  This bug appears after you’ve scrolled down the page and the header has disappeared.

Then, by using the keyboard shortcut to search `/`, focus the search bar and start typing.  

Unfortunately, the search bar remains hidden.
