### ISSUE TITLE
[RDSDataService] typeHint parameter is not recognized

### ISSUE THREAD

**Issue by sentientmachin3** [aws/aws-sdk-js#4164]
### Describe the bug

I'm currently working with the RDSDataService, and I'm trying to run the `batchExecuteStatement` method. 
The statement is `INSERT INTO alarms_log VALUES(:id, :meta);`.

The args I pass to the statement are the following:

```
[ 
  [
    { name: 'id', value: { stringValue: 'uuidString' }, typeHint: 'UUID' },
    { name: 'meta', value: { stringValue: '{}' }, typeHint: 'JSON' }
  ] 
] 
```

### Expected Behavior

I suppose the query should run with no issues.

### Current Behavior

The `batchExecuteStatement` method is throwing the exception `UnexpectedParameter: Unexpected key 'typeHint' found in params.parameterSets[0][0].`

### Reproduction Steps

- setup a simple `INSERT` statement with at least a `timestamp` field (verified also using `uuid` and `json` type hints).
- invoke the `batchExecuteStatement` method passing the list of parameters as in the bug description at the top.

### Possible Solution

I have no idea, and nobody bothered to answer me in the discussions.

### Additional Information/Context

The documentation page I used: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#batchExecuteStatement-property

### SDK version used

2.1145

### Environment details (OS name and version, etc.)

ArchLinux - kernel 5.18.14

**Comment by ajredniwja** [comment]
Hey @sentientmachin3 thanks for opening you issue. Can you share the complete code you are using?
