### ISSUE TITLE
'XMLParserError: Unexpected close tag' when using AbortMultipartUpload

### ISSUE THREAD

**Issue by wtcodeai** [aws/aws-sdk-js#4168]
### Describe the bug

1. Start multipart upload by using createMultipartUpload method with needed params
2. Try to abort multipart upload by using abortMultipartUpload method with params returned by previous method

### Expected Behavior

1. Multipart upload started, createMultipartUpload method returns Key, Bucket and UploadId, method successfully returns upload params
2. Multipart upload successfully aborted by using abortMultipartUpload method called with params returned in 1

### Current Behavior

1. Multipart upload started, createMultipartUpload method returns Key, Bucket and UploadId
2. abortMultipartUpload method called, but returned an error: 
`XMLParserError: Unexpected close tag\nLine: 5\nColumn: 7\nChar: >`

### Reproduction Steps

For upload start
```
  try {
      const fileName = req.query.n
      const connS3 = {
        accessKeyId: 'key',
        secretAccessKey: 'key',
        endpoint: new AWS.Endpoint('enpoint'),
        region: 'region',
        sslEnabled: true,
        s3BucketEndpoint: true
      };
      const bucket = 'bucket'
      const file_name = 'provided file name'
      const s3 = new AWS.S3(connS3)
      const awsParams = {
        Key: bucket + '/' + file_name,
        Bucket: bucket
      }
      const response = await s3.createMultipartUpload(awsParams).promise()
 } catch (e) {

}
```
For upload abort
```
const connS3 = {
    accessKeyId: 'key',
    secretAccessKey: 'key',
    endpoint: new AWS.Endpoint('enpoint'),
    region: 'region',
    sslEnabled: true,
    s3BucketEndpoint: true
};
// these params provided from createMultipartUpload response
const awsParams = {
  Bucket: data.Bucket,
  Key: data.Key,
  UploadId: data.UploadId
}
const s3 = new AWS.S3(connS3)

try {
  const response = await s3.abortMultipartUpload(awsParams).promise()
} catch(e) {

}  
```

### SDK version used

2.889.0

### Environment details (OS name and version, etc.)

macOS Monterey 12.1, NodeJS v 18.0.0, express v 4.17.1

**Comment by ajredniwja** [comment]
Hey @wtcodeai fo you see similar error with the latest version as well?

**Comment by mrowles** [comment]
Was this ever resolved? I'm getting it using Cloudfront as an endpoint with origin identity access setup.
