### ISSUE TITLE
Options to verify both phone_number and email while Cognito signup.

### ISSUE THREAD

**Issue by Ganesha2552** [aws/aws-sdk-js#4174]
### Describe the feature

Cognito provides verification like this verify your phone, email and phone or email. But when we choose email for verification and use phone for authentication (MFA). Since the phonenumber is not verified it doesnt allows user to login without verifying. Users have to implement their own custom verification for the phone_number.
So I request Cognito to provide options to verify both phone and email.

### Use Case

Most the users using Cognito wants to verify both email and phone_number. Currently there are no options to accommodate both.

### Proposed Solution

It would be better if there is an option called verifyMobile and verifyEmail methods which can generate verification codes.

### Acknowledgements

- [x] I may be able to implement this feature request

### SDK version used

v2,v3

### Environment details (OS name and version, etc.)

ALL

**Comment by ajredniwja** [comment]
Hey @Ganesha2552 thanks for opening this issue, I can reach out to the team for discussion. If you would like to take this up, I'd be happy to take a PR as well.
