### ISSUE TITLE
S3 Bucket - getBucketVersioning returns circular response if versioning status is not set

### ISSUE THREAD

**Issue by soccermax** [aws/aws-sdk-js#4175]
### Describe the bug

Executing `getBucketVersioning` will lead to a circular response if neither versioning nor MFA is set for the bucket.
Code example:
```js
const params = {
  Bucket: _getBucket(),
}
const result = await s3.getBucketVersioning(params).promise();
```

result will be:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/18613510/183360517-54d4feae-79c4-4ef5-a869-edeb345840c4.png">

--> circular: result["$response"].data === result

This is probably caused because neither versioning nor MFA settings are returned in the original response.

```js
const originalResponse = Buffer.from(result["$response"].httpResponse.body).toString();
```

originalResponse is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>
```

If the settings versioning and mfa are set via api then `getBucketVersioning` works as expected.

### Expected Behavior

- no circular response
- default versioning and/or MFA to false if not present in the response

### Current Behavior

see describe bug

### Reproduction Steps

see describe bug

### Possible Solution

see expected behavior

### SDK version used

2.1186.0

### Environment details (OS name and version, etc.)

Mac M1 with node v16.16.0

**Comment by ajredniwja** [comment]
Hey @soccermax thanks for opening this issue and apologies it felt out of queue, 
Running the code something like this: 

```js
var aws = require('aws-sdk');
var params = {
    Bucket: "gi"
};

var s3 = new aws.S3({ region: 'us-west-2' })
s3.getBucketVersioning(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else console.log(data); // successful response
});
```

I get an empty response `{}`.
Note: `getBucketVersioning` doesnt return `disabled` if the versioning is not enabled.

Possible values returned for versioning state of the bucket  `Enabled | Suspended`.

**Comment by aBurmeseDev** [comment]
Hi there - checking in here. I understand it's been awhile since this was created and apologies for the delay. Before further investigation, is it still valid in recent SDK version?

**Comment by soccermax** [comment]
As we are using managed S3 buckets, we no longer have permission to request the version settings. So I can't reproduce this anymore. Feel free to close the issue if you can't reproduce the issue.
