### ISSUE TITLE
SIGTERM error when calling adminCreateUser

### ISSUE THREAD

**Issue by naresh-yml** [aws/aws-sdk-js#4178]
### Describe the bug

Facing SIGTERM error when trying to create user in cognito using CognitoIdentityServiceProvider.adminCreateUser function. This is happening randomly. Unable to log anything from this exception. This didn't work either of the below implementation.

```
  cognitoIdentityProvider.adminCreateUser(cognitoParams, (error, data) => {
      if (error) {
          console.log('error in promise ', error);
          return reject(error);
      }
      return resolve(data);
  });
```

```
try {
    let response = await cognito.adminCreateUser(cognitoParams).promise();
    console.log(JSON.stringify(response, null, 2));
} catch((error)=>{
    console.log(error
})
```

We are seeing this in Ubuntu only, In Mac OS its working without any issue.

### Expected Behavior

Create user in Cognito

### Current Behavior

SIGTERM error randomly

### Reproduction Steps

This is happening randomly. Sample params object we are using
```
{
  UserPoolId: "poolID",
  Username: "test@gmail.com",
  TemporaryPassword: "Password@1",
  UserAttributes:
    [
      { Name: "email", Value: "test@gmail.com" },
      { Name: "given_name", Value: "GivenName" },
      { Name: "family_name", Value: "FamilyName" },
      { Name: "email_verified", Value: "true" },
    ],
}
```

### SDK version used

2.1108.0

### Environment details (OS name and version, etc.)

Node(v14.17.3), Ubuntu

**Comment by ajredniwja** [comment]
Hey @naresh-yml thanks for opening this issue, the SIGTERM error seems to not come from the SDK but client side. Also if you could share the stack trace that can help narrow the problem.

**Comment by naresh-yml** [comment]
Unfortunately I am unable to capture any stack trace for this error. This SIGTERM error is throwing after I made the above call only. And I can see all the logs just before calling this API.

**Comment by naresh-yml** [comment]
This issue was fixed by increasing request timeout. if we use 6 sec default gateway timeout we are facing this issue. now we have increased to 15sec.
