### ISSUE TITLE
bug: Importing key in Ubuntu 22.04 using ImportKeyPairCommand puts the Key in same line

### ISSUE THREAD

**Issue by anishghimire862** [aws/aws-sdk-js#4182]
### Describe the bug

While importing key using `ImportKeyPairCommand` in Ubuntu 22.04 the imported key is placed on the same line as `no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"ubuntu\" rather than the user \"root\".';echo;sleep 10;exit 142"`. This makes my key invalid and I can't connect to the instance from my device. 

![CleanShot 2022-08-16 at 11 50 03@2x](https://user-images.githubusercontent.com/24493516/184809274-a15999e8-38d1-4687-a236-7c01a4f11541.png)

### Expected Behavior

The imported key should start in the new line.

### Current Behavior

The imported key is in the same line.

### Reproduction Steps

Import key using:

```
new ImportKeyPairCommand({
      KeyName: keyName,
      PublicKeyMaterial: fromString(publicKey, 'binary'),
})
```

### SDK version used

"@aws-sdk/client-ec2": "^3.16.0"

### Environment details (OS name and version, etc.)

macOS Monterey version 12.5

**Comment by ajredniwja** [comment]
@anishghimire862 thanks for opening this issue, I see you are using V3 of the SDK can you please share your code to reproduce the issue?

**Comment by anishghimire862** [comment]
Hello @ajredniwja,

Sorry for keeping this issue open. 

SSH Key being on the same line wasn't causing the problem instead I had a program that tried SSHing into the server using `root` user which was causing all the problems.

Closing the issue now.
