### ISSUE TITLE
No way to pass httpOptions into `new SsoCredentials()`

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-sdk-js#4195]
### Describe the bug

Originally reported in https://github.com/aws/aws-cdk/issues/21328

`SsoCredentials` uses an SSO client it creates internally, but there is no way to pass in `httpOptions` for that SDK client. The result of this is that SSO credentials cannot be made to work in environments where traffic needs to go through a proxy, or requires a special cert bundle, because there's no way to configure the client correctly.

### Expected Behavior

`SsoCredentials` needs to take and use `HttpOptions` just like `SharedIniFileCredentials` does for the STS client it creates:

https://github.com/aws/aws-sdk-js/blob/f2f0881cbe5b34d4d10f42ce78b10b5cd96c983a/lib/credentials/shared_ini_file_credentials.js#L88

https://github.com/aws/aws-sdk-js/blob/f2f0881cbe5b34d4d10f42ce78b10b5cd96c983a/lib/credentials/shared_ini_file_credentials.js#L242-L246

### Current Behavior

Only default HTTP connections can be made, because there's no way to pass `httpOptions`:

https://github.com/aws/aws-sdk-js/blob/f2f0881cbe5b34d4d10f42ce78b10b5cd96c983a/lib/credentials/sso_credentials.js#L133

### Reproduction Steps

N/A

### Possible Solution

See above.

### Additional Information/Context

Leading to a bug report in CDK

### SDK version used

Still present in latest

### Environment details (OS name and version, etc.)

N/A

**Comment by ajredniwja** [comment]
Hey @rix0rrr thanks for reporting this, the feature was added few months back https://github.com/aws/aws-sdk-js/pull/4047, I'll discuss with the team and have it reviewed soon.

**Comment by ajredniwja** [comment]
Missed: https://github.com/aws/aws-sdk-js/pull/4200

Would close this issue now.
