### ISSUE TITLE
CreatePresignedPost URL format is preventing CORS preflight check.

### ISSUE THREAD

**Issue by ajredniwja** [aws/aws-sdk-js#4202]
### Discussed in https://github.com/aws/aws-sdk-js/discussions/4183

<div type='discussions-op-text'>

<sup>Originally posted by **colesiegel** August 16, 2022</sup>
Hi

I'm having the exact same issue as described in https://github.com/aws/aws-sdk-js/issues/2128

The format of the URL returned by `createPresignedPost` doesn't seem to conform to other standards that are used for PUT URLs returned by `getSignedUrl`.

I am not sure why the above issue was closed, does anyone know why the URL format is different?

Expected Format: `https://[BUCKET_NAME].s3.amazonaws.com`
Actual Format: `https://s3.amazonaws.com/[BUCKET_NAME]`</div>

**Comment by ajredniwja** [comment]
Was able to reproduce

**Comment by roberttaylor426** [comment]
FWIW @ajredniwja and @colesiegel it appears your expected behaviour now occurs in v3 of the SDK. Have you observed this?

Ironically I was treating the [old behaviour](https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L1071) as a feature rather than a bug, as it helped me test locally :joy:

**Comment by aBurmeseDev** [comment]
Upon discussing with the team, there's no plan to address this behavior. Please upgrade to [JS SDK v3](https://github.com/aws/aws-sdk-js-v3) as this behavior has been addressed and resolved in the v3 version of the SDK. Closing the issue.

**Comment by aBurmeseDev** [comment]
Upon discussing with the team, there's no plan to address this behavior. Please upgrade to [JS SDK v3](https://github.com/aws/aws-sdk-js-v3) as this behavior has been addressed and resolved in the v3 version of the SDK. Closing the issue.
