### ISSUE TITLE
Remove util

### ISSUE THREAD

**Issue by jimmywarting** [aws/aws-sdk-js#4205]
### Describe the feature

Is there any possibility that you could remove `util` from the dependency?
it's very [huge](https://npmgraph.js.org/?q=util). and mostly bloats the hole thing. 

could you reconsider if you do _really_ need it? or can you instead can live without it?

### Use Case

reduce package size

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

2.1215.0

### Environment details (OS name and version, etc.)

n/a

**Comment by ajredniwja** [comment]
Hey @jimmywarting thanks for opening this issue, util was added to resolve https://github.com/aws/aws-sdk-js/issues/3501.

[ V3 of the SDK](https://github.com/aws/aws-sdk-js-v3) was introduced to reduce the package size. 

https://aws.amazon.com/blogs/developer/how-we-halved-the-publish-size-of-modular-aws-sdk-for-javascript-clients/
