### ISSUE TITLE
After installed aws-sdk, am getting compile error in my angular project

### ISSUE THREAD

**Issue by Abinaya158** [aws/aws-sdk-js#4213]
### Describe the bug

i followed the steps in this link- https://www.npmjs.com/package/aws-sdk
but i am getting this compile error in angular

### Expected Behavior

i want to  be compile the code without compile error after installed aws-sdk  successfully

### Current Behavior

after installed aws-sdk getting an compile error , here i attached the error screenshot
![image](https://user-images.githubusercontent.com/84078711/191419609-36eb398f-bd39-4470-a6c2-822fd0f2f6ba.png)

### Reproduction Steps

here i my tsconfig.app.json , in this i removed types:[node] then only i could  use import S3 from 'aws-sdk/clients/s3'; in my ts file

{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "",
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
tsconfig.json file

{
  "compilerOptions": {
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "module": "esnext",
    "esModuleInterop": true
  }
}
package.json
{
    "dependencies": {     
        "aws-amplify": "^4.3.36",
        "aws-sdk": "^2.1220.0",
        "bootstrap": "4.5.2",
       ,
        "jquery": "3.5.1",
        "jwt-decode": "^3.1.2"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^13.2.6",
        "@angular/cli": "^13.2.6",
        "@angular/compiler-cli": "^13.2.6",
        "@angular/language-service": "13.2.6",
        "@types/chartist": "0.11.0",
        "@types/node": "^16.3.2",
        "codelyzer": "6.0.2",
        "jasmine-core": "~4.0.1",
        "jasmine-spec-reporter": "~7.0.0",
        "ts-node": "~10.7.0",
        "typescript": "~4.4.2"
    }
}

### SDK version used

^2.1220.0

### Environment details (OS name and version, etc.)

os:windows, angular: ^13.2.6 version, typescript: ~4.4.2

**Comment by ajredniwja** [comment]
Hey @Abinaya158 thanks for opening this issue, can you share complete steps you followed? 
Also there is https://github.com/angular/angular-cli/issues/20819 which mentions a lot of cases where things can go wrong coz of webpack.
