### ISSUE TITLE
s3fs.js: Uncaught TypeError: Right-hand side of 'instanceof' is not an object(short issue description)

### ISSUE THREAD

**Issue by believeohiozua** [aws/aws-sdk-js#4215]
### Describe the bug

import S3FS from 's3fs';
 var options = {
            region: process.env.REACT_APP_REGION,
            accessKeyId: process.env.REACT_APP_ACCESS_KEY_ID,
            secretAccessKey: process.env.REACT_APP_SECRET_ACCESS_KEY,
        };
 var fsImpl = new S3FS("holotch-service-content", options);

then I get this error : ```s3fs.js:43 Uncaught TypeError: Right-hand side of 'instanceof' is not an object```

which seem to be coming from here:
```
        var bucketParts = s3Utils.decomposePath(bucket);
        ---> this.s3 = options instanceof AWS.S3 ? options : new AWS.S3(options); <---
        this.bucket = bucketParts[0];
        this.path = bucketParts.slice(1).join('/');
        if (this.path) {
            this.path += '/';
        }
    }
```

### Expected Behavior

To list and read all the files with S3FS

### Current Behavior

Throws Error

### Reproduction Steps

```
        var bucketParts = s3Utils.decomposePath(bucket);
        ---> this.s3 = options instanceof AWS.S3 ? options : new AWS.S3(options); <---
        this.bucket = bucketParts[0];
        this.path = bucketParts.slice(1).join('/');
        if (this.path) {
            this.path += '/';
        }
    }
```

### SDK version used

 "s3fs": "^2.5.0",  Reactjs

### Environment details (OS name and version, etc.)

Mac, 2021

**Comment by ajredniwja** [comment]
Hey @believeohiozua thanks for opening this issue can you please share how the SDK is consumed? I am not familiar with s3fs, can you add complete steps on how I can use it to reproduce this issue. Currently the error suggests some circular dependencies.

**Comment by believeohiozua** [comment]
Well long story short, I uninstall s3fs and used @hasnat/s3fs instead and it worked

**Comment by ajredniwja** [comment]
I'll close this issue now, please reach out if you have any other questions foe the SDK. thanks
