### ISSUE TITLE
maxResults parameter for Ground Station listMissionProfiles not working as expected

### ISSUE THREAD

**Issue by andrewpuch** [aws/aws-sdk-js#4220]
### Describe the bug

When adding maxResults to the parameters of listMissionProfiles for AWS Ground Station service it always returns more than requested and does *not* return a nextToken.

```
listMissionProfiles({ maxResults: 2 })
```

[SDK Link](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/GroundStation.html#listMissionProfiles-property) 

### Expected Behavior

When specifying a maxResult it should return as many results as requested as well as a nextToken for pagination.

### Current Behavior

There are no uncaught exceptions or stack traces. The functionality does not work as expected.

### Reproduction Steps

For my use case here is how I wrote a simple test case.

```js
const chai = require("chai");
const aws = require("aws-sdk");

aws.config.update({ region : "us-east-2" });

const groundstation = new aws.GroundStation({ apiVersion : "2019-05-23" });

const test = async () => {
    const expect = chai.expect;

    const noMaxResults = await groundstation.listMissionProfiles().promise();

    // Success.
    expect(noMaxResults.nextToken).to.be.an('undefined');

    // Success (I only have 3 profiles).
    expect(noMaxResults.missionProfileList).to.have.lengthOf(3);

    const withMaxResults = await groundstation.listMissionProfiles({ maxResults:2 }).promise();

    // Failure. There should be a nextToken.
    expect(withMaxResults.nextToken).to.be.a('string');

    // Failure. Returns all 3 profiles.
    expect(withMaxResults.missionProfileList).to.have.lengthOf(2);
};

test();
```

### Possible Solution

I spent some time looking through the SDK and the function looked very similar to how the other "list" functions behaved within the Ground Station SDK so I'm thinking it's on the AWS backend side. For example `listConfigs` in the same Ground Station SDK works as expected.

### Additional Information/Context

Please contact me if you need additional help.

### SDK version used

2.1224.0

### Environment details (OS name and version, etc.)

Mac / Linux / Docker (Tested multiple environments)

**Comment by andrewpuch** [comment]
Recently upgraded to SDK Version `2.1241.0` and issue is still present.

**Comment by andrewpuch** [comment]
Issue still persists in `2.1304.0`.

**Comment by RanVaknin** [comment]
Hi @andrewpuch ,

Sorry for the late reply. Unfortunately we don't have access to groundstation to test the paginator, so it can take some time until I get internal access.

Looking at your code I'm a bit confused, I'm not entirely sure its correct, but hard for me to validate. 
I was able to paginate on a different client using the following code (refactored into groundstation client):

```js
const aws = require("aws-sdk");

const groundstation = new aws.GroundStation({ apiVersion : "2019-05-23" });

async function test(){
    const paginator = groundstation.listMissionProfiles({ maxResults: 2 })

    paginator.eachPage((error, data, done) => {
        if (error) {
            console.error('Error listing objects:', error);
            return done();
        }
        
        if (data) {
            data.missionProfileList.forEach((item) => {
            console.log(`Key: ${item.Key}`);
            });
        }
        
        done();
    });
}
test()
```

Can you let me know if this helps?

Thanks,
Ran~
