### ISSUE TITLE
SignatureDoesNotMatch(short issue description)

### ISSUE THREAD

**Issue by DuyK13** [aws/aws-sdk-js#4230]
### Describe the bug

Nodejs aws-sdk signed url is not working, it always encoded my signature making my url always wrong as expected

### Expected Behavior

API can get the object by signed url

### Current Behavior

It always throw SignatureDoesNotMatch. I have tested with aws cli, it work as I expected. But code doesn't

### Reproduction Steps
```js
const credentials = new AWS.SharedIniFileCredentials({
  profile: config.aws_profile,
});
AWS.config.credentials = credentials;

export const s3 = new AWS.S3({
  signatureVersion: "v4",
  region: config.aws_region,
  params: { Bucket: config.aws_media_bucket },
});

const signedUrlExpireSeconds = 60 * 5;

  const signedUrl: string = s3.getSignedUrl("putObject", {
    Bucket: config.aws_media_bucket,
    Key: key,
    Expires: signedUrlExpireSeconds,
  });

  return signedUrl;
```

### SDK version used

^2.429.0

### Environment details (OS name and version, etc.)

windows 11

**Comment by ajredniwja** [comment]
Hey @DuyK13 thanks for opening this issue, running the script like this:
```js
var AWS = require('aws-sdk');

const s3 = new AWS.S3({
    signatureVersion: "v4",
    region: "us-west-2",
    params: { Bucket: "bucket" },
});

const signedUrlExpireSeconds = 60 * 5;

const signedUrl = s3.getSignedUrl("putObject", {
    Bucket: "bucket",
    Key: 'key.txt',
    Expires: signedUrlExpireSeconds,
});
console.log(signedUrl);
```

I am able to get the URL, can you try the same with the latest version of the SDK?
