### ISSUE TITLE
AWS IOT list things with more than one attributes(short issue description)

### ISSUE THREAD

**Issue by jjayaraman** [aws/aws-sdk-js#4236]
### Describe the feature

In AWS IOT Core,

I would like to list things and filter with more than one attributes. For example I want to filter with 3 attributes at the same time

Is it possible?

But in the ListThingsRequest it just take one attributeName & attributeValue only as below. How to pass multiple attributes and values ?

Please check this : https://stackoverflow.com/questions/74054812/aws-iot-list-things-with-more-than-one-attributes

### Use Case

Want to be able to iot.listThings()  and search with more than one attributes at the same time... For example upto 3 attributes.

The CLI supports this but Javascript SDK 2 does not

### Proposed Solution

Support this in Javascript SDK 2 as it is currently supported in CLI

### Other Information

https://stackoverflow.com/questions/74054812/aws-iot-list-things-with-more-than-one-attributes

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

Javascript 2  - "aws-sdk": "2.1094.0",

### Environment details (OS name and version, etc.)

MacOS

**Comment by ajredniwja** [comment]
@jjayaraman thanks for opening this issue, Can you please share the the code and library you are using currently?

**Comment by jjayaraman** [comment]
Thanks,

 I am using iot module from "aws-sdk": "2.1094.0",

Sample code:-

const listThingsRequest =
{
"attributeName": "state",
"attributeValue": "registered"
}

iot.listThings(listThingsRequest)

But I would like to pass multiple attributes something like below, which is currently supported in the CLI where we can pass multiple attributeName and attributeValue

const listThingsRequest =
{
"attributeName": "state",
"attributeValue": "registered"
"attributeName": "color",
"attributeValue": "red"

}

**Comment by jjayaraman** [comment]
Any feedback on this issue please? Thanks

**Comment by kellertk** [comment]
Hi. I will be closing this issue as we are no longer considering feature requests against v2 of the JS SDK. Please check out AWS SDK for JS v3 instead.
