### ISSUE TITLE
AWS IOT Thing search with iot.listThings() with both thingTypeName and attributes

### ISSUE THREAD

**Issue by jjayaraman** [aws/aws-sdk-js#4237]
### Describe the feature

In AWS IOT Javascript SDK,

I am not able to do iot.listThings() with both thingTypeName and attribute with code as below

  let listThingsRequest = 
  {
      "thingTypeName": "mythingtype",
      "attributeName": "state",
      "attributeValue": "registered"
  }

  // List all iotThings based on search criteria in listThingsRequest
  export const listThings = async (listThingsRequest: ListThingsRequest) => {
    return iot.listThings(listThingsRequest).promise()
  }

I get a error message as below,

"Listing things by the combination of attribute and thing type is not supported

Please check this: https://stackoverflow.com/questions/74066002/aws-iot-thing-search-with-iot-listthings-with-both-thingtypename-and-attribute

### Use Case

Should be able  to do iot.listThings()  with both attributes and thingTypeName

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

Javascript 2  - "aws-sdk": "2.1094.0",

### Environment details (OS name and version, etc.)

MacOS

**Comment by ajredniwja** [comment]
@jjayaraman thanks for opening this feature request however it looks like you are using https://github.com/aws/aws-iot-device-sdk-js, you would probably need to open an issue in their repo. Thanks

**Comment by jjayaraman** [comment]
> @jjayaraman thanks for opening this feature request however it looks like you are using https://github.com/aws/aws-iot-device-sdk-js, you would probably need to open an issue in their repo. Thanks


Thanks, I am using iot module from   "aws-sdk": "2.1094.0",
I am not using aws-iot-device-sdk-js

```

const listThingsRequest =
{
"thingTypeName": "mythingtype",
"attributeName": "state",
"attributeValue": "registered"
}

iot.listThings(listThingsRequest)

```

**Comment by ajredniwja** [comment]
Can you please share your complete code example?

**Comment by raziza** [comment]
I have also the same issue. Kind of. just without the thingType.
I'm using the `listThings` to get all the things from a different environment which stated in the attribute.. But sometimes I don't get anything, or sometimes all.. 
For now as a workaround I do not send any attribute and do the filtering in my side. But would like to have a solution for this weird bug. which I think is related to yours @jjayaraman.

I'm using java in this is the simple code
```
ListThingsResponse things = iotClient.listThings(builder -> builder.attributeName("env").attributeValue("test").build);
```

**Comment by kellertk** [comment]
Hello, at this time we are focusing our efforts on v3 of the JavaScript SDK. Please migrate to AWS SDK for JS v3.
