### ISSUE TITLE
Subscripcion to SQS from NestJS app

### ISSUE THREAD

**Issue by SAEE94** [aws/aws-sdk-js#4241]
### Describe the bug

i'm trying to to a listener to a specific que using SQS but at the moment to run the app i'm getting this error

(node:48371) UnhandledPromiseRejectionWarning: SQSError: SQS receive message failed: Inaccessible host: `sqs-test' at port `undefined'. This service may not be available in the `us-east-2' region.

and i verified the queue is already created in AWS

### Expected Behavior

i would to receive the message that are published in the que

### Current Behavior

i got the error i mentioned above

### Reproduction Steps

this happen just running mi nest app

### Additional Information/Context

This is ni listener module where i'm creating the configurations
`import { Module } from '@nestjs/common';
import { SqsModule } from '@ssut/nestjs-sqs';
import * as AWS from 'aws-sdk';
import { config} from '../config';
import { ListenerService } from './listener.service';

AWS.config.update({
    region: config.AWS_REGION,
    accessKeyId: config.ACCESS_KEY_ID,
    secretAccessKey: config.SECRET_ACCESS_KEY,
});
@Module({
    imports: [
        SqsModule.register({
            consumers: [
                {
                    name: config.TEST_QUEUE, // name of the queue 
                    queueUrl: config.TEST_QUEUE, // the url of the queue
                    region: config.AWS_REGION,
                },
            ],
            producers: [],
        }),
    ],
    controllers: [],
    providers: [ListenerService],
})
@Module({})
export class ListenerModule {}
`

and this is mi service

`import { Injectable } from '@nestjs/common';
import { SqsMessageHandler } from '@ssut/nestjs-sqs';
import * as AWS from 'aws-sdk';
import { config } from '../config';

console.log('config.AWS_REGION', config);

@Injectable()
export class ListenerService {
    
    constructor() { }
    
    @SqsMessageHandler(config.TEST_QUEUE, false)
    async handleMessage(message: AWS.SQS.Message) {
        const obj: any = JSON.parse(message.Body) as {
            message: string;
            date: string;
        };
        const { data } = JSON.parse(obj.Message);

        // use the data and consume it the way you want // 
        console.log(data);
    }
}
`

also i'm using this dependency ssut/nestjs-sqs

### SDK version used

2.1233.0

### Environment details (OS name and version, etc.)

macOS monterey verion 12.5.1

**Comment by ajredniwja** [comment]
Hey @SAEE94 thanks for opening this issue, you have mentioned you are using mi nest app and it is only happening in the app. Can you please mention on how you set your app, and provide minimal repro code to reproduce the error? 
Were you able to run this successfully when not using the app?

**Comment by iCarlosAugusto** [comment]
The error is because `queueUrl` in the consumer module is wrong. 

```
@Module({
  imports: [
    SqsModule.register({
      consumers: [
        {
          name: config.TEST_QUEUE,
          //queueUrl: config.TEST_QUEUE, <===== Wrong
          queueUrl: config.TEST_QUEUE_URL, // Correct
          region: config.AWS_REGION,
        },
      ],
      producers: [],
    }),
  ],
  controllers: [],
  providers: [MessageHandler],
})
```

**Comment by faiqshariff** [comment]
Still not working
