### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by ahmete60** [aws/aws-sdk-js#4244]
### Describe the bug

npm install asw-sdk
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/asw-sdk - Not found

### Expected Behavior

installation of aws-sdk

### Current Behavior

npm install asw-sdk
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/asw-sdk - Not found

### Reproduction Steps

npm install asw-sdk

### SDK version used

not downloaded

### Environment details (OS name and version, etc.)

windows 10

**Comment by ajredniwja** [comment]
@ahmete60 thanks for opening this issue, I am not able to reproduce this error. This error doest seem to come from the SDK. You can follow some steps found at this [StackOverFlow post](https://stackoverflow.com/questions/47520181/installing-npm-package-fails-with-404)

**Comment by ahmete60** [comment]
I solved it by global install. But plain install failed repeated tries.

**Comment by ccampanale** [comment]
@ahmete60 

Not sure if the issue is verbatim but `npm install asw-sdk` is not the same as `npm install aws-sdk`. Perhaps this was just a typo?

**Comment by ahmete60** [comment]
Yes thats just a typo. Even having it globally install withot -g still
gives dame response. I have it working now, but problem remains.

**Comment by zshzbh** [comment]
Hey @ahmete60 ,

I can't reproduce this issue and I don't think this is AWS SDK specific issue. I do think it could be network/config/permission related.  To help unblock your work, could you please try ```check npm registry``` and see where's the npm registry pointing to? And also could you please send the error msg(not the error msg triggered by typo :-) ) that you have?

Thanks!
Maggie
