### ISSUE TITLE
Feature request: load config by default

### ISSUE THREAD

**Issue by jedwards1211** [aws/aws-sdk-js#4246]
### Describe the feature

I want the sdk to load the config file by default instead of only if `AWS_SDK_LOAD_CONFIG` is truthy.  Why isn't it loaded by default?

### Use Case

It's frustrating to have to either set `AWS_REGION` or `AWS_SDK_LOAD_CONFIG`.  I guess I could set `AWS_SDK_LOAD_CONFIG=1` in my login script, though this wouldn't work I'm using any tools that run scripts via non-login shell.  What's the point of config files if they aren't loaded automatically?  I want to be able to configure the SDK to use a default region for a given profile automatically.

### Proposed Solution

Either load the config automatically, or support an option in the credentials file to automatically load the config for a given profile.

The SDK loads the profiles from disk automatically so I don't get why the config feature wasn't designed from the get-go to load automatically.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

2.1100.0

### Environment details (OS name and version, etc.)

macOS 12.6

**Comment by ccampanale** [comment]
@jedwards1211 I'd guess that default to not loading config files was chosen in order to avoid issues with configurations from environments. Many people (myself included) use metadata services (like ECS task roles provided to containers or EC2 instance profiles) and don't use config files. I think this is a common use case and arguably more common that config files. Perhaps this is why?

**Comment by ajredniwja** [comment]
@jedwards1211 thanks for opening this feature request and I kinda agree with @ccampanale, more information can be found in this [PR](https://github.com/aws/aws-sdk-js/pull/1391) when it was added. Loading config by default can also be a breaking change for many customers at this point. 

As a general rule, any value that you can place in the shared credentials file can alternatively be placed in the shared config file. The reverse isn't true; only a few settings can be placed in the credentials file. However, as a security best practice, we recommend that you keep any sensitive values, such as access key IDs and secret keys, in the separate credentials file. This way, you can provide separate permissions for each file, if necessary.

https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html#setting-region-config-file

**Comment by jedwards1211** [comment]
> we recommend that you keep any sensitive values, such as access key IDs and secret keys, in the separate credentials file.

Yes I already do this.  But while i can also put the region I want in the credentials file, it doesn't get loaded by default.  Why does setting a default region have to be so tedious?

What y'all are saying about how it would have been a breaking change doesn't make sense, since people wouldn't have even had a config file before that feature was introduced.   The presence of a config file would have been a good enough signal to opt in...

**Comment by jedwards1211** [comment]
> in order to avoid issues with configurations from environments

Don't environment vars override values from the config files anyway?

Also I don't see why someone would use config files on EC2 instances, so any potential conflict there seems like a moot point.   Do some people use config files on instances?

**Comment by kellertk** [comment]
Hi, I am closing this issue in favor of the issue in SDK v3. We are no longer implementing new feature requests in AWS SDK for JS v2.
