### ISSUE TITLE
executeSql marked as Deprecated without full feature replacement

### ISSUE THREAD

**Issue by NicolasGhesquier** [aws/aws-sdk-js#4253]
### Describe the issue

Hi,

The `executeSql` method of `RdsDataService` is marked as deprecated, however it's the only method that can take multiple semicolon separated statements like following: 

``` sql
 CREATE TABLE users;
 CREATE TABLE companies;
```

`executeStatement` of `batchExecuteStatement` do not offer this feature.

Is the recommended way to split this type of string by `;` and run a `executeStatement` for each?

The possibility to execute multiple semicolon separated statements is great, in particular when executing migration files.

Looking forward for your recommendations

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html

**Comment by ajredniwja** [comment]
Hey @NicolasGhesquier thanks for opening this request, unfortunately the way right now will be to iterate over different sql statements but not separated by `;` as it is not required for `executeStatement` operation. The decision to deprecate the operation was taken by RDS team, you can raise a concern at [rds-data-api-feedback@amazon.com](mailto:rds-data-api-feedback@amazon.com) but its unlikely they will be able to bring the deprecated API back. A case can be made to allow `executeStatement` to take multiple values in, which maybe an issue with backwards compatibility.
