### ISSUE TITLE
AWS.ResourceGroupsTaggingAPI is not a constructor

### ISSUE THREAD

**Issue by karanpokar** [aws/aws-sdk-js#4262]
### Describe the bug

SDK in index.html

`<script src="https://sdk.amazonaws.com/js/aws-sdk-2.1247.0.min.js"></script>`

Importing ResourceGroupsTaggingAPI 

`/* global AWS */`

`var resourcegroupstaggingapi = new AWS.ResourceGroupsTaggingAPI({apiVersion: '2017-01-26'});`

Throws issue like AWS.ResourceGroupsTaggingAPI is not a constructor

PS. it is a React Project

### Expected Behavior

Expected to create a ResourceGroupsTaggingAPI constructor and access the resource

### Current Behavior

Throws exception like 

`TypeError: AWS.ResourceGroupsTaggingAPI is not a constructor`

### Reproduction Steps

1. create react app
2. Add `<script src="https://sdk.amazonaws.com/js/aws-sdk-2.1247.0.min.js"></script>` in index.html
3. Initialise as `var resourcegroupstaggingapi = new AWS.ResourceGroupsTaggingAPI({apiVersion: '2017-01-26'});`

### SDK version used

2.1247.0

### Environment details (OS name and version, etc.)

macOS Monterey V12.3.1

**Comment by ajredniwja** [comment]
HI @karanpokar thanks for opening this issue, can you please follow the steps found [here](https://aws.amazon.com/blogs/mobile/integrate-the-aws-sdk-for-javascript-into-a-react-app/). That would be the recommended way to use the SDK with React.
