### ISSUE TITLE
Amplify createDeployment method

### ISSUE THREAD

**Issue by andretpc** [aws/aws-sdk-js#4264]
### Describe the issue

I'm not sure how to use the 'zipUploadUrl' returned from the 'createDeployment' method and I can't seem to find any examples anywhere.

Should use multipart/form-data? If not, then how?

Also, I'm getting an error when trying to post to 'zipUploadUrl': 

"The request signature we calculated does not match the signature you provided. Check your key and signing method.", 

which doesn't make sense to me since the zipUploadUrl already seems to have every field necessary to authorize the request in its search params (algorithm, signature, credentials, etc).

Are there any examples anywhere on how to use zipUploadUrl in javascript (or any other language)?

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Amplify.html#createDeployment-property

**Comment by ajredniwja** [comment]
@andretpc thanks for opening this issue, can you please provide what your use case is and share your example. 
The error suggests it to be a credentials/authentication issue. It would be helpful if you could answer the questions in bug template: https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug-report.yml&title=%28short+issue+description%29
