### ISSUE TITLE
FIPS endpoints not resolved correctly in Govcloud region

### ISSUE THREAD

**Issue by yuvalyacoby** [aws/aws-sdk-js#4266]
### Describe the bug

We enabled FIPS endpoints by setting environment variable `AWS_USE_FIPS_ENDPOINT` to true.
For SNS and IAM services the endpoint is resolved uncorrectly.

### Expected Behavior

Service endpoint should be resolved correctly in govcloud according to  https://aws.amazon.com/compliance/fips/

### Current Behavior

SNS resolved to `sns-fips.us-gov-west-1.amazonaws.com`, while the correct endpoint is `sns.us-gov-west-1.amazonaws.com`
IAM endpoint is resolved to `iam-fips.us-gov-west-1.amazonaws.com` while the correct endpoint is `iam.us-gov.amazonaws.com`
`UnknownEndpoint: Inaccessible host: `iam-fips.us-gov-west-1.amazonaws.com' at port `undefined'. This service may not be available in the `us-gov-west-1' region`

It might happen in more services we didn't encountered yet.

### Reproduction Steps

* create a JS lambda in `us-gov-west-1`
* set environment variable `AWS_USE_FIPS_ENDPOINT` to true.
* create IAM/SNS instance:  `const IAM = new AWS.IAM();`
* make any call to the service

### SDK version used

2.676.0

### Environment details (OS name and version, etc.)

AWS Lambda Node.js 16.x runtime

**Comment by ajredniwja** [comment]
Hey @yuvalyacoby thanks for opening this issue, do you see similar behavior with latest version of the SDK. The SDK version seems to be fairly old, https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html

**Comment by yuvalyacoby** [comment]
@ajredniwja Hi thanks for reviewing the issue.
Yes I see it with latest version - `"aws-sdk": "^2.1258.0"`.
can easily be reproduced with the following code:
```js
// index.mjs
import AWS from 'aws-sdk';

const sns = new AWS.SNS({ region: 'us-gov-west-1' });

const topics = await sns.listTopics({}).promise();

console.log(topics);
```

and running: `export AWS_USE_FIPS_ENDPOINT=true && export AWS_PROFILE=my-gov-profile && node index.mjs` 
will result with following error:
```
UnknownEndpoint: Inaccessible host: `sns-fips.us-gov-west-1.amazonaws.com' at port `undefined'. This service may not be available in the `us-gov-west-1' region.
```
unsetting `AWS_USE_FIPS_ENDPOINT` env var will result in a good response.

**Comment by yuvalyacoby** [comment]
@ajredniwja any updates on this one please?

**Comment by RanVaknin** [comment]
Hi @yuvalyacoby ,

Sorry for the late reply. We are combing through our repo and addressing old issues that might have slipped through the cracks. 

There has been a lot of re-work done around fips endpoint and I think SNS was one of the impacted services. 
This issue is now solved and working as expected. 

With your code:

```js
import AWS from 'aws-sdk';
const sns = new AWS.SNS({ region: 'us-gov-west-1' });
console.log(sns.config.endpoint)
```

output:

```console
$ node index.js
sns.us-gov-west-1.amazonaws.com
```

Since this is an old issue and the problem is addressed I feel confident we can close this. If any other issues arise, please feel free to open a new issue. 

Thanks,
Ran~

**Comment by matthill33** [comment]
Hello, I'm still experiencing this issue but I'm not using terraform and not the AWS-SDK directly. Is it possible that terraform is using an outdated version of the SDK and that's where my issue is? Thanks
