### ISSUE TITLE
SES SDK - Email Header - Content Type issue

### ISSUE THREAD

**Issue by poovannan-tmx** [aws/aws-sdk-js#4269]
### Describe the bug

Hi,

We have built an system  which uses an SES service to send an email using the  aws-sdk (v2).Application is written in node js(v12). Our application uses  AWS batch job which is getting triggered by Event bridge. Batch job posts the message to queue, these messages will be picked by the AWS lambda function which is written in node js (v12). Here lambda function uses the SES services to send the mail by calling the  ses.sendmail function. 

We are facing an issues here some time users receives an email as text  format  some time users receives an email as html format for the same email parameters. We see the content-type is some how picking incorrect,  instead of the " text/html"  aws-sdk sets the content type header as " text/plain" for the same email parameters. For same email parameter we see the content type picked by the sdk  is at  time "text/plain" and some time "text/html".

Thanks

### Expected Behavior

Expected content type is "text/html".

### Current Behavior

Content type is getting  in consist at time it sets the text/plain at time it sets  the content type as "text/html" for the same email params 

### Reproduction Steps
```js
const emailParams = {
    Source: senderEmail,
    Destination: {
      ToAddresses: emailList,
      CcAddresses: ccAddress,
      BccAddresses: bccAddress,
    },
    ReplyToAddresses: [senderEmail],
    Message: {
      Body: {
        [contentType ? "Html" : "Text"]: {
          Charset: "UTF-8",
          Data: content,
        },
      },
      Subject: {
        Charset: "UTF-8",
        Data: subject,
      },
    },
  };
}
```

await ses.sendEmail(emailParams).promise();

### SDK version used

aws-sdk version 2

### Environment details (OS name and version, etc.)

AWS Lambda

**Comment by RanVaknin** [comment]
Hi @poovannan-tmx ,

Sorry for the very late reply. It seems like this issue fell off our radar, I truly apologize for that. 

Since Node 12 has been end of support as of april 22, and SES now has an SESv2 client, I don't know if this is still an issue. 
Can you update your runtime and refactor your code to use the newer SESv2 client and see if it solves the issue?

Thanks,
Ran~
