### ISSUE TITLE
AWS Batch submitJob method does not allow job definition revisions

### ISSUE THREAD

**Issue by vjfuenzalida** [aws/aws-sdk-js#4280]
### Describe the bug

The submitJob method is supposed to receive the `jobDefinition` parameter, which is documented as: 

> The job definition used by this job. This value can be one of name, name:revision, or the Amazon Resource Name (ARN) for the job definition. If name is specified without a revision then the latest active revision is used.

But when I make a request with a specific revision or simply `latest`, it gets rejected because of this:
`ClientException: Provided name bank-account-statement-job:latest is not supported pattern[a-zA-Z_0-9-]{1,128}`
(It doesn't make sense that the documentation suggest using a revision or ARN when the pattern will always reject it).

If I remove the revision and only use the jobDefinition name (because it will use the latest by default), it returns a 403 error saying: 
`User: arn:aws:iam::xxxxxxx:user/my-username is not authorized to perform: batch:SubmitJob on resource: arn:aws:batch:us-west-1:xxxxxxx:job-definition/my-job` (no ":latest" appended to the resource ARN).

Any clues on how to do this right? On the other side, I have a policy that restrict job submission to the job definition used above (with the ":*" wildcard at the end to allow any revision).

### Expected Behavior

Job definition revisions should be allowed as the docs explain, and the default behaviour should also be checked ("revision = latest" by default). The regex pattern (`[a-zA-Z_0-9-]{1,128}`) used to validate the jobDefinition and jobQueue restrict the usage of ARNs (because of the `/` and `:` characters).

### Current Behavior

I'm not able to submit any jobs unless I change the policy to something really wide and unsecure. This should work properly the same way as the dashboard job submission interface.

### Reproduction Steps

1. Install the `aws-sdk` node package.
2. Create an AWS user with a policy that restricts actions to a certain job definition (with the wildcard ":*" for the definition revision number).
3. Call the `submitJob` method using the SDK, and passing as parameter the whole job definition ARN, without any revision (docs say latest will be used by default).
4. Receive a 403 response with the mentioned error.

### Possible Solution

Allow job definition revisions and modify the pattern used to validate both `jobDefinition` and `jobQueue` parameters for the `submitJob` method in the AWS Batch SDK.

### SDK version used

2.1169.0

### Environment details (OS name and version, etc.)

macOS Big Sur, Node 16.13

**Comment by msardana94** [comment]
I am facing this problem while using boto3. The only work around is to give All Resources permission in IAM for this to work which can be problematic

**Comment by JulianFerry** [comment]
If it helps, I thought I was having this problem when executing a batch job from a step function by passing an ARN with a revision number to the `arn:aws:states:::batch:submitJob.sync` task. However it turned out that I wasn't passing the ARN as I thought I was.

Once I correctly passed the ARN to the `JobDefinition` parameter I no longer had this error, so it seems like the regex in the error message is incorrect and misleading.
