### ISSUE TITLE
AWS.EventBridge is not a constructor

### ISSUE THREAD

**Issue by Trephneor** [aws/aws-sdk-js#4290]
### Describe the bug

Hey, I have the following code. Similar to the guide for in [browser Polly implementation from the official docs](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/getting-started-browser.html) I have tried to create a script that interacts with EventBridge to enable a rule:
```
<!DOCTYPE html>
  <body>
    <div id="textToSynth">
      <button class="btn default" onClick="activateService()">Activate Service</button>
      <p id="result">Click button to activate service</p>
    </div>

    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.595.0.min.js"></script>
    <script type="text/javascript">

        // Function invoked by button click
        function activateService() {
          // Initialize the Amazon Cognito credentials provider
          AWS.config.region = '...';
          AWS.config.credentials = new AWS.CognitoIdentityCredentials(...);

          // Create the EventBridge service object
          var eventbridge = new AWS.EventBridge({apiVersion: '2015-10-07'});
    </script>
  </body>
</html>
```
However, when I try running this code by pressing the button, I get the following error:
```
tgtg.html:24 Uncaught TypeError: AWS.EventBridge is not a constructor
    at activateService (tgtg.html:24:29)
    at HTMLButtonElement.onclick (tgtg.html:10:63)
```
I am able to interact with any other service I have tried so far, but I cannot seem to use AWS.EventBridge at all. Is this a bug?

### Expected Behavior

I expect to be able to interface through AWS.EventBridge. It works with AWS.Polly or other services (similar to this example from docs on [how to make Amazon Polly work in a browser script](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/getting-started-browser.html))

### Current Behavior

When I try running this code, I get the following error:
```
tgtg.html:24 Uncaught TypeError: AWS.EventBridge is not a constructor
    at activateService (tgtg.html:24:29)
    at HTMLButtonElement.onclick (tgtg.html:10:63)
```

### Reproduction Steps

1. Create a HTML page with the following code. Replace AWS.config.region and AWS.config.credentials with your own. This implementation is very similar to [Getting Started in a Browser Script from Developer Guide for SDK v2](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/getting-started-browser.html)
```
<!DOCTYPE html>
  <body>
    <div id="textToSynth">
      <button class="btn default" onClick="activateService()">Activate Service</button>
      <p id="result">Click button to activate service</p>
    </div>

    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.595.0.min.js"></script>
    <script type="text/javascript">

        // Function invoked by button click
        function activateService() {
          // Initialize the Amazon Cognito credentials provider
          AWS.config.region = 'YOUR_REGION';
          AWS.config.credentials = new AWS.CognitoIdentityCredentials({IdentityPoolId: 'YOUR_CREDENTIALS'});

          // Create the EventBridge service object
          var eventbridge = new AWS.EventBridge({apiVersion: '2015-10-07'});
    </script>
  </body>
</html>
```
2. Open developer panel and run script using the button
3. Observe error in console

### SDK version used

https://sdk.amazonaws.com/js/aws-sdk-2.595.0.min.js

### Environment details (OS name and version, etc.)

Windows 10 Pro Version	21H2, "Google Chrome";v="107"

**Comment by ajredniwja** [comment]
Hey @Trephneor thanks for opening this issue can you check if you see the same error when using the latest version.

```<script src="https://sdk.amazonaws.com/js/aws-sdk-2.1264.0.min.js"></script>```

I was able to call the constructor correctly without any errors. 

Alternatively you can also use: https://sdk.amazonaws.com/builder/js/ for custom browser build. 

Thanks

**Comment by Trephneor** [comment]
Hey @ajredniwja I have tried changing the version for `<script src="https://sdk.amazonaws.com/js/aws-sdk-2.1264.0.min.js"></script>` however it threw the same error.

However, when I have tried building my own AWS SDK with EventBridge included through the link you have provided, it worked.
I downladed a minified version and put it on my webhost, then replaced the line above with `<script src="js/aws-sdk-2.1265.0.min.js"></script>`

**Comment by ajredniwja** [comment]
The browser build only includes services that support cross origin resource sharing but not enabled for. We maintain a list of supported services: [here](https://github.com/aws/aws-sdk-js/blob/master/SERVICES.md) .
The `<script src="https://sdk.amazonaws.com/js/aws-sdk-2.1264.0.min.js"></script>` should not work hence you can use the browser builder. 

I will close this issue now, please reach back if you have any questions. 

Thanks
