### ISSUE TITLE
Receiving duplicate push notifications

### ISSUE THREAD

**Issue by th-kenil** [aws/aws-sdk-js#4298]
### Describe the bug

After publishing payload to send push notifications through SNS api. It sends same notification twice to targeted devices.
e.g. If I publish notification to one device endpoint then device receives two same notifications for it. From CloudWatch Logs I got console logs of published endpoints which were correct but notification received were twice

### Expected Behavior

It should send one single notification instead of twice for one publish of notification to endpoint

### Current Behavior

It is sending same notification twice while only one time notification was published to an endpoint

### Reproduction Steps
```js
async notifySpringIsDue(userDeviceEndpoints: string[], sName: string, sId?: number): Promise<IApiResponse | undefined> {
    try {
        const messagePayload = JSON.stringify({
              aps: {
                alert: {
                  title: notification_messages.NOTIFICATION_TITLE,
                  body: notification_messages.NOTIFICATION_BODY,
                },
                sound: 'default',
                category: notification_messages.NOTIFICATION_CATEGORY,
              },
              data: { sName, sId },
      });
      for (const endpoint of userDeviceEndpoints) {
        await this.publishSnsNotification(messagePayload, endpoint, 'Default Notification');
      }
   } catch (error: any) {
      logger.error(error);
      throw error;
    }
  }
  
  private async publishSnsNotification(messagePayload: string, endpoint: string, defaultPayload: string) {
    try {
      const params = {
        Message: JSON.stringify({ default: defaultPayload, APNS_SANDBOX: messagePayload }),
        TargetArn: endpoint,
        MessageStructure: 'json',
      };
      await this.aws.getSnsClient.publish(params).promise();
      console.log('Published --> ', endpoint);
    } catch (error: any) {
        console.error(error);
    }
  }
```

### SDK version used

2.1166.0

### Environment details (OS name and version, etc.)

Node.js - 16.15.0

**Comment by RanVaknin** [comment]
Hi @th-kenil ,

Your code example is missing some information like how you are setting the client and where you are calling `notifySpringIsDue`.

Regardless, this issue comes up every once in a while and it's usually because folks are calling `.promise()` like you have here:
```js
      await this.aws.getSnsClient.publish(params).promise();
```

I wasn't able to reproduce your code, but I don't think you need that `.promise()` in there. 

Let me know if that helps. Otherwise if you can include a more complete (and preferably more concise) code sample I can try to repro.

Thanks,
Ran

**Comment by 2manoj1** [comment]
We are face same issue.
