### ISSUE TITLE
InvalidClientMetadataException due to apostrophe in hostname

### ISSUE THREAD

**Issue by hey-leon** [aws/aws-sdk-js#4299]
### Describe the bug

The other day I had two computers on my local area network with the same hostname. MacOS decided to update my hostname to resolve the conflict. However this resulted in my hostname containing an apostrophe.

Low and behold a couple days later I was using a package that leverages this sdk. It was no longer working. I managed to trace it back to my hostname containing an apostrophe.

### Expected Behavior

This SDK would with hostnames containing apostrophes. Especially as MacOS may add these by default in some scenarios.

### Current Behavior

This SDK fails with `InvalidClientMetadataException`. 

It is quite hard to pin point the issue from this error as well. The stack traces that came along with this error were too short and only contained lines from inside the SDK and not the package I was using directy.

### Reproduction Steps

1. change hostname to contain an apostrophe
2. npm install -f aws-sso-cli
3. run aws-sso-cli

### Possible Solution

1. Handle apostrophes in hostnames gracefully.
2. Increase stack traces size
3. Point out limitations on hostname

### SDK version used

2.1270.0

### Environment details (OS name and version, etc.)

MacOS 12.5.1

**Comment by ajredniwja** [comment]
Hey @hey-leon thanks for opening this issue, it would be helpful to add minimal code example for the issue.

The SDK has not done any customizations for the SSO specifically, the error generated is by SSO service. 

Briefly looking at the issue, I can discuss with the team if we should be doing a validation check on the hostnames as the error indicates that the client information sent in the request during registration is invalid but I would need to confirm how this error is generated from the SDK. 

The [npm aws-sso-cli package](https://www.npmjs.com/package/aws-sso-cli) is not owned by the SDK team. It has a dependency very old version of this SDK. 

With that being said, I understand the problem with the stack traces in this version of the SDK which was solved in [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3) which does provide better [error handling](https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/).

**Comment by hey-leon** [comment]
@ajredniwja I see this is version is to be phased out next year. Is adoption of v3 happening quickly. If it seems low value to fix this I am more than happy to close this. Otherwise if it seems v3 adoption is some time away let me know and I will dig up a minimum replication.

**Comment by ajredniwja** [comment]
@hey-leon, Currently, I dont regard this necessarily to be a bug with the SDK. For the use case you mentioned it does seem to be a low value fix right now if its not the in the V3 of the SDK.
There are no official dates that I can point you towards but [we are formalizing our plans to enter AWS SDK for JavaScript v2 into maintenance mode in 2023](https://github.com/aws/aws-sdk-js#version-2x-support).

**Comment by hey-leon** [comment]
@ajredniwja ok no problem happy to close this. Thanks for taking the time.
