### ISSUE TITLE
searchPlaceIndexForPosition is not showing the exact location

### ISSUE THREAD

**Issue by dhwaj1902** [aws/aws-sdk-js#4305]
### Describe the bug

I was trying to implement the `searchPlaceIndexForPosition`, but the lat and long I am entering are showing accurately on google, but not on aws sdk.

### Expected Behavior

I have put the 
``
lat: 29.8543
long: 77.8880
``
Actually, they are the coordinates of `Roorkee` but in aws api it is showing `Sonipat`

### Current Behavior

Showing wrong region

### Reproduction Steps

Can be more presise.

### SDK version used

Location - 2020-11-19

### Environment details (OS name and version, etc.)

Windows- 11, aws-sdk - 2.1244.0

**Comment by RanVaknin** [comment]
Hi @dhwaj1902,

Thanks for reaching out to us. 

Using the reverse lookup operations (coordinates to location name)  `searchPlaceIndexForPosition` you are expecting a place **A**, but instead receive a place **B**.
The SDK is just a client that facilitates the requests between the customer and the service. We can't really do anything about how accurate an API call might be, that logic is defined in the service layer. 

AWS Location services uses a few different data providers to geolocate. Based on the description of these providers, some are more accurate for certain areas than others. Perhaps you need to change a data provider of your index? 

> ### Creating a place index resource
>Begin by creating a place index resource in your AWS account.
>
>When you create a place index resource, you can choose from the data providers available to support queries for geocoding, reverse geocoding, and searches:
>
>Esri – For more information about Esri's coverage in your region of interest, see [Esri geocoding coverage](https://developers.arcgis.com/rest/geocode/api-reference/geocode-coverage.htm) in the Esri documentation.
>
>HERE Technologies – For more information about HERE's coverage in your region of interest, see [HERE geocoding coverage](https://developer.here.com/documentation/geocoder/dev_guide/topics/coverage-geocoder.html) in the HERE documentation.
>
>Grab – Grab only provides data for Southeast Asian countries. For more information about Grab's coverage, see [Countries and area covered](https://docs.aws.amazon.com/location/latest/developerguide/grab.html#grab-coverage-area) in this guide.

Can you tell us more about which data provider you used to set up your index? Can you please also share your code?
If non of the data providers work for you, I can create an internal ticket with the service team. 

Thanks,
Ran~
