### ISSUE TITLE
I am unable to stop the uploading process

### ISSUE THREAD

**Issue by Jpatidar9** [aws/aws-sdk-js#4312]
### Describe the bug
```js
 const myBucket = new aws.S3({
      params: { Bucket: `${bucketInfo.name}/${bucketInfo.directoryName}` },
      region: bucketInfo.regin,
    });

    const params = {
      Bucket: `${bucketInfo.name}/${bucketInfo.directoryName}`,
      Key: key,
      Body: file,
    };
    myBucket
      .upload(params)
      .on("httpUploadProgress", callback)
      .send(function (err, data) {
        resolve(data);
      });
```
      
      
    I am using this type of finality and I want to stop the uploading whenever users wants to stop it....but when I try to call the 
       abort() it is not found on the finality.....please help me to solve or suggest any way to achieve the same.
   

Thanks.  

### Expected Behavior

Need to stop the uploading file in mid way.

### Current Behavior

unable to stop the uploading file 

### Reproduction Steps

Just call the method

### SDK version used

2.1273.0

### Environment details (OS name and version, etc.)

Linux

**Comment by ajredniwja** [comment]
Hey @Jpatidar9 thanks for opening this issue, you can use `abort()` on AWS request. 
See: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#abort-property

Please check some of the [stackoverflow examples](https://stackoverflow.com/questions/34429957/how-to-abort-stop-an-amazon-aws-s3-upload-in-progress) on the same.
