### ISSUE TITLE
Webpack does not processes Aws_query.js, EndpointParameters.js or runtimeConfig.js with Nullish operator

### ISSUE THREAD

**Issue by robertlario** [aws/aws-sdk-js#4320]
### Describe the bug

Under Node.js v16.17.0, when webpack@4.46.0 is applied to aws-sdk@2.1291.0, webpack fails on @aws-sdk/client-sns/dist-cjs/protocols/Aws_query.js, @aws-sdk/client-sns/dist-cjs/runtimeConfig.js, and @aws-sdk/client-sns/dist-cjs/endpoint/EndpointParameters.js.

It appears to hang on operators '?' and '??'
as an example, with Aws_query.js webpack calls out the '? as the offending token in the line:

'if (input.AWSAccountId?.length === 0) {':

### Expected Behavior

The respective files would have been processed without error and included in the overall index.js 

### Current Behavior

Webpack produces: 

/***/ "../../@aws-sdk/client-sns/dist-cjs/protocols/Aws_query.js":
/*!*******************************************************************************************************************************************************!*\
  !*** /node_modules/@aws-sdk/client-sns/dist-cjs/protocols/Aws_query.js ***!
  \*******************************************************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

throw new Error("Module parse failed: Unexpected token (2801:31)\nYou may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n|     if (input.AWSAccountId != null) {\n|         const memberEntries = serializeAws_queryDelegatesList(input.AWSAccountId, context);\n>         if (input.AWSAccountId?.length === 0) {\n|             entries.AWSAccountId = [];\n|         }");

/***/ }),

/***/ "../../@aws-sdk/client-sns/dist-cjs/runtimeConfig.js":
/*!*************************************************************************************************************************************************!*\
  !*** /node_modules/@aws-sdk/client-sns/dist-cjs/runtimeConfig.js ***!
  \*************************************************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

throw new Error("Module parse failed: Unexpected token (31:34)\nYou may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n|         runtime: \"node\",\n|         defaultsMode,\n>         bodyLengthChecker: config?.bodyLengthChecker ?? util_body_length_node_1.calculateBodyLength,\n|         credentialDefaultProvider: config?.credentialDefaultProvider ?? (0, client_sts_1.decorateDefaultCredentialProvider)(credential_provider_node_1.defaultProvider),\n|         defaultUserAgentProvider: config?.defaultUserAgentProvider ??");

/***/ }),

### Reproduction Steps

debugging code in visual studio using serverless.

{
    "version": "0.2.0",
    "configurations": [

        {
            "type" :"node",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceFolder}/node_modules/serverless/bin/serverless",
            "args": [
                "offline",
                "start",
                "-s",
                "dev"
            ],
            "internalConsoleOptions": "openOnSessionStart",
            "outFiles": ["${workspaceFolder}/.webpack/**/*.js"],
            "sourceMaps": true,
            "env":{
                "SLS_DEBUG": "*",
                "ARCHIVE_CONFIG": "AuditEvent,60|Patient,120",
                "AWS_PROFILE": "default",
                // AWS_ACCESS_KEY_ID = The access id to the account, was provided when the AWS account was created
                "AWS_ACCESS_KEY_ID": "XXXXXXXXXXXXXXXXXXXX",
                // AWS_SECRET_ACCESS_KEY = The secret key provodied 
                "AWS_SECRET_ACCESS_KEY": "XXXXXXXXXX",
                "OFFLINE_BINARY_BUCKET": "XXXXXXXXXXXXX",
                "OFFLINE_ELASTICSEARCH_DOMAIN_ENDPOINT": "XXXXXXXXXX",
                "AWS_DEFAULT_REGION": "us-east-1"
            },
            "runtimeArgs": [
                "--preserve-symlinks-main",
                "--preserve-symlinks"
            ],
            "autoAttachChildProcesses": true,
            "stopOnEntry": true
        }
    ]
}

### SDK version used

webpack 5.0, aws-sdk 2.12920.0

### Environment details (OS name and version, etc.)

Windows 11 21H build 22000.1335

**Comment by bflemi3** [comment]
Was there ever a resolution discovered? I'm having the same issue.

**Comment by robertlario** [comment]
It was a versioning issue. Kick back one version.

r/ Robert

On Feb 23, 2023, at 3:29 PM, Brandon ***@***.***> wrote:

﻿

Was there ever a resolution discovered? I'm having the same issue.
