### ISSUE TITLE
"Access Token has been revoked" on cognito pre auth lambda trigger 

### ISSUE THREAD

**Issue by ShashwatMDas** [aws/aws-sdk-js#4323]
### Describe the bug

I want to revoke the refresh tokens of other active sessions of the cognito user, when they login from a new browser/device. The code inside pre auth lambda is:

```js
const res = await new Promise((resolve, reject) => {
cognitoidentityserviceprovider.adminUserGlobalSignOut(params, (err, data) => {
    if (err) {
         console.log('Global signout error:', err, err.stack); 
         resolve(err)
       }
       else {
         console.log('Global signout success:', data);
         resolve(err)
       }           
     })
   });
done(null, event)
 ```

### Expected Behavior

The user should get logged in when they try to sign in, and other active sessions' refresh tokens should get revoked.

### Current Behavior

The user should get logged in when they try to sign in, and other active sessions' refresh tokens should get revoked. This happens 2/3rd of the times a user tries to login. However almost 1/3rd times cognito returns a response "Access Token has been revoked" error response, which I believe should be happening because the token is getting revoked these 1/3 times, before the authentication for new login request completes. Not sure why it would happen though

### Reproduction Steps

1. Create a pre auth lambda trigger
2. Add code to globally signout user for pre auth lambda
3. Connect the trigger lambda to cognito

### SDK version used

2.216.1

### Environment details (OS name and version, etc.)

Serverless

**Comment by RanVaknin** [comment]
Hi,

Before we try to reproduce this, can you please check the code sample you have provided? 
You are resolving the promise and passing err if it succeeded? 

```js
const res = await new Promise((resolve, reject) => {
cognitoidentityserviceprovider.adminUserGlobalSignOut(params, (err, data) => {
    if (err) {
         console.log('Global signout error:', err, err.stack); 
         resolve(err) // <--- reject(err) ???
    } else {
         console.log('Global signout success:', data);
         resolve(err) // <-- resolve(data) ???
       }           
     })
   });
done(null, event)
```

Thanks,
Ran~
