### ISSUE TITLE
AWS SDK ignoring IAM role credentials after transpiling .ts to .js

### ISSUE THREAD

**Issue by alexfernandezv** [aws/aws-sdk-js#4331]
### Describe the bug

After transpiling a simple _.ts_ aws sdk script (sending a queue message) to a bundled _.js_, the script fails after trying to get aws credentials inherited from an IAM role. 
Running the same script in plain _.js_, the code runs succesfully without any error.

### Expected Behavior

Credentials are taken into consideration by the aws-sdk even if the source script is a bundled _.js_ coming from _.ts_. 

### Current Behavior

Bundled .js after transpiling fails with:
`Error Error [CredentialsError]: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at credError (webpack://test/./node_modules/aws-sdk/lib/config.js?:400:40)
    at Config.getCredentials (webpack://test/./node_modules/aws-sdk/lib/config.js?:441:14)
    at Request.VALIDATE_CREDENTIALS (webpack://test/./node_modules/aws-sdk/lib/event_listeners.js?:111:28)
    at Request.callListeners (webpack://test/./node_modules/aws-sdk/lib/sequential_executor.js?:102:18)
    at Request.emit (webpack://test/./node_modules/aws-sdk/lib/sequential_executor.js?:78:10)
    at Request.emit (webpack://test/./node_modules/aws-sdk/lib/request.js?:686:14)
    at Request.transition (webpack://test/./node_modules/aws-sdk/lib/request.js?:22:10)
    at AcceptorStateMachine.runTo (webpack://test/./node_modules/aws-sdk/lib/state_machine.js?:14:12)
    at Request.runTo (webpack://test/./node_modules/aws-sdk/lib/request.js?:406:15)
    at Request.send (webpack://test/./node_modules/aws-sdk/lib/request.js?:370:10) {
  code: 'CredentialsError',
  time: 2023-01-31T20:05:32.864Z,
  originalError: {
    message: 'No credentials to load',
    code: 'CredentialsError',
    time: 2023-01-31T20:05:32.864Z
  }
}`

### Reproduction Steps

https://github.com/alexfernandezv/aws-sdk-ts

1. Install dependencies _npm i_
2. Modify SQS queue url pointing to an existing one in _index.ts_
3. Transpile the code by running _npm run build_
4. Execute the bundled .js script,  _node dist/bundle.js_

### SDK version used

2.1305.0

### Environment details (OS name and version, etc.)

NodeJS latest, Windows 10

**Comment by alexfernandezv** [comment]
Hey @RanVaknin thanks for your time! 
I am not loading the creds in any way, I am trying to use the injected web identity role from an EKS context. As the SDK docs stay, I don't need to load the credentials explicitly. Maybe I am missing something.

**Comment by RanVaknin** [comment]
Can you please add the link of the docs you are following, and your code? 

Thanks,
Ran~

**Comment by alexfernandezv** [comment]
Here you have the [docs](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-iam.html) I am referring to.
The reproducible code can be found  on the issue.
Thanks @RanVaknin

**Comment by RanVaknin** [comment]
Hi @alexfernandezv ,

I was able to reproduce your issue. 

I was able to fix it with adding a `target: "node"` in the webpack config file.
My understanding is that there is no process object in browsers, so webpack snapshots your process object and injects it. 

Let me know if that helped.
Thanks,
Ran~

**Comment by alexfernandezv** [comment]
Hey @RanVaknin thanks for the response!
Yes, the bug is fixed if I target node as environment to run my webpack bundle. But what if I need a browser bundle? I need the Webpack target to be web. Is this possible?
Thanks again.

**Comment by RanVaknin** [comment]
If you are bundling your code for web you need to use an appropriate credential loading strategy for web like I linked in my first comment. Ec2 role creds don't apply for web environments.
