### ISSUE TITLE
listTagsForResource is not a function when using NodeJS v18 runtime

### ISSUE THREAD

**Issue by mnlttt** [aws/aws-sdk-js#4335]
### Describe the bug

When invoking `listTagsForResource` from `CloudWatchLogs` of `@aws-sdk/client-cloudwatch-logs` on NodeJS v18 runtime, the lambda says `cloudWatchLogs.listTagsForResource is not a function`. On NodeJS v16 it works.

### Expected Behavior

To work with both 16 and 18.

### Current Behavior

The method is undefined.

### Reproduction Steps

When invoking `listTagsForResource` from `CloudWatchLogs` of `@aws-sdk/client-cloudwatch-logs` on NodeJS v18 runtime, the lambda says `cloudWatchLogs.listTagsForResource is not a function`. On NodeJS v16 it works.

### SDK version used

3

### Environment details (OS name and version, etc.)

MacOS 13.0.1

**Comment by kuhe** [comment]
The bundled SDK is provided as a convenience but does not update as often as the SDK available on NPM. 

- https://docs.aws.amazon.com/lambda/latest/operatorguide/sdks-functions.html

It suggests here that you'll have to deploy your own copy to use a different version.

The command in question was added in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.200.0. The Node.js 18 Lambda runtime uses v3.188.0 according to https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html.
