### ISSUE TITLE
use URLSearchParams instead of the querystring package (deprecated)

### ISSUE THREAD

**Issue by mahmoud-triki** [aws/aws-sdk-js#4347]
### Describe the bug

The aws-sdk npm package is using the query-string@0.2.0 which is deprecated.
You can see more details about the deprecating of the [querystring](https://www.npmjs.com/package/querystring) package here.

### Expected Behavior

Use the URLSearchParams API sintead

### Current Behavior

aws-sdk package is using a deprecated package which is [querystring](https://www.npmjs.com/package/querystring).

### Reproduction Steps

You can do `npm install` and you'll see the npm Deprecation warning

### Possible Solution

uninstall querystring package

### SDK version used

latest

### Environment details (OS name and version, etc.)

all

**Comment by yenfryherrerafeliz** [comment]
Hi @mahmoud-triki, thanks for opening this issue. I agree with this suggestion. I will mark this issue as feature-request and to be reviewed so it can be further addressed.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Related: https://github.com/aws/aws-sdk-js/issues/4150
