### ISSUE TITLE
Why is the AWS SSM SDK caching results of DescribeParametersCommand and how to avoid this

### ISSUE THREAD

**Issue by gatapia** [aws/aws-sdk-js#4349]
### Describe the issue

I am currently having some strange behaviour with the `@aws-sdk/client-ssm` AWS Node.JS SDK.  The following code is incorrectly printing `length:0`

```
import {SSMClient, PutParameterCommand, ParameterType, DescribeParametersCommand, DeleteParametersCommand } from "@aws-sdk/client-ssm";

const client = new SSMClient({});
const name = 'param-name';

// clean up to allow multiple runs
await client.send(new DeleteParametersCommand({ Names: [name] }));

// make first 'list' call
const res1 = await client.send(new DescribeParametersCommand({}));
const list1 = (res1.Parameters || []).filter(p => p.Name === name);

// add parameter
(await client.send(new PutParameterCommand({ Name: name, Value: 'value', Type: ParameterType.STRING })))

// expect second 'list' to show this newly added parameter
const res2 = await client.send(new DescribeParametersCommand({}));
const list2 = (res2.Parameters || []).filter(p => p.Name === name);

// length=0.  However, if we comment out first `client.send(new DescribeParametersCommand({}))` above then length=1
console.log('length:', list2.length);
```
However, if I comment out the first call to `client.send(new DescribeParametersCommand({}))` then the correct value is logged: `length: 1`:

```
...
// make first 'list' call
// const res1 = await client.send(new DescribeParametersCommand({}));
// const list1 = (res1.Parameters || []).filter(p => p.Name === name);
...
const res2 = await client.send(new DescribeParametersCommand({}));
const list2 = (res2.Parameters || []).filter(p => p.Name === name);

// length=0.  However, if we comment out first `client.send(new DescribeParametersCommand({}))` above then length=1
console.log('length:', list2.length);
```

It appears that the result to `DescribeParametersCommand` is being cached?  However, there is nothing about caching in the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ssm/classes/describeparameterscommand.html) or anything about invalidating the cache.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ssm/
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ssm/classes/describeparameterscommand.html

**Comment by RanVaknin** [comment]
Hi @gatapia ,

There is no caching happening here.

What you are seeing is just a result of asynchronous code. You are counting on the fact that your delete command will run first, and that your code will execute in the order in which it is written - which is not guaranteed.

For example, I've refactored your code a bit using `setTimeout()` to mimic blocking synchronous code behavior.
```js
import {SSMClient, PutParameterCommand, ParameterType, DescribeParametersCommand, DeleteParametersCommand } from "@aws-sdk/client-ssm";

const client = new SSMClient({region: "us-east-2"});
const name = 'my-param';

try {
    // clean up to allow multiple runs
    await client.send(new DeleteParametersCommand({ Names: [name] }));
    
    // make first 'list' call
    setTimeout(async() => {
        const res1 = await client.send(new DescribeParametersCommand({}));
        console.log("res1: " + res1.Parameters.length)
    }, 5000);
        
    // add parameter
    setTimeout(async() => {
        await client.send(new PutParameterCommand({ Name: name, Value: 'value', Type: ParameterType.STRING }))
    }, 5000);
    
    // expect second 'list' to show this newly added parameter
    setTimeout(async() => {
        const res2 = await client.send(new DescribeParametersCommand({}));
        console.log("res2: " + res2.Parameters.length)
    }, 10000);
} catch (error) {
    console.log(error)    
}
```

```console
$ node index.js
res1: 0
res2: 1
```

**This is not a solution.** This is just a "hack" to demonstrate why your code was not behaving the way you wanted it to. 

I don't quite understand your use case of running this `delete > list > create > list` setup using the same parameter name. 

Thanks,
Ran

**Comment by gatapia** [comment]
_I don't quite understand your use case of running this delete > list > create > list setup using the same parameter name_

This is just an example showing the issue, not a real scenario.

_What you are seeing is just a result of asynchronous code. You are counting on the fact that your delete command will run first, and that your code will execute in the order in which it is written - which is not guaranteed._

Interesting, the fact that the code above `await`s the response I assumed would mean that the command had been executed. As is the case with the S3Client, DynamoClient and many others.  In fact this is the first client that responds with an inconsistent response.

However, if that is the way it works, then I'll close the ticket.

**Comment by RanVaknin** [comment]
Hi @gatapia ,

Sorry I might have misinterpreted what you have written at first. 

>Interesting, the fact that the code above awaits the response I assumed would mean that the command had been executed. 

It has been executed, but even if the server gives you a 200, it takes the record time to be created and propagated throughout AWS. So you have written to it, but _reading_ from it might take an extra second that your next await calls already fired and returned.

You can simplify my whole example with this snippet:

```js
    await client.send(new PutParameterCommand({ Name: name, Value: 'value', Type: ParameterType.STRING }))
    
    // // expect second 'list' to show this newly added parameter
    setTimeout(async() => {
        const res2 = await client.send(new DescribeParametersCommand({}));
        console.log("res2: " + res2.Parameters.length)
    }, 10000);
```

The reason I asked about your workflow is because if you were running into this in a "real world scenario" maybe I could have helped rewrite your code in a way that produces the desired results.

At any rate, if you have any additional questions you can open a discussion.

Thanks,
Ran~
