### ISSUE TITLE
Broken dependency on node module sax when creating rpm

### ISSUE THREAD

**Issue by comtaler** [aws/aws-sdk-js#435]
Since version 2.0.x, it has updated the dependency of xml2js from 0.2.4 to 0.2.6. On xml2js 0.2.4, it has dependency on sax>=0.4.2. But on xml2js 0.2.6, it has dependency sax=0.4.2.

The problem is that sax 0.4.2 has an executable script (https://github.com/isaacs/sax-js/blob/v0.4.2/examples/switch-bench.js). When building rpm that contains aws-sdk 2.0.x, it will requires a dependency of file "/usr/local/bin/node-bench", but that isn't available on a target machine.

This executable file has been removed since sax 0.5.3, the dependency on that is fixed on xml2js from 0.2.8.

If we can update aws-sdk's dependency on xml2js to at least 0.2.8, this will solve the problem.

This is not exactly aws-sdk's problem, it's just a dependency issue.

**Comment by comtaler** [comment]
Currently, I workaround this by removing the executable flag of the file from sax.

**Comment by lsegal** [comment]
How often is this RPM re-built? Is this something that has to be done a lot, or is this shared by some single task / release?

**Comment by lsegal** [comment]
I'm going to mark this as closed since this seems to be a third-party packaging issue. If this is complicated to work around, feel free to reopen and we can try to find a better solution, but upgrading the dependency will require some more work.

**Comment by mataneine** [comment]
I have the exact same issue, and found this which is related:
https://bugs.launchpad.net/juniperopenstack/+bug/1391351
https://github.com/Juniper/contrail-third-party-cache/pull/9

**Comment by denodaeus** [comment]
This was a really really super annoying issue for me to track down before reading this, and I echo @mateneine, if you guys can just fix it without having to do work arounds and search for things broken, that would be awesome.  The problem is when starting a new project, I have no clue that because I'm using the latest and greatest, one of the dependencies for aws-sdk is broken when bundling as an rpm with grunt-rpm unless I do @comtaler's workaround.  I pulled my hair out looking for the issue within grunt-rpm for almost two hours before tracking this down.

**Comment by assen-totin** [comment]
Still an issue for me as of today; AWS still pulls 0.2.7. 
I'm using %filter_from_requires in my spec file to fix the broken require.

**Comment by AdityaManohar** [comment]
@assen-totin which version of the SDK are you using? As of SDK version `v2.1.22`, we use `xml2js v0.2.8` and `sax v0.5.3`. See [package.json](https://github.com/aws/aws-sdk-js/blob/master/package.json#L29).

**Comment by assen-totin** [comment]
My package.conf has:
    "azure-mgmt": "*",
    "azure-mgmt-vnet": "*",
    "azure-mgmt-compute": "*",
    "azure-mgmt-storage": "*",
So, it should be the latest that npm has to offer - and I;m still getting 0.2.7 for xml2js.

**Comment by mhart** [comment]
Heh, Azure :smiling_imp: 

This is the AWS SDK.
