### ISSUE TITLE
Lambda does not behave as expected with SES's sendEmail()

### ISSUE THREAD

**Issue by naimGur** [aws/aws-sdk-js#4356]
### Describe the bug

Inconsistency while using `sendEmail()` method in Lambda. The same code working in my nodejs project locally does not behave the same in the Lambda function. 

### Expected Behavior

I shall be able to send emails immediately (in seconds or minutes) as I call the `sendEmail()` method in Lambda function with the below code:

```

const AWS = require("aws-sdk");
AWS.config.update({
  region: "eu-west-1",
  accessKeyId: "xxxxxxxxxxxxxxxxxx",
    secretAccessKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
});
const ses = new AWS.SES();

const emailParams = {
  Destination: {
    ToAddresses: ["YOUR VERIFIED EMAIL"],
  },
  Message: {
    Body: {
      Text: {
        Data: "bodyString",
      },
    },
    Subject: {
      Data: "subjectData",
    },
  },
  Source: "YOUR VERIFIED EMAIL",
};
console.log("sending:", emailParams);
ses.sendEmail(emailParams, (err) => {
    if (err) {
        console.log("err", err);
    } else {
        console.log("email sent");
    }
});

```

And below policy added to my Lambda:
```
{
            "Action": [
                "dynamodb:ListStreams",
                "dynamodb:DescribeTable",
                "dynamodb:GetItem",
                "dynamodb:Query",
                "dynamodb:Scan",
                "ses:*"
            ],
            "Resource": [
                "arn:aws:dynxxxxxxxx",
                "arn:aws:dyxxxxxxxxxx",
                "*"
            ],
            "Effect": "Allow"
        }
```

### Current Behavior

I am able to send emails immediately by running the nodejs project that I am running on my computer. And I know that they are delivered by checking my Gmail account. The same code in Lambda is not generating any error, but emails are not delivered.

When I trigger the lambda once, nothing happens, when I trigger it many times, some of the emails are delivered, and some of them are like being ignored. 

I am not in the SES sandbox, and both receiver and sender emails are verified.

Here is the Stackoverflow post that I opened for this issue:
https://stackoverflow.com/questions/75612286/aws-ses-does-not-send-emails-immediately

### Reproduction Steps

The code can be deployed to the lambda and a test can be made by triggering that lambda. In my configuration, my lambda function is triggered by DynamoDB. 

### SDK version used

"aws-sdk": "^2.1252.0"

### Environment details (OS name and version, etc.)

Windows 11 and Mac, NodeJs, Typescript, Serverless-framework

**Comment by RanVaknin** [comment]
Hi @naimGur ,

I assume this code is the NodeJS code. 

Is your lambda code setup correctly with a handler?

> The same code in Lambda is not generating any error, but emails are not delivered.

I don't see in your policy any cloudwatch related permissions. 
Do you have cloudwatch log groups configured to receive logs from the lambda execution?
The log group would have all the relevant logs from the lambda execution so if it failed, there should be a response stack trace in the relevant log group.

Thanks,
Ran~
