### ISSUE TITLE
Lambda 'updateFunctionConfiguration' UnexpectedParameter

### ISSUE THREAD

**Issue by eyal-solomon1** [aws/aws-sdk-js#4359]
### Describe the bug

getting `UnexpectedParameter: Unexpected key 'EphemeralStorage' found in params` while calling `updateFunctionConfiguration`

in both docs [JS SDK V2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#updateFunctionConfiguration-property) and [lambda docs](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html) there is an optional parameter named `EphemeralStorage`

checked the API reference and there is **no** `EphemeralStorage` parameter available [Link](https://github.com/aws/aws-sdk-js/blob/8a6df808956890445f355e5e94880fabc149be72/apis/lambda-2015-03-31.min.json#L1650) 

using latest SDK version (`aws-sdk@2.698.0`)

### Expected Behavior

`updateFunctionConfiguration` should accept the `EphemeralStorage` parameter and update to Lambda function `/tmp` folder storage size based on the inputed value

### Current Behavior

`updateFunctionConfiguration` doesn't accept the `EphemeralStorage` parameter and throws an error

### Reproduction Steps

call `updateFunctionConfiguration` with `EphemeralStorage` object parameter 

### Additional Information/Context

node version `v18.12.1`

### SDK version used

2.698.0

### Environment details (OS name and version, etc.)

Mac M1 macOS Ventora 13.0

**Comment by RanVaknin** [comment]
Hi @eyal-solomon1 ,

Im able to successfully update the config on my lambda:

```js
const AWS = require("aws-sdk")

var lambda = new AWS.Lambda({region: "us-east-1"});

var params = {
    FunctionName: 'test-lambda',
    EphemeralStorage: {
      Size: '10240'
    },
}

lambda.updateFunctionConfiguration(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
  });
```

Can you share your code snippet so we can get some more insights? 

Thanks,
Ran~

**Comment by eyal-solomon1** [comment]
> Hi @eyal-solomon1 ,
> 
> Im able to successfully update the config on my lambda using this code:
> 
> ```js
> const AWS = require("aws-sdk")
> 
> var lambda = new AWS.Lambda({region: "us-east-1"});
> 
> var params = {
>     FunctionName: 'test-lambda',
>     EphemeralStorage: {
>       Size: '10240'
>     },
> }
> 
> lambda.updateFunctionConfiguration(params, function(err, data) {
>     if (err) console.log(err, err.stack); // an error occurred
>     else     console.log(data);           // successful response
>   });
> ```
> 
> Can you share your code snippet so we can get some more insights?
> 
> Thanks, Ran~

Hi @RanVaknin ,

Surprisingly  it works now .. no idea what I did wrong before 

Maybe can you link me the correct API reference ? where `EphemeralStorage` is included in the optional params (in the link I provided it isn't)

**Comment by RanVaknin** [comment]
Hi @eyal-solomon1 ,

I think I understand the source of confusion. From the [JS SDK V2 LINK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#updateFunctionConfiguration-property) you have sent to our v2 docs:
```js
  EphemeralStorage: {
    Size: 'NUMBER_VALUE' /* required */
  },
```
I believe "required" here is referring to `Size` being required in the context of the `EphemeralStorage` object.
Meaning if you want to include EphemeralStorage storage in your request, the object must have a size field.


Additioanlly, you can see in the [lambda docs](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html) link you have provided:  `EphemeralStorage` is an _optional_ field.
It's marked as `Required: No` as shown in the photo

<img width="878" alt="image" src="https://user-images.githubusercontent.com/50976344/223575330-aef64b69-0d33-4320-b91d-4a804bedd76a.png">

I know the docs can be somewhat confusing. We are working on making our SDK v3 docs much better so hopefully that will be a catalyst for people to migrate to v3.

At any rate, It seems like you have figured out the issue and not running into the error anymore. 
If you are running into any other issues, feel free to open a new thread.

Thanks,
Ran~
