### ISSUE TITLE
NodeJS exits silently when describeTrustedAdvisorCheckResult has large response

### ISSUE THREAD

**Issue by mingli-trend** [aws/aws-sdk-js#4360]
### Describe the bug

`Support.describeTrustedAdvisorCheckResult` will kill NodeJS without throwing any errors if the response is too big.

The problem only happens when the response is too big. In our case, tens of thousands of `flaggedResources` are in the response.

It seems related to a memory issue, but there is no exception. The NodeJS quits silently. 

The issue happens intermittently ( 50% chance ). 

The problem impacts a lot of customers. The big customers have a large number of resources for certain checks.

One case is the customer has 15,000+ EBS snapshots, so `describeTrustedAdvisorCheckResult` `H7IgTzjTYb` check cause the issue.

### Expected Behavior

The API should response without causing Node.JS failure.

### Current Behavior

Node.JS exit silently if the API response is too big.

### Reproduction Steps

1. Create 15000+ EBS snapshots
2. Make sure  *Amazon EBS Snapshots* check (H7IgTzjTYb) contains all these snapshots as flagged resources. Other check with a large amount of flagged resources also have same issue.
3. Run the below code.

```js
const AWS = require("aws-sdk");

const Support = new AWS.Support({
  accessKeyId: "",
  secretAccessKey: "",
  sessionToken: "",
  region: "us-east-1",
});

(async () => {
    try {
        const checkResult = await Support.describeTrustedAdvisorCheckResult({
            checkId: "H7IgTzjTYb",
            language: "en",
        }).promise();

        console.log(checkResult);

    } catch (error) {
        console.error(error);
    }
})();
```
4. The issue will happen intermittently. From the screenshot, you can see the first-time response is correct. But the second time Node.JS exit without any error.
![image](https://user-images.githubusercontent.com/85924193/223283853-daa35952-2f15-4934-8f30-36a25c2678a9.png)

### Possible Solution

No workaround.

### SDK version used

2.1092.0

### Environment details (OS name and version, etc.)

Lambda, MacOS

**Comment by mingli-trend** [comment]
Any update?

**Comment by yenfryherrerafeliz** [comment]
Hi @mingli-trend, thanks for opening this issue. I suspect that maybe the promise is neither rejected or resolved internally, however, I need to confirm it. Have you tried using callbacks instead of promises, if so, do you see the same behavior?. Example:
Instead of:
```js
(async () => {
    try {
        const checkResult = await Support.describeTrustedAdvisorCheckResult({
            checkId: "H7IgTzjTYb",
            language: "en",
        }).promise();

        console.log(checkResult);

    } catch (error) {
        console.error(error);
    }
})();
```
Have:
```js
Support.describeTrustedAdvisorCheckResult({
    checkId: "H7IgTzjTYb",
    language: "en",
}, (err, data) => {
    if (err) {
        console.log('Error: ', err)
    } else {
        console.log(data)
    }
});
```
You could also try using pagination, but I am not sure if this operation supports it, may need to investigate, but would it be easier if you could just do the following:
```js
Support.describeTrustedAdvisorCheckResult({
    checkId: "H7IgTzjTYb",
    language: "en",
}).eachPage((err, data) => {
    if (err) {
        console.log('Error: ', err)
    } else {
        console.log('Data: ', data)
    }
})
```

Thanks!

**Comment by mingli-trend** [comment]
Thank you @yenfryherrerafeliz , I'll test it out soon.

**Comment by mingli-trend** [comment]
I cannot reproduce it anymore. From the system logs the problem only happens in a few days. I'll close it. Thank you!
