### ISSUE TITLE
Allow array of strings as Body for S3 PutObjectCommandInput

### ISSUE THREAD

**Issue by Izhido** [aws/aws-sdk-js#4366]
### Describe the feature

As the title says.

### Use Case

When generating large text files that, during its creation in memory, require a lot of string handling (a known weak point of Javascript), one of the many recommendations for increased performance is to hold an array with lots of small pieces of data that, at the end, are join()ed together into a single large string, which is then sent to whatever I/O process is required for it.

But, what if we had the chance to not generate the single large string, and allow the array with small strings to be sent directly to I/O for processing? This would save both memory and processing time from not having to join anything into a single large block.

### Proposed Solution

Just like the title says, allow Body in PutObjectCommandInput to be, in addition to a single string, Buffer or Uint8Array, to also be an array of strings. The SDK has a better chance to handle the array and generate the web requests in whatever way is more efficient, while at the same time saving the SDK user the cost of assembling manually the single source of data.

Naturally, this could also be applied to other components of the various SDK services, whenever they make any sense for the component itself.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v3

### Environment details (OS name and version, etc.)

JS

**Comment by kuhe** [comment]
Please open this in https://github.com/aws/aws-sdk-js-v3/issues
