### ISSUE TITLE
AWS DynamoDB DAX "NoRouteException" handling in nodejs

### ISSUE THREAD

**Issue by aruntechspian** [aws/aws-sdk-js#4377]
I am getting error for using dynamodb dax even if the endPoint and Region is corrent in the configuration.
In these scenario i need to handle the exception and redirect the request to DynamoDb intead of DAX cache.

How can i handle these i have added code for refence.
```js
var ddbClient = new AWS.DynamoDB.DocumentClient()
var daxClient = null;

if (process.argv.length > 2) {
    var dax = new AmazonDaxClient({endpoints: [process.argv[2]], region: region})
    daxClient = new AWS.DynamoDB.DocumentClient({service: dax });
}

var client = daxClient != null ? daxClient : ddbClient;`
```
In the above code my end Point is correct but sometimes due to cluster restart the dax shows the "NoRouteException".

**Comment by RanVaknin** [comment]
Hi @aruntechspian ,

The Dax Client makes requests to your Dax Cluster. NoRouteException gets returned when the Dax client can't find any endpoints (or nodes) for your cluster (like during a restart)
This means your request isn't hitting the Dax cluster. You could probably confirm this by looking at the Cloudwatch metrics for your cluster in the AWS Dax Console (or Cloudwatch).

In your logs you should see if the request is being retried, and if not, implement a retry strategy.

Thanks,
Ran~
