### ISSUE TITLE
Beware of cross-browser Blob.slice() in ManagedUpload.

### ISSUE THREAD

**Issue by dconnolly** [aws/aws-sdk-js#438]
For at least Safari, Blob.slice() is vendor-prefixed as webkitSlice, and if a File/Blob is passed as the body for a ManagedUpload, calling slice() on it will fail. See https://developer.mozilla.org/en-US/docs/Web/API/Blob.slice for specifics. Using some slice function detection logic can avoid this, eg:

```
var sliceFunction = (self.body.slice ? 'slice' : (self.body.mozSlice ? 'mozSlice' : 'webkitSlice'));
var buf = self.body[sliceFunction](self.partPos, self.partPos + self.partSize);
```

**Comment by lsegal** [comment]
Interestingly enough, we ran tests against Safari 5.1 and 6, and 5.1 works but 6 fails: https://travis-ci.org/aws/aws-sdk-js/builds/45632157

So I do have some code in place to check and call the `webkitSlice` or `mozSlice` functions as a fallback. Will be pushing that soon.

**Comment by dconnolly** [comment]
Ha that's odd. That change looks great, I'll leave this open until it finds its way into a release. Cheers!

**Comment by lsegal** [comment]
Cherry picked this change from the `selenium` branch over into master to resolve this more quickly. Thanks for reporting!

**Comment by dconnolly** [comment]
Awesome, thanks!
