### ISSUE TITLE
xml2js is vulnerable to prototype pollution(short issue description)

### ISSUE THREAD

**Issue by Harisene** [aws/aws-sdk-js#4387]
### Describe the bug

When I run **npm i** or **npm ci** I get the error and the installation process fails. 

### Expected Behavior

npm ci should run successfully.

### Current Behavior

Getting bellow error,
- 2 high severity vulnerabilities

This is what I got from running **npm audit**
![Screenshot 2023-04-10 at 1 48 13 PM](https://user-images.githubusercontent.com/33250282/230860079-b9406963-2fed-4e3b-b4dd-f4a0403927fe.png)

### Reproduction Steps

running npm i or npm ci

### SDK version used

2.1353.0

### Environment details (OS name and version, etc.)

macOS Monterey 12.6.1

**Comment by prathameshmhatre** [comment]
I was also facing same issue but I have added a overrides within the package.json as below 
```
"overrides": {
    "xml2js": "0.5.0"
  }
```
And did a npm update and it resolved the Issue.
The actual fix will be aws-sdk being updated for the  "xml2js": "0.5.0" version

**Comment by SamucaDev** [comment]
Same problem with "aws-sdk": "^2.996.0"

![Screenshot from 2023-04-10 11-03-11](https://user-images.githubusercontent.com/51060285/230916730-2cdf1786-c570-4ff2-a579-7b4238c7efbf.png)

**Comment by ricardofaria-minu** [comment]
this issue was fixed, but not publish in the NPM.
