### ISSUE TITLE
theres an error in one of the node_modules

### ISSUE THREAD

**Issue by privateGenish** [aws/aws-sdk-js#4409]
### Describe the bug

When using `npm i aws-sdk` theres an error in one of the node_modules folder named `xmlbuilder`. 
The `appveyour.yml` file is raising an error that says `Incorrect type. Expected "boolean | build options".`  on line 19.

### Expected Behavior

well... no to show an error?

### Current Behavior

I dont know if it's related but my aws-sdk is also causing some bug and i cant access it's modules. but it's probably a bug in my code because im doing dependency injections. 

### Reproduction Steps

just `npm i aws-sdk` and you'll see the error soon enough. 

### SDK version used

latest

### Environment details (OS name and version, etc.)

aws sam

**Comment by RanVaknin** [comment]
Hi @privateGenish,

I'm not sure I quite understand the issue. Is this a compile error when using typescript? 

Seeing your code, project structure and package.json might help.

Additionally I'd delete your `node_modules` and `package.json` and run npm install again.

Thanks,
Ran~
