### ISSUE TITLE
[S3 Docs] .upload / ManagedUpload does not document how to abort upload

### ISSUE THREAD

**Issue by mfn** [aws/aws-sdk-js#441]
The documentation at http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html does not describe how to actually abort an upload which is in progress.

Through trial and error I found this pattern to "work for me"; but I'm neither sure if it's a good idea nor if it's supposed to work that way:

``` JS
var manager = bucket.upload(...);
bucket.send(function(err,data)) {
  if (!err && !data) {
    // user aborted
  }
}

// somewhere else
function cancelUpload() {
  manager.cleanup();
}
```

**Comment by onassar** [comment]
@lsegal is abort currently supported in browser version of sdk? Calling it seems to go through, but the upload is continuing.
