### ISSUE TITLE
AWS.config.credentials return undefined when IRSA is configured

### ISSUE THREAD

**Issue by Marwennnne** [aws/aws-sdk-js#4412]
### Describe the bug

I am using IRSA ( IAM ROLES for Service Account ). I can't access the temporary creds in my source code using the aws-sdk.
```
const AWS = require('aws-sdk');
console.log(AWS.config.credentials);
```
I get `undefined`. Is there any thing wrong  am I doing ?

### Expected Behavior

I get the temporary credentials generated when the pod assumed the role

### Current Behavior

I can't have access the credentials but the aws-sdk is authentified and authorized 

### Reproduction Steps

- Setup IRSA
- Access credentials like this AWS.config.credentials

### SDK version used

2.1370.0

### Environment details (OS name and version, etc.)

node:14-bullseye

**Comment by RanVaknin** [comment]
Hi @Marwennnne ,

Are you following any doc or tutorial for IRSA + SDK?

Thanks,
Ran~

**Comment by Marwennnne** [comment]
@RanVaknin No actually, because the sdk is already authentified and authorized according to the policy attached to the role. My problem is that I want access to the current temporary credentials generated when I assumed the role

**Comment by RanVaknin** [comment]
@Marwennnne ,

I'm not sure what you mean by 
> the sdk is already authentified and authorized according to the policy attached to the role.

a role policy is just describing the permissions the role has, it has nothing to do with auth. You mentioned in you reproduction setps "setup IRSA" can you send me the documentation you are following to do that? 

Are you running this code on lambda? In an EC2 instance? 
Thanks,
Ran~
