### ISSUE TITLE
Exceptions from credentials provider replaced with 'Missing credentials in config'

### ISSUE THREAD

**Issue by everett1992** [aws/aws-sdk-js#4417]
### Describe the bug

When a client's credential provider throws an error aws-sdk replaces the error's message with 'Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1'. The original message is available under `originalError` but that is not always logged, or may be logged as `[object Object]`.

https://github.com/aws/aws-sdk-js/blob/master/lib/event_listeners.js#L113-L118

### Expected Behavior

I expect the original error's message to be preserved. Credentials are not undefined, they are not missing, the provider threw an error.

### Current Behavior

```
> const aws = require('aws-sdk')
> await new aws.STS({credentials: new aws.SharedIniFileCredentials({ profile: 'not-a-profile' })}).getCallerIdentity().promise()

> Error [CredentialsError]: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at SharedIniFileCredentials.load (/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:103:11)
    at SharedIniFileCredentials.coalesceRefresh (/node_modules/aws-sdk/lib/credentials.js:205:12)
    at SharedIniFileCredentials.refresh (/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:170:10)
    at SharedIniFileCredentials.get (/node_modules/aws-sdk/lib/credentials.js:122:12)
    at getAsyncCredentials (/node_modules/aws-sdk/lib/config.js:408:24)
    at Config.getCredentials (/node_modules/aws-sdk/lib/config.js:428:9)
    at Request.VALIDATE_CREDENTIALS (/node_modules/aws-sdk/lib/event_listeners.js:111:28)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/node_modules/aws-sdk/lib/request.js:686:14) {
  code: 'CredentialsError',
  time: 2023-05-09T22:16:53.295Z,
  originalError: {
    message: 'Could not load credentials from SharedIniFileCredentials',
    code: 'CredentialsError',
    time: 2023-05-09T22:16:53.295Z,
    originalError: {
      message: 'Profile not-a-profile not found',
      code: 'SharedIniFileCredentialsProviderFailure',
      time: 2023-05-09T22:16:53.294Z
    }
  }
}
```

### Reproduction Steps

See current behavior

### Possible Solution

Keep the error message, or add the original error message to the 'Missing credentials' text.
```
        req.service.config.getCredentials(function(err) {
          if (err) {
            req.response.error = AWS.util.error(err,
              {
                code: 'CredentialsError',
                message: err.message ?? 'Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1'
              }
            );
          }
          done();
        });
```

### SDK version used

2.1368.0

### Environment details (OS name and version, etc.)

Ubuntu / Not relevent

**Comment by RanVaknin** [comment]
Hi @everett1992 ,

The errors should be available in originalError, if it returns [Object] it means that the error is getting truncated because thats the default behavior of JS. 

For example:

```console
$ const nestedObj = {one: {two: {three: { four: {}}}}};
undefined
$ console.log(nestedObj);
{ one: { two: { three: [Object] } } }
undefined
$ JSON.stringify(nestedObj);
'{"one":{"two":{"three":{"four":{}}}}}'
```

The solution is to use JSON stringify to display the entire error trace.

You can argue that we can surface all the errors on the same level, but since JS SDK v2 is going into maintenance mode we are shifting focus onto enhancing v3 instead.

Thanks,
Ran~

**Comment by everett1992** [comment]
In my case the credential-provider I've implemented is used in someone else's code and when aws-sdk hides my error under originalError their code doesn't use JSON.stringify. 

There are so many logging libraries that do not print all members of an error (include aws lambda), I don't think your suggestion that error catcher's should use JSON.stringify to print errors.

Can you explain how `Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1` is a correct or relevant error message? The client _is not_ missing credentials in config, the error is throw no matter if AWS_CONFIG_FILE is not set, or AWS_SDK_LOAD_CONFIG is set to 1. The message doesn't add any value
