### ISSUE TITLE
CodeBuild client ignores "environmentVariablesOverride" values

### ISSUE THREAD

**Issue by NicholasValiente** [aws/aws-sdk-js#4418]
### Describe the bug

When calling `CodeBuildClient.send` with a `StartBuildCommand` or calling `CodeBuild.startBuild` with a value for `environmentVariablesOverride` set the build is triggered without the values of `environmentVariablesOverride`.[](url)

### Expected Behavior

Given a `StartBuildCommand` is sent
When the command contains a value for `environmentVariablesOverride`
Then the triggered CodeBuild should use the environment variables specified in the `environmentVariablesOverride`

Given `startBuild` is run 
When the input contains a value for `environmentVariablesOverride`
Then the triggered CodeBuild should use the environment variables specified in the `environmentVariablesOverride`

### Current Behavior

Codebuild is triggered with the last successfully ran values for the environment variables, instead of the ones specified by the `environmentVariablesOverride` value

### Reproduction Steps

1. Create a codebuild pipeline with the below definition and the environment variable `TARGET_REGION = us-east-1` 
``` yaml
version: 0.2

env:
  shell: bash
phases:
  build:
    on-failure: ABORT
    commands:
      - echo $TARGET_REGION
```
2.  Create a Node 18 Lambda that runs the following code to trigger the above CodeBuild pipeline
```javascript
const {
  CodeBuildClient,
  StartBuildCommand,
} = require("@aws-sdk/client-codebuild");
const codeBuild = new CodeBuildClient();

const handler = async (event) => {
  const projectName = "code-build-project-name";
  const environmentVariables = [
    { name: "TARGET_REGION", value: "ap-southeast-2" },
  ];

  const params = {
    environmentVariablesOverride: environmentVariables,
    projectName,
  };

  const response = await codeBuild.send(new StartBuildCommand(params));
  console.log(JSON.stringify(response, null, 2));
  return response;
};

module.exports = {
  handler,
};

```
3. Trigger the lambda
4. Check the CodeBuild response and find that the `environmentVariablesOverride` values were ignored
5. Check the latest builds for the project in CodeBuild and find that both use the last successful value instead of the passed values 

### SDK version used

@aws-sdk/client-codebuild@3.329.0

### Environment details (OS name and version, etc.)

AWS Lambda, Node 18

**Comment by RanVaknin** [comment]
HI @NicholasValiente ,

Using your code and the buildspec.yml you provided, I was able to create a pipeline, build it, and build it again with overridden environment variables using the StartBuildCommand from a local environment (not lambda):

Build result without env variable override:
```json
{
  "$metadata": {
    "httpStatusCode": 200,
    "requestId": "REDACTED",
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "build": {
    "arn": "arn:aws:codebuild:us-east-1:REDACTED:build/my-project:REDACTED",
    "artifacts": {
      "encryptionDisabled": false,
      "location": "arn:aws:s3:::REDACTED/my-project"
    },
    "buildComplete": false,
    "buildNumber": 5,
    "buildStatus": "IN_PROGRESS",
    "cache": {
      "type": "NO_CACHE"
    },
    "currentPhase": "QUEUED",
    "encryptionKey": "arn:aws:kms:us-east-1:REDACTED:alias/aws/s3",
    "environment": {
      "computeType": "BUILD_GENERAL1_SMALL",
      "environmentVariables": [],
      "image": "aws/codebuild/standard:5.0",
      "imagePullCredentialsType": "CODEBUILD",
      "privilegedMode": false,
      "type": "LINUX_CONTAINER"
    },
    "id": "REDACTED",
    "initiator": "REDACTED",
    "logs": {
      "cloudWatchLogsArn": "REDACTED",
      "deepLink": "REDACTED"
    },
    "phases": [
      {
        "durationInSeconds": 0,
        "endTime": "2023-06-05T06:21:00.656Z",
        "phaseStatus": "SUCCEEDED",
        "phaseType": "SUBMITTED",
        "startTime": "2023-06-05T06:21:00.600Z"
      },
      {
        "phaseType": "QUEUED",
        "startTime": "2023-06-05T06:21:00.656Z"
      }
    ],
    "projectName": "my-project",
    "queuedTimeoutInMinutes": 480,
    "serviceRole": "REDACTED",
    "source": {
      "insecureSsl": false,
      "location": "REDACTED",
      "reportBuildStatus": false,
      "type": "GITHUB"
    },
    "startTime": "2023-06-05T06:21:00.600Z",
    "timeoutInMinutes": 60
  }
}
```

Refactored code with trycatch:
```js
import { CodeBuildClient,StartBuildCommand } from "@aws-sdk/client-codebuild"

const client = new CodeBuildClient();

const projectName = "my-project";
const environmentVariables = [
  { name: "TARGET_REGION", value: "us-east-2" },
];

const params = {
  environmentVariablesOverride: environmentVariables,
  projectName,
};

try {
  const response = await client.send(new StartBuildCommand(params));
  console.log(JSON.stringify(response, null, 2));
} catch (error) {
  console.log(error)
}
```

Build result with env variable override:
```json
...
"environment": {
      "computeType": "BUILD_GENERAL1_SMALL",
      "environmentVariables": [
        {
          "name": "TARGET_REGION",
          "type": "PLAINTEXT",
          "value": "us-east-2"
        }
      ],
      "image": "aws/codebuild/standard:5.0",
      "imagePullCredentialsType": "CODEBUILD",
      "privilegedMode": false,
      "type": "LINUX_CONTAINER"
    },
...
```

___
>4. Check the CodeBuild response and find that the environmentVariablesOverride values were ignored

Does your lambda have an IAM role with a `codebuild:StartBuild` allow statement in it's policy? If you were to run your code from a local Node.js application, does it trigger the same behavior?
Did you check the logs associated with your lambda? You aren't explicitly handling error with something like a try catch block, so errors might not be visible from the lambda execution window in the console. 
The logs might reveal if and why the executions fail.

>5. Check the latest builds for the project in CodeBuild and find that both use the last successful value instead of the passed values

I'm not sure what you mean by this. If the builds are not successful the overrides wont take affect.

Can you please elaborate a bit?

Thanks,
Ran~

**Comment by NicholasValiente** [comment]
Hi @RanVaknin  to go over your questions


> Does your lambda have an IAM role with a codebuild:StartBuild allow statement in it's policy? 

yes it does, here is an excerpt from the IAM role that the lambda uses 
```yaml
 Effect: Allow
        Action:
          - codebuild:BatchGetBuilds
          - codebuild:BatchGetProjects
          - codebuild:CreateProject
          - codebuild:DeleteProject
          - codebuild:StartBuild

```

> Did you check the logs associated with your lambda? 

Yes we did, we dont see any errors in the logs, and i tried printing the value of `params.environmentVariablesOverride` directly before the call which shows the call is correct
```json
[
  {
    "name": "TARGET_REGION",
    "value": "us-east-2"
  }
]

```
 but this is what we get as output currently before adding the try/catch
```json
{
  "$metadata": {
    "httpStatusCode": 200,
    "requestId": "REDACTED",
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "build": {
    "arn": "arn:aws:codebuild:us-east-1:REDACTED:build/REDACTED",
    "artifacts": {
      "location": ""
    },
    "buildComplete": false,
    "buildNumber": 6,
    "buildStatus": "IN_PROGRESS",
    "cache": {
      "type": "NO_CACHE"
    },
    "currentPhase": "QUEUED",
    "encryptionKey": "arn:aws:kms:us-east-1:REDACTED:REDACTED",
    "environment": {
      "computeType": "BUILD_GENERAL1_MEDIUM",
      "environmentVariables": [
        {
          "name": "TARGET_REGION",
          "type": "PLAINTEXT",
          "value": "us-east-1"
        }
      ],
      "image": "aws/codebuild/standard:5.0",
      "imagePullCredentialsType": "CODEBUILD",
      "privilegedMode": false,
      "type": "LINUX_CONTAINER"
    },
    "id": "REDACTED",
    "initiator": "REDACTED-lambdaRole/REDACTED",
    "logs": {
      "cloudWatchLogsArn": "arn:aws:logs:us-east-1:REDACTED:log-group:null:log-stream:null",
      "deepLink": "REDACTED"
    },
    "phases": [
      {
        "durationInSeconds": 0,
        "endTime": "2023-06-06T01:51:17.520Z",
        "phaseStatus": "SUCCEEDED",
        "phaseType": "SUBMITTED",
        "startTime": "2023-06-06T01:51:17.457Z"
      },
      {
        "phaseType": "QUEUED",
        "startTime": "2023-06-06T01:51:17.520Z"
      }
    ],
    "projectName": "service-sample-repo-deploy-branch",
    "queuedTimeoutInMinutes": 480,
    "serviceRole": "REDACTED",
    "source": {
      "auth": {
        "type": "OAUTH"
      },
      "buildspec": "REDACTED",
      "insecureSsl": false,
      "location": "REDACTED",
      "reportBuildStatus": false,
      "type": "GITHUB"
    },
    "sourceVersion": "refs/heads/main",
    "startTime": "2023-06-06T01:51:17.457Z",
    "timeoutInMinutes": 60
  }
}
```

>You aren't explicitly handling error with something like a try catch block, so errors might not be visible from the lambda execution window in the console. 

after adding the try/catch block like you showed above the output is identical to above apart from timestamps and build number as we have a try/catch around the call to our function that i cut down for the example code. 

> If you were to run your code from a local Node.js application, does it trigger the same behavior?

triggering the build locally does work as expected for the env override
![image](https://github.com/aws/aws-sdk-js/assets/89753679/cb1a02dd-7e31-4789-b122-67b5e234188d)
```json
...
"environment": {
      "computeType": "BUILD_GENERAL1_SMALL",
      "environmentVariables": [
        {
          "name": "TARGET_REGION",
          "type": "PLAINTEXT",
          "value": "us-east-2"
        }
      ],
      "image": "aws/codebuild/standard:7.0",
      "imagePullCredentialsType": "CODEBUILD",
      "privilegedMode": false,
      "type": "LINUX_CONTAINER"
    },
...
```

> > 5. Check the latest builds for the project in CodeBuild and find that both use the last successful value instead of the passed values
> 
> I'm not sure what you mean by this. If the builds are not successful the overrides wont take affect.

what is happening is that we have previous builds that were triggered from our lambda on AWS SDK v2 with an environment variable override set (e.g. `TARGET_REGION=us-east-1`) from that trigger. 

After upgrading our lamdba to AWS SDK v3 we then go and trigger a new build from the lambda to a different target region (e.g.`TARGET_REGION=us-east-2`)

When we do that the expected environment variable override is not being used, it is instead using the last builds value instead 

e.g we set `TARGET_REGION=us-east-2` in the SDK V3 lambda triggered build, but it is instead running with `TARGET_REGION=us-east-1` from the last SDK V2 build when we check the build in the console and check the logs

**Comment by RanVaknin** [comment]
HI @NicholasValiente ,

Thanks for the information. 

>triggering the build locally does work as expected for the env override

This is interesting. I'm not entirely sure why you are seeing a different behavior on lambda. I ran this code on Lambda as well and had no issues overriding the env variable.

>After upgrading our lamdba to AWS SDK v3 we then go and trigger a new build from the lambda to a different target region (e.g.TARGET_REGION=us-east-2)

>When we do that the expected environment variable override is not being used, it is instead using the last builds value instead

Not sure how your trigger is configured. But is there a chance you are triggering an older version of your lambda / a different lambda using v2 (which uses the previously use override)?  
Steps I would take to try and debug this further:

1. Make sure that your latest changes on your lambda are **saved** and **deployed** before triggering the Lambda. 
If you made changes without saving and deploying it, triggering the lambda would trigger _**The last deployed version of your lambda**_. Which sounds like the behavior you are reporting.

Unstaged changes:
- ![image](https://github.com/aws/aws-sdk-js/assets/50976344/cedb658e-aa33-4b76-ba25-ace2c8c1c680)

You can do that manually from the console by hitting Cmd + S, which will indicate that your changes are not deployed:
- ![image](https://github.com/aws/aws-sdk-js/assets/50976344/92b049dc-e9b6-44ee-8640-8160b4f88d8e)

Then deploy by clicking on "Deploy". This must be done every time you update your lambda function:
- ![image](https://github.com/aws/aws-sdk-js/assets/50976344/d32298f8-2a50-4162-ba64-27b78bf18561)
___

2. If you have 2 separate lambdas: older v2, and a new v3 lambda, your trigger might be configured to invoke the v2 lambda instead of the new lambda. You can click on "Test" button from the Lambda console to manually trigger the v3 lambda and check the execution results.
____

3. Add a custom log middleware step to check the outbound request. This would be a good way to see which requests are actually going out:

```js
// imports
//... more code ...
const client = new CodeBuildClient({
  region: "us-east-1",
})

client.middlewareStack.add(next => args => {
  console.log('before sign: ' , args.request);
  return next(args);
}, {step: 'build'})

const projectName = "my-project";
const environmentVariables = [
  { name: "TARGET_REGION", value: "us-east-2" },
];
// ... more code...
```

This should output the request:

```console
before sign:  HttpRequest {
  method: 'POST',
  hostname: 'codebuild.us-east-1.amazonaws.com',
  port: undefined,
  query: {},
  headers: {
    'content-type': 'application/x-amz-json-1.1',
    'x-amz-target': 'CodeBuild_20161006.StartBuild',
    'content-length': '106'
  },
  body: '{"environmentVariablesOverride":[{"name":"TARGET_REGION","value":"us-east-2"}],"projectName":"my-project"}',
  protocol: 'https:',
  path: '/'
}
```

Let me know how it goes.

Thanks,
Ran~

**Comment by NicholasValiente** [comment]
Hi @RanVaknin,

> 1. Make sure that your latest changes on your lambda are saved and deployed before triggering the Lambda.
...
> 2. If you have 2 separate lambdas: older v2, and a new v3 lambda, your trigger might be configured to invoke the v2 lambda instead of the new lambda.

we deploy our lambda via CloudFormation stacks through Serverless framework configured with x-ray tracing on, i can see on the latest version i deployed that it was triggered in X-ray
![image](https://github.com/aws/aws-sdk-js/assets/89753679/60bd5d5c-de58-4076-8f18-8c7ee3d2a4f8)

> 3.Add a custom log middleware step to check the outbound request. This would be a good way to see which requests are actually going out:

from the logs in the lambda i see that the existing log directly before the call shows the correct value, but it seems on the next line where the call to codebuild is made the debug logging you suggested shows that the wrong value is being sent
```javascript
codeBuild.middlewareStack.add(
  (next) => (args) => {
    logger.debug("before sign: ", args.request);
    return next(args);
  },
  { step: "build" }
);
logger.debug(JSON.stringify(params.environmentVariablesOverride, null, 2));
const codebuildResponse = await codeBuild.send(new StartBuildCommand(params));
logger.info(JSON.stringify(codebuildResponse, null, 2));

```

```
2023-06-07T00:07:09.658Z	REDACTED	INFO	[DEBUG] [
  {
    "name": "TARGET_REGION",
    "value": "us-east-2"
  }
]

2023-06-07T00:07:09.663Z	REDACTED	INFO	[DEBUG] before sign:  {
    method: 'POST',
    hostname: 'codebuild.us-east-1.amazonaws.com',
    port: undefined,
    query: {},
    headers: {
      'content-type': 'application/x-amz-json-1.1',
      'x-amz-target': 'CodeBuild_20161006.StartBuild',
      'content-length': '3447'
    },
    body: '{ "environmentVariablesOverride": [ { "name": "TARGET_REGION", "value": "us-east-1" }, ], "projectName": "REDACTED", "sourceVersion": "refs/heads/main" }',
    protocol: 'https:',
    path: '/'
  }
  
```

**Comment by NicholasValiente** [comment]
Hi @RanVaknin,

Our team had a meeting to go over why this could still be happening, and discovered the issue is on our end so i will be closing the ticket.

the short version of the issue is the code above is in a function that gets called in an async loop, we were modifying the `TARGET_REGION` value inside that async loop but didnt deep copy the array 🤦 
```javascript
return Promise.all(
  deploymentRegions.map(async (deploymentRegion) => {
    environmentVariables = environmentVariables.map((envVar) => {
      if (envVar.name === "TARGET_REGION") {
        envVar.value = deploymentRegion;
      }

      return envVar;
    });

    return startBuild(projectName, environmentVariables, gitVersion);
  })
);
```
The fix was to simply deep copy the array before making the modifications within the async loop
```javascript
return Promise.all(
  deploymentRegions.map(async (deploymentRegion) => {
    const environmentVariablesOverrides = structuredClone(
      environmentVariables
    ).map((envVar) => {
      if (envVar.name === "TARGET_REGION") {
        envVar.value = deploymentRegion;
      }

      return envVar;
    });

    return startBuild(projectName, environmentVariablesOverrides, gitVersion);
  })
);

```
We dont know how we never ran into this on SKD V2 as this part of the code didnt change, but we have fixed it now and determined that this behavior was not an SDK V3 bug but an bug in our code.


Thank you again for your help, it really helped us narrow down where things could be going wrong 👍
