### ISSUE TITLE
S3 upload / AWS.S3.ManagedUpload does not work when amount of data exceeds partSize

### ISSUE THREAD

**Issue by utzc** [aws/aws-sdk-js#442]
I am trying to use the new S3 ManagedUpload functionality to stream files to S3. However, when the amount of data in the stream exceeds the part size, only part of the file is written to S3. 

Given the following example:

```
var aws = require('aws-sdk');
var fs = require('fs');

var s3 = new aws.S3({accessKeyId: '...', secretAccessKey: '...'});
var stream = fs.createReadStream('file');
var params = {Bucket: 'mybucket', Key: 'file', Body: stream};

s3.upload(params, function () { 
    var params = {Bucket: 'mybucket', Key: 'file'};
    s3.headObject(params, function (err, data) {
        console.log(data['ContentLength']);
    });
});
```

If file is < 5mb, all data is uploaded. If the file is > 5mb and the file size is not a multiple of 5mb, only data from the last part is uploaded. If the file is a multiple of 5mb, no file is uploaded. So it seems when the amount of data exceeds the configured partSize, only the last part is actually uploaded.

I am using Node v0.10.32 and AWS SDK version 2.1.2.

**Comment by goozo** [comment]
I am getting this issue when I try to stream data to S3 ManagedUpload when the total size is unknown
