### ISSUE TITLE
AWS Cognito returning 400 Bad Request when authorizing identity pool

### ISSUE THREAD

**Issue by colt-netgain** [aws/aws-sdk-js#4420]
### Describe the bug

This has been working in our Salesforce frontend environment for the last month, however recent attempts to authenticate with a Cognito Identity Pool have been met with 400 errors, the exact response is:
`{"code":"BadRequest","message":"The server did not understand the operation that was requested.","type":"client"}`

The same code works when ran locally, however upon upload to Salesforce, the calls no longer go through. The code is being ran from a webpacked js bundle.

### Expected Behavior

Previously, these same calls were authenticating with Cognito without issue.

### Current Behavior

400 error `{"code":"BadRequest","message":"The server did not understand the operation that was requested.","type":"client"}`

### Reproduction Steps

The hosted code is being ran from a Salesforce sandbox environment. This is the pre-webpack code:
```js
const { fromCognitoIdentityPool } = require("@aws-sdk/credential-providers");
const { CognitoIdentityClient } = require("@aws-sdk/client-cognito-identity");
const {
  TextractClient,
  DetectDocumentTextCommand,
} = require("@aws-sdk/client-textract");

/**
 *
 * @param {UInt8Array} bytes an array of base64-encoded bytes for a document
 * @returns an object containing the AWS Textract response, null otherwise
 */
window.handleOCRTextract = async function (bytes) {
  // the current user that this function loads only has access to
  // aws textract full access, any other services will require
  // a new user to be created, or the current user to have their access
  // policy updated. aws iam & aws cognito can control this.
  const credentials = fromCognitoIdentityPool({
    client: new CognitoIdentityClient({ region: "us-east-1" }),
    identityPoolId: "us-east-1:REDACTED",
    clientConfig: {
      region: "us-east-1",
    },
  });
  console.log(credentials);

  const serviceConfiguration = {
    region: "us-east-1",
    credentials,
  };
  console.log(serviceConfiguration);

  const textract = new TextractClient(serviceConfiguration);

  const params = {
    Document: {
      Bytes: bytes,
    },
  };
  const command = new DetectDocumentTextCommand(params);
  try {
    const data = await textract.send(command);
    return data;
  } catch (err) {
    console.error(err);
  }
  return null;
};
```

### SDK version used

v3

### Environment details (OS name and version, etc.)

Macbook Pro Ventura 13.1

**Comment by RanVaknin** [comment]
Hi @colt-netgain ,

Since you are running this from a website context can you share the request you are sending? 
Host, endpoint, headers any information on the request that can help us see if it is being re-written somehow.


**Side note**: I had to redact the poolId you shared, in the future please scrub out any sensitive data from your code

**Comment by colt-netgain** [comment]
> Hi @colt-netgain ,
> 
> Since you are running this from a website context can you share the request you are sending? Host, endpoint, headers any information on the request that can help us see if it is being re-written somehow.
> 
> **Side note**: I had to redact the poolId you shared, in the future please scrub out any sensitive data from your code

Thank you for scrubbing the pool ID, my apologies on not obfuscating that originally.

The requests can be seen below. Note that we tried changing regions from us-east-1 to us-east-2 and that did not solve the issue.

<img width="1145" alt="Screenshot 2023-05-13 162601" src="https://github.com/aws/aws-sdk-js/assets/126120099/a674c675-f1e6-4b1c-9a53-7a703368bfa2">
<img width="714" alt="Screenshot 2023-05-13 162615" src="https://github.com/aws/aws-sdk-js/assets/126120099/f82b7a45-88a3-4485-a26c-8f4ead78cdcf">

These requests are being made from a Salesforce LWC sandbox environment. Previously, they worked fine. After about a month is when these errors came through. We are using an unauthenticated Identity Pool ID for service authorization.

**Comment by RanVaknin** [comment]
Hi @colt-netgain 

> These requests are being made from a Salesforce LWC sandbox environment. 

I'm not too familiar with Salesforce to be able to reproduce this on my end, so I'm looking out for general clues in your request structure to see if there are any discrepancies between what a local execution might look like vs the Salesforce environment.

I'm not sure if this is related, but I noticed that the request is going out to `cognito-identity.us-east-2.amazonaws.com`, whereas in your code the region is configured as us-east-1.  Is it being overwritten somewhere?

> After about a month is when these errors came through.

Did you update the SDK version within that time? If you think this is due to a recent update that caused this, you can try installing an older version for example: `npm i @aws-sdk/credential-providers@3.xxx.0`

Thanks,
Ran~

**Comment by colt-netgain** [comment]
Thanks for the reply. 

>  I'm looking out for general clues in your request structure to see if there are any discrepancies

That is what is bugging us the most on this. The code that I originally shared is the same code being used on both our local development systems for testing (placing the webpack'd code into a local index.html and loading it from there) and the Salesforce frontend, which just involves uploading the bundle to a Salesforce sandbox.

> whereas in your code the region is configured as us-east-1. Is it being overwritten somewhere?

This was just a small change I made in the hopes that maybe us-east-1 was the source of the issue. This did not solve it, both regions are affected. I also did not update the SDK, but I'll see if that will maybe fix the issue. I can also share my AWS configuration, if needed. [This is the "Getting Started" guide that I followed in creating an Identity Pool.](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/getting-started-browser.html)

**Comment by colt-netgain** [comment]
Thank you for your help @RanVaknin. Are you able to open a ticket on our behalf? That would be much appreciated as we don't currently have an assigned technical account manager for our organization. I have a copy of the `x-amzn-requestid` ready if needed. 
Best,
Colton

**Comment by RanVaknin** [comment]
Hi @colt-netgain ,

Yes, please share the request ID with me and I can upstream you request to the service team. 

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @colt-netgain ,

I still haven't heard back about this. I highly recommend opening a support ticket in your AWS console. 
The support ops team is very capable and they will be able to closely monitor and get answers from the dynamo team.
If you need to reference my ticket please provide the support person this id `P88754518`.

Thanks,
Ran~

**Comment by colt-netgain** [comment]
Thank you for your help with this, @RanVaknin. It looks like the issue is actually gone now, but we've elevated our support account to a Business tier and will go ahead and open a ticket to make sure we understand what happened and that this issue doesn't arise in the future in a production version. I'll close this out.

Thank you,
Colton
