### ISSUE TITLE
Issue with special characters in file name

### ISSUE THREAD

**Issue by csk14** [aws/aws-sdk-js#4434]
### Describe the bug

I have a file in aws ftps bucket with name `22-1524_Winter! Loeb. 2nd* Floor'-RCP-(123).rcs` (as per aws object keys [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html#object-key-guidelines), name contains all safe/allowed special characters `!_.*'()`.

I have a lambda function which uses that file, in function code, I have below line which gives Forbidden error.
`await s3.headObject({Key: sourceKey, Bucket: sourceBucket}).promise();`

But if I rename the file to `22-1524-Winter Loeb 2nd Floor-RCP-123.rcs` (removed safe special characters `!_.*'()`), it works with no error. So forbidden error does not seems right here, as I am able to access the file.

**Note** Object key (i.e., file path/name) is encoded using encodeURIComponent

Wondering if it related to the aws-sdk version `2.896.0` which I am using? Not sure.

**Error:**
Forbidden: null
    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/services/s3.js:691:35)
    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
...

### Expected Behavior

Retrieve the specified file from s3.

### Current Behavior

Forbidden: null
    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/services/s3.js:691:35)
    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'Forbidden',
  region: null,
  time: 2023-05-30T08:50:47.173Z,
  requestId: 'XNRC1HSBYMXGDS84',
  extendedRequestId: 'dx6rxT31A7AbcIjeFNeBKBttllN6nmBhVwmC4StWY0vlqPdVrIIpy7J8lvcAGLG8iwNUrJxvHWg=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 85.80941110572269
}

### Reproduction Steps

await s3.headObject({
             Bucket: '...',
             Key: 'zzzz%2F7187%2F3D%20Point%20Clouds%2FAL01%20-%2073761%20-%20ASD%20SKY%20-%20Winter%20Loeb%202nd%20Floor-RCP%20Support%2F22-1524_Winter!%20Loeb.%202nd*%20Floor'-RCP-(123).rcs'
}).promise()

encoded source key:
zzzz%2F7187%2F3D%20Point%20Clouds%2FAL01%20-%2073761%20-%20ASD%20SKY%20-%20Winter%20Loeb%202nd%20Floor-RCP%20Support%2F22-1524_Winter!%20Loeb.%202nd*%20Floor'-RCP-(123).rcs

unencoded source key:
zzzz/7187/3D Point Clouds/AL01 - 73761 - ASD SKY - Winter Loeb 2nd Floor-RCP Support/22-1524_Winter! Loeb. 2nd* Floor'-RCP-(123).rcs

### SDK version used

2.896.0

### Environment details (OS name and version, etc.)

AWS cloud, Javascript

**Comment by RanVaknin** [comment]
Hi @csk14 ,

I'm not sure why you are running into issues with this. A few things that are unclear from your issue is:
Which version of aws-sdk are you using? You mentioned `2.896.0` but we are on  `aws-sdk@2.1387.0` so Im confused about that. 

The error you are received is a 403 which in most cases has to do with permissions. I'm not sure if you are error handling, because the code you have provided snippet is missing a lot of information. Maybe your Lambda doesn't have permissions to call s3?

Using the same object name Im successfully able to head object:

```js
var AWS = require('aws-sdk');


var s3 = new AWS.S3({
    region: 'us-east-1'
});

var params = {
  Bucket: "foo-bucket", 
  Key: "zzzz/7187/3D Point Clouds/AL01 - 73761 - ASD SKY - Winter Loeb 2nd Floor-RCP Support/22-1524_Winter! Loeb. 2nd* Floor'-RCP-(123).rcs"
};

s3.headObject(params, function(err, data) {
  if (err) {
    console.log("Error: ", err);
  } else {
    console.log("Metadata: ", data);
  }
});
```

```console
$ node sample.js
Metadata:  {
  AcceptRanges: 'bytes',
  LastModified: 2023-05-30T20:37:59.000Z,
  ContentLength: 0,
  ETag: '"REDACTED"',
  ContentType: 'binary/octet-stream',
  ServerSideEncryption: 'AES256',
  Metadata: {}
}
```

I would check your Lambda's permissions to make sure it is allowed to do a `HeadObject` against s3. 

Thanks,
Ran~

**Comment by csk14** [comment]
@RanVaknin thanks for your response. I checked on version, our AWS instance is on 2.1229.0 version and also issue with forbidden error is resolved. Your code snippet helped me in debugging the lambda function.

**Comment by RanVaknin** [comment]
No problem, glad to hear it worked out.
