### ISSUE TITLE
socket.setKeepAlive is not called, which could prevent timeouts during long requests

### ISSUE THREAD

**Issue by kuhe** [aws/aws-sdk-js#4439]
### Describe the bug

When making very long duration requests, such as a lambda invoke that takes over 5 minutes to complete, the SDK may eventually timeout even if the response completes because the socket is not kept alive.

A current workaround seems to have fixed this issue for an internal customer, so we should add a `socket.setKeepAlive` call to the Node.js HTTP request. 

```js
var AWS = require('aws-sdk');

var handle = AWS.NodeHttpClient.prototype.handleRequest
if (!handle.override) {
  AWS.NodeHttpClient.prototype.handleRequest = function () {
    var ret = handle.apply(this, arguments);
    ret.on("socket", function (socket) {
      socket.setKeepAlive(true, 4 * 60 * 1000);
    });
    return ret;
  }
  AWS.NodeHttpClient.prototype.handleRequest.override = true;
}
```

### Expected Behavior

long request >5 min completes

### Current Behavior

long request >5 min reports a timeout even if the server completes the request successfully

### Reproduction Steps

invoke a lambda transaction that takes a long time, 5-15 minutes.

### Possible Solution

add `socket.setKeepAlive(true, xxx)` somewhere in the request creation process

### SDK version used

current

### Environment details (OS name and version, etc.)

EC2 to Lambda

**Comment by yenfryherrerafeliz** [comment]
A possible workaround would be:

```js
import https from "https";

const keepAliveMsecs = 5 * 1000;
const tempHttpsRequestFn = https.request;
https.request = (options, callback) => {
    const clientRequest = tempHttpsRequestFn(options, callback);
    clientRequest.once('socket', (socket) => {
        console.log(keepAliveMsecs)
        socket.setKeepAlive(true, keepAliveMsecs || 0);
    });

    return clientRequest;
};
```

A quick example would be:

```js
import AWS from "aws-sdk";
import https from "https";

const keepAliveMsecs = 5 * 1000;
const tempHttpsRequestFn = https.request;
https.request = (options, callback) => {
    const clientRequest = tempHttpsRequestFn(options, callback);
    clientRequest.once('socket', (socket) => {
        socket.setKeepAlive(true, keepAliveMsecs || 0);
    });

    return clientRequest;
};
const client = new AWS.Lambda({
    region: 'us-east-2'
});
const response = await client.invoke({
    FunctionName: "sleep",
    Payload: JSON.stringify({
        sleep: 100
    })
}).promise();
console.log(response)

```

**Comment by aBurmeseDev** [comment]
The team has determined that they will not be addressing this issue at this time, closing it.
