### ISSUE TITLE
No Such host is known

### ISSUE THREAD

**Issue by PuneetKumar-02** [aws/aws-sdk-js#4442]
### Describe the bug

While reading file content from S3 bucket using .Net SDK, most of the time we are getting the data but frequently we are getting "No Such host is known" error. Due to this, many calls are getting failed daily. Our code has 'polly retry' mechanism which calls/retries to fetch it from S3( in case call gets failed) due to which our users are facing latency. For example,  for one request we got the error "No Such host is known" even after retrying the same request for three times and when the same request was made after some time, we got successful response in milli seconds. Could you please help to resolve this issue ?

SDK version - 3.7.2

Code snippet:
AmazonS3 _s3Client = new AmazonS3Client(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, RegionEndpoint.GetBySystemName(AWS_REGION));
GetObjectRequest request = new GetObjectRequest
                {
                    BucketName = AWS_BUCKETNAME,
                    Key = fileName
                };
GetObjectResponse response = await _s3Client.GetObjectAsync(request);
using (StreamReader reader = new StreamReader(response.ResponseStream))
                {
                    responseObject = reader.ReadToEnd(); 
                }

### Expected Behavior

Should able to read file content from S3 bucket using .Net SDK without any issues

### Current Behavior

Frequently we are getting "No such host is known" while reading data from S3 file.

### Reproduction Steps

Completely sporadic issue, no specific steps to replicate

### SDK version used

7.2.2

### Environment details (OS name and version, etc.)

.Net core 3.1

**Comment by RanVaknin** [comment]
Hi @PuneetKumar-02 ,

This is the Javascript SDK repo. Please open this issue in https://github.com/aws/aws-sdk-net

Thanks,
Ran~
