### ISSUE TITLE
Note about sdk entering maintainance mode when launching server

### ISSUE THREAD

**Issue by mogulcoder26** [aws/aws-sdk-js#4445]
### Describe the bug

Everytime i try to start my node server,I get this note

```bash 
(node:19348) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

### Expected Behavior

 `NOTE`  shouldn't be getting displayed everytime server is started

### Current Behavior

 `NOTE`  is getting displayed everytime server is started

### Reproduction Steps

install the package via npm/yarn and require it in a module,eg: `app.js`

for yarn :
```bash 
yarn add aws-sdk/clients/s3
```

for npm : 

```bash 
npm i  aws-sdk/clients/s3
```

Run the server via :
` node app`

### Possible Solution

Supressing the note from popping up again.

### SDK version used

2.1383.0

### Environment details (OS name and version, etc.)

Windows 10 Pro

**Comment by RanVaknin** [comment]
Hi @mogulcoder26,

This is not a bug, it's intentional to encourage customers to migrate to v3.

You can suppress this message by setting this env variable before running your applicatino: `AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE=1 node app.js`

Thanks,
Ran~
