### ISSUE TITLE
Wrong type for lambda.invoke callback's err argument

### ISSUE THREAD

**Issue by surdu** [aws/aws-sdk-js#4446]
### Describe the bug

Hello,

Am I missing something or the [error argument for the invoke's callback](https://github.com/aws/aws-sdk-js/blob/master/clients/lambda.d.ts#L284-L288) should be optional?

### Expected Behavior

The type for `err` to be `AWSError | undefined`

### Current Behavior

The type for `err` is `AWSError`

### Reproduction Steps

When mocking the invoke function for tests, the type of the callback's error argument will force me to pass an error, when I don't need to.

### SDK version used

master branch

### Environment details (OS name and version, etc.)

N/A

**Comment by RanVaknin** [comment]
Hi @surdu ,

Instead of using callbacks where you are forced to pass in (err, data), you can use [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function).

This should circumvent the need to supply AWSError. 

Thanks,
Ran~

**Comment by surdu** [comment]
Thank you for the alternative, but the issue still stands: the err argument should be optional

**Comment by RanVaknin** [comment]
Hi @surdu , 

We could support this. I'm going to mark this as a feature request. 

Thanks,
Ran

**Comment by kellertk** [comment]
Hello, this behavior is different in v3 of the SDK. Please migrate to v3, as we are not currently implementing new features in v2.
