### ISSUE TITLE
AWS.NodeHttpClient use undefined httpAgent instead of default one

### ISSUE THREAD

**Issue by pivstone** [aws/aws-sdk-js#4452]
### Describe the bug

when a user pass agent: undefined to a client (us DynamoDB as example).

```ts
import AWS from 'aws-sdk';
const options = {
    apiVersion: '2012-10-08',
    httpOptions: {
      agent: undefined
    },
  }
new AWS.DynamoDB.DocumentClient(options);
```
AWS.NodeHttpClient set a default agent in here. 
https://github.com/aws/aws-sdk-js/blob/ffc003b6b9b8ac14b2d1039430d8b11cc8e965fb/lib/http/node.js#L35-L39

but the in the next line `options.agent` is updated to `undefined` by this line.
https://github.com/aws/aws-sdk-js/blob/ffc003b6b9b8ac14b2d1039430d8b11cc8e965fb/lib/http/node.js#L41

Because the httpOptions.agent is undefined.

### Expected Behavior

The http agent shouldn't be undefined.

### Current Behavior

The http agent is undefined.

### Reproduction Steps

as the description

### Possible Solution

```
AWS.util.update(options, httpOptions);
```
should be executed before assign the default http agent instance.

A suggest fix: https://github.com/aws/aws-sdk-js/pull/4453

### SDK version used

2.1374.0

### Environment details (OS name and version, etc.)

Lambda/NodeJs 16

**Comment by kuhe** [comment]
What is the scenario where you pass `undefined` to the agent?

**Comment by pivstone** [comment]
> What is the scenario where you pass `undefined` to the agent?

We have an internal library dynamodb client for all our AWS Lambda, something like this.

```ts
type BaseOptions = {
  maxRetries?: number;
  timeoutMs?: number;
  httpsAgent?: httpsAgent;
};

function buildOption(options: BaseOptions) {
  return {
    apiVersion: '2012-10-08',
    convertEmptyValues: true,
    maxRetries: options.maxRetries ?? 3,
    httpOptions: {
      agent: options.httpsAgent ?? undefined,
      timeout: options.timeoutMs ?? 3000,
    },
  };
}

new AWS.DynamoDB.DocumentClient(buildOption(options));
```

we added the `httpOptions. agent` as the an optional parameter, because the sdk accept an undefined, so we think it's fine to use undefined as default value, then we found the latency of calling dynamodb increased from few ms to 22ms.

**Comment by RanVaknin** [comment]
PR merged. Closing.
