### ISSUE TITLE
Unable to make partiQL/executeStatement query work with Limit and ConsumedCapacity parameters

### ISSUE THREAD

**Issue by mazyvan** [aws/aws-sdk-js#4457]
### Describe the bug

My code:

```javascript
await dynamodb.executeStatement({
    Statement: statement,
    Limit: 10,
    ReturnConsumedCapacity: 'TOTAL',
    NextToken: nextToken,
}).promise();
```

Documentation suggest I should be able to set the `ConsumedCapacity` and `Limit` parameters in a `executeStatement()` operation but this does not work in reality. The https://partiql.org/ docs does not provide much info about such parameters tho.

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ExecuteStatement.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#executeStatement-property

### Expected Behavior

Either get the operation to work or change the documentation if options are not valid

### Current Behavior

```javascript
{
  "errorType": "MultipleValidationErrors",
  "errorMessage": "There were 2 validation errors:\n* UnexpectedParameter: Unexpected key 'Limit' found in params\n* UnexpectedParameter: Unexpected key 'ReturnConsumedCapacity' found in params"
}
```

### Reproduction Steps

Use my code as base to test this

### SDK version used

2.1404.0

### Environment details (OS name and version, etc.)

Lambda runtime, x86_64, Node.js 14.x

**Comment by RanVaknin** [comment]
Hi @mazyvan ,

I can't see a full code snippet, maybe you are using wrong imports or wrong client?

Here is my working code:

```js
const AWS = require("aws-sdk");
AWS.config.update({ region: "us-east-1" });

const dynamodb = new AWS.DynamoDB();

const tableName = "Coffees";

const params = {
  Statement: `INSERT INTO ${tableName} VALUE {'varietal': ?, 'profile': ?}`,
  Parameters: [
    { 'S': "arabica" },
    { 'S': "floral" }
  ],
  Limit:10,
  ReturnConsumedCapacity:"TOTAL",
};

async function executeStatement() {
  try {
    const data = await dynamodb.executeStatement(params).promise();
    console.log(data);
  } catch (err) {
    console.log(err, err.stack);
  }
}

executeStatement();
```

Response:

```js
{
  Items: [],
  ConsumedCapacity: { TableName: 'Coffees', CapacityUnits: 1 }
}
```

Thanks,
Ran~
