### ISSUE TITLE
adminInitiateAuth call is taking longer time to respond for first call

### ISSUE THREAD

**Issue by gokul-ilango** [aws/aws-sdk-js#4460]
### Describe the bug

cognitoidentityserviceprovider.adminInitiateAuth call is taking around 10 Seconds to respond for first time. The successive calls are getting resolved faster like in 2 Seconds.

```javascript
function _loginUserToUserPool() {
    return new Promise (function (resolve, reject) {
        try {
            const params = {
                AuthFlow: 'ADMIN_USER_PASSWORD_AUTH',
                ClientId: '**************',
                UserPoolId: '**************',
                AuthParameters: {
                    USERNAME: 'xyz@email.com',
                    PASSWORD: 'password123'
                }
            };
            let startTime = new Date().getTime();
            cognitoidentityserviceprovider.adminInitiateAuth(params, function(error, data) {
                let diff = (new Date().getTime() - startTime) / 1000;
                console.log("time taken in seconds: "+ diff);
                if (error){
                    reject(error);
                }
                resolve(data)
            })
        }
        catch(err){
            reject(err);
        }
    })
}

_loginUserToUserPool();
```
Note: 
1. This issue is not present in sdk version 2.361.0
2. issue noticed after upgrading the version to 2.618.0
3. tried v3 version of the SDKs as well. same issue is noticed

### Expected Behavior

run the above code block and expected lesser latency

run 1: time taken in seconds: 1.717
run 2: time taken in seconds: 1.803

### Current Behavior

first call takes longer time to resolve

run 1: time taken in seconds: 10.341
run 2: time taken in seconds: 1.717
run 3: time taken in seconds: 1.803

### Reproduction Steps

please run the code block in description in Node Js env.

### SDK version used

2.1406.0

### Environment details (OS name and version, etc.)

Windows 10, Node 16.16.0, npm 6.14.15

**Comment by yenfryherrerafeliz** [comment]
Hi @gokul-ilango, sorry to hear about your issues. I think this behavior may be caused by the default credentials resolution, which will go over each credentials provider set in the default chain, and once the credentials are resolved the first time then, the subsequent calls will reuse those credentials and therefore you notice those calls take less than the first call. Could you please confirm which credentials provider are you using?, and would it be possible for you to explicit set it when instancing the client?. For example, lets assume your credentials are from environment then, you could the following:

```js
import AWS from "aws-sdk";

const client = new AWS.CognitoIdentityServiceProvider({
    credentials: new AWS.EnvironmentCredentials(""),
    region: "us-east-2"
});

``` 

Please let me know if this help!

Thanks!

**Comment by gokul-ilango** [comment]
even after using credentials parameter explicitly, the issue exists.

 set the following env variables  SET AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN
 created client with 'AWS' env prefix
```
 const client = new AWS.CognitoIdentityServiceProvider({
    credentials: new AWS.EnvironmentCredentials("AWS"),
    region: "us-east-2"
});
```
still seeing same issue,
First call : 12.749 seconds
Second call: 2.234 seconds

**Comment by zshzbh** [comment]
Hey @gokul-ilango ,

Thanks for the feedback! Can you try to setup config this way ? - 

```js

 AWS.config.region = 'us-east-2';
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({IdentityPoolId: '...'});

```

Please let us know if the issue persists. 

Thanks!
Maggie
