### ISSUE TITLE
Correctclockskew not working as expected

### ISSUE THREAD

**Issue by html5js3** [aws/aws-sdk-js#4462]
### Describe the bug

Hello,

I'm using aws-js-sdk v2.1252 and when I initialized my client, I already set `correctClockSkew` as true. However, I tried setting up my system clock to more than 5minutes off, and it still gave me the auth error. 

Can someone advise? Thanks!

### Expected Behavior

After setting `correctClockSkew` to true, and set system clock to more then 5 mins off, client should not get an auth error. 

### Current Behavior

Client still returns an error even after passing in `correctClockSkew`

### Reproduction Steps

1. Setup javascript library
2. Install `aws-sdk` v2.1252.0
3. Initialize sdk client with 
```
const GuardDutyClient =  new GuardDuty({
 correctClockSkew: true,
 region,
 credentials,
})
```

### SDK version used

2.1252

### Environment details (OS name and version, etc.)

macos

**Comment by RanVaknin** [comment]
Hi @html5js3 ,

What is the error you are seeing?

Additionally you can log the request using the following middleware:

```
GuardDutyClient.middlewareStack.add(next => args => {
	console.log('before sign: ' , args.request);
	return next(args);
}, {step: 'build'})
```

Please paste this here and redact any sensitive information like your secretID

Thanks,
Ran~
