### ISSUE TITLE
Having error called npm WARN deprecated querystring@0.2.0

### ISSUE THREAD

**Issue by nisalrenuja** [aws/aws-sdk-js#4466]
### Describe the bug

after adding aws-sdk npm package with deployed files to aws elastic beanstalk and it is failing to deploy the build. when it comes to checking logs 
got an error message as "Command /bin/su webapp -c npm --omit=dev install failed with error exit status 244. Stderr:npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead." as the error.
![image](https://github.com/aws/aws-sdk-js/assets/42801983/2197a0f6-ae34-41dc-bb52-ebe15af69c84)

### Expected Behavior

deploy the build to aws elastic beanstalk

### Current Behavior

failing to deploy aws elastic beanstalk

### Reproduction Steps

deploy code into the elastic beanstalk

### SDK version used

2.1419.0

### Environment details (OS name and version, etc.)

Node.js 16 running on 64bit Amazon Linux 2/5.8.0

**Comment by Seokhyeon315** [comment]
I have same warning message. Is it okay to ignore the message until aws fix it??

**Comment by yenfryherrerafeliz** [comment]
Hi @Seokhyeon315, I will add a needs-review label to this issue so we can analyze this further. 

Related: https://github.com/aws/aws-sdk-js/issues/4347, https://github.com/aws/aws-sdk-js/issues/4150

Thanks!

**Comment by RanVaknin** [comment]
Related:
https://github.com/aws/aws-sdk-js/issues/4150#issuecomment-1839677577

Closing.
