### ISSUE TITLE
CORS header ‘Access-Control-Allow-Origin’ missing with PUT request to Digital Ocean PreSigned URL

### ISSUE THREAD

**Issue by UmamaheshMaxwell** [aws/aws-sdk-js#4467]
### Describe the bug

I am using NodeJS to generate my PreSigned URL using digital ocean API (AWS SDK S3) and passing it to my frontend Angular App, which is making a PUT request to upload a file. There starts the problem it is throwing a CORS error as shown below from my browsers (Chrome and Firefox).

### Expected Behavior

Should upload the file successfully

### Current Behavior

Throws CORS Error
>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [https‍://dflowbucket.sfo3.digitaloceanspaces.com/images-1690112583187-pdf-test.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=DO00B48K2AUXRE8KXVWN%2F20230723%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230723T114303Z&X-Amz-Expires=900&X-Amz-Signature=66076aaa6dfe6b11eb9d29a37e124a97b0d0aa36baab97207d0edb697218ec58&X-Amz-SignedHeaders=host&x-amz-acl=public-read&x-id=PutObject](https‍://dflowbucket.sfo3.digitaloceanspaces.com/images-1690112583187-pdf-test.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=DO00B48K2AUXRE8KXVWN%2F20230723%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230723T114303Z&X-Amz-Expires=900&X-Amz-Signature=66076aaa6dfe6b11eb9d29a37e124a97b0d0aa36baab97207d0edb697218ec58&X-Amz-SignedHeaders=host&x-amz-acl=public-read&x-id=PutObject (*Reason: CORS header ‘Access-Control-Allow-Origin’ missing*). Status code: 400.

### Reproduction Steps

**NodeJS Code**

```
exports.getPreSignedUrl = async (fileName, contentType) => {

    const params = {
      Bucket: digitalocean.BUCKET_NAME,
      Key: fileName,
      ContentType: contentType,
      ACL: 'public-read'
    };
  
    return await getSignedUrl(s3Client, new PutObjectCommand(params), { expiresIn: 15 * 60 });
}
```

```
router.post("/getPreSignedUrl", async (req, res) => {
    const {fileName, contentType} = req.body
    const signedUrl = await digitalocean.getPreSignedUrl(fileName,contentType)
    res.status(200).send({ signedUrl });
});
```

**Angular Code**

```
  onSave() {
    if (this.isLoading) { return }
    if (!this.files.length) {
      this._snackBar.open("You need to choose file first!", 'Close', {
        duration: 2000,
      });
      return;
    }
    const file = this.files[0];
    const contentType = file.type;
    const fileName = 'images-' + `${new Date().getTime()}-${file.name.toLowerCase()}`
    this.isLoading = true;
    this.itemService
      .getPreSignedUrl({ fileName, contentType : '*' })
      .subscribe((res: { signedUrl: string }) => {
        const signedUrl = res.signedUrl
        this.http.put(signedUrl, file) // my PUT request for pre-signed URL
          .subscribe((output) => {
            this.itemService
              .saveTechLink({ fileName }, this.data.itemId)
              .pipe(take(1))
              .subscribe((res: { sharedLink: string }) => {
                this.isLoading = false;
                this.dialogRef.close(res.sharedLink)
              })
          },
            (error) => {
              console.error('Error uploading file:', error);
            }
          );
      })
  }
```

### Additional Information/Context

This works with postman or CURL but not with browser

### SDK version used

    "@aws-sdk/client-s3": "^3.338.0",     "@aws-sdk/s3-request-presigner": "^3.374.0"

### Environment details (OS name and version, etc.)

Windows 11

**Comment by RanVaknin** [comment]
Hi @UmamaheshMaxwell ,

The issue you are describing sounds like a classic CORS configuration issue. I'm not familiar with Digital Ocean, but in AWS's S3 you'll have to configure your bucket with a CORS policy that allows PUT request from your URL.

Here is an article I found online that might be helpful https://docs.digitalocean.com/products/spaces/how-to/configure-cors/

Since AWS does not offer support for 3rd party tools like Digital Ocean I'm going to close this thread. If this issue persists and you need additional support, I suggest you reach out to Digital Ocean's support operations.

Thanks,
Ran~
