### ISSUE TITLE
Newly added Chime SDK Media Pipelines Composition Capabilities not available

### ISSUE THREAD

**Issue by jienco** [aws/aws-sdk-js#4469]
### Describe the bug

[On 7/24/2023, Amazon Chime SDK introduced enhancements to the composition capability of media pipelines in Amazon Chime SDK](https://aws.amazon.com/blogs/business-productivity/streamlining-media-workflows-amazon-chime-sdks-advanced-composition-capability-for-media-pipelines/).

However, the newly added properties for the [CreateMediaLiveConnectorPipeline command](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_CreateMediaLiveConnectorPipeline.html) are not available in this library. The typescript types are not updated, and even when using `any` for the type, an error is thrown in runtime when trying to use the new properties.

More info:
- https://docs.aws.amazon.com/chime-sdk/latest/dg/pipeline-compositing.html
- https://docs.aws.amazon.com/chime-sdk/latest/dg/compositing-layouts.html

### Expected Behavior

Newly added composition capabilities should be available for use in TypeScript and on runtime.

### Current Behavior

Error is thrown when using new properties such as `HorizatontalLayoutConfiguration`:

`UnexpectedParameter: Unexpected key 'HorizontalLayoutConfiguration' found in params.Sources[0].ChimeSdkMeetingLiveConnectorConfiguration.CompositedVideo.GridViewConfiguration`

### Reproduction Steps

```typescript
    const params: CreateMediaLiveConnectorPipelineRequest = {
      Sources: [
        {
          SourceType: 'ChimeSdkMeeting',
          ChimeSdkMeetingLiveConnectorConfiguration: {
            Arn: `arn:aws:chime::<accountId>:meeting:${meeting.MeetingId}`,
            MuxType: `AudioWithCompositedVideo`,
            CompositedVideo: {
              Layout: 'GridView',
              Resolution: 'FHD',
              GridViewConfiguration: {
                ContentShareLayout: 'Horizontal',
                HorizontalLayoutConfiguration: {
                  TileOrder: 'SpeakerSequence',
                  TilePosition: 'Top',
                  TileCount: 2,
                  TileAspectRatio: '4/3',
                },
              },
            },
          },
        },
      ],
      Sinks: [
        {
          SinkType: 'RTMP',
          RTMPConfiguration: {
            Url: ingestUrl,
            AudioChannels: 'Stereo',
            AudioSampleRate: '48000',
          },
        },
      ],
    };

    const mediaPipeline: MediaPipeline = await pipelineClient.createMediaLiveConnectorPipeline(params).promise();
```

### Additional Information/Context

- [Pipeline Compositing](https://docs.aws.amazon.com/chime-sdk/latest/dg/pipeline-compositing.html)

### SDK version used

"@aws-sdk/client-chime-sdk-media-pipelines": "3.376.0"

### Environment details (OS name and version, etc.)

Ubuntu 22.04 LTS

**Comment by RanVaknin** [comment]
Hi @jienco ,

Thanks for reaching out about this. I believe you saw this discrepancy because it took time from the moment the service team announced the launch and the time it took for our release pipeline to approve all the changes. 

https://github.com/aws/aws-sdk-go-v2/blame/main/codegen/sdk-codegen/aws-models/chime-sdk-media-pipelines.json#L2943

I see that the model changed last week to include those new features. You'll have to update your SDK version through npm, and those new types should be available. 

Thanks!
Ran~
