### ISSUE TITLE
DynamoDB PartiQL query clauses ignored in Amplify Lambda

### ISSUE THREAD

**Issue by nathan-mill** [aws/aws-sdk-js#4475]
### Describe the bug

The following query executes in the AWS console perfectly, returning the expected results. When I run the exact same query through the SDK, it returns an empty result set. Through experimentation, it seems as though the SDK ignores any `AND` clause after the first one no matter where it's placed in the query.

```
SELECT * FROM "CronRunLog"
    WHERE "JobName" = 'somejob'
    AND "JobStatus" = 'success'
    AND "Operation" = 'write'
    ORDER BY CreatedAt DESC
```

### Expected Behavior

I expect to receive an Items array containing Items which match the query parameters. 

### Current Behavior

I get nothing:

```
 {"Items":[],"NextToken":"COL+YioGvYHDOVrzco9wlvmrnqQl8GNGz0iYWeLXBKPbq+Ydi3c/QroxUXpPf2TnfW4RA4+VJnkUd2nzCchYgGQNh/hqQaIHNfmYZ2dw2hOtJRJxKodVJ0YISKhGUTRy7Xz3nPYaoLoFyECmhqMpXvO/MhcaFCsZ3kKlgLXKK0DJwgbIM9gfU7lo9wdevMvDXKqeQKaDtvu8yelfR3c4ybopoeONs4mT2oS8PEla5AsWie68CGphhJEzX4VTj/nkblz2al7Z3fO8WdscP+c9/KSxg4pt0K7qFlLPDES/na49kJCyhTKcE0I2UluLiYQpCPlTedJp9PcJCEECNNkb+BcnyAzkF+bWNtPpPpV0piULtjAAj1fhAp9GiDrZ6HfbGEvQypUs7g==","LastEvaluatedKey":{"JobName":{"S":"somejob"},"CreatedAt":{"S":"1691106221007"}}}
```

### Reproduction Steps

Run a PartiQL query with multiple AND clauses. 

### SDK version used

2.1425.0

### Environment details (OS name and version, etc.)

Amplify Lambda

**Comment by RanVaknin** [comment]
Hi @nathan-mill ,

Since you didn't share the SDK code, I can't tell if there's an issue with your implementation.

Considering what your setup is, I have this code snippet:

```js
const AWS = require('aws-sdk');

const ddb = new AWS.DynamoDB({
    region: 'us-east-1' 
});

const params = {
    Statement: `SELECT * FROM "CronRunLog"
                WHERE "JobName" = 'somejob'
                AND "JobStatus" = 'success'
                AND "Operation" = 'write'
                ORDER BY CreatedAt DESC`
};

ddb.executeStatement(params, (err, data) => {
    if (err) {
        console.error("Error", err);
    } else {
        console.log(JSON.stringify(data, null, 2));
    }
});
```

Result:
```console
$ node sample.js
{
  "Items": [
    {
      "Operation": {
        "S": "write"
      },
      "JobName": {
        "S": "somejob"
      },
      "JobStatus": {
        "S": "success"
      },
      "CreatedAt": {
        "N": "1691106221001"
      }
    }
  ]
}
```

Let me know if this helps.
Thanks,
Ran~

**Comment by nathan-mill** [comment]
Appreciate the effort, but we've come to the conclusion that Dynamo is simply not the right fit for this table. Feel free to close.
