### ISSUE TITLE
Observed high latency when using getObject to fetch from S3

### ISSUE THREAD

**Issue by navin22** [aws/aws-sdk-js#4476]
### Describe the bug

Using the aws-sdk 2.1420 to get an object from the S3 bucket is very slow. There are many instance where the object size is just in KBs still we see the latency.
Especially if your service is running in eks, we are using IAM Roles for Service accounts for authentitcation.

One thing we noticed is the call back event `validate`, `sign` and `build` were called very late like as high as ~10-15 seconds. We don't see any of our pod cpu, mem or bandwidth spike as well during that time.

### Expected Behavior

Since aws-sdk is the recommended method for the interaction expecting the performance should be good.

### Current Behavior

We have seen the high latency even during the low peak hours.

### Reproduction Steps

```
config s3 = new S3({
          region: 'us-west-2'
        })


const request = s3.getObject({
        Bucket: bucketName,
        Key: key
      })


    request.on('validate', () => {
      console.log({
        message: 'validating request',
        key: key,
        latency: Date.now() - start
      })
    })

    request.on('build', () => {
      console.log({
        message: 'building request',
        key: key,
        latency: Date.now() - start
      })
    })

    request.on('sign', () => {
        console.log({
        message: 'signing request',
        key: key,
        latency: Date.now() - start
      })
    })

    request.on('send', () => {
        console.log({
        message: 'sending request',
        key: key,
        latency: Date.now() - start
      })
    })

```

### SDK version used

2.1420.0

### Environment details (OS name and version, etc.)

Ubuntu (AMI image: dkr.ecr.us-west-2.amazonaws.com/builder-base:181ed6f58e6d779ce325c9008a5068689b290d85)

**Comment by RanVaknin** [comment]
Hi @navin22 ,

Im not an EKS expert, but the pod setup time +  IRSA auth can take some time until the SDK is provided with temporary credentials for the actual operation:

0. Pod start time
1. Call to OIDC provider to get the token (handled by EKS internally).
2. Call to STS to assume the role and get temporary credentials.
3. GetObject using temporary credentials.

After the first get-object call, those IRSA creds should be cached and available for pre-determined amount of time (I think its 60 min) so subsequent calls should be able to execute faster. 

Are testing with a single execution of getObject every time the pod gets restarted? Or do you have multiple getObject in the same credential life time and they are all slow? 

Thanks,
Ran~

**Comment by navin22** [comment]
> Hi @navin22 ,
> 
> Im not an EKS expert, but the pod setup time + IRSA auth can take some time until the SDK is provided with temporary credentials for the actual operation:
> 
> 0. Pod start time
> 1. Call to OIDC provider to get the token (handled by EKS internally).
> 2. Call to STS to assume the role and get temporary credentials.
> 3. GetObject using temporary credentials.
> 
> After the first get-object call, those IRSA creds should be cached and available for pre-determined amount of time (I think its 60 min) so subsequent calls should be able to execute faster.
> 
> Are testing with a single execution of getObject every time the pod gets restarted? Or do you have multiple getObject in the same credential life time and they are all slow?
> 
> Thanks, Ran~

Hi @RanVaknin 

We had multiple object of the SDK created, may be that's the reason we had lot of STS calls happening. And by the way this was not logged by sdk v2, we had to use the sdk v3 and that was logging lot of STSclient calls with morethan one attempt and a retryDelay. So once we fix that and have a single object to make the getobject calls, we are seeing a much better performance.

Few questions:
- Is passing the region to the SDK constructor doesn't guarantee that the STS endpoint used by SDK is regional or not?
```

const { S3 } = require('aws-sdk')
const s3 = new S3({
          region: 'us-west-2'
        })
``` 

does this mean the STS endpoint used here is us-west-2 or we have to explicitly set the env as suggested [here](https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html) 

- Is there a way we can increase the token expiration window to more than 1 hour by passing a config value or env value ?

**Comment by RanVaknin** [comment]
Hi @navin22 ,

Thanks for the clarification. I just want to confirm that your change is correct. There should only have 1 instance of the SDK client per region and per service. So if you are using S3 in `us-east-2` you should only have a single client instantiated for that region.

>Is passing the region to the SDK constructor doesn't guarantee that the STS endpoint used by SDK is regional or not?

No. The region you pass to the S3 client will be used by the SDK to construct requests to the listed S3 endpoints on us-west.  When running inside of an EKS pod, the SDK client will attempt to get credentials implicitly using the STS global endpoint.  Since you are using v2 you can either use the env variable or the setting on the client itself:

```js
const s3 = new S3({
          region: 'us-west-2',
          stsRegionalEndpoints: "regional"
        })
```

>Is there a way we can increase the token expiration window to more than 1 hour by passing a config value or env value ?

To the best of my knowledge this token expiration window is managed by Kubernetes and is not configurable. However the pod should refresh credentials automatically when the credentials are about to expire. 

Hope this helps. 
Thanks,
Ran~
