### ISSUE TITLE
Use IAM Role of EC2 instance to get aws credential

### ISSUE THREAD

**Issue by softdev1029** [aws/aws-sdk-js#4487]
### Describe the bug

Hi there
I made an AWS role to allow EC2 access to S3.
And I applied it to EC2 instance in us-east-1 region.
It's ubuntu 20.04.3

In ec2 instance, my application using React and a-frame (an entity component system framework for Three.js where developers can create 3D and WebXR scenes using HTML) is running on ec2.
I want to remove any aws key/secret from my code.
My old code is:

```
import s3ParseUrl from 's3-url-parser';

const AWS = require('aws-sdk');
const s3 = new AWS.S3({
accessKeyId: process.env.REACT_APP_AWS_ID,
secretAccessKey: process.env.REACT_APP_AWS_SECRET
});

export const getSignedUrl = (url) => {
if (!url) return url;
let signedUrl = url;
if (process.env.REACT_APP_TYPE === "production") {
const { bucket, key } = s3ParseUrl(url);
signedUrl = s3.getSignedUrl("getObject", { Bucket: bucket, Key: key, ResponseCacheControl: "no-cache" });
}
return signedUrl;
}
```

Now, I changed my code like below by removing aws key/secret.

```
const s3 = new AWS.S3();
```

But i get this error.

```
Uncaught CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

1. I correctly applied IAM role to ec2 instance. AWS SDK verion is 2.1066.0.
2. The role has the correct permission 'AmazonS3FullAccess'
3. And I restarted EC2 instance.
4. I even tried to set "AWS.config.update({ region: 'us-east-1' });" before "new AWS.s3" but no luck.
5. I even upgraded AWS SDK to 2.1431.0
6. I also tried to clear any metadata cache on EC2 instance. sudo systemctl restart ec2-instance-metadata
7. I connect to EC2 instance using SSH and run the following curl command in the terminal
curl http://169.254.169.254/latest/meta-data/
And the metadata service is accessible and I can see a list of metadata categories returned, such as ami-id, instance-id, instance-type, etc.
8. After SDK logging like below,

```
AWS.config.update({
region: 'us-east-1',
logger: console // Enable SDK logging to console
});
```

I get

```
[AWS s3 undefined 0.012s 0 retries] getObject({ Bucket: 'kc-assets-us',
Key: 'uploads/categories/202301301942_1902/texture_url/Catalina Gloss Bianco.webp',
ResponseCacheControl: 'no-cache' })
```

s3 is 'req.service.serviceIdentifier'
And the 3rd string is 'resp.httpResponse.statusCode'
Now that 'statusCode' is undefined, the credential part doesn't seem to be fetched correctly.

10. I also tried to clear the instance metadata cache
Sometimes, clearing the instance metadata cache can resolve issues. I tried running the following command on your EC2 instance to clear the cache:
sudo rm -rf /var/lib/cloud/instances/*

11. I tried to add the following permission to the role but no luck

```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"ec2:DescribeInstance*",
"ec2:GetConsoleOutput"
],
"Resource": "*"
}
]
}
```

13. I tested the fetching of temporary credentials manually using the AWS CLI on EC2 instance. Run the following command to see if it successfully fetches credentials:

```
aws sts get-caller-identity
```

Then I get the information about the IAM role associated with the instance.

```
{
"UserId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"Account": "xxxxxxxxxxxxxxx",
"Arn": "arn:aws:sts::xxxxxxxxxxxxxxx:assumed-role/AllowS3ForEC2/i-0e3dc6a677b704c0b"
}
```

14. I tried to access the S3 directly from the ec2 instance “i-0e3dc6a677b704c0b” directly using CLI like below:
aws s3 ls s3://kc-assets-us
                           PRE /
                           PRE uploads/
It successfully returns the info of s3.

15. To use the AWS SDK to achieve something similar to 'aws configure list', I did:

```
const AWS = require('aws-sdk');
const awsConfig = new AWS.Config();
const profiles = awsConfig.getCredentials((e)=>console.log('3=',e));
```

But I get this:

```
3= CredentialsError: No credentials to load
    at credError (config.js:402:1)
    at Config.getCredentials (config.js:447:1)
```

16. To use the AWS SDK to achieve something similar to 'aws sts get-caller-identity', I did:

```
const sts = new AWS.STS();
// Make the getCallerIdentity request
sts.getCallerIdentity({}, (err, data) => {
  if (err) {
    console.error('Error:', err);
  } else {
    console.log('Caller Identity:', data);
  }
});
```

But I get this:

```
index.js:1437 Error: CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

17. I simply did this:

```
const config = new AWS.Config();
console.log('AWS Config:', config);
```

Then, I get this:

```
AWS Config:
{
    "credentials": null,
    "credentialProvider": null,
    "region": null,
    "logger": null,
    "apiVersions": {},
    "apiVersion": null,
    "httpOptions": {
        "timeout": 120000
    },
    "maxRedirects": 10,
    "paramValidation": true,
    "sslEnabled": true,
    "s3ForcePathStyle": false,
    "s3BucketEndpoint": false,
    "s3DisableBodySigning": true,
    "s3UsEast1RegionalEndpoint": "legacy",
    "computeChecksums": true,
    "convertResponseTypes": true,
    "correctClockSkew": false,
    "customUserAgent": null,
    "dynamoDbCrc32": true,
    "systemClockOffset": 0,
    "signatureVersion": null,
    "signatureCache": true,
    "retryDelayOptions": {},
    "useAccelerateEndpoint": false,
    "clientSideMonitoring": false,
    "endpointCacheSize": 1000,
    "hostPrefixEnabled": true,
    "stsRegionalEndpoints": "legacy",
    "useFipsEndpoint": false,
    "useDualstackEndpoint": false,
    "token": null
}
```

Even though I tried the above all approaches, but I still get the error

```
Uncaught CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

Can you please help me troubleshoot it?

### Expected Behavior

I made an AWS role to allow EC2 access to S3.
And I applied it to EC2 instance in us-east-1 region.
It's ubuntu 20.04.3

In ec2 instance, my application using React and a-frame (an entity component system framework for Three.js where developers can create 3D and WebXR scenes using HTML) is running on ec2.
Now, I changed my code like below by removing aws key/secret.

```
const s3 = new AWS.S3();
```

### Current Behavior

But i get this error.

```
Uncaught CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

### Reproduction Steps

I made an AWS role to allow EC2 access to S3.
And I applied it to EC2 instance in us-east-1 region.
It's ubuntu 20.04.3

In ec2 instance, my application using React and a-frame (an entity component system framework for Three.js where developers can create 3D and WebXR scenes using HTML) is running on ec2.
I want to remove any aws key/secret from my code.
My old code is:

```
import s3ParseUrl from 's3-url-parser';

const AWS = require('aws-sdk');
const s3 = new AWS.S3({
accessKeyId: process.env.REACT_APP_AWS_ID,
secretAccessKey: process.env.REACT_APP_AWS_SECRET
});

export const getSignedUrl = (url) => {
if (!url) return url;
let signedUrl = url;
if (process.env.REACT_APP_TYPE === "production") {
const { bucket, key } = s3ParseUrl(url);
signedUrl = s3.getSignedUrl("getObject", { Bucket: bucket, Key: key, ResponseCacheControl: "no-cache" });
}
return signedUrl;
}
```

Now, I changed my code like below by removing aws key/secret.

```
const s3 = new AWS.S3();
```

But i get this error.

```
Uncaught CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

### SDK version used

2.1431.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04.3 LTS

**Comment by RanVaknin** [comment]
Hi @softdev1029 ,

Thanks for the in-depth reproduction steps. I might be wrong, but it sounds like your react app is client side rendered. 
In the context how credentials on an EC2 instance are vended, the EC2 container will be ran with the correct IAM role by virtue of injecting environment variables. When a _**Node based**_ SDK application is ran from EC2, it draw those env variables available on the container and makes a call to STS to exchange them for valid credentials.

On web, that app will not be able to read env variables from the container like a backend application does. Your container is communicating with IMDS correctly, but your application is not built with the env variables for the SDK a reference to them. And even if it did, exposing metadata of an instance for a browser application is a terrible idea from a security standpoint.

We can test node.js app access by running a simple backend application from your Ec2 instance. 
- ssh into your instance
- create a new nodejs project:
```console
$ mkdir foo && cd foo && touch app.js && npm init -y && npm install aws-sdk
```
- in app.js have this test code:
```js
const AWS = require('aws-sdk');

const s3 = new AWS.S3();

s3.listBuckets({}, function(err, data) {
  if (err) console.log(err, err.stack); 
  else     console.log(data);           
});
```
- run the code:
```console
$ node app.js
```

If the buckets are printed, you can see that the SDK recognizes the injected env variables and exchanges them for valid credentials.

---

I'm not sure what your use case is exactly, but if your application is client-rendered and you need your users to be able to interact with S3, you might want to use Cognito identity pools. With Cognito, your users can log into your app themselves and get their own set of temporary credentials every time,  or use Amplify which abstracts the need to use cognito altogether.

You can also try something like building a small Node.js server that will handle vending this presigned URL for your react app. I'd create a `getPresignedUrl.js` file in your instance. In that file you can setup SDK code similar to what I previously shared in this comment, and an express server that will listen on port :8080 or something, with express define a GET "/" and whenever your react app makes a call to that port in that path, the express app will return that presigned URL for you. (you will probably need to setup CORS correctly for this to work which can be a pain).

I hope this is helpful. Let me know if you have any other questions.
Ran~

**Comment by softdev1029** [comment]
Hi @RanVaknin 
I tried to use Cognito Identity pool in my client React app.

1. I created a new identity pool with an IAM role having S3FullAccess.
2. In my client React app,

import s3ParseUrl from 's3-url-parser';

const AWS = require('aws-sdk');
AWS.config.update({
  credentials: new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'us-east-1:a9b46a78-1193-4343-bf38-99135e238fa5',
  }),
});
const s3 = new AWS.S3();

export const getSignedUrl = (url) => {
  if (!url) return url;
  let signedUrl = url;
  try{
    const { bucket, key } = s3ParseUrl(url); 
    signedUrl = s3.getSignedUrl("getObject", { Bucket: bucket, Key: key, ResponseCacheControl: "no-cache" });
  }catch(error){
    console.error(error)
  }
  return signedUrl;
}

But for any s3 url, `signedUrl` is always `'https://s3.amazonaws.com/'`

**Comment by softdev1029** [comment]
FYI, I tried your steps.

1. mkdir foo && cd foo && touch app.js && npm init -y && npm install aws-sdk
2. in app.js have this test code:

const AWS = require('aws-sdk');
const s3 = new AWS.S3();
s3.listBuckets({}, function(err, data) {
  if (err) console.log(err, err.stack); 
  else     console.log(data);           
});

3.    run the code: node app.js

Then, I correctly get the result.
{
  Buckets: [
    {
      Name: 'aws-cloudtrail-logs-084709402479-ee55ea6c',
      CreationDate: 2022-06-13T15:19:20.000Z
    },
    {
      Name: 'kc-assets-bucket',
      CreationDate: 2021-04-14T14:55:36.000Z
    },
    { Name: 'kc-assets-us', CreationDate: 2021-04-25T16:32:01.000Z }
  ],
  Owner: {
    DisplayName: 'sebastian',
    ID: '2a78b4df8cd73bf3dcfebfb9e5f735adb39e54aca7993b43950fa2589f64de23'
  }
}

**Comment by RanVaknin** [comment]
Hi @softdev1029 ,
 
Thanks for the follow up. 

>Then, I correctly get the result.

This is great news. This means that your Node.js application can be ran from your pod successfully. 

>I created a new identity pool with an IAM role having S3FullAccess.

I see you created both a presigned url and a cognito identity pool.  My suggestion was to use one or the other.
Cognito identity pool lets your users sign into your app and then your app uses their temporary credentials to interact with S3. 
A presigned URL is for you to use your own credentials, and then you just supply your frontend with that Presigned URL.
While you can use them both together, It's probably not what you are looking for. 

As for your code to generate a presigned URL, `s3.getSignedUrl` can be called both asynchronously and synchronously (with or without a callback respectively. . Since your code relies on the returned credentials from Cognito, the synchronous s3.getSigendUrl function fires immediately without the necessary data and may lead to what you are experiencing.
You can fix it by passing your function a callback and changing the function signature:

```js
const s3 = new AWS.S3();

function generatePresignedUrl(callback){
    signedUrl = s3.getSignedUrl("getObject", { Bucket: "foo", Key: "bar"}, (err, url)=>{
        if (err){
            callback (err, null);
            return
        }
        callback(null, url)
    });
}
```

Thanks,
Ran~
