### ISSUE TITLE
No documentation on asynchronously event to reaches lambda

### ISSUE THREAD

**Issue by gfernandes410** [aws/aws-sdk-js#4491]
A lambda can be triggered by an asynchronous event. This is described in this article. 
https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html

The lambda will receive the following payload.
``` json
{
    "version": "1.0",
    "timestamp": "2019-11-14T18:16:05.568Z",
    "requestContext": {
        "requestId": "e4b46cbf-b738-xmpl-8880-a18cdf61200e",
        "functionArn": "arn:aws:lambda:us-east-2:123456789012:function:my-function:$LATEST",
        "condition": "RetriesExhausted",
        "approximateInvokeCount": 3
    },
    "requestPayload": {
        "ORDER_IDS": [
            "9e07af03-ce31-4ff3-xmpl-36dce652cb4f",
            "637de236-e7b2-464e-xmpl-baf57f86bb53",
            "a81ddca6-2c35-45c7-xmpl-c3a03a31ed15"
        ]
    },
    "responseContext": {
        "statusCode": 200,
        "executedVersion": "$LATEST",
        "functionError": "Unhandled"
    },
    "responsePayload": {
        "errorMessage": "RequestId: e4b46cbf-b738-xmpl-8880-a18cdf61200e Process exited before completing request"
    }
}
```

There is no type on the package mapping this event.

### Links

https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html

**Comment by ajredniwja** [comment]
Hi @gfernandes410 thanks for opening the issue, you have pointed out the docs that mention how to handle async invocations, but can you please elaborate your ask?

**Comment by padraic-mcatee** [comment]
I think the request here is for a dataclass/model to support event parsing with this JSON schema. If I have lambda A sending payload to lambda B, it would be nice to configure lambda B to deserialize the inbound event using the event parser (even better if this could be further typed based on a pydantic model for `requestPayload` field
