### ISSUE TITLE
computeChecksums(data: Buffer|string): GlacierComputeChecksumsOutput;

### ISSUE THREAD

**Issue by venkatnarasimharao** [aws/aws-sdk-js#4500]
### Describe the bug

after installing     "aws-sdk": "^2.1468.0", in angular 16, it is creating the blow issue
even after running npm i --save-dev @types/node
![image](https://github.com/aws/aws-sdk-js/assets/38693729/33e1982a-6a7e-4ea5-936d-9b1249c519f3)

### Expected Behavior

can't use aws-sdk

### Current Behavior

![image](https://github.com/aws/aws-sdk-js/assets/38693729/74b0fbd1-0f8a-47d5-928f-06b5c6c42a7b)

### Reproduction Steps

use angular 16 and install "aws-sdk": "^2.1468.0" & then compile it

### SDK version used

"^2.1468.0",

### Environment details (OS name and version, etc.)

Windows

**Comment by ajredniwja** [comment]
Hi @venkatnarasimharao thanks for opening this issue, can you please refer to the comment here: https://github.com/aws/aws-sdk-js/issues/1271#issuecomment-291658668
