### ISSUE TITLE
Want to upload the file in s3 and add the CSP /custom header without to prefix of X-Amz-Meta 

### ISSUE THREAD

**Issue by ketan0809** [aws/aws-sdk-js#4511]
### Describe the bug

I intend to upload a file to S3 using the AWS SDK (version 2.1336.0). During the file upload, I want to include custom headers, such as the Content-Security-Policy-Report-Only header. However, I've noticed that the headers are prefixed with `X-Amz-Meta` when the file is uploaded.

### Expected Behavior

I expected to be able to add the headers without the `X-Amz-Meta` prefix.

### Current Behavior

Headers are currently coming with the `X-Amz-Meta` prefix.

<img width="1052" alt="Screenshot 2023-10-19 at 11 11 49 AM" src="https://github.com/aws/aws-sdk-js/assets/22344750/83aa75e8-2e16-4232-af1b-dc286e291ec7">

### Reproduction Steps

Code snippet of uploading the file 

const client = new AWS.S3({
   accessKeyId: 'xxx',
   secretAccessKey: 'xxx',
});

const uploadFile = ({ file, params }) =>
  new Promise((resolve, reject) => {
    const date = new Date();
    
    const uploadParams = {
      Bucket: 'xxx',
      CacheControl: params.cacheControl,
      ContentSecurityPolicyReportOnly: params.contentSecurityPolicyReportOnly,
      ContentSecurityPolicy: params.contentSecurityPolicy,
      'x-temp': 'temp', 
      Metadata: {
        ContentSecurityPolicyReportOnly: params.contentSecurityPolicyReportOnly,
        ContentSecurityPolicy: params.contentSecurityPolicy,
        'x-temp': 'temp1',
      },
      Key: params.key,
      Body: fs.createReadStream(file),
    };

    console.time(`Uploading - ${file}`);
    client.upload(uploadParams, (err, data) => {
      if (err) {
        reject(err);
      } else {
        console.timeEnd(`Uploading - ${file}`);
        resolve();
      }
    });
  });
  
 

### SDK version used

2.1336.0

### Environment details (OS name and version, etc.)

macOS and version - 13.5.2

**Comment by RanVaknin** [comment]
Hi @ketan0809 ,

Thanks for reaching out. The SDK adding the `x-amz-meta-` prefix is the intended behavior for user defined metadata. This is done so that the S3 service knows that these are metadata headers. This is documented [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata):

> When uploading an object, you can also assign metadata to the object. You provide this optional information as a name-value (key-value) pair when you send a PUT or POST request to create the object. When you upload objects using the REST API, the optional user-defined metadata names must begin with x-amz-meta- to distinguish them from other HTTP headers. 

I hope this clears things up. Please let me know if you need anything else.

All the best,
Ran~
