### ISSUE TITLE
aws-sdk (v2): S3 Upload Issue

### ISSUE THREAD

**Issue by iamankitsaxena** [aws/aws-sdk-js#4516]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Error (The request signature we calculated does not match the signature you provided. Check your key and signing method.)  when uploading the file to S3 Bucket. Was working fine until last week.

### SDK version number

aws-sdk@2.569.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.16.0

### Reproduction Steps

```js
 s3.upload(params, function (err, data) {
              if (err) {
                reject("Error in generating QR , Please contact us!");
              } else {
                resolve();
              }
            });
          }
```
### Observed Behavior

Should upload file

### Expected Behavior

Gives Error ; Error in generating QR , Please contact us!

**Comment by RanVaknin** [comment]
Hi @iamankitsaxena ,

Without seeing your entire code snippet (imports, client initialization etc) I can't see why you might be running into this.
I'm able to use s3.upload() without any issue. 

If you can share the entire code snippet with us, that would help me dive deeper into the root cause. 

Thanks,
Ran~
