### ISSUE TITLE
Aws s3 Upload stream error.

### ISSUE THREAD

**Issue by jerrywu55** [aws/aws-sdk-js#452]
{ [NetworkingError: getaddrinfo EIO]
            message: 'getaddrinfo EIO',
                code: 'NetworkingError',
            errno: 'EIO',
            syscall: 'getaddrinfo',
            region: 'us-west-2',
            hostname: 'xxxxx-staging.s3-us-west-2.amazonaws.com',
            retryable: true,
            time: Sat Dec 27 2014 01:52:54 GMT+0800 (CST) } 'Error: getaddrinfo EIO\n    at errnoException (dns.js:37:11)\n    at Object.onanswer [as oncomplete] (dns.js:124:16)'

**Comment by lsegal** [comment]
I'm going to mark this as closed since there hasn't been a reply in a few weeks. If you can provide more information or help narrow down the code that reproduces this, feel free to reopen and I will take another look!
