### ISSUE TITLE
Starting to get InvalidChecksumError in @aws-sdk/client-sqs version 3.447.0

### ISSUE THREAD

**Issue by ShaharAdskAcc** [aws/aws-sdk-js#4522]
### Describe the bug

After upgrading to  @aws-sdk/client-sqs version 3.447.0 from version 3.445.0,
I started receiving "InvalidChecksumError" for every message I sent to SQS.

I didn't investigate it further - I just rolled back to 3.445.0.

### Expected Behavior

To not receive the "InvalidChecksumError"

### Current Behavior

I receive "InvalidChecksumError", sending a message to sqs does not work.

### Reproduction Steps

I didn't dive into it...

### SDK version used

3.447.0

### Environment details (OS name and version, etc.)

mac

**Comment by aBurmeseDev** [comment]
Hi @ShaharAdskAcc - thanks for reaching out and apologies for not getting to you sooner. I attempted to reproduce this on my end but was unable to. Can you share your code so that I can try to understand the issue better? Also does it happen intermittently?
