### ISSUE TITLE
Getting Project Config from Console Injection

### ISSUE THREAD

**Issue by rajeshigo** [aws/aws-sdk-js#4567]
### Describe the bug

we using S3 file storage (aws-sdk) for react project. we storing aws properties in .env , when inspecting and typing in console as **AWS.config.credential**  it gives all the project keys with accessKeyId ,secretAccessKey

### Expected Behavior

we need to restrict the project level details from console

### Current Behavior

![Capture](https://github.com/aws/aws-sdk-js/assets/143483115/32ac7300-ad67-411b-989a-98e014b3a22f)
![image](https://github.com/aws/aws-sdk-js/assets/143483115/f5ca2324-9eb0-4f2a-8e88-73a7bcdc2429)

### Reproduction Steps

1. run your react application
2. inspect your browser dev tool
3. go to console and type like AWS.config
4. there you will get your project level details easily

### SDK version used

2.1455.0

### Environment details (OS name and version, etc.)

window 10

**Comment by aBurmeseDev** [comment]
Hi @rajeshigo - thanks for reaching out. Can you provide a reproducible code for us to investigate further? Also which version of Node are you using?
