### ISSUE TITLE
MediaPipeline did not record video individual streams 

### ISSUE THREAD

**Issue by Kick933** [aws/aws-sdk-js#4570]
### Describe the bug

We have migrated to V3 sdk for our platform. We record the combined audio, seperate video streams and meeting events.

The config is in format -:

`
ChimeSdkMeetingConfiguration: {
      SourceConfiguration: {
        SelectedVideoStreams: {
          ExternalUserIds: arrayOfAttendeesExceptInterviewer,
        },
      },
      ArtifactsConfiguration: {
        Audio: {
          MuxType: 'AudioOnly',
        },
        Content: {
          State: 'Enabled',
          MuxType: 'ContentOnly',
        },
        Video: {
          MuxType: 'VideoOnly',
          State: 'Enabled',
        },
      },
    },
`

Here the array of attendees contains the external ids to be recorded.
The ChimeMeetingId for the two meetings we had problem with are-:

1.
`
chimeMeetingID = eff0fcdb-db3c-4ead-abd3-30919c272965
`

The Mediapipeline details for this meeting is-:(obtained from mediaPipelineDeleted event on EventBridge)
`
{'version': '0', 'eventType': 'chime:MediaPipelineDeleted', 'timestamp': 1704875590763.0, 'meetingId': '58265298-05ca-4d7b-bcf7-d6213a9f2954', 'externalMeetingId': 'eff0fcdb-db3c-4ead-abd3-30919c272965', 'mediaPipelineId': 'fe7646a8-8cda-46f0-8b6b-82a2f1920256', 'mediaRegion': 'ap-south-1'}
`

I am searching for details of 2nd meeting in our logs and update it as soon i i find it.

This issue happened with only two meetings. We have had more than 50 meetings since migrating to v3 SDK.

Please help us find the issue so we can rectify the issue.

### Expected Behavior

We expect the Video to be recorded and chunks be stored at our target S3 bucket.

### Current Behavior

Only Audio and meeting Events are being pushed to our S3 bucket. The issue only occurred for two meetings since 22nd December 2023. But since the chunks are used to process videos and allow our clients to view those videos for verification and validation, we are having significant issues due to Videos not being recorded. We personally verify that each meeting has camera on and no network issue.

It was also verified that the video was visible to other attendees during the meeting. It was just not recorded by MediaPipeline.

### Reproduction Steps

We are unable to consistently reproduce this issue. 

### SDK version used

v3

### Environment details (OS name and version, etc.)

NodeJS 14

**Comment by aBurmeseDev** [comment]
Hi @Kick933 - thanks for reaching out and sorry that you're having trouble finding the details on specific meetings.

In order for better assist you, could you share a minimal reproducible code that would give us more insight on this behavior? 

Best,
John

**Comment by Kick933** [comment]
Closing this issue as same is being discussed in https://github.com/aws/aws-sdk-js-v3/issues/5669
