### ISSUE TITLE
Temporary session creds for IAM user do not work for calls to IAM service only?

### ISSUE THREAD

**Issue by e-gineer** [aws/aws-sdk-js#460]
I have an interesting situation where temporary session credentials created for a user do not work for the IAM service only. They receive an InvalidClientTokenId error.

The same credentials do work with other services (e.g. EC2, S3, KMS) and return results. They also work for a service like CodeDeploy where the user has no permissions, returning an expected AccessDeniedException.

The use case flows as follows:
1. Create an IAM user.
2. Create access key & secret key for the user.
3. Use sts.getSessionToken to create temporary session credentials using the keys from 2.
4. Create AWS service object using temporary session creds in 3.
5. EC2, S3, KMS etc work.
6. IAM fails with InvalidClientTokenId error.

Below is some CoffeeScript to reproduce. Am I doing something wrong? Or is this a bug?

Thanks, Nathan

```
aws = require 'aws-sdk'

sts = new aws.STS
  accessKeyId: 'TODO'
  secretAccessKey: 'TODO'

sts.getSessionToken (err, creds) ->
  if err then return console.log err

  # unexpected error - fails with InvalidClientTokenId
  iamConn = new aws.IAM
    accessKeyId: creds.Credentials.AccessKeyId
    secretAccessKey: creds.Credentials.SecretAccessKey
    sessionToken: creds.Credentials.SessionToken
    region: 'us-west-2'
  iamConn.listUsers (err, results) ->
    console.log err, results

  # success
  ec2Conn = new aws.EC2
    accessKeyId: creds.Credentials.AccessKeyId
    secretAccessKey: creds.Credentials.SecretAccessKey
    sessionToken: creds.Credentials.SessionToken
    region: 'us-west-2'
  ec2Conn.describeInstances (err, results) ->
    console.log err, results

  # expected error - access denied
  cdConn = new aws.CodeDeploy
    accessKeyId: creds.Credentials.AccessKeyId
    secretAccessKey: creds.Credentials.SecretAccessKey
    sessionToken: creds.Credentials.SessionToken
    region: 'us-west-2'
  cdConn.listApplications (err, results) ->
    console.log err, results
```

**Comment by lsegal** [comment]
@e-gineer thanks for bringing this up. I'm looking into this with the IAM team.

**Comment by lsegal** [comment]
@e-gineer I got a response on this. It looks like STS session tokens are not supported with IAM *unless* you are also using MFA, or if you are using assumed roles. There is some documentation on this here:

http://docs.aws.amazon.com/STS/latest/UsingSTS/Welcome.html#sts-api-capabilities

Hope that helps!

**Comment by e-gineer** [comment]
Thanks very much for the quick response and link to clear documentation. I'm closing this ticket.

(For what it's worth, I find it surprising that the iam:* API actions are restricted when accessing via temporary session credentials, especially since it works for role-based credentials and the IAM console also works for federated users...)
