### ISSUE TITLE
webBoundary

### ISSUE THREAD

**Issue by LuckDragon82** [aws/aws-sdk-js#461]
we are trying to upload files straight from the client into s3 using pre-signed url. We can generate the url (we are currently supplying the Content-Type: 'video/x-m4v') and with curl we can successfully upload the file. I am trying to use ajax and stole some simple code from you from another thread. The problem is the files in s3 all have the following appending at the top.

------WebKitFormBoundaryaskMyMljnnwYsAY3
Content-Disposition: form-data; name="ncaa_video_file"; filename="holiday.m4v"
Content-Type: video/mp4

This is making the files unusable unless that is removed. I'm not sure how to remove this. Have you run into this before? Below is my jquery ajax call

```
    var formData = new FormData($('#upload-file')[0])

    
 
    $.ajax({
      url: presignedUrl, // the presigned URL
      type: 'PUT',
      data: formData,
      processData: false,
      contentType: 'video/x-m4v',
      success: function() { console.log('Uploaded data successfully.')},
      xhr: function() {  // Custom XMLHttpRequest
                  var myXhr = $.ajaxSettings.xhr();
                  if(myXhr.upload){ // Check if upload property exists
                      myXhr.upload.addEventListener('progress',progressHandlingFunction, false); // For handling the progress of the upload
                  }
                  return myXhr
              }
    })
    function progressHandlingFunction(e){
        if(e.lengthComputable){
            $('progress').attr({value:e.loaded,max:e.total});
        }
    }
```

Thanks for any insight you have

**Comment by AdityaManohar** [comment]
You are passing in `FormData` as your data. You probably want to be passing in the `File` object directly.

```javascript
var data  = $("#upload-file")[0].files[0];

$.ajax({
  url: presignedUrl,
  type: 'PUT',
  data: data,
});

```

Let me know if this helps.

**Comment by LuckDragon82** [comment]
wow. its so simple it hurts. Thank you!
