### ISSUE TITLE
How to pass filter  params for custom filter parameters to quicksightClient.generateEmbedUrlForRegisteredUser()

### ISSUE THREAD

**Issue by SinhaRakesh** [aws/aws-sdk-js#4611]
### Describe the issue

How to pass filter params for custom filter, for generating embedded url for register user 

my code is 

quicksightClient.generateEmbedUrlForRegisteredUser(
{
    AwsAccountId: "",
    ExperienceConfiguration: {
      Dashboard: {
        InitialDashboardId: "",
      },
    },
    UserArn: "",
    SessionLifetimeInMinutes: 100,
  };
)

### Links

.//

**Comment by aBurmeseDev** [comment]
Hi @SinhaRakesh - thanks for reaching out.

It sounds like you're calling [GenerateEmbedUrlForRegisteredUserCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/quicksight/command/GenerateEmbedUrlForRegisteredUserCommand/) from quicksight client. Can you elaborate more on what you're trying to filter? 

Please check out the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/quicksight/command/GenerateEmbedUrlForRegisteredUserCommand/) for your reference.
