### ISSUE TITLE
Announcement link in V2 EOL banner doesn't work

### ISSUE THREAD

**Issue by perpil** [aws/aws-sdk-js#4617]
### Describe the issue

In this [banner](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest), the announcement isn't linked:

<img width="1191" alt="image" src="https://github.com/aws/aws-sdk-js/assets/97474956/85ed1865-7d26-43e6-b1c1-66f31961ef16">

I think you mean to point here: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-javascript-v2/

Also, I'm somewhat surprised that [AWSJavaScriptSDK/latest](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest) still points at V2 and V3 is [AWSJavaScriptSDK/v3/latest](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/) I would expect latest to point at V3.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest

**Comment by aBurmeseDev** [comment]
Hi @perpil - thanks for catching that. 

I'll check in with our doc team to update the link. 

>Also, I'm somewhat surprised that [AWSJavaScriptSDK/latest](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest) still points at V2 and V3 is [AWSJavaScriptSDK/v3/latest](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/) I would expect latest to point at V3.

I don't full understand what you're proposing here though, are you suggesting v3 URL should be https://docs.aws.amazon.com/AWSJavaScriptSDK/latest instead of https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/ ?

Best,
John

**Comment by perpil** [comment]
I'd expect https://docs.aws.amazon.com/AWSJavaScriptSDK/latest to be an alias for https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/ but understand that that might be tricky since there wouldn't be a home for V2 and there is no https://docs.aws.amazon.com/AWSJavaScriptSDK/v2/latest/
