### ISSUE TITLE
AWS.CloudWatchLogs is undefined?

### ISSUE THREAD

**Issue by downie** [aws/aws-sdk-js#463]
I'm trying to use the CloudWatchLogs service in a single page webapp. Despite being [well documented](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatchLogs.html), it looks like this object is just missing from the js (both minified and un-minified):
```
TypeError: undefined is not a constructor (evaluating 'new AWS.CloudWatchLogs({
      region: "us-west-2"
})')
```

Is there another file I need to include to get this functionality? Is it accessible off of the `AWS.CloudWatch` object? How can I use the CloudWatchLogs service with this sdk?

**Comment by mhart** [comment]
Out of interest, does `AWS.Logs` work?

**Comment by downie** [comment]
Nope. Here are all the properties accessible from AWS:
```
> for (var x in AWS) { console.log(x); }
[Log] util
[Log] VERSION
[Log] Signers
[Log] Protocol
[Log] XML
[Log] JSON
[Log] Model
[Log] apiLoader
[Log] Service
[Log] Credentials
[Log] CredentialProviderChain
[Log] TemporaryCredentials
[Log] WebIdentityCredentials
[Log] CognitoIdentityCredentials
[Log] SAMLCredentials
[Log] Config
[Log] config
[Log] Endpoint
[Log] HttpRequest
[Log] HttpResponse
[Log] HttpClient
[Log] SequentialExecutor
[Log] EventListeners
[Log] Request
[Log] Response
[Log] ResourceWaiter
[Log] ParamValidator
[Log] events
[Log] XHRClient
[Log] CloudWatch
[Log] CognitoIdentity
[Log] CognitoSync
[Log] DynamoDB
[Log] ElasticTranscoder
[Log] Kinesis
[Log] Lambda
[Log] S3
[Log] SNS
[Log] SQS
[Log] STS
```

**Comment by AdityaManohar** [comment]
Which version of the SDK are you using? I am unable to reproduce this with version 2.1.5.

**Comment by downie** [comment]
Version 2.1.5

**Comment by downie** [comment]
I'm not sure how you're not able to reproduce it. Even using the published minified code at https://sdk.amazonaws.com/js/aws-sdk-2.1.5.min.js doesn't appear to have the `CloudWatchLogs` property in it.

**Comment by AdityaManohar** [comment]
@downie Sorry! I missed out the fact that you are using the browser build of the SDK. 

`CloudWatchLogs` isn't included in the default build of the SDK because the service does not support CORS. 

Unfortunately, there is nothing that we can do about this right now. If you are using this in a browser environment where you can disable CORS, then you can build a custom version of the SDK as mentioned here: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-building.html

**Comment by downie** [comment]
Bummer. Well, I'm glad I'm not crazy at least. Thanks anyway.

**Comment by AdityaManohar** [comment]
Sure, no problem!
