### ISSUE TITLE
local no error, dev error

### ISSUE THREAD

**Issue by xinzhiheng123** [aws/aws-sdk-js#4653]
### Describe the issue

local no error, dev error
![20240627-103532](https://github.com/aws/aws-sdk-js/assets/167166804/3abe6d65-3420-40b9-ab39-b4f54a1e1ea7)

### Links

https://dev.mesas.com/user/user

**Comment by aBurmeseDev** [comment]
Hi @xinzhiheng123 - thanks for reaching out.

Can you elaborate more on what the issue is? Is it related to AWS SDK? Please share your SDK code or documentation link if it's docs related issue.
