### ISSUE TITLE
CORS Error When Accessing Swagger API Deployed on AWS EC2

### ISSUE THREAD

**Issue by ashu1230** [aws/aws-sdk-js#4671]
### Describe the issue

I have deployed a NestJS backend on an AWS EC2 instance. The Swagger UI is accessible, but when I try to hit the API using Swagger, I receive the following error:

ISSUE: Failed to fetch. Possible Reasons:
1. CORS
2. Network Failure
3. URL Scheme must be "http" or "https" for CORS request.
Details:
The API works correctly when tested directly on the EC2 instance (e.g., using `curl`).
The Swagger UI is accessed via the public IP address of the EC2 instance.
The error occurs when trying to access the API endpoint through the Swagger UI.
My backend is running on `http://localhost:3033`, and the Swagger UI is being accessed via the public IP of the EC2 instance.

Troubleshooting Steps Taken:
Confirmed that the backend API is accessible directly from the EC2 instance.
Verified that the server is configured to handle CORS requests by setting the appropriate CORS headers in the NestJS application.
Checked the network configurations and security groups in AWS EC2 to ensure proper access.

Environment:
NestJS version: 
AWS EC2 Instance: Amazon linus(t2.micor).
Swagger version: 6.0.5
Browser: Chrome, Edge
Node.js version: Latest
CORE: 9.0.0
Request URL: http://localhost:3033/api/v1/auth/signin

![Error Image](https://github.com/user-attachments/assets/c147bf73-e840-4100-a31d-b343dd5344c7)

Question:
How can I resolve this CORS issue, and what configurations are required to allow the Swagger UI to make successful API requests in this setup?

### Links

Request URL: http://localhost:3033/api/v1/auth/signin

**Comment by zshzbh** [comment]
@ashu1230,

Could you please check with the API owner to make sure your request URL is on the allowlist?

**Comment by ashu1230** [comment]
@zshzbh 

Yes it is.

**Comment by ashu1230** [comment]
issue now solved

**Comment by zshzbh** [comment]
Thanks for closing the ticket, just want to get more info for future reference. 

May I know how does this issue get resolved on your end?
