### ISSUE TITLE
S3 SSE-C Key MD5 Invalid

### ISSUE THREAD

**Issue by cbkihong** [aws/aws-sdk-js#469]
I just started out on Node.js and the AWS SDK on Node.js but ran straight into this issue when I tried to GET a previously uploaded SSE-C encrypted object on S3. I checked the code and found that the "X-Amz-Server-Side-Encryption-Customer-Key-MD5" header sent to S3, was doubly base64 encoded.

I made the following change against the library and the problem was gone.

```
diff --git a/lib/services/s3.js b/lib/services/s3.js
index 750f560..bca1b48 100644
--- a/lib/services/s3.js
+++ b/lib/services/s3.js
@@ -246,7 +246,7 @@ AWS.util.update(AWS.S3.prototype, {
         req.httpRequest.headers[header] = AWS.util.base64.encode(key);
         if (!req.httpRequest.headers[md5header]) {
           var value = AWS.util.crypto.md5(key, 'base64');
-          req.httpRequest.headers[md5header] = AWS.util.base64.encode(value);
+          req.httpRequest.headers[md5header] = value;
         }
 
       }
```

I think the bug is pretty apparent. Though, ritual test case as you requested :-

Node version: v0.10.35
Tested SDK version: 2.1.6 (from npm)

```
var s3 = new AWS.S3();
var key = '123456789012345678901234567890AB';
s3.getObject({
	Bucket: 'mybucket',
	Key: 'some_path/testupload.txt',
	SSECustomerAlgorithm: 'AES256',
	SSECustomerKey: key
}, function(err, data) {
	response.write(data.Body);
	response.end();
});
```

**Comment by AdityaManohar** [comment]
@cbkihong This is fixed in master. Thanks for reporting!
