### ISSUE TITLE
invokeArgs - escape chars

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#481]
Hi,

So when I invoke my function in Lambda I noticed the following problem.

When I invoke without "Enter Character" in my text_html, works fine. When I invoke it with Enter Char it doesn't work.

Works:
```
{"args":{"from":"FROMEMAIL","subject":"Message Subject","text_message":"TEST"}}
```

Doesn't work:
```
{"args":{"from":"FROMEMAIL","subject":"Message Subject","text_message":"test\n\n\nasdfasd"}}
```

This is how I'm escaping chars.
```
jsonString = JSON.stringify(invokeArgs),
    repString = jsonString.replace(/\\n/g, "\\n")
    .replace(/\\'/g, "\\'")
    .replace(/\\"/g, '\\"')
    .replace(/\\&/g, "\\&")
    .replace(/\\r/g, "\\r")
    .replace(/\\t/g, "\\t")
    .replace(/\\b/g, "\\b")
    .replace(/\\f/g, "\\f");
```

Please help :)

**Comment by lsegal** [comment]
Can you explain what you mean by "doesn't work"? What happens? Do you get an error? If so, what is the error?

**Comment by ramonck** [comment]
I get this feedback in CloudWatch
```
Unable to parse input as json
```

**Comment by lsegal** [comment]
Have you tried without modifying the JSON string you generated? You should not be modifying the `JSON.stringify()` return value, as you are likely corrupting the JSON payload with those replace calls.

**Comment by ramonck** [comment]
I did try that in the first place.

Also tried now again to retest, and still the same problem.

First string worked
```
teste
```

Second didn't

```
teste\n\nasdfasd
```

Feedback on CloudWatch
```
Unable to parse input as json
```

**Comment by lsegal** [comment]
In that case I would recommend opening a thread on the [AWS Lambda forums](https://forums.aws.amazon.com/forum.jspa?forumID=186) since that seems like it is probably an issue  with parsing JSON in the service itself. This doesn't look like an issue with the SDK side.

**Comment by ramonck** [comment]
Ok Thanks
