### ISSUE TITLE
[node 0.11.15] S3#getSignedUrl is not working

### ISSUE THREAD

**Issue by lazutkin** [aws/aws-sdk-js#487]
It returns truncated urls like `https://<bucket>.s3.amazonaws.com/`

**Comment by lsegal** [comment]
Can you provide the version of the SDK you are using? Note that Node.js 0.11.x is unstable branch that is not directly supported by the SDK. Although most things *should* work, we can't guarantee that they always will, since backwards compatibility is not guaranteed in that branch. Can you reproduce this in 0.10.x?

**Comment by lazutkin** [comment]
No, it works as expected in 0.11.14 and less versions. Lib version is 2.1.8

**Comment by lazutkin** [comment]
Here is a bash session:

```
comp:~ node junk.js 
url is: https://<bucket name>.amazonaws.com/some.key?AWSAccessKeyId=<Key>&Expires=1422649851&Signature=MF2qqIw0r5Cp3TYxx0xBB53L9aw%3D

comp:~   nvm use next
Now using node v0.11.15

comp:~  node -v
v0.11.15

comp:~  node junk.js 
url is: https://<bucket name>.s3.amazonaws.com/

comp:~  cat junk.js 
var AWS = require( "aws-sdk" )
var s3  = new AWS.S3()


s3.getSignedUrl('putObject', {Key: 'some.key', Bucket: 'my-bucket'}, function(err, url){
  console.log('url is: %s', url)
})

```

**Comment by lsegal** [comment]
That seems like a regression or breaking change in the v0.11.15 release, then. Looking at the [release notes](http://blog.nodejs.org/2015/01/20/node-v0-11-15-unstable/) it's hard to track down the exact change, but if you're able to figure out the cause, do let us know. You might also want to look at the Node.js GitHub issues to see if anyone has reported any bugs in the latest release that might be relevant.

As a sidenote, have you printed the `err`? Is it not being set?

**Comment by mhart** [comment]
Also, v0.11.16 was just released, so worth trying that (especially if there is an error and it's SSL or URL path related: http://blog.nodejs.org/2015/01/30/node-v0-11-16-unstable/

**Comment by mhart** [comment]
(just checked, works fine in v0.11.16 for me - but breaks in v0.11.15 - so I think it's a regression, perhaps in the path handling stuff)

**Comment by lsegal** [comment]
Thanks for diving in on this @mhart!

**Comment by mhart** [comment]
No probs, I was as intrigued as you. Pretty bad regression - or just an unlucky edge case that the SDK was hitting.

**Comment by lazutkin** [comment]
Checked, it works on node 0.11.16.

**Comment by lsegal** [comment]
Going to mark this as closed since it's an issue with Node.js. Thanks for letting us know about this regression!
