### ISSUE TITLE
TypeError: Object doesn't support property or method 'indexOf'

### ISSUE THREAD

**Issue by manzanofab** [aws/aws-sdk-js#491]
Hi I am trying to use this file. It works perfectly on all browsers except for IE 
if i display the error message i get
TypeError: Object doesn't support property or method 'indexOf'

I am using like:
            bucket.putObject(params, function (err, data) {
              console.log('data inside function: ' + data);
              console.log('err inside function: ' + err);
              .......
            });

**Comment by AdityaManohar** [comment]
Which version of IE are you using? The SDK works on IE 10+.

**Comment by manzanofab** [comment]
Hi Thank you so much for prompt reply, I am using IE 11. I dont understand why, I have also try IE in different computers with the same outcome.
This is a bigger portion of my code

This morning I got a new error, not sure if it is because before I was usingan older version of the sdk
addEventLIstener
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.1.8.min.js"></script>
    <script type="text/javascript">
      j$ = jQuery.noConflict(); 


      function blockme() {

     
        var stringvalue='{!RandomFileName}';
        AWS.config.update({accessKeyId: '.......', secretAccessKey: '......'});
        AWS.config.region = 'ap-southeast-2';

        var bucket = new AWS.S3({params: {Bucket: 'jdl-sf-lu5n6evy'}});
        var fileChooser = document.getElementById('file-chooser');             
        var file = fileChooser.files[0];

        var type = document.getElementById('{!$Component.formId.blockid.sectionid.itemid1.type}').value;
        var documetn = document.getElementById('{!$Component.formId.blockid.sectionid.itemid2.documentId}').value;
        var description = document.getElementById('{!$Component.formId.blockid.sectionid.itemid3.descriptionId}').value;

        if(type != "" && documetn !="" && description !="") {

          if (file) {
            j$.blockUI({ css: {
              border: 'none',
              padding: '15px',
              backgroundColor: '#000',
              '-webkit-border-radius': '10px',
              '-moz-border-radius': '10px',
              opacity: .5,
              color: '#fff'
              }
            });
            var finenamefull=file.name;
            finenamefull = finenamefull.replace(",", ""); 
            var arrayOfStrings = finenamefull.split('.');
            var noofStrings=arrayOfStrings.length;
            var extension=arrayOfStrings[noofStrings-1];
            var filenamewithext=stringvalue+'.'+extension;
            var params = {Key: filenamewithext, ContentType: file.type, Body: file};
            var r = finenamefull+','+file.type;
            document.getElementById("awsId").value = r;
            
            bucket.putObject(params, function (err, data) {
              console.log('data inside function: ' + data);
              console.log('err inside function: ' + err);
              alert('Message inside bucket function');

              j$.unblockUI();
              var z = 'status'
              document.getElementById("awsIdStatus").value = z;
              console.log(err);
              console.log(data);
              showStatus();
            });
          } 
        }
      }//END FUNCTION

    </script> 
![amazon-upload-issue](https://cloud.githubusercontent.com/assets/2888146/6029643/b06a0650-ac3d-11e4-8e8f-c94cd342907b.jpg)

**Comment by manzanofab** [comment]
![amazon-upload-issue](https://cloud.githubusercontent.com/assets/2888146/6029688/03e48c9c-ac3e-11e4-82db-0fda1c7a1028.jpg)

**Comment by AdityaManohar** [comment]
Are you using some version of `sarissa.js` (possibly through Salesforce) in your application?

**Comment by manzanofab** [comment]
Hi Thank you so much for your prompt reply, I am sorry i just realised that it didnt  copy all my code
yes I am using t in a Visualforce page 
the current version that I am using is "sdk.amazonaws.com/js/aws-sdk-2.1.8.min.js"
on firebug I wasnt able to find sarissa.js in the find tool

![vfpage-request](https://cloud.githubusercontent.com/assets/2888146/6032897/803340ce-ac5a-11e4-8d40-86ef48cf64ab.jpg)

**Comment by manzanofab** [comment]
So this means that I cant use aws-sdk-2.1.8.min.js in visualforce? or is there a work around ?
Actually (not sure if already mentioned but) this visualforce page works fine in chrome and in firefox

**Comment by AdityaManohar** [comment]
Salesforce/VisualForce seems to be replacing the native `XMLHttpRequest` object only on IE browsers. 

Can you inspect the `XMLHttpRequest` on IE?

The workaround is to cache a reference of the modified `XMLHttpRequest` object, and restore the native `XMLHttpRequest` object before using the AWS SDK.

**Comment by manzanofab** [comment]
HI Thank you so much for the prompt response.
I am sorry I know that this will be out of topic, but I am not familiar with XMLHttpRequest, from google I understand that this are the headers of the page?
![xml request](https://cloud.githubusercontent.com/assets/2888146/6033858/f4588e12-ac66-11e4-8f21-43c2fe41930d.jpg)
this is what  get in the console tool network tab

Thank you so much

**Comment by AdityaManohar** [comment]
In IE you can `console.log(XMLHttpRequest)` to inspect it.

**Comment by manzanofab** [comment]
Hi 

thank you very much for that, this is the result when calling it from a onload:
window.onload=function(){
is the following:

function() {
    if (!_SARISSA_XMLHTTP_PROGID) {
        _SARISSA_XMLHTTP_PROGID = Sarissa.pickRecentProgID(["Msxml2.XMLHTTP.6.0", "MSXML2.XMLHTTP.3.0", "MSXML2.XMLHTTP", "Microsoft.XMLHTTP"]);
    }
    return new ActiveXObject(_SARISSA_XMLHTTP_PROGID);
}
![xmlrequest1](https://cloud.githubusercontent.com/assets/2888146/6034075/0f6025f0-ac6a-11e4-97b5-49c2a7cb2d1d.jpg)

this is from firefox 
![xmlrequest2](https://cloud.githubusercontent.com/assets/2888146/6034161/2de9627e-ac6b-11e4-9f72-a8ed0b17cb1a.jpg)

So I will need to manipulate that ?

**Comment by manzanofab** [comment]
again thank you so much for the help

**Comment by AdityaManohar** [comment]
@manzanofab anytime!

You don't need to call `console.log(XMLHttpRequest)` on `window.onload`. You can simply type it into your console and it should print out the object

You will need to restore the native `XMLHttpRequest` only in IE, something to the effect of:
```javascript
// Cache Sarissa's XHR
Sarissa.XHR = XMLHttpRequest;
XMLHttpRequest = Sarissa.originalXMLHttpRequest;
// Run AWS-SDK code here
// ...
// Replace Sarissa's XHR
XMLHttpRequest = Sarissa.XHR
```
This will work provided this function block is sequentially executing.

**Comment by manzanofab** [comment]
Thank you so much, that works perfectly!!!!!

**Comment by AdityaManohar** [comment]
@manzanofab Glad you got it to work!

**Comment by proerp5** [comment]
Hi Aditya,

We are also facing the similar issue in our salesforce Environment, so can you please elaborate the solution as we do not have much idea about how the XMLHTTP works and how to replace the Sarissa's XHR to get this working.

it would be nice if you could immediately reply to this, asit is causing a major issue for us


thanks,
proerp5

**Comment by manzanofab** [comment]
@proerp5 

You dont have to do anything special just put your js code between this lines
<script type="text/javascript">
	Sarissa.XHR = XMLHttpRequest;
	XMLHttpRequest = Sarissa.originalXMLHttpRequest;

	//YOUR CODE


	XMLHttpRequest = Sarissa.XHR
</script>

**Comment by proerp5** [comment]
Thanks for the reply.
yes, i tried doing that and it is not working even after this.
then , i tried assigning XMLHttpRequest = Sarissa.originalXMLHttpRequest; after my code but then i am getting error for a param 'QueueId'.

the solution that had been suggested doesn't seems to work in my case and i dont seem to understand why it isnt working as it did  for you. 

Thanks,
proerp

**Comment by manzanofab** [comment]
@proerp5

Can you paste your code? or add on a repository?
maybe try having first only those 3 lines and where it says //YOUR CODE put console.log('anything'), and one after, just to check if it is your browser doing something

**Comment by proerp5** [comment]
below is the code snippet and it seems that the uploadDocumentandMessageToQueue seems to error out in case of IE 10+ browser:

var meta2 = JSON.parse(metadata);
if(filesList[i].type=='text/xml' || filesList[i].type=='application/xml'){
meta2.structured = 'Y';
}
meta2.originalFileName= filesList[i].name;
meta2.mimeType=filesList[i].type;
meta2.loanEvent = 'Origination';

                Sarissa.XHR = XMLHttpRequest;
                alert('reqearlier: '+XMLHttpRequest);//same as git
                XMLHttpRequest = Sarissa.originalXMLHttpRequest;
                alert('req: '+XMLHttpRequest);//native code block

                uploadDocumentandMessageToQueue(token, jQuery('#fileToUpload')[0].files[i], JSON.stringify(meta2), 'handleReturn');


                if(Sarissa.originalXMLHttpRequest) {
                    XMLHttpRequest = XMLHttpRequest;
                } else {
                        XMLHttpRequest = Sarissa.XHR;
                    }

**Comment by manzanofab** [comment]
Now that you mentioned IE, I just remember (as this was from my old job), I couldn't work it out in IE, from memory I dont think it was the same errror, but I couldnt make it work in IE.

I am sorry
