### ISSUE TITLE
Https CloudFront + AWS Lambda JS

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#492]
Hello,

I have the following scenario, wondering what's the security for a "user/password" authentication utilizing Lambda using only aws-sdk-js, what are the best practices?

![image](https://cloud.githubusercontent.com/assets/5229948/6018471/261e1b7c-ab7e-11e4-9e43-ae0f497ac0ae.png)

Best Regards

**Comment by AdityaManohar** [comment]
@ramonck can you help me understand where you want to authenticate users? Would you also be able to elaborate a little on your scenario?

**Comment by ramonck** [comment]
Hi Aditya,

So I'm building a scenario to authenticate a user directly on a HTML page utilizing aws-sdk-js.

I'm worried about the security implications of this scenario. I've drawed it so you can understand ir better.

![image](https://cloud.githubusercontent.com/assets/5229948/6039364/67bb9ca6-ac4d-11e4-8d9e-433e4d904d7c.png)


I want to know what are the best practices and what are the security implications regarding what's in red.

Best Regards,

**Comment by AdityaManohar** [comment]
@ramonck From what I understand, you are trying to authenticate the SDK in the browser. There are a couple of ways to do this:

1. The recommended way to authenticate the SDK in the browser is to use [Amazon Cognito](http://aws.amazon.com/cognito/). Our developer guide describes how to [authenticate users using Cognito](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-configuring.html#Using_Amazon_Cognito_to_Authenticate_Users). Amazon Cognito is used in conjunction with IAM roles to control access to your AWS resources. Amazon Cognito works with identity providers like Facebook and Google as well as developer authenticated identities (your own backend authentication process).

2. The other approach is to use web identity federation. Our developer guide also describes [using web identity federation to authenticate users in the browser](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-configuring.html#Using_Web_Identity_Federation_to_Authenticate_Users).

I hope this helps!

**Comment by ramonck** [comment]
Hi Aditya,

Thanks for the feedback, yes you nailed it. I never thought about using Cognito, always had in mind as being a game api, it sure fits like a glove in my solution puzzle.
 Found this post on utilizing the AWS-SDK-JS API
http://mobile.awsblog.com/post/TxBVEDL5Z8JKAC/Use-Amazon-Cognito-in-your-website-for-simple-AWS-authentication

```
// The parameters required to intialize the Cognito Credentials object.
// If you are authenticating your users through one of the supported
// identity providers you should set the Logins object with the provider
// tokens. For example:
// Logins: {
//   graph.facebook.com : facebookResponse.authResponse.accessToken
// }
var params = {
    AccountId: "YOUR_AWS_ACCOUNT_ID",
    RoleArn: "arn:aws:iam::6157xxxxxxxx:role/a_valid_aws_role_arn",
    IdentityPoolId: "YOUR_COGNITO_IDENTITY_POOL_ID"
};
 
// set the Amazon Cognito region
AWS.config.region = 'us-east-1';
// initialize the Credentials object with our parameters
AWS.config.credentials = new AWS.CognitoIdentityCredentials(params);
 
// We can set the get method of the Credentials object to retrieve
// the unique identifier for the end user (identityId) once the provider
// has refreshed itself
AWS.config.credentials.get(function(err) {
    if (!err) {
        console.log("Cognito Identity Id: " + AWS.config.credentials.identityId);
    }
});
 
// Other service clients will automatically use the Cognito Credentials provider
// configured in the JavaScript SDK.
var cognitoSyncClient = new AWS.CognitoSync();
cognitoSyncClient.listDatasets({
    IdentityId: AWS.config.credentials.identityId,
    IdentityPoolId: "YOUR_COGNITO_IDENTITY_POOL_ID"
}, function(err, data) {
    if ( !err ) {
        console.log(JSON.stringify(data));
    }
});
```

Wanted to know now how do I pass in the username and password fields from the form, I don't want to do federated login for now (seems that it's going to complicate for now). 

Best Regards,

**Comment by AdityaManohar** [comment]
Are you referring to the username and password of the provider or access key-secret access key combination?

**Comment by ramonck** [comment]
I just want a simple login and password with Cognito authentication scenario, how do I do it in JS API?

**Comment by ramonck** [comment]
I've seen in some tutorials that I can send them to login at Facebook and when they comeback Cognito will fetch the identity, does it work like that or do I have to send the user to login to facebook through a special Cognito API on the JS SDK?

**Comment by AdityaManohar** [comment]
1. You will have to register your application with a 3rd party provider. Amazon Cognito currently supports Facebook, Google, and Login with Amazon.
2. Use the provider SDK to authenticate users with their username and password. You will have to refer to the provider documentation to see how to do this. Here is the documentation for the [Facebook](https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.2), [Google](https://developers.google.com/+/web/signin/), and [Login with Amazon](http://login.amazon.com/website).
3. The provider will return a token which you need to pass into Cognito in exchange for credentials.

This is covered in detail in the ["Authenticating Users with Amazon Cognito"](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-configuring.html#Using_Amazon_Cognito_to_Authenticate_Users) section of the developer guide.

I hope this helps!

**Comment by ramonck** [comment]
Aditya,

You nailed it once again. Thank you very much for all your help, I now continue on being a happy aws-sdk-js user :).
Keep up the great work.
Best Wishes,
