### ISSUE TITLE
Cannot read property 'removeAllListeners' of undefined

### ISSUE THREAD

**Issue by piuccio** [aws/aws-sdk-js#493]
Hi, I'm using this [grunt plugin](https://github.com/guardian/grunt-frequency-graph) to upload a file to an S3 bucket.

The AWS logic is in [aws.js](https://github.com/guardian/grunt-frequency-graph/blob/master/tasks/lib/aws.js).

It works fine on my machine, but when I try to use it on [TeamCity](https://www.jetbrains.com/teamcity/) I get this error.

```
Fatal error: Cannot read property 'removeAllListeners' of undefined
TypeError: Cannot read property 'removeAllListeners' of undefined
    at Request.cleanup (grunt-frequency-graph/node_modules/aws-sdk/lib/s3/managed_upload.js:466:25)
    at Request.callListeners (grunt-frequency-graph/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (grunt-frequency-graph/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (grunt-frequency-graph/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (grunt-frequency-graph/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (grunt-frequency-graph/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at grunt-frequency-graph/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (grunt-frequency-graph/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (grunt-frequency-graph/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (grunt-frequency-graph/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
```

Looking at the stack trace, this seems to be in the done callback, however the file was not uploaded.

Do you have any idea of what could cause the error? Or how I can get more information?

Thanks

**Comment by piuccio** [comment]
I figured out what's causing the error. Somewhere the following exception is thrown

```
{ [CredentialsError: Missing credentials in config]
  message: 'Missing credentials in config',
  errno: 34,
  code: 'CredentialsError',
  path: '~/.aws/credentials',
  syscall: 'open',
  time: Wed Feb 04 2015 16:53:08 GMT+0000 (GMT),
  originalError: 
   { message: 'Could not load credentials from SharedIniFileCredentials',
     errno: 34,
     code: 'CredentialsError',
     path: '~/.aws/credentials',
     syscall: 'open',
     time: Wed Feb 04 2015 16:53:08 GMT+0000 (GMT),
     originalError: 
      { errno: 34,
        code: 'ENOENT',
        path: '~/.aws/credentials',
        syscall: 'open',
        message: 'ENOENT, no such file or directory \'~/.aws/credentials\'' } } } error
```

**Comment by lsegal** [comment]
Looks like you don't have a shared credentials file, which is required by that plugin. I'm not sure why they are only checking environment and shared credentials-- you may want to open an issue with that project to simply use the default credentials provider which already checks in these locations. Until then, you can follow the [Getting Started Guide](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html) to configure credentials using the shared credentials file, or use the environment variables as per their documentation.

**Comment by piuccio** [comment]
:grin: I'm the author of that plugin. Honestly I didn't understand the documentation, how to use the default credentials provider. A snippet of code would have helped. I'll try to change that

Anyway the question is why on my machine I get a nice error message while on CI the message is hard to understand.

TeamCity is using node 0.10.24
Local machine uses 0.10.35

**Comment by lsegal** [comment]
@piuccio the default provider is just that-- the default. You don't need any special code to get the default provider, simply start calling AWS operations and it will look for configuration. This is described in the guide linked above.

As for the difference in error messages, perhaps this is more relevant to TeamCity? I've never used the tool, so I'm not sure if there is something related to its own error reporting setup-- that would be my first guess though. Perhaps it isn't catching a throw somewhere? Maybe the Node.js version is relevant? Have you tried upgrading TeamCity to use the latest Node.js release?

If you could provide a minimal reproduction that would be helpful to debugging this from the SDK's end.

**Comment by piuccio** [comment]
@lsegal off topic, how do i specify a different file for credentials using the default config?

Anyway, it's not related to the node version. The error `Cannot read property 'removeAllListeners' of undefined` happens when `validate` fails, the `Body` is a Buffer and the stream is chunked.

You can reproduce
* clone this repo https://github.com/guardian/frontend.git
* checkout branch `debug-frequency-graph` (it has extra logging)
* `npm install`
* (remember to use node 0.10.24)
* `grunt frequency_graph`

It takes a while (~3 minutes) and generates a file (~5MB) that is then sent to S3.

**Comment by lsegal** [comment]
> how do i specify a different file for credentials using the default config?

See [AWS.SharedIniFileCredentials](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html) documentation for information on how to specify a different file, but ideally you should not need to provide a different name. The reason the file is called a "shared" credentials file is because the file is shared among the CLI and all other SDKs when grabbing configuration. By checking for a different path you are losing the reusability of this file.

> (remember to use node 0.10.24)

If this is not related to the Node.js version, is there a reason that I need to reproduce with 0.10.24?

**Comment by piuccio** [comment]
oh sorry, any version is fine

**Comment by AdityaManohar** [comment]
@piuccio I was able to reproduce your issue with just a plain `s3.upload()`. The above commit fixes the error reporting issue. It does not fix the lack of credentials in your plugin.

Here is the output when I run `grunt frequency_graph`
```
Get file stats
======================================== 100% 0.0 seconds left
Get repository history
======================================== 100% 0.0 seconds left
Writing results to tmp/frequency_graph.html
{ [CredentialsError: Missing credentials in config]
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: Thu Feb 05 2015 18:17:57 GMT-0800 (PST),
  originalError:
   { message: 'Could not load credentials from SharedIniFileCredentials',
     code: 'CredentialsError',
     time: Thu Feb 05 2015 18:17:57 GMT-0800 (PST),
     originalError: { message: 'Credentials not set in /Users/aditm/.aws/credentials using profile nextgen' } } }
Fatal error: Missing credentials in config


Execution Time (2015-02-06 02:15:08 UTC)
loading tasks              2.6s  ▇▇▇▇ 2%
frequency_graph:files  2m 45.9s  ▇▇▇▇▇▇▇▇▇ 98%
Total 2m 49.3s
```
Let me know if this works for you, and feel free to re-open this issue if you continue to experience issues!

**Comment by AdityaManohar** [comment]
@piuccio Your plugin *also* seems to be working fine and picking up credentials. Since you've specified `profile: 'nextgen'` in `grunt-configs/frequency_graph.js` you will need to set up the same profile in your shared INI credentials file (~/.aws/credentials)

Here is what I was able to replicate using your code (logging credentials in `tasks/lib/aws.js`).
```ini
# ~/.aws/credentials
[nextgen]
aws_access_key_id=foo
aws_secret_access_key=bar
```
When I run `grunt frequency_graph`:
```bash
...
Get file stats
======================================== 100% 0.0 seconds left
Get repository history
======================================== 100% 0.0 seconds left
Writing results to tmp/frequency_graph.html
accessKeyId=foo
secretAccessKey=bar
...
```

**Comment by piuccio** [comment]
Thanks
