### ISSUE TITLE
Cognito Identity how to keep session on page change (next page)

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#498]
Hello,

Wanted to know if I go into another page utilizing the js sdk, utilizing a href, how would I get the current session the user is logged in with cognito? I'm in the next page and I want to keep the session alive from the user that already logged in to Google or Facebook.

Do I have to do the AWS.config.credentials = new AWS.CognitoIdentityCredentials(params); on the next page again? If yes then I have to pass over the id_token? Is this correct?

Best Regards,

**Comment by AdityaManohar** [comment]
> Do I have to do the AWS.config.credentials = new AWS.CognitoIdentityCredentials(params);

Yes, any JavaScript state that you had on your previous page will be lost when you make a synchronous HTTP request.

The AWS SDK however, caches the Cognito `IdentityId` in `localStorage`, so you will be refreshing credentials for the same identity. You will need to pass in the provider auth token when you create the new `CognitoIdentityCredentials` object.

Most provider SDKs will manage the auth token for you across synchronous requests, but you will have to check the provider documentation for the correct API to check the login status of the user.

* For Login With Amazon, calling `amazon.Login.authorize()` will return a valid cached token, as long as the user has not logged out, or the session has not expired. I suspect it is similar for Google.
* For Facebook you can call `FB.getLoginStatus()` to return a token if the user has already logged in.

I would recommend checking out the API documentation for each of the providers you are using for more information on how to main session state.

**Comment by ramonck** [comment]
Thank you Aditya.

**Comment by awsong** [comment]
@AdityaManohar , does amazon.Login.authorize() or FB.getLoginStatus() have to be called from customer's browser or can it be called from my server?

**Comment by AdityaManohar** [comment]
Typically this is called from a browser client.

I don't see why it can't be called from a javascript server though. That might need some more investigation, but theoretically, it seems possible.
