### ISSUE TITLE
Add timeout setting per API call

### ISSUE THREAD

**Issue by nilskassube** [aws/aws-sdk-js#5]
It should be possible  to add timeout settings per API call. Please also document how to best handle timeouts globally for all AWS SDK API calls.

**Comment by syahmeds** [comment]
Suppose the download takes longer than 5000 ms, does the connection get aborted? It doesn't seem to work that way. Is there a way to do that?

**Comment by datfinesoul** [comment]
I agree with @syahmeds, I'm doing a test, setting the timeout to 1ms, but it takes anywhere from 10-20 seconds to get a "Connection timed out after 1ms" message back.  It would be nice if the connection gets aborted when the timeout is reached, or if `httpOptions.timeout` is not the proper way to get the connection terminated, is there another option I'm not seeing that does abort the connection?

**Comment by bhudgens** [comment]
We identified these delays in the retry logic and not in the http session.  Setting "maxRetries: 1" as a test should result in the behavior expected.  Docs [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html)
