### ISSUE TITLE
AWS S3 constructor ignoring passed accessKeyId & secretAccessKey

### ISSUE THREAD

**Issue by zain-qubit** [aws/aws-sdk-js#501]
I use the S3 constructor in the following way:
`var s3Options = {
accessKeyId: "my key",
secretAccessKey: "my secret",
region: "eu-west-1"
};`
`new AWS.S3(s3Options)`
But it still tries to look for credentials in ~.aws/credentials file.
I was under the impression that passing hardcoded keys would skip the traversal of default credentials provider chain.
I understand passing hardcoded keys is not a good practice, but it should work at least.

**Comment by lsegal** [comment]
I can't seem to reproduce this behavior. S3 accepts the keys for me:

```js
var AWS = require('aws-sdk');
var s3 = new AWS.S3({accessKeyId: 'xxx', secretAccessKey: 'yyy'});
console.log(s3.config.credentials);
```

Output:

```js
{ expired: false,
  expireTime: null,
  accessKeyId: 'xxx',
  sessionToken: undefined }
```
