### ISSUE TITLE
JavaScript SDK build on WIndows does not include any AWS service

### ISSUE THREAD

**Issue by oz-boots** [aws/aws-sdk-js#505]
Building the SDK on a Windows 8 system with node.js v0.12.0 does not include the AWS services in the output SDK js file.

For further details see https://forums.aws.amazon.com/thread.jspa?threadID=171478&tstart=0

**Comment by AdityaManohar** [comment]
@oz-boots This should fix the builder on a Windows box. Feel free to reopen this issue if you continue to have problems building, or have any other questions.

Thanks for reporting!
