### ISSUE TITLE
Download file using Javascript

### ISSUE THREAD

**Issue by AlaRuba** [aws/aws-sdk-js#509]
Hi,

I can get the data from my S3 bucket. However, the file is in memory. I'm wondering how to download the file. I don't see any documentation on this.

```
s3.getObject(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else    {
         console.log(data)
    }          // successful response
  });
```

Thanks in advance.

**Comment by lsegal** [comment]
Browsers do not currently allow programmatic access of writing to the filesystem, or at least, not in the way that you would likely want. My recommendation would be to generate a signed url (see [S3.getSignedUrl()](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property)) and put that in a HTML link and/or navigate to that URL in an iframe the way that [auto-downloader pages work](http://stackoverflow.com/questions/156686/how-to-start-automatic-download-of-a-file-in-internet-explorer).

**Comment by odeke-em** [comment]
If doing this in NodeJS or io.js on the server side, this is how I do it.
```javascript
...
var fs = require('fs');

var outStream = fs.createWriteStream(LOCALPATH);
var awsStream = s3.getObject(params).createReadStream();

awsStream.pipe(outStream);

// Then monitor the events
awsStream.on('end', function() {
    // Done here
}).on('error', function(err) {
    // Handle your error
});
```

**Comment by AdityaManohar** [comment]
I'm closing this issue out as the question seems to be answered. Feel free to re-open this issue, or open another issue if you have other questions.
