### ISSUE TITLE
AWS.SNS GCM no error but no message delivered

### ISSUE THREAD

**Issue by miickel** [aws/aws-sdk-js#510]
Hi,

I'm using SNS to send notifications to iOS and Android devices. I've gotten it to play nicely on iOS, but not on Android. :anguished: 

I use two Application ARNs, one for iOS and one for Android. I can publish messages to the Android ARN using the AWS dev console, but only when selecting 'Use platform specific JSON message dictionaries'.

This makes me think that the node.js AWS SDK does not use platform specific JSON message dictionaries for Android, is that right?

Shouldn't the options to AWS.SNS.publish look the same, no matter which platform I'm sending the message to?

Here's the options I use with publish():

    ({
      TargetArn: 'android or ios arn',
      Subject: 'test',
      Message: 'hello',
    })

Sending the message gives no error, and I get back ResponseMetadata and MessageId, but still no message delivered to the android device.

Any help would be greatly appreciated!

**Comment by AdityaManohar** [comment]
From what I read in the [SNS Publish documentation](http://docs.aws.amazon.com/sns/latest/APIReference/API_Publish.html), you will need to send a [platform specific payload](http://docs.aws.amazon.com/sns/latest/dg/mobile-push-send-custommessage.html) to mobile devices.

For Android your messsage would need to look like this:
```javascript
var message = { 
  GCM:{
    data:{
      message:'Foo bar!',
      url:'www.example.com'
    }
  }
}

var params = {
  TargetArn: 'arn:aws:sns:us-west-2:123456789012:endpoint/GCM/foobar/1234567890'
  Subject: 'foo',
  Message: JSON.stringify(message)
}
```

Let me know if this helps!

**Comment by miickel** [comment]
@AdityaManohar thanks! That did not work either. However, I got it to work. :pray: First, I had to set `MessageStructure` to `'json'`. Then I formatted the message like this, so that quotes got escaped by stringify:
```javascript
  var message = JSON.stringify({
    "GCM": util.format('{"data":{"message":"%s"}}', 'Foo bar!')
  });
```

**Comment by andRyanMiller** [comment]
@miickel This saved me - thank you so much for following up with your solution.

**Comment by biranchi2018** [comment]
I am trying from from AWS Console, but still its not working.
![sns to gcm](https://user-images.githubusercontent.com/191425/48887973-233ed880-ee6c-11e8-9ef9-93eeb99424ba.png)
