### ISSUE TITLE
Route53 CreateHostedZone specification

### ISSUE THREAD

**Issue by polythene1337** [aws/aws-sdk-js#513]
Hi,
This should probably be tagged as feedback as it's only related to the documentation.

The documentation for CreateHostedZone is a bit misleading unless you read the fine print.
The example states:
```javascript
HostedZoneConfig: {
    Comment: 'STRING_VALUE',
    PrivateZone: true || false
  },
```
But if you continue reading under **Parameters** it says:
> PrivateZone — (Boolean)
> A value that indicates whether this is a private hosted zone. The value is returned in the response; do not specify it in the request.

The aws-cli documentation does not mention the PrivateZone parameter at all:
> Config -> (structure)
> A complex type that contains the Comment element.
> Comment -> (string)
> An optional comment about your hosted zone. If you don't want to specify a comment, you can omit  the  --hosted-zone-config and Comment elements from the XML document.

Wouldn't it make sense to omit the PrivateZone from the request documentation completely and only reference it in the response documentation to avoid confusion or am I by chance missing some reasoning that would validate the reference in the request documentation?

/ Carl

**Comment by AdityaManohar** [comment]
@polythene1337 

Thanks for reporting this! All of our documentation is auto generated and I will reach out to the Route53 service team to report / clarify this parameter.

**Comment by AdityaManohar** [comment]
@polythene1337 
I'm closing this issue out because the documentation needs to be fixed upstream by the Route53 team. I would recommend opening an issue on the [Amazon Route53](https://forums.aws.amazon.com/forum.jspa?forumID=87) forums.

Feel free to reopen this issue, or open another issue if you have other questions.
