### ISSUE TITLE
Config Encapsulation

### ISSUE THREAD

**Issue by AnonymousOpposum** [aws/aws-sdk-js#516]
I'm building a service that allows users to interact with the Amazon Cloud through a GUI. It's being built as SaaS in Node.js. With out of the box Node.js architecture, every user session would use the same Node.js thread on the app server. Currently, the AWS SDK Node.js module returns a singleton namespace. So, every user session uses the same instance of the AWS SDK in the thread.

This means that, unless one sets credentials and region before every single request to Amazon, each user would inadvertently  use the credentials and region config of the last user to have their credentials and region set in the singleton.

For security, I would much rather have some sort of constructor that allows me to create one instance of the AWS SDK for every user session.

Is there already a feature somewhere in the SDK that allows me to create a new class instance using a constructor? If not, would anyone be opposed to me writing a version of the SDK that returns a constructor rather than a singleton namespace?

**Comment by AnonymousOpposum** [comment]
Ah, wait. I think I found what I'm looking for [here](https://github.com/aws/aws-sdk-js/blob/master/doc-src/guide/node-configuring.md)

I'll come back and close once I've done a little testing.

**Comment by AnonymousOpposum** [comment]
Is it possible to decouple the config object of each service class from the global config object? I would like it if it were possible to make sure there were absolutely no way config settings leak from one user session to another.

**Comment by lsegal** [comment]
Can you clarify if you're allowing users to execute arbitrary code in this process? If not, you can guarantee that no global config ever comes through by wiping out the global object before constructing any client:

```js
AWS.config = {};
var c = new AWS.S3();
```

**Comment by AnonymousOpposum** [comment]
Regarding arbitrary code, what users can and can not run, I'm creating one use interface element in my GUI for each method in the Node.js AWS API. After the user logs into my app, they can interact with the GUI, triggering calls to a restful interface on my server, bound to a wrapper of aws-sdk-js.

The wrapper provides the same interface as the clients in the aws-sdk namespace, but is chainable, promise based, and uses verbs like `fetch` instead of `describe` to match internal naming standards at the company.

After finding the documentation above, I'm trying something like this for the wrapper's constructor:

    var AWS = require("aws-sdk");

    function Interface( credential, region ) {
      
      this.ec2 = new AWS.ec2({ ... });
      [ ...other services are instantiated in the same way... ]

      this.fetchVpc = fetchVpc;

      function fetchVpc() {

         this.ec2.describeVpcs( ... );

         ...
      }
    }

    module.exports = Interface;


The wrapper is instantiated once per user session in the app server.

I'll add a line that clobbers `AWS.config` on instantiation of the wrapper as well, and will write back with the result.

Thank you for the quick response! I appreciate it.

**Comment by lsegal** [comment]
FYI another option would be to use [Object.defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) to define a non-writable constant to `AWS.config` such that you could never accidentally re-write the object unless you tried really hard:

```js
Object.defineProperty(AWS, 'config', { get: function() { return {} } });
```

That way you wouldn't need to explicitly clobber it at each call and you could ensure that your process doesn't accidentally try to rewrite that object, as the JS interpreter should be guarding against any modifications:

```js
> AWS.config
{}
> AWS.config = {value: 1}
{ value: 1 }
> AWS.config
{}
> AWS.config.x = 1
1
> AWS.config
{}
> Object.defineProperty(AWS, 'config', { value: {x: 1} });
TypeError: Cannot redefine property: config
```

**Comment by AnonymousOpposum** [comment]
Oh, wow. `Object.defineRroperty` is a beautiful, beautiful thing! Thank you; I'll try that.

**Comment by AnonymousOpposum** [comment]
Using `Object.defineProperty` does the trick. Thank you!

**Comment by AnonymousOpposum** [comment]
After looking a little closer, it seems clobbering `AWS.config` isn't isolating the config data for different client instances afterall.

Here are the steps to reproduce:

 1. ) Create two AWS accounts, Account A and Account B
 2. ) Put the credentials for Account A in your `~/.aws/credentials` file under `[default]`
 3. ) Put the credentials for Account B in your project's root directory, `repo/accountB.js`
 4. ) Put [this Gist][1] in `repo/index.js`
 5. ) Run `node index.js`
 6. ) Observe that `index.js` returns data from Account A
 7. ) Delete `~/.aws/credentials`
 8. ) Run `node index.js`
 6. ) Observe `Missing credentials in config` error

I think maybe setting `AWS.config` to an immutable object does not ensure config encapsulation between client instances? Also, it seems it is not possible to use the `aws-sdk` node module without having a valid, global account registered in `~/.aws/credentials`?


  [1]: https://gist.github.com/AnonymousOpposum/927702a83d0948a3b69a

**Comment by AnonymousOpposum** [comment]
I can see that credentials aren't meant to be passed directly to `AWS.EC2`. I wonder where credentials can be passed to make sure a call to  `new AWS.EC2()` knows to use them.

**Comment by AnonymousOpposum** [comment]
I tried using [this Gist][1] in `repo/index.js`, instead. The difference being I use `AWS.Credentials( accountB )` to generate credentials that are then assigned to `new AWS.EC2( region ).config.credentials`

Repeating Steps 7 and 8 above with that gist returns an `AWS was not able to validate the provided access credentials` error.

So, so close now, I think. I wonder what I'm missing.


  [1]: https://gist.github.com/AnonymousOpposum/e7bd15754e5576bafec1

**Comment by AnonymousOpposum** [comment]
We were prepending `aws` on all the keys in `accountB` ( So, `accountB.accessKeyId ` was actually found on `accountB.awsAccessKeyId ` )... No longer doing that, everything works fine now.

 ...time for a cup of coffee and a good cry. Lol

Sorry about that.
