### ISSUE TITLE
More parameters for filtering listObjects

### ISSUE THREAD

**Issue by piuccio** [aws/aws-sdk-js#517]
Filtering [listObject](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property) can only be done with `Prefix`.

Would it be possible to add something like
`Since` -> all objects modified since that data
`Reverse` -> list 1000 items starting from the bottom

In my bucket I have objects like this
```
2014-01-01-time.json
2014-01-02-time.json
2014-01-03-time.json
...
2015-02-23-time.json
2015-02-23-time.json
```
and I have multiple objects with the same date but different time, certainly more than 1k.

What I'd like to get is the objects modified in the last `X`days. These are at the bottom of the list, with the current api my options are
*  list them all, which seems quite expensive.
* hack around the `Prefix` and make multiple calls for the `year-month` i'm interested in.

Any thoughts?

**Comment by AdityaManohar** [comment]
@piuccio 
You can you a combination of `Prefix` and `Marker` to filter your keys. Only keys that are lexicographically after the `Marker` will be listed Here are some examples:

```javascript
var bucket = new AWS.S3({params: {Bucket: 'foo'}});
var callback = function(err, data) { if (err) console.log(err); else console.log(data);}

// Objects since 2015-02-23
bucket.listObjects({Prefix: '2015-02', Marker: '2015-02-23-00:00:00'}, callback);

// Objects after 4:00 p.m on 2015-02-23
bucket.listObjects({Prefix: '2015-02-23', Marker: '2015-02-23-16:00:00'}, callback);
```
The S3 API documentation describes this in further detail: [ListObjects](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html).

If you want something even more sophisticated, then you can also use [JMESPath](https://www.npmjs.com/package/jmespath) to filter through a fetched list of objects. 

Let me know if this helps!

**Comment by odeke-em** [comment]
Thank you @AdityaManohar, to build upon your response, don't forget to use some sort of pagination since @piuccio you say you have > 1K objects.
The response returns values  of interest
```
IsTruncated (type: boolean)
NextMarker  (type: string)
```
If `IsTruncated` is set, repeat almost the previous query performed except this time set `Marker` to the value retrieved from `NextMarker`.

I could be wrong so feel free to educate me.

**Comment by AdityaManohar** [comment]
Closing this issue since there are a couple of solutions suggested. Feel free to reopen this issue if you have other questions.

**Comment by vladejs** [comment]
How about returning a list of filtered keys by a random text?

Given the text: was. Return all this files:

- bucketName/itwasfine.txt
- bucketName/alreadyinthere.was.txt

And exclude everything else.

My goal is to create a client side table with a fuzzy search functionality on the bucket's keys, including incremental pagination.

How to achieve that without getting all objects on the bucket?

**Comment by tomasdev** [comment]
> @piuccio
> You can use a combination of `Prefix` and `Marker` to filter your keys. Only keys that are lexicographically after the `Marker` will be listed. Here are some examples:
> 
> ```js
> var bucket = new AWS.S3({params: {Bucket: 'foo'}});
> var callback = function(err, data) { if (err) console.log(err); else console.log(data);}
> 
> // Objects since 2015-02-23
> bucket.listObjects({Prefix: '2015-02', Marker: '2015-02-23-00:00:00'}, callback);
> 
> // Objects after 4:00 p.m on 2015-02-23
> bucket.listObjects({Prefix: '2015-02-23', Marker: '2015-02-23-16:00:00'}, callback);
> ```
> 
> The S3 API documentation describes this in further detail: [ListObjects](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html).
> 
> If you want something even more sophisticated, then you can use [JMESPath](https://www.npmjs.com/package/jmespath) to filter through a fetched list of objects.
> 
> Let me know if this helps!

the PHP SDK supports jmespath via `$result->search()` - is there any plan in having nodejs also accept a JMESPath on the AWS-SDK library?
