### ISSUE TITLE
Send Message to SNS Topic

### ISSUE THREAD

**Issue by RavikiranDasari** [aws/aws-sdk-js#518]
Hello,

I am trying to send a message to SNS topic in webMethods 8.2. I am using the AWS SDK to generate the signature. I have passed the correct Access and Secret Keys and used the method called "Publish".

Unfortunately I am getting the below error-
"<Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>"

Got stuck here. Any help is much appreciated.

Thanks,
Ravi.

**Comment by RavikiranDasari** [comment]
Sorry, Correction in my post.

Signature Methode - HmacSHA256
Action = Publish

**Comment by AdityaManohar** [comment]
Which version of the SDK are you using? Also which version of Node.js is this server running? Can you provide some sample code that you are using?

My initial guess would be the time on your server is not correctly synchronized.

**Comment by AdityaManohar** [comment]
I'm going to mark this as closed since there hasn't been any recent activity. Feel free to reopen this issue or another issue if you continue to run into problems.
