### ISSUE TITLE
Update README to include bower install instructions

### ISSUE THREAD

**Issue by demisx** [aws/aws-sdk-js#519]
Currently, it appears that bower is not one of the supported methods of installation.

**Comment by AdityaManohar** [comment]
@demisx 
Bower installation instructions have been added to the [README](https://github.com/aws/aws-sdk-js/blob/master/README.md) as well as the [developer guide](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-intro.html). The changes to the developer guide will go out with our next release.

Thanks for reporting!
