### ISSUE TITLE
S3.getObject fails with version 2.1.13 & 2.1.14

### ISSUE THREAD

**Issue by polythene1337** [aws/aws-sdk-js#521]
Hi,

We just found an issue with aws-sdk version 2.1.14 & 2.1.13.
We do a simple s3.getObject and what happens is that the process starts consuming 100% CPU and eventually all available memory. Running the same script with 2.1.12 works as expected though.
We had the same behaviour locally on Mac OSx as on EC2 (Amazon Linux).
Not sure what's actually happening and we're kind of stressed to fix the issue at the moment but I'll gladly provide any additional information you might need.

Sample code:
> npm install aws-sdk@2.1.14
> npm install aws-sdk@2.1.12
```javascript
var aws = require('aws-sdk');
var s3 = new aws.S3();
var params = {
    "Bucket": "bucket",
    "Key": "my_key"
};
s3.getObject(params, function (error, response) {
    console.log('error', error);
    console.log('response', response);
});
```

Br,
Carl

**Comment by lsegal** [comment]
@polythene1337 thanks for reporting this! We're working on a fix right now and will have a patch release out shortly for this regression.

**Comment by AdityaManohar** [comment]
@polythene1337 
This fix is out in master. I will cut a patch release shortly.

**Comment by AdityaManohar** [comment]
@polythene1337 
I just pushed a release. You can now use `v2.1.16` from `npm`. Let me know if this fixes the issue for you.

Thanks again for reporting!

**Comment by trozware** [comment]
When using Lambda, what do I have to specify to get this new version?
I was using 

    var s3 = new aws.S3({
    	apiVersion: '2006-03-01'
    });

and then tried:

    var s3 = new aws.S3({
    	apiVersion: '2014-11-11'
    });

But both fail at s3.getObject for any large files.

Or is this the line I need to change?

    var aws = require('aws-sdk');

Regards,
Sarah

**Comment by AdityaManohar** [comment]
@trozware 
You'll have to update to the latest version of the SDK:
```sh
$> npm update aws-sdk
```
Let me know if this helps.

**Comment by trozware** [comment]
My script is a Lambda script running on the AWS servers, using the AWS-SDK installed there.
How can I get that updated?

**Comment by AdityaManohar** [comment]
Unfortunately there is no way to force an update of the SDK in the Lambda environment. You can open an open an issue on the [AWS Lambda Forums](https://forums.aws.amazon.com/forum.jspa?forumID=186) and let them know about it. I will also try to talk to the Lambda team internally.

In the meantime you can also upload a bundle containing the SDK and its dependencies. Doing this will `require` your local bundled version.

Your bundle package should contain the node_modules directory:
```
handler.js
node_modules/
|-- aws-sdk/
|---- node_modules/
|------ //SDK dependencies
```
Hope this helps.

**Comment by trozware** [comment]
Thanks very much.
I got here from the Lambda forums, so this is already an issue there, but I will add to the topic.

Meanwhile I will experiment with creating and uploading a bundle.

**Comment by trozware** [comment]
And for anyone else waiting for the fix, here is the response I got on the forum:

"We're working to deploy the corrected JavaScript SDK in AWS Lambda now. I'll update this thread again by 9pm Pacific Time on progress. Apologies for the problems this is causing our users."

Posted on: Mar 5, 2015 6:58 PM

**Comment by AdityaManohar** [comment]
@trozware 
Lambda seems to have upgraded the AWS SDK version to `v2.1.16`. You should be able to use the latest version of the SDK in Lambda now.

**Comment by trozware** [comment]
@AdityaManohar Thanks for your help, it all appears to be working correctly now.

**Comment by polythene1337** [comment]
I've tested with 2.1.16 and it works like a charm. Thanks for fixing the
issue so fast as always :)

**Comment by AdityaManohar** [comment]
@polythene1337 and @trozware 
I'm glad you got it working. Thanks again for reporting!
