### ISSUE TITLE
SES example?

### ISSUE THREAD

**Issue by alessioalex** [aws/aws-sdk-js#524]
I find the documentation really weird, I would have expected it to be in the Github wiki really. That's how 90% of the projects do it from what I've seen (just my opinion).

The fact of the matter is that I could not find a simple SES example unfortunately. Can you point me in the right direction? I would prefer a code sample and not an API link. Thanks!

**Comment by lsegal** [comment]
What kind of examples are you looking for? If just you're looking to send mail, you can look at the example for [AWS.SES.sendEmail()](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendEmail-property) which is part of the API documentation. Each operation includes sample code at the API level, which should help you get started. If you're looking for a higher level overview of how to use the API, you might want to check out the [Amazon SES Developer Guide](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/Welcome.html), which provides more information about how identities work and which operations to use. 

Hope that helps!

**Comment by AdityaManohar** [comment]
I'm marking this as closed because there hasn't been any recent activity. Feel free to reopen this issue or open another issue if you have any other questions.
