### ISSUE TITLE
Provide decent expiration/cache headers AWS JS SDK

### ISSUE THREAD

**Issue by ondruska** [aws/aws-sdk-js#536]
Can you please set some expiration (Expires = now + X) and/or caching (Cache-Control = public,max-age=X,s-maxage=X") headers to AWS JS SDK? Thanks, relates to #535

**Comment by AdityaManohar** [comment]
@ondruska We are looking into this. Thanks for reporting!

**Comment by kaibo-ondruska** [comment]
For reference, should anyone need cacheable version, look elsewhere (cdnjs, etc.). Pity because it is so easy for AWS to set these headers themselves.
