### ISSUE TITLE
"Optimistic Locking With Version Number"  support for dynamodb

### ISSUE THREAD

**Issue by chetandhembre** [aws/aws-sdk-js#540]
Hi, 
   I was reading about optimistic locking for dynamodb here (http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/JavaVersionSupportHLAPI.html), is it implemented in node.js sdk aws ? if not how can i implement it ? 

Can any one help me here ?

**Comment by AdityaManohar** [comment]
@chetandhembre 
The SDK currently doesn't have any optimistic locking abstractions for DynamoDB. I will mark this as a feature request, because this will involve developing a high level abstraction that supports this behavior.

**Comment by AdityaManohar** [comment]
@chetandhembre 
I would recommend opening a feature request with the [DynamoDB Document SDK](https://github.com/awslabs/dynamodb-document-js-sdk) project.

I'm marking this as closed in favor of the feature request that you can open here: [awslabs/dynamodb-document-js-sdk/issues](https://github.com/awslabs/dynamodb-document-js-sdk/issues).

Feel free to open another issue if you have any questions.

**Comment by jasonfill** [comment]
I just filed the issue over on the awslabs/dynamodb-document-js-sdk/issues repo but looks like that repo has been depreciated for the AWS.DynamoDB.DocumentClient which is part of this this main js sdk.  Unless I am missing something, should this issue be re-opened here?

**Comment by benoittgt** [comment]
Could we reopen this issue ?

**Comment by leggiero** [comment]
Currently I'm using Java Lambda's instead of Node.js ones, just because of the lack of Optimistic Locking feature, that is a crucial point on some projects that I'm working on.

Could we reopen this issue?

**Comment by youcangetme** [comment]
:+1: this would be nice to have in Lambdas with JavaScript/Node.js

**Comment by jeskew** [comment]
This thread contains some outdated information about the DynamoDB document client, so I'll leave this closed as a duplicate in favor of #1422. Please refer to #1422 for current discussion on this feature request.
