### ISSUE TITLE
Locking to API Version 2009-04-15

### ISSUE THREAD

**Issue by gagecarto** [aws/aws-sdk-js#546]
I'd like to use the JavaScript SDK along with a SimpleDB

The docs tell me to lock the api at 2009-04-15
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SimpleDB.html

Trying simple examples from the above docs result in errors like
"AWS.SimpleDB is not a constructor"

If I load the SDK using the most recent 2.1.17, I don't see the 2009-04-15 included.
https://sdk.amazonaws.com/js/aws-sdk-2.1.17.js

Questions
• Is it safe to still use the 2009-04-15 version?
• Should I just fork from the link below? 
https://github.com/aws/aws-sdk-js/blob/ebc438876945d55707d84b8986bd2fc3aa3004e9/apis/sdb-2009-04-15.normal.json

**Comment by AdityaManohar** [comment]
Simple DB is not included in the default hosted build of the SDK. Here are a list of [supported services included in the hosted build](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-services.html#Supported_Services). You can of course choose to [build your own version of the SDK](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-building.html) if your are using it in an environment where you have explicit control of CORS configuration.

Hope this helps!

**Comment by gagecarto** [comment]
I am a total n00b when it comes to building my own SDK versions. 

Could I just include the source of the 2009-04-15.. Something ugly like below or would that be a total failure?

<script src="https://sdk.amazonaws.com/js/aws-sdk-2.1.17.min.js"></script> 
<script src="https://raw.githubusercontent.com/aws/aws-sdk-js/ebc438876945d55707d84b8986bd2fc3aa3004e9/apis/sdb-2009-04-15.normal.json"></script>

**Comment by AdityaManohar** [comment]
@gagecarto that would not work.

Building your own SDK version is actually quite simple. All you need to is `git clone` this repository and `npm install` the dependencies (assuming you have Node.js installed). This is described in detail in the developer guide here: [Building the SDK for Use in the Browser](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-building.html).

I'm curious about where you are using this actually. Are you running this in an environment which does not enforce CORS?

**Comment by gagecarto** [comment]
@AdityaManohar 

The environment I am working in does enforce CORS. Why do you ask? Is there a different approach I should be taking entirely?

**Comment by AdityaManohar** [comment]
@gagecarto 
Simple DB currently does not support CORS requests. The hosted browser version of the SDK includes support for all services that do support CORS. I would recommend opening an issue on the [SimpleDB Forums](https://forums.aws.amazon.com/forum.jspa?forumID=38) to request CORS support. 

As an alternative, you could also use DynamoDB if your application is talking directly to services from the browser.

I hope this helps.

**Comment by lsegal** [comment]
Marking this as closed since SimpleDB does not support CORS and is therefore not part of the default hosted browser build. You *can* build your own version with the instructions that @AdityaManohar provided above, but note that the CORS restriction is enforced by the browser and the service itself, and there is unfortunately nothing the SDK can do to make things work without CORS enabled. I would recommend posting a feature request for CORS on the forums as Aditya suggested. Hope that helps!
