### ISSUE TITLE
S3 Upload data.Location duplicates itself

### ISSUE THREAD

**Issue by zackehh** [aws/aws-sdk-js#553]
When uploading using a snippet like this (taken from the AWS docs), the data.Location field in the response is giving an incorrect URL. It is repeating certain sections of the path. This is on the latest npm bundle as of today; `"aws-sdk": "^2.1.20"`. I am working on OS X 10.10.2, should that matter.

This should reproduce it:

```javascript
var body = fs.createReadStream('my-file.txt').pipe(zlib.createGzip());

var s3obj  = new (require('aws-sdk')).S3();

s3obj.upload({
    Bucket: 'my-bucket',
    Key: 'path/to/my-file.txt.gz',
    ACL: 'public-read',
    Body: body
}, function(err, data) {
    if (err) console.log("An error occurred", err);
    console.log("Uploaded the file at", data.Location);
    // https://my-bucket.s3-us-west-2.amazonaws.com/path/to/my-file.txt.g/path/to/my-file.txt.gz
});
```

The logged Location is actually `https://my-bucket.s3-us-west-2.amazonaws.com/path/to/my-file.txt.g/path/to/my-file.txt.gz`, which is clearly incorrect.

**Comment by lsegal** [comment]
I just tried the code you provided for a small file (10 bytes) and a large file (29MB) on 2.1.20 / OSX 10.10 and cannot seem to reproduce that behavior. Have you run your test with the code above, or is there something else required to reproduce this?

What version of Node.js are you using?

**Comment by iwhitfield** [comment]
@lsegal I'm using v0.10.36, and the file was only a few hundred KB. If you want me to try it out on another version of node (perhaps 0.12.x), I can do so.

**Comment by lsegal** [comment]
@iwhitfield I was testing on 0.10 as well, but I could not reproduce with a file of that size. Have you tried the above code as provided, or is there something else that is needed to reproduce?

**Comment by silveur** [comment]
I'm experiencing exactly the same issue where an mp3 file 1.mp3 becomes is returned in the data field with a strange location: 
https://mybucket.s3-eu-west-1.amazonaws.com/1.mp/1.mp3

Yesterday seemed to be fine though... I don't really know. My version of the aws-sdk is latest 2.1.50

**Comment by iwhitfield** [comment]
@silveur when I experienced it, it was also fine one minute and changed the next - I think maybe it's an S3 issue or something? As I mentioned above, the snippet which reproduced it suddenly stopped working.

I'll reopen this just so that someone can follow up if they deem necessary.

**Comment by AdityaManohar** [comment]
@iwhitfield I haven't been able to replicate the issue with the code posted above. Do you have any code/test conditions that can help reproduce the issue?

**Comment by iwhitfield** [comment]
@AdityaManohar that's sort of the point - the above code **did** reproduce it for a while, but then it suddenly stopped - exact same code (I triple checked). After reading what @silveur posted, it appears this could be an intermittent issue, which could very well be on the S3 server side. I just re-opened this in case anyone wants to follow it up in the code.

**Comment by christianhaller** [comment]
same here!

It isconcatenating the data.Location string with itself.

**Comment by lostcolony** [comment]
I'm seeing this now. Though it's only concatenating -part- of the string. This is what I'm firing - 

var saveImageToS3 = function(name, buffer, callback) {
	console.log(name);
	var params = {Bucket: '(my_bucket)', Key: name, Body: buffer};
	s3.upload(params, {}, function(err, data) {
		console.log(data);
		return callback(err, "");
	});
}


In my case, name is "pro-images/1.jpeg". What I'm getting back is https://(my_bucket).s3-us-west-2.amazonaws.com/pro-images/1.jpe/pro-images/1.jpeg


Thankfully I can work around it since the URL is well known after I get the region off, but this is...really problematic.

**Comment by iwhitfield** [comment]
Yeah, looks like it trims the last character of the actual location, then dups the dir tree once more.

**Comment by AdityaManohar** [comment]
@lostcolony Can you provide the exact size of the file you are uploading in bytes? Can you also enable logging in the SDK as follows:

AWS.config.update({
  logger: console
});

I'd specifically like to know if the request is being retried. Thanks!

**Comment by lostcolony** [comment]
Hmm. Now I'm unable to reproduce, but I'm seeing 0 retries. It may be an issue with AWS itself?

**Comment by AdityaManohar** [comment]
@zackehh @lostcolony @silveur I was able to reproduce this by creating a bucket in a region that is not `us-east-1` and configuring my `AWS.S3` client to use `us-east-1`. 

I should have a fix out for this soon. Thank you for reporting and reopening!
