### ISSUE TITLE
Presigned URL returns a 403 when sending a Content-Type

### ISSUE THREAD

**Issue by shamoons** [aws/aws-sdk-js#557]
Okay, so first I am generating the presigned url in Node.js, via

```
  AWS.config.credentials = new AWS.Credentials 'myKey', 'mySecret'

  s3 = Promise.promisifyAll new AWS.S3()
  filename = "#{req.body.EntityId}_#{req.body.filename}"
  s3.getSignedUrlAsync 'putObject',
    Bucket: 'mybucket'
    Key: filename
    Expires: 60 * 20 # 20 minute expiration
  .then (presigned_url) ->
    res.json
      data:
        type: 'presigned-url'
        url: presigned_url
  .catch (err) ->
    next err
```

Easy enough, it returns a URL like `https://s3.amazonaws.com/mybucket/1_myfile?AWSAccessKeyId=myKey&Expires=1427993282&Signature=tzxdB4%2FFES81KgP1mBiwrhbcu6w%3D`

If I curl a file to it, it works just fine. However, using AngularJS I am trying to PUT a file up. The response I'm getting is:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
   <Code>SignatureDoesNotMatch</Code>
   <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
   <AWSAccessKeyId>mykey</AWSAccessKeyId>
   <StringToSign>PUT

multipart/form-data
1427992617
/mybucket/1_myfile</StringToSign>
   <SignatureProvided>dEyHSGBGcSmCfsZ1ahPryYTaB0U=</SignatureProvided>
   <StringToSignBytes>50 55 54 0a 0a 6d 75 6c 74 69 70 61 72 74 2f 66 6f 72 6d 2d 64 61 74 61 0a 31 34 32 37 39 39 32 36 31 37 0a 2f 6d 6f 6e 65 67 72 61 70 68 2e 64 65 76 2e 75 70 6c 6f 61 64 73 2f 31 5f 6d 79 66 69 6c 65</StringToSignBytes>
   <RequestId>F2C56B03E9F27E3F</RequestId>
   <HostId>4sC6jReptppcxmE5yb5MvcZ70cB/gC0obCMEZHI+2zC/qqNFtxHd2wU2+niCHBHV</HostId>
</Error>
```

![g3ulh](https://cloud.githubusercontent.com/assets/1019677/6968427/bb3572e4-d934-11e4-8330-4392a95f4abf.png)
I've also included my Request Headers.

So why is it that when I upload via a web client to the URL, it returns a 403 error?

**Comment by AdityaManohar** [comment]
@shamoons 
This seems like it is related to #547. It looks like your AngularJS code is posting the entire form to the signed url. You should instead only upload the file to the signed URL.

**Comment by shamoons** [comment]
@AdityaManohar I don't think that I'm posting the form. If you look at the data I'm sending:

![monegraph_explorer](https://cloud.githubusercontent.com/assets/1019677/6969802/608efbac-d93f-11e4-9235-343c518cd1c7.png)

It's not a form data

**Comment by AdityaManohar** [comment]
Would you be able to share a full wire trace of your request?

**Comment by shamoons** [comment]
How would I get that going?

**Comment by AdityaManohar** [comment]
@shamoons 
I missed this in the sample code that you provided. It looks like you are not specifying a `ContentType` when generating a signed URL. You will need to specify the `ContentType` when generating a signed URL and then set the `Content-type` header when you PUT to the signed URL.

I hope this helps!

**Comment by shamoons** [comment]
@AdityaManohar tried that. In my generation code, I have
```
  AWS.config.credentials = new AWS.Credentials 'myKey', 'mySecret'

  s3 = Promise.promisifyAll new AWS.S3()
  filename = "#{req.body.EntityId}_#{req.body.filename}"
  s3.getSignedUrlAsync 'putObject',
    Bucket: 'mybucket'
    Key: filename
    Expires: 60 * 20 # 20 minute expiration
    ContentType: 'image/png'
  .then (presigned_url) ->
    res.json
      data:
        type: 'presigned-url'
        url: presigned_url
  .catch (err) ->
    next err
```
And even if a cURL it with the specified `Content-Type`, it fails

```
curl -v -k -H "Content-Type:image/png" -v --upload-file tumblr_nl29hydgtP1uq22wlo1_r2_1280.jpg https://s3.amazonaws.com/mybucket/tumblr_nl29hydgtP1uq22wlo1_r2_1280.jpg\?AWSAccessKeyId\=mykey\&Expires\=1428010954\&Signature\=VFVsPs51X97OcbXSAPXb1KW59Ec\=
```

Same 403 error

**Comment by AdityaManohar** [comment]
Would you be able to share the code that you're using to upload the file from your web client? 

FWIW, you should quote the signed URL when using it with cURL.

**Comment by shamoons** [comment]
@AdityaManohar I think if I can resolve the `curl` case, the rest will flow easily. When I send along a `Content-Type`, I get the `403` error. I updated the issue title to reflect this.

**Comment by AdityaManohar** [comment]
I'm not able to reproduce the issue when using a signed URL with cURL. Have you tried quoting the signed URL instead of escaping characters?

```sh
curl -v -H "Content-Type: image/png" --upload-file "https://bucket.s3-us-west-2.amazonaws.com/test?AWSAccessKeyId=foo&Content-Type=image%2Fpng&Expires=1428082106&Signature=bar%3D"
```

**Comment by shamoons** [comment]
Yeah, it's working it seems. But I created a new issue to resolve a new problem I'm having https://github.com/aws/aws-sdk-js/issues/558
