### ISSUE TITLE
Should access key be available immediately after creating?

### ISSUE THREAD

**Issue by mpranjic** [aws/aws-sdk-js#559]
Hi!

When I create new access key using ```createAccessKey``` (AWS.IAM), and then use them with AWS.S3, I am getting the following error:
InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

If I add 15 second delay, keys are working. Is this delay expected?

My workflow is:
1. have root keys, create new AWS.IAM
2. IAM.createUser
3. IAM.attachUserPolicy (S3 full access)
4. IAM.createAccessKey
5. trying to use new keys, create new AWS.S3 with them
6. S3.createBucket <-- here it breaks

**Comment by AdityaManohar** [comment]
@mpranjic 
I am able to confirm that the `AccessKeyId` is not immediately "active" after it is created. There is no IAM API that the SDK can poll to check the status of the `AccessKeyId`, and this makes it difficult to add a waiter state to poll an `AccessKeyId`.

The workaround would be to use the `AccessKeyId` after a delay, similar to what you already seem to be doing. I would also recommend opening an issue on the [IAM Forums](https://forums.aws.amazon.com/forum.jspa?forumID=76) to get further clarification on this behavior.

**Comment by mpranjic** [comment]
Thank you @AdityaManohar for confirmation!
