### ISSUE TITLE
SQS, addPermission wildcard

### ISSUE THREAD

**Issue by stockholmux** [aws/aws-sdk-js#565]
I'm trying to set a SQS queue to allow anyone to receive a messages. I'm using this code:
```
  sqs.addPermission({
    AWSAccountIds : ['*'],
    Actions : ['ReceiveMessage'],
    Label : 'mylabel',
    QueueUrl : queueUrl
  }, function(err,data) {
    if (err) {
      cb(err);
    } else {
      cb(null,inObj);
    }
  });
```

I get this error:

```
{ [InvalidParameterValue: Value [*] for parameter PrincipalId is invalid. Reason: Unable to verify.]
  message: 'Value [*] for parameter PrincipalId is invalid. Reason: Unable to verify.',
  code: 'InvalidParameterValue',
  time: Tue Apr 07 2015 15:19:19 GMT-0500 (CDT),
  statusCode: 400,
  retryable: false,
  retryDelay: 30 }
```

Am I missing something in how to set the permission for all? (`*` works in the console)

This is with SDK version `2.1.20` and using node `v0.10.36`

**Comment by AdityaManohar** [comment]
@stockholmux 
I can verify that SQS does not accept `'*'` as a possible list value for the `AWSAccountIds` parameter. I would recommend opening an issue on the [SQS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=12) to report this behavior.

In the meantime, you can also use the [`AWS.SQS.setQueueAttributes()`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#setQueueAttributes-property) for more fine grained control of SQS policies.

```javascript
var AWS = require('aws-sdk');
var sqs = new AWS.SQS();

var policy = {
  "Version": "2012-10-17",
  "Id": "Queue_Policy",
  "Statement": 
    {
       "Sid":"Queue_AnonymousAccess_ReceiveMessage",
       "Effect": "Allow",
       "Principal": "*",
       "Action": "sqs:ReceiveMessage",
       "Resource": "arn:aws:sqs:*:111122223333:queue"
    }
}

sqs.setQueueAttributes({
  QueueUrl: 'https://sqs.us-west-2.amazonaws.com/111122223333/queue',
  Attributes: {
    Policy: JSON.stringify(policy)
  }
}, callback);
```

Let me know if this helps!

**Comment by AdityaManohar** [comment]
@stockholmux 
I'm marking this as closed. Feel free to reopen this issue or open another issue if you have any questions.

**Comment by DavidTPate** [comment]
I was running into the same issue as through the console it seems like it is just sending `*` for Everyone when setting the permissions. This might be a good caveat to add to the documentation as it's not clear that the policy needs to be attached instead of using the `addPermission` API. 

At first it appeared to me that the API implemented in the SDK just wasn't allowing `*` instead of it needing to be done in a different way.

**Comment by toaster33** [comment]
Section for possible [example](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/acp-overview.html#PermissionTypes).
