### ISSUE TITLE
S3 upload fails when file size exceeds 5mb

### ISSUE THREAD

**Issue by ecdeveloper** [aws/aws-sdk-js#570]
When I'm trying to upload a file larger than 5mb with `s3.upload()` it just hangs. After some time it throws the following error - `Part number must be an integer between 1 and 10000, inclusive`. After a quick research, I end up putting the following code into this line - https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L410:
```
console.log('upload part', chunk.toString().length, partNumber);
```
When I try to upload a file larger than 5mb, I see the following output:
```
upload part 5044533 1
upload part 98150 2
upload part 0 3
upload part 0 4
...
```
It keeps trying to upload a 0-length chunk endlessly (until it hits the maxTotalParts limit).

I use the latest module version - 2.1.22. Node version - 0.10.30. OS - OSX 10.9.5

**Comment by AdityaManohar** [comment]
@ecdeveloper 
Thanks for reporting! We are working on a fix and will have a patch release out for this regression shortly.

**Comment by ecdeveloper** [comment]
Great. Thanks!

**Comment by AdityaManohar** [comment]
@ecdeveloper 
This fix is out in master. I will cut a patch release out shortly.

**Comment by AdityaManohar** [comment]
@ecdeveloper 
I just cut a release `v2.1.23`. Let me know if this works for you.

**Comment by ecdeveloper** [comment]
@AdityaManohar Perfect! Works like a charm now. Thank you!

**Comment by AdityaManohar** [comment]
@ecdeveloper Thanks for reporting! Glad you have it working.
