### ISSUE TITLE
Environment variable name inconsistencies between SDKs and ElasticBeanstalk

### ISSUE THREAD

**Issue by phsstory** [aws/aws-sdk-js#571]
In particular other SDKs use the environment variable {PREFIX}_SECRET_KEY to support the  immutable environment variable AWS_SECRET_KEY in the ElasticBeanstalk Console.

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/EnvironmentVariableCredentialsProvider.html
> AWSCredentialsProvider implementation that provides credentials by looking at the: AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY) environment variables.

Is this an issue where some of the SDKs have moved to the new {PREFIX}_SECRET_ACCESS_KEY structure and the ElasticBeanstalk environment (or Console) has not updated or is this an oversight in configuration interoperability?

**Comment by AdityaManohar** [comment]
@phsstory 
The documented and recommended usage is `[PREFIX_]ACCESS_KEY_ID` and `[PREFIX_]SECRET_ACCESS_KEY`. Both these environment variables are supported by all the AWS SDKs and the AWS CLI.

These are also the same keys used in the shared credentials file and picked up by the [`AWS.SharedIniFileCredentials`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html) provider.

That being said, we can look to add compatibility in the [`AWS.EnvironmentCredentials`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EnvironmentCredentials.html) provider for other legacy combinations like those used by ElasticBeanstalk.

**Comment by phsstory** [comment]
The inclusion of legacy combinations would solve an immediate rough edge exposed by the forced ElasticBeanstalk environment variables.

Should I also open a feature request with the ElasticBeanstalk for the ability to rename these environment variables or would it best be served coming from an internal resource since it would also have an impact to other distributed products such as the VisualStudio AWS ToolKit interface?

**Comment by AdityaManohar** [comment]
@phsstory 
> The inclusion of legacy combinations would solve an immediate rough edge exposed by the forced ElasticBeanstalk environment variables

Agreed!

>Should I also open a feature request with the ElasticBeanstalk for the ability to rename these environment variables

Feel free to open an issue on the [Elastic Beanstalk Forums](https://forums.aws.amazon.com/forum.jspa?forumID=86). I will also follow up on this internally.

Also, thank you for bringing this to our attention.

**Comment by lsegal** [comment]
@phsstory can you elaborate on which environment variables you're referring to? If you're looking at the ones provided in the default configuration of the console, you can already rename these.

**Comment by phsstory** [comment]
AWS Console -> ElasticBeanstalk -> [Application] -> [Environment] -> Configuration -> Software Configuration : Environment Properties

AWS_SECRET_KEY is the problematic one. I've had more than one developer make the mistake and assume the provided field was the correct one to populate.

![console](https://cloud.githubusercontent.com/assets/11877226/7101578/ea561712-e024-11e4-9e1b-cf3803c00794.png)

**Comment by lsegal** [comment]
I think that can be resolved by simply adding description text to the Elastic Beanstalk console screen. It looks like the console already supports AWS_SECRET_ACCESS_KEY, which is supported by our other SDKs and tools. AWS_SECRET_KEY is not universally supported, and can simply be ignored in most cases.

As a sidenote, the recommended / preferred way to configure credentials in Elastic Beanstalk is actually to use [IAM Roles](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.iam.roles.aeb.html). This setup is more secure and configurable. Ideally you should not even be setting access keys in your environment variables-- the only time you would ever set these would be if you needed to use a third-party tool that did not support IAM Roles.

**Comment by phsstory** [comment]
yes, AWS_SECRET_ACCESS_KEY is supported as a user supplied environment variable.
This issue is about ElasticBeanstalk defaults include a legacy environment variable name which is supported in some of the SDKs and not others.

We understand AWS roles are the preferred mechanism but sometimes the environment variables are advantageous especially during prototyping and early dev when roles are not available in the developers local environment.

**Comment by lsegal** [comment]
> This issue is about ElasticBeanstalk defaults include a legacy environment variable name

Can you explain where this default is? The console screenshot above does not seem to be showing any defaults, but simply the choice of providing both environment variables. If one was marked clearly as "legacy", would it clarify?

> sometimes the environment variables are advantageous especially during prototyping and early dev when roles are not available in the developers local environment.

Can you elaborate here as well? IAM roles are very easy to configure, and one of the benefits of IAM roles is specifically that each developer does not need to know the specific keys that are used on the deployed instance. In other words, your developers should not need IAM in their local development environment. They can rely on access keys provided in the [shared credentials file](http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs), which ideally are a *separate* set of access keys. This way they would never need to configure credentials in Elastic Beanstalk, only in their local environment, which should simplify prototyping.

**Comment by phsstory** [comment]
The defaults are the parameters without the "X" on the right. These can not be removed / renamed.
The two involving the credentials are marked in the attached screenshot.

On the subject of roles and/or shared credentials files; although off topic for this issue, we are dealing with many products and aws accounts, with a few having development predating the support for credentials files. We find it easier to continue to maintain product/environment credentials pairs in the individual project file hierarchy to avoiding lengthy developer setup issues for the time being.

**Comment by AdityaManohar** [comment]
@phsstory 
It looks like Elastic Beanstalk has updated the Environment Properties to not include any legacy defaults. You can now specify only the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables for your container environment.

I'm marking this as closed since it doesn't look like there is anything to be fixed at this time from the SDK side of things. Feel free to reopen this issue or open another issue if you have other questions.

**Comment by phsstory** [comment]
I'm still showing the forced, unremoveable, fields `AWS_SECRET_KEY` and `AWS_ACCESS_KEY_ID` in the console. Do you have a reference to an pending change to the console where these fields are not forced with empty strings?

**Comment by AdityaManohar** [comment]
Any new Elastic Beanstalk container created will not have these defaults environment variables specified.
![screen shot 2015-07-13 at 2 32 55 pm](https://cloud.githubusercontent.com/assets/966440/8661401/1b1fe57c-296c-11e5-80fc-ef90519ed580.png)

**Comment by phsstory** [comment]
Thank you. I just confirmed that new containers are not forcing these parameters.

**Comment by AdityaManohar** [comment]
Sure! Glad you have it working!
