### ISSUE TITLE
AWS JS SDK support for Lambda invoke sync

### ISSUE THREAD

**Issue by katrotz** [aws/aws-sdk-js#572]
Hi,
I've come to know that AWS has [released](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property) synchronous version of Lambda invokation.

When should we expect it implemented in the JS SDK?

Thanks in advance!

**Comment by mhart** [comment]
The documentation you linked to *is* the synchronous version exposed in the JS SDK. `invokeAsync` is the asynchronous version.

It's synchronous in the sense that it returns the results of your lambda invocation in the same HTTP request – ie, you don't need to make further asynchronous HTTP requests to receive the results/logs/etc.

**Comment by AdityaManohar** [comment]
@katrotz 
As  @mhart mentioned, what you linked to is the "synchronous" `invoke()` method in the latest Lambda API version (2015-03-31). [`v2.1.23`](https://github.com/aws/aws-sdk-js/releases/tag/v2.1.23) of the SDK has support for the latest Lambda API.

I'm marking this as closed. Feel free to reopen this issue or open another issue if you have any questions.
