### ISSUE TITLE
AWS Elastic Transcoding Signature expired

### ISSUE THREAD

**Issue by arvindgt** [aws/aws-sdk-js#573]
I am using PHP SDK for AWS Elastic Transcoding. When I am creating a transcoding job, it gives me an error, Like:

Signature expired: 20150411T064107Z is now earlier than 20150411T064135Z (20150411T064635Z - 5 min.)

I am using region US-WEST-2.
Can any body guide me please how to solve this issue.

**Comment by AdityaManohar** [comment]
I'm marking this as closed because this is the repository for the AWS SDK for JavaScript. You can open an issue here [https://github.com/aws/aws-sdk-php/issues](https://github.com/aws/aws-sdk-php/issues) for questions about the AWS SDK for PHP.
