### ISSUE TITLE
Access-Control-Allow-Origin issue with CloudFormation

### ISSUE THREAD

**Issue by scampiuk** [aws/aws-sdk-js#581]
Hi,

My requests in Chrome to the CloudFront endpoint are failing with the message: 
XMLHttpRequest cannot load https://cloudformation.eu-west-1.amazonaws.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource.

If I run chrome in a less secure mode (chromium-browser --disable-web-security) then I can perform the same actions.

It's looking like the CloudFront endpoint isn't setting the Access-Control-Allow-Origin: * header, causing problems. 

Any guidance would be appreciated.

**Comment by lsegal** [comment]
Hi @scampiuk,

CloudFront's API does currently not support CORS, which is a requirement to use this service in a CORS-restricted environment. I found [this feature request](https://forums.aws.amazon.com/thread.jspa?threadID=150169&tstart=0) on the Amazon CloudFront forums. I would recommend jumping in on that thread if you have not already done so.

**Comment by scampiuk** [comment]
Hi,

Thanks, yes I'm going to do that, I've also raised a support ticket with AWS ;) 

Thanks again,

Chris -.

**Comment by AdityaManohar** [comment]
@scampiuk 
I'm marking this as closed. Feel free to reopen this issue or another issue if you have any more questions.

**Comment by scampiuk** [comment]
For people who get her via Google, and are looking for answers:


> The Cloudformation team has added your feature request, thank you for the service feedback.
>
>At the moment, the only option will be to proxy requests through an intermediate server that can tunnel requests to the Cloudformation API endpoints using any AWS SDK. 
> 
> Finally, I would like to add to the previous correspondence. 
> 
> While for AWS requests you can disable CORS security checking, your clients would be vulnerable to XSS attacks.
