### ISSUE TITLE
Retried S3 request uses a bogus hostname (the bucket name is repeated)

### ISSUE THREAD

**Issue by jstamerj** [aws/aws-sdk-js#585]
I have a node service using the aws-sdk that gets thousands of files from S3 per day.  It is using node v0.10.26 and aws-sdk 2.0.1 (although aws-sdk 2.1.24 still appears to have this bug based on a code inspection).

The vast majority of the time, s3.getObject() succeeds.  However, very infrequently -- approximately once every month -- I see a call to s3.getObject fail with a certificate error like this one:
```
 { [NetworkingError: Hostname/IP doesn't match certificate's altnames]
     message: 'Hostname/IP doesn\'t match certificate\'s altnames',
     code: 'NetworkingError',
     region: 'us-east-1',
     hostname: 'hurley-config-us-west-2.hurley-config-us-west-2.s3-us-west-2.amazonaws.com',
     retryable: true,
     time: Fri Apr 17 2015 17:39:38 GMT+0000 (UTC),
     statusCode: 200 } }
```
What really got my attention was the hostname above.  The name of the bucket is repeated in the hostname.  The bogus hostname resolves in DNS, but the certificate used by the HTTPS/SSL server has a common name of "*.s3-us-west-2.amazonaws.com" which does not match the bogus hostname being used.  This explains the cert error.

But, why is this bogus hostname being used?  The service code passes in the region, bucket name, and key to the aws-sdk this way:
```
var AWS = require('aws-sdk');
var s3 = new AWS.S3({region: 'us-west-2'});
var params = {
  Bucket: 'hurley-config-us-west-2',
  Key: various valid paths
};
s3.getObject(params, function(err, data) {
  ...
```
...so the hostname is computed by the aws-sdk code.

In aws-sdk/lib/services/s3.js, I see this code in populateURI:
```
  populateURI: function populateURI(req) {
    var httpRequest = req.httpRequest;
    var b = req.params.Bucket;

    if (b) {
      if (!req.service.pathStyleBucketName(b)) {
        if (!req.service.config.s3BucketEndpoint) {
          httpRequest.endpoint.hostname =
            b + '.' + httpRequest.endpoint.hostname;

          var port = httpRequest.endpoint.port;
          if (port !== 80 && port !== 443) {
            httpRequest.endpoint.host = httpRequest.endpoint.hostname + ':' +
              httpRequest.endpoint.port;
          } else {
            httpRequest.endpoint.host = httpRequest.endpoint.hostname;
          }
        }
      ...
```
The first time populateURI is run for my request, it would set req.httpRequest.endpoint.hostname to:
```
hurley-config-us-west-2.s3-us-west-2.amazonaws.com
```
This is correct.
However, if populateURI were to be called a second time for the same request, it would now reset req.httpRequest.endpoint.hostname to:
```
hurley-config-us-west-2.hurley-config-us-west-2.s3-us-west-2.amazonaws.com
```
This is incorrect -- the name of the bucket is repeated in the hostname.

Further examining the code, it appears that the request's state machine allows it to go through the 'build' state more than once in some failure/retry scenarios.  This would cause populateURI to be called more than once, which then uses this bogus hostname and causes the certificate validation error.

The aws-sdk code should not do this.  The unwanted effects are:
- The retry logic for s3 in the aws-sdk will always fail for this scenario.
- Whatever the original error was is masked by the bogus certificate error.

Instead, when retrying s3 requests, the aws-sdk should use the same hostname it used the first time, for example:

bucketName.s3-region.amazonaws.com
(NOT bucketName.bucketName.s3-region.amazonaws.com).

**Comment by lsegal** [comment]
Thanks for reporting. Looks like something we can look into. One note: the `build` state / handlers are not [supposed to be] executed on a retry-- in other words, triggering a retry only triggers from the sign/send events, not build. That said, I know of a special case where the state machine can theoretically back up to the build state (tl;dr if an uncaught synchronous exception is thrown at a special place). This is a known issue that we're working on fixing, but I'm not sure if that (extremely rare) case is related to your issue.

It would help a lot if you could create a minimal test case based on your code path that reproduces this. I'll try to generate a test case too, but it might be a lot faster if I understand how you're using the SDK.

**Comment by lsegal** [comment]
@jstamerj also, have you actually tested this on v2.1.24? You mentioned that you believe it has the same bug based on a "code inspection"-- did that involve actually running code? Even if this were a bug in 2.0.1, we can't move forward with a fix unless it is also present in 2.1.24-- and any fix would require you to upgrade. I would recommend upgrading to see if this issue still persists as a first step.

**Comment by jstamerj** [comment]
@lsegal - I do not have an easy consistent repo -- it is an error that I've seen very infrequently, around once per month.  I have not tried using v2.1.24 yet.  I will update to v2.1.24 now and check if we still see it occurrences of this error in the next month.

I can make the error reproduce reliably by injecting an error into the sdk code.  With v2.1.24, when I edit lib/services/s3.js and modify computeContentMd5 to throw one retryable error per request, like this:
```
computeContentMd5: function computeContentMd5(req) {
  if (!this.threwSimulatedError) {
    this.threwSimulatedError = true;
    var err = new Error('simulated error')
    err.retryable = true;
    throw err;
  }
  if (req.service.willComputeChecksums(req)) {
    var md5 = AWS.util.crypto.md5(req.httpRequest.body, 'base64');
    req.httpRequest.headers['Content-MD5'] = md5;
  }
},
```
...so that the above function throws the first time and succeeds the second time, it is then easy to reproduce the error with this code:
```
var AWS = require('aws-sdk');

var s3 = new AWS.S3();
s3.listObjects({Bucket: 'hurley-config'}, function(err, data) {
    console.log('result', err, data);
});
```
Running this in node spits out:
```
result { [NetworkingError: Hostname/IP doesn't match certificate's altnames]
  message: 'Hostname/IP doesn\'t match certificate\'s altnames',
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: 'hurley-config.hurley-config.s3.amazonaws.com',
  retryable: true,
  time: Mon Apr 20 2015 19:57:41 GMT+0000 (UTC) } null
```

Without injecting any errors into aws-sdk, I suspect something in the build step of s3 requests is throwing a retryable error very infrequently, but I don't know what/where/why that may be happening or how to make it occur more frequently.

**Comment by lsegal** [comment]
Thanks! Your case is actually very helpful in narrowing down the root cause. I'll take a look at this.
