### ISSUE TITLE
SES default user credential doesn't work

### ISSUE THREAD

**Issue by patoi** [aws/aws-sdk-js#587]
After SES service creaton on web interface the AWS create a new user for smtp. This ne user credential does not work. After creating new user for smtp, the new user's credential is working.

See more:  
https://github.com/andris9/nodemailer-ses-transport/issues/2

**Comment by AdityaManohar** [comment]
@patoi 
SMTP credentials are not the same as the `AccessKeyId` and `SecretAccessKey` credential pair and therefore cannot be used by the SDK to sign requests.

From the [SES documentation](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html):
> Your SMTP user name and password are not the same as your AWS access key ID and secret access key

It looks like [nodemailer-ses-transport](https://github.com/andris9/nodemailer-ses-transport) is using the SMTP credentials to sign requests (see [ses-transport.js#L49](https://github.com/andris9/nodemailer-ses-transport/blob/master/src/ses-transport.js#L49)). This will not work for the aforementioned reason and is not an issue with the JavaScript SDK.

**Comment by AdityaManohar** [comment]
@patoi 
I'm marking this as closed since it is not an issue with the SDK. Feel free to reopen this issue or another issue if you have any questions.
