### ISSUE TITLE
getBucketLocation returns empty object

### ISSUE THREAD

**Issue by ChrisZieba** [aws/aws-sdk-js#590]
```
s3.getBucketLocation({ Bucket: 'mybucket' }, function(err, data) {
    console.log(err, data) // null Object {}
});
```

There are no properties in the data object, and the err object is null. I double checked the permissions (s3:GetBucketLocation) and it appears to be all correct, event tried giving the bucket all permissions. The bucket is "US Standard" but the docs say the "LocationConstraint" should be set to empty string.

**Comment by ChrisZieba** [comment]
After digging around a bit this seems to be how the response is parsed. The response for "US Standard":

```
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>
```

and for a bucket in a different region:

```
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/">us-west-1</LocationConstraint>
```

**Comment by lsegal** [comment]
Thanks for reporting. I actually came across this recently. I'll take a look at this.

**Comment by lsegal** [comment]
The above commit should fix this issue.

**Comment by rubenhak** [comment]
I see this happening with  nodejs "aws-sdk", "version": "2.235.1". The LocationConstraint returns empty for us-east-1
