### ISSUE TITLE
TTL is a required parameter for changeResourceRecordSets

### ISSUE THREAD

**Issue by robbiet480** [aws/aws-sdk-js#593]
As per the official [API Docs](http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets_Requests.html#change-rrsets-request-ttl) TTL is a required parameter. The API docs for AWS-SDK do not list it as required (seen [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Route53.html#changeResourceRecordSets-property))

**Comment by lsegal** [comment]
The problem with TTL is that it is not required in *all* cases, meaning it is only conditionally required. As per docs:

> (Required for All **Except Alias Resource Record Sets**)

For alias resource record sets, this value can be omitted.

**Comment by AdityaManohar** [comment]
I'm marking this as closed because there hasn't been any recent activity.

As @lsegal mentioned `TTL` is conditionally required. Feel free to reopen this issue or open another issue if you have any questions.
