### ISSUE TITLE
ManagedUpload callback is never invoked if body is 0 bytes, nor an error thrown.

### ISSUE THREAD

**Issue by dconnolly** [aws/aws-sdk-js#594]
If the input body is size 0, the callback is never called, because nextChunk() is never called. I would expect the callback to be called with an err value. Otherwise the upload is kicked off and no other events are triggered, nor Error's thrown, it just goes dark.

**Comment by AdityaManohar** [comment]
@dconnolly This looks like it may be related to #549

**Comment by lsegal** [comment]
I am closing this in favor of #549 since this is likely related. Feel free to reopen if you think this is a different issue.
