### ISSUE TITLE
getSignedUrl resulting in SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by wlingke** [aws/aws-sdk-js#595]
I am requesting a signedUrl of a document in s3 that is signed with a SSECustomerKey.

I retrieve it like so:
```
function retrieve(path, key, cb) {
    var params = {
        Bucket: bucket,
        Key: path,
        SSECustomerAlgorithm: "AES256",
        SSECustomerKey: key
    };

    return s3.getSignedUrl('getObject', params, cb);
}

var request = require('request')
var fs = require('fs')
retrieve(my_path, my_key, function(err, url){
    request.get(url).pipe(fs.createWriteStream('test.pdf'));
})
```
However, I end up producing an XML file that shows a `SignatureDoesNotMatch` error with message: `The request signature we calculated does not match the signature you provided. Check your key and signing method.`

I am sure `Key` and `SSECustomerKey` are correct because I am able to retrieve the document with the exact same `params` using `getObject`.

I am currently using node 0.12.2 and AWS-SDK 2.1.26

**Comment by wlingke** [comment]
For what its worth, this is how I uploaded the file in the first place:

```
function upload(stream, destinationPath, key, contentLength, contentType, cb) {
    var params = {
        Bucket: bucket,
        Key: destinationPath,
        Body: stream,
        ContentLength: contentLength,
        ContentType: contentType,
        SSECustomerAlgorithm: "AES256",
        SSECustomerKey: key
    };

    return s3.putObject(params, cb)
}
```

**Comment by lsegal** [comment]
@wlingke when sending a request with a signed URL you must ensure to also pass any header parameters that you generated the URL with as headers in your actual request with the signed URL. The SSE params are such headers that must be passed through.

This worked for me, with V4 signing:

```js
var s3 = new AWS.S3({signatureVersion: 'v4'});
var url = s3.getSignedUrl('getObject', {Bucket: 'bucket', Key: 'encrypted',
  SSECustomerKey: key, SSECustomerAlgorithm: 'AES256'});
// url is https://bucket.s3.amazonaws.com/encrypted?....
```

And then sending the request:

```
$ curl 'https://bucket.s3.amazonaws.com/encrypted?X-Amz-Algorithm=...' \
  -H 'x-amz-server-side-encryption-customer-algorithm: AES256' \
  -H 'x-amz-server-side-encryption-customer-key: YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE=' \
  -H 'x-amz-server-side-encryption-customer-key-MD5: Xsqb0+sHwAbNQ65I395/0w=='
```

You can find many of the headers in the generated URL (which should make it easier to convert this request), but they must actually be passed in as headers even though they are part of the URL.

Hope that helps.

**Comment by wlingke** [comment]
I see. My goal was to be able to send this link to a client webpage and allow the end-user to click on a link to download the protected file. However, based on what you're saying I'd need the client to make an AJAX request but then there is no good way of downloading a file via AJAX get request.

Is there a better solution for what I am trying to do (or am I over-complicating this)?

**Comment by lsegal** [comment]
@wlingke you can send the header values down as well, or simply construct the AJAX request from the information provided in the URL (the SDK will provide the key information in the URL which you can turn into headers).

**Comment by wlingke** [comment]
Okay. I think I will have to move to normal server side encryption. Requiring headers is not good for my use case since I need a browser to open the link directly without AJAX.

This issue is actually the same as https://github.com/aws/aws-sdk-js/issues/457 upon reflection, I just didnt understand it at the time..

What is the reason that headers are required with pre-signed urls?

**Comment by lsegal** [comment]
> Requiring headers is not good for my use case since I need a browser to open the link directly without AJAX.

Oops sorry I missed that!

> What is the reason that headers are required with pre-signed urls?

This is a behavior of the Amazon S3 API, so I cannot provide an authoritative rationale, but I would recommend heading to the [Amazon S3 forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) to ask this question and possibly even request support for reading these values from the URL in order to support your use case.

I am going to mark this as closed given that the behavior is expected. Feel free to ask any more questions or re-open if you think there is still an issue.
