### ISSUE TITLE
CPU 100% when using ManagedUpload with many small writes

### ISSUE THREAD

**Issue by emptyemail** [aws/aws-sdk-js#597]
When using a stream that sends very small amounts of data with ManagedUpload the cpu will go to 100% while buffering. The culprit is

`self.partBuffer = AWS.util.Buffer.concat([self.partBuffer, buf]);`

Imagine if each write is only a 100 bytes, there are too many concat operations. Much more efficient to add "buf" to an array of buffers and then do one final concat when enough data has been queued up.

As a work around I had to build a buffering stream that does exactly that, and it fixed the problem.

**Comment by lsegal** [comment]
> As a work around I had to build a buffering stream that does exactly that, and it fixed the problem.

Can you describe how you implemented this behavior and where you added this? Was this added to the SDK directly?

**Comment by emptyemail** [comment]
I did not modify the SDK, I just put a transformer in between the SDK and my other streams. 

CoffeeScript

```
class BufferingTransform extends Transform
  constructor: (opts) ->
    super(opts)
    @bufferSize = opts.bufferSize
    @buffers = []
    @size = 0
  _transform: (data, encoding, callback) ->
    @buffers.push(data)
    @size+=data.length
    if @size >= @bufferSize
      return @_flush(callback)
    callback()
  _flush: (callback) ->
    @push(Buffer.concat(@buffers))
    @buffers = []
    @size = 0
    callback()
```

**Comment by lsegal** [comment]
@emptyemail thanks for the info, this is something we can certainly start doing in the SDK-- it will probably simplify some of our internal logic too.
