### ISSUE TITLE
No way to remove all S3 bucket notifications

### ISSUE THREAD

**Issue by lwoggardner** [aws/aws-sdk-js#598]
S3#putBucketNotificationConfigration  requires the NotificationConfiguration property, but the API method to remove all notifications is to send an empty value.

I have tried 
- empty object > MissingRequestBody
-  null > Required Parameter
-  "" > Expecting Structure

**Comment by lsegal** [comment]
Passing an empty NotificationConfiguration parameter is the expected usage, but I can confirm this is a bug. I am investigating this.

**Comment by lsegal** [comment]
This is fixed by the above commit and will be in our next release. If you want to run it now you can:

```
npm install git://github.com/aws/aws-sdk-js
```

And use:

```js
var params = {Bucket: 'bucket', NotificationConfiguration: {}};
s3.putBucketNotification(params, function(err, data) { console.log(err, data) });
```

**Comment by lwoggardner** [comment]
Thanks
