### ISSUE TITLE
Sequential Execution in DynamoDB calls?

### ISSUE THREAD

**Issue by doapp-jeremy** [aws/aws-sdk-js#602]
I have code that looks like this:
```
for (var i = 0; i < 100; ++i) {
  dynamo.getItem(params,function(err,result){
     console.log('get item completed: ' + i);
     if (!result.Item) {
       dynamo.putItem(params,function(err,result){
           console.log('putItem completed: ' + i);
        });
    }
   });
}
```

All of the getItem calls complete before the first putItem call completes.  I have lowered the read throughput on the table so I get some throttling, and still I see the same behavior.

Is this expected behavior, or am I doing something wrong?

**Comment by mhart** [comment]
Expected behaviour – your `for` loop is synchronous, so it will fire off all 100 `getItem` calls before the next event loop ticks around (when the callbacks will get called).

If you want to do this synchronously, then you need to wait until the callback is called in each `getItem` before calling another `getItem`. You can roll your own pattern for this, or just use something like https://github.com/caolan/async#eachSeries

**Comment by mhart** [comment]
For example, this will do what you want (if I understand what you want to achieve correctly):

```js
function getAndPut(i) {
  if (i >= 100) return // all done
  dynamo.getItem(params, function(err, result) {
    console.log('get item completed: ' + i)
    if (!result.Item) {
      dynamo.putItem(params, function(err, result) {
        console.log('putItem completed: ' + i)
        getAndPut(i + 1) // call the next getAndPut
      })
    }
  })
}

getAndPut(0)
```

**Comment by doapp-jeremy** [comment]
Right, except getItem doens't always return almost immediately.  During testing, I set the read throughput to 1 and get throttling.   Say that I have 99 queries that take 10ms, and 1 query that takes 10 seconds.  I would expect to continue on with my putItem for the 99 that have finished, before waiting for the one that takes 10 seconds, but that's now that I see.  I see all 100 put's waiting until all 100 get's finish.

**Comment by mhart** [comment]
@doapp-jeremy well, that's still non-deterministic – that might just be due to the throttling on the http agent from node. There's no guarantees about order in the code you've posted.

If you do:
```js
require('http').globalAgent.maxSockets = require('https').globalAgent.maxSockets = Infinity
```
Before you instantiate your DynamoDB client, that might change things.

**Comment by mhart** [comment]
(sorry, I'm assuming you're using node not the browser)

**Comment by doapp-jeremy** [comment]
Yep, using node, I'll give that a shot.

**Comment by doapp-jeremy** [comment]
And now it's working as I expected.  Thanks!

**Comment by mhart** [comment]
This also only happens in node 0.10.x and below btw. Node 0.12 and io.js shouldn't have this issue – so I'm assuming you're on 0.10.x...

**Comment by doapp-jeremy** [comment]
Yep, I am.  I wish I could use io.js, but I'm writing this for lambda.  Can you push those guys to support io.js soon ;)

**Comment by doapp-ryanp** [comment]
@mhart not sure how much pull you have on the Lambda team, but we've been pushing them to allow consumers of the service to specify node js version for reasons like this.  Right now Lambda only supports 0.10.33.  We understand how the pace of dev is hard to support in a production environment - however node is still in it's infancy, so being able to use new versions is critical.  For example, as @doapp-jeremy states we really would prefer to use io.js so we can leverage things like native ES6 promises.

**Comment by mhart** [comment]
I wish I had pull! Have been thinking the same thing. It's certainly possible to run io.js on Lambda, I've done this – you can include the binary in your function zip (or download it on the fly) and then spawn out to it – but it does take a good second or two to fire up.

Would be great if it was an option.

**Comment by lsegal** [comment]
@doapp-ryanp @mhart I would recommend opening an issue on the [AWS Lambda forums](https://forums.aws.amazon.com/forum.jspa?forumID=186) as this would be the best way to let the team know about your feature request-- they check the forums far more often than this project's issues. We set our roadmaps based on customer feedback, so go forth and leave them this feedback!

**Comment by doapp-ryanp** [comment]
@lsegal done.  For others who come across this thread here is the post (so you can up-vote ;): https://forums.aws.amazon.com/thread.jspa?threadID=180512
