### ISSUE TITLE
Out of memory when downloading a large file from S3

### ISSUE THREAD

**Issue by fpereiro** [aws/aws-sdk-js#605]
Hi there! I am using node.js (v0.12.1) and the aws-sdk (latest version, 2.1.27) to download a large S3 file (~4.8GB). I am using the following code, taken from the documentation (http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-examples.html):

var AWS    = require ('aws-sdk');
var s3 = new AWS.S3 ();
var params = {Bucket: 'BUCKET NAME', Key: 'FILE NAME'};
var output = fs.createWriteStream ('output.tar.gz');
s3.getObject(params).createReadStream().pipe(output);

When I start the script, CPU and memory usage skyrockets, to the point that other processes die (ie: redis) and finally the process is killed by the OS (this in an ubuntu instance with 2 CPUs and 2GB of memory, doing next no nothing in the background). This happens well before downloading 2GBs of the file.

We need to download large S3 files for performing backup restores. Even with a beefier machine (which should be unnecessary considering the performance of node streams), we would be worried about the download taking up all available memory and disrupting other processes (for example, the script that generates and uploads those same backups).

Please let me know if I can contribute further information to replicate the bug.

Thanks!

**Comment by lsegal** [comment]
Has this been happening all the time, or has it only began recently? Specifically, have you tried this in Node 0.10.x before? This would be useful information to diagnose the problem.

**Comment by fpereiro** [comment]
I just tried to run the script the script with node v.0.10.35 and the
memory usage looks normal. However, the transfer speed is very low
(~100KB/s) compared to the ~5-10MB/s of previous downloads.

Immediately after, I reran the script with node v.0.12.1 and memory usage
also looks normal - however the download speed is still very slow. My guess
is that because S3 is transferring the files slowly, memory usage doesn't
grow as much and the bug cannot be replicated.

I unfortunately cannot tell you whether 0.10.x would work fine until S3's
normal speed is back. I will retry tomorrow.

Meanwhile, if you have time to replicate the bug, you can use the script I
posted and attempt to download a file that's at least 4GBs. You can get the
node binary for 0.12.1 here <http://nodejs.org/dist/v0.12.1/>.

Thank you!

2015-05-14 21:06 GMT+02:00 Loren Segal <notifications@github.com>:

**Comment by fpereiro** [comment]
I confirm that this only happens with node v.0.12.x. I tried again with 0.10.35 and memory usage is stable. With v.0.12.x and adecuate bandwidth, RAM usage grows at an average of ~30MB/s.

Let me know if you need further info.

Thanks!

**Comment by lsegal** [comment]
@fpereiro could you bisect 0.12.x to figure out which version of 0.12.x this is an issue with? It almost seems like this might be a regression in 0.12.x itself. The SDK doesn't actually manage downloads through createReadStream, we delegate to stream.pipe() directly, so if there is a memory leak that is specific to 0.12 it would be due to some implementation detail in that version.

**Comment by fpereiro** [comment]
Hi there,

I tried with both 0.12.1 and 0.12.3 (the latest version) and the leak is
present in both versions (I am assuming that the same will happen for
0.12.2).

Can you point me to the code that delegates to stream.pipe ()?

2015-05-16 1:16 GMT+02:00 Loren Segal <notifications@github.com>:

**Comment by lsegal** [comment]
@fpereiro sorry I may have misspoke slightly-- we don't call pipe() ourselves, but we delegate all events through. You can see the createReadStream implementation here: https://github.com/aws/aws-sdk-js/blob/master/lib/request.js#L558-L582

You can however access the low-level stream object if you want to test with it. Sample code is available in the description for #345. Using this lower-level stream interface (which createReadStream is built on) will allow you to pipe directly.

**Comment by fpereiro** [comment]
I found a possible bug at line 559 of request.js. In node 0.10.x,
legacyStreams is set to false, however in 0.12.x it is set to true.

However, making the code ignore this condition on 0.12.x (and jumping
straight to the else in line 566) still doesn't resolve the leak for 0.12.x.

Unfortunately I don't have time to keep on finding the error in the stream
interface. For now, we will use a node 0.10.x binary to avoid the issue.

I implore you to look into the issue when you have time - from all I've
seen, this will happen to anybody downloading a large file from S3 with
node 0.12.x. I doubt this is a regression in the node codebase, since
streams are widely used, especially for transferring and processing large
amounts of data.

2015-05-16 2:48 GMT+02:00 Loren Segal <notifications@github.com>:

**Comment by lsegal** [comment]
@fpereiro I can confirm that using the code in #345 works around this issue for me in 0.12.x. Still investigating what is going on in request.js that might trigger this issue.

**Comment by fpereiro** [comment]
I confirm that the memory leak is gone with this fix (I used aws-sdk v.2.1.30).

Thank you very much for looking into this!
