### ISSUE TITLE
Cognito identities are cached per-pool but not per user

### ISSUE THREAD

**Issue by wearhere** [aws/aws-sdk-js#609]
`AWS.CognitoIdentityCredentials` will not fetch a Cognito ID [if one is already cached](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/cognito_identity_credentials.js#L152). But since IDs are keyed [only on the identity pool ID](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/cognito_identity_credentials.js#L288), only one ID can be cached per-pool. This may cause ID/login token mismatches if an application has multiple users that authenticate using the same browser.

#### Example 

My application, for instance, uses Google as an identity provider. My application runs inside of Gmail, so it is common for users to have multiple instances of the application running at a time—one per Gmail account. If the user uploads a file to S3 from their `joe1@gmail.com` account, they will succeed and the ID of `joe1` will be cached. But if the user then tries to upload a file to S3 from their `joe2@gmail.com` account, they will fail because the SDK will try to authenticate `joe1`'s identity using `joe2`'s login token.

#### Fix

To fix this, I suggest that the `AWS.CognitoIdentityCredentials` cache space be subdivided by means of a new parameter `LoginHint` provided to the constructor. The value of `LoginHint` should differ by user; perhaps it could be the user's email address:

```js
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
  IdentityPoolId: ...,
  Logins: ...,
  LoginHint: 'joe1@gmail.com'
});
```

That parameter would supplement [the cache key](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/cognito_identity_credentials.js#L288) like so:

```
this.storage[this.localStorageKey[key] + this.params.IdentityPoolId + (this.params.LoginHint || '')] = val;
```

I'm glad to submit a PR if you like this approach.

**Comment by wearhere** [comment]
In the meantime, a workaround is to call [`clearCachedId`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html#clearCachedId-property) before using an AWS service. But because `clearCachedId` is an instance method and [it doesn't clear the instance's information](https://github.com/aws/aws-sdk-js/pull/608) you've got to re-initialize the instance after clearing the cache:

```
var credentialParams = { IdentityPoolId: ..., Logins: ... };
var credentials = new AWS.CognitoIdentityCredentials(credentialParams);
credentials.clearCachedId();
credentials  = new AWS.CognitoIdentityCredentials(credentialParams);

// Now you can use S3 or whatever.
var bucket = new AWS.S3;
```

**Comment by wearhere** [comment]
Thanks @chrisradek! It looks like this will make it into v2.2.11?

**Comment by chrisradek** [comment]
@wearhere 
Yes, this will be available in the next release. Thanks for requesting this feature and for your feedback!

**Comment by aaaguirrep** [comment]
I have used the suggestion of @wearhere and it worked.

**Comment by gregkowalski** [comment]
@alexjfno1 `LoginId` was the new field added to the `AWS.CognitoIdentityCredentials`
