### ISSUE TITLE
SQS receiveMessage() has memory leak

### ISSUE THREAD

**Issue by TehNrd** [aws/aws-sdk-js#610]
There appears to be a memory leak with receiveMessage() function for SQS in node. This issue is very simple to reproduce. I've created a repo to reproduce this issue, https://github.com/TehNrd/node-sqs-mem-leak . This is using node 0.12.2.

Here is the code:
```
var AWS = require('aws-sdk');
AWS.config.update({region: 'us-east-1', sslEnabled: false}); //We are not sending secure data and disabling SSL improves performance
var sqs = new AWS.SQS();
var GEOCODE_AWS_SQS_URL = 'https://sqs.us-east-1.amazonaws.com/000000000/somequeue';

//Get messages from SQS every second
function getMessages(){

	//Do 10 receiveMessage() calls
	for(var i = 0; i < 10; i ++){
		var params = {
		  QueueUrl: GEOCODE_AWS_SQS_URL,
		  MaxNumberOfMessages: 10
		};

		sqs.receiveMessage(params, function(err, data) {
		  if(err) {
		  	console.log(err, err.stack) 
		  }else{
		  	//Handle messages
		  } 
		});
	}

	//Get more messages
	setTimeout(function(){
		getMessages();
	},1000);
}
getMessages();

//Log memory usage every 2.5 seconds
function logMemory(){
	var memUsage = process.memoryUsage();

	console.log('RSS: ' + memUsage.rss/1000000 + ' MB, Heap Used: ' + memUsage.heapUsed/1000000 + ' MB, Heap Total: ' + memUsage.heapTotal/1000000 + ' MB');

	setTimeout(function(){
		logMemory();
	},2500);
}
logMemory();
```

Here is the log output. Memory usage will continue to grow unchecked.
```
RSS: 28.946432 MB, Heap Used: 10.158272 MB, Heap Total: 17.029888 MB
RSS: 43.511808 MB, Heap Used: 11.95104 MB, Heap Total: 20.113664 MB
RSS: 48.8448 MB, Heap Used: 10.584512 MB, Heap Total: 30.554112 MB
RSS: 51.257344 MB, Heap Used: 15.367984 MB, Heap Total: 30.554112 MB
RSS: 56.311808 MB, Heap Used: 12.494864 MB, Heap Total: 30.554112 MB
RSS: 63.565824 MB, Heap Used: 13.040576 MB, Heap Total: 31.586048 MB
RSS: 67.03104 MB, Heap Used: 18.140128 MB, Heap Total: 32.605952 MB
RSS: 69.255168 MB, Heap Used: 16.290632 MB, Heap Total: 34.669824 MB
RSS: 72.86784 MB, Heap Used: 15.588328 MB, Heap Total: 35.70176 MB
RSS: 73.310208 MB, Heap Used: 18.495832 MB, Heap Total: 35.70176 MB
RSS: 77.426688 MB, Heap Used: 18.1686 MB, Heap Total: 53.510912 MB
RSS: 80.564224 MB, Heap Used: 22.792408 MB, Heap Total: 53.510912 MB
RSS: 87.32672 MB, Heap Used: 29.318816 MB, Heap Total: 53.510912 MB
RSS: 90.447872 MB, Heap Used: 31.993984 MB, Heap Total: 53.510912 MB
RSS: 94.973952 MB, Heap Used: 25.386608 MB, Heap Total: 54.542848 MB
RSS: 101.675008 MB, Heap Used: 29.957768 MB, Heap Total: 54.542848 MB
RSS: 109.58848 MB, Heap Used: 22.719552 MB, Heap Total: 56.60672 MB
RSS: 113.455104 MB, Heap Used: 28.845592 MB, Heap Total: 57.638656 MB
RSS: 114.622464 MB, Heap Used: 30.874976 MB, Heap Total: 57.638656 MB
RSS: 119.156736 MB, Heap Used: 25.034576 MB, Heap Total: 60.734464 MB
RSS: 121.229312 MB, Heap Used: 30.189776 MB, Heap Total: 60.734464 MB
```

**Comment by mhart** [comment]
A couple of things spring to mind:

1. It can often take a while for the GC to kick in (ie, many minutes) – are you sure that nothing is being reclaimed?
2. Depending on how many requests you've got in flight at any time, it could just be open sockets. Try doing this before your code and see if it helps:

```js
require('http').globalAgent.maxSockets = 20
```

**Comment by mhart** [comment]
Oh sorry, I can't tell if you're using https or not – so you might need to do this just to be sure:

```js
require('http').globalAgent.maxSockets = require('https').globalAgent.maxSockets = 20
```

**Comment by TehNrd** [comment]
Some thoughts:

1) GC, it never kicks in, or if it does it is missing things. That log selection is just a small sample. It will keep growing into the GB size.

2) Even if sockets are infinite shouldn't they be closed after receiving the response. And shouldn't they also be re-used with socket pooling if not. (node core is not my strength so not sure here). I am trying the maxSockets change now. Will report back.

**Comment by TehNrd** [comment]
Add max sockets made no difference. Memory usage still grows unchecked. I also tried this below, just to be more explicit, in addition to the code you provided but with no success.

```
var http = require('http');
http.globalAgent.maxSockets = 30;
var https = require('https');
https.globalAgent.maxSockets = 30;
```

**Comment by TehNrd** [comment]
This actually has nothing to do with receiveMessage(). In the code above if you replace receiveMessate() with getQueueAttributes() you still get the same memory growth issues. Seems to be an issue with performing "lots" of calls (10/second) and this causing memory growth.

```
sqs.getQueueAttributes({QueueUrl: GEOCODE_AWS_SQS_URL, AttributeNames: ['MessageRetentionPeriod']}, function(err, data) {
	if (err){
		console.log(err, err.stack); // an error occurred
	}else{
		//Handle attributes
	} 
});
```

**Comment by TehNrd** [comment]
Good news, this does not appear to be an issue with AWS SDK. Even doing basic requests to google in a loop are causing memory issues. Bad news, seems to be a larger issues with node core.

Even doing this call in the loop causes memory issues.

```
request('http://www.google.com', function (error, response, body) {
  if (!error && response.statusCode == 200) {
    //console.log(body) // Show the HTML for the Google homepage.
  }else{
  	console.log('body');
  }
})
```

**Comment by mhart** [comment]
@TehNrd I think you might want to wait a bit longer checking your GC results when using a fixed number of agents (like in the code I posted)

I see the heap total stabilise around 77MB when using a maxSockets of 10.

**Comment by TehNrd** [comment]
Yup, I am seeing the same thing @mhart . Thanks so much! For some reason I thought node would be better about throwing away/re-using sockets as 10/sec is not that many really.

**Comment by TehNrd** [comment]
Oh, and keep up the great work! Library is so much better to work with than trying to interact with these APIs directly!
