### ISSUE TITLE
Handle CloudSearch Query Limit

### ISSUE THREAD

**Issue by tgroshon** [aws/aws-sdk-js#614]
When making a request to a CloudSearchDomain with the SDK, if the query is too long, the SDK returns an `UnknownError` with code 413.  To overcome the error, we had to patch the `request` object to convert to a *POST*.

```javascript
function awsRequestToPostIfHuge(request) {
  request.on('build', function() {
    var http = request.httpRequest
    // convert queries to POST to avoid length restrictions
    var path = http.path.split('?')
    http.method = 'POST'
    http.path = path[0]
    http.body = path[1]
    http.headers['Content-Length'] = http.body.length
    http.headers['Content-Type'] = 'application/x-www-form-urlencoded'
  })
}
// Usage
var request = searchDomain.search(params)
awsRequestToPostIfHuge(request)
request.send(function callback() { /* do stuff */ })
```

It seems like this should be handle transparently by the SDK.  You could use *POST* for all requests or optionally if the `request.httpRequest.path.length` is too large.

**Comment by AdityaManohar** [comment]
@tgroshon Thanks for reporting this! We are looking into this feature request. I will keep this issue updated as we have more information on when this will land in master.

**Comment by tgroshon** [comment]
:+1:
