### ISSUE TITLE
AWS lambda - Recursive process.nextTick detected. RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pablocaselas** [aws/aws-sdk-js#615]
Trying to use createFunction from AWS.Lambda({apiVersion: '2015-03-31'}) like this...
```
lambda.createFunction(params_create, function(err, data) {
				  if (err) console.log(err, err.stack); // an error occurred
				  else{
						console.log("succesfully created function ",lambda_function.name);
						console.log(data);  
					}
				});
```
I get the following warnings that result in an abrupt error and the process finishes.

I am using node v10.0.32.
```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

RangeError: Maximum call stack size exceeded
```

Trying to upload the same zip from a ec2 machine results in previous error but works okay from my local machine(tried same node version v10.0.32). Any idea on what could be causing it?? upload is much slower??

**Comment by AdityaManohar** [comment]
@pablocaselas 
This is a known issue with Node v0.10.x (see [joyent/node/issues/#6065](https://github.com/joyent/node/issues/6065). This has also been discussed a couple of times on this repository as well (see #158).

We did investigate changing the `highWaterMark` setting of `stream.Readable`, but noticed a non-trivial memory performance regression (see #551).

Let me know if upgrading your Node runtime to v0.12.x fixes this issue.

Hope this helps!

**Comment by pablocaselas** [comment]
Yes, it seems to be working fine. Thanks!
