### ISSUE TITLE
s3.upload() does not really support arbitrarily sized buffers

### ISSUE THREAD

**Issue by bkw** [aws/aws-sdk-js#617]
Streaming a big file to s3.upload() can cause the PartNumber parameter to overflow the allowed maximum of 10000, resulting in an `InvalidArgument: Part number must be an integer between 1 and 10000` Error.

I managed to work around the problem by using a 10mb `partSize`, but I think the documentation should be updated to reflect this limitation.

btw, using a partSize of 20mb resulted in another failure:

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
[…]

RangeError: Maximum call stack size exceeded
```

**Comment by lsegal** [comment]
> I managed to work around the problem by using a 10mb partSize, but I think the documentation should be updated to reflect this limitation.

If this is not mentioned in our docs I agree that it should be.

> btw, using a partSize of 20mb resulted in another failure:

What version of Node.js are you using?

**Comment by bkw** [comment]
> What version of Node.js are you using?
```
$ node --version
v0.10.38
```

**Comment by lsegal** [comment]
I would suggest upgrading to 0.12. The Recursive nextTick issue is a known one in Node.js, see https://github.com/joyent/node/issues/6065.
