### ISSUE TITLE
Generate Signed Cookies in Lambda for Serving Private Content w/ CloudFront

### ISSUE THREAD

**Issue by LasCondes** [aws/aws-sdk-js#618]
I've posted this question in the AWS Lambda Forum and been directed here.

https://forums.aws.amazon.com/thread.jspa?threadID=181683

The AWS .NET SDK recently added this functionality.

https://blogs.aws.amazon.com/net/post/Tx13FWI3QBQXMZ1/Serving-Private-Content-Through-Amazon-CloudFront-Using-Signed-Cookies

It would be really helpful to have this added to the javascript SDK to be used in an AWS Lamda function.

What I would like to do is host a website with an area for authenticated users 100% in an S3 bucket and use Lambda functions when needed. The use case I see is as follows:

1. site would be stored in an s3 bucket and distributed through CloudFront. Restricted content would have a behavior set in CloudFront requiring signed cookies. 
2. user would login with "Login with Amazon" and the token passed to Cognito where it would be linked to an id.
3. A Lambda call would be made. In the Lambda function you can see the users unique cognito ID and this can be checked to see if they have permission to access to the secure content of the web site.
4. In the same lambda function signed cookies would be generated and returned to the web page. With these the authorized user can access the secure content.

The piece I'm missing in the SDK is a nice function to:

Generate Signed Cookies in Lambda for Serving Private Content w/ CloudFront

Is there a clear example of how to do this or can it be added to the javascript SDK?

**Comment by AdityaManohar** [comment]
@LasCondes We are looking at this feature request. In the meantime, there is a related npm module (aws-cloudfront-sign)[https://github.com/jasonsims/aws-cloudfront-sign] which generates CloudFront signed URLs. I would recommend opening a feature request on this projects page for CloudFront signed cookies as well. 

Hope this helps!

**Comment by bshyong** [comment]
@AdityaManohar is there any update on this feature? I would like to set up a lambda function that will read cookies on the client and set one if it does not exist.

Thanks

**Comment by LasCondes** [comment]
@jeskew Johnathan any chance you can help with this implementation? https://forums.aws.amazon.com/thread.jspa?messageID=698539&#698539

**Comment by jeskew** [comment]
This change went out with version 2.2.29, which may not yet be available by default in Lambda.

**Comment by jeskew** [comment]
Lambda currently provides version 2.2.12 of the SDK. You can bundle a newer version if you prefer by [following the instructions on issue #765](https://github.com/aws/aws-sdk-js/issues/765#issuecomment-152033324).
