### ISSUE TITLE
S3 SSE-C Key Cannot be Binary?

### ISSUE THREAD

**Issue by cbkihong** [aws/aws-sdk-js#621]
I refer to the same use case I had with #469 for which we are trying to use the Node.js AWS SDK to GET a previously uploaded S3 object encrypted by SSE-C. However, I just ran into an interesting observation that apparently binary string keys would be garbled upon construction of the API request. Tracing that, it looks like being the way the Buffer is being initialized for base64/crypto making an assumption that the key has to be utf8 string. The main issue here is that we cannot fully utilize the 256-bit keyspace provided by AES256 by using utf8 characters alone, which hurts security and it introduced an interoperability issue because the S3 service actually allows that kind of binary key.

In fact, I did a quick experiment and found that indeed I could GET the encrypted object I wanted (saved using another SDK implementation with binary string key) if the code was modified like :-

```
--- node_modules/aws-sdk/lib/services/s3.js	2015-06-05 03:44:55.000000000 +0800
+++ /tmp/s3.js	2015-06-05 07:02:45.000000000 +0800
@@ -211,9 +211,9 @@
         var key = req.httpRequest.headers[header];
         var md5header = header + '-MD5';

-        req.httpRequest.headers[header] = AWS.util.base64.encode(key);
+        req.httpRequest.headers[header] = (new Buffer(key, 'binary')).toString('base64');
         if (!req.httpRequest.headers[md5header]) {
-          var value = AWS.util.crypto.md5(key, 'base64');
+          var value = AWS.util.crypto.md5(new Buffer(key, 'binary'), 'base64');
           req.httpRequest.headers[md5header] = value;
         }
```

I understand that this is not really an acceptable "fix" because in return it breaks non-ascii utf8 string keys. However, what can we do with respect to this situation? To put it in context, we are testing on keys that look like

```
new Buffer('4d339a39686c4b0da1fc923347d2d1c85995f14cae4de7aaf6d17fef86d7e68e', 'hex')
```

Same configuration as #469 except re-tested on a newer aws-sdk.

**Comment by AdityaManohar** [comment]
@cbkihong I'm looking into this and will have a fix out shortly, that should support blob keys as well.

**Comment by AdityaManohar** [comment]
@cbkihong the above fix should allow you to use binary keys. Let me know if you run into any issues!

**Comment by cbkihong** [comment]
Haven't tried the fix yet but will do later today, and thank you so much for the quick fix. One question though, I noticed that in your tests you utilized AWS.util.Buffer though it seems from util.js (at present) it is just made an alias to Node.js core Buffer. Can we be certain that we can directly reference Node.js Buffer instead of AWS.util.Buffer when we specify the params, since AWS.util.Buffer is apparently "internal" and not documented?

**Comment by lsegal** [comment]
@cbkihong `AWS.util.Buffer` safely models the Buffer object. It's an alias for browser environment compatibility.

**Comment by cbkihong** [comment]
Tested and looks like this change worked for us. Will wait for your release, thank you again!
