### ISSUE TITLE
Broken link to the API reference

### ISSUE THREAD

**Issue by AWSRandall** [aws/aws-sdk-js#622]
I was looking at this page: https://github.com/aws/aws-sdk-js/blob/master/doc-src/guide/index.md and it has a broken link to the API reference.

Expected:link to http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/index.html (for Node.js)

**Comment by AdityaManohar** [comment]
@AWSRandall 
What you are referencing is the documentation source. Here is the corresponding published documentation: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/. The link to the API reference documentation is pointing to the correct page.
