### ISSUE TITLE
AWS Lambda on Browser: Context.succeed() value not returning to invoke from Browser

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#625]
Hey guys,

I have a function in Lambda where I'm fetching information and I want to return results.
I can log the results with console.log in CloudWatch, but I need to get the results back to my javascript :).

I'm trying currently using the context.succeed value in the front-end (javascript) but I have not had success yet, I'm able to console.log it in cloudwatch, but I only get Status 202 in the front-end, I read in some site about having RequestResponse enabled in the invoke, not sure if I set this as a parameter when I invoke the function? This is my current front-end function.
```javascript
function LambdaClient(options){
  //this.options = options || {};
  this.lambdaClient = new AWS.Lambda({region:'us-west-2'});

  this.invoke = function(functionName, invokeArgs){
    var callId = functionName,
    jsonString = JSON.stringify(invokeArgs),
    repString = jsonString;

    console.log(repString);
    var params = {
      FunctionName: functionName,
      InvokeArgs: repString
    }
    this.lambdaClient.invokeAsync(params, function(err, data) {
      if (err) { throw 'Erro: '+err; } else { console.log(data);}
    });
  }
}
```

Do I have to put it here? If yes, what?
```javascript
var params = {
      FunctionName: functionName,
      InvokeArgs: repString
      InvokeType???
    }
```

**Comment by lsegal** [comment]
Ideally you should be using the new [`invoke()`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property) function. This allows you to synchronously return data. You can see a couple of examples in Lambda's own "Custom" template functions. For example, using the "Hello World" sample Lambda function. the code to call with invoke would be:

```js
var params = {
  FunctionName: 'myfunc',
  Payload: JSON.stringify({key1: 'value', key2: 'value2', key3: 'value3'})
};
lambda.invoke(params, function(err, data) {
  console.log(data); // this will be 'value' from event.key1
});
```

The above function

**Comment by ramonck** [comment]
Worked like a charm, thank you.

**Comment by SwethaMK** [comment]
Hi @lsegal , What if I have to use invokeAsync , since I need to make Asynchronous calls ?
I have been trying to get back results from my lambda function ( written in Node.js ) back to my browser, but to no avail. While testing it on Lambda console, I can see the correct results & proper console output, but when I try getting it from the browser, it always says 'Unexpected token u in JSON at position 0'.

**Comment by jeskew** [comment]
Hi @SwethaMK,

`InvokeAsync` will either throw an exception or return an empty response. If you need to access the output of a lambda function, you will need to use `Invoke`. Additionally, AWS Lambda has deprecated `InvokeAsync` and suggests you use `Invoke` instead.
