### ISSUE TITLE
Thank you for the help guys

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#626]
I would like to thank Amazon's work in helping us in our Lambda efforts, it's such a great piece of technology and it's the future to many upcoming projects, thank you Amazon for helping me with my efforts and projects, I love it how you guys help me fast :).

**Comment by lsegal** [comment]
@ramonck thank you for the kind words, I'll be sure to pass this feedback on to the Amazon Lambda team as well!

(Marking as closed since this is not an actual problem but certainly a welcomed "issue"!)
