### ISSUE TITLE
Cognito after AWS SDK JS loaded

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#627]
Hey guys,

Sometimes when doing Cognito with unauthenticated I'm receiving that AWS has not been loaded yet this is the Javascript Error: "Uncaught ReferenceError: AWS is not defined".

I was trying to use the boundaries outside to wait for AWS onload, but it's not working as expected, sometimes I still get the error even with the boundaries.

```javascript
;( function(AWS){
// My Cognito coding which works fine
})(AWS);
```

Is there a better way for waiting for the SDK JS onload then do my Cognito stuff?

```javascript
AWS.loaded({
Now Go! :)
});
```

Best Regards,

**Comment by lsegal** [comment]
@ramonck I can suggest a few ways to unblock yourself here, but following up with some more information on how you are loading the SDK might help us point you in a better direction.

1. Generally speaking, using `<script src=>` tags should cause the SDK to load synchronously on the page-- that is, any code block *after* the `<script>` tag should have `AWS` available to it. As long as you put the script tag before your Cognito code, it *should* work-- unless you are injecting the script tag dynamically.

2. If you are loading the script dynamically or asynchronously, one thing you could do to unblock yourself for now would be to download the aws-sdk.*.min.js file locally and make a small modification to the file. Namely, add the following single line to the end of the file:

```js
window.dispatchEvent(new CustomEvent('awsLoaded'));
```

This line will cause the script tag to trigger the 'awsLoaded' event on window, so you could track loading of the SDK with:

```js
window.addEventListener('awsLoaded', function() {
  console.log("AWS is now available: " + AWS.VERSION);
}, true);
```

Currently you would have to work around this yourself in the method described above, but this is certainly an event that we could easily start emitting for this use-case by default in the browser environment of the AWS SDK.

**Comment by ramonck** [comment]
Yes,
I can provide some feedback :).

I don`t want to load AWS SDK JS synchronously due to the critical rendering path, I want to keep up with the 100% on the Page Insights (Google) so I want to keep on loading the majority of my script async.

Will do what you said.

Best Regards

**Comment by ramonck** [comment]
The error doesn`t come up anymore as your solution solves it, but the Cognito behavior is a bit weird now, sometimes is works sometimes it doesn`t, I don`t see the Cognito log in a couple of refreshes sometimes yes, others no. Here`s the url http://m.jtavares.com.br.s3-website-us-east-1.amazonaws.com/

Best Regards

**Comment by lsegal** [comment]
@ramonck looks like it's occasionally running the event prior to you registering it, which likely has to do with the ordering of where you are dynamically loading the SDK vs your frontend.js file. If the aws-sdk*.js is cached, the dynamic load will happen before you load the frontend script. My suggestion would be to make sure you load frontend.js before you asynchronously load everything else, or, move the loading of the SDK to window.onready or window.onload to ensure that all event registration happens first.

**Comment by ramonck** [comment]
I'm certain you're right about the caching, the caching mechanism is messing up the loading of the aws sdk.

I'm loading is as <script async> call separatly, will try to call it dynamically inside my script so I can enforce the order (frontend.js)

Thanks for the advice, will give feedback if it worked well.

Best Regards,

**Comment by ramonck** [comment]
Solved it, loaded async within script and putted the AWS code (Cognito) dependent on it.

Thanks again for the help, it's now working fully cached ;).

Best Regards
