### ISSUE TITLE
Retry Redirect?

### ISSUE THREAD

**Issue by ronag** [aws/aws-sdk-js#628]
The documentation mentions `response.error.redirect = true` on the ´retry´ event but not how to specify what to redirect to?

**Comment by lsegal** [comment]
@ronag can you point to where you are seeing this documentation? `redirect` is not a publicly documented property. Can you explain what you are trying to accomplish? The SDK should be handling redirects on your behalf and only based on the server response.

**Comment by AdityaManohar** [comment]
I'm marking this as closed as there hasn't been any recent activity. Feel free to reopen this issue or open another issue if you have any questions.
