### ISSUE TITLE
Error on put bucket Notification

### ISSUE THREAD

**Issue by PunkyPot** [aws/aws-sdk-js#632]
I'm trying to add bucket notification to a bucket but failing with error : `Unable to validate the following destination configurations`, and full error:
```
{ [InvalidArgument: Unable to validate the following destination configurations]
  message: 'Unable to validate the following destination configurations',
  code: 'InvalidArgument',
  time: Mon Jun 22 2015 12:48:26 GMT+0300 (EEST),
  statusCode: 400,
  retryable: false,
  retryDelay: 30 }
```
I'm trying to put an event that's run on: `s3:ObjectCreated:*` and uses lambda
here is the code i'm trying to run: 

```
var params = {
  Bucket : 'MyBucket',
  NotificationConfiguration : {
    LambdaFunctionConfigurations : [
      {
        Events: [
          's3:ObjectCreated:*'
        ],
        LambdaFunctionArn: 'arn:aws:lambda:us-east-1:AccountID:function:MyLambdaFunction'
      }
    ]
  }
};


s3.putBucketNotificationConfiguration(params, function(err, data) {
  if (err) return console.log(err);            // an error occurred
  else     return console.log(data);           // successful response
});
```

UPDATE: 

If i create manually an event and delete it, the code above works fine

**Comment by AdityaManohar** [comment]
Can you share the raw HTTP response body?. The raw HTTP response body can be accessed in the following manner:

```javascript
s3.putBucketNotificationConfiguration(params,  function(err, data) {
  // Logs the raw HTTP response
  console.log(this.httpResponse.body.toString());
});
```
My initial guess is that your S3 resource is not authorized to invoke your Lambda function. The raw HTTP response should throw some light on what is actually happening.

**Comment by PunkyPot** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>InvalidArgument</Code>
    <Message>Unable to validate the following destination configurations</Message>
    <ArgumentName1>arn:aws:lambda:us-east-1:AccountID:function:LambdaName, null</ArgumentName1>
    <ArgumentValue1>Not authorized to invoke function [arn:aws:lambda:us-east-1:AccountID:function:LambdaName]</ArgumentValue1>
    <RequestId>52D12E87577573C9</RequestId>
    <HostId>aOVXqainz/IPQufy33AdA/5S5RDAkR/bKcCQPplIrKJSY3LkFkfr6L2QD7VfSx5jvuMDk00FRO0=</HostId>
</Error>
```


You are right, but how should i give s3 permissions?

**Comment by lsegal** [comment]
@PunkyPot you can take a look at the [AWS Lambda guide](http://docs.aws.amazon.com/lambda/latest/dg/walkthrough-s3-events-adminuser.html) for information and diagrams on how to configure Amazon S3 buckets with Lambda. For example,

> An access policy – In the access policy associated with the Lambda function, you will add a permission granting Amazon S3 permission to invoke the Lambda function. You will also restrict the permission so that Amazon S3 can invoke the Lambda function only for object-created events from a specific bucket owned by a specific AWS account.

This is the access policy that you must configure.

**Comment by AdityaManohar** [comment]
@PunkyPot I'm marking this as closed because it doesn't look like an issue with the SDK. As @lsegal mentioned, the [AWS Lambda guide](http://docs.aws.amazon.com/lambda/latest/dg/walkthrough-s3-events-adminuser.html) discusses how to grant your Lambda function access to your Amazon S3 resources. 

The  [Working with Policies](http://docs.aws.amazon.com/IAM/latest/UserGuide/policies_manage.html) guide further discusses attaching IAM policies to your roles. 

Feel free to reopen this issue or open another issue if you have other questions.

**Comment by ozbillwang** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/
