### ISSUE TITLE
Resume multipart upload with 'leavePartsOnError'?

### ISSUE THREAD

**Issue by dconnolly** [aws/aws-sdk-js#633]
As far as I can tell from the current implementation of `ManagedUpload`, the user has to do a lot of work/bookkeeping to resume an upload that partially completed and then left parts behind. Trying to start a `ManagedUpload` from where it left off will not kick off the chunks that failed prior to the current `partPos`, and the 'complete' request will be incomplete or malformed. Is there any way to resume a multipart upload after stopping it while leaving parts behind with the current sdk api, or will you accept PR's trying to make this possible?

**Comment by lsegal** [comment]
@dconnolly it's something we could support as a feature addition. We would be happy to look at a PR. I'll mark this as a feature request.

**Comment by dconnolly** [comment]
Awesome, thanks. :+1:
