### ISSUE TITLE
[AWS.SES] directly from javascript

### ISSUE THREAD

**Issue by ddimitrioglo** [aws/aws-sdk-js#637]
We are trying to send an email using AWS.SES, directly from javascript like this:
```
  AWS.region = 'us-east-1';
  AWS.config.credentials = new AWS.Credentials({accessKeyId: "aKey", secretAccessKey: "sKey"});
  var service = AWS.Service.defineService('SES', ['2010-12-01']);

  var ses = new service();

  ses.makeRequest('sendEmail', email_obj, function(err, data) {
    // callback code
  });
```

but we are receiving an error: "Could not find API configuration SES-2010-12-01"

Is it possible to send the email from javascript directly?

**Comment by ondruska** [comment]
AWS SES is not amongst the services you can use from browser: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-services.html

**Comment by ddimitrioglo** [comment]
How about this ambiguous article?
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Service.html

**Comment by lsegal** [comment]
@ddimitrioglo @ondruska is correct, the AWS.SES service is not part of the hosted version of the SDK-- this is explained in the browser guide link provided above. The API reference guide that you linked lists the entire API, not specific builds of the SDK.

Note that Amazon SES does not currently support CORS and therefore is not included in the hosted build of the SDK. You can build it yourself by following the instructions linked in the guide above, but it will not work over HTTP/HTTPS schemes unless your browser environment explicitly allows cross-origin requests.

**Comment by AdityaManohar** [comment]
I'm marking this as closed as there doesn't seem to be an issue with the SDK. As a side note, I would recommend opening an issue on the [Amazon SES Forums](https://forums.aws.amazon.com/forum.jspa?forumID=90) requesting CORS support. 

Feel free to reopen this issue or open another issue if you have other questions.

**Comment by ddimitrioglo** [comment]
I have already implemented with AWS.Lambda + AWS.SES, therefore we can close this issue.
Thank you for your help!
