### ISSUE TITLE
Release notes for 2.1.36 misses API versions

### ISSUE THREAD

**Issue by ondruska** [aws/aws-sdk-js#638]
The notes on http://aws.amazon.com/releasenotes/5873934951898767 are missing API versions

**Comment by AdityaManohar** [comment]
Which client are you specifically referring to? All the API updates are backward compatible and shouldn't affect any consuming code.

**Comment by ondruska** [comment]
Compare with release notes for 2.1.35 http://aws.amazon.com/releasenotes/3577030144306744 . Supported API versions section.

**Comment by AdityaManohar** [comment]
Oops! I missed that. Thanks for catching this @ondruska !

**Comment by AdityaManohar** [comment]
This is now fixed: http://aws.amazon.com/releasenotes/5873934951898767

Thanks much for reporting @ondruska !
