### ISSUE TITLE
loadFromPath should be a relative path

### ISSUE THREAD

**Issue by DelvarWorld** [aws/aws-sdk-js#641]
It's not mentioned [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html) that `loadFromPath` is relative to where you ran your node instance. This is counter-intuitive in a node ecosystem, where *all* requires are relative paths. `loadFromPath` should always load relative to the file it's called from.

**Comment by lsegal** [comment]
@DelvarWorld thanks for opening this issue. You're right that it loads from your working directory (`process.cwd()`) and not the executing file. I think we can make the documentation more clear, but note that this is *not* a `require()` call, and actually follows the standard Node.js convention for fs calls. In fact, this is the exact same behavior as:

```js
var fs = require('fs');
var config = JSON.parse(fs.readFileSync(path));
```

This is, in fact, the exact implementation: https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L102

Unfortunately changing the behavior of this would be a breaking change, so it is not possible to make it load relative to the file, and given that we are simply delegating to Node.js `fs.readFileSync`, the behavior seems to follow stdlib conventions.
