### ISSUE TITLE
How to specify `content-length-range` for S3 `putObject`?

### ISSUE THREAD

**Issue by ryancole** [aws/aws-sdk-js#643]
I don't know if this is possible with `putObject`, to S3, but I found the following [link](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html) via Google. It mentions a `content-length-range` setting that would restrict direct-to-S3 upload file size on S3's side. I'm interested in limiting file upload sizes to S3 in a scenario where I'm pre-signing `putObject` requests for my users. I could honor the file size that the user provides to my server-side code, and check the size there before providing a valid signed URL, but that seems not optimal.

**Comment by lsegal** [comment]
@ryancole the `content-length-range` policy value is part of the **POST object** operation, not putObject. The AWS SDK for JavaScript currently does not support POST operations; though you can use other tools (or this [document](http://aws.amazon.com/articles/1434)) to set up that operation.

**Comment by nicka** [comment]
Still don't get why this isn't possible with signed urls.

**Comment by aleclarson** [comment]
How can I limit `contentLength` of a pre-signed url for `putObject`, if `content-length-range` is not available?

**Comment by aleclarson** [comment]
I'll try creating only the `Policy` and `Signature` query params on the server-side (instead of creating a pre-signed url). Then I'm using `FormData` with `XMLHttpRequest` to perform the upload on the client-side.

**Comment by chadbrewbaker** [comment]
Here is how Both does it, https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3.html#generating-presigned-posts
