### ISSUE TITLE
PageSpeed Insights complains about script not gzipped

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#644]
Srs.,

I have and issue with you guys not gzipping the javascript on https://sts.amazonaws.com/?Action=AssumeRoleWithWebIdentity&RoleArn=***&RoleSessionName=web-identity&Version=2011-06-15&WebIdentityToken=*****

I don't get the 100% on Google PageSpeed Insights due to this, it's a Cognito script.

PageSpeed: https://developers.google.com/speed/pagespeed/insights/

My page: http://m.jtavares.com.br.s3-website-us-east-1.amazonaws.com/

Score Now: 99/100 (Used to be 100/100)

![insights2](https://cloud.githubusercontent.com/assets/5229948/8409632/905fe6ca-1e4f-11e5-887c-37525dc7dc36.png)

![insights1](https://cloud.githubusercontent.com/assets/5229948/8409591/4b3943fc-1e4f-11e5-9fc7-eb474d66fa89.png)

Can you guys please gzip your Cognito call-up script?

**Comment by AdityaManohar** [comment]
@ramonck 
This is the service response from AWS Security Token Service (STS). The actual request does include the `Accept-Encoding:gzip, deflate, sdch` header. It is left to the service whether they wish to compress content before wire transport. There is really nothing that the SDK can do to mitigate this.

I also picked the response of the STS call from your page and ran it through gzip compression for comparison. Here are the results:

```sh
-rw-r--r--   1 adityamanohar  Users      1678 Jun 29 12:00 response
-rw-r--r--   1 adityamanohar  Users      1076 Jun 29 12:00 response.gz
```

Your gaining close to `600 bytes` on compressing the response. There *may not* be any cost benefit when you compare the time taken to transmit 600 additional bytes vs. the time taken to compress this content.

FWIW, I would recommend opening an issue on the [AWS STS Forum](https://forums.aws.amazon.com/forum.jspa?forumID=76) (part of the AWS Identity and Access Management forum) to request for this feature.

Hope this helps!

**Comment by ramonck** [comment]
Thanks for the feedback, I'm not too worried about the size, I'm worried about the score, want to keep up the 100%.

What would be a good practice for lazy loading the unath role in cognito so I don't have this issue on page load, that way I would turn around this issue and keep the 100% without waiting for a 600kb reduction.

Best Regards,

**Comment by AdityaManohar** [comment]
You should be able to lazy load your Cognito credentials by hooking into the `window.onload` or `(document).ready()` (looks like you are using jQuery) handlers.

Let me know if this helps!

**Comment by ramonck** [comment]
I'm already doing that, I had a problem calling the Cognito long after aws sdk has been loaded, it's async already. 

The problem is that today I call cognito right after exactly within a "document.ready" in JQuery, but the problem is that Google's Page Insights is parsing the page until it finished the initial load, therefore I have to call cognito when I click on a link.

I'll play around and see calling up cognito unauth within a "link", JQuery -> on('click'...
let's see how it rolls out, not sure if it will be fast enough.

Best Regards,

**Comment by AdityaManohar** [comment]
From `frontend.js` it looks like you are fetching the SDK and getting Cognito credentials when the `cjs.min.js` loads:

```javascript
$.getScript('js/aws-sdk.min.js', function() {
  //  window.addEventListener('awsLoaded', function() {
  var params = {
    RoleArn: "arn:aws:iam::215507325553:role/Cognito_jtsiteUnauth_Role",
    IdentityPoolId: 'us-east-1:511614d4-4078-4d39-be6c-cfd9bf7692fe'
  };
```

This will be treated by the browser as a synchronous script because it will not load and parse the next script file until this script file has been parsed and executed completely.

What I was suggesting earlier was to register a handler with the `window.onload` event or jQuery's `$(document).read()` which will execute after all synchronous script loading happens.

Hope this helps!

**Comment by ramonck** [comment]
Thanks for the help, I did get the 100% back :), yes!

I only call cognito now after clicking where there is an action with Lambda, so there's a need for cognito. It's good because my customer will save on API calls to Cognito at least on the first page look only if someone visited by mistake, if it was a bot, etc. So the effort was valid :+1: 
Best Regards
