### ISSUE TITLE
Deleting an Object From S3 Causes Unexpected Error in AWS-SDK Node Module

### ISSUE THREAD

**Issue by Bipsy** [aws/aws-sdk-js#648]
So, I am trying to delete a file from S3 using the following code snippet:

s3.deleteObject({ Bucket: <name_of_bucket>, Key: <key_name> }, callback);

It does in fact delete the file, but afterwards crashes at the following location and with the following message:

/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:107:43

Cannot ready property _id of undefined

Node Version: 0.12.4
AWS-SDK Version: 2.1.36

I am very interested in having this resolved. If there is any other information that would be useful please let me know.

**Comment by lsegal** [comment]
@Bipsy do you have code showing what's actually in your callback? Do you have a call to `_id` in there?

**Comment by Bipsy** [comment]
It seems I have wasted your time. I apologize for this. I was confused by the stack trace, but you are correct. The error was in my callback. Thank you for responding so quickly and pointing me in the right direction. Also, want to say the documentation for the module is superb. Well done.
