### ISSUE TITLE
SQS Messages get created but throws a lot of "UnknownEndpoint: Inaccessible host:" errors

### ISSUE THREAD

**Issue by imranansari** [aws/aws-sdk-js#649]
I'm executing a script from my macbook, to insert around 50k messages in SQS, why do I keep getting the error below.

I have the error on "unknown" endpoint set to "retry", but why is this a problem to begin with ??
works fine if I try inserting couple of hundred messages without any errors though.

{ [UnknownEndpoint: Inaccessible host: `sqs.us-west-1.amazonaws.com'. This service may not be available in the `us-west-1' region.]
  message: 'Inaccessible host: `sqs.us-west-1.amazonaws.com\'. This service may not be available in the `us-west-1\' region.',
  code: 'UnknownEndpoint',
  region: 'us-west-1',
  hostname: 'sqs.us-west-1.amazonaws.com',
  retryable: true,
  originalError: 
   { [NetworkingError: getaddrinfo ENOTFOUND sqs.us-west-1.amazonaws.com]
     message: 'getaddrinfo ENOTFOUND sqs.us-west-1.amazonaws.com',
     code: 'NetworkingError',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'sqs.us-west-1.amazonaws.com',
     region: 'us-west-1',
     retryable: true,
     time: Fri Jul 03 2015 11:23:02 GMT-0700 (PDT) },

**Comment by mhart** [comment]
Check that it's not a `ulimit` restriction that's causing this – Mac's have low defaults for this. (Google "ENOTFOUND ulimit" for more info).

May be the same as #145 

What version of node.js are you using?

**Comment by AdityaManohar** [comment]
@imranansari This looks like it is related to #528. This is typically related to underlying network / DNS resolver issues and there is not much that the SDK can do here besides retrying. It looks like as of SDK `v2.1.18` we are retrying this class of errors. Which version of the SDK are you using?

**Comment by AdityaManohar** [comment]
@imranansari I'm marking this as closed as it is not an SDK issue. If you haven't already, I would recommend upgrading to v2.1.18 of the SDK or higher where these class of errors are being retried. 

Feel free to reopen this issue or open another issue if you have other questions.

**Comment by jrencz** [comment]
Just for the record: I bumped into the same issue (yet via Serverless) and the answer by @mhart was helpful enough to make me reboot the machine. It helped

**Comment by kodayashi** [comment]
I was doing development work at the office, then went home and restarted my node app and started getting this. I ran `sudo killall -HUP mDNSResponder` on my Mac (macOS) to flush the DNS cache and boom it started working.
