### ISSUE TITLE
Support npm usage for front-end development

### ISSUE THREAD

**Issue by yoannmoinet** [aws/aws-sdk-js#651]
We're using aws-sdk-js both on the back and on the front.

But we're now only using npm to get our dependencies for both (bower was randomly crashing our build machine).

I had to fork this depot to remove the `dist` folder from the `.npmignore` listing to be able to get both scripts (front and back) from npm.

Do you have a better way to do this? 
To stay in sync with your package instead of having to fork it.

Thanks.

**Comment by lsegal** [comment]
> Do you have a better way to do this? 

Using `bower` is the supported way to use the SDK via package management in the browser. I would suggest using that tool. If you are running into problems with your build machine, I would recommend opening an issue against the [bower/bower](https://github.com/bower/bower) project on GitHub to have that resolved. I cannot resolve any crashes or failures when using bower on my machine.

Note that bower is just a simple wrapper around Git to grab the source at the latest tag, so you could emulate this with basic git commands if you were interested.

**Comment by yoannmoinet** [comment]
I understand.
It was just a move in the direction of npm's [way of seeing things](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging).
I'm okay with keeping my fork up to date myself.

**Comment by lsegal** [comment]
@yoannmoinet you probably don't need a fork to do this:

```sh
curl -O https://sdk.amazonaws.com/js/aws-sdk-$(npm dist-tag ls aws-sdk | cut -d " " -f 2).min.js
```

**Comment by yoannmoinet** [comment]
@lsegal thank you for the tip.

I don't think I can add this into our workflow, but I'll have another way of getting this at least.

**Comment by jacob-israel-turner** [comment]
I want to +1 this.  I'm creating a ReactNative app, which out of the box uses NPM as the package manager.  It's not possible for us to switch our project to Bower.

**Comment by AdityaManohar** [comment]
@yoannmoinet @jacob-israel-turner I've pushed a fix which removes the `dist/` directory from .npmignore.

**Comment by yoannmoinet** [comment]
thanks, appreciated.

**Comment by jacob-israel-turner** [comment]
:clap:
