### ISSUE TITLE
[SNS] Error when setting MessageAttributes

### ISSUE THREAD

**Issue by askmon** [aws/aws-sdk-js#652]
We are trying to publish a message to SNS using Javascript SDK (latest version). It works fine, but now we are trying to set a TTL and are getting the following error:

`UnexpectedParameter: Unexpected key 'MessageAttributes' found in params`

And this is how we are trying to set the TTL (Without it the publish works):

`Message:'{\"GCM\":\"{\\\"data\\\":{\\\"message\\\":\\\"Hello World\\\"}}\",\"APNS\":\"{\\\"aps\\\":{\\\"alert\\\":\\\"Hello World\\\",\\\"sound\\\":\\\"default\\\",\\\"content-available\\\":1}}\"}'
MessageStructure:'json'
TargetArn:'arn:aws:sns:us-east-1:x:endpoint/GCM/x/x'
MessageAttributes:
  'AWS.SNS.MOBILE.GCM.TTL':
    DataType:'String'
    StringValue:'300'
  'AWS.SNS.MOBILE.APNS.TTL':
    DataType:'String'
    StringValue:'300'`

(The x is replacing our topic values).

We've followed the following docs:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html#publish-property

Can you please check why this error message occurs?

Thanks!

**Comment by AdityaManohar** [comment]
It looks like you have incorrectly formatted coffeescript. I am not able to reproduce the problem with the following parameters:
```javascript
params = { 
  Message: JSON.stringify({default: 'test'}),
  MessageStructure: 'json',
  TargetArn: 'arn:aws:sns:us-west-2:012345678912:foo-bar',
  MessageAttributes: { 
    'AWS.SNS.MOBILE.GCM.TTL': { 
      DataType: 'String', 
      StringValue: '300' 
    },
    'AWS.SNS.MOBILE.APNS.TTL': { 
      DataType: 'String', 
      StringValue: '300' 
    } 
  } 
}
```
On an related note, the `Message` body in your sample code above also looks like incorrectly stringified JSON. 

Hope this helps

**Comment by askmon** [comment]
Oh sorry! The format was gone when I pasted the code. Anyway, I've made a Javascript to send and it works, so it's not an SDK issue. Thanks for the help and sorry for the work!
