### ISSUE TITLE
Memory leak in getObject method.

### ISSUE THREAD

**Issue by solker** [aws/aws-sdk-js#656]
Hello, I have an express app that receive a request with specific object key and download this object via `s3.getObject` method. Here is a code.

```js
function getFileFromS3(file_name) {
  logger('info', 'Downloading the file ' + file_name + ' from S3.')

  var params = {Bucket: s3_config.bucket, Key: 'Raw/' + file_name};
  var deferred = Q.defer();

  s3.getObject(params, function(err, data) {
    if (err) {
      logger('error', 'Error while downloading files from S3.');
      deferred.reject(err);
    }
    else {
      logger('info', 'The file ' + file_name + ' have been downloaded successfully.');
      deferred.resolve(data);
    }
  });

  return deferred.promise;
}
``` 

Problem that after each request I have minus 10Mb in my memory. How can I fix that?

**Comment by lsegal** [comment]
Hi,

This is not a memory leak, `getObject()` buffers the entire object contents into memory in the `data.Body` parameter as a Buffer object. If you are looking to do something with the body contents, I would suggest using [s3.getObject(...).createReadStream()](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-examples.html#Amazon_S3__Streaming_Objects_to_Files_on_Disk__getObject_) to stream contents from S3 instead.

**Comment by AdityaManohar** [comment]
@solker I'm marking this as closed because this is not an issue with the SDK. Feel free to reopen this issue or open another issue if you have other questions.

FWIW here is some sample code to elaborate what @lsegal mentioned above:

```javascript
var AWS = require('aws-sdk');
var fs = require('fs');

var s3 = new AWS.S3();
var fileStream = fs.createWriteStream('path/to/file');

var s3Stream = s3.getObject(params).createReadStream();
// You can alternatively pipe this into a HTTP response stream
s3Stream.pipe(fileStream);
```
