### ISSUE TITLE
Setting custom headers on upload

### ISSUE THREAD

**Issue by MathieuLoutre** [aws/aws-sdk-js#660]
Hi there,

I've been using the SDK quite happily for my plugin `grunt-aws-s3` which handles upload/download/delete/copy flow for S3 through Grunt.

One of the user recently reported that he wasn't able to set custom headers (without the x-amz-meta prefix) through the plugin (link to discussion and example: https://github.com/MathieuLoutre/grunt-aws-s3/issues/75). I had a look at the docs and couldn't find anything but he seems to be able to do it through direct upload fro the browser (here: https://aws.amazon.com/articles/1434).

Any plans to support that in the SDK soon?

**Comment by lsegal** [comment]
Hey @MathieuLoutre, great question.

It's possible to set custom headers in the SDK by hooking into the event system and modifying the request object directly:

```js
s3.putObject(params).
  on('build', function(req) { req.httpRequest.header['Custom-Header'] = 'value'; }).
  send(function(err, data) { ... });
```

You could expose this in your plugin if you wanted.

Hope that helps!

**Comment by MathieuLoutre** [comment]
Ooooh, that's nice. Will give it a try. Must say that I only searched the S3 documentation and didn't think to look in Request. Thanks! Will report how I get on.

**Comment by AdityaManohar** [comment]
@MathieuLoutre I'm marking this as closed since there hasn't been any recent activity on it. Feel free to reopen this issue or open another if you have other questions.

**Comment by MathieuLoutre** [comment]
@lsegal Hi there. I finally got around to try this properly and your example (and the docs') isn't working for me with the latest SDK. I can see that it goes through and the header is properly sent with the request but when the file is requested after upload the custom header doesn't show. Am I missing something?

**Comment by joelwass** [comment]
@MathieuLoutre are you uploading to s3 like this? what is the issue you're experiencing?

![screen shot 2016-04-24 at 2 07 02 pm](https://cloud.githubusercontent.com/assets/7344422/14769459/75bfc61e-0a26-11e6-951f-1c38c70e15ad.png)
