### ISSUE TITLE
Equivalent of ssl.certificate_authority configuration in php sdk

### ISSUE THREAD

**Issue by ianbytchek** [aws/aws-sdk-js#662]
I'm dealing with exactly the same issue I dealt awhile ago with PHP sdk – aws/aws-sdk-php#408. 

Is there a way to provide `ssl.certificate_authority = 'system'` with JS sdk to make it use system certificates?

**Comment by lsegal** [comment]
@ianbytchek  the AWS SDK for JavaScript delegates to your Node.js environment to load CA bundles. You can see [this question](http://stackoverflow.com/questions/20658120/nodejs-unable-to-read-default-cas-in-ubuntu) for more information, but generally speaking, the solution to loading your system certificates would be the same as the general solution for Node.js.

Note that you can configure default HTTP options with a CA bundle: 

```js
AWS.config.httpOptions = {ca: certBuffer};
```

**Comment by ianbytchek** [comment]
@lsegal thanks! That makes perfect sense, I'll dig in that direction.
