### ISSUE TITLE
Does this  fully support cognito functions ?

### ISSUE THREAD

**Issue by asanka-x** [aws/aws-sdk-js#664]
I am getting an error saying action not found when using cognito developer identity (method name mentioned below)

getOpenIdTokenForDeveloperIdentity

**Comment by lsegal** [comment]
Can you provide code that reproduces this along with the version of the SDK you're using and Node.js or browser versions?

**Comment by AdityaManohar** [comment]
I'm marking this as closed since there hasn't been any recent correspondence. Feel free to reopen this issue or open another issue if you have other questions.
