### ISSUE TITLE
API Gateway ETA?

### ISSUE THREAD

**Issue by ac360** [aws/aws-sdk-js#665]
Is there an ETA for supporting the AWS API Gateway in this SDK?

**Comment by joshrtay** [comment]
+1

**Comment by johntitus** [comment]
+1

**Comment by AdityaManohar** [comment]
Amazon API Gateway is not currently supported by the SDK because it utilizes HAL (Hypertext Application Language) which is not yet supported. We'll update this issue when we have more information.

**Comment by doapp-ryanp** [comment]
+1

**Comment by southpolesteve** [comment]
@AdityaManohar will you be using the same API as documented here?https://docs.aws.amazon.com/apigateway/api-reference/

**Comment by binoculars** [comment]
:+1: @wv hoping for announcement on this tomorrow!

**Comment by nisaacson** [comment]
+1

**Comment by gimenete** [comment]
:+1:

**Comment by joostfarla** [comment]
This would be great! :+1:

**Comment by gimenete** [comment]
If anybody is interested I found this npm module
https://www.npmjs.com/package/jaws-api-gateway-client

There's no documentation and probably doesn't cover all the options but I downloaded the source code and it is pretty straightforward.

**Comment by doapp-ryanp** [comment]
@gimenete that is from the [JAWS framework project](https://github.com/jaws-framework/JAWS/) I and @ac360 maintain.  While you can use it, we do not wan't people to get too dependent on it because we feel its something AWS should own and maintain in their SDKs (I believe it is already in Java aws SDK).  I guess what I'm saying is don't settle with ours...

**Comment by chrisradek** [comment]
The latest version of the SDK, v2.2.12, has just been released and includes API Gateway support.

**Comment by ac360** [comment]
:+1: Nice @chrisradek!!!  Really great job getting that done!
