### ISSUE TITLE
S3: Uploaded gz file in bad format

### ISSUE THREAD

**Issue by canhoviet** [aws/aws-sdk-js#666]
Hi,
I'm using AWS S3 api putObject to put a gz file to S3: 
```javascript
var fileStream = fs.createReadStream('a.tar.gz');
var param = {
		Body: fileStream,
		Bucket: 'myBucket',
		Key: 'a.tar.gz'
};
s3.putObject(param, function(err, data){
});
```
After running the code to put the file a.tar.gz to S3, I downloaded it from the bucket "myBucket" and verified that the download file and original file are in same size. I opened downloaded file using 7-Zip.  However, 7-Zip reported error: "Can't open file a.tar.gz as archive".  I was able to open the original file using 7-Zip.

I tried adding some headers like: Content-Type: "application/x-gzip" , Content-Length: file length but it didn't work.

My environment:
* Node: 0.12.7
* aws sdk : 2.1.39

Any idea on how  uploaded .gz file is in bad format ?

**Comment by canhoviet** [comment]
I downloaded the file by double-clicking on the file and after "Save As" dialog appeared, clicked "Save". I also mounted s3 bucket to a local folder and using tar command to unzip the file but the command failed. So, the problem the file on the bucket is damaged.

**Comment by AdityaManohar** [comment]
@canhoviet I am not able to reproduce the issue with the code that you posted. Extracting the downloaded archive with `tar -xzf foobar.tar.gz` seems to work correctly for me. Are you able to extract the archive before uploading it with 7-Zip?

**Comment by canhoviet** [comment]
Thanks Aditya
> Are you able to extract the archive before uploading it with 7-Zip?

Sure. It seems that the uploaded file is corrupted. I tried with many .gz files and the same issue occurred. So, I guess the issue is caused by putObject api ?

**Comment by canhoviet** [comment]
My mistake. I forgot to remove encoding param in the function fs.createReadStream
