### ISSUE TITLE
S3 Multipart upload via cloudfront distribution

### ISSUE THREAD

**Issue by SDiniz** [aws/aws-sdk-js#669]
This is mainly a copy of the issue: https://github.com/aws/aws-sdk-js/issues/423, but since it has been fixed, and I still keep getting the 503's SignatureDoesNotMatch, I'm reposting, hoping to get an example of how to configure this correctly, I even tried harcoding the cloudfront endpoint on populateURI, but to no avail.

    <Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
    <AWSAccessKeyId>...</AWSAccessKeyId>
    <StringToSign>POST

    application/octet-stream; charset=UTF-8

    x-amz-acl:private
    x-amz-date:Tue, 28 Jul 2015 15:22:01 GMT
    x-amz-user-agent:aws-sdk-js/2.1.40
    /bucket-name/test_797965294</StringToSign>
    <SignatureProvided>...</SignatureProvided>
    <StringToSignBytes>....</StringToSignBytes><RequestId>7488F0A2F70E4AC5</RequestId>
    <HostId>...</HostId>
    </Error>

I'm using the following code start the multi-part upload:

    AWS.config.update({
    	accessKeyId: 'XXXXXXXXXXXXXXXXX',
    	secretAccessKey: 'XXXXXXXXXXXXXXXXXX'
    });
    
    var s3Client = new AWS.S3({
    	endpoint: 'XXXXXXXX.cloudfront.net',
    	s3BucketEndpoint: true,
    	region: 'eu-west-1'
    });
    
    var TEMP_filename = 'test_' + Math.floor(1000000000*Math.random());
    
    var params = {
    	Bucket: 'bucket-name',
    	Key: TEMP_filename, 
    	ACL: 'private'
    };
    
    s3Client.createMultipartUpload(params, function(err, data) {
    	if (err) {
    		console.log(err, err.stack); // an error occurred
    	} else {
    		console.log(data);           // successful response
    	}
    });

And the result is:
![image](https://cloud.githubusercontent.com/assets/1837715/8935728/21eb063a-3546-11e5-9113-0338e7154e7c.png)

![ticket1](https://cloud.githubusercontent.com/assets/1837715/8935792/79762be6-3546-11e5-9f47-f8ad701ee859.jpg)

Am I missing something in the configuration of the client?

It's also worth to mention, that when using, AWS.S3.ManagedUpload, almost everything works perfectly. If the file size is smaller than the required to make an multipart upload, everything goes ok, but when switching to an multipart upload everything breaks again. It's always on the POST requests, the PUT requests seem to work fine.

Or maybe the createMultipartUpload, can't be used with cloudfront? I will experiment, only using the `uploadPart` trough Cloudfront to see if this works.

EDIT: Using `uploadPart` with an Cloudfront endpoint, also breaks the upload, and I start to receive `SignatureDoesNotMatch` errors.

BTW, I'm using the latest version of the SDK: aws-sdk-js/2.1.40

**Comment by AdityaManohar** [comment]
@SDiniz 
Is your CloudFront distribution configured to forward query strings? I am not able to reproduce the problem on a test distribution that I have setup. 

I have configured the origin behavior to forward query strings, whitelist CORS headers, and allow PUT an POST requests. Here is a screenshot of what that looks like.

![screen shot 2015-07-29 at 12 04 59 pm](https://cloud.githubusercontent.com/assets/966440/8967169/37b0816c-35ea-11e5-9037-194637a38681.png)

Let me know if this helps!

**Comment by SDiniz** [comment]
@AdityaManohar actually, no, I didn't had that configured, the put and post were already configured, but the forward headers and query strings no. I will test this new configurations ( just need to wait a little for the changes to update on the distribution, and I will get back to you.

Thanks

**Comment by SDiniz** [comment]
EDIT:
@AdityaManohar, you were right, everything is working now, I guess it was missing the forward query strings, I didn't even noticed that there were parameters begin passed by query string.

Thanks once again, this can be closed!
