### ISSUE TITLE
Support KeepAlive for HTTP requests

### ISSUE THREAD

**Issue by parisholley** [aws/aws-sdk-js#671]
Currently, neither HTTP (no agent configured ) or HTTPS agent within http/node.js is using an agent with keep alive configured. For a high number of calls (for example processing messages of a large queue), it is throttled tremendously. I'm hacking in a agent for testing, which has shown a tremendous improvement. Going to research a bit more and potentially issue a pull.

**Comment by AdityaManohar** [comment]
@parisholley The SDK is supported across Node.js v0.8, v0.10, and v0.12. Keep-Alive supported landed only in Node v.0.12. That being said it is simple to configure a keep-alive agent with the SDK by using `httpOptions`

```javascript
var AWS = require('aws-sdk');
var http = require('http');
AWS.config.update({
  httpOptions: {
    agent: new http.Agent({keepAlive: true})
  }
})
```

Let me know if this helps.

**Comment by parisholley** [comment]
Already processed my backlog, but I've implemented this and sure it solves my issue. Though I wonder if it is worth detecting the node version, and implementing by default, or updating documentation to note the performance gain by using an agent.

**Comment by AdityaManohar** [comment]
@parisholley Given how simple it is to use a keep-alive agent, I think documenting this is a better approach for now. I'll make sure to add a note about using keep-alive agents to the configuring section of our developer guide. Thank you for bringing this to our attention!

**Comment by Alonkad** [comment]
We also experienced this issue with Firehose.
We have a NodeJS server that accepts requests and writes to Firehose (the SDK uses HTTPS agent for that).
When the throughput reached a certain level (depends on the VM) we started getting timeouts (after the default 2 minutes).
Adding keep-alive solved the problem (tested with twice the load that originally failed).

We read the documentation - no mention of the above subject.
This is highly important for services like Firehose which are build for scale (users will experience this issue real quick)

Please consider adding keep-alive by default.
