### ISSUE TITLE
S3 Key length limit in ElasticTranscoder API (255 chars) too restrictive?

### ISSUE THREAD

**Issue by gmorpheme** [aws/aws-sdk-js#672]
https://github.com/aws/aws-sdk-js/blob/master/apis/elastictranscoder-2012-09-25.normal.json#L1805 seems to limit the length of S3 keys to 255 characters in the elastic transcoder API.

I'm getting a whole load of 

```
Member must have length less than or equal to 255]
```

errors when trying to transcode files I've "aws s3 sync"ed to S3 because the key names are too long for the API to handle. But they're plainly not too long for S3: the objects already exist in S3. (It's Input.Key that's triggering the validation.)

I believe S3 keys can be up to 1028 bytes (UTF-8 encoded) so 255 chars is seems overly restrictive for anything but malicious input data. Not many keys are going to consist entirely of 4-byte characters.

The restriction means an awkward workaround of copying to temporary locations in S3 I think.

Is there a real 255 limit imposed by ETS for other reasons? Or is this just a feature of the way the API input is validated? In which case can the validation be smarter?

**Comment by AdityaManohar** [comment]
@gmorpheme The `Key` parameter length is not enforced by the SDK. Unfortunately, I don't have an answer for why the `Key` length is limited by Elastic Transcoder to 255 characters. I would recommend opening an issue on the [Amazon Elastic Transcoder Forum](https://forums.aws.amazon.com/forum.jspa?forumID=147) and let them know about this limitation.

In the meantime, I will also try to get in touch with the Elastic Transcoder team to get some clarification on this issue.

Hope this helps!

**Comment by AdityaManohar** [comment]
@gmorpheme I did get confirmation from the Elastic Transcoder team that the Key length is being validated by the service. I don't have an an ETA for when this might be fixed.

Like I mentioned earlier, I would recommend opening an issue on the [Amazon Elastic Transcoder Forum](https://forums.aws.amazon.com/forum.jspa?forumID=147) to let them know of the limitation. 

I'm marking this as closed as there isn't much that the SDK can do to at this point. It also looks like you do have a workaround for now. Feel free to reopen this issue or open another issue if you have other questions.

**Comment by sharang-d** [comment]
Does anyone know if the API made changes to accommodate larger input keys? I could not find anything on the Amazon Dev Forums. Thanks!
