### ISSUE TITLE
ContentMD5 for s3.getSignedUrl

### ISSUE THREAD

**Issue by thattommyhall** [aws/aws-sdk-js#675]
I can't get a signed request to work with ContentMD5.

If I do 

```
var s3_params = {
  Bucket: bucketName,
  ContentType: 'image/jpeg',
  ContentMD5: "f0oxEyT+4qR3E/70ID0PfA==",
  ACL: 'public-read',
  Key: 'TESTDIRECT.jpeg',
  Body: fs.readFileSync('/home/thattommyhall/TEST.jpg')
};


s3.putObject(s3_params, function(err, data){
  if(err){
    debug('put', 'error', err);
  }
  else {
    // debug('put', data);
  }
});
```

It works, but 

```
var s3_params_sign = {
  Bucket: bucketName,
  ContentType: 'image/jpeg',
  ContentMD5: "f0oxEyT+4qR3E/70ID0PfA==",
  ACL: 'public-read',
  Key: 'TESTsigned.jpeg',
  Expires: 6000,
};

s3.getSignedUrl('putObject', s3_params_sign, function(err, url){
  if(err){
    debug('error', err);
  }
  debug(url);
});

```

will not work if I have ContentMD5.

I have tried adding Content-MD5 headers to the put (as the content type was not set until I added headers).

I made a project at https://github.com/thattommyhall/aws-sdk-bug, you should be able to run 

```
$ node example.js | python upload.py 
```
(but I have also tried it with `curl --upload-file` )

**Comment by AdityaManohar** [comment]
@thattommyhall I see [here that you are creating the signed url](https://github.com/thattommyhall/aws-sdk-bug/blob/master/example.js#L36) *without* the `ContentMD5` parameter set.

You will have to create that signed url with the `ContentMD5` parameter *as well as* set the `Content-MD5` header when PUTting to the signed URL.

For example:
```javascript
// NOTE: This is a private API and may change in the future
var md5 = AWS.util.crypto.md5('hello' ,'base64');

var params = {
  Bucket: 'bucket', 
  Key: 'key', 
  ContentMD5: md5, 
  ContentType: 'text/plain'
}
var url = s3.getSignedUrl('putObject', params);

// Using jQuery in the browser
$.ajax({
  url: url, 
  method: 'PUT', 
  data: 'hello', 
  contentType: 'text/plain', 
  headers: {
    'Content-MD5': md5
  },
  success: callback
});

```
The above code works fine when PUTting to a pre-signed URL with Content-MD5 specified.

Hopes this helps clarify things!

**Comment by thattommyhall** [comment]
I was commenting and uncommenting those lines, sorry I committed the one with it commented out.

I have updated the project, with the example directly PUTing using the `request` module immediately after generating the signed url using your code.

https://github.com/thattommyhall/aws-sdk-bug/blob/master/example.js

Both Content-MD5 are commented out now, but I have tried all 4 options of using them, the only one that works is not setting it in both the sign and PUT

**Comment by AdityaManohar** [comment]
@thattommyhall I missed the fact that you're using the SigV4. I was able to reproduce the issue and I've pushed up a fix which should land in master soon.

Thanks very much for reporting this!

**Comment by AdityaManohar** [comment]
@thattommyhall Can you also explain what your use case is that is causing this issue?
