### ISSUE TITLE
Cognito WebIdentityCredentials, help!

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#677]
Hey,

I'm trying to use Cognito WebIdentityCredentials, no success yet :(

Can you guys look and see what I'm doing wrong? I'm using the same code I see here: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-configuring-wif.html

The site: http://sig.maxwal.com.br/

**Comment by AdityaManohar** [comment]
Can you post the some sample code that you are using?

**Comment by ramonck** [comment]
This is what I'm using, I'm receiving the id_token from Google, but When using in AWS SDK JS I'm not getting any access or log within the console.
```AWS.config.credentials = new AWS.WebIdentityCredentials({
  RoleArn: 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/<WEB_IDENTITY_ROLE_NAME>',
  WebIdentityToken: ACCESS_TOKEN
});```

**Comment by AdityaManohar** [comment]
> When using in AWS SDK JS I'm not getting any access or log within the console

What are you logging? Can you post the the code that you are using? 

Note that these credentials are loaded lazily only when a request is made, and not when the credential provider is constructed.

**Comment by ramonck** [comment]
```
  console.log(profile.getEmail());
  console.log(googleUser.getAuthResponse().id_token);
  AWS.config.region = 'us-east-1';
  AWS.config.credentials = new AWS.WebIdentityCredentials({
    RoleArn:  'arn:aws:iam::XXXXXXXXX:role/XXXXXXXXX_Role',
    WebIdentityToken: googleUser.getAuthResponse().id_token
  });

  console.log('You are now logged in.');
```

I don't see any logging in the AWS Console

**Comment by ramonck** [comment]
hey, anyone there?

**Comment by AdityaManohar** [comment]
@ramonck Which AWS console are you referring to? The Cognito console?

The `WebIdentityCredentials` provider uses AWS.STS behind the scenes. If you want to use Amazon Cognito then you will have to use the [`CognitoIdentityCredentials`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html) provider.

Also like I mentioned earlier, the credential providers load credentials lazily, i.e. credentials will be fetched only when a request is made. not when credential provider is constructed.

Hope this helps clarify things.

**Comment by ramonck** [comment]
Hey Aditya,

Didn't know that WebIdentityCredentials uses STS.
Changed my code to the CognitoIdentityCredentials and nothing yet :(

![cognito](https://cloud.githubusercontent.com/assets/5229948/9241040/7861f2b2-4144-11e5-855b-344333f40555.png)

**Comment by AdityaManohar** [comment]
@ramonck Can you share the code you are using?

**Comment by ramonck** [comment]
Sure @AdityaManohar,

```
AWS.config.region = "us-east-1", 
        AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: "us-east-1:6a5ab06b-9705-4ec1-887a-6bf300e57692",
        RoleArn: "arn:aws:iam::383382744383:role/Cognito_sigAuth_Role",
        Logins: {
            "accounts.google.com": n.getAuthResponse().id_token
        }
    }), console.log("You are now logged in."), AWS.config.update({
        region: AWS.config.region,
        credentials: AWS.config.credentials
    })
```

**Comment by AdityaManohar** [comment]
@ramonck Like I've mentioned above, *the credential providers load credentials lazily*, i.e. credentials will be fetched only when a request is made and *not* when the credential provider is constructed.

For it to create an identity and load credentials you need to make a request. For example:

```javascript
AWS.config.update({
  region: 'us-east-1',
  credentials: new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'us-east-1:00000000000000000000000'
  });
});

var dynamodb = new AWS.DynamoDB({region: 'us-west-2'});

dynamodb.listTables(function(err, data){
  if (err) console.log(err);
  else console.log(data);
});
```

**Comment by ramonck** [comment]
@AdityaManohar

I do have the update right after.

```
  AWS.config.update({
    region: AWS.config.region,
    credentials: AWS.config.credentials
  });
```

**Comment by AdityaManohar** [comment]
`AWS.config.update()` does not make any request. It merely sets attributes on the config object.

**Comment by ramonck** [comment]
@AdityaManohar 

Thanks for the feedback, I tried refresh, didn't work so I used the get and I'm getting an error.

```
  AWS.config.credentials.get(function(err) {
    if (err) {
      console.log("Error: "+err);
      return;
    }
    console.log("Cognito Identity Id: " + AWS.config.credentials.identityId);
  });
```

```
POST https://cognito-identity.us-east-1.amazonaws.com/ 400 (Bad Request) 
Error: NotAuthorizedException: Invalid login token. 
```

Looked on the internet and found this:
```

You are passing an expired or null token.

You are passing a valid token,but the Google App Id that you are using on your app doesn't match the one you have configured in your identity pool.
```

I'm signing out and signing in and it's still the same. And both client IDs are matching. What can be the issue now?

**Comment by AdityaManohar** [comment]
@ramonck I don't know the specifics of your identity pool configuration. I would recommend reading this [blog post which describes authentication in the browser with Amazon Cognito](http://blogs.aws.amazon.com/javascript/post/TxTUNTVES4AL15/Authentication-in-the-Browser-with-Amazon-Cognito-and-Public-Identity-Providers) and external providers.

From what I can see, your identity pool may not be configured with the correct Google Client ID. I would recommend following the blog post when creating your identity pool, and then try replicating the issue.

FWIW, it is not required to pass in a `RoleArn` to the `CognitoIdentityCredentials` provider if you already have configured your identity pool with IAM roles.

**Comment by ramonck** [comment]
Hey @AdityaManohar 

I did look at your post before as a reference to my implementation.

The only thing I see different is the nonauth users is not enabled. I don't want anyone nonauth in my case.

I have the Cliend ID configured in the Google+ tab, I'm not using OpenID.

I commented the RoleArn and nothing yet :(.

**Comment by ramonck** [comment]
Hello, anyone can help me?

**Comment by AdityaManohar** [comment]
@ramonck I would recommend following the [Amazon Cognito Developer Guide](http://docs.aws.amazon.com/cognito/devguide/identity/external-providers/google/) for JavaScript when integrating with Google+ sign in (you will have to select JavaScript as your platform on the top right of the page).

I'm not sure of the configuration of your Google+ project or you Cognito identity pool. Have you enabled your Google+ API in the Google Developer Console like it mentions in the Amazon Cognito Developer Guide? If not, I would start by enabling the Google+ API and see if you can get your setup working.

**Comment by ramonck** [comment]
@AdityaManohar I've all that setup correctly, I'm now trying to get the Google token into Cognito, and I'm getting that error. Can you help me? Do you have a test google account? Want me to create one for you?

The url is http://sig.maxwal.com.br

Best Regards,

**Comment by AdityaManohar** [comment]
@ramonck I was able to reproduce the error that you are getting with a Google Client ID that I created.

You will have to explicitly enable the Google+ API in to the Google Developer Console under

`APIs and auth > APIs > Social APIs > Google+ API ` and then click enable. This should fix it for you.

**Comment by ramonck** [comment]
@AdityaManohar That's ok too :(
![api_ok](https://cloud.githubusercontent.com/assets/5229948/9337096/8942a4aa-45b3-11e5-9ddd-3cb9f6a5ae18.png)

**Comment by turacma** [comment]
Hello, can you share an example id token you are trying to send that is being rejected by Cognito?

**Comment by ramonck** [comment]
@turacma Sure.
So on the console log of the webpage, when you do a sign in action you can see it, here's when I signed in

eyJhbGciOiJSUzI1NiIsImtpZCI6ImZjZWM5ODhmZWQ0OTFhZTA3YjEyN2Q2Yjg4MzZiNjdiNzg3Yjc4ZmEifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6IkJ5RGx1Q3Y3VC1BMk13V2wyM2hUc0EiLCJhdWQiOiI2ODY3MTYzOTg1NzItNmtqOWU1cmFtN2czZTE2dmVjcDIzMWZzYnVqbWN0bmkuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDkyNTQ1MjA0NjgzODUyODEwOTYiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiNjg2NzE2Mzk4NTcyLTZrajllNXJhbTdnM2UxNnZlY3AyMzFmc2J1am1jdG5pLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJyYW1vbmNrQGdtYWlsLmNvbSIsImlhdCI6MTQzOTkyMTU2NiwiZXhwIjoxNDM5OTI1MTY2LCJuYW1lIjoicmFtb24gbGltYSIsInBpY3R1cmUiOiJodHRwczovL2xoNS5nb29nbGV1c2VyY29udGVudC5jb20vLTg0SlJ5VHhKSE5ZL0FBQUFBQUFBQUFJL0FBQUFBQUFBQVE0L3FYNTJoMjF0ZEVVL3M5Ni1jL3Bob3RvLmpwZyIsImdpdmVuX25hbWUiOiJyYW1vbiIsImZhbWlseV9uYW1lIjoibGltYSIsImxvY2FsZSI6InB0In0.CiO8lrgeBWoTJVAUhPPHe_h7cHggh8nk7nBc8hYTJb5LaYlkv0etG30MF50L8UFHLwIHIyZWGuH_X4ptegHg45_YX2wlAZeQ-mw4bo_gpXkdz52Xcyyxewm_l0YRyqKtA0LAhmgjLjEq7zYrKzjpJNFObLfohBVgli-S9tRZ_Cx43ttxY3SyW0Vq6VVsZAgmO-QxGFiEU4pSYVO7iUHJurRLsnApKQXhUB2IjmLoaMdYEtOnqq2UqoUyo7JoqPoVytHeMVlmIWlj7UrGDYl9DrAdbU8m4LnsqGrMZNJ6-lTeuLmqIZqWZFxb9bOeTUVlTx8Y0dV7J3YtDBZFf47ECw

For easier copy & paste:
```
eyJhbGciOiJSUzI1NiIsImtpZCI6ImZjZWM5ODhmZWQ0OTFhZTA3YjEyN2Q2Yjg4MzZiNjdiNzg3Yjc4ZmEifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6IkJ5RGx1Q3Y3VC1BMk13V2wyM2hUc0EiLCJhdWQiOiI2ODY3MTYzOTg1NzItNmtqOWU1cmFtN2czZTE2dmVjcDIzMWZzYnVqbWN0bmkuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDkyNTQ1MjA0NjgzODUyODEwOTYiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiNjg2NzE2Mzk4NTcyLTZrajllNXJhbTdnM2UxNnZlY3AyMzFmc2J1am1jdG5pLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJyYW1vbmNrQGdtYWlsLmNvbSIsImlhdCI6MTQzOTkyMTU2NiwiZXhwIjoxNDM5OTI1MTY2LCJuYW1lIjoicmFtb24gbGltYSIsInBpY3R1cmUiOiJodHRwczovL2xoNS5nb29nbGV1c2VyY29udGVudC5jb20vLTg0SlJ5VHhKSE5ZL0FBQUFBQUFBQUFJL0FBQUFBQUFBQVE0L3FYNTJoMjF0ZEVVL3M5Ni1jL3Bob3RvLmpwZyIsImdpdmVuX25hbWUiOiJyYW1vbiIsImZhbWlseV9uYW1lIjoibGltYSIsImxvY2FsZSI6InB0In0.CiO8lrgeBWoTJVAUhPPHe_h7cHggh8nk7nBc8hYTJb5LaYlkv0etG30MF50L8UFHLwIHIyZWGuH_X4ptegHg45_YX2wlAZeQ-mw4bo_gpXkdz52Xcyyxewm_l0YRyqKtA0LAhmgjLjEq7zYrKzjpJNFObLfohBVgli-S9tRZ_Cx43ttxY3SyW0Vq6VVsZAgmO-QxGFiEU4pSYVO7iUHJurRLsnApKQXhUB2IjmLoaMdYEtOnqq2UqoUyo7JoqPoVytHeMVlmIWlj7UrGDYl9DrAdbU8m4LnsqGrMZNJ6-lTeuLmqIZqWZFxb9bOeTUVlTx8Y0dV7J3YtDBZFf47ECw
```

**Comment by turacma** [comment]
Can you confirm if you have google listed as an identity provider in the [IAM console](https://console.aws.amazon.com/iam/home?region=us-east-1#providers)? Based on the errors in our logs it seems that there may be an issue in the service if you register an OpenId Connect provider for Google and don't register the client ids used with Cognito, even if you don't use the OpenId Connect provider ***with*** Cognito.

We'll address this in a future service update, but please try one of the following to resolve your problem:

1. Register your Google client IDs in the OpenId Connect provider in the IAM console and associate this to your Cognito identity pool instead of the bare google client ID.
2. Delete the OpenId Connect provider from the IAM console.

**Comment by ramonck** [comment]
Bob, you nailed it!

I used to have a IAM accounts.google.com, deleted it from the IAM, also before that check marked ok the OpenID, then removed the IAM, made sure back in Cognito that the OpenID is gone then saved changes and everything is ok.

So the solution for now is not to have a OpenID and  GoogleClientID at the same time, only Google Client ID.

Best Regards,

**Comment by ramonck** [comment]
Thank you guys for the help!

**Comment by robinvalk** [comment]
@turacma It seems that the issue is still present. You can't have an identity provider via IAM and have the Google client id filled in Cognito.
