### ISSUE TITLE
Authentication using signature v2 does not work

### ISSUE THREAD

**Issue by StuAtGit** [aws/aws-sdk-js#678]
When I try code like so:

```
var awsConfig = {
	accessKeyId:amazonId,
	secretAccessKey:amazonPassword,
	sslEnabled:true,
	signatureVersion: 'v2'
};

var s3client = new aws.S3( new aws.Config(awsConfig) );
s3client.getObject( {
		Bucket: bucket,
		Key: key
	}, function( err, result ) {
		console.log("S3 result: " + result + " error: " + err );
	}
);
```
The library fails when it tries to set a (sub) property on the undefined "params" property here:

https://github.com/aws/aws-sdk-js/blob/master/lib/signers/v2.js#L14

It works fine if I remove the signatureVersion property or set it to v4.

I tried just hacking in the line:

```   
    var r = this.request;
    r.params = {};
    ...
```
And the original error no longer shows up, but I get an "Access Denied" error - so it looks like there is more going on then just a missed initialization.

I checked that the credentials were set:

    r.params.AWSAccessKeyId = credentials.accessKeyId;
    console.log("set access key to: " + r.params.AWSAccessKeyId);
    console.log("Secret access key: " + credentials.secretAccessKey );

And they matched up what  I put in - and what works with v4

When I log into my s3 console, it shows I'm in the us-east region, which should still support version 2, I believe. 

I do need version to work against s3 to rule out a bug in the library preventing me from accessing an "s3 lookalike" my company uses internally. So if I can get it working with version 2 against my personal s3 account, that would rule out the aws-sdk-js library having a bug.

I pulled the library down today, so it should be the latest, but for the sake of completeness, here is the version from my package.json:

 "version": "2.1.44",

Thanks!

**Comment by AdityaManohar** [comment]
@StuAtGit 
[`AWS.Signers.V2`](https://github.com/aws/aws-sdk-js/blob/master/lib/signers/v2.js) is not supported by Amazon S3. S3 supports a modified version of Signature Version 2. In the SDK this is implemented by [`AWS.Signers.S3`](https://github.com/aws/aws-sdk-js/blob/master/lib/signers/s3.js). You shouldn't have to specify this signer as the `AWS.S3` client picks this up by default. 

```javascript
var s3 = new AWS.S3({signatureVersion: 's3'});
```

If you want to use Signature Version 4, then you must specify this as an option.
```javascript
var s3 = new AWS.S3({signatureVersion: 'v4'});
```

Hope this helps clarify things!

**Comment by StuAtGit** [comment]
It does help :)

I was mainly testing my config against aws to cross-check what I was doing against an internal S3-lookalike cluster that did not support v4. It looks like it does support s3, so I'm good. Closing.

As far as clarify... I may have just moved the confusion in my head to a new layer.
