### ISSUE TITLE
uncaught exception in S3

### ISSUE THREAD

**Issue by gvelo** [aws/aws-sdk-js#680]
S3 request is throwing the following uncaught error after 'error' event handler execute properly.

    /node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
    NoSuchBucket: The specified bucket does not exist

this error break the event loop crashing the entire app

In the following code the error handler is executed but the error is throw anyways.

```javascript

    var params = {
      Bucket: 'wrongbucket', 
      Key: photo._id.toString(), 
    };

    var s3Req = S3.getObject(params);
    var st = s3Req.createReadStream();
    res.status(200).set({ 'Content-Type': photo.mimetype , 'Content-Length': photo.size });      
    st.pipe(res);

    s3Req.on('success',function() {      
      console.log("success");
    });

    s3Req.on('error',function(err) {
      res.status(500).send();
    }
```

I'm using 

aws-sdk@2.1.44
node v0.12.4

Thanks,

**Comment by AdityaManohar** [comment]
@gvelo I'm looking into this and will get back to you soon.

**Comment by AdityaManohar** [comment]
@gvelo 
This looks like it is similar to #397. This is just the default behavior of streams in Node.js.

Note that when using streams you want to hook into the stream's error event and not the event emitted by the `AWS.Request` object. 

Here is a modified version of your example: 

```javascript
var AWS = require('./');
var fs = require('fs');

var params = {
  Bucket: 'foo',
  Key: 'bar'
};

var s3 = new AWS.S3({region: 'us-west-2'});

var req = s3.getObject(params);
var read = req.createReadStream();
var write = fs.createWriteStream('/Users/aditm/bug');

req.on('error', function(err) {
  console.log(err);
});

read.pipe(write);
``` 

This code does not throw for me. Let me know if this helps!

**Comment by AdityaManohar** [comment]
@gvelo I'm marking this as closed as there hasn't been any recent activity. Feel free to reopen this issue or open another issue if you have other questions.

**Comment by gvelo** [comment]
Sorry for the long silence. You are right , this is the same that #397 , adding the event handler on the stream works for me.

Thanks,
