### ISSUE TITLE
Submit to jsdelivr

### ISSUE THREAD

**Issue by bradvogel** [aws/aws-sdk-js#681]
It'd be great to have this also hosted on jsdelivr.com. It would allow us to fetch aws-sdk with all our other scripts in a single request (e.g. `<script src="https://cdn.jsdelivr.net/g/jquery@2.1.4,underscorejs@1.8.3,aws-sdk@2.1.42">`)

See https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by wearhere** [comment]
+1

**Comment by AdityaManohar** [comment]
@bradvogel @wearhere I've opened up a pull request on jsdelivr: https://github.com/jsdelivr/jsdelivr/pull/6465

**Comment by wearhere** [comment]
:raised_hands:

**Comment by AdityaManohar** [comment]
I'm marking this as closed because this seems to have landed in jsdelivr. Feel free to reopen if you run into problems.

@bradvogel thanks for bringing this up!

**Comment by wearhere** [comment]
Works great, thanks!
