### ISSUE TITLE
RequestTimeout in s3.putObject

### ISSUE THREAD

**Issue by BjoernRuberg** [aws/aws-sdk-js#684]
I've found similar older bug reports which were closed after having been fixed. For me this bug is real right now running aws-sdk 2.1.38

When uploading files to s3 I randomly catch this error:

{ [RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.]
  message: 'Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.',
  code: 'RequestTimeout',
  time: Tue Aug 18 2015 08:28:44 GMT+0000 (UTC),
  statusCode: 400,
  retryable: true }

Sometimes reuploading helps. 
But some files are rejected in this way even 10 times while others work. Approximately 5% of my uploads to S3 are not possible because of this problem.

**Comment by AdityaManohar** [comment]
@BjoernRuberg  can you share the code that you are using?

**Comment by BjoernRuberg** [comment]
@AdityaManohar  sure.
This is the extracted code:

    var Q		= require("q");
    var AWS 	= require('aws-sdk');
    var fs		= require('fs');

    var awsS3Client = new AWS.S3();

    var upload = function(params) {

            var defer	= Q.defer();
            awsS3Client.putObject(params, function(err) {
                    if (err) {
                            defer.reject(err);
                    }
                    else {
                            defer.resolve();
                    }
            });
            return defer.promise;
    };


    var s3params	= {
        Body    : fs.createReadStream("localfile"),
        Bucket  : "bucket",
        Key	    : remotefile
    };

    var attempts = 0;

    var doUpload = function() {
        return upload(_.assign(s3params, options || {}))
            .then(function() {
                return Q.resolve();
            })
            .fail(function(err) {
                if (attempts < 10) {
                        console.log("Retrying upload of file " + remotefile + ". Turn " + attempts);
                        attempts++;
                        return doUpload();
                }
                else {
                        return Q.reject(err);
                }
            });
    };

    return doUpload();

I now got the reason why reuploads did not work. The stream I used was finished after first upload and would never have transferred any new data for the next attempts.

But I still see a problem with putObject that it can fail at the first attempt. I now use ManagedUpload which seems to not have the problem.

**Comment by AdityaManohar** [comment]
@BjoernRuberg For larger files I would recommend using `AWS.S3.ManagedUpload`. 

If you are using `AWS.S3.putObject()` with large files, you can also increase the socket timeout by setting the [`httpOptions`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#httpOptions-property).

For example:
```javascript
var s3 = new AWS.S3({
  httpOptions: {
    timeout: 240000
  }
});
```

I'm going to mark this as closed since you already seem to have it working with `AWS.S3.ManagedUpload`. Feel free to reopen this issue or open another issue if you have other questions.
