### ISSUE TITLE
[question] Is there a way to get an S3 public URL that will never expire?

### ISSUE THREAD

**Issue by wearhere** [aws/aws-sdk-js#685]
It seems like signed URLs will always have a default expiration: https://github.com/aws/aws-sdk-js/blob/fd5fb93f8ffa4ce96933fe0418a95218b526c637/lib/services/s3.js#L371.

Is there some other way to disable expiration?

If not, is there any effective upper limit on the expiration interval? i.e. could I set it to, say, 5 years?

**Comment by AdityaManohar** [comment]
@wearhere if you are using the default `'s3'` signature version, you can set the `params.Expires` to 200 years or any other value.

If you are using signature version 4 then the maximum expiry time on presigned URLs is one week.

Hope this helps clarify things!

**Comment by wearhere** [comment]
Ok thanks!

**Comment by dmyers** [comment]
Isn't the better solution to make the object public and link to it like normal? The PHP SDK has a `getObjectUrl` which essentially just build the URL for you without the signature requirement.

**Comment by wearhere** [comment]
Oh! That would be great. All the examples I had seen used `getSignedUrl`.

@AdityaManohar is it possible to get a public link like @dmyers suggests using the JS SDK? I don't see `getObjectUrl` [in the JS reference](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html).

**Comment by dmyers** [comment]
I managed to hack it by looking at the private APIs in the JS internals like this:

```js
var client = new AWS.S3();
var req = new AWS.Request(client, 'getObject', {Key: key, Bucket: bucket});
client.populateURI(req);
var fullUrl = req.httpRequest.endpoint.protocol + "//" + req.httpRequest.endpoint.host + '/' + path;
```

Though [the PHP one](https://github.com/aws/aws-sdk-php/blob/master/src/S3/S3Client.php#L154) mainly looks at the final URL built from the request package Guzzle, I couldn't figure out how to do it in Node myself and that was the best solution other than hardcoding any hostnames as I wanted to have the same logic as the PHP version I used in the past.

**Comment by wearhere** [comment]
Awesome thanks @dmyers!

**Comment by patoncrispy** [comment]
Hmm @dmyers that didn't work for me. That generated a URL with the format https://{bucket}.s3-{region}.amazonaws.com/{key}, whereas what is required is https://s3-{region}.amazonaws.com/{bucket}/{key}. Not sure why there is a difference...

**Comment by sandyleo26** [comment]
@AdityaManohar but according to [this](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html), the default signature is being V4 now. Does it mean longer-than-7-day expiration time is not possible? Thanks

**Comment by miensol** [comment]
Are there any plans to add this feature to aws-sdk-js? Something similar to what is available already in e.g. [aws-sdk-ruby](https://github.com/aws/aws-sdk-ruby/blob/9ea447b7e9e57e27bb7924aca40a5bf0c3265a94/gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb#L210) would suffice. Currently we need to resort to workarounds like handcrafting the urls or using [3rd party packages](https://www.npmjs.com/package/s3-public-url).

**Comment by andythedandyone** [comment]
Yep, following this. I need the same feature.

This thread has been rolling since 2015. So far we got hacks to make it work. I doubt it will get any implementation towards it. Which makes the function kinda useless in a sense if you can't really use it past short time expiration time.

**Comment by RichardSilveira** [comment]
Why only one week? This value should depends on busines rules of each application...
