### ISSUE TITLE
Can't upload a http.IncomingMessage stream from request

### ISSUE THREAD

**Issue by watson** [aws/aws-sdk-js#686]
If using native Node.js, this works:

``` js
var https = require('https')
var AWS = require('aws-sdk')

var s3 = new AWS.S3()
var url = 'https://a0.awsstatic.com/main/images/logos/aws_logo_105x39.png'

console.log('Requesting', url)
https.get(url, function (res) {
  var opts = {
    Bucket: 'name-of-bucket',
    Key: 'test.png',
    Body: res,
    ContentType: res.headers['content-type'],
    ContentLength: res.headers['content-length']
  }

  console.log('Starting upload to S3')
  s3.upload(opts, function (err) {
    if (err) throw err
    console.log('Upload completed')
  })
})
```

Using the [request](https://github.com/request/request) npm module, you should be able to do the same thing:

``` js
var request = require('request')
var AWS = require('aws-sdk')

var s3 = new AWS.S3()
var url = 'https://a0.awsstatic.com/main/images/logos/aws_logo_105x39.png'

console.log('Requesting', url)
request(url).on('response', function (res) {
  var opts = {
    Bucket: 'name-of-bucket',
    Key: 'test.png',
    Body: res,
    ContentType: res.headers['content-type'],
    ContentLength: res.headers['content-length']
  }

  console.log('Starting upload to S3')
  s3.upload(opts, function (err) {
    if (err) throw err
    console.log('Upload completed')
  })
})
```

But this will never complete the upload. Instead the S3 connection times out after waiting for a while.

**If I change the `s3.upload` to `s3.putObject` then everything works fine?!**

The `res` object provided to the `response` event is in both cases an instance of `http.IncomingMessage`, so everything should be the same - but apparently it isn't. Could it be that you are relying on some Node.js internals that is different when the `http.IncomingMessage` object doesn't come directly from the `http` / `https` module?

**Comment by AdityaManohar** [comment]
@watson I'm going to have to investigate this a little further. I will get onto this sometime soon and let you know what I find.

Thanks for reporting!

**Comment by chrisradek** [comment]
@watson 
I ran the code you provided on Node.js `v0.10.x` and `v0.12.x`. On Node.js `v0.10.x`, both the native `https` client as well as `request` seem to be working correctly.  However, on Node.js `v0.12.x` only the native `https` client works.

My initial suspicion is that there may be something else going on with `request` on Node.js `v0.12.x`. I'm not aware of the internal details of `request`, but it doesn't look like the SDK relies on any unsupported Node.js internals.

Let me know if this information helps!

**Comment by chrisradek** [comment]
Closing. Feel free to reopen if you want to discuss this further.

**Comment by devinus** [comment]
I'm also experiencing this issue.

**Comment by devinus** [comment]
@chrisradek Could this be reopened? The fact that `putObject` works but `upload` doesn't is indicating there's a discrepancy with the SDK itself. The response is a standard node `http. IncomingMessage`

**Comment by chrisradek** [comment]
@devinus 
I took a deeper look at what `request` is returning and what the SDK is doing in an `upload` vs `putObject` operation, and have some early thoughts on what may be happening.  I'll re-open and mark as a feature request for now, since this seems to be an issue with `request` and not `https`.

**Comment by watson** [comment]
I just did a little digging in the request module because I was puzzled that this doesn't work out of the box and that my original findings indicated that it should.

1. At [request.js#L946](https://github.com/request/request/blob/d18cb487cf4e02740778d4bb464b5a1c7441d800/request.js#L946) the `response` event is emitted with the `response` object
1. The emitted `response` object it self was just passed into the parent function `Request.prototype.onRequestResponse` at [request.js#L818](https://github.com/request/request/blob/d18cb487cf4e02740778d4bb464b5a1c7441d800/request.js#L818)
1. Which in turn was called because `self.req` emitted its own `response` event at [request.js#L782](https://github.com/request/request/blob/d18cb487cf4e02740778d4bb464b5a1c7441d800/request.js#L782)
1. `self.req` is initialised at [request.js#L741](https://github.com/request/request/blob/d18cb487cf4e02740778d4bb464b5a1c7441d800/request.js#L741) to the return value of the `self.httpModule.request` function
1. `self.httpModule` is a reference to the http module that matches the current protocol (either `http` or `https`) and is set at [request.js#L463](https://github.com/request/request/blob/d18cb487cf4e02740778d4bb464b5a1c7441d800/request.js#L463)

**So to sum up:**

The `self.httpModule.request` function actually just equals the core Node.js [`http.request`](https://nodejs.org/api/http.html#http_http_request_options_callback) or [`https.request`](https://nodejs.org/api/https.html#https_https_request_options_callback) function dependent on the protocol used.

In case of the http protocol (this issue affects both http and https), the emitted `response` event by `self.req` is just the [`response` event](https://nodejs.org/api/http.html#http_event_response) emitted by [http.ClientRequest](https://nodejs.org/api/http.html#http_class_http_clientrequest) so the object that is assigned to the `Body` property in the original example above should just be an instance of [http.IncomingMessage](https://nodejs.org/api/http.html#http_http_incomingmessage), which is what I also verified using `instanceof` when I originally opened this issue.

Conclusion? I'm still just as puzzled as to why the AWS-SDK shouldn't just treat this as any other `http.IncomingMessage` instance. One answer to this question could be that the request module changes part of the internal state of the `http.IncomingMessage` object that the AWS-SDK depends on. If that's the case, I think it would happen on one of thise lines: https://github.com/request/request/blob/d18cb487cf4e02740778d4bb464b5a1c7441d800/request.js#L819-L946

**Comment by jongyoonlee** [comment]
We are also running into this problem on node v5.0.0 and aws-sdk v2.2.21.

**Comment by devinus** [comment]
Can anybody from the AWS team or the @aws or @request team comment on this?

**Comment by ahageali** [comment]
+1

**Comment by edwardysun** [comment]
+1

**Comment by bryanjhatton** [comment]
+1

**Comment by kevindpsilitonga** [comment]
+1

**Comment by maxbrodie** [comment]
+1

**Comment by chrisradek** [comment]
We'll take another look to see what it would take to support request.

**Comment by chrisradek** [comment]
It looks like the issue is due to `request` binding a `data` event on the response. The `upload` method binds `readable` internally, and when it attempts to read the stream isn't able to read any data.

Request code:
https://github.com/request/request/blob/d9906af527e0e452bb3e4f680348f017cf27b451/request.js#L958

Binding `data` basically has the affect of changing our stream from 'paused mode' to 'flowing mode'. In flowing mode, the `readable` event doesn't get emitted except for the last one, end-of-stream.
https://nodejs.org/api/stream.html#stream_class_stream_readable

I still have to see what's possible on our end to mitigate this. We may be able to pause the stream, but I'll have to see if we end up losing some data going down this route. This does however explain why `upload` doesn't work when using `request`.

**Comment by devinus** [comment]
@chrisradek Thanks for taking a look at this.

**Comment by robertjustjones** [comment]
+1

**Comment by kanongil** [comment]
I encountered this with another readable. I made it work by doing a call to `upload.fillQueue()` after `upload.send()`.

**Comment by kanongil** [comment]
Also, this is not a **feature request**, but a rather critical bug.
