### ISSUE TITLE
MultipleValidationErrors: There were 2 validation errors

### ISSUE THREAD

**Issue by Durss** [aws/aws-sdk-js#687]
Hello,

I just tried to make the sample work with no success.
No matter what i do, i always get these errors :
```
Error uploading data:  { [MultipleValidationErrors: There were 2 validation erro
rs:
* InvalidParameterType: Expected params.inEnum to be a string
* InvalidParameterType: Expected params.getProp to be a string]
  message: 'There were 2 validation errors:\n* InvalidParameterType: Expected pa
rams.inEnum to be a string\n* InvalidParameterType: Expected params.getProp to b
e a string',
  code: 'MultipleValidationErrors',
  errors:
   [ { [InvalidParameterType: Expected params.inEnum to be a string]
       message: 'Expected params.inEnum to be a string',
       code: 'InvalidParameterType',
       time: Sun Aug 23 2015 17:07:33 GMT+0200 (Paris, Madrid (heure d'été)) },
     { [InvalidParameterType: Expected params.getProp to be a string]
       message: 'Expected params.getProp to be a string',
       code: 'InvalidParameterType',
       time: Sun Aug 23 2015 17:07:33 GMT+0200 (Paris, Madrid (heure d'été)) } ]
,
  time: Sun Aug 23 2015 17:07:33 GMT+0200 (Paris, Madrid (heure d'été)) }
```

I created the env vars **AWS_ACCESS_KEY_ID**, **AWS_SECRET_ACCESS_KEY** and **AWS_REGION** with the appropriate values, and simple tried this code sample :
```javascript
// Load the AWS SDK for Node.js
var AWS = require('aws-sdk');
AWS.config.region = 'us-west-2';//probably not necessary as i created env var

var s3bucket = new AWS.S3({params: {Bucket: 'XXX'}});
s3bucket.createBucket(function() {
  var params = {Key: 'xxx/xxx/xxx', Body: 'Hello!'};
  s3bucket.upload(params, function(err, data) {
    if (err) {
      console.log("Error uploading data: ", err);
    } else {
      console.log("Successfully uploaded data to myBucket/myKey");
    }
  });
});
```

Do you have any hint of what i could have done wrong.?

Have a good day :)

**Comment by AdityaManohar** [comment]
@Durss It looks like you might be using a JavaScript library that is adding properties `Object.prototype` - in this case `inEnum` and `getProp`.

You can verify this by doing:
```javascript
for (var key in params) { console.log(key); }
```
You should see only `Bucket`, `Key`, and `Body`. If you see anything else then this is caused by an external JavaScript library.

This is similar to #575. Let me know what you find!

**Comment by Durss** [comment]
Oh nice !
Indeed i use node-persist" module that adds properties isEnum and getProp to the Object's prototype.

Now it's up to me to decide how i deal with it !
Thanks for your helpful answer !

**Comment by AdityaManohar** [comment]
@Durss  no problem! 

I'm going to mark this as closed since it isn't a problem with the SDK. Feel free to reopen this issue or another issue if you have any questions.

**Comment by AmareshB** [comment]
In my case, I have used putItem of docClient instance to insert an item in the dynamoDb. All I had to do was to create an instance of DynamoDoc and call putItem method of that instance.

`const doc = require('dynamodb-doc');
 const dynamo = new doc.DynamoDB();`

And call the putItem method on dynamo object.

**Comment by supportcoinsafer** [comment]
Same here.

When I call internal direct in my code there is no problem.

But if I call by  http://localhost:3001/myfunction post request, there is the same error.
