### ISSUE TITLE
EBS App creates some SQS Messages then throws 'Connection timed out' errors

### ISSUE THREAD

**Issue by imranansari** [aws/aws-sdk-js#688]
Hello,

I'm trying to insert around 50k messages into SQS from EBS,  I get the below error.
It does insert around 10k messages though, so is it a EBS Network issue or SQS or Node SDK?

I'm using SDK Version '2.1.34'

/var/log/nodejs/nodejs.log
-------------------------------------
```
{ [TimeoutError: Connection timed out after 120000ms]
  message: 'Connection timed out after 120000ms',
  code: 'NetworkingError',
  time: Sun Aug 23 2015 05:33:02 GMT+0000 (UTC),
  region: 'us-west-1',
  hostname: 'sqs.us-west-1.amazonaws.com',
  retryable: true } 'TimeoutError: Connection timed out after 120000ms\n    at ClientRequest.
<anonymous> (/var/app/current/node_modules/aws-sdk/lib/http/node.js:56:34)\n    at ClientRequest.g (events.js:199:16)\n    at ClientRequest.emit (events.js:104:17)\n    at TLSSocket.emitTimeout 
(_http_client.js:543:10)\n    at TLSSocket.g (events.js:199:16)\n    at TLSSocket.emit (events.js:104:17)\n    at TLSSocket.Socket._onTimeout (net.js:348:8)\n    at _makeTimerTimeout (timers.js:476:11)\n    at 
Timer.unrefTimeout (timers.js:540:5)'
{ [TimeoutError: Connection timed out after 120000ms]
  message: 'Connection timed out after 120000ms',
  code: 'NetworkingError',
  time: Sun Aug 23 2015 05:33:02 GMT+0000 (UTC),
  region: 'us-west-1',
  hostname: 'sqs.us-west-1.amazonaws.com',
  retryable: true } 'TimeoutError: Connection timed out after 120000ms\n    at ClientRequest.
<anonymous> (/var/app/current/node_modules/aws-sdk/lib/http/node.js:56:34)\n    at ClientRequest.g 
(events.js:199:16)\n    at ClientRequest.emit (events.js:104:17)\n    at TLSSocket.emitTimeout 
(_http_client.js:543:10)\n    at TLSSocket.g (events.js:199:16)\n    at TLSSocket.emit (events.js:104:17)\n    at TLSSocket.Socket._onTimeout (net.js:348:8)\n    at _makeTimerTimeout (timers.js:476:11)\n    at 
Timer.unrefTimeout (timers.js:540:5)'
```

What am I missing?
thanks

**Comment by AdityaManohar** [comment]
@imranansari the SDK delegates directly to Node.js HTTP `request.setTimeout()`. If you are sending a large number of messages then I would recommend that you increase the default configured [`httpOptions.timeout`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#httpOptions-property) value to something greater than 120000 seconds. 

For example: 
```javascript
var sqs = new AWS.SQS({httpOptions: { timeout: 240000}});
```
Let me know if this helps!

**Comment by imranansari** [comment]
didn't make a difference, still brings down the micro instance.
btw, I'm running this as a cron job on an EBS worker, so my steps are :
- Get records from Salesforce (50k)
- Insert into SQS Queue

I thought scaling issues would be the last of my concerns :)

**Comment by imranansari** [comment]
the funny thing is, I get network timeout errors on my mac, but it still succeeds eventually, but not so on EBS

**Comment by AdityaManohar** [comment]
@imranansari which version of Node.js are you running? On Node.js v0.10+ it might be worth to increase the number of `agent.maxSockets` since the default is set to 5. Here is code snippet to increase the global max sockets:

```javascript
require('http').globalAgent.maxSockets = require('https').globalAgent.maxSockets = 10
```

Let me know if this helps!

**Comment by AdityaManohar** [comment]
@imranansari I'm marking this as closed because there doesn't seem to be any recent activity. Feel free to reopen this issue or open another issue if you continue to have problems.
