### ISSUE TITLE
Add support for Elastic Container Service

### ISSUE THREAD

**Issue by jonhester** [aws/aws-sdk-js#690]
This would be fantastic so that I no longer have to use my own wrapper for interacting with ECS.

**Comment by AdityaManohar** [comment]
@jonhester Do you mean support for Amazon EC2 Container Service? The SDK already has support for Amazon EC2 Container Service under the `AWS.ECS` namespace. See the [API documentation for AWS.ECS](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECS.html).

**Comment by jonhester** [comment]
Yep. Not sure how I missed it. Thanks!
