### ISSUE TITLE
Request could not be completed

### ISSUE THREAD

**Issue by franklynsd** [aws/aws-sdk-js#699]
Hi, I am having a problem. I am calling createPlatformApplication from a hybrid mobile app (cordova) in IOS. I am setting PlatformPrincipal with the ssl certificate from the .p12 file generated from the IOS push certificate. I am getting: request could not be completed.

Any help?

**Comment by franklynsd** [comment]
I get notifications on Android, but not in IOS.
I get notifications on IOS if I send it using AWS console, creating an endpoint using the device token.

**Comment by AdityaManohar** [comment]
@franklynsd Can you share the code you are using?

**Comment by franklynsd** [comment]
Yes,

platconfig={PlatformCredential: '[platform credential]'};

platconfig.PlatformPrincipal='-----BEGIN CERTIFICATE-----\nMIIFejCCBGKgAwIBAgIIULSnaYstx..............PhtCx\nKakQGdwpfj1T3oq+o/M=\n-----END CERTIFICATE-----';
       
AWS.config.update({accessKeyId: '[accessKeyId]', secretAccessKey: '[secretAccessKey]'});
AWS.config.region = 'us-west-2';

sns = new AWS.SNS({apiVersion: '2010-03-31', sslEnabled: true});

var params = {
    Attributes: platconfig ,
    Name: '[AppName]', 
    Platform: 'APNS_SANDBOX' 
};
sns.createPlatformApplication(params, function(err, data) {
    if (err){
        alert(err);
        alert(err.stack);
    }
    else
    {
        alert('Success:'+data.PlatformApplicationArn);
    }
 });

**Comment by franklynsd** [comment]
I addes \n for every new line in the certificate as it says in the documentation.

**Comment by franklynsd** [comment]
In the real code all keys and private information are fine.

**Comment by chrisradek** [comment]
@franklynsd 
Sorry for the delayed response. Are you still encountering issues? Is there anything else in the error that's thrown besides 'request could not be completed'?

**Comment by franklynsd** [comment]
Hi, I had an error in the PlatformCredential parameter. Thanks. It's ok now
