### ISSUE TITLE
Malformed XML with putBucketCors

### ISSUE THREAD

**Issue by robksawyer** [aws/aws-sdk-js#701]
I keep getting the following error when trying to apply the following origins to my bucket. The only schema that I'm aware of is the one listed at <http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketCors-property>. Am I missing something?

My data:
```
var params = {
	Bucket: 'my-bucket-name',
	CORSConfiguration: {
		CORSRules: [{
				AllowedOrigins: [ 'test.com', 'testing2.com' ],
				MaxAgeSeconds: 0
			}]
	}
};
```

Error: 
```
error: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
```

**Comment by robksawyer** [comment]
Hmm... It appears that some properties are required even though the docs do not specify. 

Looks like it worked ok by adding the following:
```
var params = {
				Bucket: 'my-bucket-name',
				CORSConfiguration: {
					CORSRules: [
						{
							AllowedHeaders: ['*'],
							AllowedOrigins: origins,
							AllowedMethods: ['GET'],
							ExposeHeaders: ['ETag']
							//MaxAgeSeconds: 0
						}
					]
				}
			};
```

**Comment by AdityaManohar** [comment]
@robksawyer Thanks for reporting this. It should be fairly easy to correct the documentation and correctly validate the required properties. I'll take a look at doing this soon.

**Comment by chrisradek** [comment]
@robksawyer I've pushed up a patch that corrects the documentation and validates the required parameters.
Let me if this works for you and thanks for reporting!
