### ISSUE TITLE
Memory leak after upload

### ISSUE THREAD

**Issue by johneke** [aws/aws-sdk-js#702]
After uploading a large file to S3, I notice memory spikes that don't go away. The code snippet below uploads a file to S3 every 5s and logs memory usage.

Steps to reproduce:

1. `npm install aws-sdk@2.1.50`
2. Create (or copy over) a large file (at least 20MB to 30MB) to the current directory and name it `file.file`
3. Source your `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in your terminal
3. Create `s3-upload-leak.js` with the contents below
4. Update `my-s3-bucket` to point to your own S3 bucket
5. Run `node s3-upload-leak.js`

```javascript
var aws = require('aws-sdk');
var fs = require('fs');

var s3 = new aws.S3();
var startRSS, endRSS;

function toMB(bytes){
	return (bytes/1024/1024) + 'mb';
}

function doUpload(callback){
	// perform upload
	console.log('Starting upload for file of size: ' + toMB(fs.statSync('./file.file')['size']));

	startRSS = process.memoryUsage().rss;

	s3
	.upload({
		Bucket: 'vindie-videos-originals',
		Key: 'file.file',
		Body: fs.createReadStream('./file.file')
	}, function (error, data){
		console.log('Done upload');

		endRSS = process.memoryUsage().rss;

		console.log('memory usage delta: ' + toMB(endRSS - startRSS) + ', total: ' + toMB(endRSS));
		callback();
	});
}

function doneCallback(){
	setTimeout(function(){doUpload(doneCallback)}, 5000);
}

doUpload(doneCallback);

```

Found with node `v0.12.7` on OSX (OS details below)

<img width="300" alt="osx" src="https://cloud.githubusercontent.com/assets/1062797/9722540/0fa5f0aa-557d-11e5-863c-ddb1dd5e2a49.png">

Here is my print out from running the code snippet on my Mac. The deltas show that per upload, there is a memory spike. The increasing total memory shows that the memory isn't going away

```
memory usage delta: 61.0703125mb, total: 84.859375mb
...
memory usage delta: 52.19921875mb, total: 137.07421875mb
...
memory usage delta: 27.75390625mb, total: 164.83203125mb
```

Is there something I am doing wrong? Some resource I'm not freeing? I would really appreciate any help on this.

**Comment by johneke** [comment]
I re-ran the same code snippet, performing a GC before each upload and here is the output:

```
memory usage delta: 65.59375mb, total: 89.9140625mb
...
memory usage delta: 8.61328125mb, total: 98.55078125mb
...
memory usage delta: 7.859375mb, total: 106.41015625mb
...
memory usage delta: 2.88671875mb, total: 109.30078125mb
...
memory usage delta: 3.74609375mb, total: 113.05859375mb
```

Leaks are smaller but still there.

**Comment by AdityaManohar** [comment]
@johneke have you tried limiting the number of open sockets. Node.js v0.12+ sets `agent.maxSockets` to `infinity`. You can limit the number of sockets like this:

```javascript
require('http').globalAgent.maxSockets = require('https').globalAgent.maxSockets = 10
```
You might also want to wait a while for GC to kick in. This sounds like it is related to #610.

Let me know if this helps!

**Comment by johneke** [comment]
Seems more sane. Thanks @AdityaManohar!

```
...
memory usage delta: 85.6640625mb, total: 112.05078125mb
...
memory usage delta: 4.56640625mb, total: 116.65625mb
...
memory usage delta: 1.6015625mb, total: 118.296875mb
...
memory usage delta: -4.40234375mb, total: 113.91015625mb
...
memory usage delta: 0.04296875mb, total: 113.96484375mb
```
