### ISSUE TITLE
How to configure maxRetries and retryDelays for SQS, S3, SES. What are there default values?

### ISSUE THREAD

**Issue by anuradhag** [aws/aws-sdk-js#703]
We received Inaccessible host issue for SQS and S3 and as per recommendation in #528 we upgraded to latest sdk. 
We are unable to find out the default values of maxRetries and the delay between retries. Just to be sure we wanted to know these numbers. Can anyone provide the information.

**Comment by AdityaManohar** [comment]
The default retry count for all service clients is 3. You can increase the default retry count by setting the `maxRetries` option when constructing a service client.

For example:
```javascript
var s3 = new AWS.S3({maxRetries: 10});
```
The delay between retries is a calculated number and increases exponentially with the number of retries per this formula 
delay<sub>n</sub> delay = 2<sup>n</sup> * 30 milliseconds

For example:
* delay<sub>0</sub> delay = 2<sup>0</sup> * 30 = 30 ms
* delay<sub>1</sub> delay = 2<sup>1</sup> * 30 = 60 ms
* delay<sub>2</sub> delay = 2<sup>2</sup> * 30 = 120 ms

Hope this helps clarify things.

**Comment by anuradhag** [comment]
Thank you @AdityaManohar for your detailed reply.
