### ISSUE TITLE
error on s3.copyObject with curly apostrophe

### ISSUE THREAD

**Issue by Aoreias** [aws/aws-sdk-js#712]
aws-sdk=2.2.0
node.js = v0.10.36 - presumably, invoked in AWS Lambda.

A SignatureDoesNotMatch error is thrown when calling s3.copyObject with a key and CopySource which contain a curly apostrophe.

Sanitized object for params:

copyObject params: { 
  Bucket: 'bucketname-test', 
  Key: 'test’-orig.jpg', 
  CopySource: 'bucketname-test/test’.jpg', 
  Metadata: { xxxx: 'xxxxxx' } }

Unable to upload to xxxx-test/test’.jpg due to an error: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by AdityaManohar** [comment]
@Aoreias Thanks for reporting this. I'm working on a fix and this should land in master soon.

**Comment by AdityaManohar** [comment]
@Aoreias I've pushed up a patch that should fix this issue. Let me know if this works for you. This change will be available in the next release. In the meantime you can install from npm install from GitHub:

```sh
$> npm install git://github.com/aws/aws-sdk-js
```

**Comment by AdityaManohar** [comment]
@Aoreias It looks like this fix introduces a breaking change to the way the `CopySource` parameter is supplied.

You will have to manually URL encode any keys that have URL unsafe characters as specified in the [`AWS.S3.copyObject()`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property) API documentation.

**Comment by Aoreias** [comment]
That makes a lot of sense, but thank you!
