### ISSUE TITLE
S3: Metadata needs parsing

### ISSUE THREAD

**Issue by CSharpFan** [aws/aws-sdk-js#716]
So consider the following piece of code:

```javascript
var AWS = require("aws-sdk");

var s3 = new AWS.S3({
    region: "eu-west-1",
    signatureVersion: "v4"
});

// now for a given bucket put an object:
s3.putObject({
    Bucket: "metadata-test",
    Key: "MyFile.txt",
    Body: "Test1234",
    Metadata: {
        "foo": "bar",
        "FOO": "bar"
    }
}, function (err, data) {
    if (err) {
        console.log(err);
    }
    else {
        console.log(data);
    }
});

```
I know that because the Metadata are just plain http headers, meaning they're case insensitive.

The problem is 2part. 

One: this code throws the weirdest error: 

```
{ [SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.]
  message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  code: 'SignatureDoesNotMatch',
  time: Tue Sep 15 2015 11:49:05 GMT+0200 (Romance Daylight Time),
  statusCode: 403,
  retryable: false,
  retryDelay: 30 }
```
Which seems to be related to the fact that the headers are merged, and thus the checksum differs. Maybe some upfront checks? Like a key validation? 

The second part is actually more annoying. 

Imagine you posting the data with the following headers:
```javascript
var key = "FOO";
var value = "bar";

var metadata = { };
metadata[key] = value;

myPutObjectRequest.Metadata = metadata;
```

Now further on in the code, maybe at a later date, we try to retrieve that object from s3. 

If we have the object, and we try to get the metadata:

```javascript
var result = myGetObjectResponse.Metadata[key] // "FOO"
``` 
yields `undefined`. 

Can we solve this by exposing Metadata as an object with some methods to get & set the properties, instead of a hashmap? This would allow us to add logic to it, and thus do a `toLowerCase()`, or an error when one tries to add/fetch properties with uppercase characters.

**Comment by AdityaManohar** [comment]
@CSharpFan Are you running the code in a browser? The second problem you mentioned can be very easily solved by whitelisting the headers in Amazon S3 bucket's CORS configuration.

For example if you are using `Foo` or `foo` as a key in your object metadata, the you would have to expose the `x-amz-meta-foo` header in your S3 CORS configuration like this.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <ExposeHeader>x-amz-meta-foo</ExposeHeader>
    </CORSRule>
</CORSConfiguration>
```

This should allow you to access object metadata with GET/HEAD requests from the browser. 

As far as validating the case of metadata keys, the SDK does not validate any user content values because this it is difficult to do reliably across the board and does not scale well across services and operations.

**Comment by CSharpFan** [comment]
Hi Aditya,

Notice that for the second example the issue is that my `key` is `FOO`, however the metadata returned looks like `{ "foo": "bar" }` instead of { "FOO": "bar" }`.

**Comment by AdityaManohar** [comment]
@CSharpFan 

Object metadata are transported as headers prefixed with `x-amz-meta-`. This means that metadata keys are lowercased for transport as a header. This is the way that [Amazon S3 API for object metadata](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata) works. 

As per the RFC 7230 [header field specification](https://tools.ietf.org/html/rfc7230#section-3.2), all header field names are case-insensitive. For this reason, I don't believe it is possible to have case-sensitive object metadata keys. The value may be case-sensitive though.

Hope this helps clarify things.

**Comment by CSharpFan** [comment]
Okay, thank you for the clarification.
