### ISSUE TITLE
Support index field statistics

### ISSUE THREAD

**Issue by oscar-espada** [aws/aws-sdk-js#717]
Since 2015-03-05, we can retrieve statistics against index numeric field.
http://aws.amazon.com/releasenotes/Amazon-CloudSearch/5060064203846541

But the sdk doesn't support to get stats for a numeric field.

**Comment by AdityaManohar** [comment]
@oscar-espada Thanks for reporting. It looks like this change didn't make it into the SDK. I've notified the Amazon CloudSearch team about it. I will keep this issue updated as we get more information. In the meantime, I would recommend opening an issue on the [Amazon CloudSearch Forum](https://forums.aws.amazon.com/forum.jspa?forumID=137) to let them know about the issue.

**Comment by LiuJoyceC** [comment]
Support for statistics was added to the SDK on 3/1/2016. Please note that this is a change to the API of AWS.CloudSearchDomain, not AWS.CloudSearch.
http://aws.amazon.com/releasenotes/6103040037792580
