### ISSUE TITLE
Uploading to s3 with ArrayBuffer data and Signature Version 4

### ISSUE THREAD

**Issue by kentor** [aws/aws-sdk-js#719]
I'm trying to upload parts to s3 via the browser (Chrome). If I give `s3.uploadPart()` an ArrayBuffer (they come from Web Workers) as the `Body`, it will eventually try to call `reader.readAsArrayBuffer(sliceFn.call(data, index, back));` and fail because `readAsArrayBuffer` only works on Blobs.

Now I could convert the ArrayBuffer to a Blob with `new Blob([arrayBuffer])` but this makes a copy of the data which is very expensive. These are 5mb chunks and they cause the UI to freeze and jank.

Is there a better way of handling this without making copies of the ArrayBuffer data?

**Comment by kentor** [comment]
Another question.. we still have to compute the SHA256 of the 5mb chunks in the UI thread which is where we call `s3.uploadParts()`. This will cause jank no matter what will it not?

**Comment by AdityaManohar** [comment]
@kentor 
> Is there a better way of handling this without making copies of the ArrayBuffer data?

I would recommend checking out the `AWS.S3.ManagedUpload` abstraction. It performs parallel multipart uploads using Amazon S3's  `UploadPart` API operation.

> we have to compute the SHA256 of the 5mb chunks in the UI thread which is where we call s3.uploadParts(). This will cause jank no matter what will it not?

Unfortunately, yes. Calculating the SHA256 checksums on a 5MB chunk is computationally intensive. You can try using a Web Worker to compute the SHA256 checksum. This is a little involved because you will have to detach the existing handlers and instead write your own request handler to compute the SHA256 checksum using private APIs which is not recommended. An alternative would be to use the default `s3` signature version.

Hope this helps!

**Comment by kentor** [comment]
Thanks for the answers. I may have to resort to using web workers to calculate the checksums. I don't think I can use the `s3` signature version for the eu-central-1 region right?

**Comment by jeskew** [comment]
Right; the eu-central-1 region requires all signatures to be v4.

**Comment by kentor** [comment]
I was hoping to run the sdk and use a Managed Upload in a web worker to avoid the checksum computation in the main thread. But Managed Uploads do not work in a Worker when `parts` are involved because it tries to use `DOMParser` which is not available in a worker.

**Comment by kentor** [comment]
Anyway to use WebCrypto to calculate the SHA256?

**Comment by kentor** [comment]
In the meantime, why does the sdk have to call readAsArrayBuffer when passed in an ArrayBuffer? Shouldn't it just use the value as is?

**Comment by kentor** [comment]
Closing this since I've found a workaround which is patching AWS.util.computeSha256 to use webcrypto.

**Comment by Hemanshu1belani** [comment]
@kentor For DOMParser you mentioned 
"Edit: I polyfilled the worker with a DOMParser and that seems to work"
Can you please share the code example? or how you made it happen? Even I'm stuck because of DOMParsed in webworker
