### ISSUE TITLE
How to know in code that a an upload is currently failed / canceled

### ISSUE THREAD

**Issue by lonormaly** [aws/aws-sdk-js#720]
Hey there,

Is there a way to know that an upload request is currently failed / canceled?

Let me picture the scenario - I'm uploading using multipart upload and while uploading i'm closing the laptop. Automatically the part uploads change their status to (canceled).
Is there a way to know from the request that something went wrong? obviously the failure event is not being called due to the fact that the laptop was closed.

Thanks

**Comment by chrisradek** [comment]
Hey @lonormaly 
The upload object has a failed field that should return true if the upload failed.  I tested this on my own machine by starting a multipart upload and disconnecting my internet connection.  After a period of retries passed, I could inspect the failed field on my upload object to see that it had failed to upload.

If the computer goes to sleep during the upload, that may stop the upload object from updating its failed status.  
Let me know if this information helps!
-Chris

**Comment by lonormaly** [comment]
Thanks! Regarding the latter comment, in that case (when you close your
laptop for example), how can I detect that the upload was interrupted and
it's not active anymore, after I open the laptop again?

Because it is shows on the network tab clearly that the upload is canceled
but can't find a way to check if its current status is active or not using
JavaScript. Obviously the upload request didn't update its Failed field.

So unfortunately your answer doesn't add new information...

Thanks

On Tuesday, 22 September 2015, chrisradek <notifications@github.com> wrote:

> Hey @lonormaly <https://github.com/lonormaly>
> The upload object has a failed field that should return true if the upload
> failed. I tested this on my own machine by starting a multipart upload and
> disconnecting my internet connection. After a period of retries passed, I
> could inspect the failed field on my upload object to see that it had
> failed to upload.
>
> If the computer goes to sleep during the upload, that may stop the upload
> object from updating its failed status.
>
> Let me know if this information helps!
> -Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-js/issues/720#issuecomment-142146249>.
>


-- 
Thanks
       Shai

**Comment by chrisradek** [comment]
@lonormaly 
The SDK currently doesn't have a way of determining if an upload was canceled under the use case you provided. 

However, with pull request #736, multipart uploads can now be resumed if `leavePartsOnError` is set to `true` on a `ManagedUpload` instance. If an `error` is returned in the callback to the `send()` method, calling `send()` again should resume where the previous attempt left off.

Let me know if this information helps and thank you for your patience!

**Comment by chrisradek** [comment]
@lonormaly 
I'm marking this as closed because there's not much we can do from the SDK side to support recovering from a process shutdown.  Feel free to reopen this issue or open another issue if you have other questions.

**Comment by lonormaly** [comment]
@chrisradek Thanks for your rapid response, sorry that mine wasn't as quick :)
The thing is that more often than not when resuming a failed upload the parts keep failing over and over again no matter how many times I send() the request again.
So we need to know exactly the state of the upload in order to determine wether it's active and correct or something went wrong with it, regardless of the firing of the error event, because it's not that rare that the event wasn't fired.

Hope that I'm clear enough.
Thanks
