### ISSUE TITLE
ETag without "

### ISSUE THREAD

**Issue by calidion** [aws/aws-sdk-js#721]
current:
```js
{ 
  ETag: '"239041f069d38009f3a161c347cafc15"',
  Location: 'https://s3-ap-northeast-1.amazonaws.com/aa.jpg'
}
```
should be:
```js
{ 
  ETag: '239041f069d38009f3a161c347cafc15',
  Location: 'https://s3-ap-northeast-1.amazonaws.com/aa.jpg'
}
```

**Comment by AdityaManohar** [comment]
@calidion This is the way that Amazon S3 returns the `etag` header. Can you explain a bit more about why you are trying to manipulate this value instead of passing it around as is?

**Comment by calidion** [comment]
Thanks for the reply.
But the "\"" is really not in good smell.
