### ISSUE TITLE
SNS: Fetching the Token for confirmSubscription()

### ISSUE THREAD

**Issue by pree011235** [aws/aws-sdk-js#724]
Trying to do a seemingly simple confirm subscription but I keep hitting the Invalid Token 400 issue:
```
endPointTest()
  .then((result) => {
    console.log("Result", result);

    AWS.config.update({
      accessKeyId:'accessKeyIdvalue',
      secretAccessKey:'secretAccessKeyvalue',
      region: 'us-west-2'
    });
    var sns = new AWS.SNS();
    console.log("SNS OBj", sns); 
    var params2 = {
      Protocol: 'http', /* required */
      TopicArn: 'topic_ARN_from_console', /* required */
      Endpoint: 'http://website.com/'
    };
    sns.subscribe(params2, function(err, data) {
      if (err) console.log(err, err.code); // an error occurred, where it breaks
      else     {
        console.log("Subscribing...", data.ResponseMetadata.RequestId);//Prints this
        console.log("Subscribing... with data", data); //Prints this fine
        var params1 = {
          Token: data.ResponseMetadata.RequestId, /* Where can I get this from?? */
          TopicArn: 'topic_ARN_from_console' /* required */
          //AuthenticateOnUnsubscribe: 'false'
        };
        sns.confirmSubscription(params1, function(err, data) {
          if (err) console.log(err, err.stack); // an error occurred
          else    {
            console.log("Confirmed Sub", data);
          }          // successful response
        });
      }
    });
  }).catch(console.error.bind(console));
```
Where can I get the endpoint Token from, right after the subscribe (Tried to look up my ```this``` but that didn't have it either? Thanks!

**Comment by jeskew** [comment]
Hi @pree011235,

The token will be provided in a message sent to the endpoint you're subscribing to an SNS channel. The endpoint will receive a POST message with a JSON payload containing, [among other fields](http://docs.aws.amazon.com/sns/latest/dg/json-formats.html#http-subscription-confirmation-json), a `Token` parameter and a `SubscribeURL` parameter. To confirm a subscription, you can perform a GET request on the value provided for `SubscribeURL` or use the provided `Token` to call `sns.confirmSubscription`.

**Comment by AdityaManohar** [comment]
@pree011235 I'm marking this as closed as it is not an SDK issue. As @jeskew mentioned, the `token` parameter is supplied in a confirmation message supplied to the `endpoint` that has been subscribed to receive SNS notifications.

Feel free to reopen this issue or open another issue if you have other questions.

**Comment by aadamsx** [comment]
I'm trying to do this same thing, using the sms protocol.  I too was placing the confirmSubscription in the subscribe callback.  @pree011235 in my case, when I call the subscribe, my test phone gets the SMS message and I have to reply YES <topic name> in order to confirm the subscribe.  From a coding standpoint, How do I confirm that phone subscribed?

**Comment by jeskew** [comment]
@aadamsx You can call [`listSubscriptions`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html#listSubscriptions-property) and check to see if your test phone has been successfully subscribed.

**Comment by aadamsx** [comment]
Thank you.  

I'm going to use listSubscriptionsByTopic.  But it only returns 100 subscriptions, requiring a NextToken in order to get more.

Do you have any sudo-code that would help?

This is what I came up with:
```     
      AWS.config.update({
         accessKeyId: Meteor.settings.awsAccessKeyId,
         secretAccessKey: Meteor.settings.awsSecretKey,
         region: "us-east-1"
      });

      var sns = new AWS.SNS({params: {TopicArn: 'arn:aws:sns:us-east-1:34523452345:test'}});
      var nextToken = null;
      var index = 0;
      var results[];
      do {
        result = sns.ListSubscriptionsByTopic({NextToken: nextToken}, function (err, data) {
          if (err) console.log(err, err.stack); // an error occurred
          else {
            // call ListSubscriptionsByTopic again?  How?
            results[index] = data.Subscriptions;
            index = index + 1;
          }
        });  
      }
      while (nextToken !== null);

    // do something with the results
```

**Comment by jeskew** [comment]
Hi @aadamsx,

The callback passed to `sns.ListSubscriptionsByTopic` will be called by the operation's response, which has a `hasNextPage` method and a `nextPage` method. The latter takes a callback and handles pagination for you. You won't need to keep track of the `nextToken`.
```js
var sns = new AWS.SNS({region: 'us-west-2'})
var paginate = function (err, data) {
        if (err) {
            console.log(err);
        } else {
            // current page of data is available as 'data'
            if (this.hasNextPage()) {
                this.nextPage(paginate);
            }
        }
    };

sns.listSubscriptions(paginate);
```

**Comment by aadamsx** [comment]
Thank you, this is exactly the feedback I was looking for!

**Comment by desaiazaz** [comment]
var nextToken = null;
            var index = 0;
            var results=[];
            do {
                results = sns.ListSubscriptionsByTopic({NextToken: nextToken}, function (err, data) {
                    if (err) console.log(err, err.stack); // an error occurred
                    else {
                        // call ListSubscriptionsByTopic again?  How?
                        results[index] = data.Subscriptions;
                        if (NextToken) {
                            nextToken = NextToken;
                            index = index + 1;
                        } else {
                            nextToken = null;
                        }
                    }
                });
            }
            while (nextToken !== null);
            console.log("LIST>>>",results);
 
got the error ListSubscriptionsByTopic function not found
