### ISSUE TITLE
s3.copyObject() tries to URL encode 'versionId' parameter

### ISSUE THREAD

**Issue by jmswhll** [aws/aws-sdk-js#727]
The SDK suggests that when copying a specific object version, the versionId should be appended to the CopySource parameter, for example: '?versionId=123456789'.

However doing this causes a 'NoSuchKey' exception.

It would appear that the SDK is trying to URL encode the extra parameter causing the operation to fail. I suggest a fix below: (line 221, aws-sdk/lib/services/s3.js)

```javascript
encodeCopySourceHeaders: function encodeCopySourceHeaders(req) {
    if (req.operation === 'copyObject' || req.operation === 'uploadPartCopy') {
      if (req.httpRequest.headers['x-amz-copy-source']) {
        /* Fix for copying with versionId */
        var paramSplit = req.httpRequest.headers['x-amz-copy-source'].split('?');
        req.httpRequest.headers['x-amz-copy-source'] =
          AWS.util.uriEscapePath(paramSplit[0]) + '?' + paramSplit[1];
        /* End fix */
      }
    }
  }
```

**Comment by jmswhll** [comment]
@AdityaManohar I believe this may be related to this commit:

https://github.com/aws/aws-sdk-js/commit/af181f8636030e798fe7144aa376b4a7b4f3f4a1

**Comment by AdityaManohar** [comment]
@jmswhll Thanks for reporting this! I've pushed up a fix that reverts this change. This should land in our next release.
