### ISSUE TITLE
Intermittent error with CognitoIdentityCredentials.getId()

### ISSUE THREAD

**Issue by benrady** [aws/aws-sdk-js#732]
I'm trying to use a Google token to create an authenticated identity using the JavaScript AWS library. When calling CognitoIdentityCredentials.getId(), I sometimes get a "Cannot read property 'getId' of undefined" error from within the AWS library. The error occurs in a function named n.CognitoIdentityCredentials.n.util.inherit.getId, that is called from the AWS.config.credentials.getId() call in the code below. It _might_ be related to the credentials timing out, but reproducing it is not as simple as waiting an hour. I haven't really found a pattern yet.

Any ideas what might be going on?

```javascript
function googleSignIn(googleUser) {
  window.user = googleUser;
  var id_token = googleUser.getAuthResponse().id_token;
  AWS.config.region = 'us-east-1';
  AWS.config.credentials = new AWS.CognitoIdentityCredentials({ 
    IdentityPoolId: "MY_POOL_ID",
    Logins: {
      'accounts.google.com': id_token
    }
  });
  AWS.config.credentials.getId(function(err, id) { // throws error, sometimes
    // processing id here...
  }
}  
```

**Comment by AdityaManohar** [comment]
@benrady Do you have a stack trace that you can provide? This will help debug the issue. Also which version of the SDK are you using?

FWIW, it is not recommended to explicitly call `AWS.CognitoIdentityCredentials.getId()`. This is a private API and you shouldn't need to explicitly call `getId()`. Can you also describe why your use case requires invoking the `getId()` method?

**Comment by benrady** [comment]
I don't know how helpful it will be, but here's a stack trace:

<img width="526" alt="autherror" src="https://cloud.githubusercontent.com/assets/56928/10062495/b767c3ba-6228-11e5-8f09-1b4cbbd5bf6d.png">

If there's an alternative to calling getId, I'm more than happy to use that. Should I just be calling get() instead? I'm trying to get a Cognito ID to attach to a document to be written to DynamoDB, similar to [this](https://mobile.awsblog.com/post/Tx2323YHCM0I7OO/Understanding-Amazon-Cognito-Authentication-Part-4-Enhanced-Flow). I'm using the Cognito ID with a policy variable to ensure the data is only writable by an authenticated user.

**Comment by AdityaManohar** [comment]
@benrady 

I haven't been able to reproduce the issue with a test setup I have. Is is possible that you have some sort of race condition going on in your code? Do you have multiple blocks of code that construct the credential provider?

The Cognito `IdentityId` is cached in local storage and is available at the [`AWS.CognitoIdentityCredentials.identityId`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html#identityId-property) property after the credentials have been refreshed.

For example:
```javascript
AWS.config.update({
  region: 'us-east-1',
  credentials: new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'foo-bar',
    Logins: {
      'accounts.google.com': id_token
    }
  })
})

AWS.config.credentials.refresh(function() {
  // IdentityId available now
  console.log(AWS.config.credentials.identityId);
  // Write to DynamoDB now
});
```

Hope this helps clarify this.

**Comment by benrady** [comment]
I'm not sure there's a race condition. There's only one block of code that does this. 

Will the credentials refresh automatically when I make a DynamoDB call with the SDK (putItem, for example), or do I have to refresh them myself after they expire?

**Comment by benrady** [comment]
As far as version goes, I'm using 2.1.48. I used the custom builder you guys provide to create a library with the following services:

• CognitoIdentity
• STS
• CognitoSync
• CognitoDynamoDB 
• Lambda

Am I missing any?

**Comment by benrady** [comment]
I haven't seen this happen again since switching to using refresh instead of getId. Closing for now. I'll open a new ticket if I see this problem while using refresh.
