### ISSUE TITLE
 Operation sqs on node js 

### ISSUE THREAD

**Issue by misfitdavidl** [aws/aws-sdk-js#737]
I read all the guide  ,but i can not find the guide of operating sqs on node js .In that case ,any one can help?

**Comment by ondruska** [comment]
https://aws.amazon.com/sdk-for-node-js/
and http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/index.html has all what I need.

**Comment by misfitdavidl** [comment]
Thanks for your help .node js and browser js have common in operation sqs.

**Comment by AdityaManohar** [comment]
@misfitdavidl you can check out the [API documentation for the `AWS.SQS`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html) client for information about the operations available as well as examples of how to use them. The documentation applies to both Node.js as well as the browser.

Let me know if this helps

**Comment by AdityaManohar** [comment]
@misfitdavidl 
I'm marking this as closed since there doesn't seem to be anything that needs to be done from the SDK side of things. Feel free to reopen this issue or open another issue if you have other questions.
