### ISSUE TITLE
Multipart Uploading using Cognito credentials access denied

### ISSUE THREAD

**Issue by lonormaly** [aws/aws-sdk-js#741]
Hello,

When using the multipart upload with Cognito id most of the times the upload finishes successfully, but once in every 7 uploads, some part gets 403 forbidden with error code AccessDenied and the upload fails to finish.

Nothing with the Cognito credentials changed since the upload began.
What can result this error if none of the parameters changed?

Thanks

**Comment by chrisradek** [comment]
@lonormaly 
Can you provide some sample code to help me reproduce this issue?

**Comment by lonormaly** [comment]
@chrisradek Sure: 
https://gist.github.com/lonormaly/9302863584550715a57d

Let me know if it's enough.
Notice that it's written using angularjs so $q, $interval, $log are being used.

Cheers

**Comment by chrisradek** [comment]
@lonormaly 
I'm still trying to reproduce this issue, but can you tell me if there is a common time interval between when you start performing uploads and when you encounter a failure?  Also, are you seeing this issue when retrying a failed or aborted upload, or is it any upload?

Thanks for your patience!

**Comment by lonormaly** [comment]
Hey, thanks for your time :)

The 403 error, caused by the Cognito service, was starting to appear, as far as we could test it, after the computer entered to some kind of a sleep process. Right after that, every retry failed with same error - a retry process includes an .abort() and a .send() calls.
In last couple of days I added a fix that before every retry, right after the call to .abort() function, I get the Cognito credentials again.

Thanks for help and time friend :)
Shai

**Comment by chrisradek** [comment]
Closing old issues.

Please open a new issue if you're having any additional problems.
