### ISSUE TITLE
[Feature Request - DynamoDB] Getting item attributes shouldn't require end user to marshal/unmarshal

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-js#743]
Right now attributes are returned with type information. This requires end users to now marshal/unmarshal these data structures. For 99% of use cases, this type information is overkill. At the very least, there should be a convenience method to get a clean JSON representation of an item's attributes. 

The fact that this library exists is troublesome https://github.com/CascadeEnergy/dynamoDb-marshaler 

For example, when someone is building a microservice between aws API Gateway<->Lambda<->DynamoDB  `dynamodb.get()` the end user is now required to manually map the attributes back into a sane response. The client should be able to take this type information and make a reasonable JSON representation.

**Comment by AdityaManohar** [comment]
@rromanchuk The SDK now does support the [`AWS.DynamoDB.DocumentClient`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html). This solves the problem that you just mentioned. Here is a blog post that introduces the document client: [Announcing the Amazon DynamoDB Document Client in the AWS SDK for JavaScript](http://blogs.aws.amazon.com/javascript/post/Tx1OVH5LUZAFC6T/Announcing-the-Amazon-DynamoDB-Document-Client-in-the-AWS-SDK-for-JavaScript)

Hope this helps!

**Comment by rromanchuk** [comment]
cool, thanks! RTFMing now
