### ISSUE TITLE
Getting error in ses service

### ISSUE THREAD

**Issue by Ashesh007** [aws/aws-sdk-js#746]
{ [SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

host:email.us-west-2.amazonaws.com
x-amz-content-sha256:37ae7fc816853ad13a2076564c2e7388ce3b5cff8b753cecfcf5e119b0ceb4a3
x-amz-date:20151007T094246Z

host;x-amz-content-sha256;x-amz-date
37ae7fc816853ad13a2076564c2e7388ce3b5cff8b753cecfcf5e119b0ceb4a3'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20151007T094246Z
20151007/us-west-2/ses/aws4_request
d3f4ff7ef8b0ce8edf79fa199ff3fe9dd119e1c1391824983cce554f5e375a14'
]
message: 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n\'POST\n/\n\nhost:email.us-west-2.amazonaws.com\nx-amz-content-sha256:37ae7fc816853ad13a2076564c2e7388ce3b5cff8b753cecfcf5e119b0ceb4a3\nx-amz-date:20151007T094246Z\n\nhost;x-amz-content-sha256;x-amz-date\n37ae7fc816853ad13a2076564c2e7388ce3b5cff8b753cecfcf5e119b0ceb4a3\'\n\nThe String-to-Sign should have been\n\'AWS4-HMAC-SHA256\n20151007T094246Z\n20151007/us-west-2/ses/aws4_request\nd3f4ff7ef8b0ce8edf79fa199ff3fe9dd119e1c1391824983cce554f5e375a14\'\n',
code: 'SignatureDoesNotMatch',
time: Wed Oct 07 2015 15:12:47 GMT+0530 (IST),
statusCode: 403,
retryable: false,
retryDelay: 30 }

Getting above error while using amazon sns service for mailing,
and while this secretKey and accestokenkey used in PHP its working. then what should i have to do??

**Comment by chrisradek** [comment]
@Ashesh007 
Can you provide some more information on what operations are causing this error to manifest? Is it all SES operations or just specific ones?

**Comment by Ashesh007** [comment]
I m using following code 
var fmt = require('fmt');
var amazonSes = require('awssum-amazon-ses');

var ses = new amazonSes.Ses({
    'accessKeyId'     : process.env.ACCESS_KEY_ID,
    'secretAccessKey' : process.env.SECRET_ACCESS_KEY,
    'region'          : amazonSes.US_EAST_1
});

ses.ListVerifiedEmailAddresses(function(err, data) {
    fmt.dump(err, 'err');
    fmt.dump(data, 'data');
});

I got above error using this code....
Can u help me how to solve this issue...
I m stuck from last 2-3 days and don't got answer...
And Using same credential in PHP script it's working...
Want to know what's the issue in above code...
I m tried many packages for SES but in all packages getting same error

**Comment by chrisradek** [comment]
@Ashesh007 
Can you try calling calling the operations using the `aws-sdk` directly?

Here's an example:
```javascript
var AWS = require('aws-sdk');
var ses = new AWS.SES({
    accessKeyId: YOUR_ACCESS_KEY, //Don't use in PRODUCTION
    secretAccessKey: YOUR_SECRET_ACCESS_KEY, //Don't use in PRODUCTION
    region: YOUR_REGION
});

ses.listVerifiedEmailAddresses(function(err, data) {
    if (err) {
        console.log(err);
    }
    if (data) {
        console.log(data);
    }
});
```

I've tried both the example you provided, and the one I listed above, and haven't been able to reproduce your issue yet.  One thing I did notice was that your error shows the region being used is `us-west-2`, and the example you provided shows you were trying to set it to `us-east-1`.

Let me know if the above example helps.

**Comment by Ashesh007** [comment]
I m providing same as format as u given in above example and sending to aws but getting same error ??? what should i have to do ??
any issue while creating sns credential for my API??

**Comment by chrisradek** [comment]
@Ashesh007 
How are you currently getting your credentials to pass into the SES operations?  Using the above example, did you hard-code them, or did you use some other method?

**Comment by Ashesh007** [comment]
Giving Hard-code them in my program

**Comment by chrisradek** [comment]
@Ashesh007 
I've still not had any luck reproducing your exact error message, but have you tried setting the `correctClockSkew` config parameter to `true` when creating an instance of SES?
Some details about this parameter can be found here:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#correctClockSkew-property

I don't think this is what's causing your issue, because normally the service would return back that your signature is out of date, but it'd be good to make sure about that.

Can you also tell me what versions of node and the SDK you are using?

**Comment by chrisradek** [comment]
@Ashesh007 
Are you still having issues with SES after trying the above?

**Comment by Ashesh007** [comment]
yes getting same issue .......

**Comment by ondruska** [comment]
In my opinion you are using SMTP credentials instead of correct access keys. That explains PHP (mailer?) works. Read the docs http://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html

**Comment by Ashesh007** [comment]
yes i have use that process as given docs... And Using same credentials in PHP code is working but in nodejs notworking...

**Comment by jeskew** [comment]
Hi @Ashesh007 -- I work on the AWS SDK for PHP. Could you provide the PHP code that works so we can help you translate it to JavaScript?

**Comment by Ashesh007** [comment]
```
<?php
function Send_Mail($to,$subject,$body)
{
require 'class.phpmailer.php';
$from = "From Id";
$mail = new PHPMailer();
$mail->IsSMTP(true); // SMTP
$mail->SMTPAuth   = true;  // SMTP authentication
$mail->Mailer = "smtp";
$mail->Host       = "tls://email-smtp.us-west-2.amazonaws.com"; // Amazon SES server, note "tls://" protocol
$mail->Port       = 465;                    // set the SMTP port
$mail->Username   = "";  // SES SMTP  username Access Key
$mail->Password   = "";  // SES SMTP password Secret Key
$mail->SetFrom($from, 'From Name');
$mail->AddReplyTo($from,'9lessons Labs');
$mail->Subject = $subject;
$mail->MsgHTML($body);
$address = $to;
$mail->AddAddress($address, $to);

if(!$mail->Send())
return false;
else
return true;

}
?>
```
Above function is use for Sending Mail Using SMTP....
Using above code its working in PHP but while using this credential in nodejs its getting error..

**Comment by jeskew** [comment]
As @ondruska suspected, the PHP script is using a username and password to send mail over SMTP. The `AWS.SES` constructor you're using in JavaScript is expecting an AWS access key and secret key -- these are not the same as the SMTP credentials that you're successfully using in PHP.

You can also use an SMTP library in JavaScript in you'd prefer. I don't have any recommendations, but there seem to be [a number of options on NPM](https://www.npmjs.com/search?q=smtp).

Hope this helps clarify things. Please feel free to reopen if you have any questions or concerns.

**Comment by Ashesh007** [comment]
using aws-sdk-js then which credentials which i have to use as access key and secret key....... while creating SES, got only access key and secret key... and that credentials are works in PHP then what's the difference in that ?????????

**Comment by jeskew** [comment]
The PHP code is connecting to SES over SMTP using [SMTP credentials](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html), whereas the JavaScript code is attempting to connect to SES over the HTTP API, which is authenticated with [AWS security credentials](http://docs.aws.amazon.com/general/latest/gr/aws-security-credentials.html). 

These credentials will always be different.

**Comment by Ashesh007** [comment]
thanks for yr support........... Its working.........
