### ISSUE TITLE
Cloudwatch describeAlarms by namespace?

### ISSUE THREAD

**Issue by samsamm777** [aws/aws-sdk-js#753]
Is there a way to list cloudwatch alarms by namespace? If not, this would be a really useful feature.

**Comment by chrisradek** [comment]
@samsamm777 
Currently alarms can only be retrieved by name or prefix. I would recommend creating a Feature Request thread on the Amazon CloudWatch forums (https://forums.aws.amazon.com/forum.jspa?forumID=138)  to let the service team know about this request.

I'm closing this issue, but feel free to re-open if you want to discuss this further.
