### ISSUE TITLE
No way to handle RequestAbortedError error when intentionally aborting request

### ISSUE THREAD

**Issue by chazmo03** [aws/aws-sdk-js#755]
It seems that there is no way to abort a a request without an error being thrown.

I am using `s3.getObject(params).createReadStream()` to read through files but I want to abort the request after I have gotten the data I need, which is a little data at the beginning of a large file.

Per #750, adding `stream.on('error', function() {})` doesn't prevent the error from being thrown. I see nothing in the documentation for aborting a request without throwing an error. Is there any way to do this?

**Comment by chrisradek** [comment]
@chazmo03 
The error event bound to the stream is intended to be passed an `error` object that indicates the request was aborted. Are you also seeing another thrown error, similar to #750? If so, can you provide a reproducible, minimal code snippet so I can investigate more thoroughly?

**Comment by andreasherzog** [comment]
We were just able to resolve  #750: It is necessary to listen also to the error object of the stream you pipe to / here it could be a stream you pipe your ReadStream to

**Comment by chazmo03** [comment]
Thank you @andreasherzog . @chrisradek, I'm going to try this suggestion and if it doesn't resolve it, I'll post a snippet.

**Comment by chrisradek** [comment]
@chazmo03 
I'm closing this issue, but feel free to comment or re-open if you're still having issues getting this to work.
