### ISSUE TITLE
ManagedUpload abort() in browser

### ISSUE THREAD

**Issue by tgrant59** [aws/aws-sdk-js#760]
ManagedUpload for S3 is great. But it is mentioned in the docs (and I have double checked myself) that abort does not work in the browser.

Are there any plans to implement this in the browser or is there a reason why it is not available? This feature would be quite useful.

Is there any workaround for stopping a ManagedUpload (even if it is unclean/ugly) started in the browser?

**Comment by chrisradek** [comment]
@tgrant59 
Interestingly, when I tested the `abort` method in the latest versions of Safari, Firefox, and Chrome, it stopped the upload and aborted as expected. I will need to investigate more thoroughly what issues there were with aborting in a browser. 

Have you encountered a situation where the `abort` method hasn't worked yet?

**Comment by ig16022** [comment]
Hi guys,

Can anyone confirm that the 'abort' method of AWS.S3.ManagedUpload class should be working in the browser environment now? The official documentations states:

Method Details
abort() ⇒ void
Note: This feature is not supported in the browser environment of the SDK.

If this is the case, what are our options for abort / resume?

**Comment by franleplant** [comment]
The `abort` function is not working for me two, tested with the latest SDK.
The file keeps uploading as inspected in the Network tab.
Tested in Chrome

**Comment by Villa41** [comment]
The abort function is not working and also I've tested with the latest SDK... The file keeps uploading and callback error is "Error: RequestAbortedError Request aborted by user"
Tested in Chrome
There is someone that knows another option to abort the upload?

**Comment by chrisradek** [comment]
@Villa41 
Can you share what version of Chrome and for what OS you're testing in?

**Comment by Villa41** [comment]
I'm testing in 
Chrome Versión 48.0.2564.97 (64-bit)
OS Ubuntu 15.10, 64 bits

**Comment by Villa41** [comment]
Hi everyone,
I was testing the abort method and i found the problem. In my case, it's with the file.
When the size is less than 5 MB the mothod doesn't work  but there is no problem with a bigger file. 
I tried with a files 6,8 MB and 14MB.

**Comment by chrisradek** [comment]
@Villa41 
That makes sense. When the file is smaller than 5MB, then behind the scenes the managed uploader does a single `putObject` request. There isn't a way to abort that from our end once it's been sent. Anything larger than 5 MB will be uploaded as a multi-part upload. Any `uploadPart` requests that have already been sent won't abort, but any future requests should never get sent, in theory.

**Comment by chrisradek** [comment]
The docs have been updated to clarify how the `abort()` method works within the browser.

Currently, it will simply prevent additional `uploadPart` requests from being sent, but we may look into aborting the actual requests in the future as well.
