### ISSUE TITLE
AutoScaling is missing?

### ISSUE THREAD

**Issue by samsamm777** [aws/aws-sdk-js#761]
When trying to do ```var asg = new AWS.AutoScaling();``` i get an error.

```
TypeError: undefined is not a function
    at new AutoScalingService (file:///media/sam/47bc07be-8934-4bbf-8aab-b4ab50aaddcb/repos/els/operations/monitoring/build/src/app/aws/autoscaling.module.js:14:13)
```

however, constructing any of the other services. does work fine. I am following the docs http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/AutoScaling.html

**Comment by chrisradek** [comment]
@samsamm777 
What version of the SDK are you using? Also, are you running this in the browser or in node?

**Comment by samsamm777** [comment]
Hey, I am using 2.2.9 and the browser version.

**Comment by samsamm777** [comment]
So it appears the AutoScaling service is not included in the default sdk. So I built my own full sdk with all the services. However the other services to not support CORS. So now im stuck....

**Comment by chrisradek** [comment]
@samsamm777 
At this time AutoScaling isn't supported in a browser environment.  You can use it within node, or an environment that doesn't enforce the CORS standard (i.e. Google Chrome extensions and Windows Store Applications.) 

If you'd like to see this functionality supported in a browser, I'd suggest creating a feature request thread for CORS support of Auto Scaling on the forums here:
https://forums.aws.amazon.com/forum.jspa?forumID=30

Let me know if you have any further questions!

**Comment by chrisradek** [comment]
Closing since the SDK doesn't support AutoScaling in the browser.  Please feel free to comment or reopen if you have any related questions or want to discuss this further.
