### ISSUE TITLE
No cross domain XHR calls are firing in any version of Internet Explorer when trying to upload to an S3 bucket.

### ISSUE THREAD

**Issue by droplab** [aws/aws-sdk-js#762]
I've tried the following versions of the sdk: 2.2.6, 2.2.11. The documentation states support for IE10+. I've tested this in IE 10 and IE11 and no request is firing at all. Is anyone else having this problem?? 

Also, we have proper CORS rules on the target S3 bucket. This is the request:

    var params = { Key: filename, ContentType: 'image/png', Body: typed_array, ACL:"public-read" };		
			
    this.aws.upload(params, function(err, data) {		
        if(data) console.log(data.Location);		
        else console.log('AWS ERROR',err);		
    });

**Comment by chrisradek** [comment]
@droplab 
Have you verified if the same code runs in a browser such as Firefox or Chrome? And am I understanding correctly that the callback function you supply to the upload method isn't being triggered as well?

**Comment by chrisradek** [comment]
@droplab 
Are you still having issues with IE?

**Comment by andrey-bahrachev** [comment]
It has to do with IE's security settings, namely 'Access data sources across domains' setting - it's disabled by default. Say hi to MS.

**Comment by chrisradek** [comment]
Closing the issue, but feel free to comment or re-open if you are still encountering issues.
