### ISSUE TITLE
ManagedUploads and streams in the browser

### ISSUE THREAD

**Issue by kentor** [aws/aws-sdk-js#771]
Is it possible to pass something that implements the Readable Stream interface as the Body of a ManagedUpload in the browser environment?

I'm trying to do some client side encryption on very large files. I was thinking of creating a `Readable Stream` from a `File`, then `pipe`ing it to some encryption function, and then passing that to `ManagedUpload`.

However, I believe the current sdk expects the body object to implement `slice` in the browser environment, otherwise it throws `Unsupported body payload`.

**Comment by chrisradek** [comment]
@kentor 
There isn't currently a way to use streams with `ManagedUpload` in the browser.  What are you using to include support for streams in the browser?

It is possible to enable server side encryption so that objects are encrypted when stored in S3. More information on server-side encryption that S3 supports can be found here: http://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html
However, I do realize server side encryption may not suit your needs.

**Comment by kentor** [comment]
@chrisradek 
I was thinking of using the [filereader-stream](https://github.com/maxogden/filereader-stream) library to get a readable stream from a `File`. Then I'm using [crypto-browserify](https://github.com/crypto-browserify/crypto-browserify) to encrypt the stream.

Btw I did a quick and dirty modification of the `send` function in `lib/s3/managed_upload.js` to take a stream in the browser and it does appear to work.

I changed this
```js
    if (self.sliceFn) {
      self.fillQueue = self.fillBuffer;
    } else if (AWS.util.isNode()) {
      var Stream = AWS.util.nodeRequire('stream').Stream;
      if (self.body instanceof Stream) {
        ...
      }
    }
```

to this 
```js
    if (self.sliceFn) {
      self.fillQueue = self.fillBuffer;
    } else if (typeof self.body._read === 'function') {
      ...
    }
```

My app code is something like this:
```js
const crypto = require('crypto-browserify');
const fileReaderStream = require('filereader-stream');

...

const encrypt = crypto.createCipheriv(
  'aes-256-cbc',
  '3zTvzr3p67VC61jmV54rIYu1545x4TlY',
  '60iP0h6vJoEaJoEa'
);
const stream = fileReaderStream(file).pipe(encrypt);
const managedUpload = s3.upload({
  Body: stream,
  Key: `test/${file.name}`,
});
managedUpload.send();
```

**Comment by chrisradek** [comment]
@kentor 
I know this is tangential to your request, but is there a reason you'd prefer client-side encryption in the browser over server-side encryption?

**Comment by kentor** [comment]
@chrisradek At my work (the product I am working on) I think it would be a bunch of work to add support something like SSE-C. Another reason is say if we were to back our storage with another storage provider, it would be easier to add support for that if we handled our own encryption. We don't want to be too tied down to what AWS offers.

**Comment by ajredniwja** [comment]
Closing this issue since it was taken care of in a PR.
