### ISSUE TITLE
headObject command fails on Network Failure

### ISSUE THREAD

**Issue by lonormaly** [aws/aws-sdk-js#772]
Hello,

headObjects return error of Network Failure while same parameters with same Cognito credentials, getObject works.

Maybe this issue is related: https://github.com/aws/aws-sdk-js/issues/203

Cheers

**Comment by jeskew** [comment]
I'm not sure this is related to issue 203, as that concerned invoking a callback multiple times in the case of a network failure. 

Are you calling `headObjects` or `headObject`? The former is not a supported operation.

**Comment by lonormaly** [comment]
headObject

**Comment by jeskew** [comment]
Thanks! What does the [CORS Configuration](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) on your bucket look like?

**Comment by lonormaly** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>ETag</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>


I use an IAM role that is attached to the Cognito user:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:GetObject"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::<bucket>/Local/Artworks/Artwork*/${cognito-identity.amazonaws.com:sub}/*"
            ]
        }
    ]
}

With getObject it works and I get the object, yet with headObject I get Network Failure and I do have internet connectivity...

**Comment by jeskew** [comment]
Can you try adding `<AllowedMethod>HEAD</AllowedMethod>` to your CORS configuration?

**Comment by lonormaly** [comment]
Ok, now it works, yet I don't get most of the properties, such as ContentLength:

![image](https://cloud.githubusercontent.com/assets/3742919/10917624/6b1bcf6c-826a-11e5-914e-b823eefd6731.png)

**Comment by jeskew** [comment]
You'll need to expose additional headers to get that information. It looks like you're only exposing the ETag header in the CORS configuration above; you can add `ExposeHeader` nodes for 'Content-Length' and [other common response headers](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html) if you'd like for those to be visible in a browser.

Hope that helps!

**Comment by jeskew** [comment]
Closing, as it sounds like you should be all set now. Please feel free to reopen if you have any further questions.

**Comment by lonormaly** [comment]
No, I'm ready to go. Thanks for you help :)
PS - It would be great to add this information on documentation as well next to the headObject command
