### ISSUE TITLE
Slow file upload

### ISSUE THREAD

**Issue by optimisme** [aws/aws-sdk-js#773]
Hi,

I am uploading several files from my 'nodejs' server to S3 using the next function:

Drive.prototype.saveText = function (path, str, callback) {
    var self = this,
        exists = true,
        params = {},
        pathFix = path,
        pathFull = this.getBase(path) + path + '.gz';

    zlib.gzip(str, function (err, objGzip) {
        switch (self.destination) {
        case 'drive':
            mkpath(pathFull.substr(0, pathFull.lastIndexOf('/')), function (err) {
                if (err) {
                    callback(err);
                } else {
                    fs.writeFile(pathFull, objGzip, function (err) {
                        callback(err);
                    });
                }
            });
            break;
        case 's3':
            params = {Key: pathFull, Body: objGzip};
            self.loadText(pathFix, function (err, obj) {
                if (err) {
                    exists = false;
                }
                console.log('a3x3 ' + objGzip.length);
                self.s3bucket.upload(params, function (err, data) {
                    if (exists || pathFix.indexOf(self.s3List) !== -1) {
                        console.log('a3x4a');
                        callback(err);
                    } else {
                        console.log('a3x4b');
                        self.unlink(pathFix.substr(0, pathFix.lastIndexOf('/')) + '/' + self.s3List, function (err) {
                            callback(err);
                        });
                    }
                });
            });
            break;
        }
    });
};

The step between logs 'a3x3' and 'a3x4a' sometimes is fast, but very often needs several seconds (>10s) to call the callback. Usually objGzip.length is arround 22000. Can I do something to improve speed or at least kill the S3 request after a timeout?

Thanks

**Comment by optimisme** [comment]
Sorry by several seconds I mean >10 not lower.

**Comment by chrisradek** [comment]
@optimisme 
There is a way to abort an upload, by using the `ManagedUpload` `abort` method:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#abort-property

What's the typical size (in MB) of the `Body` of your uploads?  Are there differences in the size of your `Body` when the `upload` method completes quickly versus when it takes a longer time?

**Comment by optimisme** [comment]
Thanks for your help, my uploads are arround 100kilobytes and never bigger than 200. I modified the source so it looks like this:

        case 's3':
            params = {Key: pathFull, Body: objGzip};
            self.loadText(pathFix, function (err, obj) {
                if (err) {
                    exists = false;
                }
                upObj = self.s3bucket.upload(params, function (err, data) {
                    upObj = null;
                    if (exists || pathFix.indexOf(self.s3List) !== -1) {
                        callback(err);
                    } else {
                        self.unlink(pathFix.substr(0, pathFix.lastIndexOf('/')) + '/' + self.s3List, function (err) {
                            callback(err);
                        });
                    }
                });
                setTimeout(function () {
                    if (upObj !== null) {
                        upObj.abort();
                        callback({ code: 0, msg: 'Upload aborted by timeout'});
                    }
                }, 1500);
            });
            break;

**Comment by optimisme** [comment]
This bug can be closed, looks like something is wrong with my local server. I can't reproduce it at openshift.
