### ISSUE TITLE
DynamoDb: C++ Error

### ISSUE THREAD

**Issue by gregorskii** [aws/aws-sdk-js#776]
Hi,

I am experiencing an intermitted write issue to DynamoDb using the local db.

All configuration is correct, as it works most of the time.

Error:
```
#
# Fatal error in ../deps/v8/src/deoptimizer.cc, line 2764
# CHECK(result == fixed_size + (stack_slots * kPointerSize) + outgoing_size) failed
#

==== C stack trace ===============================

 1: ??
 2: ??
 3: ??
 4: ??
 5: ??
 6: ??
 7: ??
Program node --debug index.js exited with code null
```

NOTE:

I was getting CRC32 errors so I did disable CRC with my initialization (note I am using Dynasty JS):

```
Error: Unhandled rejection CRC32CheckFailed: CRC32 integrity check failed
```

```

require('dynasty')({
        accessKeyId: process.env.AWS_KEY,
        secretAccessKey: process.env.AWS_SECRET,
        dynamoDbCrc32: false
    }, process.env.AWS_ENDPOINT);

```

Thanks for any help

**Comment by chrisradek** [comment]
@gregorskii 
I'm not familiar with the dynasty library. What sort of operations are failing?

As of version 2.2.0 of the AWS SDK, much better DynamoDB support has been baked in with the addition of the `DocumentClient`.  Documentation on this client can be found here:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html

I would strongly recommend making use of the client built into the AWS SDK if it can suit your needs.

Let me know if this information is helpful!

**Comment by gregorskii** [comment]
@chrisradek I will try without the ORM.

Thanks

**Comment by chrisradek** [comment]
Closing this issue, but feel free to comment or open a new one if you continue facing issues using the AWS SDK.

**Comment by gregorskii** [comment]
Yes this appears to work. Will update if I find any issues.

Thanks!
