### ISSUE TITLE
getSignedUrl creates invalid signature when CacheControl parameter is present

### ISSUE THREAD

**Issue by Prinzhorn** [aws/aws-sdk-js#780]
Here's a demo repo https://github.com/Prinzhorn/aws-s3-signature-cache-control-issue

Relevant code:

```js
var uuid = require('uuid');
var AWS = require('aws-sdk');

AWS.config.update({
    region: 'eu-central-1'
});

var s3 = new AWS.S3();

var params = {
    Bucket: process.env.BUCKET,
    Expires: 3600,
    Key: uuid.v4(),
    ContentType: 'image/jpeg',

    //Comment this line out and the signature is valid.
    CacheControl: 'max-age=' + 10000
};

s3.getSignedUrl('putObject', params, function(err, url) {
    if(err){
        return console.error(err);
    }

    console.log(url);
});
```

Basically if I remove the `CacheControl` from the params object, it works. Otherwise the upload with the generated URL fails because of a wrong signature. Maybe I'm doing something stupid there?

**Comment by Prinzhorn** [comment]
This unwritten law kicked in again, where you get closer to the issue once you ask for help. It seems like `ContentType` is ignored, albeit the signature is valid. So how do I sign a POST/PUT request with all parameters except the file itself without having to duplicate the parameters again when making the request? I mean `getSignedUrl` doesn't seem like the right choice for `putObject`, is it? I guess I have to supply all the parameters separate from the URL and only need the signature itself.

**Comment by chrisradek** [comment]
@Prinzhorn 
Thanks for the example code. My initial suspicion is that the Cache-Control header needs to be provided when making the request because it is included as a signed header in the presigned URL (X-Amz-SignedHeaders). I'm looking into if this is truly necessary.

**Comment by chrisradek** [comment]
@Prinzhorn 
It is indeed necessary to provide the `Cache-Control` header in your request if it is included as a parameter to `getSignedUrl`. It is possible to only set the `Cache-Control` header when making your request, and leave it out of your `getSignedUrl` call.  If it is included in `getSignedUrl` however, it is essentially enforcing that `Cache-Control` must be sent with the same value in the request.

Let me know if this explanation helps, or if you'd like to discuss further.

**Comment by Prinzhorn** [comment]
I cannot confirm what you said. Given my demo code above, if I sign the request and include `CacheControl:'max-age=1337'` and then upload the image using `curl -T unsplash.jpg -H 'Cache-Control:max-age=1337' the-url` I get an invalid signature error. If I exclude the CacheControl from the `getSignedUrl` params and send it along it is applied correctly. So it seems that enforcing a certain Cache-Control header is currently not possible.

**Comment by chrisradek** [comment]
@Prinzhorn 
Just to confirm, you've been testing in a `V4` region only, correct? (i.e. eu-central-1). I may have found an issue in the code causing the request to fail even when the Cache-Control header is set to the same as defined when generating a signed url.

**Comment by Prinzhorn** [comment]
> Just to confirm, you've been testing in a V4 region only, correct? (i.e. eu-central-1)

Yes, my buckets are all eu-central-1
