### ISSUE TITLE
Google Closure compability

### ISSUE THREAD

**Issue by aleksandersumowski** [aws/aws-sdk-js#783]
Hi,
is the sdk compatible with Google Closure advanced compilation, i.e. fits inside following limitations:
https://developers.google.com/closure/compiler/docs/limitations

Cheers,
Aleksander

**Comment by chrisradek** [comment]
@aleksandersumowski 
We don't specifically test the SDK with Google Closure. That said, I would not feel comfortable saying the SDK will work with advanced compilation. I think there are risks, particularly with regards to compilation renaming properties.

**Comment by aleksandersumowski** [comment]
Thanks!
