### ISSUE TITLE
Cognito headObject Forbiden after connectivity restarted

### ISSUE THREAD

**Issue by lonormaly** [aws/aws-sdk-js#787]
Hello,

I use Cognito as authenticator to S3. 
Usually I can perform headObject function to retrieve the file meta-data.
Sometimes after the internet connection is lost, I get an error with "Forbidden" code.
I tried to refresh the Cognito credentials before the request but with no help.

Thank you

**Comment by chrisradek** [comment]
@lonormaly 
Can you share how you're refreshing your credentials before making a request?

When you say internet connection is lost, do you mean the connection drops and comes back after a short time, or the system goes to sleep and then when waking up the user returns to the application?

**Comment by lonormaly** [comment]
Sure:

`            AWS.config.region = 'us-east-1'; // Region
            AWS.config.credentials = new AWS.CognitoIdentityCredentials({
                IdentityPoolId: COGNITO_POOL
            });
            if ($localStorage.cognitoId) {
                AWS.config.credentials.refresh(function(err) {
                    if (err) {
                        getNewCognitoCredentials()
                            .then(function(res) {
                                deferred.resolve(AWS.config.credentials.identityId);
                            }, function(err) {
                                deferred.resolve(err);
                            });
                    } else {
                        deferred.resolve(AWS.config.credentials.identityId);
                    }
                });`

When I say connection is lost I mean the connection was dropped for several minutes.

**Comment by chrisradek** [comment]
Closing old issues.

The likely culprit is that your credentials had expired.

Please open a new issue if you're having any additional problems.
