### ISSUE TITLE
Using the npm module in the browser

### ISSUE THREAD

**Issue by nowakj** [aws/aws-sdk-js#789]
Hi,

I ma trying to use the aws-sdk module in the browser (with webpack) by doing:
var AWS = require('aws-sdk');

When I try to get Cognito credentials it fails with the following error:
TypeError: AWS.CognitoIdentity is not a function
    at CognitoIdentityCredentials.AWS.CognitoIdentityCredentials.AWS.util.inherit.createClients 
    at CognitoIdentityCredentials.refresh 
    at CognitoIdentityCredentials.get 

It seems that it is not initialising the CognitoIdentity service.
If I require the dist file it works fine:
require('../../node_modules/aws-sdk/dist/aws-sdk');
but I would like to require the module instead of the specific file.

Is there any way to make this work with the module require?

Thanks

**Comment by jeskew** [comment]
Hi @nowakj,

Have you tried using our script package for the browser? You can find more on how to use it in our [user guide](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-intro.html).

**Comment by nowakj** [comment]
Hi jeskew,

I am able to use the packaged files that come in the 'dist' directory just fine.
However the model we have for our product is to do the packaging with webpack and use npm modules directly with 'require' or 'import'. I was hoping we could do the same with the aws-sdk npm as this would be more consistent with our approach.

Thanks,
Jacek

**Comment by jeskew** [comment]
There was some discussion on how to use the SDK with webpack in #603. A few solutions were proposed, but I'm not sure if they'd work for everyone. Webpack support seems pretty popular so I'm going to mark this ticket as a feature request and keep it open for now.

**Comment by nowakj** [comment]
I was able to solve the problems described in #603, so the module loads fine. but than fails at runtime as the CognitoIdentity service is not loaded.
It would be great if you could add webpack support. thanks!

**Comment by hassankhan** [comment]
Indeed, it would be really beneficial if the SDK was updated rather than us having to work around specific issues by trial and error.

**Comment by jeskew** [comment]
Support for webpack was added in [version 2.6.0](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#260)
