### ISSUE TITLE
callback signature for s3.upload is not documented

### ISSUE THREAD

**Issue by markstos** [aws/aws-sdk-js#790]
The callback signature for `s3.upload` is not documented. It should be documented to be the same callback that `send()` called from the S3 Managed Upload service, since the `send()` method immediately if a callback is provided.  Users may be particularly interested that the callback `data` object has the `Location` property.  The REST API PUT method does not return the `Location` method, so the inclusion here is notable.

I just ended writing a custom method to build the S3 Objects full URL after uploading, but after reading the source code, I was about to confirm what the callback was confirming and that the `upload` method should always produce a `data.Location` value, whether the operation is an object upload, replacement or multi-part upload.

I was previously using `s3-upload-stream` and was glad to find the AWS SDK now includes supports for streaming uploads directly.

**Comment by chrisradek** [comment]
@markstos 
Thanks for the feedback, I will update the docs to include the callback signature.
