### ISSUE TITLE
data is empty even though the request was completed successfully

### ISSUE THREAD

**Issue by darkpssngr** [aws/aws-sdk-js#793]
var sqs = new AWS.SQS(config.aws);
sqs.getQueueUrl({QueueName: queueName},function (err, data) {
        if(err){
          console.log(error);
          return;
        }
        console.log(data)
});

The data is empty even though the requested was completed successfully and the response had the necessary data. I'm not sure what is wrong although the response seems to be empty when xml is parsed and once the call back is executed I'm able to see the response in the network logs. I'm using node-inspector to debug.

I'm not sure I am doing something wrong here. please help. 
Thanks

**Comment by chrisradek** [comment]
@darkpssngr 
What version of the SDK are you using?  Can you also inspect `this` in the callback and verify `data` and `error` are both empty? Your code looks correct, aside from logging `error` instead of `err`.

**Comment by darkpssngr** [comment]
I'm using verion 2.2.16 and yes I inspected this, at the time when the xmlparse is called on the response the response body in the http is also empty.

**Comment by darkpssngr** [comment]
Closing the issue as it got fixed, once I update my nodejs to the latest stable version.

**Comment by darkpssngr** [comment]
It seems node-inspector is causing this problem. When I update my nodejs version node-inspector broke and everything worked perfectly, but once I fixed the problem with node-inspector it again started giving me an empty response. I'm raising this issue on node-inspector.

**Comment by darkpssngr** [comment]
Can you please have a look at this comment and let me know if it is something that should be fixed on node-inspector or aws-sdk.
https://github.com/node-inspector/node-inspector/issues/703#issuecomment-147019826

**Comment by darkpssngr** [comment]
any updates on this ?

**Comment by chrisradek** [comment]
@darkpssngr 
Thanks for the link to the discussion over at node-inspector. I haven't had a chance to test the code change suggested yet but will take a look shortly.

Can you confirm which version of node-inspector you're able to replicate the issue with?

**Comment by darkpssngr** [comment]
I'm using the latest version(v0.12.3).

**Comment by darkpssngr** [comment]
Hey,
any updates?

**Comment by chrisradek** [comment]
@darkpssngr 
Sorry for the delays. I finally had a chance to read through the issue you linked. Without diving further into the node-inspector code, it's hard to tell exactly why data is being returned as an empty object. While the change that was suggested does appear to fix the issue for the example provided in this thread, it also causes many of our unit tests to fail. 

It also sounds like earlier versions of node-inspector worked with the SDK, so it'd be interesting to see exactly what changed between those versions and recent ones.

At this point, I'm not sure what we can do from the SDK side to make this work better with node-inspector without taking a deeper look into that package.

**Comment by darkpssngr** [comment]
@chrisradek 
Sorry for the delay, there was no proper internet connection here due to floods. 
I think this started to fail when node-inspector added the feature to see network logs. Anyways if nothing can be done, I'll use the workaround provided in the thread during development.
Thanks for looking into it. :)

**Comment by darkpssngr** [comment]
closing this issue as it was fixed in node-inspector/node-inspector#703
