### ISSUE TITLE
Documentation: phrase like "See AWS.S3.region for more information." should be linked

### ISSUE THREAD

**Issue by markstos** [aws/aws-sdk-js#794]
This page contains some references to further documentation to review, like this:

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html

"See AWS.S3.region for more information."
"See AWS.S3.maxRetries for more information."

However, the references aren't linked and it's not clear where to find the reference documentation. The simplest think for the documentation readers would be to able to click on links in these phrases that go to the referenced documentation.

**Comment by govindrai** [comment]
@srchase Since this has not made it into the documentation, I am unable to get the proper information for S3.maxRetries. I am trying to find the defaults that s3 uses for its maxRetries for any given operation. How can I get that information?

**Comment by RanVaknin** [comment]
This is terrible
(Test)

**Comment by markstos** [comment]
Still an issue.
