### ISSUE TITLE
params in object 'new AWS.S3()' doesn't work for regions other than default region

### ISSUE THREAD

**Issue by forestzrd** [aws/aws-sdk-js#799]
the code before only works for default region : us-east-1, not for other regions if you set with ' AWS.config.region = 'xx-xxxxxxx-x''.

var s3 = new AWS.S3({params: {Bucket: 'myBucket', Key: 'myKey'}});
s3.createBucket(function(err) {
  if (err) { console.log("Error:", err); }
  else {
    s3.upload({Body: 'Hello!'}, function() {
      console.log("Successfully uploaded data to myBucket/myKey");
    });
  }
});

**Comment by OllieJennings** [comment]
Getting this error as well.

Can't seem to create any buckets with params expect for the default region.

Using aws-sdk: 2.2.17

**Comment by chrisradek** [comment]
@OllieJennings @forestzrd 
If you want to create a bucket outside of `us-east-1`, you need to also specify the `LocationConstraint`.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createBucket-property

That said, it looks like there may be a bug when `AWS.config.region` is set to something other than `us-east-1` and no `LocationConstraint` is set. Based on the documentation, it would suggest that the bucket should be created in `us-east-1` in this situation.  I'll investigate that issue further.

In the meantime, let me know if specifying the `LocationConstraint` allows you to create buckets in the desired region.

**Comment by AdityaManohar** [comment]
@forestzrd @OllieJennings to create a bucket in a region other that `us-east-1`, you will need to specify the correct signing region by setting `AWS.config.region` **and** set the `LocationConstraint` parameter to the same region as the region. This is not so much a bug, more a nuance of how the Amazon S3 API works.
