### ISSUE TITLE
Put inserting empty item

### ISSUE THREAD

**Issue by susanlinsfu** [aws/aws-sdk-js#803]
Creating the table works fine and when I insert an item it says the item inserted successfully, but shows an empty item was inserted.

"Added item:{}"

It should instead show the item has a username of 'bob' and a password of 'password'. I am using the most recent versions of nodejs, npm, dynamodb local, and the javascript aws-sdk. When I try to get the item it says it is unidentified.

var dynamodb = new AWS.DynamoDB();

var dynamodbDoc = new AWS.DynamoDB.DocumentClient();

var createUsersTable= {
TableName : "Users",
KeySchema: [
{ AttributeName: "username", KeyType: "HASH"}
],
AttributeDefinitions: [
{ AttributeName: "username", AttributeType: "S" }
],
ProvisionedThroughput: {
ReadCapacityUnits: 1,
WriteCapacityUnits: 1
}
};

dynamodb.createTable(createUsersTable, function(err, data) {
if (err) {
console.error("Unable to create table. Error JSON:", JSON.stringify(err, null, 2));
} else {
console.log("Created table. Table description JSON:", JSON.stringify(data, null, 2));
}
});

setTimeout( function(){
var table = "Users";

var username = 'bob';

var params = {
    TableName:table,
    Item:{
        "username": 'bob',
        "password": 'password'
    }
};

console.log("Adding a new item...");
dynamodbDoc.put(params, function(err, data) {
    if (err) {
        console.error("Unable to add item. Error JSON:", JSON.stringify(err, null, 2));
    } else {
        console.log("Added item:", JSON.stringify(data, null, 2));
    }
});
}, 4000 );

**Comment by susanlinsfu** [comment]
@chrisradek 

I have changed my params to now look like this:

var params = {
        TableName: table,
        Item:{
            "username": 'bob'
        },
        ReturnValues: 'ALL_NEW'
    };

But get the error message when I try to insert now:

Unable to add item. Error JSON: {
  "message": "Return values set to invalid value",
  "code": "ValidationException",
  "time": "2015-11-18T03:25:33.853Z",
  "statusCode": 400,
  "retryable": false,
  "retryDelay": 0
}

**Comment by susanlinsfu** [comment]
@chrisradek  Thanks Chris, I have just tried ALL_OLD, and NONE and these work!

**Comment by cleung2010** [comment]
@chrisradek Since `put` and `putItem` doesn't return the new item attributes through `ReturnValues`, is there a way to have it return the newly inserted entry without querying the table separately with a `get`?

**Comment by sickDevelopers** [comment]
+1 for cleung2010 question

**Comment by hariom12** [comment]
You can get the return value as the new inserted json entry.You have to just write one return value statement so it will give you the response as your recent json object entry.For Ex:-

var params = {
    TableName: 'Music',
     Item: {
        "Artist":"Nofddf5653659",
        "SongTitle":"Cfdsll33637656",
        "AlbumTitle":"Sfvewhat323589326",
        "Year": 2015,
        "Price": 2.14,
        "Genre": "Country",
        "Tags": {
            "Composers": [
                  "Smith",
                  "Jones",
                  "Davis"
            ],
            "LengthInSeconds": 214
        }
    },
   
    ReturnValues: 'ALL_OLD', 
};
dynamodb.putItem(params, function(err, data) {
    if (err) print(err); // an error occurred
    else print(data); // successful response
});

This is my entry now i am pasting the console output of javascript shell
![hari](https://cloud.githubusercontent.com/assets/15011520/16875198/c6f11f1c-4abb-11e6-9fce-996e35cdd5e7.png)

**Comment by hariom12** [comment]
while inserting into the Json data to table we have to write Return value statement .
For Ex:-
var params = {
    TableName: 'Music',
    Item: {
        "Artist":"No One You Know",
        "SongTitle":"Call Me Today",
        "AlbumTitle":"Somewhat Famous",
        "Year": 2015,
        "Price": 2.14,
        "Genre": "Country",
        "Tags": {
            "Composers": [
                  "Smith",
                  "Jones",
                  "Davis"
            ],
            "LengthInSeconds": 214
        }
    },
    
    ReturnValues: 'ALL_OLD', // optional (NONE | ALL_OLD)
    
};
dynamodb.putItem(params, function(err, data) {
    if (err) print(err); // an error occurred
    else print(data); // successful response
});


I have run this in javascript shell we can get the recent inserted value on the console output.I am sharing the screenshot.
![dynamo](https://cloud.githubusercontent.com/assets/15011520/16892684/e6d94fe6-4aae-11e6-8a07-4272be138948.png)

**Comment by alayor** [comment]
I just had the same issue as @susanlinsfu. Changed ReturnValues to ALL_OLD and it worked.
However, I wonder if there is way to return the actual NEW values.

**Comment by jeskew** [comment]
A note was added in https://github.com/aws/aws-sdk-js/commit/9ddc7fb192f7303ff80cc26db84c8ca4e324f416 spelling out which `ReturnValues` value is accepted by both `PutItem` and `DeleteItem`.

@alayor When making a `PutItem` request, you're overwriting the entire item, so if the request succeeds then the new values are the ones provided as input parameters. If you're updating an item in place with an `UpdateItem` operation, you can use `ALL_NEW` to get the updated value.
