### ISSUE TITLE
no httpDownloadProgress event fired when calling getObject

### ISSUE THREAD

**Issue by yawhide** [aws/aws-sdk-js#805]
using `aws-sdk 2.2.17`
I am calling the following:
```
var file = fs.createWriteStream(filePath);
var s3 = new aws.S3(credentials);
var download = s3.getObject({
   Bucket: bucket,
   Key: key,
})
.on('httpDownloadProgress', function (evt) {
   console.log('progress:', evt);
})
.on('error', cb)
.createReadStream()
.pipe(file);
```
and I am not getting any console.logs.
My file downloads fine, just no progress updates.

Anything look wacky?
thanks

EDIT: i should add, that the filePath is to a file that already exists

**Comment by AdityaManohar** [comment]
@yawhide [`AWS.Request.createReadStream()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#createReadStream-property) returns an instance of [`stream.PassThrough()`](https://nodejs.org/api/stream.html#stream_class_stream_passthrough).

The returned stream will only emit stream events, i.e: `data`, `error`, `end` and so on. The `httpDownloadProgress` event is specific to the `AWS.Request` object and will not be emitted when you return a readable stream. This is mainly to preserve the [`stream.Readable`](https://nodejs.org/api/stream.html#stream_class_stream_readable) interface.

It is very easy to simulate your own progress event by listening to the `data` event emitted by the stream. Here is some sample code to do this:

```javascript
var totalBytes;
var s3 = new AWS.S3();
var req = s3.getObject(params);

req.on('httpHeaders', function(status, headers, response) {
  totalBytes = parseInt(headers['content-length']);
});

var stream = req.createReadStream();

stream.on('data', function(chunk) {
  console.log((chunk.length / totalBytes) * 100);
});

stream.pipe(writeableStream);
```

Hope this helps!

**Comment by yawhide** [comment]
ah never even thought of that. let me try that out. thanks

**Comment by yawhide** [comment]
so yes, it works now. thank you
