### ISSUE TITLE
`null` can't be `false`

### ISSUE THREAD

**Issue by chrisguttandin** [aws/aws-sdk-js#810]
I discovered a minor bug in the docs. I am not sure where to fix it, that's why I created this issue here. I hope that's okay.

The docs for the [Dynamo DB Service](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html) indicate in several places that a property of type `NULL` can be either true or false. Since I couldn't think of any use case for  `NULL` to be false, I tried to manually insert an item in one of my tables via the console. The console does not allow values of type `NULL` to be false. That's why I think it is not allowed in general and should not be mentioned in the docs as an option.

Please correct me if I'm wrong.

**Comment by chrisradek** [comment]
@chrisguttandin 
Thanks for the feedback.  You're correct, only `true` is an accepted value for a property type of `NULL`. I'll work on correcting the docs to specify only `true` is an accepted value.
