### ISSUE TITLE
Multipart Managed Upload encoded Location

### ISSUE THREAD

**Issue by fyockm** [aws/aws-sdk-js#811]
When using the Managed Uploader on a large file (>5M), the `Location` returned in the data of the callback is incorrect, with `%2F` instead of a `/`. Using the Managed Uploaded with a file smaller than 5M does not yield the same result- the Location is set as expected.

Here's some code to illustrate:
```
var key = filename;

s3.upload({
    Bucket: 'bucket',
    Key: req.user.id + '/' + key,
    Body: req
}, function(err, data) {
    if (err) {
        return res.status(err.statusCode).end(err.message);
    }

    console.log('data:', data);

    // Fix the S3 Multipart Upload bug
    data.Location = data.Location.replace('%2F', '/');

    res.set(data);
    res.end();
});
```

For the large file, we get the following output. Notice the `%2F` in the `Location`.
```
data: { Location: 'https://s3.amazonaws.com/bucket/55159b8b109ea8d1653eb5b1%2F1largeImage.jpg',
  Bucket: 'bucket',
  Key: '55159b8b109ea8d1653eb5b1/1largeImage.jpg',
  ETag: '"96c30c200150682f407619e5046505d8-2"' }
```

The same code run for a smaller image yields this output:
```
data: { Location: 'https://s3.amazonaws.com/bucket/55159b8b109ea8d1653eb5b1/1testImage.jpg' }
```

**Comment by chrisradek** [comment]
@fyockm 
What are you doing with the `Location`? Both URLs should be valid and return the same object from S3. This wouldn't be the case if you were using another SDK function like `getObject`, but in that scenario you'd likely use the `Key` instead.

**Comment by fyockm** [comment]
We are using `Location` to store the full URL for the object, so that it's accessible later by whatever method is required for the given client. That might be directly via an html `<img>` tag, or through `getObject`. In case of the latter, we have to parse out the Bucket and Key, which becomes more difficult with inconsistent URLs.

As you can see from my code, I can easily fix the encoding problem with the `Location` for a multipart file. 

1. I thought this could trip up some other dev in the future and wanted it to be documented
2. I believe the `Location` url should be consistent, regardless of filesize

To my understanding, the whole point of the `s3.upload` function is to make it easier on devs by hiding the underlying `getObject` vs `createMultipartUpload` craziness. Unexpected results like this only add to the frustration.

**Comment by chrisradek** [comment]
@fyockm 
Would it help if the `data` returned by `s3.upload` always included `Bucket` and `Key`?

The main issue with automatically decoding the `Location` url by default is backwards compatibility. We don't want to break someone who has already written code around the way it currently works. Ideally, the `Key` and `Bucket` for an object shouldn't have to be parsed from `Location` either.

Thanks for the feedback so far, I agree that there is some room for improvement here.

**Comment by fyockm** [comment]
@chrisradek While it won't solve my particular problem, I'm sure it would help others if `Bucket` and `Key` were always returned from `upload`. And, I think that's probably a fair compromise for the time being. 

Perhaps you could auto decode `Location` in the next major release?

**Comment by igrayson** [comment]
For others looking for a workaround,

```javascript
data.Location = data.Location.replace('%2F', '/');
```

is more reliably done:
```javascript
data.Location = data.Location.replace(/%2F/g, '/');
```

**Comment by fyockm** [comment]
Please explain why more reliable? just because of the `g` global flag?

**Comment by igrayson** [comment]
Yes.

**Comment by LiuJoyceC** [comment]
`.upload()` should now return both `Key` and `Bucket` regardless of file size so customers do not need to parse them out of `Location`.

**Comment by igrayson** [comment]
@LiuJoyceC when `Location` is present, will it consistently contain `%2F` instead of `/`?

**Comment by LiuJoyceC** [comment]
@igrayson 
Unfortunately, changing `Location` would be a breaking change, as there are customers who currently depend on the current format. The PR eliminates the need to parse the `Key` and `Bucket` out of `Location`, as discussed above. `Location` will be consistent for small and large file uploads in future major versions. Thanks.
