### ISSUE TITLE
AWS SDK JS with ElastiCache

### ISSUE THREAD

**Issue by ramonck** [aws/aws-sdk-js#812]
Srs.,

I would like to know if you have any examples of utilizing ElastiCache with AWS JS SDK?

I'm using memcached.

Best Regards,

**Comment by chrisradek** [comment]
@ramonck 
We don't have specific examples for utilizing ElastiCache with the JavaScript SDK. However, the API is documented here: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ElastiCache.html

You can also visit the Amazon ElastiCache user guide for more information specific to this service:
http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/WhatIs.html

Did you have a question about a specific operation or scenario?

**Comment by chrisradek** [comment]
Closing this issue for now, but feel free to comment or open a new issue if you have a specific question about the SDK.
