### ISSUE TITLE
APIGateway getSdk data.body is not a buffer

### ISSUE THREAD

**Issue by SamVerschueren** [aws/aws-sdk-js#815]
Hi

I am using the `apigateway.getSdk` method to download the zip file of my SDK. This way I can integrate that with my gulpfile to make sure I always have the latest version.

The documentation can be found [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#getSdk-property).

It states that the callback returns a `data` object with the property `body`, which is a `String`, `Buffer`, etc. So I tried that call and write the `data.body` directly as zip file to my filesystem.

```js
apigateway.getSdk(params, function (err, data) {
    if(err) {
        // handle error
        return;
    }

    fs.writeFileSync('apigateway.zip', data.body);
});
```

It didn't work as turned out, `data.body` is not a `Buffer`, but a `string`. So I tried to convert it into a buffer with `new Buffer(data.body)` and tried every possible encoding argument there is. Nothing worked for me.

But, what did work was the following.

```js
var request = apigateway.getSdk(params, function (err, data) {
    if(err) {
        // handle error
        return;
    }

    fs.writeFileSync('apigateway.zip', request.response.httpResponse.body);
});
```

So it turns out, the property in the `httpResponse` is a `Buffer` which can be written directly as zip file.

Is this an issue in the library or should I convert the `data.body` property body with a different function?

Kind regards,
Sam

**Comment by chrisradek** [comment]
@SamVerschueren 
The SDK is automatically converting `body` into a utf8 string due to the way it is modeled for that operation.

Currently there are 2 ways to work around this. 

The 1st, you've already discovered, by accessing `this.httpResponse.body` within the callback.
The 2nd would be to use streams instead.  Here's an example of how the code may look:
```javascript
var file = fs.createWriteStream('apigateway.zip');
file.on('close', function(){
  console.log('Finished downloading SDK');
});
apigateway.getSdk(params).createReadStream().on('error', function(err) {
  console.log(err);
}).pipe(file);
```
Let me know if this helps!

**Comment by SamVerschueren** [comment]
@chrisradek Alright, thanks for the information. So at the moment, `result.body` is not very useful? 

Thanks for the example with streams, might come in handy :).

**Comment by chrisradek** [comment]
@SamVerschueren 
At the moment, you should get a UTF-8 string representing the SDK when accessing `data.body`. That said, I also can't write a working zip using the contents of `data.body` directly. I'd like to update it so using streams, or accessing the response directly, aren't necessary.

**Comment by SamVerschueren** [comment]
Yes I think it would be nice if `data.body` was the same (Buffer) object as the `httpResponse` object. Thanks for looking into this.
