### ISSUE TITLE
Duplicate requests for Kinesis Firehose putRecord?

### ISSUE THREAD

**Issue by ee99ee** [aws/aws-sdk-js#816]
For each request I make to putRecord, I end up seeing my callback executed two times with two different request IDs and two sets of data ending up in Kinesis. I think this is a bug?

```javascript
// This gets logged once...
console.log('Send data');
firehose = new aws.Firehose({
  apiVersion: '2015-08-04',
  accessKeyId: config.kinesis.key,
  secretAccessKey: config.kinesis.secret,
  region: config.kinesis.region
})

kinesisData = {
  DeliveryStreamName: config.kinesis.streamName,
  Record: { Data: buffer }
}

firehose.putRecord(kinesisData, function (err, data) {
  // This gets called twice...
  console.log('Callback...')
})
```

**Comment by chrisradek** [comment]
@ee99ee 
Is this the exact code you're testing with? What version of the SDK/node are you using? When I run your code using version 2.2.17 of the SDK and node 0.12.7, I only see the callback trigger once.

**Comment by ee99ee** [comment]
Sorry, my error. Closing.
