### ISSUE TITLE
Cannot add x-amz-server-side-encryption header to S3 managed upload large file

### ISSUE THREAD

**Issue by kaurranjeet12** [aws/aws-sdk-js#819]
Hi, I am using AWS javascript sdk to upload file to S3. I am using managed upload which upload file in parts if the size is bigger.

So, the issue is, If the file size is bigger I am not able to add ServerSideEncryption: 'AES256' header.

Its throwing following error:
"x-amz-server-side-encryption header is not supported for this operation"

**Comment by chrisradek** [comment]
@kaurranjeet12 
Can you tell me what version of the SDK you are using, and if it is within nodejs or the browser?

Using version 2.2.17 of the SDK in node with a large (~240 MB) file, I am able to set `ServerSideEncryption` using code similar to the following:

```javascript
var s3 = new AWS.S3();
var params = {
  Bucket: 'bucket',
  Key: 'test',
  Body: stream,
  ServerSideEncryption: 'AES256'
};
var uploader = new AWS.S3.ManagedUpload({params: params});
uploader.send(function(err, data) {
  console.log(data);
}
```

**Comment by kaurranjeet12** [comment]
Thanks for your reply. I was using aws sdk 2.2.12 and doing direct upload from browser using javascript.
After upgrading to latest version 2.2.17, it works fine.

**Comment by chrisradek** [comment]
@kaurranjeet12 
Glad to hear it!
