### ISSUE TITLE
Uploading to s3 with metadata throws SignatureDoesNotMatch (sometimes)

### ISSUE THREAD

**Issue by ar1hur** [aws/aws-sdk-js#820]
hi, i have some trouble with uploading files to s3, especially if I set the "metadata" parameter. If it's set, it does not work in some situations which i can`t identify. 
The region I am using is 'eu-central-1'

```js
var params = {
    Key: 'te/test/b5117457679bd00231925a3030a2aad07b69316d.jpg',
    StorageClass: 'STANDARD_IA',
    Metadata: { filename: 'groß.jpg' },
    Body: <Buffer ff d8 ... >,
    ContentType: 'image/jpeg' 
}
s3.putObject(params, ....);
```

throws the following error:
```js
[SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.]
     message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
     code: 'SignatureDoesNotMatch',
     region: null,
     time: Tue Dec 01 2015 09:13:09 GMT+0000 (UTC),
     statusCode: 403,
     retryable: false,
     retryDelay: 30
```
Any suggestions ?

**Comment by ar1hur** [comment]
ahh, seems like german characters are making trouble here...

**Comment by chrisradek** [comment]
@ar1hur 
According to the S3 documentation for user-defined metadata:
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
"Each name, value pair must conform to US-ASCII when using REST..."
If you're in the browser, using a POST based upload would allow for UTF-8 encoding for the metadata.

eu-central-1 uses Signature Version 4 signing when performing operations. As part of sigv4 signing, the headers are used when creating a signature. Likely what is happening is S3 isn't reading the metadata value correctly when non ascii characters are supplied, and so generates a different signature on their end than what we supply from the SDK. Unfortunately this is a limitation in the service for now.

Let me know if this information helps clarify the behavior you're seeing!

**Comment by ar1hur** [comment]
@chrisradek 
Thank you for your fast feedback! I didnt know that.. Your mentioned article should be linked on the api docs page to specifiy this kind of parameter: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property

Best Regards
Arthur
