### ISSUE TITLE
AWS::DynamoDb::BatchWriteItem() throws error

### ISSUE THREAD

**Issue by Chatatata** [aws/aws-sdk-js#821]
I've written a recursive function in order to make batch requests with 25 items each (which seems the maximum):

    function multipleBatchWrite(rows, quantity, callback) {
        var AWSRequestParams = {
            RequestItems: {
                Something: []
            },
        }, deleted
        
        if (rows.length > quantity) {
            deleted = rows.splice(0, quantity)
        } else {
            deleted = rows;
        }
        
        while (deleted.length) {
            var request = {
                PutRequest: {
                    Item: null,
                },
            }
            
            request.PutRequest.Item = deleted.pop()
            AWSRequestParams.RequestItems.Something.push(request)
        }
        
        console.log(AWSRequestParams)
        
        dynamodb.batchWriteItem(AWSRequestParams, function (err, data) {
            if (err) {                
                callback(err)
            } else {
                if (rows.length) {
                    multipleBatchWrite(rows, quantity, callback)
                } else {
                    console.log(string + ", write completed.")
                    
                    callback(null)
                }
            }
        })
    }

However function `BatchWriteItem()` throws error:

    /Users/Instigater/Documents/Hippo/HippoWebServer/node_modules/aws-sdk/lib/request.js:30
            throw err;
            ^
    
    ReferenceError: string is not defined
        at Response.<anonymous> (/Users/Instigater/Documents/Hippo/HippoWebServer/dynamodb/sync.js:550:33)
        at Request.<anonymous> (/Users/Instigater/Documents/Hippo/HippoWebServer/node_modules/aws-sdk/lib/request.js:353:18)
        at Request.callListeners (/Users/Instigater/Documents/Hippo/HippoWebServer/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
        at Request.emit (/Users/Instigater/Documents/Hippo/HippoWebServer/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
        at Request.emit (/Users/Instigater/Documents/Hippo/HippoWebServer/node_modules/aws-sdk/lib/request.js:595:14)
        at Request.transition (/Users/Instigater/Documents/Hippo/HippoWebServer/node_modules/aws-sdk/lib/request.js:21:10)
        at AcceptorStateMachine.runTo (/Users/Instigater/Documents/Hippo/HippoWebServer/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /Users/Instigater/Documents/Hippo/HippoWebServer/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/Users/Instigater/Documents/Hippo/HippoWebServer/node_modules/aws-sdk/lib/request.js:37:9)
        at Request.<anonymous> (/Users/Instigater/Documents/Hippo/HippoWebServer/node_modules/aws-sdk/lib/request.js:597:12)

I'm triggering this function repeatedly with different parameters, execution is expected to be serial with `async.eachSeries`.

Could you reproduce? I will try to do my best if you want anything.

As I've read your code of contribution, I realized I forgot to tell my specs:
I reinstalled the SDK with `npm install aws-sdk`.
I'm using node.js' latest stable version, v5.1.0.
The OS currently running is OS X El Capitan 10.11.1.
I have `request`, `hapi` and `htmlparser2` packages installed via npm in my application; it's also worth noting it's been a month since I began using AWS and haven't had a problem until now.

**Comment by chrisradek** [comment]
@Instigater 
The error indicates that `string` is undefined when you attempt to log it, and I don't see it defined in your example.  If you remove `string` or replace it with an actual string, do you still see this issue?

**Comment by Instigater** [comment]
@chrisradek 
As you see in the error, the error is thrown from a `aws-sdk` library file, `request.js`.

Also I couldn't understand what you meant with *logging*.

**Comment by chrisradek** [comment]
@Chatatata 
In your code, you have the following line:
`console.log(string + ", write completed.")`
`string` is being logged, but is not defined.

That `string` is being referenced in the error.  `request.js` is in the call stack because the error is in the callback that is called once the dynamodb response is returned, and `request.js` is catching it.

If you replace `string` with an actual string, or remove it entirely, do you still see an error?

**Comment by Chatatata** [comment]
The error was probably unrelated to `AWS-SDK`, somehow its solved (`string` was global var).

Thank you, anyways.
