### ISSUE TITLE
socket hang up on s3.listObjets using node 0.10.x

### ISSUE THREAD

**Issue by marcopiraccini** [aws/aws-sdk-js#822]
Hi, 
I have this very  simple code:

```
  var s3 = new AWS.S3(config)
  var aw = s3.listObjects(params, function (err, data) {
    // Do something
  })
````
This works with node >= 0.12 (tested with 0.12.4, 4.0.0, 5.1.0) but with node 0.10.x (tested with 0.10.38 and 0.10.40) raise this error:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1473:15)
    at CleartextStream.socketCloseListener (http.js:1523:23)
    at CleartextStream.emit (events.js:117:20)
    at tls.js:694:10
    at process._tickDomainCallback (node.js:492:13)
```
Since I have to use node 0.10.x...there's a workaround for that?

**Comment by chrisradek** [comment]
@marcopiraccini 
What version of the SDK are you using?

Does the callback function supplied to `listObjects` ever get called?

I ran code based off what you've supplied in nodejs version 0.10.40 and haven't seen an issue yet.  That error might be indicating some communication issue between your server and S3. I'm not sure how much it will help, but can you turn on logging to see if your requests are going through?  Just include `logger: console` in the config you pass into the `AWS.S3` constructor.

**Comment by marcopiraccini** [comment]
Tried with 2.1.36 and 2.2.19 (the last one). I agree that it can be some communication issue, but if so it depends on node version, since with >=0.12.x it works perfectly.  And I don't see more info on the console running with:

```
config.logger = console
var s3 = new AWS.S3(config)
  s3.listObjects(params, function (err, data) {
(...)
})
```

**Comment by chrisradek** [comment]
@marcopiraccini 
Are you only having issues with `S3`, or can you replicate issues with other services as well? Is there any other code you're running alongside the sample you've provided?

**Comment by marcopiraccini** [comment]
Good point. I have a code that purge a SQS queue and I have the very same problem. 
The code I've provided is executed in a tape test, I simply run it using `node mytest`.  It's something like: 
```
var test = require('tape')
(...)
function tests (config) {
  test('Cleanup S3 bucket', function (t) {
	    var s3 = new AWS.S3(config)
	    s3.listObjects(params, function (err, data) {
	})
  })
}

```

**Comment by chrisradek** [comment]
This is sounding more like a connection issue that manifests when using node 0.10.x instead of something wrong with the SDK. Is there anymore information you can give about the environment node is running on?

**Comment by marcopiraccini** [comment]
Ok, found the issue. In the tape test, there's one condition when I use `nock` (not for AWS, but for mocking another service). This happens when:
- Nock is required before AWS. Just required, no further config needed :)
- Node 0.10.x

That's weird but definitely is not a aws-sdk issue. Closing.
