### ISSUE TITLE
Lambda invoke with 'LogType = Tail' doesn't return LogResult

### ISSUE THREAD

**Issue by mgoria** [aws/aws-sdk-js#825]
Hi,

I'm trying to receive LogResults when invoking a lambda function as it is described [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property), by setting LogType = Tail, but it seems that returned response data contains only "StatusCode" and "Payload" properties and doesn't contain "LogResult" that should be an base64-encoded string.

``` javascript
var params = {
  FunctionName: '<my_lambda_func_name>',
  InvocationType: 'RequestResponse',
  LogType: 'Tail',
  Payload: {foo: 'bar'}
};

lambda.invoke(params, function(err, data) {
  console.log(data);
/*
{
"Payload": {},
"StatusCode": 200
}
*/
});
```

Thanks,
Marcel

**Comment by chrisradek** [comment]
@mgoria 
What version of the SDK are you testing with? Using the latest version and your example, I'm also seeing `LogResult` as part of the `data` object.

Inside your callback, can you also see if the `x-amz-log-result` header is being returned? You can access the headers within your callback by looking at `this.httpResponse.headers`.

**Comment by mgoria** [comment]
@chrisradek 
I'm using aws-sdk version 2.2.20 and '2015-03-31' lambda version.

Regarding ```x-amz-log-result``` header, it's not being returned by ```this.httpResponse.headers```:

<img width="1277" alt="screen shot 2015-12-03 at 10 10 00 pm" src="https://cloud.githubusercontent.com/assets/2959952/11572595/c1ba878e-9a0a-11e5-8b3f-cdf374880468.png">


I've noticed that it is returned in browser response headers (see below screen shot), but this doesn't work for our use case unfortunately. It'll be nice to have it in callback data or in httpResponse.headers.

<img width="1278" alt="screen shot 2015-12-03 at 10 06 55 pm" src="https://cloud.githubusercontent.com/assets/2959952/11572656/056e3aac-9a0b-11e5-9259-b9e16df6ae03.png">

**Comment by chrisradek** [comment]
@mgoria 
Thanks for the information so far. 

Is your first example in your last post from Node? Can you also verify what request headers are being sent? You could check it the same way as response using `this.request.httpRequest.headers`. Specifically looking for `X-Amz-Log-Type` and `X-Amz-Invocation-Type`.

**Comment by chrisradek** [comment]
@mgoria 
Just to be sure, are you testing with the example you provided above?

This is the code I'm running in node (with an actual FunctionName) and I see the LogResult in the data object:

```javascript
var AWS = require('aws-sdk');

var lambda = new AWS.Lambda();

var params = {
    FunctionName: '<FUNCTION_NAME>',
    InvocationType: 'RequestResponse',
    LogType: 'Tail',
    Payload: JSON.stringify({
        foo: 'bar'
    })
};

lambda.invoke(params, function(err, data) {
    if (err) {
        console.log(err);
    } else {
        console.log(data);
    }
});

```

Output:
```javascript
{ StatusCode: 200,
  LogResult: '...',
  Payload: '...' }
```

**Comment by mgoria** [comment]
@chrisradek 

I'm calling lambda from browser, you can try it [here](http://deep.dev.public.a498a19d.s3-website-us-west-2.amazonaws.com/), and check out the browser console (I'm logging lambda 'Response' object).

**Comment by mgoria** [comment]
I've also checked ```this.request.httpRequest.headers``` and ```X-Amz-Log-Type``` and ```X-Amz-Invocation-Type``` are being sent:

<img width="1280" alt="screen shot 2015-12-03 at 11 46 29 pm" src="https://cloud.githubusercontent.com/assets/2959952/11575167/4fd5942a-9a18-11e5-8c66-f1ce46249e5e.png">

**Comment by chrisradek** [comment]
I believe this may be an issue with how the deep-framework is parsing the response from the SDK.

@mgoria 
I believe this issue may be with how the deep-framework is parsing the responses from Lambda.
I took a look at the following source code:
https://github.com/MitocGroup/deep-framework/blob/9b6b13176a6cc2f8d5ad2c7d6e62074c7ecbc8b5/src/deep-resource/lib/Resource/LambdaResponse.js

It looks like StatusCode and Payload are being extracted from the response's rawData. I'm assuming that `rawData` contains the data that the AWS SDK would return, though I haven't tested it myself. `LogResult` gets sent back to the AWS SDK as a header, and isn't part of the Payload object. The SDK knows to look for the header and add `LogResult` to the `data` object that gets returned. 

Have you tried the above code sample outside of another framework?

**Comment by mgoria** [comment]
@chrisradek 
Nope, but let me try this, I'll get back to you once I have an working sample without deep-framework.

Btw, have you inspected the console.log-ed Response object, I'm asking because it is raw lambda Response, not parsed by deep-framework, and it seems it doesn't have ```LogResult``` property.

This way I'm console logging lambda response:

```
this._lambda = new AWS.Lambda(options);

this._lambda.invoke(invocationParameters, function (error, data) {

  console.log("this._lambda.invoke - resposne - ", this);

  callback(new LambdaResponse(_this, data, error));
});
```

**Comment by chrisradek** [comment]
@mgoria 
Apologies, I was testing with node before you posted your last update. I actually am seeing an issue in the browser as well. I'll keep investigating.

**Comment by chrisradek** [comment]
@mgoria 
The issue lies in what headers the service exposes through the access-control-expose-headers response header. This explains why it works in node and not in the browser. I'll get in touch with the service team and report back here once I hear back.

**Comment by mgoria** [comment]
@chrisradek 
Ok, Thank you! Looking forward.

**Comment by eistrati** [comment]
@chrisradek We were wondering if there is any resolution to this issue? Please let us know and thanks in advance for your effort.

**Comment by chrisradek** [comment]
@eistrati 
I'll bring this up again with the service team. As far as I know they haven't made the necessary updates yet.

**Comment by chrisradek** [comment]
@eistrati 
Actually, looks like the work was completed a month ago! I just tested using the latest version of the SDK and LogResult is being returned.
