### ISSUE TITLE
Broken link in docs: https://github.com/aws/aws-sdk-js/blob/master/doc-src/guide/index.md

### ISSUE THREAD

**Issue by michaelBenin** [aws/aws-sdk-js#826]
https://github.com/aws/aws-sdk-js/blob/master/doc-src/guide/index.md 

Link: API reference documentation
Address: https://github.com/aws/aws-sdk-js/blob/master/AWSJavaScriptSDK/latest

**Comment by chrisradek** [comment]
Thanks for catching that @michaelBenin 

I'll get that link corrected.

**Comment by chrisradek** [comment]
This has been fixed in version 2.2.21 of the SDK.
