### ISSUE TITLE
Region Frankfurt: Please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by ataraxus** [aws/aws-sdk-js#829]
Hey using LoopBack which itself uses pkgcloud which in the end uses aws-sdk. If I access my S3 Bucket in Frankfurt I get: "Failed InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256." 
How do I use the aws-sdk with this region? 

Here is the related issue on LoopBacks site: https://github.com/strongloop/loopback-component-storage/issues/101

On this lib they somehow fixed it: https://github.com/s3tools/s3cmd/issues/402

**Comment by chrisradek** [comment]
@ataraxus 
I can't comment specifically on what the issue might be with the 3rd party frameworks. However, my best guess based on the error message you're receiving is that they don't handle SigV4 signing.

There are two different signature versions that are supported by S3 in various regions. Some regions only support the newest (v4) signing.  There's a list of regions and what signature versions they support here: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

If possible, I'd recommend trying the aws-sdk for interacting with S3.  We have API documentation on how to use the SDK to interact with S3 here: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html
We also have a Getting Started guide: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-intro.html

Let me know if you have specific questions or issues using the AWS SDK!

**Comment by ataraxus** [comment]
Hey @chrisradek, 

after reading the original documentation I got my error. If you don't specify a region the aws-sdk will use a default region 'us-east-1' which is not compatible with my target region in Frankfurt: 'eu-central-1' after having a look where to set the appropriate region in the loopback sdk i got everything working. Ticket can be closed now. 

Thanks again.

**Comment by ataraxus** [comment]
Just for folks ending up on this page, here is the site to look up your region: https://docs.aws.amazon.com/general/latest/gr/rande.html
