### ISSUE TITLE
DynamoDB.DocumentClient should support empty string properties

### ISSUE THREAD

**Issue by thoean** [aws/aws-sdk-js#833]
When the object contains a property with an empty string, it results in an exception instead of for example silently removing this property or replacing with a user-provided constant.

To be specific, the following example request:

```
var params = {
    TableName: 'my-test-table',
    Item: { Key:"foo", MyData: ""}
};
```

Results in the following error on DynamoDB:

```
[AWS dynamodb 400 0.588s 0 retries] putItem({ TableName: 'my-test-table',
  Item: { Key: { S: 'foo' }, MyData: { S: '' } } })
```

Which is returned from the DocumentClient as:

```
Unable to store request. Error was {
  "message": "One or more parameter values were invalid: An AttributeValue may not contain an empty string",
  "code": "ValidationException",
  "time": "2015-12-10T09:19:17.204Z",
  "statusCode": 400,
  "retryable": false,
  "retryDelay": 0
}
```

**Comment by chrisradek** [comment]
@thoean 
What you're seeing is currently documented behavior:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#putItem-property
`String and Binary type attributes must have lengths greater than zero. Set type attributes cannot be empty. Requests with empty values will be rejected with a ValidationException exception.`

This could be something we support in the future by having something like an `ignoreEmptyStrings` configuration option for the `DocumentClient` that was opt in.

**Comment by thoean** [comment]
Your proposal sounds great and would solve my use case.

Whether opt-in or standard behavior depends how much DocumentClient is a simplification over DynamoDB, not only in simplification of providing the necessary parameters, but also trying to do the right thing for the client. I think this case has arguments in both directions, so opt-in to maintain compatibility to its current version makes sense.

**Comment by RedaBenh** [comment]
+1

**Comment by brcline** [comment]
+1

**Comment by clicktravel-jaroslav** [comment]
+1

**Comment by jeffbakerexpedia** [comment]
+1

**Comment by hammadmlk** [comment]
+1

**Comment by jesucarr** [comment]
+1

**Comment by chandan449** [comment]
+1

**Comment by simoami** [comment]
+1

**Comment by itaykahana** [comment]
+1

**Comment by bo01ean** [comment]
I worked around this by just wiping out the empty keys from the object:
    
```javascript
    var Item = { Key:"foo", MyData: "", Item: { Key:"foo", MyData: "", Item: { Key:"foo", MyData: ""}}};
    function removeEmptyKeys(obj) {
      for (var prop in obj) {
        switch (typeof obj[prop]) {
          case 'object':
            removeEmptyKeys(obj[prop]);
            break;
          case 'string':
              if(obj[prop] === '') {
                delete obj[prop];
              }
            break;
        }
      }
      return obj;
    } 
    removeEmptyKeys(Item);
/*
{
  "Key": "foo",
  "Item": {
    "Key": "foo",
    "Item": {
      "Key": "foo"
    }
  }
}
*/

**Comment by pzimny** [comment]
+1

**Comment by milanbrahmbhatt** [comment]
+1

**Comment by joshwils82** [comment]
+1

**Comment by manikandants** [comment]
Do we have support for empty strings in the latest version? If not, any timeline for this feature to be available? I have a specific case where I am persisting the payment response with hash. If I remove the keys with empty strings, the hash generation would fail later.

**Comment by LiuJoyceC** [comment]
Hi @manikandants 

Unfortunately, we can't share a timeline for this, but thanks for everyone who has given a +1 or voiced a concern about this feature request, as it helps us prioritize. I will look into this as soon as I can.

**Comment by John2496** [comment]
+1

**Comment by ossie1971** [comment]
+1

**Comment by lindell** [comment]
+1

**Comment by joegesualdo** [comment]
+1

**Comment by RhysC** [comment]
+1

**Comment by bradledford** [comment]
+1

**Comment by pavei** [comment]
+1

**Comment by dustinbolton** [comment]
+1  -- This is the most commented feature request and a real pain point as it is now. Please consider this feature.

**Comment by amitatgit** [comment]
+1

**Comment by jppellerin** [comment]
+1

**Comment by cstavro** [comment]
+1

**Comment by kienpham2000** [comment]
+1

**Comment by iSkore** [comment]
+1

**Comment by CJNE** [comment]
+1

**Comment by tejasmanohar** [comment]
+1

**Comment by Rajkumar55** [comment]
+1

**Comment by danieldelouya** [comment]
+1

**Comment by MindTailor** [comment]
+1

**Comment by seanchann** [comment]
+1

**Comment by superandrew** [comment]
+1

**Comment by rtrompier** [comment]
+1

**Comment by MindTailor** [comment]
+1

**Comment by whiteswift** [comment]
+1

**Comment by csabakollar** [comment]
+1

**Comment by iSkore** [comment]
```
function cleanObj( o ) {
	if( o && o === o && typeof o === "string" ) return o;
	else if( o && o === o && typeof o === "number" ) return o;
	else if( o && o === o && Array.isArray( o ) ) {
		let x = [], i = -1, l = o.length, r = 0;
		while( ++i < l ) if( o[ i ] ) x[ r++ ] = cleanObj( o[ i ] );
		return x;
	} else if( o && o === o && typeof o === "object" ) {
		for( const k in o ) o[ k ] ? o[ k ] = cleanObj( o[ k ] ) : delete o[ k ];
		return o;
	}
	return o;
}
```

**Comment by DianaIonita** [comment]
+1

**Comment by Imran99** [comment]
+1

**Comment by jamie-reddell** [comment]
+1

**Comment by khoi-nguyen-2359** [comment]
+1

**Comment by sasanala** [comment]
+1

**Comment by jbuddha** [comment]
+1

**Comment by Jorenm** [comment]
+1

**Comment by alistairg** [comment]
+1

**Comment by kellenp** [comment]
+1

**Comment by asantibanez** [comment]
+1

**Comment by cbarcenas** [comment]
+1

**Comment by MerryOscar** [comment]
+1

**Comment by nfmelendez** [comment]
+1

**Comment by chaliy** [comment]
+1, and at least be more specific in error message.

**Comment by bwestergard** [comment]
+1

**Comment by jcready** [comment]
@LiuJoyceC could you disclose whether this is something that is actually being worked on or even discussed internally? I only ask because [this bug seems to be almost a half-decade old](https://forums.aws.amazon.com/thread.jspa?threadID=90137). So is this something that actually *could* be fixed but hasn't, or is it a fundamental limitation of the DynamoDB internal structure?

**Comment by pzimny** [comment]
Glad to see something is being done, but that's really just trading one problem for a new one.

**Comment by enlightendata** [comment]
+1

**Comment by brandonmbanks** [comment]
+1

**Comment by jeskew** [comment]
@brandonmbanks Converting empty values to `null` is now an opt-in feature of the document client; you can pass a boolean `convertEmptyValues` option to the document client constructor to have it do so. I'll open a PR to improve the documentation of this feature.

**Comment by svoeller99** [comment]
+1

**Comment by njgrisafi** [comment]
+1

**Comment by clearly** [comment]
+1

**Comment by pixelfuture** [comment]
+1

**Comment by ntrivix** [comment]
+1

**Comment by ruleechen** [comment]
+1

**Comment by elioncho** [comment]
+1

**Comment by yipcma** [comment]
this is much needed, please...

**Comment by jeskew** [comment]
@yipcma As noted [above](https://github.com/aws/aws-sdk-js/issues/833#issuecomment-274616983), this has been implemented as an opt-in feature. Set the `convertEmptyValues` constructor option to `true` when creating a document client.

**Comment by jcready** [comment]
@jeskew I think what people want is the ability to store and retrieve an empty string. All this provides is a way to convert empty strings to `null` which really isn't the same thing.

**Comment by jcready** [comment]
People want to be able to store JSON documents in DynamoDB but right now we only have two options: 1) store the full JSON as a string in a single column, or 2) use `convertEmptyValues` and accept that you will not be able to use 100% of the JSON spec without data loss.

**Comment by jeskew** [comment]
Unfortunately, that isn't something that can be handled client-side without knowledge of the expected data schema.

If the SDK included a higher-level abstraction that knew which types certain fields were expected to be (like the AWS SDK for Java's [DynamoDB Data Mapper](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.html) or the Ruby [`Aws::Record`](https://github.com/aws/aws-sdk-ruby-record)), then the client could convert a `null` value to an empty string or empty buffer as appropriate. That's a reasonable feature request, but it's not something that could be built into the document client without breaking changes to its interface.

**Comment by lamon** [comment]
+1

**Comment by jeremysuriel** [comment]
+1

**Comment by jstradli** [comment]
+1

**Comment by ashikkalavadiya** [comment]
+1

**Comment by rafiek** [comment]
+1000

**Comment by superandrew** [comment]
ive never seen a issue desired like this one. Any roadmap to implement the possibility to store an empty string in dynamodb? should everyone move to another database? 🙏🏼

**Comment by jeskew** [comment]
@superandrew We've implemented opt-in, client-side support for this feature via the convertEmptyValues flag as discussed above.

**Comment by superandrew** [comment]
in my opinion, this is more of a client side patch for something that needs to be done on the dynamodb side. And, more importantly, and as someone else said before me, null is no replacement for an empty string. So if more and more people keeps asking for a more complete fix, I wouldn't call this issue "closed". But, of course, still my opinion.

**Comment by nfmelendez** [comment]
2 years with this, come on people, LET IT GO!

**Comment by jeskew** [comment]
Just wanted to remind everyone to please keep the discussion constructive.

@superandrew I understand what you mean, but the SDK is a client-side library, and the DynamoDB team does not monitor the issue queue of any AWS SDK. For a server-side fix, I recommend that you reach out directly to the DynamoDB team via [their AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=131) or via a support ticket.

**Comment by ashikkalavadiya** [comment]
@superandrew you can accelerate this type of request to AWS Team where plenty of people is facing issue with kind of problems! Though its almost 2 years, Developer finds a way on their(client) side as well!! LET IT GO!

**Comment by jcready** [comment]
@jeskew [this bug is almost half a decade old](https://forums.aws.amazon.com/thread.jspa?threadID=90137). No one seems to be getting satisfaction over there so they are voicing their concerns here. Perhaps AWS could open-source DynamoDB and put the code up on GitHub so we could create an issue there and/or make a PR which allows empty strings to be stored.

**Comment by tsmiser** [comment]
+1

**Comment by worsnupd** [comment]
+1

**Comment by roderyc** [comment]
+1

**Comment by amistein** [comment]
+1

**Comment by emaildanwilson** [comment]
Slight change to the code suggested by @bo01ean so that it tokenizes and detokenizes the empty string. It works for me but it's annoying that I need to do this to preserve the original JSON when using dynamodb.

```
const token = '~&*^AWSSTILLHASNOTFIXEDTHIS!!!~&*^';

const tokenizeEmptyStringElements = function (obj) {
  for (var prop in obj) {
    if (typeof obj[prop] === 'object') {// dive deeper in
      tokenizeEmptyStringElements(obj[prop]);
    } else if(obj[prop] === '') {
      // tokenize elements that are empty strings
      obj[prop] = token
    }
  }
  return obj;
}

const detokenizeEmptyStringElements = function (obj) {
  for (var prop in obj) {
    if (typeof obj[prop] === 'object') {// dive deeper in
      detokenizeEmptyStringElements(obj[prop]);
    } else if(obj[prop] === token) {
      // tokenize elements that are empty strings
      obj[prop] = ''
    }
  }
  return obj;
}
```

**Comment by ngocketit** [comment]
+1

**Comment by arvinkx** [comment]
+1

**Comment by svnlabs** [comment]
AWS Error Type: client, AWS Error Message: One or more parameter values were invalid: An AttributeValue may not contain an empty string

Validate empty string with " " SPACE

**Comment by MattTunny** [comment]
+1

**Comment by arctair** [comment]
+1

**Comment by eddyfabery** [comment]
+1

**Comment by terge** [comment]
+1

**Comment by vvemulak** [comment]
+1

**Comment by bo-ora** [comment]
+1

**Comment by bluepeter** [comment]
+8

**Comment by franciscotfmc** [comment]
+1

**Comment by JamesDorrian** [comment]
+1

**Comment by rocedavor** [comment]
+1

**Comment by kunalpatilabg** [comment]
+1

**Comment by atulrawat** [comment]
+1

**Comment by josepapaianni** [comment]
+1

**Comment by esteban-uo** [comment]
+1

**Comment by superandrew** [comment]
this is the single most requested thing I saw in my life.

**Comment by jeskew** [comment]
Hi @superandrew,

You might want to check out [the DynamoDB Data Mapper for JavaScript](https://github.com/awslabs/dynamodb-data-mapper-js), which is now in developer preview. That project allows you to define your table schema up front so that empty strings can be saved as a sigil value compatible with DynamoDB's data model (`null`) and then deserialized back to an empty string when the item is loaded.

If you don't want to define a schema and don't mind transforming empty strings and buffers into `null`, you can also use the `convertEmptyValues` option on the Document client as discussed above.

**Comment by superandrew** [comment]
thanks @jeskew as others have pointed out, this is not a problem of the js sdk but of dynamodb itself. I was just noticing how many people continue to request a dynamodb feature here because it's not possible to do it nowhere else.

**Comment by adimoraret** [comment]
+1

**Comment by M1chaelTran** [comment]
+1

**Comment by jhoel** [comment]
+1

**Comment by sowmitranalla** [comment]
+1

**Comment by invisibleroads** [comment]
lol

**Comment by mymail4blogs** [comment]
Trying to insert the data directly from a third party service which has almost 234 fields, some of them are empty. +1

**Comment by a1exwang** [comment]
+1

**Comment by mstudio** [comment]
+1

**Comment by Mnilko** [comment]
+1

**Comment by stephenfowler** [comment]
+1

**Comment by chrisburkejr** [comment]
+1

**Comment by bvanloocke** [comment]
+1

**Comment by yzhong52** [comment]
+1

**Comment by rtatiparthy** [comment]
+1

**Comment by XBeg9** [comment]
+1

**Comment by frankjl** [comment]
+1

**Comment by lilnate22** [comment]
+100000

**Comment by mlensment** [comment]
+1

**Comment by Kivylius** [comment]
+1

**Comment by devalpcyb** [comment]
+1

**Comment by alopes** [comment]
+9001

**Comment by synergiclabs** [comment]
+1

**Comment by gesposito** [comment]
```
const dynamodb = new AWS.DynamoDB.DocumentClient({
    convertEmptyValues: true,
});
```

**Comment by chrisburkejr** [comment]
convertEmptyValues changes them into null values not empty strings https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html

**Comment by jeskew** [comment]
@chrisburkejr Empty string values will be rejected by DynamoDB; `null` is the only emptiness sigil that can be persisted in a DynamoDB table. If a particular field must always be a string, you could try using a schema-driven abstraction like [the DynamoDB DataMapper](https://github.com/awslabs/dynamodb-data-mapper-js), which can transparently handle empty strings.

**Comment by nickcoad** [comment]
This has been an issue for 5 years and has virtually no response on the DynamoDb forum, which is why you're getting hassled about it here. Maybe it's possible for you to raise this internally with the DynamoDb team so they can at the very least jump into the forum thread and address it with the users?

**Comment by Aristocles** [comment]
+1

**Comment by raaone7** [comment]
+1

**Comment by menkveldj** [comment]
+1

**Comment by fptavares** [comment]
convertEmptyValues: true

was enough to fix it for me.

**Comment by BetaMee** [comment]
+1

**Comment by nephe** [comment]
+1

**Comment by hcho112** [comment]
+1

**Comment by chauhanprateek89** [comment]
+1

**Comment by JamesTheHacker** [comment]
@fptavares solution works just fine. It's documented here. Here is a quick example on usage:

```
module.exports.postback = (event, context, callback) => {
  const body = qs.parse(event['body']) || {}

  const params = {
    TableName: "conversions",
    Item: {
      "gclid": body.gclid,
      "leadid": body.leadid,
      "affid": body.affid,
      "campid": body.campid,
      "cid": body.cid,
      "tid": body.tid,
      "s1": body.s1,
      "s2": body.s2,
      "s3": body.s3,
      "s4": body.s4,
      "s5": body.s5,
      "price": body.price,
      "udid": body.udid,
    }
  }

  const dynamo = new AWS.DynamoDB.DocumentClient({
    convertEmptyValues: true
  })
  
  dynamo.put(params, (err, data) => {
    if (err) Raven.captureException(err)
    callback(null, {
      statusCode: 200,
      body: JSON.stringify({ "message": "success" })
    })
  })
}
```

**Comment by synergiclabs** [comment]
@JamesTheHacker That is not a viable solution. The option `convertEmptyValues` converts a string into a NULL value. There are instances you really need EMPTY STRING and not a null data type.
In JavaScript, `"" !== null;`

**Comment by JamesTheHacker** [comment]
@synergiclabs Of course, but in my instance and maybe for others, the solution is fine as I do not require empty strings to be stored.

**Comment by Hanslen** [comment]
+1

**Comment by seckcoder** [comment]
+1

**Comment by Antommyj** [comment]
+1

**Comment by spolyak** [comment]
+1

**Comment by wowmama** [comment]
+1, we really need to persist empty string into database.

**Comment by kushbhandari** [comment]
+1 ... read in some other issue that empty strings will be supported in DDB in 2018 .. any update when?

**Comment by eduardoconekta** [comment]
+1

**Comment by whitechdevs** [comment]
+1

**Comment by richard-gebbia** [comment]
+1

**Comment by nejcr** [comment]
+1

**Comment by kimthangatm** [comment]
+1

**Comment by cahenyossi** [comment]
+1

**Comment by keesvanlierop** [comment]
+1

**Comment by smtheard** [comment]
can someone explain why setting an empty string would ever be considered invalid? this behavior makes no sense, the issue is closed, and it seems clearly incorrect despite being documented.

**Comment by andreafalzetti** [comment]
+1

**Comment by Anonymous20180110** [comment]
+1

**Comment by jchirschy** [comment]
+1

**Comment by PavelSizov** [comment]
+1

**Comment by cmavromichalis** [comment]
+1

**Comment by jeremyputeaux** [comment]
+1

**Comment by bogdan-maksak** [comment]
+1

**Comment by onrul** [comment]
+1

**Comment by thoean** [comment]
@chrisradek , may I ask you to use the [lock conversation](https://blog.github.com/2014-06-09-locking-conversations/) to avoid having another million of +1s and notifying so many users? The `DocumentClient` solves this already with the `convertEmptyValues: true` option. And if the request is to store empty strings in dynamoDB, then the client library is the wrong repository to report this.

Thanks.

**Comment by richard-gebbia** [comment]
Just to be clear, `convertEmptyValues` does NOT solve the problem of dynamodb's inability to store empty strings. @thoean where is the correct place to report this issue if this isn't it?

**Comment by thoean** [comment]
@richard-gebbia I don't know the correct place. But it's not the client library as stated many times above. Best done via your account manager at AWS, or if your at a smaller contract probably just by filing a support ticket from your AWS account.

**Comment by rqton** [comment]
+1 

This issue has been created on the AWS forums for more than **6 years** : https://forums.aws.amazon.com/thread.jspa?threadID=90137

**Comment by chrisradek** [comment]
Locking this thread. This is a service behavior that can not be addressed by the SDK. Locking to prevent continued spam.
