### ISSUE TITLE
S3 events that have semicolons in their keys come with urlencoded key value 

### ISSUE THREAD

**Issue by netoneko** [aws/aws-sdk-js#837]
Hey guys,

I use SDK version `2.1.47` and I have a problem: I have configured S3 to send events to SQS. When I pull events from SQS, I get urlencoded value of the key, so when I try to use `S3.getObject` it obviously fails because it does not match the actual key name.

So, if I upload file to S3 with a name `test/10:47:07.20151213-1450022300.log.bz2`, I will receive an event, with value `s3.key.object.name` as `test%2F10%3A47%3A07.20151213-1450022300.log.bz2`.

I did not test this SDKs of other languages, but I assume the problem lies not in the SDK itself, but somewhere when events are triggered, because SDK just provides SQS event's unmodified `Body` property, which is a JSON string that I have to parse myself.

Reference documentation: http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html

**Comment by LiuJoyceC** [comment]
Hi @netoneko,
Thank you for your question. The reference documentation you mentions: The s3 key provides information about the bucket and object involved in the event. Note that the object keyname value is URL encoded. For example "red flower.jpg" becomes "red+flower.jpg".

You will need to url-decode the key name before passing it to `S3.getObject`. Please let us know if you have further questions.
