### ISSUE TITLE
API Gateway generated JavaScript SDK with IAM does not work by default in Firefox

### ISSUE THREAD

**Issue by drieselliott** [aws/aws-sdk-js#838]
When sending a POST request with data I had to set the 'defaultContentType' to "application/json; charset=UTF-8" otherwise the signing does not work.

Environment:
Firefox 42

It seems that this is an issue in Firefox itself according to this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=416178#c45

Apparently this bug is fixed in Firefox 44 which will be released at the end of January next year.

I currently have a workaround for this issue, so no problem. I'm just logging this in the case that anyone else is looking for a solution to this issue.

**Comment by jeskew** [comment]
Thanks for reporting this, @drieselliott. Glad to hear it will be fixed in a future version of Firefox.
