### ISSUE TITLE
UnexpectedParameter: Unexpected key 'recordingGroup' found in params.ConfigurationRecorder

### ISSUE THREAD

**Issue by mlconnor** [aws/aws-sdk-js#843]
Any help with this would be appreciated.  This is the first issue I've found in the SDK to date and I've been using it pretty extensively.  I'm currently running version 2.1.17 of the aws-sdk with ConfigService (node_modules/aws-sdk/apis/config-2014-11-12.min.json) and this error is being thrown.  My options object looks like this...

    {
      "ConfigurationRecorder": {
        "name": "SystemMonitor",
        "roleARN": "arn:aws:iam::732917605968:role/SystemMonitor",
        "recordingGroup": {
          "allSupported": true
        }
      }
    }

The params I'm using seem to be consistent with the docs here http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ConfigService.html#putConfigurationRecorder-property

The stack starts with this...

    UnexpectedParameter: Unexpected key 'recordingGroup' found in params.ConfigurationRecorder
      at [object Object].fail (/Users/a58179/js/highland_test/node_modules/aws-sdk/lib/param_validator.js:115:37)

**Comment by mlconnor** [comment]
I should not that if I leave that parameter out the method succeeds but Config does not subscribe to any services.

**Comment by chrisradek** [comment]
@mlconnor 
Support for `recordingGroup` in the `Config` service became available with version 2.1.36 of the SDK:
http://aws.amazon.com/releasenotes/5873934951898767

The docs will show the latest available APIs, and not what was available in a specific version of the SDK. Upgrading the SDK should resolve this issue.

Let me know if you still have issues with an updated version of the SDK!

**Comment by mlconnor** [comment]
Thanks @chrisradek.  That fixed the issue, and thank you so much for the quick reply.
