### ISSUE TITLE
Authentication v4 - question

### ISSUE THREAD

**Issue by Aldor007** [aws/aws-sdk-js#847]
On page http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html  you can read "If the Content-Type header is present in the request, it must be added to the CanonicalHeaders list." But  on https://github.com/aws/aws-sdk-js/blob/master/lib/signers/v4.js#L199 you have excluded it from canonical headers and signed headers, that behavior is correct?

**Comment by jeskew** [comment]
Hi @Aldor007,

The Content-Type header must be included in the canonical request when using an authorization header, but its inclusion is optional when the signature is provided with [query parameters](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html). The code you linked to generates presigned URLs, which always authenticate via query parameters.

Hope that helps!
