### ISSUE TITLE
IAM.putRolePolicy delay

### ISSUE THREAD

**Issue by mlconnor** [aws/aws-sdk-js#850]
This is likely more of an AWS API issue than a node sdk issue but I thought I would start here.  I have a script that creates a role and then specifies a policy.  I then try to make another call to use that policy and it fails... unless I put a 15 second sleep in my code.  Here is the basic flow

    iam.createRole(...)
    iam.putRolePolicy(...)

The policy document is as follows

    {
      "Version": "2012-10-17",
        "Statement": [
        {
          "Action": [
    	"appstream:Get*",
          "autoscaling:Describe*",
          "cloudformation:DescribeStacks",
          "cloudformation:DescribeStackEvents",
          "cloudformation:DescribeStackResource",
          "cloudformation:DescribeStackResources",
          "cloudformation:GetTemplate",
          "cloudformation:List*",
          "cloudfront:Get*",
          "cloudfront:List*",
          "cloudtrail:DescribeTrails",
          "cloudtrail:GetTrailStatus",
          "cloudwatch:Describe*",
          "cloudwatch:Get*",
          "cloudwatch:List*",
          "config:Put*",
          "directconnect:Describe*",
          "dynamodb:GetItem",
          "dynamodb:BatchGetItem",
          "dynamodb:Query",
          "dynamodb:Scan",
          "dynamodb:DescribeTable",
          "dynamodb:ListTables",
          "ec2:Describe*",
          "elasticache:Describe*",
          "elasticbeanstalk:Check*",
          "elasticbeanstalk:Describe*",
          "elasticbeanstalk:List*",
          "elasticbeanstalk:RequestEnvironmentInfo",
          "elasticbeanstalk:RetrieveEnvironmentInfo",
          "elasticloadbalancing:Describe*",
          "elastictranscoder:Read*",
          "elastictranscoder:List*",
          "iam:List*",
          "iam:Get*",
          "kinesis:Describe*",
          "kinesis:Get*",
          "kinesis:List*",
          "opsworks:Describe*",
          "opsworks:Get*",
          "route53:Get*",
          "route53:List*",
          "redshift:Describe*",
          "redshift:ViewQueriesInConsole",
          "rds:Describe*",
          "rds:ListTagsForResource",
          "s3:Get*",
          "s3:List*",
          "sdb:GetAttributes",
          "sdb:List*",
          "sdb:Select*",
          "ses:Get*",
          "ses:List*",
          "sns:Get*",
          "sns:List*",
          "sqs:GetQueueAttributes",
          "sqs:ListQueues",
          "sqs:ReceiveMessage",
          "storagegateway:List*",
          "storagegateway:Describe*",
          "trustedadvisor:Describe*"
    	],
          "Effect": "Allow",
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": [
    	"s3:PutObject*"
    	],
          "Resource": [
    	"arn:aws:s3:::#{v.bucketName}/AWSLogs/#{v.accountid}/*"
    	],
          "Condition": {
    	"StringLike": {
    	  "s3:x-amz-acl": "bucket-owner-full-control"
    	}
          }
        },
        {
          "Effect": "Allow",
          "Action": [
    	"s3:GetBucketAcl"
    	],
          "Resource": "arn:aws:s3:::#{v.bucketName}"
        },
        {
          "Effect": "Allow",
          "Action": "sns:Publish",
          "Resource": "arn:aws:sns:us-east-1:#{v.accountid}:awsConfig"
        }
      ]
    }

This is all well and good.  I then try to use the config service to putDeliveryChannel (in the same script)

    configService.putDeliveryChannel(...)

And the following exception is thrown.

    Error caught: aws.ConfigService.putDeliveryChannel err=InsufficientDeliveryPolicyException: Insufficient delivery policy to s3 bucket: ciautomationsystemlogs, unable to assume role: arn:aws:iam::542524431430:role/SystemMonitor

If I add a 15 second delay in after the creation of the role, everything seems to work ok.  I'm guessing that because IAM is a global resource, it takes the regions a little while to sync up.  If that's the case, I'm good with that, but it might be good to document that.

**Comment by jeskew** [comment]
Hi @mlconnor,

IAM is a distributed service, so you can sometimes run into propagation delays when attempting to use newly granted permissions. In [an answer on the AWS IAM forum](https://forums.aws.amazon.com/thread.jspa?messageID=195539), it's pointed out that changes are immediately reflected in the IAM APIs but can take a short time to propagate to other services:

> While changes you make to IAM entities are reflected in the IAM APIs immediately, it can take noticeable time for the information to be reflected globally. In most cases, changes you make are reflected in less than a minute. Network conditions may sometimes increase the delay, and some services may cache certain non-credential information which takes time expire and be replaced.

It sounds like delaying for fifteen seconds solves your issue, though the delay necessary may go up or down if you deploy your application to other AWS regions. You might want to try a loop that retries any `InsufficientDeliveryPolicyException`s with an exponentially increasing delay between loop iterations.

Hope that helps! Please feel free to reopen if you have any questions or concerns.
