### ISSUE TITLE
Provide ability to request list of IOT devices

### ISSUE THREAD

**Issue by bripkens** [aws/aws-sdk-js#851]
It would be great to have the ability to retrieve device / thing listings via the SDK. For instance, with the AWS CLI:

```
$ aws iot list-things
{
    "things": [
        {
            "attributes": {
                "room": "balcony"
            },
            "thingName": "balcony-light"
        }
    ]
}
```

**Comment by jeskew** [comment]
Tthe SDK supports a [listThings operation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Iot.html#listThings-property) for IoT.

Hope that helps! Please feel free to reopen if you have any questions or concerns.

**Comment by bripkens** [comment]
I didn't know this feature exists :(. Thanks @jeskew!
