### ISSUE TITLE
Memory leak uploading logs to kinesis

### ISSUE THREAD

**Issue by dschenkelman** [aws/aws-sdk-js#855]
When uploading logs to kinesis, the request body is leaked due to hanging event listeners. I'm going to put together a detailed analysis as part of a blog post, but basically in the callback of each request whether it fails or succeeds, we added this to fix it:

```
var req = kinesis.putRecords(..., function(err, res){
   ...
   req.response.httpResponse.stream.removeAllListeners();
   req.httpRequest.stream.removeAllListeners();
});
```

That works, but it seems a bit hacky. Is there a better way to achieve that?

I was planning on sending a PR but haven't been able to understand the entire code base. A few pointers would be appreciated.

Thanks,

**Comment by jeskew** [comment]
Thanks for looking into this, @dschenkelman. Do you know if the leak just affects Kinesis uploads or if requests to any other service caused a similar leak?

**Comment by dschenkelman** [comment]
Should be for all requests. The problem is that live sockets keep a reference to `_events` and that keeps the request body alive. The following figure shows the retainers:
![](https://cldup.com/xQlt4egq4E.png)

So if you are using any sort of connection keep alive, references to the body are kept as well.

**Comment by chrisradek** [comment]
@dschenkelman 
Sorry for the late response to this. Just to be clear, am I correct in understanding you're only seeing these issues when using keepalive?

**Comment by dschenkelman** [comment]
Yes, open sockets are the originators of these.

**Comment by shimont** [comment]
We encountered the same issue - memory leaking when putting records to kinesis.
I am trying what @dschenkelman suggested above.

**Comment by snoop31** [comment]
I was faced with the same problem with DynamoDB.updateItem(). Every 2 seconds, I execute this code, and judging by Timeline in Chrome, and every request aws-sdk creating 5 listeners. I was trying what @dschenkelman suggested but no luck... The number of listeners and memory is still increasing.
Any suggestion how to solve this problem?
Thanks!
![2016-03-06 19 38 26](https://cloud.githubusercontent.com/assets/17688586/13555504/1c4b2714-e3d3-11e5-891f-b095fdc5c8ec.png)

**Comment by lawlmart** [comment]
+1, having the same issue here. @dschenkelman solution doesn't resolve the leak for me.

**Comment by dschenkelman** [comment]
Another thing that might be related: if you are using `forever-agent` to keep HTTP connections alive, it always creates a new socket instead of reusing old ones (https://github.com/request/forever-agent/blob/ece900a6e8dfac734186db3080c00875c0300450/index.js#L70) because `req.useChunkedEncodingByDefault ===  true`.

Use the regular agent with keep alive instead of `forever-agent`.

**Comment by rocketspacer** [comment]
2017 and we are experiencing the same issue

**Comment by ajredniwja** [comment]
Hey @dschenkelman,

Apologies for late reply, are you still experiencing the the issue?

Closing the issue now, please re-open and use the [issue template](https://github.com/aws/aws-sdk-js/issues/new/choose) if you have any additional questions.
