### ISSUE TITLE
Node domain.dispose() is deprecated, test script needs update

### ISSUE THREAD

**Issue by sabrinaluo** [aws/aws-sdk-js#859]
https://github.com/aws/aws-sdk-js/blob/7d02a64bc559a0edba3799dae42a3f964cfb9c28/test/event_listeners.spec.coffee#L585

When run `mocha test/event_listeners.spec.coffee`, there is always a `undefined` displayed in the console, because `domain.dispose()` is called. 

As this method is deprecated, test scripts may need to be modified.

Refer to: https://github.com/nodejs/node-v0.x-archive/issues/5018

**Comment by jeskew** [comment]
Thanks for reporting this. It looks like the entire module is deprecated [as of Node 4](https://nodejs.org/docs/v4.0.0/api/domain.html#domain_domain), so we should look into how to port domain-based code to a current version of node. This would require modifying [lib/request.js](https://github.com/aws/aws-sdk-js/blob/7ab5ea827a42ed2c1229370f2cc6153a2224f886/lib/request.js#L24) as well as the tests for [request](https://github.com/aws/aws-sdk-js/blob/7d02a64bc559a0edba3799dae42a3f964cfb9c28/test/request.spec.coffee#L349) and [event_listener](https://github.com/aws/aws-sdk-js/blob/7d02a64bc559a0edba3799dae42a3f964cfb9c28/test/event_listeners.spec.coffee#L572).

As far as removing the call to `dispose` goes, the method doesn't appear to do much [in Node >= 0.12](https://github.com/nodejs/node-v0.x-archive/commit/d86814aeca64d8985402dc073eff1fc8ac93c231), but it might have desirable side effects in Node 0.10.x, which we do support. @chrisradek -- What would you think about removing this?

**Comment by srchase** [comment]
This has been removed. Closing this issue.
