### ISSUE TITLE
ECS waitFor

### ISSUE THREAD

**Issue by gerardo8a** [aws/aws-sdk-js#861]
Do we have waiters for ECS? if yes which ones are available?

What I need to is to launch an instance then wait till it launches. Then launch the containers on those instances and wait until they are ready.

Whats the best way to achieve this?

I start using ec2.waitFor('instanceRunning'... 
but it seems the instance is running but no all services are up. Then I need to proceed with the container, basically I would like to mimic the behavior when using the ECS wizard from the aws console.

Thanks

**Comment by chrisradek** [comment]
@gerardo8a 
We don't currently support ECS waiters, but will consider this as a +1 for #828.

Are you starting by launching an EC2 instance that includes the Amazon ECS Container Agent?
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_agent.html

Amazon ECS-optimized AMIs should automatically start the Amazon ECS container agent for you, which registers your instance to an ECS cluster:
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html

You could set an interval to poll for which services are active.  `describeServices` allows you to see the current status of services, along with a lot of other information. For waiters on other services, the SDK is essentially calling an operation on an interval x number of times to see if the associated actions have completed. This would be a work-around similar to what the SDK could eventually do.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECS.html#describeServices-property

Let me know if this helps!

**Comment by gerardo8a** [comment]
I already launched the instance and got it registered into a cluster. I will use the api you mentioned to check for the services. 
thanks @chrisradek

**Comment by chrisradek** [comment]
Closing this issue in favor of #828.
