### ISSUE TITLE
Some errors intentionally `throw` instead of pass through callbacks

### ISSUE THREAD

**Issue by rclark** [aws/aws-sdk-js#866]
In my application I'm seeing errors thrown by aws-sdk instead of passed through callbacks so that I can handle them. An example log:

```
/usr/local/src/.../node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
NetworkingError: socket hang up
    at createHangUpError (http.js:1473:15)
    at CleartextStream.socketCloseListener (http.js:1523:23)
    at CleartextStream.emit (events.js:117:20)
    at tls.js:694:10
    at process._tickDomainCallback (node.js:492:13)
```

I'm having trouble understanding why [there is this condition in which an error is thrown](https://github.com/aws/aws-sdk-js/blob/07e0bb831e777918538ef724a6665f109b5f3852/lib/request.js#L30) rather than managed? How can I structure my application such that it can be tolerant of these kinds of problems? This is particularly important for `NetworkingErrors` which ought to get retried instead of crashing.

**Comment by chrisradek** [comment]
@rclark 
It looks like there has been a lot of conversations around errors being 'swallowed' by the SDK in the past (#307, #392, #74 to name a few). I believe the throw statement was added to prevent the SDK from swallowing errors that were thrown from an operation's callback.

I've recreated a few NetworkingErrors but have always seen them get passed through to the callback. I'll dig deeper to try and find why your case isn't. Just to be sure, are you certain your callback isn't being called, and some error is being thrown from there?

**Comment by rclark** [comment]
Thanks for taking a look here. I also tried reproducing the failure with a NetworkingError, but was unable to. Thanks for pointing out that if I just throw an error in the callback, then I see that it ends up being thrown by `request.js`.

I'm not explicitly doing _anything_ in my callback function that could throw a NetworkingError, but:
- by watching `retry` events I noticed that every time I encountered this error in production, it was preceded by 3 retries
- increasing `maxRetries` on the s3 client has made this issue vanish in my application
- There is no further network I/O in the callback function that could cause a NetworkingError, but I am using a custom agent (see https://github.com/node-modules/agentkeepalive). Maybe it is possible that a failure in that module could be throwing an error in the context of my `putObject` callback. 

Since I can't reproduce without some failure in the calling code, I'm happy to close this issue. It is a shame, though, how some aspects of the sdk's architecture lead to misleading or otherwise useless stack traces.

**Comment by Marak** [comment]
`aws-sdk` 100% will throw instead of calling back.

Here is an easy to reproduce one for dynamodb. Really inconvenient guys. I've looked at how the sdk is built in JavaScript, and it is not best-practice.

```js
/Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
ValidationException: Item size has exceeded the maximum allowed size
    at Request.extractError (/Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (/Users/a/dev/frame.io/dynamodb-simple/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

**Comment by chrisradek** [comment]
@Marak 
Can you provide some code or details on your test case? We definitely want to look into this if you have a reproducible case.

**Comment by Marak** [comment]
This isn't rocket science.

Here is the line that throws the uncaught error: https://github.com/aws/aws-sdk-js/blob/master/lib/request.js#L30

I'm able to trigger this error by attempting to set a document in DynamoDB larger then 400k. This results in the following error: `ValidationException: Item size has exceeded the maximum allowed size`

Why a callback continuation is not provided in `request.js` makes little sense. It looks like there *might* be support for domain context, but domains are deprecated, and also terrible to work with.

It appears that I'll either have to fork `aws-sdk`, which will probably require a non-trivial patch...or I have to rewrite the dynamodb adapter from scratch or use another client library.


-10 for whoever decided a state machine with domain context was a good idea for this API client.

**Comment by chrisradek** [comment]
@Marak 
I'd like to understand what's going on in your example better. Even with that `ValidationException` error, the callback you provide to your `putItem` (or any other) operation should still be called with the error passed to it. Where things start to fall apart is when an error is thrown in some code that's called within that callback function. As you've pointed out, these uncaught errors get thrown within `request.js`.

I just tested this myself by calling `putItem` with a 500KB buffer, and logged the error in my callback. I'm not trying to defend the state machine, but want to understand why your example is exhibiting different behavior.

**Comment by Marak** [comment]
@chrisradek -

> Where things start to fall apart is when an error is thrown in some code that's called within that callback function.

This information helped a lot. Thank you.

I incorrectly assumed `aws-sdk` was the source of the uncaught error, but in reality the `aws-sdk` was taking over the error stack so I couldn't see where the original throw was coming from ( from an expected throw inside the application code ).

Sorry for jumping to any conclusions. You could imagine this was a show stopping issue here. I'm still not assumed that `aws-sdk` is squashing the error stack, but at least it's not the actual source of the uncaught errors.

Thanks again for your quick response, it really helped me today.
