### ISSUE TITLE
SharedIniFileCredentials ignores profile option if default profile present

### ISSUE THREAD

**Issue by petemounce** [aws/aws-sdk-js#867]
I have a `~/.aws/credentials` file in my windows profile. I don't have any environment variables set prefixed with `AWS` other than `AWS_REGION`, which is `eu-west-1`.

The content of the file is similar to
```ini
[default]
aws_access_key_id = ........
aws_secret_access_key = ..........

[foo]
aws_access_key_id = ........
aws_secret_access_key = ..........

[bar]
aws_access_key_id = ........
aws_secret_access_key = ..........

[assumed-creds1]
aws_access_key_id = ........
aws_secret_access_key = ..........
aws_session_token = ........

[baz]
aws_access_key_id = ........
aws_secret_access_key = ..........
```

If I run 
```js
var creds = new AWS.SharedIniFileCredentials({profile: 'assumed-creds1'});
console.log(creds.accessKeyId);
```

the output is the access key from the `default` profile, where I expect the one from `assumed-creds1`.

Same thing happens if I pick a set that isn't temporary.

If I comment out the `default` profile lines, it works as I expect for both regular and temporary creds.

I'm using `v2.2.26`.

**Comment by petemounce** [comment]
Problem In Chair, Not In Computer.

I'd actually done
```js
  var chain = new AWS.CredentialProviderChain();
  chain.providers = []; // override default chain
  var fromIni = new AWS.SharedIniFileCredentials({profile: 'foo'});
  var fromEnv = new AWS.EnvironmentCredentials('AWS');
  chain.providers.push(fromEnv); // for build agents
  chain.providers.push(fromIni); // for local use
```
and _not_ cleared the `providers` property (ie, I hadn't added line 2 above) before resolving the chain. I misunderstood the docs.

```js
  var fromIni = new AWS.SharedIniFileCredentials({profile: 'foo'});
  var fromEnv = new AWS.EnvironmentCredentials('AWS');
  var chain = new AWS.CredentialProviderChain([fromEnv, fromIni]);
```
is how I imagine you meant for that to be used, right?

**Comment by chrisradek** [comment]
@petemounce 
You could also set your credentials by doing something like this:
```javascript
AWS.config.credentials = new AWS.SharedIniFileCredentals({profile: 'foo'});
```

Then any service client you instantiate will use those credentials.

**Comment by chrisradek** [comment]
Closing the issue, feel free to comment or reopen if you have further questions!
