### ISSUE TITLE
ManagedUpload may return incorrect url for multi-part uploads on completion

### ISSUE THREAD

**Issue by sedninja** [aws/aws-sdk-js#876]
When using AWS.S3.ManagedUpload object to upload objects to an S3 compatible service, the location reported upon completion (in send callback function) shows s3.amazonaws.com url rather than the configured endpoint when the file upload is chunked rather than a simple putObject(). single file uploads do still report the configured endpoint url.

To reproduce:

configure AWS.S3 object to use an endpoint other than amazonaws

```javascript
uploader.send(function(err,d) {
    if ( err ) {
      console.log(err);
    } else {
      console.log(d);
   } 
});
```

Upload a file < maxPartSize and a file > maxPartSize. The one that is larger will report the amazonaws endpoint even though the file was uploaded to your configured endpoint. Listing the contents of your configured bucket will show the object has been successfully uploaded, but if you rely on the information passed to your callback for anything other than error reporting you may run into issues.

This was discovered using aws-sdk-2.2.9.js within chrome browser, but should be able to reproduce using nodejs as well I imagine.

**Comment by AdityaManohar** [comment]
Would you be able to paste the wire trace of your requests (raw XML response)?

The `data.Location` property was added for **non-chunked** upload responses to provide compatibility with [`AWS.S3.completeMultipartUpload()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#completeMultipartUpload-property) response data. See [`AWS.S3.putObject()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property).

We aren't actually altering the `data.Location` property for chunked uploads - this is being directly parsed from the response of the `AWS.S3.completeMultipart()` operation.

**Comment by sedninja** [comment]
@AdityaManohar Upon closer inspection I found it is possible this is an issue with RiakS2 rather than the aws-sdk. I am in fact receiving s3.amazonaws.com from the server which is configured to use my internal address as the `root_host` in `/etc/riak-cs/riak-cs.conf but it appears to be ignoring that value. According to the comments in the configuration file the default value here is s3.amazonaws.com so if my root_host was not used for some reason I assume this would be the expected behavior. I will go ahead and close this for now and if I find my assumption is wrong I'll let you know.
