### ISSUE TITLE
Workflow re-run stops working after some time

### ISSUE THREAD

**Issue by jharajeev** [aws/aws-sdk-js#879]
I just started working on aws swf and have developed a simple workflow using AWS flow framework for JAVA. After I register the workflow, when I try to re-run it, it works fine for some time no matter how many times I try that. But after some time, say few hours, re-run stops working. I checked the history and can see that execution is stuck at DecisionTaskScheduled event and so eventually times out. It seems that activity and workflow workers have stopped running as I can see "No Activities found for the given execution" message in Activities tab of the execution history. It starts working again if I run the workflow and activity host manually.

Am I doing something wrong? For my use case, I need workflow and activity workers to run continuously so that I can trigger the workflow whenever I need from my web application.

**Comment by jeskew** [comment]
HI @jharajeev,

The flow framework for Java is part of the AWS SDK for Java, not the AWS SDK for JavaScript. If you open this issue on https://github.com/aws/aws-sdk-java, someone will be able to help you out.

**Comment by jharajeev** [comment]
Hi @jeskew,

I am really sorry about that. Will definitely raise this issue on the right platform.

**Comment by jimitkr** [comment]
Was there a resolution on this issue? I am facing this right now
