### ISSUE TITLE
Uploading multiple files to S3 gets "Killed"

### ISSUE THREAD

**Issue by ruandre** [aws/aws-sdk-js#883]
When I try to upload a large number of files it fails and returns "Killed" (uploading fewer files work fine).

```js
for ( var i = files.length - 1; i >= 0; i-- ) {

  var file     = files[ i ];
  var template = fs.readFileSync( file, 'utf8' );
  var inject   = handlebars.compile( template );
  var html     = inject( obj ); // add data

  console.log( 'Processing '+ file +' for '+ key +' ...' );

  var params = {
    Bucket : bucket,
    Key    : 'generate/' + key + '/index.html',
    Body   : html
  };

  s3.upload( params, function( err, data ) {
    if ( err ) console.log( err, err.stack );
    else       console.log( 'success' );
  });

};
```

With a few files I get:
```
Processing src/html/index.html for 1234567890 ...
Processing src/html/example.html for 1234567890 ...
Processing src/html/index.html for 1234567891 ...
Processing src/html/example.html for 1234567891 ...
success
success
success
success
```

I should be getting something like this, which leads me to believe it's an async issue.
```
Processing src/html/index.html for 1234567890 ...
success
Processing src/html/example.html for 1234567890 ...
success
Processing src/html/index.html for 1234567891 ...
success
Processing src/html/example.html for 1234567891 ...
success
```

With many files I get:
```
...
Processing src/html/index.html for 99994565 ...
Processing src/html/example.html for 99994565 ...
Processing src/html/index.html for 99997328 ...
Processing src/html/example.html for 99997328 ...
Killed
```

The loop should wait for the current file to finish uploading before proceeding to the next.
Is this caused by a bug in AWS SDK or do I need to change something in my code?

**Comment by chrisradek** [comment]
@ruandre 
The SDK will perform it's service operations asynchronously, so you're actually kicking off as many uploads as you have files at once. 

If you want each upload to occur one after another, you can start the next upload in the callback you pass into the upload function. The `async` module can likely help you accomplish this as well.

Let me know if this helps!

**Comment by chrisradek** [comment]
I'm closing this issue as resolved, but feel free to comment or reopen if you have more questions related to this!
