### ISSUE TITLE
Uncaught TypeError: AWS.IotData is not a function

### ISSUE THREAD

**Issue by lsilvs** [aws/aws-sdk-js#885]
I'm trying to get a thing shadow but I can't even instantiate the AWS.IotData class.

I'm using the latest version of the sdk
```html
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.2.32.min.js"></script>
```

```js
var iotdata = new AWS.IotData({endpoint: 'https://<MY-STRING>.iot.eu-west-1.amazonaws.com'});
```

I'm getting the error:
```js
Uncaught TypeError: AWS.IotData is not a function
```

**Comment by chrisradek** [comment]
@lsilvs 
At this time IoT doesn't support CORS, so Iot and IotData aren't included by default in the browser build of the SDK. We are pushing services to support CORS, but there's currently no ETA when IoT will.

There is a forum post asking about CORS support on the IoT forums you could +1 here:
https://forums.aws.amazon.com/thread.jspa?threadID=217647&tstart=0

There are ways you could work around this. For example, you could set up an API in API Gateway that runs a lambda function that gets the data you need and returns it back to your browser, though I understand this isn't as nice as being able to run the operations directly in a browser and would incur the cost of running Lambda.

**Comment by chrisradek** [comment]
Closing this issue, but feel free to comment or re-open if you have further questions related to this!

**Comment by lsilvs** [comment]
Gotcha. I'm gonna try few options here.

Cheers,
Lucas
