### ISSUE TITLE
ListObjects failure on truncated response

### ISSUE THREAD

**Issue by rclark** [aws/aws-sdk-js#886]
I have an application that paginates through S3 ListObjects responses to find all the keys in a particular prefix. I noticed that sometimes it stopped early, without throwing any errors.

If I build a mock S3 server that begins providing ListObjects response XML, then abruptly closes the connection, the sdk silently accepts the response, and provides what looks like the end of the listing.

An http server like this one:

```js
var server = http.createServer(function (req, res) {
  res.writeHead(200, { 'Content-Length': 500 });
  res.write('<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>bucket</Name><Prefix>list-truncated</Prefix><Marker>next-one</Marker><MaxKeys>1000</MaxKeys><IsTruncated>true</IsTruncated><Contents><Key>first-one</Key><LastModified>2015-09-24T21:09:21.000Z</LastModified><ETag>&quot;9a194fc78eaede');
  return req.socket.destroy();
});
```

If I monitor the `extractData` event, I find that the response was accepted as "valid":

```js
s3.listObjects(params, function(err, data) {
  console.log(err); // null
  console.log(data); // { Contents: [], CommonPrefixes: [] }
  console.log(data.IsTruncated); // undefined
  console.log(data.Marker); // undefined
  console.log(data.Contents.slice(-1)[0]); // undefined
}).on('extractData', function(resp) {
  console.log(resp.error); // null
  console.log(resp.data); // { Contents: [], CommonPrefixes: [] }
});
```

It seems to me that this body ought to fail XML parsing... or fail since the `body.length` !== `headers.ContentLength`... or something other than present what's likely to be detected as a legitimate end to the listing.

**Comment by LiuJoyceC** [comment]
Hi @rclark 
Thanks for bringing this to our attention. I was able to reproduce the error you described and am now actively working on a fix for this bug.
