### ISSUE TITLE
Delete Bucket not working

### ISSUE THREAD

**Issue by rajinderodz** [aws/aws-sdk-js#887]
Hi,
   I am using aws-sdk-js in node js. I want to to delete bucket but its not working. Please let me know required parameters for delete bucket in node js. I am using s3.deleteBucket function.
Please reply me asap.

**Comment by chrisradek** [comment]
@rajinderodz 
The only parameter `deleteBucket` accepts is the bucket name:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#deleteBucket-property

That said, a bucket can only be deleted after all objects within the bucket have been deleted. Are you having issues deleting an empty bucket?

**Comment by chrisradek** [comment]
Closing this issue, feel free to reopen if you're still having issues.
