### ISSUE TITLE
getSignedUrl - Any idea on the body?

### ISSUE THREAD

**Issue by aichholzer** [aws/aws-sdk-js#889]
```
var s3 = new AWS.S3({computeChecksums: true}); // this is the default setting
var params = {
    Bucket: 'myBucket',
    Key: 'myKey',
    Body: 'EXPECTED CONTENTS'
};

var url = s3.getSignedUrl('putObject', params);
console.log("The URL is", url);
```

Does anyone have an idea what the body should be?
Trying to get a signature for a file to be uploaded. Tried a buffer, a stream, the binary content of the image... In all cases AWS rejects my request.

`Body: EXPECTED CONTENTS` - You really got to love the AWS documentation.

Any ideas, any one?

**Comment by chrisradek** [comment]
@aichholzer 
Is your intent to specify a presigned url that contains a body? Typically, presigned URLs are used when the body isn't known. In that case, you would not need to supply the `Body` parameter.

**Comment by aichholzer** [comment]
@chrisradek I guess you did not read my question or it was not clear.

> Trying to get a signature for a file to be uploaded.
Yes, I want to get a presigned URL for a `PUT` request. I assume the presigned `Body` parameter is to ensure that the same presigned URL cannot be used to upload another image, since there is no other way to check the payload.

```
var params = {
    Bucket: 'myBucket',
    Key: 'myKey',
    Body: 'EXPECTED CONTENTS'
};
```
Again, my question is what is the `Body` supposed to hold? Which data?
