### ISSUE TITLE
Node Lambda Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by loretoparisi** [aws/aws-sdk-js#890]
I'm having this error when doing HTTP calls from a node module that uses `superagent` to make requests  - https://github.com/visionmedia/superagent
I get this error at every request. I have enough Lambda timeout, and I'm using the context.done() when needed as described in https://aws.amazon.com/it/blogs/compute/container-reuse-in-lambda/

**Comment by chrisradek** [comment]
@loretoparisi 
Can you provide a code sample that reproduces the issue?

**Comment by loretoparisi** [comment]
@chrisradek So I have found the issue. By default `superagent` does not specify a `BASEURL`, so you have to pass the whole url (`hostname` + `uri`) in order to work properly, otherwise it will try to call `/uri` as relative path.
Thank you.
