### ISSUE TITLE
Is the SDK modular?

### ISSUE THREAD

**Issue by dmitriz** [aws/aws-sdk-js#892]
The recommended way to include the complete SDK:

```html
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.2.33.min.js"></script>
```

However it is over 500kB minified! 
I imagine only small part of it will be needed for basic tasks. 

Are there any way to include smaller modules on the need-to-basis?

**Comment by LiuJoyceC** [comment]
Hi @dmitriz 
Thanks for your question.
If you know which specific AWS services you plan to use, you can use the SDK Builder for the Javascript Browser SDK to customize the SDK and reduce its size. Please see the following links to get started:
https://blogs.aws.amazon.com/javascript/post/Tx39SJYJ8FN7O85/Introducing-the-SDK-Builder-for-the-AWS-SDK-for-JavaScript-in-the-Browser
http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-building.html

**Comment by dmitriz** [comment]
Thanks @LiuJoyceC !
