### ISSUE TITLE
SES - sendRawEmail with attachment, must contain a "TO" address.

### ISSUE THREAD

**Issue by gellin** [aws/aws-sdk-js#893]
I am building a raw message with an attachment and I ONLY wish to send the message as "BCC". I do not want a single "TO" address, because I am doing bulk sending and that would use up 1 of my 50 allowed mail slots per API request.

I believe that what I am trying to do should be supported, because I can send with only bcc addresses using **sendEmail**. 

But sending only as "BCC" will not work with **sendRawEmail** and an attachment.

**The following works just fine, but it does not work when I change the send method from "to" -> "bcc"**

    var mailOptions = {
	    from: from,
	    subject: subject,
	    text: body,
	    html: body,
	    to: to,
	    attachments: [
		    {
			    filename: "test.jpg",
			    path: "http://www.cosmic-energy.org/wp-content/uploads/2013/01/background.jpg"
		    }
	    ]
    };
    var mail = mailcomposer(mailOptions);

    mail.build(function (err, message){
		ses.sendRawEmail({RawMessage: {Data: message}}, function (err, data) {
	        if (err) {
	            console.log(err, err.stack);
	            context.fail('Internal Error: The email could not be sent.');
	        } else {
	            console.log(message);
	            context.succeed('The email was successfully sent');
	        }
	    }); 
    });

**This is what I am trying to do, note that I have only switched the "to", with the word "bcc" in my mailOptions.**

    var mailOptions = {
	    from: from,
	    subject: subject,
	    text: body,
	    html: body,
	    bcc: to,
	    ...........

My error is as follows - **2016-02-02T21:18:39.658Z	85b776e7-c9f2-11e5-a954-e3a72b3423bb	{ [InvalidParameterValue: Missing required header 'To'.]**

I believe this is/was a related issue, that was found and resolved in the php/aws-sdk.  - https://github.com/daniel-zahariev/php-aws-ses/issues/8

Maybe I need to set some custom header as well? Documentation unclear.

**Comment by chrisradek** [comment]
@gellin 
Can you try adding a custom header and see if that fixes the issue? There's an example of how to do that here:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#build-event

It's possible we need to add a similar customization as what php did.

**Comment by gellin** [comment]
I am confused on how to add a custom header like the link suggests, because I am not using the AWS Request class directly, and I do not see anything exposed to do so.

 I am calling the SES sendRawMail with a custom built raw message.

I did however test adding headers to the mail through mailcomposer, which has never failed me in the past on any email API's or services (except SES) and I received the same error.

[InvalidParameterValue: Missing required header 'To'.]


This is how I added the header into my raw message, this method of adding headers has never failed me in the past. Note, that everything works PERFECTLY, if you use "to" instead of "bcc", and the headers come out just fine as well.

	    var mailOptions = {
		    from: from,
		    subject: subject,
		    text: textBody,
		    html: htmlBody,
		    bcc: to,
		    headers: [{key: "X-Key-Name1", value: "val1"}, {key: "Force-headers", value: "1"}],
		    attachments: attachments ? attachments : []
    	};

**Comment by chrisradek** [comment]
@gellin 
If you call the ses operation without passing in a callback, you'll get a request object returned to you. Then you can add a custom header.
```javascript
mail.build(function (err, message){
    var req = ses.sendRawEmail({RawMessage: {Data: message}});
    req.on('build', function() {
      req.httpRequest.headers['Custom-Header'] = 'value';
    });
    req.send(function (err, data) {
        if (err) {
            console.log(err, err.stack);
            context.fail('Internal Error: The email could not be sent.');
        } else {
            console.log(message);
            context.succeed('The email was successfully sent');
        }
    }); 
});
```
I modified a part of your code snippet to illustrate how you could do this.

**Comment by gellin** [comment]
Thank you very much for your time, and your elegant code snippet. However I regret to inform you that I am encountering the same issue. It may be something on my end, however sending via BCC works fine with **sendEmail** But I cannot make **sendRawEmail** send via BCC at all without a "to" address. It doesn't seem to matter If I have an attachment or not either.

Full code below 

`console.log('Lambda/SES Email Fowarder Full - Version 0.1.0');

var aws = require('aws-sdk');
var ses = new aws.SES();

var mailcomposer = require('mailcomposer');
var MailComposer = mailcomposer.MailComposer;

exports.handler = function (event, context) {

    console.log("Event: " + JSON.stringify(event));
    
    if (!event.email) {
        context.fail('Missing argument: email');
        return;
    }
    
    if (!event.subject) {
        context.fail('Missing argument: subject');
    }
    
    if (!event.from) {
        context.fail('Missing argument: from');
    }

    if (!event.html && !event.text) {
	    context.fail('Missing argument: html|text');
    }

    var to 	 	= event.email;
    var from 	= event.from;
    var subject = event.subject;
    var htmlBody = event.html;
    var textBody = event.text;
    var attachments = event.attachments;
	    
    var mailOptions = {
        from: from,
        subject: subject,
        text: textBody,
        html: htmlBody,
        bcc: to[i],
        attachments: attachments ? attachments : []
    };
    
    var mail = mailcomposer(mailOptions);

    mail.build(function (err, message){
        var req = ses.sendRawEmail({RawMessage: {Data: message}});
        
        req.on('build', function() {
            req.httpRequest.headers['Force-headers'] = '1';
        });
        
        req.send(function (err, data) {
            if (err) {
                console.log(err, err.stack);
                context.fail('Internal Error: The email could not be sent.');
            } else {
                console.log(message);
                context.succeed('The email was successfully sent');
            }
        }); 
    }); 
};`

**Comment by chrisradek** [comment]
@gellin 
You're running from within Lambda? I'll try to reproduce, thanks for giving the custom headers a try.

**Comment by gellin** [comment]
Yes I am, and no problem. Here is the test event configuration I am using to fire off my lambda event. The **from** and both of the **emails** I am using have been 100% verified, because I am still in sandbox mode, and I can confirm that it works, because my script will send the emails if I change my mailoptions from **bcc** to **to**. If anyone tests my code exactly, just **npm install mailcomposer**


`{
  "email": [
    "SOME_EMAIL@AOL.com",
    "SOME_OTHER_EMAIL@AOL.com"
  ],
  "subject": "λ SES Test λλλ",
  "html": "<br><h1>Hello world!!!!!</h1> - from lambda",
  "text": "Hello world!!!!! - from lambda",
  "from": "YOUR_VERIFIED_FROM_EMAIL@AOL.COM",
  "attachments": [
    {
      "filename": "test.jpg",
      "path": "http://www.cosmic-energy.org/wp-content/uploads/2013/01/background.jpg"
    }
  ]
}`

**Comment by gellin** [comment]
If it helps at all **cc** is working for me with **sendRawEmail**

**Comment by chrisradek** [comment]
@gellin 
It might be that `mailcomposer` is not compatible with `ses.sendRawEmail`.
I found an AWS forum post that offers some insight:
https://forums.aws.amazon.com/message.jspa?messageID=336807#336807

Here's a simplified example of what I did to send an email to BCC:
```javascript
var AWS = require('aws-sdk');
var ses = new AWS.SES();
var params = {
  RawMessage: {
    Data: 'BCC: TEST_EMAIL_ADDRESS@TEST.COM\nBody of my message'
  },
  Destinations: [],
  Source: 'MY_SENDER_EMAIL@TEST.COM'
};

ses.sendRawEmail(params, function(err, data) {
  if (err) {
    console.log(err);
  } else {
    console.log('Message sent!');
  }
});
```
This information is documented by the `SES` service here but could be clearer:
http://docs.aws.amazon.com/ses/latest/APIReference/API_RawMessage.html
The SES developer guide also provides an example of how to build the `RawMessage:Data` string in Java that should help as an example of how to build your raw data as well:
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html

Let me know if this helps or if you have additional questions!

**Comment by gellin** [comment]
Thank you very much for your hard work on this issue. You are absolutely correct, there is no issue with your API it is an issue with my usage of it and mailcomposer. Thanks to your reply's I have been able to fix the issue, and confirmed there is no issue with the amazon SDK. Sorry for wasting your time, this issue is not an issue.

**Comment by chrisradek** [comment]
@gellin 
Glad you were able to get it to work!

**Comment by ericmcbride** [comment]
https://github.com/eleven41/aws-lambda-send-ses-email/blob/master/SendSesEmail/index.js
