### ISSUE TITLE
Logger facility causes crash or stall with NodeJs 4.2.5+

### ISSUE THREAD

**Issue by tcf909** [aws/aws-sdk-js#897]
When using the 'logger' config to specific a logging facility (such as process.stdOut) with anything after NodeJs 4.2.4 you get crashes and/or stalled processes when using nodeJs debug mode.

Using Node 5.x the process stalls. Using Node 4.2.5+ you will see exit code 139.

This is related to nodejs/node#4440.

Tested on AWS SDK 2.2.33.

Reverting to 4.2.4 resolved the issue for now. Possible workaround: avoid util.inspect().

**Comment by chrisradek** [comment]
@tcf909 
Looks like there is a PR that relates to this:
https://github.com/nodejs/node/pull/4819

**Comment by chrisradek** [comment]
Closing, this was fixed with version 4.3.1 of node.
