### ISSUE TITLE
S3.copyObject(...) does not follow the API documentation and incorrectly sets the 'x-amz-copy-source'

### ISSUE THREAD

**Issue by Sparragus** [aws/aws-sdk-js#901]
The API [documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html#RESTObjectCOPY-requests) mandates that the `x-amz-copy-source` header should follow the pattern `x-amz-copy-source: /source_bucket/sourceObject`. However, the header set by `AWS.S3.copyObject(...)` misses the first forward-slash ('/').

Take a look at this example of the headers set by the request made by S3:

```
{
    "user-agent": "aws-sdk-nodejs/2.2.35 darwin/v5.3.0",
    "x-amz-copy-source": "EXAMPLE_BUCKET/example.png",
    "content-type": "application/octet-stream",
    "content-length": "0",
    "host": "localhost:23456",
    "x-amz-date": "Mon, 15 Feb 2016 19:32:28 GMT",
    "authorization": "AWS ACCESS_KEY_ID:OxONlB41mmWkBM5Pfe8ipTytLhw=",
    "connection": "close"
}
```

I've created a [repo with code and instructions](https://github.com/Sparragus/aws-sdk-s3-copyObject-bug) to reproduce this bug. Please clone it and follow the steps on the README.

I should also mention that the documentation has conflicting versions of how to specify the header. Please see the [Other Notes](https://github.com/Sparragus/aws-sdk-s3-copyObject-bug#other-notes) section on the README.

**Comment by jeskew** [comment]
The CopySource parameter should be passed in as `'/' + bucket + '/' + key`. I'll update the documentation for that parameter.

**Comment by Sparragus** [comment]
Great news! Thank you.

Can you please report back when the update of the documentation is done?

**Comment by jeskew** [comment]
On further investigation, S3 will accept either form. This sounds like a bug in s3rver, which should probably be normalizing CopySource paths. In the meantime, you can use the `'/' + bucket + '/' + key` form, which will be accepted by both S3 and s3rver.

**Comment by Sparragus** [comment]
It's nice that S3 will accept either form, but still, the documentation should reflect that. Right now it's ambiguous and a library developer can't know for sure which one to use.

Again, no problem with having both as long as they are explicitly documented.

And `s3rver` isn't the only case. See this line of code on [`s3fs`](https://github.com/RiptideElements/s3fs/blob/a39b0b716e96190fff620e793e92cafbe6a90c7f/lib/s3fs.js#L345).  It starts the `CopySource` parameter **without** a '/'.

Had the documentation been explicit this wouldn't happen. (Or at least it would be their fault) Both projects are great tools for S3 development, but right now they are both in conflict due to this issue.

So, who should I go bother, `s3rver` or `s3fs`? Who's wrong and who's right?

**Comment by jeskew** [comment]
Clients are free to include or not include an initial slash; S3 will normalize `x-amz-copy-source` paths server side. In that sense, `s3fs` is not wrong to omit the slash at the beginning of the path. [This is what the AWS SDK for Ruby does, too.](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/object_copier.rb#L40).

`s3rver` should be normalizing paths on incoming requests if their goal is 100% compatibility with the S3 API. You can also always use paths that begin with a slash if you are writing a library that you wish to be compatible with S3 and any already-released versions of `s3rver`.
