### ISSUE TITLE
AWS.ElasticTranscoder.deletePreset data always empty object

### ISSUE THREAD

**Issue by rainabba** [aws/aws-sdk-js#903]
I've had to modify my code to ensure I had my param object encapsulated so I had a reference to the IDs that failed (and need resubmitted because the API and/or SDK is apparently not meant for enterprise scale) and succeeded.

Shouldn't data contain at least the ID?

```
var results = { success: [], error: [] };
presetsToDelete.forEach( preset => {
    var param = { Id: preset.id || preset.Id };
    et.deletePreset( param , function(err, data) {
        if (err) {
            results.success.push(err);
        } else {
          console.log('success call to delete', { data: data, param: param }); // param is fine, but data is always {}
          results.success.push( { data: data, param: param } );
        }

    });
});
```

**Comment by rainabba** [comment]
On further research, I discovered more documentation that indicates I should be able to use a promises implementation, but none of the events ever file for deletePreset() even though the docs say, `You can alternatively register callbacks on events provided by the AWS.Request object returned by each service operation method. This request object exposes the success, error, complete, and httpData events, each taking a callback that accepts the response object.` in the section AWS.Request Events

http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-making-requests.html

Is this approach only supported on some services/service-methods? If so, where is this documented?

**Comment by chrisradek** [comment]
@rainabba 
The `deletePreset` operation doesn't return any data other than an empty JSON object if it succeeds. If the operation fails then `data` will be `null`.

Can you explain a little more what you're trying to accomplish by listening to events emitted by the `AWS.Request` object?

**Comment by rainabba** [comment]
Given the throttling issues I'm seeing, I am going to have to maintain a queue to deal with slowing down my code and/or handling retries (I don't see how this issues can exist given the apparent popularity of AWS). To manage that queue, I need to remove items that succeed. Getting an empty response on success makes that kind of hard. I could try to retrieve all the presets and parse them each time I hit that callback, but that would be grossly inefficient and make the throttling issue significantly worse.

If the success returned the preset id, I could remove it from my queue, log the success and anything else needed.

If we could establish a more private communication I can provide more meaningful details than I can here, but I can say that I will be handling a significant quality and variety of unique videos (not typical 16:9, 30fps and often UHD60). Due to the unique nature of our environment, I will have to constantly maintain rendering profiles and since I'm under the impression that I can't provide them ad-hoc in a job (can I?), I will have to generate as many as 32 at a time, create the job (which will be a 1-off), and when the job is complete, delete them to deal with the 50-preset limit (which significantly slows me down since that really means I can only run 1 job at a time).

With my understanding of the current state of Elastic Transcoder (which is hopefully incomplete and/or incorrect), I'm not sure it will scale for us. It is ideal in many ways (save for lacking h.264 Level 5.2 and h.265 support) too so I wish that weren't so. The only other alternative I have doesn't have an API in place and that's very important for us.

If you're in an appropriate position, I'd be happy to connect to discuss more. I dare say that we are in a very unique position and are doing something big right now as Oculus, Samsung, C3 and a few others would confirm :)

**Comment by chrisradek** [comment]
@rainabba 
Regarding the throttling issues, please feel free to post to the AWS forums to voice your pain points with the Elastic Transcoder service team:
https://forums.aws.amazon.com/forum.jspa?forumID=147

So if I'm understanding correctly, when your `deletePreset` operation is run, you want to be able to know which preset was deleted?

It looks like you've already set up one way of keeping track of which preset was deleted. Inside the example you provided above, if `data` is defined (empty object), you can assume the preset was deleted and make use of the id in `param` to keep track of which preset was deleted. If `data` is `null`, then you can assume the same id in `param` was not deleted (and can look at the error for more details, i.e. due to throttling.)

Alternatively, you can use the `success` and `error` events that get emitted by the request to handle some of this. Here's an example of what that might look like:

```javascript
var req = elastictranscoder.deletePreset(param); //Omitting the callback returns a request object
req.on('success', function (response) {
  console.log(param.Id + ' was deleted');
});
req.on('error', function (err) {
  console.log(param.Id + ' was not deleted');
  console.error(err);
});
req.send();
```

Let me know if that helps or you have other questions/concerns.

**Comment by rainabba** [comment]
I am in contact with the team about having limits raised, but I also spent ~16 hours yesterday solving these issues along with implementations around ET. What I don't understand why it was required. Why wouldn't it make 100% sense to just provide the id of the object affected? If AWS isn't going to provide batched requests and can't cope with small bursts, then the library should just abstract out that behavior. I did it inside of a day and now I'll likely turn it into a module to share, but it seems like something so fundamental to this platform that I don't understand its lack of existence in the SDK. As I see it, either 1) Every person/team working with AWS API's has to solve the same problem over and over 2) My perception of the scale that AWS is used at, is grossly over-sized and so the scale of this issues hasn't been recognized. If this is just an issue with my perspective or expectations, I welcome them to be corrected.

Because I still see this as an issue (regardless of my ability to work around it), I'm not inclined to close it. It's like an error object without a stack, or user auth without an id. Yes, there are dozens of solutions to get to the same point, but I fully expect that the source in AWS has that id, so it's merely a matter of bubbling that back up with the event right?

**Comment by chrisradek** [comment]
I understand your frustration. In this case, the SDK doesn't have control over what information is coming back in the `data` object, it just returns what the Elastic Transcoder service returns. One thing I can do is forward this issue to their team so they can take a look and determine if they'll add this information in the response.

The throttling issue is interesting. Our SDKs have logic to exponentially backoff on throttled requests, but this is done per operation. It does sound like having an request batching mechanism within the SDK could be a useful feature. That would probably be better to log as a separate issue for tracking. (It could reference this one)

**Comment by rainabba** [comment]
Understood. That is an important point of clarification and I have to admit that I recognized that potential, but I still wasn't recognizing the difference in teams/projects. To your knowledge, if the API was returning the data, is the SDK setup to relay it already? If so, then I must close this as it's not an issue with the SDK at all, but the API.

**Comment by chrisradek** [comment]
@rainabba 
I reached out to the service team and references this issue, so when I hear back I'll post back here.

We would need to update our API model in order to also return the Id. However, these are generated automatically so we don't modify them directly.

**Comment by chrisradek** [comment]
Closing old issues. We can't provide support for individual service behavior. If you're having issues with the SDK and its behavior, please open an issue.

Please post to the [fourms](https://forums.aws.amazon.com/forum.jspa?forumID=147) or if you have a support agreement reach out to AWS support.
