### ISSUE TITLE
Uploading to Glacier into an unexisting vault

### ISSUE THREAD

**Issue by BernhardBezdek** [aws/aws-sdk-js#906]
Updated today to ``aws-sdk@2.2.37 ``and in the case (one of my unit tests) when I'm uploading into a vault which does not exists I'll get the following error ``AccessDeniedException``.
Previously (before update) I've got the error ``ResourceNotFoundException```.

Credentials are working in a previous Upload to an existing vault so I expect ``ResourceNotFoundException`` over a  ``AccessDeniedException``.

Please clarify what's the correct behave from now.

**Comment by chrisradek** [comment]
@BernhardBezdek 
When I try uploading an archive to a non-existent vault I get the `ResourceNotFoundException` as expected. 

Are there any more details you can provide about the error you're seeing? When you said credentials are working in a previous upload, do you mean that this test used to work and doesn't, or a separate test is continuing to work?

I also only tested using my AWS account credentials, are you using an IAM role?

**Comment by BernhardBezdek** [comment]
@chrisradek 

I have two different unit test.
Extracted the executed code and showed up how the function is called:

```js
 
var AWS =  require('aws-sdk'),
    treehash=require('treehash');

AWS.config.update({
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_KEY,
        region: global.Constants.AWS.REGIONS.FRANKFURT
});

Glacier = new AWS.Glacier();


saveToGlacier = function(vaultName, description, buffer){

	var params = {
            accountId: process.env.AWS_AMAZON_ID,
            vaultName: vaultName,
            body: buffer,
            checksum: treehash.getTreeHashFromBuffer(buffer);,
            archiveDescription: description
        };

	return new Promise(function (resolve, reject) {
            Glacier.uploadArchive(params, function (err, data) {
                if (err) {

                    log.message(err);

                    reject(error);
                } else {
                    resolve(data);
                }
            });
    	});
	};
}




saveToGlacier(existingVault, 'A::Backup....',fileBuffer)
 => resolves and when compare => data.checksum === treehash.getTreeHashFromBuffer(buffer)



saveToGlacier(aVaultWhichDoesNotExist, 'A::Backup....',fileBuffer) 
=> rejects and when compare => error.code !== ResourceNotFoundException 
```												

But at the last unit test run yesterday it returned a ResourceNotFoundException exception. But from today it's a AccessDeniedException Exception
Before I run the test the aws sdk was updated.

**Comment by chrisradek** [comment]
What version of the SDK were you using before? If you revert the SDK, does the error code match what you expect?

**Comment by BernhardBezdek** [comment]
Just made a change on an older branch.
The exeception now happens also with the previous version of aws-sdk@2.2.37.
Code which depends on the aws package including the unit test weren't changed for weeks.

The new error message points from my perspective to an issue which is not the real error because the credentials are correct but the old one pointed exactly to what's wrong -> the specifield vault doesn*t exist.

**Comment by chrisradek** [comment]
@BernhardBezdek 
I don't believe this is an issue with the SDK.

The SDK is returning the error that the Glacier service returns in the response. Information on what causes the different error codes to be returned by the service can be found here:
http://docs.aws.amazon.com/amazonglacier/latest/dev/api-error-responses.html

The model for the `uploadArchive` hasn't changed recently. While it's possible the service could have changed which error gets returned, I haven't been able to reproduce what you're seeing yet. 

Can you try the following example? When I run it, it returns the error `ResourceNotFoundException` as well as the current version of the SDK (2.2.37).

```javascript
var AWS = require('aws-sdk');
var treehash = require('treehash');

AWS.config.update({
  region: 'eu-central-1'
});

var glacier = new AWS.Glacier();

var buffer = new Buffer(500*1024).fill('text');

var params = {
  accountId: '-', //Glacier assumes account id based on provided credentials
  vaultName: 'fake-name',
  body: buffer,
  checksum: treehash.getTreeHashFromBuffer(buffer),
  archiveDescription: 'desc'
};

glacier.uploadArchive(params, function(err, data) {
  if (err) {
    console.error(err);
  } else {
    console.log(data);
  }
});
console.log(AWS.VERSION)
```

**Comment by chrisradek** [comment]
@BernhardBezdek 
The other possibility, is if the accountId you're passing doesn't match your credentials, and now the archive you were specifying actually does exist for the specified account. If your account doesn't have access to the archive, you'd see an `AccessDeniedException`.

**Comment by BernhardBezdek** [comment]
@chrisradek 

Tested the script also with a fantasy vault name and still get the ``AccessDeniedException``.
<img width="519" alt="bildschirmfoto 2016-02-20 um 16 39 01" src="https://cloud.githubusercontent.com/assets/1717382/13197527/7c3e0ec8-d7f0-11e5-99a6-ac3b657b3078.png">


![bildschirmfoto-2016-02-20-um-16 36 37](https://cloud.githubusercontent.com/assets/1717382/13197529/89034844-d7f0-11e5-8e15-331338d09f59.jpg)

**Comment by BernhardBezdek** [comment]
@chrisradek Are there any updates? using the script you provided end in the same results as my previous tests.

**Comment by chrisradek** [comment]
@BernhardBezdek 
Did you get the same error when setting `accountId` to a dash? It's commented out in your example so I can't tell if you used a dash or set it to something else.

**Comment by BernhardBezdek** [comment]
@chrisradek Just verified that. Yes I get the same error.

**Comment by chrisradek** [comment]
@BernhardBezdek 
Very sorry for the delay in responding! I am unable to reproduce your error unless I enter an accountId that is not my own. This error is also coming from the service, not generated by the SDK, so I don't believe it is an SDK issue.

If you're still having issues, I believe your best bet is to post to the [AWS Glacier forums](https://forums.aws.amazon.com/forum.jspa?forumID=140). If you provide the `requestId` that's part of the error object, they should be able to look into what happened on their end to cause the error.
