### ISSUE TITLE
Improved input validation when calling cognitoIdentity.setIdentityPoolRoles()

### ISSUE THREAD

**Issue by matsev** [aws/aws-sdk-js#908]
When calling the [cognitoIdentity.setIdentityPoolRoles()](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html#setIdentityPoolRoles-property) with role names, e.g. by passing a `{"Ref" : "SomeRole"}` from CloudFormation Template using a Custom Resource, to `authenticated` and `unauthenticated` respectively, you get the following exception:

``` json
"message": "Access to Role 'my-stack-SomeRole-KBKHTR8P6UC2' is forbidden.",
"code": "NotAuthorizedException",
...
```

This error message made me erroneously believe that it was something wrong with my roles and / or policies despite that they indeed were correct. 

A better error message would be to throw a validation exception, e.g.

``` json
"message": "1 validation error detected: Value 'my-stack-SomeRole-KBKHTR8P6UC2' at 'authenticated' is not a valid ARN",
"code": "ValidationException",
...
```

It seems like someone else [has made the same mistake](https://github.com/boto/boto3/issues/73#issuecomment-97181770).

**Comment by chrisradek** [comment]
@matsev 
Thanks for bringing up this issue. From the SDK side, we're just passing along the error that the service provides us with. The docs do specify that the values in the `Roles` map should be role ARNs, but I can ask the service team if they could do some validation on the roles passed in to make sure they conform to what an ARN looks like.

**Comment by ericblade** [comment]
Get same using CloudFormation to attempt to create.  Improving the error message returned from the service would be quite helpful, I've just spent hours digging to find this post.  Of course, had I read the doc pages more closely, I would know that they were looking for a ARN, but it's always easier when the error message tells you more information about how you failed. :-D

**Comment by chrisradek** [comment]
Closing old issues. We can't provide support for individual service behavior. If you're having issues with the SDK and its behavior, please open an issue.

Please post to the [fourms](https://forums.aws.amazon.com/forum.jspa?forumID=92) or if you have a support agreement reach out to AWS support.
