### ISSUE TITLE
Improve documentation of AWS.CognitoIdentityCredentials(params)

### ISSUE THREAD

**Issue by matsev** [aws/aws-sdk-js#912]
The documentation of the [AWS.CognitoIdentityCredentials(params)](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html#constructor-property) constructor can be improved:

- In the example code, the location of the inline comments is inconsistent. Sometimes, they are at the end of a line, sometimes on a new line making it confusing to which key they correspond.
- The `LoginId` key in the example code is not documented in the `Parameters` section.
- It is not stated which parameter keys are mandatory and which are optional.
- There are three different documentations of the `params (Object)` that have different keys, none of which maps to the example code. There is some overlap between them (the `Logins` key appear twice, but is only explained in detail once), but it is unclear why there are three different documentations and why one would choose one set of params instead of another one.

**Comment by LiuJoyceC** [comment]
Hi @matsev 
Thanks for pointing these out! We have put these changes in our backlog and will look into it.
