### ISSUE TITLE
Make services mockable at library level rather than instantiation

### ISSUE THREAD

**Issue by dgreene-r7** [aws/aws-sdk-js#915]
I'm not sure how heavy a lift this would be (although I'm guessing probably significant) but there doesn't seem to be a good way to override various services throughout the API at a library level in order to mock and/or stub methods.

Case in point, there doesn't seem to be a way to do something like this:
```javascript
const AWS = require('aws-sdk');
const sinon = require('sinon');

const payload = {
  foo: 'bar',
  baz: 3
};

AWS.S3.getObject = sinon.stub().callsArgWith(1, null, {
  ETag: 'SomeETag',
  Body: new Buffer(JSON.stringify(payload))
});

const s3 = new AWS.S3();
s3.getObject({bucket: 'mybucket', path: 'file.json'}, (err, data) => {
  console.log(JSON.parse(data)); // {foo: 'bar', baz: 3}
});
```

As far as I can tell, this is because of the way services are generated at instantiation.

While I'm sure this method saves you guys a lot of time, it makes working with the library, especially in cases where my packages and AWS services are tightly coupled by necessity, an absolute bear to test. It shouldn't be complicated to stub out `getObject` (or really any other service and method.)

Is there anything you guys can do to address this? Any workarounds in the meantime?

Thanks!

**Comment by LiuJoyceC** [comment]
Hi @dgreene-r7 
It looks like you what you are trying to do can be accomplished by stubbing out the method on the prototype object of the service class. In the example you provided, `getObject` is not going to be found on the S3 constructor function, but instead on `AWS.S3.prototype`. If you stub out the method on the service class prototype, that should take effect for all instances that you create for that service, including ones that have already been instantiated. Please let me know if that isn't what you are attempting to accomplish.

**Comment by dgreene-r7** [comment]
I swear I tried this a while ago and it wasn't working but damned if it's not behaving perfectly right now. Thanks!

**Comment by kbariotis** [comment]
@LiuJoyceC 

> If you stub out the method on the service class prototype, that should take effect for all instances that you create for that service, including ones that have already been instantiated.

This doesn't seem to work. Is it something that was working and broke at some point after this issue?

Thank you
