### ISSUE TITLE
s3.upload is not a function

### ISSUE THREAD

**Issue by dmitri-bazz** [aws/aws-sdk-js#916]
So I'm trying to store a node stream in s3. However, I get this error
`Error caught in top-level domain: TypeError: s3.upload is not a function`

And when I run a get properties to check to see what functions are on the s3 object I get: [ 'client', 'config', 'endpoint' ], so I'm not finding any methods.

```
var AWS = require('aws-sdk');

 exports.uploadReportToS3 = function name(tenantGuid, reportType, path, body) {
   const isUsingAWS = hostsConfig.mode.usingAWS == "true" ? true : false;
   if (isUsingAWS) {
         var s3 = new AWS.S3(),
             params = {
                 Bucket: S3_BUCKET,
                 Key: path,
                 Body: body
             },
             retryCounter = 5;
        
        function upload() {
            global.logger.info(Object.getOwnPropertyNames(s3));
            s3.upload(params, function(err, data) {
                if (err) {
                    // If there was an error, log it, and then retry the upload, up to 5 times
                    global.logger.error('Error in s3.upload: ' + err);
                    retryCounter -= 1;
                    if (retryCounter > 0) {
                        upload();
                    }
                } else {
                    global.logger.info('Report data uploaded to ' + path);
                }
            });
        }
        
        upload();
        
    } else
 //Irrelevant

```

Npm version says aws-sdk is v2.2.39.

**Comment by LiuJoyceC** [comment]
Hi @dmitri-bazz 
Thanks for providing your sample code. The reason you don't see any methods on the s3 instance object when you log `Object.getOwnPropertyNames(s3)` is because the methods are on the instance object's prototype, `AWS.S3.prototype`, and when you call `s3.upload`, the method is looked up on the prototype.

However, I am not able to reproduce the problem you are describing and will need more information. When you log `Object.getOwnPropertyNames(AWS.S3.Prototype)`, do you see `upload` in the list? If that's not the problem, is it possible the `upload` function that you defined is being called elsewhere inside of `uploadReportToS3`, such as in the `else` block (since `upload` is hoisted and is defined in all of `uploadReportToS3`)?

It may help to enable the logger by passing the console into the logger param when you instantiate s3: `var s3 = new AWS.S3({logger: console})`, and providing the log messages here. Also, as additional information, what version of Node are you using?

**Comment by dmitri-bazz** [comment]
Hello @LiuJoyceC 
Thank you for the swift response. It's unlikely that the upload function is being called elsewhere (the else code handles the case of an offline VM), however for prudence's sake I've renamed the function.

The version of node being ran is v4.2.1.

This is the output of 

```[ 'initialize',
  'setupRequestListeners',
  'populateURI',
  'addContentType',
  'computableChecksumOperations',
  'willComputeChecksums',
  'computeContentMd5',
  'computeSha256',
  'pathStyleBucketName',
  'dnsCompatibleBucketName',
  'escapePathParam',
  'successfulResponse',
  'retryableError',
  'extractData',
  'extractError',
  'setEndpoint',
  'getSignedUrl',
  'constructor',
  'createBucket' ]
```

This is how the code looks as of now

```
exports.uploadReportToS3 = function name(tenantGuid, reportType, path, body) {
  const isUsingAWS = hostsConfig.mode.usingAWS == 'true' ? true : false;
  if (isUsingAWS) {
            
        var tempLogger = {
          log: function (params) {
            global.logger.info(params);
          }
        };
        
        var s3 = new AWS.S3({logger: tempLogger}),
          params = {
            Bucket: S3_BUCKET,
            Key: path,
            Body: body
        },
        retryCounter = 5;
        
        function _upload() {
          global.logger.info(Object.getOwnPropertyNames(AWS.S3.prototype));
            s3.upload(params, function(err, data) {
                if (err) {
                    // If there was an error, log it, and then retry the upload, up to 5 times
                    global.logger.error('Error in s3.upload: ' + err);
                    retryCounter -= 1;
                    if (retryCounter > 0) {
                        _upload();
                    }
                } else {
                    global.logger.info('Report data uploaded to ' + path);
                }
            });
        }
        
        _upload();
        
    } else {
//Irrelevant
```

**Comment by LiuJoyceC** [comment]
`AWS.S3.prototype` should have `upload` defined as its own property, and I have not been able to reproduce your error. The `upload` method is being added in the file `aws-sdk/lib/services/s3.js`. I noticed that a few other methods that are defined in this file are also missing from your list of property names on `AWS.S3.prototype`. Can you check if the code in this file is being run (perhaps put a debugger statement or console.log at the top of this file to check)?

**Comment by dmitri-bazz** [comment]
So I think I found what the issue was. We were previously running aws-sdk "2.0.0-rc8". I then manually updated it to the latest version with npm via "npm update aws-sdk", which seems to not work correctly. After purging node_modules and reinstalling all the npm modules through package.json everything worked fine. 

Thanks for your help @LiuJoyceC !
