### ISSUE TITLE
Is there a way to resolve "unresolved method or function" in WebStorm with the aws sdk?

### ISSUE THREAD

**Issue by drfence** [aws/aws-sdk-js#922]
http://blog.jetbrains.com/webstorm/2014/07/how-webstorm-works-completion-for-javascript-libraries/

**Comment by chrisradek** [comment]
@drfence 
The way the SDK is currently written, there isn't an easy way for us to provide code completion capabilities. Most of the methods that get accessed on a service client (i.e. AWS.S3) are generated at run-time, so we don't have methods to add comments to.

It does look like Webstorm can use TypeScript definition files to enable code completion on JavaScript files, and there is a community-maintained repo:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/aws-sdk
That said, I don't know how up-to-date this is kept.

We could look into providing TypeScript definition files in the future as a way to address this.

I'll mark this as a feature request for now. We'd love to hear feedback from the community on how helpful providing TypeScript definition files would be for your development!

**Comment by aldrinleal** [comment]
Just in case, we wrote [aws-sdk-typescript](https://github.com/ingenieux/aws-sdk-typescript/). Should work from a [typings](http://github.com/typings/typings) perspective

**Comment by chrisradek** [comment]
Closing in favor of #994
