### ISSUE TITLE
AttributeValues with reserved keywords fail with JS SDK

### ISSUE THREAD

**Issue by sylwit** [aws/aws-sdk-js#925]
Hi

If you try to use a reserved keywords as a key into a attributeValue, you will see that JS try to map the key with a datatype instead of using it as a simple string. It's working on AWS console so I assume it's working with java SDK

 To reproduce this bug

```
//create the table
  const dynamodb = new AWS.DynamoDB();

  const params = {
    TableName: 'country',
    AttributeDefinitions: [
      {AttributeName: 'code', AttributeType: 'S'}
    ],
    KeySchema: [
      {AttributeName: 'code', KeyType: 'HASH'}
    ],
    ProvisionedThroughput: {ReadCapacityUnits: 1, WriteCapacityUnits: 1}
  };


  dynamodb.createTable(params, function (err) {
    next(err);
  });

//then load data
  const docClient = new AWS.DynamoDB.DocumentClient();

  const params = {
    TableName: 'country',
    Item: {
      code: 'CA',
      name: 'Canada',
      //NU: "Nunavut", //for testing, uncomment this line and remove the regions object
      regions: {
        'AB': 'Alberta',
        'BC': 'British Columbia',
        'MB': 'Manitoba',
        'NB': 'New Brunswick',
        'NL': 'Newfoundland and Labrador',
        **//'NS': 'Nova Scotia', //fail**
        'NT': 'Northwest Territories',
        **'NU': 'Nunavut', //fail**
        'ON': 'Ontario',
        'PE': 'Prince Edward Island',
        'QC': 'Quebec',
        'SK': 'Saskatchewan',
        'YT': 'Yukon'
      }
    }
  };

  docClient.put(params, function (err, data) {
    next(err);
  });

//and get the object
const params = {
    TableName: 'country',
    Key: { 
        code: { S: 'CA' }
    },
};
dynamodb.getItem(params, function(err, data) {
    if (err) console.error(err); // an error occurred
    else console.log(data); // successful response
});
```

Thanks
Sylvain

**Comment by LiuJoyceC** [comment]
Hi @sylwit 
Could you provide more information about your error? Where in your code are you using a reserved keyword as an attributeValue? What is the error message you are seeing and in which line of your code is the error emerging?

It will also be helpful to provide the version number of the JS SDK, and the version of Node you are using (or if you are using the browser SDK instead). Thanks.

**Comment by sylwit** [comment]
Hi @LiuJoyceC 

Here is a screen shot of the result

![dynamo](https://cloud.githubusercontent.com/assets/395413/13671153/29063d9c-e69c-11e5-824b-6e348dfdcafe.png)


# node -v
v5.5.0

"_id": "aws-sdk@2.2.41",

As described, problem are on these lines

```
**//'NS': 'Nova Scotia', //fail**
**'NU': 'Nunavut', //fail**
```

Using these key are considered as type , NULL and NUMBER SET

I added a simpler version to see th ebug
`//NU: "Nunavut", //for testing, uncomment this line and remove the regions object`

Thank you

**Comment by LiuJoyceC** [comment]
Hi @sylwit 
I am unable to replicate the error. Here is a screenshot of what I see when I run your code: 
![screen shot 2016-03-14 at 3 23 34 pm](https://cloud.githubusercontent.com/assets/12114318/13762381/ee210cda-e9fb-11e5-94dd-3f01c93c8ff8.png)

Neither NS nor NU is on the list of DynamoDB's reserved keywords: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html

However, if they for some reason are being interpreted as keywords, you can try using placeholders:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ExpressionPlaceholders.html

**Comment by sylwit** [comment]
Hi @LiuJoyceC 

Thank you for feedback. I guess the problem comes from dynamodb-local then. My screenshot came from the dynamodb-local shell.

NU and NS are not keywords but they are data type Null and NumberSet.
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html

I change my structure to fix this but maybe it would have worked in production.

**Comment by LiuJoyceC** [comment]
I'm glad the issue was fixed :)
