### ISSUE TITLE
Unable to change instance health

### ISSUE THREAD

**Issue by roeyazroel** [aws/aws-sdk-js#929]
Hello,

i'm trying to programmatic change instance health using this code:

`function updateInstanceHealth(instanceId, status, cb) {
    var M_TAG = ".updateInstanceHealth";
    var params = {
        InstanceId: instanceId,
        HealthStatus: status,
        ShouldRespectGracePeriod: false
    }
    ASG_AWS.setInstanceHealth(params, function(err, data){
        if (err) {
            cb(err, null);
        } else {
            cb(null, data);
        }
    })
}`

for some reason, this doesn't work.
I verified that the instance id and the status parameters are valid using the aws cli.

Any suggestions?
Roey

**Comment by chrisradek** [comment]
@roeyazroel 
Are you getting an error when running the `setInstanceHealth` command? If so, can you share it?

**Comment by roeyazroel** [comment]
@chrisradek nothing is returning, it's look like the request doesn't executed, i did breakpoints inside the function but it doesn't get in.

**Comment by chrisradek** [comment]
@roeyazroel 
Can you share what environment (node version or browser) and what version of the SDK you are using?

Can you also share how you've set up `ASG_AWS`?

When you're instantiating your AutoScaling client, can you pass in the `logger: console` configuration with the constructor? That'll log out the status of any requests made using the client.

**Comment by roeyazroel** [comment]
@chrisradek 

node version v4.2.1
aws-sdk version 2.2.43

ASG_AWS = new AWS.AutoScaling({
    "apiVersion": "2011-01-01",
     "region": "us-east-1"
})

I added logger like this:
AWS.config.update({
    accessKeyId: config.aws.accessKeyId,
    secretAccessKey: config.aws.secretAccessKey,
    logger: console
});

it works as i see more info about other requests, but nothing regarding the setInstanceHealth request.

**Comment by chrisradek** [comment]
@roeyazroel 

It doesn't look like there is anything wrong based on your code snippet. When you were debugging, you were able to verify that `setInstanceHealth` was called?

We can add some logic to enable more logging, but first, can you try just running setInstanceHealth on it's own? Something as simple as:

```javascript
var autoscaling = new AWS.AutoScaling({
  region: 'us-east-1'
});
autoscaling.setInstanceHealth({
  InstanceId: '11111',
  HealthStatus: 'fake',
  ShouldRespectGracePeriod: false
}, function (err, data) {
  if (err) {
    console.log(err);
  else {
    console.log(data);
  }
});
```
The above code should return an error from the service.

**Comment by roeyazroel** [comment]
getting nothing, no error and no log. took the code as is.

**Comment by chrisradek** [comment]
@roeyazroel 
Alright, I can't reproduce your error using just the script I supplied.

Here's another example that adds a log to each event that gets triggered during the request's lifecycle:
```javascript
var AWS = require('aws-sdk');

var autoscaling = new AWS.AutoScaling({
    region: 'us-east-1'
});

var req = autoscaling.setInstanceHealth({
    InstanceId: '11111',
    HealthStatus: 'fake',
    ShouldRespectGracePeriod: false
});

req.on('validate', function(request) {
    console.log('validate completed');
});
req.on('build', function(request) {
    console.log('build completed');
});
req.on('sign', function(request) {
    console.log('sign completed');
});
req.on('send', function(response) {
    console.log('send completed');
});
req.on('retry', function(response) {
    console.log('response completed');
});
req.on('extractError', function(response) {
    console.log('extractError completed');
});
req.on('extractData', function(response) {
    console.log('extractData completed');
});
req.on('success', function(response) {
    console.log('success completed');
});
req.on('error', function(error, response) {
    console.log(error);
    console.log('error completed');
});
req.on('complete', function(response) {
    console.log('complete completed');
});
req.on('httpHeaders', function() {
    console.log('httpHeaders completed');
});
req.on('httpData', function() {
    console.log('httpData triggered');
});
req.on('httpUploadProgress', function() {
    console.log('httpUploadProgress triggered');
});
req.on('httpDownloadProgress', function() {
    console.log('httpDownloadProgress triggered');
});
req.on('httpError', function() {
    console.log('httpError completed');
});
req.on('httpDone', function() {
    console.log('httpDone completed');
});
req.send(function(err, data) {
    console.log('callback triggered');
});
```
With the above code I see the following:
```
validate completed
build completed
sign completed
httpUploadProgress triggered
httpHeaders completed
httpDownloadProgress triggered
httpData triggered
httpDone completed
send completed
extractError completed
response completed
{ [ValidationError: Valid instance health states are: [Healthy, Unhealthy].]
  message: 'Valid instance health states are: [Healthy, Unhealthy].',
  code: 'ValidationError',
  time: Mon Mar 14 2016 14:31:04 GMT-0700 (PDT),
  requestId: '0e111d9b-ea2c-11e5-aa48-c361319c5111',
  statusCode: 400,
  retryable: false,
  retryDelay: 35.94129232224077 }
error completed
complete completed
callback triggered
```

Can you try running just the above code and share what gets logged?

Just to double check, you ran just the example by itself, no surrounding code? I've seen issues occur in rare cases due to another library being imported, so want to make sure to eliminate as many variables as possible.

**Comment by roeyazroel** [comment]
with surrounding code.

those are that logs that were added after using the above code:
[2016-03-14 23:44:09.710] [INFO] console - validate completed
[2016-03-14 23:44:09.711] [INFO] console - build completed
[2016-03-14 23:44:09.711] [INFO] console - sign completed

**Comment by chrisradek** [comment]
Do you get the same results when you run it stand-alone?

**Comment by roeyazroel** [comment]
@chrisradek 

and this is the result when standalone.

validate completed
build completed
sign completed
httpUploadProgress triggered
httpHeaders completed
httpDownloadProgress triggered
httpData triggered
httpDone completed
send completed
extractError completed
response completed
{ [ValidationError: Valid instance health states are: [Healthy, Unhealthy].]
  message: 'Valid instance health states are: [Healthy, Unhealthy].',
  code: 'ValidationError',
  time: Mon Mar 14 2016 23:47:15 GMT+0200 (IST),
  requestId: '51326311-ea2e-11e5-86f9-475f844906f7',
  statusCode: 400,
  retryable: false,
  retryDelay: 93.82062589284033 }
error completed
complete completed
callback triggered

**Comment by chrisradek** [comment]
Thanks @roeyazroel 
So it looks like there's something in your surrounding code that is causing issues with the SDK. Are you making use of any other libraries other than the SDK?

If you post the results of logging out the `httpRequest` in the `sign` callback, that might provide some clues:
`console.log(request.httpRequest);`
You might want to replace your credential that's logged if you share the log here.

Otherwise, without seeing the full surrounding code, there's not much more I can do to troubleshoot from my end unfortunately. (which I realize you may not want to share).

**Comment by roeyazroel** [comment]
@chrisradek 

i'm using 2 others:
"aws-sdk": "^2.2.43",
"config": "^1.19.0",
"log4js": "^0.6.31"

this is the code that calling the function 

function updateCluster(asGroup, launchConfig) {
    var M_TAG = ".updateCluster";
    awsHandler.getAutoScaleGroup(asGroup, function(err, data){
        if (err) {
            log.error(TAG, M_TAG, err);
            process.exit(1);
        } else {
            data.AutoScalingGroups[0].Instances.forEach(function(instance){
                if (instance.LaunchConfigurationName!=launchConfig) {
                    log.info(TAG, M_TAG, instance.InstanceId, "is not up to date");
                    awsHandler.updateInstanceHealth(instance.InstanceId, "Unhealthy", function(err, data){
                        if (err) {
                            log.error(TAG, M_TAG, err);
                            process.exit(1);
                        } else {
                            log.info(TAG, M_TAG, instance.InstanceId, "Set to Unhealthy");
                        }
                    })
                } else {
                    log.info(TAG, M_TAG, instance.InstanceId, "is up to date");
                }
            })
            process.exit(0);
        }
    })
}

**Comment by chrisradek** [comment]
@roeyazroel 
It looks like `process.exit(0);` gets called before `setInstanceHealth` finishes. 
All of the SDK operations are asynchronous. You loop through the autoscaling groups and call `updateInstanceHealth` on each instance, which in turn calls `setInstanceHealth`. The first few states of the request lifecycle (validate, build, sign) occur synchronously, but then actually making the request is async. This means that before those responses are returned, your `forEach` loop will complete and then `process.exit(0);` will be called.

You can use a library such as async to more easily manage running asynchronous tasks. This would allow you to do something like only exit the process once all callbacks have returned.

**Comment by roeyazroel** [comment]
10x!

Working great.
