### ISSUE TITLE
Cannot abort putObject

### ISSUE THREAD

**Issue by dukedougal** [aws/aws-sdk-js#931]
I've tried every solution I can think of but putObject won't work from Chrome on Windows.

Is there a known problem there?  If not, what is the correct syntax?

**Comment by LiuJoyceC** [comment]
Hi @dukedougal 
Can you describe the problem you're having? What is the error you receive? Can you provide the code snippet you're running? Have you tried running it on other browsers and OS to verify that this problem just occurs in Chrome on Windows?

Thanks.

**Comment by chrisradek** [comment]
@dukedougal 
Aborting requests is not supported in a browser currently.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#abort-property
` Note: This feature is not supported in the browser environment of the SDK.`
