### ISSUE TITLE
should add documentation on how to build the SDK using command line tools

### ISSUE THREAD

**Issue by lauterry** [aws/aws-sdk-js#933]
Hello

You should add in the ReadME, a link to this [documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-building.html)
and mention in the readme that it is possible to build yourself the SDK and choose the service you need.

It took me some times to figure out that it is possible to build the SDK using command line tools

Best regards

**Comment by LiuJoyceC** [comment]
Hi @lauterry 
Thanks for the helpful feedback. We'll put this into planning in a future sprint.

**Comment by lauterry** [comment]
Nice @LiuJoyceC !
