### ISSUE TITLE
lambda.listAliases does not understand version parameter

### ISSUE THREAD

**Issue by jkervine** [aws/aws-sdk-js#934]
I can obtain list of all aliases created to a function with listAliases, but when I want the aliases pointing to a function version, I get an empty result.

Example code: 

```javascript
var allAliasesParams = {
  FunctionName : 'simple'
};
var versionAliasesParams = {
  FunctionName : 'simple',
  FunctionVersion: '14'
};
var lambda = new aws.Lambda({
  apiVersion: '2015-03-31'
});
lambda.listAliases(allAliasesParams, function(err, data){
  if(err) console.log(err, err.stack);
  else {
    console.log("all aliases:",data);
  }
})
lambda.listAliases(versionAliasesParams, function(err, data){
   if(err) console.log(err, err.stack);
   else {
     console.log("version aliases:",data);
   }
})

outputs:

all aliases: { NextMarker: null,
  Aliases:
   [ { AliasArn: 'arn:aws:lambda:eu-west-1:907243218659:function:simple:testialias',
       Name: 'testialias',
       FunctionVersion: '14',
       Description: 'foo' } ] }
version aliases: { NextMarker: null, Aliases: [] }

**Comment by chrisradek** [comment]
@jkervine 
What version of the SDK are you using, and is this in node or the browser?

I tested the above in node and am getting the expected results when passing in the `FunctionVersion`.

Can you run the following code and verify that the `path` that is logged contains `?FunctionVersion=14` in the querystring?

```javascript
var versionAliasesParams = {
  FunctionName : 'simple',
  FunctionVersion: '14'
};
var lambda = new aws.Lambda({
  apiVersion: '2015-03-31'
});

var req = lambda.listAliases(versionAliasesParams);
req.on('build', function(request) {
    console.log(request.httpRequest.path);
    //path should end with ?FunctionVersion=14
});
req.send(function(err, data){
   if(err) console.log(err, err.stack);
   else {
     console.log("version aliases:",data);
   }
});
```

**Comment by jkervine** [comment]
@chrisradek, this is plain node, v5.7.0, aws sdk through npm "aws-sdk": "^v2.2.41"

The code above says:

```
/2015-03-31/functions/simple/aliases?FunctionVersion=14
version aliases: { NextMarker: null, Aliases: [] }
```
Also here is a capture how it is in the was console:
![simplelambda](https://cloud.githubusercontent.com/assets/983442/13839147/9e02c6ee-ec21-11e5-9fd7-c969871f803d.png)

**Comment by chrisradek** [comment]
@jkervine 
Did you try running the code example in a stand-alone script, without any surrounding code (aside from setting up credentials)? Using the same version of node.js and the SDK, I'm unable to reproduce the issue you're seeing.

**Comment by jkervine** [comment]
@chrisradek 
Finally managed to test this through. It seems like there is something wrong with that particular version and function. Running a minimal example (here: https://raw.githubusercontent.com/jkervine/node-lambda/3a6f9eb2af78d9d2fd4a10a4e156a3d21fe6a9ac/bin/aliastest.js), whenever I give it version 14, nothing is returned. changing it to, for example 13 yields aliases associated with v.13.

There's also something wrong with the function itself. when I try to delete the function (using aws console), it says:

There was an error deleting your function: Rate Exceeded. (Service: AWSLambda; Status Code: 429; Error Code: TooManyRequestsException; Request ID: f281f873-f111-11e5-9fb2-3d39a6b57e7b)

This particular function is not called even once (verified that from cloudwatch metrics).

**Comment by jkervine** [comment]
... and still adding that this is not a problem anymore to me, I have not seen the issue with other functions / versions I have created anymore - so for my part the issue can be closed. Maybe you guys want to still investigate this though.

**Comment by chrisradek** [comment]
Thanks for the update @jkervine. This sounds like it was a service-side issue, not one related to the SDK (thank you for providing some of your logged output).
