### ISSUE TITLE
ECR.describeRepositories

### ISSUE THREAD

**Issue by mathieuruellan** [aws/aws-sdk-js#937]
Hello, I'm facing an issue with the ECR.describeRepositories. It's working fine with awscli.
I've got a callback with with  err=null and data=null
I'm doing nothing else, and after i've got an exception, from request api.

`   
    
    var ECR = new AWS.ECR({region:'us-east-1'});

    ECR.describeRepositories({maxResults: 100}, new function(err, data) {
        if (err) {
            console.log(err, err.stack);
            return callback(err);
        } // an error occurred

        console.log('repositories: ', data);
    });`

**Comment by chrisradek** [comment]
@mathieuruellan 
You shouldn't be using the `new` keyword when passing a callback function to any of the operations. Can you remove that and try again?

**Comment by mathieuruellan** [comment]
Well spotted. It's working fine now.
Thank you.
