### ISSUE TITLE
[IAM] - IAM endpoint has moved temporarily

### ISSUE THREAD

**Issue by Ninir** [aws/aws-sdk-js#938]
Hello Guys,

While trying to use IAM calls from the SDK (custom build) with method [getUser](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IAM.html#getUser-property), I'm facing a XMLHttpRequest issue as in
> XMLHttpRequest cannot load https://iam.amazonaws.com/. Response for preflight is invalid (redirect)

The XMLHttpRequest returns for the preflight request (OPTIONS) a 302 Moved temporarly as in the following failing cURL request (generated from Chrome with `right click > Copy as cUrl`
> curl -v 'https://iam.amazonaws.com/' -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: http://localhost:9000' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://localhost:9000/' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: authorization, content-type, x-amz-content-sha256, x-amz-date, x-amz-user-agent' --compressed

Whereas, when you change the endpoint from `https://iam.amazonaws.com/` to `http://aws.amazon.com/fr/iam/` as in the cURL request:
> curl -v 'http://aws.amazon.com/fr/iam/' -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: http://localhost:9000' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://localhost:9000/' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: authorization, content-type, x-amz-content-sha256, x-amz-date, x-amz-user-agent' --compressed

It does seem to work for the preflight one.

What do you think I could change easily to get the appropriate result?

Thanks!

| Q  | A  |
|---|---|
| Version?  | 2.2.45  |
| Credentials?  | accessKeyId & secretAccessKey  |
| Build? | Custom |

**Comment by LiuJoyceC** [comment]
Hi @Ninir 
If CORS checking is enabled in your environment, then IAM is currently not a supported service and the preflight request will not succeed. Please see the developer guide for a list of services that are currently supported in environments that enforce CORS: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-services.html

We have contacted the IAM service team and are working towards getting CORS support for the service in the future. I will keep you updated once CORS support is added for IAM.

**Comment by Ninir** [comment]
Hey @LiuJoyceC 
Thank you for taking the time to answer.
So for now, I guess it could be done using an API Gateway endpoint with a Lambda developed in NodeJS for instance, thus making the exact same call?

Thank your for taking the lead on this from an AWS side, really appreciated.

**Comment by LiuJoyceC** [comment]
Hi @Ninir 
Yes, you can use a Lambda function to call IAM's getUser operation and use an API Gateway endpoint to access the result.
If this is your first time using API Gateway with Lambda, please see this guide for a step-by-step walkthrough: https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started.html
Let me know if this accomplishes what you are trying to do!

**Comment by LiuJoyceC** [comment]
Hi @Ninir 
I am reaching out to the IAM team for an update. It would be helpful post this request for CORS support on the AWS Forum for IAM to add visibility to this issue. Thanks! I will close this issue as it is not an SDK issue.
https://forums.aws.amazon.com/forum.jspa?forumID=76
