### ISSUE TITLE
Pagination with EC2

### ISSUE THREAD

**Issue by abhiofdoon** [aws/aws-sdk-js#939]
Hi, 
Seems like the pagination is not working correctly.

I have 12 instances and in my describe instance parameters I specify MaxResults as 12. I was expecting to get 12 instances and no NextToken. However I get 12 instances and a NextToken. If there are only 12 instance then NextToken seems unnecessary.

var AWS = require('aws-sdk');
var params = {
               MaxResults:"12"};

var ec2 = new AWS.EC2({
    accessKeyId: 'xxxx',
    secretAccessKey: 'xxxx',
    region: 'us-west-1',
    sslEnabled: false });

ec2.describeInstances(params, function (err, result) {
        console.log(result);
});

-- Output is --
$ node paging.js
{ Reservations:
   [ { ReservationId: 'r-819b3f44',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-b401d971',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-840bc841',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-ab5ef66b',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-b4d21471',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-63e25ba3',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-deae556c',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-78ef2ebd',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-615ba3d3',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-c5924900',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-46d07b86',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-5cfc6f9c',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] } ],
  NextToken: 'eyJ2IjoiMSIsImMiOiJ3S1hIaTEvSjdOSVk3V2tYYUxlWU9WdGVZSjFNZHJ6WjdNZmoyejZEQXFHZnhhWk1XUWNMcmtTMUMwbXdETEQxTFFkcXlMbG5aTmhuVlNQa2FLUkxDWWVTdU1vbUMvK2lyQTBRQXZXZXV3cDZRUnJVMk9sMlJrYjJBNXRZblQvZVZXeHRKUXB6ZTdRbURDeFl0RER0Vlo3NDZRMkxQd2FFQTlvODdGWW5EeWs9IiwiaSI6ImQ4eHU5VVNKSTJlM2RrQXo4WUk2Q2c9PSIsInMiOiIxIn0=' }

**Comment by LiuJoyceC** [comment]
Hi @abhiofdoon 
Thanks for raising this issue. You are correct, with EC2 describeInstances, the results will only omit a NextToken if the number of returned results is strictly less than the specified MaxResults. As a workaround, you will just need to check if the Reservations array has length 0 to see if the NextToken returned from the previous result actually contains more results. This is an EC2 service issue rather than an SDK issue, and I will contact the service team regarding this. Also feel free to raise this issue with the service team through the [AWS Forum](https://forums.aws.amazon.com/forum.jspa?forumID=30).
