### ISSUE TITLE
streaming images doesnt work

### ISSUE THREAD

**Issue by hereandnow** [aws/aws-sdk-js#94]
so i tried to stream an image (manipulated it with gm first), and did something like that:

<pre>
gm(request('http://www.some-domain.com/image.jpg'), 'image.jpg').stream(function(err, stdout, stderr) {
  var data, request;

  data = {
    Bucket: 'my-bucket',
    Key: 'image.jpg',
    Body: stdout,
    ContentType: mime.lookup('image.jpg')
  };
  s3.client.putObject(data, function(err, res) {
   console.log('done');
  });
});
</pre>

that throws following error: Cannot determine length of [object Object]

of course it does, because in the 'afterBuild' event it tries to get the byte-length of the httpRequest-body. 

but if my body is a stream, of course he can not get the content-length. 

but thats only part1 of the issue. if i remove the 'afterBuild' for testing purposes, streaming still doesnt work. (the writeBody-method is called every couple of seconds, but the request is not finished).

i installed the module from github (not npm), to have the latest available sources...

**Comment by nmccready** [comment]
@rcmonteiro your example may work, but it defeats the purpose of streaming. (your putting everything into memory)

**Comment by kindlyseth** [comment]
Google ranks this issue highly, so perhaps it's worth noting for the next person that http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property handles streaming.

**Comment by nmccready** [comment]
Ultimately they should copy some code from here https://github.com/nathanpeck/s3-upload-stream , as it is done right .

**Comment by kindlyseth** [comment]
@nmccready, according to its README, that is made obsolete by the functionality I linked.

**Comment by nmccready** [comment]
Ah nice, misread your post. So this supports streaming. Can there be an example where `.pipe` is being used?

**Comment by lsegal** [comment]
@nmccready you still don't need to use pipe, simply pass the stream object as the `body` parameter of the [upload()](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) as shown in the doc examples. The stream object depends on the library you are using, but it's typically the thing you are trying to call `.pipe` on.

**Comment by kindlyseth** [comment]
Something like this. Beware that I haven't run this so it probably contains typos.

```js
var https = require("follow-redirects").https;
var s3 = new (require("aws-sdk")).S3();

var gitHubToken = "hex string from github personal token";

module.exports = function(callback) {
  var request = https.get(
    {
      host: "api.github.com",
      path: "/repos/aws/aws-sdk-js/tarball/4a404cb8c06bba6b7b00c323671376c6377889ed?access_token="+gitHubToken,
      headers: {
        "User-Agent": "Unique user agent string",
      },
      function(response) {
        return handleTarball(null, response, callback);
      }
    }
  );
  request.on("error", function(err) {
    return handleTarball(err, null, callback);
  });
};
var handleTarball = function(err, response, callback) {
  if (err) {
    return callback(err);
  }
  if (response.statusCode != 200) {
    return callback(new Error("unsuccessful status code: "+response.statusCode));
  }
  s3.upload({
    Bucket: "some-bucket",
    Key: "aws-sdk-js-latest.tar.gz",
    Body: response, // <--------------------- it's that simple if you use s3.upload
    ContentType: response.headers["content-type"], // shouldn't hurt
  }, callback);
};
```

**Comment by 0xdevalias** [comment]
> it's that simple if you use s3.upload

I was definitely hoping that would be the case from how it's [described in the docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property), but in trying to do this, I still end up with this error:

```json
{
  "errorMessage": "Cannot determine length of [object Object]",
  "errorType": "Error",
  "stackTrace": [
    "byteLength (/var/runtime/node_modules/aws-sdk/lib/util.js:179:26)",
    "ManagedUpload.fillBuffer (/var/runtime/node_modules/aws-sdk/lib/s3/managed_upload.js:385:19)",
    "ManagedUpload.send (/var/runtime/node_modules/aws-sdk/lib/s3/managed_upload.js:199:33)",
    "/var/runtime/node_modules/aws-sdk/lib/util.js:799:25",
    "new Promise (<anonymous>)",
    "ManagedUpload.promise (/var/runtime/node_modules/aws-sdk/lib/util.js:798:14)",
    "/var/task/index.js:55:106",
    "handler (/var/task/index.js:19:54)",
    "<anonymous>",
    "process._tickDomainCallback (internal/process/next_tick.js:228:7)"
  ]
}
```

Basic flow of my code is reading a list of 'filenames' from s3, then fetching each as a stream, which are then written out as a stream using the s3 upload function. I'm using [highland](https://highlandjs.org/) to handle some of the higher level concepts, but it just returns a node ReadableStream at the end, so I can't see why this would be an issue.

```typescript
  const fileList = await client.listResultsFiles();
  const mergedFiles = highland(fileList)
    .map(client.streamFile)
    .sequence()
    .toNodeStream();

  return client.uploadStream('results-AAAAAA.json')(mergedFiles)
```

Helpers for reference
```typescript
const listResultsFiles = async function(): Promise<string[]> {
    // List
    const s3Objects = await s3.listObjectsV2({
      ...commonParams,
      Prefix: cfg.resultsKeyPrefix
    }).promise();

    // ..snip.. some bits that make the filenames sortable

    // Sort
    return lodash
      .sortBy(files, ['prefix', 'start', 'end', 'suffix'])
      .map(({filename}) => filename);
  };

  const streamFile = (key: string) => {
    const fileStream = s3.getObject({...commonParams, Key: key}).createReadStream();
    return highland(fileStream)
  };

  const uploadStream = (destinationKey: string) => (streamToUpload: ReadableStream) => {
    return s3.upload({
      ...commonParams,
      Key: destinationKey,
      Body: streamToUpload,
    }).promise()
  };
```
