### ISSUE TITLE
Pagination + Filters

### ISSUE THREAD

**Issue by abhiofdoon** [aws/aws-sdk-js#940]
If I specify both MaxResults and Filters, then what is the order in which these things are applied ?

For example I have 12 instances. 2 are running and 10 are stopped. I want all the stopped instances and I want only 7 results at a time.

var params = {Filters: [{
                Name:"instance-state-name",
                Values:["stopped"]
                }],
               MaxResults:"7"};

Does the SDK 
1. get a page of 7 instances and then apply the instance-state-name filter to those 7 instances
OR
2. does it get all the instances, apply the instance-state-name filter and then include 7 of them in a page which gets returned ?

From my observation #1 seems to be the case but I am not sure.

var AWS = require('aws-sdk');
var params = {Filters: [{
                Name:"instance-state-name",
                Values:["stopped"]
                }],
               MaxResults:"7"};
var ec2 = new AWS.EC2({
    accessKeyId: 'xxx',
    secretAccessKey: 'xxx',
    region: 'us-west-1',
    sslEnabled: false });
ec2.describeInstances(params, function (err, result) {
        console.log(result);
});

-- Output --
It returns 6 instances to me and gives me a NextToken. Why ? Is it supposed to behave like this ?

$ node paging.js
{ Reservations:
   [ { ReservationId: 'r-819b3f44',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-b401d971',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-840bc841',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-b4d21471',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-78ef2ebd',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] },
     { ReservationId: 'r-c5924900',
       OwnerId: '681705436370',
       Groups: [],
       Instances: [Object] } ],
  NextToken: 'eyJ2IjoiMSIsImMiOiJLUEFJZUxMeU5HRGVTOXVKT2pZL3RGVmFxczczVmJNdmZSK1ZjU1dmWkxub1gvM2JqWXNWRFBzNUp6TmdoQUlVOXkwRjFZSzBRUDQ0Vlo5QUhHRnN0YTUvU01RclcxMGt0emxvdWVjWXA4RWhoTloxQmlYTG0yZ1JXZ3QvZmxyUjhkT0JYRVJpMUVydGtId05odXlOTmlOY01VTXJXN21CYUpzQk9ad2J0bVE9IiwiaSI6IlpzeHk3VmF5WWxFV2RoS2YvOHFKZnc9PSIsInMiOiIxIn0=' }

**Comment by LiuJoyceC** [comment]
Hi @abhiofdoon 
Yes, the MaxResults is applied before the Filters. So in your example, the service will get the first 7 instances regardless of their state, and then apply the filter so only those in the 'stopped' state will be returned. So your case 1 is correct.

**Comment by abhiofdoon** [comment]
Thanks for the reply @LiuJoyceC 
In that case how are the for 7 determined ? Is it my the instance creation time ?
Basically how is it decided which instance are in which page ?

**Comment by LiuJoyceC** [comment]
Hi @abhiofdoon 
The order in which results appear when paginators are used are not intended to be predicted. I'm not sure I see a use case in which you would want to treat the results on one page differently than on another page. It is more reliable to specify your filters for exactly the results you want, and then get all pages of results that are returned. However, please let me know if you feel that your use case would necessitate knowing the order in which instances appear.

**Comment by abhiofdoon** [comment]
Got it.
I am just trying to understand the behavior. I got confused by the difference between the AWS API and AWS CLI behavior.

For the same case mentioned above (I have 12 instances. 2 are running and 10 are stopped. I want all the stopped instances and I want only 7 results at a time) the AWS CLI gives me 7 results and a NextToken (after appliying the filters). Whereas the API gives me 6 results and a NextToken.(after applying the filters)
 
$aws ec2 describe-instances --max-items 7 --filters "Name=instance-state-name, Values=stopped"
{  
   "Reservations":[  
      {  },
      {  },
      {  },
      {  },
      {  },
      {  },
      {  }
   ],
   "NextToken":"eyJOZXh0VG9rZW4iOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiA3fQ=="
}

Does the CLI do some other magic behind the scene ?

Also the token strings looks very different in API vs CLI
API NextToken = eyJ2IjoiMSIsImMiOiJLUEFJZUxMeU5HRGVTOXVKT2pZL3RGVmFxczczVmJNdmZSK1ZjU1dmWkxub1gvM2JqWXNWRFBzNUp6TmdoQUlVOXkwRjFZSzBRUDQ0Vlo5QUhHRnN0YTUvU01RclcxMGt0emxvdWVjWXA4RWhoTloxQmlYTG0yZ1JXZ3QvZmxyUjhkT0JYRVJpMUVydGtId05odXlOTmlOY01VTXJXN21CYUpzQk9ad2J0bVE9IiwiaSI6IlpzeHk3VmF5WWxFV2RoS2YvOHFKZnc9PSIsInMiOiIxIn0=' }

CLI NextToken= eyJOZXh0VG9rZW4iOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiA3fQ==
