### ISSUE TITLE
apiSummary missing from getDeployments

### ISSUE THREAD

**Issue by rdewaele** [aws/aws-sdk-js#941]
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#getDeployments-property

The documentation states that the returned data from this call should have an apiSummary entry. However, I do not see this when performing this call (nor for getDeployment), nor can I find documentation whether perhaps extra parameters should be added.

Curious on how this was done on the AWS console, I observed that a call was made using an embed parameter (https://'zone'.console.aws.amazon.com/apigateway/backend/restapis/'api_id'/deployments/'id'?embed=apisummary) making me believe this may be related to #764

**Comment by chrisradek** [comment]
@rdewaele 
It doesn't look like the embed functionality is working with `getDeployments()` in the SDK, so I'l reach out to the API Gateway team about that.

However, it is supported with `getDeployment()`. You're right in that this is related to #764. We haven't yet implemented the changes to support using `embed` as it requires updating the models that the SDKs share, and we're working on making sure all the SDKs support it before making the change.

There is a work-around you can use though. It's possible to add `embed=apisummary` to the path's query string.

```javascript
var req = apigateway.getDeployment({
    restApiId: 'apiId', 
    deploymentId: 'deploymentId'
});

req.on('build', function(req) {
    req.httpRequest.path += '/?embed=apisummary';
});

req.send(function(err, data) {
    if (err) {
        console.log(err);
    } else {
        console.log(data);
    }
});
```

**Comment by ajredniwja** [comment]
Is this still an issue for you @rdewaele?

Will go ahead and close this issue, please reach out if you continue to run into this problem.

**Comment by rdewaele** [comment]
> Is this still an issue for you @rdewaele?
> 
> Will go ahead and close this issue, please reach out if you continue to run into this problem.

I'm afraid I no longer have access to the relevant code base. I believe we used the work-around as suggested at the time.
In other words, no, this is not an issue for me any more. :wink: 

I do wonder if the feature has been implemented in the API because it does not seem to have been related to this issue if it was. :thinking:
