### ISSUE TITLE
AWS S3 Multipart upload restarting when reaching 12MB of loaded data

### ISSUE THREAD

**Issue by adolfosrs** [aws/aws-sdk-js#949]
I'm kind of having a hard time looking it this issue that i have posted on [stackoverflow](
http://stackoverflow.com/questions/36297603/aws-s3-multipart-upload-restarting-when-reaching-12mb-of-loaded-data). 

Dont know if posting it here is the right approach but any help will be awesome.

**Comment by chrisradek** [comment]
@adolfosrs 
Can you take a look at your network connections through your browser when uploading a file? I'd like to know if any of the requests to S3 are timing out.

By default, the SDK has a timeout period of 2 minutes. If the connection is slow enough that a single part can't finish uploading within 2 minutes, then the SDK will attempt to retry uploading it. This could also happen if the connection is unstable/dropping enough packets that the SDK has to retry uploading a part.

It's possible to turn off the timeout, or change it.
Using the example in your stackoverflow post, you could turn it off by doing the following:
```javascript
var bucket = new AWS.S3({
  apiVersion: '2006-03-01', 
  httpOptions: {timeout: 0}, 
  params: {Bucket: $scope.creds.bucket}
});
```

Let me know what you find out!

**Comment by adolfosrs** [comment]
@chrisradek This was exactly the problem. Thanks for the reply!
