### ISSUE TITLE
GetCommit operation missing from CodeCommit

### ISSUE THREAD

**Issue by bok-** [aws/aws-sdk-js#951]
Hi,

The [documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CodeCommit.html#getCommit-property) suggests that `getCommit()` should be available in the SDK, however it is not available in the aws-sdk-js package that ships with Lambda.

A quick check of the [apis/codecommit-2015-04-13.normal.json](https://github.com/aws/aws-sdk-js/blob/54bc46d471c6a9ba86c696a7c108bc8e2dae84c3/apis/codecommit-2015-04-13.normal.json) definition seems to show `GetCommit` as missing.

Rob

**Comment by chrisradek** [comment]
@bok- 
The version of the AWS SDK hosted by Lambda lags behind the most current release. Currently, Lambda deploys version 2.2.41 of the SDK. The `getCommit` change was introduced with version 2.2.42.

The definition for `GetCommit` is in the model (looks like you were looking on a different branch):
https://github.com/aws/aws-sdk-js/blob/master/apis/codecommit-2015-04-13.normal.json#L123

In the post below, I've given some instructions on how to bundle up a different version of the AWS SDK with Lambda. It can be used as a stop-gap until Lambda updates the version of the SDK they use.
https://github.com/aws/aws-sdk-js/issues/765#issuecomment-152033324
