### ISSUE TITLE
Lambda: Unable to provide 'Runtime' parameter to updateFunctionConfiguration

### ISSUE THREAD

**Issue by danthegoodman** [aws/aws-sdk-js#954]
Lambda just released a new node runtime, and I'd like to programmatically upgrade my functions. The Lambda API supports a `Runtime` parameter but it is missing in the js sdk.

Lambda HTTP API: http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html
JS Api: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#updateFunctionConfiguration-property

**Comment by LiuJoyceC** [comment]
Hi @danthegoodman 
Thanks for submitting this issue. Version 2.3.2 of the SDK, which was released an hour ago, now includes support for the value `"nodejs4.3"` in the `Runtime` parameter.

**Comment by danthegoodman** [comment]
@LiuJoyceC Thank you!
