### ISSUE TITLE
documentation: defaultProviders is not an empty array

### ISSUE THREAD

**Issue by hulbert** [aws/aws-sdk-js#955]
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html#defaultProviders-property

This says:

> Default value:
> ```js
> AWS.CredentialProviderChain.defaultProviders = []
> ```

This (run in node's repl) shows there is obviously a chain of four providers:

```js
> var AWS = require('aws-sdk')
> AWS.CredentialProviderChain.defaultProviders
// [ [Function], [Function], [Function], [Function] ]
```

There really needs to be documentation of the default provider order as I'm seeing odd behavior with both ENV credentials and an ini file, but the default behavior isn't documented like it is for other languages' SDKs.

**Comment by LiuJoyceC** [comment]
Hi @hulbert 
Thanks for bringing this to our attention.
In the browser, `AWS.CredentialsProviderChain.defaultProviders` is an empty array, but as you pointed out, in Node, it contains 4 functions:
```
AWS.CredentialProviderChain.defaultProviders = [
  function () { return new AWS.EnvironmentCredentials('AWS'); },
  function () { return new AWS.EnvironmentCredentials('AMAZON'); },
  function () { return new AWS.SharedIniFileCredentials(); },
  function () { return new AWS.EC2MetadataCredentials(); }
];
```
So the default chain will check environmental variables first for credentials, and if not found, will fall through to the shared credentials file, and then fall through to checking EC2 metadata.

We will update our documentation to reflect this.
