### ISSUE TITLE
GCM push not received using amazon sns even after receiving message id.

### ISSUE THREAD

**Issue by revic1993** [aws/aws-sdk-js#957]
I have strange issue regarding amazon sns. I am using nodejs sdk of amazon aws to send pushnotifications to android devices. The problem is when I send the message to amazon server it returns with a MessageID, but the message is not delivered.

Here's the code for amazon publish :

```
publishMessage : function(topicArn,message){
  var gcmMessage = JSON.stringify({data:message});
  var SnsMessage = JSON.stringify({default:"default",GCM:gcmMessage});
  var params = {
    Message : SnsMessage,
    TopicArn : topicArn,
    MessageStructure : "json"
  };
  console.log("AmazonService",params);
  return AmazonSns.publish(params).promise();}
```
If I publish using amazon console the notification is working perfectly. Also I if i Remove JSON.stringify from gcmMessage it is sending pushnotification but without gcm data.

**Comment by chrisradek** [comment]
@revic1993 
I don't believe you need to JSON stringify the gcmMessage.
This may be a better question for the SNS team, but can you try formatting your GCM message a little differently? I believe your `data` object needs to contain a `message` field with the message as the value.
```javascript
var gcmMessage = {
  "data": {
    "message": message
  }
};
```

**Comment by revic1993** [comment]
@chrisradek  I got it working. Actually I was using keys in message like "from" and "to" which apparently google also uses. I just changed it to messageFrom and messageTo and now its working. Thanks for responding.
