### ISSUE TITLE
kms.decrypt is throwing TypeError: Not a buffer error

### ISSUE THREAD

**Issue by alexosunas** [aws/aws-sdk-js#958]
When implementing kms.decrypt function and the the parameter ciphertextBlob obtained from kms.generateDataKey function is set as a value for the property CiphertextBlob on params object is showing the next error:

`TypeError: Not a buffer
    at TypeError (native)
    at new Hmac (crypto.js:87:16)
    at Object.Hmac (crypto.js:85:12)
    at sign (/home/vagrant/node_modules/jwt-simple/lib/jwt.js:177:24)
    at verify (/home/vagrant/node_modules/jwt-simple/lib/jwt.js:162:27)
    at Object.jwt_decode [as decode] (/home/vagrant/node_modules/jwt-simple/lib/jwt.js:97:10)
    at /var/www/project/controllers/validation.js:81:28
    at Response.<anonymous> (/var/www/project/services/aws/kms.js:48:5)
    at Request.<anonymous> (/home/vagrant/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/home/vagrant/node_modules/aws-sdk/lib/sequential_executor.js:105:20)`

This is the implementation:

```javascript
function(ciphertextBlob, callback){

  console.log('is Buffer: ', Buffer.isBuffer(ciphertextBlob)); //true
  var blobString = ciphertextBlob.toString('base64');

  console.log('CiphertextBlob blobString : ', blobString); //posible string argument

  var params = {
    CiphertextBlob: ciphertextBlob
  };

 kms.decrypt(params, function(err, data) {
    if (err) 'Error on KMS decrypt: ' + err;
    callback(data);

  });

};
```

**Comment by chrisradek** [comment]
@alexosunas 
What version of the SDK are you using, and what environent? (node.js version or browser).
Using the latest version of the SDK in node 0.12.x, this code is working for me:

```javascript
var kms = new AWS.KMS({apiVersion: '2014-11-01'});
var generateDataKey = kms.generateDataKey({
    KeyId: 'alias/MyAlias',
    KeySpec: 'AES_256'
}).promise();

generateDataKey.then(function(data) {
    return kms.decrypt({
        CiphertextBlob: data.CiphertextBlob
    }).promise();
}).then(function(data) {
    console.log(data);
}).catch(function(err) {
    console.log(err);
});
```

**Comment by alexosunas** [comment]
@chrisradek 
The SDK version:
"name": "jwt-simple",
  "description": "JWT(JSON Web Token) encode and decode module",
  "version": "0.5.0",

Node version is:
v4.4.1

**Comment by chrisradek** [comment]
@alexosunas 
That isn't the AWS SDK. Can you try the above code using just the AWS SDK? If the problem is with `jwt-simple`, then the issue should be logged against that project.

**Comment by alexosunas** [comment]
@chrisradek sorry, the info is updated

**Comment by alexosunas** [comment]
@chrisradek 
that code is throwing this error:

```javascript
{ [ConfigError: Missing region in config]
  message: 'Missing region in config',
  code: 'ConfigError',
  time: Mon Apr 11 2016 22:26:55 GMT+0000 (UTC) }
```

**Comment by alexosunas** [comment]
@chrisradek 
It works fine, I just added the region on the constructor for your code:

```javascript
var kms = new AWS.KMS({apiVersion: '2014-11-01', region: 'us-west-2'});
```

Thanks a lot for your help.

**Comment by chrisradek** [comment]
@alexosunas 
Glad to hear it!
