### ISSUE TITLE
Uploading ArrayBuffers/ArrayBufferViews are slow in Chrome compared to Firefox

### ISSUE THREAD

**Issue by kentor** [aws/aws-sdk-js#960]
I've noticed a huge difference when uploading ArrayBuffers/ArrayBufferViews in Chrome 49 vs Firefox 45.

My application deals with large files and transforming the uploaded files, so I'm working with uploading by parts and array buffers. Here's a sample code that should run in the latest Chrome and Firefox:

```html
<!DOCTYPE html>
<html>
  <body>
    <input id="upload" type="file">
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.3.3.min.js"></script>
    <script>
      const s3 = new AWS.S3({
        accessKeyId: 'accessKeyId',
        params: {
          Bucket: 'Bucket',
          Key: 'Key',
        },
        region: 'region',
        secretAccessKey: 'secretAccessKey',
      });

      class Uploader {
        constructor(file) {
          this.file = file;
          this.lastInProgressPart = 0;
          this.parallelism = 4;
          this.partSize = 5 * 1024 * 1024;
          this.s3Parts = [];

          this.numParts = Math.ceil(this.file.size / this.partSize);
        }

        upload() {
          Promise.resolve(null).then(() => {
            return this.createMultipartUpload();
          }).then(() => {
            return this.uploadParts();
          }).then(() => {
            return this.completeMultipartUpload();
          }).then(() => {
            console.log(this);
          }).catch(err => {
            console.log(this);
            console.log(err);
          })
        }

        uploadParts() {
          return new Promise((resolve, reject) => {
            this.uploadPartsResolve = resolve;
            this.uploadPartsReject = reject;
            for (let i = 1; i <= this.parallelism; i++) {
              this.uploadPart(i);
            }
          });
        }

        uploadPart(partNumber) {
          this.lastInProgressPart = partNumber;

          const start = (partNumber - 1) * this.partSize;
          const end = start + this.partSize;

          const fr = new FileReader();
          fr.onload = e => {
            const body = new Uint8Array(e.target.result);
            // const body = new Blob([e.target.result]); // Much faster in Chrome
            s3.uploadPart({
              Body: body,
              PartNumber: partNumber,
              UploadId: this._uploadId,
            }).promise().then(data => {
              this.s3Parts.push({ ETag: data.ETag, PartNumber: partNumber });
              if (this.s3Parts.length === this.numParts) {
                this.uploadPartsResolve();
              } else {
                const nextPart = this.lastInProgressPart + 1;
                if (nextPart <= this.numParts) {
                  this.uploadPart(nextPart);
                }
              }
            }).catch(this.uploadPartsReject);
          };
          fr.readAsArrayBuffer(this.file.slice(start, end));
        }

        createMultipartUpload() {
          const p = s3.createMultipartUpload({}).promise();
          p.then(data => {
            this._uploadId = data.UploadId;
          });
          return p;
        }

        completeMultipartUpload() {
          return s3.completeMultipartUpload({
            MultipartUpload: {
              Parts: this.s3Parts.sort((a, b) => a.PartNumber - b.PartNumber),
            },
            UploadId: this._uploadId,
          }).promise();
        }
      }

      document.getElementById('upload').addEventListener('change', e => {
        const file = e.target.files[0];
        const uploader = new Uploader(file);
        uploader.upload();
      });
    </script>
  </body>
</html>
```

I've tested this on an c4.8xlarge windows instance. Uploading with Chrome shows spikes every few seconds that maxes out at ~44Mbps:

![image](https://cloud.githubusercontent.com/assets/240493/14472103/6ad52c82-00a6-11e6-9be3-cd9b0a3edb6b.png)

Whereas firefox gives a higher throughput of 300-600Mbps.

There seems to be a lot of idle time in between the batched uploads in chrome when I do a CPU profile. I can't figure out why.

![image](https://cloud.githubusercontent.com/assets/240493/14472443/162ff9f8-00a8-11e6-9ca2-b0b913b65661.png)

![image](https://cloud.githubusercontent.com/assets/240493/14472457/1f084abc-00a8-11e6-9b0e-7387c66f203e.png)

**Comment by chrisradek** [comment]
@kentor 
Can you share what region you are testing in? I'm specifically curious if signature version 4 is being used or not as that can affect performance. Signature version 2 is used by default unless the region only supports version 4.

**Comment by kentor** [comment]
us-east-1. I don't believe this is using signature version 4

**Comment by chrisradek** [comment]
@kentor 
I tried running your code in an m4.xlarge instance in us-west-1, using firefox and chrome. I tested using a ~300 MB video file. In both browsers, the upload speed was at least 200 Mbps, with chrome sometimes approaching 300 Mbps. Just in case, the version of Chrome I was testing with was: `49.0.2623.112 m`

How large are the files you're transferring? Is Chrome consistently slower?

**Comment by kentor** [comment]
Oh wow. Yeah that's the version I'm using. I get slow speeds with the inspector opened. But full speed when it's closed.

**Comment by chrisradek** [comment]
@kentor 
I see the same 'spikey' behavior when the inspector is open. However, I think this is specifically related to Chrome, not the SDK, since the uploads are not spikey when the inspector is closed.

**Comment by kentor** [comment]
Thanks @chrisradek
