### ISSUE TITLE
Request.promise() not making request?

### ISSUE THREAD

**Issue by JaKXz** [aws/aws-sdk-js#961]
I am trying to use [the `.promise()` method](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#promise-property) with the S3 class set up [edited] as below.
I have an array of redirect objects to go through, and I would like to return a promise for each one from the `putObject` method:

```js
var R = require('ramda');
var Q = require('q');
var s3bucket = new AWS.S3({
  params: {
    Bucket: S3_BUCKET_NAME
  }
});

gulp.task('push-redirects', function () {
  console.log('pushing to:', S3_BUCKET_NAME);
  return generateRedirects(gulp.paths.redirectList)
    .then(R.map(createAndSendRedirectObject))
    .then(function (promises) {
      return Q.all(promises);
    })
    .catch(function throwError(err) {
      throw new Error(err, err.stack);
    });
});

function createAndSendRedirectObject(redirect) {
  var objectParams = {
    Key: redirect.from,
    ACL: 'public-read',
    WebsiteRedirectLocation: redirect.to
  };
  return s3bucket.putObject(objectParams).promise();
}
```

Does calling `.promise()` not send the request? When inspect the results it appears that the promises are fulfilled but my redirects are not registered on my S3 bucket.

**Comment by LiuJoyceC** [comment]
Hi @JaKXz 
Do you get any error saying `Missing required key 'Bucket' in params`? Since you didn't specify a bucket in your `objectParams`, the SDK's param validation would give an error and not send the request. If you add the bucket name in `objectParams`, are you still getting the same problem?

**Comment by LiuJoyceC** [comment]
And just to verify, are you using version 2.3.0 (or higher) of the aws-sdk? Thanks

**Comment by JaKXz** [comment]
@LiuJoyceC thanks for the response. The `s3bucket` object I'm using is defined with a bucket of my choosing, contained the `S3_BUCKET_NAME` variable. I've updated the code to be a little clearer.

And yes, I'm using v2.3.3 (`npm@latest` at time of writing).

**Comment by LiuJoyceC** [comment]
Thanks for clarifying and updating the code snippet. Can you also provide the part of the code where you define the function `generateRedirects`?

**Comment by JaKXz** [comment]
@LiuJoyceC here's a simplified version: 
```js
function generateRedirects(redirectsFile) {
  //based on redirectsFile, return a promise that resolves to an array.
  return Q.when([{
    from: 'some/old/path/',
    to: 'a/new/path/'
  }]);
}
```

**Comment by JaKXz** [comment]
@LiuJoyceC do you or the SDK team have any updates? This is blocking our team and we currently have to push / fix redirects manually. Thanks!

**Comment by chrisradek** [comment]
@JaKXz 
Yes, calling `promise()` will immediately trigger the request.

Are your objects showing up in your S3 bucket? If you inspect your object and look at the Metadata, is there a `Website Redirect Location` key?

**Comment by chrisradek** [comment]
@JaKXz 
I haven't used `ramda` before, but based on your example, I think you are missing a functor.
```javascript
 .then(R.map(createAndSendRedirectObject))
```
Rambda docs:
http://ramdajs.com/0.21.0/docs/#map

`R.map` isn't passing in the `redirect` object that `createAndSendRedirectObject` needs.
 
If you replaced the above line with a new function that accepted an array of objects you could do something like this:
```javascript
.then(createAndSendRedirectObjects)
```

```javascript
function createAndSendRedirectObjects(redirects) {
  var allObjects = redirects.map(function(redirect) {
    var objectParams = {
      Key: redirect.from,
      ACL: 'public-read',
      WebsiteRedirectLocation: redirect.to
    };
    return s3Bucket.putObject(objectParams).promise();
  });
  return Promise.all(allObjects); //Might be able to substitute with Q.all(allObjects);
}
```

Using this code, you wouldn't need the `Q.all` that you have in your example either.

Note: I haven't tested the above code, but that's the general idea. Let me know if that helps!

**Comment by JaKXz** [comment]
@chrisradek that was it. Thanks!

**Comment by JaKXz** [comment]
However, I should suggest that there is some better error reporting so that I know what I'm sending and why nothing is happening - the way I had it written clearly should have returned some sort of error, but every request resolved to a promise that was fulfilled, and the value was always an anonymous function. This made it pretty hard to debug where the actual problem was.

**Comment by chrisradek** [comment]
I don't think there's anything we could have done from the SDK side. `R.map` likely was returning an empty array, as nothing was passed in for the function to iterate over. I'd suspect that `s3.putObject` wasn't being called.

If `s3.putObject` was called, then I'd be interested to see what `R.map` was actually returning.

**Comment by JaKXz** [comment]
@chrisradek I have [an example here](https://tonicdev.com/jakxz/57155dc2fb9e2a1100b5fd37) which illustrates what I was going for - your snippet is definitely the correct/more concise solution, but I'm not sure I was using `R.map` wrong. Feel free to clone/mess with that tonic notebook :)
