### ISSUE TITLE
Error: Non-file stream objects are not supported with SigV4 when using s3.uploadPart()

### ISSUE THREAD

**Issue by olivierlesnicki** [aws/aws-sdk-js#965]
I get the following error:
```
Non-file stream objects are not supported with SigV4
```
when passing a `FileStream` to `s3.uploadPart()`.

Oddly I don't get the error if I swap `s3.uploadPart()` for `s3.upload()` - this leads me to believe my object is a valid file stream.

**Comment by olivierlesnicki** [comment]
```
  signatureVersion: 'v4',
  region: 'eu-west-1',
```

**Comment by chrisradek** [comment]
@olivierlesnicki 
Can you share some more details on how you're doing a multi-part upload with a stream? Internally for the `upload` operation, the SDK will read the stream in 5 MB chunks, and make the `uploadPart` calls using those buffered chunks.

**Comment by olivierlesnicki** [comment]
The stream is created by `Busboy` https://github.com/mscdex/busboy and I just pass it as is to s3

```js
router.post('/upload/:key/:uploadId/:partNumber', function(req, res, next) {
  var busboy = new Busboy({
    headers: req.headers
  });

  busboy.on('file', (fieldname, stream, filename, encoding, mimetype) => {
      let s3req = s3.uploadPart({
        Bucket: process.env.AWS_BUCKET,
        Key: req.params.key,
        UploadId: req.params.uploadId,
        PartNumber: req.params.partNumber,
        Body: stream,
      });

      s3req.send((err, data) => {
        if (err) {
          return next(err);
        }

        res.send(data);
      });

  });

  req.pipe(busboy);
});
```

Note that if I build the incoming busboy stream in memory before handing it to `s3.uploadPart()` it works fine:

The stream is created by `Busboy` https://github.com/mscdex/busboy and I just pass it as is to s3 - but that's just to slow and memory intensive.

```js
router.post('/upload/:key/:uploadId/:partNumber', function(req, res, next) {
  var busboy = new Busboy({
    headers: req.headers
  });

  busboy.on('file', (fieldname, stream, filename, encoding, mimetype) => {
    stream.fileRead = [];
    stream.on('data', (chunk) => {
      stream.fileRead.push(chunk);
    });

    stream.on('end', () => {
      let s3req = s3.uploadPart({
        Bucket: process.env.AWS_BUCKET,
        Key: req.params.key,
        UploadId: req.params.uploadId,
        PartNumber: req.params.partNumber,
        Body: stream.fileRead,
      });

      s3req.send((err, data) => {
        if (err) {
          return next(err);
        }

        res.send(data);
      });
    });

  });

  req.pipe(busboy);
});
```

**Comment by olivierlesnicki** [comment]
Changing https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L697 to
```
  computeSha256: function computeSha256(body, done) {
    if (util.isNode()) {
      var Stream = util.nodeRequire('stream').Stream;
      var fs = util.nodeRequire('fs');
      if (body instanceof Stream) {
        if (typeof body.path === 'string') { // assume file object
          body = fs.createReadStream(body.path);
        }
      }
    }
```
(removing the error)

Allows the stream to go forward. And the sha256 is correctly computed. However an error is then thrown because the `byteLength` can't be read for the stream. Which can be solved by explicitely defining the Content-Length (this one is known).

However when all of this is done, everything just stale.

**Comment by vcernomschi** [comment]
I also have this issue for aws-sdk@2.4.1

**Comment by vcernomschi** [comment]
This issue is not reproducible on aws-sdk@2.3.6

**Comment by chrisradek** [comment]
@vcernomschi 
Are you using a file stream created from the `fs` module, or from something else?

**Comment by PsyTae** [comment]
I am also seeing this issue in aws-sdk@2.4.1.

uninstalled aws-sdk@2.4.1 and installed aws-sdk@2.3.7 and uploaded file successfully.

**Comment by chrisradek** [comment]
@PsyTae 
With version 2.4.0, the S3 client was updated to use Sigv4 by default. It's still possible to use Sigv2 by specifying you want to use that when instantiating your client:
```javascript
var s3 = new AWS.S3({signatureVersion: 'v2'})
```
This issue should only occur when using `signatureVersion: v4` due to how the body is signed. Can you share how your input stream is created?

**Comment by PsyTae** [comment]
I am currently using [S3@4.4.0](https://github.com/andrewrk/node-s3-client) to upload my files to the s3.

My Code pertaining to the upload is below.
```
var aws = require('aws-sdk'),
	s3 = require('s3'); //S3

aws.config.loadFromPath('./AwsConfig.json');
var s3sdk = new aws.S3();

var s3Client = s3.createClient({
	s3Client: s3sdk,
	maxAsyncS3: 20,
	s3RetryCount: 5,
	s3RetryDelay: 5000,
	multipartUploadThreshold: 20971520,
	multipartUploadSize: 15728640
});

function putS3(filePath, bucket, prefix, sn, cb){
	var filename = path2.basename(filePath);
	console.log(clc.magentaBright(clc.blueBright('Upload -  Started:  ', filename, '\n')));
	var s3Path;

	if (bucket.indexOf('fail') === -1){
		s3Path = prefix + '/' + sn + '/' + filename;
	} else {
		s3Path = filename;
	}

	var uploadParams = {
		localFile: filePath,
		s3Params: {
			Bucket: bucket,
			Key: s3Path,
			Metadata: { source: META }
		}
	};

	var upload = s3Client.uploadFile(uploadParams);
	upload.on('error', function(err) {
		console.log(clc.magentaBright(clc.blueBright('Upload - ERROR OCC: ', filename, '\n')));
		cb(new Error('Unable to Upload: ' + filename + ': ' + err.message), 'Unable to Upload: ' + filename + ': ' + err.message);
	});
	upload.on('end', function(data) {
		console.log(clc.magentaBright(clc.blueBright('Upload - Finished:  ', filename, '\n')));
		cb(null, data);
	});
}
```

**Comment by chrisradek** [comment]
@PsyTae 
Glad to know the work-around is working for you! I submitted PR #1034 that you're free to try that should resolve your issue even when using `signatureVersion: v4`. If you have a chance to give it a try, please let me know if it resolves your issue!

You can also test it by commenting out this line in your local copy of the SDK:
https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L738

**Comment by vcernomschi** [comment]
Thanks @chrisradek!
Issue is not reproducible after updated to  v2.4.2 with `signatureVersion: v4`.

**Comment by chrisradek** [comment]
@olivierlesnicki 
With version 2.4.2 of the SDK, you body signing is disabled by default when using `signatureVersion: v4` and https. 
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#s3DisableBodySigning-property

Non-file streams should now work as long as `s3DisableBodySigning` is set to `true` and the above conditions are met.

**Comment by olalonde** [comment]
I'm also getting this error with v2.6.3. `Non-file stream objects are not supported with SigV4`

I setup my client like this:

```
const client = new aws.S3({
  accessKeyId,
  secretAccessKey,
  endpoint: new aws.Endpoint(endpoint),
  s3ForcePathStyle: true, // needed for minio
  signatureVersion: 'v4',
  s3DisableBodySigning: true,
})
```

putObject works, just uploadPart doesn't.

**Comment by olalonde** [comment]
Stack trace points here: https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L700

**Comment by olalonde** [comment]
Hmm I'm using a Minio server running in docker for testing, which is not on https :/

**Comment by olalonde** [comment]
What is body signing anyway? Is it a header that needs to be sent before the body is streamed?

**Comment by mano-bharathi** [comment]
Hi, My bucket is located in our storage layer which is above aws. So when ever i try to upload by passing endpoint it is uploading the url "bucketname.endpoint" example (mybucket.10.86.2.44) how to change this to custom endpoint. I want something like this. http://10.86.2.44/mybucket/directory. Is that possible ??
