### ISSUE TITLE
Immutable Config

### ISSUE THREAD

**Issue by njeirath** [aws/aws-sdk-js#969]
I'm working on a purely web based project (no backend) that allows a user to create and access resources in AWS using their own API key and secret.  The flow I'm trying to build is to allow a user to provide their API credentials, test them and adjust if necessary.  I'm running into an issue where, once the service I'm using is created and used, the credentials appear to be persisted/cached and any subsequent updates are ignored. I noticed the last section [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html) that refers to the immutable config but I haven't been able to figure out how to use the suggestions to get around the issue.

I've attempted the suggestions in #516 as well but to no avail.

I was able to reproduce the issue using the Chrome developer tools console with the following code:

```
var goodConfig = {accessKeyId: 'GOOD_KEY', secretAccessKey: 'GOOD_SECRET', region: 'us-east-1'}
var badConfig = {accessKeyId: 'BAD_KEY', secretAccessKey: 'BAD_SECRET', region: 'us-east-1'}
var ec2 = new AWS.EC2(badConfig)
ec2.describeKeyPairs({}, function(err, data){console.log(err, data)})
//This call fails as we'd expect it to with a 401 response
var ec2 = new AWS.EC2(goodConfig)
ec2.describeKeyPairs({}, function(err, data){console.log(err, data)})
//This call still fails even though the credentials are valid
```

If anyone has any suggestions/advice on how I might be able to get this to work, it would be greatly appreciated.  Thanks.

**Comment by chrisradek** [comment]
@njeirath 
The way you're specifying your credentials in your config is a little off. You'll need to put credential related properties, such as `accessKeyId` and `secretAccessKey` in a `credentials` object.
Example:
```javascript
var goodConfig = {
  credentials: {
    accessKeyId: 'GOOD_KEY',
    secretAccessKey: 'GOOD_SECRET'
  },
  region: 'us-east-1'
};
```
The fields you were adding would have been added to your client's `config` property. Since `credentials` wasn't provided in your config, the clients would have used whatever was defined in the global config.

**Comment by njeirath** [comment]
Thanks for the reply.  I made the change you mention and seem to be still seeing the same issue.  As an additional test to make sure I'm doing things correctly, I tried the reverse case as well and got similar results:

The original test as in the above post but with fixed configs:

```
var goodConfig = {credentials: {accessKeyId: 'GOOD_KEY', secretAccessKey: 'GOOD_SECRET'}, region: 'us-east-1'}
var badConfig = {credentials: {accessKeyId: 'BAD_KEY', secretAccessKey: 'BAD_SECRET'}, region: 'us-east-1'}

var ec2 = new AWS.EC2(badConfig)
ec2.describeKeyPairs({}, function(err, data){console.log(err, data)})
//This call fails as we'd expect it to with a 401 response

var ec2 = new AWS.EC2(goodConfig)
ec2.describeKeyPairs({}, function(err, data){console.log(err, data)})
//This call still fails even though the credentials are valid
```


The reverse test:

```
var goodConfig = {credentials: {accessKeyId: 'GOOD_KEY', secretAccessKey: 'GOOD_SECRET'}, region: 'us-east-1'}
var badConfig = {credentials: {accessKeyId: 'BAD_KEY', secretAccessKey: 'BAD_SECRET'}, region: 'us-east-1'}

var ec2 = new AWS.EC2(goodConfig)
ec2.describeKeyPairs({}, function(err, data){console.log(err, data)})
//This call works as we'd expect it to

var ec2 = new AWS.EC2(badConfig)
ec2.describeKeyPairs({}, function(err, data){console.log(err, data)})
//This call still works even though it shouldn't
```


I did additionally try the above test cases with the suggestion from #516 which also didn't seem to make a difference:

`Object.defineProperty(AWS, 'config', { get: function() { return {} } });`

**Comment by chrisradek** [comment]
@njeirath 
Can you provide a full script that reproduces this issue, minus the actual credentials? Also, what version of the SDK are you testing with?

I tried your original code in firefox and chrome, and they both work as expected, where one call passes and one fails. I'm wondering if something is happening elsewhere in the code to cause this unexpected behavior.

**Comment by anthonygreen** [comment]
I'm seeing the same issue. Example

    AWS.config.loadFromPath('./config.json');
    AWS.config.update({ "secretAccessKey" …

does not work, the config doesn't get updated with the options object

**Comment by njeirath** [comment]
@chrisradek 
Well interestingly enough if I try this in isolation with the test page below, it seems to work as expected.  I must have something in my specific application that is causing the behavior.  If I can reproduce the error that I'm seeing I'll post again.

Test script that works as expected:

```
<head>
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.3.14.min.js"></script>
</head>

<body>

<script type="text/javascript">

var goodConfig = {credentials: {accessKeyId: 'GOOD_KEY', secretAccessKey: 'GOOD_SECRET'}, region: 'us-east-1'}
var badConfig = {credentials: {accessKeyId: 'BAD_KEY', secretAccessKey: 'BAD_SECRET'}, region: 'us-east-1'}

var ec2 = new AWS.EC2(badConfig)
ec2.describeKeyPairs({}, function(err, data){
  document.write("Error: " + String(err) + "<br>")
  document.write("Data: " + String(data) + "<br>")
})

document.write("<hr>")

var ec2 = new AWS.EC2(goodConfig)
ec2.describeKeyPairs({}, function(err, data){
  document.write("Error: " + String(err) + "<br>")
  document.write("Data: " + String(data) + "<br>")
})

</script>
</body>

```

**Comment by chrisradek** [comment]
@njeirath 
Glad to hear the example is working at least.

@anthonygreen 
You can only specify the `accessKeyId`, `secretAccessKey` and `sessionToken` directly in the config options when you are passing them into the `AWS.Config` constructor:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property

When calling `AWS.config.update`, you need to pass those fields as properties on the `credentials` object:
```javascript
AWS.config.update({ "credentials": {"secretAccessKey" …
```

See the `General Configuration Options` for a list of params you can set directly.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html

**Comment by anthonygreen** [comment]
> When calling AWS.config.update, you need to pass those fields as properties on the credentials object

That doesn't appear to be the case.
This code does work

    var AWS = require('aws-sdk'); 

    var awsSecretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;

    AWS.config.update({ "accessKeyId": "…", "region": "eu-west-1", "secretAccessKey": awsSecretAccessKey })

**Comment by chrisradek** [comment]
@anthonygreen 
Can you log the `AWS.config` object and see if the `accessKeyId` and `secretAccessKey` are shown?

When I tested, the operation didn't throw an error, but it also didn't save the fields. There's a flag you can set to allow non-standard fields to be saved, but that still wouldn't help your use case.

I think we should have thrown an error when an unsupported field was submitted, but we risk breaking users if we started doing that now. We may be able to add a warning though when this happens.
