### ISSUE TITLE
s3.headObject freezes on Lambda

### ISSUE THREAD

**Issue by felixnext** [aws/aws-sdk-js#971]
Hello,

I have a Lambda Function, which reacts to images uploaded to an s3 bucket. In there I want to get the metadata from the S3 Bucket and insert it into a database like so:
```js
var aws = require('aws-sdk');
var s3 = new aws.S3({ apiVersion: '2006-03-01' });
aws.config.region = 'eu-central-1';
aws.config.httpOptions = { timeout: 1000 };

// in the code

s3.headObject({ Bucket:bucket, Key:key }, function (err, s3Data) {
  // Code here
}
```

However I do not get any response from that and lambda just returns a timeout (lambda is set to run 5 secs and the code before is taking <1sec), i.e. is does not execute the callback function on headObject. The lambda uses node.js 4.3  and has a policy attached that allows access to s3.

**Comment by felixnext** [comment]
I ran a policy simulation, so it is not a policy problem. However, if I revoke the policy I also do not get any error message in the callback.

**Comment by felixnext** [comment]
I also just tried to set the time limit to 300 secs. Still the same error with no response at all from the headObject call.

**Comment by chrisradek** [comment]
@felixnext 
In the Lambda console, where you can select a blueprint, have you tried the `s3-get-object` blueprint? It walks you through setting up a Lambda function to listen for when objects are created in an S3 bucket, and by default calls `getObject`. I just created a new Lambda function using this blueprint, changing `getObject` to `headObject` and it worked immediately.

**Comment by felixnext** [comment]
@chrisradek 
Just tried the sample and it worked. Seems that the error with my lambda is the VPC. If I don't attach the VPC the lambda code works. However the VPC is needed to access RDS. Do you know if there is a way to get access to Buckets in the VPC? I thought the access was restricted only through the role (and policy) attached to the lambda...

**Comment by chrisradek** [comment]
@felixnext 
That's a question the Lambda team would be better equipped to answer. You can leave a message on their forums: https://forums.aws.amazon.com/forum.jspa?forumID=186

According to their [faq](https://aws.amazon.com/lambda/faqs/), there is some additional configuration in your VPC that needs to be done to be able to access AWS Service endpoints:
`
Q: Can Lambda functions in a VPC also be able to access the internet and AWS Service endpoints?
Lambda functions configured to access resources in a particular VPC will not have access to the internet as a default configuration. If you need access to external endpoints, you will need to create a NAT in your VPC to forward this traffic and configure your security group to allow this outbound traffic.
`

**Comment by felixnext** [comment]
Alright. Thanks!

**Comment by felixnext** [comment]
For folks with similar issues: https://aws.amazon.com/de/blogs/aws/new-vpc-endpoint-for-amazon-s3/
This seems to do the trick.
