### ISSUE TITLE
AWS.SharedIniFileCredentials broke

### ISSUE THREAD

**Issue by dainbrump** [aws/aws-sdk-js#972]
I have in Node:
`var creds = new AWS.SharedIniFileCredentials({profile:'myprofile'});`

Even with a valid section in the credentials INI under my home directory in '.aws/', the creds variable is not populated. This is after updating to the latest version of the SDK(2.3.4). Previously, we were using 2.3.1 and it works. What happened?

**Comment by chrisradek** [comment]
@dainbrump 
Does your 'profile' in your credentials file contain a `roleArn`?

**Comment by dainbrump** [comment]
No. Does it need to?

**Comment by chrisradek** [comment]
@dainbrump 
Nevermind, I misread your post.

The credentials object wasn't intended to be populated until either `get` or `refresh` was called. There was some work done recently to support 'assume role' credentials in this file which removed the `get` from the constructor.

Were you grabbing the credentials from the `creds` variable directly? The first time a request is made, the credentials should be populated.

**Comment by dainbrump** [comment]
I define `creds` like in my original post. Then later I refer to `creds.accessKeyId` and `creds.secretAccessKey`. I've dumped the `creds` object to console and neither key is defined. Do I need to do `creds.refresh()` before I can use them?

**Comment by chrisradek** [comment]
Either `creds.get()` or `creds.refresh()` will populate the object. If no `roleArn` is in your profile, then that should be a synchronous task, so you won't need to supply a callback to either operation.

**Comment by dainbrump** [comment]
Ok. Now I'm getting the accessKeyId but no secretAccessKey. In fact, secretAccessKey is not even present in the `creds` object after running `creds.get()` or `creds.refresh()`.

**Comment by chrisradek** [comment]
Was the secretAccessKey viewable previously by just logging creds? The SDK hides that property from util.inspect so that it's not accidently logged. Logging in node.js shouldn't show it, but if you log it directly you can see it.
i.e. `console.log(creds.secretAccessKey)`

**Comment by dainbrump** [comment]
Without doing `creds.get()`:
`{ expired: false,
  expireTime: null,
  accessKeyId: undefined,
  sessionToken: undefined,
  filename: undefined,
  profile: 'myprofile',
  disableAssumeRole: false }`

After doing `creds.get()`:
`{ expired: false,
  expireTime: null,
  accessKeyId: '{MY_ACCESS_KEY}',
  sessionToken: undefined,
  filename: '/home/dainbrump/.aws/credentials',
  profile: 'myprofile',
  disableAssumeRole: false }`

I was creating `creds` like the first post. Then right after:
`var redshift = new AWS.Redshift({
  accessKeyId: creds.accessKeyId,
  secretAccessKey: creds.secretAccessKey
});`

**Comment by dainbrump** [comment]
Ah. The `get()` seemed to do the trick. I was noticing something else. I think we can close this. Would be handy to update the docs mention the need for the `get()` before doing things.

**Comment by chrisradek** [comment]
@dainbrump 
Glad to hear. We'll get the docs updated. We also may need to consider adding `get` back into the constructor. While it wasn't meant to be there, if users are already writing code based on how it was working (docs haven't been the clearest on how it should work), it might be worth keeping that in there so user's don't break when they upgrade.

**Comment by dainbrump** [comment]
@chrisradek I'd say adding the `get` back to the constructor may be necessary. There are a few libraries I've come across that use the SharedIniFileCredentials. None of which I've seen use the `.get()` after instantiation. Could be a breaking change maybe?
