### ISSUE TITLE
Unhandled rejection RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.

### ISSUE THREAD

**Issue by nairicode** [aws/aws-sdk-js#974]
cant upload file to Amazon S3. 
-----------------------------------------------------------------------------------
{ fieldName: 'file',
  originalFilename: 'Сdasdsadнимок.PNG',
  path: 'C:\\Users\\nnn\\AppData\\Local\\Temp\\AVtF1A9-ryhVhnmMhS8pO16q.PNG',
  headers:
   { 'content-disposition': 'form-data; name="file"; filename="myfile.PNG"',
     'content-type': 'image/png' },
  size: 2668,
  name: 'myfile.PNG',
  type: 'image/png' }

> 

> ---------------------------------------------------------------------------------

```
   return s3fsImpl.writeFile(file.originalFilename, stream).then(function () { 
        fs.unlink(file.path, function (err) {
            if (err) {
                console.error(err);
            }
        });
		res.redirect('/');
	})
```

**Comment by siyuan1995** [comment]
Hi bro did you find the solution? Is it like to change the setTimeOut of AWS configuration?
