### ISSUE TITLE
SQS MessageAttributes missing NumberValue for Number types

### ISSUE THREAD

**Issue by kyriesent** [aws/aws-sdk-js#978]
There's no support for using `Number`s for SQS MessageAttributes, even though it's documented [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#sendMessage-property).

The relevant lines of the spec are [here](https://github.com/aws/aws-sdk-js/blob/e8bd91efa373d943edbf6a0498dc1e386459c64f/apis/sqs-2012-11-05.normal.json#L1084). I don't fully understand how the code works, but I think that this is the spec that does the validation of the input. There's no support here for `Number`s.

I'm using version 2.3.4.

Am I missing something or is this just not implemented?

Thanks for the great work on the sdk!

**Comment by LiuJoyceC** [comment]
Hi @kyriesent 
Thanks for your question. For MessageAttributes of type Number, you need to use the `StringValue` property and provide the number in the form of a string:
```
params = {
	MessageBody: 'myMessageBody',
	QueueUrl: 'myQueueUrl',
	MessageAttributes: {
		'myAttributeName': {
			DataType: 'Number',
			StringValue: '4'
		}
	}
}
```
I will add to the documentation to make this more clear. Let me know if this resolves your issue!
