### ISSUE TITLE
AWS.CognitoIdentityServiceProvider doesn't have authenticate API for User Pools

### ISSUE THREAD

**Issue by srkprasadam** [aws/aws-sdk-js#987]
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html

AWS.CognitoIdentityServiceProvider doesn't have authentication API. I see that there are apis to signup, getting attributes for a user etc. It is surprising that there aren't APIs to authenticate, with the given username and password.

**Comment by LiuJoyceC** [comment]
Hi @srkprasadam,
User Pools are intended to be used with another SDK on top of the AWS SDK:
https://github.com/aws/amazon-cognito-identity-js
This SDK provides mechanisms for authentication.

Please note that this other SDK is currently in developer preview and may be subject to breaking changes. Feel free to open issues on the amazon-cognito-identity-js repository if you have any questions.
Thanks!
