### ISSUE TITLE
`httpUploadProgress` not emitted for small uploads

### ISSUE THREAD

**Issue by winsome** [aws/aws-sdk-js#990]
I'm receiving file uploads with an express API and then uploading those files to s3 with s3.upload. I'm listening for `httpUploadProgress` so that I can read and save the file size in my own metadata. The problem is I'm never seeing this event emitted with small file uploads. Based on my own debugging, the cutoff appears to be around 16KB.

In \lib\http\node.js, stream's `drain` event is used to detect that the data has been written for files that are fully loaded into memory. Seems like rather than the `drain` event, it should use the `finish` event since that's really what it needs to know.

**Comment by winsome** [comment]
Created #991 with the proposed change

**Comment by chrisradek** [comment]
@winsome 
Thanks for reporting this issue and providing a PR. I'll take a look asap.

**Comment by chrisradek** [comment]
The PR has been merged. Thank you!
