### ISSUE TITLE
SDK throws error when used in global module

### ISSUE THREAD

**Issue by afaqurk** [aws/aws-sdk-js#995]
I have the following code:

``` js
const s3ObjectParams = {
  Bucket: 'mybucket',
  Key: `mykey`,
}

// this works when script is called via `node {script name}` 
 // but errors out if the module is installed globally
s3.getObject(s3ObjectParams, (err, data) => {
})
```

The above code works for me **unless** the module is installed globally (`npm i -g`). If installed globally, it throws a signature mismatch error:

**SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided.**

Two questions:
1. Why does the same exact code work (on the same machine) if the package is called manually via `node {script name}` but fails when installed globally and called via CLI? Is there something I need to account for?
2. If I am not using signed URLs, why would I receive this error?

**Comment by chrisradek** [comment]
@afaqurk 
Are you referring to the SDK being installed globally, or your module that consumes it?

That error you're receiving can occur whenever the SDK calculates a different signature than what the service does for a request. For example, some S3 regions only support sigv4. Part of what goes into the signature calculation with sigv4 is the region. If your SDK was configured to use the region `us-east-1`, but your bucket was in `eu-central-1`, that would cause the error to occur because the SDK and the service would be calculating the signature using different regions.

Can you share how you're calling the code from the CLI?

**Comment by afaqurk** [comment]
@chrisradek, I meant that the module that is consuming the SDK is installed globally. When that same module is just used manually (node cli), it works. 

I checked and the bucket is in the right region (`us-east-1`). To be safe, I tried it with other regions as well, with no luck.

**Example of when it works:**
1. I go to the folder containing the node app (which consumes the sdk)
2. I run `node index.js`, which calls the code I pasted above, with the s3 object configured to the right bucket
3. Result: It works

**When it doesn't work:**
1. I install the same module globally via `npm i -g .`
2. I run the command (configured to run `index.js` via `packa.json`'s `bin` option)
3. I get the signature error.

If it is truly a signature mismatch, I am curious to see why it only happens when the module is installed globally. 

Is there any way to tell what the underlying cause of the signature mismatch is? As in, have the SDK tell me if it is the incorrect bucket or some other property that causes the mismatch?

Any help is appreciated.

**Comment by afaqurk** [comment]
Btw, this is the exact error:

```json
{ [SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.]
  message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  code: 'SignatureDoesNotMatch',
  region: null,
  time: Thu May 19 2016 11:53:03 GMT-0400 (Eastern Daylight Time),
  requestId: '{redacted}',
  extendedRequestId: '{redacted}',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 42.30998351704329 }
```

I have confirmed with an internal team that our bucket does not have a region restriction (if that helps at all).

**Comment by chrisradek** [comment]
Closing old issue due to inactivity.
