### ISSUE TITLE
S3 sync failing with request.js:31  throw err; Forbidden: null

### ISSUE THREAD

**Issue by jrbenito** [aws/aws-sdk-js#997]
I´ve created a site with [hexo](https://hexo.js) and deploying it to AWS S3 using [hexo-deployer-s3-cloudfront](https://github.com/jrbenito/hexo-deployer-s3-cloudfront/tree/teste) (on branch "teste"). I am currently using of my branch "teste" because I changed dependency from [S3-sync](https://github.com/hughsk/s3-sync) to [s3-sync-aws](https://github.com/andreialecu/s3-sync-aws/) because the latest supports other S3 regions.

The deploy process fails on [aws-sdk-js](https://github.com/aws/aws-sdk-js) module as follows:

    [...]hexo-deployer-s3-cloudfront/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/request.js:31
                throw err;
                ^
    Forbidden: null
        at Request.extractError ([...]/hexo-deployer-s3-cloudfront/node_modules/s3-sync-aws/node_modules/aws-sdk/lib/services/s3.js:344:35)

This fail happens about 95% of deploy attempts, I don´t know why.

Researching on the [aws-sdk-js](https://github.com/aws/aws-sdk-js) ticket issues I found [issue #291](https://github.com/aws/aws-sdk-js/issues/291) although it is supposed to be fix (I tried aws-sdk@2.3.12 and @2.3.13), my issue is very similar in sporadic happening. Also, [issue #221](https://github.com/aws/aws-sdk-js/issues/221) shares similar characteristics.

Aws-sdk logs (extracted as suggested on issue #291) shows:

`[AWS s3 403 0.99s 0 retries] headObject({ Bucket: 'benito.com.br', Key: 'page-sitemap.xml' })`

Which suggests the script has no right to overwrite `page-sitemap.xml` file. However this script uses an access key with full access to this bucket and that file was originally created by the same script in another iteration. Also, the file name varies across attempts.

### First question:

I think the `403` error should be shown in place of `null` and this is related to s3-sync-aws calls to aws-sdk and its callbacks.  Am I right? 

### Second question:

Even do I empty bucket and try a new deploy the error is thrown. However, can´t figure out why the deploy worked 3 out 5 attempts than stopped. And, with this very same credentials I can deploy using [s3-sync](https://github.com/hughsk/s3-sync) which is Knox based instead of aws-sdk.

Any clue why I am getting `403` errors?

### Note

I´ve notice from yesterday OK attempt to today´s NOK attempts that aws-sdk@2.3.13 was released and travis-ci was picking the latest. I did downgrade it on travis-ci and had one success attempt followed by fail attempts after it. So there is no correlation with yesterday´s aws-sdk release.

**Comment by chrisradek** [comment]
@jrbenito 
**First question:**
S3 sends back a `403` response when a user does not have access to the resource they are attempting to access. Based on what was said in #291, it sounds like this occurs on `HEAD` operations. The `null` part of the error is supposed to be the message, but in cases where the response doesn't have a body, it isn't filled out. 

**Second question:**
The `403` error indicates you don't have access to the object you're trying to access. Have you tried using the AWS SDK directly to make a `headObject` call with your credentials? If it works with the SDK, then there's likely an issue with how s3-sync-aws is configured.  Can you explain what you mean by `Even do I empty bucket and try a new deploy the error is thrown`?  Are you deleting an empty bucket and immediately creating a new one with the same name?

**Comment by jrbenito** [comment]
Hi @chrisradek ,

First of all thanks for your reply.

I understand what `403`  means and now I understand why `null` body. However, how someone is supposed to know what error is going on if the error did not show `403` or `access denied` explicit? I only got a clear `403` after tuning on `aws-sdk` debug. Anyway, this does not solve the issue yet because I do have access to the resource.

I did not try to call AWS SDK directly however I used same credentials with python boto3 library over the same resources without any issues; I also used `s3-sync` knox based (not `s3-sync-aws` that is AWS SDK based) with same credentials over the same bucket and resources with no issues at all.

Sorry, I was not clear on what I meant. When I wrote `Even do I empty bucket and try a new deploy the error is thrown`, I want to make it clear that I first tried to overwrite existem objects in a given bucket (that is the normal operation of my "deploy" action). Since I eventually got `403`, I tried to delete all files in my bucket, not the bucket itself, and deploy. In other words: no overwrite of any file. I also got `403`errors in this attempt. However, and this is the most important thing, I *already did deploy in the same bucket, overwriting the same files, with very same tools (nodejs, s3-sync-aws, aws-sdk) and with the very same credentials.* Can´t understand why I got `403` randomly.

Once again thanks for taking time to answer.

**Comment by jrbenito** [comment]
@chrisradek 

Just to illustrate, I deployed right now with the very same credentials and tools over the very same bucket overwriting files. **No errors** at all, this deploy failed yesterday and the logs I put here was taken from this failed attempt. right now I just retried (same computer, same terminal used yesterday) and got a success deploy.

Those `403` errors happens randomly, but once they happy I got a bunch of them.

**Comment by chrisradek** [comment]
@jrbenito 
Are you using your account credentials when testing or using something else like EC2MetadataCredentials/TemporaryCredentials/etc?

When s3-sync-aws starts failing on `headObject`, is this before or after you've deployed a new object? Is it always `headObject` that is failing?

**Comment by jrbenito** [comment]
@chrisradek 

Credentials are a IAM User with its Access Key and a policy attach allowing it full operation on this bucket. 

Regarding your next question, based on logs I have until now just headObject fails is happening. Also, `s3-sync-aws` consult a metadata (headObject operation) to determine if a object need to be uploaded or not (hash).

**Comment by jrbenito** [comment]
Hi,

During the weekend I run a lot of deployments without a single issue. Temporary instability? Environment issues? I don´t know, I changed nothing on my work environment and my travis-ci presented no issue too. 

Anyway, I am closing this since no error was found nor reproducible.
